### ISSUE TITLE
Airplay works with OSX but not iOS

### ISSUE THREAD

**Issue by inferiorhumanorgans** [mikebrady/shairport-sync#1004]
Of note: yes, there is a restrictive firewall between the shairport-sync device and the other computers (phone, notebook). However, when playing from OSX 10.14.6 shairport is able to pick ports from the range specified in the config file (6001–6101).  When playing from iOS 13.4.1 it looks like the phone is trying to pick random ports (that are blocked by the firewall).

An older version of shairport-sync shows this output:

```
iOS
RTSP Response:
  Type: "CSeq", content: "3"
  Type: "Server", content: "AirTunes/105.1"
    Transport: RTP/AVP/UDP;unicast;mode=record;timing_port=59776;control_port=60172.
    CSeq: 4.
    DACP-ID: D9876494DA62DF3D.
    Active-Remote: 900795569.
    User-Agent: AirPlay/420.45.

OSX
RTSP Response:
  Type: "CSeq", content: "1"
  Type: "Server", content: "AirTunes/105.1"
    CSeq: 2.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002.
    User-Agent: iTunes/12.9.5 (Macintosh; OS X 10.14.6) (dt:1).
    Client-Instance: 4D515D4BFE001322.
    DACP-ID: 4D515D4BFE001322.
    Active-Remote: 2476078310.
```

From master (`4c6628a`):
```
         0.001365989 "rtsp.c:2416" Connection 2: RTSP Response:
         0.001289989 "rtsp.c:464"   Type: "CSeq", content: "3"
         0.001259989 "rtsp.c:464"   Type: "Server", content: "AirTunes/105.1"
         0.085167287 "rtsp.c:2373" Connection 2: Received an RTSP Packet of type "SETUP":
         0.001425988 "rtsp.c:464"   Type: "Transport", content: "RTP/AVP/UDP;unicast;mode=record;timing_port=51557;control_port=61763"
         0.003187973 "rtsp.c:464"   Type: "CSeq", content: "4"
         0.002086983 "rtsp.c:464"   Type: "DACP-ID", content: "F305253882DA2852"
         0.002066982 "rtsp.c:464"   Type: "Active-Remote", content: "2343741574"
         0.001113991 "rtsp.c:464"   Type: "User-Agent", content: "AirPlay/420.45"
         0.000129999 "rtsp.c:921" Connection 2: SETUP -- Active-Remote string seen: "2343741574".
         0.000117999 "rtsp.c:936" Connection 2: SETUP -- DACP-ID string seen: "F305253882DA2852".
         0.000133999 "rtp.c:981" Connection 2: SETUP -- Connection from 10.22.1.206 to self at 10.22.10.10.
         0.005675952 "rtsp.c:1001" Connection 2: SETUP DACP-ID "F305253882DA2852" from 10.22.1.206 to 10.22.10.10 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
         0.000145999 "rtsp.c:2416" Connection 2: RTSP Response:
         0.002869976 "rtsp.c:464"   Type: "CSeq", content: "4"
         0.001104991 "rtsp.c:464"   Type: "Server", content: "AirTunes/105.1"
         0.000107999 "rtsp.c:464"   Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002;server_port=6003"
         0.000089999 "rtsp.c:464"   Type: "Session", content: "1"
```

Followed by the inevitable:

```
0.989882708 "rtp.c:449" Sync packet received before we got a timing packet back.
```

**Comment by mikebrady** [comment]
Thanks for the post. I am puzzled by the diagnostics. The log entry:
```
 0.000107999 "rtsp.c:464"   Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002;server_port=6003"
```
indicates that Shairport Sync is offering to listen for UDP traffic on ports 6001, 6002 and 6003. That is what all recent version of Shairport Sync should do, so I would expect that the firewall should allow this.

The log entry:
```
    Transport: RTP/AVP/UDP;unicast;mode=record;timing_port=59776;control_port=60172.
```
looks very odd. In fact, it looks like something sent to Shairport Sync rather than a response from Shairport Sync.

What version of Shairport Sync was that on?

If you would be kind enough to post a longer log (please see [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md)), that would be very helpful.

**Comment by mikebrady** [comment]
Thinking about your message again, it is worth saying that Shairport Sync has no control over the ports used by the player. It is not necessarily the case that the player will use ports 6001 and so on.

**Comment by inferiorhumanorgans** [comment]
Per the initial comment the newer version of shairport-sync is 4c6628a (or HEAD at the time I built it).  From the indentation it appears that, yes, the transport line is indeed from a client generated packet.


What's the point of the `udp_port_base` and `udp_port_range` options then if the clients ignore them?  This setup works with OSX 10.14 and iOS 12, but does not with iOS 13.

What extra log information do you need/want?

**Comment by mikebrady** [comment]
Thanks. My question about the version (not the commit hash, BTW) was in relation to this:
> An older version of shairport-sync shows this output:

What version was that, please?

In any case, 
>What's the point of the udp_port_base and udp_port_range options then if the clients ignore them? This setup works with OSX 10.14 and iOS 12, but does not with iOS 13.

The `udp_port_base` and `udp_port_range` options specify what ports Shairport Sync uses. As I wrote, Shairport Sync has no control over the ports used by the player.

My experience is that this has been the case for many years. As I said, while the macOS Music app (and iTunes before it) use ports 6000 and up, iOS uses high-numbered ports.
