### ISSUE TITLE
TEARDOWN on pause / stop results with abort and crash

### ISSUE THREAD

**Issue by arcadilius** [mikebrady/shairport-sync#1007]
Service starts and works continuously without a problem until pause or stop is being pressed on connected client, in this case MacOS or iPhone. Shairport is running on OpenBSD machine, same behaviour on three different hardware configurations. Message in log just after pause / stop is pressed attached below:

```
         0.000117790 "rtsp.c:852" Connection 1: OPTIONS
         0.000126229 "rtsp.c:2416" Connection 1: RTSP Response:
         0.000105953 "rtsp.c:464"   Type: "CSeq", content: "32"
         0.000112753 "rtsp.c:464"   Type: "Server", content: "AirTunes/105.1"
         0.000099928 "rtsp.c:464"   Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
         1.536001122 "rtsp.c:533" RTSP Message Received: "TEARDOWN rtsp://172.17.0.1/14614043795203313301 RTSP/1.0".
         0.000198468 "rtsp.c:563"     CSeq: 33.
         0.000121041 "rtsp.c:563"     DACP-ID: 99A33E0A56EB4330.
         0.000109016 "rtsp.c:563"     Active-Remote: 551612124.
         0.000130053 "rtsp.c:563"     User-Agent: AirPlay/420.45.
         0.000137654 "rtsp.c:2373" Connection 1: Received an RTSP Packet of type "TEARDOWN":
         0.000121466 "rtsp.c:464"   Type: "CSeq", content: "33"
         0.000100541 "rtsp.c:464"   Type: "DACP-ID", content: "99A33E0A56EB4330"
         0.000094665 "rtsp.c:464"   Type: "Active-Remote", content: "551612124"
         0.000116253 "rtsp.c:464"   Type: "User-Agent", content: "AirPlay/420.45"
         0.000117791 "rtsp.c:861" Connection 1: TEARDOWN
         0.000121103 "common.c:1269" mutex_lock "&playing_conn_lock" at "rtsp.c:266".
         0.000141954 "common.c:1294" mutex_unlock "&playing_conn_lock" at "rtsp.c:269".
         0.000109453 "rtsp.c:868" TEARDOWN: synchronously terminating the player thread of RTSP conversation thread 1 (2).
         0.000104541 "player.c:3052" player_stop
         0.000104265 "player.c:3054" player_thread cancel...
         0.000422487 "player.c:3056" player_thread join...
         0.000348429 "player.c:1587" Connection 1: player thread main loop exit via player_thread_cleanup_handler.
Abort trap (core dumped)
```

**Comment by mikebrady** [comment]
Thanks for the post, however some more information would be useful – please have a look at [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md). In particular, the version of Shairport Sync would be very useful. (Do `$shairport-sync -V` to get the version information.)

**Comment by arcadilius** [comment]
3.3.6-libdaemon-OpenSSL-Avahi-sndio-sysconfdir:/etc, tested on OpenBSD 6.6 and 6.7

**Comment by mikebrady** [comment]
Super, thanks. I'll take a look.

**Comment by mikebrady** [comment]
Unfortunately, due to the current crisis, an OpenBSD machine is not readily to hand – it's have to wait a few weeks (!) until access is restored. Meantime, could you say what kind of hardware and what kind of sound cards you are using please?

**Comment by arcadilius** [comment]
I understand, I do appreciated your help regardless. I have Intel based machines with integrated sound cards running on azalia driver, to be more specific these are Intel 3400 HD Audio (Realtek ALC888 codec) and Intel Braswell HD Audio (Realtek/0x0887 codec). I've ordered as well EMU10K1 card to test as alternative and rule out hardware issue.

**Comment by mikebrady** [comment]
Thanks again. BTW, see #975, which might be relevant.
