### ISSUE TITLE
Connection keeps dropping

### ISSUE THREAD

**Issue by atdotde** [mikebrady/shairport-sync#1010]
I use shairport-sync as part of Volumio on a RaspberryPi. I can connect to it and play sound for a few seconds which then always disconnects independent of the source of the sound (Mac, iPhone, AppleTV). I put  a log file on http://logs.volumio.org/volumio/UJ0AHUN.html It's not obvious to me if this is a Volumio or a shairport-sync problem.

**Comment by mikebrady** [comment]
Thanks for the post. You might find something interesting at [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) – it sounds like a possible networking problem. Also, there are some suggestions at [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) for the kind of information that would be useful to us.
