### ISSUE TITLE
Question regarding release of 3.3.7

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#1011]
Hi Mike,

I'm just running up 3.3.7d6 and was curious when you'd think you would do a 3.3.7 release version? 
No rush, just curious!

Thanks.

**Comment by mikebrady** [comment]
Hi Julian (?). At the moment, we are tracking down some issues inside Docker containers and associated with Snapcast. After that, hopefully, we'll push out the update!

**Comment by juliandc1969** [comment]
Thanks, that sounds promising! I'll keep checking. It's actually Ed.. I've been using my mates login for way tooooo long...
