### ISSUE TITLE
Add recommended WiFi throughput to TROUBLESHOOTING.md

### ISSUE THREAD

**Issue by dschuessler** [mikebrady/shairport-sync#1014]
I'm currently troubleshooting crackles with my Shairport-Sync setup. TROUBLESHOOTING.md recommends testing WiFi throughput with `speedtest-cli`. 

Given a result, it would be very useful to know the approximate download speed shairport-sync requires to decide whether WiFi is really the issue.

**Comment by mikebrady** [comment]
Thanks for the suggestion.

The throughput requirements of AirPlay are quite modest – approximately half the rate of a CD. Thus the rate is approximately half of (44,100 * 2 * 2) * 8 bits per second (bps) or approximately 0.7 Mbps – say 1 Mbps to allow some overhead.

What is more important, IMHO, is a degree of consistency, i.e. that there are not wide swings in throughput delays and so on. Most of the problems with WiFi turn out to be that power management on the WiFi chip is enabled, or that the router is causing problems with multicast, is not routing correctly between ethernet and WiFi or is simply faulty. Firmware updates sometimes help.

The `speedtest-cli` measures download speed from a server on the internet, so it's of limited value when you are trying to figure out if the local network and WiFi is good enough. Another tool that might be of use is `wavemon`. 

Here is a `wavemon` screen of quite a reliable Shairport Sync system's WiFi, with an uptime of 33 days. The system is a Raspberry Pi 3B with built-in WiFi:
```
┌─Interface────────────────────────────────────────────────────────────────────┐
│wlan0 (IEEE 802.11, WPA/WPA2),  ESSID: "<redacted>"                 │
├─Levels───────────────────────────────────────────────────────────────────────┤
│                                                                              │
│link quality: 56%  (39/70)                                                    │
│===========================================                                   │
│                                                                              │
│signal level: -71 dBm (0.08 nW)                                               │
│=====================                                                         │
│                                                                              │
│                                                                              │
├─Statistics───────────────────────────────────────────────────────────────────┤
│RX: 40,197,297 (21.64 GiB), invalid: 0 nwid, 0 crypt, 0 frag, 20901 misc      │
│TX: 7,379,588 (792.61 MiB), mac retries: 5644, missed beacons: 0              │
├─Info─────────────────────────────────────────────────────────────────────────┤
│mode: Managed,  access point: <redacted>                               │
│freq: 2.462 GHz, channel: 11,  bitrate: 39 Mbit/s                             │
│power mgt: off,  tx-power: 20 dBm (100.00 mW)                                 │
│retry: short limit 7,  rts/cts: off,  frag: off                               │
│encryption: n/a (requires CAP_NET_ADMIN permissions)                          │
├─Network──────────────────────────────────────────────────────────────────────┤
│mac: 00:0F:13:38:07:D4, ip: 192.168.50.22/24                                  │
└──────────────────────────────────────────────────────────────────────────────┘
F1info  F2lhist F3scan  F4      F5      F6      F7prefs F8help  F9about F10quit
```
