### ISSUE TITLE
shairport-sync.service not starting

### ISSUE THREAD

**Issue by razorcow** [mikebrady/shairport-sync#1016]
Hi,
I ran into the problem that the systemd-service could not be started (like #922). I found that the culprit was an old startup script `/lib/systemd/system/shairport-sync.service` – and not `/etc/systemd/system/shairport-sync.service` as stated in the "Remove old startup scripts" instruction. Removed the script in `/lib/…`, installed from scratch, and it worked again like a charm.

My system, in case it matters:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
I started with a fresh Raspbian install and tried the `apt-get install …` method, no success. Worked my way up to 
``` $ shairport-sync -V
3.3.7d8-OpenSSL-Avahi-ALSA-sysconfdir:/etc
```
which now works the new startup script.

HTH, and thank you for your work!

**Comment by mikebrady** [comment]
Fantastic, thanks. I'll update the guides.
