### ISSUE TITLE
PCM disconnect and reconnect information

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#1017]
Hi Mike,

This is more a ticket for information regarding a personal modification I really need to do. As my ARM board is a standalone headless render using SPS, MPD and other apps I use hw:x,x as the PCM where possible to avoid dmix and alsa plugs doing conversions. Jack is not an option for me unfortunately. As you can appreciate this causes headaches because all the applications expect to see a PCM while running. A few like MPD disconnect the PCM immediately. Is there a way to disconnect the PCM while keeping SPS alive then reconnecting to the PCM on play? I can sort the play/stop hooks, I just need to know a suitable place to teardown the PCM and to initiate it again.
I know player.c does it's own PCM connections but I'm looking for something a little more forced.

So:
Which file would be suitable to hack for a PCM tear-down
Which file to re-instantiate the PCM?

Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. As things stand, when Shairport Sync is outputting to an `alsa` device, it acquires the output device when a play session starts and releases the output device when play stops. So the output device may freely be used when Shairport Sync isn't playing. Do you have something different in mind?

**Comment by juliandc1969** [comment]
Yes, more immediate. Through past discussions with you I know that it takes time before iOS releases the transport so SPS can tear-down the PCM; on average I found it to be 4-6 seconds. Then there's my old posts about iOS YouTube hogging the transport even though paused for up to a minute. I have a requirement to grab the PCM immediately from SPS like I do with MPD. I understand this is all down to transport, MPD releases immediate, SPS waits for iOS.  

So what I'm after is a modification/hack or just the right place to disconnect from the PCM at the same time keeping SPS alive. Then sometime later reconnect the PCM. Ultimately I'm looking at the possibility of not having to wait for iOS transport tear-down and not killing the session

Thanks!

**Comment by mikebrady** [comment]
Thanks for the clarification. This is a lot more difficult that it looks. It would require Shairport Sync (SPS) to save and retain all the output device state information while being disconnected from it and then restore it when requested. Another problem is signalling to SPS to ask it to connect and disconnect. To an extent, solving this problem has been make a good deal easier by the addition of the `D-Bus` interface, but it would require something like an extra command and status.

A possible alternative is to take output from SPS via the `pipe` back end. In effect, SPS becomes just another PCM source. You can connect or disconnect to the output of the pipe and it makes no difference to the operation of SPS. The downside, of course, is that you lose SPS's _full_ audio synchronisation. OTOH, assuming the pipe reader doesn't block, SPS will synchronised audio output, usually to within one packet (352 audio frames, about 8 milliseconds) of the correct time.
(BTW, if you're going to experiment with this, let me suggest you use the `development` branch.)

**Comment by juliandc1969** [comment]
Thanks Mike,

Certainly appreciate the difficulty! For a test, signalling won't be an issue, I can uses a Linux pipe, shared memory or a touch file to cobble a signal together. Like the SPS pipe I'm currently using aloop as a PCM stub then when needed linking that to the actual sound-card. The audio however is a bit rubbish and gets pops and clicks in it. 

So I'll give it a shot, any tips on where to look at a PCM detach and reattach ( output device state aside )? I'll just setup another test project.

Cheers.

**Comment by mikebrady** [comment]
One possibility might be to tell SPS to switch backends – to stop the flow to the `audio_alsa` backend output device, tell `audio_alsa` it to clean itself up and switch to the `audio_dummy` backend. Then, to re-enable it, switch back to the `audio_alsa` backend.

The backend is hooked into the player thread via the `config.output` variable, which is an array of function calls. 

It is very likely, unfortunately, that some state information about the backend is stored in player thread variables, as this dynamic facility to switch backends was never envisaged, but IMHO this would be the most general way of going about it.

**Comment by juliandc1969** [comment]
Cheers.
