### ISSUE TITLE
"Could not acquire ... on the system bus" with pa

### ISSUE THREAD

**Issue by TiiFuchs** [mikebrady/shairport-sync#1018]
Hi,

I installed shairport-sync with pulseaudio a week ago on an armbian based on debian and it worked fine (shairport-sync Version 3.2.2-1).
Today I tried the same on an armbian based on ubuntu (shairport-sync Version 3.3.5-1) and it does not work. :(

I configured it to use "pa" as output_backend and when I start it, it prints the following to the syslog:
```
Could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i1734" on the system bus.
Could not acquire an MPRIS interface named "org.mpris.MediaPlayer2.ShairportSync.i1734" on the system bus.
```

After a search and a few related issues I found out that there is no `/etc/dbus-1/system.d/shairport-sync-dbus.conf`. It seems to me, that this should be existent...

On both systems I installed shairport-sync via `apt install shairport-sync -y`. 
Should I compile it myself? :/

**Comment by mikebrady** [comment]
Thanks for the post. It's always better to build it yourself – you'll always have the latest and best :)  For Ubuntu, the instructions on the [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) page should work well, but remember to include `--with-pa` in the configuration step is you want the PulseAudio backend to be included.

Regarding the error messages, it does appear as if the installer didn't fully work or is incomplete. However, unless you are using the `D-Bus` or `MPRIS` interfaces, it's not an issue.

**Comment by TiiFuchs** [comment]
I am not using either of those, but it seems that shairport-sync is not starting correctly. Do I need to deactivate D-bus or MPRIS in the conf-file? I tried something like that, but it didn't change the error messages.

I can't test it (again) until the end of the week though. :(

**Comment by mikebrady** [comment]
Thanks. It is not necessary to deactivate either one – Shairport Sync (SPS below) would continue to operate; it's just that it would be unable to activate either one of those interfaces.

Regarding the problem with startup, As mentioned in more detail in the README, PulseAudio (PA below) is not normally configured as a system service – it's a user service. That means that if SPS is using the PA backend, it (SPS) can not be started as a system service, which in turn means that it can't be started automatically at boot up. Instead, it must be started after the PA user service has been started. It's a pain, but the PA guys do not recommend setting up PA as a system service.

Does that make any sense of your situation?

**Comment by TiiFuchs** [comment]
I compiled it myself and made it work. :)
Thanks for the advice.
