### ISSUE TITLE
MQTT: different pub and sub topic names

### ISSUE THREAD

**Issue by fredchung** [mikebrady/shairport-sync#1019]
Shairport-sync uses the same base topic for pub and sub. This works great on solutions like Mosquitto. I'm trying to use it on public cloud mqtt servers but they seem to require "remote devices" to publish to and subscribe from **different base topics**. Any recommendation on how best to configure this or would this be an enhancement? Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. I'm not that familiar with MQTT, to be honest. Could you give me an example of what you mean, so that I can figure it out, please?

**Comment by minix1234** [comment]
if I understand your question this is not currently possible.  

I am experimenting with MQTT locally and shairport will publish items to the configure base topic and with remote enabled it will subscribe to the base "topic"/remote

**Comment by fredchung** [comment]
Thanks minix and mike. May be I can set up forwarding.
