### ISSUE TITLE
Amp powers off after some time with no input

### ISSUE THREAD

**Issue by jamestaverne** [mikebrady/shairport-sync#1020]
My amp powers off automatically after a few minutes if there is no input. It would be nice for it to power on as soon as there is input again. I think this could be done using the cec-utils package but I don't know how to do it. The package would allow the raspberry pi to check if the amp is on and turn it on if not. It could also control the amp to select the raspberry pi as its input.

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync has hooks for executing scripts or programs when play begins and ends, so it should be possible to do what you suggest.

Please take a look at the `"active"` hooks in the `sessioncontrol` part of the configuration file.
