### ISSUE TITLE
Cygwin - audio speed is slower with fast intermittent gaps

### ISSUE THREAD

**Issue by joaodriessen** [mikebrady/shairport-sync#1025]
Shairport-sync is a great piece of software!
I run windows 10 and followed the Cygwin guide in order to get shairport-sync running via Cygwin as a service.
shairport-sync is running as a service and I'm able to connect to it from my iOS devices without issue.
Only the outputted audio contains many gaps per second and the audio sounds slow (pitch is unaffected). I thought this might be due to a difference in bitrate received vs. output, but I assume this would cause a alteration in pitch?
would an audio sample of the issue be helpful?
Any help you can offer is much appreciated.

`$ shairport-sync -V
3.3.7d8-libdaemon-OpenSSL-Avahi-ao-metadata-dbus-sysconfdir:/etc
`
(unsure how to obtain logs on shairport-sync when running under cygwin, please let me know if they are helpful and how to obtain)

**Comment by mikebrady** [comment]
Thanks for the post, and the kind words! The issue you report is puzzling. I've just run up the latest development version on Windows 10 running in VMware Fusion on an iMac, and it runs nicely. 

Logs should appear in `/var/logs/shairport-sync.log`. You should set the log verbosity of Shairport Sync to `1` or `2` in the configuration file and restart.

I wonder if there is something strange about the audio infrastructure of your Windows system, though I can't think what it could be, and I'm not a Windows guy. Maybe an audio sample would be useful alright.

**Comment by joaodriessen** [comment]
Here's a link to an audio sample of the issue. The first 15 seconds of audio connected via shairport-sync, and the last 15 seconds of audio a sample of the sound with a direct connection via an audio cable as a comparison):
[https://drive.google.com/file/d/1I7Sp3juDK_6TUDViPFuN9QgtxrEfiVgx/view?usp=sharing](url)


Here's the shairport-sync.log file:
[shairport-sync.log](https://github.com/mikebrady/shairport-sync/files/4803702/shairport-sync.log)

Thanks for the reaction, for some extra information, I'm running Windows 10. I changed the sample rate of the audio within windows 10, which unfortunately didn't seem to effect the issue.
The Device is a realtek HD ALC887, on an MSI H110i Pro motherboard.

**Comment by mikebrady** [comment]
Thanks. The audio sample is very useful. The pitch is not being altered, as you pointed out. That make me think that the output device isn't, for example, trying to play it at 48,000.

A few observations about the logs:
* There seems to be a networking problem, and IMHO this is the cause of the problem. If you look at this line:
```
         1.746756600 "rtp.c:127" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:    11955.4,   167859.6,  6057676.0.
``` 
  These packets should be arriving at 7,981.86 microsecond intervals. You can see that this is not happening – Shairport Sync is being starved of audio. The mean interval is 11,955.4 microseconds and the longest interval for that measurement period is over six seconds!

* You have requested statistics, but no statistical output is evident on the logs. These are lines of information coming every eight seconds or so, like this line:
```
      0.15,       0.0,       0.0,        1003,      0,      0,      0,      0,   8539,  208,  225,   44099.95,   44274.21,   44099.68,      0.00,     0,     -6.12
```
  They would be very useful. So if you could stand to play for a few minutes, that would be great.


3. You can see lines like this:
```
         0.026886000 "player.c:1975" Player has supplied a silent frame, (possibly frame 7562) for play number 130, status 0x5 after 3 resend requests.
```
  indicating that gaps of silences are being inserted, as you can hear.

**Comment by joaodriessen** [comment]
I've let shairport-sync run roughly 8 minutes, whilst streaming audio from my iPad (same as before), here's the log:
[shairport-sync.log](https://github.com/mikebrady/shairport-sync/files/4805565/shairport-sync.log)

Maybe some extra info is handy, the windows 10 device is connected to my LAN via gigabit ethernet. iPad is at iOS 12.4.7 and connected to the LAN via 802.11ac wifi. There are no proxies or funny vpn type things on the LAN or running on any of the devices.
To rule some things out, I tried running a commercial piece of software called AirServer Universal on the windows PC. the audio appears to playback without issue via AirServer Universal.
That being said, I much prefer shairport-sync over that closed source stuff. + the fine grain control of shairport-sync is wicked, not to mention how interesting it is to see how it all works.

**Comment by mikebrady** [comment]
Thanks indeed for the update. It's interesting and unexpected. The statistics are showing that once things settle down, the reception rate of packets is fine, and very few packets are lost. Completely different from before, and very curious.
```
         0.921257200 "player.c:2136" Player: packets out of sequence: expected: 45007, got: 46031, with ab_read: 46032 and ab_write: 46151.
         1.411077400 "rtp.c:127" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:    11712.0,   168666.0,  5978959.0.
         8.850677200 "player.c:2746"         1003,      0,      0,      0,      3,  117, 1021,   44100.01,   44086.24,      0.00,     0
         0.651173700 "player.c:990" Aliasing of buffer index -- reset.
         0.980327600 "player.c:2136" Player: packets out of sequence: expected: 46497, got: 47521, with ab_read: 47522 and ab_write: 47644.
         9.496653000 "rtp.c:127" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7956.8,    15497.8,   118286.4.
         1.233236900 "player.c:990" Aliasing of buffer index -- reset.
```
however, the music is simply not passing through the system properly, causing the buffers to fill up.

Now, here is a slightly weird thing to ask – would you be kind enough to build and test from the `master` branch and see if it makes a difference? I hope and expect that it doesn't, as the development branch works fine for me on my Cygwin installation. But I have been making changes that affect the backend used in Cygwin, and there is a small chance that something has gone wrong.

I see a PulseAudio message there – could you tell me about that please? I don't have PulseAudio running on my system.

**Comment by joaodriessen** [comment]
Regarding PulseAudio, I had installed MATE Desktop via Cygwin and I think PulseAudio was bundled in.
I've now switched to master, and decided to add libpulse and libsoxr via cygwin's package installer:
libpulse-devel (11.1-1) and libsoxr-devel (0.1.2-1).

Shairport-sync seems to have compiled properly including following flags:
--with-pa --with-soxr.

Output of shairport-sync -V:
3.3.6-libdaemon-OpenSSL-Avahi-ao-pa-soxr-metadata-dbus-sysconfdir:/etc

So here's a log file of shairport-sync (3.3.6) running using the ao backend and interpolation set to basic:
[shairport-sync.log](https://github.com/mikebrady/shairport-sync/files/4809329/shairport-sync.log)

And here's a log file running using the pa backend and interpolation set to soxr:
[shairport-sync.log](https://github.com/mikebrady/shairport-sync/files/4809346/shairport-sync.log)

Interestingly with pulseaudio as backend, there are intermittent moments of working audio. But unfortunately the audio does contain large amount of fast intermittent dropouts, which seem to follow a pattern:
[https://drive.google.com/file/d/1JZg8r6yFWVnfQMKDwLpyrf8hpCQSt1g3/view?usp=sharing](https://drive.google.com/file/d/1JZg8r6yFWVnfQMKDwLpyrf8hpCQSt1g3/view?usp=sharing)

**Comment by mikebrady** [comment]
Thanks for the update. So, these probelms don't seem to be associated with anything that has been recently changed in Shairport Sync.

In both the logs, it looks as if, after a settling down period, the audio is arriving at a reasonably good rate, with few dropouts. However, in both the `ao` and the `pa` backends, there seems to be an inability to "consume" the audio, causing the system to back up and misbehave.

To investigate this, (bit not to fix it), it is possible to build Shairport Sync with support for a dummy back end – include the configuration flag `--with-dummy` and then set the output backend to `dummy`.  Running this with statistics and debug verbosity at 1 or 2 would allow us to see whether the audio is indeed reaching Shairport Sync without any potential interference from a problem with the player.

If you wish to do this, please switch back to the `development` branch and do a `$ git pull`, as there have been a number of minor updates, including one that affects the dummy backend. If anything needs to be done, we can get to it more quickly.

**Comment by joaodriessen** [comment]
here's the output of shairport-sync -V:
3.3.7d11-libdaemon-OpenSSL-Avahi-ao-pa-dummy-soxr-metadata-dbus-sysconfdir:/etc

dummy set as audio backend, the log:
[shairport-sync.log](https://github.com/mikebrady/shairport-sync/files/4809822/shairport-sync.log)

**Comment by mikebrady** [comment]
Many thanks. Basically, that log indicates that everything on the incoming side is very close to perfect. So, it would be reasonable to wonder what is is happening on the output side – the side that talks to the output device. I wonder if the MATE Desktop has installed something that is causing the problem.

I'd also be curious to see if MATE Desktop has installed the `alsa` audio subsystem. If it has, then something like `alsamixer` would be able to locate output devices, which of course would then be piped in some way through to the Windows audio system...

**Comment by joaodriessen** [comment]
Thanks for the tip Mike.
I couldn't find anything related to alsa installed.
I decided to start fresh, so completely removed cygwin and any related services.
reinstalled again following your cygwin install guide.
Shairport-Sync is now running without issue. Audio is clear and haven't noticed any issues.

Will follow up if there are any issues.

**Comment by mikebrady** [comment]
Many thanks for the update.

**Comment by joaodriessen** [comment]
I tired to build shairport-sync with pulseaudio and soxr support. with packages libpulse-devel (11.1-1) and libsoxr-devel (0.1.2-1) from cygwin, which compiled and installed fine.

shairport-sync fails to start if audio-backend is set to "pa".
So I installed pulseaudio (11.1-1) package from cygwin.

With the backend set to "pa" shairport-sync now starts, but the audio is corrupted as before.
However, setting the audio backend to "ao" doesn't resolve the audio corruption issues.

Only when I removed the pulseaudio (11.1-1) package from cygwin did the sound issues get resolved. and did the ao backend work properly again.

**Comment by mikebrady** [comment]
That's interesting – so it seems that the `pulseaudio` package is somehow involved. One could imagine that it attempts to monopolise the audio output, preventing the `ao` driver from working properly. However, that doesn't explain why Shairport Sync doesn't work properly in Cygwin with the `pa` backend. However, at least you have some kind of explanation.
