### ISSUE TITLE
Increased dynamic range in 24 bit mode when using softvolume?

### ISSUE THREAD

**Issue by Accostare** [mikebrady/shairport-sync#1026]
Hi,

when set to 24bit mode, are the volume calculations done in formats that preserve the incoming 16bits (for the first 48dB reduction)?

i.e. 
given the incoming 16bit signal, and using the built in softvolume; when reducing volume by lets say 30dB, this means truncating the precision to 11 bits if output is written with 16bits. So lowering volume does not reduce the noise floor.

if I change to 24bit mode, do you use data types in your signal chain in the softvolume and after that preserves the 16bit signal as long (as volume is not reduced more than 8bits=48dB)? So lowering volume would reduce the noise floor.

**Comment by mikebrady** [comment]
Thanks for the interesting post.

In brief, the answers is yes – Shairport Sync does take advantage of the extra dynamic range.

In the processing chain, incoming 16-bit samples are converted to 32-bit by multiplying by 2^16. (If mono output is selected, the left and right samples are added and the result multiplied by 2^15.) The resulting 32-bit sample is multiplied by a 32-bit attenuation factor giving a 64-bit result. The result is then dithered and truncated down to the output size.

So, yes, all 16 bits of audio are preserved as far down as possible and dither is added at the lowest possible level.

**Comment by Accostare** [comment]
Excellent, thank you for your serious effort in maintaining maximum quality !
