### ISSUE TITLE
Missing instructions to compile with mpris

### ISSUE THREAD

**Issue by jgabriel98** [mikebrady/shairport-sync#1027]
There are no --with-mpris like flag in the readme, nor any instruction on how to enable mpris.

**Comment by mikebrady** [comment]
Thanks for the your interest in Shairport Sync, and sorry for making it a bit hard for you. You are right that there is no instruction as to how to enable the [`MPRIS`](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiB1LLC9o_qAhViXhUIHbnwAosQFjAAegQIBhAB&url=https%3A%2F%2Fspecifications.freedesktop.org%2Fmpris-spec%2F2.2%2F&usg=AOvVaw0eIFVq4lFw6ZpHxvthwbdy) interface. Someday...

Meantime, you can always get a list of the configuration flags at the `./configure...` stage:
```
./configure --help

[...]
  --with-dbus-interface = include support for the native Shairport Sync D-Bus interface
  --with-dbus-test-client = compile dbus test client
  --with-mpris-interface = include support for a D-Bus interface conforming to the MPRIS standard
  --with-mpris-test-client = compile mpris test client
  --with-mqtt-client = include a client for MQTT -- the Message Queuing Telemetry Transport protocol
[...]
```
There's a lot of stuff in there, not all applicable at the same time, but you could, e.g. add the `MPRIS` interface, the Shairport Sync native D-Bus interface and the [`MQTT`](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi824zd9o_qAhW2URUIHSxrDU8QFjAAegQIBRAB&url=http%3A%2F%2Fmqtt.org%2F&usg=AOvVaw1kJdOPEcd5GGWuRdKvE4DU) client all at once, if you wanted.

**Comment by jgabriel98** [comment]
I see, makes sense.

yeah D-feet is great, i am already using it.

So how about saying in the README.md that you can type `--help` in the `./configure` script, in this case to see more details?
Because i had no clue that this script had the --help option.
