### ISSUE TITLE
Issues setting this up with IQaudIO Pi-DAC Pro

### ISSUE THREAD

**Issue by HarrisonWilde** [mikebrady/shairport-sync#1029]
Hi, I am having a couple of issues:

1. Not sure what I should set my configuration as in order to utilise the DAC I have, the output of aplay -l is this, so should I set the output device to `hw:2` ?

```
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 [IQaudIO DAC HiFi pcm512x-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Secondly, setup seemed to be going fine until it came to enabling the service and then starting it, I get prompted to authenticate some stuff and then when I try to start the service get the following error:

```
pi@raspberrypi:~ $ systemctl enable shairport-sync
Synchronizing state of shairport-sync.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable shairport-sync
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  root
Choose identity to authenticate as (1-2): 2
Password:
==== AUTHENTICATION COMPLETE ===
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  root
Choose identity to authenticate as (1-2): 2
Password:
==== AUTHENTICATION COMPLETE ===
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-unit-files ===
Authentication is required to manage system service or unit files.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  root
Choose identity to authenticate as (1-2): 2
Password:
==== AUTHENTICATION COMPLETE ===
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  root
Choose identity to authenticate as (1-2): 2
Password:
==== AUTHENTICATION COMPLETE ===
pi@raspberrypi:~ $ sudo systemctl start shairport-sync
Job for shairport-sync.service failed because the control process exited with error code.
See "systemctl status shairport-sync.service" and "journalctl -xe" for details.
```

Any ideas what is going wrong here?

**Comment by mikebrady** [comment]
Thanks for the post.

1. If you do `$ shairport-sync -h`, you'll get a list of the output devices at the end:
```
$ shairport-sync -h
Usage: shairport-sync [options...]
  or:  shairport-sync [options...] -- [audio output-specific options]

Options:
[...]

Settings and options for the audio backend "alsa":
    -d output-device    set the output device, default is "default".
    -c mixer-control    set the mixer control name, default is to use no mixer.
    -m mixer-device     set the mixer device, default is the output device.
    -i mixer-index      set the mixer index, default is 0.
    hardware output devices:
      "hw:ALSA"
      "hw:IQaudIODAC"

[...]
```

...so, in this example, the name of the output device is `hw:IQaudIODAC`.

Also, I find that the tool `alsamixer` is useful for seeing what's out there – use the `F6` key to choose the output device. Here's a screenshot:

<img width="1942" alt="image" src="https://user-images.githubusercontent.com/4265913/85220161-452e7300-b3a1-11ea-8495-fca7eebde732.png">

You can see the output device's card name `IQaudIODAC` at the top left. It allows me to work out that the name of the mixer is `"Digital"`.

2. To use `systemctl` in this way, you must be the superuser, and in this case you don't seem to be. Use `sudo` to execute a command as superuser – please see the [INSTALL](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) guide for more.

**Comment by HarrisonWilde** [comment]
After following the steps again (not at 2am after a hectic day of work) everything seems to work smoothly. I think I was probably running some earlier step without sudo and missed a failure or something as cannot seem to reproduce what I was seeing after starting fresh. Thanks for the tip on the name of the card, I am stuck without a keyboard and doing everything headless so couldn't press F6, that name works fine though.
