### ISSUE TITLE
player.c won't build in FreeBSD because 'rc' is not defined

### ISSUE THREAD

**Issue by supermaik** [mikebrady/shairport-sync#103]
player.c:1096 begins an `#ifdef COMPILE_FOR_LINUX` block, and following that is an `#ifdef COMPILE_FOR_OSX` block.  I took a guess and modified common.h:19 to read: `#if defined(__linux__) || defined(__FreeBSD__)`

This allowed player.c to compile and the build to complete.  Other than that the only other trouble I had was having to specify `LDFLAGS='-I/usr/local/lib'` and `CPPFLAGS='-L/usr/local/include'` before running `./configure --with-foo`.  I've yet to test audio but wanted to offer the above info for FreeBSD support.

**Comment by mikebrady** [comment]
Thanks Mike. I'd love to see this working on FreeBSD, but I haven't been able to find an audio output system in FreeBSD that gives exact timing in the way that ALSA does...

**Comment by supermaik** [comment]
I'm using ALSA :) I am working on getting it into the ports system. I used
it all day today with no issues.

**Comment by mikebrady** [comment]
I didn't know that, Mike, so thanks for the information. I'll work your suggestion in to the `development` build, thanks.

**Comment by mikebrady** [comment]
I'm closing this, if thats okay. Feel free to reopen.
