### ISSUE TITLE
Remote control play/pause reversal question

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#1031]
Hi Mike,

I've finally got a chance to look into my ongoing remote control issues today and I've noticed something very strange; I don't believe this is a SPS issue at all but something I need to work around. Still using the iPad mini and YouTube I get a situation where play and pause actually swap around!

SPS version 3.3.7 development

I can reproduce this almost every time:
Starting with SPS not connected.
Play a YouTube song THEN connect to SPS - continue playing.. 
Send a DBus pause while playing - YouTube will pause
Minimise YouTube
Wait 3-4 seconds
Maximise YouTube and press iPad "play"
Once playing sending DBus pause no longer pauses but sending a DBus play now pauses!
Once paused, DBus pause and play return to normal.

It's like the YouTube app remembers the wrong state on being minimised/maximised. I know it's not SPS because I spy the DACP send command when I issue a DBus play/pause and the outgoing GET message strings are definitely correct. This could be the reason for a few more of my failure to pause issues.... 

So question to you, similar to getting the volume status every second ( GET /ctrl-int/1/getproperty?properties=dmcp.volume )
is there a similar command to get the play/pause state or state in general?

EDIT: On an old ticket I mentioned things used to come right after the next song or commercial started.. I feel that's directly related to this ( and probably just the YouTube app ) as maybe the new "play" status resync'd things with what was cached.

My other issue of not contacting the remote back-end server is still on going but I'll get more debug and reproducible use cases before returning on that ticket.

Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. Let me take a look at this over the next few days.

**Comment by juliandc1969** [comment]
So cutting through my long-winded blurb is there an equivalent of:   GET /ctrl-int/1/getproperty?properties=dmcp.volume    that gets the state of play/pause/stop/idle etc?

Thanks.

**Comment by mikebrady** [comment]
Unfortunately not. The only player that has provided this level of information has been iTunes on Mac or PC. At present, I think macOS Music may provide it too (it used to) but Shairport Sync can not, at present, set up a remote control connection to macOS Music. Apple keep changing it; maybe it'll come back.

**Comment by juliandc1969** [comment]
OK, my work around is sending a play then immediately after a pause this fixes Youtube. Also if it's already playing then the initial play is ignored. Just didn't want to do this every time as it's only occasionally YouTube gets in a twist..

Cheers.
