### ISSUE TITLE
DACP 491 and 490 codes on quick client session disconnect-reconnect

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#1033]
Hi Mike,

Here is a small bit of a debug showing my on-going fight with intermittent connections to the remote server. What happened here is I was playing some YouTube music and stopped the session then quickly reconnected. At that point the DACP error codes appeared and no remote control functionality worked after that. Interestingly music still played and incoming DBus volume status still worked; just nothing going back to the client. 

I'm still working of capturing more debug, perhaps from the mdns and rtsp files. If the DACP server misses the start of a new session (maybe due to the DACP server still letting go ) as it might have below, is there any was to respin it? 
 
```
SPS-DACP] message length was 141
[SPS-DACP] GET /ctrl-int/1/getproperty?properties=dmcp.volume HTTP/1.1
Host: 2a00:23c4:baa5:7901:b0d2:b4e8:d73:fba:49294
Active-Remote: 4194756287

[SPS-DACP] message length was 141
[SPS-DACP] GET /ctrl-int/1/getproperty?properties=dmcp.volume HTTP/1.1
Host: 2a00:23c4:baa5:7901:b0d2:b4e8:d73:fba:49294
Active-Remote: 4194756287

[SPS-DACP] message length was 141
[SPS-DACP] Error 491 DACP server doesn't want to talk anymore...

<== Quick session disconnect and reconnect in here ==>

[SPS-DACP] Error 490 No DACP port specified yet
<== Pause sent ==>
method return time=1593608690.499714 sender=:1.67 -> destination=:1.140 serial=304 reply_serial=2

[SPS-DACP] Error 490 No DACP port specified yet
<== Pause sent ==>
method return time=1593608690.532560 sender=:1.67 -> destination=:1.141 serial=305 reply_serial=2

[SPS-DACP] Error 490 No DACP port specified yet

<== Pause sent ==>
method return time=1593608697.768643 sender=:1.67 -> destination=:1.142 serial=306 reply_serial=2

<== Pause sent ==>
[SPS-DACP] Error 490 No DACP port specified yet
method return time=1593608697.803598 sender=:1.67 -> destination=:1.143 serial=307 reply_serial=2
```
Thanks

**Comment by mikebrady** [comment]
I'll take a look over the next few days, thanks.

**Comment by juliandc1969** [comment]
Hi,

Here's a little more debug. Certainly appearing to get out of sync on a quick disconnect/reconnect for me.  As you can see it was playing doing the periodic volume get. Then a quick disconnect/reconnect from the iPad and a play. As you can see the audio in player.c started and kicked off set_dacp_server_information() then the next debug is at the end of that function and appears to have an id. But, somehow this is was not passed on to the dacp monitor as any dbus remote control pause/plays return error 490 ( as well as the 1 second volume poll no longer exists. ) yet still laying music.

[SPS-DACP] message length was 141


[SPS-DACP] GET /ctrl-int/1/getproperty?properties=dmcp.volume HTTP/1.1
Host: 2a00:23c4:baa5:7901:106:9a66:6034:897:49723
Active-Remote: 2475708378

[SPS-DACP] message length was 141

[SPS-DACP] GET /ctrl-int/1/getproperty?properties=dmcp.volume HTTP/1.1
Host: 2a00:23c4:baa5:7901:106:9a66:6034:897:49723
Active-Remote: 2475708378

[SPS-DACP] message length was 141

[SPS-DACP] Error 491 DACP server doesn't want to talk anymore...

[SPS-DACP] set_dacp_server_information() kick from player.c   //   line ~536

[SPS-DACP] set_dacp_server_information set active-remote id to 1314077271.      // line ~590

** pause **
method return time=1594115335.406559 sender=:1.25 -> destination=:1.52 serial=129 reply_serial=2

[SPS-DACP] Error 490 No DACP port specified yet

** pause **
method return time=1594115341.611055 sender=:1.25 -> destination=:1.53 serial=130 reply_serial=2

[SPS-DACP] Error 490 No DACP port specified yet

** pause **
method return time=1594115351.404705 sender=:1.25 -> destination=:1.54 serial=131 reply_serial=2

[SPS-DACP] Error 490 No DACP port specified yet



I'll keep on it, thanks for your patience.

**Comment by juliandc1969** [comment]
/* Normal  play - volume poll */
[SPS-DACP] GET /ctrl-int/1/getproperty?properties=dmcp.volume HTTP/1.1
Host: 2a00:23c4:baa5:7901:2d31:2b3f:37ab:c6ab:49187
Active-Remote: 2246946288
[SPS-DACP] message length was 143

/* Quick disconnect and reconnect */
[SPS-DACP] Error 491 DACP server doesn't want to talk anymore...
/* Line  ~666  while (dacp_server.scan_enable == 0) and pthread_cond_wait(&dacp_server_information_cv, &dacp_server_information_lock);/*
[SPS-DACP] dacp_server.scan_enable == 0 -> loop

/* Play on the iPad is recognised and audio starts up again */ 
[SPS-DACP] set_dacp_server_information kick from player.c

/* Communicates with DACP server.. */
[SPS-DACP] set_dacp_server_information set active-remote id to 3037178806.

/* Sticks here /*  
[SPS-DACP] dacp_server.scan_enable == 0 -> loop

The code that it sticks on is:
		  while (dacp_server.scan_enable == 0)
		  {
			print_to_kmsg( "dacp_server.scan_enable == 0 -> loop", XCYAN );

		    // debug(1, " wait for an event to possible enable scan");
		      pthread_cond_wait(&dacp_server_information_cv, &dacp_server_information_lock);
		    //      debug(1,"dacp_monitor_thread_code wake up.");
		  }


Cheers..

**Comment by juliandc1969** [comment]
Might be a bingo moment.. Still looks like a leading zero UUID issue.  The problem is mdns-ahavi is not calling dacp_monitor_port_update_callback [ dacp.c ]. 

Focusing on [mdns-avahi.c] resolve_callback() case AVAHI_RESOLVER_FOUND: whenever I get a '0' leading UUID i.e. 
Service 'iTunes_Ctrl_0277480D99EA7EB6' of type '_dacp._tcp' in domain 'local'    then things fail here:

if (dbs->dacp_id)
{
      char *dacpid = strstr(name, "iTunes_Ctrl_");
      if (dacpid)
      {	
          print_to_kmsg( "AVAHI dacpid", XBGREEN );   <=====     last debug printed
          dacpid += strlen("iTunes_Ctrl_");
          if (strcmp(dacpid, dbs->dacp_id) == 0)
          {
               debug(3, "resolve_callback: client dacp_id \"%s\" dacp port: %u.", dbs->dacp_id, port);
#ifdef CONFIG_DACP_CLIENT
              dacp_monitor_port_update_callback(dacpid, port);   <==== not called
              print_to_kmsg( "AVAHI callig dacp_monitor_port_update_callback", XBGREEN );    <====   not printed 
#endif
#ifdef CONFIG_METADATA
              char portstring[20];
              memset(portstring, 0, sizeof(portstring));
              snprintf(portstring, sizeof(portstring), "%u", port);
              send_ssnc_metadata('dapo', strdup(portstring), strlen(portstring), 0);
#endif
        }
    }

This for me happens every time on a leading 0. Out of curiosity was the last leading 0 fix you did in a similar place of further up the chain? Maybe be iPad mini produces more leading 0 UUIDs than other Apple devices, who knows..

Thanks.

**Comment by mikebrady** [comment]
Wow, this is good work, thanks! Have to check it out. As you might see, I'm a bit busy with Docker and release candidates now, but I'll check this before a release.

**Comment by juliandc1969** [comment]
No worries!

**Comment by juliandc1969** [comment]
It's the compare alright.

resolve_callback: Service 'iTunes_Ctrl_01468F6FF3FE44B6' of type '_dacp._tcp' in domain 'local':

if (strcmp(dacpid, dbs->dacp_id) == 0)

Where        dacpid is 01468F6FF3FE44B6 and    dbs->dacp_id is 1468F6FF3FE44B6

**Comment by mikebrady** [comment]
Apologies -- I did indeed miss another place where leading zeroes should have been removed alright.
It's here, starting at line 150 of `mdns_avahi.c` in the `development` branch :

```c
#ifdef CONFIG_DACP_CLIENT
    dacp_browser_struct *dbs = (dacp_browser_struct *)userdata;
    char *dacpid = strstr(name, "iTunes_Ctrl_");
    if (dacpid) {
      dacpid += strlen("iTunes_Ctrl_");
      if ((dbs->dacp_id) && (strcmp(dacpid, dbs->dacp_id) == 0))
        dacp_monitor_port_update_callback(dbs->dacp_id, 0); // say the port is withdrawn
    } else {
      debug(1, "Browse callback: Can't see a DACP string in a DACP Record!");
    }
#endif
```
Here is the fix:
```c
#ifdef CONFIG_DACP_CLIENT
    dacp_browser_struct *dbs = (dacp_browser_struct *)userdata;
    char *dacpid = strstr(name, "iTunes_Ctrl_");
    if (dacpid) {
      dacpid += strlen("iTunes_Ctrl_");
      while (*dacpid == '0')
        dacpid++; // remove any leading zeroes
      if ((dbs->dacp_id) && (strcmp(dacpid, dbs->dacp_id) == 0))
        dacp_monitor_port_update_callback(dbs->dacp_id, 0); // say the port is withdrawn
    } else {
      debug(1, "Browse callback: Can't see a DACP string in a DACP Record!");
    }
#endif
```

I've just pushed it to the `development` branch. Feedback welcome!

**Comment by juliandc1969** [comment]
Hi,

Still jamming at the same spot. This patch is supposed to be in "case AVAHI_BROWSER_REMOVE:" ? 

Cheers.

**Comment by juliandc1969** [comment]
Based on your patch I did this and it worked!

if (dbs->dacp_id)
{
      char *dacpid = strstr(name, "iTunes_Ctrl_");
      if (dacpid)
      {	
          print_to_kmsg( "AVAHI dacpid", XBGREEN );   <=====     last debug printed
          dacpid += strlen("iTunes_Ctrl_");

      while (*dacpid == '0')                                              <====== patch
        dacpid++; // remove any leading zeroes               <===== patch

          if (strcmp(dacpid, dbs->dacp_id) == 0)
          {
               debug(3, "resolve_callback: client dacp_id \"%s\" dacp port: %u.", dbs->dacp_id, port);
#ifdef CONFIG_DACP_CLIENT
              dacp_monitor_port_update_callback(dacpid, port);   <==== not called
              print_to_kmsg( "AVAHI callig dacp_monitor_port_update_callback", XBGREEN );    <====   not printed 
#endif
#ifdef CONFIG_METADATA
              char portstring[20];
              memset(portstring, 0, sizeof(portstring));
              snprintf(portstring, sizeof(portstring), "%u", port);
              send_ssnc_metadata('dapo', strdup(portstring), strlen(portstring), 0);
#endif
        }
    }

**Comment by mikebrady** [comment]
Hmm. Are you on the same revision -- that patch is already there in mine. Here are the two functions, `resolve_callback` and `browse_callback`, from line 74 to line 170:
```c
static void resolve_callback(AvahiServiceResolver *r, AVAHI_GCC_UNUSED AvahiIfIndex interface,
                             AVAHI_GCC_UNUSED AvahiProtocol protocol, AvahiResolverEvent event,
                             const char *name, const char *type, const char *domain,
                             __attribute__((unused)) const char *host_name,
                             __attribute__((unused)) const AvahiAddress *address, uint16_t port,
                             __attribute__((unused)) AvahiStringList *txt,
                             __attribute__((unused)) AvahiLookupResultFlags flags, void *userdata) {
  // debug(1,"resolve_callback, event %d.", event);
  assert(r);

  dacp_browser_struct *dbs = (dacp_browser_struct *)userdata;

  /* Called whenever a service has been resolved successfully or timed out */
  switch (event) {
  case AVAHI_RESOLVER_FAILURE:
    debug(2, "(Resolver) Failed to resolve service '%s' of type '%s' in domain '%s': %s.", name,
          type, domain, avahi_strerror(avahi_client_errno(avahi_service_resolver_get_client(r))));
    break;
  case AVAHI_RESOLVER_FOUND: {
    //    char a[AVAHI_ADDRESS_STR_MAX], *t;
    debug(3, "resolve_callback: Service '%s' of type '%s' in domain '%s':", name, type, domain);
    if (dbs->dacp_id) {
      char *dacpid = strstr(name, "iTunes_Ctrl_");
      if (dacpid) {
        dacpid += strlen("iTunes_Ctrl_");
        while (*dacpid == '0')
          dacpid++; // remove any leading zeroes
        if (strcmp(dacpid, dbs->dacp_id) == 0) {
          debug(3, "resolve_callback: client dacp_id \"%s\" dacp port: %u.", dbs->dacp_id, port);
#ifdef CONFIG_DACP_CLIENT
          dacp_monitor_port_update_callback(dacpid, port);
#endif
#ifdef CONFIG_METADATA
          char portstring[20];
          memset(portstring, 0, sizeof(portstring));
          snprintf(portstring, sizeof(portstring), "%u", port);
          send_ssnc_metadata('dapo', strdup(portstring), strlen(portstring), 0);
#endif
        }
      } else {
        debug(1, "Resolve callback: Can't see a DACP string in a DACP Record!");
      }
    }
  }
  }
  // debug(1,"service resolver freed by resolve_callback");
  avahi_service_resolver_free(r);
}

static void browse_callback(AvahiServiceBrowser *b, AvahiIfIndex interface, AvahiProtocol protocol,
                            AvahiBrowserEvent event, const char *name, const char *type,
                            const char *domain, AVAHI_GCC_UNUSED AvahiLookupResultFlags flags,
                            void *userdata) {
  // debug(1,"browse_callback, event %d.", event);
  assert(b);
  /* Called whenever a new services becomes available on the LAN or is removed from the LAN */
  switch (event) {
  case AVAHI_BROWSER_FAILURE:
    warn("avahi: browser failure.",
         avahi_strerror(avahi_client_errno(avahi_service_browser_get_client(b))));
    avahi_threaded_poll_quit(tpoll);
    break;
  case AVAHI_BROWSER_NEW:
    // debug(1, "browse_callback: avahi_service_resolver_new for service '%s' of type '%s' in domain
    // '%s'.", name, type, domain);
    /* We ignore the returned resolver object. In the callback
       function we free it. If the server is terminated before
       the callback function is called the server will free
       the resolver for us. */
    if (!(avahi_service_resolver_new(client, interface, protocol, name, type, domain,
                                     AVAHI_PROTO_UNSPEC, 0, resolve_callback, userdata)))
      debug(1, "Failed to resolve service '%s': %s.", name,
            avahi_strerror(avahi_client_errno(client)));
    break;
  case AVAHI_BROWSER_REMOVE:
    debug(2, "(Browser) REMOVE: service '%s' of type '%s' in domain '%s'.", name, type, domain);
#ifdef CONFIG_DACP_CLIENT
    dacp_browser_struct *dbs = (dacp_browser_struct *)userdata;
    char *dacpid = strstr(name, "iTunes_Ctrl_");
    if (dacpid) {
      dacpid += strlen("iTunes_Ctrl_");
      while (*dacpid == '0')
        dacpid++; // remove any leading zeroes
      if ((dbs->dacp_id) && (strcmp(dacpid, dbs->dacp_id) == 0))
        dacp_monitor_port_update_callback(dbs->dacp_id, 0); // say the port is withdrawn
    } else {
      debug(1, "Browse callback: Can't see a DACP string in a DACP Record!");
    }
#endif
    break;
  case AVAHI_BROWSER_ALL_FOR_NOW:
  case AVAHI_BROWSER_CACHE_EXHAUSTED:
    // debug(1, "(Browser) %s.", event == AVAHI_BROWSER_CACHE_EXHAUSTED ? "CACHE_EXHAUSTED" :
    // "ALL_FOR_NOW");
    break;
  }
}
```

You can see the little bit of code to remove the leading zeroes is in two places. Anyway, this particular problem is solved, it would seem, yes? (BTW, the comment should be "skip any leading zeroes" rather than "remove...")

**Comment by juliandc1969** [comment]
I'm on shairport-sync-development-3.3.7d9 ( should be ), what's your last comment above in?

**Comment by mikebrady** [comment]
Aha, it's `3.3.7d13`. That explains it.

**Comment by juliandc1969** [comment]
That's moved along quick, I thought I was just a few weeks behind! Thanks again.

**Comment by mikebrady** [comment]
Thanks to you!

**Comment by juliandc1969** [comment]
Cheers! Have you got a link to the repo of saved zips for the development versions? Reason being is the download zip button just gives a standard zip'd name and the release-notes and config.h all contain 3.3.6 so once downloaded it's hard to figure out what you've got. I guessing the versions are all updated each "release" version.

**Comment by mikebrady** [comment]
Lately, I've only been generating releases in the master branch, so while you could go back through the commit history on GitHub and find the exact point at which a new development version was committed (and then download that zip), it would be tedious, I'm afraid.

**Comment by juliandc1969** [comment]
OK, no problem. Well this wraps up all my remote control niggles now. Regarding the other ticket about iOS Youtube getting muddled about what state it's in any thoughts? I can work around it by a sequential play->pause and this corrects it's state but I'd like to ask it what state it thinks it's in. We ask for the volume in dacp.c is there a similar command that requests it play/pause/stopped state?
