### ISSUE TITLE
Airplay not changing PCM volume

### ISSUE THREAD

**Issue by boblund** [mikebrady/shairport-sync#1034]
Hi,

First, thanks for shairport-sync. My set up on a RPI3 is not changing PCM volume with iTunes. Here are the alsa lines from /etc/shairport-sync.conf:

    output_device = "hw:0";
    mixer_control_name = "PCM";

Here are what seem to be the relevant lints from shairport-sync -vvv:

    Looking for the configuration file "/etc/shairport-sync.conf".
    Looking for configuration file at full path "/etc/shairport-sync.conf"
    Output device name is "hw:0".
    Open Mixer
    Mixer device name is "hw:0".
    Mixer Control name is "PCM".
    Lowest dB value is a mute -- try minimum volume +1
    Hardware mixer has dB volume from -102.380000 to 4.000000.
    Has mute ability.
    AirPlayLatency is -1.
    iTunesLatency is -1.
    ignore_volume_control is 0.
    playback_mode is 0 (0-stereo, 1-mono).
    disable_synchronization is 0.
    audio backend latency offset is 0.
    volume range in dB (zero means use the range specified by the mixer): 60.
    zeroconf regtype is "_raop._tcp".
    configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
    Successful Startup

I can change the volume from the RPI command line, e.g. amixer set PCM 90%.

Any  ideas?

Thanks,
Bob Lund

**Comment by mikebrady** [comment]
That’s very peculiar. Are you listening on the headphone jack (as opposed to the HDMI port)?

In `alsamixer`, you should be able to see the PCM value follow the iTunes volume control.

**Comment by boblund** [comment]
I am listening on the headphone jack. But I rebooted the RPI and the source device (macbook+itunes) and now things seem to be working. Thanks for the quick response.

**Comment by AStoker** [comment]
Hate to bring this back from the dead, but I'm having the same issue. I'm using the Adafruit speaker bonnet and have configured it according to their docs (https://learn.adafruit.com/adafruit-speaker-bonnet-for-raspberry-pi). Everything works correctly, EXCEPT the volume control. When I run `alsamixer` to look at the volume, and then change the volume from airplay, the volume mixer in alsamixer does not change, but remains static. I need to have the `alsamixer` volume to 100 in order for any substantial volume to be heard.
I've rebooted, double checked configs, all that jazz, but so far no joy. Any chance you happened to know if something in particular fixed this?

**Comment by mikebrady** [comment]
Thanks. Would you be kind enough to create a new issue for this please? There's some useful information you'll be asked for that might help.
