### ISSUE TITLE
fatal error: audio_alsa: Sample format X not available for device "hw:1": Invalid argument

### ISSUE THREAD

**Issue by flatsiedatsie** [mikebrady/shairport-sync#1035]
I have a USB ReSpeaker microphone and audio output device. It's designed for privacy friendly, local voice control of smart homes.

I have tried some output formats and output rates, but nothing so far has worked.

Output formats `U8` and `S24_3LE` give:
`fatal error: Can't set the D/A converter to 44100.`

All other output formats give:
`fatal error: audio_alsa: Sample format X not available for device "hw:1": Invalid argument`

`cat /proc/asound/card1/pcm0p/sub0/hw_params` gives:
```
closed
```

`cat /proc/asound/card1/pcm0c/sub0/hw_params` gives:
```
cat /proc/asound/card1/pcm0c/sub0/hw_params
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 6
rate: 16000 (16000/1)
period_size: 86
buffer_size: 87381
```

`cat /proc/asound/card1/pcm0p/sub0/info` gives:
```
card: 1
device: 0
subdevice: 0
stream: PLAYBACK
id: USB Audio
name: USB Audio
subname: subdevice #0
class: 0
subclass: 0
subdevices_count: 1
subdevices_avail: 1
```

Shairport-sync works fine with the Raspberry Pi 4's built in audio card.

**Comment by flatsiedatsie** [comment]
If I use the `plughw:CARD=ALSA,DEV=0` instead of `hw:1`, it seems to work.

**Comment by mikebrady** [comment]
Thanks for the posts. Yes, it looks like the USB ReSpeaker can only do 16,000 frames per second audio. Using the `plughw:CARD=ArrayUAC10,DEV=0` as distinct from the `hw:CARD=ArrayUAC10,DEV=0` enable;es the ALSA subsystem to transcode from 44,100 frames per second down to 16,000.
