### ISSUE TITLE
I have 4 “raspberry pi” options on my airplay

### ISSUE THREAD

**Issue by Emiliasky** [mikebrady/shairport-sync#1038]
None of them work
![image](https://user-images.githubusercontent.com/48217459/87222406-a8de0780-c373-11ea-8be1-58d7be89f4fb.png)

I’m using a raspberry pi zero W

**Comment by Axlsky** [comment]
When i try to connect to either of them, a loading icon just spins next to the name, infinitely

**Comment by mikebrady** [comment]
Yikes, that *is* peculiar alright. Let me suggest that you look through [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) and [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) for some hints and suggestions.

A Raspberry Zero W is fine for Shairport Sync.

**Comment by Axlsky** [comment]
This has fixed its, the 4 are now merged into 1.
However, another problem arised. When i connect, no audio plays. Please help?

**Comment by giggywithit** [comment]
I once had 2 showing up all the time and issues with sound until I disabled IPV6 on the PI running shairport-sync

**Comment by juliandc1969** [comment]
Apple devices like iPads do have a habit of caching and holding on to services that don't exist especially Airplay. I will get this sometimes if I reboot things quickly and stuff like UUID's, IP addresses change on board giving the illusion that it's another device when it's not. Once things have settled you'll always see just the one.
