### ISSUE TITLE
Metadata and config file

### ISSUE THREAD

**Issue by tatoosh** [mikebrady/shairport-sync#104]
How can i use metadata?
My version: shairport-sync -V v2.3.7-openssl-Avahi-ALSA-configfile

In config file i did:
metadata =
{
	enabled = "yes";
	include_cover_art = "yes";
	pipe_name = "/tmp/shairport-sync-metadata";
};

but the file isn't there.

By running the service the config file will not be loaded only by stopping the service and running with:
shairport-sync --configfile=/etc/shairport-sync.conf

Can you please help?

**Comment by mikebrady** [comment]
Hi there. Thanks for trying Shairport Sync. You must compile Shairport Sync with the `--with-metadata` configuration option – please see the `development` branch version of the README.md document.

**Comment by tatoosh** [comment]
okay thanks for the advice. and how to use the service with the correct
conf file in etc?
Am 29.07.2015 20:33 schrieb "Mike Brady" <notifications@github.com>:

**Comment by mikebrady** [comment]
The settings you specify are okay. Have a look at the shairport-sync-metadata-player code for an example of using the metadata. Or simply `cat` the metadata file.

**Comment by tatoosh** [comment]
Okay i did a make install with meta-data and have no: 2.3.7-openssl-Avahi-ALSA-metadata-configfile
I will try it out on the weekend. Thx

**Comment by mikebrady** [comment]
Sounds good!

**Comment by tatoosh** [comment]
i tested it now, the file /tmp/shairport-sync-metadata is always 0 byte. with the sync-metadata-reader or cat i won't get a result.
I tried to change user, group and file permissions - no change.
By deleting the file it will created empty again.

**Comment by mikebrady** [comment]
You should not have to do anything to permissions, etc. The file is a pipe. If you cat the pipe and then play something to Shairport Sync with metadata enabled, you will get metadata being fed through the pipe. Make sure Shairport Sync is running and has metadata enabled in the configuration file. If you run it from the I it script, it will run in root mode.

**Comment by tatoosh** [comment]
Okay, so the filesize will always be 0byte? I tried to get an output with cat or yout shairport-sync-metadata-reader.

**Comment by mikebrady** [comment]
Yes, and information will be piped through it as it is created and will then disappear. If you want to store it in a real file you could `cat` it to the file, e.g. `cat /tmp/shairport-sync-metadata > sample.txt`.

**Comment by tatoosh** [comment]
ok i understand, it is working now - thx a lot

**Comment by mikebrady** [comment]
Great.
