### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by gburkell** [mikebrady/shairport-sync#1041]
*EDIT* Sorry, I had a larger issue that I've fixed, I just can't get the audio to work now. And I can't see how to delete this issue. So I'm going through your previous answers to that and will update the issue ticket if I figure it out.  

Hi Mike,
Thanks for all this work you've done it's great!
I've installed Shairport-Sync using your instructions [here](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md).

I'm using a Raspberry Pi 3 and I can see the Raspberry Pi on my Mac OS High Sierra but not on iOS 13.5.1.

When I try to use Airplay to send to the pi from my computer I get no audio.

**Comment by mikebrady** [comment]
Thanks for the post. On a Pi (apart from a Pi Zero) it’s often a good idea to get everything working with the built-in headphone jack. Sorry if this is obvious, but just make sure the mixer is turned up full — the `alsamixer` utility is your friend here.

**Comment by gburkell** [comment]
Thanks Mike, I found your solution [here](https://github.com/mikebrady/shairport-sync/issues/741) and have got it all working.

GREAT SYSTEM MAN!
