### ISSUE TITLE
HDMI required to hear despite audio being directed to the Audio Jack

### ISSUE THREAD

**Issue by gburkell** [mikebrady/shairport-sync#1042]
Hey Mike,
So a really odd issue is occurring.  I finished the build, works great.  Unplug everything, and I go to another room, plug it in, no audio, I went back to the area I built it, plugged everything in, worked perfectly. Back to the other room, not working.  I plugged in an HDMI from another screen in the room I want to put it in, and the system works. It seems if I don't have an HDMI plugged into the pi, the config files are all correctly patched to the mini audio jack, and the audio comes out the mini-jack but with no HDMI plugged in from a monitor it doesn't seem to work. 

Have you experienced this before, any ideas?

**Comment by mikebrady** [comment]
Thanks. This doesn’t seem to be a Shairport Sync issue specifically.  Please see https://www.raspberrypi.org/documentation/configuration/audio-config.md for suggestions.

**Comment by gburkell** [comment]
Thanks, Mike, This is most likely it; I'm just at work, when I get back I'll try it out and report back!

Thanks for being so attentive to your Issues section, I've noticed as I've troubleshot the project, most of my questions are answered in other issues, and you have actually been very attentive to them!

**Comment by gburkell** [comment]
Off-topic question, I found when my pi went to a screensaver, it would lose the connection with Airplay.  I simply set the screen to not go to sleep.  Is this a suitable method, or is there a preferred method?

**Comment by mikebrady** [comment]
Hmm, I don’t know — I’ve always used the Pi in headless mode, without a monitor or keyboard. Maybe another contributor could help?

**Comment by gburkell** [comment]
@mikebrady - Unfortunately, the solution from that link you sent didn't work.

**Comment by mikebrady** [comment]
Hmm. Another possibility might be using `raspi-config`, though maybe you’ve tried that too.  This is not a problem I’ve ever run in to, possibly because I always use the Pi in headless mode and run Raspbian Lite.

**Comment by gburkell** [comment]
I found a workaround, it isn't pretty, but it works. I boot it up connected to a monitor, then once fully up, just test it, make sure that the system works.  Then I pulled out the HDMI and works fine. 

Thanks for all your help Mike!
