### ISSUE TITLE
Cannot work out how to get audio from the line output jack.

### ISSUE THREAD

**Issue by cragger89** [mikebrady/shairport-sync#1043]
Hi.

I've had success installing and configuring shairport-sync to the point where I can reliably play audio from an iPad without lip sync issues, it's fab.

The issue I am having is, I can only get audio from the HDMI output, even though the default device is the line output, if the TV I've connected to test with is disconnected from the Pi, it doesn't revert after a reboot.

Possibly from information overload, I cannot work out how to change this.

I used this guide: https://l.messenger.com/l.php?u=https%3A%2F%2Fthepi.io%2Fhow-to-set-up-a-raspberry-pi-airplay-receiver%2F&h=AT10Mf0wWGaWbJ4Z4qfyufFnj89LHvobcQkGxuDALwJOQXjtNpeb1bRmdpfPeVuwIvKipR9lS9cTzNtNp6c7xbBLWvpgzqrFc-_rdBz6FypuZRT0vMxPDx0TnXebTdo2Sns on a Pi 3B.

If there is a guide you link me to, it'd be appreciated, I'm just getting nowhere with looking on Google for "how to change shairport-sync output device", so decided to just ask you directly.

Craig

**Comment by mikebrady** [comment]
Thanks for the post. Have a look at #1042 — the contributor there Seems to have had a similar problem.

**Comment by cragger89** [comment]
Mike,

I persisted and noticed I'd failed to capitalise the beginning of the word headphones when I'd edited the config file.

System works perfectly, you're a talented man!
