### ISSUE TITLE
shairport pipe file

### ISSUE THREAD

**Issue by hankp46** [mikebrady/shairport-sync#1044]
I'm using shairport-sync to put audio input into a .raw file using pipe argument. This is working perfectly.

I have a linux python process that "listens'" to see if there is anything in the .raw file. I do this by checking to see if the size of the raw file is greater than 0. The problem I run into, ****I think****,  is that due to timing, the raw file is still being written to  and my process starts, getting no results. I thought checking to see if the raw file was closed would be the solution. Research brought me to the following :

```
from subprocess import check_output,Popen, PIPE
import time
while True:
   try:
       lsout=Popen(['lsof','/home/pi/testout.raw'],stdout=PIPE, shell=False)
       check_output(["grep",'/home/pi/testout.raw'], stdin=lsout.stdout, shell=False)
    except:
       print('file closed')
    else:
       print('file open') 
```

This works when I open and close the raw file in a python process. But when I use shairport-sync (start/stop speaking into mic) it never shows the file opening., always showing it closed.
Being a novice i don't understand why. 
Is there a better way (in python} to check to see if shairport-sync has finished writing to the raw file?

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately for this situation, Shairport Sync never closes the pipe, as to do so would potentially disturb programs that were listening to it continuously.

One way to check, indirectly, whether Shairport Sync had written to the pipe would be to use the `run_this_before_play_begins` and `run_this_after_play_ends` hooks. You could use these to know when output had started and when it had stopped.

**Comment by hankp46** [comment]
Thanks for the reply. I figured that was the case after I posed the question. I have a workaround, not the greatest but does work. Will look into your suggestion. The run_this_after_play_ends looks promising.



Sent from myMail for iOS


Wednesday, July 22, 2020, 1:26 PM -0400 from notifications@github.com  <notifications@github.com>:

**Comment by hankp46** [comment]
In issue #904 you mention that run_this_after_play_ends is activated when a “teardown signal is sent. What is that and how do you send it?

**Comment by mikebrady** [comment]
The `TEARDOWN` signal is part of the protocol used to communicate between the music player – the sender, which could be, for example an iOS device –  and the AirPlay output device, which would be Shairport Sync in this case. When the player stops, it sends a TEARDOWN signal to Shairport Sync. This causes Shairport Sync to close down the play session and call the program connected to the `run_this_after_play_ends` hook, if any.

So, only the music player can send a `TEARDOWN` signal, I'm afraid.

**Comment by hankp46** [comment]
Sorry to keep bothering you. I’m speaking through an IOS device using the Microphone app. Is the TEARDOWN signal sent went I stop speaking or when I shutoff the mic or something else?



Sent from myMail for iOS


Thursday, July 23, 2020, 7:33 AM -0400 from notifications@github.com  <notifications@github.com>:

**Comment by mikebrady** [comment]
I’m afraid I don’t know the answer to that — the developer might be able to tell you.
