### ISSUE TITLE
Question: Avoiding interpolation / stuffing

### ISSUE THREAD

**Issue by raisinbear** [mikebrady/shairport-sync#1045]
Hi  

first of all let me say this project is excellent work, thanks so much for developing and maintaining!  
My question is in regard to the stuffing. I have a pi zero (connected via wifi) hooked up to my hifi via hifiberry digi+ / coax. I'm mainly using shairport sync because I liked the idea of streaming losslessly via wifi (from iOS to be specific). I'd like to keep the audio material as bit perfect as possible, so I want to minimize interpolation. I'm still trying to wrap my head around how the whole transport mechanism works, but I see there is no option to disable stuffing, maybe for the reason that it could be necessary due to the source pushing data too fast / slow with respect to the sink device processing / outputting(?). With the --statistics option I see that I have very little stuffing to begin with (maybe every fourth to sixth entry) and then only +-3 corrections.

Would there be any downside to setting the drift tolerance very high, so corrections do not occur? Obviously output would not be in sync anymore, but I do not see how that would affect me with a single playback device. Worst case I could get issues with buffer under or overrun (but not as long as I leave resyncing activated, I guess), if one device is sytematically too fast or too slow and not just randomly ahead or behind.  

Thanks :)

**Comment by mikebrady** [comment]
Thanks for the post and for the kind words.

Actually, it is possible to turn off synchronisation -- see the `disable_synchronization` setting in the `alsa` section of the configuration file. 

Generally, with a single playback device there is no particular problem with disabling synchronisation or setting the drift tolerance to a very high value, except, of course, that you will eventually get overrun or underrun. In my experience, devices are usually systematically slow or fast, so it will happen eventually.

**Comment by raisinbear** [comment]
Thank you very much for the quick reply. I can't believe I missed this option. Probably it's because I installed the version from the official Raspian Buster repo, which might be quite a bit older. I will compile the current one later and give it a go.
