### ISSUE TITLE
Equalizer ALSA plugin doesn't work

### ISSUE THREAD

**Issue by project-owner** [mikebrady/shairport-sync#1046]
Hi,

I'm trying to add equalizer functionality to the shairport-sync. The platform: Raspberry Pi 3B+, OS: Raspberry Pi OS.
I installed equalizer plugin this way:
sudo apt-get install libasound2-plugin-equal
Here is my /home/pi/.asoundrc file:
```
pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw card 0
}
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm "plughw:0,0";
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}
```

I use the following parameters in the 'alsa' section in the file /etc/shairport-sync.conf:
output_device = "default";
mixer_control_name = "Headphone";

When shairport-sync is running the equalizer changes don't have any effect in the output sound. For example when I change frequency band values manually using 'alsamixer':
alsamixer -D equal

If I use any other player for example 'vlc' with the same 'default' device everything works as expected.
I'm not sure if this is shairport-sync issue or some ALSA misconfiguration. Probably you faced this before.

Thanks in advance!

**Comment by mikebrady** [comment]
Thanks for the post, but I’m afraid I don’t use the ALSA plugins or equalizer — Shairport Sync is really designed to output to the hardware directly.

Maybe some other contributors would have some experience they could share.

**Comment by hobbyquaker** [comment]
For me this works - have nearly the same configuration, only difference is `mixer_control_name = "Digital";`.
Keep in mind that you need to run alsamixer under the shairport-sync user like e.g. `sudo -H -u shairport-sync alsamixer -D equal`

**Comment by PaulWieland** [comment]
Does anyone know how to make shairport-sync output to the alsa equalizer when it's running under docker?

I'm running the alsa equalizer on the host, and shairport-sync is running under docker.

**Comment by shameerariff** [comment]
It can done in a very simple manner as follows
In the config make the following changes

`output_device = "equal"
`mixer_control_name="Digital"`

Make sure to enable the alsa equalizer as well as Digital is only applicable if the DAC was used other wise use the actual device control usually Master.
