### ISSUE TITLE
Configuration File Not Found

### ISSUE THREAD

**Issue by gburkell** [mikebrady/shairport-sync#1050]
When I try to go into the configuration file to configure things for the system, I get no file found or a blank file? Has anyone encountered this?

**Comment by mikebrady** [comment]
At a guess, the installation has not been done correctly. Did you carry out the `# make install` step without error?

**Comment by gburkell** [comment]
It was a few days ago so I'm not sure, I'm going to try a fresh reinstall and let you know.  I'll update the post when I finish that.

**Comment by gburkell** [comment]
Yup, that was it, thanks Mike.
