### ISSUE TITLE
Airplay 2 Support 

### ISSUE THREAD

**Issue by lukeb0t** [mikebrady/shairport-sync#1053]
As AP2 has been cracked for a while now, are there plans to integrate support? So far, I haven't seen the cracked code yield  any easily consumable github project.

https://9to5mac.com/2019/12/05/airplay-2-cracked/

**Comment by gmkey** [comment]
Maybe the fact that the article links to a very long thread on this issue #535 might have been a giveaway to the fact that there is already an issue and it's up-to-date with the current information.

**Comment by mikebrady** [comment]
Agreed, Issue #535 is the place to follow it.
