### ISSUE TITLE
warning: Speed requested: 44100. Speed available: 48000.

### ISSUE THREAD

**Issue by adminy** [mikebrady/shairport-sync#1056]
I get this message when I do -u ... also It's jumpy in audio, like with micro interrupts.

I use alsa, USB audio dac, pi 4b. Installed through apt at first then compiled myself, no difference ...

**Comment by mikebrady** [comment]
It sounds like your DAC can not output at 44,100 frames per second or a multiple of it, which Shairport Sync needs. Could you post the full message please? See also the TROUBLESHOOTING.md page.

**Comment by adminy** [comment]
Yes, you are right, This is due to my usb DAC because I See no interruptions with aux.
 - My raspberry pi isn't using usb internet, it's directly plugged into lan cable.
 - I set a flag telling alsa not to worry about synchronisation in shairport-sync configuration and that made it worse.
 - I plugged it into usb 3.0 as well, same issue (no other usb device in)

I tried playing a wav with `aplay` and it plays fine despite the warning message: `Warning: rate is not accurate (requested = 44100Hz, got = 48000Hz)`

My device:
```
card 0: BR21 [JieLi BR21], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

I also tried adding the configuration into alsa as you mentioned with the slave but then I got this:
```
ALSA lib pcm_hw.c:1898:(_snd_pcm_hw_open) Unknown field slave
aplay: main:828: audio open error: Invalid argument
```
I understand its a usb dac specific issue since it plays with aux but I'm not entirely certain as to what the issue is since aplay plays the audio fine despite the rate being different.

I also compiled apple alac so I can add the with-alac flag. 

Anyways here are the statistics:
```
warning: The "general" "statistics" setting is deprecated. Please use the "diagnostics" "statistics" setting instead.
warning: Speed requested: 44100. Speed available: 48000.
sync error in milliseconds, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy, source nominal frames per second, source actual frames per second, output frames per second, source clock drift in ppm, source clock drift sample count, rough calculated correction in ppm
    -31.58,     962.1,    1026.9,        1003,      0,    161,      0,      8,   6106,  200,  224,       0.00,       0.00,   47995.55,      0.00,     0,1000000.00
    -33.24,    2840.9,    2840.9,        2006,      0,    288,      0,     14,   6126,  200,  224,       0.00,       0.00,   47994.68,      0.00,     0,1000000.00
    -33.14,    2840.9,    2840.9,        3009,      0,    421,      0,     21,   6097,  200,  224,       0.00,       0.00,   47994.08,      0.00,     0,1000000.00
    -33.11,    2840.9,    2840.9,        4012,      0,    552,      0,     27,   6065,  201,  224,       0.00,       0.00,   47992.65,      0.00,     0,1000000.00
    -32.84,    2840.9,    2840.9,        5015,      0,    706,      0,     34,   6069,  200,  224,       0.00,       0.00,   47992.57,      0.00,     0,1000000.00
    -32.94,    2840.9,    2840.9,        6018,      0,    835,      0,     40,   6053,  200,  224,       0.00,       0.00,   47992.81,      0.00,     0,1000000.00
    -32.96,    2840.9,    2840.9,        7021,      0,    973,      0,     47,   6081,  200,  224,       0.00,       0.00,   47992.60,      0.00,     0,1000000.00
    -33.05,    2840.9,    2840.9,        8024,      0,   1128,      0,     54,   6067,  200,  224,       0.00,       0.00,   47992.79,      0.00,     1,1000000.00
    -32.92,    2840.9,    2840.9,        9027,      0,   1258,      0,     60,   6059,  200,  224,       0.00,       0.00,   47993.20,      0.00,     1,1000000.00
    -33.00,    2840.9,    2840.9,       10030,      0,   1397,      0,     67,   6096,  201,  224,       0.00,       0.00,   47992.80,      0.00,     2,1000000.00
    -32.99,    2840.9,    2840.9,       11033,      0,   1529,      0,     73,   6053,  200,  224,       0.00,       0.00,   47992.91,      0.00,     2,1000000.00
    -33.08,    2840.9,    2840.9,       12036,      0,   1668,      0,     80,   6074,  200,  224,       0.00,       0.00,   47992.98,      0.00,     2,1000000.00
```

**Comment by mikebrady** [comment]
Yeah, what the statistics are showing is that Shairport Sync is trying to compensate for the fact that frames of audio are being consumed by the DAC at 48,000 fps and supplied at 44,100.

The ALSA subsystem has transcoding facilities built in, so, by directing the output to an ALSA pseudo-device which does the transcoding and sends it to the real DAC, you should be able to get it to work. Perhaps some other contributor would be able to help you to set that up -- I have not done it.

**Comment by adminy** [comment]
Ok, well I guess there was a software conversion device on the list, so all I had to do is default my configuration to it.
the following changes to `/etc/asound.conf` solved the problem.
```
defaults.pcm.!card BR21
defaults.ctl.!card BR21
defaults.pcm.!device 0
defaults.ctl.!device 0
```

But highly advised to test with aplay song.wav to see if you get any warning messages, if you don't then this is not a 48000 to 44100 conversion issue.
