### ISSUE TITLE
Bit perfect stream for a DAC through USB?

### ISSUE THREAD

**Issue by serafxxx** [mikebrady/shairport-sync#1059]
Hey, I'm very excited to pair shairport-sync with my Teac UD-503 DAC through USB and I'm really curious how I can achieve best sound possible. AFAIK I'll meet two problems: latency (staffing) and resampling.

Question 1: Would it be possible to beat stuffing/latency by enabling partial audio synchronisation (how?). What if I'll disable Resynchronisation (resync_threshold_in_seconds = 0 ?). I can imagine that instead of staying in sync, it will be better (for the bit-perfectness) to buffer more data to stay robust to network interruptions. 

Question 2: Going to set alsa to use hardware driver. Am I right that it will skip all the resampling and send bit-perfect stream to USB?

Question 3: Will it make more sense to use something more powerful then Respberry pi (like some Intel NUC)

Would be great if you could direct/correct me. Thanks

**Comment by mikebrady** [comment]
Thanks for the post.

First, I think there is a slight misunderstanding about latency. Latency is just the time difference between when sound is sent and when it is played. It's a feature of the AirPlay protocol. Shairport Sync sets the latency to whatever the source, e.g. the Music app, requests, which is normally 2 or 2.25 seconds. There is no real way around it, unfortunately -- when AirPlay audio is selected by the source, it is expected that there will be a latency. Anyway, the good news is that latency doe not effect fidelity.

AirPlay is basically CD quality -- 16 bit interleaved stereo at 44,100 frames per second. Samples are signed linear 16 bit PCM. To get as close to bit-perfect performance, you should use the settings in the configuration file to
1. Select 44,100 `output_rate`. 
2. Select S16 (signed 16-bit sample size) `output_format`.
3. Use the DAC's hardware mixer for volume control by setting `mixer_control_name` to the name of the mixer. This will avoid requiring Shairport Sync to do integer arithmetic for volume control and associated dithering.
4. Set the output device to the hardware driver for the DAC, which will begin with `hw:...`.

These settings will mean that audio will pass through Shairport Sync unchanged to the DAC hardware except for occasional synchronisation events -- see below.

Interpolation, or "stuffing", is done for synchronisation, i.e. to keep audio in time with what is expected. If the DAC is running fast, then, without synchronisation, the output from the DAC would run ahead of when it supposed to be. If the DAC is running slow, then, without synchronisation, the output from the DAC would run later and later.

To interpolate, Shairport Sync will occasionally remove or insert a frame to keep the output coming out at exactly the right time. Interpolation is done either by removing or inserting a single frame (`"basic"`) or using the SoX library (`"soxr"`) to resample a sequence of 352 frames to either 353 or 351 frames. While `basic` is arguably more bit-perfect, `soxr` is less audible.

You can experimentally turn off synchronisation (and thus stop interpolation) with the `disable_synchronization` setting. Synchronisation will be lost but, worse, the buffers between the source or player will eventually underflow or overflow.

If you enable the logging of statistics on Shairport Sync, and if you let the Shairport Sync device connect to an `NTP` time server, I believe you will get an accurate idea of exactly what rate your DAC is really running at, and you'll get a good estimate of the rate at which audio is being supplied by the source, as well as drift between the devices' clocks.

Generally speaking, with a decent output device, a Pi has plenty of power; IMHO there is no benefit from a higher performance system.
