### ISSUE TITLE
No Audio - Sound Test Works Config File Set with AlsaMixer

### ISSUE THREAD

**Issue by ed620** [mikebrady/shairport-sync#1060]
Hi - any help would be gratefully received - I do not get audio for some reason.

Tuneblade connects and shows data being streamed at 75Kbps. I assume this indicates the issue is further down the line. 

The command  `speaker-test -c2 -D plughw:1,0` gets output from speakers (Headphone jack for now) when run on Pi.

I have been through [#741 No Audio](https://github.com/mikebrady/shairport-sync/issues/741) and attempted to make the same fixes. The service seems to start and run OK. 

I have a config file with edits as noted in the above thread: 

[shairport-sync.txt](https://github.com/mikebrady/shairport-sync/files/5114207/shairport-sync.txt)

Edit: Pi shows rx ~500kbit/s over virtual desktop. It is getting things I think.

**Comment by mikebrady** [comment]
Thanks for the post.

All of the settings are commented out -- that is, they have no effect. If you (as I think is the case) are attempting to output to `hw:1` and use the `"Headphone"` mixer for volume control then the lines:
```
//	output_device = "hw:1"; // the name of the alsa output device. Use "shairport-sync -h" to discover the names of ALSA hardware devices. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
//	mixer_control_name = "Headphone"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
```
needs to be uncommented to make them active:
```
	output_device = "hw:1"; // the name of the alsa output device. Use "shairport-sync -h" to discover the names of ALSA hardware devices. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
	mixer_control_name = "Headphone"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
```

**Comment by ed620** [comment]
Bloomin magic. 

You wouldn't believe how long I just ignored those comment-marks.
