### ISSUE TITLE
Is it possible to configure Shairport-sync so you can select multiple instances from an iPhone at the same time.  This is possible with the old Airport Express and Apple TV, however my sharepoint-sync instances only allow one to be selected at a time on the iPhone so selecting another one will turn off the first.

### ISSUE THREAD

**Issue by mcopete** [mikebrady/shairport-sync#1061]

**Comment by mikebrady** [comment]
Thanks for the post. A popular was of describing what you're referring to is "Multi-Room Audio" -- that is, the ability for one audio source to drive multiple speaker systems simultaneously, presumably in different rooms.

Shairport Sync is an AirPlay player (and so is the old AirPort Express), and can do Multi-Room Audio from sources that support it. The standard apps that support Multi-Room Audio in AirPlay are iTunes on Mac and PC and the macOS "Music" app. [Forked-daapd](https://github.com/ejurgensen/forked-daapd) is a popular Linux implementation that also supports Multi-Room Audio. However, the iPhone has never supported Multi-Room Audio through AirPlay.

In 2018, AirPlay 2 was introduced. iOS devices can use AirPlay 2 to provide Multi-Room Audio. Shairport Sync does not implement AirPlay 2, so can not support Multi_Room Audio from iOS devices.

**Comment by OnnoH** [comment]
If you're on a Mac, Rogue Amoeba's Airfoil (https://www.rogueamoeba.com/airfoil/mac/) in combination with Airfoil Satellite (https://www.rogueamoeba.com/airfoil/satellite/) might be something to consider.

No sponsor, shareholder or employee. Just use it myself ;-)

**Comment by iVolt1** [comment]
TuneBlade works well on Windows 10 and has a simple app for connecting and controlling volume on all Airplay receivers it finds.  I use TuneAero also sometimes as a central airplay reciever to play out to the others as well.  I mostly use spotify connect from my iphone to have the Windows 10 machine play out to the Airplay receivers I chose form the TuneBlade app to 3 openwrt routers with USB DACS and a Pi 3B+ and Pi Zero W with a JustBoom DigiHat.  All run Shairport-sync of course!  Thanks Mike.
