### ISSUE TITLE
Streaming audio to multiple backends

### ISSUE THREAD

**Issue by djcopley** [mikebrady/shairport-sync#1063]
Is it currently possible to stream the music to multiple backends? I am working on a music visualizer and would like to stream the raw data to a named pipe in addition to the alsa backend. Secondary question - running shairport-sync with `shairport-sync -o pipe` causes an immediate return with no output. Any thoughts?

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync outputs just to one back end at a time. But you could take output from a named pipe and split that with the unix `tee` command, I believe.

If you look in the system log, I imagine you'll find an error message from Shairport Sync. My guess is that Shairport Sync doesn't have permission to open the pipe, but you should check the log. What version of Shairport Sync are you using?

**Comment by djcopley** [comment]
Doh! Of course! Permissions was the issue. I'm looking at the source code - would I only need to modify player.c to hack together multiple outputs... Could I not just send the buffer to alsa and pipe?

**Comment by mikebrady** [comment]
I’m glad that it worked out. There’s a bit more going on than just sending the frames to the backends, though some backends are pretty straightforward. My guess is that it would be gnarly.

**Comment by djcopley** [comment]
That is unfortunate :/ I would love to run shairport-sync normally as a systemd daemon, and write a standalone program that does signal processing on the audio data from the unix pipe. Thanks for the help.
