### ISSUE TITLE
Jack re-patch causes 1.5 second dropout

### ISSUE THREAD

**Issue by kiwi-ed** [mikebrady/shairport-sync#1067]
Hi Mike,

I'm having another crack at this sink switching stuff again but with this time using Jack ( with SPS left playing ). The only issue I have is about 1 second after a Jack reconnect I get a 1.5 second break in the audio - so that's 1 second audio immediately after reconnecting, then 1.5 gap, after that fine. By the looks of the debug it may be because there's a large positive sync error which is probably correct. Is there any possible workaround you could think of that could avoid this dropout i.e. a redirection stub to keep the buffers flowing? 

What I would like to know is how `player.c` knows the sink - in this case Jack - has been un-patched so to speak causing sync errors. Does the sink return frames written and that's compared to the next incoming etc? 

FYI - If it's a fast unpatch => repatch i.e. with no delay then there's no errors or dropouts as you'd expect. But of course it could be sometime in use before switching back to SPS. 

Test:
```
./off && sleep 4 && ./on
```
// Jack unpatched
```
3.715909916 "audio_jack.c:187" JACK graph reorder callback called.
0.000103750 "audio_jack.c:191" JACK latency for port out_L	min: 0	 max: 0
0.000032875 "audio_jack.c:191" JACK latency for port out_R	min: 0	 max: 0
0.000025624 "audio_jack.c:196" Average maximum JACK latency across all ports: 0
method return time=1599639616.525154 sender=:1.13 -> destination=:1.96 serial=530 reply_serial=2
```

// Sleep 4

// SPS repatched to Jack
```
method return time=1599639620.596380 sender=:1.13 -> destination=:1.98 serial=545 reply_serial=2
method return time=1599639620.609036 sender=:1.13 -> destination=:1.99 serial=548 reply_serial=2
         4.097070296 "audio_jack.c:187" JACK graph reorder callback called.
         0.000070125 "audio_jack.c:191" JACK latency for port out_L	min: 0	 max: 0
         0.000036375 "audio_jack.c:191" JACK latency for port out_R	min: 2048	 max: 2048
         0.000026625 "audio_jack.c:196" Average maximum JACK latency across all ports: 1024
method return time=1599639620.641508 sender=:1.13 -> destination=:1.100 serial=551 reply_serial=2
         0.023682276 "audio_jack.c:187" JACK graph reorder callback called.
         0.000092875 "audio_jack.c:191" JACK latency for port out_L	min: 2048	 max: 2048
         0.000036499 "audio_jack.c:191" JACK latency for port out_R	min: 2048	 max: 2048
         0.000029875 "audio_jack.c:196" Average maximum JACK latency across all ports: 2048
         0.018138050 "player.c:2326" Large positive sync error: 3657.
         0.082420781 "player.c:2172" Player: packets out of sequence: expected: 54865, got: 54874, with ab_read: 54875 and ab_write: 55060.
         0.022235157 "player.c:2326" Large positive sync error: 2800.
         0.077599426 "player.c:2172" Player: packets out of sequence: expected: 54878, got: 54887, with ab_read: 54888 and ab_write: 55068.
         0.111140161 "player.c:2326" Large positive sync error: 2566.
         0.079814667 "player.c:2172" Player: packets out of sequence: expected: 54902, got: 54911, with ab_read: 54912 and ab_write: 55092.
        11.725768910 "rtp.c:138" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.5,    12403.0,    58228.4.
```

Thanks.

**Comment by kiwi-ed** [comment]
I can reduce the 1.5 second delay right down by commenting out the Jack graph call back. So that's causing the delay. What is left is now 3-4 quick stutters as the syncs catch up. Is it possible to do anything with this?

 0.080813948 "player.c:2172" Player: packets out of sequence: expected: 25177, got: 25186, with ab_read: 25187 and ab_write: 25370.
         0.021875135 "player.c:2326" Large positive sync error: 3523.
         0.079776829 "player.c:2172" Player: packets out of sequence: expected: 25190, got: 25199, with ab_read: 25200 and ab_write: 25381.
         0.025684114 "player.c:2326" Large positive sync error: 2629.
         0.076923844 "player.c:2172" Player: packets out of sequence: expected: 25203, got: 25212, with ab_read: 25213 and ab_write: 25396.
         0.039335043 "player.c:2326" Large positive sync error: 2519.
         0.083484434 "player.c:2172" Player: packets out of sequence: expected: 25218, got: 25227, with ab_read: 25228 and ab_write: 25413.

Thanks.

**Comment by mikebrady** [comment]
I started to answer your question yesterday but got called away, unfortunately.

Shairport Sync doesn't know much about what the backend is doing. If enabled (as the Jac backend is) it continually asks the backend for the latency -- the time from when a frame of audio is given to it to when the frame is actually output. I imagine that when you change the Jack configuration you disrupt the latency calculation. TBH, I do not know of a systematic or principled way of circumventing that, so it follows that I don't know of a nice to deal with your requirement.

**Comment by kiwi-ed** [comment]
Thanks, it was a bit of a long shot. To be honest since posted this ticket I've made a few tweaks and it's 'acceptable' at the mo. I've hidden some of the stuttering deliberately in a slow change over... 

 Cheers.
