### ISSUE TITLE
conn->software_mute_enabled to avoid a blip and burst of old audio

### ISSUE THREAD

**Issue by kiwi-ed** [mikebrady/shairport-sync#1068]
Hi Mike,

In pursuit of the perfect pause and sink switch again.. actually almost there! So I'm using Jack as you know but no longer the SPS plugin but through an ALSA plugin and /etc/asound. The SPS plugin gave me bad stuttering and a few nightmares doing the patchbay connections where ALSA's a bit more automated. Anyway.. I'm messing around with the pausing and detecting of silence within player.c and then detecting when the audio starts up again ( to work around the iOS transport holding necessity).  

While doing this I've added a variable that toggles the "conn->software_mute_enabled" which seems to work and blanks out a few re-connection audio drop-outs. I can enable this when I pause and steal the sink and after starting play again re-enable the audio. The only issue now is a very short audio burst on initial play.  What's really strange is the audio burst (~200-500ms?) sounds like audio that's already been played! For example on Youtube there's always ads, if I play an ad then pause SPS on the first second of the following song, when pressing play again I get a burst of the previous ad even though the next song's video shows we're not playing the ad. Then conn->software_mute_enabled kicks in for as long as I enable it.  Could this weirdism be caused by residue RTP buffering?

If you have any hacks to silence this burst of audio it would be appreciated. I have tried putting a few conditionals before some of the config.output->play()s but oddly the audio still get past..

Thanks.

**Comment by mikebrady** [comment]
Thanks. Let me try to get my head around that.

**Comment by kiwi-ed** [comment]
Appreciated. I'm using 3.3.7rc1.

**Comment by kiwi-ed** [comment]
The burst is only present when stopped and started while the transport is still active. So:
Play music, pause via DBus, within a couple of seconds hit play again on the iPad - burst

**Comment by mikebrady** [comment]
Yeah, so what you are doing by turning off `conn->software_mute_enabled` is allowing Shairport Sync to send out received audio packets that should be muted. So it sounds like `conn->software_mute_enabled` is working properly at that point. I don't know where those packets of audio are coming from -- they seem to be coming from the player, and AFAIR they are not coming from any SPS buffers -- they would have been flushed by then.
