### ISSUE TITLE
Volume range set in conf not the same as on dbus

### ISSUE THREAD

**Issue by kiwi-ed** [mikebrady/shairport-sync#1069]
Hi Mike,

Quick question here about volumes and dbus. I'm trying to adjust/combine/link various music apps volumes and it's working but needs a lot of polishing. My ARM has no mixers etc. I use dbus to fire the volume value back to SPS. What I need to do is to match the other apps volume range and get SPS to use 0db to -80db. I can set this in the conf i.e.   volume_range_db = 80;       volume_max_db = 0.0 ; and see that reflected in -vv debug as the volume changes. But what I see on bus is somewhat different. This may be how it's designed but can it be the same as I set SPS? Does "volume mode is 0" has a bearing?

This is a mix of SPS debug and dbus-monitor:

```
         0.000025126 "rtsp.c:497"   Type: "Content-Type", content: "text/parameters"
         0.000019750 "rtsp.c:497"   Type: "CSeq", content: "24"
         0.000018000 "rtsp.c:497"   Type: "DACP-ID", content: "BF4EC4356561A649"
         0.000018750 "rtsp.c:497"   Type: "Active-Remote", content: "3100009626"
         0.000018250 "rtsp.c:497"   Type: "User-Agent", content: "AirPlay/425.1"
         0.000070875 "loudness.c:47" Volume: -56.9 dB - Loudness gain @10Hz: 18.5 dB  **<======= I'd like to keep this value**
         0.000084625 "player.c:3278" player_volume_without_notification: volume mode is 0, airplay volume is -26.250000, software_attenuation: -5692.307692, hardware_attenuation: 0.000000, muting is disabled.   **<== SPS changed it here!**
         0.000042376 "rtsp.c:2672" Connection 1: RTSP Response:
         0.000020875 "rtsp.c:497"   Type: "CSeq", content: "24"
         0.000018750 "rtsp.c:497"   Type: "Server", content: "AirTunes/105.1"
         0.000930878 "dbus-service.c:195" Build metadata

```

```
signal time=1600107496.607654 sender=:1.99 -> destination=(null destination) serial=26 path=/org/gnome/ShairportSync; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.gnome.ShairportSync.RemoteControl"
   array [
      dict entry(
         string "AirplayVolume"
         variant             double -26.25   **<============================== dbus** 
      )
   ]
   array [
   ]
 ```
Thanks once again.

**Comment by mikebrady** [comment]
Looking at this very quickly -- do you have the "loudness" filter enabled?

**Comment by kiwi-ed** [comment]
Not sure, it's certainly not in my conf. My conf is pretty basic.

**Comment by mikebrady** [comment]
Okay, so the range of an AirPlay volume control or slider is from -30.0 to 0.0, with -30.0 being the lowest volume and 0.0 being the highest. There is also -144.0 which signifies "mute". The range seems to be more or less logarithmic, but in Shairport Sync is mapped though a "volume control profile" -- a piecewise linear transfer function -- that gives slightly finer control at the start and end of the range. The fact that the transfer function is non-linear means that there isn't a linear relation between the -30.0 .. 0.0 range of the AirPlay volume control and the -80.0 .. 0.0 range of the attenuator. In the log extracts above, you're seeing the AirPlay volume of -26.25 being mapped to -56.9 on the attenuator.

If you want a linear relationship, when choose the `"flat"` volume control profile. In the log, the volume control profile is called the volume mode. Zero is the standard profile and (I guess!) 1 is the flat profile. (I should reword that message!)

**Comment by kiwi-ed** [comment]
OK, understood. In the end I whipped up a simple matching algorithm between the various application volume units.

Thanks again, appreciated!
