### ISSUE TITLE
Logitech Media Server PlugIn (Squeezebox)

### ISSUE THREAD

**Issue by opacey** [mikebrady/shairport-sync#107]
I have been trying to find a way to integrate airplay into LMS such that airplay sources on the network can broadcast to any of the squeezebox devices controlled via LMS. I run LMS on a Synology NAS. Matej (http://blog.freshlytyped.nl/shareport-squeezbox-synology/) has been most successful in putting together a solution as far as I can see but the lack of sync and poor lag meant the project was abandoned. As shairport-sync now has a successful beta port to Synology would anyone be willing to extend the shairport-sync project into the LMS? I'm afraid I don't have the skills to do it.

**Comment by mikebrady** [comment]
I think I'll pass on this, TBH. IT looks like a lot of work...

**Comment by opacey** [comment]
Thanks Mike, I understand. Hopefully someday soon I'll be able to contribute. In the mean time I'll see if I can gather support from the LMS community and perhaps build a bounty pot. LMS is a great platform and extending support to AirTunes/Play makes it unbeatable in my book.

**Comment by noelhibbard** [comment]
I assume you have seen this thread:

**Comment by opacey** [comment]
I had not! Thank you kindly for the link. I haven't been able to get it working as yet on my synology but will report up here once successful. Not being able to sync is a shame but not a big negative for me.

**Comment by opacey** [comment]
PS, I second your suggestion of a synchronised broadcast 'bridge'(?). It'd be a nice feature.

**Comment by noelhibbard** [comment]
I managed to modify the WaveInput LMS plugin to read the pipe output of shairport-sync. The problem right now is LMS gets lost when ever the stream of data to the pipe stops. When I pause, seek or change tracks on my phone then the pipe output from shairport-sync stops momentarily. I asked Mike if it would be possible to fill in the blanks with science rather so the stream of data to the pipe never ends. If that is possible then I think we have a solution for LMS. I should also be able to take advantage of shairport-sync's metadata pipe to get the track info and artwork into LMS.

**Comment by mikebrady** [comment]
Please see https://github.com/mikebrady/shairport-sync/issues/108#issuecomment-141116717
