### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.6.dylib

### ISSUE THREAD

**Issue by dmatora** [mikebrady/shairport-sync#1071]
Installed on macOS Catalina using `brew install shairport-sync`, when i try to run it i get
```
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.6.dylib
  Referenced from: /usr/local/opt/pulseaudio/lib/libpulse.0.dylib
  Reason: image not found
Abort trap: 6
```

**Comment by mikebrady** [comment]
I’m not the originator of the HomeBrew installer, I’m afraid, so I don’t know too much about it. Maybe another contributor would be able to help.

**Comment by dmatora** [comment]
Well, I figured to do `brew install gdbm` and that solved it.
Too bad it has no support of Airplay 2

**Comment by mikebrady** [comment]
I’ll close this, if that’s okay. It seems to be resolved. Feel free to reopen if necessary.
