### ISSUE TITLE
Information request: Supported Airplay client remote control servers.

### ISSUE THREAD

**Issue by kiwi-ed** [mikebrady/shairport-sync#1074]
Hi Mike,

Over time I've probably had some of this answered but I'm after a list of what SPS supports and doesn't support regarding the remote control back-end. I seem to remember you mentioned there were some that SPS couldn't RC play/pause due to lack of information or something ( iTunes?? )...

Thanks.

**Comment by mikebrady** [comment]
Yeah, I've never really documented this, but rescue is at hand -- there is a GUI program on Linux called `D-Feet`. This will allow you to see what properties and commands Shairport Sync can deal with -- see the screenshot below.

As fas as remote control goes, there are two broad categories -- iTunes and the macOS Music app provide, let's say, "Advanced Remote Control". Everything else from Apple provides just "Remote Control". (BTW, different version of macOS Music are more or less compatible with SPS. At present, the compatibility is fine.

When a play session is started to SPS, it probes the player to see if it can do remote control and if so whether it can also do advanced remote control. These statuses are provided as the appropriate `Available` properties in the D-Bus interfaces. Here is that screenshot:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4265913/94304691-d9dbda80-ff67-11ea-913a-0aa908155922.png">
