### ISSUE TITLE
Remote control with SPS and ROON

### ISSUE THREAD

**Issue by kiwi-ed** [mikebrady/shairport-sync#1076]
Hi Mike,

I'm trying to figure out why I cannot pause or adjust the volume on a PC music client call Roon. Roon provides Airplay capability on Windows so I can play music using SPS. However I have no remote control functionality. What's interesting is the cycling debug I get from rtsp.c compared to an iOS device. On my iPad I do not get the continual debug below; could this be a good place to start?

```
root@devcie:~#          1.217582484 "rtsp.c:2621" Connection 4: Received an RTSP Packet of type "SET_PARAMETER":
         0.000081373 "rtsp.c:497"   Type: "Client-Instance", content: "aa38c8986a0e43ab"
         0.000048999 "rtsp.c:497"   Type: "DACP-ID", content: "88433A5F90D34CDB"
         0.000028874 "rtsp.c:497"   Type: "Active-Remote", content: "637366269380647998"
         0.000027250 "rtsp.c:497"   Type: "User-Agent", content: "iTunes/12.6 (Macintosh; OS X 10.12.4)"
         0.000027249 "rtsp.c:497"   Type: "Content-Type", content: "text/parameters"
         0.000025875 "rtsp.c:497"   Type: "RTP-Info", content: "rtptime=1003474925"
         0.000025999 "rtsp.c:497"   Type: "CSeq", content: "16"
         0.000036374 "rtsp.c:497"   Type: "Content-Length", content: "43"
         0.000104373 "rtsp.c:2664" Connection 4: RTSP Response:
         0.000035374 "rtsp.c:497"   Type: "CSeq", content: "16"
         0.000025750 "rtsp.c:497"   Type: "Server", content: "AirTunes/105.1"
         0.000170496 "metadata_hub.c:542" MH Progress String set to: "992229425/1003474925/1011016025"
         0.001600591 "dbus-service.c:195" Build metadata
```
This is dumped every second or two when connect to Roon, as mentioned on the I pad I probably get this once as it's setting up then no more..

Any thoughts?

Thanks.

**Comment by kiwi-ed** [comment]
A full connection log.
[debug-roon-sps.txt](https://github.com/mikebrady/shairport-sync/files/5282395/debug-roon-sps.txt)

**Comment by kiwi-ed** [comment]
After a few tweaks to uint64 I can now get the larger "active-remote id" stored ( -vvv )
-- dacp.c:453" set_dacp_server_information set active-remote id to 637366370733369481.

 Apart from enlarging the ints I tweaked  rstp.c conn->dacp_active_remote = strtoull(ar, &p, 10) to accept a larger string.

However still no connection back to the server..

**Comment by mikebrady** [comment]
> A full connection log.
> [debug-roon-sps.txt](https://github.com/mikebrady/shairport-sync/files/5282395/debug-roon-sps.txt)
> 
> May not be anything but compared to iOS the "Active-Remote", content: "637366269380647998" numbers are a lot longer..
> If I'm matching up the right things => uint32_t client_active_remote - so this number won't fit..
> ( or this one uint32_t dacp_active_remote )

Is this a log of Roon on Windows playing to SPS?

> Hi Mike,
> 
> I'm trying to figure out why I cannot pause or adjust the volume on a PC music client call Roon. Roon provides Airplay capability on Windows so I can play music using SPS. However I have no remote control functionality. What's interesting is the cycling debug I get from rtsp.c compared to an iOS device. On my iPad I do not get the continual debug below; could this be a good place to start?
> 
> root@devcie:~# 1.217582484 "rtsp.c:2621" Connection 4: Received an RTSP Packet of type "SET_PARAMETER":
> 0.000081373 "rtsp.c:497" Type: "Client-Instance", content: "aa38c8986a0e43ab"
> 0.000048999 "rtsp.c:497" Type: "DACP-ID", content: "88433A5F90D34CDB"
> 0.000028874 "rtsp.c:497" Type: "Active-Remote", content: "637366269380647998"
> 0.000027250 "rtsp.c:497" Type: "User-Agent", content: "iTunes/12.6 (Macintosh; OS X 10.12.4)"
> 0.000027249 "rtsp.c:497" Type: "Content-Type", content: "text/parameters"
> 0.000025875 "rtsp.c:497" Type: "RTP-Info", content: "rtptime=1003474925"
> 0.000025999 "rtsp.c:497" Type: "CSeq", content: "16"
> 0.000036374 "rtsp.c:497" Type: "Content-Length", content: "43"
> 0.000104373 "rtsp.c:2664" Connection 4: RTSP Response:
> 0.000035374 "rtsp.c:497" Type: "CSeq", content: "16"
> 0.000025750 "rtsp.c:497" Type: "Server", content: "AirTunes/105.1"
> 0.000170496 "metadata_hub.c:542" MH Progress String set to: "992229425/1003474925/1011016025"
> 0.001600591 "dbus-service.c:195" Build metadata
> 
> This is dumped every second or two when connect to Roon, as mentioned on the I pad I probably get this once as it's setting up then no more..
> 
> Any thoughts?
> 
> Thanks.

Maybe the Roon implementation of AirPlay doesn't incorporate a remote control facility. (There's no reason why it should, I guess.) The one-second bursts of activity seem to just be sending the progress triple at regular intervals.

I'll make the active_remote accept a larger number -- maybe just a string, thanks for that!

**Comment by mikebrady** [comment]
SO, I've pushed an update that I believe removes the size restriction on the `Active_Remote` token -- in fact, it treats it as a string rather than an unsigned 32-bit number. While your changes would allow SPS to read and store a larger `Active_Remote` number, from what you've written I am unsure as to whether it would be send the correct `Active_Remote` token back to ROON when necessary (it might be sending a 64 bit number mangled in some way to 32 bits), and this might cause ROON to ignore remote control messages. Of course we have no assurance that ROON implements _any_ remote control functionality, but if it did, this bug might stop it responding. So this update might be worth trying!

**Comment by kiwi-ed** [comment]
Thanks for the update. I ran it up and there's not a lot more response compared to what I did but conversion to strings is a better idea. I am beginning to wonder if you're correct in thinking that ROON doesn't actually offer a RC server... Reason being through SPS -vvv debug I cannot get a dacp_server.port number; I get "No DACP port specified". That lead me to mdns_avahi.c and it seems that after registering the callbacks nothing's ever called.... Checking avahi-browser on another PC it turns out that no "iTunes Remote Control" avahi service pops up for ROON like it does with iOS. Without the RC service we'll never get a DACP port number.

I checked this theory using a MAC mini on iTunes and sure enough a remote control server pops up on connection to SPS and gets a DACP port number. ROON cannot be providing the functionality!

**Comment by mikebrady** [comment]
Yeah, it might be worth asking them (ROON) -- I think they are fairly responsive.

**Comment by kiwi-ed** [comment]
Thanks. I've sent of an email so I'll keep you posted.

**Comment by kiwi-ed** [comment]
Hi Mike,

Had a message back from Roon and there is an issue somewhere. They are going to look into the problem and feed back some information that should enable us to make SPS connections. 

Cheers.

**Comment by mikebrady** [comment]
Good news indeed!
