### ISSUE TITLE
No bitperfect playback with unstable Soundcard clock?

### ISSUE THREAD

**Issue by DrCWO** [mikebrady/shairport-sync#1079]
Hello,
I have a very special setup I like to discuss.

As soundcard I use an ALSA Loopback device. The clock of this device can be tuned. At the other end of the ALSA Loopback device I do some processing and writing the result to a physical soundcard.

To keep the ALSA Loopback device and the soundcard in sync I measure the buffer size inside my processing queue and tune the clock of the ALSA Loopback device up and down as necessary.

My issue is that caused by this tuning Shairport-Sync sends zeros for a while and then restarts sending data.

For my use case I do not need synchronized playback with other speakers. I like to implement a scenario where Shairport-Sync does no time synchronization at all and just streams the data bit perfect (without inserting and dropping frames) to the ALSA Loopback device. So the speed the data is sent to the ALSA Loopback device is only determined by the speed oft he ALSA Loopback device.

Any idea how to achieve this? I would be really grateful for any help.
Best DrCWO

**Comment by mikebrady** [comment]
Thanks for the interesting post. Have you considered taking the output from Shairport Sync via the `pipe` backend? The audio comes out bit-perfect and is put into the pipe at the "right" time, which can be a (small) fixed amount ahead or after the synchrnonous time. Perhaps you can then take it into your workflow and process it there. And maybe this would also allow you to skip the ALSA loopback.

**Comment by DrCWO** [comment]
mikebrady,
thanks for your hint. Sorry to say but using the pipe is no option because there are other playback services like MPD or roon-bridge. Especially roon-bridge does't support piping and needs a real ALSA device :-(
