### ISSUE TITLE
[Linux] [3.3.7rc3] Build fails with custom CFLAGS

### ISSUE THREAD

**Issue by MichaIng** [mikebrady/shairport-sync#1081]
I just tried to compiled Shairport-Sync v3.3.7rc3 on Linux (Debian Bullseye) with custom CFLAGS:
```
apt install automake pkg-config make g++ libpopt-dev libconfig-dev libssl-dev libsoxr-dev libavahi-client-dev libasound2-dev libglib2.0-dev libmosquitto-dev
autoreconf -i -f
./configure --with-alsa --with-avahi --with-ssl=openssl --with-soxr --with-metadata --with-systemd --with-dbus-interface --with-mpris-interface --with-mqtt-client
make CFLAGS='-g0 -O3' CXXFLAGS='-g0 -O3'
```
which results in:
```
gcc -DHAVE_CONFIG_H -I.    -fno-common -Wno-multichar -Wall -Wextra -Wno-clobbered -Wno-psabi -pthread -DSYSCONFDIR=\"/usr/local/etc\"   -MT shairport.o -MD -MP -MF $depbase.Tpo -c -o shairport.o shairport.c &&\
mv -f $depbase.Tpo $depbase.Po
shairport.c:60:10: fatal error: glib.h: No such file or directory
   60 | #include <glib.h>
      |          ^~~~~~~~
compilation terminated.
```
- `CXXFLAGS` works fine.
- `CFLAGS`, also when passing an empty string, seems to override the required linker flags.

To compare with successful compilation:
```
gcc -DHAVE_CONFIG_H -I.    -fno-common -Wno-multichar -Wall -Wextra -Wno-clobbered -Wno-psabi -pthread -DSYSCONFDIR=\"/usr/local/etc\"  -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2 -MT shairport.o -MD -MP -MF $depbase.Tpo -c -o shairport.o shairport.c &&\
```

I didn't have this problem with 3.3.6, although didn't enable D-Bus or MQTT that time, so since no glib was used, probably the issue was just not apparent.

`sed -Ei 's/-g[0-9]? -O[0-9]?/-g0 -O3/g' Makefile` works fine instead to change those flags (`-g -O2`) directly inside the Makefile.

Not sure if this is a bug or expected? If the latter, it would be nice to allow overriding the default flags by appending any passed variable to the required/defaults. Debugging and optimising flags override previous ones so appending would work just fine in this particular case.

**Comment by mikebrady** [comment]
Thanks for the post. This also happens on Ubuntu 20.04. The following works, though, so might be worth trying on Bullseye:

```
$ autoreconf -fi
$ CFLAGS='-g0 -O3' CXXFLAGS='-g0 -O3' ./configure --with-alsa --with-avahi --with-ssl=openssl --with-soxr --with-metadata --with-systemd --with-dbus-interface --with-mpris-interface --with-mqtt-client
$ make
```

**Comment by MichaIng** [comment]
Many thanks, your solution looks much cleaner then altering the `Makefile` 👍.

Probably some change in the build tools:
- `autoconf` didn't get any significant change with Bullseye: https://metadata.ftp-master.debian.org/changelogs//main/a/autoconf/autoconf_2.69-11.1_changelog
- But `automake` did: https://metadata.ftp-master.debian.org/changelogs//main/a/automake-1.16/automake-1.16_1.16.2-4_changelog

I'll test it on Buster, so see if it is really something introduced with latest build tools, when I find time.
