### ISSUE TITLE
ALSA really small period_size

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#1082]
I just noticed that shairport-sync configures a really small ALSA period size as compared to MPD. Is this OK?

MPD
```
pi@rp3:~ $ cat /proc/asound/card2/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 5513
buffer_size: 22050
```

Shairport-sync
```
pi@rp3:~ $ cat /proc/asound/card2/pcm0p/sub0/hw_params
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 256
buffer_size: 262144
```

**Comment by mikebrady** [comment]
Thanks for the post. By default, Shairport Sync doesn't set the period size at all — it leaves it as it is. This seemed to be the most prudent course of action, given that there are so many different devices out there. It can be set, if desired, using a configuration file setting.

**Comment by moodeaudio** [comment]
Ah yes, I see the conf settings.
