### ISSUE TITLE
shairport-sync -v  don't show any verbose messages in console

### ISSUE THREAD

**Issue by Baffless** [mikebrady/shairport-sync#1084]
Hi,
I don't understand why i get no verbose info in console after running shairport-sync -v.  Shairport works fine, just info is not printed on the screen. Some years ago i remember it worked as expected. I tried enabling verbose in config file, but no changes. What i am missing?

**Comment by mikebrady** [comment]
Thanks for the post. Yeah, it’s changed somewhat. By default, logging goes to the system log. To get it to appear in the console instead, add `-u`. Thus, for example, `-vu` Would give level 1 verbosity logs on the console.

**Comment by Baffless** [comment]
Thanks for response. 
I am trying to debug the problem which is similar to issue [#686](https://github.com/mikebrady/shairport-sync/issues/686) crackling broken signal. I just copied some info from log file. Can you confirm that it is the network problem from that file? Drift tolerance and resync time have some effect for a while but doesn't help. have tried different routers, use lan cable from router to pc, but still the same. No i am thinking about some wifi interference pollution problems in my house...
[log.txt](https://github.com/mikebrady/shairport-sync/files/5402134/log.txt)

**Comment by mikebrady** [comment]
Well, it's really quite different from #686 as you are using the Jack back end. The log file doesn't really indicate much, TBH, but there is nothing in it that would make me worry about the network. 

If it was possible, it might be worth getting everything working with a regular ALSA back end, and then move over to Jack. In this way, you could perhaps narrow down the source of the problem.

**Comment by Baffless** [comment]
The problem i can not get it working properly with alsa. But maybe my expectations are wrong. On music  signal i can't hear anything wrong. But if i feed sine signal than the crackling is very audible.(default drift tolerance) Most audible is when i set 20khz sine signal full scale. The signal itself i can't hear at my age, but crackling is very strong. It is the same for alsa and 
![Screenshot_2020-10-19_14-08-04 2](https://user-images.githubusercontent.com/70075090/96494716-6a4bc900-124f-11eb-9a88-e6d75638bdd4.png)
for jack output. Just for jack output i have ability for easy measurement of spectrum in jack. Which jumps a lot when crackling starts. I think if soxr is trying to fix sync issues the errors should be below -100db in spectral domain. Or i am wrong for this shairport case? Crackling is not constant. Sometime i have to wait 5min to get this, kind of random appearance. Another strange thing that i don't see any increase for CPU usage then soxr is enabled. Intel NUC i5 maybe is powerful enough not to see any CPU increase? Have no clue..
What would be a reliable debug setup? Now i see that it is difficult for me to explain properly the problem. Measurement based debugging should be somehow possible i hope. 
and i believe that there could be more users with such problems just because music listening has no artefacts. they are masked with music. What do you think about these artefact?
[logalsa.txt](https://github.com/mikebrady/shairport-sync/files/5403685/logalsa.txt)

Regards
Rytis

**Comment by mikebrady** [comment]
Thanks for the interesting clarifications, Rytis. I think your expectations are a bit high, TBH. When playing music or speech the distortion is masked, but if you run a sine wave into it, you can hear it readily with basic interpolation and much more faintly with soxr interpolation. If you enable statistics, you'll get an idea of how much interpolation is going on.

The only really cure is really good quality resampling, which I have been working on, but haven't finished yet. The difficulty is that it should work on a very low-powered machine.

Just thinking about your 20kHz sample. Given that the sample rate is 44.1 kHz, is it possible that you are encountering an artefact due to filtering up there. (I don't think I ever heard a 20kHz signal, TBH.)

I might come back to you when my resampling is ready -- it would be great to evaluate it!

**Comment by Baffless** [comment]
only one problem here that i don't hear much difference if any between basic and soxr interpolation. I will check tomorrow more. yes evaluate i can.I have kind off a gift finding a problems in many apps constantly:) As engineer i can say that fundamentally there is no obstacles to do good resampling, but to code it and in efficient why is another story where i have no knowledge. yes i would like to help in testing, you can write me. if i can help in anyway of speeding the progress towards quality i am in!  Just in case you didn't know take a look at this guy work about resampling. his codes are very impressive and efficient.  zita resampler and other stuff is impressive work! https://kokkinizita.linuxaudio.org/linuxaudio/

**Comment by Baffless** [comment]
Hello again,
Don’t want to bother but, just if this can be answered in two sentences. I read about all these GPL licenses  and can’t understand them properly. If i use your shairport-sync in a system which can become commercial some day. Can i do that? i see many systems with open source software used inside. Are there any requirements i have to know about?  i respect your work very much and want to do everything in legal way:)  i am working on a system which sounds really good:) www.baffless.com <http://www.baffless.com/>

Regards 
Rytis Smolskas

**Comment by Baffless** [comment]
Just made some digital waveform records of the problem. Which tells that it is a little different than we thought. Alsa recorded over alsaloopback. 20kHz sine signal with peak amplitude -0.1dBFs The pictures are for default drift_tolerance and resync_threshold settings. There are dropouts of about 342 samples in lenght for both alsa and jack cases. Interesting that these dropouts are only the reduction in amplitude about -20dB. Increasing  drift_tolerance takes more time to appear, but looks like never gone, probably just less frequent. Disabling resync_treshold cures this for alsa, but not for jack. Could it be something in shairport code? Or my machine is a crap?:)
And the crazy part i hear no problems on music signal without A-B testing.
![dropouts_about_342samples_lenght_-20db](https://user-images.githubusercontent.com/70075090/96593794-9409fc00-12f2-11eb-834a-6bff13450e07.JPG)
![jack_alsa_glitches](https://user-images.githubusercontent.com/70075090/96593804-979d8300-12f2-11eb-8ffb-f5784c994b54.JPG)

**Comment by mikebrady** [comment]
Thanks -- I'll have to think about the significance of those traces...

**Comment by Baffless** [comment]
Little update.
I went to my friend to test different setup with shairport-sync. Still same behaviour. He has also AirPort Express, which is apple's implementation for airplay receiver . Guess what. Same crackling sound for apple to apple streaming case! Unbelievable how this can be?...So decided to look how things look with real music signals. Found some track where crackling can be heard.But the pattern of the problem looks way different compared to sine signal. Looks like clipping behaviour and only few samples are dropped. With minimum volume lowering this disappears. And with sine signal 20khz feed lowering volume does't help. There is some strange things going on there. Hope it is interesting. Any thoughts would be very welcome.

![nogliches_lower volume](https://user-images.githubusercontent.com/70075090/96976145-2513e980-1524-11eb-98e4-36f6015435f1.JPG)
![gliches_music_signal](https://user-images.githubusercontent.com/70075090/96976149-26451680-1524-11eb-9b73-a4497852587d.JPG)

**Comment by mikebrady** [comment]
This is really interesting. How certain are you that your inputs are "true"? AirPlay uses Apple Lossless encoding (ALAC), so it is supposed to be lossless end-to-end. Are you supplying the audio to it in a way that is definitely lossless?

**Comment by Baffless** [comment]
For sine signal i generate it with REW. I have checked and it looks correct.
Check the file for yourself, play this file and you should see what it is like.
https://www.icloud.com/iclouddrive/0UPle-HHTj-avJkSgOA2ECDbA#Sine_20000_44k_Float_LR

**Comment by mikebrady** [comment]
Thanks. I think I see what you mean about the clipping, which is really surprising. I'll need to check what's going on there.

**Comment by mikebrady** [comment]
Just wondering if you would go to the trouble of building Shairport Sync with Apple ALAC support. This uses Apple's own sample ALAC decoder rather than one built by David Hammerton. I guess it is possible that the clipping might be a decoder issue, though I haven't come across any reason to believe there is any issue with the Hammerton decoder. Therefore it might be just a waste of time.

To do it, you need to build and install the ALAC library -- I have one [here](https://github.com/mikebrady/alac), and then build Shairport Sync with the `--with-apple-alac` configure flag added.

**Comment by Baffless** [comment]
Just tried. Nothing changes. Everything the same.
[with_alac.txt](https://github.com/mikebrady/shairport-sync/files/5430631/with_alac.txt)

**Comment by mikebrady** [comment]
Thanks for that. I'll have to check my code very carefully.

**Comment by mikebrady** [comment]
Again, can just I check that you're not inadvertently using any of the effects in iTunes/Music/iOS. In particular, the Sound Check, Sound Enhancer and Equalizers are off and that you are not raising the output level in the Preamp part of the Equalizer on iTunes/Music? All these can these cause clipping.

**Comment by Baffless** [comment]
I am pretty sure there are no any EQ or other preamp part. For 20khz signal i can stream it with -20dB attenuation and still hear problem just more silent. It is a mystery in some way. Today i can't reproduce problem with jack backend(there where changes in jack setting last days on my linux machine). But i can reproduce problem with alsa backend. Mac or iphone->shairport(ALAC)->hw:card->headphones. This week i will bring home airport express apple native receiver and look one more time how things going on there. I will report how things are going.

**Comment by Baffless** [comment]
Maybe not critical, but there is definitely something going on. Streaming directly from apple product to apple, ugly crackling sound is there. 
**Summary for apple to apple case:**
1. For sine signal it doesn't depend on amplitude. It is always there
2.For sine signal it doesn't depend on frequency. It is always there
3.For music signal i can't tell if the problem exists. If something exists it is not audible.(without taping into i2S signal before dac can't tell)

**Summary for shairport-sync case:**
1. For sine signal it doesn't depend on amplitude with no friendly shairport-sync settings.
2.For sine signal it doesn't depend on frequency. with no friendly shairport-sync settings.
3.For music signal problem exist(one or two samples drop in my case) with no friendly shairport-sync settings.(Music signal has to have 0dBFs samples and be streamed at full volume ).So in reality even if someone has this problem, probably don't know.
4. I don't here or measure any problems even after long test times(~up to one hour) with shairport-sync settings drift_tolerance_in_seconds = 0.05 resync_threshold_in_seconds = 0.1 output_backend = "jack". 
5. I get problems after 5 min or so with drift_tolerance_in_seconds = 0.05 resync_threshold_in_seconds = 0.1 output_backend = "alsa"

Hope info will help someone someday. This is my experience. So your's could be different. If this is a bug or what i have no idea. Looks like i have working setup(hope it stays like this for a while:)), so i am going to forget this mystery.

**Comment by Baffless** [comment]
Just quick question. Does shairport-sync sox resampling takes care about clipping prevention? Because resampling process by itself can increase peak samples, so they can go above 0dB after resampling.

**Comment by mikebrady** [comment]
Hmm, I didn’t know that, and Shairport Sync doesn’t ask for any special treatment regarding clipping.

**Comment by Baffless** [comment]
I thought the resampler takes care about this, but googled a little and looks like not. https://izotope-rx.livejournal.com/4971.html

**Comment by mikebrady** [comment]
Very interesting, thanks. I wonder if the SoX resampler e.g. clamps overshoots?

**Comment by Baffless** [comment]
don't know, but believe yes.it's just the nature of how the resampler works. Usually in audio mastering world  normalising is done a little below 0dB for such reasons.
