### ISSUE TITLE
shairport-sync stopped working with "Music" on macOS 10.15.7

### ISSUE THREAD

**Issue by SomeBdyElse** [mikebrady/shairport-sync#1085]
After updating my MacBook Pro to macOS 10.15.7, I cannot use my shairport-sync pi as an Airplay target in "Music " (1.0.6.10) any more. The option still appears in the Airplay target list, but once i click on it, the checkbox stays disabled (but checked). After some time, a message appears: 

> The AirPlay device “[Devicename]” cannot be found on your network. Please verify your network settings and AirPlay configuration or select another device.

Playback from iOS is still fine. 

shairtport-sync version: `3.3.7rc3-OpenSSL-Avahi-ALSA-sysconfdir:/usr/local/etc`.

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync 3.3.7rc3 is working fine both on my iMac and on a MacBook Pro, running the same version of macOS and the same version of the Music app.

**Comment by SomeBdyElse** [comment]
You were right. After I deinstalled the VPN client "Checkpoint Endpoint Security", my AirPlay started working again!
