### ISSUE TITLE
Shairport-sync instance (docker in container) stops after a few hours

### ISSUE THREAD

**Issue by brvdboss** [mikebrady/shairport-sync#1091]
Hello,

I've been trying to set up something similar to what's described in this issue: https://github.com/mikebrady/shairport-sync/issues/701

The main difference in my setup:
- running it in a docker container (see https://hub.docker.com/r/brvdboss/shairstream and https://github.com/brvdboss/ShairStream)
- Using the feature to output to from shairport-sync to a pipe and using that as the input to create an mp3 stream to publish on icecast

The reason I'm doing this is, is to provide this as an mp3 stream which I can select in Roon as a source.  The docker container is run on a device without any audio hardware (I want to use) and it didn't seem possible to create the also loopback device without elevated privileges. So I went the pipe-path.

Everything is working great (4-5 seconds delay, but that's to be expected). However, after an unspecified amount of time shairport-sync shuts down. Typically between 6 to 30 hours, regardless if I have been using it or not.  I haven't been able to figure out what's causing it.

**Edit:  I now observed other situations where this wasn't the case as well**
~~The last 3 lines of the log seem to be the same every time (verbosity level 3 -vvv) Included some extra lines to show the time difference:~~
```
Oct 30 10:46:41 Phone daemon.debug : 0.000009597 "rtsp.c:1534"pipe: done.  
Oct 30 10:46:41 Phone daemon.debug : 0.000049777 "mpris-service.c:167" Build metadata  
Oct 30 10:46:41 Phone daemon.debug : 0.000036877 "rtsp.c:1606"hub: done.
Oct 31 06:24:35 Phone daemon.debug :70674.196671903 "mdns_avahi.c:283" avahi: client failure: Daemon connection failed
Oct 31 06:24:35 Phone daemon.debug : 0.000023909 "mdns_avahi.c:286" avahi client -- we have been disconnected, so let's reconnect.
Oct 31 06:24:35 Phone daemon.debug : 0.000660628 "mdns_avahi.c:311" avahi: received AVAHI_CLIENT_CONNECTING
```

I've observed it quit using the standard docker container as well which I just deployed and after a few hours/days it also shuts down automatically.  My docker host is a QNAP NAS (TVS-882BR to be exact)

shairport-sync version:
```
/ # shairport-sync -V 
3.3.7rc3-alac-mbedTLS-Avahi-ALSA-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc
```

Any reason what might be causing this? As the shairport-sync instance isn't the main process of this container it doesn't restart automatically. Yet even if it was, it doesn't look like tit should behave like that?

Any suggestions or ideas are highly appreciated!

**Comment by mikebrady** [comment]
Thanks for the post. I'm afraid that I do not know why `avahi` is disconnecting -- that is an unusual occurrence and dissent happen on my docker installations (running on Raspberry Pis for the most part). Is it possible, I wonder (guessing wildly!) that something peculiar is happening in the host? For example, is the host dropping its IP number and getting a new one, or some such event?

**Comment by brvdboss** [comment]
Thanks for the feedback.  I can't find anything out of the ordinary immediately.

I do find one log entry like this:
`[689232.930701] shairport-sync[1696]: segfault at 9 ip 00007f765ce053c9 sp 00007f765c4fd4c0 error 4 in libavahi-client.so.3.2.9[7f765ce04000+8000]`
But I can't pinpoint it to the exact time of what I was doing then so not sure if this has anything to do with it.
Frankly, I'm not even sure if the avahi failure is even related.

I do run the docker container in a bridged mode. I don't know how you have yours configured?

I'll keep an eye on it and try to gather more information.  The Linux version running on the QNAP is somewhat mysterious at times. It does run its own avahi daemon, but I don't think those are interfering.  I'm gonna keep an eye on it and see if I can dig up more information.

In the meanwhile, I do have Raspberry Pi laying around I can use to set up another instance and see if I can reproduce the problem.  This will probably for next weekend.  I'll keep this issue updated with my findings.

**Comment by mikebrady** [comment]
Thanks. That would be very useful.

**Comment by brvdboss** [comment]
Short update:  I've had it running on a Raspberry Pi for almost 40 hours now without it shutting down on me. Which is longer than any attempt on my qnap.  So for now I'll assume that it's related to the docker setup on my qnap and not related to the shairport-sync docker container.  (One is amd64 and the other one arm, but I doubt that would be the root cause in this case)

I'll close this issue, if I find something relevant to this project I'll report back here.  Thanks for the help in searching for the root cause of the issue
