### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by applepiuser** [mikebrady/shairport-sync#1095]
have issues with headphone jack no luck fallowed the instructions  #741

**Comment by mikebrady** [comment]
Please take a look at the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page and then, if the problem persists, [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md).
