### ISSUE TITLE
App doesn't start on macOS Catalina 10.15.7 due to the Pulseaudio issue

### ISSUE THREAD

**Issue by Specyk** [mikebrady/shairport-sync#1096]
Hi! I installed Shairport-Sync with Homebrew on my MacBook Pro, macOS Catalina 10.15.7 (newest). When i try to launch the app I get the following message:

> ╰─ W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
> pa context is not good -- the error message "Connection refused".
> zsh: abort      shairport-sync

I upgraded homebrew. Please help!

**Comment by mikebrady** [comment]
Sorry, I don't have anything to offer here -- maybe some other contributor can help. There may be some suggestions in the open and closed issues here.

**Comment by mikeskk** [comment]
@Specyk Having the exact same issue on macOS Big Sur 11.0.1, were you able to resolve the issue?

**Comment by Schlaubischlump** [comment]
I have the same problem, even when compiling from source. MacOS Catalina 10.15.7

```
         0.000325061 "shairport.c:461" looking for configuration file at full path "/usr/local/etc/shairport-sync/shairport-sync.conf"
         0.001587706 "shairport.c:1729" Started!
         0.000087079 "shairport.c:1756" software version: "3.3.8d6-libdaemon-OpenSSL-dns_sd-ao-pa-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc/shairport-sync"
         0.000007048 "shairport.c:1762" log verbosity is 3.
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
         0.064034439 "audio_pa.c:144" *fatal error: pa context is not good -- the error message "Connection refused".
         0.000078680 "shairport.c:1424" emergency exit
```

**Comment by jansendotsh** [comment]
I guess the only thing that might come of this issue report would be a different default on Darwin-based systems but this isn't a bug. You just gotta configure the config typically at `/usr/local/etc/shairport-sync/shairport-sync.conf` to uncomment `output-backend` and set it to `ao`.
