### ISSUE TITLE
Could not acquire an MPRIS interface on read only Raspberry OS

### ISSUE THREAD

**Issue by giovi321** [mikebrady/shairport-sync#1099]
Hi all,
I keep getting the following error when trying to start shairport-sync 3.3.5-1~bpo10+1 (installed through apt) on Raspberry OS Linux 5.4.72-v7+:
`Could not acquire an MPRIS interface named "org.mpris.MediaPlayer2.ShairportSync.i1175" on the system bus.`
I can usually fix the problem by issuing:
```
systemctl daemon-reload
systemctl restart shairport-sync
```
I had a similar issue with the following error, maybe it could hbe of similar nature?
`Could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i1007" on the system bus.`
that I have solved by copying the file `scripts/shairport-sync-dbus-policy.conf` to `/etc/dbus-1/system.d`.

**Comment by mikebrady** [comment]
Thanks for the post. Yes, it could be a similar issue with the installation process. If you can find the equivalent MPRIS policy configuration file and copy it to the same place, it should fix the problem.
