### ISSUE TITLE
Shairport-sync, airplay v1 or v2 (raop or not)

### ISSUE THREAD

**Issue by marcokeur** [mikebrady/shairport-sync#110]
Hi guys,

Awesome work on shairport-sync. I've tried to get it working with one of the airplay modules in NodeJS because i got the impression that shairport-sync supports Airplay v2. But the source code tells me that it advertises it self with RAOP which, in my belive, is still Airplay v1. The nodeJS client modules known to me don't support RAOP anymore but just Airplay (so they look for the mdns advertisement 'airplay').

So, i'm a little confused, is shairport-sync Airplay v1 (raop) or v2? Or just a mix(?) of them? Any plans on supporting v2?

Thanks,
Marco

**Comment by mikebrady** [comment]
Hi Marco. Thanks for the post. There's quite a lot of confusion about this. Let me give you my understanding of it. Apple introduced a thing called AirTunes in 2004 for playing audio from iTunes to Airport Express devices. The protocol was advertised in `mdns` with the string `_raop._tcp`. This protocol was called AirTunes.

In 2010 Apple introduced AirPlay which added video and graphics. To support this, they introduced another protocol that advertises itself in `mdns` with the string `_airplay._tcp`. At the same time, they revised the `_raop._tcp` protocol to give it synchronised output capability. This enhanced `_raop._tcp` protocol is informally called "AirTunes Version 2" and that is what Shairport Sync supports. To the best of my knowledge, there has never been a Version 2 of the `_airplay._tcp` protocol. I have seen references to "AirTunes V2", which is fine, but the term "AirPlay V2" is, to me, ambiguous. I understand it to mean "The version of AirTunes what was introduced when AirPlay was introduced by Apple in 2010."

Does that correspond with your understanding of it?

BTW, I have no plans to support the `_airplay._tcp` protocols in Shairport Sync at present.

**Comment by marcokeur** [comment]
Hi Mike, thanks for your quick reply! I didn't know that raop was enhanced at one point. Some explanation of what i'm trying to achieve; My NodeJS home automation platform needs to push audio to multiple endpoints. I already have 2 raspberries running Shairpoint-sync which works perfectly with my iPhone.

So the search was on for a NodeJS module that could talk to Shairpoint-sync. I didn't find anything that looks for the _raop._tcp protocol, only for _airplay._tcp. I thought that synchronistation support in the server meant that it was running _airplay._tcp so i didn't quite understand why it didn't work.

Now; i think i need to create a NodeJS module that can speak to Shairpoint-sync. Do you have any more documentation on the protocol that is used?

**Comment by mikebrady** [comment]
The documentation is scarce, TBH.

The links I've found useful are: http://git.zx2c4.com/Airtunes2/about/ and, especially, http://nto.github.io/AirPlay.html.
