### ISSUE TITLE
Audio slows and distorts after 10 seconds when output_backend is pipe 

### ISSUE THREAD

**Issue by gramtech** [mikebrady/shairport-sync#1100]
Hi

I am having an issue when the output_backend is set to pipe. 

The audio is fine for ~10 seconds and then slows down and gets a bit crackled.

What I am trying to acheive
- build a snapcast server with snapserver and mopidy as well as apple music airplay functionality

I have tried the following:
- Run in a vm
- Running on Raspberry Pi 4
- installed from package using apt
- built and installed from source using
`./configure --sysconfdir=/etc --with-alsa --with-pipe --with-configfiles --with-apple-alac --with-pa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd`

- shairport-sync works OK when output_backend is ALSA but not via pipe to snapserver
- snapserver does work fine however when Mopidy is writing to the same pipe

- Tried pushing music from iPhone and from a Mac (over wireless and wired network)
- The VM i mentioned above was on the mac I tried pushing music from. 
- The Pi4 has always been wired.

- I have also tried tweaking many setting including trying to get the bit rates etc matched in case that was the issue.

I am at a loss and pretty frustrated as I would very much like this to work.

Please help.

Thanks
G

**Comment by mikebrady** [comment]
Thanks for the post. Could I suggest checking whether output from the pipe works when it is connected through `aplay` rather than SnapCast? Then you can see whether the problem is a Shairport Stnc problem or a SnapCast one.
