### ISSUE TITLE
Pulsaudio connection refused and pisound external soundcard

### ISSUE THREAD

**Issue by magino50** [mikebrady/shairport-sync#1102]
Hi all,

I tried to setup Shairport with "pisound": https://community.blokas.io/t/shairport-with-pisound/2427
But there is no sound coming out if I work with output_device = "hw:pisound".

The moderator of pisound wrote:
> Hi, it could be using an incompatible sampling rate by default. Pisound natively supports 48000, 96000 and 192000 rates. Ideally, the software should be configured to use one of those, or if that’s not possible, some software resampling stage should be set up.

Now, I know this issue was once here, that pisound only accepts 48000 rate.
So I tried with pa backend as someone sugggested here, but when I activate it via the conf file, I get this error and shairport doesn't even start. 

```
patch@patchbox:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-11-19 17:28:00 GMT; 4min 27s ago
  Process: 28047 ExecStart=/usr/local/bin/shairport-sync (code=exited, status=1/FAILURE)
 Main PID: 28047 (code=exited, status=1/FAILURE)

Nov 19 17:28:00 patchbox systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Nov 19 17:28:00 patchbox shairport-sync[28047]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
Nov 19 17:28:00 patchbox shairport-sync[28047]: fatal error: failed to connect to the pulseaudio context -- the error message is "Connection refused".
Nov 19 17:28:00 patchbox systemd[1]: shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 17:28:00 patchbox systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
```

Now the funny thing is, I installed an older shairport and that worked earlier, but the delay was severe, ranging from 3-4 seconds and I wanted to try it here.
Hope there is some way to find out what the problem is, thank you!

Best

Edit:
When I go over hw:pisound, I'm getting this message when I connect the Airport (Mac) to Shairport in the status messages:

```
 patch@patchbox:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-11-19 18:08:47 GMT; 18s ago
 Main PID: 28834 (shairport-sync)
    Tasks: 13 (limit: 2199)
   Memory: 3.0M
   CGroup: /system.slice/shairport-sync.service
           └─28834 /usr/local/bin/shairport-sync

Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
Nov 19 18:09:05 patchbox shairport-sync[28834]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:pisound".
```

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync requires an output device with a rate of 44,100 frames per second or a multiple. Some users have used the resampling facilities in ALSA to output to devices with different rates. 

In your situation it is very difficult to see what might be the problem, but it looks like PulseAudio isn’t working properly.

**Comment by magino50** [comment]
Hi thanks for the answer? What do you recommend? Should I re-install pulseaudio? Im quite a beginner in this, would be great to have a hint :)

**Comment by magino50** [comment]
So, at Pisound they told me I should try to do it over the JACK connection, otherwise there seems to be no other way :(

**Comment by magino50** [comment]
Hi, now I managed to do it via Alsa connecting hw:pisound!
Jack was occupied, that's why no sound came through.
However, now I have a lot of Stutter, I tried it with audio backend buffer, but changing the value here, makes the stutter even more. 
audio_backend_buffer_desired_length = 19845;

This is what I get as status rightnow:
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-11-25 22:23:27 GMT; 2min 37s ago
 Main PID: 28419 (shairport-sync)
    Tasks: 13 (limit: 2199)
   Memory: 3.1M
   CGroup: /system.slice/shairport-sync.service
           └─28419 /usr/local/bin/shairport-sync

Nov 25 22:23:27 patchbox systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Nov 25 22:23:33 patchbox shairport-sync[28419]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
Nov 25 22:23:33 patchbox shairport-sync[28419]: warning: Speed requested: 44100. Speed available: 48000.


Thanks for any hint!

**Comment by mikebrady** [comment]
Thanks. The problem is still that the output device doesn't do 44100 or multiple thereof, which is unfortunate. It would be worth checking to see if there is an ALSA device called `plughw:pisound`.  If so, it would be the `hw:pisound` device but with rate and formats conversions provided by ALSA. In other words, it might be able to take audio from Shairport Sync at 44,100 fps and convert it to the 48,000 fps rate required by the PiSound device.

Use the command `$ aplay -L` to list the device names. This is what I get on a default Raspberry Pi 4B running Raspberry Pi OS:
```
pi@raspberryPi4B:~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
dsnoop:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample snooping device
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
pi@raspberryPi4B:~ $ 
```
You can see both the `hw:...` device without conversions and the `plughw:...` device with conversions. It's certainly worth trying.
