### ISSUE TITLE
Shairport config files for password and name not working

### ISSUE THREAD

**Issue by TheBushMaster** [mikebrady/shairport-sync#1104]
I don’t know if I’m doing something wrong but I go into the shairport file with the password and all the other settings and I edited it and took the // out in the places I needed to but it seems to not work. When I reboot, it’s exactly the same, no password required even though I enabled the password. I’m really confused and could use some help. I’m about to give up and call it a day.

**Comment by RUGMJ7443** [comment]
Could I see your config fule I might be able to help 😄

**Comment by mikebrady** [comment]
It might be that Shairport Sync is looking in a different place to what you are expecting.

Could you run `$ shairport-sync -V` and post the rest here, please? It will tell us what directory Shairport Sync will look in.

**Comment by TheBushMaster** [comment]
So I ran that and it gave me this: "3.3.7rc3-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/usr/local/etc"

**Comment by TheBushMaster** [comment]
Here is some of the config file as well:![Uploading 100682623...]

**Comment by mikebrady** [comment]
Thanks. That means that the configuration file will be looked for at:
`/usr/local/etc/shairport-sync.conf`.

Can you post its contents here please?

**Comment by TheBushMaster** [comment]
ok, so i got into that file and I relized I had been puting .sample on the end of it. So the Password works now but I ran into another problem. The audio won't come out of the headphone jack. Do you still wana look at the config file or do you have any suggestions?

**Comment by mikebrady** [comment]
Yeah, the config file would be worth seeing. Also, it might be worth checking through the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) and [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) pages.

**Comment by TheBushMaster** [comment]
// General Settings
general =
{
        name = "%h"; // This means "Hostname" -- see below. This is the name th$
//              The default is "Hostname" -- i.e. the machine's hostname with t$
//              You can use the following substitutions:
//                              %h for the hostname,
//                              %H for the Hostname (i.e. with first letter cap$
//                              %v for the version number, e.g. 3.0 and
//                              %V for the full version string, e.g. 3.3-OpenSS$
//              Overall length can not exceed 50 characters. Example: "Shairpor$
        password = "secret"; // leave this commented out if you don't want to r$
---------------------------------------------------------------------------------------
and then everything else is commented out until you get to here:
---------------------------------------------------------------------------------------
alsa =
{
        output_device = "default"; // the name of the alsa output device. Use "shairport-$
        mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volu$
//      mixer_device = "default"; // the mixer_device default is whatever the output_devi$
--------------------------------------------------------------------------------------------------------------------------
everything below this is commented out.

**Comment by TheBushMaster** [comment]
Well I ended up figuring it out by changing the output device to wh:Headphone which was previously wh:0. I thought wh:0 was the correct output for the headphones but I guess not. Anyway, thanks for the help.
