### ISSUE TITLE
ubuntu install doesn't show up

### ISSUE THREAD

**Issue by karlzre** [mikebrady/shairport-sync#1105]
Hi, 

I just installed shairport-sync on my ubunutu pc.
the goal is to stream to the internal speakers.

the linux is connected to the network trough ethernet enp2s0
Service looks to run but i cant find it on my macbook air.

I'm runing ubuntu 18.04

could you help me to make it working.
Thx
```
$ shairport-sync -v
alsa output device name is "default".
Version: "3.1.7-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
daemon pid file is "/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Administrateur-iMac".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_playback_switch_for_mute is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metadata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
convolution is 0.
convolution IR file is "(null)"
convolution max length 8192
convolution gain is 0.000000
loudness is 0.
loudness reference level is -20.000000
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'FE0AEEEA818A@Administrateur-iMac' successfully added.
```

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest that you take a look at the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page.

At a guess, there is some kind of network issue:

1. Is there a firewall operating somewhere?
2. Is there more than one connection from the Ubuntu machine to the local network?
3. Is one of the machines on a VPN?

**Comment by karlzre** [comment]
Hi Mike, 
Thank you for you answer.

1 Is there a firewall operating somewhere?
 sudo ufw status
[sudo] password for administrateur:
Status: inactive

2. Is there more than one connection from the Ubuntu machine to the local network?
no wifi is disabled.

 ifconfig
enp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.136  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::abd1:b481:4e72:4466  prefixlen 64  scopeid 0x20<link>
        ether 3c:07:54:7a:27:2c  txqueuelen 1000  (Ethernet)
        RX packets 1457227  bytes 724176412 (724.1 MB)
        RX errors 0  dropped 143411  overruns 0  frame 0
        TX packets 998986  bytes 151731991 (151.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1816757  bytes 471732313 (471.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1816757  bytes 471732313 (471.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

3.Is one of the machines on a VPN?
No, ubuntu is on the lan cable, mac is on the wifi.
I can see apple tv on the same lan .

which port do you use for shairport-sync ?
Maybe i have a port conflict with another app on the server ?

**Comment by karlzre** [comment]
My port 5005 is already used by another application, may this impact ?
Can i change that port ?

**Comment by karlzre** [comment]
Just changed the port of the other app to 5006, i still can't see the linux pc from my macbook

**Comment by mikebrady** [comment]
Thanks. Shairport Sync listens on port 5000 for TCP connections and uses three ports from 6000 upwards for UDP connections.

So, I suggest you update to the latest version of Shairport Sync, version 3.3.7, in case your problems are caused by some long-since-fixed bug. There is a guide at [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) and you should pay particular attention to removing old startup and service scripts, as described therein. 

Second, it does seem as if there is a problem between the Ubuntu device and your Mac. You can use `avahi-browse` on Ubuntu to check if the AirPlay service (`_raop._tcp`) is being advertised and you can use `"Discovery"` from TildeSoft on Mac or iOS to see if the service advertisement is being received..

**Comment by karlzre** [comment]
Hi, 

I just saw this from avahi-browser:

  lo IPv4 FE0AEEEA818A@Administrateur-iMac              AirTunes Remote Audio local

Does that mean that it's running on the loopback interface ?

**Comment by karlzre** [comment]
Discovery on my mac can see the linux pc.

I saw that i can see the linux in the settings/sound/output.

But not in then airplay in the mac osx taskbar.

then i think the issue was a pebcak.
Thx for your support

**Comment by mikebrady** [comment]
> Hi,
> 
> I just saw this from avahi-browser:
> 
> ```
>   lo IPv4 FE0AEEEA818A@Administrateur-iMac              AirTunes Remote Audio local
> ```
> 
> Does that mean that it's running on the loopback interface ?

I don't get that, no. Only on the active port , in my case `wlan0`. What command line arguments did you use?

**Comment by mikebrady** [comment]
> Discovery on my mac can see the linux pc.
> 
> I saw that i can see the linux in the settings/sound/output.
> 
> But not in then airplay in the mac osx taskbar.
> 
> then i think the issue was a pebcak.
> Thx for your support

Thanks. What's "pebcak"?

**Comment by p3ck** [comment]
pebcak = problem exists between chair and keyboard :-)

**Comment by mikebrady** [comment]
Haha — you learn something new every day!
