### ISSUE TITLE
output not listed on big sur vm

### ISSUE THREAD

**Issue by Hello71** [mikebrady/shairport-sync#1106]
I'm trying to use shairport-sync to output audio from a macOS VM, but no matter what I try, no outputs are listed in the Sound preferences panel. For network connections, I have tried combinations of:

- bridge macvtap + bridge macvlan
- separate ordinary tap (two interfaces)
- vepa macvtap + separate physical interface to same switch, allmulticast on or off
- ipv6 on or off
- static ip or dhcp
- explicitly specified interface or 0.0.0.0/::
- avahi or tinysvcmdns

With most configurations, IPv4 and/or IPv6 addresses are visible in both Discovery as well as `dns-sd -B` and can be queried with `dns-sd -L`, and the addresses can be successfully pinged, but none of them show up as a sound output. I have verified that the macOS firewall is off, and there appears to be no useful information in the default Console output. shairport-sync also has no (additional) output, since macOS never initiates a connection.

**Comment by Hello71** [comment]
I also tested an iPad which works fine (with shairport-sync set to eth0).

**Comment by mikebrady** [comment]
Thanks for the post. Perhaps you would take a look at the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) guide and the [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) page. What is hosting the macOS VM -- is it VMWare, Parallels, something else? You're not giving us much to go on... It's good that the iPad can see it -- that's hopeful.

**Comment by Hello71** [comment]
yes, I have already read those documents. I am using a modified https://github.com/kholia/OSX-KVM/ with virtio networking, but I also tried vmxnet3, e1000e, and rtl8139 since there were some bugs with virtio-net on Catalina, but the former had no difference and the latter two have some driver/emulation bugs and show as null mac address and unconnectable.

**Comment by mikebrady** [comment]
Thanks for that. And what about the Shairport Sync setup?

**Comment by Hello71** [comment]
I tested various configurations, for example:

> 3.3.7-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/usr/local/etc

but also without metadata and with tinysvcmdns instead (shairport-sync issues errors and is not successfully published)

**Comment by mikebrady** [comment]
Thanks. Tinysvcmdns is IPv4 only and is doesn't have some features needed to remote-control discovery.

Cold you try using `avahi-browse` on the Shairport Sync end to check that it is advertising properly?

**Comment by Hello71** [comment]
yes, I have

```
+   eth0 IPv6 97E68F7BD1E6@shairport-sync                   _raop._tcp           local
+   eth0 IPv4 97E68F7BD1E6@shairport-sync                   _raop._tcp           local
+     lo IPv4 97E68F7BD1E6@shairport-sync                   _raop._tcp           local
```

along with other services. with the macvlan/macvtap active, there are more entries for those interfaces (unless interface is explicitly specified).

**Comment by mikebrady** [comment]
Thanks. If you happen to have the Music app in Catalina, does it show the Shairport Sync service?

<img width="824" alt="image" src="https://user-images.githubusercontent.com/4265913/101183144-ffabec80-3646-11eb-9271-b73b428e4b7d.png">

**Comment by Hello71** [comment]
I found it possible to play from Music in both Catalina and Big Sur in at least some network configurations. Additionally, in Catalina, shairport-sync is displayed and can be selected in Sound, but has no effect (no connection is made).

I decided to give up and use PCI passthrough though, so I probably won't be pursuing this path further. Thanks for the help though.

**Comment by mikebrady** [comment]
Thanks for the feedback. I'll close the issue. Please feel free to open another if the need arises.
