### ISSUE TITLE
Possible SYN flooding on port 5000.

### ISSUE THREAD

**Issue by PieGuy314** [mikebrady/shairport-sync#1107]
Upgraded today.

[2003797.120215] TCP: request_sock_TCP: Possible SYN flooding on port 5000. Sending cookies.  Check SNMP counters.

3.3.7-OpenSSL-Avahi-ALSA-sysconfdir:/usr/local/etc

Linux hifipi 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux

**Comment by mikebrady** [comment]
Thanks for the post. I haven't seen this, and the laters version,3.3.7, is 3.3.7rc3 which has been stable for some weeks.

Is it possible that your device is being attacked, or that there is some malfunction between your AirPlay source(s) and the Shairport Sync device? See [here](https://www.thegeekdiary.com/kernel-logs-warning-messages-kernel-possible-syn-flooding-on-port-x-sending-cookies-is-logged/) for example?

**Comment by PieGuy314** [comment]
I'm not overly worried. Hadn't seen it myself before and wondered if it might be related to any code updates.

I'm fairly certain my network is safe. Probably something I was doing (ie. flicking between remotes).

**Comment by mikebrady** [comment]
Thanks -- please keep us apprised.

**Comment by Hello71** [comment]
https://github.com/mikebrady/shairport-sync/blob/54cb9de1836fcb764bbae7397b6f79899f674268/rtsp.c#L2892

this is a fairly low buffer considering there is non-negligible work to be done between accepts (mainly creating a new thread). nginx for example uses 511.

**Comment by mikebrady** [comment]
Many thanks -- I'll push it up in a forthcoming revision.

**Comment by Hello71** [comment]
it's still 5

**Comment by mikebrady** [comment]
Darn it, I forgot. I’ll fix it — promise!

**Comment by mikebrady** [comment]
Finally, I set this to 255 in a `development` version -- it'll be posted soon. Apologies for the [amazingly long!] delay.

**Comment by PieGuy314** [comment]
Cough.

**Comment by mikebrady** [comment]
Done, I think.

**Comment by kiwi-ed** [comment]
I've seen exactly the same issue but in my case is wasn't Shairport-sync. I added network bonding and the type of bonding (round-robin) caused my issue after an intense investigation. It may seem related to shairport-sync but more likely it's related to your recent upgrade.

Hope is some way this helps..
