### ISSUE TITLE
MPD as Airplay sender

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#111]
Hi Mike, I've just finished integrating your wonderfully engineered shairport-sync into Moode Audio Player and was wondering if you had any thoughts on Airplay sender software that would enable MPD/ALSA based players like Moode to output both locally and to shairport-sync Airplay receivers?

An Airplay sender module + shairport-sync could be a very nice audio distribution solution :-) 

Regards,
Tim Curtis

**Comment by mikebrady** [comment]
Hi Tim. Thanks for the encouraging words. Regarding an AirPlay sending program, I have limited experience, TBH. I've used @ejurgensen's version of [forked-daapd](https://github.com/ejurgensen/forked-daapd) a few times and found it very good. It's well worth checking out, IMHO.
All the best,
Mike
