### ISSUE TITLE
Raspberry Pi OS specific info (might apply to others that use pulseaudio)

### ISSUE THREAD

**Issue by imabuddha** [mikebrady/shairport-sync#1110]
Since the OS now uses pulseaudio shairport-sync doesn't work after login/loout. With the pulseaudio backend shairport-sync can't run shairport-sync as a service. Fix requires an autostart file & two script files: one for the user & one for lightdm. This is because it should only kill when the user's session actually ends. (~~killing directly from the session-cleanup-script won't work properly if screen is locked~~ UPDATE: still kills after unlock 😥)

To remedy this do the following:

**Run shairport-sync on login** [create new file shairpoint-sync-autostart in /home/pi/.config/autostart]
```
[Desktop Entry]
Type=Application
Name=Shairport-sync autostart
Comment=must be run after login because of pulseaudio
NoDisplay=true
Exec=/usr/local/bin/shairport-sync
```

**Make sure shairport-sync is terminated on logout**
```
#! /bin/sh
#
# Location for this script: /usr/local/bin/lightdm_cleanup.sh
#
# Place the following line in /etc/lightdm/lightdm.conf [Seat:*] section to run this script:
# session-cleanup-script=/usr/local/bin/lightdm_cleanup.sh

if [ -e $HOME/.lightdm_cleanup.sh ]; then su -c "$HOME/.lightdm_cleanup.sh" $USER; fi
```

```
#! /bin/bash
# This script is for Raspberry pi os (current as of 7 Dec 2020)
# Make sure shairport-sync is terminated on logout
# (with pulseaudio backend can't run shairport-sync as service)
#
# Location for this script: ~/.lightdm-cleanup.sh

pgrep -x shairport-sync | xargs -t kill -1
```

**Note:** The only issue I've noticed now is that if you lock the screen it blanks briefly then the unlock greeter appears. This happens even if shairport-sync is killed before locking. If shairport-sync isn't ever started then lock behaves normally (screen blanks until keypress or mouse event).

(see my [gists](https://gist.github.com/imabuddha) for more info)

**Comment by imabuddha** [comment]
**UPDATE:** Unfortunately shairport-sync still gets killed when the greeter session ends (for example when user unlocks a locked session). 

Unfortunately I can't find any way to detect whether the session-cleanup-script is being run after the greeter ends or when the user actually logs out. This seems like a really _dumb_ implementation choice the lightdm, but what do I know? 

If anyone can shed some light on how to make the session-cleanup-script work only when the user actually logs out, or if you have any idea on how to fix the lock screen not staying blank is shairport-sync has been run, please let me know. 🙇

**Comment by imabuddha** [comment]
OK, I fixed the ~/.lightdm-cleanup.sh script so now it only kills shairport-sync when the user actually logs out. It turns out that when run after the greeter ends **$DISPLAY=:1** and **:0** when user logs out. 🎉

I still don't understand the weirdness with the lock screen not staying blank, but I do have some more info: this issue seems to only occur when the system is booted from power off. After that if rebooted it works perfectly. 👍️ I've chased this long enough, and I think it's likely to be a slight config problem with pulseaudio in the new OS, so I'm done.

**Comment by 0d0a** [comment]
Did not work .. should the .sh files be executable ? If yes for the user or for root?

**Comment by imabuddha** [comment]
@0d0a Yes the .sh files should be executable `chmod +x`. The file in /usr/local/bin will be run as root on logout, but would be ok if run as the current user. The file in the home dir will be run as the user who's logging out.

I'm using the latest kernel in the Raspberry Pi OS distro, which at this moment is `5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux`.

**Comment by imabuddha** [comment]
@0d0a I see that there's been an update to the repo since I checked yesterday, and it appears there's a new kernel. I'm upgrading it now & will report back after I've tested it.

**Comment by imabuddha** [comment]
@0d0a OK, I've tested it on `5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux` and it seems to still be working perfectly. I tried locking/unlocking the screen, and also logging out/in. Shairport-sync is properly killed only when actually logging out, and airplay from Music on my iPhone works.

*Note re lock screen not staying blank:* I'm not entirely sure what the problem was, but it's been working fine for me. Sometime after my prior posts I ended up reinstalling the x screensaver pkg, and there have been numerous system updates.

**Comment by imabuddha** [comment]
BTW, today's raspi kernel update (& possibly other pkgs) have some serious bugs. First that I noticed is that when playing audio the kbd randomly stops responding! 😱

See https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=297779&sid=35b029f2fb4d043714ed2cb8fcfb8d4b for more info. I **strongly** advise against upgrading system pkgs until this gets sorted!
