### ISSUE TITLE
Failure at boot launch via systemctl : Start requests repeated to quickly

### ISSUE THREAD

**Issue by blakespot** [mikebrady/shairport-sync#1114]
I have a Pi Zero W and a USB sound device from Sabrent. When I launch from the command line it works perfectly - streams audio from iPhone fine, but when I boot and have it set to autoload I get errors.

I set it to autoload with:
```
sudo systemctl enable shairport-sync
```
Errors:
```
shairport-sync.service: Service RestartSec=100ms expired, scheduling restart.
shairport-sync.service: Scheduled restart job, restart counter is at 9.
Stopped ShairportSync AirTunes receiver.
shairport-sync.service: Start request repeated too quickly.
shairport-sync.service: Failed with result 'signal'.
Failed to start ShairportSync AirTunes receiver.
```
Anyone have a suggestion here? Again, works just fine if I launch shairport-sync from command line after boot is finished.

Thanks.

bp

**Comment by mikebrady** [comment]
Thanks for the post. Did you build this or install it?

If you installed it, then there may be a fault with the installation scripts, and it might be better to build it from scratch -- see #1057.

**Comment by blakespot** [comment]
Thanks. I have followed the build instructions and built for Raspbian and it works perfectly! $35 total for a replacement to my now-dead, but long-neglected-by-Apple Airport Express. 


bp

**Comment by mikebrady** [comment]
Thanks for the nice writeup on [MacRumors](https://forums.macrumors.com/threads/built-a-35-rpi-based-airplay-receiver-replacing-a-dead-airport-express-works-great.2274965/)!
