### ISSUE TITLE
iOS 14.3 breaks Shairport

### ISSUE THREAD

**Issue by Cyrelion** [mikebrady/shairport-sync#1118]
I’ve a little problem with the latest update of iOS 14.3
All shairport devices aren’t visible anymore on the phones that are updated but still visible on the phones that are still on the previous version.

**Comment by mikebrady** [comment]
Thanks for the post. No problems to report here, with iOS 14.3 and macOS 11.1.

**Comment by Cyrelion** [comment]
Okay, after switching to a private mac (in settings) and rebooting it looks like it's working again.

Sure I tried the reboot of the device already before but didn't see the mac protection enabled. So case closed
