### ISSUE TITLE
mono pipe output same as stereo

### ISSUE THREAD

**Issue by jdtsmith** [mikebrady/shairport-sync#1119]
I enabled 

```json
        output_backend = "pipe";
        playback_mode = "mono";
```

and can read data from the named pipe.  I was surprised however, to find no apparent difference in the file stream outputted (modulo some stuffing bytes).  Does `pipe` output not respect `playback_mode`?

`Version: "3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc"`

**Comment by mikebrady** [comment]
Thanks for the post. The output is still two channels but the output on both should be the same — it’s the linear sum of the two channels divided by two.

**Comment by jdtsmith** [comment]
That's what I expected from looking at the code, but oddly that's not what I'm finding.  The output doesn't have repeating bytes, and is identical (modulo some zero padding up front) when the same song is played and pipe output is captured with mono vs. stereo enabled.  Example of side-by-side hexdump of mono (left, shifted by 4 bytes) and stereo (right) output:

```
mono (starting after 4 bytes)              stereo
0000004 0000 0000 0000 0000 0000 0000 0000 0000 0000000 0000 0000 0000 0000 0000 0000 0000 0000
*       *
00b09d4 ffff 0001 ffff 0000 0000 fffe 0001 ffff 00b09b0 ffff 0001 ffff 0000 0000 fffe 0001 ffff
00b09e4 0000 ffff ffff ffff 0000 ffff 0000 ffff 00b09c0 0000 ffff ffff ffff 0000 ffff 0000 ffff
00b09f4 0001 ffff 0000 fffe 0000 ffff 0000 fffe 00b09d0 0001 ffff 0000 fffe 0000 ffff 0000 fffe
00b0a04 0001 0000 0000 fffe ffff 0001 0000 fffe 00b09e0 0001 0000 0000 fffe ffff 0001 0000 fffe
00b0a14 ffff 0001 ffff fffe 0000 0001 0000 fffe 00b09f0 ffff 0001 ffff fffe 0000 0001 0000 fffe
00b0a24 0000 0000 0000 0000 ffff ffff 0000 fffe 00b0a00 0000 0000 0000 0000 ffff ffff 0000 fffe
00b0a34 0001 ffff ffff fffe 0000 0000 0000 ffff 00b0a10 0001 ffff ffff fffe 0000 0000 0000 ffff
00b0a44 ffff 0001 ffff ffff ffff ffff ffff 0000 00b0a20 ffff 0001 ffff ffff ffff ffff ffff 0000
00b0a54 0000 0000 0000 0000 fffe ffff ffff 0001 00b0a30 0000 0000 0000 0000 fffe ffff ffff 0001
00b0a64 0000 ffff ffff 0001 fffe 0000 ffff 0000 00b0a40 0000 ffff ffff 0001 fffe 0000 ffff 0000
00b0a74 ffff ffff 0001 fffe 0000 fffe 0001 ffff 00b0a50 ffff ffff 0001 fffe 0000 fffe 0001 ffff
00b0a84 ffff 0001 0000 fffe 0000 ffff 0000 ffff 00b0a60 ffff 0001 0000 fffe 0000 ffff 0000 ffff
```

Notice the bytes in mono also don't repeat (`0001` and `fffe`).

**Comment by mikebrady** [comment]
Yeah, but then there is dithering as well. Would that account for the differences? It looks like it would.

**Comment by jdtsmith** [comment]
That could be.  Is dithering random and applied to each channel separately, after mono conversion?  How can you disable dithering (I tried `ignore_volume_control = "yes"` to no avail)?  Thanks.

**Comment by mikebrady** [comment]
I’ll have to check the code. The rule I used was that if the audio was modified in any way, it was to be dithered. AFAIR there isn’t a “Disable Dither” flag in there.

**Comment by jdtsmith** [comment]
OK, thanks.  Maybe I don't understand the byte format of the pipe output.  I expected 16bit LRLRLR...  E.g. in this block:

```
ffff 0001 ffff 0000 0000 fffe 0001 ffff
```

I'd imagine `L1=ffff` is the first 16bit sample of the left channel, `R1=0001` is the first 2-byte sample of right channel, and so on.   But clearly they don't match in level for mono output even with random dithering offsets between the channels.

**Comment by mikebrady** [comment]
Again AFAIR, dither can affect the lowest two bits -- see http://www.ece.rochester.edu/courses/ECE472/resources/Papers/Lipshitz_1992.pdf.

**Comment by mikebrady** [comment]
There is not setting to disable dithering, but it wouldn't be too hard to add, I'd say.

**Comment by mikebrady** [comment]
Also, it might be worth updating -- 3.2.2 is pretty old and a fair few changes have been made, including to the dither code.

**Comment by jdtsmith** [comment]
Thanks.  In fact for non-dithered mono uses, it might be nice to have _non-interleaved_ output (MMM vs. LRLRLR where L=R).  Application here is an AirPlay-targeted audio-reactive LED lighting server, where you want to read a block of bytes, quickly perform FFT-type calculations, and ship them off via UDP.  So all latency should be as low as possible.

RE Version: Sadly raspbian buster stable still has 3.2.2. In the (testing) bullseye branch it's up to 3.3.5 so hopefully that will resolve soon.  

Regarding my byte confusion (in case anyone is having the same issue); I was expecting _unsigned 16bit data_ to the pipe, as it is streamed originally, but of course this doesn't work with dithering, so the pipe output is _signed_ 16 bit.  

Interpreted that way, Left and Right differ only at the ±2.5 level: 

![r_l](https://user-images.githubusercontent.com/93749/102697728-02414100-4206-11eb-9b64-a8bb4915a9fa.png)

**Comment by mikebrady** [comment]
Thanks for the information. Just one point though — the original would have been signed 16 bit interleaved (compressed in ALAC for transmission).

**Comment by jdtsmith** [comment]
Interesting, thanks.  Every PCM I reference I found mentioned unsigned...

**Comment by mikebrady** [comment]
Yeah, the standard abbreviation for CD quality music would be S16LE, which means signed 16 bit little-endian. There are 44,100 LR pairs per second in the stream. 

For your application, could you simply pick up every second sample from the “mono” stream?

**Comment by jdtsmith** [comment]
That will probably be what I try, just adds twice as much reading.  Probably not an issue.
