### ISSUE TITLE
./configure enables the feature when using --without-FEATURE

### ISSUE THREAD

**Issue by bassdr** [mikebrady/shairport-sync#1123]
When using autotool for configuring and passing `--without-FEATURE` to configure, the option is enabled instead of being explicitly disabled. This is annoying as Gentoo's ebuild system provides helper functions `use_with` that automatically sets eg. `--with-FEATURE` or `--without-FEATURE` automatically based on what have been chosen by the user ([Gentoo's USE Flags](https://devmanual.gentoo.org/general-concepts/use-flags/)).

The issue applies to at least the following configure options, but probably all `--without-*` are affected:
 - `--without-dummy`
 - `--without-stdout`
 - `--without-pipe`
 - `--without-apple-alac`

**Comment by mikebrady** [comment]
Thanks for the post. I'll have a look at this.

**Comment by mikebrady** [comment]
Yep, you're right -- I misunderstood the operation of `AC_ARG_WITH` 😕. It'll take a few days to fix it.

**Comment by mikebrady** [comment]
I believe I have fixed this problem and I have pushed an update to the `development` branch. If you got a chance to check it, that would be great.
