### ISSUE TITLE
Also support DLNA audio streams?

### ISSUE THREAD

**Issue by bassdr** [mikebrady/shairport-sync#1126]
Hi,
This is not a bug, but more of a question/idea.

I want to convert a raspberry pi into a headless audio streamer connected to an old-school amplifier. I came across shairport-sync because it looks close to what I want to achieve. Maybe the only thing missing would be handling DLNA streams (audio only).

FWIW, here is the setup I have in mind:
 - Raspberry-Pi 2 connected to an quite old amplifier setup, and also connected to wifi, but no screen, so everything should be remote-controlled.
 - Supports that anyone can connect from their phone (Android and iPhones) and stream audio, with little to nothing to install.
 - Have an audio library on a PC/NAS also able to stream audio.
     - It would probably be linux box, but if a windows app can stream an audio library to AirPlay/DLNA I'd like to know!
 - This is a _nice to have_: Some kind of handling if more than one source is trying to connect at the same time, no matter the stream source. 
     - e.g. if an Android device connects but an iPhone is already playing, don't play both and pause/mute one source, maybe following some priority list, or just first arrived first served.

My questions are:
 1. Do you think shairport-sync is the solution, that it would be easier to install software on Android and linux to stream AirPlay? not supporting DLNA at all?
 2. Would it make sense to make shairport-sync also accept DLNA feeds, what would be the effort?
     - FWIW, I am an experienced C++ developer willing to contribute if you think this is the way to go
 3. Do you have any suggestion on how to achieve what I have in mind, maybe using another software combined with shairport-sync. 
 4. Any suggestion is welcome.

Thank you, please feel free to close this issue if you think it is too off topic.

**Comment by fnordism** [comment]
You may need to modify a OpenHome Renderer like upmpdcli to pipe audio and artwork into shairport-sync, you can control such OpenHome Renderer with BubbleDS for Android/iPhone. s

**Comment by bassdr** [comment]
Thanks @fnordism, looking into this option.

**Comment by fnordism** [comment]
Take a look to https://github.com/ejurgensen/forked-daapd it also supports Airplay protocol and DLNA.

**Comment by kiwi-ed** [comment]
Like fnordism said upmpdcli. upmpdcli is an add-on for MPD and I've used it for years as a DLNA renderer and it will appear in standard apps such as 8Player and MConnect no problem. Essentially xcompile MPD and upmpdcli for the RPI then spin them up.

**Comment by minix1234** [comment]
you can try balena sound project.

https://github.com/balenalabs/balena-sound
