### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by WouterB92** [mikebrady/shairport-sync#1127]
Hello,
I'm having trouble installing. I've walked thru every step in [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) but unfortunatly I'm not hearing anything. 

I've also read other issues. 

Running _shairport-sync -V_ results in:
```
3.3.8rc2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
```

Running _$ systemctl status shairport-sync_ results in:
```
shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-12-31 15:06:43 CET; 17min ago
 Main PID: 478 (shairport-sync)
    Tasks: 4 (limit: 3861)
   CGroup: /system.slice/shairport-sync.service
           └─478 /usr/local/bin/shairport-sync

dec 31 15:06:43 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
dec 31 15:08:01 raspberrypi shairport-sync[478]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
```
Hoping you're able to help.

**Comment by mikebrady** [comment]
Hmm, it looks like it is running. Is it possible that you need to turn up the mixer level, say using `alsamixer`?

**Comment by skumka** [comment]
After updating my linux box I see service is masked.
what is the solution?
roon@roon:~$ systemctl status shairport-sync.service 
● shairport-sync.service
     Loaded: masked (Reason: Unit shairport-sync.service is masked.)
     Active: inactive (dead)
