### ISSUE TITLE
improved MQTT support and topic structure

### ISSUE THREAD

**Issue by ccutrer** [mikebrady/shairport-sync#1129]
I'm curious what your thoughts are on implementing an MQTT standard like https://homieiot.github.io/specification/ to make it easier for HA systems to detect available fields? At least for the "parsed" version, or maybe as a separate option? I'd be more than happy to do a PR if you're amenable to it.

In particular, I want to implement setting volume directly, instead of just the volumeup/volumedown that we currently have.

**Comment by mikebrady** [comment]
Thanks for the interesting post. One way to do it, I guess, might be to add, say, a `--with-mqtt-iot` configuration option (or some suitable name)  to include this enhanced system. A user could configure the build to include the existing MQTT or to include the alternative.

The volume setting facility is absent from MQTT because at the time the MQTT code was developed, we didn’t know that the player had a volume-setting facility.

**Comment by ccutrer** [comment]
why a build option as opposed to a config option? I think I'll throw together a PR to show what I'm envisioning... it should be fairly simple

**Comment by mikebrady** [comment]
> why a build option as opposed to a config option? I think I'll throw together a PR to show what I'm envisioning... it should be fairly simple

No particular reason, I guess, other than to keep the code size down. Shairport Sync is plug on some really small devices!

**Comment by minix1234** [comment]
evening,

sounds interesting. which HA system are you using?

I know that various systems have their own way of doing discovery, ways of specifying media players, etc 

I am using Home Assistant and another user has setup a nice custom component to utilize this published mqtt as an integration for the media player.

https://github.com/parautenbach/hass-shairport-sync

truth be told it's usually not very difficult to create such components to integrate into HA systems.

**Comment by brianlay714** [comment]
I'm using OpenHab and have just begun integrating with Shairport.
Apparently the Homie convention would also work with OpenHab.
https://www.openhab.org/addons/bindings/mqtt.homie/#mqtt-homie-binding

I'm happy to help with this effort but I'm not a developer, just a product manager!

**Comment by minix1234** [comment]
the components for home assistant can be readily modified.

I would support improvement of mqtt volume control and the state binary publishing.  i.e. play active, etc.

**Comment by ccutrer** [comment]
I also use openhab. and while setting up an mqtt device item-by-item (i.e. "creating a home assistant component") is doable, it's slow. Especially since all it takes to make it automatic is for the device to follow a convention when publishing their data, along with a few small bits of metadata. Home Assistant itself supports its own scheme for this, though it's not formalized, which is why I always push for the Homie Convention. It's also supported by almost every HA system (and those that it doesn't, can still configure MQTT things directly; see https://github.com/hjdhjd/homebridge-unifi-protect/issues/87#issuecomment-693565452 for a table I researched of which HA systems support which MQTT conventions). Auto-configuration like this is nearly a must when you have a large number of devices. I myself have 24 processes publishing Homie metadata to MQTT, representing 136 discrete devices, each device exposing from 1 to ~40 properties. That'd be a heckuva a lot of clicking if I had to configure everything manually!

Anyhow, I apologize for my absence. My wife gave the go-ahead (nay, the mandate!) to finish our home theater, so I've been going full-bore on that for the past couple weeks in any free time I have. I promise I won't forget this, and plan to get back to it.

**Comment by ccutrer** [comment]
I'm assuming focus has been on AirPlay 2 for the past couple months, and probably for the next bit as well. Just want to say I'm still interested in improvements here when time allows

**Comment by rogersmj** [comment]
@ccutrer I found this old topic when hunting for a way to set volume via MQTT. Did you ever make any progress on implementing that?

**Comment by ccutrer** [comment]
I ended up only doing https://github.com/mikebrady/shairport-sync/pull/1384 (and some related PRs to make sure those fields work with AP2). I never did anything with volume control.
