### ISSUE TITLE
Standby/low-power mode on RPi4

### ISSUE THREAD

**Issue by maziarzamani** [mikebrady/shairport-sync#1132]
I have a RPi4 running with Shairport-Sync successfully, which is only used for AirPlay. However when the device is not streaming I would like to run it in a standby/low-power state. Is this possible, and has anyone attempted on doing this?

**Comment by mikebrady** [comment]
Thanks for the post. One think to think of is that, if you’re using WiFi, it’s important that WiFi power management should remain off, as otherwise it may drop the link to the network when it is not being used.

**Comment by maziarzamani** [comment]
> Thanks for the post. One think to think of is that, if you’re using WiFi, it’s important that WiFi power management should remain off, as otherwise it may drop the link to the network when it is not being used.

Makes sense! However I am getting a feeling that this will not be possible with the Raspberry Pi, to actually hibernate it as this is not already possible. Seems that the only way is to reduce power consumption is by downclocking CPU, using less cores, disabling unnecessary peripherals and automatically scheduling on/off time of the device. Is this state-of-the-art or are there other tricks I have missed?

**Comment by mikebrady** [comment]
Hmm, don’t know anything about that, I’m afraid.

**Comment by vasilisvg** [comment]
There is a simple solution that works: adding a power button to your Pi. Simply turn it off if you don’t need it. 
Then there are a few things you can do to consume less power: you should disable the USB and ethernet block if you don’t need them. Or disable wifi if you don’t need it. Disable bluetooth if you don’t need it. Turn off the LEDs. And you could disable the HDMI port.
