### ISSUE TITLE
shairport stops playing audio 

### ISSUE THREAD

**Issue by brianlay714** [mikebrady/shairport-sync#1135]
shairport stops playing audio with error in the log 
``
Jan 18 12:34:36 aspen shairport-sync: warning: alsa: error -24 ("Too many open files") opening alsa device "hw:1".
``
running on a Pi 3B using HiFiBerry DAC
created with options:  3.3.8rc1-OpenSSL-Avahi-ALSA-soxr-metadata-mqtt-sysconfdir:/etc

after playing several hours, when you change streaming source on the device, audio stops playing.

Any advice on how to proceed with troubleshooting/log capture?

Thanks
Brian

**Comment by mikebrady** [comment]
Thanks for the post. Are you using the metadata or the MQTT stuff? (I wonder if there is anything downstream of Shairport Sync that might be opening files or pipes, etc., but that might not be closing them? And would `lsof` be useful here?)

**Comment by brianlay714** [comment]
thanks for the quick response.  I'm using MQTT to send metadata of what's playing to my home automation.
My understanding is that MQTT is simply sending data to a port, regardless of whether it's being consumed, so it should be decoupled from any receivers.
In my system Shairport is sending to a dedicated broker which relays to the HA.
I've now installed LSOF and will use it to investigate the next time this happens.
Maybe I should increase the logging level in Shairport as well?  currently @ 1

**Comment by mikebrady** [comment]
Thanks. I think that the focus should be on what program has opened so many files, and I’m not sure increasing the log level of Shairport Sync will help. I could be wrong, of course 😊.
