### ISSUE TITLE
shairport-sync[480]: warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:0".

### ISSUE THREAD

**Issue by JoernUhl** [mikebrady/shairport-sync#1136]
Hi,

I hope this is correct that I am posting this here as I am pretty sure it is actually not an issue with shairport-sync but rather my own inability to make this work. Please let me know if this question should be asked elsewhere :-)

I installed shairport-sync along with [RPi-Jukebox-RFID](https://github.com/MiczFlor/RPi-Jukebox-RFID/). I installed both on a Raspberry Pi 3, with an [Adafruit Speaker Bonnet](https://www.adafruit.com/product/3346). If I use the functionality provided by RPi-Jukebox-RFID, I get sound and music plays as it should. However, if I try to use airplay from any of my iDevices, no sound is heard.

After running the command `systemctl status shairport-sync` I get the following output a couple of times: 

```
 shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-01-22 17:39:53 GMT; 30min ago
 Main PID: 480 (shairport-sync)
    Tasks: 11 (limit: 2063)
   CGroup: /system.slice/shairport-sync.service
           └─480 /usr/local/bin/shairport-sync
```
as well as:

```
warning: alsa: error -16 ("Device or resource busy") opening alsa device "hw:0".
```
Running `aplay --list-devices`, I get:

```
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 [HifiBerry DAC HiFi pcm5102a-hifi-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

In  `/etc/shairport-sync.conf` I added within the `alsa` section:
```
output_device = "hw:0";
```
and
```
mixer_control_name = "Master";
```

I guess the RPi-Jukebox-RFID installation occupies the Adafruit Speaker Bonnet and is not letting shairport-sync play any music? I would appreciate any tipps or pointers into the right direction :-)

And again, sorry if I am posting this question in the wrong forum.

Thanks a lot for your help,

jrn

**Comment by mikebrady** [comment]
Thanks for the post, which I edited slightly for layout. I think you're right -- my guess is that the RPi-Jukebox-RFID system takes, and keeps, the output device. It may be possible to send output from both RPi-Jukebox-RFID and Shairport Sync to an `alsa` mixer device which in turn connects to the real output device, but I've never tried it -- perhaps someone else has experience. Also, Shairport Sync really expects to be outputting to a real hardware device, from which it can get true device characteristics and reliable latency information.

It might be worth asking the RPi-Jukebox-RFID crowd if it hold the output device and/or could be persuaded to release it when not active.
