### ISSUE TITLE
Cannot change service name on Raspberry Pi

### ISSUE THREAD

**Issue by MalbecsDad** [mikebrady/shairport-sync#1138]
Hi,

Am running Shairport-sync (version 3.2.2) on RaspberryPiOS (version 10, Buster), standard install from apt repository. I have tried to change the name of the service from the default "hostname" by uncommenting the line name = "%H"; in /etc/shairport-sync.conf. Every time I try this (e.g. name = "Spare Room";) the service fails to start with the error message

Job for shairport-sync.service failed because a fatal signal was delivered to the control process.
See "systemctl status shairport-sync.service" and "journalctl -xe" for details.

Output of systemctl status:
```
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sun 2021-01-31 12:12:17 GMT; 21s ago
     Docs: man:shairport-sync(7)
           file:///usr/share/doc/shairport-sync/README.md.gz
           https://github.com/mikebrady/shairport-sync
  Process: 1771 ExecStart=/usr/bin/shairport-sync --daemon $DAEMON_ARGS (code=killed, signal=ABRT)

Jan 31 12:12:17 beaker systemd[1]: shairport-sync.service: Service RestartSec=100ms expired, scheduling restart.
Jan 31 12:12:17 beaker systemd[1]: shairport-sync.service: Scheduled restart job, restart counter is at 5.
Jan 31 12:12:17 beaker systemd[1]: Stopped ShairportSync AirTunes receiver.
Jan 31 12:12:17 beaker systemd[1]: shairport-sync.service: Start request repeated too quickly.
Jan 31 12:12:17 beaker systemd[1]: shairport-sync.service: Failed with result 'signal'.
Jan 31 12:12:17 beaker systemd[1]: Failed to start ShairportSync AirTunes receiver.
```
In fact, any time I uncomment any line from the config file, the service fails to start. I've tried the simple config file below, and this still fails. What am I doing wrong?

```
// Sample Configuration File for Shairport Sync
// Commented out settings are generally the defaults, except where noted.

// General Settings
general =
{
  name = "%H";
};
```

**Comment by mikebrady** [comment]
Thanks for the post. There was a bug in 3.2.2 that causes the problem you refer to. The easiest thing is to build the latest version yourself -- there's a guide at [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md). You should pay particular attention to the instructions for removing all vestiges of the package installation.

**Comment by MalbecsDad** [comment]
Mike Brady, you sir are a legend! A legend for providing excellent quality free software, for amazingly quick response to a problem report, great documentation on recompiling... Thank you!

**Comment by mezza** [comment]
Works brilliantly, thank you!
