### ISSUE TITLE
Can shairport-sync receive 5.1 audio?

### ISSUE THREAD

**Issue by netzling** [mikebrady/shairport-sync#1139]
I would like to use shairport-sync to get 5.1 surround sound from my appleTV to my hifi plus additional speakers via airplay 2. It seems that HomePods can provide some sort of surround sound via airplay so apple TV seems to have the ability to send more than stereo via airplay.

Stereo airplay from apple TV to shairport sync works great but I can find nothing in the documentation of shairport-sync indicating how to set up output of more than two channels.

Before banging my head against this for too long, I thought its quicker to ask.

So can shairport-sync receive 5.1 audio? And if yes, how do I have to set it up to make this work?

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync only works on two-channel stereo, as that seems to be all that AirPlay 1 ever provided. Specifically, AirPlay 1 uses CD-quality audio: 44,100 frames per second, with signed linear little-endian 16 bit left and right samples in a frame. Apple lossless compression is used when transmitting the material.

So, to answer your question, if your Apple TV can provide two-channel stereo to Shairport Sync, then it will play it.

However, another possible issue is that Shairport Sync implements the AirPlay 1 protocol, and AFAIK you can not play simultaneously to a combination of AirPlay 1 and AirPlay 2 speakers.

**Comment by ffrappo** [comment]
Does this answer also apply to the `development` branch?

**Comment by mikebrady** [comment]
> Does this answer also apply to the `development` branch?

Yes, in [AirPlay 2 operation](https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md#airplay-2----more-about-what-works), the `development` version only sees stereo material coming from the player.
