### ISSUE TITLE
cannot start with systemctl

### ISSUE THREAD

**Issue by blackLotus1998** [mikebrady/shairport-sync#1143]
Failed to enable unit: Unit file /lib/systemd/system/shairport-sync.service is masked.

**Comment by mikebrady** [comment]
Thanks for the post. If you installed it from a package and it is version 3.2.2, there is a bug in the installation. If so it's best to reinstall it  by building it -- see #1138. Take care to fully remove the scripts, as detailed by the [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) guide.

**Comment by blackLotus1998** [comment]
thanks for reply. i'm now can install with this.
