### ISSUE TITLE
Distortion noise when playback paused

### ISSUE THREAD

**Issue by hanerd** [mikebrady/shairport-sync#1147]
Using the latest docker image rebuilt to support `--with-pa` I'm getting terrible digitial distortion when anything coming through shairport is paused.  The noise is roughly the same sound as if there were a ground loop coming through a speaker.

I'm at a complete loss as to where the noise is coming from.  No other service running on that box (mopidy and some TTS stuff) has any kind of noise when idle--only shairport.

I can reliably make the sound go away by stopping the shairport container so it leads me to believe there's some sort of comfort noise or something playing when paused, but I can't find anything in the configs that would let me control / disable that.  My current work around is to have sessioncontrol mute and unmute the speakers before and after pause, but that causes a quick blast of the noise before the song starts playing again.

I'd really appreciate any kind of pointer toward where it could be coming from.

**Comment by mikebrady** [comment]
Thanks for the report. I’ve been running Shairport Sync out of the Docker image but into an `alsa` backend and haven’t had any problems with it. So maybe something odd about the PulseAudio backend or system. Maybe someone else might have direct experience with this.
