### ISSUE TITLE
Shairport stops playing audio from iPhone almost every time in 2–10 minutes

### ISSUE THREAD

**Issue by a-x-** [mikebrady/shairport-sync#1148]
… and doesn’t continue until I re-connect iPhone. 
(also, I cannot re-connect it immediately. I have to disconnect, wait 1–5 minutes, connect. Otherwise, I get kind of _busy status_ error.

iOS: 14, all sub-versions.
Streaming from macbook (music/iTunes) works find.
shairport-sync: a bunch of latest versions at least.
Raspberry: 1,2,3,4 (I have one of them in each room). Every Pi is ethernet-wired.
I have fast 1gb lan.

I recorded verbose logs:

[shairport.log](https://github.com/mikebrady/shairport-sync/files/5979900/shairport.log)

**Comment by a-x-** [comment]
Probably, a series of 
```
Feb 15 09:26:37 rpi2 shairport-sync[435]:          0.000052239 "player.c:622" Frame 42863 is missing with ab_read of 42737 and ab_write of 42965.
```
might be a problem.

**Comment by a-x-** [comment]
In 2020 dec I recorded another log with the same problem:
[shairport.log](https://github.com/mikebrady/shairport-sync/files/5979912/shairport.log)

Looks like have “frame missing” problem too.

**Comment by mikebrady** [comment]
Thanks for the posts. On the face of it, it looks like a network problem. If it is not happening on the Ethernet connections, then it would seem to be associated either with the WiFi network or with the connection between the wired and WiFi sections. This is not an uncommon problem, and it might well be worth checking for reports of router issues, firmware updates, etc. Of course, there may be other problems such as interference, etc.

The logs show that the network seems to get into difficulties after a while. For example:
```
Feb 15 09:26:37 rpi2 shairport-sync[435]:          2.752149778 "rtp.c:834" Time ping turnaround time: 690115 us -- it looks like a timing ping was lost.
```
is an indication that a UDP timing ping that should have resulted in a responding ping in a few milliseconds took over half a second.

Similarly there are some long sequences of lost UDP audio packets. These all indicate some kind of network slowdown or even of occasional complete loss of connectivity.

It would be worthwhile enabling the gathering of statistics in the configuration file -- they may give a better idea of how the network seems to be performing. And it's okay to set the `log_verbosity` to 2.

Also, perhaps you would be kind enough to post the start of the Shairport Sync log -- it begins with something like:
```
         0.002752998 "shairport.c:1653" Started!
         0.000350518 "shairport.c:1677" software version: "3.3.7d3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
```
Some of the information there might be useful.
