### ISSUE TITLE
core dumps on linux 5.10.14

### ISSUE THREAD

**Issue by gearhead** [mikebrady/shairport-sync#1149]
Apologize for the low info issue, but it just core dumps when I try to run it on armv7. Worked fine under 5.4.83. No issues when building.  No problems on aarch64. No problems on armv6. Very strange. I noticed that arch now builds a package, so I may start using that as long as alac is built in it.
```
# /usr/bin/shairport-sync -vvvv
Segmentation fault (core dumped)

# uname -r
5.10.14-2-ARCH
```

**Comment by mikebrady** [comment]
Thanks. Do you have `gdb` installed on it?

**Comment by gearhead** [comment]
Mike,

I do not, but can. It will take me a bit to get to this. Maybe later in the
week. It is strange. the version I built *and* the version from the Arch
Linux repos will not run on the 32 bit images (armv6/v7) image. It seems to
be fine on aarch64

Armv6:
Feb 17 07:50:58 runeaudio systemd[1]: Started Shairport Sync - AirPlay
Audio Receiver.
Feb 17 07:50:59 runeaudio systemd[1]: Started Process Core Dump (PID
27280/UID 0).
Feb 17 07:51:02 runeaudio systemd-coredump[27281]: Process 27279
(shairport-sync) of user 971 dumped core.

                                                   Stack trace of thread
27279:
                                                   #0  0x00000000768e1de0
strlen (libc.so.6 + 0x7dde0)
                                                   #1  0x00000000768bdc18
__vfprintf_internal (libc.so.6 + 0x59c18)
Feb 17 07:51:02 runeaudio systemd[1]: shairport-sync.service: Main process
exited, code=dumped, status=11/SEGV
Feb 17 07:51:02 runeaudio systemd[1]: shairport-sync.service: Failed with
result 'core-dump'.
Feb 17 07:51:02 runeaudio systemd[1]: systemd-coredump@9-27280-0.service:
Succeeded.

 Armv7:
Feb 17 07:53:10 runeaudio systemd[1]: Started Shairport Sync - AirPlay
Audio Receiver.
Feb 17 07:53:10 runeaudio systemd[1]: Created slice
system-systemd\x2dcoredump.slice.
Feb 17 07:53:10 runeaudio systemd[1]: Started Process Core Dump (PID
15879/UID 0).
Feb 17 07:53:10 runeaudio systemd-coredump[15880]: Process 15878
(shairport-sync) of user 972 dumped core.

                                                   Stack trace of thread
15878:
                                                   #0  0x00000000b691a92e
strlen (libc.so.6 + 0x7d92e)
                                                   #1  0x00000000b68f65ec
__vfprintf_internal (libc.so.6 + 0x595ec)
Feb 17 07:53:10 runeaudio systemd[1]: shairport-sync.service: Main process
exited, code=dumped, status=11/SEGV
Feb 17 07:53:10 runeaudio systemd[1]: shairport-sync.service: Failed with
result 'core-dump'.
Feb 17 07:53:10 runeaudio systemd[1]: systemd-coredump@0-15879-0.service:
Succeeded.

I will install gdb and await further instructions.

**Comment by mikebrady** [comment]
Super, thanks. I'll rustle up some instructions...

**Comment by mikebrady** [comment]
Here are some instructions. The basic idea is to run Shairport Sync inside `gdb` until it crashes and then do a backtrace on it. This might give us the location in the code where the crash occurred.

First, check that it's not already running. Here, you can see that it is running as process 24478:
```
$ ps aux | grep shai
shairpo+ 24478  2.2  1.8 151964 18736 ?        Ssl   2020 2566:53 /usr/local/bin/shairport-sync
pi       28585  0.0  0.0   7348   472 pts/0    S+   12:36   0:00 grep --color=auto shai
```
If it's already running, then kill it.

Next, run it inside `gdb`:

```
gdb --args shairport-sync -vu
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from shairport-sync...done.
(gdb) 
```
At this point, enter `run`. You should get something like the following followed by a crash:
```
(gdb) run
Starting program: /usr/local/bin/shairport-sync -vu
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
         0.002582320 "shairport.c:1729" Started!
         0.000209321 "shairport.c:1756" software version: "3.3.8d5-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000087812 "shairport.c:1762" log verbosity is 1.
         0.000142030 "audio_alsa.c:1015" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000408017 "audio_alsa.c:1302" alsa: disable_standby_mode is "never".
         0.000326507 "audio_alsa.c:1304" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000170572 "audio_alsa.c:1306" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000206196 "audio_alsa.c:1345" alsa: output device name is "hw:1".
[New Thread 0x76548390 (LWP 6624)]
...
....
```
 When it does crash, enter `bt` or `bt full`:
```
(gdb) bt
#0  __GI___select (timeout=0x0, exceptfds=0x0, writefds=0x0, readfds=0x7effed40, nfds=5) at ../sysdeps/unix/sysv/linux/select.c:41
#1  __GI___select (nfds=5, nfds@entry=349377, readfds=0x7effed40, readfds@entry=0x7effed38, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=0x7effec98, timeout@entry=0x7effec90)
    at ../sysdeps/unix/sysv/linux/select.c:37
#2  0x0001b9c8 in rtsp_listen_loop () at rtsp.c:2933
#3  0x000151f4 in main (argc=<optimized out>, argv=<optimized out>) at shairport.c:1987
```
If you could post the responses here, including the direct response to the `gdb` `run` command, it would be very interesting.

**Comment by gearhead** [comment]
Mike,

Thanks, but I think I found my problem. My config file was hosed and causing the crash. I fixed the config and it runs. I did note that Arch Linux does compile a package for this, but does not compile in alac.

Sorry for the alarm!
