### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by lorenzoCuevas** [mikebrady/shairport-sync#1150]
Hi, mind if I ask if there any progress on implementing airplay 2 into shareport as of right now?

**Comment by mikebrady** [comment]
Working on parts of it, but it’s a bit early to say anything definite. There are lots of things to discover and to figure out.

**Comment by lorenzoCuevas** [comment]
Okay, let me know if you have fully implemented airplay 2 into shairport

**Comment by mikebrady** [comment]
> Any update on Airplay 2 support on Belena Sound?

That's a question for the Belena Sound guys...
