### ISSUE TITLE
Shairport Sender/Streamer

### ISSUE THREAD

**Issue by NotOnBoard** [mikebrady/shairport-sync#1151]
I have a couple of shairport-sync players alongside existing Hifi all working nicely together for multiroom playback, thanks Mike.

Is there a software package that is the Sender/Streamer equivalent of shairport-sync ?  That is, a software package I can run on a raspberry pi that will allow me to send an audio stream to multiple shairport-sync player/dac devices.

I don't mean a full blown media player, just a service that will connect to and send an audio stream to multiple shairport-sync players.  So for example, I could send audio from a turntable to multiroom players.

This will obviously require a codec/ADC to digitise the audio and maybee some additional coding work to control it, but if the basis is there I'd like to investigate it.

**Comment by NotOnBoard** [comment]
Yeah, haven't quite got the hang of the message system yet, bear with me please.

**Comment by mikebrady** [comment]
Thanks for the post. There is a repository [RAOP-Player](https://github.com/philippe44/RAOP-Player) that might be worth checking out. Apart from that, I'm afraid I don't know of other work.

**Comment by NotOnBoard** [comment]
Thanks Mike
