### ISSUE TITLE
Shairport dbus / mpris as session 

### ISSUE THREAD

**Issue by NNEU-1** [mikebrady/shairport-sync#1152]
Hi,

Im trying to run the Shairport dbus / mpris as session and not as system service.
I've already gone through the code and it seems that this can be achieved by defining "config.dbus_service_bus_type" as "DBT_session".
However, I'm not sure of an adequate way (or rather where) to do this.

This is probably very easy to answer, i'd highly appreciate it!

**Comment by mikebrady** [comment]
You can set this in the configuration file. If you look in the sample configuration file that should have been  loaded when you installed Shairport Sync, you'll find the following lines:
```
//	dbus_service_bus = "system"; // The Shairport Sync dbus interface, if selected at compilation, will appear
//		as "org.gnome.ShairportSync" on the whichever bus you specify here: "system" (default) or "session".
//	mpris_service_bus = "system"; // The Shairport Sync mpris interface, if selected at compilation, will appear
//		as "org.gnome.ShairportSync" on the whichever bus you specify here: "system" (default) or "session".
```
Remember to uncomment the relevant lines to activate them and restart Shairport Sync for the new settings to take effect.

**Comment by NNEU-1** [comment]
Thanks for your quick reply !
For some reason I was so sure that this is a compile time option. Issue solved :)
