### ISSUE TITLE
System beep (alert) sound corrupt playback after using shairport-sync

### ISSUE THREAD

**Issue by luckman212** [mikebrady/shairport-sync#1153]
- mac mini 2018 connected to external speakers via headphone jack
- macOS 11.2.1
- shairport-sync 3.3.7-libdaemon-OpenSSL-dns_sd-ao-pa-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc/shairport-sync

I'm hitting a strange bug, where after streaming audio to my Mac, the audio output stream gets corrupt somehow.

The most noticable symptom is: when playing sounds such as the system beep or other effects like the "snap" sound after taking a screenshot, instead of the sound that should be played, I hear a short (~0.5s) repeating loop of the last moments of the audio that was being piped into shairport (kind of a "[max headroom](https://www.youtube.com/watch?v=nt56RMbpq_0)" effect, for those old enough to know what that is).

Here's my `/usr/local/etc/shairport-sync/shairport-sync.conf`:
```
general = {
	name = "mini";
	output_backend = "ao";
	ignore_volume_control = "no";
};

sessioncontrol = {
	active_state_timeout = 5.0;
	allow_session_interruption = "yes";
	session_timeout = 10;
};
```

Anyone else seeing this or got any ideas?

**Comment by mikebrady** [comment]
Hmm, haven’t come across this, I’m afraid. I’ll have a look.

**Comment by luckman212** [comment]
Thanks, if you need me to collect any other info or if you're unable to reproduce, let me know. One thing I noticed, it seems to affect certain streams more than others. It was very easy to reproduce by streaming sound from the CNN app to my desktop.
