### ISSUE TITLE
Check for external volume change

### ISSUE THREAD

**Issue by dersimn** [mikebrady/shairport-sync#1154]
Basically the same feature of librespot-org/librespot#516 but for this project.

> I also have IR receiver attached to my Raspberry PI to do some stuff including volume control. It also works with ALSA mixer.
> 
> And as I understand it seems like librespot doesn't check the volume value. For example I set volume on my phone to 60% then changed it to 30% via IR. After that I still see 60% on my phone.
> 
> Is it possible to add the volume value reading?

Currently volume sync from shairport-sync → ALSA works, but a change to the volume from an external source is not synced back to shairport-sync / the sending device.

**Comment by mikebrady** [comment]
Thanks for the post. Right now there are no plans to implement this. TBH it’s messy to do this in a reliable way — not all sources listen for the remote control signals needed.

**Comment by dersimn** [comment]
Sounds reasonable, thanks for the reply!
