### ISSUE TITLE
Play from router instead of phone?

### ISSUE THREAD

**Issue by Murosic** [mikebrady/shairport-sync#1155]
Hi, is it possible to configure Shairport to play directly from the wifi router instead of via the phone? So in the same way as a Chromecast. Now the music stops when my phone is out of the wifi range. Multi room/devices is not needed in this case.
Thanks in advance.

**Comment by mikebrady** [comment]
I’m afraid I don’t know what you mean. Can you explain?

**Comment by Murosic** [comment]
Hi, thanks for your reply!
I mean: with a Chromecast, if you start music with your phone, some autonomous player is set up on the chromecast. After that, when your phone is out of wifi, or even turned off, the chromecast keeps playing because it streams directly via the router. So only the start/stop of a music stream is triggered by the phone.
With Shairport, the music seems to be streamed via the phone, because a continue stable wifi connection on the phone is needed to keep the music playing.

I read something saying this is a “feature” in the newer Airport protocol, to provide multiroom/speaker playback without latency. I prefer the “Chromecast” way and don’t need multi speaker functionality.

Is there a configuration option to achieve this?
Thanks again.

**Comment by mikebrady** [comment]
Ah okay, thanks. Unfortunately that is well beyond the scope of Shairport Sync, which is basically to provide wirelessly connected speakers for an AirPlay source.

**Comment by Murosic** [comment]
Ah ok, thanks, it is how it is. Best!
