### ISSUE TITLE
Shairport-sync not found on macOS

### ISSUE THREAD

**Issue by drstil** [mikebrady/shairport-sync#1156]
I installed shairport-sync on my raspberry and can connect successfully with iOS, but do not find shairport-sync on my MacBook 2015 with Big Sur 11.1. Still found issue #1024, so it could be a similar issue. With the "Discovery" app I do not find the 
code `_raop._tcp` on macOS, but on iOS. But I find some other code from other devices (e. g. printer) on macOS. Could it be an ipv4 ipv6 issue?
I still read REPORTING ISSUES and TROUBLESHOOTING.

3.3.8rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Do you need more information?

Thank you and best!

**Comment by mikebrady** [comment]
Thanks for the post. If the `_raop._tcp` messages are not appearing on the Mac, then it seems very like that its some kind of network issue. Is the Mac on a VPN? Is there a firewall running somewhere?

**Comment by drstil** [comment]
There is no VPN or any firewall running in the network. Is there some way how I can check the network stuff? As I still said I do find some other items with discovery, e. g. my printer, which is in the same network.

**Comment by lovelyxmj** [comment]
I have the same problem. What can I do？

**Comment by steinmb** [comment]
Sounds like a network related problem. Prob. unrelated to Shairport - Perhaps try disabling `ipv6` on your Mac, reboot your router. Try connecting on ethernet etc.
