### ISSUE TITLE
Shairport.config run_this_before_play_begins sudo command Raspi

### ISSUE THREAD

**Issue by bawx25** [mikebrady/shairport-sync#1157]
I want to use the `run_this_befor_play_begins` functions in the Shairport Sync configuration file.

My aim is to achive than an Airplay connection is established the bluealse service gets disconnected, so you can´t sent musik to the Raspi via Bluetooth just via Airplay. Then Airplay is disconnected you can connect again with Bluetooth.?

I already tried to give an application path like `/etc/bt_end` and wrote into it

```
#!/bin/bash -e
    
sudo service bluealsa-aplay stop
```
and in the settings i set this

```
sessioncontrol = {
  run_this_before_play_begins = "/etc/bt_end";
  run_this_after_play_ends = "/etc/bt_start";
  wait_for_completion = "yes";
  session_timeout = 20;
};
```

Also i tried to stop the bluealse service direktly with this command, which also didnt help

```
run_this_after_play_start = "/usr/bin/sudo service bluealsa-aplay stop";
```

I just want running the `sudo` command `sudo service bluealsa-aplay stop`, but didn't know how to make it.

**Comment by mikebrady** [comment]
Thanks for the post. This is a tricky problem, made more difficult by the fact that you need to use `sudo`. I suggest you look elsewhere on the Internet to find out how to do this -- it's a unix/Linux competency.

**Comment by bawx25** [comment]
I asked already on stackoverflow and looked in the Internet after anwsers. But didn´t find help. But thank you for your anwser. Maybe someone here will have the a solution.

**Comment by p3ck** [comment]
This works for me...

run_this_before_play_begins = "/usr/bin/sudo /usr/local/bin/unmute";
run_this_after_play_ends = "/usr/bin/sudo /usr/local/bin/mute";


[root@vt-inside ~]# more /usr/local/bin/unmute
#!/usr/bin/sh

echo 22 > /sys/class/gpio/export 2>/dev/null
echo out >/sys/class/gpio/gpio22/direction
echo 1 >/sys/class/gpio/gpio22/value

[root@vt-inside ~]# more /usr/local/bin/mute
#!/usr/bin/sh

echo 22 > /sys/class/gpio/export 2>/dev/null
echo out >/sys/class/gpio/gpio22/direction
echo 0 >/sys/class/gpio/gpio22/value

[root@vt-inside ~]# cat /etc/sudoers.d/shairport-sync
shairport-sync  ALL=NOPASSWD: /usr/local/bin/unmute, /usr/local/bin/mute
