### ISSUE TITLE
Shairport-sync on Raspberry Pi, audio corruption after recent updates

### ISSUE THREAD

**Issue by durwin99** [mikebrady/shairport-sync#1158]
I have an RPi 4 running Raspbian that has been running shairport-sync for something like 9 months without any issues - using Airplay to stream from iPhone 12, audio out through a HiFiBerry DAC+ Pro. Network is Ethernet only. Towards the end of 2020 I installed the then-latest Raspberry Pi OS (2020-08-20-raspios-buster-armhf-lite.img) onto a new SD card, then installed Pi-hole according to the standard process. Once that was up and running, I installed shairport-sync again, following the install process documented here on github (enabling soxr). This ran fine for probably 6-8 weeks, absolutely rock solid.

Then suddenly in early Feb (I think) the process stopped working properly, sometimes the audio would work for a short time, then I would get either silence (with music) or seriously garbled audio (from podcasts etc). Occasionally the airplay device wouldn't show at all - checking with systemctl showed the service was failed/not working (sorry, I didn't grab the exact status). I wrote a cron job to check every minute for the service to be "active (running)" and to restart it if not, and I set the systemd service to auto-restart after 5 seconds if it failed. It seems the service would be fine then if I didn't use it (ie send via airplay) but when I did, the symptoms above re-appeared.

Yesterday I removed all the shairport-sync software, config etc, stopped the cron jobs, rebooted and went through the install again, this time without the soxr support (actual command was "./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-systemd". The only changes I made to the conf file were the airplay name and the Alsa output_device to "hw:1". I'm still getting the same issues.

I suspect this is down to something else in Raspbian being updated (I usually run apt upgrade at the beginning of each month). Looking through the apt history, there were various firmware updates at the end of January, something for systemd in mid-Feb but I can't see any of the libraries that are specified as needed for shairport-sync in the list. I can supply logs as needed...

OS is listed as "Raspbian GNU/Linux 10"
uname -a : "Linux rpi1 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux"
shairport-sync -V : "3.3.8rc3-OpenSSL-Avahi-ALSA-sysconfdir:/etc"

On a side-note, I have another RPi 4 running a slightly older Raspbian (also "Raspbian GNU/Linux 10" but uname -a shows "Linux rpi2 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux") also with a HiFiBerry DAC+ Pro, and shairport-sync version "3.3.7-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc". This hasn't had any problem at all but I also have not updated the OS (apt upgrade) since discovering the problem on rpi1 as this is my last working combo ! There is no other process running on this RPi currently, though it is destined to probably run Nextcloud

If you have any suggestions how I can troubleshoot this (I've gone through the Troubleshooter here but haven't messed with any latency settings as it has been working fine until now), or any logs I can provide, please let me know. Am I able to down-grade/reinstall an older version of the software ? Sorry, I can't figure out how to get to an older version for the "git clone" command which is I suspect what I need to do (can I copy the folder from my other RPi?)
Thank you!
Jean

**Comment by mikebrady** [comment]
Thanks for the post. This is slightly reminiscent of a situation I had with a really very good IQaudIO DigiAmp+ running on a Pi that was updated incrementally. One day, the amplifier stopped working properly and I even contacted one of the developers of the driver used. It seems that the incremental updating omitted or changed a crucial component -- I still don't know which. By erasing the SD card and starting over, my problem disappeared.

So, my suggestion it to build a new system, maybe on a separate SD card, and see if the problem disappears with it.

**Comment by cleverer** [comment]
Also having those issues and using a HiFiBerry Amp2. Usually after a reboot, the audio works fine, but there is about 1s delay when streaming to two targets from my Mac Pro.

Will try recreating the image (fortunately I already built a custom [pi-gen](https://github.com/RPi-Distro/pi-gen) setup).

**Comment by mikebrady** [comment]
Good stuff. Just remember that there is an approximately two second delay inherent in Airplay.

**Comment by durwin99** [comment]
I haven't been able to rebuild the system config yet due to the RPi running pi-hole being our DNS & print server so I have to find time to do that out of hours. (Alternately, can I build the OS & software on another RPi4 & swap the SD card without issue?)
What I *have* done is to switch shairport-sync to use the RPi audio out (hw:0) and that has been working fine for a few days now, so it does look like something has recently changed with the HiFiBerry hardware driver/software support. If I can figure out how to test audio direct out of the DAC+ then I can discount shairport-sync if that is still messed up - it looks like maybe aplay can do this...
Also, the HiFiBerry cards had issues with the hardware description/device tree in linux5.4 requiring the eeprom to be ignored, perhaps something has changed again in a later kernel - I need to reverse the boot/config.txt change and see if that fixes it.
Will update when I find out more

**Comment by mistakenideas** [comment]
I may be having the same/a similar problem. In the last couple of weeks audio started becoming garbled and stuttering when streamed through shairport-sync. This only happens after about a day of uptime and is resolved by a reboot, just restarting shairport-sync does not resolve it. Before this things have been running smoothly for many months.

Does this sound similar to your issue?

Some technical details:
RaspberryPi 3 with an iQAudio DAC running DietPi which is based upon Raspbian GNU/Linux 10 (buster)
Linux Loft-Stereo 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

I initially thought this may be related to the firmware change mentioned in this issue https://github.com/Hexxeh/rpi-firmware/issues/257
However since getting the fix my problem hasn’t gone away, although I have narrowed it down to affecting only shairport-sync as playing audio through other sources (directly with forked-daapd rather than via shairport-sync or directly with aplay) is unaffected.

**Comment by cleverer** [comment]
Reinstalled from a fresh image. So far so good, no distorted audio. Will check back again after the PI has been running for some time.

As a side note (I''m aware of the inheret Airplay delay): before the updates Apple Music/iTunes used to sync the Mac Pro and shairport sync and the multiroom experience was great. Now when you walk between rooms they're out of sync…

**Comment by durwin99** [comment]
> I may be having the same/a similar problem. In the last couple of weeks audio started becoming garbled and stuttering when streamed through shairport-sync. This only happens after about a day of uptime and is resolved by a reboot, just restarting shairport-sync does not resolve it. Before this things have been running smoothly for many months.
> 
> Does this sound similar to your issue?

That's exactly the same symptoms I'm getting - it's works great after reboot for up to a day, then I get garbled audio (more noticeable with streaming a podcast) or basically no audio (music). You have different hardware to me so that's interesting, but you're on 5.10.x kernel I see... my other RPi4 is running 5.4.x kernel and has no problem whatsoever, though I haven't updated it now for 2-3 months so it could be any of those pending updates. If I knew how to clone the SD card I would do so and update that one to see what happens - will do some research on that!

As I mentioned earlier, I get no dropouts using the inbuilt audio out from the Pi using shairport-sync, even after 3-4 days. I've yet to test audio through the DAC using other means...

**Comment by cleverer** [comment]
I'm also on Kernel `5.10.17-v7+`.

It should be quite easy to clone a sd-card with [balenaEtcher](https://www.balena.io/etcher/)

**Comment by durwin99** [comment]
> It should be quite easy to clone a sd-card with [balenaEtcher](https://www.balena.io/etcher/)

Thank you, that's a good idea!

> I'm also on Kernel 5.10.17-v7+.

Looking at the issues listed here, I think there's something going on with either the latest kernel versions or RPi firmware: [https://github.com/Hexxeh/rpi-firmware/issues](url)

**Comment by cleverer** [comment]
Well, the clean reinstall did not help. After the night, the audio was garbled again.

I'm downgrading the kernel now and will report back again. (According to [this](https://www.markjunghanns.de/index.php/2017/12/27/raspberry-pi-kernel-upgraden-downgraden/), it can easily be done with `sudo rpi-upgrade 43022f5adbbf5d6e05ea0e022a3090c2c9feff7c`, with the hash corresponding to one of the last commits using the old kernel.)

**Comment by cleverer** [comment]
Huh, that was quicker than expected. Downgrading did indeed fix the issues of my multiroom not in sync. I'm assuming it also fixes the garbled audio, but only time will tell.

Also: I'm not an expert regarding linux/raspbian, so **try the kernel downgrade at your own risk**! Also, downgrading a kernel this way is certainly not a permanent solution, but rather a temporary workaround.

I suspect some changes in the new kernel broke the magic stuff for third party DACs that gives shairport-sync it's name. Unfortunately I'm not deep enough into C and the kernel to debug this further.

@mikebrady is there anything I/we can do to help resolve this issue? I'd be happy to try out debug builds and provide further log data.

**Comment by mikebrady** [comment]
Thanks for all this information, everyone. It's really puzzling.

One idea -- a shot in the dark, really -- is to set the Shairport Sync `alsa` configuration setting `use_precision_timing` to `"off"` and see if it makes any difference.

**Comment by mistakenideas** [comment]
I’ve just been gathering some logs, so my system is in a ‘failed’ state and setting use_precision_timing to no and restarting the shairport-sync service solved the problem for me. Thanks @mikebrady 

Thanks @cleverer for confirming it was a firmware change that broke things.

I’m still interested to get to the bottom of what in the firmware has changed things here, maybe we can use rpi-update to narrow it down to a specific change? Or is there more info we can collect here to better report this to the firmware people?

**Comment by mikebrady** [comment]
Glad to hear that it did the trick -- I better recheck the software activated by the `use_precision_timing` code before we go to the firmware people!

**Comment by cleverer** [comment]
Can confirm as well, that was a sniper shot in the dark! 🎉

As a side note, I think the comment here is off (default seems to be auto according to code):
https://github.com/mikebrady/shairport-sync/blob/54cb9de1836fcb764bbae7397b6f79899f674268/common.h#L256

**Comment by mikebrady** [comment]
Thanks. According to the confit file, the default is “auto”. It would’ve be the first out-of-date comment I’ve ever seen or made! It’ll take a few days to track this down, I’m afraid.

**Comment by cleverer** [comment]
> Thanks. According to the config file, the default is “auto”. It wouldn’t have been the first out-of-date comment I’ve ever seen or made! It’ll take a few days to track this down, I’m afraid.

Yes, config seems to be correct. Just wanted to let you know, but not expecting a change here (after all it is just an internal code comment…)

Actually on second thought, I think the comment might even be correct, as an uninitialized variable would be all zeroes… so the variable will default to no. Sorry for the confusion and diverging from the actual subject!

**Comment by mistakenideas** [comment]
When the issue is occurring, a couple of notable things seem to pop up in the logs, the normally intermittent and benign No SCLK message is spammed constantly and the same messages from shairport repeat for a while as follows:

```
Mar 08 09:29:41 kernel: pcm512x 1-004c: No SCLK, using BCLK: -2
Mar 08 09:29:41 shairport-sync[13747]:          0.025687188 "audio_alsa.c:721" alsa: precision timing selected for "auto" mode
Mar 08 09:29:41 shairport-sync[13747]:          0.000095208 "audio_alsa.c:1724" do_open() set_mute_state
Mar 08 09:29:41 shairport-sync[13747]:          0.000024323 "audio_alsa.c:1777" alsa: play() -- opened output device
Mar 08 09:29:41 shairport-sync[13747]:          0.000021250 "audio_alsa.c:1782" alsa: play() -- alsa_backend_state => abm_playing
Mar 08 09:29:41 shairport-sync[13747]:          0.000536146 "player.c:1156" Run a bit past the exact start time by 1101614722 frames with a DMar 08 09:29:41 shairport-sync[13747]:          0.000072500 "audio_alsa.c:1833" alsa: flush() -- closing the output device
Mar 08 09:29:41 shairport-sync[13747]:          0.001710000 "audio_alsa.c:1751" alsa: do_close() -- closing alsa handle
Mar 08 09:29:41 shairport-sync[13747]:          0.000095677 "audio_alsa.c:1835" alsa: flush() -- alsa_backend_state => abm_disconnected.
Mar 08 09:29:41 shairport-sync[13747]:          0.000205729 "player.c:1016" pffr
Mar 08 09:29:41 kernel: pcm512x 1-004c: No SCLK, using BCLK: -2
Mar 08 09:29:41 shairport-sync[13747]:          0.025631094 "audio_alsa.c:721" alsa: precision timing selected for "auto" mode
Mar 08 09:29:41 shairport-sync[13747]:          0.000094843 "audio_alsa.c:1724" do_open() set_mute_state
Mar 08 09:29:41 shairport-sync[13747]:          0.000025105 "audio_alsa.c:1777" alsa: play() -- opened output device
Mar 08 09:29:41 shairport-sync[13747]:          0.000021354 "audio_alsa.c:1782" alsa: play() -- alsa_backend_state => abm_playing
Mar 08 09:29:41 shairport-sync[13747]:          0.000532031 "player.c:1156" Run a bit past the exact start time by 1101614370 frames with a DMar 08 09:29:41 shairport-sync[13747]:          0.000043177 "audio_alsa.c:1833" alsa: flush() -- closing the output device
Mar 08 09:29:41 shairport-sync[13747]:          0.001710990 "audio_alsa.c:1751" alsa: do_close() -- closing alsa handle
```

And then the sync error messages appear 
```
Mar 08 09:29:42 kernel: pcm512x 1-004c: No SCLK, using BCLK: -2
Mar 08 09:29:42 shairport-sync[13747]:          0.025595833 "audio_alsa.c:721" alsa: precision timing selected for "auto" mode
Mar 08 09:29:42 shairport-sync[13747]:          0.000092344 "audio_alsa.c:1724" do_open() set_mute_state
Mar 08 09:29:42 shairport-sync[13747]:          0.000023906 "audio_alsa.c:1777" alsa: play() -- opened output device
Mar 08 09:29:42 shairport-sync[13747]:          0.000021823 "audio_alsa.c:1782" alsa: play() -- alsa_backend_state => abm_playing
Mar 08 09:29:42 shairport-sync[13747]:          0.000401719 "player.c:1278" prsm
Mar 08 09:29:42 shairport-sync[13747]:          0.147834896 "player.c:634" request resend of 64 packets starting at seqno 6160.
Mar 08 09:29:42 shairport-sync[13747]:          0.010738385 "player.c:634" request resend of 46 packets starting at seqno 6226.
Mar 08 09:29:42 shairport-sync[13747]:          0.198364219 "player.c:2273" Large positive sync error: 1101604157.
Mar 08 09:29:42 shairport-sync[13747]:          0.078941198 "player.c:2148" Player: packets out of sequence: expected: 6098, got: 6107, with Mar 08 09:29:42 shairport-sync[13747]:          0.022382552 "player.c:2273" Large positive sync error: 1101603802.
Mar 08 09:29:42 shairport-sync[13747]:          0.084263906 "player.c:2148" Player: packets out of sequence: expected: 6111, got: 6120, with Mar 08 09:29:42 shairport-sync[13747]:          0.022718854 "player.c:2273" Large positive sync error: 1101603444.
Mar 08 09:29:42 shairport-sync[13747]:          0.078002083 "player.c:2148" Player: packets out of sequence: expected: 6124, got: 6133, with Mar 08 09:29:42 shairport-sync[13747]:          0.022688073 "player.c:2273" Large positive sync error: 1101603094.
```

If more complete logs or any other details would help, let me know. I realised I forget to mention the version of shairport-sync I’m using is the latest from raspbian rather than the latest here.

**Comment by giggywithit** [comment]
I had this issue a long time ago FYI
Was too busy working on other things to track it all down
Good to see it's being handled

**Comment by durwin99** [comment]
Thank you for the "shot in the dark" Mike ! I firstly just restarted shairport-sync while the problem was present, it didn't make any difference. I then set use_precision_timing to "no" in the config and restarted the service and it is working now. I shall have to wait the usual 24+ hours to be sure... If you have time, I would be interested to hear whether you can work out the cause of the problem. I don't know the functionality this setting enables, but given the issue, would it be worth setting the default to "no" for future releases ?
Regards,

**Comment by mistakenideas** [comment]
After a bit of faffing when I used a firmware version that wouldn’t boot (whoops) I’ve now got a couple of RPis with DACs one on the old and one on the new kernel/firmware versions.

@mikebrady Would tests on different firmware versions using the audio_time tool from alsa-lib be useful? I’ve got it compiled and have been reading https://www.kernel.org/doc/html/latest/sound/designs/timestamping.html although frankly my knowledge level of linux audio is very much closer to dangerous than useful :)

**Comment by ben-willmore** [comment]
I have two RPis which have been running shairport-sync seamlessly for numerous months. One is running raspian buster with kernel `5.10.17+` and has recently started glitching with this same pattern -- fine after reboot, then glitches the next day. Restarting shairport-sync doesn't help, nor does upgrading to the latest version. However, I set `use_precision_timing = "no"`, and this seems to have fixed it for now. I haven't tried downgrading the firmware.

The other RPi is running raspian stretch with kernel `4.19.66+`, and is working fine as usual.

**Comment by mikebrady** [comment]
That's useful, thanks. I will look at the problem Real Soon Now. It may well be a bug in Shairport Sync, as I moved the timing code from a fixed-point 64-bit representation a la NTP to a nanosecond-based 64 bit instead. This may have caused, shall we say, an infelicity in the precision timing code.

**Comment by ben-willmore** [comment]
Thanks for your reply! I had these problems with version 3.3.2, which (I think) pre-dates the timing representation change, as well as with current master.

(However, with precision timing enabled and the glitch occurring, my logs are full of `player.c:2213" Underrun of -108279589 frames reported, but ignored.` which does sound a bit like the kind of problem you are suggesting.)

**Comment by giggywithit** [comment]
I had been off shairport for a while and recently installed again and found it unusable. The audio is constantly choppy. Once upon a time it would chop for maybe 7 seconds every few days or so streaming from a variety of sources on a variety of networks. 

I use the iqaudio driver as well

**Comment by mistakenideas** [comment]
> This may have caused, shall we say, an infelicity in the precision timing code.

That’s a wonderful description @mikebrady :) Looking at the release notes did the changes you mention arrive in 3.3.7? https://github.com/mikebrady/shairport-sync/blob/master/RELEASENOTES.md#version-337

Like @ben-willmore I’m seeing these problems on an earlier version, I’m running 3.3.6.

**Comment by mikebrady** [comment]
So, just turning to this problem now. Can anyone cause it to happen really quickly? Is so, the receipt would be useful.

**Comment by durwin99** [comment]
I've just now commented out the use_precision_timing = "no" line & restarted but it will not happen immediately I think, working fine right now. When it goes, what info would you like?

**Comment by mikebrady** [comment]
Thanks for the quick response.

Actually I have found something which I am struggling to explain, but it does look as if the underlying driver has changed its behaviour.

Specifically, it looks as if a call to `snd_pcm_status_get_driver_htstamp` now returns an elapsed time since some time in the recent past -- maybe since the driver was opened. AFAIK this is a new behaviour; it used to be based off CLOCK_MONOLITHIC. I was using it because it looked as if it might provide a tiny bit of extra precision.

However, I'm not sure which behaviour is correct (maybe both are) -- the [alsa documentation](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___status.html#ga6ee47c7a98005629ec691eae4b7f1b0e) is rather opaque.

Anyhoo, I've pushed an update in the `development` branch that reinstates the precision timing code, but without using the `snd_pcm_status_get_driver_htstamp` call. If you got a chance to try it out, that would be great.

**Comment by mistakenideas** [comment]
With a RaspberryPi that is in a ‘failed state’ (which seems to be one that has been running for over 24 hours and is running the 5.10.17 kernel and firmware) enabling and disabling use_precision_timing and restarting shairport-sync then playing audio seems to be enough to enable or disable the problem. At least that’s what’s working for me (just tested to confirm). 

Disabling use_precision_timing and restarting shairport-sync OR downgrading the kernel/firmware seem to resolve the issue permanently. Rebooting the Pi resolves the issue temporarily.

I’m afraid I don’t have any quicker repro steps than ‘wait for a day’ for a system that has been rebooted. 

What else can we do to help?

**Comment by ben-willmore** [comment]
The `development` branch fixes the glitches for me with `use_precision_timing` enabled (and I can switch back to the glitched state by returning to `master`). Thanks!!

**Comment by mikebrady** [comment]
Super. Thanks for the update.

**Comment by ben-willmore** [comment]
I meant to add -- the synchronisation between two Pis in neighbouring rooms is perfect to my ears (though that is also the case with `use_precision_timing` disabled). I haven't done any objective tests but a click track sounds good.

**Comment by mikebrady** [comment]
Thanks, Ben. TBH, I'm not really too sure if the precision timing is any better. A while back, it made a really big difference in the Raspberry Pi's built-in DAC, but that has been fixed since.

**Comment by giggywithit** [comment]
Is there anything I should wait for before giving it another shot? What settings should I use with an IQ audio driver dac?

Thx

**Comment by mikebrady** [comment]
Nothing to wait for — just pull the latest update from the `development` branch...

**Comment by giggywithit** [comment]
Alright thx
What settings do you prefer with your IQ DAC?

**Comment by mikebrady** [comment]
So, I have an IQaudIO DigiAmp+ and this is the overlay entry in `/boot/config.txt`:
```
dtoverlay=iqaudio-dacplus,unmute_amp
```
I use the mixer called `"Digital"` for volume control, and no other special settings.
Is that the kind of information you are looking for?

**Comment by giggywithit** [comment]
I just use the driver for the IQaudio in my project as I have built my own entire system from DAC to speakers.
Ive actually got my own overlay now for the project and within the overlay it loads the IQaudio driver..
I use the same settings as you within, but I am reading above a lot of talk about precision timing and potential issues with settings

Thanks

**Comment by mikebrady** [comment]
Wow, that looks fantastic. Lovely looking hardware and 300w of clean power per channel is insane!

**Comment by giggywithit** [comment]
Thanks Mike
Lemme know if you want one
I'll be most likely only making the mini chassis versions as the wider chassis is only for using a different make transformer and unnecessary for the time being.
Gonna start off offering them between 3-4k depending - 250w and 350w /ch versions.
I think they will do well locally.
I can do you personally about half that price.
Everything going nicely so far..
It's dual use right now raspotify and sh-sync and actually was just functioning using sh-sync and I didn't even know.
I love being able to use it for watching movies etc..
Thank you super

**Comment by mikebrady** [comment]
Just FYI, I found another bug in the `alsa` backend which would very occasionally cause it simply to abort with an obscure `alsa` subsystem `assert` error. Fixed and pushed into the `development` branch.
