### ISSUE TITLE
AppleTV, Airplay, Youtube - no Audio

### ISSUE THREAD

**Issue by mtavares77** [mikebrady/shairport-sync#1159]
We are observing that when we tried to play music through the  YouTube on the AppleTV via Airplay, it only plays for 10s and stops.  In the Apple forum some user mentioned that the problem is related to the fact that YouTube only supports Airplay2.  

I am using the Airplay renderer hosted on MoOde installed in a RPi4.

https://discussions.apple.com/thread/251...4742964022

This issue started on the tvOS 14.

If we tried to use the YouTube on the iPhone  and mirror it on the AppleTV is works perfectly.

Thanks in advance by your support.

Best Regards,

QJA

**Comment by mikebrady** [comment]
Thanks for the post. This seems to be a problem with the YouTube app and has been reported before — see #1092.

**Comment by mikebrady** [comment]
BTW, the Apple Discussions link seems to be broken (?)

**Comment by mtavares77** [comment]
@mikebrady 

Thanks by your comments.

It seems that this problem is similar to the #1092 

However, you should consider that the problem is solved for the people that equipments operate via Airplay2.

I am posting the Apple discussion link again for analysis.

https://discussions.apple.com/thread/251934651

Regards,

QJA

**Comment by ophilips** [comment]
@mikebrady, I just tested the new development version with Airplay 2 and everything works now in the YouTube App on AppleTV. With the stable version audio stops after some seconds when watching a video.

**Comment by mikebrady** [comment]
@ophilips, thanks for the report. Just to clarify, by the "stable" version, do you mean the regular "classic" AirPlay 1 build from the `master` branch?

**Comment by ophilips** [comment]
@mikebrady, I just wanted the clarify that I also had the issue before upgrading from master branch (Airplay 1) to development branch (with Airplay 2). For now everything works for me with that amazing new version even if its still in development.

**Comment by mikebrady** [comment]
@ophilips, that's great -- thanks again for the report!

**Comment by mtavares77** [comment]
@ophilips , Very good news and great job. Airplay 2 solves the issue.  Do you have an idea when the Airplay 2 version release date?

Thank you very much. QJA

**Comment by ophilips** [comment]
@mtavares77, I didn’t implement airplay 2. You should thank @mikebrady for that. if you need more informations just check the development branch.
After testing the development version for a week now I found some different issues with the youtube app (had to reconnect to shairport-sync when a commercial was shown) but that’s a completely different issue. Maybe youtube switches the audio output between normal playback and commercials.

**Comment by mtavares77** [comment]
@ophilips 
Thanks by your feedback and work to test this new airplay release.

@mikebrady 
Congratulations by your great work developing the Airplay 2 version. Very nice. We expect that it will be released soon.

Thank you! QJA

**Comment by microfx** [comment]
> @mtavares77, I didn’t implement airplay 2. You should thank @mikebrady for that. if you need more informations just check the development branch.

Quite hard to find informations on the dev branch... where can I find it / install it?

**Comment by microfx** [comment]
I have the same problems as OP - just wanted to let you know that I was convinced it wouldn't be a good idea to try out Dev branche since Apple TV was not fully supported - this thread gave me hope to try it out! Maybe remove/rephrase those words from the README so that people won't be scared.
