### ISSUE TITLE
Airplay audio and streaming formats

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#116]
Hi Mike,

What audio and streaming formats does Airplay protocol use? 

I recall reading that it transcodes source to 16/44.1 ALAC then packetizes it in UDP/RTP (RAOP) for streaming to destination.

Regards,
Tim

**Comment by mikebrady** [comment]
Hi Tim. You're right – everything is 16/44.1 ALAC. There's a fair bit of unofficial documentation out there about it, e.g. http://nto.github.io/AirPlay.html.

**Comment by moodeaudio** [comment]
Thanks Mike. Thats the spec I remember reading :-)
