### ISSUE TITLE
Show up on phone but no audio when i connect.

### ISSUE THREAD

**Issue by ICYBAWSS** [mikebrady/shairport-sync#1160]
It shows up on my iPhone but when i connect to it and play something no audio comes through.

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest that you take a look at the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) guide -- perhaps there is something there that can help you.

**Comment by ICYBAWSS** [comment]
I went in the troubleshooting.md and followed the ufw instructions but
nothing changed. I am using a pi4 btw

**Comment by mikebrady** [comment]
Thanks. In that case, the problem must lie elsewhere. There are lots of hints and explanations in the Issues, both open and closed, and the Pi4 is a very common platform for Shairport Sync. If you still have no luck, please take a look at [REPORTING ISSUES](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) to get an idea what kind of information contributors might need.
