### ISSUE TITLE
Multi-Room Audio using single Raspberry Pi

### ISSUE THREAD

**Issue by techgeek77** [mikebrady/shairport-sync#1161]
Hi,

So my current setup is four USB audio cards connected to a single Raspberry Pi. These audio cards are then connected to individual amps and they go to four different rooms. Its used for various things even regular announcements manually played, scheduled via cron, etc. I also wanted to add AirPlay functionality to it. My objective being able to stream audio to individual speakers or all speakers. Now I achieved this with no issue by running multiple instances of the service following comments over here. It works like a charm when the backend is ALSA. Then I realized I need to run one instance that connects to all speakers since this is needed for the announcements. I tried playing around with dmix, etc but in the end I realized PulseAudio was the way to go as it made so much more easier. 

But now, I realize the pa backend doesn't have so much options as ALSA to select the specific audio device for that instance of the service. I tried to run ALSA and PulseAudio together but since ALSA only accepts one client, PulseAudio is already hooked so Shairport-Sync throws an error saying resource is busy. 

How do we go about this to have multiple Shairport-Sync instances that use pa backend but has a hardcoded audio device selected for each. I do need one that streams to all of them together as well.

Thanks for any suggestions/input.

**Comment by mikebrady** [comment]
Thanks for the interesting post. Actually the PulseAudio has an (unfortunately) undocumented backend setting called `sink`, which is supposed to allow you to specify which named PulseAudio output sink to direct the audio to. Obviously, it's untested, and may not do what you want anyway, but worth a try.

The sample configuration file has been updated in the `development` branch with the following change:
```
pa =
{
//	server = "host"; // Set this to override the default pulseaudio server that should be used.
//	sink = "Sink Name"; // Set this to override the default pulseaudio sink that should be used. (Untested"
//	application_name = "Shairport Sync"; //Set this to the name that should appear in the Sounds "Applications" tab when Shairport Sync is active.
};
```
Please let us know if it is of any use.

**Comment by techgeek77** [comment]
Thank you for the prompt response! Do I need to re-download and compile Shairport Sync from dev branch or will this work with existing service?

**Comment by techgeek77** [comment]
Also for the name of the sinks, Shairport-sync -h does not provide this right? I have to list sinks using 
pacmd list-sinks 
and use the name written there?

Thanks

**Comment by mikebrady** [comment]
Yeah, you're right on both counts; this facility is in the current `master` branch and `shairport-sync -h` does not list PulseAudio sinks, so using `$ pacmd list-sinks` would be the way to go.

**Comment by techgeek77** [comment]
Great! Thanks for the information. I will test this out within the course of the next 24 hours and close this issue!

**Comment by techgeek77** [comment]
Im running into issues. This is the output from `$ systemctl status shairport-sync` :

`systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-03-09 14:16:37 +0530; 3s ago
  Process: 1434 ExecStart=/usr/local/bin/shairport-sync (code=exited, status=1/FAILURE)
 Main PID: 1434 (code=exited, status=1/FAILURE)

Mar 09 14:16:37 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Mar 09 14:16:37 raspberrypi shairport-sync[1434]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
Mar 09 14:16:37 raspberrypi shairport-sync[1434]: fatal error: failed to connect to the pulseaudio context -- the error message is "Connection refused".
Mar 09 14:16:37 raspberrypi systemd[1]: shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
Mar 09 14:16:37 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
`

It is looking like Pulseaudio has some issues... Any ideas?

**Comment by rogersmj** [comment]
@techgeek77 I'm wanting to do the exact same thing -- single RPi with multiple audio outs that go to different amps, and have each of those audio outs exposed as AirPlay speakers so someone can completely control zone on/off and volume from their iPhone now playing card. Did you ever get this working?

**Comment by techgeek77** [comment]
I ran out of time I had to experiment and focusing on work right now. I plan on picking up this project sometime later. 

This idea can be completely executed using ALSA backend but one issue is that you can’t create one virtual device to play all speakers. This is why I went with PA so that I can easily create a sink for that. But I think the issue lies with getting the names right for PA. I tried many things but I have a feeling the main issue is that the name of the sink i provide in the Shairport config is not what it wants….

**Comment by jgabriel98** [comment]
Ive just dropped in this issue.
But maybe you can use snapcast to control if the audio goes to specific(s) instance(s) or all of them.

Install snapserver and two (or more) snapclients and then open the snapserver web on you browser (or download the android app), then you will get what i mean (it's very intuitive to use).

Snapcast and shariport-sync work together vey nicelly. 
If you have any questions about how to install/setup those two to work together, you can check the instalation script from my repo: [spotifypiHome](jgabriel98/spotifypiHome)

**Comment by noelhibbard** [comment]
> Ive just dropped in this issue.
> 
> But maybe you can use snapcast to control if the audio goes to specific(s) instance(s) or all of them.
> 
> 
> 
> Install snapserver and two (or more) snapclients and then open the snapserver web on you browser (or download the android app), then you will get what i mean (it's very intuitive to use).
> 
> 
> 
> Snapcast and shariport-sync work together vey nicelly. 
> 
> If you have any questions about how to install/setup those two to work together, you can check the instalation script from my repo: [spotifypiHome](jgabriel98/spotifypiHome)

This is similar to what I was doing before shairport-sync added support for AirPlay2. I also wrote a homebridge plugin to turn the snapclients on and off and adjust volume. It worked well but the new AP2 support is way better.
