### ISSUE TITLE
How to contribute to wiki?

### ISSUE THREAD

**Issue by p3ck** [mikebrady/shairport-sync#1162]
Hello,

I'm a long time fan of shairport-sync and I currently build it for Fedora and Epel.  I have put together some ansible scripts that make it easy to deploy on rpi3 or 4 with iqaudio or hifiberry hats.

https://github.com/p3ck/ansible-shairport

You can reference it from the wiki if you like?

**Comment by mikebrady** [comment]
Thanks for your kind offer, Bill. Can I link to it from the README? Would that be okay?

**Comment by p3ck** [comment]
That would be fine.  

Thanks!

**Comment by mikebrady** [comment]
Just done that now, Bill. Let me know if you think the wording should be changed. Many thanks.
