### ISSUE TITLE
Local installation should put systemd unit into `/usr/local/`

### ISSUE THREAD

**Issue by herrernst** [mikebrady/shairport-sync#1163]
When installing "locally", i. e. by `make install`, the systemd unit file should also be into `/usr/local/`.

Like the default directory (without setting an option with `./configure`) for the config file is `/usr/local/etc/` and `/usr/local/bin/` for the binary, the default directory for the systemd service unit should be `/usr/local/lib/systemd/system/`, not `/lib/systemd/system/`, which is reserved for the package manager [as described here in the systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#id-1.8.4) and for example not writable in a read-only rootfs system.

**Comment by mikebrady** [comment]
Thanks for the post. I think I looked at this before and found that it didn't quite correspond with the real world.

**Comment by herrernst** [comment]
Thanks for your feedback. All I can say is it did work for me when manually changing the directory.

**Comment by mikebrady** [comment]
Thanks. I may revisit it -- it's lost in the mists of time. And maybe I didn't fully understand it.
