### ISSUE TITLE
using echo in "run_this_.."

### ISSUE THREAD

**Issue by NNEU-1** [mikebrady/shairport-sync#1164]
Hello,

I'm trying to use the "run_this_.." hooks in order the write the current status to a pipe. 

`run_this_before_play_begins = "/bin/echo -n 'AirPlay Playing' > /statuspipe"`

Unfortunately, no success. 
The problem seems to be this particular command. Scripts can be run with no problem. 
Other commands also seem to work fine, such as:

`run_this_before_play_begins = "/bin/systemctl --user restart spotifyd"`

I've also tried the same command to write to a text file, but there is no output.

Any feedback appreciated !

**Comment by p3ck** [comment]
redirection is something you get from running in the shell.  I'm sure shairport is not using a shell to execute the commands.  you could try:

```
run_this_before_play_begins = "/bin/bash -c ''/bin/echo -n 'AirPlay Playing' > /statuspipe''"
```

Notice the single quotes are escaped

**Comment by NNEU-1** [comment]
Thanks for your reply !

`run_this_before_play_begins = "/bin/bash -c '/bin/echo -n AirPlay Playing > /statuspipe'"`

Doesn't work unfortunately. 

I don't understand why one of the mentioned commands works and the other one doesn't.

**Comment by NNEU-1** [comment]
Oops.. My apologies, it actually does work. 

I tried it before the edit; 
`run_this_before_play_begins = "/bin/bash -c '/bin/echo -n AirPlay Playing > /statuspipe'"`
works

`run_this_before_play_begins = "/bin/bash -c ''/bin/echo -n 'AirPlay Playing' > /statuspipe''"`
doesn't
