### ISSUE TITLE
Guidance on using jackd

### ISSUE THREAD

**Issue by lowflyerUK** [mikebrady/shairport-sync#1165]
Hi!

Thanks for shairport-sync. It is fantastic.

I am trying to get shairport-sync to run using jackd (I want to mix its output with output from a midi instrument using fluidsynth). Everything seems to run, but I get no sound. Is there a step-by-step guide somewhere?

What I have:
Headless raspberry Pi with i2s sound HAT. Onboard audio socket is disabled in /boot/config.txt so hw:0 is the i2s HAT.
Works fine with shairport-sync (from raspbian) using alsa.

What I have done:
Installed jackd2.
`sudo mount -o remount,size=128M /dev/shm`
Tested using fluidsynth. Works fine.
`sudo apt remove --purge shairport-sync`
installed shairport-sync from git including libjack-jackd2-dev. It compiles fine with:
`./configure --sysconfdir=/etc --with-alsa --with-jack --with-avahi --with-ssl=openssl --with-metadata --with-systemd`
launch jackd in one terminal with:
`jackd -p16 -v -d alsa --device hw:0 --rate 44100 --period 64`
and launch shairport-sync in another terminal with:
`/home/pi/shairport-sync/shairport-sync -v`
Connect to shairport-sync from iPad and play something.

What I get:
No sound :(
Lots of debug info from jackd with no obvious errors.
Lots of debug info from shairport-sync in syslog with no obvious errors.

Any ideas very gratefully received! Many thanks.

**Comment by mikebrady** [comment]
Thanks for the post. I'm afraid I don't have much expertise in this. Perhaps someone else could contribute...
