### ISSUE TITLE
iOS audio stops playing after 5 to 20 minutes

### ISSUE THREAD

**Issue by mrfantastico** [mikebrady/shairport-sync#1166]
Hi,

```
3.3.8rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
```

```
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-15 04:22:46 GMT; 12min ago
 Main PID: 533 (shairport-sync)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/shairport-sync.service
           └─533 /usr/local/bin/shairport-sync

Mar 15 04:29:03 hi-fi shairport-sync[533]:         19.952770887 "rtp.c:138" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.1,    21300.8,   302433.6.
Mar 15 04:29:23 hi-fi shairport-sync[533]:         19.968056849 "rtp.c:138" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7978.5,    12079.3,   187944.5.
Mar 15 04:30:41 hi-fi shairport-sync[533]:         78.060751779 "mdns_avahi.c:149" (Browser) REMOVE: service
Mar 15 04:30:41 hi-fi shairport-sync[533]:          0.000313749 "mdns_avahi.c:149" (Browser) REMOVE: service
Mar 15 04:31:39 hi-fi shairport-sync[533]:         57.211444188 "rtsp.c:665" Connection 1: getting Error 11 -- EAGAIN from a blocking read!
Mar 15 04:31:42 hi-fi shairport-sync[533]:          3.002686448 "rtsp.c:338" Connection 1: As Yeats almost said, "Too long a silence / can make a stone of the heart".
Mar 15 04:31:42 hi-fi shairport-sync[533]:          0.000676967 "audio_alsa.c:1836" alsa: flush() -- closing the output device
Mar 15 04:31:42 hi-fi shairport-sync[533]:          0.005296415 "audio_alsa.c:1754" alsa: do_close() -- closing alsa handle
Mar 15 04:31:42 hi-fi shairport-sync[533]:          0.000634885 "audio_alsa.c:1838" alsa: flush() -- alsa_backend_state => abm_disconnected.
Mar 15 04:31:42 hi-fi shairport-sync[533]:          0.002833855 "rtsp.c:2595" Connection 1: terminated.

```

I'm seeing a similar issue to what was reported in #1148 with iOS devices (reproduced with iOS 14 and 12) playing fine for a while before the Pi stops playing and iOS gives an "unable to connect" error. I'm running shairport-sync on a Raspberry Pi 3 with Raspbian stretch. I followed [the steps](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) for the simple Linux installation after doing a fresh OS install. I've also observed this issue on Raspbian buster and Ubuntu Server 20.04. Airplay playback from two separate macs works just fine for hours.

Usually the issue happens after 5 minutes or so every time I try to play something, but twice I've had the iOS device continue to play for over 20 minutes without issue.

I have a log with four instances of the playback issue if helpful, but each occurance is associated with a similar set of lines to what's above about the "Error 11".

I tried the steps in the troubleshooting for the wifi power management every time I have set this up across OSes (did it again during this latest troubleshooting just to be sure). I also un-commented and increased the "audio_backend_buffer_desired_length_in_seconds" to 0.6 from 0.2 and rebooted. The last failure above still happened after both those changes.

I'm still getting iOS drops and can't figure it out.

**Comment by mikebrady** [comment]
Thanks for the post, and apologies for the delay. It really does sound like some kind of a network issue.
the line:
```
78.060751779 "mdns_avahi.c:149" (Browser) REMOVE: service
```
means that Shairport Sync could no longer "see" the player's advertisement for its Remote Control port, which further points to a loss of connectivity. If that's the case, it needs to be investigated. It could be a router setting or something like that.

For more troubleshooting, you could use `avahi-browse` on the Shairport Sync end to check that it continues to advertise the  Shaiport Sync AirPLay service (`_raop._tcp`) service, and to see if the aforementioned `_dacp._tcp` service is present and disappears when the problem recurs.

**Comment by mrfantastico** [comment]
Hi Mike,

Thanks for the response! avahi-browse shows that the Shairport Sync is showing two advertisements (IPv6 and IPv4) for AirTunes Remote Audio (_raop._tcp) and then that there are two advertisements (IPv6 and IPv4) for iTunes Remote Control (_dacp._tcp) as well. Running avahi-browse and recreating the issue does show the iTunes Remote Control advertisements disappearing after about 10-15 seconds of silence from the speakers while the song still shows as playing and aligning with when the iPhone finally says that it is unable to connect.

Looking through the last couple times this has happened,  it seemed to correspond to the wlan0 address expiring before getting a new address. So, I thought maybe shairport-sync was looking for the iPhone during that time and couldn't find it so it disconnected.

```
Mar 20 19:49:22 hi-fi shairport-sync[533]:         20.300121181 "rtp.c:138" Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8119.7,    20856.6,   138130.9.
Mar 20 19:49:32 hi-fi dhcpcd[528]: wlan0: expired address
Mar 20 19:49:32 hi-fi avahi-daemon[351]: Withdrawing address record
Mar 20 19:49:32 hi-fi dhcpcd[528]: wlan0: deleting route
Mar 20 19:50:34 hi-fi shairport-sync[533]:         72.215158796 "mdns_avahi.c:149" (Browser) REMOVE: service 
Mar 20 19:50:34 hi-fi shairport-sync[533]:          0.001084350 "mdns_avahi.c:149" (Browser) REMOVE: service 
Mar 20 19:51:08 hi-fi dhcpcd[528]: wlan0: adding route 
Mar 20 19:51:08 hi-fi avahi-daemon[351]: Registering new address record
Mar 20 19:51:35 hi-fi shairport-sync[533]:         61.103824427 "rtsp.c:338" Connection 8: As Yeats almost said, "Too long a silence / can make a stone of the heart".
Mar 20 19:51:35 hi-fi shairport-sync[533]:          0.000476980 "audio_alsa.c:1836" alsa: flush() -- closing the output device
Mar 20 19:51:35 hi-fi shairport-sync[533]:          0.005301243 "audio_alsa.c:1754" alsa: do_close() -- closing alsa handle
Mar 20 19:51:35 hi-fi shairport-sync[533]:          0.000475520 "audio_alsa.c:1838" alsa: flush() -- alsa_backend_state => abm_disconnected.
Mar 20 19:51:35 hi-fi shairport-sync[533]:          0.002571855 "rtsp.c:2595" Connection 8: terminated.
```

I set a static IP and turned off IPv6 router advertisements on the Pi and have since been playing music all day without issues. 😀
