### ISSUE TITLE
pops while playing audio with USB device

### ISSUE THREAD

**Issue by bob808** [mikebrady/shairport-sync#117]
Hello Mike,
I just installed shairport-sync on my raspberry pi B rev2 using the directions from here.
It seems that I get a random pop during listening. Doesn't matter what I listen to, I still get some pop once every 20 seconds or so. It's not fixed, I just averaged. Happens on youtube from browser and also when listening to flac files on VLC.
I adjusted the sampling rate to 44.1KHz in alsa config.
What else could I do?
I'm using a Focusrite Scarlett 2i4 usb card that seems to be supported by ALSA. I also have a USB hub that powers the card. I disabled the onboard ethernet so I can fully use the USB bandwidth. Still no change, I still have the random pops. 
cat /proc/asound/card0/stream0 outputs:
Focusrite Scarlett 2i4 USB at usb-20980000.usb-1.2.4, high speed : USB Audio

Playback:
  Status: Running
    Interface = 1
    Altset = 1
    Packet Size = 126
    Momentary freq = 44103 Hz (0x5.8348)
    Feedback Format = 16.16
  Interface 1
    Altset 1
    Format: S32_LE
    Channels: 4
    Endpoint: 1 OUT (ASYNC)
    Rates: 44100, 48000, 88200, 96000
    Data packet interval: 125 us

Capture:
  Status: Stop
  Interface 2
    Altset 1
    Format: S32_LE
    Channels: 2
    Endpoint: 2 IN (ASYNC)
    Rates: 44100, 48000, 88200, 96000
    Data packet interval: 125 us

**Comment by bob808** [comment]
I am waiting for a Digi board from Hifiberry, and I will use it's spdif output to my external DAC.
But for the moment I'm trying to use this USB card, and the experience is real bad. If I try it louder the pops are really annoying and actually I start worrying for my speakers.
Maybe there's an easy fix?

**Comment by mikebrady** [comment]
Thanks for the report. Just to be clear, are you talking about a Raspberry Pi 2 – that is, the new raspberry Pi with 4 USB ports and a 4-core processor, or are you talking about an early rev of the first Raspberry Pi B with 2 USB ports and a single-core processor?

Anyhow, some information from the log would be very useful. So, could you enable statistics and also set debug verbosity to 1 in the `/etc/shairport-sync.conf` file, play some music for maybe ten or fifteen minutes, preferably from iTunes and post the resulting log? Also could you post the result of `uname -a`?

**Comment by mikebrady** [comment]
Is it possible to run the card without the powered hub, do you think? Just thinking the the popping might be coming from the hub's power supply.

**Comment by bob808** [comment]
I am using the Raspberry Pi 1, with the single core processor.
I enabled the log, will post again later after I have the info from the log.
output of uname -a:
root@raspberrypi:/home/pi# uname -a
Linux raspberrypi 4.1.6+ #810 PREEMPT Tue Aug 18 15:19:58 BST 2015 armv6l GNU/Linux

**Comment by bob808** [comment]
I tried and the card did run powered from the PI, but I had some problems with that. Sometimes it would just fail to boot. The Pi's power supply would drop bellow 4.5VDC and that caused a world of problems.
I can play files on the pi without the pop anyway, the problem seems to be with shairport-sync.
I had loads more pops before I adjusted the sample rate from 48KHz to 44.1KHz, that took care of most of them but still have some once in a while.

**Comment by bob808** [comment]
This is the only thing that shairport-sync had to say in the log:

Aug 30 20:06:30 raspberrypi shairport-sync[2725]: exit...
Aug 30 20:06:31 raspberrypi shairport-sync[2976]: startup
Aug 30 20:06:31 raspberrypi shairport-sync[2976]: avahi: avahi_register.
Aug 30 20:06:31 raspberrypi shairport-sync[2976]: avahi: register_service.
Aug 30 20:06:31 raspberrypi shairport-sync[2976]: Avahi without metadata
Aug 30 20:06:55 raspberrypi shairport-sync[2976]: new RTSP connection.
Aug 30 20:06:55 raspberrypi shairport-sync[2976]: Play connection from device named "Bob’s MacBook Pro".
Aug 30 20:06:55 raspberrypi shairport-sync[2976]: Play connection from user agent "AirPlay/215.18".
Aug 30 20:06:55 raspberrypi shairport-sync[2976]: Active-Remote string seen: "3668530090".
Aug 30 20:06:55 raspberrypi shairport-sync[2976]: Connection from IPv4: 192.168.0.111:57601

**Comment by bob808** [comment]
Sorry but I don't know how to insert code snippets :/

**Comment by bob808** [comment]
Just noticed that playing more complex music, louder (from the laptop) I get pops more frequently.
And I can get them pretty much once every 3 seconds or so if I put the Raspberry to work, like searching for a file.

**Comment by mikebrady** [comment]
Sorry for the delay. Okay, what I meant about the statistics was this: There is a settings file at `/etc/shairport-sync.conf`. If you edit it, you'll see a "general" section with an entry for "statistics". Uncomment it an change the "no" to "yes" and restart.

Also, thinking a bit about the extra information you got about dropouts and how busy the processor is, it might be that the buffer length is too short. So, in the same file, could you go to the `alsa` section and change the `audio_backend_buffer_desired_length` from `6615` (0.15 seconds) to, say 22050 (half a second). Don't forget to uncomment the line. Then restart the system.

Please let me know what effects you get.

**Comment by mikebrady** [comment]
BTW, looking at the FAQs for the USB card, there seem to be some issues when using a Mac that are quite similar to the issues you are reporting here. It makes me wonder if it's some peculiarity of the card.

**Comment by bob808** [comment]
I've used this card with my Mac with absolutely no problems so far, via USB. Great little piece of gear.
Here's the output after restart:

Aug 30 23:00:36 raspberrypi shairport-sync[2750]: startup
Aug 30 23:00:36 raspberrypi shairport-sync[2750]: avahi: avahi_register.
Aug 30 23:00:36 raspberrypi kernel: [   41.555150] uart-pl011 20201000.uart: no DMA platform data
Aug 30 23:00:36 raspberrypi shairport-sync[2750]: avahi: register_service.
Aug 30 23:00:36 raspberrypi shairport-sync[2750]: Avahi without metadata
Aug 30 23:00:36 raspberrypi kernel: [   41.915812] cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
Aug 30 23:02:33 raspberrypi shairport-sync[2750]: new RTSP connection.
Aug 30 23:02:33 raspberrypi shairport-sync[2750]: Play connection from device named "Bogdan’s MacBook Pro".
Aug 30 23:02:33 raspberrypi shairport-sync[2750]: Play connection from user agent "AirPlay/215.18".
Aug 30 23:02:33 raspberrypi shairport-sync[2750]: Active-Remote string seen: "170086529".
Aug 30 23:02:33 raspberrypi shairport-sync[2750]: Connection from IPv4: 192.168.0.111:51415
Aug 30 23:03:05 raspberrypi shairport-sync[2750]: Sync error: -71.4 (frames); net correction: 99.8 (ppm); corrections: 207.1 (ppm); missing packets 0; late packets 51; too late packets 0; resend requests 31; min DAC queue size 4579, min and max buffer occupancy 221 and 238.
Aug 30 23:03:35 raspberrypi shairport-sync[2750]: Sync error: 55.4 (frames); net correction: -102.1 (ppm); corrections: 105.1 (ppm); missing packets 0; late packets 55; too late packets 0; resend requests 33; min DAC queue size 5814, min and max buffer occupancy 212 and 235.
Aug 30 23:04:05 raspberrypi shairport-sync[2750]: Sync error: 56.7 (frames); net correction: -98.3 (ppm); corrections: 98.3 (ppm); missing packets 0; late packets 55; too late packets 0; resend requests 33; min DAC queue size 6104, min and max buffer occupancy 223 and 235.
Aug 30 23:04:35 raspberrypi shairport-sync[2750]: Sync error: 56.9 (frames); net correction: -106.6 (ppm); corrections: 114.2 (ppm); missing packets 0; late packets 55; too late packets 0; resend requests 33; min DAC queue size 6025, min and max buffer occupancy 225 and 235.
Aug 30 23:05:05 raspberrypi shairport-sync[2750]: Sync error: 58.0 (frames); net correction: -139.9 (ppm); corrections: 144.4 (ppm); missing packets 0; late packets 55; too late packets 0; resend requests 33; min DAC queue size 6078, min and max buffer occupancy 224 and 235.
Aug 30 23:05:35 raspberrypi shairport-sync[2750]: Sync error: 58.0 (frames); net correction: -156.5 (ppm); corrections: 156.5 (ppm); missing packets 0; late packets 57; too late packets 0; resend requests 34; min DAC queue size 6134, min and max buffer occupancy 223 and 235.
Aug 30 23:06:05 raspberrypi shairport-sync[2750]: Sync error: 62.8 (frames); net correction: -257.0 (ppm); corrections: 261.6 (ppm); missing packets 0; late packets 57; too late packets 0; resend requests 34; min DAC queue size 5985, min and max buffer occupancy 224 and 235.
Aug 30 23:06:35 raspberrypi shairport-sync[2750]: Sync error: 61.1 (frames); net correction: -195.0 (ppm); corrections: 195.0 (ppm); missing packets 0; late packets 57; too late packets 0; resend requests 34; min DAC queue size 6066, min and max buffer occupancy 224 and 235.
Aug 30 23:07:05 raspberrypi shairport-sync[2750]: Sync error: 60.3 (frames); net correction: -248.0 (ppm); corrections: 249.5 (ppm); missing packets 0; late packets 57; too late packets 0; resend requests 34; min DAC queue size 5645, min and max buffer occupancy 226 and 235.


I tried to count the pops and the error msgs and they don't correspond, or just about 2 pops per message :)

**Comment by mikebrady** [comment]
Thanks. There doesn't seem to be anything peculiar there, apart from the high rate of net corrections, indicating that the DAC is running 250 ppm slower than the Mac, which is quite high. I do not see how it could account for the popping though. Did you change the `alsa` output buffer size to 22050?

**Comment by bob808** [comment]
Yes, I did that as well before I restarted the whole system.
I might try scoping the USB and see if I get anything when the pop is happening but I think I will it will be hard. So I understand if it's from the USB card or from the Raspberry. But knowing that there are way more pops when I put the raspberry to work, I think the raspberry has something to do with the pops, not the soundcard itself.

**Comment by bob808** [comment]
Also I did use a linear regulated supply, adjusted for cable loss and I have 5.01V at the main capacitor on the raspberry. So supply noise into the raspberry shouldn't be a problem.

**Comment by bob808** [comment]
And also I disabled the ethernet module and added a small heatsink on the usb chip as it gets quite hot. That didn't help either.

**Comment by mikebrady** [comment]
Thanks – very sensible ideas. Is it possible to vary the latency in the 2i4?

**Comment by bob808** [comment]
I don't think so, or I don't know how. Alsamixer has no controls for the card.
I just made another test with mplayer, and it seems I do have the same problems sadly.
Seems like it's not shairport-sync related at all, it behaves the same on any type of audio output.
I'm sorry for wasting your time. 
Hopefully the digi board will solve this for me.

**Comment by bob808** [comment]
One last question. Do you think you will go 24 bit in the near future? This is a very very useful bit of software for me and 24 bit would be perfect. 16 bit sounds nice as it is already, but would love 24 bit :)

**Comment by mikebrady** [comment]
Thanks for the new replies. Doing a quick google search for "focusrite scarlett 2i4 problems linux" got this as the most recent and first hit: http://linuxmusicians.com/viewtopic.php?f=6&t=13893. There's usually more heat than light on these things, but it might be significant.

Regarding 24-bit, the central issue is that all sources are converted to 44.1/16 before being sent to an AirPlay device, so there doesn't really seem to be much point. Of course, Apple might introduce a different standard – there doesn't seem to be a technical reason why not. But until they do, there really doesn't seem to be any point. Or am I missing something?

**Comment by bob808** [comment]
Oh, now I understand, so OSX is downsampling the audio stream before sending it.
Well, let's wait for Apple TV 4. Seems like they will make a big change in the architecture of the device so maybe they will update this as well.

**Comment by mikebrady** [comment]
Let's hope!

**Comment by bob808** [comment]
How do I check the latency?
I found other forum posts that are successful in using this board in linux with jack.
So I really think it has something to do with the Raspberry Pi's USB chipset.
Did the new Raspberry 2 fix these USB issues? Or do they share the chip with ethernet as well?

**Comment by mikebrady** [comment]
I don't know how to measure the latency in a general way. Shairport Sync is always measuring the size of the queue of samples waiting to be output, so it kind-of sidesteps the latency issues. It would report an error in the logfile if the buffer ever went empty.

As far as I know, the Raspberry Pi 2 architecture is very similar to the original one, and the Ethernet port is still routed though the USB system.

**Comment by bob808** [comment]
the digi board would bypass the USB so I should be good.
Anyway I need the USB board for the system on my desk. The Pi is for the music in the living room :)
Thanks for the help Mike. By the way, I love Dublin! Been there a couple of times :+1:

**Comment by mikebrady** [comment]
Thanks for the kind words!
