### ISSUE TITLE
Clear MQTT metadata on disconnect

### ISSUE THREAD

**Issue by hanerd** [mikebrady/shairport-sync#1170]
I'm not sure if I have something misconfigured or if it's just to be expected, but when a device stops play / disconnects from the server the MQTT metadata still shows the last playing album information when that client disconnected.

Is it possible to reset the metadata on disconnect so that consumers of it don't think something is still going when it's not?

**Comment by mikebrady** [comment]
Thanks for the post. Does MQTT not indicate when play has stopped?

**Comment by hanerd** [comment]
It does not.  It continues to show the last state that it was sent before a device disconnected so it's perpetually playing or paused.  There's no third state unless I restart the application.

**Comment by mikebrady** [comment]
Thanks. I'll take a look...

**Comment by minix1234** [comment]
sounds odd.

what states are you looking at to determine play status.  there are four published topics indicate if play has started/ended or a the session is active or not.

```
     case 'abeg':
        mqtt_publish("active_start", data, length);
        break;
      case 'aend':
        mqtt_publish("active_end", data, length);
        break;
      case 'pbeg':
        mqtt_publish("play_start", data, length);
        break;
      case 'pend':
        mqtt_publish("play_end", data, length);
        break;
```
