### ISSUE TITLE
ufw IPv6 rules

### ISSUE THREAD

**Issue by billhuey** [mikebrady/shairport-sync#1173]
I'm getting this in my ufw logs:

> Mar 28 17:52:13 pngnsd kernel: [352350.436215] [UFW BLOCK] IN=eno1 OUT= MAC=4c:72:b9:21:d8:09:a0:fb:c5:40:53:3d:86:dd SRC=2600:1700:2ec2:4440:91aa:88a7:934f:128d DST=2600:1700:2ec2:4440:38ae:c076:e602:5c35 LEN=1224 TC=0 HOPLIMIT=64 FLOWLBL=746621 PROTO=UDP SPT=63479 DPT=6003 LEN=1184 
Mar 28 17:52:13 pngnsd kernel: [352350.459085] [UFW BLOCK] IN=eno1 OUT= MAC=4c:72:b9:21:d8:09:a0:fb:c5:40:53:3d:86:dd SRC=2600:1700:2ec2:4440:91aa:88a7:934f:128d DST=2600:1700:2ec2:4440:38ae:c076:e602:5c35 LEN=1181 TC=0 HOPLIMIT=64 FLOWLBL=746621 PROTO=UDP SPT=63479 DPT=6003 LEN=1141 
Mar 28 17:52:13 pngnsd kernel: [352350.459102] [UFW BLOCK] IN=eno1 OUT= MAC=4c:72:b9:21:d8:09:a0:fb:c5:40:53:3d:86:dd SRC=2600:1700:2ec2:4440:91aa:88a7:934f:128d DST=2600:1700:2ec2:4440:38ae:c076:e602:5c35 LEN=1135 TC=0 HOPLIMIT=64 FLOWLBL=746621 PROTO=UDP SPT=63479 DPT=6003 LEN=1095 

----

Looks like an IPv6 issue with the ufw fire rules with troubleshooting. Is this the case ?

**Comment by mikebrady** [comment]
Thanks for the post, but I truly have no idea what this is, I'm afraid.

**Comment by billhuey** [comment]
It's the ufw firewall complaints. I think I have have to add rules using ipv6 conventions to enabled connection to ufw. Even so with the ipv4 rules in troubleshooting, I've had to turn off ufw to allow for streaming to work.

I only post here to bring the discussion up and get a more brains on this, suggest fixes and let folks know etc

**Comment by mikebrady** [comment]
Hi Bill. TBH, there is no context to your contribution. Are you certain this is the right forum?

**Comment by billhuey** [comment]
I'm sorry for being vague. I'm running the latest Ubuntu and I've been playing with shairport-sync and running into ufw firewall issues. I should have mentioned that before. In your troubleshooting documentation you have rules to allow for passthrough of ports needed for it to operate but they're only using legacy ipbv4 conventions.

I saw in the ufw logs that I pasted above that I saw ports blocked in the ranges allowed by the ipv4 rules. What I'm suggesting here is that the documentation also be updated to take into account ipv6 conventions.

Since I don't work with ipv6 regularly I'm having to piece together how ufw works with ipv6 and then attempt work around issues with ufw that prevents my iPhone from connecting and streaming over shairport-sync

**Comment by mikebrady** [comment]
Thanks Bill, I get it now. Do you have those IPv6-oriented rules? If so, we can add them to the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md#ufw-firewall-blocking-ports-commonly-includes-raspberry-pi) page.

**Comment by billhuey** [comment]
>billh@pngnsd:~/audio$ ip -6 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000                                                                                                                                                                                   inet6 ::1/128 scope host                                                                                                                                                                                                                         valid_lft forever preferred_lft forever                                                                                                                                                                                                3: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000                                                                                                                                                                            inet6 2600:1700:2ec2:4440: xxxx:xxxx:xxxx:xxxx/64 scope global temporary dynamic                                                                                                                                                                  valid_lft 3514sec preferred_lft 3514sec                                                                                                                                                                                                    inet6 2600:1700:2ec2:4440: xxxx: xxxx: xxxx: xxxx/64 scope global temporary deprecated dynamic                                                                                                                                                       valid_lft 3514sec preferred_lft 0sec                                                                                                                                                                                                       inet6 2600:1700:2ec2:4440: xxxx: xxxx: xxxx:a/64 scope global temporary deprecated dynamic                                                                                                                                                          valid_lft 3514sec preferred_lft 0sec                                                                                                                                                                                                       inet6 2600:1700:2ec2:4440: xxxx: xxxx: xxxx: xxxx/64 scope global temporary deprecated dynamic                                                                                                                                                       valid_lft 3514sec preferred_lft 0sec                                                                                                                                                                                                       inet6 2600:1700:2ec2:4440::49a/128 scope global dynamic noprefixroute                                                                                                                                                                            valid_lft 2524742sec preferred_lft 537542sec                                                                                                                                                                                               inet6 2600:1700:2ec2:4440: xxxx: xxxx: xxxx: xxxx/64 scope global temporary deprecated dynamic                                                                                                                                                       valid_lft 3514sec preferred_lft 0sec                                                                                                                                                                                                       inet6 2600:1700:2ec2:4440: xxxx: xxxx: xxxx: xxxx/64 scope global dynamic mngtmpaddr noprefixroute                                                                                                                                                   valid_lft 3514sec preferred_lft 3514sec                                                                                                                                                                                                    inet6 fe80:: xxxx: xxxx: xxxx: xxxx/64 scope link noprefixroute                                                                                                                                                                                      valid_lft forever preferred_lft forever                                                                                                                                                                                                17: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000                                                                                                                                                                         inet6 fd42:8378:a83a:190::1/64 scope global                                                                                                                                                                                                      valid_lft forever preferred_lft forever                                                                                                                                                                                                    inet6 fe80::216:3eff:fed3:1fad/64 scope link                                                                                                                                                                                                     valid_lft forever preferred_lft forever

-----------

```bash
#!/bin/bash

v=192.168.11.0
#sudo ufw allow from 192.168.11.0/24 to any port 3689 proto tcp
#sudo ufw allow from 192.168.11.0/24 to any port 5353
#sudo ufw allow from 192.168.11.0/24 to any port 5000:5005 proto tcp
#sudo ufw allow from 192.168.11.0/24 to any port 6000:6005 proto udp
#sudo ufw allow from 192.168.11.0/24 to any port 35000:65535 proto udp


v="2600:1700:2ec2:4440:e7d4::/64"
sudo ufw allow from ${v} to any port 3689 proto tcp
sudo ufw allow from ${v} to any port 5353
sudo ufw allow from ${v} to any port 5000:5005 proto tcp
sudo ufw allow from ${v} to any port 6000:6005 proto udp
sudo ufw allow from ${v} to any port 35000:65535 proto udp

**Comment by billhuey** [comment]
ip addr

> ...
inet6 2600:1700:2ec2:4440:1111:1111:1111:1111/64 scope global temporary
dynamic
   valid_lft 3587sec preferred_lft 3587sec
...

sudo ufw allow from  2600:1700:2ec2:4440::/64

**Comment by mikebrady** [comment]
Thanks the the reminder @billhuey. I simplified and updated the [hint](https://github.com/mikebrady/shairport-sync/blob/development/TROUBLESHOOTING.md#ufw-firewall-blocking-connections-on-raspbian-raspberry-pi) in the `development` branch, and it should allow IPv6 as well as IPv4.
