### ISSUE TITLE
Convolution not working

### ISSUE THREAD

**Issue by DeLub** [mikebrady/shairport-sync#1178]
Triggered by the new wiki page, I started experimenting with convolution. This is what I have in my .conf-file:
```
dsp =
{

//////////////////////////////////////////
// This convolution filter can be used to apply almost any correction to the audio signal, like frequency and phase correction.
// For example you could measure (with a good microphone and a sweep-sine) the frequency response of your speakers + room,
// and apply a correction to get a flat response curve.
//////////////////////////////////////////
//
        convolution = "yes";                   // Set this to "yes" to activate the convolution filter.
        convolution_ir_file = "test-16.wav";  // Impulse Response file to be convolved to the audio stream
        convolution_gain = -7.9;              // Static gain applied to prevent clipping during the convolution process
//      convolution_max_length = 44100;       // Truncate the input file to this length in order to save CPU.

```
But this sounds exactly the same as before. The config file is read: when I change the gain value I can hear a difference. Changing the file name to a full path does not help. Changing it to a file that doesn't exist has exactly the same effect :)

Running with ```-vvv``` doesn't give me any additional output.

Version: ```3.3.7-OpenSSL-Avahi-ALSA-soxr-convolution-metadata-sysconfdir:/usr/local/etc```

Can you please help?

**Comment by DeLub** [comment]
Ok. I've figured it out. I left the max_length commented out. This results in a default max_length of 8192 samples. REW generates a file of 131,072 samples. So I didn't hear a difference since most of the file was not used. So the easy solution is to set max_length tot 131072, or to 200000 which is the maximum accepted length. This is larger than the wav, but shairport figures this out correctly.

@paulwieland, 
Perhaps this hint could be added to the wiki?

**Comment by PaulWieland** [comment]
@DeLub that is very strange as I didn’t have to use the max length parameter at all. 

Can you share your wav file?

also I can’t modify the wiki (GitHub calls it a wiki, but it’s anything but). But I think once we figure out why yours is behaving differently we can ask Mike to update the page.

**Comment by DeLub** [comment]
Sure. I've uploaded two wav files to this [dropbox](https://www.dropbox.com/sh/g9g309w20e4gfd3/AADlHEMkJkhYnZYmPjkXFWwJa?dl=0) folder. One is an extreme test which should make detecting whether it works very easy. And the other one I use for equalising my headphones. Both were created with REW.

BTW, my shairport-sync is the 3.3.7 release, not head.

**Comment by PaulWieland** [comment]
So both of your filters work for me. My configuration has `convolution_max_length` and `convolution_gain` commented out.

I'm also using 3.3.7:

```
shairport-sync -V
3.3.7-alac-mbedTLS-Avahi-ALSA-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc
```

So I'm a bit at a loss of why it doesn't work for you.

I'm running mine under docker on a raspberry pi 4.
What platform are you running it on?

**Comment by DeLub** [comment]
I'm running on an old Raspberry Pi 2 with DietPi.

If you increase verbosity to 3, what do you see near the top of the log?

**Comment by PaulWieland** [comment]
`0.003727008 "FFTConvolver/convolver.cpp:62" IR initialized from "/etc/shairport_filters/bose_5.wav" with 1 channels and 8192 samples`

When I load your file:
`0.000981320 "FFTConvolver/convolver.cpp:62" IR initialized from "/etc/shairport_filters/hd600-44k.wav" with 1 channels and 8192 samples`
