### ISSUE TITLE
Low volume

### ISSUE THREAD

**Issue by mbundes** [mikebrady/shairport-sync#1179]
New installation on clear system 
RPi4 8
All work correctly (thanks so much)
But very low volume by AirPlay from Iphone. 
Plugin for Spotify for Home Assistant work correctly. 
I changed different settings in the config file and no changes.

**Comment by mbundes** [comment]
Raspberry Pi OS (32 bit)
`git clone https://github.com/mikebrady/shairport-sync.git`

```
cd shairport-sync
autoreconf -i -f
 ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemd
make
```
```
getent group shairport-sync &>/dev/null || sudo groupadd -r shairport-sync >/dev/null
getent passwd shairport-sync &> /dev/null || sudo useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null
```
```
sudo make install
sudo systemctl enable shairport-sync
```

**Comment by p3ck** [comment]
I would check for a volume control from the iPhone itself.

**Comment by mbundes** [comment]
Done 😊

**Comment by p3ck** [comment]
Does the smile mean it worked?  :-)  If so can you close this?

Thanks

**Comment by mbundes** [comment]
Not.  Unfortunately, this means that it was done right away and did not help.

**Comment by mikebrady** [comment]
Hi there. Could you check, using `alsamixer` that the output device's volume control is set high enough? And also, does changing volume on the iPhone change the device's volume control?

**Comment by mbundes** [comment]
Settings in Alsamixer 100%
Yes. Changing volume on the Iphone change the device's volume. 
But changing volume in alsamixer DON'T change volume.

**Comment by mikebrady** [comment]
If changing the volume with `alsamixer` doesn't change the volume, then perhaps you are looking at the wrong output device.

**Comment by shawnc722** [comment]
I'm having what sounds like the same issue, but I'm pretty sure it was caused by Apple. What I'm seeing is that I airplay from my phone to shairport-sync and the volume will start at about 40% regardless of what it was set at when I last disconnected. I can adjust the volume on the phone and everything works as expected, but disconnecting from airplay and reconnecting sets it back to ~40% volume.
I use shairport-sync and shairport4w on my linux and windows installs and the same issue began with both around the time I updated to iOS 14.5. I borrowed some devices from family members and tested across a bunch of devices. The latest builds of iOS, iPadOS, and the beta build of MacOS Catalina all have the same problem. When airplaying to a homepod mini instead, the problem doesn't happen (volume is retained from last use) - but it does for an old (non-4K) apple tv. For each airplay receiver except the homepod mini the volume is always reset to about 40%, so it seems to have nothing to do with shairport-sync.
It's not an ideal solution, but I've turned the `ignore_volume_control` setting in `/etc/shairport-sync.conf` on to avoid having to adjust the volume on my phone every time I connect and it does the job. @mbundes does this sound like the same problem you're having? If so, it might be worth submitting to https://feedbackassistant.apple.com/ - I'm planning to, but more reports of the same bug might help them fix it faster.

**Comment by glic3rinu** [comment]
I also experience the same lower volume issue (build from master with similar params as @mbundes ). I made sure my phone/laptop and pulseaudio/alsa all have the volume settings at their highest. But still the volume output is half of what other apps produce (and I need to double my amplifier power with added distortion). Volume control works, but the maximum coming out from shairport somehow does not match what other apps produce (mocp, bluez, subsonic, mplayer, ...)

**Comment by groner** [comment]
I'm observing behavior similar to what @shawnc722 described. Switching to one of my shairpoint-sync devices causes the volume level to be reset to the same low point. It's a recent behavior change that has also led me to suspect iOS 14.5.

I use `output_backend = "pa"`. The volume levels on my pulseaudio sinks and sink inputs are all 100%. The alsa device is a USB optical link with no working volume control. Turning the volume back up to 100% on my iphone doesn't appear to change any of the pulseaudio or alsa device volume levels.

Setting `run_this_when_volume_is_set = "/bin/echo volume is now "` shows the volume resets to -20, and comes back up to 0 when I turn the volume back up to 100%.

I know apple has some precautions around headphones and loud listening levels, but I'm unfamiliar with the specifics. Is the behavior I described above similar to how ios 14.5 works with generic headphones?

**Comment by mikebrady** [comment]
Thanks. This seems like a new behaviour on the part of iOS. I don't know if it's a bug or a feature!

**Comment by mikebrady** [comment]
Just checking what's happening. iOS is specifically asking for the volume to be set to -20 (on a -30 to 0 scale) the first time Shairport Sync (SPS) is chosen as the system output.  Subsequent plays to SPS do not change the volume. It really does seem like an iOS bug to me. If SPS don't receive an instruction to set volume, its default is -18, so it seems unlikely that iOS is receiving a hint for the startup volume from SPS.

The volume is also set to -20 when you set SPS as the Mac sound output device. Most peculiar.

**Comment by groner** [comment]
I'm having to reset the volume each time I change the output to an SPS device.  I'm including some log excerpts showing this.

After restarted SPS to configure the `run_this_when_volume_is_set` hook, the value -18 appeared but the volume displayed on the iphone was still 100%. It took me about 20 seconds to realize the volume up button wasn't working because the volume control on the phone was already at 100%.

It's interesting that the volume appears to be initialized twice except for the first time. 


<details>
<summary>log output from switching to SPS multtiple times</summary>
```
May 24 16:47:29 selector shairport-sync[4125160]:       4486.437313642 "rtsp.c:996" Connection 4: SETUP DACP-ID "29BA0E5179E44475" from 2601:5c2:200:9cc0:b54a:1e49:3e18:3a99 to 2601:5c2:200:9cc0:dea6:32ff:fe79:d887 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
May 24 16:47:29 selector shairport-sync[4128071]: volume is now 0.000000
May 24 16:47:29 selector shairport-sync[4128072]: volume is now -20.000000
May 24 16:47:36 selector shairport-sync[4128073]: volume is now -18.125000
May 24 16:47:37 selector shairport-sync[4128074]: volume is now -16.250000
May 24 16:47:37 selector shairport-sync[4128075]: volume is now -10.624999
May 24 16:47:37 selector shairport-sync[4128076]: volume is now -8.749999
May 24 16:47:37 selector shairport-sync[4128077]: volume is now -6.874999
May 24 16:47:38 selector shairport-sync[4128078]: volume is now -4.999999
May 24 16:47:39 selector shairport-sync[4128079]: volume is now -3.124999
May 24 16:47:39 selector shairport-sync[4128080]: volume is now -1.249999
May 24 16:47:39 selector shairport-sync[4128081]: volume is now 0.000000
May 24 16:47:59 selector shairport-sync[4125160]:         30.291904393 "rtsp.c:996" Connection 5: SETUP DACP-ID "DAFA7260CA594FD8" from 2601:5c2:200:9cc0:b54a:1e49:3e18:3a99 to 2601:5c2:200:9cc0:dea6:32ff:fe79:d887 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
May 24 16:47:59 selector shairport-sync[4128096]: volume is now -20.000000
May 24 16:47:59 selector shairport-sync[4128097]: volume is now -20.000000
May 24 16:48:05 selector shairport-sync[4128119]: volume is now -18.125000
May 24 16:48:05 selector shairport-sync[4128120]: volume is now -16.250000
May 24 16:48:05 selector shairport-sync[4128121]: volume is now -14.374999
May 24 16:48:05 selector shairport-sync[4128122]: volume is now -12.499999
May 24 16:48:05 selector shairport-sync[4128123]: volume is now -10.624999
May 24 16:48:05 selector shairport-sync[4128124]: volume is now -8.749999
May 24 16:48:05 selector shairport-sync[4128125]: volume is now -6.874999
May 24 16:48:05 selector shairport-sync[4128126]: volume is now -4.999999
May 24 16:48:05 selector shairport-sync[4128127]: volume is now -3.124999
May 24 16:48:05 selector shairport-sync[4128128]: volume is now -1.249999
May 24 16:48:06 selector shairport-sync[4128129]: volume is now 0.000000
May 24 16:48:24 selector shairport-sync[4125160]:         24.567056546 "rtsp.c:996" Connection 6: SETUP DACP-ID "2C64E659BA78ED32" from 2601:5c2:200:9cc0:b54a:1e49:3e18:3a99 to 2601:5c2:200:9cc0:dea6:32ff:fe79:d887 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
May 24 16:48:24 selector shairport-sync[4128144]: volume is now -20.000000
May 24 16:48:24 selector shairport-sync[4128145]: volume is now -20.000000
May 24 16:48:33 selector shairport-sync[4128146]: volume is now -18.125000
May 24 16:48:33 selector shairport-sync[4128147]: volume is now -16.250000
May 24 16:48:33 selector shairport-sync[4128148]: volume is now -14.374999
May 24 16:48:33 selector shairport-sync[4128149]: volume is now -12.499999
May 24 16:48:33 selector shairport-sync[4128150]: volume is now -10.624999
May 24 16:48:33 selector shairport-sync[4128151]: volume is now -8.749999
May 24 16:48:33 selector shairport-sync[4128152]: volume is now -6.874999
May 24 16:48:33 selector shairport-sync[4128153]: volume is now -4.999999
May 24 16:48:33 selector shairport-sync[4128154]: volume is now -3.124999
May 24 16:48:33 selector shairport-sync[4128155]: volume is now -1.249999
May 24 16:48:33 selector shairport-sync[4128156]: volume is now 0.000000
```
</details>

<details>
<summary>log output from first connection to SPS after restarting SPS</summary>
```
May 24 15:28:57 selector shairport-sync[4125160]:          9.432638787 "rtsp.c:996" Connection 1: SETUP DACP-ID "A4953A67084FD63E" from 2601:5c2:200:9cc0:b54a:1e49:3e18:3a99 to 2601:5c2:200:9cc0:dea6:32ff:fe79:d887 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
May 24 15:28:57 selector shairport-sync[4125181]: volume is now -18.000000
May 24 15:29:08 selector shairport-sync[4125201]: volume is now -0.779470
May 24 15:29:08 selector shairport-sync[4125202]: volume is now -1.083650
May 24 15:29:08 selector shairport-sync[4125203]: volume is now -1.577947
May 24 15:29:08 selector shairport-sync[4125204]: volume is now -2.072244
May 24 15:29:08 selector shairport-sync[4125205]: volume is now -2.414449
May 24 15:29:08 selector shairport-sync[4125206]: volume is now -2.756655
May 24 15:29:08 selector shairport-sync[4125207]: volume is now -3.250950
May 24 15:29:08 selector shairport-sync[4125208]: volume is now -3.631180
May 24 15:29:08 selector shairport-sync[4125209]: volume is now -4.011408
May 24 15:29:08 selector shairport-sync[4125210]: volume is now -4.353613
May 24 15:29:08 selector shairport-sync[4125211]: volume is now -4.695818
May 24 15:29:08 selector shairport-sync[4125212]: volume is now -5.114069
May 24 15:29:08 selector shairport-sync[4125213]: volume is now -5.494298
May 24 15:29:08 selector shairport-sync[4125214]: volume is now -5.988595
May 24 15:29:08 selector shairport-sync[4125215]: volume is now -6.482890
May 24 15:29:08 selector shairport-sync[4125216]: volume is now -7.015209
May 24 15:29:08 selector shairport-sync[4125217]: volume is now -7.585552
May 24 15:29:08 selector shairport-sync[4125218]: volume is now -8.117872
May 24 15:29:08 selector shairport-sync[4125219]: volume is now -8.764259
May 24 15:29:09 selector shairport-sync[4125220]: volume is now -9.486692
May 24 15:29:09 selector shairport-sync[4125221]: volume is now -10.209126
May 24 15:29:09 selector shairport-sync[4125222]: volume is now -10.969583
May 24 15:29:09 selector shairport-sync[4125223]: volume is now -11.806085
May 24 15:29:09 selector shairport-sync[4125224]: volume is now -12.566541
May 24 15:29:09 selector shairport-sync[4125225]: volume is now -13.212928
May 24 15:29:09 selector shairport-sync[4125226]: volume is now -13.783272
May 24 15:29:09 selector shairport-sync[4125227]: volume is now -14.315590
May 24 15:29:09 selector shairport-sync[4125228]: volume is now -14.923956
May 24 15:29:09 selector shairport-sync[4125229]: volume is now -15.798479
May 24 15:29:09 selector shairport-sync[4125230]: volume is now -16.292776
May 24 15:29:09 selector shairport-sync[4125231]: volume is now -14.733841
May 24 15:29:09 selector shairport-sync[4125232]: volume is now -13.707226
May 24 15:29:09 selector shairport-sync[4125233]: volume is now -12.376426
May 24 15:29:09 selector shairport-sync[4125234]: volume is now -11.159698
May 24 15:29:09 selector shairport-sync[4125235]: volume is now -10.285172
May 24 15:29:09 selector shairport-sync[4125236]: volume is now -9.676807
May 24 15:29:09 selector shairport-sync[4125237]: volume is now -9.182510
May 24 15:29:09 selector shairport-sync[4125238]: volume is now -8.650192
May 24 15:29:09 selector shairport-sync[4125239]: volume is now -8.079849
May 24 15:29:10 selector shairport-sync[4125240]: volume is now -7.471483
May 24 15:29:10 selector shairport-sync[4125241]: volume is now -6.787072
May 24 15:29:10 selector shairport-sync[4125242]: volume is now -6.102660
May 24 15:29:10 selector shairport-sync[4125243]: volume is now -5.456275
May 24 15:29:10 selector shairport-sync[4125244]: volume is now -4.809886
May 24 15:29:10 selector shairport-sync[4125245]: volume is now -4.163498
May 24 15:29:10 selector shairport-sync[4125246]: volume is now -3.479088
May 24 15:29:10 selector shairport-sync[4125247]: volume is now -2.718632
May 24 15:29:10 selector shairport-sync[4125248]: volume is now -2.034221
May 24 15:29:10 selector shairport-sync[4125249]: volume is now -1.349811
May 24 15:29:10 selector shairport-sync[4125250]: volume is now -0.703424
May 24 15:29:10 selector shairport-sync[4125251]: volume is now -0.095059
May 24 15:29:10 selector shairport-sync[4125252]: volume is now 0.000000
```
</details>

**Comment by mikebrady** [comment]
Thanks -- I edited your message slightly for format. The -18 value was probably because no command to set the volume was given prior to that.

**Comment by mikebrady** [comment]
As far as I can tell, it's still the same in iOS 14.6 and macOS 11.4. Odd.

**Comment by shawnc722** [comment]
This issue has been fixed in iOS 14.7 for me and the volume works as you'd expect. If anyone is still getting this problem, updating might fix it.

**Comment by aftrmth728** [comment]
> This issue has been fixed in iOS 14.7 for me and the volume works as you'd expect. If anyone is still getting this problem, updating might fix it.

Hi there, 

I have a similar issue but I'm not sure if it's the same as reported here. The volume is low but with the slider maxed in iOS its a good volume. The slider from 0% to roughly around 65% doesn't do much and the volume is almost silent in this region but the rest of the slider area makes drastic changes in volume.

**Comment by groner** [comment]
This was better with iOS 14.7, but the problem has returned with iOS 15.

**Comment by mikebrady** [comment]
Thanks for the post. TBH, I'm losing track of what the original problem is -- could you restate it for me, please?

**Comment by groner** [comment]
This is the issue of volume being reset to a low (nearly inaudible) level when switching to a shairport-sync output.

Because past investigation points to this being an iOS behavior change, I'm not sure there's anything to be done about it.

**Comment by mikebrady** [comment]
Thanks for the clarification. Have you tried building Shairport Sync for AirPlay 2?

**Comment by groner** [comment]
I was not aware that airplay 2 support has progressed. I'll give it a try.

**Comment by groner** [comment]
The AirPlay2 behavior is better. It seems to remember what volume level I had last time I used the output.

**Comment by groner** [comment]
I spoke too soon. Sometimes the volume is at the previous level, and other times it is reset. I haven't noticed a pattern to the behavior.

**Comment by handyMay** [comment]
I am having the same issue as @mbundes . I am using SPS with volumio and the volume output is about 60-70% lower when compared to directly playing media stored on the sd card or using the spotify plugin to stream. 

Happy to help diagnose or share logs if it helps.

**Comment by ccozkan** [comment]
I experienced low volume on only on Spotify (not when streaming from another sources)
Disabling "Enable Audio Normalization" on Spotify App(under playback settings) solved the problem for me

**Comment by nook24** [comment]
>  Disabling "Enable Audio Normalization" on Spotify App(under playback settings) solved the problem for me

Yes Thanks!!
