### ISSUE TITLE
play music

### ISSUE THREAD

**Issue by amz4u2nv** [mikebrady/shairport-sync#118]
Is it possible to play an mp3 or some raw music file to several raspberry pi's that has shairport-sync installed via the command line. What would the command look like.

**Comment by mikebrady** [comment]
Hi there. Thanks for the question. Shairport Sync doesn't have a command line interface – it's basically a server that has applications like iTunes as clients. You'd need a client that accepted command line requests. It may be that something like the excellent forkedDaapd might have one.
