### ISSUE TITLE
Any way to not change alsamixer volume?

### ISSUE THREAD

**Issue by fooness** [mikebrady/shairport-sync#1182]
Is there any way to configure `shairport-sync` to not change the volume defined in `alsamixer`?

For example, my volume in `alsamixer` ist set to `64%` and this is the optimum for my audio setup. When using `raspotify`, I can change my volume in Spotify, but the volume is not changed in `alsamixer` … I somehow cannot reproduce this setup with `shairport-sync` … maybe someone here could help out.

Thank you!

PS: I’m running `shariport-sync` on latest Raspberry Pi OS.

**Comment by mikebrady** [comment]
Thanks for the post. It's easy to do this -- simply don't tell Shairport Sync the name of the `alsamixer`. In other words, comment out the `mixer_control_name` in the `alsa` part of the configuration file. Shairport Sync will then not use a hardware mixer for volume control, but will use an internal software mixer instead.

**Comment by And1** [comment]
@mikebrady I will try this, thank you very much!

**Comment by fooness** [comment]
@mikebrady I will try this, thank you very much!

**Comment by fooness** [comment]
@mikebrady Maybe this could be combined with volume min/max and volume range …

```
general {
  volume_range_db = 60 ; // use this advanced setting to set the range, in dB, you want between the maximum volume and the minimum volume. Range is 30 to 150 dB. Leave it commented out to use mixer's native range.
  volume_max_db = 0.0;   // use this advanced setting, which must have a decimal point in it, to set the maximum volume, in dB, you wish to use.
  		         // The setting is for the hardware mixer, if chosen, or the software mixer otherwise. The value must be in the mixer's range (0.0 to -96.2 for the software mixer).
  		         // Leave it commented out to use mixer's maximum volume.
}
```

Guess I need to play around with those values to kinda re-produce the volume min/max and volume range of `raspotify` as well as local `mpd` …
