### ISSUE TITLE
Changing volume results in audio drop outs on raspberry pi 4 when using hardware sound control

### ISSUE THREAD

**Issue by dasl-** [mikebrady/shairport-sync#1183]
First off, thank you so much for creating this!

I found two issues in my recent installation of shairport on raspberry pi 4 model B:
1. The recommended shairport-sync.conf settings in the installation guide did not result in hardware volume control
2. When the settings were modified to allow hardware volume control, adjusting the volume causes the audio output to drop out for ~10s.

### problem 1: The recommended shairport-sync.conf settings in the installation guide did not result in hardware volume control
I just installed shairport-sync on a raspberry pi 4: with the latest rasbian lite:
```
Raspberry Pi OS 
Release date: March 4th 2021
Kernel version: 5.10 
```
I followed the [raspberry pi install guide instructions](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md#build-and-install) to set `/etc/shairport-sync.conf` to:
```
// Sample Configuration File for Shairport Sync on a Raspberry Pi using the built-in audio DAC
general =
{
  volume_range_db = 60;
};

alsa =
{
  output_device = "hw:0";
  mixer_control_name = "PCM";
};
```

I noticed that this does not result in hardware volume control -- adjusting the volume on my iphone, `alsamixer` volume level remains constant.

In `/var/log/daemon.log`, I see:
```
Apr 30 06:43:19 now-thats-what-i-call-music-1 shairport-sync: warning: failed to find mixer control "PCM".
```

To determine the proper `output_device`, I ran:
```
% shairport-sync -h | grep -A1 'hardware output devices'
    hardware output devices:
      "hw:Headphones"
```

To determine the proper `mixer_control_name`, I ran `alsamixer`: 
<img width="1423" alt="Screen Shot 2021-04-30 at 1 49 34 AM" src="https://user-images.githubusercontent.com/1332576/116654095-79c27200-a956-11eb-809d-052a2701e6a3.png">

This suggests that I should use `mixer_control_name = "Headphone";`. I am using the built in audio output jack.

### problem 2: When the settings were modified to allow hardware volume control, adjusting the volume causes the audio output to drop out for ~10s
I restart the `shairport-sync.service` with a new `/etc/shairport-sync.conf` file:
``` 
// Sample Configuration File for Shairport Sync on a Raspberry Pi using the built-in audio DAC
general =
{
  volume_range_db = 60;
};

alsa =
{
  output_device = "hw:Headphones";
  mixer_control_name = "Headphone";
};
```
I no longer get the `/var/log/daemon.log` warning lines, great! Furthermore, adjusting the volume on my iphone, I can see that the volume is adjusted in `alsamixer` on the raspberry pi. Also great! 

Adjusting the volume on my iphone in small increments (one or two clicks at a time on the volume buttons) works fine. But adjusting the volume on my iphone in larger increments, for example holding the volume buttons down to go from 100% -> 0% -> 100% volume in quick succession results in a sound drop out for ~10s. This does not happen when using software volume control.

This audio drop out issue is reproducible even adjusting the volume via `alsamixer` in large increments. So perhaps this is an issue with the alsa sound system, and not the fault of your software?

UPDATE: actually, I have determined that the problem is only reproducible when adjusting the volume in large increments via `alsamixer` when music is playing through shairport-sync at the same time. If the shairport-sync.service is stopped, or if music is not playing through it, adjusting the volume in large increments via `alsamixer` works fine. So perhaps the problem is related to shairport-sync.

In the output of `dmesg -T`, I see:
```
[Fri Apr 30 06:03:02 2021] bcm2835_audio bcm2835_audio: vchi message timeout, msg=3
[Fri Apr 30 06:03:02 2021] bcm2835_audio bcm2835_audio: Failed to set ALSA controls..
[Fri Apr 30 06:03:12 2021] bcm2835_audio bcm2835_audio: vchi message timeout, msg=3
[Fri Apr 30 06:03:12 2021] bcm2835_audio bcm2835_audio: Failed to set ALSA controls..
[Fri Apr 30 06:13:47 2021] bcm2835_audio bcm2835_audio: failed to close VCHI service connection (status=1)
[Fri Apr 30 06:23:29 2021] bcm2835_audio bcm2835_audio: failed to close VCHI service connection (status=1)
...
```
The timestamps of these messages are correlated with when I adjust the hardware volume in large increments and experience the audio drop outs.

Any idea what's going on?

Thanks for looking.

**Comment by mikebrady** [comment]
Thanks for the interesting post, and for your thorough analysis. Briefly, you're right on both counts:
1. The mixer name for the Pi's built-in DAC was `"PCM"` but changed in the last few years to `"Headphone"`.
2. I have come across this problem in my own testing, and am pretty sure that it's a Raspberry Pi 4 problem.
  Specifically, on occasion, the time it takes to execute the `alsa` call: `snd_mixer_selem_set_playback_dB_all` can vary from less than 2 milliseconds to around 10 seconds. It doesn't happen on any other audio devices I have tried. (I am sorry to say that I have not reported this -- I've been rather busy with something else.)

So, I will update the documentation shortly to address the first point, but the second one is, AFAICT, a Raspberry Pi problem.

**Comment by dasl-** [comment]
RE "problem 1: The recommended shairport-sync.conf settings in the installation guide did not result in hardware volume control", I have found this information about the raspberry pi changes:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=275406
https://www.raspberrypi.org/blog/latest-raspberry-pi-os-update-may-2020/ (see the section "Other changes")

**Comment by mikebrady** [comment]
This is definitely a bug in the Raspberry Pi. if you change the volume a few times in rapid succession, it locks up for about 10 seconds.

**Comment by dasl-** [comment]
Agreed, I posted about it here, but to no avail: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=311007&p=1859777#p1859777

Fwiw, changing the volume via `sudo amixer cset numid=1 40%` doesn't appear to suffer from this problem, even if you change it rapidly in this manner.
