### ISSUE TITLE
*fatal error: could not establish a service on port 5000

### ISSUE THREAD

**Issue by NotOnBoard** [mikebrady/shairport-sync#1184]
I have two shairport-sync players running version:  3.3.8rc2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

One is a Pi0W (wireless) and the other a Pi1B+ (wired).  They run nicely and play in sync, but both players flag a fatal error in the log file and I don't know why.  

In the log file straight after boot (no music played yet) both players flag the same fatal error:
```
  0.006774916 "rtsp.c:2896" unable to listen on IPv4 port 5000. The error is: "Address already in use".
  0.000367996 "rtsp.c:2896" unable to listen on IPv6 port 5000. The error is: "Address already in use".
  0.000188997 "rtsp.c:3028" *fatal error: could not establish a service on port 5000 -- program terminating.  Is another instance of Shairport Sync running on this device?
  0.000164998 "shairport.c:1424" emergency exit
```

I followed the install process carefully and I'm not running any other Applications on these devices, so don't expect competition for the ports.

I've checked the ports and they do seem to be allocated to `shairport-sync`:   
```
sudo ss -tulpn | grep 5000
tcp     LISTEN   0        5    0.0.0.0:5000     0.0.0.0:*   users:(("shairport-sync",pid=440,fd=3))
                                        
tcp     LISTEN   0        5    [::]:5000        [::]:*      users:(("shairport-sync",pid=440,fd=4))
```

So I checked the number of processes running.  After boot (no music played) `htop` shows there are four shairport processes running, but I don't know how many should be running.

When playing music `htop` shows there are eleven Shairport Sync processes running.  When the music is stopped, `htop` shows only four shairport processes running again.  

I assume `shairport-sync` may have a number of child processes, but I just don't know if the above is the correct number.  Only four of the processes seem to clock up any significant CPU time, the other seven clock up less than half a second CPU time over 1hour of playing.

So my Questions are:
How many shairport processes should be running when the player is idle straight after boot ?
How many processes should be running when the player is active ?
Is the fatal error genuine ?
And how do I correct it please ?

Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. What appears to be happening is that you installed Shairport Sync correctly and fully, and it is starting by itself as a startup daemon (as it should) when the computer powers up. When you run it from the command line, it's already running in the background and using those ports.

Shaiport Sync only occasionally runs child processes, and then only for a very short time. What `htop` is showing you are the *threads* running within Shairport Sync. Threads are created to manage separate tasks within the application and are deleted when not needed. It is normal for one or two threads to use the vast bulk of the CPU time of the application.

So, there is nothing to correct, AFAICT. Shairport Sync starts running as soon as the machine has started up.

**Comment by NotOnBoard** [comment]
Hi Mike, thanks for the feedback.  

The fatal error is recorded in the log file when shairport sync STARTS UP at boot time BEFORE I have attempted to play any music at all.

Not sure what you mean by "When you run it from the command line", I don't start shairport sync from the command line.

Shairport sync is configured to start automatically at boot time, and at some time after boot I play music from my streaming app (Synology Audio Station) which connects to the shairport sync service and plays music.

It's possible I've got my knickers in a twist somewhere along the line, but I don't think so.

I have configured a separate log file i.e.   /etc/shairport-sync.conf

 log_verbosity = 2;
 log_show_file_and_line = "yes";
 log_output_to = "shairport-sync-logfile.log";

I'd appreciate any further diagnostic advice yo can offer.

Thanks again.

**Comment by mikebrady** [comment]
Thanks. This is most peculiar. The problem generally arises because someone tries to start it from the command line even though it is running already as a daemon. Since you are not starting it from the command line, I wonder if it is not being started by some other program or some script somewhere. Or is it possible that there is a second Shairport Sync installed in your system as part of another suite of software?

**Comment by NotOnBoard** [comment]
This is a basic install, no other apps running, no extra scripts.  It could well be something stupid I have done, but I don't know what, and the player works well.

I see I'm a few versions behind the current release (rc2 v rc7), so I think I'm going to start again, build a new image and then investigate this again.

Thanks again.
