### ISSUE TITLE
Visible from guest network / different subnet?

### ISSUE THREAD

**Issue by jajcayn** [mikebrady/shairport-sync#1189]
Dear Mike,

first off, thanks for a great piece of software, works like a charm:) So everything works for me as expected, however, I'd like to add one functionality and was hoping you would be able to help me. 
So I have more subnets at home (my main is 192.168.3.X - my RPi with shairport-sync lives here, my guest is 192.168.5.X). I was wondering which ports/protocols I should open such that RPi as an AirPlay target is visible from my guest network?
In the [troubleshooting file](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md#ufw-firewall-blocking-ports-commonly-includes-raspberry-pi), I found a set of rules for `ufw` and I hoped these would be the same so I just allowed those protocols/ports (see the attached screenshot from my router). Unfortunately, I still cannot see my RPi from the guest network as an AirPlay target. Is this even possible? If so, do you know which additional ports/protocols I should allow?

Thanks a lot!
Best,
N.

<img width="825" alt="Screenshot 2021-05-03 at 7 33 53 PM" src="https://user-images.githubusercontent.com/6525217/116911060-aa502780-ac46-11eb-8f29-7f6eb086628f.png">

**Comment by mikebrady** [comment]
Thanks for the post. I'm not sure it is possible -- you could use the macOS/iOS app called Discovery (from TildeSoft) to check if the Bonjour/mDNS "advertisements" are making it on to the Guest network.

**Comment by jajcayn** [comment]
Hey, thanks for the prompt response and for the advice. The advertisements are not making it to the guest. However, it pointed me in the right direction - I was able to found several questions on forums relating to my router+VLAN setup - I believe the culprit is mDNS actually so I'll try to mess with that.
Thanks a lot again, I think I can safely close this as the solution probably won't relate to shairport-sync.

**Comment by NotOnBoard** [comment]
Hi Jajcayn

I suspect the data packets are created with a time to live TTL=1 so when they reach your router they will die and not propagate to a different subnet.  So you may need to setup a rule to increment the TTL.  Hope that helps.  Very interested to know if you get it to work.

**Comment by giovi321** [comment]
Hi @jajcayn, did you manage to achieve this?
