### ISSUE TITLE
volume_control_combined_hardware_priority or volume_range_combined_hardware_priority ?

### ISSUE THREAD

**Issue by iEns** [mikebrady/shairport-sync#1190]
The default configuration file states that volume_**range**_combined_hardware_priority will enable combined hardware and software volume control. It doesn't work.

Looking at shairport.c (line 741) it seems like the correct keyword is volume_**control**_combined_hardware_priority. And it does indeed work.

One or the other should be changed. I could make a PR, but I am unsure which of the two to change.

**Comment by mikebrady** [comment]
Yikes, thanks. I'll fix it. I think I prefer `volume_control_combined_hardware_priority`. Which do you think makes most sense? 

It may take a few weeks for this fix to appear, even in the `development` branch.

**Comment by iEns** [comment]
Thank you, that is awesome.

After giving it some thought, I have come to the conclusion that `volume_control_combined_hardware_priority` is the safe bet.

My reasoning is this:

Some existing installations might have `volume_range_combined_hardware_priority` enabled, but it does nothing. People might be unaware that they enabled this setting while experimenting. When updating Shairport-sync, the behavior would suddenly change if `volume_range_combined_hardware_priority` was the chosen one.

By choosing `volume_control_combined_hardware_priority` as the correct keyword, no existing installation would change behavior.

**Comment by mikebrady** [comment]
Thanks for the well-reasoned justification!
