### ISSUE TITLE
shairport-sync on WSL2

### ISSUE THREAD

**Issue by noelhibbard** [mikebrady/shairport-sync#1193]
Ubuntu under WSL2 on recent Windows 10 insider builds has native PortAudio out of the box. Actually, the very latest Win10 build even has native out of the box support for Linux GUI apps. No more need for a X windows client or any sort of hackery to make this work. Anyways, I was trying to test shairport-sync in WSL2 but I'm not having any luck. Has anyone else had any success?

**Comment by minix1234** [comment]
I was interested in this myself. 

how far did you get?
