### ISSUE TITLE
Suggestion: Partial support for multi-channel interfaces

### ISSUE THREAD

**Issue by ross-m-dickson** [mikebrady/shairport-sync#1195]
There are several different posted work around many of which use pulse-audio to add support for connecting multi-channel interfaces to the raspberry pi to work around the limitation that there is not support for interfaces with other than 2 output channels. With some experimentation using a Behringer XR18 (an 18 channel mixer that can serve as an audio interface) I have found the following patch is sufficient to make things work. I chose not to submit as a pull request as it in now way actually supports multi-channel interfaces, rather it simply enables multi-channel interfaces to be used as if 2 channel, if your speakers aren't connected to channels 1 and 2 this may not work for you.

```
diff --git a/audio_alsa.c b/audio_alsa.c
index b464279..ab788ac 100644
--- a/audio_alsa.c
+++ b/audio_alsa.c
@@ -480,7 +480,8 @@ int actual_open_alsa_device(int do_auto_setup) {
     return ret;
   }
 
-  ret = snd_pcm_hw_params_set_channels(alsa_handle, alsa_params, 2);
+  uint ch_count = 2;
+  ret = snd_pcm_hw_params_set_channels_min(alsa_handle, alsa_params, &ch_count);
   if (ret < 0) {
     warn("audio_alsa: Channels count (2) not available for device \"%s\": %s", alsa_out_dev,
          snd_strerror(ret));
```

the only changes to the /etc/shairport-sync.conf is
output_device = "plughw:X18XR18,0"

I note that simply changing the channel count to 18 and retaining the call to snd_pcm_hw_params_set_channels results in many buffer overruns that totally clobber the stack. I was unable to track down the actual line of code but disabling several functions such as time synchronization suggests that the library memcopy using the channel count member of the alsa_params structure as the length but that the buffer is allocated using a static size. I gave up tracking these down once I discovered the ...channels_min alternate function call.

**Comment by mikebrady** [comment]
Thanks for this interesting idea. So, just to be clear, is it the case that if you set things up this way, the audio will come out of Channel 1 and Channel 2?

**Comment by ross-m-dickson** [comment]
That is correct. The audio from Shairport-sync (L and R) arrives at the Behringer as the two lowest number USB channels (1 and 2, or 0 and 1 depending on if the viewing app uses 1 based or 0 based channel numbering). These are the same two USB channels that audio arrives on when I use play from SoX or when I plug into my Mac and hit play on Apple Music. The only time I have seen audio on the other 16 channels is when I use a DAW to send more than 2 channels of audio and in those cases there is generally a rather complex control panel to set things up.
