### ISSUE TITLE
Can't play on hw:0,0 if the "name" is set

### ISSUE THREAD

**Issue by kdubious** [mikebrady/shairport-sync#1196]
Going crazy here.

1. I *can* play to a USB DAC (`alsa / output_device` set to "hw:1,0") with `general / name` set to "Device Name"
2. I *can* play to an internal (custom driver... `alsa / output_device` set to "hw:0,0") card with `general / name` Commented Out
3. I can not play to an internal (custom driver... `alsa / output_device` set to "hw:0,0") card with `general / name` set to "Device Name"
4. I can not play to an internal (custom driver... `alsa / output_device` set to "hw:0,0") card with `general / name` set to "%H"
5. I can not play to an internal (custom driver... `alsa / output_device` set to "hw:0,0") card with `general / name` set to "%h"

Why?

**Comment by mikebrady** [comment]
Thanks. Can we see some logs, please? Also, the list of output devices produced by `$ shairport-sync -h`?

**Comment by mikebrady** [comment]
Update -- it would be very useful to know what version of Shairport Sync you are using please.

**Comment by LadnerJamie** [comment]
I am also having the same problem with my new install of shairport-sync. This a brand new install of raspberryOS Buster Lite. I have a HiFiBerry AMP+ installed and working. 

My version of shairport-sync reports as:
3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc

shairport-sync runs properly after install with "apt install shairport-sync". 

If I edit the /etc/shairport-sync.conf and make the one change  to remove "//" from the general setting line "//      name = "%H" This means "Hostna..... " and then stop and restart the shairport-sync service, the service fails with a "Failed to start ShairportSync AirTunes receiver." error.  It does not make a difference what the host name is between the " " , it always produces the same error.

If I stop the service and manually load shairport-sync from the command line with the "-a Garage" option, shairport-sync will sucessfully start with itself correctly named.  I have attached  the log below.

The audio devices listed with shairport-sync -h are:
Available audio outputs:
    alsa (default)
    pa
    pipe
    stdout
    dummy

LOG:
Jun  6 06:55:52 garagepi systemd[1]: Starting ShairportSync AirTunes receiver...
Jun  6 06:55:52 garagepi shairport-sync[1214]: debug_mutex_lock at "audio_alsa.c:169".
Jun  6 06:55:52 garagepi shairport-sync[1214]: alsa output device name is "default".
Jun  6 06:55:52 garagepi shairport-sync[1212]: free(): double free detected in tcache 2
Jun  6 06:55:52 garagepi shairport-sync[1214]: debug_mutex_unlock at "audio_alsa.c:465".
Jun  6 06:55:52 garagepi systemd[1]: shairport-sync.service: Control process exited, code=killed, status=6/ABRT
Jun  6 06:55:52 garagepi shairport-sync[1214]: The processor is running little-endian.
Jun  6 06:55:52 garagepi shairport-sync[1214]: Version: "3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc"
Jun  6 06:55:52 garagepi shairport-sync[1214]: statistics_requester status is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: daemon status is 1.
Jun  6 06:55:52 garagepi shairport-sync[1214]: daemon pid file path is "/run/shairport-sync/shairport-sync.pid".
Jun  6 06:55:52 garagepi shairport-sync[1214]: rtsp listening port is 5000.
Jun  6 06:55:52 garagepi shairport-sync[1214]: udp base port is 6001.
Jun  6 06:55:52 garagepi shairport-sync[1214]: udp port range is 100.
Jun  6 06:55:52 garagepi shairport-sync[1214]: player name is "Garage".
Jun  6 06:55:52 garagepi shairport-sync[1214]: backend is "(null)".
Jun  6 06:55:52 garagepi shairport-sync[1214]: on-start action is "(null)".
Jun  6 06:55:52 garagepi shairport-sync[1214]: on-stop action is "(null)".
Jun  6 06:55:52 garagepi systemd[1]: shairport-sync.service: Failed with result 'signal'.
Jun  6 06:55:52 garagepi shairport-sync[1214]: wait-cmd status is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: on-start returns output is 0.
Jun  6 06:55:52 garagepi systemd[1]: Failed to start ShairportSync AirTunes receiver.
Jun  6 06:55:52 garagepi shairport-sync[1214]: mdns backend "(null)".
Jun  6 06:55:52 garagepi shairport-sync[1214]: userSuppliedLatency is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: stuffing option is "0" (0-basic, 1-soxr).
Jun  6 06:55:52 garagepi shairport-sync[1214]: resync time is 0.050000 seconds.
Jun  6 06:55:52 garagepi shairport-sync[1214]: allow a session to be interrupted: 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: busy timeout time is 120.
Jun  6 06:55:52 garagepi shairport-sync[1214]: drift tolerance is 0.001995 seconds.
Jun  6 06:55:52 garagepi shairport-sync[1214]: password is "(null)".
Jun  6 06:55:52 garagepi shairport-sync[1214]: ignore_volume_control is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: volume_max_db is not set
Jun  6 06:55:52 garagepi shairport-sync[1214]: playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
Jun  6 06:55:52 garagepi shairport-sync[1214]: disable_synchronization is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: use_mmap_if_available is 1.
Jun  6 06:55:52 garagepi shairport-sync[1214]: output_rate is 44100.
Jun  6 06:55:52 garagepi shairport-sync[1214]: output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
Jun  6 06:55:52 garagepi shairport-sync[1214]: audio backend desired buffer length is 0.150000 seconds.
Jun  6 06:55:52 garagepi shairport-sync[1214]: audio backend latency offset is 0.000000 seconds.
Jun  6 06:55:52 garagepi shairport-sync[1214]: audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
Jun  6 06:55:52 garagepi shairport-sync[1214]: volume range in dB (zero means use the range specified by the mixer): 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: zeroconf regtype is "_raop._tcp".
Jun  6 06:55:52 garagepi shairport-sync[1214]: decoders_supported field is 1.
Jun  6 06:55:52 garagepi shairport-sync[1214]: use_apple_decoder is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: alsa_use_hardware_mute is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: no special mdns service interface was requested.
Jun  6 06:55:52 garagepi shairport-sync[1214]: configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
Jun  6 06:55:52 garagepi shairport-sync[1214]: metadata enabled is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: metadata pipename is "(null)".
Jun  6 06:55:52 garagepi shairport-sync[1214]: metadata socket address is "(null)" port 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: metadata socket packet size is "500".
Jun  6 06:55:52 garagepi shairport-sync[1214]: get-coverart is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: convolution is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: convolution IR file is "(null)"
Jun  6 06:55:52 garagepi shairport-sync[1214]: convolution max length 8192
Jun  6 06:55:52 garagepi shairport-sync[1214]: convolution gain is 0.000000
Jun  6 06:55:52 garagepi shairport-sync[1214]: loudness is 0.
Jun  6 06:55:52 garagepi shairport-sync[1214]: loudness reference level is -20.000000
Jun  6 06:55:52 garagepi shairport-sync[1214]: disable resend requests is off.
Jun  6 06:55:52 garagepi shairport-sync[1214]: diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
Jun  6 06:55:52 garagepi shairport-sync[1214]: shutdown requested...
Jun  6 06:55:52 garagepi shairport-sync[1214]: Request to shut down all rtsp conversation threads
Jun  6 06:55:52 garagepi shairport-sync[1214]: asking playing threads to stop
Jun  6 06:55:52 garagepi shairport-sync[1214]: debug_mutex_lock at "audio_alsa.c:906".
Jun  6 06:55:52 garagepi shairport-sync[1214]: debug_mutex_unlock at "audio_alsa.c:923".
Jun  6 06:55:52 garagepi systemd[1]: shairport-sync.service: Service RestartSec=100ms expired, scheduling restart.
Jun  6 06:55:52 garagepi systemd[1]: shairport-sync.service: Scheduled restart job, restart counter is at 5.
Jun  6 06:55:52 garagepi systemd[1]: Stopped ShairportSync AirTunes receiver.
Jun  6 06:55:52 garagepi systemd[1]: shairport-sync.service: Start request repeated too quickly.
Jun  6 06:55:52 garagepi systemd[1]: shairport-sync.service: Failed with result 'signal'.
Jun  6 06:55:52 garagepi systemd[1]: Failed to start ShairportSync AirTunes receiver.

**Comment by kdubious** [comment]
I was using the version bundled with the latest Buildroot. Moving to the latest version of shairport-sync solved this for me.

**Comment by LadnerJamie** [comment]
Thanks for the tip @kdubious . I was using the version of shair-port sync (3.2.2) that was installed with apt. I've purged that version and re-installed with the instructions @mikebrady  provided in the documentation so I am now at the latest version which solved the problem for me as well.
