### ISSUE TITLE
Music quality very poor at high volumes

### ISSUE THREAD

**Issue by Tone866** [mikebrady/shairport-sync#1197]
I'm using Ubuntu 20.04 with a USB Soundcard and check it with amixer.
Amixer shows me I have -28dB at 1% Volume and 0dB at 100%.

> $ amixer -c 1
>   Simple mixer control 'Speaker',0
>   Capabilities: pvolume pswitch pswitch-joined
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 151
>   Mono:
>   Front Left: Playback 2 [1%] [-28.00dB] [on]
>   Front Right: Playback 2 [1%] [-28.00dB] [on]

I've configured the following:
> volume_range_db = 30 ;
> volume_max_db = -7.0 ; 
> output_device = "hw:1";
> mixer_control_name = "Speaker";

>Available mDNS backends:
>    avahi
>
>Available audio backends:
>    alsa (default)
>
>    hardware output devices:
>      "hw:Audio"
>      "hw:Device"
 
-If I change the volume on my iPhone and check it with amixer, it reaches -7dB somewhere in the middle of the slider and I can still increase the volume, but amixer still shows me -7dB, even if I hear it gets louder, why is that?
I've noticed I can change this with an other option (I think it was `volume_range_combined_hardware_priority`), so -7dB is the maximum, but whats the point of `volume_max_db` then?

-If I comment out the `volume_range_db` option I can increase the volume on my iPhone or PC and it both sounds crappy. 
Only if I set `volume_range_db` and set the iPhone to a very low volume and then increase the volume via amixer it sounds good. If I increase it on the iPhone it sounds bad again.
Sounds like clipping to me., like a soundcard gets over 0dB, but amixer shows only my physical and that seems ok.

My soundknowledge is limited, so maybe I just do something wrong and I couldn't unterstand it in the manual, but at the moment I have no idea anymore.

I'm now using a softwaremixer and it sounds better then before, but I think it still doesn't sound as good at high volume.

**Comment by mikebrady** [comment]
Thanks. It would be interesting to know something about the sound card. Also, why pick a volume range as small as 30? A typical range for even a low-end HiFi would be 60. 

If you use `alsamixer`, it will actually animate any changes made to the mixer by Shairport Sync.

AirPlay 1, which Shairport Sync uses, has a lossless transport, so if you are using a hardware volume control, the audio goes straight from the source through Shairport Sync, unchanged except for occasional resyncing. Turn on `statistics` to see how much of that is happening.

If you have equalisation, Sound Enhancer or Sound Check enabled, In my experience they can introduce distortion.

**Comment by Tone866** [comment]
1. Ah ok, no I'm using my iPhone with "default sound settings" I didn't play with the EQ or have any sound enhancing apps.
2. The slider on the iPhone, yes, but if I'm using my soundcard as mixer they are anyway the same. 
3. Sorry! I forget to mention the sound card.
I'm using a "BIGtec USB Adapter" (https://www.amazon.de/gp/product/B005BYBWLG/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) and it has this range:
```
Limits: Playback 0 - 151
Playback 151 [100%] [-0.06dB] 
Playback 0 [0%] [-28.37dB]
```
So that means my card has in fact only (around) -30dB - 0dB.
So would you recommend a sound card with a higher max volume (like the rpi with it's +4dB)?

4. Again, sorry!
3.3.8rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
```
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-06-02 12:57:50 CEST; 24s ago
   Main PID: 1837685 (shairport-sync)
      Tasks: 11 (limit: 3946)
     Memory: 4.1M
     CGroup: /system.slice/shairport-sync.service
             └─1837685 /usr/local/bin/shairport-sync -w -B /bin/sh /home/tom/Scripts/shairport-start.sh

Jun 02 12:57:50 Velvet systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Jun 02 12:57:59 Velvet shairport-sync[1837713]: Simple mixer control 'Speaker',0
Jun 02 12:57:59 Velvet shairport-sync[1837713]:   Capabilities: pvolume pswitch pswitch-joined
Jun 02 12:57:59 Velvet shairport-sync[1837713]:   Playback channels: Front Left - Front Right
Jun 02 12:57:59 Velvet shairport-sync[1837713]:   Limits: Playback 0 - 151
Jun 02 12:57:59 Velvet shairport-sync[1837713]:   Mono:
Jun 02 12:57:59 Velvet shairport-sync[1837713]:   Front Left: Playback 151 [100%] [-0.06dB] [on]
Jun 02 12:57:59 Velvet shairport-sync[1837713]:   Front Right: Playback 151 [100%] [-0.06dB] [on]
```

>I suggest you stop using the volume_range_db and volume_max_db settings and see what happens.

It sounds even worse.
In fact my current settings (with the software mixer) are already the best I could find out.

**Comment by mikebrady** [comment]
Great stuff, thanks. In my experience, these little USB sound cards can sound okay apart from the restricted volume range. It can be extended with the `volume_range_db`. 

IMHO it's more important to find out why the sound is so bad at any volume. Could you enable statistics (in the configuration file, towards the bottom) and play some music through it for a few minutes and post the logs here, so that we can see if there is anything amiss there please?

Finally, have you tried playing audio through it from another source? If it sounds good from another source but bad from Shairport Sync ("SPS"), then the problem might lie with SPS, but if it sounds bad from another source too, then it would indicate something else.

**Comment by Tone866** [comment]
>IMHO it's more important to find out why the sound is so bad at any volume.

No, thats not the case! Sorry if I didn't make myself clear.
Indeed it's only at high volume. 
I have now tried a quick test, I'm using headphones and hear music locally on my pc over my soundcard (without shairplay). And at high volume it also sounds crappy. Then I did the same on my raspberry and indeed it sounds better.
So the problem seems to be this cheap soundcard.. I'm sorry I took up your time!
Thanks for your help!

As mentioned I'm not really a sound expert. I've quickly googled for some soundcards now, but almost all doesn't specify the volume range. Is there a other spec I can looking for? Specially for "louder" ones? Thanks!

**Comment by mikebrady** [comment]
Thanks, and it's good that you figured it all out.

TBH, I'm not really too sure what to look for -- I've tried those cheap USB cards and they have sounded pretty good, apart from the poor volume range.

On the Raspberry Pi I've had success with the Pimoroni PHAT and the IQAudIO stuff -- they are not USB though, and very specific to the Pi. Maybe some other users could  offer some recommendations.
