### ISSUE TITLE
Lossless support

### ISSUE THREAD

**Issue by sosickstudio** [mikebrady/shairport-sync#1199]
It seems that despite specifying ALAC as alac_decoder option Shairport does not support apple's lossless on Apple Music.

When connected to the Shairport device the song just refuses to play songs that were dowloaded in lossless. 
When playing a non download song The lossless logo doesn't show up when playing via Shairport as well.

Any ideas ?

**Comment by mikebrady** [comment]
Thanks for the post.

My experience is that Shairport Sync 3.3.8 is working fine with the new lossless music. I'm pretty sure the audio is being transcoded in iOS and macOS Music. Theoretically, therefore, you'd expect material coming in as 44.1 lossless will be transported to Shairport Sync losslessly. 

I've tried it with a number of lossless tracks, streamed and downloaded, and it worked okay. It also plays Spatial Audio tracks.

Could you give us some information about the version of Shairport Sync, and maybe a few sample tracks, please?

**Comment by sosickstudio** [comment]
Yes alac seems to play lossless, however it seems shairport doesn't seem to support the latest Apple Music lossless feature.
This is a screenshot of an Apple Music song playing in lossless directly on the computer
![Capture d’écran 2021-06-08 à 18 30 57](https://user-images.githubusercontent.com/8607654/121223561-f581d980-c887-11eb-8809-5b191fc05155.png)

And this is the same song playing it on the shairport device, notice the lossless logo disappeared.
![Capture d’écran 2021-06-08 à 18 31 13](https://user-images.githubusercontent.com/8607654/121223848-3bd73880-c888-11eb-8fe8-99e98e2b6802.png)

If you downloaded the song (from Apple Music in lossless), it doesn't want to play at all.
![Capture d’écran 2021-06-08 à 18 37 26](https://user-images.githubusercontent.com/8607654/121224214-9ff9fc80-c888-11eb-97a7-b2998505ae6f.png)

Probably an interface bug as airplay doesn't recognize the device

**Comment by mikebrady** [comment]
Thanks. From a marketing point of view, I can understand why the Lossless symbol might disappear if you are outputting to an AirPlay 1 device like Shairport Sync. On the other hand, given that the AirPlay 1 transport is lossless, one might guess (but not be certain!) that it is lossless end-to-end.

It plays for me whether it is streamed or downloaded.

**Comment by getowic** [comment]
I think @sosickstudio is right with his understanding. If i click on the file informations playing over shairport it shows the codec AAC Audio

<img width="714" alt="image" src="https://user-images.githubusercontent.com/21356603/121230678-d38c5500-c88f-11eb-8191-fa00f5d00518.png">

If i play the file directly on the macbook speaker it shows the codec Losless-Audio

<img width="714" alt="image" src="https://user-images.githubusercontent.com/21356603/121230767-f3237d80-c88f-11eb-8e8e-125f48b344dd.png">

Could the frequency with 44.1 khz (shairport) and 48khz (Apple Music Lossless) be the problem?

**Comment by mikebrady** [comment]
That's interesting. So it looks like it's reverting to AAC. 

> Could the frequency with 44.1 khz (shairport) and 48khz (Apple Music Lossless) be the problem?

It's impossible to say, isn't it? We don't know why Apple have made that choice -- it could be marketing (as I guess), or it could be something else...

**Comment by sosickstudio** [comment]
@mikebrady Yes it is streaming (without displaying the logo), but if you download the song in lossless it won't play it. It seems that shairport doesn't accept it.

Though a programmer I don't know anything about sound qualities and associated frequencies, I can try to dig the raspi to show the logs if there's any.

Another interesting thing. It plays lossless on my HomePod though apple stated HomePods wouldn't support lossless.

**Comment by mikebrady** [comment]
> @mikebrady Yes it is streaming (without displaying the logo), but if you download the song in lossless it won't play it. It seems that shairport doesn't accept it.

My experience is that it does accept lossless downloaded tracks, so that is most peculiar. 



> Another interesting thing. It plays lossless on my HomePod though apple stated HomePods wouldn't support lossless.

pretty sure it’s being transcoded to AAC before being sent to the HomePod. 
> 
> EDIT: after a quick look around, https://support.apple.com/en-us/HT212183 it seems that Apple Music lossless runs at 48khz.

It also can be 44.1, 48, 96 or 192 and maybe other formats. It’ll be transcoded to suit the output device.

**Comment by sosickstudio** [comment]
After looking at your code it seems its all hardcoded for 44100 Hz and its multiples. It seems airplay 2 sends it differently.

I took a screen record since you really don't wanna believe me https://we.tl/t-AK9KnzrGli

Tried to look if the logs gave anything

 0.001212595 "rtsp.c:475" msg_init message 61
Jun 08 21:31:27 raspberrypi shairport-sync[12398]:          0.000092499 "rtsp.c:580" RTSP Message Received: "TEARDOWN rtsp://192.168.1.237/3706036274 RTSP/1.0".
Jun 08 21:31:27 raspberrypi shairport-sync[12398]:          0.000055573 "rtsp.c:610"     CSeq: 7.
Jun 08 21:31:27 raspberrypi shairport-sync[12398]:          0.000048437 "rtsp.c:610"     Session: 1

**Comment by Ranguvar** [comment]
I just got into the Apple sphere, just picked up some high-end headphones, and just found out about this project.
This makes the analog or digital mixer I needed unnecessary, and could do so much else besides with Pi-sized devices.
Even cover art, etc. -- wow.

Wish I could add more, but I'll definitely follow and help in any way possible.

**Some of the recordings have Apple Digital Master 24-bit/192kHz "Hi-Res Lossless" available.
It sounds like that won't be possible to stream without implementing AirPlay 2?**

**Comment by sosickstudio** [comment]
@Ranguvar I think we would need to solve the frequency problem first thing first. This project uses a fixed base frequency of 44.1khz which is airport 1 standard. However to support Apple Lossless and  Apple Digital Master 24-bit/192kHz we would need to be able to either pick 44.1khz and 48khz as bases (all currently accepted frequencies are multiples of 444100, we would need to take either 44100 & 48000). 
@mikebrady one of the original author is sure that it is being converted to 44.1khz before streaming. However by doing so it transforms the lossless into lossy (its being converted). 
That would be a good and important first step. If we could simply accept both base frequency that awesome project would be ahead of industrial airport connector (belkin soundform connects only accepts 44.1khz)

**Comment by mikebrady** [comment]
You're right that Shairport Sync ("SPS") is fixed to 44.1k, but it would be a fairly straightforward piece of work to fork it and change it to 48k.

That isn't the problem though. The problem is that we can't get the audio at any rate other than what iOS or maCOS sends. In AirPlay 1, it's 44.1k 16-bit interleaved stereo, encoded in ALAC, irrespective of the encoding of the original. That's what is used to send lossless audio to SPS.

Apparently in AirPlay 2 audio is sent in 44.1k AAC or ALAC. I believe it's using these formats to send lossless audio to AirPlay 2 devices.

Remember, the AirPlay 1 protocol has never been published, so we do not know if it's possible to get different rates or how it might be done if it was possible. The same is true of AirPlay 2 -- we don't have a specification. If we could get the source audio in its "native" form, then we could really make progress.

**Comment by sosickstudio** [comment]
What piece of audio would you need ? If you have an Apple Music subscription you can access the new lossless format. I can check on my HomePod wether the file's format changes if you play it on the HomePod. Theoretically homepods can't play lossless "yet" because according to apple they don't support the ALAC codec, but, and I can't say this enough: A lossless song means no compression, so airplay 2 must definitely support 48khz and multiple rates in some way.

But as you said, the protocols aren't public so there's not many ways to know. Would trying to listen to the network when you initiate a connection with something like wireshark help ?

**Comment by easp** [comment]
FWIW, it [appears that Apple Music isn't sending ALAC to Airplay 2 devices](https://community.naimaudio.com/t/apple-music-hifi-tier-incoming/16445/437?u=crystalgipsy).

Sending from my Mac to an Airport Express, I don't think the bitrate is high enough to be ALAC.

**Comment by sosickstudio** [comment]
Well, so that's what apple meant by "Homepods will support lossless in the future" AirPlay 2 isn't compatible yet.
Guess I'll ditch out the good old cable...

**Comment by mikebrady** [comment]
> When connected to the Shairport device the song just refuses to play songs that were dowloaded in lossless.
> 
> Any ideas ?

@sosickstudio, I finally got this to happen! But, crucially, it also happens when I try to play to a second-generation AppleTV, in other words, an AppleTV that can only do AirPlay 1. So it looks like a fault in macOS Music.

**Comment by easp** [comment]
Apple seems to be [going out of their way to avoid an unbroken lossless chain from their servers to AirPlay (v1 and v2) ](https://techobsessed.net/2021/06/apple-music-lossless-and-airplay-dont-work-like-you-think-they-should/)devices.

**Comment by jacobxdouglas** [comment]
So I'm 99% certain that files that stream at 24-bit 48 kHz play as _lossy ACC_ over Airplay whereas 24-bit 44.1 kHz play as _lossless ALAC_. Must be some issue with losslessly transcoding the frequency range; bit depth doesn't seem to be the issue. Also this does seem to mean that albums with are available as hi-res lossless will always play as AAC over Airplay.

**Comment by aleszczynskig** [comment]
Hi, I've been following this thread. Is it worth remembering that Apple have not released the code for their airplay products to support lossless playback yet? I expect once they update their HomePod products, other Airplay2 products may also be able to support lossless playback.

**Comment by easp** [comment]
@jacobxdouglas That's interesting. Do you have some examples of 24-bit/44.1 tracks on Apple Music? I don't remember what tracks I used when trying to figure out which codec was being used based on the bitrate sent to the AirPort Express 2 (I suspect that at least some were 16-bit/44.1KHz). I'd like to redo my tests.

**Comment by jacobxdouglas** [comment]
@easp Yeah, the album Blue Weekend by Wolf Alice is available in that format. 

Having done some more reading, it still seems likely that the actual Airplay audio stream is AAC, but Music does display the lossless symbol and claim to be playing lossless while playing those files over Airplay (with Airplay 1 at the very least). But you should test it!

**Comment by sosickstudio** [comment]
@jacobxdouglas Yes according to apple own statement lossless isn't supported on HomePods and yet the lossless logo displays. So I guess the issue is directly in the airplay2 protocols. On another note I have no idea why the bug I encountered using shairport happened. But I doubt that we will ever be able to really play apple lossless via shairport.

**Comment by npmstart-pray** [comment]
Not to add fuel to the file format wars, or take the topic off track, but DSD can't be that difficult to implement these days. 1 bit at 2.8MHz (or multiples of that: 5.6 MHz...) seems entirely possible for multi core processors at 1.something GHz clock frequencies. The bitstream more closely resembles the longitudinal waveform of the original sound...we have the technology to move the bits, so why mess around with data compression?

**Comment by stevodotorg** [comment]
Came here looking for 24bit support on my hifiberry. Subscribed.

**Comment by npmstart-pray** [comment]
That’s largely dependant on the player, and the source material. The DAC wants to (because it was designed to) natively change a 24b/192kHz bitstream to an analog signal, but if the file isn’t encoded that way, or the software isn’t capable of sending it through to the converter chips, you really can’t do much. And it’s pointless to upsample something that wasn’t recorded/mixed/mastered and released at that resolution- you’ll never achieve (construct, actually) the depth, clarity, imaging…. 
FLAC is nice, MQA is a marketing thing - where it’s REALLY at from an audiophile perspective is DSD. Pulse density more closely matches the characteristics of a longitudinal sound wave…but I digress into the esoteric…
