### ISSUE TITLE
Shairport-Sync crashes to "Bus error"

### ISSUE THREAD

**Issue by pk2061** [mikebrady/shairport-sync#1201]
HI,

I am trying to install Shairport-Sync on my old G3 iMac running MacOSX 10.4 Tiger.

I used the home-brew formula to compile with these parameters:

```
args = %W[
      --with-os=darwin
      --with-libdaemon
      --with-ssl=openssl
      --with-dns_sd
      --with-ao
      --with-stdout
      --with-pipe
      --with-soxr
      --with-metadata
      --with-piddir=#{var}/run
      --sysconfdir=#{etc}/shairport-sync
      --prefix=#{prefix}
    ]
    system "./configure", *args
    system "make", "install"
```

I got one warning while compiling:
```
Warning: shairport-sync dependency libconfig was built with a different C++ standard
library (libstdc++ from gcc). This may cause problems at runtime.
```

This is my output from shairport-sync -h:
```
Available mDNS backends: 
    dns-sd

Available audio backends:
    ao (default)
    pipe
    stdout

Settings and options for the audio backend "ao":
    -d driver           set the output driver
    -o name=value       set an arbitrary ao option
    -i id               shorthand for -o id=<id>
    -n name             shorthand for -o dev=<name> -o dsp=<name>
```

I attached my config file here:
[shairport-sync.conf.txt](https://github.com/mikebrady/shairport-sync/files/6619593/shairport-sync.conf.txt)

When I try to run shairport-sync I get the following error:
```
imac-g3:/ jan$ shairport-sync
Bus error
imac-g3:/ jan$ 
```

Do you maybe have any advice to help me or at least point me in the right direction?
Thanks a lot in advance!

Best regards.

**Comment by pk2061** [comment]
Hi,

thanks for the reply.
Unfortunately  I get the same output:
imac-g3:~ jan$ shairport-sync -v
Bus error
imac-g3:~ jan$ shairport-sync -V
3.3.6-libdaemon-OpenSSL-dns_sd-ao-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc/shairport-sync
imac-g3:~ jan$ 

Here ist the crash log: 

Host Name:      iMac-G3
Date/Time:      2021-06-09 20:44:04.272 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: shairport-sync
Path:    /usr/local/bin/shairport-sync
Parent:  bash [212]

Version: ??? (???)

PID:    295
Thread: 0

Exception:  EXC_BAD_ACCESS (0x0001)
Codes:      KERN_PROTECTION_FAILURE (0x0002) at 0x00000000

Thread 0 Crashed:
0   libSystem.B.dylib 	0x90049a5c realpath + 124
1   shairport-sync    	0x00006120 parse_options + 1876
2   shairport-sync    	0x00025150 main + 768
3   shairport-sync    	0x000042b4 _start + 340 (crt.c:272)
4   shairport-sync    	0x0000415c start + 60

Thread 0 crashed with PPC Thread State 64:
  srr0: 0x0000000090049a5c srr1: 0x000000000000f030                        vrsave: 0x0000000000000000
    cr: 0x82000222          xer: 0x000000000000000c   lr: 0x0000000090049a48  ctr: 0x00000000900013a0
    r0: 0x000000000000002f   r1: 0x00000000bfffe450   r2: 0x0000000054485244   r3: 0x00000000a000edcc
    r4: 0x0000000000000000   r5: 0x0000000000000010   r6: 0x0000000000000007   r7: 0x0000000000000000
    r8: 0x0000000000000001   r9: 0x0000000001100510  r10: 0x0000000001200009  r11: 0x00000000a00061ec
   r12: 0x00000000900013a0  r13: 0x00000000000259d4  r14: 0x000000000002ac98  r15: 0x000000000002ac94
   r16: 0x000000000002d874  r17: 0x0000000000000000  r18: 0x00000000000259d4  r19: 0x000000000001bfac
   r20: 0x000000000001b044  r21: 0x00000000011004f0  r22: 0x00000000000259d4  r23: 0x0000000000000002
   r24: 0x00000000bffffcb0  r25: 0x0000000000000000  r26: 0x000000000002d448  r27: 0x000000000002d450
   r28: 0x00000000000259d4  r29: 0x00000000000259d4  r30: 0x0000000000029c90  r31: 0x00000000900499e8

Binary Images Description:
    0x1000 -    0x26fff shairport-sync 	/usr/local/bin/shairport-sync
   0x39000 -    0x3ffff libao.4.dylib 	/usr/local/lib/libao.4.dylib
   0x43000 -    0x61fff libsoxr.0.dylib 	/usr/local/lib/libsoxr.0.dylib
   0x72000 -    0xc3fff libssl.1.0.0.dylib 	/usr/local/lib/libssl.1.0.0.dylib
   0xe1000 -    0xe5fff libdaemon.0.dylib 	/usr/local/lib/libdaemon.0.dylib
   0xe9000 -    0xf1fff libconfig.11.dylib 	/usr/local/lib/libconfig.11.dylib
  0x205000 -   0x354fff libcrypto.1.0.0.dylib 	/usr/local/lib/libcrypto.1.0.0.dylib
  0x3d2000 -   0x3dbfff libpopt.0.dylib 	/usr/local/lib/libpopt.0.dylib
  0x3df000 -   0x48efff libstdc++.6.dylib 	/usr/local/lib/gcc/7/libstdc++.6.dylib
  0x603000 -   0x60dfff libgcc_s.1.dylib 	/usr/local/lib/gcc/7/libgcc_s.1.dylib
0x8fe00000 - 0x8fe52fff dyld 46.16	/usr/lib/dyld
0x90000000 - 0x901bcfff libSystem.B.dylib 	/usr/lib/libSystem.B.dylib
0x90214000 - 0x90219fff libmathCommon.A.dylib 	/usr/lib/system/libmathCommon.A.dylib
0x91434000 - 0x9143ffff libgcc_s.1.dylib 	/usr/lib/libgcc_s.1.dylib
0x92a07000 - 0x92af5fff libiconv.2.dylib 	/usr/lib/libiconv.2.dylib

**Comment by mikebrady** [comment]
Thanks. The maximum verbosity of the log is with:
```
$ shairport-sync -vvv
```
It just might give a clue...

**Comment by pk2061** [comment]
I am afraid, that I was not able to retrieve more useful information.
Here is my try with the -vvv option:

Terminal input:
```
imac-g3:~ jan$ shairport-sync -vvv
Bus error
imac-g3:~ jan$ 
```

Syslog:

```
Jun 10 20:59:25 iMac-G3 crashdump[481]: shairport-sync crashed
Jun 10 20:59:25 iMac-G3 crashdump[481]: crash report written to: /Users/jan/Library/Logs/CrashReporter/shairport-sync.crash.log

```
Crashlog:

```
**********

Host Name:      iMac-G3
Date/Time:      2021-06-10 20:59:24.570 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: shairport-sync
Path:    /usr/local/bin/shairport-sync
Parent:  bash [252]

Version: ??? (???)

PID:    480
Thread: 0

Exception:  EXC_BAD_ACCESS (0x0001)
Codes:      KERN_PROTECTION_FAILURE (0x0002) at 0x00000000

Thread 0 Crashed:
0   libSystem.B.dylib 	0x90049a5c realpath + 124
1   shairport-sync    	0x00005828 parse_options + 2416
2   shairport-sync    	0x00007ac0 main + 988
3   shairport-sync    	0x00003d94 _start + 340 (crt.c:272)
4   shairport-sync    	0x00003c3c start + 60

Thread 0 crashed with PPC Thread State 64:
  srr0: 0x0000000090049a5c srr1: 0x000000000000f030                        vrsave: 0x0000000000000000
    cr: 0x82000222          xer: 0x0000000000000010   lr: 0x0000000090049a48  ctr: 0x00000000900013a0
    r0: 0x000000000000002f   r1: 0x00000000bfffe440   r2: 0x0000000054485244   r3: 0x00000000a000edcc
    r4: 0x0000000000000000   r5: 0x0000000000000010   r6: 0x0000000000000005   r7: 0x0000000000000000
    r8: 0x0000000000000001   r9: 0x0000000000400670  r10: 0x000000000050000c  r11: 0x00000000a00061ec
   r12: 0x00000000900013a0  r13: 0x000000000002d020  r14: 0x000000000002e14c  r15: 0x0000000000034ec0
   r16: 0x0000000000024ec0  r17: 0x0000000000000000  r18: 0x00000000bffffca8  r19: 0x0000000000000002
   r20: 0x0000000000022560  r21: 0x00000000000225e4  r22: 0x0000000000024ec0  r23: 0x0000000000022398
   r24: 0x00000000000223d8  r25: 0x0000000000000000  r26: 0x00000000000224e0  r27: 0x0000000000024ec0
   r28: 0x0000000000033810  r29: 0x0000000000005524  r30: 0x000000000002ee84  r31: 0x00000000900499e8

Binary Images Description:
    0x1000 -    0x2cfff shairport-sync 	/usr/local/bin/shairport-sync
   0x3a000 -    0x40fff libao.4.dylib 	/usr/local/lib/libao.4.dylib
   0x44000 -    0x62fff libsoxr.0.dylib 	/usr/local/lib/libsoxr.0.dylib
   0x73000 -    0xc4fff libssl.1.0.0.dylib 	/usr/local/lib/libssl.1.0.0.dylib
   0xe2000 -    0xe6fff libdaemon.0.dylib 	/usr/local/lib/libdaemon.0.dylib
   0xea000 -    0xf2fff libconfig.11.dylib 	/usr/local/lib/libconfig.11.dylib
  0x205000 -   0x354fff libcrypto.1.0.0.dylib 	/usr/local/lib/libcrypto.1.0.0.dylib
  0x3d2000 -   0x3dbfff libpopt.0.dylib 	/usr/local/lib/libpopt.0.dylib
0x8fe00000 - 0x8fe52fff dyld 46.16	/usr/lib/dyld
0x90000000 - 0x901bcfff libSystem.B.dylib 	/usr/lib/libSystem.B.dylib
0x90214000 - 0x90219fff libmathCommon.A.dylib 	/usr/lib/system/libmathCommon.A.dylib
0x91434000 - 0x9143ffff libgcc_s.1.dylib 	/usr/lib/libgcc_s.1.dylib
0x92a07000 - 0x92af5fff libiconv.2.dylib 	/usr/lib/libiconv.2.dylib
0x94c22000 - 0x94c93fff libstdc++.6.dylib 	/usr/lib/libstdc++.6.dylib
```
