### ISSUE TITLE
Help needed creating Pipe Shairport-Sync 2 Owntone / Forked Daapd

### ISSUE THREAD

**Issue by juite** [mikebrady/shairport-sync#1202]
Hi,

I need a bit of help in creating a pipe.

I would like to achieve the following:

I installed on a Raspberry Pi 4 Owntone (fna: Forked Daapd) and Shairport-Sync. I would like to stream from i.e an iPhone to Shairport-Sync and forward that to Owntone for multiroom functionality. I have read that a pipe is needed. But how does that work? Is here somebody who can help me here how to configure that? Like setting up a pipe (how to) and stream audio to multiroom with Owntone?

Manay thanks in advance.

JU

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest you take it in stages. Get it outputting to a pipe first (use `aplay` or similar to play the pipe's output) and then try to hook it up to Owntone.

**Comment by juite** [comment]
> Thanks for the post. Let me suggest you take it in stages. Get it outputting to a pipe first (use `aplay` or similar to play the pipe's output) and then try to hook it up to Owntone.
> 
> 

Thanks for you quick reply! For me its the first time working with pipes. I dont know how to set this up. I'm searching for a step by step set up.

**Comment by mikebrady** [comment]
You should be able to find some examples of using a pipe and `aplay` in the issues here, including the closed issues.

**Comment by juite** [comment]
Thanks for your reply agian. Unfortunately I'm not getting further on this. Now I messed up the complete .conf because it doesnot work anymore ;). I am in need of a step by step help. Anyone who would like to help?

**Comment by aleszczynskig** [comment]
Hi, I can help you out. 

What specifically is the problem?

Have you created your pipe using mkfifo?

**Comment by aleszczynskig** [comment]
In summary,

1. You need to create two pipes (using mkfifo), one for the audio stream, the second for metadata transfer (this is optional but recommended)
2. Configure shairport-sync.conf to output it's audio stream to pipe, 
3. Disable the mixer in shairport-sync so that audio control is passed direct to owntone.
4. Make sure Owntone can see the pipe (it needs to be in the one of the folders owntone monitors).

Do you need specific technical guidance?

**Comment by mikebrady** [comment]
Thanks for the help, @aleszczynskig. AFAIR (not at my computer right now) Shairport Sync will create a pipe if it doesn’t already exist. It uses a default if a pipe name has not been specified.

**Comment by aleszczynskig** [comment]
@mikebrady - no problem. Yes I believe you are right. 

Then the only requirement is that Owntone can see the pipe in one of its monitored directories. The Owntone default configuration will auto play any valid input audio stream.

**Comment by mikebrady** [comment]
Thanks again.

**Comment by juite** [comment]
Wow! Thanks to take the time to reply! I'm going to try it as soon as possible today...

**Comment by aleszczynskig** [comment]
No problem. If you need specific help with config let me know.

**Comment by aleszczynskig** [comment]
HI @juite 

Item 1 - almost right (note that @mikebrady corrected me earlier stating that you do not need to create these as shairport-sync will create them if they do not exist but create them will not do any harm). You need to rename pipe_metadata to pipe_stream.metadata. Note my comment in Item 2 about the use of - or _

Item 2 seems correct though I note you - in and _, this may be a typo but these need to be correct.

For item 3 modify this line in your shairport-sync.conf and set it to yes.

// ignore_volume_control = "no"; // set this to "yes" if you want the volume to be at 100% no matter what the source's volume control is set to.

For item 4 if you search in the owntone UI for pipe-stream or pipe_stream (whichever is correct) do you get a match?

For item 5 you will need to set these options in shairport-sync.conf in metadata section. include_cover_art is only needed if you want to pass the currently playing cover art to Owntone.

enabled = "yes";
include_cover_art = "yes"; 
pipe_name = "/srv/pipes/pipe_stream.metadata"; (or pipe-stream.metadata). 

* Note that you need to use the name of the audio pipe with .metadata at the end. 

You will need to restart shairport-sync after the changes are made (just in case you aren't). Your Owntone config will also need to be correct however "out of the box" Owntone should auto delete the pipes as they are in the monitored directories and play when audio becomes available. I presume you have Owntone outputting correctly to some playback devices already?

I hope this is helpful.
