### ISSUE TITLE
Logging not working in 3.3.8

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#1206]
Hi,

I can't seem to get console logging to work using either -vvv or log_verbosity = 2;

```
pi@rp2:~ $ shairport-sync -V
3.3.8-OpenSSL-Avahi-ALSA-stdout-soxr-metadata-mqtt-dbus-sysconfdir:/etc
```
After executing the command below no console output appears.

```
sudo /usr/local/bin/shairport-sync -vv -a "RP2 Airplay" -- -d _audioout
```

**Comment by mikebrady** [comment]
Remember, you need to include `-u` to get the log onto the console, thus:
```
$ sudo /usr/local/bin/shairport-sync -vvu -a "RP2 Airplay" -- -d _audioout
```
(I may well get rid this requirement — it confuses a lot of users and may not be really necessary.)

**Comment by moodeaudio** [comment]
Got it.
