### ISSUE TITLE
How to troubleshoot mqtt publisher in docker?

### ISSUE THREAD

**Issue by embolon** [mikebrady/shairport-sync#1208]
I am experimenting the mqtt publisher with a docker shairport-sync container using the recommended configuration in the MQTT.md document, but the mqtt broker does not see anything published. Is mqtt publisher supported in the docker installation? How to troubleshoot in this case?

Note: the testing mqtt broker is local without any security rules or user/pass.

**Comment by mikebrady** [comment]
Thanks for the post. TBH, I'm not an expert on either MQTT or Docker, so I suggest maybe looking at prior issues, e.g. [this one](https://github.com/mikebrady/shairport-sync/issues/1005). In any case, I suggest that setting the verbosity of Shairport Sync to 1 or 2 might help.

**Comment by embolon** [comment]
Thanks a lot for your quick response! I try out the config that you mentioned. Docker sends out diagnostic logs correctly after I add
`
diagnostics = {
  log_output_to = "/var/log/shairport-sync.log";
  log_verbosity = 2;
};
`
and find that there is a mistake in my configuration file. I put
`
enable = "yes";
`
which should be 
`
enabled = "yes";
`
Now the local mqtt broker can get the published metadata information. May I suggest add how to enable the diagnostic configuration into the docker or configuration documents?

**Comment by mikebrady** [comment]
Thanks for the suggestion.
