### ISSUE TITLE
Script "run_this_before_play_begins" can't write to file

### ISSUE THREAD

**Issue by MCUdude** [mikebrady/shairport-sync#1212]
Hi!
This is more of a question, but I'm very stuck at the moment and could need some help.

I'm using Shairport-sync to control my surround receiver. When I start Shairport sync it turns on the receiver, asks for the current source and volume, stores this in a file and changes the audio source to the one assigned to Shaiport-sync.

On disconnect it changes back to the previous source and volume by running another script.

The problem is that the receiver spits out list of information when volume and source is queried, so Iæm just dumping all this into a file. This has been working fine for a week or so, but now I don't have write access to this file anymore. It's just a text file in my home folder, nothing special.

```
# Path to start script
/home/chromebox/Marantz_SR5008_Shairport_start.sh

# Path to file that data should be stored to
/home/chromebox/Marantz_status.txt
```

Start script:
``` bash
#!/bin/bash

# 
# 

# Turn on the power for the main zone
#echo ZMON | nc marantz.local 23 -C
echo -ne ZMON\\r | nc -w1 marantz.local 23

# wait a little
sleep 3

sudo su

# Store previous source and volume setting so we have something to return back to
echo -ne SI?\\r | nc -w5 marantz.local 23 > /home/chromebox/Marantz_status.txt
sleep 1
echo -ne MV?\\r | nc -w5 marantz.local 23 >> /home/chromebox/Marantz_status.txt
sleep 1

# Set the correct source (DVD)
#echo SIDVD | nc marantz.local 23 -C
echo -ne SIDVD\\r | nc -w1 marantz.local 23

# wait a little
sleep 1

# Set the correct volume (-18 dB)
#echo MV62 | nc marantz.local 23 -C
echo -ne MV62\\r | nc -w1 marantz.local 23

sleep 1

# Set subwoofer level to +4dB
# (50 = 0dB, 54 = +4dB)
#echo CVSW 54 | nc marantz.local 23 -C
echo -ne CVSW 54\\r | nc -w1 marantz.local 23

```

When I run `sudo service shairport-sync status`I get this log:
```
Jun 21 20:44:56 chromebox sudo[1886]: shairport-sync : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/su
Jun 21 20:44:56 chromebox sudo[1886]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 21 20:44:56 chromebox su[1887]: Successful su for root by root
Jun 21 20:44:56 chromebox su[1887]: + ??? root:root
Jun 21 20:44:56 chromebox su[1887]: pam_unix(su:session): session opened for user root by (uid=0)
Jun 21 20:44:57 chromebox su[1887]: pam_unix(su:session): session closed for user root
Jun 21 20:44:57 chromebox sudo[1886]: pam_unix(sudo:session): session closed for user root
Jun 21 20:44:57 chromebox shairport-sync[1001]: /home/chromebox/Marantz_SR5008_Shairport_start.sh: line 16: /home/chromebox/Marantz_status.txt: Permission denied
Jun 21 20:44:58 chromebox shairport-sync[1001]: /home/chromebox/Marantz_SR5008_Shairport_start.sh: line 18: /home/chromebox/Marantz_status.txt: Permission denied
Jun 21 20:44:58 chromebox shairport-sync[1001]: /home/chromebox/Marantz_SR5008_Shairport_start.sh: line 18: echo: write error: Broken pipe
```

How can I get write access to a text file within the script? I've tried adding `sudo`, but that doesn't help at all.

**Comment by p3ck** [comment]
Your sudo su doesn't mean the commands after it are run in the sudo
context.  You can see in the log that sudo runs (session opened) and then
sudo closed (session closed)  Then the rest of your commands run.

I would check what user you are running shairport-sync as and what user the
file is.  You could also change the path to /tmp which every user should be
allowed to write to.

And I'm jealous that you can send commands like that to your receiver.  I
have a serial port on my Sony and have yet to figure out a nice way to do
that :-)

**Comment by MCUdude** [comment]
> I would check what user you are running shairport-sync as and what user the
file is.  You could also change the path to /tmp which every user should be
allowed to write to.

This is exactly what I'm looking for! I don't really care _where_ the file is located, as long as the script has read and write permissions to it. I'll give it a try and report back!

> Your sudo su doesn't mean the commands after it are run in the sudo
context.  You can see in the log that sudo runs (session opened) and then
sudo closed (session closed)  Then the rest of your commands run.

Just for fun, how do I check this?

> And I'm jealous that you can send commands like that to your receiver.  I
have a serial port on my Sony and have yet to figure out a nice way to do
that :-)

If you have a receiver with a serial port and/or ethernet power, there are good chances there is a telnet interface you can utilize. I'm using the Telnet interface, but I'm using netcat (nc) since it's better at connecting, sending a message, and logging out than telnet is.

**Comment by MCUdude** [comment]
>> I would check what user you are running shairport-sync as and what user the
file is. You could also change the path to /tmp which every user should be
allowed to write to.

> This is exactly what I'm looking for! I don't really care where the file is located, as long as the script has read and write permissions to it. I'll give it a try and report back!

Storing the file in /tmp/ certainly solved my problem. Thank you!

@p3ck if you tell me which Sony receiver you have, I can take a look at the programming manual to see if there's an easy way to interface with it 🙂
