### ISSUE TITLE
Gapless playback is not available only between the first track and the second track. 

### ISSUE THREAD

**Issue by kevin314159** [mikebrady/shairport-sync#1216]
Thank you for the wonderful project.

I am using shairport-sync on my Linux-PC and there is one strange problem.

Gapless playback is not available only between the first track and the second track.
From the second track, playback will be gapless. 
When I look RTP audio data that is actually transmitted, several mute frame(filled with 0x00) is transmitted between the first track and the second track. Additionally, if you do a Seek during playback, a mute frame is added between that song and the next song, so it cannot be played gapless.

Using the same phone and pad, when I test it with another device that supports airplay, gapless playback is always normal.

I looked at the source code, but couldn't find the cause. What could be the problem?

./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd

**Comment by mikebrady** [comment]
Thanks for the post. It is a bit surprising that the silent frames are added, but from what your write, it seems that they are added by the source. One can only guess as to why they are added. What kind of "other devices" are you referring to, please? Are they AirPlay 1 or AirPlay 2 devices? How do you access the bit stream?

**Comment by kevin314159** [comment]
I was testing with Samsung Smart TV(KQ43QT60AFXKR), which it seems that support airplay 2.
When testing with a TV, I didn't check the bit stream. 
However, if you check an album( in Apple Music) which each track is played continuously, the TV plays seamlessly, but you can hear the sound cut off in shairport-sync.

For example, 
Track 1 -> Track 2 -> Track 3 ...

When I started on track 1, there are mute frames(RTP packet with mute PCM) between track 1 and track 2, but no mute frames between track 2 and track 3.
When I started from track 2, there are mute frames between track 2 and track 3.

I used the following code to check if there are mute frames.

at line 1419 in player.c 
    {
        static int muted_packet_count = 0;
        int i, muted_packet = 1;
        for(i=0;i<curframe->length;i++) {
            if (curframe->data[i] != 0x00) {
                muted_packet = 0;
                break;
            }
        }

        if (muted_packet) {
            muted_packet_count++;
            printf("--------------------------------->got muted_packet[%d]\n", muted_packet_count);
        }
        else {
            muted_packet_count = 0;
        }
    }

In testing, Airplay( or Apple Music) sends a mute packet on startup or seeking. But I don't know why they send it between the first track and the second track as well. Is it sending something for audio sync or latency recovery. 
I wonder if this problem only occurs in my environment.
I tried rebuilding and testing on another Linux-PC, but the same problem occurred.

**Comment by mikebrady** [comment]
Thanks. Just to clarify, looking at `player.c` in the current `master` branch, I see this:
   

    1412 // seq_t read = conn->ab_read;
    1413 if (curframe) {
    1414   if (!curframe->ready) {
    1415     // debug(1, "Supplying a silent frame for frame %u", read);
    1416     conn->missing_packets++;
    1417     curframe->given_timestamp = 0; // indicate a silent frame should be substituted
    1418     }
    1419     curframe->ready = 0;
    1420  }
    1421  conn->ab_read = SUCCESSOR(conn->ab_read);
    1422  pthread_cleanup_pop(1);
    1423  return curframe;

So, is it just after line 1420 that you place your code?

**Comment by kevin314159** [comment]
I have inserted my code between line 1418 and line 1419.

 // seq_t read = conn->ab_read;
  if (curframe) {
    if (!curframe->ready) {
      // debug(1, "Supplying a silent frame for frame %u", read);
      conn->missing_packets++;
      curframe->given_timestamp = 0; // indicate a silent frame should be substituted
    }

    {
        static int muted_packet_count = 0;
        int i, muted_packet = 1;
        for(i=0;i<curframe->length;i++) {
            if (curframe->data[i] != 0x00) {
                muted_packet = 0;
                break;
            }
        }

        if (muted_packet) {
            muted_packet_count++;
            printf("--------------------------------->got muted_packet[%d]\n", muted_packet_count);
        }
        else {
            muted_packet_count = 0;
        }
    }

    curframe->ready = 0;
  }
  conn->ab_read = SUCCESSOR(conn->ab_read);
  pthread_cleanup_pop(1);
  return curframe;

**Comment by mikebrady** [comment]
Super, thanks. I'll take a look.

**Comment by mikebrady** [comment]
That was very interesting, thanks. I modified your code to get more information and moved it:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/4265913/124456818-0e948200-dd83-11eb-8e73-ec25ee65d81f.png">

I was playing tracks in an album imported from a CD in ALAC format in macOS Music. What I got was in agreement with your observations. The empty frames are definitely coming from the source -- they are not being "made up" by Shairport Sync. They have RTP timestamps consistent with their lengths and position in the stream of audio. The non-empty frame terminating a run of empty frames has an RTP timestamp consistent with following the empty frames in time.

Furthermore, the number of empty frames after a particular track was always the same.

```
       123.288912854 "player.c:532" player_put_packet: muted_packet[1, length: 352, timestamp: 2307040259].
         0.008446389 "player.c:535" player_put_packet: 1 muted packets seen. Next packet timestamp: 2307040611.
         0.063436984 "player.c:532" player_put_packet: muted_packet[1, length: 352, timestamp: 2307043427].
...
         0.007637233 "player.c:532" player_put_packet: muted_packet[277, length: 352, timestamp: 2307140579].
         0.008037525 "player.c:532" player_put_packet: muted_packet[278, length: 352, timestamp: 2307140931].
         0.008128986 "player.c:532" player_put_packet: muted_packet[279, length: 352, timestamp: 2307141283].
         0.008067950 "player.c:535" player_put_packet: 279 muted packets seen. Next packet timestamp: 2307141635.
```
So, my conclusion is that the source is inserting empty frames, but I have no idea why. Maybe it only happens when sending to an AirPlay 1 device -- I really don't know, I'm afraid.

For reference, here is the code:

        {
          static int muted_packet_count = 0;
          int i, muted_packet = 1;
          for (i = 0; i < abuf->length; i++) {
            if (abuf->data[i] != 0x00) {
              muted_packet = 0;
              break;
            }
          }

          if (muted_packet) {
            muted_packet_count++;
            debug(1, "player_put_packet: muted_packet[%d, length: %d, timestamp: %u].",
                  muted_packet_count, abuf->length, abuf->given_timestamp);
          } else {
            if (muted_packet_count != 0)
              debug(1, "player_put_packet: %d muted packets seen. Next packet timestamp: %u.",
                    muted_packet_count, abuf->given_timestamp);
            muted_packet_count = 0;
          }
        }

**Comment by kevin314159** [comment]
Thank you for quick response.

As you said, muted packets have a valid RTP sequence number, timestamp and length, so it looks like the packet cannot be skipped.

Please let me know if there are any updates related to this issue.

**Comment by JohanJongstra** [comment]
I have the same problem as above. I use apple music and a classical piece (https://music.apple.com/nl/album/vivaldi-corelli/1572111235). Between track 1 and 2 there shouldn't be a gap... I noticed when I turn volume=software to none, the problem is solved. 
I play apple music on a new macbook air. When airplay is turned off the gapless playback is just normal. I also acknowledge that gapless only fails between track 1 and 2 when volume in shairport-sync is 'software'... Hope this helps to solve the problem...

**Comment by mikebrady** [comment]
Thanks for the report. Can you clarify what you mean by:
> when I turn volume=software to none

and:

> when volume in shairport-sync is 'software'

please?

**Comment by mikebrady** [comment]
Thanks. I’m not familiar with Ropieee XL, I’m afraid. I’ll try to experiment with Shairport Sync on its own.
