### ISSUE TITLE
Unable to install shairporty-sync development with Airplay 2 support

### ISSUE THREAD

**Issue by CyberMrProper** [mikebrady/shairport-sync#1225]
Hi @mikebrady,

I'm trying to install shairport-sync with Airplay 2 support but having the following error:

>Include libraries required for AirPlay 2
checking for libplist... no
configure: error: AirPlay 2 support requires libplist 2.0.0 or later -- libplist-dev suggested!

Not sure what's happening as I have installed libplist-dev:
>$ apt-cache policy libplist-dev
libplist-dev:
  Instalados: 1.12+git+1+e37ca00-0.3
  Candidato:  1.12+git+1+e37ca00-0.3
  Tabla de versión:
 *** 1.12+git+1+e37ca00-0.3 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status

Need some advice.
Thanks

**Comment by charlesomer** [comment]
Hi @CyberMrProper, it looks like you have version 1.12 if `libplist`. Version 2.0.0 or later is required for Shairport Sync with AirPlay 2.

It seems you're running the stretch version of Raspberry Pi OS, I believe the buster version of Raspberry Pi OS now ships with `v2.0.1` available: https://packages.debian.org/buster/libplist-dev.

**Comment by mikebrady** [comment]
Thanks for the post. As it says in the guide, you need to be on the latest version of Raspberry Pi OS. It looks like you have "Stretch", which is too old.

**Comment by CyberMrProper** [comment]
Thanks guys, I've updated to buster and it seems to be working!

**Comment by CyberMrProper** [comment]
Thanks guys, I've updated to buster and it seems to be working!
