### ISSUE TITLE
Wake up speaker in standby mode during playback ?

### ISSUE THREAD

**Issue by lois-hrt** [mikebrady/shairport-sync#1230]
Hello,
I try the project BUILDFORAP2 and it works perfectly at home with a Raspberry Pi 3. Thank you very much!
However, I have a question.
Indeed, I noticed that with some projects like « balena sound » for exemple, it was possible to automatically wake up your speaker in standby mode during playback.
I would like to know if a setting in the "Shairport-sync.conf" file allowed this option to be enabled?
Thanks in advance (sorry for my broken English « I am French »).

**Comment by mikebrady** [comment]
Thanks for your post. Your English is fine.

To answer your question, Shairport Sync has some hooks for executing programs or scripts just before it starts to be active and just after it goes inactive. You will find them in the `/etc/shairport-sync.conf` configuration file.

There are two groups, one works on the basis of the `active` state and the other works on the basis to the `play` state.
My suggestion is to try the `active` hooks first. You need to take care to ensure the programs or scripts run correctly in the environment they are launched in when Shairport Sync is a daemon.

You may find examples in the issues here, including the closed issues. Alternatively, some contributors might me able to give you samples directly.

These are the hooks in the configuration file.

```
//	run_this_before_entering_active_state = "/full/path/to/application and args"; // make sure the application has executable permission. If it's a script, include the shebang (#!/bin/...) on the first line
//	run_this_after_exiting_active_state = "/full/path/to/application and args"; // make sure the application has executable permission. If it's a script, include the shebang (#!/bin/...) on the first line
//	active_state_timeout = 10.0; // wait for this number of seconds after play ends before leaving the active state, unless another play session begins.

//	run_this_before_play_begins = "/full/path/to/application and args"; // make sure the application has executable permission. If it's a script, include the shebang (#!/bin/...) on the first line
//	run_this_after_play_ends = "/full/path/to/application and args"; // make sure the application has executable permission. If it's a script, include the shebang (#!/bin/...) on the first line
```

**Comment by lois-hrt** [comment]
Thanks, I did not read the file « Shairport-sync.conf » carefully enough.
I have uncomment the two « before » hooks and the timeout and it work to wake up the speaker !

`run_this_before_entering_active_state = "/full/path/to/application and args"; `
`active_state_timeout = 10.0;`
`run_this_before_play_begins = "/full/path/to/application and args";`

Thanks for your quick reply ! Great job for this projet !

**Comment by embolon** [comment]
I did something very similar through home assistant using the mqtt module. The mqtt module can report play states that can be used to create automations to turn on/off smart devices.
