### ISSUE TITLE
Avahi inside docker seems to cause IP/hostname conflicts

### ISSUE THREAD

**Issue by embolon** [mikebrady/shairport-sync#1231]
I was trying with the docker image before and find the syslog is flooded with mDNS errors massages. Sorry I didn't post it in time that I already lost all my old logs. Now I switch to use the compiled binary directly and the error massages are gone. I read that this may be caused by the avahi inside the docker container and the avahi on the host are sharing the same IP address and hostname, which caused the conflicts. Maybe the docker container should use a different IP address rather than using "host" network?

Host is a raspberry pi 4 running raspberry pi OS.

**Comment by mikebrady** [comment]
Thanks for the post. Can you say which image you are referring to, please?

**Comment by embolon** [comment]
Was using the image mikebrady/shairport-sync latest previously about 2 ~ 3 weeks ago. I am happy with the compiled binary now. So feel free to close it if it doesn't repro. I like this project very much and thanks for the constant updates.
