### ISSUE TITLE
multiroom not possible with Airplay2?

### ISSUE THREAD

**Issue by huddx01** [mikebrady/shairport-sync#1232]
Hi,

i tried out the Airplay2 Feature from development branch.
shairplay-sync -V gives:
4.0-dev-179-g2184f1b-AirPlay2-alac-OpenSSL-Avahi-ALSA-jack-soxr-metadata-dbus-sysconfdir:/etc

But it seems to be impossible to launch two instances...

I use the /lib/systemd/system/shairport-sync@.service - Method from @cre8dojo
https://github.com/mikebrady/shairport-sync/issues/37#issuecomment-192993877

with the older Version 3.3.8 it works flawlessly without any Problems.
3.3.8d5-alac-libdaemon-OpenSSL-Avahi-dns_sd-ALSA-soxr-metadata-dbus-sysconfdir:/etc

Has someone tried this also? any hints?

thanks in advance.

**Comment by charlesomer** [comment]
Hi @huddx01, unfortunately at the moment only one instance of Shairport Sync can be run with AirPlay 2 on a particular device due to the more complex nature of AirPlay 2 compared to AirPlay 1.

> Only a single instance of Shairport Sync can run on a device.
https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md#limitations

**Comment by huddx01** [comment]
oh... i probably did no read careful enough :-)

thanks @charlesomer

**Comment by charlesomer** [comment]
No worries :)

**Comment by magichew** [comment]
Is this something that may change or is it a technical impossibility?

**Comment by charlesomer** [comment]
Based on what we know at the moment, it's unlikely to change unfortunately. Even with Docker I've not found a way to be able to do it. Having multiple VMs _might_ work but I haven't tried doing anything like that :/

**Comment by chrisimaxwell** [comment]
Happy shairport-sync user for many years. Thank you.
I was successfully using multiple instances via excellent instructions in this comment:
  https://github.com/mikebrady/shairport-sync/issues/37#issuecomment-192993877

Any update regarding multiple instances with Airplay2?

I don't seem this addressed in 'limitations' despite comment above.
 https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md#limitations

I found this (newer) docker container+config (suggesting but not confirming multiple instances) but haven't tried it yet as I have no docker expertise.
https://github.com/noelhibbard/sharport-sync-docker
