### ISSUE TITLE
alsa error -19 "No such device" (no audio out)

### ISSUE THREAD

**Issue by UngluedChalice** [mikebrady/shairport-sync#1240]
Ok, I'm super new to all of this. I've tried my best reading and googling, but I just can't figure it out. 

These are the same settings I had a week ago and it worked. Yesterday I was messing with the pi (was trying to get it to boot from an SSD, but couldn't get it to work at all, so I have it set up now just like I did before) but I didn't touch shairport-sync except to copy the config file to an SSD data drive as a backup. After that I didn't work - it would not show up as an AirPlay device. So obviously I did something that messed it up, so I followed the basic instructions to remove old versions and reinstalled. I copied over my old config file that had worked already. Maybe that's the issue, because it's an older config file and how that's formatted is way different now?

When I run`shairport-sync -V` 
I get:
`3.3.8-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`

When I run `shairport-sync -h`

at the bottom it shows
`hardware output devices:`
      `"hw:sndrpihifiberry"`

I can see on my iPhone the AirPlay device, which I have called `Speakers`. However, there is no audio output. 

So I ran `sudo systemctl status shairport-sync` and got a bunch of output split up into sections. It would have some stuff that appears to be truncated and then have `lines 1-18/18 (END)` and then I scroll down through some blank area and then more output the same as above that is slightly less truncated. Scrolling down a ton, I finally seem to see the entire output which is

```
shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-07-13 14:12:56 CDT; 2min 46s ago
 Main PID: 1930 (shairport-sync)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/shairport-sync.service
           └─1930 /usr/local/bin/shairport-sync

Jul 13 14:13:15 raspberrypi shairport-sync[1930]: ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: warning: alsa: error -19 ("No such device") opening alsa device "hw:snd_rpi_hifiberry_dacplus".
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: warning: alsa: error -19 ("No such device") opening alsa device "hw:snd_rpi_hifiberry_dacplus".
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: warning: alsa: error -19 ("No such device") opening alsa device "hw:snd_rpi_hifiberry_dacplus".
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: warning: alsa: error -19 ("No such device") opening alsa device "hw:snd_rpi_hifiberry_dacplus".
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Jul 13 14:13:15 raspberrypi shairport-sync[1930]: warning: alsa: error -19 ("No such device") opening alsa device "hw:snd_rpi_hifiberry_dacplus".
```

If I go to the Shairport-Sync configuration file, I have this set up for alsa:

```
alsa =
{
//  output_device = "hw:1";
//  mixer_control_name = "Speaker";
    output_device = "hw:sndrpihifiberry";
    mixer_control_name = "Digital";
};
```
When I run `alsamixer` I get the following:

```
cards:
0 [sndrpihifiberry]: HifiberryDacp - snd_rpi_hifiberry_dacplus
snd_rpi_hifiberry_dacplus   

devices:
 0: [ 0]   : control
16: [ 0- 0]: digital audio playback
33:       : timer   

pcm:
00-00: HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0 :  : playback 1
```

Is the devices one normal? That one seems odd.

So anyway, I figure it is something easy, but I don't have a good understanding yet of how all this works, rather I just follow instructions and copy/paste code. Thanks for any help anyone can give!

**Comment by mikebrady** [comment]
Thanks for the post. Somehow, Shairport Sync is picking up the output device name `"hw:snd_rpi_hifiberry_dacplus"`, which is incorrect; it should be `"hw:sndrpihifiberry"`.

So you need to find the configuration file that Shairport Sync is using. If you do:
```
$ shairport-sync -V
```
you'll get a string like this:

```
3.3.8-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc
```
Note the path following `sysconfdir`. In  this case it is `/etc` -- yours might be the same or different. In this case, it means that Shairport Sync expects the configuration file to be at `/etc/shairport-sync.conf`. In other words, the sysconfdir (`/etc` in this case) is where the configuration file that Shairport Sync is using is to be found.

Note that whenever you change the configuration file, you must restart Shairport Sync to get it to read it.

**Comment by UngluedChalice** [comment]
Thank you for the reply! The config file is indeed at `/etc/shairport-sync.conf`. And I've been using the command `sudo systemctl stop shairport-sync` and the similar one to start it each time I make a change to the `config` file after the write-out the file. 

So how do I address this issue? 

> Somehow, Shairport Sync is picking up the output device name "hw:snd_rpi_hifiberry_dacplus", which is incorrect; it should be "hw:sndrpihifiberry".

>

**Comment by mikebrady** [comment]
Well, it must be picking up the name from somewhere. Can you post the response from:
```
$ shairport-sync-V
```
please?

**Comment by UngluedChalice** [comment]
`3.3.8-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`

Yeah, I figured I messed something up somewhere.

**Comment by mikebrady** [comment]
Great -- I'm glad it worked out for you. Yeah, deleting that directory was the right thing to do.

**Comment by UngluedChalice** [comment]
Oh, I'm sorry, that edit was something that happened when I was re-installing the software package. Didn't know if that could indicate where shairport-sync is pulling that `"hw:snd_rpi_hifiberry_dacplus"` from. Any advice on how to track that down? 

I'm wondering at this point if I need to just nuke the entire thing and start over with containers so that when I mess stuff up, I can just nuke that container. I'm also running a Unifi controller, Plex Media Server, Pi Hole, and soon Home Assistant and Wireguard on this Pi, so it's a lot to go back and re-do every time I mess something up and need to start over as I don't know how to fix it.

**Comment by mikebrady** [comment]
Hmm. Sounds like a pile of work. Much better to see what's really happening.

From your information earlier:
```
3.3.8-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
```
The configuration file must be in `/etc`, so it must be `/etc/shairport-sync.conf`. So, once thing to do is to rename it so that Shairport Sync can't find it, e.g. rename it suspect-shairport-sync.conf. Then restart Shairport Sync and see what is in the logs... It will pick defaults for everything.

**Comment by UngluedChalice** [comment]
Also, these are the shairport files (before renaming the `conf` file) in `.etc`, in case all those save files mean something bad. 
```
shairport-sync.conf
shairport-sync.conf.sample
shairport-sync.conf.save
shairport-sync.conf.save.1
shairport-sync.conf.save.2
 shairport-sync.conf.save.3
shairport-sync.conf.save.4
shairport-sync.conf.save.5
shairport-sync.conf.save.6
```

Okay, I renamed the `conf` file and then stopped and then started shairport-sync. I then ran the `status` command and the output is below. There is no new `shair-port-sync.conf` file in `etc` now. I can see it from my iPhone as `raspberrypi`, so that name has changed from my default `Speakers` but it doesn't output audio. 

```
shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-07-14 14:57:30 CDT; 12s ago
 Main PID: 20387 (shairport-sync)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/shairport-sync.service
           └─20387 /usr/local/bin/shairport-sync

Jul 14 14:57:30 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

**Comment by mikebrady** [comment]
What are all the `.save` files??

**Comment by UngluedChalice** [comment]
I opened them and they look like a bunch of different versions of the `.conf` files. Most of them were made on 5/12/2019 and one was made on 11/22/2020. I did not purposely create any of them.

**Comment by mikebrady** [comment]
I thin this are temporary files created while the `nano` editor is running. They should be deleted when it finishes. It would be worth finding out why they weren’t deleted.
