### ISSUE TITLE
Airplay 2 pairing with Home app failing

### ISSUE THREAD

**Issue by CyberMrProper** [mikebrady/shairport-sync#1246]
Hi there, 
I've downloaded and installed the latest on development branch, I'm able to see the speaker listed and available to be added in home app, but when I click on the name it says: "Unable to Add Accessory".
Not sure if I need to configure something or it should work quite straightforward. @mikebrady do you know?
Thanks

**Comment by charlesomer** [comment]
Hi @CyberMrProper, could you post the result of `shairport-sync -V`? HomeKit integration was only added recently so you might need to update :)

**Comment by CyberMrProper** [comment]
4.0-dev-186-ge26d3ed-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc

**Comment by onlytobeking** [comment]
I'm trying to do the same thing with the same version, but I can't even get it to show up in the home app, did it pop up by itself or did you have to do anything? Code?

**Comment by CyberMrProper** [comment]
Nothing, just downloaded the latest development branch code, install it, restart and it started being listed in Home app. But when I click on the speaker name "Unable to Add Accessory" message is being displayed.

**Comment by noelhibbard** [comment]
Strange, I don't see a commit hash of "ge26d3ed" in the dev branch. I compiled this morning on commit hash g5630e20e and it's working fine. I can now add and remove speakers with Siri. I simply ran the Home app, click the + button at the top right. clicked "Add Accessory" then clicked "I Don't Have a Code or Cannot Scan" and then it listed my speakers. I then click on the speaker and it asks me to give it a name and what room to put it in. After that it shows up in the Home app and I can say, "Hey Siri, start playing in the living room and bedroom". I can also say, "Hey Siri, add the porch speaker" and it will say "Okay I added the porch speaker". But rather than "add" the porch it switches to the porch and all the others are dropped. I'm not sure if this is an Apple bug or something not right with SPS.

**Comment by CyberMrProper** [comment]
That commit is the latest in https://github.com/mikebrady/shairport-sync/commits/development

Steps I followed:
- Home app, clicked the + button at the top right. 
- Clicked "Add Accessory" then clicked "I Don't Have a Code or Cannot Scan" 
- My speaker is listed, then click on the speaker Name
- "Unable to Add Accessory" message is shown.

**Comment by noelhibbard** [comment]
I'm an idiot, I was looking for hash ge26d3ed not realizing the g isn't part of the hash. I do see some code changes after the commit I am running. Some of the code changes seem to be HomeKit related so maybe a bug was introduced. Maybe roll back to 5630e20e and see if it works for you.

**Comment by CyberMrProper** [comment]
@ejurgensen any idea on what I could be doing wrong or missing?

**Comment by ejurgensen** [comment]
No idea, I think debug level logging would be required to provide at least a clue

**Comment by charlesomer** [comment]
You may have already tried this but I was having an issue with the Home app earlier when looking for new accessories and it took a restart of my phone to fix it

Also, do you have a hub in your HomeKit setup? I'm not sure if that makes a difference or not though

**Comment by CyberMrProper** [comment]
I have several hubs (HomePods and AppleTVs). I've tried adding a new home without any hub and its working on that case.... really weird.

**Comment by onlytobeking** [comment]
A restart of my phone worked for me, thanks!

**Comment by CyberMrProper** [comment]
Well after several tries, it worked!

**Comment by CyberMrProper** [comment]
I was able to add it.

**Comment by charlesomer** [comment]
Excellent! Glad to hear it 😄

**Comment by mikebrady** [comment]
We have lot to learn about this!

**Comment by mikebrady** [comment]
> I'm an idiot, I was looking for hash ge26d3ed not realizing the g isn't part of the hash. I do see some code changes after the commit I am running. Some of the code changes seem to be HomeKit related so maybe a bug was introduced. Maybe roll back to [5630e20](https://github.com/mikebrady/shairport-sync/commit/5630e20eb02d28ce3d53abd38faab7c991986238) and see if it works for you.
> 
> Looking closer at the code changes they are just formatting changes. I don't see anything that changed that would break anything. Must be something related to your environment.

Yeah, unfortunately, adding release notes and stuff like that results in further commits to the repository that increase the build number and change the hash.

**Comment by leo150** [comment]
I'm trying to do exactly the same, but Raspberry 4 (Raspbian GNU/Linux 10) doesn't appear in the accessory search of Home app. Tried to reboot both Raspberry and iPhone (iOS 15.1). Also tried to search the raspberry from iPad (iPad OS 15.0.2). 

When I select the output speaker on iPhone or iPad, I see Raspberry in the speakers list, can connect and play audio. It only doesn't appear in the accessory search in Home app. I have latest version from development branch.
```
$ shairport-sync -V
4.1-dev-101-gfbce5906-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
```
My config is default. What am I missing?
