### ISSUE TITLE
4.0-dev-186 - HomeKit support question

### ISSUE THREAD

**Issue by acresp** [mikebrady/shairport-sync#1247]
Hello,

Just upgraded to 4.0-dev-186
The HomeKit support seems working nice.
Just a question, there is no "playing" state on the Home tiles. Is it something that it can be implemented ? When shairport is playing, I see all the metadata when I push the tile, I can also ask Siri to play in a certain room, but the tile in the Home app stays greyed instead of being lighed up with the "Playing" state.

Great work!

**Comment by mikebrady** [comment]
Thanks. Yeah, there are lots of things missing. It's on the list. 🙂

**Comment by mikebrady** [comment]
Just push an update to the `development` branch which should improve things in general. It doesn't cause the speaker tiles to light up, I'm afraid, but improves some other things. If you got a chance to try it and report back, that would be cool.

**Comment by roboterm** [comment]
I know this is stale but I even got the same problem. The tile keeps inactive. Press and hold works as intended.
