### ISSUE TITLE
Connection drops every few minutes when streaming from iOS

### ISSUE THREAD

**Issue by fwcd** [mikebrady/shairport-sync#1259]
This seems similar to #1166 and #1148, but I couldn't figure out whether it is exactly the same issue (feel free to close if it is). Usually it goes like this:

* iOS connects successfully to `shairport-sync`
* Music plays for a few minutes
* The audio stutters/pauses, possibly due to an unreliable network, this usually causes `Player has supplied a silent frame`-messages to show up in the log, then either of the following happens:
    * `shairport-sync` catches up with the stream, emits `Sent ... frames of silence` and `Large negative sync error` and continues to play again
    * The connection times out, iOS seems to 'notice' this more quickly than `shairport-sync`, preventing us from reconnecting to `shairport-sync` for another minute or so (until `shairport-sync` drops the connection too)

I am using the most recent `development` branch of `shairport-sync` with AirPlay 2 support and the `alsa` backend on a Raspberry Pi 3B running Raspbian 10 and as a client an iOS 14.7 device streaming from Spotify (i.e. not using buffered AirPlay 2).

A sample log showing several such 'stutters' and a timeout at the end can be found here:

[shairport-sync.log](https://github.com/mikebrady/shairport-sync/files/6873857/shairport-sync.log)

Another (related?) connectivity issue I've noticed is that if iOS drops the WiFi connection and reconnects quickly, the UI still indicates that it still actively streams via AirPlay, while `shairport-sync` seems to have lost the connection. Sample log:

[shairport-sync-wifi-drop.log](https://github.com/mikebrady/shairport-sync/files/6873862/shairport-sync-wifi-drop.log)

Any tips on how to debug these (I presume) network-related issues?

Thanks for this awesome piece of software by the way, the multi-room AP2 support is already really nice and I can't wait to play it with more!

**Comment by mikebrady** [comment]
Thanks for the post and for the kind words. I guess the first suggestion I'd have is to look through the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) guide. In particular, if you're WiFi, make sure WiFi power management is `off.` Sometimes these problems can also be caused, of course, by a loss of the incoming stream, but I guess you've considered that. 

I don't have any specific network-troubleshooting tips beyond trying to ensure everything is as up-to-date as possibleseet , ensuring any firewalls are configured correctly and by systematically trying to eliminate possible problems. For example, if you can bypass WiFi on a leg of the transmission path, try it and see if it makes any difference, and so on.

**Comment by fwcd** [comment]
I figured out part of the problem... the WiFi connectivity drops were caused by having a repeater on my network that caused the iOS device to connect back and forth between the repeater and the main AP.

Removing the repeater from the network fixed the disconnects, I'll have to investigate the stutters further, but I assume those are network-related issues too.

**Comment by noelhibbard** [comment]
Roaming shouldn't cause the connection to drop though. Are all your APs on the same subnet, do they all have the same SSID and are they all distanced channel wise (only 1, 6 and 11 are free of overlap on 2.4GHz)? So many people get WiFi setup completely wrong and do any of these things:
1: Put them all on the same channel
2: Leave them on auto channel and expect it to do a good job
3: Create an SSID for each AP. Ex: FrontRoom, BackPorch, ect ect
4: Use WiFi "boosters" or "repeaters" rather then hard wiring them. If you can't run ethernet then consider MoCA (if you have coax at hand) or Powerline adapters.

**Comment by danievanzyl** [comment]
I can comment - I've been using `software version: "4.0-dev-312-g687fd167-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc"` - no connection issues thus far.

```shairport-sync -vu --statistics
         0.002201765 "shairport.c:1823" Started!
         0.000120104 "shairport.c:1826" Started in Airplay 2 mode!
         0.000487134 "shairport.c:1868" software version: "4.0-dev-312-g687fd167-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc"
         0.000034323 "shairport.c:1874" log verbosity is 1.
         0.000305780 "audio_alsa.c:1015" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000148333 "audio_alsa.c:1302" alsa: disable_standby_mode is "never".
         0.000024688 "audio_alsa.c:1304" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000127655 "audio_alsa.c:1306" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000199583 "audio_alsa.c:1345" alsa: output device name is "hw:Headphones".
         0.000423749 "shairport.c:1903" libsodium initialised.
         0.000027969 "shairport.c:1930" disable resend requests is off.
         0.000122291 "shairport.c:1934" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000104479 "shairport.c:1935" statistics_requester status is 1.
         0.000021042 "shairport.c:1940" rtsp listening port is 7000.
         0.000105156 "shairport.c:1941" udp base port is 6001.
         0.000096093 "shairport.c:1942" udp port range is 10.
         0.000098333 "shairport.c:1943" player name is "Shairport sync 4.0-dev on Pi2.home".
         0.000099531 "shairport.c:1944" backend is "alsa".
         0.000199010 "shairport.c:1945" run_this_before_play_begins action is "(null)".
         0.000104427 "shairport.c:1946" run_this_after_play_ends action is "(null)".
         0.000101718 "shairport.c:1947" wait-cmd status is 0.
         0.000096979 "shairport.c:1948" run_this_before_play_begins may return output is 0.
         0.000098646 "shairport.c:1949" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000098125 "shairport.c:1950" run_this_before_entering_active_state action is  "(null)".
         0.000097968 "shairport.c:1951" run_this_after_exiting_active_state action is  "(null)".
         0.000097656 "shairport.c:1952" active_state_timeout is  10.000000 seconds.
         0.000266666 "shairport.c:1953" mdns backend "(null)".
         0.000582394 "shairport.c:1957" interpolation setting is "auto".
         0.000191041 "shairport.c:1958" interpolation soxr_delay_threshold is 30.
         0.000183698 "shairport.c:1959" resync time is 0.050000 seconds.
         0.000184322 "shairport.c:1960" allow a session to be interrupted: 0.
         0.000183437 "shairport.c:1961" busy timeout time is 0.
         0.000182083 "shairport.c:1962" drift tolerance is 0.001995 seconds.
         0.000184114 "shairport.c:1963" password is "(null)".
         0.000181979 "shairport.c:1964" ignore_volume_control is 0.
         0.000181302 "shairport.c:1968" volume_max_db is not set
         0.000180416 "shairport.c:1970" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000182968 "shairport.c:1974" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000188177 "shairport.c:1976" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000184062 "shairport.c:1977" disable_synchronization is 0.
         0.000181093 "shairport.c:1978" use_mmap_if_available is 1.
         0.000181770 "shairport.c:1980" output_format automatic selection is enabled.
         0.000182500 "shairport.c:1984" output_rate automatic selection is enabled.
         0.000181874 "shairport.c:1988" audio backend desired buffer length is 0.200000 seconds.
         0.000186927 "shairport.c:1990" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000578488 "shairport.c:1991" audio backend latency offset is 0.000000 seconds.
         0.000027812 "shairport.c:1993" audio backend silence lead-in time is "auto".
         0.001132602 "shairport.c:1997" zeroconf regtype is "_raop._tcp".
         0.000070885 "shairport.c:1998" decoders_supported field is 1.
         0.000502342 "shairport.c:1999" use_apple_decoder is 0.
         0.000064583 "shairport.c:2000" alsa_use_hardware_mute is 0.
         0.000052292 "shairport.c:2004" no special mdns service interface was requested.
         0.000085677 "shairport.c:2008" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000060729 "shairport.c:2014" metadata enabled is 1.
         0.000055677 "shairport.c:2015" metadata pipename is "/tmp/shairport-sync-metadata".
         0.000052031 "shairport.c:2017" metadata socket address is "(null)" port 0.
         0.000056041 "shairport.c:2018" metadata socket packet size is "500".
         0.000055261 "shairport.c:2019" get-coverart is 1.
         0.000050781 "shairport.c:2037" loudness is 0.
         0.000050989 "shairport.c:2038" loudness reference level is -20.000000
         0.000363124 "rtsp.c:3194" metadata pipe name is "/tmp/shairport-sync-metadata".
         0.006906701 "rtsp.c:4420" unable to listen on IPv4 port 7000. The error is: "Address already in use".
         0.000190624 "rtsp.c:4420" unable to listen on IPv6 port 7000. The error is: "Address already in use".
         0.000061250 "rtsp.c:4657" *warning: could not establish a service on port 7000 -- program terminating. Is another instance of Shairport Sync running on this device?
         0.000027917 "rtsp.c:4659" Oops -- fell out of the RTSP select loop
         1.495030202 "shairport.c:212" "soxr" interpolation has been chosen.
         0.000486093 "shairport.c:1455" exit```
