### ISSUE TITLE
Pipewire: ALSA Error when using Systemd Service

### ISSUE THREAD

**Issue by sclel016** [mikebrady/shairport-sync#1260]
Hi,

I can't seem to get `shairport-sync` working when using the `shairport-sync.service`. Things work fine when running the binary in a shell. I've attached relevant info and happy to troubleshoot and provide any information which might help. 

System
- Fedora 34 on Lenovo X1 Gen9
- shairport-sync: `3.3.7-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc`
- Default Configuration

Reproduction
1. Install `shairport-sync` on Fedora 34
2. `sudo systemctl start shairport-sync.service `
3. No errors
3. Play audio using iOS device
4. Service repeatedly throws error `warning: alsa: error -112 ("Host is down") opening alsa device "default".`

**Comment by noelhibbard** [comment]
What output do you get with `aplay -L`. Note the capital L. Also, do you get audio with `speaker-test`?

**Comment by sclel016** [comment]
I get audio with `speaker-test` over the default device (external USB Audio) as configure in `pavucontrol`.

<details>
  <summary> aplay -L </summary>
null
    Discard all samples (playback) or generate zero samples (capture)
sysdefault
    Default Audio Device
pipewire
    PipeWire Sound Server
default
    Default ALSA Output (currently PipeWire Media Server)
sysdefault:CARD=USB
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    Front output / input
surround21:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=USB,DEV=0
    ThinkPad Thunderbolt 3 Dock USB, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
sysdefault:CARD=CODEC
    USB Audio CODEC, USB Audio
    Default Audio Device
front:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    Front output / input
surround21:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=CODEC,DEV=0
    USB Audio CODEC, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
sysdefault:CARD=sofhdadsp
    sof-hda-dsp, 
    Default Audio Device
</details>

**Comment by noelhibbard** [comment]
aplay shows your default being pipewire?

**Comment by sclel016** [comment]
Yes, not quite sure how Alsa and Pipewire are supposed to interact to be honest. Pipewire is the new default audio framework for Fedora as of release 34. By default all audio is supposed to be routed from alsa to pipewire using the `pipewire-alsa` package. 

I'm not sure why the Pipewire sink would only present as an issue when lauching as a systemd service, I'm using shairport right now after launching in a terminal instance.

**Comment by mikebrady** [comment]
Thanks for the post. My guess is that the problem is that the [`pipewire-alsa` "plugin"](https://gitlab.freedesktop.org/pipewire/pipewire/-/tree/master/pipewire-alsa) runs as a user process -- it starts up when a user logs in. That means that when Shairport Sync starts up as a system deamon, the `pipewire-alsa` plugin isn't running, so the `alsa` device that it simulates is not available. This is what happens with PulseAudio.

**Comment by sclel016** [comment]
All Pipewire related processes are indeed run as user. I'm still not sure why this would be an issue once I'm already logged in with relevant processes started.

It could be that the issue is caused by the service being started as a system service instead of a user service. I managed to start `shairport-sync` using a simple user service.

```
[Unit]
Description= Airplay Service using Shairport Sync

[Service]
Type=simple
StandardOutput=journal
ExecStart=shairport-sync

[Install]
WantedBy=default.target
```

**Comment by sclel016** [comment]
@mikebrady are you okay with me closing this issue? Seems that a user service fixes the problem.

**Comment by mikebrady** [comment]
Sure thing, thanks!

**Comment by mikebrady** [comment]
Hi @sclel016. Would you be kind enough to share the text of the user service you made up, if you still have it, please?

**Comment by sclel016** [comment]
Here is the current text of my user service, very similar to what I posted last year.

```
[Unit]
Description= Airplay Service using Shairport Sync
After=pipewire-pulse.service

[Service]
Type=simple
StandardOutput=journal
ExecStart=shairport-sync -configfile=$XDG_CONFIG_HOME/shairport-sync/config


[Install]
WantedBy=default.target
```

**Comment by mikebrady** [comment]
Fantastic, thanks.

**Comment by mikebrady** [comment]
Thanks again for this.

I wonder, does your script get executed every time you log in, even over SSH, for example? If so, I guess it would be relatively alright, in that a new instance of Shairport Sync would quit if the ports it needs are in use.

What would you think of the following approach using a [desktop entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html#exec-variables)? 

I created the directory `~/.config/autostart` and I put a file called `shairport-sync.desktop` in it with the following contents:

```
[Desktop Entry]
Name=Shairport Sync
GenericName=Shairport Sync AirPlay Player
NoDisplay=true
TryExec=/usr/local/bin/shairport-sync
Exec=/usr/local/bin/shairport-sync
Terminal=false
Type=Application
```

It seems to work in Fedora 36, but I wonder if there are any hidden problems or gotchas.

**Comment by mikebrady** [comment]
**[Update]**

Okay, I've learned a lot, thanks, and I'm going to delete this and the above comment shortly as it'll be confusing to anyone coming along afterwards. Your user service method is the way to go. This is what I observe and what I think is happening:

1. Shairport Sync gets launched just once when the system boots, but it's launched under the user's own username. 
2. Once it has launched, the AirPlay service becomes visible on the network. Players can connect to it any play music to it, but it won't be heard until the user logs in through the GUI.
3. When the user logs in through the GUI, the audio coming in through Shairport Sync is routed to the speakers and can be heard.
4. If the user logs out, the audio ceases but will come back again when the user logs in again.

**Comment by spiro-c** [comment]
> **[Update]**
> 
> Okay, I've learned a lot, thanks, and I'm going to delete this and the above comment shortly as it'll be confusing to anyone coming along afterwards. Your user service method is the way to go. This is what I observe and what I think is happening:
> 
> 1. Shairport Sync gets launched just once the first time the user logs in, and is launched under the user's own username.
> 2. Once it has launched, the AirPlay service becomes visible on the network. Players can connect to it and play music to it, but it only be heard when the user logs in through the GUI.
> 3. If the user logs out of the GUI, audio stops but will come back again when the user logs in through the GUI again.

To over come this behaviour  what is normal for user services is to enable [lingering ](https://www.freedesktop.org/software/systemd/man/loginctl.html#enable-linger%20USER%E2%80%A6)  it can be enabled with `loginctl enable-linger $USER`
