### ISSUE TITLE
Missing of lib and compile flag for MQTT client

### ISSUE THREAD

**Issue by tuaminx** [mikebrady/shairport-sync#1266]
I think README.md should have below info for MQTT client.
- To use MQTT feature described in MQTT.md, need to `./configure` with `--with-mqtt-client`
- Before that, the dependent lib `libmosquitto-dev` should be installed `apt install libmosquitto-dev`

**Comment by mikebrady** [comment]
Thanks for the suggestion. I added some text in the `development` branch of MQTT.md.

**Comment by mikebrady** [comment]
Okay to close this?

**Comment by tuaminx** [comment]
Yes, totally agree with that. I see Close button, let me press :)
