### ISSUE TITLE
Sound only outputs when starting shairport-sync from command line

### ISSUE THREAD

**Issue by aftrmth728** [mikebrady/shairport-sync#1267]
Hi there. Thanks for your work on this great project, It has resurrected some speakers around the house that haven't been in use for a long time! Over the last few days I've been experimenting with different setups, specifically bluetooth. Managed to get it working after a while and stumbling across someone's solution posted in an issue here somewhere.

The issue I have is that when shairport starts as a service such as at boot or when running systemctl start shairport-sync I will have no audio output to the speaker. However, if I run it from command line or using the verbose option the sound will output fine.

Is there anything you can think of that may cause this? Again, this is over Bluetooth but it was working fine over Bluetooth previously, the issue only begun recently.

Thanks

**Comment by aftrmth728** [comment]
Some extra info from journal:

`Aug 11 02:47:40 raspberrypi shairport-sync[8913]:          0.004629409 "audio_alsa.c:442" *warning: alsa: error -22 ("Invalid argument") opening alsa device "default".`

That same error repeats seemingly every second. I assume that specifying the audio device would be better than leaving it as default but I don't actually know the device name as reported in the system. I can see it in the GUI of PulseAudio's volume control as my speaker's bluetooth broadcast name but commands such as aplay -L or -l and shairport-sync -h only return the following devices:

```
hardware output devices:
      "hw:b1"
      "hw:Headphones"
      "hw:Loopback"
```

I also can't see a volume control for the speaker in alasmixer as it isn't listed, only the above devices are.
Are there any arguments I can run with shairport-sync to see what device is being used when ran from CLI and sound output is there? I'm fairly new to this and Linux in general so I don't know my way around it very well. I would guess that I have created this issue myself through the various different approaches at getting the Pi to output sound to a Bluetooth speaker (which seems unneccasrily complicated in Linux, may I add LOL). At some point I tried just rebuilding shairport-sync but the issue persists.

Thanks

**Comment by mikebrady** [comment]
Thanks for the post.

I think you've come up against a limitation in the way PulseAudio is configured. Specifically, PulseAudio is usually set up as a `user service`. That is, it is a service provided by one or daemons that are launched when a user logs in. This is in contrast to a `system service` which is provided by one or daemons that are launched when the machine boots up. So, the output device that PulseAudio provides is simply not there until the user logs in.

Some people have turned Shairport Sync into a user service that launches after the PulseAudio service -- you may find some further information in the Issues, both open and closed.

Another possibility is to dispense with PulseAudio and simply use the `alsa` back end. This means dispensing with PulseAudio's Bluetooth support. Shairport Sync does not have a native Bluetooth-specific back end, I'm afraid, and there are no plans to add one.

**Comment by aftrmth728** [comment]
> Thanks for the post.
> 
> I think you've come up against a limitation in the way PulseAudio is configured. Specifically, PulseAudio is usually set up as a `user service`. That is, it is a service provided by one or daemons that are launched when a user logs in. This is in contrast to a `system service` which is provided by one or daemons that are launched when the machine boots up. So, the output device that PulseAudio provides is simply not there until the user logs in.
> 
> Some people have turned Shairport Sync into a user service that launches after the PulseAudio service -- you may find some further information in the Issues, both open and closed.
> 
> Another possibility is to dispense with PulseAudio and simply use the `alsa` back end. This means dispensing with PulseAudio's Bluetooth support. Shairport Sync does not have a native Bluetooth-specific back end, I'm afraid, and there are no plans to add one.

Thanks for the response Mike. In the end I started from scratch and used the ALSA backend. Bluetooth was only something I needed temporarily and getting it to work ultimately became something I wanted to conquer rather than needed to conquer. All working well now, this is a great application here. Thanks again, feel free to close this!

It may be worth mentioning for anyone who comes across this that in the days prior I did have a Bluetooth set up that worked fine but in this case I was trying to use shairport via Bluetooth in co-ordination with an LED audio reactive script and the amount of tweaking I made to various configs is likely what broke it beyond repair. There’s a guide somewhere in the issues here on a working Bluetooth setup.

**Comment by mikebrady** [comment]
It's good to hear that you got it working.
