### ISSUE TITLE
Only rudimentary metadata received [iOS 9]

### ISSUE THREAD

**Issue by andig** [mikebrady/shairport-sync#127]
I've compiled ssnc with metadata support and enabled metadata plus coverart. This is what I'm receicing when playing from iOS 9.1 beta/ iPad:

	cat /tmp/shairport-sync-metadata

	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>7072736d</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>
	<item><type>73736e63</type><code>70666c73</code><length>0</length></item>

Imho that amounts to:

	ssnc pfls 0
	ssnc prsm 0

Nothing else- no iTunes metadata, no cover art. This is when playing various songs from any album.

**UPDATE**

I do suddenly get further data when using the volume buttons on the ipad!

Any idea where I'm going wrong?

**Comment by mikebrady** [comment]
Seems like the iPad app (is it the Music app?) is not providing any metadata. I haven't looked at what the Music app produces, TBH. The extra data from the volume control is to be expected alright.

**Comment by andig** [comment]
Much appreciated. Cross test shows that iOS 8.3 music app is sending metadata, iOS 9.1 beta not, neither on iPad nor on iPhone.

Would this also be the reason for not receiving `prgr`? I would always expect those as according to docs generated by ssnc?

**Comment by mikebrady** [comment]
You are right about the `prgr` token -- just like the `PICT` token, it represents repackaged metadata coming from the source. Hopefully Apple will restore the supply of metadata, but I have no foreknowledge.

**Comment by primerpremio** [comment]
Hi there.
I recently replaced shairport by shairport-sync in my Volumio set up to keep up to date with maintenance. I use a 16x2 LCD display to show Airplay metadata which was flawlessly working until ios9. It seems Apple has changed lots of things in Airplay protocol with this new release and metadata may no longer be gathered the same way.

This is what shairport-sync-metadata-reader shows out from an ios9 playing source:

"ssnc" "snua": "AirPlay/241.33".
"ssnc" "acre": "3381963373".
"ssnc" "daid": "BEF7525837E46EFE".
"ssnc" "pbeg": "".
"ssnc" "pvol": "-20.62,-22.55,-48.10,0.00".
"ssnc" "pfls": "".
"ssnc" "prsm": "".
"ssnc" "pfls": "".
"ssnc" "prsm": "".
"ssnc" "pvol": "-9.38,-7.52,-48.10,0.00".
"ssnc" "pvol": "-7.50,-6.01,-48.10,0.00".
"ssnc" "pvol": "-5.62,-4.51,-48.10,0.00".
"ssnc" "pvol": "-3.75,-3.01,-48.10,0.00".
"ssnc" "pvol": "-1.88,-1.50,-48.10,0.00".
"ssnc" "pvol": "0.00,0.00,-48.10,0.00".

No title, album, artist, etc... Vol keeps working though...
It would be interesting to test if an Apple TV keeps showing metadata without a software upgrade.
By now, my display is empty and sad when playing through shairport-sync from ios9...

**Comment by mikebrady** [comment]
Hi, and thanks for the report. All the information listed above originates with Shairport Sync itself, so there's nothing at all coming in from iOS 9. It does appear to be sending picture data at least to an Apple TV, so they really seem to have changed their metadata system, which is worrying.

**Comment by andig** [comment]
I've read reports about display sync not working either from iOS9 to jailbroken apple tvs. Is there any raw stream of iOS9 data that we could supply for debugging purposes?

**Comment by andig** [comment]
Does this help: https://github.com/juhovh/shairplay/commit/498bc5bcdd305e04721f94a04b9f26a7da72673f

**Comment by mikebrady** [comment]
Hi. Thanks for the link -- it's interesting, but I don't think its relevant. Shairport Sync is compatible with iOS 9 already -- which is what that patch seemed to be for -- and it doesn't seem to have anything to do with the missing metadata. I'd love to be wrong, by the way :)

**Comment by dabrain34** [comment]
Did you succeed to understand what happens with the missing metadat? Is there any device combination where its working ( apple tv, airfoil etc.)

**Comment by mikebrady** [comment]
No real progress. iOS9 devices are sending metadata to updated Apple TVs, so the metadata is being sent. SO, it's not so much "missing" as moving along a different pathway with different protocols. Time for a WireShark analysis, at least... Any volunteers?

**Comment by dabrain34** [comment]
I will have a try with airfoil on my side, i dont have apple tv...

**Comment by primerpremio** [comment]
I tried tcpdump some days ago, with no luck so far. I may not be looking for the correct stuff anyway. The good news is that it seems metadata is still being sent to audio-mode devices, that's the most important thing.

**Comment by roblan** [comment]
fixed in 9.2 :smile:

**Comment by mikebrady** [comment]
Yes, I can confirm that pictures are coming through again. It seems that the picture data is being sent even if you don't ask for it – see #170 – but I think it's pretty good news overall.

**Comment by mikebrady** [comment]
It's actually nice to see some third party apps supporting metadata – TuneIn Radio is a bit crude, but the Radio Svizzera Classica app supports it rather well, as does WunderRadio. Maybe more!

**Comment by primerpremio** [comment]
What a relief, my LCD display is alive again...
Spotify also supports metadata perfectly, I wouldn't be interested in the whole project if not!

**Comment by mikebrady** [comment]
Cool. TuneIn Radio and Radio Svizzera Classica also do so! There's at least one big that's been fixed and an update is pending. All good.

**Comment by mikebrady** [comment]
I'm closing this now – Apple have come to the rescue, sorta.
