### ISSUE TITLE
No Airplay Output through Raspberry Pi 4 Headphone Jack

### ISSUE THREAD

**Issue by Strat5** [mikebrady/shairport-sync#1270]
Note: I wasn't exactly sure of where I could ask a community about troubleshooting this; if this is the wrong place for questions such as mine, just let me know and I'll take the post down. 

I've setup Shairport-sync on my Raspberry Pi 4 2GB as specified in this directory's read-me files. It appears to be functioning (the service is running, my Apple devices can connect to it, etc.), however, I cannot hear any audio outputting from speakers connected to the 3.5 mm headphone jack. I've done a few tests outside of Shairport-sync to ensure that the 3.5 headphone jack does work (such as `speaker-test` and `omxplayer -o local file.mp3`), and there were no problems there. I've set the headphone jack as default using `raspi-config` and increased the volume of the headphone jack using `alsamixer`. I've also experimented with specifying different audio devices in the Shairport-sync configuration file, but none seem to work. I would appreciate any troubleshooting advice that can be provided.

**Comment by charlesomer** [comment]
What does your current config file look like? This is an example for the Pi. Also, could you post the output of `shairport-sync -V` please :)

```
// Sample Configuration File for Shairport Sync on a Raspberry Pi using the built-in audio DAC
general =
{
  volume_range_db = 60;
};

alsa =
{
  output_device = "hw:Headphones";
  mixer_control_name = "Headphone";
};
```

**Comment by Strat5** [comment]
My output device was "hw:CARD=headphones". After changing it to "hw:Headphones" it worked perfectly. Thank you!

**Comment by charlesomer** [comment]
No problem 😊 Glad it’s working!
