### ISSUE TITLE
Cannot play audio on Ubuntu

### ISSUE THREAD

**Issue by benjistokman** [mikebrady/shairport-sync#1277]
Shairport-sync is working properly except where it gets to actually playing the audio. Nothing I do to the config fixes it.

I belive this is due to Ubuntu being weird about audio. When I try to do a speaker-test or aplay as root it just says "device or resource busy". Is there any way I could fix this, such as running shairport as my user?

**Comment by nburns** [comment]
I had a slightly similar error and eventually fixed it by:
- reinstalling alsa and pulseaudio:  `sudo apt-get install --reinstall alsa-base pulseaudio`
- checking the output of: `shairport-sync -h` the `hardware output devices:` section
- and adding the `"hw:Generic"` device string (from the step above) to the `alsa` `output_device` section in `/etc/shairport-sync.conf`
