### ISSUE TITLE
Any plans to support Shairport Sync  / Airplay protocol on pipewire?

### ISSUE THREAD

**Issue by alexbramford** [mikebrady/shairport-sync#1279]
### Discussed in https://github.com/mikebrady/shairport-sync/discussions/1271

<div type='discussions-op-text'>

<sup>Originally posted by **alexbramford** August 23, 2021</sup>
**Use case:**

- I'm looking to upgrade from Fedora 32 to Fedora 34
- Pipewire is the replacement for pulseudio on F34

**Setup:**

- F32(Rhythmbox) --> pulseaudio (module-raop-sink) --> LAN--> RaspberryPi (moodeAudio + Shairport Sync)

**Question:**

- Are there plans for Shairport Sync on RaspberryPi to support pipewire in Fedora O/S ?

**Specifically:**

1. pulseaudio  **module-raop-sink** on my Fedora 32 laptop
2. shairport-sync running on the RaspberryPi

Or is there a pipewire module that will do the same as pulseaudio (module-raop-sink?)

**References:**

- https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-raop-sink

- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1542

(If this not the appropriate forum, please recommend the correct place to ask this question!)</div>

**Comment by p3ck** [comment]
I don't understand the request.  shairport-sync uses airplay1 protocol, that's the whole point of it.  I think your issue is that pipewire doesn't currently have a raop output that could play to shairport-sync.  I think you really want to open the issue with pipewire since this is a regression when moving from pulseaudio to pipewire.

**Comment by alexbramford** [comment]
Veering of-topic, but updating this ticket in case it might help someone else :

- Wim Taymans confirmed that pipewire does not yet support the pulseaudio module-raop-sink module 
- I was able to get everything running on Fedora 34 by "rolling back" to pulseaudio with `sudo dnf swap --allowerasing pipewire-pulseaudio pulseaudio`
- This will suffice until pipewire delivers code support for the pulseaudio module-raop-sink module 

**References:**

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1542
https://github.com/wwmm/easyeffects/issues/1123

**Comment by alexbramford** [comment]
Finally, thanks @mikebrady for the excellent product that is shairport-sync.
It's a key link in my home audio setup, which you can see here if you wish

http://moodeaudio.org/forum/showthread.php?tid=32&pid=35604#pid35604
