### ISSUE TITLE
error: 'shairport_cfg' has no member named 'meta_dir'

### ISSUE THREAD

**Issue by vriera** [mikebrady/shairport-sync#128]
Both mdns_tinysvcmdns.c and mdns_dns_sd.c try to access to a non-existent member called "meta_dir" of the shairport_cfg struct (which is defined in common.h):

[snip]
#ifdef CONFIG_METADATA
  if (config.meta_dir)
[snip]

This causes a build failure like this one:

mdns_tinysvcmdns.c: In function 'mdns_tinysvcmdns_register':
mdns_tinysvcmdns.c:121:13: error: 'shairport_cfg' has no member named 'meta_dir'
   if (config.meta_dir)

**Comment by mikebrady** [comment]
Whoops -- let me check that out!

**Comment by mikebrady** [comment]
Fixed the compilation error in the development branch. Haven't checked the functionality, so please let us know if it's working properly.

**Comment by vriera** [comment]
Thanks for fixing the problem so fast. Could you please let me know which will be the next stable release that will include the fix? The 2.4 is broken so I would like to upgrade to the next stable release as soon as possible.

**Comment by mikebrady** [comment]
It'll be in 2.4.1, which should be in the next two weeks or so. Does it work, functionally?

**Comment by vriera** [comment]
I don't know, but the build problem has been fixed. I don't use this package, I just wanted to fix an autobuild failure we were having in Buildroot.

**Comment by mikebrady** [comment]
Okay, thanks. I'll check it out myself in the next few days.

**Comment by mikebrady** [comment]
Fixed, so closing the issue, thanks.
