### ISSUE TITLE
No Audio on RPi

### ISSUE THREAD

**Issue by kingscolour** [mikebrady/shairport-sync#1285]
Apologies if this isn't the right procedure--I've never been one for GitHub.

This is no longer an issue, but I wanted to share some information that I couldn't find anywhere else. This was a new install with the following version:

    $ shairport-sync -V
    >> 3.3.8-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

I was unable to produce any audio from the attached equipment over after a vast number of different config changes, etc.

However, I was able to produce sound via the test:

    $ speaker-test -r44100 --device=hw:Headphones -c2

After realizing that I was unable to access `alsamixer` due to:

    $ alsamixer 
    >> cannot open mixer: No such file or directory

It was evident that there were permission issues. `alsamixer` requires that the user be a part of the `audio` group. So, I changed the permissions and restarted the daemon. 

    # usermod -aG audio shairport-sync
    # service shairport-sync restart

Et voilà. Sound.

**Comment by mikebrady** [comment]
Many thanks for the post.

It should be the case that the installer (`# make install`) should define the `shairport-sync` user and group and should add the `shairport-sync` user to the `audio` group. Is it possible that something went wrong with that step? Or are you using an unusual version of Linux?

**Comment by sbelyea** [comment]
A thought - I just finished getting the developmental branch running on a Raspberry Pi 4B and 2B.  I did not encounter this problem on the Raspberry Pi 4B, but I _did_ encounter this exact problem on the 2B.  Changing the permissions as noted by @kingscolour resolved the issue on my 2B.
