### ISSUE TITLE
Building on Mac OS

### ISSUE THREAD

**Issue by luckydonald** [mikebrady/shairport-sync#129]
#####  Building on Mac OS
This is how far I got:
```shell
brew install openssl
brew install libdaemon
brew install autoconf
brew install libtool
brew install popt  #is that libpopt?
brew install libconfig
brew install libsoxr
```
```shell
autoreconf -i -f
``` 
Until here everything works.

Now I have problems with ALSA, avahi and systemv/systemd, on Mac OS X.
avahi is like bonjour, and I couldn't find ALSA at all.

I just tried ```configure``` anyway, (It did fail):
```shell
mac:shairport-sync luckydonald$ ./configure --with-configfile --with-soxr --with-ssl=openssl  --with-metadata
configure: WARNING: unrecognized options: --with-configfile
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for clock_gettime in -lrt... no
configure: error: librt needed
```

```shell
mac:shairport-sync luckydonald$ brew install alsa autoconf libtool libdaemon-dev libasound2-dev libpopt-dev libconfig-dev
Error: No available formula for alsa
Error: No available formula for libdaemon-dev
Error: No available formula for libasound2-dev
Error: No available formula for libpopt-dev
Error: No available formula for libconfig-dev

**Comment by mikebrady** [comment]
AFAIK, there is no ALSA on the Mac. You're on your own :)

**Comment by luckydonald** [comment]
:(

**Comment by shtirlic** [comment]
@luckydonald u can use libAO  for shairport-sync, I will post here homebrew file for the build

**Comment by shtirlic** [comment]
Here it is, gist with homebrew file 
```
brew install https://gist.githubusercontent.com/shtirlic/d55b3ac3767a2e7f54eb/raw/f7395d9f8015e5441e26811ad430c1410cc7cd44/shairport-sync.rb
```
https://gist.github.com/shtirlic/d55b3ac3767a2e7f54eb

Building with libsoxr libao dns_sd

**Comment by shtirlic** [comment]
Update
 here is the pull request to the homebrew https://github.com/Homebrew/homebrew/pull/44666

**Comment by luckydonald** [comment]
Lol. It works.

**Comment by shtirlic** [comment]
My formula accepted by homebrew and now you can install just by ```brew install shairport-sync```
@luckydonald I think u can specify additional options to configure during build process, because if we use configfiles AFAIK  ```make install``` trying to install them in linux locations (SystemV, systemd)

**Comment by mikebrady** [comment]
Thanks for this. I hope to add it to the README.md in the next few days.

**Comment by luckydonald** [comment]
@shtirlic how exactly can I add  metadata support?

**Comment by ryanaslett** [comment]
Looks like libao doesnt yet support setting backend latencies. (I see the relevant changes in the development branch: https://github.com/mikebrady/shairport-sync/commit/026b970680a19634f0901d4537ab1baaf0a1ca7a#diff-bec1ba4860114690bab01acc4830aa85R57 - also note I think I found a bug in that commit)

Additionally, it doesnt appear to be making any attempts to synchronize. Running in verbose mode shows something like this:  `Synchronisation disabled. Missing packets 0; late packets 0; too late packets 0; resend requests 0; min and max buffer occupancy 219 and 284`

**Comment by mikebrady** [comment]
Thanks for looking at this. I'll fix that bug. Synchronisation is only available on the alsa back end – as far as I can tell, it's impossible with the `ao` subsystem.

**Comment by mikebrady** [comment]
I just pushed a fix for that bug you referred to.

**Comment by ryanaslett** [comment]
I dug around in ao, and yeah, I cant see anything in that API that would give the functionality needed for the synchonization either.  I was thinking that perhaps portaudio api's (http://www.portaudio.com/) might possibly have a way to do this on osx, but it really looks like the only way to fully accomplish this is to use core audio directly.  So I wiped the drive on my old macbook, installed ubuntu on it and synchronization works perfectly.  Being able to adjust the latency manually might work for osx users, but seems like it'd still eventually drift.

**Comment by mikebrady** [comment]
I think your analysis is correct, and I don't know how to go about combining the use of Linux libraries with Core Audio stuff in, say, Xcode.

**Comment by mikebrady** [comment]
I think this issue is done, so I'll close it. Feel free to reopen it if necessary.
