### ISSUE TITLE
libavahi-client-dev not installing on Debian

### ISSUE THREAD

**Issue by NEjjjO** [mikebrady/shairport-sync#1290]
running sudo apt install libavahi-client-dev gives error message of failed to fetch library
404 Not found
http://raspbian.raspberrypi.org/raspbian/pool/main/a/avahi/libavahi-client-dev_0.7-4+b1_armhf.deb

**Comment by mikebrady** [comment]
Thanks for the post. I don’t have an angle on this — it’s not strictly a Shairport Sync issue, I’m afraid. 

Checking on an up-to-date Raspberry Pi OS and Ubuntu just now, it works. Here is an examples from Raspberry Pi OS:
```
pi@RaspberryPi4B:~ $ sudo apt install libavahi-client-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavahi-client-dev is already the newest version (0.7-4+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@RaspberryPi4B:~ $ 
```

**Comment by MichaIng** [comment]
The exact URL/package version indeed does not exist, so your APT lists seem out of date. Please try:
```sh
apt update
apt install libavahi-client-dev
```
and if it still fails:
```sh
apt clean
rm -R /var/lib/apt/lists
apt update
apt install libavahi-client-dev
```
