### ISSUE TITLE
Couldn't start JACK server

### ISSUE THREAD

**Issue by tonychh** [mikebrady/shairport-sync#1291]
Hi @mikebrady, on my raspberry pi, shairport-sync works like a charm with the default ALSA backend. However, when I changed the backend to JACK, it just couldn't start with a error of JackStatus = 11.

I did some troubleshooting by playing videos on VLC player (the audio output was set to JACK) and it worked perfectly. And I could see the application showing up in Catia's patchbox. So it seems to me that the JACK server itself is fine, but there might be some issue with my shairport-sync set-up causing its failure with JACK.

I am a bit stuck because I have kept everything default in my shairport-sync config file, other than changing the backend to JACK. Is there anything that I should also check? Thanks!

(I learnt from other posts that @nettings is using JACK without experiencing any issues. It would be great if I can also seek your advice too.)

```
pi@raspberrypi:~ $ sudo systemctl status shairport-sync
shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2021-09-18 10:29:02 HKT; 1min 23s ago
  Process: 14130 ExecStart=/usr/local/bin/shairport-sync (code=exited, status=1/FAILURE)
 Main PID: 14130 (code=exited, status=1/FAILURE)

Sep 18 10:29:02 raspberrypi shairport-sync[14130]:          0.001525458 "shairport.c:1756" software version: "3.3.8-OpenSSL-Avahi-ALSA-jack-pa-pipe-soxr-metadata-dbus-sys
Sep 18 10:29:02 raspberrypi shairport-sync[14130]:          0.000338902 "shairport.c:1762" log verbosity is 2.
Sep 18 10:29:02 raspberrypi shairport-sync[14130]: Cannot connect to server socket err = No such file or directory
Sep 18 10:29:02 raspberrypi shairport-sync[14130]: Cannot connect to server request channel
Sep 18 10:29:02 raspberrypi shairport-sync[14130]: jack server is not running or cannot be started
Sep 18 10:29:02 raspberrypi shairport-sync[14130]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Sep 18 10:29:02 raspberrypi shairport-sync[14130]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Sep 18 10:29:02 raspberrypi shairport-sync[14130]:          0.006204552 "audio_jack.c:259" *fatal error: Could not start JACK server. JackStatus is 11
Sep 18 10:29:02 raspberrypi shairport-sync[14130]:          0.000382735 "shairport.c:1424" emergency exit
Sep 18 10:29:02 raspberrypi systemd[1]: shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
Sep 18 10:29:02 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
```

**Comment by mikebrady** [comment]
Thanks for the post. I’m afraid there isn’t really enough information here to offer an opinion. Let me suggest that you take a look at the TROUBLESHOOTING and REPORTING ISSUES pages and then let us know how things stand.

**Comment by mikebrady** [comment]
Just looking at the code in `audio_jack.c`, Shairport Sync is simply trying to open a Jack client and is failing. It is not passing any parameter other than the name, `shairport-sync` by default. So it seems unlikely that it is specifically a Shairport Sync issue. There is quite a bit about this error cropping up with other audio software, e.g. [here](https://bugs.launchpad.net/ubuntu/+source/jackd-defaults/+bug/1872244), which might be helpful.

**Comment by tonychh** [comment]
Apology for my very limited knowledge in JACK. I have been able to open a JACK client with ```jack_simple_client``` without any issues so I was surprised when ```shair-port-sync``` failed to open a JACK client with ```jack_client_open```. Would this be possibly related to user permission?

**Comment by mikebrady** [comment]
No problem, and apologies on my part for the delay. Also I'm not too well up on Jack myself TBH. So, I can think of two possibilities -- one is a permissions problem and the other may be that when Shairport Sync starts as a daemon, that the Jack service e hasn't started.

So, to make a little progress, it would be good to prevent Shairport Sync from starting as a daemon and to run it from the command line. This would establish if it can work under [I think] the same circumstances as your experiment.

To stop the daemon, enter:
```
$ sudo systemctl stop shairport-sync
```
and then, on the command line, you could do:
```
$ shairport-sync -vu
```
to see what it does -- the `-vu` would turn on some logging. If that works, then we would need to see about permissions or startup conditions.

**Comment by tonychh** [comment]
Stopping the daemon seems to do the trick. Thanks!

**Comment by tonychh** [comment]
May I clarify if this seems to be a permission issue?

If I run shairport-sync from the command line, it can connect to JACK server successfully:
```
pi@raspberrypi:~ $ sudo systemctl stop shairport-sync
pi@raspberrypi:~ $ shairport-sync -vu
         0.001892069 "shairport.c:1729" Started!
         0.000179202 "shairport.c:1756" software version: "3.3.8-OpenSSL-Avahi-ALSA-jack-pa-pipe-soxr-metadata-dbus-sysconfdir:/etc"
         0.000043777 "shairport.c:1762" log verbosity is 1.
```

However, if I restart shairport-sync as daemon, it will fail to connect to JACK:
```
pi@raspberrypi:~ $ sudo systemctl stop shairport-sync
pi@raspberrypi:~ $ sudo systemctl restart shairport-sync
pi@raspberrypi:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-09-26 10:38:39 HKT; 7min ago
  Process: 8708 ExecStart=/usr/local/bin/shairport-sync (code=exited, status=1/FAILURE)
 Main PID: 8708 (code=exited, status=1/FAILURE)

Sep 26 10:38:39 raspberrypi shairport-sync[8708]:          0.000024592 "shairport.c:1762" log verbosity is 2.
Sep 26 10:38:39 raspberrypi shairport-sync[8708]:          0.000057111 "audio_jack.c:232" SOXR quality quick
Sep 26 10:38:39 raspberrypi shairport-sync[8708]: Cannot connect to server socket err = No such file or directory
Sep 26 10:38:39 raspberrypi shairport-sync[8708]: Cannot connect to server request channel
Sep 26 10:38:39 raspberrypi shairport-sync[8708]: jack server is not running or cannot be started
Sep 26 10:38:39 raspberrypi shairport-sync[8708]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Sep 26 10:38:39 raspberrypi shairport-sync[8708]:          0.004868217 "audio_jack.c:259" *fatal error: Could not start JACK server. JackStatus is 11
Sep 26 10:38:39 raspberrypi shairport-sync[8708]:          0.000128703 "shairport.c:1424" emergency exit
Sep 26 10:38:39 raspberrypi systemd[1]: shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 10:38:39 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'exit-code'.

```

**Comment by mikebrady** [comment]
Thanks for the post.

We now know in general terms that Jack can run in your system, which is good. As to the problem: as I mentioned, there are two possibilities I see. The first is a permissions issue, but the second one is that Jack is a _user service_ and not a _system service_. 

Having a quick look on the internet, I found [this post](https://discourse.ardour.org/t/a-reliable-systemd-startup-for-jack/103738/11) in a thread, which suggests that Jack is (or was) a user service.

If Jack is a user service, it does not start up automatically when the machine boots. Instead it must be started for each user, typically when the user logs in. That may be the case in your system, so that the Jack user service is automatically started when you log in, before you call Shairport Sync from the command line.

The standard installation of Shairport Sync is as a system service. When it starts up, no Jack user service will have been started and hence the error message. That's my theory anyway...

**Comment by nettings** [comment]
Sorry, late to the party. Mike is right.
@tonychh , to run any jack client as a system service, you have to solve two issues:
* jackd needs to be running as a system service already
* your client (in this case shairport-sync) and the jackd server need to be running as the same user

You can specify the user under which a systemd service runs in the .service file.
I'm working on a multimedia overlay to raspios that does what you want to do, just take a look:
https://github.com/nettings/medianet

Specifically, take a look at 
https://github.com/nettings/medianet/blob/master/overlay/usr/local/lib/systemd/system/mn_jackd.service
and
https://github.com/nettings/medianet/blob/master/overlay/usr/local/lib/systemd/system/mn_shairport-sync.service
(as you can see, I'm using my own shairport-sync service file, but you can just modify Mike's file to suit your needs).

If you're interested, I can make a current installable OS image available. That said, the INSTALL instructions also need updating... oh well.

**Comment by tonychh** [comment]
Thank you Mike and Jörn! Maybe I should run shairport-sync as user service in that case.

Jörn, your project looks very interesting. Let me connect with you offline :)
