### ISSUE TITLE
Airplay2 - AppleTV no audio on the second session

### ISSUE THREAD

**Issue by corrpel** [mikebrady/shairport-sync#1292]
Hello,
I am using the development branch (latest), and trying to output from youtube apple tv app to shairport-sync.
The initial play is outputting audio and is in sync with my other homepods.
If i stop and then play a new video, sometimes i have audio sometimes i don't.
When i don't have sound, i see that is no **"player.c:xxxx" Play begin** in log. When it works, i see it.
I am using TVOS 15 RC version, with 3 homepods mini running 14.7 software.
If this is not a know issue, can i attach the some log so you can take a looks whenever you have time?
Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. If you had a brief log, it wpild be helpful, thanks. There’s still a lot to figure out about these protocols!

**Comment by corrpel** [comment]
Hello,
Thanks for the reply. I've attached the log file.
First two times the audio is playing and the third time there is no audio.

Steps used to reproduce:
1. Connect shairport sync
2. Start youtube video
3. Check audio
4. Press back to stop video
5. Start same video
6. Check audio
7. Press back to stop video
8. Start same video
9. Check audio

Result:
3. OK
6. OK
9. NOK - no audio is playing.


You can check the attached file.
[shairp_debug-1292.zip](https://github.com/mikebrady/shairport-sync/files/7194317/shairp_debug-1292.zip)


Thanks again!

**Comment by mikebrady** [comment]
Thanks for that!

**Comment by mikebrady** [comment]
Just push an update to the `development` branch which _might_ have an effect on this. If you got a chance to try it and report back, that would be cool.

**Comment by mikebrady** [comment]
BTW, we are referring here to the `development` branch running in _AirPlay 2_ mode, not the usual AirPlay 1 protocol.

**Comment by corrpel** [comment]
Hello. I am away from home for about 2 weeks. I will be glad to try when i get home and report back.

**Comment by corrpel** [comment]
Hello
It looks like this issue is still here with the same behavior.

**Comment by corrpel** [comment]
Hello Mike,
Since the last update, i think this issue is resolved.
Just got home and played on YouTube app for about an hour.
This usually was happening on the second/third play in the past.
This issue does not exist anymore from what I can tell from this short testing session.

**Comment by mikebrady** [comment]
Thanks. Some time was spent recently with an Apple TV 4K and the latest versions of SPS and `nqptp` seem to work just about as well (as an AirPlay 2 speaker) as a HomePod mini. I’m glad that that seems to be your experience too.

SPS seems to work well with Amazon Prime, Netflix, YouTube and other common apps.

BTW, some apps don’t support AirPlay 2 speakers at all. And some apps will not permit the use of AirPlay 2 speakers for some material, presumably for licensing reasons. 

Thanks again.

**Comment by CarlBernard** [comment]
> I am on IOS 15.1 beta 1. I wil stay on this version for a while since shaiport-sync still works much of the time and running a subwoofer besides 3 homepods mini 😊 connected to the TV. IOS 15 Beta 3 indroduces the “SETRATE”, but i am not there. Initially wen i found this i was on TVOS 15 RC, which was the first official release of 15 version. I am using a video app for movies that does not have the issue described on youtube app, and i think is not using the same sync controls as youtube, it takes about 2 seconds since i press play until the sound comes up, even on homepods.
> 
> Update: Just verified what type of stream i am receiving, looks like it is realtime on video player.
> 
> > 
> 
> ```
>      0.000112999 "rtsp.c:569" Connection 1: got player lock.
>      0.000213999 "rtsp.c:2820" Connection 1: UDP realtime audio port opened: 44998.
>      0.000457998 "rtsp.c:2830" An ALAC stream has been detected.
>      0.000170999 "rtsp.c:2853" Realtime Stream Play
> ```

Hello corrpel,

How do you mean “ios 15 beta 3 introducing setrate”?
