### ISSUE TITLE
Phone call audio

### ISSUE THREAD

**Issue by BigHeadCreations** [mikebrady/shairport-sync#1295]
`$ shairport-sync -V`
`3.3.8-OpenSSL-Avahi-pipe-metadata-dbus-sysconfdir:/etc`

Is it possible to play phone call audio over shairport-sync? I'm using a Raspberry Pi 4 connected to a dumb speaker via a 3.5mm audio cable. When streaming music to the dumb speaker and I pick up a phone call on my iPhone 8 and press the "audio" button I get a list of devices I can stream the audio to (my macbook, airpods, or iPad) but my shairport-sync device is not listed. 

Is this a known limitation? Is there a work around?

Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. I'm afraid you can't stream a phone call to Shairport Sync. It seems to be the case that a different audio protocol is used for handling phone calls, different to AirPlay. Even in AirPlay 2, it does seem to be an extra protocol, which Apple haven't released, AFAIK.

**Comment by BigHeadCreations** [comment]
Ok, I understand. Thanks so much for the reply.
