### ISSUE TITLE
Why might Roon list my streamer as a "ShairportSync" device?

### ISSUE THREAD

**Issue by tk21769** [mikebrady/shairport-sync#1296]
One of my HiFi components (a Matrix Audio Element X DAC/streamer/pre-amp) is supposed to be "Roon Ready".
So, once it is connected via Ethernet to my home network, it should show up in Roon's Settings/Audio page under the "Roon Ready" list of devices.  However, lately it stopped showing up. It only shows up under "other network devices" for connection via Airplay.  After days of troubleshooting, I still cannot identify the problem. I believe I'm using the latest versions of iOS (15), Mac OS (BigSur), Matrix software and firmware, etc.

One oddity is that, when I open Roon on my iPhone, the device is labeled "Matrix1 (ShairportSync)".  "Matrix1" is the name I assigned the device, and when I open Roon on my Mac, that is the name I see.  So I'm wondering what might cause it to have the "ShairportSync" label on the iPhone?  I do not remember setting up Shairport-Sync on my system ... but maybe some application is using it under the hood?   If so, would it be possible that this application is hogging the device so that Roon cannot access it over the LAN?

I don't know if I'm even asking the right questions here, just thought I'd take a shot in case anyone on this forum might have a clue.

**Comment by mikebrady** [comment]
Thanks for the post. I am not familiar with Roon, but it may be using Shairport Sync to provide its AirPlay service. Best ask the Roon guys, I’d suggest.

**Comment by tk21769** [comment]
Mike,

Thanks for the prompt reply.
I’ve reached out to the Roon people and to the Matrix Audio folks.

Tom

**Comment by kiwi-ed** [comment]
Roon will pick up any Airplay endpoints (i.e. Shariport-sync) together with any Roon (RAAT) endpoints.
