### ISSUE TITLE
Sync Problem with audio|acacia

### ISSUE THREAD

**Issue by ulub81** [mikebrady/shairport-sync#130]
Hello mister Brady,

Thank you for your great work, I'm really enjoying listening to audio over shairport-sync!

Are you aware of this problem?
http://talk.plethra.com/214/shairport-sync-devices-when-using-itunes-using-audio-acacia

Is it possible to fix the problem without changing the shairport config?

Best regards 

Peter

**Comment by mikebrady** [comment]
Thanks Peter – I wasn't aware of it, and so Ive just left a message. It does seem as if there's some confusion about the exact latency...

**Comment by ulub81** [comment]
If you want to try it yourself, there is a trial available at:

https://www.plethra.com/resources/guides/setup

**Comment by mikebrady** [comment]
Let's see if they come back with anything first...

**Comment by ulub81** [comment]
"The developers of shairport-sync have hardcoded playback to start after 88,200 samples (2000ms) after receiving the initial Play command, rather than deriving the playback start time from the first sync packet like native AirPlay devices do."

/* sizeof(SyncPacket) == 20 */
struct SyncPacket {
  RtpHeader header;
  RtpTimestamp now_minus_latency;
  NtpTime time_last_sync;
  RtpTimestamp now;
}

Isn't this already the solution?

**Comment by mikebrady** [comment]
Unfortunately, the latency that can be calculated from this is incorrect. For example, iTunes uses a latency of around 99,400 frames, not the 88,200 frames that can be calculated.

Also, the statement in quotes is not correct. Shairport Sync identifies the type of the incoming source , e.g.  iTunes or AirPlay or forkedDaapd etc. and chooses a latency for it. Recent versions of iTunes and forkedDaapd seem to work with a latency of 99,400 frames and other sources expect a latency of 88,200 frames, and Shairport Sync chooses a latency accordingly, as mentioned in the README.

TBH, I know of no reliable way of calculating or negotiating an agreed latency dynamically, and I'd love to find a way.

**Comment by ulub81** [comment]
But my native airplay speakers are playing in sync (pioneer receiver, libtratone zipp, pc with audio|acaica) when playing audio in audio|acacia. but shairport-sync is out of sync!
So there is a kind of negotiation in airplay/airtunes 2 that shairport-sync doesn't support right now!

Wouldn't it be super cool to have a custom latency interpretation instead of a fixed mapped audio latency for the incoming device that only works for certain senders?

I think this is the last important step for a universal, reliable and robust airplay using shairport-sync!

**Comment by snikch** [comment]
Just dropping into the conversation - I'm the OP of the audio|acacia thread. I haven't done much digging since I managed to get the synced playback via a custom latency, but I'm happy to help out with anything that needs to be done to get it working smoothly. I'm a software dev so no problem with assisting.

**Comment by mikebrady** [comment]
Thanks for your inputs. Once thing that would be useful is if audio|acacia identifies itself properly to Shairport Sync. If you could turn on debug verbosity on Shairport Sync (either with the command line `-v` option or else in the configuration file) and see what gets reported in the "User-Agent" string, the would be mighty useful.

**Comment by mikebrady** [comment]
So, I looked into this a little more. It seems I was, eh, wrong when I said that a reliable value could not be negotiated. I think I have just done so for iTunes and AirPlay source, and pushed the build onto a new, temporary branch called `dynamic-latency`– see https://github.com/mikebrady/shairport-sync/tree/dynamic-latency

There's a new latency setting (also likely to be temporary) in the configuration file: `use_negotiated_latencies` which should be set to "yes" to enable Shairport Sync to pick up the latency requested by the source. As I said, it works for iTunes and AirPlay, so it you'd like to try it with audio|acacia, I'd be obliged.

**Comment by ulub81** [comment]
Wow, thanks for your effort!

So sync_rtp_timestamp-rtp_timestamp_less_latency+11025 does the trick!

I'm very unexpirienced with Linux (I'm just using Moode Player Image on my raspberry Pi) so I'm afraid I can't do the test with audio|acacia, but maybe snikch can help with that!

Thank you so much!

**Comment by mikebrady** [comment]
Yeah you're right. So it does look like 0.25 seconds is the minimum. It's actually hard to make that work reliably on a normal network.

**Comment by ulub81** [comment]
Hi Mike,

after spending some hours (as a total linux/raspberry pi noob) getting to know how to setup my raspberry pi from scratch and how to build and configure the new shairport-sync dynamic-latency branch, I can now confirm that playing audio through audio|acacia in combination with the new "dynamic-latency" shairport-sync gives me now a absolutely fantastic listening experience! The audio plays in perfect sync in combination with other "native" airplay speakers!!!!

Hope to see this as the default setting in the next stable master release soon! :-)

Thank you very much, you made my day!

**Comment by mikebrady** [comment]
That is excellent news, thanks. I just released 2.4.1, which doesn't have this dynamic latency feature. I will definitely incorporate the feature in the next stable release, but I need to figure out how best to do that. Fair warning: I will probably remove the `use_negotiated_latencies` setting and just make it automatic, then start deprecating the fixed latencies in general. I will do this in the `development` branch soon and delete the `dynamic-latency` branch. I'll keep you posted. Thanks for your work!

**Comment by mikebrady** [comment]
Hi there. I've just merged then changes in the `dynamic-latency` branch into the `development` branch and deleted the `dynamic-latency` branch. The `use_negotiated_latencies` setting is gone – the behaviour is now the default. These changes will get into the `master` branch in the next few weeks, hopefully.

I'm going to close this issue now, if that's okay. Feel free to reopen it if necessary.

**Comment by mikebrady** [comment]
All the changes here are now in the master branch – 2.6.
