### ISSUE TITLE
Raspberry PI 4 - will only output on HDMI / Intermittently available

### ISSUE THREAD

**Issue by mikebrady** [mikebrady/shairport-sync#1300]
### Discussed in https://github.com/mikebrady/shairport-sync/discussions/1262

<div type='discussions-op-text'>

<sup>Originally posted by **lestat1977uk** August  3, 2021</sup>
Hi All, 

Really cool software but i could really use some help, been through all the guides and not getting anywhere.\

I've gotten the airplay to appear a few times but it always disappears and even when it does work it only works on HDMI, i'd really like to have it use 3.5 jack.

any help would be very much appricated</div>

**Comment by iRayanKhan** [comment]
I tried this on the DAC, and still get static. It's a USB DAC.

**Comment by mikebrady** [comment]
Thanks. Going back to the original post:


> I've gotten the airplay to appear a few times but it always disappears and even when it does work it only works on HDMI, i'd really like to have it use 3.5 jack.
> 
> any help would be very much appricated

... it might be worth going through the TROUBLESHOOTING and REPORTING ISSUES pages.

@iRayanKhan, could you perhaps let us know the machine, version and DAC details please? I've been using lots of different USB DACs without problems.
