### ISSUE TITLE
AP2 IOS video freeze

### ISSUE THREAD

**Issue by corrpel** [mikebrady/shairport-sync#1308]
Hello,
I found an issue on version:
```
4.1-dev-7-g430e3eda-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc
```

IOS 15.1 beta 2 Iphone 12 mini, raspberry pi zero w streaming to bluealsa.

When opening youtube and playing video, everything looks good.
If video is changed, without a pause between videos, the IOS Youtube app is buffering but video freezes.
The issue happens also with an USB audio card.

I also found a workaround for this:
```
run_this_after_exiting_active_state = 
```
My script only changes alsa volume on a mixer to 0 value (i believe that can be any command that takes a bit of time to execute).

Thanks

**Comment by mikebrady** [comment]
Thanks for the report.
