### ISSUE TITLE
Can't connect after enabling password

### ISSUE THREAD

**Issue by AronAtGit** [mikebrady/shairport-sync#1309]
Hey, after trying to enable a password on my airplay devices running the development branch (supports AP2) by uncommenting the password line I am no longer able to connect.  I get a dialogue box on both my MacOS and my phone that says "cannot connect to [name of device].  The password protection seems to work just fine on my raspberry pi running the master branch (just AP1 support)

Any insight?

**Comment by benjitusk** [comment]
I'm also having this issue @mikebrady, is there any way this can get resolved?

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, until we know how the password mechanism works on AirPlay 2, we’re stuck.
