### ISSUE TITLE
Hardware volume control

### ISSUE THREAD

**Issue by gev** [mikebrady/shairport-sync#1321]
Hi guys! 

I use shairport-sync with the pulseaudio sink and send audio via rtp to the my own network audio player Korolab LanAmp-4.
I want change hardware volume on the LanAmp. Can I get volume level from shaitport-sync?

**Comment by mikebrady** [comment]
Thanks for the post. Yep, there’s a hook for a program or script to be called whenever the volume is changed. Have a look in the sample configuration file — there’s some documentation there.

**Comment by gev** [comment]
> Thanks for the post. Yep, there’s a hook for a program or script to be called whenever the volume is changed. Have a look in the sample configuration file — there’s some documentation there.

Yep a saw that in docs. but every volume swipe on ios will start new process isn't it?

**Comment by mikebrady** [comment]
Yes, that’s correct — a new process each time. Then there’s a D-Bus interface as well.

**Comment by gev** [comment]
Can I use D-Bus with more then one shairport-sync instance?
I use 4-8 instances in time for different zones at the one media server
