### ISSUE TITLE
Development build malfunctions when 2 AP devices on same network

### ISSUE THREAD

**Issue by DeanSCND** [mikebrady/shairport-sync#1322]
Mike,

Great work on this.I'm a coder in canada but unfortunately my C skills suck big time, otherwise I'd lend a hand. I still might see if I can make heads or tails of the code at some point.

Decided to test out the development build as I'd like Airplay 2 involved in what I'm trying to do. I have a bunch RPI's sitting here on my desk and a boatload of audio devices to fool around with.

I'm using the dev branch with Moode audio. When i build it out and run for the first time it works flawlessly. Just using HDMI or the Aux jack to test right now. When I deploy the second instance without dev branch (aiplay 1) with new hostname and Airplay name and run it. It seems to work fine as well. When I spin up both, all hell breaks loose. 

The behaviour I see is successful airplay connections to the AP2 device but no audio. Moode behaves odd in that the "Connected to airply" appears and does not disappear even after I disconnect on the device. AP1 device is fine. I thought it could be an IOS 15 issue at first but I have some 14 devices sitting around and it's the same behaviour. Also, when I take the second AP1 instance offline the behaviour persists. How can I help? What do you need from me in terms of logging and whatnot to see if we cant figure this out? Does this sound familiar? Lemme know what you'd like me to do and I'll get you some data on this.

I'm about to set up a third device with AP2 as well and see if that one goes down as well. It's odd that it only starts happening after a second AP device comes online on the network. Almost feels like they are interfering with each other but I don't know enough about he Airplay protocol and how the devices isolate themselves on the network.

cheers.

-dean

**Comment by DeanSCND** [comment]
going to strip this down and remove moode from the equation. I'll still use the base moode os config but I'll be drop down to the command line on 2 RPI's and see if I can reproduce it there. Stay tuned.

**Comment by mikebrady** [comment]
> going to strip this down and remove moode from the equation. I'll still use the base moode os config but I'll be drop down to the command line on 2 RPI's and see if I can reproduce it there. Stay tuned.

Thanks — that’s just what I was going to suggest. There were a lot of moving parts in the first scenario.

**Comment by DeanSCND** [comment]
Wiped 2 rpi's clean, kept moode out of it and upgraded both to dev branch. Did manual starts on both and started testing with a bunch of devices connecting, disconnection, grouping and have not had an issue. So only difference was, no AP1 instance. I'm now letting Moode do the managing and will continue trying it out. I have 2 Boss2's showing up early in the week so i'll bring those on with AP1 and see what happens. 

Perhaps i'll close this out for now. Mike, as i go along do you want me running in debug mode/full logging? Also,by the time i'm done i'll ideally have 5 or 6 of these running. If you want some more detailed help and even have me testing stuff out for you, let me know. Are you guys using slack at all? Would love to lend a hand if you need it.

**Comment by mikebrady** [comment]
Glad to hear the problem is less serious. Recall that when an AP1 device and and AP2 device are joined to play from, say, the Music app on macOS, the AP2 device basically changes over to AP1 protocols. This can’t be done on iOS devices of course. I wonder if this was part of your issues.

**Comment by mikebrady** [comment]
I'm wondering if the problems you are encountering are related to a Shairport Sync (SPS) instance switching from AP1 to AP2? I'll see if I can get something to happen there.
