### ISSUE TITLE
Metadata-pipe

### ISSUE THREAD

**Issue by bartosz-777** [mikebrady/shairport-sync#1325]
Hi,does metadata pipe work on development(airplay 2) version?

**Comment by mikebrady** [comment]
Thanks for the post. Yes, metadata is working, but less metadata is available. The problem is that the remote control (and information) interface to an AirPlay 2 client has not been figured out, so that source of information is not available.

**Comment by kylejohnsonkj** [comment]
Just tagging on, is cover art available in the airplay 2 version? Specifically wondering about that one... Thanks for the great project.

**Comment by mikebrady** [comment]
Yes, as long as you include metadata support when building Shairport Sync. You can include it explicitly; alternatively it is included automatically when you include DBus, MPRIS or MQTT support.
