### ISSUE TITLE
AppleTV playing to shairport-sync running on raspberry pi 4

### ISSUE THREAD

**Issue by moonwatcher** [mikebrady/shairport-sync#1329]
running 4.1-dev-7-g430e3eda-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc

Not at all sure this isn’t a TVOS bug but since the latest update STARTING playback on Netflix will stall if the appleTV is outputting to the airplay device. As soon as I switch the audio output back to the TV it will start playing. If I switch it to play to the airplay device WHILE it’s already playing, it works…

to make a bit more weird I think it only happens with Netflix…

**Comment by mikebrady** [comment]
Thanks for the report. AFAIK it happens with Amazon Prime as well. Another variation of it seems to be that if there is a HomePod mini among the output devices along with the Shairport Sync device, everything works. It seems to be something to do with the PTP system, and may be related to a problem with Apple Silicon Macs when they wake up after sleeping -- in that situation they will not play to Shairport Sync devices either.

In a few days, I should have a few ideas that will need testing if you're interested -- I don't have access to an ATV right now.

**Comment by mikebrady** [comment]
Hi there. I've pushed a new `nqptp` branch called [`wakener`](https://github.com/mikebrady/nqptp/tree/wakener) that works around this problem on an Apple Silicon Mac, and may (?) help in your situation. If you got a chance to try it out, that would be great. Please pay particular attention to the README -- the installation instructions might have changed.

**Comment by mikebrady** [comment]
Update --  apologies, one line was left out of the instructions (it was `$git checkout wakener`). Fixed now.

**Comment by mikebrady** [comment]
It looks like it might have fixed this issue — see #1317.

**Comment by moonwatcher** [comment]
I removed everything and built the ```wakener``` branch of ```nqptp``` and development branch of ```shairport-sync``` and it does seem to resolve the issue. For now... until apple makes another update ;)

**Comment by mikebrady** [comment]
Excellent -- thanks for the information. It really does seem to be a workaround for an Apple bug -- I can't understand it any other way. Let's hope they fix it soon; there are quite a few other bugs on the audio side of the Apple world right now...

**Comment by mikebrady** [comment]
Just FYI, the `wakener` branch will be deleted shortly -- it's been merged into the `development` branch.

**Comment by moonwatcher** [comment]
No problem. I can build everything again, it doesn't take that long. Thanks for the heads up :)

**Comment by mikebrady** [comment]
Again just FYI, a bug has been fixed in Shairport Sync itself that should make it more reliable with Apple TV.

**Comment by moonwatcher** [comment]
Thank you. I rebuilt `nqptp` and `shairport-sync` from `development`. Will report if I see any further issues.
