### ISSUE TITLE
Reading audio data for a spectrum analyzer

### ISSUE THREAD

**Issue by dubaleeiro** [mikebrady/shairport-sync#1333]
Hi,
this is rather a question than an issue... I am trying to "read" the audio streaming data from Shairport and with that drive some Neopixels Leds to act as an spectrum analyzer. After some internet research and manly  inputs from [this](https://forums.raspberrypi.com/viewtopic.php?t=35838&sid=41a4cfeff4aaf1df90969e0b8775e350&start=25) post I came up with a script which is throwing me the following error:

`  File "spectrum_analizer.py", line 42, in <module>
    data_in = aa.PCM(type=aa.PCM_PLAYBACK, mode=aa.PCM_NORMAL, device='hw:0', channels=no_channels, rate=sample_rate, format=aa.PCM_FORMAT_S16_LE, periodsize=chunk)
alsaaudio.ALSAAudioError: Device or resource busy [hw:0]
`

Does anyone can give me some hints on the possible reasons for that?
Thanks !

**Comment by mikebrady** [comment]
Thanks for the post. It seems that you are trying to read the stream of audio from the output device -- `hw:0` -- but you can't do that. You need to get the stream from its source, not from its sink.

You can ask Shairport Sync to send its stream to a unix pipe or to the standard output, and you could read it from there. However, you cannot ask Shairport Sync to send audio to, say, a pipe and to another output device at the same time. So, if you want to feed the output of Shairport Sync to your software and to an output device at the same time, you will have to duplicate the stream and feed one stream to each sink. Unix and linux have a command line tool called `"tee"` for doing just that.

Finally, some contributors have done something like what you are attempting. It might be worth searching for some of their documentation.

**Comment by dubaleeiro** [comment]
Thanks a lot for your feedback ! I have installed `peppyalsa` and `PeppyMeter` and I am currently trying to adapt ther libraries to achieve what I want: a Spectrum Analyzer based on a NeoPixels LED strip.
