### ISSUE TITLE
New Raspbian Bullseye Libgcrypt warning

### ISSUE THREAD

**Issue by iChUdY** [mikebrady/shairport-sync#1334]
Hello,

i complete upgraded to Bullseye on my rpi and install:

**4.1-dev-18-gb2f38e0f-AirPlay2-alac-OpenSSL-Avahi-ALSA-soxr-metadata-mqtt-dbus-sysconfdir:/etc**

get log:

```
Nov 13 13:06:37 pi3 systemd[1]: shairport-sync.service: Succeeded.
Nov 13 13:06:37 pi3 systemd[1]: Stopped Shairport Sync - AirPlay Audio Receiver.
Nov 13 13:06:37 pi3 systemd[1]: shairport-sync.service: Consumed 10.542s CPU time.
Nov 13 13:06:37 pi3 systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Nov 13 13:06:48 pi3 shairport-sync[1947]: Libgcrypt warning: missing initialization - please fix the application

```
The audio is working properly, but an error message is present.

**Comment by mikebrady** [comment]
Thanks for the report! It’s harmless, but needs fixing.

**Comment by iChUdY** [comment]
Low priority 😉 

> 13. 11. 2021 v 18:53, Mike Brady ***@***.***>:
> 
> Thanks for the report! It’s harmless, but needs fixing

**Comment by mikebrady** [comment]
Fixed now, I believe.

**Comment by iChUdY** [comment]
Fix works great.
