### ISSUE TITLE
How do I connect to shairport and appleTV at the same time on iOS 15?

### ISSUE THREAD

**Issue by klauskobald** [mikebrady/shairport-sync#1335]
I get a list like: AppleTV1, AppleTV2, Macbook, Shairport.
When I select an AppleTV I get those checkboxes to add other devices, but shairport is not available.
When I select Shairport I cannot add the other devices.
Is there a config somewhere to fix that?

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync is normally built to support AirPlay 1, which doesn’t allow multiple devices. However, on the `development` branch, you can build Shairport Sync with AirPlay 2 support, and that does allow it to combine with other devices.

**Comment by klauskobald** [comment]
thank you. I found that later :-)
