### ISSUE TITLE
Not able to connect from iOS 15 device

### ISSUE THREAD

**Issue by badbat75** [mikebrady/shairport-sync#1338]
I'm using the latest commit in dev tree, but I started from the official 4.1-dev release.
Client device continue asking me the code displayed in the device even if not set in the config file and drop the connection.
Attaching verbose logging from the server:
[shairport-sync_error.log](https://github.com/mikebrady/shairport-sync/files/7555652/shairport-sync_error.log)

**Comment by mikebrady** [comment]
Thanks for the post. It seems as if, somehow, Shairport Sync is advertising that it needs the mode of connection that requires the code. I have been relying on [this information](https://openairplay.github.io/airplay-spec/features.html), but I may have misunderstood it, or it may be incorrect. I'll have to look at it.

Meantime, as a workaround, we know it works with the standard build and almost a default configuration file. So can I suggest that you rebuild Shairport Sync exactly as shown in the BUILDFORAP2 guide, and leave all the settings in the configuration file in their default state, apart from the `alsa` stuff and the `diagnostic` stuff. I'll build your configuration here and try to replicate it. It would be very useful if you could post your configuration file.

**Comment by badbat75** [comment]
thank you for your reply.
This is the configuration file
`general =
{
interpolation = "soxr";
audio_backend_latency_offset_in_seconds = 0.0;
audio_backend_buffer_desired_length_in_seconds = 1.5;
};

sessioncontrol =
{
allow_session_interruption = "no";
session_timeout = 120;
};

alsa =
{
output_rate = 44100;
output_format = "S24";
};

sndio =
{
};

pa =
{
};

jack =
{
};

pipe =
{
};

dsp =
{
};

metadata =
{
};

mqtt =
{
}

diagnostics =
{
};
`

**Comment by mikebrady** [comment]
Thanks. I just updated my response. The plot thickens. Later tonight or early tomorrow I'll build your configuration exactly. What program are you sending audio from on the client, please?

**Comment by mikebrady** [comment]
Okay, so, I have built Shairport Sync (SPS) on the `development` branch using the configuration flags you gave above, and I used the configuration file you supplied.

I was able to connect and use SPS without problems from the Music app on iOS (15.1) and from the Music app on macOS (12.0.1).

Now, there was an unimportant error in the configuration string:
```
pi@RaspberryPi3B:~/shairport-sync $ ./configure --with-airplay-2 --with-soxr --with-avahi --with-alsa --with-piddir=/run/shairport-sync --with-systemdsystemunitdir=/lib/systemd/system --without-configfiles --without-libdaemon --with-systemd --with-openssl
configure: WARNING: unrecognized options: --with-openssl
...
configure: error: specify one of --with-ssl=openssl or --with-ssl=mbedtls or --with-ssl=polarssl
pi@RaspberryPi3B:~/shairport-sync $ 
```
It turns out to be unimportant because when you use `--with-airplay-2`,  the `--with-ssl=openssl` flag is included automatically. I'll update the instructions later.

So the issue remains a mystery.

Would you mind posting the original set of configuration flags please? And could you get a screenshot of what happens on the iOS selection screen?

**Comment by mikebrady** [comment]
[Update] Actually that configuration flag error _is_ important because it aborts the configuration sequence, leaving it incomplete.

Your configuration flags should read:
```
--with-airplay-2 --with-soxr --with-avahi --with-alsa --with-piddir=/run/shairport-sync --with-systemdsystemunitdir=/lib/systemd/system --without-configfiles --without-libdaemon --with-systemd --with-ssl=openssl
```

**Comment by badbat75** [comment]
Hi Mike, I guess I badly copied the command line.
this is the configure command:
`configure --prefix=/usr --exec-prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf --libexecdir=/usr/lib --includedir=/usr/include --sysconfdir=/etc --localstatedir=/var --with-airplay-2 --with-soxr --with-avahi --with-alsa --with-piddir=/run/shairport-sync --with-systemdsystemunitdir=/lib/systemd/system --without-configfiles --without-libdaemon --with-systemd --with-ssl=openssl`
I'm trying to record a video to show you what is the test process.

**Comment by mikebrady** [comment]
Thanks -- that would be super.

**Comment by mikebrady** [comment]
I just rebuilt it with that configuration and it's still working, I'm afraid 😕.

System is a Raspberry Pi 3B running Bullseye, fully up to date:
```
pi@RaspberryPi3B:~/shairport-sync $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@RaspberryPi3B:~/shairport-sync $ uname -a
Linux RaspberryPi3B 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
pi@RaspberryPi3B:~/shairport-sync $ 
```
Could you let us know what kind of system and OS version you are using, please?

**Comment by badbat75** [comment]
Oh things are a little bit weird... 🤣 I"m cross compiling it from an x86_64 linux to an armv6 Linux system.  The destination OS (where are the libraries) is a raspios bullseye with latest updates. Just to make things a little bit more complex I setup some flags on gcc compiler: -O3 -flto.
You gave me an idea, I try to disable LTO and O3 to see the outcome...

**Comment by badbat75** [comment]
Just to complete the scenario I'm using the same setup without issues from the first v3 of shairport-sync.

**Comment by mikebrady** [comment]
Interesting -- I've not tried LTO. -O3 yes, -flto no.

**Comment by mikebrady** [comment]
Just tried these options (on `gcc`) on a Raspberry Pi running Bullseye, and they didn't make any difference that I can see, apart from being a bit faster. I'll try `clang` a bit later.

**Comment by mikebrady** [comment]
Actually, it'll take me some more time to try `clang`, I'm afraid -- there's something else I need to do first.

**Comment by badbat75** [comment]
Ok tried my trials (20 at least... :-) )
Tried without lto and with 02, using default system libraries or compiled by me...
Last thing to try, is a native build excluding the cross-compile tool chain, so only the phone can make the difference

**Comment by badbat75** [comment]
Ok tried to compile directly into the device (RaspberryPI), same result...
I guess it is something related to my Iphone XR

**Comment by mikebrady** [comment]
Thanks for all your work. I am baffled by this, to be quite honest.

**Comment by mikebrady** [comment]
Would it be possible for you to use an iOS app called “Discovery” from TildeSoft to look at the Bonjour string SPS is using to advertise the service please?

**Comment by mikebrady** [comment]
So, here is another idea, if you'd be kind enough to try it out. It would need you to be using `git` though, so I guess building on the Pi itself...

Less than a week ago, the `pair_ap` library, which deals with authentication, was updated to the latest version. In case there might be some issue with it, perhaps you could backtrack to the last commit before it was updated. That would be commit `fb1b2e9dff455a1e85b485808ec5c915bb103a83`.

So, this would be the sequence of operations, assuming you are in the shairport-sync directory created on the Pi when you git-cloned the repository:

```
$ git checkout development
$ git checkout fb1b2e9dff455a1e85b485808ec5c915bb103a83
$ autoreconf -fi
$ ./configure ...
$ make clean
$ make -j
```

**Comment by badbat75** [comment]
Just tried it. It's continuing asking me the code.

**Comment by mikebrady** [comment]
Thanks. This is really intriguing.
