### ISSUE TITLE
compile error (--with-airplay-2)

### ISSUE THREAD

**Issue by b247** [mikebrady/shairport-sync#1341]
Hi, I try to compile shairport-sync (https://github.com/mikebrady/shairport-sync/blob/development/BUILDFORAP2.md) on a debian10 arm powered device (osmc on a rpi3) but got this during the make process (make -j)
`rtsp.c: In function ‘handle_get_info’:
rtsp.c:1510:34: error: ‘plists_get_info_response_xml’ undeclared (first use in this function); did you mean ‘pair_verify_response2’?
     plist_from_xml((const char *)plists_get_info_response_xml, plists_get_info_response_xml_len,
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  pair_verify_response2
rtsp.c:1510:34: note: each undeclared identifier is reported only once for each function it appears in
rtsp.c:1510:64: error: ‘plists_get_info_response_xml_len’ undeclared (first use in this function)
     plist_from_xml((const char *)plists_get_info_response_xml, plists_get_info_response_xml_len,
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by mikebrady** [comment]
Thanks for the report. Is `libplist` installed? What version it it? It must be 2.0.0 or later.

**Comment by b247** [comment]
Hi,

libplist-dev is already the newest version (2.0.1~git20190104.3f96731-1)

libplist3 is already the newest version (2.0.1~git20190104.3f96731-1)

libplist++-dev is already the newest version (2.0.1~git20190104.3f96731-1)

>

**Comment by mikebrady** [comment]
Thanks. Could you post the ./configure options you used, please?

**Comment by b247** [comment]
./configure --sysconfdir=/etc --with-alsa     --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2

**Comment by mikebrady** [comment]
Thanks. I tried to get started with OSMC on a Pi 3 from the command line and couldn't even `ssh` into it -- the Mac `ssh` client hung up after entering the password.

**Comment by mikebrady** [comment]
So, I spun up a minimal arm64 based Debian 11 and built `nqptp` and Shairport Sync without any difficulties. Therefore, I think it must be something specific to the OSMC image -- I suggest you talk to the OSMC guys.

**Comment by b247** [comment]
Thank You Mike. I am using OSMC 2020.11-1 (debian 10 buster - armhf [32bit] ) version on a RPI 3 armv7l CPU. Could be a problem that I am using a 32bit OS (debian 10/11 armhf)?

**Comment by mikebrady** [comment]
I'm afraid I am unable to test for that. A 32-bit OS shouldn't be a problem _per se_. After all, the Raspberry Pi OS is still 32-bit. (FWIW, Shairport Sync also builds on an `arm64` based Debian 10.)

**Comment by b247** [comment]
Never mind

**Comment by Lorilandly** [comment]
Hi, I found out that this problem is because the generated `plist_xml_strings.h` is empty. This is caused by a command in the makefile not executed. One can encounter this issue if xxd is not installed on the system the first time *shairport-sync* is compiled, stops on line 1605 in the makefile, resulted in an empty `plist_xml_strings.h`. Compile again after `xxd` is installed by the user, the makefile sees that `plist_xml_strings.h` already exists and will not attempt to add the rest of the code to it. Thus, compilation breaks. You can solve the problem if you run manually the line `xxd -i plists/get_info_response.xml >> plist_xml_strings.h` before building.

**Comment by b247** [comment]
It worked, thank you

>

**Comment by mikebrady** [comment]
> Hi, I found out that this problem is because the generated `plist_xml_strings.h` is empty. This is caused by a command in the makefile not executed. One can encounter this issue if xxd is not installed on the system the first time _shairport-sync_ is compiled, stops on line 1605 in the makefile, resulted in an empty `plist_xml_strings.h`. Compile again after `xxd` is installed by the user, the makefile sees that `plist_xml_strings.h` already exists and will not attempt to add the rest of the code to it. Thus, compilation breaks. You can solve the problem if you run manually the line `xxd -i plists/get_info_response.xml >> plist_xml_strings.h` before building.

Many thanks for finding this and for providing a PR to fix it!

**Comment by anatol** [comment]
I hit the same issue at Arch Linux.

It would be nice if the build system failed early in case `xxd` is absent.

**Comment by mikebrady** [comment]
Thanks for the update. Is there something missing from the build guide?

**Comment by duhow** [comment]
Ideally, if `xxd` program is missing, the Makefile build command should warn the user of this.
I'm currently building shairport in Docker image builder, and needed to install this application due to Airplay2.

**Comment by mikebrady** [comment]
That should be fixed now -- thanks for the reminder! If you got a chance to check it, that would be very useful.
