### ISSUE TITLE
Feature Request: add support for treble and bass control

### ISSUE THREAD

**Issue by bloomkd46** [mikebrady/shairport-sync#1347]
Could you add it so that in the config you could increase/decrease the treble and bass multiplier that defaults to 1

**Comment by mikebrady** [comment]
Thanks for your interest in Shairport Sync and for the suggestion, but TBH it would be pretty low down the list of priorities. The focus at present is really on getting the audio to the DAC as unscathed as possible — to present the audio to the DAC with as much fidelity as can be mustered. 

That said, there is a loudness filter and convolution code available — see the Wiki. And some others have followed the approach of routing the audio from Shairport Sync through various standard `alsa` filters.
