### ISSUE TITLE
Shairport does not recover from an unrecoverable error, "unable_to_cancel_play_session"

### ISSUE THREAD

**Issue by derekatkins** [mikebrady/shairport-sync#1348]
Hi,
I've been working on integrating Shairport-Sync with OwnTone, with SP-S running both in front of OT, and with OT sending to a bunch of SP-S instances that are driving my speakers.  When it works, it works.  But every once in a while I hit some strange corner cases, like when adding or removing backend SP-S "speakers" from OT.  I hit an issue this weekend where a Shairport-Sync in front of a speaker zone hit an unrecoverable error:
```
Nov 28 12:53:59 shairport shairport-sync-den[3512]: an unrecoverable error, "unable_to_cancel_play_session", has been detected.
```
Even after an hour, I couldn't play to this speaker until I manually restarted SP-S.   I realize the error says "unrecoverable error", but really, is a manual restart necessary before it will accept another RAOP connection?  Alas, there was no additional logging after this error.  Even moreso, I can't reliably reproduce the issue.

In case it matters:
```
shairport-sync -V
3.3.5-libdaemon-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc
```

**Comment by mikebrady** [comment]
Thanks for the post. Let me first suggest that you update to the latest version of Shairport Sync -- 3.3.8, or even better, with the `development` version, version 4.1. 

Yes, a manual restart is necessary when an unrecoverable error has been detected. However, there is a hook provided so that you could write a script that could restart the service.

**Comment by derekatkins** [comment]
Hi Mike.
I need to figure out how to update the dpkg appropriately -- I run about 40 RPM-based systems, but this *ONE* system is Debian-based, and I'm like....  And while I know I could just compile it directly, I always prefer to use packaged binaries for future maintenance.  Unlike RPMs, I have no idea how to download and backport a "Src-Deb" (or whatever it's called), or update an existing debian source to change just the version.
I guess there isn't a good way to just internally reset-and-restart, vs just calling out to "systemctl restart"?

**Comment by mikebrady** [comment]
Hi Derek. I understand the attraction of the packages, but there have been quite a few fixes in the intervening period, and it'll also be much easier to do any further updates should that prove necessary.

You can indeed write a script to do `systemctl restart`, but it is slightly complicated by the fact that you'd have to be in root mode, and Shairport Sync runs in an unprivileged mode. It can be done reasonably securely with `sudo` but it's a little bit tricky .

**Comment by derekatkins** [comment]
Yeah, I know.   I google'd and found instructions, so I'm building 3.3.8.

So back to the hook script -- another option -- systemd will (should) auto-restart on failure.  So, is there a way to tell shairport to exit (unclearly) instead of hanging?  I mean, if shairport needs to be restarted to recover, why not actually die so the system can do that?

**Comment by mikebrady** [comment]
Thanks. No, you can't make it exit at present, but it's a good idea, so I'll make that change in the development version; it'll be out, hopefully, by the end of the week.

I should emphasise that it's extremely unusual for that unrecoverable error to occur. It's got only one potential cause, that is that output to the final `alsa` output device has stalled. It was intended for a situation where a balky hardware DAC would occasionally lock up, and this required the entire device to reboot, since simply restarting Shairport Sync would not unlock the DAC. But this has not been a reported issue for two years, I'd say.

**Comment by mikebrady** [comment]
> 

There's a guide at [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md).

**Comment by derekatkins** [comment]
> I should emphasise that it's extremely unusual for that unrecoverable error to occur. It's got only one potential cause, that is that output to the final alsa output device has stalled. It was intended for a situation where a balky hardware DAC would occasionally lock up, and this required the entire device to reboot, since simply restarting Shairport Sync would not unlock the DAC. But this has not been a reported issue for two years, I'd say.

Interesting.  I'm not sure what's going on here, but I've had it happen multiple times already.  It could be the system I'm running on (NanoPi R1 / Armbian Buster / with 16 USB Audio devices and 16 instances of shairport-sync).  But yes, exiting so systemd will restart it would be a nice improvement.  I suppose I could make that change myself in my version once you push a patch.

> There's a guide at INSTALL.md.

That doesn't tell me how to build a DPKG.  I know very well how to run autoreconf/configure/make/make install..  But I like packages.   Call me old-fashioned, but in 2 years when I go to upgrade the system I want it to upgrade all my services.

**Comment by mikebrady** [comment]
>  I suppose I could make that change myself in my version once you push a patch.

Well, you could do it right away. In `player.c` there is code:
```
                          } else {
                            warn("an unrecoverable error, \"output_device_stalled\", has been "
                                 "detected.",
                                 conn->connection_number);
```

Just change `warn` to `die`. That'll do it.

**Comment by derekatkins** [comment]
Should I make a similar change in rtsp.c?

**Comment by mikebrady** [comment]
Oops, yes! Apologies -- I'm wrong about the "only cause" of an unrecoverable error -- the other possibility is that the play session threads can't be killed for some reason.

**Comment by derekatkins** [comment]
Okay.  Changing both of those 'warn' to 'die'.  Thanks!

**Comment by mikebrady** [comment]
Hi Derek. This fix should be in the latest build. Thanks again.

**Comment by derekatkins** [comment]
I've been running with these changes and haven't seen an issue.  I think you can probably close this issue.
