### ISSUE TITLE
no client metadata when using AirPlay 2

### ISSUE THREAD

**Issue by ccutrer** [mikebrady/shairport-sync#1354]
I'm connecting an iPhone 13 on iOS 15 and an AppleTV on tvOS 15, but I'm not seeing any of the metadata items to identify the client coming through. I'm looking for any of `clip`, `snua`, or `snam`. I'm assuming it's cause these items come from rtp.c and rtsp.c, and AirPlay 2 goes through a different route?

**Comment by mikebrady** [comment]
Thanks for the post. Can you give us some [more information](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md), please?

**Comment by mikebrady** [comment]
Excellent stuff, thanks!

**Comment by mikebrady** [comment]
Hi there. I've added a few missing metadata items in the latest build -- `svip` and `'clip` -- server and client IPs respectively. I'll have a look at adding `clip`, `snua`, and `snam`. Are there more missing?

**Comment by ccutrer** [comment]
I just built 598ddc319c1141674f223da8e377134ad51d40bf, and I'm getting `clip` and `svip` now (as well as `daid`, which I have a feeling is going to be more stable for my automations to know if a particular device is playing). But `active_start` and `active_end` no longer seem to be coming through, nor are `play_start`, `play_end`, `play_flush`, or `play_resume`.

**Comment by ccutrer** [comment]
hmm, enabling -vv logging, it looks like it _is_ trying to publish them. perhaps my MQTT Explorer is not showing them because of the empty payload. I'll dig some more.

**Comment by ccutrer** [comment]
yup, that's definitely the case. those messages are coming through just fine when I use `mosquito_sub -v`. so really the only ones that I'd like to see are `snua` and `snam`.

**Comment by ccutrer** [comment]
bah, neither Active Remote ID nor DACP ID are stable over multiple sessions from a single device. and the IP I'm getting is also changing cause it's using IPv6 private addressing...

**Comment by ccutrer** [comment]
#1389 should fully resolve this issue (I didn't see an equivalent of User Agent for AP2, but I did find several other fields that are both more specific and relevant and useful)

**Comment by mikebrady** [comment]
Thanks. I had to add a couple of conditional compilation statements to your PR but otherwise it's a nice addition!
