### ISSUE TITLE
Raspbian Systemd shairport user not created

### ISSUE THREAD

**Issue by elmoke** [mikebrady/shairport-sync#136]
The user/group shairport-sync in shairport-sync.services file are not created when configuring with --with-systemd. This user also needs to be a member of the audio group to access to mixer. This causes the script to fail.
This is all on Raspbian 4.1.8+

**Comment by mikebrady** [comment]
Hi there. AFAIK `systemd` is not available on Raspbian. I'm running 4.1.8+ and it's using `systemv` style inits. But you are right – the script does not create user or group. If you'd care to write the extra code necessary, I'd be glad to have a look at it...

**Comment by mikebrady** [comment]
Update: I see I'm a little behind the time – since September, there is a Raspbian based on Debian Jessie, which has `systemd`. I'll have a look...

**Comment by mikebrady** [comment]
I've updated the documentation about this, and show users how to create the user and group. We don't want the installers to affect the target system in any way other than install the relevant files and directories, so it follows that the user has to create the user and group manually, where necessary. Thanks for bringing it to my attention.
