### ISSUE TITLE
AirPlay 2 - No Audio across VLANS

### ISSUE THREAD

**Issue by damienpenman** [mikebrady/shairport-sync#1360]
I have my iOS devices on 1 VLAN and my shairport-sync devices on another.
My router has been configured to allow the relevant UDP/TCP ports across the VLANS for AirPlay 1 - and this has been working flawlessly for years. I have now updated to the latest dev version of shairport-sync with AirPlay2 support, and this no longer works.  Despite everything connecting ok, and the iPhone saying that audio is playing on the shairport device, no audio is heard on the shairport speaker. 

I suspect that this is because the RTSP UDP packets are having an issue getting across the VLANS, although I cant see anything being dropped by the router. Does anyone know what ports are used by the AirPlay 2 protocol?

**Comment by damienpenman** [comment]
Ok, I've manged to work out what's going on... 

Slight red herring above.. the master version does work with my setup described above, its just the dev version running AirPlay 2 that doesn't, and that seems to be because of a routing problem in my network. My devices are on different subnets to each other, and whilst I have the relevant firewall rules in place to allow AirPlay 1 to work across subnets, shairport AirPlay 2 doesn't seem to work across subnets. I have just moved the shairport-sync device into the same subnet as the iOS device - and that is now working ok... 

So, theres no problems with the shairport config.. I just now need to work out why AirPlay 1 shairport works across subnets, but AirPlay 2 shairport does not.

**Comment by mikebrady** [comment]
Thanks for the post. AirPlay 2 has two ways of sending audio, once using TCD and the other using UDP. From observation, the ports chosen are just high-numbered ports --- they don't seem to be limited to any particular range, and Shairport Sync itself doesn't try to limit them.

**Comment by damienpenman** [comment]
Thanks, I think this is probably just a UDP routing issue with the timing packets on ports 319 and 320 within our internal network... So you can delete this issue. If we find anything shairport-sync specific then we'll post the details.
