### ISSUE TITLE
AirPlay 2 over different IP Subnets (or VLAN/VPN)

### ISSUE THREAD

**Issue by damienpenman** [mikebrady/shairport-sync#1361]
Dev branch:

https://github.com/mikebrady/shairport-sync/blob/a05db62100b9d4dcd2b81d66f16f367135e4c390/rtsp.c#L2607

```
 if (!different) {
    // debug(1, "%s is in the same subnet as %s.", buf, ip_address);
    plist_array_append_item(addresses, plist_new_string(buf));
  }

```
and

https://github.com/mikebrady/shairport-sync/blob/a05db62100b9d4dcd2b81d66f16f367135e4c390/rtsp.c#L2621

```
if ((addr->sin_addr.s_addr & mask->sin_addr.s_addr) ==
    (pa4->sin_addr.s_addr & mask->sin_addr.s_addr)) {
  char buf[32];
  memset(buf, 0, sizeof(buf));
  inet_ntop(AF_INET, (void *)&addr->sin_addr, buf, sizeof(buf));
  // debug(1, "%s is in the same subnet as %s.", buf, ip_address);
  plist_array_append_item(addresses, plist_new_string(buf));
}
```

These 2 sections are checking to see whether the timing peer's IPV6 or IPV4 address is in the same IP subnet as ShairPort...
If the timing peer is in a different IP subnet, then the incoming plist isn't retained and the connection does not get properly established.

In our setup, we have Apple TV's and ShairPort devices on one network (an IoT network if you like), and user's iPhones/iPads/MacBooks on another network (a secure network). We have added appropriate services/rules into the firewall to allow AirPlay to work between the 2 networks. This has been working flawlessly with ShairPort using AirPlay 1 for a long time. However, the above lines of code are preventing this setup from working with ShairPort using AirPlay 2.

I have commented out these checks (shown below) and rebuilt on my test ShairPort devices, and this does correctly allow AirPlay 2 to work over different networks.

```
  //if (!different) {
    // debug(1, "%s is in the same subnet as %s.", buf, ip_address);
    plist_array_append_item(addresses, plist_new_string(buf));
  //}
```

```
//if ((addr->sin_addr.s_addr & mask->sin_addr.s_addr) ==
//    (pa4->sin_addr.s_addr & mask->sin_addr.s_addr)) {
  char buf[32];
  memset(buf, 0, sizeof(buf));
  inet_ntop(AF_INET, (void *)&addr->sin_addr, buf, sizeof(buf));
  // debug(1, "%s is in the same subnet as %s.", buf, ip_address);
  plist_array_append_item(addresses, plist_new_string(buf));
//}
```

Is there a reason that a check is being made against the subnet that perhaps impacts something elsewhere which I'm not aware of?
or is this something we can safely remove going forward to allow ShairPort to work across subnets for AirPlay 2 as it already does with AirPlay 1.

**Comment by mikebrady** [comment]
Many thanks for this observation. The code checking for the same subnet was added the start of the attempt to get AP2 working, when the operation of the timing peer list wasn't understood. I'll remove it from the development version in the next few days.

**Comment by bradsjm** [comment]
@damienpenman Thank you! I was frustrated as to why the AirPlay 1 version worked and version 2 didn't on my machine, since I use VLANs I had the problem described and I quickly made those same edits and now it works great!

**Comment by mikebrady** [comment]
Thanks again. I [think I] fixed this in the latest build.

**Comment by damienpenman** [comment]
That's great - Thanks Mike!

I've just pulled down the latest dev branch, although struggling to get it to build at the moment..  **configure** is complaining that **AirPlay 2 support requires libavformat -- libavformat-dev suggested**, although when I try to update libavformat, I can see that **libavformat-dev is already the newest version (7:4.1.8-0+deb10u1+rpt1).** .. once I get my head around whats going on there, I'll give it a go and see if the subnet issue is resolved.

**Comment by mikebrady** [comment]
Yeah, let me know -- it might be necessary to tweak the `configure.ac` file. Can you remind me what system you're building on again, please?

**Comment by damienpenman** [comment]
I'm running a Raspberry Pi 4B as my test unit.. Currently on latest version of Buster.. But I'm going to reflash it with Bullseye later and reinstall ShairPort to see how that goes.

**Comment by damienpenman** [comment]
Hi Mike,
Fresh install of Bullseye on RPI4B and ShairPort builds fine.. Using AirPlay 2 across subnets with the latest version of the dev branch is working also. All looks good to me. Thanks for sorting that!.

**Comment by mikebrady** [comment]
@damienpenman, did you happen to figure out what was causing that problem?

> I've just pulled down the latest dev branch, although struggling to get it to build at the moment.. configure is complaining that AirPlay 2 support requires libavformat -- libavformat-dev suggested, although when I try to update libavformat, I can see that libavformat-dev is already the newest version (7:4.1.8-0+deb10u1+rpt1). .. once I get my head around whats going on there, I'll give it a go and see if the subnet issue is resolved.

**Comment by damienpenman** [comment]
@mikebrady  - No, unfortunately I wasnt able to work this one out.. I just reflashed the SD card with a fresh image of Bullseye and it built fine.

**Comment by mikebrady** [comment]
Thanks -- probably what I'd do! 🙂
