### ISSUE TITLE
request for a new release

### ISSUE THREAD

**Issue by gearhead** [mikebrady/shairport-sync#1364]
The automake 1.16.5 error finally hit arch linux. Can you make a new release which has this fix in it?

**Comment by mikebrady** [comment]
Thanks for the information. As you probably know, this has already been fixed in the `development` branch, but it isn't ready yet for committing to the `master` branch.

Perhaps an out-of-cycle quick fix to the `master` branch can be arranged...

**Comment by gearhead** [comment]
Yep, I was able to make the patch and build the 3.3.8 version, but was looking for a new version if one may be close or is ready.

**Comment by mikebrady** [comment]
Thanks. Just pushed an update to 3.3.9 incorporating this fix.
