### ISSUE TITLE
Failed to create secure directory

### ISSUE THREAD

**Issue by christian-heusel** [mikebrady/shairport-sync#1365]
I just installed shairport on a plain raspberry and I am getting the following problem:
```
Dec 06 23:32:48 sven-sein-vadda systemd[1]: Stopping Shairport Sync - AirPlay Audio Receiver...
Dec 06 23:27:11 sven-sein-vadda shairport-sync[409]: warning: failed to find mixer control "PCM".
Dec 06 23:27:11 sven-sein-vadda shairport-sync[409]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
Dec 06 23:26:10 sven-sein-vadda systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

I think either the Docs or the code have to catch up here 🤔

**Comment by mikebrady** [comment]
Thanks for your post. The log seems to indicate that you are outputting directly to PulseAudio or to an `alsa` device that is actually a virtual device leading into the PulseAudio system. Can you say which it is, please?

**Comment by mikebrady** [comment]
Closing this.

In case anyone comes across this in future, the real issue here is that the output from Shairport Sync is going, directly or indirectly, to the PulseAudio system, which is not normally available at bootup.

That means that the PulseAudio system must be running correctly before Shairport Sync. This is often a problem because Shairport Sync is normally installed as a system daemon (one that starts running shortly after the machine starts up) whereas PulseAudio normally starts up as a user daemon (one that starts up when a user logs in). Thus, as system bootup time, PulseAudio isn't running. As you'll see from the [PulseAudio documentation](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/), this seems to be the preferred behaviour.

The OP didn't seem to be aware of this situation.

**Comment by abid76** [comment]
I'm using shairport-sync (`4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`) on a Raspberry PI 2 Model B with a fresh bullseye installation. The speakers are connected via HDMI.

Unfortunately I do not hear anything when playing music.

The logs show the same issue as noted above:
> Mär 12 20:57:19 manwe systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
> Mär 12 20:59:17 manwe shairport-sync[30046]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory

I checked the [link](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/) you provided but I'm not sure what to do actually ... AFAIK pulseaudio has to be run as a system wide service but 
1) I do not know how to start it as a system wide service this and 
2) when starting pulseaudio as root with the --system option it outputs a warning that [this is not recommended](http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/).

Do you have any idea how to fix/workaround this issue?

**Comment by mikebrady** [comment]
Thanks for the post. There are a number of issues here, so it might be worth dealing with each one separately.

The issues are:
1. No sound
2. HDMI
3. PulseAudio 

**No Sound**

I think the very first thing to do is see if audio is coming through from Shairport Sync to the system in the first place. The easiest way to do this is to use raspi-config to direct audio to the output jack, not to the HDMI output. If you have made any settings in the configuration file, you should comment them out, temporarily.

Next, if you have fully installed Shairport Sync, then it would have been installed as a startup service. You should stop this and instead run it from the command line in a terminal window, as follows:

```
$ sudo systemctl stop shairport-sync
$ shairport-sync -v --statistics
```
(Before this perhaps you should ensure that the output device's volume control is set high enough -- use the `alsamixer` tool to do this.)

Attach headphones to the output jack and try to play something to it. You should hear something and you should get some diagnostic and some statistical information on the terminal window.

If you can hear something in these circumstances, you've made some headway. Could you post your results here, please? Then hopefully we can move to the HDMI issue, and then the PulseAudio issue.

**Comment by abid76** [comment]
Ok I connected the headphone jack, set audio , set volume in alsamixer to 100 and ensured with speaker-test that sound is coming out of the speaker.

I startet shairport via `shairport-sync -v --statistics` and played some music. Everything is fine (apart from poor audio quality which I guess is because using headphone jack). See the outputs below.

> abid@manwe:~ $ shairport-sync -v --statistics
>          0.002018333 "shairport.c:2200" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "b8:27:eb:90:6b:cb".
>          0.000147031 "shairport.c:2239" Version String: "4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
>          0.000029896 "shairport.c:2258" Command Line: "shairport-sync -v --statistics".
>          0.000085781 "shairport.c:2265" libsodium initialised.
>          0.000387032 "shairport.c:2290" libgcrypt initialised.
>          0.000029010 "shairport.c:2294" Log Verbosity is 1.
>          0.000065781 "audio_alsa.c:1031" alsa: alsa_maximum_stall_time of 0.200000 sec.
>          0.000055625 "audio_alsa.c:1320" alsa: disable_standby_mode is "never".
>          0.000021094 "audio_alsa.c:1324" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
>          0.000020625 "audio_alsa.c:1326" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
>          0.000052865 "audio_alsa.c:1366" alsa: output device name is "default".
>          0.000223281 "shairport.c:2342" disable_resend_requests is off.
>          0.000031666 "shairport.c:2343" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
>          0.000024219 "shairport.c:2347" statistics_requester status is 1.
>          0.000018073 "shairport.c:2352" rtsp listening port is 7000.
>          0.000017083 "shairport.c:2353" udp base port is 6001.
>          0.000020625 "shairport.c:2354" udp port range is 10.
>          0.000018750 "shairport.c:2355" player name is "Manwe".
>          0.000017448 "shairport.c:2356" backend is "alsa".
>          0.000016719 "shairport.c:2357" run_this_before_play_begins action is "(null)".
>          0.000017344 "shairport.c:2358" run_this_after_play_ends action is "(null)".
>          0.000017239 "shairport.c:2359" wait-cmd status is 0.
>          0.000020938 "shairport.c:2360" run_this_before_play_begins may return output is 0.
>          0.000019115 "shairport.c:2361" run_this_if_an_unfixable_error_is_detected action is "(null)".
>          0.000017708 "shairport.c:2363" run_this_before_entering_active_state action is  "(null)".
>          0.000017604 "shairport.c:2365" run_this_after_exiting_active_state action is  "(null)".
>          0.000021458 "shairport.c:2367" active_state_timeout is  10.000000 seconds.
>          0.000023125 "shairport.c:2368" mdns backend "(null)".
>          0.000017292 "shairport.c:2370" interpolation setting is "auto".
>          0.000016979 "shairport.c:2374" interpolation soxr_delay_threshold is 30000000.
>          0.000018542 "shairport.c:2375" resync time is 0.050000 seconds.
>          0.000018958 "shairport.c:2376" allow a session to be interrupted: 0.
>          0.000019063 "shairport.c:2377" busy timeout time is 0.
>          0.000017187 "shairport.c:2378" drift tolerance is 0.001995 seconds.
>          0.000019011 "shairport.c:2379" password is "(null)".
>          0.000016510 "shairport.c:2380" ignore_volume_control is 0.
>          0.000020573 "shairport.c:2384" volume_max_db is not set
>          0.000016823 "shairport.c:2385" volume range in dB (zero means use the range specified by the mixer): 0.
>          0.000018229 "shairport.c:2387" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
>          0.000018125 "shairport.c:2391" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
>          0.000022240 "shairport.c:2393" disable_synchronization is 0.
>          0.000018698 "shairport.c:2394" use_mmap_if_available is 1.
>          0.000017447 "shairport.c:2395" output_format automatic selection is enabled.
>          0.000020053 "shairport.c:2399" output_rate automatic selection is enabled.
>          0.000018072 "shairport.c:2403" audio backend desired buffer length is 0.200000 seconds.
>          0.000020157 "shairport.c:2405" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
>          0.000019375 "shairport.c:2407" audio backend latency offset is 0.000000 seconds.
>          0.000018437 "shairport.c:2409" audio backend silence lead-in time is "auto".
>          0.000018594 "shairport.c:2413" zeroconf regtype is "_raop._tcp".
>          0.000019115 "shairport.c:2414" decoders_supported field is 1.
>          0.000018072 "shairport.c:2415" use_apple_decoder is 0.
>          0.000016771 "shairport.c:2416" alsa_use_hardware_mute is 0.
>          0.000018750 "shairport.c:2420" no special mdns service interface was requested.
>          0.000046146 "shairport.c:2423" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
>          0.000023021 "shairport.c:2453" loudness is 0.
>          0.000019844 "shairport.c:2454" loudness reference level is -20.000000
>          0.000127135 "shairport.c:2464" size of hw_addr is 8.
>          0.005521719 "shairport.c:2547" NQPTP is online.
>          1.500602968 "shairport.c:254" "soxr" interpolation has been chosen.
>          2.408282030 "rtsp.c:1353" Connection 1: Connection closed by client.
>          2.591474791 "rtsp.c:1353" Connection 3: Connection closed by client.
>          0.376164219 "rtsp.c:2883" Connection 2: AP2 PTP connection from 192.168.2.100:60413 ("Abids iPhone 11") to self at 192.168.2.21:7000.
>          0.031399843 "rtsp.c:4330" Connection 2: Current volume (-24.000000) requested
>          1.971385885 "rtsp.c:3294" Connection 2. AP2 Buffered Audio Stream.
>          0.794255625 "player.c:2774" Connection 2: Playback started at frame 3644496283 -- AirPlay 2 Buffered.
>          0.135802031 "player.c:2819" Large positive (i.e. late) sync error of 2632 frames (0.059683 seconds), at frame: 3644501915.
>          0.158042917 "audio_alsa.c:1780" alsa: underrun while writing 352 samples to alsa device.
>          0.020162187 "audio_alsa.c:1780" alsa: underrun while writing 352 samples to alsa device.
>          0.021392240 "audio_alsa.c:1780" alsa: underrun while writing 352 samples to alsa device.
>          0.020529531 "audio_alsa.c:1780" alsa: underrun while writing 352 samples to alsa device.
>          0.021984114 "player.c:2844" Large negative (i.e. early) sync error of -7698 frames (-0.174558 seconds), at frame: 3644513179.
>          7.704852289 "player.c:2591" Sync Error ms | Net Sync PPM | All Sync PPM | Min DAC Queue | Min Buffers | Min Buffer Size | Output FPS (r) | Output FPS (c)
>          0.000100313 "player.c:2591"         33.59        -1124.7         1124.7               0            46              233k              N/A              N/A
>          8.000929424 "player.c:2591"         15.59        -2840.9         2840.9            7814            45             3330k         44100.11         44100.39
>          8.016187861 "player.c:2591"          1.83         -235.1          235.1            7471            46             3328k         44101.48         44101.76
>

**Comment by abid76** [comment]
**Update:** I tried the exactly same as above but connected the speakers via HDMI and set audio to HDMI via `raspi-config`. 

The result is exactly the same even the poor audio quality (volume is a bit low and the output seems to have only little bass).

**Comment by mikebrady** [comment]
Thanks -- I edited your message slightly to format the log. Your results indicate that Shairport Sync is working as far as getting audio and sending it to the default output is concerned. The poor quality of the sound on the jack is certainly partly the result of the poor quality of the DAC, but the poor quality on the HDMI port is more troubling. 

At present, your output is to the `default` `alsa` device. In reality, that is probably a fake device (a `"pseudo"` device). We need to bypass it because it may be partly causing the poor audio quality. It may also be transcoding the output from 44,100 frames per second (fps) to 48,000 fps, which may be necessary for HDMI to work. We need to know if that is the case. So, to investigate these two things, perhaps you would do the following.

1. Change the output back to the jack.
2. Edit the configuration file to set `output_device` in the `alsa` stanza to `"hw:Headphones"` (remembering to uncomment the line):

```
...
alsa =
{
	output_device = "hw:Headphones"; // the name of the alsa output device. Use "shairport-sync -h" to discover the names of ALSA hardware devices. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
//	mixer_control_name = "Headphone"; // the name of the mixer to use to adjust output volume. No default. If not ```
...
```
Check that you are getting audio through the headphone jack.
Next, switch the output back to HDMI and repeat the test. Perhaps you could post your progress here.

**Comment by abid76** [comment]
Same result when using jack (`output_device = "hw:Headphones";`). Especially the volume is quite low. Log output:

```
abid@manwe:~ $ shairport-sync -v --statistics
         0.002017657 "shairport.c:2200" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "b8:27:eb:90:6b:cb".
         0.000135260 "shairport.c:2239" Version String: "4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000028698 "shairport.c:2258" Command Line: "shairport-sync -v --statistics".
         0.000104896 "shairport.c:2265" libsodium initialised.
         0.000398906 "shairport.c:2290" libgcrypt initialised.
         0.000029740 "shairport.c:2294" Log Verbosity is 1.
         0.000063645 "audio_alsa.c:1031" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000063386 "audio_alsa.c:1320" alsa: disable_standby_mode is "never".
         0.000020469 "audio_alsa.c:1324" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000020677 "audio_alsa.c:1326" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000030625 "audio_alsa.c:1366" alsa: output device name is "hw:Headphones".
         0.000220781 "shairport.c:2342" disable_resend_requests is off.
         0.000031562 "shairport.c:2343" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000023282 "shairport.c:2347" statistics_requester status is 1.
         0.000019791 "shairport.c:2352" rtsp listening port is 7000.
         0.000016823 "shairport.c:2353" udp base port is 6001.
         0.000020417 "shairport.c:2354" udp port range is 10.
         0.000018385 "shairport.c:2355" player name is "Manwe".
         0.000019219 "shairport.c:2356" backend is "alsa".
         0.000016719 "shairport.c:2357" run_this_before_play_begins action is "(null)".
         0.000017031 "shairport.c:2358" run_this_after_play_ends action is "(null)".
         0.000018750 "shairport.c:2359" wait-cmd status is 0.
         0.000018906 "shairport.c:2360" run_this_before_play_begins may return output is 0.
         0.000017500 "shairport.c:2361" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000018750 "shairport.c:2363" run_this_before_entering_active_state action is  "(null)".
         0.000019063 "shairport.c:2365" run_this_after_exiting_active_state action is  "(null)".
         0.000018333 "shairport.c:2367" active_state_timeout is  10.000000 seconds.
         0.000023281 "shairport.c:2368" mdns backend "(null)".
         0.000016563 "shairport.c:2370" interpolation setting is "auto".
         0.000020000 "shairport.c:2374" interpolation soxr_delay_threshold is 30000000.
         0.000019062 "shairport.c:2375" resync time is 0.050000 seconds.
         0.000018178 "shairport.c:2376" allow a session to be interrupted: 0.
         0.000016718 "shairport.c:2377" busy timeout time is 0.
         0.000018229 "shairport.c:2378" drift tolerance is 0.001995 seconds.
         0.000019532 "shairport.c:2379" password is "(null)".
         0.000016823 "shairport.c:2380" ignore_volume_control is 0.
         0.000016875 "shairport.c:2384" volume_max_db is not set
         0.000017968 "shairport.c:2385" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000020938 "shairport.c:2387" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000020052 "shairport.c:2391" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000019948 "shairport.c:2393" disable_synchronization is 0.
         0.000018385 "shairport.c:2394" use_mmap_if_available is 1.
         0.000018490 "shairport.c:2395" output_format automatic selection is enabled.
         0.000018750 "shairport.c:2399" output_rate automatic selection is enabled.
         0.000018854 "shairport.c:2403" audio backend desired buffer length is 0.200000 seconds.
         0.000019792 "shairport.c:2405" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000020364 "shairport.c:2407" audio backend latency offset is 0.000000 seconds.
         0.000020000 "shairport.c:2409" audio backend silence lead-in time is "auto".
         0.000018438 "shairport.c:2413" zeroconf regtype is "_raop._tcp".
         0.000018906 "shairport.c:2414" decoders_supported field is 1.
         0.000018385 "shairport.c:2415" use_apple_decoder is 0.
         0.000018386 "shairport.c:2416" alsa_use_hardware_mute is 0.
         0.000018437 "shairport.c:2420" no special mdns service interface was requested.
         0.000047396 "shairport.c:2423" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000023802 "shairport.c:2453" loudness is 0.
         0.000019323 "shairport.c:2454" loudness reference level is -20.000000
         0.000137969 "shairport.c:2464" size of hw_addr is 8.
         0.005549687 "shairport.c:2547" NQPTP is online.
         1.501543646 "shairport.c:254" "soxr" interpolation has been chosen.
         1.788685520 "rtsp.c:1353" Connection 2: Connection closed by client.
         0.273747500 "rtsp.c:2883" Connection 1: AP2 PTP connection from 2003:e9:6f19:800:1831:9c7d:890e:32d0:61295 ("Abids iPhone 11") to self at 2003:e9:6f19:800:b319:7255:535e:a686:7000.
         0.031794896 "rtsp.c:4330" Connection 1: Current volume (-24.000000) requested
         2.167297447 "rtsp.c:3294" Connection 1. AP2 Buffered Audio Stream.
         0.786697968 "player.c:2774" Connection 1: Playback started at frame 868067662 -- AirPlay 2 Buffered.
         7.913227080 "player.c:2591" Sync Error ms | Net Sync PPM | All Sync PPM | Min DAC Queue | Min Buffers | Min Buffer Size | Output FPS (r) | Output FPS (c)
         0.000129219 "player.c:2591"         -0.24            0.0            0.0            7388            46              247k              N/A              N/A
         7.992599685 "player.c:2591"         -0.60            0.0            0.0            7376            46             3604k         44100.10         44097.15
         8.029927132 "player.c:2591"         -0.78            0.0            0.0            7372            46             3345k         44100.10         44097.75
         7.997626299 "player.c:2591"         -0.80            0.0            0.0            7371            46             3088k         44100.12         44098.20
^C         2.473851041 "player.c:1736" Connection 1: Playback stopped. Total playing time 00:00:34. Output: 44100.12 (raw), 44098.20 (corrected) frames per second.
         0.005937239 "player.c:393" 1024 buffers allocated, 1024 buffers released.
         0.010649584 "shairport.c:1674" normal exit
```

When using HDMI (set `output_device = "hw:vc4hdmi";`) hear absolutely nothing (see the last line below).

```
abid@manwe:~ $ shairport-sync -v --statistics
         0.002056615 "shairport.c:2200" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "b8:27:eb:90:6b:cb".
         0.000131614 "shairport.c:2239" Version String: "4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000071458 "shairport.c:2258" Command Line: "shairport-sync -v --statistics".
         0.000136198 "shairport.c:2265" libsodium initialised.
         0.000420209 "shairport.c:2290" libgcrypt initialised.
         0.000058698 "shairport.c:2294" Log Verbosity is 1.
         0.000088229 "audio_alsa.c:1031" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000089791 "audio_alsa.c:1320" alsa: disable_standby_mode is "never".
         0.000048698 "audio_alsa.c:1324" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000047344 "audio_alsa.c:1326" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000055521 "audio_alsa.c:1366" alsa: output device name is "hw:vc4hdmi".
         0.000238594 "shairport.c:2342" disable_resend_requests is off.
         0.000063281 "shairport.c:2343" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000050625 "shairport.c:2347" statistics_requester status is 1.
         0.000045990 "shairport.c:2352" rtsp listening port is 7000.
         0.000045000 "shairport.c:2353" udp base port is 6001.
         0.000044947 "shairport.c:2354" udp port range is 10.
         0.000044428 "shairport.c:2355" player name is "Manwe".
         0.000044583 "shairport.c:2356" backend is "alsa".
         0.000044583 "shairport.c:2357" run_this_before_play_begins action is "(null)".
         0.000045313 "shairport.c:2358" run_this_after_play_ends action is "(null)".
         0.000045312 "shairport.c:2359" wait-cmd status is 0.
         0.000048438 "shairport.c:2360" run_this_before_play_begins may return output is 0.
         0.000049323 "shairport.c:2361" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000049010 "shairport.c:2363" run_this_before_entering_active_state action is  "(null)".
         0.000047188 "shairport.c:2365" run_this_after_exiting_active_state action is  "(null)".
         0.000045833 "shairport.c:2367" active_state_timeout is  10.000000 seconds.
         0.000049062 "shairport.c:2368" mdns backend "(null)".
         0.000044948 "shairport.c:2370" interpolation setting is "auto".
         0.000044740 "shairport.c:2374" interpolation soxr_delay_threshold is 30000000.
         0.000048021 "shairport.c:2375" resync time is 0.050000 seconds.
         0.000038333 "shairport.c:2376" allow a session to be interrupted: 0.
         0.000020208 "shairport.c:2377" busy timeout time is 0.
         0.000019219 "shairport.c:2378" drift tolerance is 0.001995 seconds.
         0.000020052 "shairport.c:2379" password is "(null)".
         0.000018490 "shairport.c:2380" ignore_volume_control is 0.
         0.000019271 "shairport.c:2384" volume_max_db is not set
         0.000018541 "shairport.c:2385" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000019688 "shairport.c:2387" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000020052 "shairport.c:2391" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000020208 "shairport.c:2393" disable_synchronization is 0.
         0.000018594 "shairport.c:2394" use_mmap_if_available is 1.
         0.000018646 "shairport.c:2395" output_format automatic selection is enabled.
         0.000019635 "shairport.c:2399" output_rate automatic selection is enabled.
         0.000019167 "shairport.c:2403" audio backend desired buffer length is 0.200000 seconds.
         0.000020417 "shairport.c:2405" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000020885 "shairport.c:2407" audio backend latency offset is 0.000000 seconds.
         0.000020365 "shairport.c:2409" audio backend silence lead-in time is "auto".
         0.000018802 "shairport.c:2413" zeroconf regtype is "_raop._tcp".
         0.000019218 "shairport.c:2414" decoders_supported field is 1.
         0.000018750 "shairport.c:2415" use_apple_decoder is 0.
         0.000018646 "shairport.c:2416" alsa_use_hardware_mute is 0.
         0.000018698 "shairport.c:2420" no special mdns service interface was requested.
         0.000048229 "shairport.c:2423" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000023438 "shairport.c:2453" loudness is 0.
         0.000020000 "shairport.c:2454" loudness reference level is -20.000000
         0.000144531 "shairport.c:2464" size of hw_addr is 8.
         0.005536094 "shairport.c:2547" NQPTP is online.
         1.495516510 "shairport.c:254" "soxr" interpolation has been chosen.
         2.039054218 "rtsp.c:1353" Connection 1: Connection closed by client.
         5.592419268 "rtsp.c:2883" Connection 2: AP2 PTP connection from 192.168.2.100:61312 ("Abids iPhone 11") to self at 192.168.2.21:7000.
         0.048822396 "rtsp.c:4330" Connection 2: Current volume (-24.000000) requested
         2.744499582 "rtsp.c:3294" Connection 2. AP2 Buffered Audio Stream.
         0.084720625 "audio_alsa.c:544" *fatal error: audio_alsa: Could not automatically set the output format for device "hw:vc4hdmi": Invalid argument
```

Output of `shairport-sync -h`:
```
    ...
    hardware output devices:
      "hw:Headphones"
      "hw:vc4hdmi"
```

**Comment by mikebrady** [comment]
Thanks. That's all good:

1. The statistics show that audio is going to the output device with very little interpolation, which is as it should be.
2. The `hw:vc4hdmi` device [doesn't seems to work](https://github.com/raspberrypi/linux/issues/2992) in general.
3. Regarding the low volume, given that the `alsamixer` levels are at 100%, try increasing the volume at the source, e.g. Spotify, etc. This is because, by default, the initial volume is set to -24.0 on a -30.0 to 0.0 logarithmic (?) scale.

Subject to that volume issue being fixed, you have resolved two of the three issues:
1. No sound
2. HDMI
3. PulseAudio

So let's look at the third issue, PulseAudio.

**PulseAudio**

If you have a desktop version of Raspberry Pi OS installed, then it installs the PulseAudio sound server. This makes life easier for the GUI but harder for a service like Shairport Sync because it only offers an audio service to a user that has logged in through the GUI. Once the user has logged in, audio sent to the `default` audio device is handled by PulseAudio. However, if the user has not logged in, or if a program is running as another user, the `default` audio device doesn't work.

This would account for your experience when the output device for Shairport Sync was the `default` device -- it only worked from the command line, i.e. after you had logged in.

Now, since you have changed from using the default device to the specific device `hw:Headphones`, it may be that Shairport Sync will now work as a service, since it is bypassing that fake `default` device, so (presuming you already did the full installation in the BUILD guide) let me suggest that you enable `shairport-sync` as a system service and restart:

```
$ sudo systemctl enable shairport-sync
$ sudo reboot
```

However, it is still possible, I guess, that PulseAudio is interfering with access to the real output device, so please let us know how things go.

**Comment by abid76** [comment]
Ok, after setting device to `hw:Headphones` and enabling shairport-sync as a service, `sudo journalctl -f -u shairport-sync` still ouputs
`Mär 18 10:22:00 manwe shairport-sync[480]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory`

**Comment by mikebrady** [comment]
Thanks. So, does the service work?

**Comment by abid76** [comment]
Yes as I stated [above](https://github.com/mikebrady/shairport-sync/issues/1365#issuecomment-1474786946) 😄 but the volume is a little low.

**Comment by mikebrady** [comment]
> Yes as I stated [above](https://github.com/mikebrady/shairport-sync/issues/1365#issuecomment-1474786946) 😄 but the volume is a little low.

Missed that, sorry.

That message seems benign, and has something to do with PulseAudio.

You can get the player to control the hardware volume control by setting the `mixer_control_name`. I'm guessing that the correct entry for the Pi is:
```
	mixer_control_name = "Headphone"; 
```

Once this is done, the audio is in the hands of the Pi OS and hardware. Given the very-low-to-zero amount of interpolation, the audio fidelity is as good as it can get. 

I don't use the HDMI output, but the output from the jack, while poor quality, is certainly strong enough to drive a stereo and in my experience seems on a par with other DACs.

Maybe other users have more experience of HDMI, especially on newer versions of Raspberry Pi OS.

**Comment by abid76** [comment]
> ... in my experience seems on a par with other DACs.

Just FYI: when using the jack of an Apple Airport Express the volume is remarkably higher (don't know if this is related to the PI's hardware or it's software).
