### ISSUE TITLE
Airplay2 is out of sync

### ISSUE THREAD

**Issue by ilouzl** [mikebrady/shairport-sync#1366]
When I use AP2 (on a raspberrypi zero 2) to stream to multiple devices I get a sync error:

        10.393128161 "rtsp.c:5017" Connection 1: new connection from fe80::18bb:e9ec:cc2c:32b1:65520 to self at fe80::c882:2ca3:1659:ca0a:7000.
         0.651195506 "rtsp.c:2877" SETUP on Connection 1. Buffered Audio Stream Detected.
         0.067021630 "audio_alsa.c:528" alsa: output format chosen is "S32".
         0.000392291 "audio_alsa.c:569" alsa: output speed chosen is 44100.
         1.427850866 "rtp.c:1319" Connection 1: Clock 8c859067666f0008 is now the new anchor clock and master clock. History: 1500.119205 milliseconds.
         0.000159687 "rtp.c:1403" Connection 1: NQPTP new master clock 8c859067666f0008.
         0.029485981 "player.c:1059" Connection 1: Lead time for first frame 3942423519: 0.303478 seconds.
         8.102370852 "player.c:2855" sync error ms, net sync ppm, all sync ppm,     packets, min DAC queue, min buffers, max buffers,  output fps
         0.000422968 "player.c:2855"          0.10,          0.0,          0.0,        1003,          8500,          87,          88,    44092.74
         8.006984158 "player.c:2855"          0.10,          0.0,          0.0,        2006,          8557,          87,          88,    44097.30
         8.003873875 "player.c:2855"          0.18,          0.0,          0.0,        3009,          8546,          87,          88,    44098.03

Which is also audibly noticeable - there is an actual ~0.3sec delay bw what is played on the shairport device.
I stream from a macbook pro to 3 destinations:
1. Macbook speakers
2. Homepod 
3. shairport device

1 & 2 are in perfect sync but 3 is noticeably out of sunc.

I'm using version 
4.1-dev-27-g829e1ada-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

**Comment by mikebrady** [comment]
Thanks for the post. Can you tell us what the audio output device is for the Pi Zero 2 please? A question would be whether something in it is introducing a delay.

**Comment by ilouzl** [comment]
It's currently the hdmi port - 'hw:vc4hdmi'.

**Comment by mikebrady** [comment]
Thanks. And presumably it's going to some AV device or to a TV, right?

**Comment by ilouzl** [comment]
Yes of course. It's a TV.
Do you think the TV adds the delay?

**Comment by mikebrady** [comment]
> Do you think the TV adds the delay?

Yes, they typically add a processing delay and it can be quite audible. (Apple TVs have a nice facility to allow you to automatically adjust the audio timing to compensate for the TV's audio delays.)

Shairport Sync has a setting to allow you to do the same thing manually -- see `audio_backend_latency_offset_in_seconds` in the configuration file settings. You could set it to `-0.3` to compensate.

**Comment by ilouzl** [comment]
Thanks! 
I was convinced that there has to be such a parameter but couldn't find it.
I'll test it later and post the results

**Comment by mikebrady** [comment]
Thanks. Don't do crazy -- the range is limited, but ±0.3 should be fine!

**Comment by ilouzl** [comment]
It did help. Thanks!
