### ISSUE TITLE
Make fails on latest development version

### ISSUE THREAD

**Issue by Dangoo** [mikebrady/shairport-sync#1369]
Hello,

just writing to let you know that during a recent attempt to update and rebuild SC on my Raspberry PIs lead to an error during `make`:
```bash
mv -f $depbase.Tpo $depbase.Po
rtsp.c: In function ‘rtsp_read_request’:
rtsp.c:1177:14: error: ‘shairport_cfg’ {aka ‘struct <anonymous>’} has no member named ‘metadata_enabled’
   if ((config.metadata_enabled != 0) && (config.get_coverart != 0))
              ^
rtsp.c:1177:48: error: ‘shairport_cfg’ {aka ‘struct <anonymous>’} has no member named ‘get_coverart’
   if ((config.metadata_enabled != 0) && (config.get_coverart != 0))
                                                ^
mv -f pair_ap/.deps/lib_pair_ap_a-pair-tlv.Tpo pair_ap/.deps/lib_pair_ap_a-pair-tlv.Po
make[2]: *** [Makefile:900: rtsp.o] Error 1
```

The script I used for updating can be found here:
https://github.com/Dangoo/raspberry-audio-config/blob/main/shairport-update.sh
Executed on Raspberry PI 3 and PI Zero.

I'll test some previous commits to see what the latest working version is. Let me know if you need any more information :)

**Edit:** First guess of introduced change: https://github.com/mikebrady/shairport-sync/commit/8256324a35c3621c1be30ebeffe62217547b55f6
**Edit2:** Confirming 5d5595491db3785649e4dd6ad785d021be40d561 building correctly

**Comment by mikebrady** [comment]
Thanks. I’ll take a look tomorrow!

**Comment by winstonsetiawan** [comment]
Had the same issue yesterday, I ended up removing those specific lines from the rtsp.c file as a temporary fix and it works for now.

**Comment by mikebrady** [comment]
Fixed, thanks.
