### ISSUE TITLE
Airplay endpoint shows on some devices and not on others

### ISSUE THREAD

**Issue by rogersmj** [mikebrady/shairport-sync#1379]
I've been running shairport-sync for a few months, and have an intermittent problem I've struggled to track down. I'm currently running the AirPlay 2 (development branch) build on a Raspberry Pi.

Periodically, the AirPlay device just doesn't show on _some_ client devices when I try to play music to it. Right now, for example, I can see it on the MacOS Music app and on my iPad Pro, but not on my iPhone (all connected to the same WiFi access point on the same network). The RPi running shairport-sync is hardwired into the network. It has shown on my iPhone before, but right now it's not for some reason. This has periodically happened on multiple devices. It seems random.

I tried restarting the shairport-sync service on the RPi, to no effect.

All iOS devices are on iOS 15.1.1. I realize this is _probably_ an iOS/network issue, not a shairport-sync issue, but wanted to post here anyway to see if anyone has any ideas, because I am stuck.

```
$ shairport-sync -V
4.1-dev-110-g6f7e8947-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc
```

```
$ sudo service shairport-sync status
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-12-21 17:20:55 GMT; 2s ago
 Main PID: 932 (shairport-sync)
    Tasks: 7 (limit: 2059)
   CGroup: /system.slice/shairport-sync.service
           └─932 /usr/local/bin/shairport-sync

Dec 21 17:20:55 pisensors systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

**Comment by mikebrady** [comment]
Hi there. Thanks for the post.

At a guess, this is a problem with your network.

There are some troubleshooting suggestions at [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) and then some more information about what would be helpful reporting an issue at [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md).

Let us know how it goes, please.

**Comment by rogersmj** [comment]
Thanks Mike. I should have put the version in my original post, I added that.

I did skim the troubleshooting page, but most of it is about WiFi and network configuration like VPNs. My RPi is hardwired, and I don't have a VPN. All devices in question are on the same subnet. There are no firewall rules or security policies applied to devices on this subnet.

**Comment by mikebrady** [comment]
Fair enough. Could it be the router then? Any firmware updates available for it?

You can use an app called "Discovery" from TildeSoft on the Mac or iOS device and `avahi-browse` at the Linux end to see if the mDNS information that advertises AirPlay being generated and propagated the next time this happens.

**Comment by rogersmj** [comment]
It’s not the router/network. I have all Ubiquiti gear (a UDM Pro and multiple APs), and it’s all up to date thanks to the recent log4j vulnerability.

This morning, the Shairport-sync AirPlay device cannot be seen on _any_ of our iOS devices, while all the “official” hardware (various Apple TV’s, a couple Denon receivers, Sony TVs) with AirPlay can all be seen. So I think it has to be something with Shairport-sync or the RPi itself, because nothing on the LAN is impeding AirPlay broadcasting.

**Comment by mikebrady** [comment]
Thanks. Actually there are some issues with Ubiquiti gear — details in some of the (possibly closed) issues here. You can use Discovery and `avahi-browse` to see what is and is not being propagated.

**Comment by rogersmj** [comment]
Thank you so much Mike. I hadn't seen that thread. A combination of fiddling with mDNS settings on my network and rebooting UniFi gear as described in #1116 seems like it might have resolved the issue. Closing.
