### ISSUE TITLE
"Unable to Connect" with password

### ISSUE THREAD

**Issue by Hoseasack** [mikebrady/shairport-sync#1383]
When I enable a password in `/etc/shairport-sync.conf`. My iPhone 6 (_iOS 12.5.5_) can connect properly but my iPhone 8 (_iOS 15.2_) can't. Both can if there is no password.

**Comment by mikebrady** [comment]
Thanks for the post. Please take a look at the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page for some possible hints. The [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) page offers you a guide about what information you should include to make your posts more useful.
