### ISSUE TITLE
AirPlay 2: HomeKit pairing [un]stable identifier

### ISSUE THREAD

**Issue by chrisaljoudi** [mikebrady/shairport-sync#1385]
In `rtsp.c`:

```
plist_dict_set_item(response_plist, "deviceID", plist_new_string(config.airplay_device_id));
```

As far as I can tell, `config.airplay_device_id` is derived from MAC address and PID. PID isn't stable—does this not result in the HomeKit identifier not being stable?

I got here once I started looking into why HomeKit showed the speaker I already added and assigned to a room again as available for pairing, which led me to believe the identifier is not stable.

**Comment by mikebrady** [comment]
Thanks for the post. Yesterday evening I changed the `config.airplay_device_id` so that it was dynamic. I will revert it in the next hour or so. Apologies -- it seemed like a good idea at the time.

**Comment by mikebrady** [comment]
Fixed -- Version-4.1-dev-133 has reverted to a fixed `airplay_device_id`. You'll probably have to re-add the speaker one more time to the Home app.

**Comment by mikebrady** [comment]
Version-4.1-dev-138 has added some code to make the `airplay_device_id` assignment alterable but static.

**Comment by chrisaljoudi** [comment]
You’re awesome, thanks for the quick response and fix. ❤️
