### ISSUE TITLE
Best Practice for the location of Shairport Sync?

### ISSUE THREAD

**Issue by mikebrady** [mikebrady/shairport-sync#139]
Which is the correct location for the shairport-sync executable?

* I think, since it's compiled and installed by the user, it should go in `/usr/local/bin`.
* If it was installed by a package manager that's part of a distribution, it should go in `/usr/bin`, but that's not the case here.

Is this the correct kind of reasoning? If so, I'd like to change the `shairport-sync.service` file to reflect this. Any maybe @EliaCereda or @akshay1994 have a view about it in Elia's Arch Linux script?

(http://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux)

**Comment by joerg-krause** [comment]
Your thoughts are reasonable. However, IMO best option is to install to `$PREFIX/bin`. This way you can choose a default path for `PREFIX`, e.g. `/usr/local` and package maintainers can pass `PREFIX` through the build environment, e.g. `./configure --prefix=/usr`

**Comment by mikebrady** [comment]
Thanks. That's the way it works at the moment. I'll just have to update the `shairport-sync.service` file.

**Comment by mikebrady** [comment]
Hi @p3ck. Would you venture an opinion on this? It has implications for that `shairport-sync.service` file you contributed...

**Comment by p3ck** [comment]
Using --prefix certainly makes sense.  The question is should we update the
service file to match this?  Maybe we have a shairport-sync.service.in and
that has a @prefix@.  make would generate a shairport-sync.service with the
appropriate value of prefix.

Thoughts?

On Fri, Oct 9, 2015 at 7:54 AM, Mike Brady <notifications@github.com> wrote:

> Hi @p3ck <https://github.com/p3ck>. Would you venture an opinion on this?
> It has implications for that shairport-sync.service file you
> contributed...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikebrady/shairport-sync/issues/139#issuecomment-146842253>
> .
>



-- 

Bill Peck
http://www.pecknet.com

**Comment by mikebrady** [comment]
Sounds good to me. Could I ask you to do that, or perhaps show -- or point to -- how I might do it?

**Comment by p3ck** [comment]
Hi Mike,

I'll take a stab at doing that over the weekend.

Bill

On Fri, Oct 9, 2015 at 9:03 AM, Mike Brady <notifications@github.com> wrote:

> Sounds good to me. Could I ask you to do that, or perhaps show -- or point
> to -- how I might do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikebrady/shairport-sync/issues/139#issuecomment-146865299>
> .
>



-- 

Bill Peck
http://www.pecknet.com

**Comment by mikebrady** [comment]
Thanks!
