### ISSUE TITLE
HomeKit Tile

### ISSUE THREAD

**Issue by tecdude** [mikebrady/shairport-sync#1391]
@mikebrady do you have plans to enable the HK tile to light up when playing?

**Comment by mikebrady** [comment]
Hi there. Unfortunately, as you'll surely know, the protocols have not been published, so it is not known how to do this. It would be great to know!

**Comment by acresp** [comment]
It would be great, but something I saw is that my Denon AVR which is AP2 compatible does not have the HK tile which light up when playing...
Maybe this behaviour is reserved to the AppleTV?
