### ISSUE TITLE
Unable to install on RPI

### ISSUE THREAD

**Issue by brbrr** [mikebrady/shairport-sync#140]
Going through General Build Instructions tyring to build it for my RPI(B+) on Raspbian. 
actually everything goes smooth until last step: `sudo update-rc.d shairport-sync defaults 90 10`

```
 ~/shairport-sync $ sudo update-rc.d shairport-sync defaults 90 10
update-rc.d: using dependency based boot sequencing
insserv: warning: script 'shairport-sync' missing LSB tags and overrides
insserv: There is a loop between service watchdog and shairport-sync if stopped
insserv:  loop involving service shairport-sync at depth 2
insserv:  loop involving service watchdog at depth 1
insserv: Stopping shairport-sync depends on watchdog and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
```

Here what's my `./configure` includes:
`$ ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemv`

No errors where thrown during config/make

**Comment by mikebrady** [comment]
Hi there. Are you on Raspbian Jessie, by any chance?

**Comment by brbrr** [comment]
Nope, wheezy here
```
$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
```

**Comment by mikebrady** [comment]
Hmm, that's identical to what I get, and I'm not having problems. Is it possible you have made other changes that might be causing this? (Sorry to ask, but did you do a `sudo make install` beforehand?)

**Comment by brbrr** [comment]
ah, ok. I thought my problems cause because of issues in   `$ sudo update-rc.d ...`
actually it's works after that, but I need to start it manualy, and it didn't demonize, so
```
$ sudo service shairport-sync start
startup
```
don't go to background. 
Also daemon not starting on startup.

**Comment by mikebrady** [comment]
Thanks for the information. It would be worth checking that the startup script is in correctly in place. It should be at `/etc/init.d/shairport-sync` and it should contain a `-d` to tell Shairport Sync to demonise itself. In the default file it's line 66:
```
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d || return 2
```
You can see the `-d` towards the end of it.

**Comment by brbrr** [comment]
hm, interesting. looks like `/etc/init.d/shairport-sync` is binary file.

```
$ less /etc/init.d/shairport-sync 
"/etc/init.d/shairport-sync" may be a binary file.  See it anyway? 
```

**Comment by mikebrady** [comment]
It should be a text-only file. It seems like the installation process went astray somehow...

One think to do would be to move or remove it and to re-run the `sudo make install` again. It will install the startup file again.

**Comment by brbrr** [comment]
Thats was some issue with compiling. I cloned and build from develop branch - and everything work smoothly. thanks!
