### ISSUE TITLE
Issue with lock screen volume slider on iOS devices

### ISSUE THREAD

**Issue by d80h4g** [mikebrady/shairport-sync#1400]
I'm noticing a strange effect when using the development branch. I've compiled the latest dev release on a Raspberry Pi 4:

`4.1-dev-165-gb566d641-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`

`Linux xxxx 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
`

It's generally working great - streaming to it using iOS devices and a Macbook over Airplay 2. Sounds great and multi-room works as expected.

The issue I'm having is when trying to adjust volume using the slider in the widget on the iphone lock screen. The volume immediately jumps to zero as soon as I first touch it and I have to use the iphone volume buttons to get it back up again. The volume control in the pull down control panel works fine, as do the volume buttons on the side of the phone. I'm seeing the same effect on two different iphones running iOS 15.2, although interestingly it's not happening on an old ipad running iOS 12.

I've compiled with standard config options as follows:

./configure --sysconfdir=/etc --with-alsa     --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2

Is this a known issue?

Thanks for everything you do with shairport-sync. I've had it running flawlessly on numerous devices for years, so huge thanks!

**Comment by iChUdY** [comment]
I can confirm this behavior. Sometimes it happens and sometimes it doesn't.

**Comment by th0u** [comment]
I also can confirm this iOS 15.3

`
4.1-dev-163-g7212504c-AirPlay2-alac-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc
`

**Comment by JanLp** [comment]
This has been an issue since iOS 14.8 and has nothing to do with sps. volume control with airplay 2 is generally unstable and therefore I use airplay 1

**Comment by th0u** [comment]
iOS 15.3 (19D49) does not resolve this.

**Comment by th0u** [comment]
Still unresolved in iOS15.5 Beta(19F5047e)

**Comment by JanLp** [comment]
> Still unresolved in iOS15.5 Beta(19F5047e)

Report it using the feedback assistant. I have tried several times, the more people who do it, the better

**Comment by th0u** [comment]
FYI: iOS16 B6 (20A5349b) resolves this issue. Earlier iOS16 Betas could perhaps also help.
