### ISSUE TITLE
[Feature] Volume sync between devices playing (AP2)

### ISSUE THREAD

**Issue by corrpel** [mikebrady/shairport-sync#1401]
Hello,
I don't know if it possible, but maybe ap2 can achieve it.
Can we align volume to SPS, meaning that if i play on SPS and one Homepod or multiple,
when volume is different from Homepod, send to all homepods playing in the same session as SPS the same volume?
For example, I am playing SPS as a subwoofer, and two pairs of homepod minis in the same room, sometimes volume is different and i have to adjust it.
Thank you.

**Comment by mikebrady** [comment]
Thanks for the suggestion. TBH, I think this would be difficult, and AFAIK would be beyond any of the protocols we already know about in AirPlay 2.

Regarding the issue itself, I know that when a number of devices are being used, there is usually a master volume control which seems to vary the individual device volumes proportionately.

**Comment by th0u** [comment]
iOS 15.3 (19D49) does not resolve this.

**Comment by zhjb7** [comment]
> Thanks for the suggestion. TBH, I think this would be difficult, and AFAIK would be beyond any of the protocols we already know about in AirPlay 2.
> 
> Regarding the issue itself, I know that when a number of devices are being used, there is usually a master volume control which seems to vary the individual device volumes proportionately.

I am running SPS in ubuntu, and with one homepod. I send VolumeDown via the Shairport Sync D-Bus interface,  this will down the volume of homepod. Can I use other protocol command to just down my ubuntu? Thank a lot!

**Comment by zhjb7** [comment]
> Thanks for the suggestion. TBH, I think this would be difficult, and AFAIK would be beyond any of the protocols we already know about in AirPlay 2.
> 
> Regarding the issue itself, I know that when a number of devices are being used, there is usually a master volume control which seems to vary the individual device volumes proportionately.


Thanks for the suggestion. TBH, I think this would be difficult, and AFAIK would be beyond any of the protocols we already know about in AirPlay 2.

Regarding the issue itself, I know that when a number of devices are being used, there is usually a master volume control which seems to vary the individual device volumes proportionately.

I am running SPS in ubuntu, and with one homepod. I send VolumeDown via the Shairport Sync D-Bus interface, this will also down the volume of homepod. Can I use other protocol command to just down my ubuntu? Thank a lot!

**Comment by zhjb7** [comment]
> Thanks for the suggestion. TBH, I think this would be difficult, and AFAIK would be beyond any of the protocols we already know about in AirPlay 2.
> 
> Regarding the issue itself, I know that when a number of devices are being used, there is usually a master volume control which seems to vary the individual device volumes proportionately.

I am running SPS in ubuntu, and with one homepod. I send VolumeDown via the Shairport Sync D-Bus interface, this will also down the volume of homepod. Can I use other protocol command to just down my ubuntu? Thank a lot!

**Comment by mikebrady** [comment]
Thanks for the post. I don't think there is a way to send the command just to SPS on your Ubuntu system, I'm afraid. When you send VolumeDown request to SPS over D-Bus, what happens is that SPS forwards it to the player -- iTunes, the Music app or whatever --  and then the player sends a new volume level to each output device. Unfortunately SPS can not ask  for it to be sent to just one output device.

**Comment by zhjb7** [comment]
Thanks your post. So can you delete the discussion which I can't delete it. Thanks. [1490](https://github.com/mikebrady/shairport-sync/discussions/1490 )

**Comment by mikebrady** [comment]
Many thanks. The issue is already closed, so no worries.
