### ISSUE TITLE
Ok, this isn't an issue caused by shairport, but please hear me out.

### ISSUE THREAD

**Issue by calvincorrieri** [mikebrady/shairport-sync#1402]
Ok so on Catalina, if you use the Music (iTunes) app to airplay music, the shairport speaker shows up. However, it does not show up anywhere else. So Catalina is obviously aware of the speaker and is able to play to it just fine when using the Apple Music app (I tested it myself.) On my iPhone 11, the shairport speaker shows up everywhere no matter what. It's got to be some Apple bs trying to force people with Macs to buy Apple TV's or some crap like that.

If anyone can think of a way to defeat this mechanism that seems to be built into macOS Catalina, send me an email at nutsackula@gmail.com, there will be a bitcoin bounty.

MacBook Pro 2019 16in btw

**Comment by mikebrady** [comment]
I’m afraid I don’t understand your message. Under what circumstances does “it not show up anywhere else”? Is it possible that you are running the Mac as a hotspot (i.e. using Internet Sharing) or do you have a VPN running? Or is there a firewall running somewhere?

**Comment by calvincorrieri** [comment]
Sorry for any confusion. What I’m saying is that if I open the Apple Music app on Catalina and click the airplay icon, the shairport speaker shows up. However, no other application or part of MacOS Catalina detects anything except for Apple TV’s. Like MacOS obviously sees the device and is able to cast to it, it just doesn’t show up unless you’re specifically using the Apple Music app. If you go to the top where the airplay icon is located, the shairport server won’t show up. I’ve tried enabling/disabling vpn, trying over both WiFi and direct Ethernet connection, I’ve tried rebooting both Mac and my Raspberry Pi, at this point I’m convinced that it’s Apples Catalina that is causing the issue. I believe the system is intentionally refusing to display the speaker device because it only wants to display devices capable of screen mirroring everywhere outside of the Apple Music app. Since you’re the developer of shairport I don’t expect any kind of solution to the matter since there’s not much you can do without altering how Catalina handles airplay devices. If you think that there is in fact a solution to this issue, please let me know. And if you’re willing to tinker with Catalina and find a way to get it to work with shairport across the board, I’m offering a generous bounty.

**Comment by calvincorrieri** [comment]
I’d also like to add that on iOS devices regardless of the iOS version all detect my shairport speaker as a valid airplay receiver, just like the default Apple Music app does on MacOS Catalina.

**Comment by charlesomer** [comment]
Hi @calvincorrieri, please correct me if I'm wrong but this sounds you might be trying to cast a display to Shairport Sync (which isn't possible) rather than just audio. When you click on the speaker icon instead of the airplay icon in the top menu bar of macOS do you see the Shairport Sync speaker?

**Comment by calvincorrieri** [comment]
The point that I’m trying to make, as you can see in this photo, is that the only option for airplay is to cast the screen. There is no option anywhere that allows for strictly audio airplay. The only exception I’ve been able to find is the Apple Music app which allows you to cast audio to both standalone speakers (shairport) and screen-mirroring devices like Apple TV’s. Here is another picture illustrating that outside of the Apple Music app, shairport is not listed as an available device. 
Am I missing a setting being enabled or something that allows Catalina to detect airplay sources that are audio only? It’s clearly not a compatibility issue. You alluded to a different drop down airplay menu that’s meant strictly for audio only devices, is that something I can easily enable?

**Comment by charlesomer** [comment]
Unfortunately I think your photos haven't been uploaded in your response. But it sounds like the speaker icon isn't enabled in the macOS menu bar - it can be enabled in System Preferences -> Sound > Show Sound in menu bar (at least that's what it is for Monterey but I think it's been the same for a while).

**Comment by calvincorrieri** [comment]
Dude THANK YOU!!! That was exactly it! Idk why tf it was disabled, this was a clean install. I definitely didn’t do that myself. It’s always the simplest damn thing, isn’t it? lol

**Comment by charlesomer** [comment]
Haha no worries, I think it's disabled by default for some reason 🤷‍♂️
