### ISSUE TITLE
How can I get the Airplay2 version of shairport-sync onto my raspberry?

### ISSUE THREAD

**Issue by b3z** [mikebrady/shairport-sync#1403]
Do I have to build it my self or is there a package somewhere?

**Comment by charlesomer** [comment]
Hi, the airplay 2 version is still in development and needs to be build manually. Please see the Build For Airplay 2 instructions here: https://github.com/mikebrady/shairport-sync/blob/development/BUILDFORAP2.md

Alternatively you can use the docker image here: https://github.com/mikebrady/shairport-sync/tree/development/docker
