### ISSUE TITLE
Problems with IPv6 global unicast addresses.

### ISSUE THREAD

**Issue by Alion548** [mikebrady/shairport-sync#1406]
![image](https://user-images.githubusercontent.com/8340545/150103241-bbd98699-df3c-4dff-a69e-7bbc70a6d166.png)

The logs reveal that shairport-sync is communicating via a global unicast address, not a local IPv6 address (FE80::). This causes disconnection of music playback when iOS IPv6 changes.

**Comment by mikebrady** [comment]
Thanks for the post. This is a problem alright, and I think the issue is with Avahi — it does not seem possible to prevent Avahi from advertising the SPS service on a global IP address. I’d love to be wrong! At the moment, the only workaround is to ensure that the device either doesn’t get a global address or gets a constant one.

**Comment by npmstart-pray** [comment]
Has nobody looked into if Avahi is indeed the cause, and if it has been updated since?

**Comment by mikebrady** [comment]
If you look at the the Avahi [repository](https://github.com/lathiat/avahi) itself, you'll see that there are many issues and pull requests associated with issues like this. So it looks like a topic that might take some time to resolve.

Another workaround for Shairport Sync is to ask Avahi not to use or advertise any IPv6 addresses. You can do this using the `avahi-daemon.conf` settings file. The two settings to edit are as follows:
In the `[server]` section:
```
use-ipv6=no
```
and in the `[publish]` section:
```
publish-aaaa-on-ipv4=no
```
You should restart the device.

The device will still have any IPv6 addresses it had before, but they will not be provided to devices using Bonjour-advertised services such as AirPlay 2.
