### ISSUE TITLE
Shairport device cannot be found when connected to a different mesh router via lan in same network.

### ISSUE THREAD

**Issue by Seestali** [mikebrady/shairport-sync#1413]
My configuration:
I have 2 routers in my network placed across my house.
One is configured as the as the main and the other one as the mesh router.
They are connected via cable. They are configured as the same network and the DHCP is done on the main.
The shairport-device is connected via lan to the mesh router and is pingable and reachable over lan from the main and mesh.
Shairport-sync is build with the development branch and configured with airplay 2.

My problem:
As soon as i use an ethernet connection on my mac, connected to the main router, apple music can't find the shairport-device in the network anymore. It is still shown by apple music with the given name, but as soon as you try to connect an error message appears that the device cannot be found in the network.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/15279239/150643359-41977b76-2e24-4c37-a990-5904bf10508d.png">

This problem does not occur when connected to wifi.
I am able to connect to the device and play music on any device from the mesh and main router.
It solely appears when connected via ethernet to the main router.

This is the shown log with "shairport-sync -vu --statistics"
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/15279239/150643297-03c9eacb-ee3c-40ab-a046-e0dc7a572d13.png">

No new log message appears when you try to connect via ethernet.

**Comment by mikebrady** [comment]
Thanks for the post. This looks like some kind of a network problem.

It would seem that the mDNS advertisement packets for Shairport Sync are getting through to the Mac, so the Mac can see the service. However, when the Mac attempts to make a connection, it fails; the protocol exchange fails and the Mac then reports the failure.

There's an app for the Mac called "Discovery" from TildeSoft that you can use to examine the mDNS stuff, and you might be able to see what IP numbers Shairport Sync is is advertising. Perhaps the network will not route the IP number chosen by the Mac, or something like that.But to me, it doesn't seem to be a Shairport Sync problem per se.

**Comment by Seestali** [comment]
I will check that.
What made me think it is a shairport problem is that with the master build (Airplay 1) there is no problem.
This is only on the development branch with Airplay 2.
Is it using a different protocol?

**Comment by mikebrady** [comment]
Thanks. It’s a modified RTSP protocol, similar to AirPlay 1 but it’s on port 7000, not port 5000.
