### ISSUE TITLE
Question about HomePod

### ISSUE THREAD

**Issue by leo150** [mikebrady/shairport-sync#1414]
First of all, thank you for the amazing library. It works flawlessly. 
My question is about playing music from HomePod. I have two rooms in Home app:
* Kitchen with HomePod
* Bedroom with shairport-sync Raspberry/Speakers

Playing music from iPhone > AirPlay works great.

My goal is to ask Siri to play music in the bedroom. Every time I say "Hey Siri, play some music in the bedroom" she is just ignoring "bedroom" part and plays music in kitchen. Asking to "play everywhere" plays only on HomePod as well.

So it doesn't quite understand that the speakers are assigned to the bedroom. Another possible option is that it doesn't understand that the Raspberry is a speaker, because iPhone > Control Other Speakers & TVs doesn't show the Raspberry.

Is there any way to achieve my goal?
> 4.1-dev-101-gfbce5906-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

**Comment by leo150** [comment]
Also I should mention I have HomePod mini. I've reinstalled shairport with metadata and there's some progress
> 4.1-dev-170-gfba2f33b-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc

I moved HomePod to from Kitchen to Living Room and when I asked Siri to play music in the Bedroom, it worked. The sound played on the speakers and I saw connection in the shairport log. But now I tried to say the same line for 20 times already and it keeps playing the music on the HomePod.

**Comment by leo150** [comment]
Phrase that isn't working: "Hey Siri, play music in the Bedroom" - "Sorry, I can't tell what speaker you're referring to"
But what does work is to start playing music in the Kitchen and then ask "Hey Siri, transfer music to the Bedroom". It connects to the shairport correctly.

**Comment by leo150** [comment]
Looks like HomePod problem since 15.1.1 update. [Thread](https://discussions.apple.com/thread/253350805) on Apple forum.

**Comment by b3z** [comment]
@leo150 I have the same issue. Doesn’t he SPS speaker has to be added to a room in the Home App for it to work?
