### ISSUE TITLE
Ignore volume control still sending min_db value in pvol, pipe output

### ISSUE THREAD

**Issue by greend139** [mikebrady/shairport-sync#1417]
I am using shairport-sync with the pipe output to forward to owntone.  I have noticed that with SPS configured to ignore volume control, the pvol message on the metadata pipe is ignore by owntone with the following message. 
`daapd    | [2021-12-12 11:01:29] [DEBUG]   player: Not applying Shairport airplay volume while software volume control is enabled (-27.38,0.00,-96.30,0.00)`

I seems that in [player.c](https://github.com/mikebrady/shairport-sync/blame/development/player.c#L3160) SPS is always including the min_db value, and owntone refuses to apply the volume from the pvol value unless the last 3 values in the message are equal to ",0.00,0.00,0.00".

Not sure if this is regression in SPS, or a bug in owntone.  I believe this used to work correctly. 

Running development branch
`4.1-dev-175-g8d3bbe22-AirPlay2-alac-OpenSSL-Avahi-ALSA-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc`

**Comment by mikebrady** [comment]
Thanks. I'll check this out.

**Comment by mikebrady** [comment]
Thanks again for reporting this regression, which was due to other changes in the volume control code. Would you be kind enough to try the latest version in the `development` branch to see if the problem has been resolved?

**Comment by greend139** [comment]
Thanks for the quick fix.  Tested in my docker container and it works as expected again.
