### ISSUE TITLE
control alsa volume with  plughw card 

### ISSUE THREAD

**Issue by flipoidix** [mikebrady/shairport-sync#1418]
Hello, thank you for your awesome software

I would like to know if it is possible to use one output device and other for volume control.
the problem I have is a usb speaker that the sound clicks if I use the settings:

output_device = "hw:UACDemoV10";
mixer_control_name = "PCM";
mixer_control_index = 0;

but works perfectly with 

output_device = "plughw:UACDemoV10";
mixer_control_name = "PCM";
mixer_control_index = 0;

The problem I have is that I cannot control the volume when I'm using the plughw. can I use the hw: just to set the mixer volume?

Thank you!

**Comment by mikebrady** [comment]
Thanks for the post. Have you tried using the `mixer_device` setting?
Maybe add:

```
mixer_device = "hw:UACDemoV10";
```

Please let us know how it works out -- I haven't tested it in a while.

**Comment by flipoidix** [comment]
Perfect!!! 

It worked :) 

thank you very much once again! 


> Thanks for the post. Have you tried using the `mixer_device` setting? Maybe add:
> 
> ```
> mixer_device = "hw:UACDemoV10";
> ```
> 
> Please let us know how it works out -- I haven't tested it in a while.
