### ISSUE TITLE
How RAM intensive is shairport-sync with AirPlay 2

### ISSUE THREAD

**Issue by nmcc1212** [mikebrady/shairport-sync#1421]
I am looking to use 12 pi's for per room audio, should i get the 2,4 or 8gb model

**Comment by mikebrady** [comment]
Shairport Sync uses of the order of 10s of megabytes, so even the 2GB Pi should have plenty of space.

**Comment by charlesomer** [comment]
You might also want to consider the new version of the Pi Zero depending on your use case 😄
