### ISSUE TITLE
MQTT Empty Payload not working with home assistant binary sensor

### ISSUE THREAD

**Issue by UMB8998** [mikebrady/shairport-sync#1425]
Hello.

I'm trying to set up an MQTT binary sensor for the `active_end` and `active_start`, but it doesn't work. I'm not sure if I have something that's not configured correctly or maybe home assistant has changed something on their config.

Running the mosquito server on verbose I get the message and it shows as an 0 byte message

```
1644013781: Received PUBLISH from Test (d0, q0, r0, m0, 'shairport/active_start', ... (0 bytes))
```

Similarly, if I subscribe to the topic in home assistant I can see the message, but the system doesn't do anything to update the sensor. If I send a message manually that says "OFF" the sensor goes off as it should be, but it can't detect empty messages.

There is any way to change the payload to have something on it?

P.S. Sorry for my bad English, and thank you for the good work.

**Comment by mikebrady** [comment]
Thanks for the post. Your English is excellent, but I made a few tiny format and punctuation edits to make it a bit clearer for other people are viewing it -- I hope that's okay.

See #1375 for a discussion that may be related to this. I guess we could add an MQTT configuration option to add a dummy payload -- say, the integer 0 -- to an otherwise-empty message. Would that work?

**Comment by UMB8998** [comment]
Yes, that would definitely work, I tried sending the payload to home assistant with anything but an empty message and the sensor worked flawlessly. 
Maybe it would be possible to use the same message as a status for the current state, instead of having to messages for active_start and active_end, to have only one message with a high status for active and a low status for inactive (maybe 1 and 0) that way it will be easy to monitor the current status using only one switch

**Comment by mikebrady** [comment]
Thanks. Adding a dummy payload is much easier to implement, and will work for all the messages with empty payloads, so I think we’ll go with that. It may take a few days…

**Comment by mikebrady** [comment]
I just pushed an update in the `development` branch that adds a dummy payload to otherwise-empty payloads. If you got a chance to try it out, that would be great.

**Comment by UMB8998** [comment]
Thank you it worked perfectly home assistant recognized the payload.
I just had to change some setting in home assistant for it to work, it had an issue, basically the configuration shared on the readme, only let's you start an automation when the system starts or ends, and there is no way to track the current state, also if the state changed inside the 300 seconds, both sensors will be on, and if you turn one of them on again, the system is not going to detect the change. So I change a little bit the settings and implemented a template to track the current status.

```
binary_sensor:
  - platform: mqtt
    name: "shairport active start"
    state_topic: "shairport/active_start"
    payload_on: "--"
    payload_off: "OFF"
    off_delay: 1

  - platform: mqtt
    name: "shairport active end"
    state_topic: "shairport/active_end"
    payload_on: "--"
    payload_off: "OFF"
    off_delay: 1

template:
  - sensor:
      - name: "Shairport Active"
        state: >
          {% if states.binary_sensor.shairport_active_end.last_changed > states.binary_sensor.shairport_active_start.last_changed %}
            {% if not is_state('binary_sensor.shairport_active_end', 'unknown') %}
              off
            {% endif %}
          {% elif states.binary_sensor.shairport_active_end.last_changed < states.binary_sensor.shairport_active_start.last_changed %}
            {% if not is_state('binary_sensor.shairport_active_start', 'unknown') %}
              on
            {% endif %}
          {% endif %}
```

Also something to note is that you are sending dummy payloads to all the otherwise-empty payloads, so I my case I got a song without genre and it got send the empty payload. I think that's a good thing because it updates the status, but if somebody doesn't want it it could just use a filter to ignore the result when that payload comes
