### ISSUE TITLE
SEGV when parsing incorrect data in config file

### ISSUE THREAD

**Issue by hifiberry** [mikebrady/shairport-sync#1431]
Just had my system crashing here. After some debugging, I figured, that there was an incorrect entry in the configuration file:

        wait_for_completion = "NaN";
        
With this (incorrect) configuration, shairport-sync (latest development release) crashed with a segmentation fault. I understand that the configruation is incorrect, but sahirport-sync should ignore it, report it or something like this, not crash.

**Comment by mikebrady** [comment]
You are right of course! 😊

**Comment by mikebrady** [comment]
Thanks again for the bug report. The fix will appear shortly in a `development` update. It turns out that there were a number of similar errors; hopefully they have been caught.

Some of them are meant to cause Shairport Sync to exit somewhat gracefully, but they should put a message in the log.

**Comment by hifiberry** [comment]
👍

**Comment by mikebrady** [comment]
Just FYI, that push to the `development` branch has been done.
