### ISSUE TITLE
[FR] Allow specifying port range in AP2

### ISSUE THREAD

**Issue by jrfitzsimmons** [mikebrady/shairport-sync#1435]
// Moving from https://github.com/mikebrady/shairport-sync/pull/1434.

AP2 mode currently binds to ephemeral TCP/UDP ports meaning firewalls have to allowlist a huge range of ports (~25,000 for each of TCP and UDP). Request is for configuration options to allow for a more restrictive range of ports, so that firewall rules can be made more reasonable.

> However, all the AirPlay 2 implementations examined so far use ephemeral TCP/UDP ports (as you have mentioned), so your suggested modification would be a departure from this. At this point in our understanding of the protocols, such a departure would seem inadvisable

Would you be more open to this feature if it was default-off/opt-in, so standard installs still use the ephemeral range?

I haven't looked closely at the implementation but I'm assuming shairport is telling the client what ports to connect to as part of the connection init process. Before filing the PR, I tested it with my RPis and it worked fine, so there's nothing about the spec that seems to require a high port number.

In theory a similar outcome could be achieved with ephemeral ports by adjusting `net.ipv4.ip_local_port_range`, but you'd still need a fairly wide port range and it doesn't really help with the firewall rules.

**Comment by mikebrady** [comment]
Thanks for the ideas. Actually, you’re implementation would be fine, especially with a default opt out. But until the protocols are better understood, it’s best to keep the complexity down. Perhaps this can be revisited when we have  some experience with a release.

**Comment by jrfitzsimmons** [comment]
Yep, understand the desire to keep things simple for now. I'll probably keep running with the limited port range in a branch, just because the RPi is running a few other services (Pi-hole, TIG, etc), so I'm keen to have a proper firewall setup.

If you're open to this in the future, ping the ticket and I'm happy to get the PR back up with any changes needed.

**Comment by mikebrady** [comment]
That’s great — many thanks!
