### ISSUE TITLE
No Audio (specifically YouTube)

### ISSUE THREAD

**Issue by SmelliotButton** [mikebrady/shairport-sync#1436]
I have installed Shairport-Sync on a Raspberry Pi. The sound works and I can play Music through the device using Raspotify, but upon setting up and attempting to use Shairport-Sync, I receive an error of "Something went wrong. Tap to retry" in the YouTube app on my iPhone - running iOS 15. 

I can connect to the device seemingly without any problems. 

I have attached a log file, taken using the "shairport-sync -vu --statistics"

My "/etc/shairport-sync.conf" looks like the below:

general = {
  name = "RPi-AirPlay";
}

sessioncontrol = {
  session_timeout = 20;
}
alsa = {
    output_device = "hw:Headphones";
    mixer_control_name = "Headphone";
};

Could I have some assistance, please?

[Shairport-SyncLog.txt](https://github.com/mikebrady/shairport-sync/files/8101142/Shairport-SyncLog.txt)

**Comment by mikebrady** [comment]
Thanks for the post. This seems to be a UI bug in YouTube. The AirPlay icon in the app is for video AirPlay only but it includes audio-only AirPlay devices like Shairport Sync. To play audio only to AirPlay, you should select the audio output device using the settings in the iOS Control Center.

**Comment by SmelliotButton** [comment]
Thanks for the response. I have tried it that way and tried to play something but I still don't get any sound. 

I assume it's something to do with the "mixer_control_name"? I have ran "shairport-sync -h" and get the below:

**Available mDNS backends:
    avahi
Available audio backends:
    alsa (default)
hardware output devices:
    "hw:b1"
    "hw:Device"
    "hw:Headphones"**

As per my Raspotify config, "hw:Headphones" is in use, so I think this is the correct device to use as the "output_device". How do I go about finding the correct mixer to use? I have also tried changing it from "Headphone" to "alsa" and restarted the service, but this hasn't made any difference.

Sorry if this is a simple thing! I'm new to the whole audio setup thing. Have tried to do my own research but feel a bit stuck! 

Thanks in advance!

**Comment by mikebrady** [comment]
Thanks. There is a separate app for exploring `alsa` devices that might  suit Shairport Sync -- see [sps-alsa-explore](https://github.com/mikebrady/sps-alsa-explore) -- which will list the possible `mixer_control_name` values.

One other thing is to ensure that the output device isn't muted -- see #1432.

**Comment by SmelliotButton** [comment]
I didn't see sps-alsa-explore existed, apologies!
I have ran it and it mentions "Device" as "hw:Headphones" and "Possible mixers" as "Headphone" so it seems set correctly in the config to me! 

As mentioned in the issue thread you linked, I can use "speaker-test" and hear audio. My Raspotify setup also uses "hw:Headphones" as the output device, so I know the sound itself works.
I have ran "sudo iptables -L -nv" which confirms that the Firewall on the Raspberry Pi is disabled. 

Any other ideas? Thanks for your help so far.

**Comment by mikebrady** [comment]
Thanks. It might be worth just walking through #1432 step by step (maybe you have done so already?), especially the diagnostics and checking the mute situation.

**Comment by SmelliotButton** [comment]
I have had a look through and there is lots of mentions of the statistics. I'm unable to see any settings for statistics in the config file:
![image](https://user-images.githubusercontent.com/94921276/155018941-702d5ed3-6a2c-4cd1-bdad-049e9408b7a1.png)

https://github.com/mikebrady/shairport-sync/issues/1432#issuecomment-1041176046


This is the output from `alsamixer` which shows no "MM" so doesn't look like it is muted?
![image](https://user-images.githubusercontent.com/94921276/155027526-4fd4695d-3103-4c27-ae70-fd58fbd8f82e.png)

**Comment by mikebrady** [comment]
Thanks.

The alsamixer display is of a PulseAudio device, not for the Headphones. 

The standard sample configuration file will have all possible settings. It should have been installed at `/etc/shairport-sync.conf.sample`. The `log_verbosity` and `statistics` settings are in the `diagnostics` section.

As a matter of interest, why is there a `session_timeout` setting?
