### ISSUE TITLE
Long waiting for connections

### ISSUE THREAD

**Issue by microfx** [mikebrady/shairport-sync#1438]
Hey!

Sadly now I have the problem that it takes very long ...up to 25 seconds to connect from different sources. Any idea how I could improve that? 

Sometimes I see this in the logs:

```
warning: The range requested is too large to accommodate -- ignored.
shairport-sync[26958]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
shairport-sync[26958]:                                  Dload  Upload   Total   Spent    Left  Speed
shairport-sync[26958]: [158B blob data]
```

**Comment by mikebrady** [comment]
Thanks.

The first line is a warning about the range of attenuation available on the mixer. Could you run [sps-alsa-explore]() and post the results here please?

The remaining three lines don't actually originate in Shairport Sync, so it's a mystery as to how they are being attributed to it. Are you running Shairport Sync into a PulseAudio device, by any chance?

**Comment by microfx** [comment]
```
 Device:              "hw:Loopback"
  Short Name:          "hw:0"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "PCM"                 Range:  51.00 dB
  The following rate and format will be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE

> Device:              "hw:CARD=Loopback,DEV=1"
  Short Name:          "hw:0,1"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "PCM"                 Range:  51.00 dB
  The following rate and format will be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE
```
Hmm... I have recently installed RetroPie (an emulation app) which installed a bunch of stuff – but I uninstalled PulseAudio right away because it was breaking my whole setup. Maybe it's some debris from that?  

Maybe it's a good time to switch to jack backend.

**Comment by mikebrady** [comment]
Thanks. Those loopback devices — is that what you intend to have there?

I was only guessing that those messages might come from PulseAudio. I suppose another possibility is that they come from the loopback devices. 

Not sure what advantage there would be to switch ing to `jack` at this point.

**Comment by microfx** [comment]
to be honest ... I once tried to use loopback for something I don't even remember. And it didn't work out ... so that's a relict. I think I don't actually have ever used the loopback device. But removing it was more prone to break anything than to leave it as it is. 

I guess I should remove it and see if that fixes it. :)

**Comment by microfx** [comment]
I remember now why I wanted to switch to jack .. because it would be as exhausting as getting this right.

It's all broken now. 

```
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
default
airplay
sysdefault:CARD=pisound
    pisound, 
    Default Audio Device
dmix:CARD=pisound,DEV=0
    pisound, 
    Direct sample mixing device
dsnoop:CARD=pisound,DEV=0
    pisound, 
    Direct sample snooping device
hw:CARD=pisound,DEV=0
    pisound, 
    Direct hardware device without any conversions
plughw:CARD=pisound,DEV=0
    pisound, 
    Hardware device with all software conversions
usbstream:CARD=pisound
    pisound
    USB Stream Output
```
```
/sps-alsa-explore 
> Device:              "hw:pisound"
  Short Name:          "hw:0"
  This device is already in use and can not be checked.
  To check it, take it out of use and try again.
```

```
cat .asoundrc
pcm.!default
{
  type plug
  slave sl1
}

ctl.!default
{
  type hw
  card 0
}

pcm_slave.sl1
{
  pcm "hw:0,0"
  format S16_LE
  channels 2
  rate 48000
}

pcm_slave.pisound
{
    pcm "hw:0,0"
    rate 48000
}

pcm.airplay {
    type rate
    slave pisound
}
ctl.!default
{
  type hw
  card 0
}
```

```
ALSA lib pcm_direct.c:1824:(_snd_pcm_direct_get_slave_ipc_offset) Invalid value for card
fatal error: the alsa output_device "default" can not be found.
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
[158B blob data]
```

```
alsa =
{
//      output_device = "!default"; // the name of the alsa output device. Use "shairport-sync -h" to discover the names of ALSA hardware devices. Use "als$
//      mixer_control_name = "pcm.airplay"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
//      mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.

```

I am unsure what to put into output_device ... should I use the other settings as well? I tried a bunch of combination but it never sits right ... 

My dream configuration was always to use jack (since I use my sound card also for making music / routing the inputs in jack audio to use the realtime kernel. But I don't understand the documentation of neither jack nor shairport for the implementation.

**Comment by microfx** [comment]
I fixed it ... there was some crap in the /boot/config.txt – I commented out a few things and enabled others...

dtparam=audio=on
# dtoverlay=vc4-fkms-v3d

I think it was one of these
