### ISSUE TITLE
Jack audio guide? build command --with-jack not working and guidance for setup

### ISSUE THREAD

**Issue by microfx** [mikebrady/shairport-sync#1439]
Hey!

I'm really trying to figure this jack audio backend thing out. But I'm already struggling with the first step. 

this is what I build ... it seems my build command doesn't include jack

```
software version: "4.1-dev-194-gb622c179-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc"
*fatal error: Invalid audio backend "jack" selected!
emergency exit
```
```
./configure --sysconfdir=/etc --with-alsa     --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-dbus-interface --with-airplay-2 —-with-jack

checking for —with-jack-g++... no
checking for —with-jack-c++... no
checking for —with-jack-gpp... no
checking for —with-jack-aCC... no
checking for —with-jack-CC... no
checking for —with-jack-cxx... no
checking for —with-jack-cc++... no
checking for —with-jack-cl.exe... no
checking for —with-jack-FCC... no
checking for —with-jack-KCC... no
checking for —with-jack-RCC... no
checking for —with-jack-xlC_r... no
checking for —with-jack-xlC... no
```

**Comment by mikebrady** [comment]
I really don't know where those messages are coming from. BTW, it looks like the `with-jack` flag has an incorrect dash -- a long dash -- in front of it...

On my system, this is what happens:
```
...
checking for avahi_client_new in -lavahi-client... yes
checking for avahi_strerror in -lavahi-common... yes
checking for alsa... yes
checking for jack... no
configure: error: Jack Audio Connection Kit support requires the jack library -- libjack-dev suggested!
```

**Comment by microfx** [comment]
Hey @mikebrady 

You were so right ... a weird dash was the problem. Arghs!

now it's almost! running ... I remembered jack is also running in its own realtime audio environment – changed the shairport-sync service file as well. But now I am at the problem that my DAC is 48 kHz and shairport 44,1kHz.

```
"shairport.c:1348" default metadata_pipename is "/tmp/shairport-sync-metadata".
 "shairport.c:1905" Started in Airplay 2 mode with features 0x405fca00,0x1c340 on device "b8:27:eb:bc:85:28"!
"shairport.c:1947" software version: "4.1-dev-194-gb622c179-AirPlay2-OpenSSL-Avahi-jack-soxr-metadata-dbus-sysconfdir:/etc"
"audio_jack.c:272" *fatal error: The JACK server is running at the wrong sample rate (48000) for Shairport Sync. Must be 44100 Hz.
 "shairport.c:1577" emergency exit
shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
shairport-sync.service: Failed with result 'exit-code'.
```

hmm any idea if there's an option to switch make that samplerate conversion happening?

**Comment by mikebrady** [comment]
Thanks for the update. Shairport Sync works at 44100 or exact multiples of it. There is some guidance in the `jack` section of the configuration file -- in particular, you'll need to enable `soxr_resample_quality` for resampling (from 44100 to 48000) to work. Also, you should look through closed issues for examples of use.

**Comment by microfx** [comment]
It works! Never would have believed this! And again only user error. Sorry and thank you so much!

**Comment by mikebrady** [comment]
Fantastic! Well done for your persistence!

**Comment by microfx** [comment]
> Fantastic! Well done for your persistence!

thanks! I could need your opinion on two issues 

first: 

I just saw I have a dbus issue 

```
shairport-sync[542]: warning: could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i542" on the system bus. 
```

my dbus conf looks like this (I added jack to the list since that's the user running shairport

```
cat /etc/dbus-1/system.d/shairport-sync-dbus.conf

!-- initial version, based on /etc/dbus-1/system.d/avahi-dbus.conf, with th$<!DOCTYPE busconfig PUBLIC
"-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

<!-- Allow users "root" and "shairport-sync" to own the Shairport Sync ser$<policy user="root">
<allow own="org.gnome.ShairportSync"/>
</policy>
<policy user="shairport-sync">
<allow own="org.gnome.ShairportSync"/>
</policy>
<policy user="jack">
<allow own="org.gnome.ShairportSync"/>
</policy>

Sync server -->
<policy context="default">
<allow send_destination="org.gnome.ShairportSync"/>
<allow receive_sender="org.gnome.ShairportSync"/>
</policy>

</busconfig>
```

but still the same.

And the other question is: Using ATV / more
than one device with SPS it won't really work. I was reading that about multiple instances. That will work good with jack? Do you have experience? Will try that tomorrow or later.

Almost perfect setup! Thank you so much!

**Comment by mikebrady** [comment]
Apologies, I missed this.

> I could need your opinion on two issues
> 
> first:
> 
> I just saw I have a dbus issue
> 
> ```
> shairport-sync[542]: warning: could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i542" on the system bus. 
> ```
> 
> my dbus conf looks like this (I added jack to the list since that's the user running shairport
> 
> ```
> cat /etc/dbus-1/system.d/shairport-sync-dbus.conf      ����������������─╯
> 
> <!DOCTYPE busconfig PUBLIC
>           "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
>           "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
> <busconfig>
> 
>   
>   <policy user="root">
>     <allow own="org.gnome.ShairportSync"/>
>   </policy>
>   <policy user="shairport-sync">
>     <allow own="org.gnome.ShairportSync"/>
>   </policy>
>   <policy user="jack">
>     <allow own="org.gnome.ShairportSync"/>
>   </policy>
> 
> Sync server -->
>   <policy context="default">
>     <allow send_destination="org.gnome.ShairportSync"/>
>     <allow receive_sender="org.gnome.ShairportSync"/>
>   </policy>
> 
> </busconfig>
> ```
> 
> rebooted ...but still the same.

Did you solve that problem?

>  And the other question is: Using ATV / more than one device with SPS it won't really work. I was reading that about multiple instances. That will work good with jack? Do you have experience? Will try that tomorrow or later.

Multiple AirPlay2 output devices from ATV should work, yeah, including SPS devices running AirPlay 2 with Jack Audio backends.
