### ISSUE TITLE
Airplay 2 -- run_this_before_entering_active_state sometimes gets run twice

### ISSUE THREAD

**Issue by ben-willmore** [mikebrady/shairport-sync#1440]
During repeated tests for #1430, I noticed that, with Airplay 2 only, my `run_this_before_entering_active_state` script sometimes gets run twice, even though playback is only initiated once:

```
ben@pi-dining:~ $ ./shairport-sync-airplay2/shairport-sync -c ./precision-timing-off.conf
Switching on socket 1
^Cben@pi-dining:~ $ ./shairport-sync-airplay2/shairport-sync -c ./precision-timing-off.conf
Switching on socket 1
^Cben@pi-dining:~ $ ./shairport-sync-airplay2/shairport-sync -c ./precision-timing-off.conf
Switching on socket 1
Switching on socket 1
```

(The `Switching on socket 1` message is produced by my script.)

**Comment by mikebrady** [comment]
Thanks Ben. I’ll try to reproduce it!

**Comment by mikebrady** [comment]
Hi Ben. Just wondering: did you have a hook on the `run_this_after_exiting_active_state` state as well? What I'm wondering is if the system incorrectly determined that the play went inactive and then active again...

**Comment by mikebrady** [comment]
Hi Ben. I got this to happen today, so I'll pursue it. I can't reproduce it though 😕.

**Comment by mikebrady** [comment]
Just FYI, a fix has been pushed into the `development` branch. Thanks again for the report.

**Comment by ben-willmore** [comment]
I've tested this ~10 times on the machine that previously showed the duplication, and the fix seems good to me. Thanks for looking into it!
