### ISSUE TITLE
Cannot add to homeassistant

### ISSUE THREAD

**Issue by hasspi88** [mikebrady/shairport-sync#1445]
My phone can be added to the homekit, but if you select the homekit controller in homeassistant, it cannot be added because it has no pairing code.

**Comment by mikebrady** [comment]
Thanks for the post, but it's not clear if it has anything to do with Shairport Sync.

**Comment by hasspi88** [comment]
他不支持配置到homeassistant？

**Comment by hasspi88** [comment]
> 感谢您的帖子，但尚不清楚它是否与 Shairport Sync 有关。
他不支持配置到homeassistant？

**Comment by mikebrady** [comment]
Does [this](https://github.com/mikebrady/shairport-sync/blob/development/ADDINGTOHOME.md) help?
