### ISSUE TITLE
`Provides=` not a valid directive in systemd.unit

### ISSUE THREAD

**Issue by idcrook** [mikebrady/shairport-sync#1448]
In https://github.com/mikebrady/shairport-sync/commit/0aea8107355e756294054fdbc59a9bab4c57f32d in [scripts/shairport-sync.service.in](https://github.com/mikebrady/shairport-sync/issues/new#diff-da0b2bc8d5a56525256a9a0519077685af02019716a8ceb5754e2281021cc369)

Seems `Provides=` is not valid in systemd `.service`.

 I think it may be implicit in service name, if tha tis what this was going for?

```
sudo journalctl -u shairport-sync
[...]
Mar 10 12:10:33 rpif2 systemd[1]: /lib/systemd/system/shairport-sync.service:3: Unknown key name 'Provides' in section 'Unit', ignoring.
Mar 10 12:10:47 rpif2 systemd[1]: /lib/systemd/system/shairport-sync.service:3: Unknown key name 'Provides' in section 'Unit', ignoring.
Mar 10 12:10:51 rpif2 systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

on `systemd` 247 (RasPi OS - bullseye) , but the latest release 250 has no changes here.

See here for valid Unit directives: <https://www.freedesktop.org/software/systemd/man/systemd.directives.html>
and <https://www.freedesktop.org/software/systemd/man/systemd.unit.html>

**Comment by mikebrady** [comment]
Thanks for the information. TBH I don't know where I got the idea from 😳. I'll fix it in the next few days.

**Comment by mikebrady** [comment]
I think I have fixed this in the latest push to the `development` branch. Thanks for reporting!
