### ISSUE TITLE
libpopt needed

### ISSUE THREAD

**Issue by petcol** [mikebrady/shairport-sync#1449]
Hi, this has been working just fine, I've had to rebuild the Pi 4 and when I went back in this error came up
$ sudo ./configure --sysconfdir=/etc --with-alsa     --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2
---------
checking for popt... no
configure: error: libpopt needed

Any suggestions ?
Col

**Comment by math-gout** [comment]
Take a look at BUILDFORAP2.md, you have to install ```libpopt-dev```

**Comment by petcol** [comment]
Thank you for I've worked through what was missing not sure why they were not there this time, but all looks good now.

**Comment by mikebrady** [comment]
Okay to close this now?

**Comment by petcol** [comment]
Thanks sorry for delay please close 

Sent from my iPhone use 

***@***.***

for reply 
Thank you
