### ISSUE TITLE
playback delay

### ISSUE THREAD

**Issue by brbrr** [mikebrady/shairport-sync#145]
I have some response delay between sound source playback and sound system. i.e. play/pause on youtube view. its about ~1sec delay

I'm using rasp-pi B+ as server, and mac os as client. same WI-FI network.

**Comment by mikebrady** [comment]
Thanks for your mail. The delay is two seconds and it's built on to the protocol. In recent versions of the Mac, YouTube video is delayed by the same amount to sync the sound and video.

**Comment by brbrr** [comment]
I see, thanks for explanations.
