### ISSUE TITLE
Multiple shairport instances with AP2

### ISSUE THREAD

**Issue by ndubss** [mikebrady/shairport-sync#1452]
Hi Mike and team,

Thank you all for spending so much time on this project. Need some help with a mildly complex use case. Just need some direction if this is possible right now, otherwise, I guess I will stick with AP1. 

This is on a rpi 4B. 

Have tried two setups:
1. 4 systemd services setup to individual alsa syncs. This uses the octo rpi card. Mdns works fine with AP1 and I can’t remember if I tried multiple streams. AP2 looks to be advertising with the same ipv6 and one Bonjour device overwrites the other. Output seems to work fine but can’t test multiroom. 

2. Have setup 4 docker compose instances with guidance from another user. Thank you! In this case, docker is using ipv4 for mdns, and everything advertises correctly. The issue now is that only one container is able to bind to alsa successfully. The others get resource busy. I have also tried mapping pulse to the alsa sinks but that doesn’t seem to work either. 

Solutions:
1. Do I need separate usb sound cards instead of one multi output DAC?
2. Is there an easy way to fix the systemd ipv6 issue?
3. Should pulse be able to mitigate the resource busy docker error? Trying to output to multiple sinks at same time on one card.

**Comment by mikebrady** [comment]
Thanks for the post. First off, @noelhibbard has done a lot of work on multiple instances of SPS/AP2. Let me suggest that you search for their username among the open and closed issues.

AP1 players ("clients") don't seem to have any difficulties with having multiple instances of SPS/AP1 at the same IP addresses, but -- as you have discovered -- AP2 clients get confused by it. There doesn't appear to be any obvious fix other than using virtualisation of some kind, which brings up the `alsa` device access problem in Docker. TBH, I have not really explored this problem, but @noelhibbard's approach is to use pulseaudio backends to sidestep the problem.

**Comment by noelhibbard** [comment]
@ndubss , I am personally using individual USB cards for each container. I do have a 7.1 channel USB sound card that I could do some tests with to see if I can work that out. I'm assuming you have several dmix outputs in ALSA that are bound to specific channels and then have Pulse sinks bound to these ALSA outputs?

I'm super busy today but I'll do my best to find some time to play with my multichannel USB card to see if I have better luck.

**Comment by ndubss** [comment]
Thanks @mikebrady and @noelhibbard! Yes I have 4 dmix outputs to one card. It dawned on me yesterday that I was using an old config that didn’t have “server” under pa section. Once I pointed that to the systemd pulse, I noticed that pulse.service was failing to recognize the alsa device names I put in. 

Got frustrated trying to get pacmd to list sinks, since it’s running in system mode. That’s where I’m at right now. Thanks for any help you can give @noelhibbard

**Comment by noelhibbard** [comment]
@ndubss , for whatever reason pacmd doesn't work in my containers. pactl works perfect though. I lost a lot of hair trying to figure out what was wrong with PA in my containers before realizing pacmd was the issue.

**Comment by ndubss** [comment]
Okay thanks. Pactl works inside the container and shows the multichannel card. I’m guessing I need to map pulse to channels like hw:0,1 instead of using the friendly names I setup in alsa. Alsa allowed me to map multiple single channels to one alias. I don’t think pulse will respect the alias

This is looking more and more like I should just get individual usb cards.

**Comment by ndubss** [comment]
@noelhibbard thanks for all the help. It doesn't seem to be respecting the alias in my case. Here is the entry in the system.pa and my alsa config. This is the same alias that I use in the alsa section of shairport, with no issues.

`load-module module-alsa-sink device=bath sink-name=bath
load-module module-alsa-sink device=guest sink-name=guest`

`pcm.bath {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.1.5 1
}
`

`Mar 27 22:03:22 core pulseaudio[8334]: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
Mar 27 22:03:22 core pulseaudio[8334]: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ 
Mar 27 22:03:22 core pulseaudio[8334]: Failed to parse module arguments
Mar 27 22:03:22 core pulseaudio[8334]: Failed to load module "module-alsa-sink" (argument: "device=bath sink-name=bath"): initialization failed.
Mar 27 22:03:22 core pulseaudio[8334]: Failed to parse module arguments
Mar 27 22:03:22 core pulseaudio[8334]: Failed to load module "module-alsa-sink" (argument: "device=guest sink-name=guest"): initialization failed.
Mar 27 22:03:22 core systemd[1]: Started PulseAudio system server.
`

**Comment by ndubss** [comment]
@noelhibbard So that got rid of the argument error. Still getting this:
```
Mar 28 11:48:15 core pulseaudio[12774]: Failed to load module "module-alsa-sink" (argument: "device=bath sink_name=bath"): initialization failed.
```

This works successfully to all channels:
```
paplay --verbose --device=alsa_output.platform-soc_sound.multichannel-output test.wav
```

But then this fails: 
```
Mar 28 12:10:10 core pulseaudio[12886]: Failed to load module "module-alsa-sink" (argument: "device=alsa_output.platform-soc_sound.multichannel-output"): initialization failed.
```

**Comment by noelhibbard** [comment]
@ndubss , that one probably fails because it's one of the auto generated sinks and you are trying to add it a second time. I'm not that knowledgeable on Pulse so I'm sort of grasping.

**Comment by noelhibbard** [comment]
@ndubss , I am just getting around to testing with a multichannel USB sound card. So far I can confirm it isn't working in Pulse. I configured ALSA like your example above and it works with aplay/speaker-test but Pulse will not bind to it. In the past I've configured multiple channels a different way in ALSA that you did. I'm going to try that next and see if it makes a difference. I'll report back shortly.

**Comment by noelhibbard** [comment]
@ndubss , Okay I got it to work without even changing my ALSA config. The trick was to comment out ALL lines in system.pa except for this line:
```
load-module module-native-protocol-unix
```

And of course all the sink maps.

So my entire system.pa looks like this now:
```
load-module module-native-protocol-unix
load-module module-alsa-sink device=Livingroom sink_name=Livingroom
load-module module-alsa-sink device=Garage sink_name=Garage
```

```pactl list sinks short``` list only these two sinks now.

Now I'm going to install the docker containers and make sure that part also works.

**Comment by ndubss** [comment]
Thanks @noelhibbard I will give that a try and report back. Was just about to buy separate usb sound cards!

**Comment by noelhibbard** [comment]
On the host I can test my two outputs using pactl play-sample and they come out of the correct channels but for some reason sps in the containers isn't playing to the correct channels. PA also has some channel mapping features. I'm going to give that a shot next.

**Comment by noelhibbard** [comment]
@ndubss , got it!!

```/etc/asound.conf```
```
pcm.USBCard {
    type dmix
    ipc_key 2048
    slave {
        pcm "hw:CARD=ICUSBAUDIO7D,DEV=0"
        period_time 0
        period_size 1024
        buffer_size 8192
        channels 8
    }
    bindings {
        0 0
        1 1
        2 2
        3 3
        4 4
        5 5
        6 6
        7 7
    }
}
```

```/etc/pulse/system.pa```
```
load-module module-native-protocol-unix
load-module module-alsa-sink device=USBCard sink_name=USBCard
load-module module-remap-sink sink_name=Livingroom master=USBCard channels=2 master_channel_map=front-left,front-right channel_map=front-left,front-right remix=no
load-module module-remap-sink sink_name=Garage master=USBCard channels=2 master_channel_map=front-center,lfe channel_map=front-left,front-right remix=no
```

**Comment by ndubss** [comment]
@noelhibbard thank you so much for the help. I started having issues with my rpi and finally bit the bullet and wiped it. Sound card, pulse and containers are working like a champ now. Full AP2 with multiroom. I can finally mount my home audio receiver in the rack! TY!!

I want to up the bitrate and sample. Should I seek to do this in alsa config? 

Also, some of my ceilings are a bit muddy. Want to emphasize the highs/mids a bit more. Any suggestions for EQ in SP or alsa? Maybe @mikebrady has suggestions.

**Comment by noelhibbard** [comment]
@ndubss , AirPlay will not run high sample rates but I believe it can run 24bit. For an EQ you can build SPS with ```--with-convolution```. There are a bunch of tools for making imposs response files which you could use as a very powerful EQ.

**Comment by microfx** [comment]
The best thing I did was switching to jack audio. It's not 100% perfect ... but in the end it works soooo much better. I'm using a Pisound audio interface with inputs ...so I can use librespot, shairport AND audio input (my music devices or whatever you plugin over cable). 

I never fully understood all that pulseaudio / also mix stuff. And I'm happy to not have to! 

Look up my postings here to see how it's done. It's been a huge recelation for me. And now that a lot of projects also offer jack ...I will never go back!

**Comment by noelhibbard** [comment]
@microfx , I run librespot natively on my server via ALSA dmix and use PA for SPS in Docker containers. I can have Spotify and AirPlay coming out of a speaker at the same time if I want. I've been using ALSA for a while so I've gotten fairly good with it. PA was new to me though. I'll have to try out Jack and I've also been tempted to try Pipewire.
