### ISSUE TITLE
service file needs to be adapted for --with-tinysvcmdns

### ISSUE THREAD

**Issue by klslz** [mikebrady/shairport-sync#1454]
If Shairport Sync gets compiled with `--with-tinysvcmdns` instead of `--with-avahi`, the make-installed
`systemd` startup service file still requires the Avahi service to be present.

That makes Shairport Sync fail to start.

I'd suggest that 
1. either a 2nd `systemd` startup service file should get installed or
2. the documentation should be updated 

original:

```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/local/bin/shairport-sync
User=shairport-sync
Group=shairport-sync

[Install]
WantedBy=multi-user.target
```

needs to be

```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/local/bin/shairport-sync
User=shairport-sync
Group=shairport-sync

[Install]
WantedBy=multi-user.target

```
if compiled with `--with-tinysvcmdns` and Avahi not being present.

Thx for the great work btw.

**Comment by mikebrady** [comment]
Thanks for the report. Let's see what can be done about it...

**Comment by mikebrady** [comment]
Thanks again for reporting this issue. An update has been pushed into the `development` branch with should fix this problem. If you got a chance to try it out and report back, it would be appreciated.

**Comment by klslz** [comment]
Thx. Your commit looks awesome. I'll check later on.
