### ISSUE TITLE
shairport failure at boot

### ISSUE THREAD

**Issue by klslz** [mikebrady/shairport-sync#1455]
To me it happens that 

1. the network-online.target is not working reliable 
2. the audio device is not up'n running 

during boot while shairport gets loaded. This makes shairport fail.

The sp-s documentation suggests to introduce a .timer to address these or similar issues. BTDT.

I'd like to make an alternative proposal: 

Introducing a simple systemd safety-belt.

```
[Unit]
Description=shairport-sync

After=sound.target
Wants=network-online.target
After=network.target network-online.target

# StartLimitIntervalSec >  StartLimitBurst * RestartSec
StartLimitIntervalSec=40  
StartLimitBurst=7

[Service]
User=shairport-sync
Group=shairport-sync
ExecStart=/usr/local/bin/shairport-sync

Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

What above example does:
 
Within the first 40 seconds shairport-sync will restart 7 times on failure at 5 seconds intervals.
This gives the network and audio device plenty of time to get settled. The settings
won't do anything if the network and audio is up'n running already.

This IMO makes the boot process bulletproof unless there's a real problem out there.
And this also won't require to play around with .timer files, which usually also would require adapted
.service files.

Note: This solution might cause issues on very outdated systems running systemd <  v230. (RPi OS runs at v247 nowadays)

**Comment by mikebrady** [comment]
Thanks for the suggestion.

At the moment, I am inclined to think that this is a workaround for a problem elsewhere in the system, and therefore I would not really favour it. 

Also, does this occurs if Shairport Sync is set to wait for the Avahi service? The Avahi service is mandatory for AirPlay 2, so maybe this issue only arises (1) for AirPlay 1 and (2) where Avahi is not being used.

It's worth noting also that an alternative to Avahi, `tinysvcmdns`, seems to be no longer maintained.

**Comment by klslz** [comment]
It's a workaround to cope with potential weak spots of shairport. ;)
As I said. To me it's a safety belt and prefered over your suggested .timer  "workaround".
Beside that it won't cause any trouble.
