### ISSUE TITLE
Fails to initialize on DSM 6 Beta

### ISSUE THREAD

**Issue by federaa** [mikebrady/shairport-sync#146]
When one hits run it fails to start on 6 beta on a DS414

**Comment by lost-carrier** [comment]
What is your setup? Streaming from or to the DS?

**Comment by trifle** [comment]
Additional information:
shairport-sync (receiving audio, playing via USB audio interface) installed via community package (https://synocommunity.com/package/shairport-sync) core dumps on DSM 6 Beta (Linux 3.2.40 #7135 SMP armv7l GNU/Linux synology_armada375_ds215j).
This is on a DS 215j (ARMv7).

My naive guess is that the binaries need to be cross-compiled against the new kernel/libraries/?.

**Comment by lost-carrier** [comment]
Thanks for the info. Your guess sounds readonable. Unfortunately I have no beta-DSM around here. Do you have shell access? If yes, can you try to starting it from /var/packages/shairport-sync/target/ as bin/shairport-sync --port=8303 and see what happens?

**Comment by trifle** [comment]
>root@syno:~#  /var/packages/shairport-sync/target/bin/shairport-sync
>Segmentation fault (core dumped)

**Comment by mikebrady** [comment]
Yikes! Could you try `/var/packages/shairport-sync/target/bin/shairport-sync -V` please? Int should return the version umber etc. if it doesn't crash...

**Comment by trifle** [comment]
Sorry, tried that already, but it segfaults as well.

**Comment by mikebrady** [comment]
Thanks -- it sounds like it needs to be rebuild, TBH.

**Comment by trifle** [comment]
I can't help with the cross-compiling but will gladly test any binaries (those are static, right?).

**Comment by lost-carrier** [comment]
I'm afraid we'll have to wait for the synocommunity guys to provide compilation framework for dsm 6.0. Will check with them.

**Comment by mikebrady** [comment]
Agreed, thanks.

**Comment by mikebrady** [comment]
I think I can close this now -- it seems to have been taken care of. Feel free to reopen if not.
