### ISSUE TITLE
WiiM Mini: 48kHz/24 bit supported on AirPlay 2

### ISSUE THREAD

**Issue by CarlBernard** [mikebrady/shairport-sync#1465]
Hi Mike!

Congratulations again for this fabulous software!

To stream Apple Music Lossless, I have been using your software on Raspberry Pi 3 + HiFiBerry DAC2 HD for both Airplay 1 and Airplay 2 for many months now with excellent results using iPhone, iPad, HomePod mini and Apple TV 4K.

While waiting for AP2 to be bit perfect too (fingers crossed :-)), I'm using AP1 and I can get a bit perfect streaming at 16 / 44.1.
To verify that AP1 is bit perfect, I use "stdout" to record the RAW file on RPi3 sent from iOS which I then compare in Audition with the original lossless file by reversing the phase. Audio files in CD quality (16 / 44.1) cancel each other out every time = bit perfect.

I hope that Apple decides in the future to send Apple Music lossless streaming via AP2 as well. This way, I could use my HomePod mini (which I control via iPhone) to stream to AP2 without putting a strain on my phone's battery.

I did some research on the web and on various forums to learn more and I wanted to share some links with you:

- NAIM AUDIO: https://community.naimaudio.com/t/apple-music-hifi-tier-incoming/16445/1062?page=52

On the Naim forum, the technical director confirms that AP2 can even receive up to 32/384.

- ROON: https://community.roonlabs.com/t/apple-music-high-res/159869/1572?page=37

On the Roon forum, a user did a bit-test with his RME DAC sending from iOS to MacOS Monterey and verified that AP2 even receives up to 24/192 in bit-perfect.

- WIIM MINI: https://wiimhome.com/whatsNew.html

On the website of the manufacturer of this streamer, it was announced that from next May 15th the device will support AP2 up to 24/48.

Now, this is my question:

How can the WiiM manufacturer promise that they will be able to receive via AP2 up to 24/48?

Will shairport-sync also be able to receive up to 24/48 with an upcoming update?

Anyway, I knew it is the AirPlay 2 sending device that decides what kind of audio format to send to the receiving AirPlay 2 device.

Example:
REALTIME (lossless 16 / 44.1 as in the case of Qobuz App on iOS)
BUFFERED (lossy 16 / 44.1 as in the case of Apple Music App on iOS)

If it is true that the AP2 protocol can manage a streaming up to 24/192 as confirmed in the various forums and if it is true that WiiM can receive up to 24/48 (I assume in lossless format), what should we expect from Apple?

Will it be possible to send via AP2 with Qobuz up to 24/48?

Is it possible to think that Apple decides to broadcast Apple Music contents up to 24/48 via AP2 in the near future?

Thanks in advance for your reply.

Have a good evening!

**Comment by JanLp** [comment]
Hi ... You are asking some questions I have been thinking about for a long time. Especially around the WIIM MINI and their alleged 24/48 support later in the year. I hope Mike can answer some of that.

**Comment by CarlBernard** [comment]
Hi JanLp,

I received an email response from WiiM support which I report below:

  - - - - - - - - - - - - -

[CarlBernard]
I read on your site that from May 15th Wiim Mini will be able to receive up to 24/48 streaming via Airplay 2.
Does it mean that through Qobuz I can send to AirPlay 2 up to 24/48 in lossless format?
Will it also be possible via the Apple Music app?

[WiiM]
Correct, after we support up to 24/48 streaming via AirPlay 2, you can use Qobuz and Apple Music to stream up to 24/48 streaming to WiiM Mini with AirPlay 2.

[CarlBernard]
if I understand correctly, will I be able to use the Apple Music App (NO Wiim App) on my iPhone and select WiiM as the AirPlay 2 device to transmit lossless up to 24/48?

- - - - - - - - - - - - - -

As soon as support confirms that it's possible via the Apple Music App (**and not via the WiiM App, hopefully**), I'll update you.

**Comment by mikebrady** [comment]
Hi @CarlBernard and @JanLp, and thanks for the kind words and the interesting links.

I have no doubt that AirPlay 2 has the technical capability to deal with almost any lossless format. We are told that the HomePod mini does lossless, although I think it would be hard to tell on an audio device of that quality. So I'd really expect that manufacturers would be able, with Apple support, to provide facilities such as 24/48k etc. On a slightly historical note, even AirPlay 1 appears to have, in principle, the ability to do lossless ALAC as different bit depths, e.g. 24 or 32, at different sample rates, and with different numbers of channels. However, it seems that Apple never provided a public implementation. I am sure they had good reasons. 

Apple hasn't, to my knowledge, released details of AirPlay protocols, so we have to try to deduce them, and that's the real challenge. The issues before us here are really related to how the protocols work to enable a player like Music on macOS to [perhaps -- I'm guessing here] determine the capabilities of of an AirPlay 2 endpoint, how they agree on a format, and how that is all arranged and communicated. 

TBH, I think, by and large, Apple are doing a really good job on their audio infrastructure, glitches notwithstanding. When I figure out something new about AP2 (or AP1), I am often struck by how "right" it is and how well it seems to been thought out.

**Comment by CarlBernard** [comment]
Thanks for the reply @mikebrady

I have not received a response from WiiM support but I found an interesting discussion on Audio Science Review:

https://www.audiosciencereview.com/forum/index.php?threads/wiim-mini-review-streamer.33099/page-24

Report what a user wrote:

"Yeah, you start playing the song in Apple Music. The Wiim is selected as the target. Then you open the Wiim app. Irrespective of if the song is playing or paused, inside the Wiim App you will see the same track playing with cover art and controls.
Hitting play from within the Wiim app sounds WAY better. But you have to cue up the song via Apple Music first. "

Still reading the forum, I understand that WiiM uses LinkPlay to stream to AP2 as well.

This is my guess:

- Apple Music App on iOS receives lossless streaming from Apple servers
- Before iOS encodes in AAC to send via AP2, the WiiM application in iOS "captures" the streaming from the Apple Music App and sends it to the WiiM mini device (also in 24/48 format from May 15th ...).

If there is any news, I will update you.

**Comment by CarlBernard** [comment]
The only update is that WiiM Mini has not done what it promised and is waiting to receive a response from Apple regarding streaming in lossless format up to 48/24 from Music App.

I think that if the problem of sending music in lossless format via AirPlay 2 is due to the possibility that the average user may experience signal losses or interruptions due to high traffic in his local network when sending to multiple devices simultaneously then the the only easy solution for Apple would be to provide an option in Apple Music in order to make the user decide whether to disable multiroom for AirPlay 2 and therefore be able to send in lossless format to a single device at a time.

If Apple added this simple option, we could have AirPlay 2 bitperfect and, at the same time, Apple could avoid too many calls for assistance for problems related to the functioning of AirPlay and make happy all customers who still cannot send Apple Music Lossless via AirPlay 2 to the HiFi system.

**Comment by SirHomeALotToo** [comment]
> Hi JanLp,
> 
> I received an email response from WiiM support which I report below:
> 
> [CarlBernard] I read on your site that from May 15th Wiim Mini will be able to receive up to 24/48 streaming via Airplay 2. Does it mean that through Qobuz I can send to AirPlay 2 up to 24/48 in lossless format? Will it also be possible via the Apple Music app?
> 
> [WiiM] Correct, after we support up to 24/48 streaming via AirPlay 2, you can use Qobuz and Apple Music to stream up to 24/48 streaming to WiiM Mini with AirPlay 2.
> 
> [CarlBernard] if I understand correctly, will I be able to use the Apple Music App (NO Wiim App) on my iPhone and select WiiM as the AirPlay 2 device to transmit lossless up to 24/48?
> 
> As soon as support confirms that it's possible via the Apple Music App (**and not via the WiiM App, hopefully**), I'll update you.

AirPlay does not support anything higher than lossless 16-bit/44.1 at this time: https://faq-mini.wiimhome.com/support/solutions/articles/72000536679-does-airplay-2-stream-lossless-24-192-
https://www.digitaltrends.com/home-theater/apple-homepod-24-bit-lossless-audio-airplay-2/
