### ISSUE TITLE
HomePod + AP2 - Remote Connection Loss

### ISSUE THREAD

**Issue by CarlBernard** [mikebrady/shairport-sync#1467]
Hi @mikebrady,

I have a problem with HomePod mini and SPS with Airplay 2.
I didn't have this problem before and it only occurred two weeks ago.
Yesterday, I also updated SPS and NQPTP following the guide but the problem persists (I attach commands).

[Guida Installazione SPS - AP2.xlsx](https://github.com/mikebrady/shairport-sync/files/8599193/Guida.Installazione.SPS.-.AP2.xlsx)

In my LAN, there are the following devices:

Apple TV 4K
HomePod mini
iPhone 12
iPhone 7
iPad Pro
AP2: RPi3 + Raspberry Pi OS Lite + SPS AP2 + HiFiBerry DAC2 HD
Samsung TV with AirPlay 2
MacBook Air 2016 (always off)

If I'm using iPhone, iPad, or APTV to stream Apple Music to AP2 there's no problem.
If I use HomePod to stream to AP2, there are problems.

These are the steps.

- I open control center on iPhone (Control other speakers and TV) to control HomePod

- I select AP2 as HomePod audio output (Anomaly: HomePod and AP2 are grouped (HomePod + AP2 instead of HomePod -> AP2)

- I select HomePod in the AirPlay device list so that AP2 is the only HomePod audio output (Anomaly: after this step in the list of devices in the control center it no longer appears as an AP2 selected audio output but rather iPhone even if the audio streaming comes from HomePod and is received correctly by AP2. To make sure HomePod is streaming, I close the Music app on iPhone).

- I close Music app and reopen it on iPhone

Although there are the anomalies I have described, I can check the streaming without problems as I have always done but if I close and reopen the app the problems begin.

The problem is that after this step if I close and reopen Music app on iPhone or if I select AP2 as audio output I can no longer control the streaming because the information of the playing track no longer appears on the app and it is no longer possible to control the player (stop, forward, backward etc etc etc). Also, after this step, AP2 turns out to be in the control center as a device that can be controlled remotely (as happens with APTV and HomePod, see photo).

![8AA4BD11-9A02-4736-A1FD-A117EC536A11](https://user-images.githubusercontent.com/85563569/166152497-92f1482d-5e88-4621-ad09-8030a617571a.png)

To stop streaming and remotely control HomePod again, I need to restart SPS.

I attach the log with the steps taken.

[Text_HP->AP2.txt](https://github.com/mikebrady/shairport-sync/files/8599204/Text_HP-.AP2.txt)

**Comment by mikebrady** [comment]
Thanks for the post. I think this is actually a new feature of the HomePod mini and the way Apple are arranging AirPlay 2. 

From my own experiments, I know that the HomePod mini can play a stream on its own speaker and, at the same time, _play a completely separate stream_ to an AirPlay 2 speaker. If the speaker is an accessory in the Home app, it can then be controlled from the iOS Home ("Casa?") app.

I think this behaviour is new with the most recent updates of the HomePod mini software and also with iOS. It's a nice new feature, but it is a bit confusing as it stands -- maybe Apple have future plans for it.

**Comment by CarlBernard** [comment]
I upgraded iOS to 15.4.1 and now everything works fine.

Thank you for your reply.

After the update, AP2 is now on the list of devices that can be controlled remotely. The difference is that HomePod and ATV receive directly from Apple servers, AP2 only receives from HomePod or Apple TV (I tried turning off Home Pod and after about twenty seconds streaming to AP2 is finished).

I also noticed that with the latest update, even without a family subscription, you can receive any content simultaneously through Apple Music on every device in your home. Before the update it was not possible.

![6CC98A8A-836C-4C4C-92CF-1A3BEE4E4D05](https://user-images.githubusercontent.com/85563569/166160825-0e1b9e60-6a5e-4ffe-998d-cb55603c4057.png)
