### ISSUE TITLE
 spotify sound stutter Error 101 using send-to to the timing socket: "Network is unreachable"

### ISSUE THREAD

**Issue by ddgg** [mikebrady/shairport-sync#1468]
pi4 with archlinuxarm and 3.3.9
when play spotify to shariport-sync, sound paused and resumed after about 1 seconds, it happens every 10 minutes or so
log set to 1 show 
 315.011092433 "rtp.c:506" Error 101 using send-to to the timing socket: "Network is unreachable"
what might cause this?

**Comment by mikebrady** [comment]
Thanks for the post. That does seem like an occasional network problem. It might be worth checking out the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page.

**Comment by ddgg** [comment]
my pi4 is behind a bridged wifi access point, I add a switch before ap and connect pi4 directly to switch and problem is gone, thank you very much for the help
