### ISSUE TITLE
“Control Other Speakers and TVs” Button doesn’t work

### ISSUE THREAD

**Issue by aaidenmel** [mikebrady/shairport-sync#1469]
Hi Everyone,

I don’t know if anyone else is experiencing this, but in the AirPlay 2 version when I go onto an iOS device different than the one that I am casting media from, and go into the control center, long press the media controls, press the “Control other speakers and TVs” button, my Shairport-Sync recover pops up, says “Connecting” for a few seconds, then disappears. I don’t know if this is something that I have configured wrong or the program does not yet support this feature. I have added the speaker to my Apple Home app. If this is not yet supported, I completely understand, I am still very grateful to all of the devs of this program. 

Expected behaviour: I can view what media is playing on my Shairport-Sync receiver from another iOS device

Actual behaviour: The Shairport-Sync recover shows up on the list, says “Connecting” then disappears

Thanks in advance,
Aaiden

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, as you guessed, this is not supported. The reason is that the underlying protocols for this functionality are not known -- Apple has not released details, so this stuff has to be reverse engineered.

**Comment by aaidenmel** [comment]
Thanks for the quick reply, that’s too bad that Apple doesn’t release the protocols for this. (Maybe they will in the future 🤞) Despite this, Shairport-Sync is still a great app, especially with the AipPlay 2 functionality. Thank you so much @mikebrady for developing it!
