### ISSUE TITLE
Doesn't work on Ubuntu

### ISSUE THREAD

**Issue by benjistokman** [mikebrady/shairport-sync#1471]
The server installs (via apt on 22.04) correctly and works perfectly. I am able to connect via my phone, but no audio comes out of my speakers. I think this is due to Ubuntu running pulse at the user level?

Here's my config:

```
// General Settings
general = {
	name = "%h";
	password = "********";
	
	interpolation = "soxr";
	playback_mode = "stereo";
	ignore_volume_control = "no";

alsa = {
	output_device = "hw:Generic";
	mixer_control_name = "PCM";
};
```

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest you comment out the output_device and mixer_control_name setting and restart Shairport Sync. It will output to the default device, whatever that happens to be. Check the volume control is reasonably high using, say, `alsamixer`.

You could also use the command line tool [sps-alsa-explore](https://github.com/mikebrady/sps-alsa-explore) to see what devices are present that could be used by Shairport Sync.
