### ISSUE TITLE
Mono OMG no Shareport-Sync development

### ISSUE THREAD

**Issue by petcol** [mikebrady/shairport-sync#1473]
Hi.

I have run up another Raspberry Pi 4 to use on an external speaker. The speaker takes an analogue Stereo input, and that's what I've plugged into the Pi Headphone socket.

But it sounds to me like one side is slightly louder than the other so L is louder the R. I've yet to check with a set of headphones but....

I did check via ssh to the Pi.
```
~ $ alsamixer
```
brings up a graphic interpretation of the alsa mixer and only shows one vertical VU meter bar. 
That to me would indicate Mono.
When I run:
```
~ $ amixer
Simple mixer control 'Headphone',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -1823 [79%] [-18.23dB] [on]
```
When I check the config for Shairport-Sync:
```
output_device = "hw:Headphones";
mixer_control_name = "Headphone";  // commented out either way no different.
```
I did also try uncommenting:
```
playback_mode = "stereo";
```
and restarting Shairport Sync, but no change?

One of the other units which is connected to a similar but different brand amp speaker shows similar results.

The one I have connected to a stereo amp shows the following:

```
:~ $ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [on]
  Front Right: Playback 65536 [100%] [on]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 65536
  Front Left: Capture 65536 [100%] [on]
  Front Right: Capture 65536 [100%] [on]v
```
It has developed another issue so i'm about to rebuild it keeps loosing the network...  But, put this here as an example.

Any thoughts?
Col

**Comment by mikebrady** [comment]
Thanks for the post, which I edited slightly for layout (I hope that's okay!).

This apparent imbalance between the channels is not something that has been reported here before.

The built-in DAC on the Pi is definitely capable of stereo output, but the mixer apply equally to both channels. I'm afraid I don't know why it registers as `Mono` in `amixer`, but when used by Shairport Sync ("SPS") the device definitely works in stereo. 

Commenting out the `mixer_control_name` would mean that SPS would no longer use it to set the volume; instead, it would use its internal software-based mixer for volume control. However, the `"Headphone"` mixer (no longer under the control of SPS) would determine overall volume.

The `playback_mode` is `"stereo"` by default, so if the mode hade been set to stereo, then commenting it out would make no difference -- it would be stereo. You could try setting the mode to `reverse stereo` (i.e. L → R and R → L) to see if the imbalance changed sides...
