### ISSUE TITLE
No output on Ubuntu

### ISSUE THREAD

**Issue by commodapse0q** [mikebrady/shairport-sync#1475]
I've been trying to get shairport-sync to work on a VM running Ubuntu with no luck.

I've done a fresh install of Ubuntu, run the install command for the shairport-sync package, can see the Airplay speaker on the network, however when I connect to the speaker and start playing, there is no output. The levels in audio settings stay completely flat the entire time regardless of level set.

Please advise on what exactly I need to do to diagnose the issue, I am new to working with audio in Ubuntu, thank you for any help!

Running 20.04 LTS

**Comment by mikebrady** [comment]
Thanks for the post. I routinely use Shairport Sync in Ubuntu 20.04 LTS in VMware on a Mac, so it is definitely possible.

Can you say what host machine and what VM software you are running please (e.g. Mac/VMware, Parallels)? Can you be sure audio from the VM can be heard? What version of Shairport Sync are you using? Did you edit any settings the configuration file?

By default, Shairport Sync will output to the "default" output device and will not use the volume level to control any hardware mixers. To use a specific output device or to use a specific mixer as a volume control, you need to enter the relevant information in the configuration file -- see the README or INSTALL guides.

The `alsamixer` and the [`sps-alsa-explore`](https://github.com/mikebrady/sps-alsa-explore) utilities might help you to gather information.
