### ISSUE TITLE
No sound just after starting airplay streaming

### ISSUE THREAD

**Issue by SuperKenVery** [mikebrady/shairport-sync#1483]
**Description:**
When I start airplay from an iOS device to shairport-sync, it will start streaming but no sound on my computer. I have to drag the volume bar on iOS to hear sound. It seems that shairport-sync defaults the volume to 0?

**Environment:**
Ubuntu 22.04, installed shairport-sync from official repository. 
iPadOS16 developer beta (20A5283p)

**Comment by mikebrady** [comment]
Thanks for the post. I haven't experienced this (on the same setup). Is it possible that the mixer associated with the audio output device on your Linux machine is set very low?  You can check with something like `alsamixer` to ensure it's high enough.

Shairport Sync does not try to control a mixer by default, although it can be configured to do so.

**Comment by SuperKenVery** [comment]
1. I've checked my configuration --- I configured nothing. Double checked volume related parts. All are defaults. Also my alsa volume is normal. So it shouldn't be related with alsamixer.
2. This problem is also present when AirPlaying on iOS 15.
3. As I see, dragging the volume bar on **iOS** does not affect the `alsamixer`'s volume, but only a volume inside shairport-sync. So I think it should be a problem with shairport. 
4. This happens every time on my machine. 


I would love to send you 1)packet captures or 2)shairport-sync logs or 3)anything else or even 4)debug on my computer if you tell me to (and how to, if neccessary)!

**Comment by SuperKenVery** [comment]
```
➜  ~ shairport-sync -V
3.3.8-libdaemon-OpenSSL-Avahi-ALSA-jack-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

➜  ~ systemctl status shairport-sync.service      
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-06-24 15:45:08 CST; 1s ago
       Docs: man:shairport-sync(7)
             file:///usr/share/doc/shairport-sync/README.md.gz
             https://github.com/mikebrady/shairport-sync
   Main PID: 17061 (shairport-sync)
      Tasks: 13 (limit: 19075)
     Memory: 2.7M
        CPU: 1.517s
     CGroup: /system.slice/shairport-sync.service
             └─17061 /usr/bin/shairport-sync

Jun 24 15:45:08 ubuntu-ken systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.

```

Here is the log file. I put some comments in it. Search for "===" and you'll soon find them. 
[shairport-sync-log.txt](https://github.com/mikebrady/shairport-sync/files/8974206/shairport-sync-log.txt)

**Comment by mikebrady** [comment]
Thanks. A couple of things:
1. The missing timing pings suggest that there are issues with the network. Those pings should return in the order of 10s of milliseconds.
2. The output device is `default` and that may not be a real device; in fact it may be a fake alsa device that routes audio in a PulseAudio system. Try using [`sps_alsa_explore`](https://github.com/mikebrady/sps-alsa-explore) to see what real devices are on your system.

**Comment by SuperKenVery** [comment]
1. Well maybe, but I don't think this would make it silent... and comes back after I drag the volume bar. 
2. Assuming that your (2.) is right, could this be solved by simply dragging the volume bar on my iPad? I guess not, so I don't think that's the problem. 

Just a reminder, my problem **isn't** _complete silence_, but silence just after starting airplay streaming, and after I slightly drag the volume bar everything goes **normal**. In other words, the whole system is mostly working well.

**Comment by mikebrady** [comment]
Thanks for the clarifications. I can exactly reproduce the phenomenon you have encountered, with the second iPadOS beta -- 20A5303i -- and also with iOS 15.5 on an iPhone.

When you connect to AirPlay from iOS, the volume is automatically set to -20.0 (on a -30.0 to 0.0 scale). The iOS volume slider / control is updated to show that on iOS 15.5, but not on iPadOS. (On default settings, that is -43.3 dB of attenuation.)  When you move the volume slider, the correct settings are sent.

So, the initial setting of -20.0 is a feature of AirPlay, but not updating the volume slider correctly appears to be a bug in the beta iPadOS.

**Comment by SuperKenVery** [comment]
Ohhh... **Thanks** for following up this issue all the way. It must be a difficult journey to find this bug of iPadOS/iOS. 
# Thanks so much! 


> By the way, this issue doesn't exist if I use an AV receiver (which should have an Apple-certificated chip for AirPlay), but that thing uses AirPlay2 and I haven't done any tests on `shairport-sync`'s AirPlay2. Well, this might more like an explanation on why I considered this bug to be `shairport-sync`'s. 

> By the way 2, we still seem to have different iPadOS versions --- is it because our iPad models are different?

**Comment by mikebrady** [comment]
Thanks. 

> By the way 2, we still seem to have different iPadOS versions --- is it because our iPad models are different?

A second developer beta came out, yesterday, I believe.

**Comment by mikebrady** [comment]
> By the way, if it is convenient for you, could you teach me how to debug this thing? If I set a breakpoint and the program pauses there, my iPad would report "cannot connect to ..." and disconnect from it, and shairport-sync exits and the debug session ends --- before I can see even a single variable! If it's not convenient then just never mind ~

Sorry, I didn’t see this. They say that “real programmers debug with print statements”. Well, in Shairport Sync there are lots of debug messages which are effectively conditional print statements. They can be enabled using the `log_verbosity` in the configuration file. Set it to 1 or 2 — 3 is generally too noisy.

**Comment by SuperKenVery** [comment]
Oh thanks! 

>They say that “real programmers debug with print statements”.

It sounds ugly but works perfectly!
