### ISSUE TITLE
Cutting the sound after a 4-5 minute pause

### ISSUE THREAD

**Issue by Kristian8606** [mikebrady/shairport-sync#1484]
Hello! I am extremely happy that you have created this amazing project, I enjoy my favorite music every day but I am experiencing a rather annoying bug and I can't find a solution.
Excuse me for my bad English. I will try to explain the problem.
When I listen to the last song from my playlist and the music is over if I wait 4-5 minutes and try to play music again, the timeline starts counting down the seconds but there is no sound. Sometimes I have to set the next song to get the sound back.
Once the sound returns, each subsequent song starts 4 or 5 seconds after it starts. That is, it seems that 4-5 seconds have been cut from the beginning of the song.
I hope you understand what I am trying to explain.
I was able to copy information when this happens.

```Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.001150315 "rtp.c:1952" Buffered TCP Reader Thread Exit via Cleanup.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.003997555 "rtp.c:2125" Buffered Audio Receiver Cleanup Start.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000243482 "rtp.c:2128" Connection 1: TCP Buffered Audio port closed: 50627.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000054777 "rtp.c:2131" Buffered Audio Receiver Cleanup Done.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000510093 "player.c:1685" Connection 31: Delete AirPlay 2 Control thread
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000313222 "rtp.c:1603" Connection 1: AP2 Control Receiver Cleanup.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000139630 "rtp.c:1605" Connection 1: UDP control port 58803 closed.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000182463 "rtp.c:1330" Connection 1: Clear anchor information.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000515037 "player.c:1740" Connection 1: player terminated.
Jun 15 22:53:54 Raspberry shairport-sync[6768]:          0.000286241 "rtsp.c:2521" Connection 1: TEARDOWN phase one complete
pi@Raspberry:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-06-15 22:39:10 EEST; 18min ago
   Main PID: 6768 (shairport-sync)
      Tasks: 12 (limit: 779)
        CPU: 40.320s
     CGroup: /system.slice/shairport-sync.service
             └─6768 /usr/local/bin/shairport-sync --log-to-syslog

Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000026741 "rtp.c:2518" Dropping packet 2171186776 from block 7072795 with out-of-range lead_time: -52.557 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000114203 "rtp.c:2518" Dropping packet 2171187448 from block 7072796 with out-of-range lead_time: -52.542 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000024649 "rtp.c:2518" Dropping packet 2171187800 from block 7072796 with out-of-range lead_time: -52.534 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000113407 "rtp.c:2518" Dropping packet 2171188472 from block 7072797 with out-of-range lead_time: -52.519 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000023370 "rtp.c:2518" Dropping packet 2171188824 from block 7072797 with out-of-range lead_time: -52.511 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000107260 "rtp.c:2518" Dropping packet 2171189496 from block 7072798 with out-of-range lead_time: -52.495 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000023018 "rtp.c:2518" Dropping packet 2171189848 from block 7072798 with out-of-range lead_time: -52.488 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000112926 "rtp.c:2518" Dropping packet 2171190520 from block 7072799 with out-of-range lead_time: -52.472 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000023370 "rtp.c:2518" Dropping packet 2171190872 from block 7072799 with out-of-range lead_time: -52.464 seconds.
Jun 15 22:57:48 Raspberry shairport-sync[6768]:          0.000017982 "rtp.c:1908" buffered_read: waiting for 2 bytes (okay at start of a track).
```

- I use a 3.5mm audio jack on my raspberry pi 4
- I use WIFI
- I'm not sure, but I think I've turned off WIFI management.

**Comment by Kristian8606** [comment]
Maybe more useful information, here the break is about 9-10 minutes.

```

Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000399074 "rtp.c:1541" Connection 2: AP2 Event Receiver Cleanup.
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000193037 "rtsp.c:2469" Connection 2: TEARDOWN Close Event Socket.
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000095796 "rtsp.c:2473" Connection 2: closing TCP event port 45359.
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000032945 "rtsp.c:2525" Connection 2: TEARDOWN phase two complete
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.004882592 "rtsp.c:4695" Connection 2: rtsp_conversation_thread_func_cleanup_function called.
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000059037 "rtsp.c:2460" Connection 2: TEARDOWN a Remote Control stream connection.
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000028463 "rtsp.c:2469" Connection 2: TEARDOWN Close Event Socket.
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000102426 "rtsp.c:4726" Connection 2: terminating connection from fdf5:47b3:bfb5:4aa7:48f:489d:df31:58c2:55019 to self at fdf5:47b3:bfb5:4aa7:fc>
Jun 15 23:00:15 Raspberry shairport-sync[6768]:          0.000353167 "rtsp.c:4785" Connection 2: Closed.
Jun 15 23:01:14 Raspberry shairport-sync[6768]:         59.719876890 "rtsp.c:730" Connection 2: deleted in cleanup.
pi@Raspberry:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-06-15 22:39:10 EEST; 31min ago
   Main PID: 6768 (shairport-sync)
      Tasks: 12 (limit: 779)
        CPU: 46.698s
     CGroup: /system.slice/shairport-sync.service
             └─6768 /usr/local/bin/shairport-sync --log-to-syslog

Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000049222 "rtp.c:2518" Dropping packet 2701440589 from block 2044721 with out-of-range lead_time: -96.016 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000219130 "rtp.c:2518" Dropping packet 2701441261 from block 2044722 with out-of-range lead_time: -96.001 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000049611 "rtp.c:2518" Dropping packet 2701441613 from block 2044722 with out-of-range lead_time: -95.993 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000264889 "rtp.c:2518" Dropping packet 2701442285 from block 2044723 with out-of-range lead_time: -95.978 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000056222 "rtp.c:2518" Dropping packet 2701442637 from block 2044723 with out-of-range lead_time: -95.970 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000228259 "rtp.c:2518" Dropping packet 2701443309 from block 2044724 with out-of-range lead_time: -95.955 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000048611 "rtp.c:2518" Dropping packet 2701443661 from block 2044724 with out-of-range lead_time: -95.947 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000229815 "rtp.c:2518" Dropping packet 2701444333 from block 2044725 with out-of-range lead_time: -95.932 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000050630 "rtp.c:2518" Dropping packet 2701444685 from block 2044725 with out-of-range lead_time: -95.924 seconds.
Jun 15 23:10:40 Raspberry shairport-sync[6768]:          0.000037389 "rtp.c:1908" buffered_read: waiting for 2 bytes (okay at start of a track).

```

**Comment by mikebrady** [comment]
Many thanks for this report. Your English is fine, thanks. Can you let us know, please, the version of software you are using, but posting the response to:
```
$ shairport-sync -V
```
and can you tell us what music player and platform you are using. For example, is it the Music app on a Mac? Or Spotify on an iPhone? Or something else?

Does this problem happen *every* time you wait 4–5 or 9–10 minutes? (It would be great if it did!)

**Comment by Kristian8606** [comment]
> ```
> $ shairport-sync -V
> ```

4.1-dev-345-g8c1bc874-AirPlay2-alac-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc




> Например използвайте музика на Mac ли? Или Spotify на iPhone? Или нещо друго?

App Music  on IPhone


> Това проблем е ли _всеки_ път, когато чакате 4–5 или 9–10 минути? (Би било чудесно, ако го направи!)

Yes everytime

**Comment by mikebrady** [comment]
Okay, so using your information, I was able to find a bug in NQPTP which, I believe, causes this problem. So I'd be restful if you would update NQPTP and see if the problem goes away. You should also update Shairport Sync -- an unrelated bug was fixed. Thanks for reporting the issue.

**Comment by Kristian8606** [comment]
Thank you for correcting this issue!
I did a few tests and now there is no problem, it feels like an expensive product where you have no worries about whether it will work or break.
I've noticed that the interruption when you add or remove a homepod mini to a playing SPS is fixed.
But there is a break when you add or remove SPS to a playing Homepod mini.
Probably this problem is in the mini homepod itself, but for now I can't understand because the homepod is with IOS 16 beta.
I will test for a few more days and come back to close this issue.
Once again thank you.

**Comment by mikebrady** [comment]
Thanks for testing!

> But there is a break when you add or remove SPS to a playing Homepod mini.
> Probably this problem is in the mini homepod itself, but for now I can't understand because the homepod is with IOS 16 beta.

Yeah, I've noticed this, but I think this is a feature of the HomePod mini itself. I'll try to check.

**Comment by Kristian8606** [comment]
Hi, I rarely experience an outage. I noticed that after adding and removing the homepod mini, and switching to the next song, it actually counts down the seconds but there is no sound.
And sometimes it cuts out for about 1 second in normal use without adding a homepod.


```
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.000416389 "rtp.c:2549" Dropping packet 640070598 from block 10171273 with out-of-range lead_time: 37160.694 seconds.
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.000064333 "rtp.c:2549" Dropping packet 640070950 from block 10171273 with out-of-range lead_time: 37160.702 seconds.
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.000268222 "rtp.c:2549" Dropping packet 640071302 from block 10171273 with out-of-range lead_time: 37160.710 seconds.
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.000468945 "player.c:435" Connection 384: synced by first packet, seqno 0.
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.000360518 "player.c:1075" Connection 384: Lead time for first frame 3296273895: 0.511617 seconds.
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.004382056 "audio_alsa.c:1878" alsa: play() -- opened output device
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.000088611 "audio_alsa.c:1883" alsa: play() -- alsa_backend_state => abm_playing
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.101294259 "player.c:1111" Change in estimated first_packet_time: 0.018520 milliseconds for first_packet .
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.129236667 "player.c:1111" Change in estimated first_packet_time: 0.005384 milliseconds for first_packet .
Jul 03 23:32:43 raspberry shairport-sync[23540]:          0.115949111 "rtp.c:2773" malformed AAC packet skipped.
```

``4.1-dev-363-g7f5eb3a8-AirPlay2-alac-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
``

**Comment by Kristian8606** [comment]
Sorry for the stupid question but what is the easiest way to update the SPS without wiping and installing every time from scratch.

**Comment by mikebrady** [comment]
> Hi, I rarely experience an outage. I noticed that after adding and removing the homepod mini, and switching to the next song, it actually counts down the seconds but there is no sound.

Thanks for this! It's a scenario I didn't think of.

> And sometimes it cuts out for about 1 second in normal use without adding a homepod.

I'll keep an eye out for this. If you can cause it to happen reliably, it would be very useful.

> Sorry for the stupid question but what is the easiest way to update the SPS without wiping and installing every time from scratch.

Generally, the usual way to update is simply to use `git` to pull the changes, `make`, `make install` and restart. The configuration file and the `systemd` startup file are preserved across updates. Occasionally it is necessary to manually remove the `systemd` startup file and/or to do a full `autoreconf -fi`, `./configure...` as well, but that is usually noted in the release notes.

**Comment by mikebrady** [comment]
> Hi, I rarely experience an outage. I noticed that after adding and removing the homepod mini, and switching to the next song, it actually counts down the seconds but there is no sound.

It's going to take a few days to fix this, as I am away from my testing setups.

**Comment by mikebrady** [comment]
Ah, don't bother yet -- it's not a fix; it's not even a temporary fix. My idea is wrong.

**Comment by mikebrady** [comment]
@Kristian8606, I think I've fixed this issue. Thank you so much -- it must have been there for a long time!

**Comment by mikebrady** [comment]
> And sometimes it cuts out for about 1 second in normal use without adding a homepod.

I've noticed this when playing from iPhone to HomePod mini (HPM), sometimes with an SPS device connected and sometimes without. The music stops for about a second on the HPM (and simultaneously on the SPS device if connected) and then resumes. 

When an SPS device is connected, the statistics and diagnostics don't show anything unusual w.r.t buffers, synchronisation, etc. All in all, since is also happens without SPS involvement, I'm inclined to think it might be an Apple problem.

FWIW, the iPhone Music app is set for Lossless audio quality with WiFi Streaming set to Hi-Res Lossless and Dolby Atmos set to Automatic.

**Comment by Kristian8606** [comment]
It works perfectly thank you very much.  I will close this issue and enjoy.  If I find a bug I will let you know
