### ISSUE TITLE
Audio delay in some apps

### ISSUE THREAD

**Issue by tom8347** [mikebrady/shairport-sync#1486]
When I play audio from youtube in a browser there is a small amount of buffering at the start of the video and then the video/audio are in sync for the rest of it.  This is the expected airplay behaviour.  If I play a video through another app (eg plex) then the initial buffering that I get with youtube doesn't happen and the audio and video are out of sync for the duration of the video.  I find similar behaviour with some other apps - eg spotify doesn't buffer the way youtube does but then the music being played doesn't match the time stamp shown on my laptop by a couple of seconds.

**Comment by tom8347** [comment]
Thanks for your reply!  I guess I just never noticed it before with other airplay devices.  You say it's only some airplay 2 streams that do it and all airplay 1 streams.  Is there a way to force airplay 2 to be used all the time to minimise the amount that this happens?  Perhaps that's the default behaviour?

**Comment by mikebrady** [comment]
Thanks. Unfortunately, there is always a latency or lag, even in AirPlay 2 -- it can be [less than half a second or up to two seconds](https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md#airplay-2----more-about-what-works). If your Shairport Sync is built for AirPlay 2, AirPlay 2 operation will always be chosen, and the stream type -- and hence the lag -- will be chosen automatically by the source.
