### ISSUE TITLE
Clipping when using 'Mono' playback mode using AP2 on Pi Zero W

### ISSUE THREAD

**Issue by xStatts** [mikebrady/shairport-sync#1491]
I understand that running AP2 via shairport-sync on a Zero W is not recommended, but I've found from my use that shairport-sync has generally performed great for what I need it to do!

I've just put together a mono speaker setup with a Pi Zero W running AP2 on the development branch, and I'm getting some pretty significant clipping when using the 'Mono' playback option, and great sound quality with the default setting of 'Stereo'. Is there anything I can change in order to reduce this clipping? Let me know if there are any logs I can supply if that helps!

Many thanks :)

**Comment by mikebrady** [comment]
Thanks. It's a bit surprising that there is clipping TBH, so it would be good to investigate. In the past, certain sound settings in iTunes/Music on the Mac and on iOS have been known to induce clipping and distortion. I'm thinking of the Equalizer, the Crossfade Songs, Sound Enhancer and Sound Check Settings. They should all be off. Would you be kind enough to check those please? If the clipping persists, we'll get down to business!

**Comment by xStatts** [comment]
I've checked for any EQ or any other settings that you've mentioned, and they are all off on my iPhone. Interestingly, playing from my MacBook the clipping issue is nowhere near as pronounced with 'Mono' selected, but on some tracks it's still clearly audible, just less prominent. The same clipping is there playing back from another iPhone in the house, and not there when the playback setting is set to default.

**Comment by mikebrady** [comment]
Okay, thanks. We'll take a look at the code.

**Comment by mikebrady** [comment]
Okay, it might be a misunderstanding on my part of the rules for integer promotion. This code:
```c
              case ST_mono: {
                int32_t both = ls + rs;
                both = both << (16 - 1); // keep all 17 bits of the sum of the 16bit left and right
                                         // -- the 17th bit will influence dithering later
```
may be faulty. The variables `ls` and `rs` are `int16_t`, so it may be that the sum `ls + rs` is calculated as an `int16_t` (permitting clipping) before being sized to an `int32_t`. Now it's:
```c
              case ST_mono: {
                int32_t lsl = ls;
                int32_t rsl = rs;
                int32_t both = lsl + rsl;
                both = both << (16 - 1); // keep all 17 bits of the sum of the 16bit left and right
                                         // -- the 17th bit will influence dithering later
```
so that clipping should not occur. I've pushed an update to the `development` branch, and it you could try it out and report back, that would be great.

**Comment by mikebrady** [comment]
Actually, listing to the modified version, clipping is still there!

**Comment by mikebrady** [comment]
OK -- needed to do the same kind of thing for 32-bit sources, and it sounds like it's working now, and a new version has been pushed -- look for `Version 4.1-dev-376-gca6e768f` or later.

**Comment by xStatts** [comment]
Brilliant - have updated and have no clipping issues of any kind. Appreciate the write-up of the issue also, very interesting!
