### ISSUE TITLE
Audio from Mac or iPhone plays for around 10 minutes, and then stops, leaving silence

### ISSUE THREAD

**Issue by Liiion** [mikebrady/shairport-sync#1492]
Hi, I'm new to Github, Raspberry Pi, etc.
I'm grateful for Mike for ShairPort-Sync, however, I seem to be having the same issue as some before. My Apple devices will play audio to Shairport just fine for around 10 minutes, and then it will just cut out.
My Raspberry Pi still shows up as an AirPlay device in my audio outputs, and my network monitor on my Mac shows it's still sending around 900-1000Kb/s; suggesting it believes it's still playing the audio over AirPlay.
I'm not 100% on how to provide logs and such, so please point me in the right direction if necessary
I've looked into how the problem has been solved before, but I don't think I have the same problems.
If I disconnect and reconnect, there is still silence. If I try another device, still nothing. Waiting doesn't seem to fix it; only rebooting does.

The Pi is outputting via HDMI using Alsa. It's a Pi 4 running Raspbian Bullseye.

**Comment by mikebrady** [comment]
Thanks for the post. There is some guidance at [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/development/TROUBLESHOOTING.md) and [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md).

First question is: what version of Shairport Sync are you running please (`$ shairport-sync -V`).

**Comment by Liiion** [comment]
Hi Mike, 3.3.9-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

**Comment by mikebrady** [comment]
Thanks. If you're on WiFi, make sure that WiFi power management is off. If that makes no difference, could you try temporarily outputting to the audio jack rather than to HDMI, to try to eliminate the HDMI side of things?

**Comment by Liiion** [comment]
WiFi is off; Pi is cabled in to eth0. Should I still set WiFi power management to off?
It was a bit of a challenge to get audio to output to HDMI, so how do I change it to the audio jack in the .conf?

**Comment by mikebrady** [comment]
Super, thanks.  No need to change the WiFi settings if WiFi is not in use. Let's see how it goes with the audio jack.

**Comment by Liiion** [comment]
So far so good over 3.5mm audio jack. 15 minutes or so without it dropping out. I did get one time earlier where it went for hours at a time without dropping out over HDMI, but after a reboot it went back to every 10 minutes or so. I will reboot and see if it works consistently now using the audio jack.

**Comment by mikebrady** [comment]
Thanks. Yeah, if it works consistently over the audio jack but not consistently over HDMI, then suspicion must logically fall on the HDMI side of things. TBH I'm not familiar with audio support on HDMI on the Pi, though it seems to be in transition.

The quality of the audio jack output isn't great, that's the only problem.

**Comment by Liiion** [comment]
I think you're right. The HDMI seems to be the culprit here.
When the audio goes silent via HDMI, I can change the config file to use the audio jack, restart the service, and get audio. If I then change it back to HDMI and restart the service, still silence.
Thanks for all the help.
