### ISSUE TITLE
Max volume when unpausing music (sometimes occur)

### ISSUE THREAD

**Issue by Vaarelsauce** [mikebrady/shairport-sync#1497]
For example, I set the shairport volume to 50%, and play a song on Spotify. When I pause the Spotify song to watch like a short YouTube video, and then unpause the Spotify song, the shairport volume would automatically be adjusted to 100% and blast my ears off. Is there any way to circumvent this auto-correction?

Or at least, I recommend implementing a feature where you can adjust shairport's "default" volume setting.

**Comment by mikebrady** [comment]
Thanks for the report. This is not a behaviour I have encountered. Can you let us know the version of Shairport Sync, please? (`$ shairport-sync -V`)

**Comment by Vaarelsauce** [comment]
It is shairport4w  1.0.9.4, I haven't updated it in a long time so that MIGHT be why.

**Comment by mikebrady** [comment]
Thanks. Shairport4W is a different program — nothing to do with Shairport Sync, I’m afraid.
