### ISSUE TITLE
"mden" metadata tag not being sent.

### ISSUE THREAD

**Issue by celeryclub** [mikebrady/shairport-sync#150]
Hey there. Thanks for making this fantastic software. I'm working on a set of programs to run an LCD display that shows metadata from shairport-sync.

https://github.com/celeryclub/smartie-server
https://github.com/celeryclub/smartie-client

They require the "mden" ssnc metadata tag to know when to flush data to the screen. When I build from master the tag is sent normally, but when I build from develop it's not. I believe the breaking commit is 90f8ccd0.

This is on Raspbian Jessie. I have metadata enabled, but not album art. Please let me know if I can help by providing any additional details.

**Comment by mikebrady** [comment]
Thanks for the report. I'll have a look on Tuesday.

**Comment by mikebrady** [comment]
Actually I was able to push an update which I hope fixes the problem. It also adds two tags to distinguish when the timing information relates to pictures as distinct from metadata. Please let me know if it works.

**Comment by celeryclub** [comment]
I'm sorry for the horrendous delay here - I had problems with my music server and couldn't run this at all for a while. But I've tested it with a recent build, and can confirm that it works again. Thank you very much!
