### ISSUE TITLE
Device Volume synchronisation

### ISSUE THREAD

**Issue by DrCWO** [mikebrady/shairport-sync#1509]
Hi mikebrady,
I currently work on a Roon Extension being able to stream airplay content to Roon.
Looks quite promising until now.

What I am missing is a way to control device volume von outside. Let me explain:

Currently I am able to control the Roon volume by the device slider in the iPhone and a script called from shairport-sync if I change the volume slider.

Now at initialization of the connection I like to set the slider in the iPhone to the current volume value of Roon. Is this possible?

Best DrCWO

**Comment by DrCWO** [comment]
Just one more question: Is there a chance to stop airplay streaming from outside?
The idea is if press stop in Roon I can send a stop command to my iPhone and also stop playback there.

**Comment by mikebrady** [comment]
Thanks for the posts.

> Now at initialization of the connection I like to set the slider in the iPhone to the current volume value of Roon. Is this possible?

This is not possible at present, I'm afraid -- it's not something that has suggested before, and I'd have to check to see if it was possible in principle.

> Is there a chance to stop airplay streaming from outside?

You can ask Shairport Sync (through the D-Bus* or MPRIS or MQTT interfaces)  to send a remote-control "stop" request to the AirPlay player that is sending music to Shairport Sync. Unfortunately, however, the request is not always honoured -- some third party players simply ignore it, and remote control support of AirPlay 2 by Shairport Sync is still hit-and-miss (maybe "under development" is a kinder term).

*You can see examples of D-Bus commands in the `documents` folder of the repository, so it should be easy to try them out -- look for the line after `# Play using regular Remote Control`. BTW the `Advanced Remote Control` stuff (later in that document) is only available for iTunes and (sometimes) Music on the Mac. It doesn't seem to be available for iOS.

One other contributer had the interesting idea of simply killing `shairport-sync` when you wanted it to stop.

**Comment by mikebrady** [comment]
Just a little update.

Setting the initial volume to a specific value at the initialisation of a connection is possible in principle with AirPlay 2, because the player (e.g. iTunes/Music) actually asks Shairport Sync for an initial volume when a connection to initially made. That does not happen with (classic) AirPlay, unfortunately, so it's not possible, in principle, with classic AirPlay.

Instead of stopping an AirPlay session, it would be possible to forcibly drop the AirPlay connection. This would be okay from the perspective of an iOS player. On the Mac Music app, it would flag up as an output device that had disappeared.

But just to clarify:  at the moment, neither of these ideas have been implemented as, say, D-Bus commands.

**Comment by DrCWO** [comment]
Thank you for the in depth answer.

For me the volume theme has higher priority than stoping playback. Currently I set the volume it in the conf file to 100% so the slider on the iPhone has no function at all. Even if implemented for airplay2 this behaviour will stay for Airplay1 devices as I understood. Correct?

Please let me specify my requirement:
1. I like to find out if the connected device is Airplay1 or Airplay2 compatible. If you use dbus I can implement it that way.
2. I like to set iPhone volume slider for Airplay2 devices to a value I can specify (also dbus...)

This means for the user of Airplay1 devices that the slider is at a random position and has no functionality. Discovering an Airplay2 device the slider will be set by me according the current volume setting in Roon and if the user shifts the slider the Roon volume will be changed. In both cases the iPhone sends lossless audio with 100% volume to the pipe supplying Roon input.

Is there a chance you will implement my two requirements in future?
This really would make me happy as it will improve usability for the future users of my Roon Extension a lot.

**Comment by mikebrady** [comment]
Thanks for the response. I hadn't thought of a D-Bus command for checking whether it's in AirPlay or AirPlay 2 mode!

So yeah, I can implement those two things in the next few weeks.

**Comment by DrCWO** [comment]
This sounds like good news for me :-):-):-) I really appreciate it!!

Currently I use three breakout scripts to grab Start, End and Volume. 
If you are working in the dbus corner maybe you are willing to also integrate these functions so I can get rid of the scripts  and communicate with dbus only. Will be nicer from an architectural point of view ;-)

Best DrCWO

**Comment by mikebrady** [comment]
Just looking at this.

> I like to find out if the connected device is Airplay1 or Airplay2 compatible. If you use dbus I can implement it that way.

You can do this already by parsing the GetVersion property (search for `"AirPlay2"`). It's a bit awkward, but would it be sufficient for you?

**Comment by mikebrady** [comment]
Hello again. Three items have been added to the D-Bus interface in the `development` branch:
1. A `Protocol` property -- `AirPlay` or `AirPlay 2`.
2. A `Volume` property which can be used to get and set the volume without involving the player.
3. A `DropSession` method to forcibly stop a play session.

Let's hope you finds them useful. If you got a chance to test them and report back, that would be great.

**Comment by DrCWO** [comment]
**GREAT NEWS!!!**

Until now I never used the D-Bus as I have to program in node.js as the Roon API is in Node and for IPC node has it's own mechanisms. But there is a module for the D-Bus I will use. This here: https://github.com/Shouqun/node-dbus

To make use its API I have to know some constants I currently don't know. 
`var bus = DBus.getBus('session'); // I think it should be system?`

For getting an interface the call looks like this:
`bus.getInterface('com.example.Library', '/com/example/Library/authors/DAdams', 'com.example.Library.Author1', function(err, interface) {...});`

For getting and setting properties I need something like this:
`interface.getProperty('Name', function(err, name) {...});`
`interface.setProperty('Name', 'Douglas Adams', function(err) {...});`

Maybe I also have to call a service...
```
	iface.SendObject({
		name: 'Fred',
		email: 'cfsghost@gmail.com'
	}, { timeout: 1000 }, function(err, result) {
		console.log(result);
	});
```
As you see there are some constants in the API calls I have to know to access your service. 
Would you please tell me what the constants are to make it run?

**Comment by mikebrady** [comment]
Thanks.

Yeah, by default, Shairport Sync provides the D-Bus service on the system bus, not a session bus.

You can build Shairport Sync with a sample D-Bus client (add the `--with-dbus-test-client` at the `./configure...` stage), written in C, that might give you some hints, and of course the syntax of the commands and arguments used in `dbus-send` should also help.

**Comment by DrCWO** [comment]
Is there a chance you add the new attributes and calls in the documentation here: 
https://github.com/mikebrady/shairport-sync/blob/master/documents/sample%20dbus%20commands

Maybe helpful for  others too.
Thanks' a lot :-)

**Comment by mikebrady** [comment]
Thanks – good idea. I've done that now [on the `development` branch](https://github.com/mikebrady/shairport-sync/blob/development/documents/sample%20dbus%20commands).

**Comment by DrCWO** [comment]
Last question from me:
When can I expect that this new version will be part of DietPi software repository.
I installed shairport-sync from there and would appreciate to also do it in future. Do you know how this change will be propagated?

**Comment by mikebrady** [comment]
I’m working on getting a release out in the next few weeks. Then it’s up to the packagers. I guess there’ll have to be two packages, one for AirPlay 2 and one for AirPlay…

**Comment by DrCWO** [comment]
With my current release 
`3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc`

that I installed directly as a DietPi package I tried:
`# dbus-send --print-reply --system --dest=org.gnome.ShairportSync /org/gnome/ShairportSync org.freedesktop.DBus.Properties.Get string:org.gnome.ShairportSync.AdvancedRemoteControl string:Available`

and got:
`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.ShairportSync was not provided by any .service files`

I did: 
`# dbus-send --system --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames`

And got:
```method return time=1661102328.165787 sender=org.freedesktop.DBus -> destination=:1.842 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.832"
      string "org.freedesktop.login1"
      string ":1.206"
      string "org.freedesktop.timesync1"
      string "org.freedesktop.systemd1"
      string ":1.837"
      string "org.freedesktop.Avahi"
      string ":1.838"
      string "org.bluez"
      string ":1.10"
      string ":1.839"
      string ":1.0"
      string ":1.1"
      string ":1.2"
      string ":1.3"
      string ":1.840"
      string "fi.epitest.hostap.WPASupplicant"
      string ":1.4"
      string "fi.w1.wpa_supplicant1"
      string ":1.842"
   ]
```
In the config file I have enabled this line:
`	dbus_service_bus = "system"; // The Shairport Sync dbus interface, if selected at compilation, will appear`

Any idea what is missing?

**Comment by mikebrady** [comment]
Thanks for the post. The version of Shairport Sync you reference does not include a D-Bus interface, I'm afraid. If it did, it would include `-dbus` in the version string.

**Comment by DrCWO** [comment]
Short question: 
Is this dbus extension in your stable release now?
If yes I will ask Dietpi for an update and ask them to compile with  `-dbus` .

**Comment by mikebrady** [comment]
Thanks. It's not in the release version yet. Hopefully in the next two weeks... 🤞

**Comment by DrCWO** [comment]
I get crazy with Diepi. They released a new shairport-Sync now.
3.3.8-OpenSSL-Avahi-ALSA-soxr-metadata-mqtt-dbus-mpris-sysconfdir:/usr/local/etc

It seems to have dbus but if I select` output_backend = "pipe"` in the config file it terminates without further notice.
Is this already the release we had talked about?

**Comment by mikebrady** [comment]
Thanks. This is actually pretty ancient and that big has long been fixed. Version 3.3.9 has been out for over a year, I’d say.

**Comment by mikebrady** [comment]
I think if you add a name for the pipe, the crash wil not happen.

**Comment by DrCWO** [comment]
Hi Mike,
to get stability I now decided to install shairport-sync by myself using this description: [Simple Installation Instructions](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md)

Worked fine so far and is useable in my setup. I now have this:
```
# shairport-sync -V
3.3.9-OpenSSL-Avahi-stdout-pipe-soxr-metadata-dbus-sysconfdir:/etc
```
but with:
```
# dbus-send --print-reply --system --dest=org.gnome.ShairportSync /org/gnome/ShairportSync org.freedesktop.DBus.Properties.Get string:org.gnome.ShairportSync.AdvancedRemoteControl string:Available
method return time=1663319842.664743 sender=:1.27 -> destination=:1.33 serial=19 reply_serial=2
   variant       boolean false
```
I get a **false**. I guess the Advanced Remote Control is not yet in the main thread.

Would you please:
1. Instruct me how to build from the develop thread
2. Tell me when you plan to move the Advanced Remote Control to the main thread.

Best DrCWO

**Comment by DrCWO** [comment]
Hi again,
I am back on the master branch now. 

I am able to stop and play my iPad via the dbus command  `# Play using regular Remote Control`
I also can set the volume slider of my iPad with the `# Set Airplay Volume using Remote Control.`
Thank you so much for this, works really great and will help me a lot  :-)

One last question: 
How can I find out if the connected device (iPAd, iPhone iTunes, ...) support Airplay1 or Airplay2?
As far as I understood the volume slider setting and Play/pause only work with Airplay2 compatible devices...

**Comment by mikebrady** [comment]
The remote control facilities should work in both AirPlay 1 and AirPlay 2 modes. I think I added a "Protocol" property to the D-Bus interface recently, which indicates which protocol is in use. But that does require the `development` version at the moment. There is a building guide [BUILD.md](https://github.com/mikebrady/shairport-sync/blob/development/BUILD.md) on the `development` branch.
