### ISSUE TITLE
Shairport-Sync cannot be disabled

### ISSUE THREAD

**Issue by DrCWO** [mikebrady/shairport-sync#1511]
I found that doing 

`systemctl disable shairport-sync`

does not disable shairport-sync from restarting after reboot.

Using DietPi I get a message that it got disabled but after a reboot it is active again as there is an additional entry in /etc/init.d. I deleted that and since then it works as expected. 

Doesn't this make sense for the current Linux distros to remove the /etc/init.d entry during setup.

**Comment by mikebrady** [comment]
TBH I don’t know what the best practice is with regard to package-based installation. On the [BUILD.md](https://github.com/mikebrady/shairport-sync/blob/development/BUILD.md) page, it is suggested that old service files are removed first.
