### ISSUE TITLE
New messages in log files

### ISSUE THREAD

**Issue by dasl-** [mikebrady/shairport-sync#1513]
Hi, today I noticed a drop out in shairport-sync. I was connected from my iPhone to two SPS receivers, playing music via my iPhone's Music app (`AP2 Buffered Audio Stream`). I had my music library on shuffle and was rapidly clicking "Next" to land on a song I felt like listening to. About a minute into playing the song I chose, my iPhone disconnected from one of the two SPS receivers it was connected to and music stopped playing in that room. At the same time, I noticed that the volume adjustment and play/pause controls were not affecting the one remaining SPS receiver to which my iPhone still claimed it was connected to.

It is possible that the above drop out was related to a flakey home network, so this is not necessarily a bug with SPS. I doubt it is worth looking into the drop out until I have more data, or until I am more sure it wasn't a result of a flakey home network -- i only mention that it happened for context. While I was looking at the log files, I noticed some log lines I've never seen before. I've attached the logs from 3 SPS receivers: https://gist.github.com/dasl-/2485d7e4e0623da05eea16518ca231df

I believe the drop out / disconnect happened around 18:51 in this log file: https://gist.github.com/dasl-/2485d7e4e0623da05eea16518ca231df#file-pi-study-log-L214

The above log files were generated on a slightly older version of SPS / NQPTP. I've since upgraded to the latest on all my receivers:
```
% nqptp -V ; shairport-sync -V
Version: 1.1-dev-170-ge214e3c-dirty. Shared Memory Interface Version: 7.
4.1-dev-491-g08de8a40-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc
```

I am still able to reproduce getting these new log messages, although I'm unable to reproduce any drop outs / disconnects. I can reproduce the log messages by connecting to an SPS receiver from my iPhone and playing music via the iOS Music app. When I rapidly click the "Next" button to skip a few songs, I'll get a stream of these log messages: https://gist.github.com/dasl-/cfe0debf038bab6f7c593372de08b4b2

Perhaps these log lines are innocuous -- they dont seem to affect my ability to use SPS. But I can't recall having seen them before.

**Comment by mikebrady** [comment]
Apologies -- that:

```
... "audio_alsa.c:1447" alsa_handle is NULL in standard_delay_and_status.
```
message escaped being "quietened". I'll fix it in the next push to the `development` branch!

A flaky home network could indeed cause the problem you referred to earlier. Commands, volume control changes and metadata, including artwork, travel the same TCP/IP connection, so if the connection gets bogged down, everything slows down... OTOH if you can reproduce it on a good network, it would likely be something else.

**Comment by mikebrady** [comment]
David, that noisy message should be gone now. Thanks again.
