### ISSUE TITLE
Code for HomeKit 

### ISSUE THREAD

**Issue by guussie** [mikebrady/shairport-sync#1514]
When I want to register a new player, I’m being asked for an 8-number code.

what code should I use?

thanks!
![DC25FB1A-0CF2-42D8-8BB1-B6D81C8FE3FC](https://user-images.githubusercontent.com/2110909/185250142-3ce84823-7ee0-4344-8376-021d345eb269.png)

**Comment by mikebrady** [comment]
Thanks for the post. This should be covered in [ADDINGTOHOME.md](https://github.com/mikebrady/shairport-sync/blob/development/ADDINGTOHOME.md).

**Comment by guussie** [comment]
> Thanks for the post. This should be covered in [ADDINGTOHOME.md](https://github.com/mikebrady/shairport-sync/blob/development/ADDINGTOHOME.md).

Yes, it partly is covered. I used this page to get going.

To be more precise, the Shairplay device is available in the network even without adding it to Home. But this doesn't seem to make the device available to Siri. When I ask Siri to play music in the Kitchen, Siri answers that she doesn't know this device.

I think the solution to that would be to add the device to Home, as described in your md. However, at the end of that process, I get the request to enter the 8 numbers and I don't know which 8-number code I should use.

Thanks for looking into this.

**Comment by mikebrady** [comment]
Thanks. There is no facility for specifying a code for Shairport Sync devices.

Here is what works for me:

1. The  [ADDINGTOHOME.md](https://github.com/mikebrady/shairport-sync/blob/development/ADDINGTOHOME.md) procedure adds the speakers to Home.
2. I then add the speakers to a room. So in my case I added speakers called "Speaker" to the room "Kitchen".
3. Now I am able to say to Siri: "Hey Siri, play some music in the kitchen please."

It doesn't recognise the speakers by their own name, but it does recognise them by the room they are in. I don't know if this is a feature of the Home system of a deficiency in Shairport Sync, but the AirPort Express exhibits the same behaviour.
![IMG_4532](https://user-images.githubusercontent.com/4265913/185735197-1dde46f9-3952-4b76-8bd3-c7a01c9ab88c.jpg)

**Comment by guussie** [comment]
Hello @mikebrady,

Just to confirm that I got it working now. Indeed no need for a code. I don't know why it was asking for this code, but it doesn't now.

Thanks for this great AirPlay solution. Working very well now!
