### ISSUE TITLE
Control audio playback through an API

### ISSUE THREAD

**Issue by tommyzat** [mikebrady/shairport-sync#1517]
Is it possible to control audio aspects through code without input from a client? (e.g. skip track, pause. etc)

**Comment by mikebrady** [comment]
Thanks for the question. There is some limited remote control of the audio source (e.g. iTunes/Music) via MQTT and a B-Bus interface -- see [ADVANCED TOPICS.md](https://github.com/mikebrady/shairport-sync/tree/development/ADVANCED%20TOPICS) for a bit more information.

**Comment by tommyzat** [comment]
Hello, thank you for your answer!

I still couldn't find where an example of this is in the documentation, I'd really appreciate it if you could point out to me where that is! The [MQTT](https://github.com/mikebrady/shairport-sync/blob/development/ADVANCED%20TOPICS/MQTT.md) page is broken.

**Comment by mikebrady** [comment]
Apologies — it’s [here](https://github.com/mikebrady/shairport-sync/blob/development/MQTT.md). I’ll fix the broken link.

**Comment by mikebrady** [comment]
Broken link fixed, I believe.

**Comment by tommyzat** [comment]
Thank you for fixing the broken link!

This is also broken:
https://github.com/mikebrady/shairport-sync/blob/development/ADVANCED%20TOPICS/CAR%20INSTALL.md

I still wasn't able to find an example of D-Bus or MQTT control, only how to read metadata info from shairport...

**Comment by mikebrady** [comment]
Apologies again -- _that_ link is fixed now. 

> I still wasn't able to find an example of D-Bus or MQTT control, only how to read metadata info from shairport...

I'm not sure I understand you correctly here -- could you elaborate please? (BTW, in case it's relevant, there are examples of D-Bus commands using the `dbus-send` Command Line tool [here](https://github.com/mikebrady/shairport-sync/blob/development/documents/sample%20dbus%20commands) -- I think this link is working 🙄!)
