### ISSUE TITLE
Question: internet radio over shairport-sync?

### ISSUE THREAD

**Issue by dubaleeiro** [mikebrady/shairport-sync#1521]
Hello,
Thanks once again for the great work !

I was wondering… would it be somehow possible to play an internet radio from a script on a raspberry pi using shairport-sync as a sort of middleware, so that the dbus audio commands like play, Pause, next etc. would work?

**Comment by mikebrady** [comment]
Thanks for the kind words. To be honest, the focus at the moment is making Shairport Sync work as well as possible before an initial release of the AirPlay 2 functionality. There mare other projects that you might like to consider to provide internet radio and the like — e.g. [OwnTone](https://github.com/owntone/owntone-server).

**Comment by dubaleeiro** [comment]
Thanks for your quick reply! I will take a closer look at OwnTone.
