### ISSUE TITLE
fatal error: alsa: error -19 ("No such device") opening alsa device "default"

### ISSUE THREAD

**Issue by derided** [mikebrady/shairport-sync#1522]
Hi- I'm a total newbie to this business (Pi, the terminal, linux), but I'm loving trying to make things work. I'm flying largely blind, following instructions but unclear what I'm doing- hence, my diagnostic skills are abysmal. I've been so close with shairport-sync, but it's still not working. 

I did have it all working perfectly before installing a hifiberry DAC+ADC. Since then, raspberry pi shows up as an airplay destination on Apple devices, and apparently connects, but doesn't receive audio. A short while later, the connection fails. 

I've read through all the similar issues I could find here, and re-installed everything on fresh OS, but still the same problem, as detailed below.

After a fresh restart, running `$ sudo systemctl status shairport-sync` gives:

```
pi@raspberrypi:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: >
     Active: active (running) since Fri 2022-08-19 22:28:29 BST; 16h ago
   Main PID: 507 (shairport-sync)
      Tasks: 5 (limit: 1593)
        CPU: 4.083s
     CGroup: /system.slice/shairport-sync.service
             └─507 /usr/local/bin/shairport-sync --log-to-syslog

Aug 19 22:28:29 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
lines 1-10/10 (END)
```

After I've connected to airplay and it has failed, running `$ sudo systemctl status shairport-sync` gives:

```
shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-08-19 22:28:29 BST; 16h ago
   Main PID: 507 (shairport-sync)
      Tasks: 9 (limit: 1593)
        CPU: 5.300s
     CGroup: /system.slice/shairport-sync.service
             └─507 /usr/local/bin/shairport-sync --log-to-syslog

Aug 19 22:28:29 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Aug 20 15:15:31 raspberrypi shairport-sync[507]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such >
Aug 20 15:15:31 raspberrypi shairport-sync[507]: fatal error: alsa: error -19 ("No such device") opening alsa device "default".
```

If I then run `$ sudo systemctl stop shairport-sync`, and then `$ shairport-sync -v`, it works properly: everything connects as AirPlay 2, the Pi receives sound, and the DAC led lights up.

Here is the report:
```
pi@raspberrypi:~ $ sudo systemctl stop shairport-sync
pi@raspberrypi:~ $ shairport-sync -v
         0.028295667 "shairport.c:2026" startup in Airplay 2 mode with features 0x405c4a00,0x1c340 on device "e4:5f:01:91:15:07".
         0.000103314 "shairport.c:2069" software version: "4.1-dev-499-g0b2ebd25-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000017686 "shairport.c:2075" log verbosity is 1.
         0.000022796 "audio_alsa.c:1027" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000031481 "audio_alsa.c:1316" alsa: disable_standby_mode is "never".
         0.000014149 "audio_alsa.c:1320" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000014111 "audio_alsa.c:1322" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000017796 "audio_alsa.c:1362" alsa: output device name is "default".
         0.000181648 "shairport.c:2104" libsodium initialised.
         0.000269056 "shairport.c:2154" disable resend requests is off.
         0.000017777 "shairport.c:2155" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000014797 "shairport.c:2159" statistics_requester status is 0.
         0.000013000 "shairport.c:2164" rtsp listening port is 7000.
         0.000013055 "shairport.c:2165" udp base port is 6001.
         0.000013000 "shairport.c:2166" udp port range is 10.
         0.000012778 "shairport.c:2167" player name is "Raspberrypi".
         0.000012704 "shairport.c:2168" backend is "alsa".
         0.000012574 "shairport.c:2169" run_this_before_play_begins action is "(null)".
         0.000013074 "shairport.c:2170" run_this_after_play_ends action is "(null)".
         0.000012944 "shairport.c:2171" wait-cmd status is 0.
         0.000012556 "shairport.c:2172" run_this_before_play_begins may return output is 0.
         0.000013000 "shairport.c:2173" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000013167 "shairport.c:2175" run_this_before_entering_active_state action is  "(null)".
         0.000012944 "shairport.c:2177" run_this_after_exiting_active_state action is  "(null)".
         0.000012926 "shairport.c:2179" active_state_timeout is  10.000000 seconds.
         0.000015018 "shairport.c:2180" mdns backend "(null)".
         0.000013537 "shairport.c:2182" interpolation setting is "auto".
         0.000013389 "shairport.c:2185" interpolation soxr_delay_threshold is 30000000.
         0.000012834 "shairport.c:2186" resync time is 0.050000 seconds.
         0.000013352 "shairport.c:2187" allow a session to be interrupted: 0.
         0.000012537 "shairport.c:2188" busy timeout time is 0.
         0.000012629 "shairport.c:2189" drift tolerance is 0.001995 seconds.
         0.000013334 "shairport.c:2190" password is "(null)".
         0.000012703 "shairport.c:2191" ignore_volume_control is 0.
         0.000012648 "shairport.c:2195" volume_max_db is not set
         0.000012741 "shairport.c:2196" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000013074 "shairport.c:2198" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000013241 "shairport.c:2202" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000013056 "shairport.c:2204" disable_synchronization is 0.
         0.000012462 "shairport.c:2205" use_mmap_if_available is 1.
         0.000012575 "shairport.c:2206" output_format automatic selection is enabled.
         0.000012888 "shairport.c:2210" output_rate automatic selection is enabled.
         0.000012945 "shairport.c:2214" audio backend desired buffer length is 0.200000 seconds.
         0.000013389 "shairport.c:2216" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000013555 "shairport.c:2218" audio backend latency offset is 0.000000 seconds.
         0.000016223 "shairport.c:2220" audio backend silence lead-in time is "auto".
         0.000012703 "shairport.c:2224" zeroconf regtype is "_raop._tcp".
         0.000013908 "shairport.c:2225" decoders_supported field is 1.
         0.000012648 "shairport.c:2226" use_apple_decoder is 0.
         0.000012555 "shairport.c:2227" alsa_use_hardware_mute is 0.
         0.000012704 "shairport.c:2231" no special mdns service interface was requested.
         0.000025852 "shairport.c:2234" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000015093 "shairport.c:2264" loudness is 0.
         0.000012703 "shairport.c:2265" loudness reference level is -20.000000
         0.005382797 "shairport.c:2347" NQPTP is online.
         1.495013239 "shairport.c:250" "soxr" interpolation has been chosen.
        12.457775437 "rtsp.c:4174" Connection 1: Current volume (-24.000000) requested
         1.393766574 "rtsp.c:3154" Connection 1. AP2 Buffered Audio Stream.
```

I feel like I'm missing something super obvious, but have no clue how to proceed. Thanks for any advice, help, prompts in the right direction!

**Comment by mikebrady** [comment]
Thanks for the report, which I've edited slightly for layout. 

The problem is that Shairport Sync can't find the DAC -- hence the message:
```
Aug 20 15:15:31 raspberrypi shairport-sync[507]: fatal error: alsa: error -19 ("No such device") opening alsa device "default".
```
So the question is, where is it?

If you do:
```
$ shairport-sync -h
```
then at the end of it, you should get something like this:
```
....
[snip]
Settings and options for the audio backend "alsa":
    -d output-device    set the output device, default is "default".
    -c mixer-control    set the mixer control name, default is to use no mixer.
    -m mixer-device     set the mixer device, default is the output device.
    -i mixer-index      set the mixer index, default is 0.
    hardware output devices:
      "hw:Headphones"
      "hw:sndrpihifiberry"
      "hw:vc4hdmi"
[snip]
...
```
Would you be kind enough to post your version of that, please?

Actually, there is a tool called [sps-alsa-explore](https://github.com/mikebrady/sps-alsa-explore/blob/master/README.md) that might offer a bit more help, but you'll have to build it or use it through Docker.

**Comment by mikebrady** [comment]
> If I then run $ sudo systemctl stop shairport-sync, and then $ shairport-sync -v, it works properly: everything connects as Airplay 2, the Pi receives sound, and the DAC led lights up.

Can you clarify this please? Do you mean the following:
* When Shairport Sync is run as a service, it fails with the message:
```
Aug 20 15:15:31 raspberrypi shairport-sync[507]: fatal error: alsa: error -19 ("No such device") opening alsa device "default".
```
and
*  when you run it from the command line:
```
$ shairport-sync -v -statistics
```
it runs perfectly well and you can hear the sound?

**Comment by derided** [comment]
Thank you Mike for helping me out. And for your tolerance!

After a restart, here are the results of shairport-sync -h:


Settings and options for the audio backend "alsa":
    -d output-device    set the output device, default is "default".
    -c mixer-control    set the mixer control name, default is to use no mixer.
    -m mixer-device     set the mixer device, default is the output device.
    -i mixer-index      set the mixer index, default is 0.
    hardware output devices:
      "hw:sndrpihifiberry"
      "hw:vc4hdmi1"


to answer your second question, Yes! run from the command line, it works fine, until I close the terminal window. I don't know what to infer from this, as it appears to be running from startup (shows in the airplay list on an apple device)

Beyond your instruction in the build guide- during which I ran systemctl enable shairport-sync  -  I don't even know to run it as a service!! I told you I was an amateur..!

**Comment by derided** [comment]
> $ shairport-sync -v -statistics
> ```
> 
> it runs perfectly well and you can hear the sound?

That command results in:

0.000346426 "shairport.c:461" *fatal error: -statistics: unknown option
         0.000092759 "shairport.c:1679" emergency exit

**Comment by mikebrady** [comment]
Apologies, it should be:
```
$ shairport-sync -v --statistics
```
(Two hyphens in front of the word `statistics`.)

**Comment by mikebrady** [comment]
This is interesting. It looks as if Shairport Sync can "see" the output device -- the DAC -- when run from the command line but can't see the DAC when run as a service. 

This may be due to the possibility that Shairport Sync isn't quite installed right. What should happen is:
1. `shairport-sync` should run as a service under the user `shairport-sync`. This user is defined when the `# make install` step is performed during installation.
2. As well as the user `shairport-sync` being defined, a `shairport-sync` group is also defined during the `# make install` step.
3. Finally, and perhaps most importantly, the `shairport-sync` user is added to the `audio` group. Membership of the `audio` group allows the user `shairport-sync` to see the DAC.

If something went wrong in the `#make install` sequence, it might explain the situation. So, to see what's happening, could you restart the Shairport Sync service:
```
# systemctl restart shairport-sync
```
(Note the `#` means you must be in supervisor/superuser mode; use `sudo` to promote yourself if necessary.)

Don't try to play anything.

Run the following command and post the results.

``` 
$ ps aux | grep shairport
```
This will establish if Shairport Sync is running under the user `shairport-sync`. On a Pi 3B, I get this:
```
pi@RaspberryPi3B:~ $ sudo systemctl restart shairport-sync
pi@RaspberryPi3B:~ $ ps aux | grep shairport
shairpo+ 10137 89.0  1.6 236452 15472 ?        Ssl  09:25   0:01 /usr/local/bin/shairport-sync --log-to-syslog
pi       10152  0.0  0.0   7452   536 pts/3    S+   09:25   0:00 grep --color=auto shairport
```
It's showing up as running under `shairpo+`, which is presumably an abbreviation.

Also, please run the following commands and post the results:
```
pi@RaspberryPi3B:~ $ cat /etc/group | grep audio
```
On the same Pi 3B, I get this:
```
pi@RaspberryPi3B:~ $ cat /etc/group | grep audio
audio:x:29:pi,shairport-sync
pi@RaspberryPi3B:~ $ 
```
This shows that `shairport-sync` is a member of the group `audio`. So let's see what comes back from your experiments.

**Comment by derided** [comment]
Thanks again Mike!

Here is the result of --statistics:

0.034439260 "shairport.c:2026" startup in Airplay 2 mode with features 0x405c4a00,0x1c340 on device "e4:5f:01:91:15:07".
         0.000109685 "shairport.c:2069" software version: "4.1-dev-499-g0b2ebd25-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000017592 "shairport.c:2075" log verbosity is 1.
         0.000043704 "audio_alsa.c:1027" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000034315 "audio_alsa.c:1316" alsa: disable_standby_mode is "never".
         0.000014889 "audio_alsa.c:1320" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000039444 "audio_alsa.c:1322" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000040167 "audio_alsa.c:1362" alsa: output device name is "default".
         0.002108556 "shairport.c:2104" libsodium initialised.
         0.003073925 "shairport.c:2154" disable resend requests is off.
         0.000048130 "shairport.c:2155" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000039667 "shairport.c:2159" statistics_requester status is 1.
         0.000027963 "shairport.c:2164" rtsp listening port is 7000.
         0.000013222 "shairport.c:2165" udp base port is 6001.
         0.000012204 "shairport.c:2166" udp port range is 10.
         0.000012648 "shairport.c:2167" player name is "Raspberrypi".
         0.000012037 "shairport.c:2168" backend is "alsa".
         0.000014129 "shairport.c:2169" run_this_before_play_begins action is "(null)".
         0.000012241 "shairport.c:2170" run_this_after_play_ends action is "(null)".
         0.000012926 "shairport.c:2171" wait-cmd status is 0.
         0.000011833 "shairport.c:2172" run_this_before_play_begins may return output is 0.
         0.000013260 "shairport.c:2173" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000012407 "shairport.c:2175" run_this_before_entering_active_state action is  "(null)".
         0.000013019 "shairport.c:2177" run_this_after_exiting_active_state action is  "(null)".
         0.000012055 "shairport.c:2179" active_state_timeout is  10.000000 seconds.
         0.000015093 "shairport.c:2180" mdns backend "(null)".
         0.000011907 "shairport.c:2182" interpolation setting is "auto".
         0.000030056 "shairport.c:2185" interpolation soxr_delay_threshold is 30000000.
         0.000035666 "shairport.c:2186" resync time is 0.050000 seconds.
         0.000033556 "shairport.c:2187" allow a session to be interrupted: 0.
         0.000035278 "shairport.c:2188" busy timeout time is 0.
         0.000032685 "shairport.c:2189" drift tolerance is 0.001995 seconds.
         0.000035870 "shairport.c:2190" password is "(null)".
         0.000032519 "shairport.c:2191" ignore_volume_control is 0.
         0.000035592 "shairport.c:2195" volume_max_db is not set
         0.000032704 "shairport.c:2196" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000033685 "shairport.c:2198" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000028278 "shairport.c:2202" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000013463 "shairport.c:2204" disable_synchronization is 0.
         0.000011426 "shairport.c:2205" use_mmap_if_available is 1.
         0.000012648 "shairport.c:2206" output_format automatic selection is enabled.
         0.000011945 "shairport.c:2210" output_rate automatic selection is enabled.
         0.000012000 "shairport.c:2214" audio backend desired buffer length is 0.200000 seconds.
         0.000013629 "shairport.c:2216" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000012834 "shairport.c:2218" audio backend latency offset is 0.000000 seconds.
         0.000014611 "shairport.c:2220" audio backend silence lead-in time is "auto".
         0.000011870 "shairport.c:2224" zeroconf regtype is "_raop._tcp".
         0.000030444 "shairport.c:2225" decoders_supported field is 1.
         0.000035093 "shairport.c:2226" use_apple_decoder is 0.
         0.000032722 "shairport.c:2227" alsa_use_hardware_mute is 0.
         0.000035315 "shairport.c:2231" no special mdns service interface was requested.
         0.000046408 "shairport.c:2234" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000016796 "shairport.c:2264" loudness is 0.
         0.000031833 "shairport.c:2265" loudness reference level is -20.000000
         0.005457852 "shairport.c:2347" NQPTP is online.
         0.001545759 "rtsp.c:5235" unable to listen on IPv4 port 7000. The error is: "Address already in use".
         0.000155852 "rtsp.c:5235" unable to listen on IPv6 port 7000. The error is: "Address already in use".
         0.000035130 "rtsp.c:5384" *warning: could not establish a service on port 7000 -- program terminating. Is another instance of Shairport Sync running on this device?
         0.000017889 "rtsp.c:5388" Oops -- fell out of the RTSP select loop
         1.495810462 "shairport.c:250" "soxr" interpolation has been chosen.
         0.000235481 "shairport.c:1676" normal exit

After restarting and running ps aux | grep shairport:

shairpo+  4986  6.3  1.3 165776 13096 ?        Ssl  09:55   0:01 /usr/local/bin/shairport-sync --log-to-syslog
pi        4993  0.0  0.0   7452   544 pts/0    S+   09:56   0:00 grep --color=auto shairport

After running cat /etc/group | grep audio:

audio:x:29:pi,pulse,shairport-sync

It all seems similar to your results, to me. Do you see anything revealing?

**Comment by mikebrady** [comment]
Thanks. That all looks good. Okay, so another possibility is that it seems that you are running a full Desktop version of the Pi software. That includes a sound server called PulseAudio that might be causing an issue.

So how about trying this: 
Edit the file `/etc/shairport-sync.conf` so that the `output_device` line reads:
```
        output_device = "hw:sndrpihifiberry"; // the ....
```
What follows the `//` is a comment and is not read by Shairport Sync. Just make sure you have removed the `//` from the start of the line or it will be ignored. (You'll need to be in supervisor/superuser mode to edit the file.)

Having done that, check that Shairport Sync still works and plays music from the command line:
```
$ shairport-sync -v --statistics
```
If that works, then restart the Shairport Sync service and see if it works now.

**Comment by derided** [comment]
Ha! Result! I followed your instruction, restarted the device and it then worked perfectly weithout any intervention, recieving music over airplay and passing audion from the DAC.

With the peculiarity then when I ran --statistics, it generated this:

shairport-sync -v --statistics
         0.001229759 "shairport.c:2026" startup in Airplay 2 mode with features 0x405c4a00,0x1c340 on device "e4:5f:01:91:15:07".
         0.000089778 "shairport.c:2069" software version: "4.1-dev-499-g0b2ebd25-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000020629 "shairport.c:2075" log verbosity is 1.
         0.000037889 "audio_alsa.c:1027" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000037908 "audio_alsa.c:1316" alsa: disable_standby_mode is "never".
         0.000014963 "audio_alsa.c:1320" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000014481 "audio_alsa.c:1322" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000018593 "audio_alsa.c:1362" alsa: output device name is "hw:sndrpihifiberry".
         0.000172722 "shairport.c:2104" libsodium initialised.
         0.000234944 "shairport.c:2154" disable resend requests is off.
         0.000018278 "shairport.c:2155" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000015000 "shairport.c:2159" statistics_requester status is 1.
         0.000013648 "shairport.c:2164" rtsp listening port is 7000.
         0.000013185 "shairport.c:2165" udp base port is 6001.
         0.000013426 "shairport.c:2166" udp port range is 10.
         0.000013130 "shairport.c:2167" player name is "Raspberrypi".
         0.000013148 "shairport.c:2168" backend is "alsa".
         0.000013130 "shairport.c:2169" run_this_before_play_begins action is "(null)".
         0.000013444 "shairport.c:2170" run_this_after_play_ends action is "(null)".
         0.000013241 "shairport.c:2171" wait-cmd status is 0.
         0.000013018 "shairport.c:2172" run_this_before_play_begins may return output is 0.
         0.000013574 "shairport.c:2173" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000013649 "shairport.c:2175" run_this_before_entering_active_state action is  "(null)".
         0.000013444 "shairport.c:2177" run_this_after_exiting_active_state action is  "(null)".
         0.000013333 "shairport.c:2179" active_state_timeout is  10.000000 seconds.
         0.000015260 "shairport.c:2180" mdns backend "(null)".
         0.000013055 "shairport.c:2182" interpolation setting is "auto".
         0.000029889 "shairport.c:2185" interpolation soxr_delay_threshold is 30000000.
         0.000013185 "shairport.c:2186" resync time is 0.050000 seconds.
         0.000013685 "shairport.c:2187" allow a session to be interrupted: 0.
         0.000013204 "shairport.c:2188" busy timeout time is 0.
         0.000012908 "shairport.c:2189" drift tolerance is 0.001995 seconds.
         0.000013685 "shairport.c:2190" password is "(null)".
         0.000013000 "shairport.c:2191" ignore_volume_control is 0.
         0.000012852 "shairport.c:2195" volume_max_db is not set
         0.000013074 "shairport.c:2196" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000013740 "shairport.c:2198" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000013723 "shairport.c:2202" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000013574 "shairport.c:2204" disable_synchronization is 0.
         0.000012907 "shairport.c:2205" use_mmap_if_available is 1.
         0.000012908 "shairport.c:2206" output_format automatic selection is enabled.
         0.000013351 "shairport.c:2210" output_rate automatic selection is enabled.
         0.000013574 "shairport.c:2214" audio backend desired buffer length is 0.200000 seconds.
         0.000014241 "shairport.c:2216" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000014093 "shairport.c:2218" audio backend latency offset is 0.000000 seconds.
         0.000013815 "shairport.c:2220" audio backend silence lead-in time is "auto".
         0.000013037 "shairport.c:2224" zeroconf regtype is "_raop._tcp".
         0.000013222 "shairport.c:2225" decoders_supported field is 1.
         0.000013037 "shairport.c:2226" use_apple_decoder is 0.
         0.000012889 "shairport.c:2227" alsa_use_hardware_mute is 0.
         0.000013018 "shairport.c:2231" no special mdns service interface was requested.
         0.000023797 "shairport.c:2234" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000015703 "shairport.c:2264" loudness is 0.
         0.000013352 "shairport.c:2265" loudness reference level is -20.000000
         0.005394834 "shairport.c:2347" NQPTP is online.
         0.000652111 "rtsp.c:5235" unable to listen on IPv4 port 7000. The error is: "Address already in use".
         0.000078889 "rtsp.c:5235" unable to listen on IPv6 port 7000. The error is: "Address already in use".
         0.000020277 "rtsp.c:5384" *warning: could not establish a service on port 7000 -- program terminating. Is another instance of Shairport Sync running on this device?
         0.000014778 "rtsp.c:5388" Oops -- fell out of the RTSP select loop
         1.496512481 "shairport.c:250" "soxr" interpolation has been chosen.
         0.000227222 "shairport.c:1676" normal exit

and then exited. Is it simply that I should not have run --statistics while shairport was running as a service?

Either way, it all works as it should, and if you're happy with the above then I'm delighted. Thank you, again! :)

**Comment by mikebrady** [comment]
Well done -- I hope you enjoy it.

Your intuition is correct. When it ran Shairport Sync from the command line, it noticed that a network port -- port 7000 -- was already in use, so it could not continue and exited. The reason that port was in use was precisely because another instance of Shairport Sync was already running and was using that port.

Just for anyone who comes along later to this issue, I think I was a bit unfair to PulseAudio. What I really think was happening was that PulseAudio was providing a `default` audio device to the logged-in user, so Shairport Sync could find it when run from the command line as that logged-in user. However, PulseAudio was not providing a `default` device to the `shairport-sync` user so Shairport Sync was failing. (This is okay -- this is what PulseAudio is normally configured to do.) When you specified the actual hardware DAC -- `"hw:sndrpihifiberry"` -- to Shairport Sync in its configuration file, it could be found without assistance from PulseAudio, and hence it worked.

I'm guessing that a corollary of this is that when Shairport Sync is using the DAC -- i.e. when you're playing music -- the DAC won't be available to PulseAudio, and so beeps and system sounds will not always be available. You might even get an error message from the system.
