### ISSUE TITLE
[Problem]: Not calling audio output handler start() and stop() in buffered mode when you pause and resume the music

### ISSUE THREAD

**Issue by andreadaoud** [mikebrady/shairport-sync#1532]
### What happened?

I'm adding a custom output device (struct audio_output). In my design, this output device gives out audio data through a dbus file descriptor, and also receives hardware delay information from dbus. In my mind, this will be used to cascade [CamillaDSP](https://github.com/HEnquist/camilladsp) to perform rather complex audio processing while still keeping precise delay.

I'm trying to implement this with Airplay 2 Buffered mode, playing from Apple Music app on iPhone. I need to know when the stream starts and stops, and in order to prevent issue caused by hardware underrun, I wish to use the `start()` and `stop()` callback function in `audio_output` to monitor the playing state (or, alternatively, I can use dbus `Active` indicator to get the state). However, currently the `stop()` is only called when you completely stop playing (Exiting Apple Music app) or pausing for a long time. `start()` is not triggered when you pause for a short time. Likewise, the `Active` dbus property will not change to false when you pause unless you pause for a long time.

This behaviour is not consistent with Realtime mode, where it will trigger stop immediately when you pause the audio stream. But, it is definitely possible to know the pause state from rtsp stream. So would you please explain the design decision why `stop()` is omitted in Buffered mode? Do you have any suggestions? Thank you very much.

### Operating System?

Linux 5.15.32-rt39 #2 SMP PREEMPT_RT Wed Aug 31 17:36:32 CST 2022 aarch64 GNU/Linux

### Version?

Latest development branch

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. This behaviour is an outcome of what is happening on the link from the client (the player, e.g. the Music app) to the AirPlay 2 server (Shairport Sync). With a buffered stream, when you stop or pause the audio, the link will be kept open for about 6 (?) minutes before it is closed. Let me think a little about how to incorporate all this into the `start`/`stop`, `active`/`inactive` infrastructure.

**Comment by mikebrady** [comment]
(I should add that much of the remote control stuff doesn't work reliably with AirPlay 2.)

**Comment by andreadaoud** [comment]
As you've said, remote control is not very reliable. Instead, I found that [this code](https://github.com/mikebrady/shairport-sync/blob/7cbf302666fa09a4322fde3e7489284c5a60e4fb/rtsp.c#L1912) will always be executed when pause / resume playing. Also, every time playing is resumed, [this code](https://github.com/mikebrady/shairport-sync/blob/7cbf302666fa09a4322fde3e7489284c5a60e4fb/player.c#L1088) will be called. The logic around these snippets are too long, I'm not very familiar with AirPlay protocol, but I think there might be some reliable way to detect pause / resume?

**Comment by mikebrady** [comment]
Yeah, it's a pretty complicated situation.

There are three protocols -- "classic" AirPlay, AirPlay 2 Realtime Streams and AirPlay 2 Buffered Streams. Then there are the different clients -- iOS, macOS, AppleTV with different apps and different versions.

For instance, the first piece of code you reference relates to Buffered Audio. The second piece of code relates to all audio, but may be called more than once when playing starts or is resumed.

Added to that is the desire to ensure that the processing of the metadata or associated scripts  -- at events like pause, resume, etc. in Shairport Sync -- did not block the threads processing commands or audio unless explicitly requested.

The common things for all streams, of course, is:
1. The stream of PCM audio.
2. The timing of specific frames of audio relative to the sender's clock.
3. The timing of the sender's clock relative a local clock. 

The first of these is readily available, but the others are not exposed. Perhaps a simple APl could be devised to provide them to a backend.

**Comment by andreadaoud** [comment]
Thank you very much for your explanation! I think currently I just need a signal on PCM stream start and stop, preferably exposed through `audio_output` API and dbus `Active` property. Do you think if this can be achieved easily? If so, could you please give me some guidance (or, do me a favour to implement it)?

**Comment by mikebrady** [comment]
Unfortunately, it seems to me that a reliable start/stop signal has to be deduced from the behaviour of the PCM stream.

Crudely, if the PCM stream is there, the stream is running; otherwise the stream isn't running. Your backend could do this by checking what comes in together with its timing information (as outlined above). If the stream was delivered a little ahead of time, say 100 ms or so, you might have time to pass on the stream, the timing and any supervisory signals to the next part of the processing chain.

From my perspective, it would be possible to provide that expanded timing. You can already get the stream a small fixed amount of time ahead of when it's meant to be played. Generating a stop/start signal inside Shairport Sync would be a fair bit of work, I'm afraid.

Separately, have you looked at the convolution code that is already available in Shairport Sync? It processes the audio and then "gives it back" to Shairport Sync for it to be output through an existing backend. In a similar way, I wonder if you could send audio out to CamillaDSP, get if back and then forward it on to Shairport Sync for output. Anyway, it's just a thought, and it is a bit different from your plan.

**Comment by andreadaoud** [comment]
I had a thought about the architecture today, and indeed the frame time and relative clock drift information is needed. As you said it can be added with simple effort, could you please add it?

**Comment by mikebrady** [comment]
Sure -- I'll try to add it in the next week or so.

**Comment by mikebrady** [comment]
Hello again. So, I have made an initial attempt to do this by adding three parameters to the `play()` function call to the a backend. Up to now, the `play()` function passes a buffer containing a number of audio frames to be output. Now it also includes:
1. A flag indicating whether the frames are timed or not,
2. If timed, the RTP timestamp supplied by the client that corresponds to the first frame to be played,
3. The local time at which the first frame should be played.

Now, I've put it all in the `danger` branch, and you'll have to switch over to the `danger` branch of NQPTP as well.

If you look in the `audio_dummy` backend, there's a little more information and a tiny piece of sample code.

**Comment by andreadaoud** [comment]
Thanks for your work! I have a little question regarding "The local time at which the first frame should be played." From my previous understanding of the code, "when to play" information should be adjusted by shairport-sync by reading the delay field, and insert slience to control timing. Now it seems that I have to control when to play. I wonder if something I didn't understand correctly?

**Comment by mikebrady** [comment]
Thanks. Shairport Sync does indeed insert silence to control timing -- that's those untimed frames -- but it also sends audio frames to the backend a little ahead of time. This is set by the `audio_backend_latency_offset_in_seconds`, which defaults to 0.15 seconds nominally.

If you run the audio dummy sample, it will print out the exact lead time of each frame. As you can see, you could ignore the local time info, or, if you want very fine control over the exact time the frames should be played you can use it. Here is some output from a Pi 3:
```
        94.276758714 "audio_dummy.c:61" leadtime for frame 3096227723 is 132728897 nanoseconds, i.e. 0.132729 seconds.
        94.277797255 "audio_dummy.c:61" leadtime for frame 3096228075 is 139672162 nanoseconds, i.e. 0.139672 seconds.
        94.278366630 "audio_dummy.c:61" leadtime for frame 3096228427 is 147084126 nanoseconds, i.e. 0.147084 seconds.
        94.297346318 "audio_dummy.c:61" leadtime for frame 3096228779 is 136086975 nanoseconds, i.e. 0.136087 seconds.
        94.297943974 "audio_dummy.c:61" leadtime for frame 3096229131 is 143470449 nanoseconds, i.e. 0.143470 seconds.
        94.317932151 "audio_dummy.c:61" leadtime for frame 3096229483 is 131464600 nanoseconds, i.e. 0.131465 seconds.
```

**Comment by andreadaoud** [comment]
Previously I just used the `pipe` backend, and start playing as soon as there is enough data in the buffer. What I do not understand is that, now that you added "The local time at which the first frame should be played." information, how can I take advantage of this extra information? Do I only use it to calculate delay and report back to shairport-sync, or do I have to use it to control playback bahaviour (for example, insert delay until the specified time when playing)?

**Comment by andreadaoud** [comment]
> As you can see, you could ignore the local time info, or, if you want very fine control

Assume I use ALSA backend for CamillaDSP, it will have full access to the ALSA hardware, just like ALSA backend in shairport-sync. If I want to achieve the same sync level as the alsa backend in shairport-sync, how should I use this information? Thank you very much for your explanation!

**Comment by mikebrady** [comment]
Well, if your code takes a short, fixed amount of time to execute, then I suppose you could simply ignore the extra information alright. 

What I was thinking was that if you were passing the frames of audio to another system for processing, you could pass the timing information as well, so that this other system could use it to calculate when it should play the material. It could compare it with the local time itself and work out how long to delay playing the first frame.

**Comment by mikebrady** [comment]
I'm don't know how much support CamillaDP has for ALSA, but the ALSA system itself can tell you how many frames remain to be output at any time. You can use this, along with the system time and the first frame's local time (as now given by Shairport Sync) to work out what to do.

**Comment by andreadaoud** [comment]
Basically, CamillaDSP works like this:

Capture thread ---pass audio---> Processing thread ---pass audio---> Buffer ---> Playback thread (call ALSA API)

When audio data arrived at capture thread, it will send data to process thread, and then to playback thread. Playback thread will start playing when there are enough samples in the buffer.

Processing thread contains DSP processing code, which can be time-consuming to a certain extent (but not long, maybe a few tens of milliseconds), so you can assume the latency is unpredictable until playing is started. After playing is started, the latency will not change, and can be detected reliably.

> I don't know how much support CamillaDP has for ALSA

To add precise timing support, I will modify the code of CamillaDSP, so code to get information of delay (like `snd_pcm_delay`) can be added.

> You can use this, along with the system time and the first frame's local time (as now given by Shairport Sync) to work out what to do.

I'm still not very clear what can I do with timing information. Before playing the actual audio, shairport-sync will insert some silence data (without timing information). When the silence data reaches the playback thread, it will start, and play continuously. Later, when timed frames arrive, it is not possible to pause and wait. The only way to calibrate the delay I can think of, is that shairport-sync should adjust the length of silence before starting according to the reported delay value. But when the silence is sent, timing information is not yet available, so delay cannot be calculated. Could you please be more specific on how the information can possibly be used?

I know I'm asking too many questions, thank you for your patient explanation!

**Comment by mikebrady** [comment]
Shairport Sync's behaviour depends on the capabilities of the backend.

If the backend has the ability to report a delay (e.g. `audio_alsa.c`), it implements a `delay()` function. This returns the delay in frames and a status. When silence is first sent to the backend, it will occupy the output buffer and will be reported back through the `delay()` function. Shairport Sync can then do its active synchronisation thing -- interpolating frames to keep the output buffer from growing or contracting excessively. Thus, if you can calculate delay in your processing pipeline, you can feed it back in to Shairport Sync through a `delay()` function. Then, you would not need any of the extra parameters, and Shairport Sync would do synchronisation for you.

Without a `delay()` function, Shairport Sync works as if there is no delay. It may send some silence before the start of the audio, but it tries to ensure that the initial packet of audio is delivered at exactly the right time. Without a `delay()` function, Shairport Sync does not attempt any further synchronisation -- it doesn't have any information to base it on. In that case, it would up to the backend to process the audio at exactly the right time, and to ensure that it wasn't taking too much or too little time -- hence the need for the local time.

> I know I'm asking too many questions, thank you for your patient explanation!

Not a problem.

**Comment by andreadaoud** [comment]
One more small question: are all untimed frame silence? Can I drop untimed frames?

**Comment by mikebrady** [comment]
Yep, they are always silence, though it might be dithered, so will not actually contain just zero values.
