### ISSUE TITLE
Build fails for development branch on raspberry pi

### ISSUE THREAD

**Issue by dasl-** [mikebrady/shairport-sync#1535]
### What happened?

I believe that ever since this commit, the build of the development branch fails for me on a raspberry pi: https://github.com/mikebrady/shairport-sync/commit/7cbf302666fa09a4322fde3e7489284c5a60e4fb

In fact, I've confirmed that building from the previous commit works for me: https://github.com/mikebrady/shairport-sync/commit/344fa8f8d65dc4934db72666e321e974f43bdd1d

The error I get is: `configure: error: AirPlay 2 support requires libgcrypt -- libgcrypt-dev suggested`

My build script does install all of the recommended libraries though: https://github.com/mikebrady/shairport-sync/blob/development/BUILD.md#debian--raspberry-pi-os--ubuntu

Here is a full log of running [my SPS installation script](https://github.com/dasl-/pitools/blob/main/shairport-sync/install_or_update_shairport_sync.sh) in case it's helpful: https://gist.github.com/dasl-/5172b72120b735b334d9d71f2f25fbd8

I'm not sure if it's relevant, but the output does say: `Note, selecting 'libgcrypt20-dev' instead of 'libgcrypt-dev'`

### Operating System?

```
% uname -a
Linux piwall10 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
```

### Version?

n/a

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. Yes, apologies for this. I was trying to get the build to work on another platform, and I assumed, wrongly, that the Pi would be compatible. I'll fix it...

**Comment by dasl-** [comment]
no worries!

**Comment by mikebrady** [comment]
I think I may have fixed it. The idea is that it will fall back to AC_CHECK_LIB if PKG_CHECK_MODULES fails. But I haven't been able to test it, as I'm away from all my machines. If you got a moment to check it, that would be great.

**Comment by dasl-** [comment]
it works now. thanks, as always!
