### ISSUE TITLE
[Problem]: Port 7000 blocked

### ISSUE THREAD

**Issue by tecdude** [mikebrady/shairport-sync#1539]
### What happened?

After installing Shairport Sync on two different Raspberry Pi's, one with other software on it, another clean. Both gave the same error. When trying to play Audio, I get the error 'Could not connect to Front Room.'

### Relevant log output

```shell
pi@rpi-home:~ $ shairport-sync
warning: could not establish a service on port 7000 -- program terminating. Is another instance of Shairport Sync running on this device?
```

### Operating System?

Raspberry Pi OS

### Version?

4.1-dev-535-gcae9492d-AirPlay2-alac-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [x] Confirm

**Comment by tecdude** [comment]
Note: I can see the speaker in the AirPlay menu, and I can also add it to Apple Home

**Comment by mikebrady** [comment]
Thanks for the post. My guess is that the reason for this message is that Shairport Sync is already running in the background as a daemon -- this is what should happen when you follow the BUILD.md instructions. To check, from the command line, run this command to see if the `shairport-sync` process is already running:
```
$ ps aux | grep shairp
```
This is what I get on a Ubuntu system when Shairport Sync is running as a daemon:
```
$  ps aux | grep shai
shairpo+     888  2.7  0.9 1017216 19852 ?       Ssl  17:46   0:01 /usr/local/bin/shairport-sync
paralle+    2943  0.0  0.0   8568   644 pts/0    S+   17:46   0:00 grep --color=auto shai
```
You can see that the application `/usr/local/bin/shairport-sync` is running under the username `shairpo+`, an abbreviation of the username `shairport-sync`. That is exactly what should happen, and it would account for you being able to see if from AirPlay menus and the Home app.  (You can also see that the `grep` command is running under the username `paralle+`, short for `parallels`, my username on this system.)

If Shairport Sync was not running, you'd get something like this:
```
$ ps aux | grep shai
paralle+    4644  0.0  0.0   8568   668 pts/0    S+   17:53   0:00 grep --color=auto shai
```
You can see that there is no sign of the `/usr/local/bin/shairport-sync` application running.

**Comment by tecdude** [comment]
Yep, I can see it is running, but how can I fix it?

`shairpo+     701  0.5  0.5 527184  4884 ?        Ssl  15:33   2:01 /usr/local/bin/shairport-sync --log-to-syslog
pi         23512  0.0  0.0   6040   660 pts/0    S+   21:32   0:00 grep --color=auto shairp`

**Comment by mikebrady** [comment]
Great, so it’s actually working, but I’m guessing you’re not hearing anything? If you haven’t changed any of the settings, then the audio should be coming from the default output device, usually the headphone jack. You may have to use something like `alsamixer` to ensure that the volume is high enough.

**Comment by tecdude** [comment]
Ah, yes. It's working really well now. Thank you!

**Comment by tecdude** [comment]
whoops! forgot to close earlier.
