### ISSUE TITLE
[Problem]: Adding Airplay 2 speaker to Homekit (Homepod mini) error

### ISSUE THREAD

**Issue by chalojak** [mikebrady/shairport-sync#1541]
### What happened?

When trying to add the shairport enabled Airplay 2 speaker to Homekit, I am getting the error _"Unable to Add Accessory, Make sure you iPhone is connected to Wi-Fi, then try pairing again"_
![IMG_8541](https://user-images.githubusercontent.com/44300989/191061881-62e29f18-c347-4a71-924e-1b262dfbf010.jpg)
Note that I am on the same network and subnet. As I am using Unifi and have read that Unifi can separate the lan and wifi, I continued to experiment further: this is happening for 2 different players, one connected via wi-fi, another via ethernet. This behavior is observed on both iPhone and iPad. I have also tried connecting the iPhone via Belkin ethernet adapter, which did not help. 
Disabled ufw as well. There are no firewalls configured on the router Unifi Dream Machine Special edition (but still - being on the same subnet, should not be relevant).
Not relying on Unifi mDNS and installing a custom [https://hub.docker.com/r/scyto/multicast-relay](https://hub.docker.com/r/scyto/multicast-relay) did not help either.
I see these players in Apple Music and Spotify, I am able to stream to these players from my apple devices, but for some reason, I cannot add them to Homepod mini.

### Operating System?

Linux 5.4.0-1132206031516-generic #0+mediatree+hauppauge-Ubuntu SMP Mon Jun 6 18:58:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

and 

hifiberryos 20220826

### Version?

4.1-dev-535-gcae9492d-AirPlay2-OpenSSL-Avahi-ALSA-soxr-convolution-metadata-mqtt-sysconfdir:/etc

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post, which is a real puzzle.

> I cannot add them to Homepod mini.

I don't understand this. Could you explain it a bit more, please?

A few quick things:
* Is your iPhone up to date?
* Have you succeeded in adding any non-Shairport Sync devices to your Home?

**Comment by chalojak** [comment]
Sorry for not being clear. See details below:

Yes, iPhone, iPad, Homepod mini all up to date.

I am using Home successfully with many other devices. Genuine Homekit device such as Philips Hue, multiple accessories and plugins via Homebridge, all without any issue. 

I followed the guide and got to the very last step. I see the speaker but once I select it, I get the screen that I have shared. Just one remark, in order to discover the speakers by Home, I first need to play with them via Apple Music. Once I do that, then they appear as an accessory to be added in Home.

As I was suspecting a networking issue, I did all the previously described steps in order to eliminate the potential networking root causes.

And yes, it is a real puzzle to me too.

**Comment by chalojak** [comment]
Problem solved!
In the Home settings "Allow Speaker & TV access" I needed to select the option "Anyone On the Same Network", which allowed me to finish the process of adding the accessory.
The option of "Only People Sharing this Home" (which I obviously am, being the Owner) didn't work.

**Comment by mikebrady** [comment]
That is very useful, thanks -- maybe it will help someone in the future!

**Comment by JanLp** [comment]
https://github.com/mikebrady/shairport-sync/issues/1442#issuecomment-1060709537

**Comment by alessandroagnino** [comment]
@JanLp many thanks for that! I was trying to solve it since 2/3 weeks and I was going crazy! I tried everything but your suggestion solved it instantly! @mikebrady It will be very useful to add this on your guide! And many thanks for your work, really appreciate! 
Just a question, it works perfectly except that in the home app it shows as "Not playing" even if it's playing, do you know why? I attach a couple of screenshot
![IMG_A64F0EC2D8EA-1](https://user-images.githubusercontent.com/124431080/216759302-950b6a99-15f4-4a1d-a6e9-91c1b1dffc55.jpeg)
![IMG_EF513E3C8FC5-1](https://user-images.githubusercontent.com/124431080/216759343-bbf00b03-ec58-44db-a44e-cdebfabde725.jpeg)

**Comment by mikebrady** [comment]
Thanks for their reminder -- I've just added a line to ADDINGTOHOME.md in the `development` branch. When I get a chance I'll add a picture.

The "Not Playing" issue is a known problem. Presumably it has to do with other parts of the AirPlay 2 protocol which remain unknown -- unfortunately, Apple has not published them.

**Comment by mikebrady** [comment]
> [#1442 (comment)](https://github.com/mikebrady/shairport-sync/issues/1442#issuecomment-1060709537)
> 
> mike> maybe you should add it under add to homekit ;)

Just did it now, in the `development` branch. Sorry it took so long!
