### ISSUE TITLE
[Problem]: Can I toggle back to Airport 1?

### ISSUE THREAD

**Issue by coreygreenberg** [mikebrady/shairport-sync#1552]
### What happened?

Before I update Moode, with its latest dev build of Airplay2-ready Shairport-Sync, will it be possible to go into the Shairport config and force Airport1-only? I’ve had bad experiences updating my various Airport Expresses to the latest firmware for Airport2, and I think the sound quality is actually better with Airport1, so I deprecated them back to their old firmware.

If I run into the same issues with the latest Shairport, can I go back to Airport1? Thank you!

### Operating System?

RaspberryPiOS

### Version?

shairport-sync 4.1.0-dev

### How did you install Shairport Sync?

A package manager (apt, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post, but it’s a question for Moode Audio. Shairport Sync itself can be built for of AirPlay 2 or AirPlay 1 but not both. So to be able to switch, I guess you’d need an instance of each.

**Comment by coreygreenberg** [comment]
Thanks Mike, I guess I'll see if I can swap the version of Shairport that comes with Moode with one built for AirPlay1. So far, the only thing 2 does better than 1, in my system, is allow YouTube audio to play longer than a few seconds on Apple TV. Everything else is better with AirPlay1.

**Comment by coreygreenberg** [comment]
So removing and reinstalling Shairport as per your official instructions, from the command line within Moode, doesn’t work. Tim at Moode suggests the following to downgrade back to AirPlay 1 Shairport with an existing Moode install:

# Revert to 3.3.8 prod
sudo apt update
sudo moode-apt-mark unhold
sudo apt -y --allow-downgrades install shairport-sync=3.3.8-1moode1
sudo moode-apt-mark hold

# Upgrade back to 4.1.0-dev
sudo apt update
sudo moode-apt-mark unhold
sudo apt -y install shairport-sync=4.1.0~git20220930.97fa75e8-1moode1
sudo moode-apt-mark hold

Again, this is from within an existing Moode install, not a standalone Shairport install. 

I hope this helps.

**Comment by mikebrady** [comment]
Very useful, thanks.

**Comment by moodeaudio** [comment]
Hi Mike,

Oops, I thought the 4.1.x build --with-airplay-2 would auto fallback to Airplay 1 protocol based on some negotiation with the connecting client.

If thats not the case, I'll make provisions to maintain two shairport-sync packages in our repo and offer the user n option to swap between them.

**Comment by mikebrady** [comment]
Hi Tim. You're right -- unfortunately, that hasn't been figured out (yet?).

**Comment by coreygreenberg** [comment]
Wow, I feel like I'm in "The Parent Trap"! I got Moode and Shairport talking! 

FWIW it's been [discovered](https://audiophilestyle.com/ca/bits-and-bytes/apple-music-lossless-mess-part-2-airplay-r1026/) that AirPlay 2 will, in certain cases, encode the audio stream as 256K AAC, while AirPlay 1 is always ALAC. It can be argued that 256K AAC is for all intents and purposes as transparent as ALAC, but there's lossless and there's "lossless" and to some that distinction may be important. I don't think I can hear the difference but I like knowing my ALAC files are getting to my speakers via an ALAC pipeline, so I'm sticking with AirPlay 1 flavored Shairport for the time being.

**Comment by moodeaudio** [comment]
@coreygreenberg, 

Can you confirm that the procedure I posted to revert to 3.3.8 in fact worked for you?

**Comment by coreygreenberg** [comment]
Yes Tim, I can confirm that your downgrading instructions worked perfectly, and now I have Moode 8.2.1 running with Shairplay 3.3.8 and everything's working fine. Thank you again for your help!

**Comment by JanLp** [comment]
> FWIW it's been [discovered](https://audiophilestyle.com/ca/bits-and-bytes/apple-music-lossless-mess-part-2-airplay-r1026/) that AirPlay 2 will, in certain cases, encode the audio stream as 256K AAC, while AirPlay 1 is always ALAC.

I guess there's nothing new in that... I can't find it, but I think Mike covered that topic in his description of AirPlay 2
