### ISSUE TITLE
[Problem]: MPRIS playback status is stopped when paused

### ISSUE THREAD

**Issue by klay2000** [mikebrady/shairport-sync#1554]
### What happened?

When playing audio over Airplay from Spotify, pausing Spotify makes reading the MPRIS `PlaybackStatus` attribute in D-feet return `Stopped`, I believe it should return `Paused`.

### Operating System?

Kubuntu, `uname -a` output is `Linux XPS-15-7590 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Version?

4.1-dev-708-ge7c6c4b2-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-mpris-sysconfdir:/etc

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [x] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. I'll check.

**Comment by mikebrady** [comment]
Thanks again for the report. Unfortunately, that's what the client is reporting, so we have no reliable way to tell the difference between a pause and a stop.

Actually, there is another problem too. When playing a buffered audio track, e.g. from the Music app on iOS, a pause or stop is not signalled at all; it's only when  the airplay connection is dropped that a stop is signalled. I'll fix that very soon, but in general, we are at the mercy of whatever information the client program sends.

**Comment by mikebrady** [comment]
Just FYI, an update has been pushed to the `development` branch which tidies up some noisy signalling and adds signalling of a pause in an AirPlay 2 buffered audio stream.

But just to clarify, the `PlayerStatus` will be `Playing` or `Stopped` except in the case where play on an AirPlay 2 buffered audio session is paused by the client. This can last up to about five minutes before either play is resumed or the play session is ended by the client. I hope this helps.
