### ISSUE TITLE
[Problem]: Cannot connect to shairport-sync running on rpi 4 when connected via ethernet 

### ISSUE THREAD

**Issue by mirbagheri** [mikebrady/shairport-sync#1556]
### What happened?

I have installed shairport-sync on a raspberry pi 4 with Ubuntu 22.04. I can connect and play song from my iPhone when rpi is connected to local network via Wi-Fi. However when rpi is connected to my router via Ethernet cable I cannot connect to it. The connection always times out and I get the “could not connect to…” error on my phone. Please advise how I can resolve the issue.

### Configuration Information.

From "uname -a":
 Linux rpi 5.15.0-1016-raspi #18-Ubuntu SMP PREEMPT Wed Sep 28 12:15:55 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

From /etc/os-release:
 Ubuntu 22.04.1 LTS

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 4 Model B Rev 1.4

Shairport Sync Version String:
 4.1-rc3-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Living Room Audio";
 };
 sessioncontrol : 
 {
 };
 alsa : 
 {
 };
 sndio : 
 {
 };
 pa : 
 {
 };
 jack : 
 {
 };
 pipe : 
 {
 };
 dsp : 
 {
 };
 metadata : 
 {
 };
 mqtt : 
 {
 };
 diagnostics : 
 {
 };

>> Display Config End.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. This seems likely to be a network issue. Here are a few of things to check:

1. Is the Ethernet port configured correctly? 
2. Are the client (e.g. the iPhone) and the Shairport Sync device's Ethernet port on the same subnet? This is an AirPlay requirement.
3. Is there a firewall running somewhere, possibly on the Pi, possibly on the router? (See the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) guide.)
4. Is the router's firmware up to date? (Some combined router and WiFi access points have problems routing between WiFi and Ethernet, and it's worth checking that their firmware is fully up to date.)
