### ISSUE TITLE
[Problem]: No Audio through USB-Device, only 3,5 mm

### ISSUE THREAD

**Issue by LukasNitsche** [mikebrady/shairport-sync#1564]
### What happened?

Title describes the problem well. I am running Raspberry Pi OS on a Raspberry Pi 4. Shairport is running in a docker container. I have looked to many posts with this or similar issues, but none of them helped. In the notes at the docker hub it says that shairport will use the default sound output of Linux. I tested whether the sound output is the usb output and it is. However sound from shairport is only coming through the 3.5 mm. I think there must be something configured wrong but I am not proficient enough to figure this out by myself. Any help is highly appreciated! This is such a cool program if I can get it to work through the usb-card.

As I am 1. new to Linux and 2. new to Docker, it is quite hard to troubleshoot. I don't know how to export log files and I cannot find the configuration file, so I apologize in advance!

### Configuration Information.

-/

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. It sounds like Shairport Sync is working as it should, and sending audio to the default audio device, which seems to be the audio jack. To tell Shairport Sync to use the USB device, you must either (1) make the USB card the default audio output device or (2) tell Shairport Sync to send audio to the USB card.

1. Is an operating system thing, beyond the scope of Shairport Sync.
2.  is probably best accomplished using command line options -- the [main page](https://hub.docker.com/r/mikebrady/shairport-sync) on the docker hub has some examples -- see under "Options". The `man` page (with information about command line options) is easily accessible [here](https://htmlpreview.github.io/?https://github.com/mikebrady/shairport-sync/blob/development/man/shairport-sync.html).

**Comment by LukasNitsche** [comment]
Hi Mike, thanks so much for your answer. Yesterday was a bit late and with a fresh start today and the correct hw:[number] I now got it to work. Awesome project, now I can listen synchronized with all HomePods again ;)
