### ISSUE TITLE
[Problem]:Local speak suddenly gets louder when shairport-sync device is selected

### ISSUE THREAD

**Issue by eos1d3** [mikebrady/shairport-sync#1568]
### What happened?

Tested on MacOs 12.6.1 with speaker configuration:

1. one local speaker A
2. one shairport-sync Airplay 2 device

Firstly just start running Music app and play any music with local speaker. Then click shairport-sync device checkbox to add it to play. The local speaker will suddenly become much louder for 1-2 second until shairport-sync device starts playing. Deselect shairport-sync device and select it again, the same problem will happen again.

This happens only to Airplay 2. Original shairport-sync never has this problem.

### Configuration Information.

A USB sound device is connect to PI3 and used for Airplay 2.

>> Display Config Start.

From "uname -a":
 Linux pi3 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.1-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Pi3 Airplay 2";
 };
 alsa : 
 {
   output_device = "hw:1,1";
   mixer_control_name = "PCM";
 };

>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. I've certainly noticed this, but pretty sure this behaviour is an AirPlay 2 thing rather than a Shairport Sync thing.

**Comment by eos1d3** [comment]
Good to know that. Thanks a lot for your great project which I use almost everyday.
