### ISSUE TITLE
[Problem]: AirPlay not showing up after a while

### ISSUE THREAD

**Issue by tamasfodor1988** [mikebrady/shairport-sync#1574]
### What happened?

I installed shairport-sync nativelly on a Rasberry Pi 3 B what mainly runs HomeBridge inside docker. After shairport-sync installation the AirPlay service showed up on all my Apple devices, and I could play music on it. But after a while disappears. I have read many threads and searched inside the Issues, but unti now I couldn't find the solution. First I thought it is related to the wifi power management issue (solved, disabled the power management), after I tried via ethernet port, same problem. After each system reboot it works but it takes about 20-30 minutes and stops working. After some research maybe I found the problem, but I don't know how to solve it.

I think it is related to avahi-daemon, from the logs it is seems I have some kind of Host name conflict.

nov 08 07:09:07 raspberry shairport-sync[500]:         20.022583846 "mdns_avahi.c:320" avahi: state is AVAHI_CLIENT_S_COLLISION...needs a rename: B827EB1B85F2@Konyha

Any help would appreciated. Although I'm not a Linux guy, trying my best.

### Relevant log output

```shell
nov 07 22:35:52 raspberry dhcpcd[466]: eth0: Router Advertisement from fe80::1092:62fd:86d9:8abd
nov 07 22:35:52 raspberry dhcpcd[466]: eth0: adding address fd7b:9815:79f1:4150:db10:de30:db4c:948e/64
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for fd7b:9815:79f1:4150:db10:de30:db4c:948e on eth0.*.
nov 07 22:35:52 raspberry dhcpcd[466]: eth0: adding route to fd7b:9815:79f1:4150::/64
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for fe80::1ed7:db5c:bbc5:60e7 on vethd59f781.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for 169.254.104.104 on vethd59f781.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for fe80::42:f3ff:fe91:3d6a on docker0.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for 172.17.0.1 on docker0.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for 2001:4c4e:1748:5100:3ec7:ff38:e1d2:4659 on eth0.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for 192.168.1.139 on eth0.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for ::1 on lo.
nov 07 22:35:52 raspberry avahi-daemon[332]: Withdrawing address record for 127.0.0.1 on lo.
nov 07 22:35:52 raspberry avahi-daemon[332]: Host name conflict, retrying with raspberry-2
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for fe80::1ed7:db5c:bbc5:60e7 on vethd59f781.*.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for 169.254.104.104 on vethd59f781.IPv4.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for fe80::42:f3ff:fe91:3d6a on docker0.*.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for 172.17.0.1 on docker0.IPv4.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for fd7b:9815:79f1:4150:db10:de30:db4c:948e on eth0.*.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for 2001:4c4e:1748:5100:3ec7:ff38:e1d2:4659 on eth0.*.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for 192.168.1.139 on eth0.IPv4.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for ::1 on lo.*.
nov 07 22:35:52 raspberry avahi-daemon[332]: Registering new address record for 127.0.0.1 on lo.IPv4.
nov 07 22:35:52 raspberry shairport-sync[500]:        129.752373804 "mdns_avahi.c:320" avahi: state is AVAHI_CLIENT_S_COLLISION...needs a rename: B827EB1B85F2@Konyha
nov 07 22:35:52 raspberry shairport-sync[500]:          0.008946771 "mdns_avahi.c:220" avahi: service 'B827EB1B85F2@Konyha' group is not yet committed.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for fe80::1ed7:db5c:bbc5:60e7 on vethd59f781.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for 169.254.104.104 on vethd59f781.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for fe80::42:f3ff:fe91:3d6a on docker0.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for 172.17.0.1 on docker0.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for 2001:4c4e:1748:5100:3ec7:ff38:e1d2:4659 on eth0.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for 192.168.1.139 on eth0.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for ::1 on lo.
nov 07 22:35:53 raspberry avahi-daemon[332]: Withdrawing address record for 127.0.0.1 on lo.
nov 07 22:35:53 raspberry avahi-daemon[332]: Host name conflict, retrying with raspberry-3
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for fe80::1ed7:db5c:bbc5:60e7 on vethd59f781.*.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for 169.254.104.104 on vethd59f781.IPv4.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for fe80::42:f3ff:fe91:3d6a on docker0.*.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for 172.17.0.1 on docker0.IPv4.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for fd7b:9815:79f1:4150:db10:de30:db4c:948e on eth0.*.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for 2001:4c4e:1748:5100:3ec7:ff38:e1d2:4659 on eth0.*.
nov 07 22:35:53 raspberry shairport-sync[500]:          1.318096302 "mdns_avahi.c:320" avahi: state is AVAHI_CLIENT_S_COLLISION...needs a rename: B827EB1B85F2@Konyha
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for 192.168.1.139 on eth0.IPv4.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for ::1 on lo.*.
nov 07 22:35:53 raspberry avahi-daemon[332]: Registering new address record for 127.0.0.1 on lo.IPv4.
```

### Configuration Information.

 0.002081614 "shairport.c:2057" >> Display Config Start.
         0.006108646 "shairport.c:2057" 
         0.000071198 "shairport.c:2057" From "uname -a":
         0.000024063 "shairport.c:2057"  Linux raspberry 5.15.74-v7+ #1595 SMP Wed Oct 26 11:03:05 BST 2022 armv7l GNU/Linux
         0.037162604 "shairport.c:2057" 
         0.000124166 "shairport.c:2057" From /etc/os-release:
         0.000033698 "shairport.c:2057"  Raspbian GNU/Linux 11 (bullseye)
         0.007852448 "shairport.c:2057" 
         0.000109531 "shairport.c:2057" From /sys/firmware/devicetree/base/model:
         0.000027084 "shairport.c:2057"  Raspberry Pi 3 Model B Rev 1.2
         0.000139323 "shairport.c:2057" 
         0.000030208 "shairport.c:2057" Shairport Sync Version String:
         0.000024479 "shairport.c:2057"  4.1-4-g99e76fdf-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
         0.000028750 "shairport.c:2057" 
         0.000020729 "shairport.c:2057" Command Line:
         0.000021146 "shairport.c:2057"  shairport-sync --displayConfig
         0.000126146 "shairport.c:2057" 
         0.000026458 "shairport.c:2057" Configuration File:
         0.000022396 "shairport.c:2057"  /etc/shairport-sync.conf
         0.000021459 "shairport.c:2057" 
         0.000277812 "shairport.c:2057" Configuration File Settings:
         0.000030156 "shairport.c:2057"  general : 
         0.000024896 "shairport.c:2057"  {
         0.000022083 "shairport.c:2057"    name = "Konyha";
         0.000021980 "shairport.c:2057"  };
         0.000021041 "shairport.c:2057"  alsa : 
         0.000021198 "shairport.c:2057"  {
         0.000021615 "shairport.c:2057"    output_device = "hw:Headphones";
         0.000023802 "shairport.c:2057"    mixer_control_name = "Headphone";
         0.000022396 "shairport.c:2057"  };
         0.000021250 "shairport.c:2057"  diagnostics : 
         0.000020885 "shairport.c:2057"  {
         0.000021042 "shairport.c:2057"    log_verbosity = 2;
         0.000021771 "shairport.c:2057"  };
         0.000021770 "shairport.c:2057" 
         0.000020782 "shairport.c:2057" >> Display Config End.
         0.000022968 "shairport.c:2059" >> Goodbye!
         0.000032969 "shairport.c:1534" exit function called...
         0.000023386 "shairport.c:1586" Stopping the activity monitor.
         0.000022031 "shairport.c:1588" Stopping the activity monitor done.
         0.000042760 "shairport.c:1670" normal exit

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Haven’t come across this problem, but I’ll certainly have a look.

**Comment by mikebrady** [comment]
This is a bit of a puzzle. It looks as if Avahi is getting confused -- repeatedly creating and then removing the same IP numbers but trying to register a new hostname. Is there more than one system named "raspberrypi" on your network somewhere?

**Comment by mikebrady** [comment]
Assuming that there is only one "raspberrypi" device in your system, here is a left-field suggestion: check the power supply!  

That particular Raspberry Pi model is extremely sensitive by unsuitable power supplies. Even an apparently suitable and reputable USB power supply can fail the test and cause all kind of subtle and no-so-subtle problems. In my case, the problem went away only when I used an "Official Raspberry Pi 3 Power Supply".

You can check for low voltage issues as follows:
```
$ sudo journalctl -b | grep -i volt
```
This reads the journal (i.e. the log) since boot up and checks for any entries with the string `volt` (the `-i` instructs `grep` to ignore the case of the letters). With an unsuitable power supply, you'll get messages like this:
```
Aug 15 18:43:32 raspberry kernel: hwmon hwmon1: Undervoltage detected!
Aug 15 18:43:36 raspberry kernel: hwmon hwmon1: Voltage normalised
Aug 15 18:43:38 raspberry kernel: hwmon hwmon1: Undervoltage detected!
Aug 15 18:43:44 raspberry kernel: hwmon hwmon1: Voltage normalised
Aug 15 18:43:48 raspberry kernel: hwmon hwmon1: Undervoltage detected!
...
```
In my experience, _any_ messages like these indicate problems and can cause the device to disappear from the network.

**Comment by tamasfodor1988** [comment]
> This is a bit of a puzzle. It looks as if Avahi is getting confused -- repeatedly creating and then removing the same IP numbers but trying to register a new hostname. Is there more than one system named "raspberrypi" on your network somewhere?

No there isn't. Just one Raspberry PI in the network.

**Comment by tamasfodor1988** [comment]
> Assuming that there is only one "raspberrypi" device in your system, here is a left-field suggestion: check the power supply!
> 
> That particular Raspberry Pi model is extremely sensitive by unsuitable power supplies. Even an apparently suitable and reputable USB power supply can fail the test and cause all kind of subtle and no-so-subtle problems. In my case, the problem went away only when I used an "Official Raspberry Pi 3 Power Supply".
> 
> You can check for low voltage issues as follows:
> 
> ```
> $ sudo journalctl -b | grep -i volt
> ```
> 
> This reads the journal (i.e. the log) since boot up and checks for any entries with the string `volt` (the `-i` instructs `grep` to ignore the case of the letters). With an unsuitable power supply, you'll get messages like this:
> 
> ```
> Aug 15 18:43:32 raspberry kernel: hwmon hwmon1: Undervoltage detected!
> Aug 15 18:43:36 raspberry kernel: hwmon hwmon1: Voltage normalised
> Aug 15 18:43:38 raspberry kernel: hwmon hwmon1: Undervoltage detected!
> Aug 15 18:43:44 raspberry kernel: hwmon hwmon1: Voltage normalised
> Aug 15 18:43:48 raspberry kernel: hwmon hwmon1: Undervoltage detected!
> ...
> ```
> 
> In my experience, _any_ messages like these indicate problems and can cause the device to disappear from the network.

Thank you for your quick reply. Finally, I bought a new faster SD card (but I don't think the speed causes the problem) and installed a fresh Raspbian OS with HomeBridge and shairport-sync inside docker. After that, the problem disappeared. I saved the old SD card image file, if you would like to inspect the problam, but for me the problem solved with a fresh start.

**Comment by mikebrady** [comment]
I'm glad you resolved the issue. It's not necessary to keep the old SD card image for me, thanks.

Going forward, I think it would be worth keeping an eye out for low voltage issues.

**Comment by tamasfodor1988** [comment]
Thanks the advice, but what you mentioned about the low voltage, in my case it is not a problem.
