### ISSUE TITLE
[Problem]: Cannot find shairport-sync.conf under /etc on Docker container

### ISSUE THREAD

**Issue by KC-inDomus** [mikebrady/shairport-sync#1575]
### What happened?

Hi there, 
since 4.1 comed out, when executing:

`docker run -d --name shariport --restart unless-stopped --net host --device /dev/snd mikebrady/shairport-sync`

then 

`docker exec -it shairport sh`

then, inside the container a cannot find any shairport-sync.conf under /etc or elsewhere.

### Relevant log output

```shell
-
```

### Configuration Information.

Since 3.3.8 shairport-sync.conf was available under /etc

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. I'll take a look.

**Comment by tamasfodor1988** [comment]
I have the same problem. I thought I missed something

**Comment by mikebrady** [comment]
Apologies, guys. It'll be fixed in the next day or two.

**Comment by mikebrady** [comment]
That should be fixed now in the `development` and `development-classic` tagged images on Docker Hub.

**Comment by KC-inDomus** [comment]
confirmed ok 👍

**Comment by KC-inDomus** [comment]
still not working on :latest docker image?

**Comment by mikebrady** [comment]
Thanks. The fix has not been migrated to the `master` branch yet. When it does, it will also be in the `latest` Docker image. Should be in the next few days.

**Comment by KC-inDomus** [comment]
thanks a lot!

**Comment by KC-inDomus** [comment]
solved 👍
