### ISSUE TITLE
[Problem]: can not build with avahi

### ISSUE THREAD

**Issue by hillwoodroc** [mikebrady/shairport-sync#1578]
### What happened?

libavahi-devel have been installed in system, but configure can not find it.

### Relevant log output

```shell
[    9s] checking for libconfig... yes
[    9s] checking for SSL... yes
[    9s] checking for soxr... yes
[    9s] checking for avahi_client_new in -lavahi-client... no
[    9s] configure: error: Avahi support requires the avahi-client library!
[    9s] error: Bad exit status from /var/tmp/rpm-tmp.xsSCgE (%build)
```

### Configuration Information.

No

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Check the list of packages in the [BUILD.md](https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md) guide?

**Comment by hillwoodroc** [comment]
I confirm the list of packages in spec is no problem, because the same spec profile works on 3.3.9. 
The spec:  https://build.opensuse.org/package/show/openSUSE%3AFactory/shairport-sync
[build.log](https://github.com/mikebrady/shairport-sync/files/10113147/build.log)

**Comment by mikebrady** [comment]
Sorry to have dropped this. Haven't tried it on openSUSE, TBH, so I'll take a look.

**Comment by mikebrady** [comment]
Just checking that Shairport Sync builds on openSUSE Tumbleweed 64-bit. For an AirPlay2 build, packages installed were:

```
# zypper install -t pattern devel_basis

# zypper install popt-devel libconfig-devel libopenssl-devel soxr-devel libavahi-devel alsa-devel libplist-2_0-devel libsodium-devel ffmpeg-4-libavutil-devel ffmpeg-4-libavcodec-devel ffmpeg-4-libavformat-devel
```
