### ISSUE TITLE
ear splitting noise after song change

### ISSUE THREAD

**Issue by brbrr** [mikebrady/shairport-sync#158]
Some times while playing music from browser(chrome) and song is changing - instead of next song i getting max level volume noise(like when you plug in minijack). 

I has that kinda noise when setting alsamixer to max lvl, but this is not reproducible now. So it looks like something(mac or rpi) setting volume to ~200% which is sounds like noise

**Comment by mikebrady** [comment]
Thanks for the report. Can you say what version of Shairport Sync you're using, and what output device (DAC) please? Also, if you knew a way of getting it to happen all the time, we could investigate it.

**Comment by brbrr** [comment]
I have these issues with latest master branch. So I decide to try develop (2.7.1) branch. I'm using USB sound card. 
`GeneralPlus USB Audio Device at usb-3f980000.usb-1.3, full speed`

I'll keep track on it. ATM i dont know how to reproduce it.

**Comment by mikebrady** [comment]
Thanks!

**Comment by brbrr** [comment]
Just got that issue right after connect to RPI. I checked syslog (s/p logs was disabled)
`Nov 20 13:15:52 raspberrypi kernel: [166864.046097] usb 1-1.3: 1:1: cannot get freq at ep 0x5`
Not sure is it related or not, but this oly thing I got from system.

**Comment by mikebrady** [comment]
Thanks.
Can I ask, have you moved on to 2.7.1?
I'm not having any success reproducing the problem here. If you google the error message there are a few hits. One suggests that it might be an issue with USB speeds. Doesn't "full speed" above mean USB 1.1 – USB 2 is "high speed"? Is the sound card an old one? Are you using an old version of Linux?

**Comment by brbrr** [comment]
hm. That looks like 1.1 USB:

    $ lsusb -D /dev/bus/usb/001/007 | grep -i bcdusb
      bcdUSB               1.10

Actually it's kinda new, I was manufactured in 2015 (by label on board) but it could use old driver/chipset. that one was bought for 2$ on ali.

Im using up-to-date Raspbian Wheezy 4.1.7 on RPI 2. I just realize that I started get such problems when I switch to PRI2 from RPI1B+. Installed latest dev branch, will see :)

**Comment by mikebrady** [comment]
Thanks, yeah, it looks like USB 1.1. I can't tell whether it would be a problem or not, TBH. I wonder if there's a way to tell Linux to use USB 2 on it.

**Comment by brbrr** [comment]
I'm not sure what is `culling threads` means but I got my connection right in same time as that event happen and noise issue appeared.
from `syslog`: 
```
Nov 20 21:17:01 raspberrypi /USR/SBIN/CRON[13969]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 20 21:18:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:23:33 raspberrypi kernel: [196124.915417] RTL871X: recv eapol packet
Nov 20 21:23:33 raspberrypi wpa_supplicant[1741]: wlan0: WPA: Group rekeying completed with ac:f1:df:c4:1e:05 [GTK=CCMP]
Nov 20 21:23:33 raspberrypi kernel: [196124.916750] RTL871X: send eapol packet
Nov 20 21:23:33 raspberrypi kernel: [196124.919250] RTL871X: set group key camid:5, addr:ac:f1:df:c4:1e:05, kid:1, type:AES
Nov 20 21:23:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:28:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:33:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:38:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:43:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:48:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:53:35 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]: culling threads.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]: new RTSP connection.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     CSeq: 10513.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     X-Apple-Device-ID: 0x84383563f874.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     Apple-Challenge: Pt1kkAesoH2EfvWbsfr0Eg==.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     DACP-ID: 4121048D730CE3D6.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     Active-Remote: 3206875469.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     User-Agent: AirPlay/215.18.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     Apple-Response: 0O23INU2xhIGwQ0uWkDlUkgQe6HoaOojg5xzoOGDZ+3zlVvkVDC2s6mrjjQbv8HBcEoOkWc6C/XsGD7OnSieUV3p0LuJh9CkfpkuCQVQVCc3E125oSH+EMaYMcziiWnk4d3cvHbIbOYs+R+nJAaf/VqnFyeAD00e0/fNuAbXtBZB/sA1/oGWXihbzVLsVqZosRRXjd2Nx6RgAQTHnMcC92iTk3iI9cSom8hV6WNTJ2lkdYy3Myo0/qLR4yuNHT9YHfpAEwBHLHziw1NWdSIxi5o1wmBfpqRKU4VxLzDUkorXQi7nz34ro9ROk9yIXq1CHDaHcEXdaPCy1BQA7vxkoA.
Nov 20 21:55:22 raspberrypi shairport-sync[13384]:     CSeq: 10513.
```

**Comment by mikebrady** [comment]
Shairport Sync has a quick-and-dirty way of dealing with threads, and occasionally will discover a thread that's no longer in use and kill it -- that's the the `culling threads` message.

I'be been checking, and I'm using a USB 1.1 $5 Sound Card without problems, so the slow USB is hardly a problem. I don't know whether the `usb 1-1.3: 1:1: cannot get freq at ep 0x5` signifies a problem.

Does the same noise occur if you play from Safari or from iTunes?

**Comment by mikebrady** [comment]
Hi there. Just wondering if there been any further developments on this.

**Comment by brbrr** [comment]
Hi. I didn't get noise with Safari or iTunes, but actually I didn't test it much. wasn't use shairport heavily. I'll investigate it this week.

**Comment by mikebrady** [comment]
Thanks!

**Comment by brbrr** [comment]
reproduced with safari. no issues with iTunes so far

**Comment by mikebrady** [comment]
Thanks. Any particular action in Safari that causes it?

**Comment by brbrr** [comment]
same as for Chrome. playing music from vk.com. this happens on song switch(one ends, new starting up). as for me it looks like new song starts playing with changed volume level, or something affecting it.
so maybe, due song buffering volume is affected somehow.

**Comment by mikebrady** [comment]
Okay – I'll try that out.

**Comment by mikebrady** [comment]
Can I ask you to share the settings you have in the `alsa` stanza of your `/etc/shairport-sync.conf` file please? They'll be something like this:

```
// These are parameters for the "alsa" audio back end, the only back end that supports synchronised audio.
alsa =
{
  output_device = "hw:2"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
  mixer_control_name = "Speaker"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
//  mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
//  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
//  audio_backend_buffer_desired_length = 44100; // If set too small, buffer underflow occurs on low-powered machines. Too long and the response times with software mixer become annoying.
};

```

I think I have the same USB DAC:

```
sudo lsusb -D 004
Device: ID 1b3f:2007 Generalplus Technology Inc. 

pi@raspberrypi:/dev/bus/usb/001 $  lsusb
Bus 001 Device 004: ID 1b3f:2007 Generalplus Technology Inc. 
```

**Comment by brbrr** [comment]
Recently I encounter some issue with browser playback(which was chrome specific) so I was move on to default config, so my config equals to /etc/shairport-sync.conf.sample (even device name :)  )

**Comment by mikebrady** [comment]
Thanks, and does the device look the same – what is the output from `lsusb` or equivalent?

**Comment by brbrr** [comment]
Yep, `Bus 001 Device 004: ID 1b3f:2007 Generalplus Technology Inc. `

**Comment by mikebrady** [comment]
Great – let me see if i can reproduce the problem now...

**Comment by mikebrady** [comment]
Not having much luck. I wonder if it's associated with network problems. If you got a chance, could you run it with statistics enabled and the log verbosity set to 1. That might give us an indication of dropped packets, resynchronisation events, etc. I'll keep listening...

**Comment by brbrr** [comment]
ok, will do. but I want to point that this kinda hardly reproducible issue. It could appear 1 time for ~8 hour usage.

**Comment by mikebrady** [comment]
Thanks. I do appreciate your efforts. I'll be listening for problems here too under the same conditions. It would be great to nail it down. The idea is that if a noise event occurs, one can go to the log file and see if there are any obvious anomalies, like a sudden jump in lost packets, or some diagnostic message.

**Comment by brbrr** [comment]
listening for problems here. I want to point that noise I got - is actually same song, but with white noise. and when I low volume to ~15% I can hear that song. So for me that issue is looks like 300% software volume

**Comment by brbrr** [comment]
Reproduced with chrome:

```
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: RTSP shutdown requested.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: closing RTSP connection.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: Audio receiver -- Server RTP thread interrupted. terminating.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: Control RTP thread interrupted. terminating.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: Timing RTP thread interrupted. terminating.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: rtp_timing_sender thread interrupted. terminating.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: Closed and terminated timer requester thread.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: Timing RTP thread terminated.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: new RTSP connection.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: new RTSP connection.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: RTSP connection closed.
Dec 24 15:32:41 raspberrypi shairport-sync[16882]: closing RTSP connection.
Dec 24 15:32:42 raspberrypi shairport-sync[16882]: Play connection from user agent "AirPlay/250.10".
Dec 24 15:32:42 raspberrypi shairport-sync[16882]: Active-Remote string seen: "2993187347".
Dec 24 15:32:42 raspberrypi shairport-sync[16882]: DACP-ID string seen: "3D571F054E5FBC0D".
Dec 24 15:32:42 raspberrypi shairport-sync[16882]: Connection from IPv6: fe80::8638:35ff:fe63:f874:59328
Dec 24 15:32:42 raspberrypi kernel: [623548.502045] usb 1-1.2: 1:1: cannot get freq at ep 0x5
```

**Comment by mikebrady** [comment]
Thanks. So you're saying that the events corresponded to a noise?

**Comment by brbrr** [comment]
yup, this is all I got in syslog for noise start

**Comment by mikebrady** [comment]
So it looks like an end of a play session followed by an immediate start of another one. Interesting.

**Comment by mikebrady** [comment]
Couple more questions. 1: When the noise comes, is it a short burst or does it do on for a while? 2: Are you using the `general` `volume_range_db` setting, and if so, what is it? Thanks.

**Comment by brbrr** [comment]
1. Noise is remaining there until I disconnect from AirPlay. After reconnection it works clear.
2. `volume_range_db` is from shairport `.conf` file? I do not set any custom settings. I use default `.conf` file but with changed name. 

in addition, here is how I configure build: `$ ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemv`

**Comment by mikebrady** [comment]
Struggling with this – I can't get it to happen for me. I've put in an extra audio device reset and also a short delay (100 mS) after stopping a session to [maybe] ensure the device is really reset and hasn't got junk left in a buffer somewhere... I've put it in a new branch called `ik`, so if you got a chance to try it, that would be great.

**Comment by brbrr** [comment]
testing `ik` branch. 4+ hours - good so far.

also, I forgot to mention. I'm using Weezy sd card replaced from my rPI1. So OS was installed on rPI1 B+ and there could be some packages compiled for B+. But I have no problems so far - that's why I did not do clean install.

**Comment by mikebrady** [comment]
Thanks for your work on this.

**Comment by brbrr** [comment]
reproduced. so `ik` branch didn't fix that issue

**Comment by mikebrady** [comment]
Fair enough, thanks.

**Comment by brbrr** [comment]
Hi Mike,

I've tried latest 2.8.0 build, and issues still reproducible there, BUT volume level is recovered to it's original after I mute/unmute sound. 

Here is a log:

```
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Too-short retransmitted audio packet received in control port, ignored.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
Feb  2 13:43:51 raspberrypi shairport-sync[29659]: Aliasing of buffer index -- reset.
Feb  2 13:43:53 raspberrypi shairport-sync[29659]: Player: packets out of sequence: expected: 3578, got: 4090, sync error: 0 frames.
Feb  2 13:43:53 raspberrypi shairport-sync[29659]: Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5691.
Feb  2 13:43:53 raspberrypi kernel: [1127386.941286] usb 1-1.4: 1:1: cannot get freq at ep 0x5
```

regarding that new build: I started to got some kind of interruptions, like network delays. 
in logs it looks like:

```
Feb  2 13:43:42 raspberrypi shairport-sync[29659]: Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
Feb  2 13:43:43 raspberrypi shairport-sync[29659]: Aliasing of buffer index -- reset.
Feb  2 13:43:45 raspberrypi shairport-sync[29659]: Player: packets out of sequence: expected: 2584, got: 3096, sync error: 0 frames.
Feb  2 13:43:45 raspberrypi shairport-sync[29659]: Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -6034.
Feb  2 13:43:45 raspberrypi kernel: [1127378.950970] usb 1-1.4: 1:1: cannot get freq at ep 0x5
```

Im not sure is it shairport, or my wifi connection problem, will try to use different wifi dongle.

**Comment by mikebrady** [comment]
Thanks for looking at this. I'm still working on fast clean termination and restart in the `development` branch, by the way, on the HEAD of the branch.

**Comment by brbrr** [comment]
Hi Mike

Looks like I found solution for my problem:

> If you're using a Raspberry Pi and notice the output isnt totally clean, some USB Audio adapters don't like USB-1.2 and produce crackling in the output. You can work around the problem by adding `dwc_otg.speed=1` to `/boot/cmdline.txt` and setting the USB ports to USB-1.1 mode.
[by adafruit](https://learn.adafruit.com/usb-audio-cards-with-a-raspberry-pi/troubleshooting)

made this change this morning together with update to latest dev build. So far - so good :)

**Comment by mikebrady** [comment]
That is very interesting! Thank you.

**Comment by joerg-krause** [comment]
Looks like a case for TROUBLESHOOTING...

**Comment by brbrr** [comment]
yea, but I would like to test it. I'll post here once I'll be happy with that fix

**Comment by mikebrady** [comment]
Pretty sure this has been fixed! Closing this inactive issue. Please open a new one if necessary.
