### ISSUE TITLE
[Problem]: run_this_before/after

### ISSUE THREAD

**Issue by JanLp** [mikebrady/shairport-sync#1584]
### What happened?

Nothing ;)

### Configuration Information.

I have a problem when I leave my home and there is an ongoing stream from my phone. The problem is that shairport-sync doesn't execute my script `home/home-user/script/amp_off.py`

It works perfectly when I am present and pause/stop a stream

### Check previous issues

- [x] Confirm

**Comment by mikebrady** [comment]
Thanks. Have you checked out the [guide](https://github.com/mikebrady/shairport-sync/blob/master/ADVANCED%20TOPICS/Events.md)?

**Comment by JanLp** [comment]
Yes, and thanks for the well written documentation.

The problem is that `"Active / Inactive Events"` does not change from `active` to `inactive` when I leave my home while a song is playing. The same applies if you put your phone in airplane mode while a song is playing, not that it's an everyday scenario, but just to test :)

**Comment by mikebrady** [comment]
Thanks. I’ll have to experiment a little 😬.

**Comment by mikebrady** [comment]
The Shairport Sync is not actually informed when a connection is actually broken. In particular, the TCP connection over which RTSP communication occurs is not closed. So, it seems I will have to experiment with the TCP `keep alive` functionality a bit...

**Comment by JanLp** [comment]
Thanks for the explanation :)

**Comment by JanLp** [comment]
I don't know, but could a temporary solution be to create an automation in HomeKit that stops/pauses an ongoing stream? I ask because I have three girls who are particularly happy to play via shairport and my amplifier (classd), which probably doesn't use a lot of power. But still, it's a shame to discover that it's on 😊

**Comment by mikebrady** [comment]
I'm not really familiar with HomeKit, TBH, but sounds like it's worth a try. I'll be experimenting with this `keepalive` stuff in the next few days, I hope.

**Comment by JanLp** [comment]
Of course... I won't be home until Friday, but I'll switch to development and give feedback when I get home. And thanks :)

**Comment by JanLp** [comment]
I came home earlier and tested the latest version. It works perfectly. I can't thank you enough 👏

**Comment by JanLp** [comment]
My English is unfortunately not that good, but I will try to describe what I experience. If I play from a playlist and leave my home, or disable wifi, then everything is as expected.
And here's where it gets a little tricky for me...I think/know it's an Apple thing. But when the last song in my playlist is played, Apple Music continues to play similar music (which annoys me and can't be disabled?) But the result is that my stream continues, even if I'm not at home, which then make shairport "active"
Unfortunately, I have not had the opportunity to check whether the same applies to my HomePod mini

**Comment by mikebrady** [comment]
Yeah, I guess that this must be an Apple “feature”. Maybe some other readers know more about this…

**Comment by JanLp** [comment]
I have figured it out. and yet I'm a little confused

![IMG_0013](https://user-images.githubusercontent.com/55313117/205349655-f8f936bf-448b-4a1d-9b1e-223a55311909.jpeg)
