### ISSUE TITLE
[Problem]: No audio after first song; source still shows playing, no errors

### ISSUE THREAD

**Issue by rogersmj** [mikebrady/shairport-sync#1586]
### What happened?

When playing from Apple Music (iPhone) to a Shairport Sync instance, the audio will no longer be heard once the first song ends -- but the source device still shows as playing. This is reproducible 100% of the time. It will go from song to song as if it's still being output, but no sound is heard. Tapping pause/play or skipping ahead to the next song does not fix the issue.

Going to the AirPlay sheet and toggling the Shairport Sync target on/off will fix the issue for the remainder of the current song, but then it will go silent again when it moves onto the next song.

When Shairport Sync is being used in parallel with other AP2 endpoints -- like an Apple TV -- the music continues to be heard on the other endpoints, while the speakers being driven from Shairport Sync are silent (until it is toggled on/off in the AirPlay sheet).

I'm using the master branch in a Docker container (because my intention is to have multiple Docker containers running SPS, each linked to a different Pulse Audio sink). I do not see any errors in the docker container log, but am not sure where else I should be looking (not super familiar with Docker).

### Configuration Information.

/home/shairport-sync # shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux a9e5b33adf83 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l Linux

From /etc/os-release:
 Alpine Linux v3.12

Shairport Sync Version String:
 4.1-5-g029baf2b-dirty-AirPlay2-alac-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Main Floor";
   output_backend = "pa";
 };
 pa : 
 {
   sink = "FirstFloor";
 };
 metadata : 
 {
   enabled = "yes";
   include_cover_art = "yes";
   cover_art_cache_directory = "/tmp/shairport-sync/.cache/coverart";
   pipe_name = "/tmp/shairport-sync-metadata";
   pipe_timeout = 5000;
 };
 mqtt : 
 {
   enabled = "yes";
   hostname = "192.168.2.2";
   port = 1883;
   username = "shairport";
   password = "==REDACTED==";
   topic = "shairport/mainfloor";
   publish_raw = "yes";
   publish_parsed = "yes";
   publish_cover = "yes";
   enable_remote = "yes";
 };

>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. It would be worth changing over to the `development`-tagged Docker version, as a similar issue has been identified and apparently fixed -- please see [#1580](https://github.com/mikebrady/shairport-sync/issues/1580).

**Comment by rogersmj** [comment]
Thanks @mikebrady . It does indeed seem like it might be related to #1580. I changed my docker image to use the development branch and the issue has been resolved.
