### ISSUE TITLE
[Problem]: Airplay Volume Getting Reset

### ISSUE THREAD

**Issue by EntilZha** [mikebrady/shairport-sync#1592]
### What happened?

My setup/steps are:
1. Shairport-sync is running on a raspberry pi
2. The Pi is connected to a DAC via USB, that has its own physical volume knob
3. Hence, ideally, I want the volume on the Pi itself as well as the audio level set on iPhone airplay to be max

What I am finding is that whenever I connect, the airplay volume on iPhone is pretty low, so I have to max it out each time. Is there a way to configure the default airplay volume on shairport/ios or have it remember the prior setting?

Awesome package, it's a total game changer for my setup (old setup was an old iPhone, so walking to it each time to change tracks)!

### Configuration Information.

```
pi@raspberrypi:~ $ shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.1.1-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

The Configuration file contains no active settings.

>> Display Config End.
>> Goodbye!
```

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post and the encouraging words.

You can directly control the hardware mixer of the output device from Shairport Sync, thus from iOS, and the AirPlay 2 protocol seems to ask Shairport Sync to remember the last audio level used for when it uses it again. Please take a look at [InitialConfiguration.md](https://github.com/mikebrady/shairport-sync/blob/master/ADVANCED%20TOPICS/InitialConfiguration.md) for a guide.

**Comment by EntilZha** [comment]
Thanks for the pointer. For future people (or me after I forget...), I ended up using `shairport-sync -X` to see that the config file was in `/etc/shairport-sync.conf`, looked through that, and in the `general` setting block changed `ignore_volume_control = "yes"`. Although the volume slider isn't at 100% on iPhone, it does play at 100%, achieving what I wanted (only DAC knob controlling volume).
