### ISSUE TITLE
[Problem]: cannot get airplay2 to work with tinysvcmdns

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [mikebrady/shairport-sync#1603]
### What happened?

Running shairport-sync with avahi does work as an airplay 2 receiver properly.
With tinysvcmdns, it works only as an airplay 1 receiver.

Looking at the mDNS records, below, the first "nightingale" uses avahi, the second one below uses tiny.

<img width="530" alt="Screenshot 2022-12-26 at 9 50 07 PM" src="https://user-images.githubusercontent.com/19539395/209619744-47a6c9ee-cf49-429c-856d-16f261b6abbd.png">

Furthermore, looking into https://github.com/mikebrady/shairport-sync/commit/3a02b79a622e96ee6cc0054480e460075640229d it seems from a distance that the avahi implementation was changed to accomodate more flexible txtrecords, while the other implementations (tiny, dnssd, external) were not...

Am I reading this ^ correctly?

Is this saying that only the avahi implementation is working for Airplay 2 at the moment?

### Configuration Information.

4.1.1-AirPlay2-alac-mbedTLS-tinysvcmdns-ALSA-stdout-pipe-metadata-mqtt-sysconfdir:/config

4.1.1-dirty-AirPlay2-alac-OpenSSL-Avahi-ALSA-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Yes, AirPlay 2 operation requires Avahi.

**Comment by dubo-dubon-duponey** [comment]
Thanks @mikebrady 
How hard would you say it would be to make it work for tiny?
If you think this is not too involved, happy to give it a shot.

**Comment by mikebrady** [comment]
Thanks. TBH I haven’t looked too closely at it — until recently, the effort was focused on getting some AirPlay 2 functionality working. One of the problems with tinysvcmdns is that it’s not being maintained any more and seems to have security issues. Another, if I’m not mistaken, is that it doesn’t do IPv6. So not sure it’s worth while, TBH.

**Comment by dubo-dubon-duponey** [comment]
Thanks.
I am interested in an alternative to avahi (for linux containers).
Will look into possible replacements for tiny then.
