### ISSUE TITLE
[Problem]: Configure not finishing

### ISSUE THREAD

**Issue by guussie** [mikebrady/shairport-sync#1614]
### What happened?

When running ./configure I get the following message:

checking for libplist... no
checking for libplist... no
configure: error: AirPlay 2 support requires libplist 2.0.0 or later -- search for pkg libplist-dev on Debian or libplist-2.2.0 or later on FreeBSD!

I am installing on a Raspberry Pi 3B+. I did the same install on another Raspberry Pi 3B+ yesterday and didn't have this issue.

I am installing the AirPlay2 version.

### Configuration Information.

Not available in the system I am troubleshooting. 

Below you find the output for a system with the same hardware where I successfully installed Shairport-sync

>> Display Config Start.

From "uname -a":
 Linux dining 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Plus Rev 1.3

Shairport Sync Version String:
 4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

The Configuration file contains no active settings.

>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by spiro-c** [comment]
you have probably not installed the dependencies for AirPlay2 but for classic  so just reinstall them
