### ISSUE TITLE
[Problem]: Low Sound Volume with RaspBerry PI

### ISSUE THREAD

**Issue by schechin47312** [mikebrady/shairport-sync#1615]
### What happened?

When shairport is started on Pi, sound redirected from my iphone to the shairport server running on Pi, we cannot hear sound using Hallo Boss DAC

### Relevant log output

```shell
$ shairport-sync -V
4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

shairport-sync -v -c /etc/shairport-sync.conf
         0.004341406 "shairport.c:2200" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "b8:27:eb:10:8c:d5".
         0.000220729 "shairport.c:2239" Version String: "4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000060990 "shairport.c:2258" Command Line: "shairport-sync -v -c /etc/shairport-sync.conf".
         0.000178906 "shairport.c:2265" libsodium initialised.
         0.000789271 "shairport.c:2290" libgcrypt initialised.
         0.000058125 "shairport.c:2294" Log Verbosity is 1.
         0.000072968 "audio_alsa.c:1031" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000131980 "audio_alsa.c:1320" alsa: disable_standby_mode is "never".
         0.000046979 "audio_alsa.c:1324" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000048906 "audio_alsa.c:1326" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000109063 "audio_alsa.c:1366" alsa: output device name is "hw:BossDAC".
         0.000365885 "shairport.c:2342" disable_resend_requests is off.
         0.000059323 "shairport.c:2343" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000053489 "shairport.c:2347" statistics_requester status is 0.
         0.000047605 "shairport.c:2352" rtsp listening port is 7000.
         0.000046979 "shairport.c:2353" udp base port is 6001.
         0.000043177 "shairport.c:2354" udp port range is 10.
         0.000043177 "shairport.c:2355" player name is "BO".
         0.000042969 "shairport.c:2356" backend is "alsa".
         0.000043229 "shairport.c:2357" run_this_before_play_begins action is "(null)".
         0.000044427 "shairport.c:2358" run_this_after_play_ends action is "(null)".
         0.000044323 "shairport.c:2359" wait-cmd status is 0.
         0.000043177 "shairport.c:2360" run_this_before_play_begins may return output is 0.
         0.000044375 "shairport.c:2361" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000044271 "shairport.c:2363" run_this_before_entering_active_state action is  "(null)".
         0.000044948 "shairport.c:2365" run_this_after_exiting_active_state action is  "(null)".
         0.000044531 "shairport.c:2367" active_state_timeout is  10.000000 seconds.
         0.000050885 "shairport.c:2368" mdns backend "(null)".
         0.000043646 "shairport.c:2370" interpolation setting is "auto".
         0.000043594 "shairport.c:2374" interpolation soxr_delay_threshold is 30000000.
         0.000044323 "shairport.c:2375" resync time is 0.050000 seconds.
         0.000045729 "shairport.c:2376" allow a session to be interrupted: 0.
         0.000043698 "shairport.c:2377" busy timeout time is 0.
         0.000043229 "shairport.c:2378" drift tolerance is 0.001995 seconds.
         0.000045938 "shairport.c:2379" password is "(null)".
         0.000042395 "shairport.c:2380" ignore_volume_control is 0.
         0.000043542 "shairport.c:2384" volume_max_db is not set
         0.000042240 "shairport.c:2385" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000045885 "shairport.c:2387" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000046563 "shairport.c:2391" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000046093 "shairport.c:2393" disable_synchronization is 0.
         0.000043021 "shairport.c:2394" use_mmap_if_available is 1.
         0.000043229 "shairport.c:2395" output_format automatic selection is enabled.
         0.000044167 "shairport.c:2399" output_rate automatic selection is enabled.
         0.000043802 "shairport.c:2403" audio backend desired buffer length is 0.200000 seconds.
         0.000047083 "shairport.c:2405" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000048646 "shairport.c:2407" audio backend latency offset is 0.000000 seconds.
         0.000046875 "shairport.c:2409" audio backend silence lead-in time is "auto".
         0.000043125 "shairport.c:2413" zeroconf regtype is "_raop._tcp".
         0.000043907 "shairport.c:2414" decoders_supported field is 1.
         0.000043281 "shairport.c:2415" use_apple_decoder is 0.
         0.000043021 "shairport.c:2416" alsa_use_hardware_mute is 0.
         0.000043125 "shairport.c:2420" no special mdns service interface was requested.
         0.000087500 "shairport.c:2423" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000053333 "shairport.c:2453" loudness is 0.
         0.000044427 "shairport.c:2454" loudness reference level is -20.000000
         0.000243542 "shairport.c:2464" size of hw_addr is 8.
         0.006220052 "shairport.c:2547" NQPTP is online.
         1.511843020 "shairport.c:254" "soxr" interpolation has been chosen.
         8.060959945 "rtsp.c:2883" Connection 1: AP2 PTP connection from fe80::83:88bc:5655:be87:58648 ("iPhone de Stephane") to self at fe80::d02f:59ea:4677:980c:7000.
         0.066759792 "rtsp.c:4330" Connection 1: Current volume (-24.000000) requested
         4.590502914 "rtsp.c:3294" Connection 1. AP2 Buffered Audio Stream.
         0.012045157 "audio_alsa.c:933" *warning: The hardware mixer specified -- "PCM" -- does not have a dB volume scale.
         0.000484687 "audio_alsa.c:950" alsa: hardware mixer "PCM" selected, with dB volume from -90.200000 to -8.600000.
volume is now -24.000000
volume is now -23.088923
volume is now -20.173470
volume is now -18.788630
volume is now -10.734694
volume is now -6.871719
volume is now 0.000000
```

### Configuration Information.

hairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Plus Rev 1.3

Shairport Sync Version String:
 4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "BO";
   output_backend = "alsa";
   run_this_when_volume_is_set = "/bin/echo volume is now";
 };
 alsa : 
 {
   output_device = "hw:BossDAC";
   mixer_control_name = "PCM";
 };

>> Display Config End.
>> Goodbye!

aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=BossDAC,DEV=0
    BossDAC, Boss DAC HiFi [Master] pcm512x-hifi-0
    Direct hardware device without any conversions
plughw:CARD=BossDAC,DEV=0
    BossDAC, Boss DAC HiFi [Master] pcm512x-hifi-0
    Hardware device with all software conversions
default:CARD=BossDAC
    BossDAC, Boss DAC HiFi [Master] pcm512x-hifi-0
    Default Audio Device
sysdefault:CARD=BossDAC
    BossDAC, Boss DAC HiFi [Master] pcm512x-hifi-0
    Default Audio Device
dmix:CARD=BossDAC,DEV=0
    BossDAC, Boss DAC HiFi [Master] pcm512x-hifi-0
    Direct sample mixing device
usbstream:CARD=BossDAC
    BossDAC
    USB Stream Output

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. It’s worth checking with `alsamixer` to see that the mixer `PCM` is not muted and is responding to volume control changes on the iPhone. It should respond in real time to iPhone volume changes when audio is directed to it.

**Comment by schechin47312** [comment]
Thanks Mike.
![Capture d’écran 2023-01-11 à 15 05 05](https://user-images.githubusercontent.com/122375015/211826715-998ff08e-d4ef-4b71-b5f5-fe55d4f4f950.png)

Here attached screenshot of aslamixer : for me PCM is not muted and changes when Iphone volume changes.

hereunder the statistics :
$shairport-sync -v -c /etc/shairport-sync.conf --statistics
         0.001999636 "shairport.c:2200" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "b8:27:eb:10:8c:d5".
         0.000126458 "shairport.c:2239" Version String: "4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000029323 "shairport.c:2258" Command Line: "shairport-sync -v -c /etc/shairport-sync.conf --statistics".
         0.000085989 "shairport.c:2265" libsodium initialised.
         0.000374584 "shairport.c:2290" libgcrypt initialised.
         0.000028646 "shairport.c:2294" Log Verbosity is 1.
         0.000057916 "audio_alsa.c:1031" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000062344 "audio_alsa.c:1320" alsa: disable_standby_mode is "never".
         0.000020052 "audio_alsa.c:1324" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000021042 "audio_alsa.c:1326" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000048333 "audio_alsa.c:1366" alsa: output device name is "hw:BossDAC".
         0.000217448 "shairport.c:2342" disable_resend_requests is off.
         0.000029948 "shairport.c:2343" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000023854 "shairport.c:2347" statistics_requester status is 1.
         0.000017604 "shairport.c:2352" rtsp listening port is 7000.
         0.000019063 "shairport.c:2353" udp base port is 6001.
         0.000016979 "shairport.c:2354" udp port range is 10.
         0.000016667 "shairport.c:2355" player name is "BO".
         0.000019479 "shairport.c:2356" backend is "alsa".
         0.000016927 "shairport.c:2357" run_this_before_play_begins action is "(null)".
         0.000017500 "shairport.c:2358" run_this_after_play_ends action is "(null)".
         0.000018385 "shairport.c:2359" wait-cmd status is 0.
         0.000017292 "shairport.c:2360" run_this_before_play_begins may return output is 0.
         0.000018854 "shairport.c:2361" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000019271 "shairport.c:2363" run_this_before_entering_active_state action is  "(null)".
         0.000019271 "shairport.c:2365" run_this_after_exiting_active_state action is  "(null)".
         0.000019166 "shairport.c:2367" active_state_timeout is  10.000000 seconds.
         0.000022865 "shairport.c:2368" mdns backend "(null)".
         0.000018854 "shairport.c:2370" interpolation setting is "auto".
         0.000017604 "shairport.c:2374" interpolation soxr_delay_threshold is 30000000.
         0.000017500 "shairport.c:2375" resync time is 0.050000 seconds.
         0.000019740 "shairport.c:2376" allow a session to be interrupted: 0.
         0.000018594 "shairport.c:2377" busy timeout time is 0.
         0.000017187 "shairport.c:2378" drift tolerance is 0.001995 seconds.
         0.000019792 "shairport.c:2379" password is "(null)".
         0.000018437 "shairport.c:2380" ignore_volume_control is 0.
         0.000077396 "shairport.c:2384" volume_max_db is not set
         0.000019323 "shairport.c:2385" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000023386 "shairport.c:2387" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000018541 "shairport.c:2391" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000018594 "shairport.c:2393" disable_synchronization is 0.
         0.000016875 "shairport.c:2394" use_mmap_if_available is 1.
         0.000016667 "shairport.c:2395" output_format automatic selection is enabled.
         0.000017031 "shairport.c:2399" output_rate automatic selection is enabled.
         0.000017031 "shairport.c:2403" audio backend desired buffer length is 0.200000 seconds.
         0.000020156 "shairport.c:2405" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000019323 "shairport.c:2407" audio backend latency offset is 0.000000 seconds.
         0.000020209 "shairport.c:2409" audio backend silence lead-in time is "auto".
         0.000017291 "shairport.c:2413" zeroconf regtype is "_raop._tcp".
         0.000017344 "shairport.c:2414" decoders_supported field is 1.
         0.000017292 "shairport.c:2415" use_apple_decoder is 0.
         0.000016823 "shairport.c:2416" alsa_use_hardware_mute is 0.
         0.000018541 "shairport.c:2420" no special mdns service interface was requested.
         0.000048386 "shairport.c:2423" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000023333 "shairport.c:2453" loudness is 0.
         0.000018698 "shairport.c:2454" loudness reference level is -20.000000
         0.000143385 "shairport.c:2464" size of hw_addr is 8.
         0.005571198 "shairport.c:2547" NQPTP is online.
         1.506040833 "shairport.c:254" "soxr" interpolation has been chosen.
        10.596588850 "rtsp.c:2883" Connection 1: AP2 PTP connection from fe80::83:88bc:5655:be87:60662 ("iPhone de Stephane") to self at fe80::d02f:59ea:4677:980c:7000.
         0.034028333 "rtsp.c:4330" Connection 1: Current volume (-24.000000) requested
        10.377401559 "rtsp.c:3294" Connection 1. AP2 Buffered Audio Stream.
         0.012199635 "audio_alsa.c:933" *warning: The hardware mixer specified -- "PCM" -- does not have a dB volume scale.
         0.000489427 "audio_alsa.c:950" alsa: hardware mixer "PCM" selected, with dB volume from -90.200000 to -8.600000.
         1.191408698 "player.c:2774" Connection 1: Playback started at frame 3629909262 -- AirPlay 2 Buffered.
         7.916900257 "player.c:2591" Sync Error ms | Net Sync PPM | All Sync PPM | Min DAC Queue | Min Buffers | Min Buffer Size | Output FPS (r) | Output FPS (c)
         0.000134896 "player.c:2591"         -0.77            0.0            0.0            7361            46              251k              N/A              N/A
         8.000940310 "player.c:2591"         -0.84            0.0            0.0            7363            46             3729k         44100.23         44100.42
         8.033003122 "player.c:2591"         -0.61            0.0            0.0            7381            46             3757k         44100.22         44100.42
         7.985206819 "player.c:2591"         -0.60            0.0            0.0            7381            46             3593k         44100.23         44100.43

**Comment by mikebrady** [comment]
Thanks. It looks as if Shairport Sync is indeed able to control the `PCM` mixer and audio is indeed getting through. Could you experiment by leaving `PCM` at 100% and controlling the `Digital` mixer instead?

Just FYI, here is a different device, and IQaudIO DigiAmp+, but you can see a somewhat similar
set of controls. The `Digital` control is the one that works here.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/4265913/211835800-f73d2e23-f9f2-4091-a638-5b9f7d818cdf.png">
