### ISSUE TITLE
[Problem]: iPhone Stuck in Pinwheel When Disconnecting from Multiple SSync Airplay2 Connections

### ISSUE THREAD

**Issue by YutongGu** [mikebrady/shairport-sync#1616]
### What happened?

I am running multiple instances of Airplay2 on my device and they appear fine in the iPhone control center. I can connect to multiple at once and disconnect from them one by one. However, when I try to disconnect from more than one at a time, it causes the page to pinwheel indefinitely. I am then unable to initiate any new Airplay2 connections from the control center.

Oddly enough, I am able to do it still from the Spotify app's built in Airplay menu.

iOS: 16.1.1
NQPTP git hash: c91a2bb209646c3253eed1d32d56614902380fda
Shairport-sync git hash: 250704b280fa428807dffa22079a93938586a879

These instances are also not isolated within their own docker container and are instead instantiated with unique device ids.

To reproduce:

1. Launch two instances of shairport-sync with airplay2 enabled on the same network
2. Connect to both within the control center
3. Select the 'iPhone' option as output to disconnect from both instances simultaneously.
4. Attempt to reselect one of the shairport-sync airplay2 instances

### Configuration Information.

Linux jukeaudio 4.14.114-v7 #1 SMP Tue Jul 30 13:37:58 UTC 2019 armv7l armv7l armv7l GNU/Linux
5.3.9-OpenSSL-Avahi-ALSA-stdout-pipe-metadata-sysconfdir:/etc

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by YutongGu** [comment]
The same happens with NQPTP githash fd95eb5 and Shairport Sync githash ceb3331

**Comment by YutongGu** [comment]
I've just tested the same running the latest 4.1.1 version of shairport-sync on two separate devices and observed the same behavior.

It seems that the issue may be that the iPhone enters into a bad state after attempting to disconnect from multiple shairport-sync instances at once. I have not observed this with other Airplay2 devices such as my TVs, however. When my phone enters into this state, I am unable to even connect to my TVs via Airplay2.

**Comment by mikebrady** [comment]
Thanks for the post. I have seen this behaviour with only one instance of Shairport Sync, and I believe it's an AirPlay 2 bug. IIRC it also happens occasionally with a HomePod mini. Generally, I have to restart the iPhone to get rid of the problem.

**Comment by YutongGu** [comment]
Thanks for getting back to me. We can reproduce it 100% of the time when disconnecting simultaneously from a Shairport Sync instance and an official Airplay2 device (Samsung TV) but haven't been able to when airplaying to a pair of official Airplay2 device.  While it may well be a bug on Apple's side, the issue is exacerbated when Shairport Sync is involved.

It seems like the issue happens at teardown, so could it be possible that Shairport Sync is sending a response on teardown that the iPhone does not expect, causing it to enter into that state?

**Comment by mikebrady** [comment]
Thanks — I’ll play around a bit more and see if I can reproduce it.

**Comment by mikebrady** [comment]
Hmm, I haven't been able to reproduce this issue with Shairport Sync and either an AppleTV or a HomePod mini, I'm afraid. As I wrote above, it does seem to happen occasionally and unpredictably. Another thing is that Bonjour/Zeroconf is involved, and some routers and WiFi systems occasionally have problems with this protocol.

Of course we don't have a specification for the AirPlay or AirPlay 2 protocols, so it's a lot of guesswork.

**Comment by YutongGu** [comment]
Got it. Thanks for trying it out. It appears after updating to ceb3331 on Shairport Sync we were able to disconnect simultaneously from the Samsung TV and Airplay2 instance. So that's not an issue. The issue still remains when disconnecting simultaneously from two Shairport Sync instances (on different devices) 

Did you also test with disconnecting from an instance of Airplay2 on two different devices? I'm sure this is also a common set up and this is where we had the most issue.

**Comment by mikebrady** [comment]
Thanks, yeah — I'll keep playing around with it. It can be irritating.

**Comment by mikebrady** [comment]
Thanks again for bringing this issue to notice. Your observation is correct: when two Shairport Sync devices are disconnected simultaneously by the client, the client (iOS device) hangs up and the pinwheels start. The problem can only be cleared by restarting the client. However, it can be avoided by disconnecting devices one at a time. The cause is not known but could be some kind of protocol issue. Unfortunately, we don't have a specification for the protocol.

**Comment by YutongGu** [comment]
Thank you for confirming. I'd like to try taking a crack at this as it's quite a bit undesirable. Do you have a hunch what the issue might be so I know where to start looking? Also, do know of anyone else who may be able to help in these efforts?

**Comment by mikebrady** [comment]
I'm afraid I don't have any sensible suggestions -- maybe some other users have some ideas.
