### ISSUE TITLE
[Problem]: Shairpot Sync and NQPTP Version incompatibility

### ISSUE THREAD

**Issue by danielsteiner** [mikebrady/shairport-sync#1621]
### What happened?

I just installed shairport sync in AP2 mode & NQPTP from scratch on a fresh raspbian install. Shaiport-Sync refuses to work because the version is incompatibl with the installed (latest dev) version of NQPTP. 

Shairport: 4.1-dev-867-ga6c66db2-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sys
NQPTP: Version: 1.1-dev-171-gad384f9. Shared Memory Interface Version: 8.

### Relevant log output

```shell
sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-01-25 11:20:32 CET; 2min 29s ago
   Main PID: 643 (shairport-sync)
      Tasks: 12 (limit: 1830)
        CPU: 5.642s
     CGroup: /system.slice/shairport-sync.service
             └─643 /usr/local/bin/shairport-sync --log-to-syslog

Jan 25 11:20:32 bedroom systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Jan 25 11:21:16 bedroom shairport-sync[643]: warning: This version of Shairport Sync is not compatible with the installed version of NQPTP. Please update.
```

### Configuration Information.

>> Display Config Start.

From "uname -a":
 Linux bedroom 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 4 Model B Rev 1.1

Shairport Sync Version String:
 4.1-dev-867-ga6c66db2-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   name = "Bedroom";
 };
 alsa :
 {
   output_device = "hw:Headphones";
   mixer_control_name = "Headphone";
 };

>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. The thing is that _both_ NQPTP and Shairport Sync must be checked out in their `development’ branches.

**Comment by danielsteiner** [comment]
Thanks for the reply, makes sense but that’s left out in the guide. Maybe update the guides? NQPTP building guide states that the dev branch must be checked out, the Shaiport one doesn’t.

**Comment by mikebrady** [comment]
Thanks — I’ll review the docs.

**Comment by danielsteiner** [comment]
I can confirm, that recompiling NQPTP from the dev branch fixed this issue.

**Comment by roboterm** [comment]
Unfortunately it doesn’t work for me.  
even if I completely remove nqptp and shairport and make a fresh install from development branches i m getting the incompatibility warning message.  
Also not output on the shairport. 
A few days ago everything worked fine. After I updated shairport to the last commit it’s broken.

**Comment by danielsteiner** [comment]
I don’t get Incompatibility issues anymore but after a reboot I don’t get any output either. Didn’t look further into it after closing this issue tough

**Comment by roboterm** [comment]
I downgraded to 8201903a.  
This solved my issue.

**Comment by mikebrady** [comment]
That’s for this information. I’ll see what might have made a difference, but it’ll be a few days…

**Comment by mikebrady** [comment]
Just following up on this, https://github.com/mikebrady/shairport-sync/commit/8201903a4e5f32919a985dc6e5b375f4b19b69db uses the previous version of NQPTP. So my guess is that somehow there are multiple copies of NQPTP and/or Shairport Sync floating around.

You can use the `$ which` command  to locate them.

**Comment by roboterm** [comment]
I did use the which command to make sure everything was completely removed before the fresh installations.

**Comment by mikebrady** [comment]
Thanks. It's a mystery. I'll keep monitoring it...
