### ISSUE TITLE
[Problem]: HomePod (mini) unable to connect to shairport hub to play music

### ISSUE THREAD

**Issue by carterdacat** [mikebrady/shairport-sync#1627]
### What happened?

HomePod (mini) unable to connect to shairport hub to play music, when I ask it to "play in the kitchen". I've tried to go into and control the speaker, selected the homepod, and tried to add the shairport speaker but it just doesn't add, spins for a minute then returns not to set.  I can manually select both from my phone if the audio is coming from my phone. I can upload screen recordings as well if needed.

### Configuration Information.

From "uname -a":
 Linux speakers 5.15.0-1022-raspi #24-Ubuntu SMP PREEMPT Mon Dec 5 09:58:33 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

From /etc/os-release:
 Ubuntu 22.04.1 LTS

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 4 Model B Rev 1.2

Shairport Sync Version String:
 4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

The Configuration file contains no active settings.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Super. So, I have speakers called, say, `Speakers` and in the Home app I have put them in a room called `Kitchen`. Then I can say something like `Hey Siri, play some music in the kitchen please.` and it works.

What's important is that I refer to the room, not the speakers themselves. Would that work for you?

**Comment by carterdacat** [comment]
To update, I am home now and I've attempted to add it back again after removing and now it errors ![image](https://user-images.githubusercontent.com/56525188/217364137-a5bc6b29-a592-4a7d-906b-61fde389c6ac.png)

**Comment by carterdacat** [comment]
Restart fixed the error, https://user-images.githubusercontent.com/56525188/217365633-3602c9f5-5997-4f2f-bedc-a128f595f110.MOV

Here is video of me trying to connect
