### ISSUE TITLE
[Problem]: 

### ISSUE THREAD

**Issue by Suspect-byte** [mikebrady/shairport-sync#1641]
### What happened?

The log says enough. I did everything that I know. Im running it from a synology dsm 7.1. Hopefully someone knows what toi do

### Configuration Information.

uname -a : Linux mikebrady-shairport-sync1 4.4.180+ #42962 SMP
shairport-sync -V: 4.1.1-dirty-airplay2-alac-OpenSSL-Avahi-ALSA-dummy-stdout-pipe-soxr-convution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

### How did you install Shairport Sync?

Docker

### Check previous issues

- [x] Confirm

**Comment by mikebrady** [comment]
I’m afraid I can not understand anything here apart from an apparent Bonjour naming problem. Some network or system configuration  problem??

**Comment by Suspect-byte** [comment]
@mikebrady I found something. There isnt a /dev/snd in my system.... so he cant link it to anywhere. So i think my synology doesnt understand it someway
