### ISSUE TITLE
[Problem]: Shairport does not activate with systemctl 

### ISSUE THREAD

**Issue by jackgraddon** [mikebrady/shairport-sync#1644]
### What happened?

After following the build instructions in BUILD.md, I was met with no errors. However, upon restarting, the service did not start. I checked other issues (mainly [this one](https://github.com/mikebrady/shairport-sync/issues/179)) if they experienced the same thing, and tried their solutions. 

Unfortunately, nothing seemed to work. Curious to see if the system service was running at all, I used `systemctl status shairport-sync` and was met with `Unknown operation shairport-sync.` I tried with the service created in the mentioned repo, and was met with the same response. 

The service does work, and run, but only when I manually open a terminal window and enter in `shairport-sync`. Everything works as expected, no issues there at all.

### Configuration Information.

>> Display Config Start.
From "uname -a":
Linux home-system 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34
UTC 2023 X86_64 X86_64 X86_64 GNU/Linux
From /etc/os-release I
Zorin OS 16.2
Shairport Sync Version String:
4.1.1-3-ga9fd294b-AirPlay2-OpenSSL-Avahi-ALSA-sox-sysconfdir: /etc
Command Line:
shairport-sync --displayConfig
Configuration File:
/etc/shairport-sync.conf
The Configuration file contains no active settings.
>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by jackgraddon** [comment]
If there is anything you wish to know please ask! I do however only have access to this system for a few more days.

**Comment by mikebrady** [comment]
Thanks for the post.  Does your system have a GUI? Does it have PulseAudio or PipeWire installed?

**Comment by jackgraddon** [comment]
System has a GUI, but does not have PulseAudio or PipeWire installed.

**Comment by jackgraddon** [comment]
Zorin does have the commands for systemd, but I suppose it is possible it isn’t actually using them in the OS. I’ll grab the logs in a little bit, away from the computer atm.

**Comment by jackgraddon** [comment]
Grabbed the log, it [can be downloaded here](https://dropover.cloud/e19a58).

**Comment by mikebrady** [comment]
Thanks for the log. There is no sign of Shairport Sync in it at all. So, are you certain that you followed the BUILD instructions to the bitter end? You can check, using something like this:
```bash
$ systemctl status shairport-sync
```
This is what I'm getting:
```bash
pi@RaspberryPi3B:~ $ systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-17 18:21:13 GMT; 14h ago
   Main PID: 653 (shairport-sync)
      Tasks: 12 (limit: 1596)
        CPU: 59.561s
     CGroup: /system.slice/shairport-sync.service
             └─653 /usr/local/bin/shairport-sync --log-to-syslog

Mar 17 18:21:13 RaspberryPi3B systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```
...and, FYI, this is what I'm getting for `nqptp`:
```bash
pi@RaspberryPi3B:~ $ systemctl status nqptp
● nqptp.service - NQPTP -- Not Quite PTP
     Loaded: loaded (/usr/local/lib/systemd/system/nqptp.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-17 18:21:13 GMT; 14h ago
   Main PID: 651 (nqptp)
      Tasks: 1 (limit: 1596)
        CPU: 4.802s
     CGroup: /system.slice/nqptp.service
             └─651 /usr/local/bin/nqptp -v

Mar 17 18:21:13 RaspberryPi3B systemd[1]: Started NQPTP -- Not Quite PTP.
Mar 17 18:21:13 RaspberryPi3B nqptp[651]:          0.001201823 "nqptp.c:166" Version: 1.1-dev-199-g2b5490c, SMI: 9. Clock ID: "b827ebfffed785d2".
```
You'll probably be running an older version of `nqptp`, so the version information may not appear, or may be different, but that's fine.

**Comment by jackgraddon** [comment]
Here’s what I get:
`shairport-sync.service - ShairportSync AirTunes receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-03-17 20:06:29 PDT; 11h ago
TriggeredBy: â— shairport-sync.timer
       Docs: man:shairport-sync(7)
             file:///usr/share/doc/shairport-sync/README.md.gz
             https://github.com/mikebrady/shairport-sync
    Process: 1620 ExecStart=/usr/bin/shairport-sync $DAEMON_ARGS (code=exited, status=203/EXEC)
   Main PID: 1620 (code=exited, status=203/EXEC)

Mar 17 20:06:29 home-system systemd[1]: shairport-sync.service: Scheduled restart job, restart counter is at 5.
Mar 17 20:06:29 home-system systemd[1]: Stopped ShairportSync AirTunes receiver.
Mar 17 20:06:29 home-system systemd[1]: shairport-sync.service: Start request repeated too quickly.
Mar 17 20:06:29 home-system systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
Mar 17 20:06:29 home-system systemd[1]: Failed to start ShairportSync AirTunes receiver.

nqptp.service - NQPTP -- Not Quite PTP
     Loaded: loaded (/usr/local/lib/systemd/system/nqptp.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-17 20:06:28 PDT; 11h ago
   Main PID: 1539 (nqptp)
      Tasks: 1 (limit: 18939)
     Memory: 476.0K
     CGroup: /system.slice/nqptp.service
             â””â”€1539 /usr/local/bin/nqptp

Mar 17 20:06:28 home-system systemd[1]: Started NQPTP -- Not Quite PTP.`

**Comment by mikebrady** [comment]
Great stuff, thanks. So, `systemd` is indeed installed. Now, to get a little more information about why Shairport Sync seems to be crashing, could you set the `log_verbosity` to `1` in the configuration file (not 2 or 3, please, and remember to uncomment that line!) and restart. The output from `$ systemctl status shairport-sync` log should be longer, and could be interesting.

PS: are you _certain_ that PulseAudio isn't installed?

**Comment by jackgraddon** [comment]
Got the same amount of information from that as I did with the first one, nothing new. Also, I suppose I’m not *certain* that PulseAudio isn’t installed.

And unfortunately, I won’t have access to this laptop for a few months (parents old laptop, they are not savvy enough to be able to do this on their own) so I will have to close this thread and either open or make a new issue when I’m back next.

Thank you for your support, though! I really appreciate it.
