### ISSUE TITLE
Compatiability with BeagleBoard-X15

### ISSUE THREAD

**Issue by ChadTaljaardt** [mikebrady/shairport-sync#165]
Hello,

i want to start off by saying thanks a lot for this project, i really love this program and use it on a daily basis. 

I just want to know if it will work with the BeagleBoard-X15 as i may be ordering one when its released.

Thanks

**Comment by mikebrady** [comment]
Thanks for the kind words. I'm afraid I don't really know whether it will be compatible with the BeagleBoard-X15. I guess so – it looks powerful enough and the audio subsystem seems to be well known, so likely to have `alsa` support. It looks like a nice board.

**Comment by ChadTaljaardt** [comment]
Yeah i really want to buy one but i really need this to be able to work on it as i want to move away from my pi for this project. 

I will see when i get it if it works or not :)
