### ISSUE TITLE
[Problem]: TuneBlade can only detect Shairport when downstairs

### ISSUE THREAD

**Issue by Miniontoby** [mikebrady/shairport-sync#1653]
### What happened?

So yesterday I set this thing up and it worked fine with TuneBlad
But today when I wanted to play some music, TuneBlade wasn't able to find my raspberry pi.

Then I went downstairs because I wanted to show my dad something and whilst I was waiting downstairs I tried looking again and then TuneBlade found my raspberry pi.

Then I went back upstairs and TuneBlade not found it again.

I also tried updating to AirPlay 2 to check if that would fix the problem, but it didn't.

Btw, when I add it manually it works, but I don't want to do that, cause then it gets stuck at "buffering" and will cause problems in the future with the setup of my home's router

### Relevant log output

_Not relevant and didn't have anything useful_

### Configuration Information.

```
>> Display Config Start.

From "uname -a":
 Linux kodipi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 10 (buster)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 4 Model B Rev 1.2

Shairport Sync Version String:
 4.1.1-5-g69d3b02a-AirPlay2-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 alsa : 
 {
   output_device = "hw:Headphones";
   mixer_control_name = "Headphone";
 };

>> Display Config End.
>> Goodbye!
```

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. Let me suggest you check that Wi-Fi Power Management is off. There might be other hints on the troubleshooting page.

**Comment by mikebrady** [comment]
Thanks. Then it sounds perhaps a bit like a networking issue. You can use a tool like `avahi-browse` to check that Shairport Sync is advertising to the network using Bonjour/Zeroconf. Then, at the phone end, if it was an iPhone you could use a tool like Discovery from TildeSoft to see if the advertisement can be seen. Maybe there’s something similar for Android.

**Comment by Miniontoby** [comment]
I am using Windows with TuneBlade to send to shairport-sync! I don't have iPhone or any Apple related thing. I just found this software when looking for Wireless Audio Streaming servers. But I will check `avahi-browse` and those things

**Comment by mikebrady** [comment]
Yeah so it looks as it Shairport Sync is being advertised alright — the first six lines. The question then is whether it’s being seen all the time at the TuneBlade end. I have used TuneBlade extensively in the past for testing — it’s a good product.

**Comment by Miniontoby** [comment]
> Yeah so it looks as it Shairport Sync is being advertised alright — the first six lines. The question then is whether it’s being seen all the time at the TuneBlade end. I have used TuneBlade extensively in the past for testing — it’s a good product.

I have now turned off the ipv6 and at first it didn't work, but then after some time it seemed to work, but now I am at school, so I cannot test it. I will be testing it at like 15:30 UTC+1 and will comment again.

Btw if I add it manually it also worked, but after 10 minutes it stopped working. So yeah I hope the auto detect will continue working.

**Comment by Miniontoby** [comment]
So update: It didn't detect it today!

**Comment by Miniontoby** [comment]
Does anyone have an idea how to fix it? I would really like to just be able to use a ready-to-use software to remotely play audio instead of writing my own python server-client thingy alternative.
