### ISSUE TITLE
[Problem]: Issues running on TrueNAS Scale Docker

### ISSUE THREAD

**Issue by adamef93** [mikebrady/shairport-sync#1656]
### What happened?

Receiving both of the errors below when trying to run shairport with the docker-compose app from truecharts. This only occurs when host networking is set. The container will launch without host networking declared, but isn't detected by my phone.

```
warning: could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i141" on the system bus.
warning: could not acquire an MPRIS interface named "org.mpris.MediaPlayer2.ShairportSync.i141" on the system bus.
```

### Configuration Information.

In initial description

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. These warnings are harmless -- they merely indicate that an Inter-Process Communication (IPC) protocol called D-Bus is not set up properly. All it means is that other programs can't communicate with it, but then they don't need to for Shairport Sync to function.

**Comment by adamef93** [comment]
The container isn't staying active, though.

**Comment by mikebrady** [comment]
Hmm, if it's exiting, if means Shairport Sync isn't happy about something. I don't know anything about Truecharts, I'm afraid, but it might be worth checking with them.
