### ISSUE TITLE
Stereo channels output to paired speakers

### ISSUE THREAD

**Issue by KirkAtLarc** [mikebrady/shairport-sync#166]
Thanks for your work in bringing synchronized streaming to Linux based sound devices!
It is working well for streaming music to two RPi based speakers and keeping them in sync.  I'm now wondering if it's possible to do stereo pairing with the speakers.  Is there a way to configure shairport-sync to pass just the left/right stereo channel audio data to an ALSA device?  I'm presuming that iTunes on my MBP is sending both channels to each RPi and that shairport-sync on each is mixing both channels into its ALSA device.  I'd like to output just the left or right channel, depending on a command line argument or a ~/.config/pianobar/config setting on each RPi.

**Comment by mikebrady** [comment]
Hi Kirk. At the moment, Shairport Sync does not offer the ability you are suggesting. It should be easy to add, so I'll try to add it to a future version. Thanks for the idea.

**Comment by allevi72** [comment]
Hi,
Is possibile to configure differente volume to lett and right channels ?
In this way I Couldreduce to zero Themis volume of right or lett channels.

**Comment by mikebrady** [comment]
Hi there. At present, Shairport Sync does not offer this functionality. I'll try to add it to future version.

**Comment by cre8dojo** [comment]
check out my comment here: https://github.com/mikebrady/shairport-sync/issues/186#issuecomment-192988054

**Comment by allevi72** [comment]
Hi Mike,
I am involved into audio project over openwrt platform and i'd like to use shairport sync.
Do you have a private email to discuss about enhancement?
My email is: allevi@allix.it

**Comment by mikebrady** [comment]
Shairport Sync still does not allow different volume controls on left and right channels, sorry. However, it does not offer left-only, right-only, reverse-stereo and mono.
Please open a new issue if necessary.
