### ISSUE TITLE
[Problem]: No audio after pausing for over 10 seconds, but CPU appears to be processing music

### ISSUE THREAD

**Issue by mklein9** [mikebrady/shairport-sync#1664]
### What happened?

On a fresh invocation of shairport-sync (Classic AirPlay), it works great, playing for as long as I send it music (from MacOS Music app). After pausing for more than 10 seconds, then resuming playing, Music app shows the song playing but no sound comes from the shairport-sync device. It appears it is receiving and thinks it is playing, because the CPU usage of shairport-sync rises back up to about 7-10% as if it were playing. Restarting shairport-sync always fixes the issue. Pausing playing for less than 10 seconds also does not impact playing, it responds as expected by continuing to play.

I ran it from command line with log_verbosity = 1 for log output below. The two sessions at the end are two play button presses, with a pause of about 15 seconds between them. The second play did not produce any sound.

I tried setting disable_standby_mode = "always" as I found in some related sounding issue reports, but it did not affect this issue.

### Relevant log output

```shell
0.010401406 "convolver.cpp:62" IR initialized from "/usr/local/etc/REW-filters/L+R 2020-04-07-filters-44k.wav" with 2 channels and 44100 samples
         0.000381042 "shairport.c:2251" Startup in classic Airplay (aka "AirPlay 1") mode.
         0.000119792 "shairport.c:2287" Version String: "4.1-dev-897-g32fddbfd-alac-OpenSSL-Avahi-ALSA-convolution-metadata-sysconfdir:/etc"
         0.000058281 "shairport.c:2306" Command Line: "shairport-sync".
         0.000042135 "shairport.c:2342" Log Verbosity is 1.
         0.000054584 "audio_alsa.c:1020" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000096302 "audio_alsa.c:1174" alsa output rate is 88200 frames per second
         0.000060208 "audio_alsa.c:1309" alsa: disable_standby_mode is "never".
         0.000041979 "audio_alsa.c:1313" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000044740 "audio_alsa.c:1315" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000063125 "audio_alsa.c:1355" alsa: output device name is "default".
         0.000366354 "shairport.c:2390" disable_resend_requests is off.
         0.000061615 "shairport.c:2391" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000050625 "shairport.c:2395" statistics_requester status is 0.
         0.000042604 "shairport.c:2400" rtsp listening port is 5000.
         0.000040312 "shairport.c:2401" udp base port is 6001.
         0.000040000 "shairport.c:2402" udp port range is 10.
         0.000043542 "shairport.c:2403" player name is "Audiopi".
         0.000040208 "shairport.c:2404" backend is "alsa".
         0.000038802 "shairport.c:2405" run_this_before_play_begins action is "(null)".
         0.000047552 "shairport.c:2406" run_this_after_play_ends action is "(null)".
         0.000041198 "shairport.c:2407" wait-cmd status is 0.
         0.000039480 "shairport.c:2408" run_this_before_play_begins may return output is 0.
         0.000113333 "shairport.c:2409" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000111719 "shairport.c:2411" run_this_before_entering_active_state action is  "(null)".
         0.000112812 "shairport.c:2413" run_this_after_exiting_active_state action is  "(null)".
         0.000105677 "shairport.c:2415" active_state_timeout is  10.000000 seconds.
         0.000111875 "shairport.c:2416" mdns backend "(null)".
         0.000102917 "shairport.c:2418" interpolation setting is "basic".
         0.000126354 "shairport.c:2422" interpolation soxr_delay_threshold is 30000000.
         0.000160990 "shairport.c:2423" resync time is 0.050000 seconds.
         0.000117760 "shairport.c:2424" resync recovery time is 0.100000 seconds.
         0.000107656 "shairport.c:2425" allow a session to be interrupted: 0.
         0.000529479 "shairport.c:2426" busy timeout time is 120.
         0.000251875 "shairport.c:2427" drift tolerance is 0.002000 seconds.
         0.000077969 "shairport.c:2428" password is "(null)".
         0.000103802 "shairport.c:2429" default airplay volume is: -24.000000.
         0.000111615 "shairport.c:2430" high threshold airplay volume is: -16.000000.
         0.000112500 "shairport.c:2432" check for higher-than-threshold volume for new play session is disabled.
         0.000106146 "shairport.c:2438" ignore_volume_control is 0.
         0.000103073 "shairport.c:2442" volume_max_db is not set
         0.000098645 "shairport.c:2443" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000106407 "shairport.c:2445" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000105208 "shairport.c:2449" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000105260 "shairport.c:2451" disable_synchronization is 0.
         0.000146823 "shairport.c:2452" use_mmap_if_available is 1.
         0.000048282 "shairport.c:2453" output_format automatic selection is enabled.
         0.000042760 "shairport.c:2457" output_rate automatic selection is disabled.
         0.000048646 "shairport.c:2460" output_rate is 88200.
         0.000040208 "shairport.c:2461" audio backend desired buffer length is 0.200000 seconds.
         0.000043854 "shairport.c:2463" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000048959 "shairport.c:2465" audio backend latency offset is 0.000000 seconds.
         0.000044062 "shairport.c:2467" audio backend silence lead-in time is "auto".
         0.000039792 "shairport.c:2471" zeroconf regtype is "_raop._tcp".
         0.000094375 "shairport.c:2472" decoders_supported field is 3.
         0.000103177 "shairport.c:2473" use_apple_decoder is 1.
         0.000101979 "shairport.c:2474" alsa_use_hardware_mute is 0.
         0.000104011 "shairport.c:2478" no special mdns service interface was requested.
         0.000160416 "shairport.c:2481" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000116198 "shairport.c:2488" metadata enabled is 1.
         0.000103073 "shairport.c:2489" metadata pipename is "/tmp/shairport-sync-metadata".
         0.000106146 "shairport.c:2490" metadata socket address is "(null)" port 0.
         0.000109219 "shairport.c:2492" metadata socket packet size is "500".
         0.000102708 "shairport.c:2493" get-coverart is 1.
         0.000142656 "shairport.c:2506" convolution is 1.
         0.000083125 "shairport.c:2507" convolution IR file is "/usr/local/etc/REW-filters/L+R 2020-04-07-filters-44k.wav"
         0.000045990 "shairport.c:2508" convolution max length 44100
         0.000041041 "shairport.c:2509" convolution gain is -4.000000
         0.000046250 "shairport.c:2511" loudness is 0.
         0.000039375 "shairport.c:2512" loudness reference level is -20.000000
         0.000187709 "rtsp.c:4174" metadata pipe name is "/tmp/shairport-sync-metadata".
         1.602280155 "rtsp.c:1372" Connection 1: Connection closed by client.
        92.804282153 "rtsp.c:1659" Connection 2: Classic AirPlay connection from 192.168.4.225:49553 to self at 192.168.12.36:5000.
         1.139529374 "audio_alsa.c:1751" alsa: recovering from a previous underrun.
        20.810183898 "player.c:393" 1024 buffers allocated, 1024 buffers released.
         2.006069479 "rtsp.c:1372" Connection 2: Connection closed by client.
         8.044602861 "rtsp.c:1659" Connection 3: Classic AirPlay connection from 192.168.4.225:49563 to self at 192.168.12.36:5000.
        49.043548367 "player.c:393" 2048 buffers allocated, 2048 buffers released.
         2.004403749 "rtsp.c:1372" Connection 3: Connection closed by client.
```

### Configuration Information.

>> Display Config Start.

From "uname -a":
 Linux audiopi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.1-dev-897-g32fddbfd-alac-OpenSSL-Avahi-ALSA-convolution-metadata-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 alsa : 
 {
   output_rate = 88200;
 };
 dsp : 
 {
   convolution = "yes";
   convolution_ir_file = "/usr/local/etc/REW-filters/L+R 2020-04-07-filters-44k.wav";
   convolution_gain = -4.0;
   convolution_max_length = 44100;
 };

>> Display Config End.
>> Goodbye!

Last parts of shairport-sync -h output:

Available mDNS backends: 
    avahi

Available audio backends:
    alsa (default)

Settings and options for the audio backend "alsa":
    -d output-device    set the output device, default is "default".
    -c mixer-control    set the mixer control name, default is to use no mixer.
    -m mixer-device     set the mixer device, default is the output device.
    -i mixer-index      set the mixer index, default is 0.
    hardware output devices:
      "hw:sndrpihifiberry"

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Many thanks for the report. Can I just clarify if this is a reliably-repeatable phenomenon -- in other words, should I be able to reproduce it easily, do you think?

Also, perhaps you'd let me know I could pick up the convolution file, please.

**Comment by mklein9** [comment]
Yes, this issue repeats at all times that I have tried it, on a variety of songs. It is hard for me to pinpoint when the issue started, but probably in the last month or two. It could be triggered by a recent MacOS upgrade.

I have a second RPi that also shows the issue. It also has a HiFiBerry DAC, version string 4.1-alac-OpenSSL-Avahi-ALSA-convolution-metadata-sysconfdir:/etc.

GZ convolution file is attached.
[L+R 2020-04-07-filters-44k.wav.gz](https://github.com/mikebrady/shairport-sync/files/11263496/L%2BR.2020-04-07-filters-44k.wav.gz)

**Comment by mikebrady** [comment]
Thanks. I'll see what I can figure out, but it may take as little while...

**Comment by mklein9** [comment]
Some additional info after looking at this some today and trying to understand if the issue is in the ADC or shairport-sync or somewhere in between.

`aplay -l` shows:
```
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0 [HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

While playing correctly, `cat cat /proc/asound/card0/pcm0p/sub0/status` shows:
```
state: RUNNING
owner_pid   : 752
trigger_time: 815.928777833
tstamp      : 926.173066335
delay       : 8825
avail       : 56711
avail_max   : 62134
-----
hw_ptr      : 4861736
appl_ptr    : 4870561
```

`shairport-sync` is using about 23% CPU.

Then I pause the Music app, now it shows:
```
state: PREPARED
owner_pid   : 752
trigger_time: 1037.660394402
tstamp      : 1046.455353344
delay       : 0
avail       : 65536
avail_max   : 58427
-----
hw_ptr      : 0
appl_ptr    : 0
```

After 10 seconds of pause, the device is closed:
```
closed
```

Now I try to resume playing in the Music app, the Music app shows it is playing, and (as reported before) the RPi shows that `shairport-sync` is using CPU time, but only about 7%.

The device status is:
```
state: PREPARED
owner_pid   : 922
trigger_time: 0.000000000
tstamp      : 1245.098539464
delay       : 0
avail       : 65536
avail_max   : 0
-----
hw_ptr      : 0
appl_ptr    : 0
```

I now restart `shairport-sync` and everything works:
```
state: RUNNING
owner_pid   : 1073
trigger_time: 2123.262555958
tstamp      : 2126.746413693
delay       : 8814
avail       : 56722
avail_max   : 61846
-----
hw_ptr      : 153656
appl_ptr    : 162470
```

There is no process with PID 1073.

Next, I disabled DSP and restarted `shairport-sync` and played from the Music app again. CPU usage dropped to about 15%. I paused for 10 seconds until the device status showed `closed`, and tried resuming play from the Music app. Result is same as before: no sound, `shairport-sync` using about 7% of CPU, and device status shows:
```
state: PREPARED
owner_pid   : 1184
trigger_time: 0.000000000
tstamp      : 2607.883938386
delay       : 0
avail       : 65536
avail_max   : 0
-----
hw_ptr      : 0
appl_ptr    : 0
```

**Comment by mikebrady** [comment]
Hmm, interesting, thanks.

**Comment by mklein9** [comment]
Bump.... tested again just now with latest development branch revision and fully updated Raspbian Linux 11, and exactly same symptoms.

**Comment by mikebrady** [comment]
Thanks. Could you post the output from `$ shairport-sync --displayConfig` please?

**Comment by mklein9** [comment]
```
$ shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux audiopi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.2.1d0-27-g0af12c14-alac-OpenSSL-Avahi-ALSA-convolution-metadata-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 dsp : 
 {
   convolution = "yes";
   convolution_ir_file = "/usr/local/etc/REW-filters/L+R 2020-04-07-filters-44k.wav";
 };

>> Display Config End.
>> Goodbye!
$
```

**Comment by mikebrady** [comment]
Thanks again. An obvious thing to try is to turn off convolution completely, enable statistics logging and see if the problem persists.

**Comment by mklein9** [comment]
I rebuilt `shairport-sync` without `--with-convolution` and tested it: no change, still stops producing audio after a 10-second pause.

**Comment by mikebrady** [comment]
Thanks. And just to leave no stone unturned, how about omitting `metadata` and `alac`, and again see what happens… 

(I use a Pi just like this for development and testing, and this kind of thing doesn’t happen with it.)

BTW, what kind of a Mac are you using, and what version of macOS, please?

**Comment by mklein9** [comment]
Rebuilt with `./configure --with-alsa --with-avahi --with-ssl=openssl --with-systemd --sysconfdir=/etc`: same issue.

Mac is M1 Mac Mini, 2020 and OS is the very latest: Ventura 13.4.1.

**Comment by mikebrady** [comment]
Super, thanks. Let me have a dig.

**Comment by mklein9** [comment]
I don't know how playing time is calculated but these two lines from the debug log above do not look right to me:

```
        17.186731140 "player.c:1815" Connection 2: Playback stopped. Total playing time 00:00:25.
        36.519618476 "player.c:1815" Connection 3: Playback stopped. Total playing time 00:46:29.
```
The two playing times being so different does not look right. If the first one is 25 seconds then the second one at 46 minutes is not right. If the second one at 46 seconds is right, then the first one at 1/4 of a second (or some other fraction) is not right.

**Comment by mikebrady** [comment]
> I don't know how playing time is calculated but these two lines from the debug log above do not look right to me:
> 
> ```
>         17.186731140 "player.c:1815" Connection 2: Playback stopped. Total playing time 00:00:25.
>         36.519618476 "player.c:1815" Connection 3: Playback stopped. Total playing time 00:46:29.
> ```
> 
> The two playing times being so different does not look right. If the first one is 25 seconds then the second one at 46 minutes is not right. If the second one at 46 seconds is right, then the first one at 1/4 of a second (or some other fraction) is not right.

Yep -- that looks a bit crazy. I'll investigate...

**Comment by mikebrady** [comment]
So, I found _something_. Shairport Sync (SPS) works fine when the source is Apple Music on macOS 13.4.1 on an Intel Mac, but when the source is an Apple Silicon Mac (a 2020 M1 MacBook Pro) it misbehaves -- apparent activity but no sound. My guess is that the problem is at the Mac end, but I'll have to dig further; Shairport Sync could be doing something stupid.

**Comment by mikebrady** [comment]
I just pushed a tiny bug fix -- not relevant to this.

**Comment by mikebrady** [comment]
Okay, since fixing that tiny bug -- which really was purely cosmetic -- I can't get the thing to misbehave on either the Intel Mac or the M1 Mac. It's late here; maybe I'm doing something silly. Tomorrow!

**Comment by mikebrady** [comment]
A quick thought -- do you have firewall rules running anywhere? If so, could you list them please?

**Comment by mklein9** [comment]
Yes, there are firewalls involved. The Mac and the RPi are on different VLANs. The Mac is allowed to access the RPi VLAN for any TCP connections. The RPi on a more locked-down VLAN is allowed to reply on any related/established TCP connections but not to start new ones.

`tcpdump` shows that `shairport-sync` is sending UDP packets to the client's port 6002. I had a firewall rule allowing these packets if they **came from** those ports on `shairport-sync`, but not if their destination was; this was from another guide to supporting AirPlay across VLANs. I reversed that rule and now it works. 

Is this new in recent `shairport-sync` versions? It has worked OK before this.

Is there a guide to network traffic that needs to be enabled for AirPlay and AirPlay 2 to work?

In any case, it looks like this issue is resolved. Thank you for the hint to look at network traffic and firewall.

**Comment by mikebrady** [comment]
Good stuff!

There's some firewall information on the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md#ufw-firewall-blocking-ports-commonly-includes-raspberry-pi) page.

Classic AirPlay uses three UDP ports (audio/control/timing) at a time but, from session to session, Shairport Sync will rotate the three ports in use through the range allowed, which is from 6000 to 6009 by default. This is to avoid UDP packets that may still be "in flight" from a previous session from interfering with the new session. So the ports in the range must be open for UDP in both directions.

It's been like this for a long time -- years.

**Comment by mklein9** [comment]
Thanks again, Mike.

There are numerous sources all over the web listing a variety of different port lists to support AirPlay. Most don't seem to distinguish direction. So I ran the Music app to `shairport-sync` on the RPi for a while, with some pauses and resumes, and found the following UDP ports used:

Client (Mac) -> Server (`shairport-sync`) traffic (unrestricted by firewall):
Source ports 6001, 6002 plus random ports in the high (48k - 64k) range
Destination ports 6004-6010

Server (`shairport-sync`) -> Client (Mac) traffic (restricted by firewall):
Source ports 6004-6010
Destination ports 6001, 6002

Also MDNS of course.

In the config file `udp_port_base = 6001` by default, and `udp_port_range = 10`, so is the required port range 6001-6010, not including 6000?

So relatively restrictive firewall rules from the VLAN that the RPi is on back to the Mac client could be:

Source ports: 6001-6010, 49152-65535
Dest ports: 6001, 6002

I'm testing this and it seems to work so far.

I understand AirPlay 2 adds more ports, will consider that when I get to it :-).

**Comment by mikebrady** [comment]
Thanks. Generally speaking, Shairport Sync will use three of the ports in the range 6001 (yeah, you're right!) to 6010. Any one of them can be a destination port too. Mostly the range will be 6001 to 6003, but it can use the higher ports if sessions are allowed to be interrupted. There are some updates today and one of them fixes a bug that affects how ports are selected.

**Comment by mklein9** [comment]
Well, more UDP return ports need to be allowed when playing from something other than the Mac Music app. Playing YouTube from Safari requires return traffic from `shairport-sync` on high numbered ports, in one case I observed 56533, and ports 600x were not used as UDP return ports. Touchy, uses a lot of ports. Probably need to allow UDP 6001-6010 and 49152-65535 in both directions.
