### ISSUE TITLE
[Problem]: *warning: This version of Shairport Sync is not compatible with the installed version of NQPTP. Please update.

### ISSUE THREAD

**Issue by quantonian** [mikebrady/shairport-sync#1670]
### What happened?

Greetings,

This issue is fairly straightforward but I'm not able to resolve it. I'm looking for information how to upgrade the Shared Memory Interface to Version 9.

Upgrading from shairport-sync ```dev-532``` to ```dev-896``` & nqptp ```dev-168``` to ```dev-175```

Previous version was working flawlessly.

I've compiled and installed the latest dev version of shairport-sync ```Version 4.1-dev-896-g03961830``` and the latest version of nqptp ```Version: 1.1-dev-175-g264805d```

Getting the following error:

```shairport-sync -v```
```*warning: This version of Shairport Sync is not compatible with the installed version of NQPTP. Please update.```

```nqptp -V```
```Version: 1.1-dev. Shared Memory Interface Version: 8.```

This is on openwrt 22.0.3
```uname -a```
```Linux sono 5.15.64 #0 SMP Fri Sep 9 09:15:07 2022 armv7l GNU/Linux```

I seem to be missing something??

### Relevant log output

```shell
root@sono:~# shairport-sync -v
         0.002283646 "shairport.c:2248" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "58:cb:52:bb:d0:76".
         0.000191250 "shairport.c:2287" Version String: "4.1-dev-AirPlay2-libdaemon-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
.
.
.
         0.000108292 "shairport.c:2481" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000070208 "shairport.c:2511" loudness is 0.
         0.000044938 "shairport.c:2512" loudness reference level is -20.000000
         0.006432083 "shairport.c:2610" NQPTP is online.
         1.505839686 "shairport.c:254" "soxr" interpolation has been chosen.
         6.098815724 "rtsp.c:2910" Connection 1: AP2 PTP connection from 192.168.2.180:55775 ("iPhone") to self at 192.168.2.17:7000.
         7.852879930 "rtsp.c:3326" Connection 1. AP2 Buffered Audio Stream.
         0.045596520 "rtp.c:1435" *warning: This version of Shairport Sync is not compatible with the installed version of NQPTP. Please update.

nqptp -V
Version: 1.1-dev. Shared Memory Interface Version: 8.
```

### Configuration Information.

```shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux sono 5.15.64 #0 SMP Fri Sep 9 09:15:07 2022 armv7l GNU/Linux

From /etc/os-release:
 OpenWrt SNAPSHOT

From /sys/firmware/devicetree/base/model:
 Google WiFi (Gale)

Shairport Sync Version String:
 4.1-dev-AirPlay2-libdaemon-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   volume_range_db = 60;
   name = "sono";
 };
 alsa :
 {
   output_device = "hw:KMHIFI384KHZ";
 };

>> Display Config End.
>> Goodbye!```


### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. The [`development` branch](https://github.com/mikebrady/nqptp/tree/development) of NQPTP is running Shared Memory Interface Version 9, so if you switch to the `development` branch of NQPTP, `$ git pull` any updates, rebuild and reinstall, you should be good to go. Apologies for the inconvenience.

**Comment by quantonian** [comment]
Mike, thanks for the quick response. I didn't realize there was a ```main``` and ```development``` branch for nqptp. The ```main``` stops at version ```dev-175``` which was the source of my issue. I've switched to the dev branch and successfully compiled and installed the latest nqptp version ```dev-207```. Thanks again!

**Comment by quantonian** [comment]
Closing issue as resolved.
