### ISSUE TITLE
[Problem]: Left-side (speaker) output only

### ISSUE THREAD

**Issue by RubyBailey** [mikebrady/shairport-sync#1690]
### What happened?

Hi, 
System 1: I have been using shairport-sync for quite some time on a Raspberry Pi Zero W (RPIZ) using version 3.3.8-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc (output of shairport-sync -V). It has been working extremely well! 

System 2: Today, on another  RPI Zero (with wifi dongle) I installed the latest version of [classic] Shairport-sync  (OS Raspberry PI OS Lite Bullseye) per https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md. Per 4. Test section everything worked. Then I wired up a PCM5102A (per https://raspberrypi.stackexchange.com/questions/76188/how-to-make-pcm5102-dac-work-on-raspberry-pi-zerow), updated the/boot/config.txt, created the /etc/asound.conf file and modified the  /etc/shairport-synch.conf file with output_device="hw:sndrpihifiberry”;. All of this was the same as the previous Raspberry Pi Zero W mentioned above. 

When I tried to play music only the left speaker worked. Tested on 2 separate speaker systems, including the one connected to System 1 above.

System 3: Then I installed the same software on a Raspberry Pi 3 ( I had one kicking around and thought let's use it in case the other hardware was faulty). Same OS, followed the installation instructions at https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md and setup for RPI at https://github.com/mikebrady/shairport-sync/blob/master/ADVANCED%20TOPICS/InitialConfiguration.md with output_device = "hw:Headphones";. Same results only left speaker worked. 

From iPhone:
System 1 plays stereo, System 2 and 3 only play the left speaker. All 3 systems seem to be installed and configured the same. 

I have searched for solutions and not been able to determine how to solve this issue. Any help or advice would be appreciated. 

### Configuration Information.

System1:
```
$ uname -a
Linux Master-airport 5.10.60+ #1449 Wed Aug 25 14:59:20 BST 2021 armv6l GNU/Linux
shairport-sync -V
3.3.8-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
```
System 2:
```
$ shairport-sync --displayConfig
>> Display Config Start.
From "uname -a":
 Linux Main-airport 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)
From /sys/firmware/devicetree/base/model:
 Raspberry Pi Zero Rev 1.3
Shairport Sync Version String:
 4.2-1-g12ad72c4-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
Command Line:
 shairport-sync --displayConfig
Configuration File:
 /etc/shairport-sync.conf
Configuration File Settings:
 alsa :
 {
   output_device = "hw:sndrpihifiberry";
 };
>> Display Config End.
>> Goodbye!
```
System 3:
```
$ shairport-sync --displayConfig
>> Display Config Start.
From "uname -a":
 Linux Main-airport1 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)
From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Plus Rev 1.3
Shairport Sync Version String:
 4.2-1-g12ad72c4-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
Command Line:
 shairport-sync --displayConfig
Configuration File:
 /etc/shairport-sync.conf
Configuration File Settings:
 alsa :
 {
   output_device = "hw:Headphones";
 };
>> Display Config End.
>> Goodbye!
```

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. Is it possible that the PCM5102A board is faulty? One way to test this, separately from Shairport Sync, would be to use a utility like `speaker-test` or `aplay` to ensure that sound is coming from both channels. It's worth ensuring that the sample rate is 44,100 frames per second; I think they both default to 48,000.

**Comment by RubyBailey** [comment]
I figures it out. It was an external wiring issue. Loose wire between the RPI's to the amplifier. When connected to system 1 it worked. System 2 and 3 were in slightly different locations on the table and the wire was disconnected at those locations. My apologies for the false alarm. Many thanks for your quick response. The software works great.
