### ISSUE TITLE
iOS 9.2 always sends cover-art

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#170]
After updating my iPhone to latest iOS 9.2 shairport-sync gets messed up with `PICT` data at the beginning of a session. This is what I get from the pipe:

```sh
AirPlay/267.3
[...]
<item><type>ssnc</type><code>PICT</code><length>51536</length>
```

After some seconds, the `PICT` data stops.

My config file:
```sh
// How to deal with metadata, including artwork
metadata =
{
        enabled = "yes";
//      include_cover_art = "no";
//      pipe_name = "/tmp/shairport-sync-metadata";
};
```

avahi-browser tells me:
```sh
= wlp5s0 IPv4 63909E8219DB@Wohnzimmer                            AirTunes Remote Audio local
   hostname = [Wohnzimmer.local]
   address = [192.168.178.27]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "vn=3" "sr=44100" "ss=16" "md=0,2" "ch=2" "cn=0,1" "et=0,1" "ek=1" "sm=false" "tp=UDP"]
```

So `md=0,2`, but somehow iTunes ignores it?

EDIT: Tested with shairport-sync 2.7.3 from the development branch.

**Comment by mikebrady** [comment]
Very interesting, thanks. I'll check this out.

**Comment by mikebrady** [comment]
I think I can confirm this – the Music app seems to send picture data whether you ask for it or not. I'm not sure, but the TuneIn Radio app seems to honour the setting.

All in all, this is good news, I think – Apple is sending the metadata once again.

**Comment by joerg-krause** [comment]
The only drawback is, that the CPU usage of shairport-sync is above 40% when receiving the whole bunch of metadata.

**Comment by mikebrady** [comment]
Yes indeed. Given that iTunes only sends pictures if requested, hopefully this is a minor bug that will be fixed going forward...

**Comment by joerg-krause** [comment]
Okay, as this is not shairport-sync related, but iOS related, I'll close this issue for now.
