### ISSUE TITLE
[Problem]: Installation instructions error

### ISSUE THREAD

**Issue by ocgltd** [mikebrady/shairport-sync#1708]
### What happened?

Installing shareport-sync on AlmaLinux 9 (redhat 9 clone).  Probably affects later Fedora distros too.

First, errors during installation due to missing dependencies (on Fedora/Red Hat branch), which are not included in the instructions.  I have listed all of the needed prerequisites below.

However, configure then fails at the check for uuid.  Even though packages uuid and uuid-devel are installed, configure will not detect them.

### Relevant log output

```shell
configure: error: AirPlay 2 support requires the uuid library -- uuid-dev suggested
```

### Configuration Information.

The following prerequisites are needed:
popt
popt-devel
libconfig
libconfig-devel
soxr
soxr-devel
avahi
avahi-devel
alsa-lib
alsa-lib-devel
vim-common
libplist
libplist-devel
libsodium
libsodum-devel
libgcrypt-devel
uuid-devel

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by ocgltd** [comment]
Update: Adding libuuid and libuuid-devel allowed configure to complete

So just an update to instructions are needed.

**Comment by mikebrady** [comment]
Thanks for the information. I hadn’t heard of AlmaLinux, I’m afraid. I’ll check the Fedora situation.

**Comment by mikebrady** [comment]
Just checked the building guide, and it specifically [references](https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md#fedora)  `libuuid-devel`. (I'm afraid it is not really feasible to make the configuration hints distribution-specific, so they are aimed at Debian/Ubuntu/Raspberry Pi OS.)
