### ISSUE TITLE
Shairport-Sync did not show up on iPadOS 17 device 

### ISSUE THREAD

**Issue by DrCWO** [mikebrady/shairport-sync#1717]
### What happened?

As already mentioned in some posts here (https://github.com/mikebrady/shairport-sync/issues/1543) there are some issues with iPadOS17 or iOS17.

I use Shairpport-Sync with DietPi on a Raspberry Pi4 platform.
With iOS16 it is discoverable and works, with iPadOS 17 no more discoverable.

An investigation would be greatly appreciated.
Best DrCWO

### Relevant log output

```shell
none
```

### Configuration Information.

Raspberry Pi4 DietPi

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. As I mentioned in the referenced issue, there seems to be a lot happening in this area. Different versions of iPadOS 17 beta have different peculiarities. We don’t know what further changes or reversions will be made and so the best we can do is wait and see how it all settles down. But FWIW, using the iPadOS 17 latest beta’s Home app, I am still able to add and remove devices using the latest master and development versions of SPS. And I’m still able to access them as AirPlay 2 devices.
