### ISSUE TITLE
[Problem]:Airplay device not showing (portainer)

### ISSUE THREAD

**Issue by monstruwaken** [mikebrady/shairport-sync#1722]
### What happened?

Docker installed and running in Portainer but is not showing in airplay devices. Is there something that I am missing?

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service syslogd-prepare: starting
s6-rc: info: service 01-startup: starting
STARTING - Sun Aug 20 18:57:21 UTC 2023
s6-rc: info: service 01-startup successfully started
s6-rc: info: service 04-nqptp: starting
s6-rc: info: service 02-dbus: starting
s6-rc: info: service 04-nqptp successfully started
Starting nqptp
Starting dbus
s6-rc: info: service syslogd-prepare successfully started
s6-rc: info: service syslogd-log: starting
s6-rc: info: service syslogd-log successfully started
s6-rc: info: service syslogd: starting
s6-rc: info: service syslogd successfully started
s6-rc: info: service 02-dbus successfully started
s6-rc: info: service 03-avahi: starting
Starting avahi
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
Joining mDNS multicast group on interface eth0.IPv4 with address 172.17.0.2.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.17.0.2 on eth0.IPv4.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is NickAirPi.local. Local service cookie is 256758078.
s6-rc: info: service 03-avahi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting shairport-sync
Service "NickAirPi" (/etc/avahi/services/ssh.service) successfully established.
Service "NickAirPi" (/etc/avahi/services/sftp-ssh.service) successfully established.
```

### Configuration Information.

![Screenshot 2023-08-20 at 6 30 58 PM](https://github.com/mikebrady/shairport-sync/assets/129773246/769c3be7-110d-4661-aab5-29a7564de8ba)

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. I know zero about [portainer](https://www.portainer.io), but looking at the configuration information -- if I am interpreting it properly -- you may not be asking to use the host's network. If you check the basic usage detailed on the [Docker Hub](https://hub.docker.com/r/mikebrady/shairport-sync), you'll see that the host network is requested. This is because all AirPlay players and devices must be on the same [local] network to be accessible to one another.

**Comment by monstruwaken** [comment]
Got it working. Installing from portainer created a bunch of port issues I could not work out. Ended up making my entire setup unusable. Did a fresh install but installed the shairport from CLI instead of portainer. Worked flawlessly right away. Thank you for your efforts.

**Comment by moritzthecat** [comment]
in Portainer I started preferring to use the stack/compose way, which gives me better overview and regression. thanx to the updated compose file (https://github.com/mikebrady/shairport-sync/blob/master/docker/docker-compose.yaml) I managed to get this working now in an VLAN setup with seperated container for SPS and Snapcast Server. To avoid port issues I use docker networks and a dedicated host address for almost each of the services. output is pipe fifo in my case to snapcast server and working fine. Docker is taking a bit of responsiveness/latency - more services are running on this RPi4, therefore I had to increase buffer size to 1.5 seconds to avoid occaisonal drop outs. 

Here is my shairport-sync compose file:

```
services:
   shairport-sync:
     image: mikebrady/shairport-sync:latest
     restart: unless-stopped
     user: root
     volumes:
       - /docker/shairport-sync-config/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
       - /tmp/snapcast:/tmp/snapcast      
     networks:
       network1:
         ipv4_address: 192.168.30.32
 
     logging:
       options:
         max-size: "200k"
         max-file: "10"
 
 networks:
   network1:
     name: IOTvlan
     external: true
```

some changes in shairport-sync.conf

```
output_backend = "pipe";
mdns_backend = "avahi";
port = 5000; // Listen for service requests on this port. 5000 for AirPlay 1, 7000 for AirPlay 2
udp_port_base = 6001; // (AirPlay 1 only) start allocating UDP ports from this port number when needed 
udp_port_range = 10;
audio_backend_buffer_desired_length_in_seconds = 2.5; 
pipe =
 {
 	name = "/tmp/snapcast/snapfifo"; // shared with snapcast server on same machine
 };
```
