### ISSUE TITLE
[Problem]: Ubuntu VM Crashes when playing

### ISSUE THREAD

**Issue by MaximWnck** [mikebrady/shairport-sync#1724]
### What happened?

My VM with ubuntu crashes when playing sound. It worked before, but crashes now after some Ubuntu updates.
Just reinstalled it, but it crashes again.

![image](https://github.com/mikebrady/shairport-sync/assets/33703124/717d245e-d17a-47ee-8fbf-a3f285ea48ea)

### Configuration Information.

![image](https://github.com/mikebrady/shairport-sync/assets/33703124/05ad7262-cae2-4926-82ed-2ca10519a466)

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. If you could do the following and post the log up to the point it crashes, it would be very helpful.

First, stop the shairport-sync daemon running:
```
$ sudo systemctl stop shairport-sync
```
Next, run shairport-sync from the command line with one level of debug and statistics:
```
$ shairport-sync -v --statistics
```
You'll get maybe thirty or forty lines of messages, and they might reveal a problem.

**Comment by MaximWnck** [comment]
When starting:
![image](https://github.com/mikebrady/shairport-sync/assets/33703124/7adb30d9-c167-45e9-8180-d8011c80ba7c)


When playing starts:
![image](https://github.com/mikebrady/shairport-sync/assets/33703124/c36386d0-1852-408c-b836-d028b6c6f858)

**Comment by mikebrady** [comment]
Super stuff, thanks. There is no indication of any music actually being played. What I'd expect is something like this:
```
...
...
       18.872984316 "rtsp.c:2914" Connection 1: AP2 PTP connection from fd60:823e:c8d5:4746:434:148d:7f01:b136:52224 ("Mike Brady's iPhone") to self at fd60:823e:c8d5:4746:dcf:f7cc:d71:6f7c:7000.
         0.275447969 "rtsp.c:3330" Connection 1. AP2 Buffered Audio Stream.
         1.300222968 "player.c:2813" Connection 1: Playback started at frame 3179414829 -- AirPlay 2 Buffered.
         7.944558539 "player.c:2629" Sync Error ms | Net Sync PPM | All Sync PPM | Min DAC Queue | Min Buffers | Min Buffer Size | Output FPS (r) | Output FPS (c)
         0.000171041 "player.c:2629"         -0.08            0.0            0.0            7421            46              228k              N/A              N/A
         7.991225778 "player.c:2629"         -0.35           11.3           11.3            7395            46             3483k         44100.14         44100.28
         8.018796195 "player.c:2629"         -0.23            8.5            8.5            7412            46             3484k         44100.07         44100.21
         7.989771143 "player.c:2629"          0.26            5.7            5.7            7425            46             3508k         44099.97         44100.11
         8.015137757 "player.c:2629"          0.12            2.8            2.8            7463            46             3483k         44099.99         44100.13
...
...
```
Those lines of statistics come at roughly eight-second intervals.
Was there any sign of this?
