### ISSUE TITLE
[Problem]: Mistake in Docker args instructions

### ISSUE THREAD

**Issue by brokensbone** [mikebrady/shairport-sync#1726]
### What happened?

Docker run instructions are missing a `--` that separates args passed to the audio backend. Using them as is prevents the container starting.

[Instructions are here](https://github.com/mikebrady/shairport-sync/blob/7c84523ee06622f7e7d133e749f291d1a978ff03/docker/README.md?plain=1#L39)
Current line
```
-v --statistics -a DenSystem -d hw:0 -c PCM
```
should be
```
-v --statistics -a DenSystem -- -d hw:0 -c PCM
```

The double dashes [were removed in this commit](https://github.com/mikebrady/shairport-sync/commit/b77e06be9e5e15537e2117374029e97eedf47ada).

### Relevant log output

```shell
Args as provided attempt to daemonise the process. Container logs the following and exits.

shairport-sync was built without libdaemon, so does not support daemonisation using the -d, --daemon, -j or --justDaemoniseNoPIDFile options
         0.002034636 "shairport.c:1721" normal exit
```
```


### System Information.

Raspberry Pi 3 / Docker.

### Configuration Information.

```shell
N/A - this is using the Docker iamge with no manual config.
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Many thanks for this! I've fixed it in the `master` and `development` branches. It'll propagate to the `development` version of the Docker image shortly. It'll arrive in the `master` version of the Docker image in the next week or so, whenever the next release is out.
