### ISSUE TITLE
[Problem]: volume randomly resets

### ISSUE THREAD

**Issue by ceiri** [mikebrady/shairport-sync#1732]
### What happened?

When i play music from my phone, and either exit the Apple Music player or the app itself, when I return to the player the volume level resets to a random level each time, and if the slider is moved slightly the volume changes drastically which doesn't sound great. This happens even when the slider is all the way down - it's reset to a random place and when it's touched it causes the music to start playing much louder and abruptly. I've tried playing with the high threshold airplay volume etc but it hasn't changed anything. This may well be an Apple Music issue but it doesn't happen with any of my other AirPlay devices so it's unlikely.

https://github.com/mikebrady/shairport-sync/assets/57523771/a54c79f0-0c50-45de-b095-a3f1d71b72ae

### System Information.

Raspberry Pi 3
Raspberry Pi OS (2023-05-03)
Shairport Sync 4.3.1
Airplay 2
Connected with a 3.5mm to RCA cable to a Sony STR-DE400 Amplifier

### Configuration Information.

```shell
From "uname -a":
 Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.3.1-24-g7e0e3af6-AirPlay2-smi10-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

The Configuration file contains no active settings.
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. This isn't something I've noticed, but I'll have a play around, see if I can replicate it.

**Comment by MSL-DA** [comment]
> This is what should happen, and is happening for me. I'm on iOS 17.0.1 and am using the latest `development` version, 4.3.2-dev-22-g11d7c829.
> 
> Sometimes, the volume sliders on the apps don't always update (e.g. Apple Classical). But when you use the volume up/down buttons of the phone, the volume slider is updated. This happens when playing to a HomePod mini too, so I'm inclined to think it's an Apple problem.
> 
> Does that sound plausible to you?

It does for me. Definitely an Apple problem
