### ISSUE TITLE
[Problem]: Noticed a few bad format strings in recent changes

### ISSUE THREAD

**Issue by n8gray** [mikebrady/shairport-sync#1734]
### What happened?

I was looking at the diff between master and development and noticed what appear to be some format string bugs in the debug calls in `rtsp.c`. These lines all have more format specifiers than arguments.

```
Line 774:
    debug(1, "Error %d locking reference counter lock");

Line 789:
    debug(1, "Error %d unlocking reference counter lock");

Line 5224:
        debug(1, "conns[%d] at %" PRIxPTR " has a Connection Number of 0!", conns[i]);
```

Thanks for all the work you do on this project - it's a gem!

### Relevant log output

```shell
N/A
```

### System Information.

N/A

### Configuration Information.

```shell
N/A
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Super stuff, thanks! Fixed in the `development` branch. Keep 'em coming 😬.
