### ISSUE TITLE
With ignore_volume_control="yes" volume=0 on source seems to be treated as Mute?

### ISSUE THREAD

**Issue by mc510** [mikebrady/shairport-sync#1737]
### What happened?

I've got ignore_volume_control="yes" in config file which works as intended, unless the volume level is lowered to zero on my audio source (iPhone), which causes shairport-sync to be muted. Perhaps iPhone sends a "mute" message when volume is lowered to zero, which shairport-sync is respecting? If so, is there an option to have shairport-sync ignore mute messages from the source? (Or maybe the iPhone mutes its own airplay audio stream when volume hits zero? I'm not sure how to check this, but if this is the case there would be no possible solution I suppose.)

### System Information.

Orange Pi Zero
Allwinner H3 SOC
sunxi-codec onboard audio
Armbian 23.08 (Debian bookworm)

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux radiopi 6.1.53-current-sunxi #3 SMP Wed Sep 13 07:43:05 UTC 2023 armv7l GNU/Linux

From /etc/os-release:
 Armbian 23.8.3 bookworm

From /sys/firmware/devicetree/base/model:
 Xunlong Orange Pi Zero

Shairport Sync Version String:
 4.3.1-24-g7e0e3af6-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   name = "Bose Radio (AUX)";
   interpolation = "basic";
   ignore_volume_control = "yes";
   audio_backend_buffer_desired_length_in_seconds = 1.0;
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
You were right -- mute would be enabled irrespective of the `ignore_volume_control` setting. An update has just been pushed with a fix. If you got a chance to try it out and report back, it would be appreciated.

**Comment by mc510** [comment]
Just compiled development branch this morning and, yep, it's fixed 😀. Thanks Mike, you and shairport-sync are the best!
