### ISSUE TITLE
[Problem]: Pipewire backend missing 'node.name' property.

### ISSUE THREAD

**Issue by alexsarmiento** [mikebrady/shairport-sync#1742]
### What happened?

When using the pipewire backend, utils such as 'pw-link -l' and 'wpctl status' show the shairport-sync node name as blank. For instance:

```
$ pw-link -l
....
effect_input.EQ:playback_FL
  |<- playback.USB_SPDIF:output_FL
  |<- v-sink.playback:output_FL
  |<-
effect_input.EQ:playback_FR
  |<- playback.USB_SPDIF:output_FR
  |<- v-sink.playback:output_FR
  |<- 
...
```

Indeed, a default _PW_KEY_NODE_NAME_ property key is missing in audio_pw.c at `props = pw_properties_new(...)`.   

Still works, but the node.name property is useful to manage nodes and their links.

With that property included `..., PW_KEY_NODE_NAME, "shairport-sync",...` we get:

```
$ pw-link -l
...
effect_input.EQ:playback_FL
  |<- playback.USB_SPDIF:output_FL
  |<- v-sink.playback:output_FL
  |<- shairport-sync:output_FL
effect_input.EQ:playback_FR
  |<- playback.USB_SPDIF:output_FR
  |<- v-sink.playback:output_FR
  |<- shairport-sync:output_FR
...
```

### System Information.

asus p51 mini

### Configuration Information.

```shell
Tested using shairport-sync commit d9c7f0aeb13112ebe3dd1ffa1425a966574eed02, pipewire 0.3.80-2~bpo12+1, Debian 12.
```

### PulseAudio or PipeWire installed?

- [x] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Would you be kind enough to post the output from: `$ shairport-sync --displayConfig` please?

**Comment by alexsarmiento** [comment]
[shairport-sync-displayConf.txt](https://github.com/mikebrady/shairport-sync/files/12809060/shairport-sync-displayConf.txt)
 Here it is the result attached.

**Comment by mikebrady** [comment]
Many thanks for the information and suggestion. That's one now, and an update has been pushed to the `development` branch. If you got a chance to try it out and report any issues, it would be appreciated.

**Comment by alexsarmiento** [comment]
The pipewire node-name setting is looking for a pa conf , it should be `pw.node_name` I think. At `audio_pw.c:205`

```
 /* Get the PulseAudio node name. */
      if (config_lookup_string(config.cfg, "pa.node_name", &str))
 ```

Also, can you add another setting for the property key: `PW_KEY_TARGET_OBJECT`? This to mirror the pulseaudio 'pa.sink' setting to set the target sink.  Yet another very useful feature that makes life easier for when is needed.  I believe this property can default to pipewire's `"@DEFAULT_AUDIO_SINK@"`

**Comment by mikebrady** [comment]
Ah, thanks! I'll fix and [try to] add that new property.

Perhaps you might be able to give us a hint as to how/where to pick it up programmatically. Also, is there somewhere to pick up and/or set the volume setting?

**Comment by alexsarmiento** [comment]
So I did a quick test  and  I think the 'PW_KEY_TARGET_OBJECT' can be set just like 'PW_KEY_NODE_NAME' and the other keys, ie.
```
....
if (config.pw_sink_target)
    free(config.pw_sink_target);
config.pw_sink_target = NULL;
....
  char* sinktarget = config.pw_sink_target;

  props = pw_properties_new(PW_KEY_MEDIA_TYPE, "Audio", PW_KEY_MEDIA_CATEGORY, "Playback", PW_KEY_TARGET_OBJECT, sinktarget,
                            PW_KEY_MEDIA_ROLE, "Music", PW_KEY_APP_NAME, appname,
                            PW_KEY_NODE_NAME, nodename, NULL);
```

Where `sinktarget` can be any 'node.name' string of a sink (NULL also works). _If the 'sinktarget' is not set or set but does not exist_,  the shairport-sync node will connect to a default sink already previously defined.

When the sink_target is not set ,or , is set but the target sink does not exist, the command `pw-link -l' shows:
```
pw =
{
  //    sink_target = "v-sink.capture";
}
....
$ pw-link -l
shairport-sync:output_FL
  |-> effect_input.EQ:playback_FL
shairport-sync:output_FR
  |-> effect_input.EQ:playback_FR
```

The shairport-sync node will be linked to a default sink target, in this case "effect_input.EQ" . If sink_target is defined in the conf file and does indeed exist then pw-link -l shows:

```
pw =
{
      sink_target = "v-sink.capture";
}
.....
$ pw-link -l
shairport-sync:output_FL
  |-> v-sink.capture:playback_FL
shairport-sync:output_FR
  |-> v-sink.capture:playback_FR

```
shairport connects to the sink defined in the conf file. 
Something like that?

As for the volume, I don't know.

**Comment by mikebrady** [comment]
This should be done now -- bug fixed and extra setting added.

**Comment by alexsarmiento** [comment]
Many thanks! As a side note I made this 'run_this_when_volume_is_set' script to control the volume of the pipewire sink via wireplubler's 'wpctl'
```
#!/usr/bin/env bash

vol="$1"

c=$(echo "if (${vol} < -30 ) -30 else ${vol}"|bc -l)

vol=$c
pvol=$(echo "scale=2; 1*(30+$vol)/30"|bc -l)
#echo $pvol

/usr/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ $pvol

```
Translates the shairport-sync's input to a range of 0 to 1 for wpctl.
The `@DEFAULT_AUDIO_SINK@` sink argument can be replaced with any ID number with volume control which can be found with `wpctl status|grep vol`:

```

 │      34. null_sink                           [vol: 0.59]
 │  *   44. EqualizerSink                       [vol: 0.76]
 │      47. v-sink                              [vol: 0.00]
 │      69. Renoir Radeon High Definition Audio Controller Digital Stereo (HDMI) [vol: 0.00 MUTED]
 │      71. UMC202HD 192k Pro                   [vol: 0.85]
 │  *   70. USB SPDIF Receiver Digital Stereo (IEC958) [vol: 1.20]
 │      72. UMC202HD 192k Pro                   [vol: 0.00 MUTED]
```
