### ISSUE TITLE
[Problem]: Car Install guide out of date for new Raspberry Pi OS Release 2023-10-10 (Bookworm). 

### ISSUE THREAD

**Issue by jniclas** [mikebrady/shairport-sync#1750]
### What happened?

Hi, I tried to follow the instruction https://github.com/mikebrady/shairport-sync/blob/master/CAR%20INSTALL.md with the new Raspberry Pi OS release, but the host part did not work, due to the change in the release, that removed dhcpcd as networking interface:

https://downloads.raspberrypi.com/raspios_lite_armhf/release_notes.txt?_gl=1*ub7nig*_ga*MTM0NTg1NTA5MC4xNjk3MjkzODcx*_ga_22FD70LWDS*MTY5NzM1MDE5OS40LjAuMTY5NzM1MDE5OS4wLjAuMA..

### System Information.

Raspberry Pi 3B with Raspberry Pi OS lite 2023-10-10

### Configuration Information.

```shell
shairport-sync works fine
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for alerting us to this. A note has been added to the guide. It may take some time (weeks) to properly update it.

**Comment by mikebrady** [comment]
Hi there. The guide has been updated in the `development` branch. There have been quite a few detailed changes.

If you were to try it out and report back, it would be appreciated.

**Comment by jniclas** [comment]
Cool, I test this in the next days 👍🏻

**Comment by jniclas** [comment]
Morning! I tested the CAR INSTALL.md document on the development branch successfully on my Raspberry Pi 3B 1GB.
It takes ~25sec until my phone catches the WLAN hotspot 👌🏻

**Comment by mikebrady** [comment]
> Morning! I tested the CAR INSTALL.md document on the development branch successfully on my Raspberry Pi 3B 1GB. It takes ~25sec until my phone catches the WLAN hotspot 👌🏻

That is good news indeed. I've made some more changes to the document that I'll be posting soon. They won't made it start any quicker, but they might slightly simplify updating. Thanks for drawing attention to the Bookworm update!

**Comment by jniclas** [comment]
Sounds good! You‘re Welcome 🙂
So I close the issue?

**Comment by mikebrady** [comment]
> So I close the issue?

I’ll just do it now, thanks.
