### ISSUE TITLE
[Problem]: Docker container not starting since 4.2 (Asahi Linux issue?)

### ISSUE THREAD

**Issue by powerflo** [mikebrady/shairport-sync#1756]
### What happened?

I'm running shairport-sync on Docker using the mikebrady/shairport-sync image.
The mikebrady/shairport-sync:4.1.1 image works fine.

Since release 4.2 shairport sync does not start anymore. Looking at the logs it seems like dbus does not start successfully, and everything after that is waiting for dbus to start.

Let me know if I can provide more information.

### Relevant log output

```shell
shairport-sync  | s6-rc: info: service s6rc-fdholder: starting
shairport-sync  | s6-rc: info: service s6rc-oneshot-runner: starting
shairport-sync  | s6-rc: info: service s6rc-oneshot-runner successfully started
shairport-sync  | s6-rc: info: service fix-attrs: starting
shairport-sync  | s6-rc: info: service s6rc-fdholder successfully started
shairport-sync  | s6-rc: info: service fix-attrs successfully started
shairport-sync  | s6-rc: info: service legacy-cont-init: starting
shairport-sync  | s6-rc: info: service legacy-cont-init successfully started
shairport-sync  | s6-rc: info: service syslogd-prepare: starting
shairport-sync  | s6-rc: info: service 01-startup: starting
shairport-sync  | STARTING - Mon Oct 30 20:08:21 UTC 2023
shairport-sync  | s6-rc: info: service 01-startup successfully started
shairport-sync  | s6-rc: info: service 04-nqptp: starting
shairport-sync  | s6-rc: info: service 02-dbus: starting
shairport-sync  | s6-rc: info: service 04-nqptp successfully started
shairport-sync  | Starting dbus
shairport-sync  | Starting nqptp
shairport-sync  | s6-rc: info: service syslogd-prepare successfully started
shairport-sync  | s6-rc: info: service syslogd-log: starting
shairport-sync  | s6-rc: info: service syslogd-log successfully started
shairport-sync  | s6-rc: info: service syslogd: starting
shairport-sync  | s6-rc: info: service syslogd successfully started
```

### System Information.

Mac Mini M1 running Asahi Linux

### Configuration Information.

```shell
$ uname -a
Linux macmini 6.5.0-asahi-15-1-ARCH #1 SMP PREEMPT_DYNAMIC Thu, 12 Oct 2023 08:22:22 +0000 aarch64 GNU/Linux
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post.

Can I clarify what Docker image you are using, please. Is it just the latest, or are you using any particular tag?

**Comment by powerflo** [comment]
Both the 4.2 tag and the latest tag are affected. The 4.1.1 tag is the last that works for me.

**Comment by powerflo** [comment]
Update: I've build the image on my local machine and tried to identify the change that causes the issue and it seems to be connected to the alpine version update in bea0faf488f18ca51552705519a67fa65ff29af5:

Changing the Dockerfile from the master branch to use an older alpine version fixes the issue. I've tried alpine:3.15 and crazymax/alpine-s6:3.15-3.1.1.2 and the dbus version is 1.12.26 and is working.

In alpine:3.17 the dbus version is 1.14.8 and probably causes the issue on my machine.

**Comment by mikebrady** [comment]
Thanks for the update -- yeah, I can't help wondering if it is something to do with Asahi Linux...

**Comment by powerflo** [comment]
I've digged further and with alpine:3.17 and dbus version 1.14.8 it takes almost 3 minutes until dbus is ready.

s6-notifyoncheck is used in the run command to check readyness: [exec s6-notifyoncheck  dbus-daemon --system --nofork --nopidfile](https://github.com/mikebrady/shairport-sync/blob/90c03bf0533ca10776db32c5206f605a3460c6d8/docker/etc/s6-overlay/s6-rc.d/02-dbus/run#L3)

From the [s6-notifyoncheck documentation](https://skarnet.org/software/s6/s6-notifyoncheck.html):
> It loops until ./data/check succeeds, or 7 attempts fail, or a certain amount of time elapses.

So the maximum number of checks are reached before dbus is ready.

This can be changed by setting the -n option for the s6-notifyoncheck command
> -n n : give up after n unsuccessful invocations of ./data/check. 0 means infinite, i.e. keep polling until it succeeds, or times out, or the service dies first. Default is 7.

I've tried with -n 0 and after dbus is ready the other services continue to start as expected.

**Comment by mikebrady** [comment]
Thank you so much for this! Do you mean 3 *seconds*?

**Comment by powerflo** [comment]
Minutes :(
The log with -n 0 and timestamps show how long it takes...
```
shairport-sync  | 2023-10-31T11:14:16.025365391Z s6-rc: info: service 02-dbus: starting
shairport-sync  | 2023-10-31T11:14:16.025985214Z s6-rc: info: service 04-nqptp successfully started
shairport-sync  | 2023-10-31T11:14:16.026559787Z Starting nqptp
shairport-sync  | 2023-10-31T11:14:16.026570912Z Starting dbus
shairport-sync  | 2023-10-31T11:14:16.029369489Z s6-rc: info: service syslogd-prepare successfully started
shairport-sync  | 2023-10-31T11:14:16.029413655Z s6-rc: info: service syslogd-log: starting
shairport-sync  | 2023-10-31T11:14:16.033831788Z s6-rc: info: service syslogd-log successfully started
shairport-sync  | 2023-10-31T11:14:16.033913495Z s6-rc: info: service syslogd: starting
shairport-sync  | 2023-10-31T11:14:16.035767630Z s6-rc: info: service syslogd successfully started
shairport-sync  | 2023-10-31T11:16:58.375807456Z s6-rc: info: service 02-dbus successfully started
shairport-sync  | 2023-10-31T11:16:58.375883789Z s6-rc: info: service 03-avahi: starting
shairport-sync  | 2023-10-31T11:16:58.377662139Z Starting avahi
```

I am still trying to figure out why it is taking so long. But otherwise -n 0 would be a solution so that s6 doesn't get stuck.

**Comment by mikebrady** [comment]
Yikes, 3 minutes is a long time! 😬

**Comment by powerflo** [comment]
I've looked at `strace dbus-daemon` and I don't understand much of it but that the "EBADF (Bad file descriptor)" line repeats very often looks wrong.
<details><summary>strace output</summary>
<pre>
execve("/usr/bin/dbus-daemon", ["dbus-daemon"], 0xffffdbc84cf0 /* 6 vars */) = 0
set_tid_address(0xfffed5d06230)         = 28
brk(NULL)                               = 0xaaab95fb4000
brk(0xaaab95fbc000)                     = 0xaaab95fbc000
mmap(0xaaab95fb4000, 16384, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xaaab95fb4000
openat(AT_FDCWD, "/etc/ld-musl-aarch64.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libdbus-1.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/libdbus-1.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libdbus-1.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=329624, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 409600, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xfffed5bf0000
mmap(0xfffed5c4c000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x4c000) = 0xfffed5c4c000
close(3)                                = 0
openat(AT_FDCWD, "/lib/libexpat.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/libexpat.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libexpat.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=198256, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 212992, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xfffed5bbc000
mmap(0xfffed5be8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2c000) = 0xfffed5be8000
close(3)                                = 0
mprotect(0xfffed5c4c000, 16384, PROT_READ) = 0
mprotect(0xfffed5be8000, 16384, PROT_READ) = 0
mprotect(0xaaab6cd2c000, 16384, PROT_READ) = 0
openat(AT_FDCWD, "/dev/null", O_RDWR|O_LARGEFILE) = 3
dup3(3, 0, 0)                           = 0
close(3)                                = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1073741816, rlim_max=1073741816}) = 0
fcntl(3, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(4, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(5, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(6, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(7, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(8, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(9, F_GETFD)                       = -1 EBADF (Bad file descriptor)
fcntl(10, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(11, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(12, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(13, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(14, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(15, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(16, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(17, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(18, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(19, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(20, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(21, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(22, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(23, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(24, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(25, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(26, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(27, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(28, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(29, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(30, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(31, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(32, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(33, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(34, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(35, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(36, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(37, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(38, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(39, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(40, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(41, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(42, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(43, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(44, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(45, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(46, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(47, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(48, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(49, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(50, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(51, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(52, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(53, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(54, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(55, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(56, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(57, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(58, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(59, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(60, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(61, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(62, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(63, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(64, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(65, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(66, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(67, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(68, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(69, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(70, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(71, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(72, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(73, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(74, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(75, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(76, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(77, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(78, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(79, F_GETFD)                      = -1 EBADF (Bad file descriptor)
fcntl(80, F_GETFD)                      = -1 EBADF (Bad file descriptor)
// ...
fcntl(19889638, F_GETFD)                = -1 EBADF (Bad file descriptor)
fcntl(19889639, F_GETFD)                = -1 EBADF (Bad file descriptor)
fcntl(19889640, F_GETFD)                = -1 EBADF (Bad file descriptor)
fcntl(19889641, F_GETFD)                = -1 EBADF (Bad file descriptor)
fcntl(19889642, F_GETFD)                = -1 EBADF (Bad file descriptor)
// and a lot more...
<pre>
</details>

**Comment by mikebrady** [comment]
> I've looked at `strace dbus-daemon` and I don't understand much of it but that the "EBADF (Bad file descriptor)" line repeats very often looks wrong.

It looks bad alright!

**Comment by iVolt1** [comment]
Hi Mike.  I don't know if you have heard of the docker change change that broke a lot of Docker containers including containers used as Home Assistant addons that use avahi/mdns for instance.

Here is some discussion of the issue:

https://github.com/moby/moby/pull/45534

This is an example of an addon that resolved it by adding the ulimit call before the exec

```
# Set max open file limit to avoid memory allocation issues
ulimit -n 1048576
```

Limit maximum open file handles for EMQX specifically
Newer Docker versions (their default systemd service definitions) have
a higher limit of open file handles than previously. It seems that EMQX
allocates memory proportional to the limit of open file handles, which
leads to out of memory errors on certain platforms.

Set the limit to the same value Docker has been using in earlier
version.

https://github.com/agners/addon-emqx/commit/0bc3cf0ac62b327c78366118ef846cf1c045baff

I suppose the docker change could be rolled back at some point and I don't what programs or services actually need the ulimit value set, but I hope this helps you or the OP resolve the issue.

**Comment by mikebrady** [comment]
Many thanks @iVolt1. It would be interesting to see if it does indeed resolve the OP's issue.

**Comment by powerflo** [comment]
That actually fixed the problem!!!
I added the call to ulimit in the docker/etc/s6-overlay/s6-rc.d/02-dbus/run file and now dbus starts again.

**Comment by mikebrady** [comment]
As soon as I get a chance, I’ll add this to the `development` branch.

**Comment by rp86** [comment]
> As soon as I get a chance, I’ll add this to the `development` branch.

Hi, just checking if this is still intended? dbus was failing to start for me also, and was resolved with the above ulimit fix.

Thanks!

**Comment by mikebrady** [comment]
Of course, I forgot! Darn it. Expect it in a few days, and please send reminder if not!

**Comment by mikebrady** [comment]
Actually I just pushed an update. Maybe allow about an hour for the Docker imagers to be updated (by GitHub actions) -- it's now June 8, 13:10 UTC.

**Comment by rp86** [comment]
> Actually I just pushed a `development` update with the changes.

Thanks for your rapid response!! Unfortunately the pushed fix didn't work for me, for some reason (I don't know anything about the S6 system) it doesn't work with the ulimit command in the 01-startup section; it does still work when manually added to the 02-dbus/run file:

`#!/command/with-contenv sh

echo "Starting dbus"
ulimit -n 1048576
exec s6-notifyoncheck  dbus-daemon --system --nofork --nopidfile`

**Comment by mikebrady** [comment]
Thanks for the feedback! I’ll change it later today or tomorrow.

**Comment by mikebrady** [comment]
That should be done now... Feedback appreciated!

**Comment by rp86** [comment]
Amazing, thanks! Pushed fix works, both current development images load correctly with no dbus hangs.
