### ISSUE TITLE
[Problem]: Intermittent issue when skipping to next song

### ISSUE THREAD

**Issue by jb1228** [mikebrady/shairport-sync#1761]
### What happened?

Very often when skipping to the next song in the Music app, Shairport-Sync seems to skip to a _different_ position in the **_current_** song and continue playing it for about 15 seconds before actually starting the next song. 

However the Music app doesn't seem to notice anything. It skips to the next song immediately and the track position start counting up from 0:00. So when the next song actually starts to play, the track position in the Music app is about 15 seconds ahead. 

While this happens frequently when playing from my iPhone (15 Pro Max - iOS 17.1.1), I have yet to see any issues when playing from my Mac (MacBook Air M1 - macOS 14.1). 

This also doesn't seem to be a problem Classic Airplay. I recompiled Shairport-Sync without Airplay 2 support and couldn't replicate the issue. 

### Relevant log output

```shell
I did not notice any odd messages in the log when I press the button to skip to the next song and Shairport-Sync skips to a different position in the current song. 

However I do see the messages below after about 15 seconds when Shairport-Sync does actually skip to the next song.

Here are the relevant log messages from 4 different occurrences of the issue:

------------------------------

Nov 11 22:45:04 media snapserver[423276]: (Airplay)          0.375206417 "rtp.c:2746" Block with unexpected timestamp. Expected: 2212711510, got: 2212709398, difference: -2112, blocks_read_in_sequence: 699.
Nov 11 22:45:05 media snapserver[423276]: (Airplay)          0.160829370 "rtp.c:2602" Unexpected time difference between packets -- actual: 2212716566, expected: 2212718678, difference: -2112. Packets played: 2048. Blocks played since flush: 706.

------------------------------

Nov 11 22:48:10 media snapserver[423276]: (Airplay)          0.191779481 "rtp.c:2746" Block with unexpected timestamp. Expected: 2659690493, got: 2659688381, difference: -2112, blocks_read_in_sequence: 379.
Nov 11 22:48:10 media snapserver[423276]: (Airplay)          0.181135663 "rtp.c:2602" Unexpected time difference between packets -- actual: 2659695549, expected: 2659697661, difference: -2112. Packets played: 1120. Blocks played since flush: 386.

------------------------------

Nov 11 22:49:53 media snapserver[423276]: (Airplay)          0.364333945 "rtp.c:2746" Block with unexpected timestamp. Expected: 2518153274, got: 2518151162, difference: -2112, blocks_read_in_sequence: 505.
Nov 11 22:49:53 media snapserver[423276]: (Airplay)          0.040277109 "rtp.c:2602" Unexpected time difference between packets -- actual: 2518153210, expected: 2518155322, difference: -2112. Packets played: 1472. Blocks played since flush: 507.

------------------------------

Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.161880842 "rtp.c:2746" Block with unexpected timestamp. Expected: 4067718848, got: 4067716736, difference: -2112, blocks_read_in_sequence: 501.
Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.181094483 "rtp.c:2602" Unexpected time difference between packets -- actual: 4067723904, expected: 4067726016, difference: -2112. Packets played: 1472. Blocks played since flush: 508.
Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.412590780 "player.c:1131" Dropping out of date packet 1473 with timestamp 4067724256. Lead time is 0.109433 seconds.
Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.000015310 "player.c:1131" Dropping out of date packet 1474 with timestamp 4067724608. Lead time is 0.117415 seconds.
Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.000005967 "player.c:2487" Player: packets out of sequence: expected: 1473, got: 1475, with ab_read: 1476 and ab_write: 1524.
Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.039984903 "player.c:1131" Dropping out of date packet 1479 with timestamp 4067726368. Lead time is 0.117302 seconds.
Nov 11 23:26:24 media snapserver[423276]: (Airplay)          0.000019595 "player.c:2487" Player: packets out of sequence: expected: 1479, got: 1480, with ab_read: 1481 and ab_write: 1530.



I can certainly provide more info/logs if it can help.
```

### System Information.

Client:

- iPhone 15 Pro Max 
- iOS 17.1.1
- Apple's Music app

Server:

- Debian 11
- VMware Virtual Machine
- 8 vCPUs
- 8 GB RAM

Host:

- Intel(R) Core(TM) i9-10900 CPU
- VMware ESXi-8.0b-21203435-standard

### Configuration Information.

```shell
Configured with the following options:
./configure --sysconfdir=/etc --with-alsa  --with-apple-alac --with-ao  --with-soxr --with-avahi --with-ssl=openssl --with-systemd  --with-stdout --with-pipe --with-metadata --with-mqtt-client --with-libdaemon --with-external-mdns --with-airplay-2


# shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux media 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 11 (bullseye)

Shairport Sync Version String:
 4.3.2-1-g90c03bf0-AirPlay2-smi10-alac-libdaemon-OpenSSL-Avahi-external_mdns-ALSA-ao-stdout-pipe-soxr-metadata-mqtt-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   interpolation = "soxr";
 };
 pw :
 {
 };
 metadata :
 {
   enabled = "yes";
   include_cover_art = "yes";
   cover_art_cache_directory = "/tmp/shairport-sync/.cache/coverart";
   progress_interval = 1.0;
 };
 mqtt :
 {
   enabled = "yes";
   hostname = "REDACTED";
   port = 1883;
   username = "REDACTED";
   password = "REDACTED";
   topic = "shairport";
   publish_raw = "yes";
   publish_parsed = "yes";
   publish_cover = "yes";
   enable_remote = "yes";
 };

>> Display Config End.
>> Goodbye!



Shairport-Sync is being launched by a Snapcast server on the same machine using the following source line in my /etc/snapserver.conf file:

source = airplay:///usr/local/bin/shairport-sync?name=Airplay&dryout_ms=2000&port=7000&devicename=Snapcast&codec=pcm&params=-vv%20--log-to-syslog%20--metadata-enable



Log output when Shairport-Sync is launched: 

Startup in AirPlay 2 mode, with features 0x405fca00,0x1c340 on device "REDACTED".
Version String: "4.3.2-1-g90c03bf0-AirPlay2-smi10-alac-libdaemon-OpenSSL-Avahi-external_mdns-ALSA-ao-stdout-pipe-soxr-metadata-mqtt-sysconfdir:/etc"
Command Line: "/usr/local/bin/shairport-sync --name=Snapcast --output=stdout --use-stderr --get-coverart -vv --log-to-syslog --metadata-enable --metadata-pipename=/tmp/shairmeta.426321.7000 --port=7000"
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. I think I have noticed this occasionally, but haven't been able to reproduce it. I'll take a good look.

**Comment by mikebrady** [comment]
Okay, so I've been looking at this, and it _seems_ to be a problem in the incoming data -- it looks as if the parameters that specify which blocks of audio must be skipped to get to the next track don't correspond to the information in the blocks actually queued in the incoming audio buffer.

Specifically, each block of audio frames contains an index number, and the indexes of queued blocks normally seem to go up in sequence. When you skip to the next track, a command is sent to skip to a block with a specific index. Shairport Sync discards blocks one by one until it reaches the indexed block.

However, sometimes there is a discontinuity in the sequence of block indexes, and instead of the next block having the current block index + 1, it has a different index number. Shairport Sync stops discarding blocks when that happens.

One might suggest that Shairport Sync should simply skip the number of blocks equal to the target block index and the current block index, irrespective of the block indexes themselves. There are two problems with that.
1. The timing information that is received is exactly right for the block with the unexpected block index, which seems to indicate that this is the block index the synchronisation system of AirPlay is expecting.
2. Even if Shairport Sync skipped the number of blocks equal to the difference between the target block index and the current block index, (and ignored each block's index), from testing it emerges that the correct number of block wouldn't be skipped anyway, so the timing would still be wrong.

Overall, therefore -- especially thinking about (1) above -- I think it's a fault in the incoming audio data. Of course it's always possible that we don't understand the flush parameters, so I'll think some more about it...

**Comment by mikebrady** [comment]
Trying a beta of iOS 7.2, the discontinuity of blocks is gone, but skipping is still not working properly — it sometimes plays a few more seconds of the current track before eventually skipping to the next track. And sometimes it doesn’t seem to remember to stop the track when you disconnect from it 🤷‍♂️.

**Comment by jb1228** [comment]
Well I certainly did not expect such a swift and thorough response! Thank you very much for your efforts! 

I've been using Shairport Sybc for years and just discovered Snapcast. They work perfectly together, and now I can even use all my old, original Raspberry Pi / RPi Zeros to stream AirPlay and announcements to every room in my house. 

Very nice. 😊
