### ISSUE TITLE
[Problem]: Shairport Sync and HostAPd Configuration

### ISSUE THREAD

**Issue by chengpings** [mikebrady/shairport-sync#1767]
### What happened?

I was able to run shairport-sync on ubuntu and be able to hear music.
Even using hostapd to create a password-free hotspot, I couldn't set up the new playback speaker in my IPHONE's WLAN Settings.
Can you give me some advice? Thank you。

### System Information.

Allwinner H6

### Configuration Information.

```shell
./configure --sysconfdir=/etc --with-alsa \
--with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2
```

### PulseAudio or PipeWire installed?

- [x] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by chengpings** [comment]
Thank you for your reply. I have been delayed by something at home recently. The car install guide doesn't help me much. I found that some airplay devices can find the device through the wlan interface of the iphone, as shown in the figure wlan.jpg, and then configure wifi through airplay setup, probably sending the wifi account and password to the airplay device through mdns service. After getting the account password, the device will automatically connect, as shown in the figure airspeaker.jpg. It would be great if Shairport Sync also had this feature, so you can connect to any network at any time!
![wlan](https://github.com/mikebrady/shairport-sync/assets/61931464/264b87a5-ddb7-464d-b05a-0d27e3efd1ed)
![airspeaker](https://github.com/mikebrady/shairport-sync/assets/61931464/7b4c36e6-a278-4ae0-81e4-4ddb92c4fec3)

**Comment by mikebrady** [comment]
Thanks. I think those AirPlay devices are using a special protocol with Bluetooth to "see" and communicate with devices that are not connected to WiFi. AFAIK, that protocol has not been documented. Shairport Sync doesn't support it.

**Comment by chengpings** [comment]
As you can imagine, I tested both mac and iphone with Bluetooth turned off. The wlan interface can still be configured for airplay devices.

**Comment by mikebrady** [comment]
Thanks for the update and for the information. The mystery of how those devices deepens! Maybe someone else has a better grasp of the mechanism.
