### ISSUE TITLE
[Problem]: Crackling sound inverse to music volume with Airplay 2

### ISSUE THREAD

**Issue by ConstrictedHubert** [mikebrady/shairport-sync#1783]
### What happened?

When I try to play songs from Apple Music, it always begins with a very loud crackling noise until the music starts; same in between songs. When I directly assign the Raspberry as a general sound output on the Mac, the crackling starts immediately.
Loud music makes the noise vanish. With quiet music, there are still some occasional crackles to hear.

This problem persists for some time and then vanishes, just to return days later. I have had it for some time and across multiple versions of shairport-sync (dev branch).

Using raspotify on the same hardware does not create that noise.

### Relevant log output

```shell
Jan  4 11:24:21 lalaland shairport-sync: Connection 1: Playback started at frame 2431437346 -- AirPlay 2 Buffered.
Jan  4 11:24:29 lalaland shairport-sync: Sync Error ms | Net Sync PPM | All Sync PPM | Output FPS (r) | Output FPS (c)
Jan  4 11:24:29 lalaland shairport-sync:          0.09            0.0            0.0              N/A              N/A
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 65323 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:30 lalaland librespot[585]: [2024-01-04T10:24:30Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:24:31 lalaland librespot[585]: [2024-01-04T10:24:31Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:32 lalaland librespot[585]: [2024-01-04T10:24:32Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:32 lalaland librespot[585]: [2024-01-04T10:24:32Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:24:34 lalaland librespot[585]: [2024-01-04T10:24:34Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:34 lalaland librespot[585]: [2024-01-04T10:24:34Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:24:37 lalaland shairport-sync:         -0.02            0.0            0.0         44099.77         44099.54
Jan  4 11:24:38 lalaland librespot[585]: [2024-01-04T10:24:38Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:24:38 lalaland librespot[585]: [2024-01-04T10:24:38Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:24:45 lalaland shairport-sync:         -0.20            0.0            0.0         44099.87         44099.65
Jan  4 11:24:53 lalaland shairport-sync:         -0.51            0.0            0.0         44100.01         44099.79
Jan  4 11:25:01 lalaland shairport-sync:         -0.28            0.0            0.0         44100.02         44099.79
Jan  4 11:25:09 lalaland shairport-sync:         -0.49            0.0            0.0         44100.02         44099.80
Jan  4 11:25:17 lalaland shairport-sync:         -0.95            0.0            0.0         44100.02         44099.80
Jan  4 11:25:20 lalaland kernel: [ 3714.290703] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan  4 11:25:26 lalaland shairport-sync:         -0.65            0.0            0.0              N/A              N/A
Jan  4 11:25:34 lalaland shairport-sync:         -0.55            0.0            0.0         44099.80         44099.57
Jan  4 11:25:42 lalaland kernel: [ 3735.929819] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan  4 11:25:43 lalaland shairport-sync:         24.60        -1736.3         1736.3              N/A              N/A
Jan  4 11:25:44 lalaland librespot[585]: [2024-01-04T10:25:44Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:25:44 lalaland librespot[585]: [2024-01-04T10:25:44Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 65323 is invalid
Jan  4 11:25:44 lalaland librespot[585]: [2024-01-04T10:25:44Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:25:44 lalaland librespot[585]: [2024-01-04T10:25:44Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:25:44 lalaland librespot[585]: [2024-01-04T10:25:44Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:25:44 lalaland librespot[585]: [2024-01-04T10:25:44Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:25:45 lalaland librespot[585]: [2024-01-04T10:25:45Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:25:46 lalaland librespot[585]: [2024-01-04T10:25:46Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:25:46 lalaland librespot[585]: [2024-01-04T10:25:46Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:25:48 lalaland librespot[585]: [2024-01-04T10:25:48Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:25:48 lalaland librespot[585]: [2024-01-04T10:25:48Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:25:51 lalaland shairport-sync:         -0.28            0.0            0.0         44100.26         44100.03
Jan  4 11:25:51 lalaland librespot[585]: [2024-01-04T10:25:51Z WARN  libmdns::fsm] couldn't parse packet from [fe80::8d1:4959:c168:4eca%3]:5353: type 25 is invalid
Jan  4 11:25:59 lalaland shairport-sync:         -0.52            2.8            2.8         44100.07         44099.85
Jan  4 11:26:07 lalaland shairport-sync:         -1.09            0.0            0.0         44100.03         44099.81
Jan  4 11:26:15 lalaland shairport-sync:         -2.81          753.4          753.4         44100.03         44099.80
Jan  4 11:27:47 lalaland librespot[585]: [2024-01-04T10:27:47Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.26:5353: type 25 is invalid
Jan  4 11:27:47 lalaland librespot[585]: [2024-01-04T10:27:47Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.24:5353: type 25 is invalid
```

### System Information.

Raspberry 3b Rev 1.2
Hifiberry Amp2
MacOS 14.2.1, iOS 17.1.2 and PadOS, as well as previous versions of all of them

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux lalaland 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.3.3-dev-6-ge36ec5c4-AirPlay2-smi10-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Lalaland";
   output_backend = "alsa";
 };
 alsa : 
 {
   output_device = "hw:sndrpihifiberry";
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. It seems that`librespot` and Shairport Sync are running at the same time. Can you stop `librespot` completely and see what happens, please?

**Comment by ConstrictedHubert** [comment]
It had been working flawlessly for two weeks, with librespot running and being used.
Now, all of a sudden, the crackling came back. Killed the libresprot task, crackling stayed. Remove librespot, rebooted and it is working right now.

This is the log from before the reboot:
`
Jan 18 13:31:25 lalaland kernel: [1220887.908691] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:31:43 lalaland systemd[1]: raspotify.service: Succeeded.
Jan 18 13:31:43 lalaland systemd[1]: raspotify.service: Consumed 9min 6.863s CPU time.
Jan 18 13:31:46 lalaland kernel: [1220908.474841] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:33:25 lalaland shairport-sync: Connection 32: Playback stopped. Total playing time 00:18:07. Output: 44100.03 (raw), 44100.31 (corrected) frames per second.
Jan 18 13:33:32 lalaland kernel: [1221014.846664] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:33:34 lalaland shairport-sync: Connection 33: Playback started at frame 2331840758 -- AirPlay 2 Buffered.
Jan 18 13:33:41 lalaland kernel: [1221023.704962] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:33:43 lalaland kernel: [1221025.467640] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:34:12 lalaland dhcpcd[536]: wlan0: part of Router Advertisement expired
Jan 18 13:35:14 lalaland systemd[1]: Started Session 380 of user pi.
Jan 18 13:35:50 lalaland shairport-sync: Connection 33: Playback stopped. Total playing time 00:02:16.
Jan 18 13:36:02 lalaland kernel: [1221164.061400] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:36:03 lalaland shairport-sync: Connection 34: Playback stopped. Total playing time 339:12:45.
Jan 18 13:36:10 lalaland kernel: [1221172.514736] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:37:17 lalaland kernel: [1221239.966487] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:37:18 lalaland shairport-sync: Connection 35: Playback started at frame 1349623233 -- AirPlay 2 Buffered.
Jan 18 13:37:48 lalaland dhcpcd[536]: wlan0: part of Router Advertisement expired
Jan 18 13:38:00 lalaland shairport-sync: Connection 35: Playback stopped. Total playing time 00:00:42.
Jan 18 13:38:00 lalaland systemd[1]: Stopping Shairport Sync - AirPlay Audio Receiver...
Jan 18 13:38:00 lalaland systemd[1]: shairport-sync.service: Succeeded.
Jan 18 13:38:00 lalaland systemd[1]: Stopped Shairport Sync - AirPlay Audio Receiver.
Jan 18 13:38:00 lalaland systemd[1]: shairport-sync.service: Consumed 3h 55min 59.204s CPU time.
Jan 18 13:38:00 lalaland systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Jan 18 13:38:06 lalaland shairport-sync: warning: failed to find mixer control "snd_soc_hifiberry_dacplus",0.
Jan 18 13:38:06 lalaland kernel: [1221288.114884] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:38:08 lalaland shairport-sync: Connection 1: Playback started at frame 2026313545 -- AirPlay 2 Buffered.
Jan 18 13:38:12 lalaland shairport-sync: Connection 1: Playback stopped. Total playing time 00:00:04.
Jan 18 13:38:12 lalaland systemd[1]: Stopping Shairport Sync - AirPlay Audio Receiver...
Jan 18 13:38:12 lalaland systemd[1]: shairport-sync.service: Succeeded.
Jan 18 13:38:12 lalaland systemd[1]: Stopped Shairport Sync - AirPlay Audio Receiver.
Jan 18 13:38:12 lalaland systemd[1]: shairport-sync.service: Consumed 2.210s CPU time.
Jan 18 13:38:12 lalaland systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Jan 18 13:38:45 lalaland dhcpcd[536]: wlan0: part of Router Advertisement expired
Jan 18 13:39:52 lalaland shairport-sync: warning: failed to find mixer control "snd_soc_hifiberry_dacplus",0.
Jan 18 13:39:52 lalaland kernel: [1221394.144834] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:39:53 lalaland shairport-sync: Connection 1: Playback started at frame 2806547696 -- AirPlay 2 Buffered.
Jan 18 13:40:01 lalaland kernel: [1221403.289940] pcm512x 1-004d: No SCLK, using BCLK: -2
Jan 18 13:40:02 lalaland shairport-sync: Sync Error ms | Net Sync PPM | All Sync PPM | Output FPS (r) | Output FPS (c)
Jan 18 13:40:02 lalaland shairport-sync:         -0.23            0.0            0.0              N/A              N/A

`

**Comment by ConstrictedHubert** [comment]
Issue hasn't reappeared since I removed librespot. Issue solved (unless you want to run both servers in parallel)
