### ISSUE TITLE
[Problem]: delay when using vmware and a homepod mini

### ISSUE THREAD

**Issue by Noboxj** [mikebrady/shairport-sync#1788]
### What happened?

hello
The pc has like a 0.8 seconds delay when music is playing on linux via vmware and my homepod mini.

### System Information.

i'm using a windows 11 pc running ubuntu on vmware.

### Configuration Information.

```shell
From "uname -a":

Linux Albixpc 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:

49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

From /etc/os-release:

Ubuntu 23.10

Shairport Sync Version String:

4.3.2-1-990c03bf0-AirPlay2-smi10-OpenSSL-Avahi-pw-soxr-sysconfdir:/etc

Command Line:

shairport-sync --displayConfig

Configuration File:

/etc/shairport-sync.conf

Configuration File Settings:

pw :
{
};
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Homebrew for Mac

### Check previous issues

- [X] Confirm

**Comment by Noboxj** [comment]
sorry forgot to change i installed shairport-sync by a package manager

**Comment by mikebrady** [comment]
Thanks for the post, and apologies for the delay.

If I understand your post properly, the problem is that the audio coming from Shairport Sync, running in Ubuntu 23.10 on a VMWare VM in a Windows 11 PC is about 0.8 seconds late and is out of sync with the audio coming from the source -- a HomePod mini.

I have noticed that the audio coming from a VMWare VM is always delayed, usually be a few 10s to 100s of milliseconds, and I believe that it's a limitation of the virtualisation. That being the case, I'm afraid there isn't anything that can easily be done about it.

**Comment by Noboxj** [comment]
Ok thanks you for the response
Is there another way to use shairport-sync on windows 11 so that i could have way less delay ?

**Comment by mikebrady** [comment]
Thanks. It needs Linux or Unix, and I have never tried the Linux compatibility subsystem in Windows. Maybe someone else has?

**Comment by Noboxj** [comment]
I tried the linux subsystem in wodws but coudn't get it to work...

**Comment by mikebrady** [comment]
> I tried the linux subsystem in wodws but coudn't get it to work...

Thanks for the clarification.

**Comment by Noboxj** [comment]
The problème there is with wsl is that it's pretty hard to connect your sound output to ubuntu. And that's the step i'm blocked at.

**Comment by mikebrady** [comment]
Thanks. I’m away from computers until the end of the month, but after that I will experiment…

**Comment by Noboxj** [comment]
I'll be happy to know if you've succeed. And if yes how you did it.

**Comment by Noboxj** [comment]
Any news ?

**Comment by mikebrady** [comment]
Apologies for the delay. It turns out that I don't have a machine that is capable of running Windows 11 with virtualisation, so I can't run `wsl`.

**Comment by Noboxj** [comment]
Oh ok it's true that you must have a pretty recent machine to be able to run it. Still thanks for the response.

**Comment by mikebrady** [comment]
> Oh ok it's true that you must have a pretty recent machine to be able to run it. Still thanks for the response.

Apologies again for the delay. Apparently VMWare Fusion doesn't support virtualisation on Apple Silicon either. 😕

**Comment by mriwhh** [comment]
WSL as well as VMWARE virtualize. Using both on the same host might be a cause for some performance issues and delays. 
WSL relies on Microsoft Hyper-V and in fact when activating Hyper-V even Windows technically runs kind of virtualized. Installing VMware on top leads to some double virtualization.
You could try Ubuntu on Hyper-V or VMWARE on a fresh installed clean slate Windows.

**Comment by Noboxj** [comment]
Ok thanks i'll give it a shot this weekend

**Comment by Noboxj** [comment]
Anybody got any news of how to resolve this issue or does someone knows a workaround or another way to do it ?
