### ISSUE TITLE
Auto start after reboot

### ISSUE THREAD

**Issue by maumi** [mikebrady/shairport-sync#179]
I use shairport-sync on 2 rPi2, both with OSMC.
Ithink I did the same things to install it. On one pi ss starts automatic but on the other pi I always need to "sudo systemctl start shairport-sync".
I know it's not a real issue related to ss, more to debian.
But maybe you have an idea to solve this little annoying problem.

**Comment by mikebrady** [comment]
On the machine where it does not start automatically, enter `sudo systemctl enable shairport-sync` and then it should start automatically on reboot.

**Comment by maumi** [comment]
Already tried that. But no effect

**Comment by mikebrady** [comment]
Thanks. Is AirPlay disabled in Kodi?

Look in the log using journalctl as root. Also set log verbosity in Shairport Sync to 1 and restart.

**Comment by maumi** [comment]
Sorry, I've said wrong things. The system where it works on startup is a cubox with pure debian, so no kodi distro.
Back to the problem:
Log with verbosity 1 looks unspectacular. Even with verb. 3 I can't see any errors.

Dez 17 10:13:49 osmc shairport-sync[263]: Output device name is "default".
Dez 17 10:13:49 osmc shairport-sync[263]: startup
Dez 17 10:13:49 osmc shairport-sync[263]: avahi: avahi_register.
Dez 17 10:13:49 osmc shairport-sync[263]: avahi: register_service.
Dez 17 10:13:49 osmc shairport-sync[263]: Avahi without metadata

Ah ok, grep found more than my eyes.

End of log:

Dez 17 10:17:33 osmc shairport-sync[254]: avahi: avahi_register.
Dez 17 10:17:33 osmc shairport-sync[254]: avahi: register_service.
Dez 17 10:17:33 osmc shairport-sync[254]: Avahi without metadata
Dez 17 10:17:43 osmc systemd[1]: shairport-sync.service: main process exited, code=killed, status=6/ABRT
Dez 17 10:17:43 osmc systemd[1]: Unit shairport-sync.service entered failed state.
Dez 17 10:17:43 osmc shairport-sync[254]: avahi client failure
Dez 17 10:17:43 osmc shairport-sync[254]: avahi: avahi_unregister.
Dez 17 10:17:43 osmc shairport-sync[254]: shairport-sync: thread-watch.c:149: avahi_threaded_poll_stop: Assertion `!pthread_equal(pthread_self(), p->thread_id)' failed.

**Comment by mikebrady** [comment]
That's interesting – it looks as if avahi isn't ready, or something similar.

The only thing I can suggest is to delay starting Shairport Sync for a few seconds – maybe this might be relevant http://www.freedesktop.org/software/systemd/man/systemd.timer.html

**Comment by maumi** [comment]
Great. Created a delay of 10s. Normally I never restart my pi so I don't experiment on smaller timer.
Thanks for your fast and good support. 
I really like your project and enjoy how flawless it works. Even with multi room sync and also with iOS 9.

**Comment by mikebrady** [comment]
Thanks. If you used that `systemd` timer mechanism, would you be kind enough to post the file contents?

**Comment by maumi** [comment]
For sure.
File is next to shairport-sync.service and called shairport-sync.timer
`
[Unit]
Description=ShairportSync AirTunes receiver
                   
[Timer]                       
OnBootSec=10s              
Unit=shairport-sync.service
       
[Install]    
WantedBy=multi-user.target  
`
Then you need to disable shairport-sync service because the timer is calling the service.
`systemctl disable shairport-service
systemctl start shairport-service.timer
systemctl enable shairport-service.timer
`

**Comment by mikebrady** [comment]
Fantastic, thanks!
