### ISSUE TITLE
Audio only plays for 5 - 10 seconds.

### ISSUE THREAD

**Issue by shiv69420** [mikebrady/shairport-sync#1796]
I installed amixer, set the volume to 100 on master. Got volume and sound for about 5 seconds before it just stopped. My phone still shows its playing but no audio is coming out anymore.

I can get audio for about 5-10 seconds if I select my phone and the speaker again. I also get a pop up saying "cannot connect to Shivs speaker" (shivs speaker my speaker name). But it continues to play audio up until about 6 seconds after. The audio doesn't pause it just stops playing while my phone shows it is still playing audio.

**Comment by shiv69420** [comment]
changed hostname to patels12 and I'm still getting the same issue.

**Comment by shiv69420** [comment]
I installed the wrong version, I fixed it now. 🤦

**Comment by shiv69420** [comment]
I installed the docker but it wasn't working for me it kept giving me the error up above. So I tried the Build linux version on my ubuntu server and I have the speaker in my homekit and I can connect to it but i'm not getting any audio. I have something plugged into the headphone jack but its playing anything.

**Comment by shiv69420** [comment]
After running MikeBrady's alsa explore. I get this
`> Device Full Name:    "hw:PCH"
  Short Name:          "hw:0"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "Master",0              Range:  65.25 dB
                       "Headphone Mic",0       Range:  46.50 dB
                       "Headphone+LO",0        Range:  65.25 dB
                       "Speaker",0             Range:  65.25 dB
                       "PCM",0                 Range:  51.00 dB
                       "Beep",0                Range:  46.50 dB
                       "Headset Mic",0         Range:  46.50 dB
                       "Headphone Mic Boost",0 Range:  30.00 dB
                       "Headset Mic Boost",0   Range:  30.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE

> Device Full Name:    "hw:CARD=PCH,DEV=3"
  Short Name:          "hw:0,3"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "Master",0              Range:  65.25 dB
                       "Headphone Mic",0       Range:  46.50 dB
                       "Headphone+LO",0        Range:  65.25 dB
                       "Speaker",0             Range:  65.25 dB
                       "PCM",0                 Range:  51.00 dB
                       "Beep",0                Range:  46.50 dB
                       "Headset Mic",0         Range:  46.50 dB
                       "Headphone Mic Boost",0 Range:  30.00 dB
                       "Headset Mic Boost",0   Range:  30.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE

> Device Full Name:    "hw:CARD=PCH,DEV=7"
  Short Name:          "hw:0,7"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "Master",0              Range:  65.25 dB
                       "Headphone Mic",0       Range:  46.50 dB
                       "Headphone+LO",0        Range:  65.25 dB
                       "Speaker",0             Range:  65.25 dB
                       "PCM",0                 Range:  51.00 dB
                       "Beep",0                Range:  46.50 dB
                       "Headset Mic",0         Range:  46.50 dB
                       "Headphone Mic Boost",0 Range:  30.00 dB
                       "Headset Mic Boost",0   Range:  30.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE

> Device Full Name:    "hw:CARD=PCH,DEV=8"
  Short Name:          "hw:0,8"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "Master",0              Range:  65.25 dB
                       "Headphone Mic",0       Range:  46.50 dB
                       "Headphone+LO",0        Range:  65.25 dB
                       "Speaker",0             Range:  65.25 dB
                       "PCM",0                 Range:  51.00 dB
                       "Beep",0                Range:  46.50 dB
                       "Headset Mic",0         Range:  46.50 dB
                       "Headphone Mic Boost",0 Range:  30.00 dB
                       "Headset Mic Boost",0   Range:  30.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE

> Device Full Name:    "hw:CARD=PCH,DEV=9"
  Short Name:          "hw:0,9"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "Master",0              Range:  65.25 dB
                       "Headphone Mic",0       Range:  46.50 dB
                       "Headphone+LO",0        Range:  65.25 dB
                       "Speaker",0             Range:  65.25 dB
                       "PCM",0                 Range:  51.00 dB
                       "Beep",0                Range:  46.50 dB
                       "Headset Mic",0         Range:  46.50 dB
                       "Headphone Mic Boost",0 Range:  30.00 dB
                       "Headset Mic Boost",0   Range:  30.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE

> Device Full Name:    "hw:CARD=PCH,DEV=10"
  Short Name:          "hw:0,10"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "Master",0              Range:  65.25 dB
                       "Headphone Mic",0       Range:  46.50 dB
                       "Headphone+LO",0        Range:  65.25 dB
                       "Speaker",0             Range:  65.25 dB
                       "PCM",0                 Range:  51.00 dB
                       "Beep",0                Range:  46.50 dB
                       "Headset Mic",0         Range:  46.50 dB
                       "Headphone Mic Boost",0 Range:  30.00 dB
                       "Headset Mic Boost",0   Range:  30.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S32_LE
`
Note that I do not see anything saying "Headphone". 
The PC that is hosting this (ubuntu server) is a mini pc with a built in speaker, If that helps. Thank you

**Comment by shiv69420** [comment]
I installed amixer, set the volume to 100 on master. Got volume and sound for about 5 seconds before it just stopped. My phone still shows its playing but no audio is coming out anymore.

**Comment by shiv69420** [comment]
I got it to play for about 1 song sometimes but the end result is the same, it just stops playing after a while. Its not my phone as I also tested with multi room audio and it doesn't pause it just stops playing music only on the shairport device.

**Comment by mikebrady** [comment]
Thanks for the post, but you seem to have had a number of issues which seem to have changed, so it's difficult to understand quite what the problems are. Let me suggest that you submit a new issue, and please let us have the information requested -- otherwise we won't have enough information to (hopefully!) help you.
