### ISSUE TITLE
[Problem]: App stops playing music after 5-10 seconds.

### ISSUE THREAD

**Issue by shiv69420** [mikebrady/shairport-sync#1799]
### What happened?

I connect and then i proceed to play music, sometimes it will finish a song and have a problem halfway through the next, or most of the time it only plays for about 5-30seconds. It will pause the music and the speaker will disappear from the airplay choices. It will then reappear after about a minute or 2.

### System Information.

Mini PC
4gb Ram
optiplex 3060 mini

### Configuration Information.

```shell
NA at the moment.
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Could you post the command used to invoke the Docker image, please? Is it:
```
$ docker run -d --restart unless-stopped --net host --device /dev/snd mikebrady/shairport-sync
```
Or is it something else?

**Comment by shiv69420** [comment]
I had used the docker with no luck. So I moved to the build "https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md" and thats when I started getting audio but only for a brief time.

**Comment by shiv69420** [comment]
I also see that everytime I turn on my tv, or airplay from my laptop I get the error "could not connect to (myspeaker)". I get this error on devices that I'm not trying to connect to airplay with, just idle devices.
