### ISSUE TITLE
[Problem]: Apple HomeKit shows "No Response" with AirPlay 2

### ISSUE THREAD

**Issue by Kosti05** [mikebrady/shairport-sync#1802]
### What happened?

I installed and configured Shairport-sync. I added the speaker to my HomeKit. It seems to be working mostly fine, but HomeKit still says that there is no response. I am using a HomePod mini.

### System Information.

Raspberry Pi Zero
DAC: PCM5102 connected to GPIO

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi Zero W Rev 1.1

Shairport Sync Version String:
 4.3.2-2-g165431a8-AirPlay2-smi10-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   name = "Lautsprecher";
 };
 sessioncontrol :
 {
   run_this_before_entering_active_state = "/usr/bin/python3 shairport_startup.py";
   wait_for_completion = "yes";
 };
 pw :
 {
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. If I understand your post properly, Shairport Sync is playing audio okay, but in the Home app, it shows as if it's not responding?

If that is so, unfortunately, it's something we don't know how to fix -- most of the protocols are unknown. There's a bit more discussion e.g. [here](https://github.com/mikebrady/shairport-sync/issues/1543).

**Comment by mikebrady** [comment]
Apologies for the delay. I don’t think that the warnings in the log are related, I’m afraid — I’m guessing you are running Shairport Sync in a Docker container?. It really does seem as if we are missing an understanding of the messages that seem to be exchanged between AirPlay 2 devices.

**Comment by PBHDK** [comment]
> Apologies for the delay. 

No worries!

> I don’t think that the warnings in the log are related, I’m afraid — I’m guessing you are running Shairport Sync in a Docker container?. 

Yes, I am. I already suspected that they might be docker-related but just wanted to make sure.

> It really does seem as if we are missing an understanding of the messages that seem to be exchanged between AirPlay 2 devices.

Ah, that's a shame. But thank you anyway!

**Comment by ageorgios** [comment]
I am running over docker, I have the same problem, is it docker related ?

**Comment by mikebrady** [comment]
Yeah, the [warnings](#issuecomment-1941508037)  reported by @PBHDK are caused indirectly by it being a Docker image. The reason is as follows: A copy of an IPv4 mDNS implementation called Avahi is running on the host, and another copy of it is also running in the Docker image. Shairport Sync needs a local copy of Avahi to function properly. The issue causing the warning seems to be harmless.

The first part of that message: `WARNING: No NSS support for mDNS detected, consider installing nss-mdns!` can also be ignored -- it's really just a suggestion for improved functionality.
