### ISSUE TITLE
[Problem]: fatal error could not establish service

### ISSUE THREAD

**Issue by DifferentComputers** [mikebrady/shairport-sync#1805]
### What happened?

I was trying to set the audio output.

There is not, to my knowledge any other instance. I did attempt to install Rogue Aomeba's Satellite Speakers, but top does not show me that it is running by any reasonable name.

I'd prefer not to completely wipe this up-to-date Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-18-generic x86_64)

Only other software running on this old MacBook Pro is Pi-Hole.

### Relevant log output

```shell
$ shairport-sync output_device = "hw:CARD=HDMI,DEV=3"
fatal error: could not establish a service on port 5000 -- program terminating. Is another instance of Shairport Sync running on this device?
```

### System Information.

Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-18-generic x86_64)

Intel MacBook Pro 2013

### Configuration Information.

```shell
shairport-sync --displayConfig
fatal error: --displayConfig: unknown option

uname -a
Linux SlabBook 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

3.3.8-libdaemon-OpenSSL-Avahi-ALSA-jack-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

There's no output on default. I'm trying to change it to 
shairport-sync output_device = "hw:CARD=HDMI,DEV=3"
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by DifferentComputers** [comment]
Hmmmm. 

`sudo lsof -n -P -i +c 13` tells me

`shairport-syn 1573 shairport-sync    5u  IPv4  28706      0t0  TCP *:5000 (LISTEN)
shairport-syn 1573 shairport-sync    6u  IPv6  28707      0t0  TCP *:5000 (LISTEN)
shairport-syn 1573 shairport-sync   12u  IPv4  33653      0t0  TCP 192.168.0.68:5000->192.168.0.150:58738 (ESTABLISHED)
shairport-syn 1573 shairport-sync   13u  IPv4  33654      0t0  UDP 192.168.0.68:6001 
shairport-syn 1573 shairport-sync   14u  IPv4  33655      0t0  UDP 192.168.0.68:6002 
shairport-syn 1573 shairport-sync   15u  IPv4  33656      0t0  UDP 192.168.0.68:6003 `

So it seems that... well, I dunno. I don't think I have it installed multiple times! I'll try un- and reinstalling.

**Comment by DifferentComputers** [comment]
Tried to edit the config file to add hw:CARD=HDMI,DEV=3 to the output, and that didn't work.

**Comment by mikebrady** [comment]
Thanks for the post. There are a couple of things here:
1. The version of Shairport Sync is very old, and well worth updating.
2. You can get a rough idea of what output devices are available using `$ shairport-sync -h`.
3. The application [`sps-alsa-explore`](https://github.com/mikebrady/sps-alsa-explore) will give you more detail.

**Comment by DifferentComputers** [comment]
It's odd that version of shairport-sync is old--far as I know I was using an up to date link.

also this:

```
$ sudo apt-get upgrade shairport-sync
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
shairport-sync is already the newest version (3.3.8-1build1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

So what am I missing?

I *DID* a` shairport-sync -h` to get the list of outputs. attempting to change outputs generates an error. The output that works when I do a sound check is hw:CARD=HDMI,DEV=3

**Comment by mikebrady** [comment]
Thanks. That package is the problem — it’s very dated. You should build it from sources. There’s a guide in the BUILD.md page.

**Comment by DifferentComputers** [comment]
Building from source worked a charm!

Many thanks for this.
