### ISSUE TITLE
[Problem]: INSTALL_USER_TARGET = install-user-local causes issues for packaging

### ISSUE THREAD

**Issue by p3ck** [mikebrady/shairport-sync#1808]
### What happened?

I'm trying to update the fedora package for shairport-sync and I have previously let the configure script generate and install the sysemd file but now when I do this the Makefile also tries to generate a local user and group.  This should not be done when building the RPM but when installing the RPM.

Can we have a way to generate the systemd file but not try to create the user/group?  An extra flag maybe?

Thanks 

### Relevant log output

```shell
/usr/bin/make  install-am
make[1]: Entering directory '/home/bpeck/Sandbox/shairport-sync/shairport-sync-4.3.2'
make[2]: Entering directory '/home/bpeck/Sandbox/shairport-sync/shairport-sync-4.3.2'
 /usr/bin/mkdir -p '/home/bpeck/rpmbuild/BUILDROOT/shairport-sync-4.3.2-0.fc41.x86_64/usr/bin'
  /usr/bin/install -p shairport-sync '/home/bpeck/rpmbuild/BUILDROOT/shairport-sync-4.3.2-0.fc41.x86_64/usr/bin'
/usr/bin/make  install-exec-hook
make[3]: Entering directory '/home/bpeck/Sandbox/shairport-sync/shairport-sync-4.3.2'
install -d /home/bpeck/rpmbuild/BUILDROOT/shairport-sync-4.3.2-0.fc41.x86_64/etc
install -m 0644 ./scripts/shairport-sync.conf /home/bpeck/rpmbuild/BUILDROOT/shairport-sync-4.3.2-0.fc41.x86_64/etc/shairport-sync.conf.sample
[ -f /home/bpeck/rpmbuild/BUILDROOT/shairport-sync-4.3.2-0.fc41.x86_64/etc/shairport-sync.conf ] || cp ./scripts/shairport-sync.conf /home/bpeck/rpmbuild/BUILDROOT/shairport-sync-4.3.2-0.fc41.x86_64/etc/shairport-sync.conf
getent group shairport-sync &>/dev/null || groupadd -r shairport-sync &>/dev/null
make[3]: *** [Makefile:1656: install-group-local] Error 10
make[3]: Leaving directory '/home/bpeck/Sandbox/shairport-sync/shairport-sync-4.3.2'
make[2]: *** [Makefile:1497: install-exec-am] Error 2
make[2]: Leaving directory '/home/bpeck/Sandbox/shairport-sync/shairport-sync-4.3.2'
make[1]: *** [Makefile:1385: install-am] Error 2
make[1]: Leaving directory '/home/bpeck/Sandbox/shairport-sync/shairport-sync-4.3.2'
make: *** [Makefile:1378: install] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.TWfmMT (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.TWfmMT (%install)
```

### System Information.

Fedora release 39 (Thirty Nine)

### Configuration Information.

```shell
%build
autoreconf -i -f
%configure --sysconfdir=/etc --with-alsa --with-pipe --with-dummy \
           --with-stdout --with-pa --with-pq --with-metadata \
           --with-soxr --with-avahi --with-ssl=openssl \
           --with-systemd --with-ssl=openssl
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. I'll set about it, but it may be a little while...

**Comment by mikebrady** [comment]
Thanks, I'll check it out, soon!

**Comment by mikebrady** [comment]
Just taking a look at this. If I understand your suggestion correctly, you would always build `scripts/shairport-sync.service`, `scripts/shairport-sync.service-avahi` `scripts/shairport-sync` anyway, even when `--with-systemd` configuration flag was not selected. Then, later on in your `spec` file, you would copy them in as appropriate? Did  I get that right?

**Comment by mikebrady** [comment]
Thanks. I'll make that change in there next day or so -- no need for a PR.

**Comment by mikebrady** [comment]
Hi there. I've pushed an update which implements your idea, thanks, but with a slight change that should specialise it to Linux only. I hope it works! Thanks for the idea.
