### ISSUE TITLE
[Problem]: White noise when Apple DAC auto-detected 24-bit format is used

### ISSUE THREAD

**Issue by jasonmc** [mikebrady/shairport-sync#1815]
### What happened?

Hello again Mike!

I'm not sure if this is really an issue with Shairport-sync per-se (and really an issue with the driver) but others may run into it so thought I'd share: when using the latest Shairport-sync on a RPi-3B with Apple's USB-C to 3.5mm DAC there is excessive white noise. This is because the bitrate is chosen as `S24_3LE` (which can be verified from `docker run --device /dev/snd mikebrady/sps-alsa-explore`), however `S24_3LE` only appears to work smoothly for 48kHz audio.

The noise can be trivially reproduced via `speaker-test -t sine -F S24_3LE -r 44100 -c 2 -D hw:A`.

Manually setting the Alsa format to `S16_LE` in `shairport-sync.conf` allows it to work (after also following the instructions to switch the mode in https://github.com/mikebrady/shairport-sync/issues/1504).

### Relevant log output

```shell
> Device Full Name:    "hw:Headphones"
  Short Name:          "hw:0"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "PCM",0                 Range: 106.38 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S16_LE

> Device Full Name:    "hw:A"
  Short Name:          "hw:1"
  This device seems suitable for use with Shairport Sync.
  Possible mixers:     "PCM",0                 Range:  60.00 dB
  The following rate and format would be chosen by Shairport Sync in "auto" mode:
     Rate              Format
     44100             S24_3LE
```

### System Information.

Raspberry Pi 3b
Apple USB-C to 3.5mm Adapter

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux bedroompi 6.5.0-1011-raspi #14-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 14:06:28 UTC 2024 aarch64 Linux

From /etc/os-release:
 Alpine Linux v3.17

Shairport Sync Version String:
 4.3.3-dev-31-g2dba9bc8-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 alsa :
 {
   output_format = "S16_LE";
 };
 pw :
 {
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post.

I notice that you are not actually specifying the `output_device`, so output is probably going to the default `alsa` device, which in all probability is an `alsa` pseudo-device with built-in transcoding. Let me suggest that you try setting the output device to `"hw:A"` and the mixer name to `"PCM"` and restarting. 

Note that a jack must be plugged in to the Apple USB audio adapter for it to appear as an audio output device, and also, when you disconnect, it may forget how to change to 44,100...
