### ISSUE TITLE
[Problem]: Configuration issues

### ISSUE THREAD

**Issue by wressens** [mikebrady/shairport-sync#1825]
### What happened?

Tried to install it several times with different guides. But cant get it to act like airplay 2 where you can select other airplay 2 speakers at the same time. 
Installed nqptp. 

What am I missing? Cant find anything in the config referencing airplay 2? 

### System Information.

Raspberry pie 3 a+ pi os lite.

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 6.6.21-v8+ #1741 SMP PREEMPT Fri Mar  8 13:40:00 GMT 2024 aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model A Plus Rev 1.1

Shairport Sync Version String:
 4.3.2-2-g165431a8-OpenSSL-Avahi-ALSA-pa-pipe-soxr-metadata-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 pw : 
 {
 };
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Just looking at the Configuration Information, you can see that the Version String:
```
4.3.2-2-g165431a8-OpenSSL-Avahi-ALSA-pa-pipe-soxr-metadata-sysconfdir:/etc
```
does not include `airplay2` (or similar — I’m not near a computer just now), so it means that Shairport Sync has been built for classic AirPlay operation only.

Let me suggest that you follow our own [BUILD.md](https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md) guide exactly and precisely and you should be okay.

**Comment by wressens** [comment]
I have followed that guide. Reinstalled the whole PI OS and done it again with no success. If I fail to install it as airplay 2, must it be completely uninstalled and installed again?  

Is the PI OS version important? 32bit, 64bit? Lite or full version? 

Im grateful for the help. Spent so many hours on this now. hehe I promised a friend to help here create a multi-room system with her Apple tv4 and here kitchen speaker.

**Comment by mikebrady** [comment]
Lite is best, 32/64 doesn’t matter. If you want to start over, it’s probably easier to start with a fresh version of the OS. Please note that every detail and step in the guide is important, and  that Unix is case-sensitive, i.e. it distinguishes between uppercase and lowercase.

**Comment by wressens** [comment]
Got it working now. I think i needed "sudo" on som of the lines. I have very limited knowledge but I think the "autoreconf -fi" failed without sudo and I missed that. Its not easiest thing to setup when you dont have any knowledge about these things. 

It works great now. By the way do you need to play around with audio sync depending how far the speakers are from each other? (after some distance theres bound the be some echo effect I would suppose?)

Thanks for an awesome work!

**Comment by MRIO** [comment]
Hi Wressens, to synchronize you will need to tune the delay as a function of speaker distance `audio_backend_latency_offset_in_seconds = 0.0`, which you'll find in the configuration file `shairport-sync.conf`, possibly located at /etc/
