### ISSUE TITLE
[Problem]: No sound after restart

### ISSUE THREAD

**Issue by Jumbo125** [mikebrady/shairport-sync#1826]
### What happened?

Hy. 
Great project!!!

I try to stream music from owntone to shairport to listen music in another room.
So i installed nqptp and shairport.

After finished the installation, it worked (i need to set the volume higher, via alsamixer)

I was happy. Sounds great!

EDIT: FOUND THE PROBLEM, BUT MISSING SOLUTION!

when i enter in terminal:
`shairport-sync
`
it works!
but when i start it with 
`sudo systemctl restart shairport-sync`
 
it not works....

------   OLD POST ----------------

_But i need to sethup the DHCP and so i changed the IP-Adress from the raspi and did a restart

So i tried to run it automatically after restart the pi (raspi pi 3 B)

the services start correctly. (shairport and nqptp)
the speaker-test works too. I hear the sound. 

I tried it with the direct 3.5 klinke output and a external soundcard.
The speaker test works on both, but shairport not.

Do you have any ideas?

Thank you!_

### Relevant log output

```shell
raspberry@raspberrypi2:/etc $ shairport-sync -V
4.3.2-2-g165431a8-AirPlay2-smi10-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc



raspberry@raspberrypi2:/etc $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; prese>
     Active: active (running) since Fri 2024-03-15 14:11:44 CET; 13min ago
   Main PID: 1962 (shairport-sync)
      Tasks: 12 (limit: 756)
        CPU: 3min 27.694s
     CGroup: /system.slice/shairport-sync.service
             └─1962 /usr/local/bin/shairport-sync --log-to-syslog

Mar 15 14:11:44 raspberrypi2 systemd[1]: Started shairport-sync.service - Shair>
Mar 15 14:11:48 raspberrypi2 shairport-sync[1962]: Failed to create secure dire>
lines 1-11/11 (END)





raspberry@raspberrypi2:/etc $ sudo systemctl status nqptp
● nqptp.service - NQPTP -- Not Quite PTP
     Loaded: loaded (/usr/local/lib/systemd/system/nqptp.service; enabled; pres>
     Active: active (running) since Fri 2024-03-15 14:11:36 CET; 14min ago
   Main PID: 1957 (nqptp)
      Tasks: 1 (limit: 756)
        CPU: 5.504s
     CGroup: /system.slice/nqptp.service
             └─1957 /usr/local/bin/nqptp

Mar 15 14:11:36 raspberrypi2 systemd[1]: Started nqptp.service - NQPTP -- Not Q>
lines 1-10/10 (END)

uname -a
Linux raspberrypi2 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
```

### System Information.

System Infos: 
Raspberry Pi 3 B v. 1.2
1GB Ram
5V Power Supply

direct soundcard and external soundcard tested. Want to use the external card

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux raspberrypi2 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 12 (bookworm)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.3.2-2-g165431a8-AirPlay2-smi10-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   name = "Radio Buero";
 };
 pw :
 {
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by Jumbo125** [comment]
is this the typical problem which is listen on this site:
https://github.com/mikebrady/shairport-sync/blob/master/ADVANCED%20TOPICS/PulseAudioAndPipeWire.md

**Comment by mikebrady** [comment]
Thanks for the posts. TBH, I'm not quite sure what the problems are, so let's see if we can figure some things out.

Does your system use either PulseAudio or PipeWire?

**Comment by Jumbo125** [comment]
did it with php and api-protocoll :-)
