### ISSUE TITLE
[Problem]: Alsa Mixer volume scaling for strange max/min db settings

### ISSUE THREAD

**Issue by peqoud** [mikebrady/shairport-sync#1843]
### What happened?

Hello,

I am using an [Orange PI Zero 3](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-Zero-3.html) with an [Extension Board.](http://www.orangepi.org/html/hardWare/otherAccessories/details/Orange-Pi-Expansion-Board-For-Zero.html)

With the docker container in the latest version I got everything working. Current the hardware mixer does not properly work.

During startup I get this message:
```
0.000064708 "audio_alsa.c:940" *warning: The hardware mixer specified -- "LINEOUT volume" -- does not have a dB volume scale.
0.000624500 "audio_alsa.c:955" alsa: hardware mixer "LINEOUT volume" selected, with dB volume from -99999.990000 to 1.500000.
```

It seems like the calculations for the actual volume for the alsamixer seem to be not reliable with these upper and lower values:
```
0.000041500 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -24.00, software_attenuation dB: 0.00, hardware_attenuation dB: -56999.35, muting is disabled.
0.000003709 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -24.00, software_attenuation dB: 0.00, hardware_attenuation dB: -56999.35, muting is disabled.
0.000002000 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -22.12, software_attenuation dB: 0.00, hardware_attenuation dB: -51374.26, muting is disabled.
0.000212458 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -20.25, software_attenuation dB: 0.00, hardware_attenuation dB: -45749.18, muting is disabled.
0.000001166 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -16.50, software_attenuation dB: 0.00, hardware_attenuation dB: -34499.01, muting is disabled.
0.000052708 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -12.75, software_attenuation dB: 0.00, hardware_attenuation dB: -23248.85, muting is disabled.
0.000069333 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -7.12, software_attenuation dB: 0.00, hardware_attenuation dB: -11873.68, muting is disabled.
0.000646125 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is -3.38, software_attenuation dB: 0.00, hardware_attenuation dB: -5623.58, muting is disabled.
0.000048666 "player.c:3528" player_volume_without_notification: volume mode is 1, airplay volume is 0.00, software_attenuation dB: 0.00, hardware_attenuation dB: 1.50, muting is disabled.
```

As these values are read from ALSA directly as I see, the following options right now
1. use the vol_sw_only mode
2. Adjust the volume code to use linear scale in the mixer from 0 to 100 for this strange min/max_db settings

[alsa-info.txt](https://github.com/mikebrady/shairport-sync/files/15054826/alsa-info.txt)
[shairport-sync_hardware_mixer.log](https://github.com/mikebrady/shairport-sync/files/15054827/shairport-sync_hardware_mixer.log)

### System Information.

[Orange PI Zero 3](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-Zero-3.html) with an [Extension Board.](http://www.orangepi.org/html/hardWare/otherAccessories/details/Orange-Pi-Expansion-Board-For-Zero.html)

### Configuration Information.

```shell
0.001529125 "shairport.c:1470" default metadata_pipename is "/tmp/shairport-sync-metadata".
         0.000078875 "shairport.c:2113" >> Display Config Start.
         0.002885000 "shairport.c:2113"
         0.000048875 "shairport.c:2113" From "uname -a":
         0.000014375 "shairport.c:2113"  Linux orangepizero3 6.1.31-sun50iw9 #1.0.2 SMP Mon Sep 25 13:54:37 CST 2023 aarch64 Linux
         0.005351459 "shairport.c:2113"
         0.000063333 "shairport.c:2113" From /etc/os-release:
         0.000014125 "shairport.c:2113"  Alpine Linux v3.17
         0.003022833 "shairport.c:2113"
         0.000051334 "shairport.c:2113" Shairport Sync Version String:
         0.000013750 "shairport.c:2113"  4.3.2-2-g165431a8-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc
         0.000019208 "shairport.c:2113"
         0.000010375 "shairport.c:2113" Command Line:
         0.000014208 "shairport.c:2113"  /usr/local/bin/shairport-sync -c /etc/shairport_conf/conf.conf --displayConfig
         0.000040917 "shairport.c:2113"
         0.000011958 "shairport.c:2113" Configuration File:
         0.000010917 "shairport.c:2113"  /etc/shairport_conf/conf.conf
         0.000011833 "shairport.c:2113"
         0.000190375 "shairport.c:2113" Configuration File Settings:
         0.000022000 "shairport.c:2113"  general :
         0.000013459 "shairport.c:2113"  {
         0.000011000 "shairport.c:2113"    name = "ace_player_airplay";
         0.000011041 "shairport.c:2113"    output_backend = "alsa";
         0.000010750 "shairport.c:2113"    playback_mode = "stereo";
         0.000011209 "shairport.c:2113"    volume_control_profile = "flat";
         0.000010916 "shairport.c:2113"    audio_backend_latency_offset_in_seconds = -0.1;
         0.000012625 "shairport.c:2113"    dbus_service_bus = "system";
         0.000010917 "shairport.c:2113"  };
         0.000010458 "shairport.c:2113"  alsa :
         0.000010500 "shairport.c:2113"  {
         0.000010542 "shairport.c:2113"    output_device = "default:audiocodec";
         0.000011625 "shairport.c:2113"    mixer_control_name = "LINEOUT volume";
         0.000012667 "shairport.c:2113"    mixer_control_index = 0;
         0.000010750 "shairport.c:2113"    mixer_device = "default:audiocodec";
         0.000010583 "shairport.c:2113"    output_rate = 352800;
         0.000010458 "shairport.c:2113"    output_format = "S16_LE";
         0.000010667 "shairport.c:2113"  };
         0.000010708 "shairport.c:2113"  diagnostics :
         0.000010500 "shairport.c:2113"  {
         0.000010417 "shairport.c:2113"    log_verbosity = 3;
         0.000010583 "shairport.c:2113"    log_show_file_and_line = "yes";
         0.000010500 "shairport.c:2113"  };
         0.000061667 "shairport.c:2113"
         0.000014000 "shairport.c:2113" >> Display Config End.
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by fritz-fritz** [comment]
Hey I actually came across a similar issue and spent some time implementing a work around the will probably work for you.

My setup is that I use pipewire for my audio and shairport is not in a docker container. I configured my backend to use alsa via pipewire-alsa as I wanted to enable higher bitdepth and rate ( even though reportedly airplay doesn't go above 16/44100 ) to try and keep my audio from being resampled.

Where things are similar is that my alsa default monitor does not report a dB volume scale. As I wanted to be able to directly control the volume from my device and not have the overhead of software, I needed a solution.

**Long story short: airplay uses a known dB range and we can get the raw integer range from alsa and calculate the equivalent.**

My workaround without forking code and implementing was to add these two lines to my `general` section of the conf:

```bash
ignore_volume_control = "yes";
run_this_when_volume_is_set = "/usr/bin/bash -c 'amixer=$(amixer get Master); min=$(echo \"$amixer\" | grep \"Limits:\" | sed \"s/.*Playback \\([0-9]\\+\\) - \\([0-9]\\+\\)/\\1/\"); max=$(echo \"$amixer\" | grep \"Limits:\" | sed \"s/.*Playback \\([0-9]\\+\\) - \\([0-9]\\+\\)/\\2/\"); (/usr/bin/amixer -M set Master \"$(echo \"scale=4; ($1 - (-30.0)) / ($min - (-30.0)) * $max\" | bc)\" >/dev/null 2>&1)' _ ";
```

Writing that escaped code to take the input from shairport was painful!

But the basic principle of mapping the mixer's reported raw integer limits to the known decibel range of airplay seems like reliable fallback method that could be implemented in the code! If you're interested Mike let me know and I'll take a stab at sending a PR.

**Comment by mikebrady** [comment]
Thanks for all that, @fritz-fritz, and props to you for the workaround and the code. However, I think I will refrain from adding it to Shairport Sync, simply because we have no knowledge of the transfer function between the non-dB-denominated mixer levels and the actual attenuation. In your case it may be fine, but in others, we simply don't know.

So perhaps it's best to leave the workaround here for people to experiment with themselves. As mentioned in a [reply](#issuecomment-2072917708) to @peqoud, there seem to be very few DAC mixers that are not dB-denominated.
