### ISSUE TITLE
[Problem]: Option -d for daemonization conflicts with option -d for ALSA backend

### ISSUE THREAD

**Issue by acli** [mikebrady/shairport-sync#1849]
### What happened?

If built with an ALSA backend, shairport-sync -h will say at the end

    Settings and options for the audio backend "alsa":
        -d output-device    set the output device, default is "default".
    [...]

However, if we try to run `shairport-sync -o alsa -d hw:Notepad5` (for example), it will die with the error

    shairport-sync was built without libdaemon, so does not support daemonisation using the -d, --daemon, -j or --justDaemoniseNoPIDFile options

This is essentially the same as #909, which was closed because a workaround was found, so the root cause was never fixed.

PS: According to a quick grep, the same issue would also affect the ao and sndio backends.

### System Information.

Raspberry Pi 3 Model B running Debian Buillseye (32-bit OSMC)

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux osmc 5.15.92-1-osmc #1 SMP PREEMPT Tue Jul 25 00:26:57 UTC 2023 armv7l GNU/Linux

From /etc/os-release:
 Open Source Media Center

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.3.2-AirPlay2-smi10-OpenSSL-Avahi-ALSA-pa-soxr-metadata-mqtt-sysconfdir:/usr/local/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /usr/local/etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   interpolation = "basic";
   output_backend = "pa";
   playback_mode = "mono";
 };
 alsa : 
 {
   output_device = "Notepad5";
 };
 pw : 
 {
 };
 pa : 
 {
   server = "127.0.0.1";
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. The issue is simply that backend options need to be separated from other options by `--`.

So, for example, `$ shairport-sync -v -- -d hw:0 -c PCM` It is not connected with #909.
