### ISSUE TITLE
[Problem]: Development AirPort 1 Build not discovered by iOS 17.5 devices when PR #1831 is enabled

### ISSUE THREAD

**Issue by poker335** [mikebrady/shairport-sync#1856]
### What happened?

I have this issue when building shairport-sync, recent development branch, for AirPlay 1:

iOS 17.5 and iPadOS 17.5 devices do not discover shairport-sync (when PR #1831 is included).
However, macOS 14.5 does discover this build of shairport-sync.

When building the development branch with the changes from PR #1831 rolled back/reverted, the shairport-sync device is discovered by iOS 17.5 devices.

When using the release branch, the device is also discovered by iOS 17.5 devices.

So I assume there is a problem with PR #1831 & AirPlay 1 builds.

### Relevant log output

```shell
No log output indicating an error.
```

### System Information.

RPi 1, Raspberry Pi Model B Rev 2; dietpi distribution; Wolfson/Cirrus Logic sound card. 

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 6.6.29+ #1760 Mon Apr 29 14:38:33 BST 2024 armv6l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 12 (bookworm)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi Model B Rev 2

Shairport Sync Version String:
 4.3.3-dev-74-gc2fe06b8-alac-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   interpolation = "soxr";
   ignore_volume_control = "yes";
 };
 alsa :
 {
   output_device = "hw:RPiCirrus";
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. Let me take a look, bit illl be a day or so…

**Comment by mikebrady** [comment]
Thanks again for this report. I think you are correct, and an update has been pushed on the `development` branch with the changes in PR #1831 reverted.

**Comment by poker335** [comment]
Many thanks for update! I can confirm that the latest dev branch build works again with iOS 17.5 und AirPlay 1.
