### ISSUE TITLE
nqptp fails to launch: "Unit file nqptp.service does not exist"

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#1859]
### What happened?

After building nqptp I ran:

pi@pi00:~/nqptp $ sudo systemctl enable nqptp
Failed to enable unit: Unit file nqptp.service does not exist.

I know the issue, I use Chrony for my time and not NTP

https://chrony-project.org

### Relevant log output

```shell
NA
```

### System Information.

RPi 4

### Configuration Information.

```shell
pi@pi00:~/shairport-sync $ shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux pi00 4.19.83-v8+ #1277 SMP PREEMPT Mon Nov 11 16:53:30 GMT 2019 aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 12 (bookworm)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 4 Model B Rev 1.2

Shairport Sync Version String:
 4.3.3-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 pw : 
 {
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post, but I'm not sure I understand the issue. Perhaps installing or manipulating `chrony` may have upset the date and time on the device. If so, that could potentially interfere with the build process.

My suggestion would be to get to a good, stable, situation first with the device's data and time, and then go back to the `nqptp` build directory and start the build process from the start again. Enter `$ make distclean` first and then follow the regular updating instructions.

I

**Comment by rockrabbit** [comment]
Tried rebuilding after first performing the distclean and I still get the same error.

Chrony removes the default time service on install. It installs chronyd as a daemon.

**Comment by mikebrady** [comment]
Thanks. TBH, I don't think `chrony` is the problem (assuming the Pi is set to the right time in general). I just installed it on a Pi 5 and it doesn't use `PTP` by default, so okay.

Just checking -- have you included the `--with-systemd-startup` during the `./configure` stage and done a `# make install` after the `$ make`?

Also, might just be worth doing a `# systemctl daemon-reload` before and after the `# make install`.

**Comment by rockrabbit** [comment]
That did it.. adding:

sudo ./configure --with-systemd-startup

Now works!

Thank you!
