### ISSUE TITLE
Output to multiple soundcards

### ISSUE THREAD

**Issue by noelhibbard** [mikebrady/shairport-sync#186]
Is there any way to output to multiple sound cards at the same time. For example, could I have one instance of shairport-sync and name it "All Rooms" and have it output to multiple sound cards.

**Comment by mikebrady** [comment]
Hi Noel. It's not on my horizon, I've got to say. It would require a pretty big rearrangement of the application, and TBH I'm not sure it's got a lot of use cases. I cod be wrong, of course...

**Comment by noelhibbard** [comment]
I think multizone audio is very much on people's wish list.

**Comment by mikebrady** [comment]
Fair point!

**Comment by noelhibbard** [comment]
There is some windows software called TuneAero which is an AirPlay emulator which runs as a single instance but lets you configure multiple zones and each zone can output to a different sound card or a group of soundcards. So you can have an AirPlay target named "All Rooms" which outputs to several soundcards at once. So from an iPhone you could stream to "All Rooms" and hear the music through the whole house. The sync is perfect too. This version of TuneAero is currently in beta though. It would be nice to have something similar to this on Linux though. I would love to have a Raspberry Pi Zero connected to a USB hub which has several soundcards and a WiFi dongle running shairport-sync.

**Comment by tsynik** [comment]
it's all on audio routes / devices side. In linux, you can setup alsa to output to more than one soundcard at once with dmix:
http://www.6by9.net/output-to-multiple-audio-devices-with-alsa/

**Comment by noelhibbard** [comment]
This is great advice. I suspected ALSA had some way to accomplish this. After reading up on ALSA a little more I am thinking I can bust up all the channels on my 6ch sound card into multiple outputs. Thanks tsynik.

**Comment by cre8dojo** [comment]
Not an answer for the original question, but.... Separate Left and Right channels on a sound card and make each of them a separate zone (hw:1 = usb sound card):


pcm.hw1_dmixer {
  type dmix
  ipc_key 1024 # must be unique!
  slave {
    pcm {
      type hw
      card 1
      device 0
    }
    period_time 0
    period_size 1024
    buffer_size 8192
    rate 44100 
  }
}





pcm.usb_snd1_l {
  type plug
  slave {
    pcm {
      type route
      slave.pcm "hw1_dmixer"
      slave.channels 2
      ttable.0.0 1
      ttable.1.0 1
    }
  }
}
pcm.usb_snd1_r {
  type plug
  slave {
    pcm {
      type route
      slave.pcm "hw1_dmixer"
      slave.channels 2
      ttable.0.1 1
      ttable.1.1 1
    }
  }
}



Then make output_device on one Zone = usb_snd1_r and usb_snd1_l on a diferent Zone. Then you can power two separate Zones on a 2 channel sound card.

**Comment by mikebrady** [comment]
Thanks for this useful contribution. Please open a new issue if necessary.
