### ISSUE TITLE
[Problem]: HomeKit AirPlay 2 incompatibilities

### ISSUE THREAD

**Issue by cbrunnkvist** [mikebrady/shairport-sync#1861]
### What happened?

I'm documenting these issues here mostly in order to save other users from having to go through the same troubleshooting, but hopefully there might be some fix in the future too:

There are two, **probably interrelated**, parts to the current HomeKit incompatibilities:

1. In Apple _Home > Settings_ there are three access levels for _"Speakers & TV"_:
- Everyone
- Anyone on The Same Network
- Only People Sharing This Home

![IMG_632D7A34EDEA-1](https://github.com/mikebrady/shairport-sync/assets/34006/3a5c5d05-54b6-477d-94a0-4ac8579089a9)

As concluded originally by @ghost in _https://github.com/mikebrady/shairport-sync/issues/1442#issuecomment-1060709537_, in order to be able to add Shairport Sync speakers to a Home at all, you are [required](https://github.com/mikebrady/shairport-sync/blob/master/ADDINGTOHOME.md) to switch the _"Speakers & TV"_ access mode of your Home to mode "...Same Network" _and_ disable _"Require Password"_, which in some cases is an undesirable workaround. 

Failing to change access mode results in a confusing error along the lines of _"make sure your device is connected to the WiFi network"._  

2. Once added, the status of the Speaker in my Home never seems to accurately reflect its current playback status: in the Home app from the device playing, it show blank status but when you tap on it you get your local media controls - on other devices in the Home, the speaker status is "No Response"

Example: playing from iPad, check Home status on iPhone:
![IMG_8B7F018A4A82-1](https://github.com/mikebrady/shairport-sync/assets/34006/e45c5c9a-7e2c-4ef2-9da0-b1f11417f62c)

### System Information.

The [Docker container `:latest`](https://github.com/mikebrady/shairport-sync/blob/master/docker/README.md) running on x86, dockerd in LXC, "host" network mode, Alsa device passthrough. 

### Configuration Information.

N.b. I use the default all-commented-out config file.

```
>> Display Config Start.

From "uname -a":
 Linux dockge 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 Linux

From /etc/os-release:
 Alpine Linux v3.17

Shairport Sync Version String:
 4.3.3-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 pw : 
 {
 };

>> Display Config End.
>> Goodbye!
```
```


### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the information!

Unfortunately we don't know enough about the AirPlay 2 protocols yet to fix the playback status issue.

**Comment by cbrunnkvist** [comment]
I see. So, as it stands, besides from "cool - adding works!" ;-) I don't see any advantages to adding my speaker to the Home setup at the moment since it doesn't bring [any of the advantages](https://nuki.io/en/blog/smart-home/airplay-2-what-can-apples-new-streaming-protocol-do/#:~:text=The%20major%20benefit%20is%20that,through%20the%20Siri%20voice%20assistant.) ... Still works fine without lag for regular AirPlay, and at least I can protect it using nftables/iftables/ebtables, if push comes to shove.

**Comment by mikebrady** [comment]
Well, oddly, if you have a HomePod mini and you add the Shairport Sync device to a room, you can get Siri to play to it and raise and lower its volume and stuff.

TBH it _is_ a bit frustrating that is sorta works. 🤷‍♂️

**Comment by cbrunnkvist** [comment]
I have an Apple TV 4th gen set up as home hub. It can stream audio (but not games/realtime?) to Shairplay, but again having the speaker part of the Home or just on the networks makes no practical difference for that use case.

I read up on https://emanuelecozzi.net/docs/airplay2/authentication/, and I understand it's still an unsolved (MFi-) mystery. 

As I understand it, we've got password protection working in AirPlay 1 mode though. Are there any particular downsides for running it that way, for casual music streaming? I mean, if you really need/want no free-for-all network access.
