### ISSUE TITLE
[Problem]: No audio with AirPlay2 (AirPlay1 works)

### ISSUE THREAD

**Issue by rp86** [mikebrady/shairport-sync#1865]
### What happened?

Hi, 

In my system, SPS built with AirPlay2 connects but passes no audio. SPS built with AirPlay1 passes audio correctly. 

I have tried SPS in both Docker, self built and from Fedora 40 repo. 

Docker: Connects but no audio
Fedora 40 (3.3.9-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc): passes audio
Self built (4.3.3-OpenSSL-Avahi-ALSA-pa-pw-soxr-metadata-dbus-sysconfdir:/etc): passes audio
Self built (4.3.3-AirPlay2-smi10-OpenSSL-Avahi-ALSA-pa-pw-soxr-metadata-dbus-sysconfdir:/etc): Connects but no audio

I have tried the above with alsa, pa and pw outputs (no pw for Docker or v3.3.9), with no change to the results. 

The only relevant debug information I have been able to find is using the pw output, with AirPlay2 there are repeated 'send silence' messages in the -vvv log; with AirPlay1 these switch to 'play [x] samples' messages after playback starts. 

I've also tried maxing the volume and the option to disable the volume control with no change to above results. 

Log excerpts below, full AP2 log attached.
[Full AP2 Log.txt](https://github.com/user-attachments/files/15755977/Full.AP2.Log.txt)

Thanks :)

### Relevant log output

```shell
./shairport-sync_ap1 -o pw -vvv
---------------
         0.017797862 "player.c:1153" Check packet from buffer 39551, timestamp 3789632, 0.330349 seconds ahead.
         0.000029683 "audio_pw.c:339" total delay in frames: 1260.
         0.000010965 "audio_pw.c:286" play 352 samples; 53260 bytes already in the buffer.

./shairport-sync_ap2 -o pw -vvv
---------------
         0.000019835 "audio_pw.c:151" Queueing 1024 frames for output.
         0.023392917 "audio_pw.c:142" send silence
```

### System Information.

Fedora 40 / GNOME running Pipewire/Pipewire-pulse
Topping DM7 DAC 
CamillaDSP via ALSA-loopback to DM7

### Configuration Information.

```shell
------- AirPlay1:
>> Display Config Start.

From "uname -a":
 Linux htpc 6.8.11-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 27 14:53:33 UTC 2024 x86_64 GNU/Linux

From /etc/os-release:
 Fedora Linux 40 (Workstation Edition)

Shairport Sync Version String:
 4.3.3-OpenSSL-Avahi-ALSA-pa-pw-soxr-metadata-dbus-sysconfdir:/etc

Command Line:
 ./shairport-sync_ap1 -X
No configuration file.

>> Display Config End.
>> Goodbye!

------- AirPlay2:
>> Display Config Start.

From "uname -a":
 Linux htpc 6.8.11-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 27 14:53:33 UTC 2024 x86_64 GNU/Linux

From /etc/os-release:
 Fedora Linux 40 (Workstation Edition)

Shairport Sync Version String:
 4.3.3-AirPlay2-smi10-OpenSSL-Avahi-ALSA-pa-pw-soxr-metadata-dbus-sysconfdir:/etc

Command Line:
 ./shairport-sync_ap2 -X
No configuration file.

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Homebrew for Mac

### Check previous issues

- [X] Confirm

**Comment by rp86** [comment]
Quick update in light of my response to the dbus bug in another thread, I had forgotten there was a -classic docker image to use as well. I've just confirmed my AP1 vs AP2 findings with the latest docker development images: development-classic passes audio as expected, development (AP2) connects but doesn't pass audio. 

I'm satisfied for now as the AP1/docker setup appears to work well for me, but I'd be happy to help troubleshoot the AP2 issue.

**Comment by mikebrady** [comment]
Thanks for the post.

I'm going to make a guess that this is a firewall issue -- AirPlay 2 needs more port access than classic AirPlay. Fedora runs a firewall by default, and you need to ensure that ports 319 and 320 are open for UDP traffic. See [here](https://github.com/mikebrady/nqptp/blob/main/README.md#firewall) for more information on this.

**Comment by rp86** [comment]
That did it! Confirmed working with AirPlay 2 on latest docker image. I think adding a note re opening firewall ports on the docker/README.md might be helpful for future docker users, as running in docker doesn't require going through the build instructions of NQPTP. 

Thanks for your help!! :)

**Comment by mikebrady** [comment]
Thanks -- good to see that it's working. I added a little note to the Docker Hub README.
