### ISSUE TITLE
[Problem]: iOS 18 beta 1 Breaks AirPlay 1 Support

### ISSUE THREAD

**Issue by b3ll** [mikebrady/shairport-sync#1866]
### What happened?

Fully aware that betas aren't expected to be supported until they're public, but just wanted to give a heads up here :( 

Built from `development` branch and it works fine with 17.5 but 18.0b1 fails to connect.

AirPlay 2 seems to work just fine (minus remote controls, as expected), but AirPlay 1 will connect and then if you attempt to play any music it'll fail on the device saying it failed to connect. Still looking into things, but nothing was immediately obvious from the verbose output. Will keep looking into it and follow up here if I notice anything! 

### Relevant log output

         0.000015111 "rtsp.c:5204" Join watchdog thread.
         0.000055945 "rtsp.c:617" Connection 1: Watchdog Exit.
         0.000053278 "rtsp.c:5206" Delete watchdog mutex.
         0.000005388 "rtsp.c:5209" Connection 1: Closed.
         0.000009556 "rtsp.c:5431" Connection 1: RTSP thread exit.
         1.110821573 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000065721 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000060333 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000061017 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000060517 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000068536 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000076295 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000062073 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000062314 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000063721 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000062091 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000063554 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         2.000063370 "dacp.c:503" mutex_lock "&dacp_server_information_lock".
         0.476877129 "rtsp.c:700" mutex_lock "&conns_lock".
         0.000048870 "rtsp.c:703" Found RTSP connection thread 1 in a non-running state.
         0.000037871 "rtsp.c:706" Connection 1: deleted.
         0.000038889 "common.c:1687" mutex_unlock "&conns_lock" at "rtsp.c:716".
         0.000035666 "rtsp.c:727" Airplay Volume for new connections is -24.000000.
         0.000061871 "rtsp.c:5713" Connection 2: New connection from fe8 to self at fe8.
         0.000080889 "rtsp.c:5729" Successfully created RTSP receiver thread 2.
         0.000030851 "rtsp.c:5267" mutex_lock "&conns_lock".
         0.000008204 "common.c:1687" mutex_unlock "&conns_lock" at "rtsp.c:5274".
         0.000014852 "rtsp.c:667" mutex_lock "&conns_lock".
         0.000059611 "common.c:1687" mutex_unlock "&conns_lock" at "rtsp.c:689".
         0.001339944 "rtsp.c:782" msg_init message 7
         0.000006797 "rtsp.c:896" RTSP Message Received: "OPTIONS * RTSP/1.0".
         0.000010796 "rtsp.c:927"     CSeq: 0.
         0.000012278 "rtsp.c:927"     DACP-ID: 2000000009C.
         0.000011667 "rtsp.c:927"     Active-Remote: 0000000009.
         0.000004870 "rtsp.c:927"     User-Agent: AirPlay/800.55.3.
         0.000005444 "rtsp.c:782" msg_init message 8
         0.000004111 "rtsp.c:5293" Connection 2: Received an RTSP Packet of type "OPTIONS":
         0.000004556 "rtsp.c:5295"   Type: "CSeq", content: "0"
         0.000004037 "rtsp.c:5295"   Type: "DACP-ID", content: "2B4000000009C"
         0.000004000 "rtsp.c:5295"   Type: "Active-Remote", content: "3000000009"
         0.000003963 "rtsp.c:5295"   Type: "User-Agent", content: "AirPlay/800.55.3"
         0.000003907 "rtsp.c:5295"   No Content Plist. Content length: 0.
         0.000005963 "rtsp.c:2666" OPTIONS request
         0.000003815 "rtsp.c:2666"   Type: "CSeq", content: "0"
         0.000003871 "rtsp.c:2666"   Type: "DACP-ID", content: "200000009C"
         0.000003944 "rtsp.c:2666"   Type: "Active-Remote", content: "3000000009"
         0.000012815 "rtsp.c:2666"   Type: "User-Agent", content: "AirPlay/800.55.3"
         0.000013278 "rtsp.c:2666"   No Content Plist. Content length: 0.
         0.000008129 "rtsp.c:2667" Connection 2: OPTIONS
         0.000004797 "rtsp.c:5354" Connection 2: RTSP Response:
         0.000004037 "rtsp.c:5355"   Response Code: 200.
         0.000003759 "rtsp.c:5355"   Type: "CSeq", content: "0"
         0.000003926 "rtsp.c:5355"   Type: "Server", content: "AirTunes/105.1"
         0.000003926 "rtsp.c:5355"   Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
         0.000004629 "rtsp.c:5355"   No Content Plist. Content length: 0.
         0.000022334 "rtsp.c:872" msg_free freed message 8
         0.000009370 "rtsp.c:872" msg_free freed message 7
         0.000003963 "rtsp.c:5267" mutex_lock "&conns_lock".
         0.000004481 "common.c:1687" mutex_unlock "&conns_lock" at "rtsp.c:5274".
         0.076817889 "rtsp.c:782" msg_init message 9
         0.000005723 "rtsp.c:896" RTSP Message Received: "OPTIONS * RTSP/1.0".
         0.000010037 "rtsp.c:927"     CSeq: 1.
         0.000013870 "rtsp.c:927"     DACP-ID: 2B00000009C.
         0.000009018 "rtsp.c:927"     Active-Remote: 300000039.
         0.000004463 "rtsp.c:927"     User-Agent: AirPlay/800.55.3.
         0.000005000 "rtsp.c:782" msg_init message 10
         0.000004037 "rtsp.c:5293" Connection 2: Received an RTSP Packet of type "OPTIONS":
         0.000004149 "rtsp.c:5295"   Type: "CSeq", content: "1"
         0.000003870 "rtsp.c:5295"   Type: "DACP-ID", content: "2B40000000009C"
         0.000004000 "rtsp.c:5295"   Type: "Active-Remote", content: "30000000939"
         0.000003889 "rtsp.c:5295"   Type: "User-Agent", content: "AirPlay/800.55.3"
         0.000003926 "rtsp.c:5295"   No Content Plist. Content length: 0.
         0.000004426 "rtsp.c:2666" OPTIONS request
         0.000004092 "rtsp.c:2666"   Type: "CSeq", content: "1"
         0.000003871 "rtsp.c:2666"   Type: "DACP-ID", content: "2B0000C09C"
         0.000003926 "rtsp.c:2666"   Type: "Active-Remote", content: "300000000039"
         0.000003963 "rtsp.c:2666"   Type: "User-Agent", content: "AirPlay/800.55.3"
         0.000003888 "rtsp.c:2666"   No Content Plist. Content length: 0.
         0.000003834 "rtsp.c:2667" Connection 2: OPTIONS
         0.000012074 "rtsp.c:5354" Connection 2: RTSP Response:
         0.000013333 "rtsp.c:5355"   Response Code: 200.
         0.000009759 "rtsp.c:5355"   Type: "CSeq", content: "1"
         0.000008260 "rtsp.c:5355"   Type: "Server", content: "AirTunes/105.1"
         0.000004092 "rtsp.c:5355"   Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
         0.000004482 "rtsp.c:5355"   No Content Plist. Content length: 0.
         0.000013833 "rtsp.c:872" msg_free freed message 10
         0.000005833 "rtsp.c:872" msg_free freed message 9
         0.000003908 "rtsp.c:5267" mutex_lock "&conns_lock".
         0.000004315 "common.c:1687" mutex_unlock "&conns_lock" at "rtsp.c:5274".
         0.030461796 "rtsp.c:782" msg_init message 11
         0.000004944 "rtsp.c:896" RTSP Message Received: "OPTIONS * RTSP/1.0".
         0.000009704 "rtsp.c:927"     CSeq: 2.
         0.000009815 "rtsp.c:927"     DACP-ID: 2B47B11B4A26C09C.
         0.000004333 "rtsp.c:927"     Active-Remote: 30000000009.
         0.000004315 "rtsp.c:927"     User-Agent: AirPlay/800.55.3.
         0.000005074 "rtsp.c:782" msg_init message 12
         0.000003889 "rtsp.c:5293" Connection 2: Received an RTSP Packet of type "OPTIONS":
         0.000004000 "rtsp.c:5295"   Type: "CSeq", content: "2"
         0.000003889 "rtsp.c:5295"   Type: "DACP-ID", content: "2B400000000C09C"
         0.000003963 "rtsp.c:5295"   Type: "Active-Remote", content: "3028607939"
         0.000004018 "rtsp.c:5295"   Type: "User-Agent", content: "AirPlay/800.55.3"
         0.000003889 "rtsp.c:5295"   No Content Plist. Content length: 0.
         0.000004260 "rtsp.c:2666" OPTIONS request
         0.000003740 "rtsp.c:2666"   Type: "CSeq", content: "2"
         0.000003834 "rtsp.c:2666"   Type: "DACP-ID", content: "2B400000000C09C"
         0.000003926 "rtsp.c:2666"   Type: "Active-Remote", content: "3028607939"
         0.000012555 "rtsp.c:2666"   Type: "User-Agent", content: "AirPlay/800.55.3"
         0.000013037 "rtsp.c:2666"   No Content Plist. Content length: 0.
         0.000010482 "rtsp.c:2667" Connection 2: OPTIONS
         0.000008796 "rtsp.c:5354" Connection 2: RTSP Response:
         0.000004074 "rtsp.c:5355"   Response Code: 200.
         0.000003722 "rtsp.c:5355"   Type: "CSeq", content: "2"
         0.000003759 "rtsp.c:5355"   Type: "Server", content: "AirTunes/105.1"
         0.000004056 "rtsp.c:5355"   Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
         0.000004426 "rtsp.c:5355"   No Content Plist. Content length: 0.
         0.000010667 "rtsp.c:872" msg_free freed message 12
         0.000008666 "rtsp.c:872" msg_free freed message 11
         0.000010611 "rtsp.c:5267" mutex_lock "&conns_lock".
         0.000009278 "common.c:1687" mutex_unlock "&conns_lock" at "rtsp.c:5274".
         0.018529111 "rtsp.c:1335" Connection 2: Connection closed by client.
         0.000005685 "rtsp.c:5425" Connection 2: Terminate RTSP connection.
         0.000009871 "rtsp.c:5110" Connection 2: unspecified stream rtsp_conversation_thread_func_cleanup_function called.
         0.000010537 "rtsp.c:2817" Connection 2: TEARDOWN (Classic AirPlay).
         0.000004685 "player.c:3645" Connection 2: player_stop.
         0.000004389 "player.c:3647" mutex_lock "&conn->player_create_delete_mutex".
         0.000004667 "player.c:3665" Connection 2: no player thread.
         0.000004833 "activity_monitor.c:131" mutex_lock "&activity_monitor_mutex".
         0.000020722 "rtsp.c:5121" Connection 2: terminating  -- closing timing, control and audio sockets...
         0.000005352 "rtsp.c:5142" Connection 2: terminating -- closing RTSP connection socket 13: from fe80:02 to self at fe80::da300.
         0.000023704 "rtsp.c:5202" Cancel watchdog thread.
         0.000012907 "rtsp.c:5204" Join watchdog thread.
         0.000098593 "rtsp.c:617" Connection 2: Watchdog Exit.
         0.000040000 "rtsp.c:5206" Delete watchdog mutex.
         0.000010907 "rtsp.c:5209" Connection 2: Closed.
         0.000010519 "rtsp.c:5431" Connection 2: RTSP thread exit.

### System Information.

Raspberry Pi 5

### Configuration Information.

```shell
/* Doesn't really seem relevant to attach as it fails regardless of configuration */
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Very interesting indeed, thanks. Let’s hope for the best.

**Comment by BrokeTechEnthusiast** [comment]
Doesn’t appear to be fixed as of iOS 18 Dev Beta 2.

**Comment by BrokeTechEnthusiast** [comment]
Apple replied to my feedback saying that they couldn’t reproduce the issue. They also asked for the make/model of speaker. My assumption is that they’d simply say this isn’t a supported use case anyway.

**Comment by mikebrady** [comment]
Thanks -- it's interesting that they replied!

**Comment by mikebrady** [comment]
The situation remains the same with iPadOS 18 Dev Beta 3. Unfortunately I don't have a bona-fide classic-AirPlay-only device anymore, so I can't tell if it's -- as I suspect -- a classic Airplay issue or a specific Shairport Sync one.

**Comment by jrgstr** [comment]
I can use AirPlay perfectly with the Apple TV (older generation) and a Sony TV. I think it’s due to Shairport Sync and I fear it will stay that way.

**Comment by BrokeTechEnthusiast** [comment]
I’m fearing the same. I saw on my ticket that there are now “more than 10” people having this issue but I suspect the overlap of beta users and shairplay-sync users might be around there. I rebuilt my config with AirPlay 2, though it’s very noticeably less reliable than the AirPlay 1 setup was.

**Comment by mikebrady** [comment]
> I can use AirPlay perfectly with the Apple TV (older generation) and a Sony TV. I think it’s due to Shairport Sync and I fear it will stay that way.

I’m not sure I understand this — does your Apple TV definitely only do AirPlay 1?

**Comment by mikebrady** [comment]
> I’m fearing the same. I saw on my ticket that there are now “more than 10” people having this issue but I suspect the overlap of beta users and shairplay-sync users might be around there. I rebuilt my config with AirPlay 2, though it’s very noticeably less reliable than the AirPlay 1 setup was.

Could you characterise what kind of reliability issues you are encountering, please?

**Comment by jrgstr** [comment]
> > I can use AirPlay perfectly with the Apple TV (older generation) and a Sony TV. I think it’s due to Shairport Sync and I fear it will stay that way.
> 
> Thanks for the report. I’m not sure I understand this — does your Apple TV definitely only do AirPlay 1?

It is the A1625 (Apple TV HD) model

Laut support-Forum:
“The Apple TV is an airplay receiver not an emitter. It can receive audio over AirPlay 2 from other devices, but does not itself use Airplay 2 to connect to speakers or sound bars. “

**Comment by ondpe** [comment]
Just came here searching for why the Airplay 1 is not working. I can therefore confirm it is not issue of your software, it is not working for me on regular Airplay 1 (only) speakers. Reddit thread: https://www.reddit.com/r/iOSBeta/comments/1dhskou/ios_18_db1_airplay_1_broken/. Hope it helps someone flag this issue properly to Apple. I got also questions after questions and then "unable to reproduce".

**Comment by littleblack111** [comment]
i see. i thought it was my problem of configurations. my day was wasted lmfao. but im curious how u obtained the log? (shairport-sync -v) seem to just stop providing any more log after the initilization. doesnt show anything even after a connection(which failed). this is the log:
```         0.000852452 "shairport.c:2281" Startup in classic Airplay (aka "AirPlay 1") mode.
         0.000043398 "shairport.c:2317" Version String: "4.3.3-OpenSSL-Avahi-dns_sd-ALSA-jack-pa-stdout-pipe-soxr-metadata-mqtt-sysconfdir:/etc"
         0.000010564 "shairport.c:2336" Command Line: "shairport-sync -v".
         0.000004205 "shairport.c:2372" Log Verbosity is 1.
         0.000018425 "audio_alsa.c:1022" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000014305 "audio_alsa.c:1311" alsa: disable_standby_mode is "never".
         0.000005127 "audio_alsa.c:1315" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000005586 "audio_alsa.c:1317" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000009931 "audio_alsa.c:1357" alsa: output device name is "default".
         0.000096414 "shairport.c:2440" disable_resend_requests is off.
         0.000006744 "shairport.c:2441" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000009346 "shairport.c:2445" statistics_requester status is 0.
         0.000007840 "shairport.c:2450" rtsp listening port is 5000.
         0.000003745 "shairport.c:2451" udp base port is 6001.
         0.000005858 "shairport.c:2452" udp port range is 10.
         0.000005996 "shairport.c:2453" player name is "ArchLinux".
         0.000006104 "shairport.c:2454" backend is "alsa".
         0.000005483 "shairport.c:2455" run_this_before_play_begins action is "(null)".
         0.000006163 "shairport.c:2456" run_this_after_play_ends action is "(null)".
         0.000005108 "shairport.c:2457" wait-cmd status is 0.
         0.000004727 "shairport.c:2458" run_this_before_play_begins may return output is 0.
         0.000008716 "shairport.c:2459" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000006007 "shairport.c:2461" run_this_before_entering_active_state action is  "(null)".
         0.000005488 "shairport.c:2463" run_this_after_exiting_active_state action is  "(null)".
         0.000005272 "shairport.c:2465" active_state_timeout is  10.000000 seconds.
         0.000006333 "shairport.c:2466" mdns backend "(null)".
         0.000006195 "shairport.c:2468" interpolation setting is "auto".
         0.000008222 "shairport.c:2472" interpolation soxr_delay_threshold is 30000000.
         0.000003837 "shairport.c:2473" resync time is 0.050000 seconds.
         0.000005304 "shairport.c:2474" resync recovery time is 0.100000 seconds.
         0.000005923 "shairport.c:2475" allow a session to be interrupted: 0.
         0.000005729 "shairport.c:2476" busy timeout time is 120.
         0.000004608 "shairport.c:2477" drift tolerance is 0.002000 seconds.
         0.000009547 "shairport.c:2478" password is not set.
         0.000004841 "shairport.c:2479" default airplay volume is: -24.000000.
         0.000005585 "shairport.c:2480" high threshold airplay volume is: -16.000000.
         0.000003578 "shairport.c:2482" check for higher-than-threshold volume for new play session is disabled.
         0.000004959 "shairport.c:2488" ignore_volume_control is 0.
         0.000003419 "shairport.c:2492" volume_max_db is not set
         0.000004545 "shairport.c:2493" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000006520 "shairport.c:2495" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000007764 "shairport.c:2499" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000005088 "shairport.c:2501" disable_synchronization is 0.
         0.000006076 "shairport.c:2502" use_mmap_if_available is 1.
         0.000004877 "shairport.c:2503" output_format automatic selection is enabled.
         0.000003419 "shairport.c:2507" output_rate automatic selection is enabled.
         0.000004584 "shairport.c:2511" audio backend desired buffer length is 0.200000 seconds.
         0.000005338 "shairport.c:2513" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000005755 "shairport.c:2515" audio backend latency offset is 0.000000 seconds.
         0.000006456 "shairport.c:2517" audio backend silence lead-in time is "auto".
         0.000004790 "shairport.c:2521" zeroconf regtype is "_raop._tcp".
         0.000003754 "shairport.c:2522" decoders_supported field is 1.
         0.000005660 "shairport.c:2523" use_apple_decoder is 0.
         0.000004545 "shairport.c:2524" alsa_use_hardware_mute is 0.
         0.000007116 "shairport.c:2528" no special mdns service interface was requested.
         0.000008959 "shairport.c:2531" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000007470 "shairport.c:2538" metadata enabled is 1.
         0.000005591 "shairport.c:2539" metadata pipename is "/tmp/shairport-sync-metadata".
         0.000005391 "shairport.c:2540" metadata socket address is "(null)" port 0.
         0.000005070 "shairport.c:2542" metadata socket packet size is "500".
         0.000005294 "shairport.c:2543" get-coverart is 1.
         0.000004714 "shairport.c:2546" mqtt is disabled.
         0.000006159 "shairport.c:2547" mqtt hostname is (null), port is 1883.
         0.000006226 "shairport.c:2548" mqtt topic is /ArchLinux.
         0.000003453 "shairport.c:2549" mqtt will not publish raw metadata.
         0.000004783 "shairport.c:2550" mqtt will not publish parsed metadata.
         0.000004903 "shairport.c:2551" mqtt will not publish cover Art.
         0.000007657 "shairport.c:2552" mqtt remote control is disabled.
         0.000009077 "shairport.c:2561" loudness is 0.
         0.000005871 "shairport.c:2562" loudness reference level is -20.000000
         0.002073307 "rtsp.c:4235" metadata pipe name is "/tmp/shairport-sync-metadata".
         1.498145743 "shairport.c:255" "soxr" interpolation has been chosen.
         1.498145743 "shairport.c:255" "soxr" interpolation has been chosen.
```

**Comment by owldown** [comment]
I can add to the notion that this doesn't seem to be a shairport issue. I have a very old AirPort Express and a Yamaha receiver with built in airplay 1, and I cannot play to either of them with the iOS beta from either my iPhone or iPad. Playing to a Pi Zero W running an Airplay 2 build of Shairport works fine from those devices under the beta.

**Comment by mikebrady** [comment]
> I can add to the notion that this doesn't seem to be a shairport issue. I have a very old AirPort Express and a Yamaha receiver with built in airplay 1, and I cannot play to either of them with the iOS beta from either my iPhone or iPad. Playing to a Pi Zero W running an Airplay 2 build of Shairport works fine from those devices under the beta.

Thanks for that!

**Comment by jrgstr** [comment]
Yes, running

**Comment by b3ll** [comment]
let's hope it stays that way! :D

**Comment by mikebrady** [comment]
> This is fixed in iOS 18 beta 4.

Late to the party here, but I can confirm this -- it's back in iPadOS Beta 4 too.

**Comment by shailesh001** [comment]
Also can confirm it is fixed in Beta 4 and Volumio Shairport is functional again.

**Comment by littleblack111** [comment]
confirm working!

**Comment by hazymat** [comment]
FYI the latest iOS18 Public Beta does not appear to work with airplay connections to older Apple AirPort Express devices (1st gen at least). I’m anware this thread is not about that but flagging it here.

Unsure if this is related to Airplay version 1 vs 2 (or wig it’s related to not supporting specific devices) but I would assume it’s protocol related. I have raised an Apple Feedback.

**Comment by adriancable** [comment]
The latest public beta is the same as dev beta 3, which still has the bug (was fixed in dev beta 4). It’s the same bug with AirPlay 1 that also prevents playback to your AirPlay Express.

No need to file further feedback with Apple, this issue is now addressed.

**Comment by hazymat** [comment]
> No need to file further feedback with Apple, this issue is now addressed.

Thank you, I wasn’t aware the public beta is the same as dev beta 3. It’s reassuring that Airplay 1 will be supported in iOS 18.
