### ISSUE TITLE
[Problem]: Shairport-sync lowers the volume (almost mute) after every connect and disconnect

### ISSUE THREAD

**Issue by eurovisionfanatic** [mikebrady/shairport-sync#1892]
### What happened?

On RPI with desktop, installing Shairport-sync through the docker container, it lowers the volume when you play and pause/connect/reconnect music requiring it to be manually increased again in the GUI and then everything works fine.  I have tried development and latest containers.

### System Information.

RPI 3, no DAC just the standard audio output

### Configuration Information.

```shell
Using docker
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Could you post the command you used to launch the Docker image, please?

And maybe some information about the Pi. Could you post the output from these three commands please?

```
$ uname -a

$ cat /etc/os-release
 
$ cat /sys/firmware/devicetree/base/model
```

Thanks.

**Comment by eurovisionfanatic** [comment]
Hi Mike,

The issue was me, there appears to be 2 volume controls on my iphone, the one used by the volume buttons and is next to the brightness control in the action centre and the other in the actual play pause part of the action centre.  Using the one near the action centre does change the volume correctly, whereas the other does nothing.


Thanks for the help,
Cheers

**Comment by mikebrady** [comment]
Glad you got it sorted out.
