### ISSUE TITLE
How to autostart Shairport-Sync on Ubuntu 15.10

### ISSUE THREAD

**Issue by b3nk3** [mikebrady/shairport-sync#190]
Hello, 

I have followed all the steps and successfully installed the script, I can start it manually with:
`shairport-sync -d -a "Joe's Stereo" `
from the main folder, however when I run this:
`$sudo update-rc.d shairport-sync defaults 90 10`
it returns with the following:
`insserv: script shairport-sync is not an executable regular file, skipped!`

I've done some digging that [said](http://www.redsilico.com/comment/198#comment-198) I should copy the init script manually to the `/etc/init.d/ ` location.

However it did not solve my problem.

`which shairport-sync` returned the following
`/usr/local/bin/shairport-sync`

Upon 
`sudo service shairport-sync start` or status, restart etc I get the following:
`Failed to start shairport-sync.service: Unit shairport-sync.service failed to load: No such file or directory.`
Please advise what should I fix. 
Thanks

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. Something is clearly wrong with the installation. One thing that occurs to me quickly is that Ubuntu 15.10 uses `systemd` for startup. Is it possible that you might have used the `systemv` option instead of the `systemd` option at the point where you do the `./configure ...` step?

**Comment by b3nk3** [comment]
Yes that is the conclusion I came to as well..

How should I proceed?

**Comment by mikebrady** [comment]
I suggest you remove the wrongly-installed System-V-appropriate component (just one file) and redo the compilation and installation for `systemd` systems. You can remove the wrongly-installed component as follows:

```
sudo rm /etc/init.d/shairport-sync
sudo systemctl daemon-reload
```

You should then go back to the `./configure ...` step and resume from there, taking care to do the `systemd`-appropriate stuff. The `make` command shouldn't recompile Shairport Sync, but `sudo make install` will install the correct files for `systemd` startup.

**Comment by b3nk3** [comment]
Worked as a charm. Thanks for your time and for making this awesome thing!

On the side, is there any possibility I can get it working on bluetooth as well? Things getting more complicated with my Broadcom chip which is not recognised by Ubuntu.( dell n5010)

**Comment by mikebrady** [comment]
I'm glad that worked out, but I'm afraid Bluetooth is beyond the scope of this project right now.

**Comment by b3nk3** [comment]
Anyway, thanks ever so much. 

I'm gonna close this now.
