### ISSUE TITLE
[Problem]: The audio is constantly breaking as if someone is pausing and playing it again and again it plays okay for a second and then starts to lag

### ISSUE THREAD

**Issue by ThunderBirrddd** [mikebrady/shairport-sync#1906]
### What happened?

Hey,
I am flabbergasted by the way Shairport-sync works, flawless airplay2 ah love it.

Just took me some time to get it set up because I had to route my audio to a Bluetooth device which was a big hassle but got it working, now the issue I am facing is:

**The audio is constantly breaking as if someone is pausing and playing it again and again it plays okay for a second and then starts to lag like this,
I have a video attached below . Let me know if it makes sense.**

Pretty sure the issue lies somewhere In the audio server or shairport-sync as I've tried running normal audio through GUI and it plays perfectly fine on the speaker.

Let me know if you require anything to troubleshoot.
Also, I am a literal beginner to Linux and have very little knowledge,
Any help will be appreciated
I am running ubuntu on a core 2 duo, 3gb ram machine.

https://github.com/user-attachments/assets/cd39a8a4-bb13-4c52-804c-2c5826a6f41a

### System Information.

Ubuntu running on Intel core2duo and 3gb RAM

### Configuration Information.

```shell
warning: The "general" "log_verbosity" setting is deprecated. Please use the "diagnostics" "log_verbosity" setting instead.
         0.022871189 "shairport.c:2129" >> Display Config Start.
         0.017718900 "shairport.c:2129" 
         0.000049173 "shairport.c:2129" From "uname -a":
         0.000016613 "shairport.c:2129"  Linux Bhaviks-linux 6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
         0.022122429 "shairport.c:2129" 
         0.000046778 "shairport.c:2129" From /etc/os-release:
         0.000006353 "shairport.c:2129"  Ubuntu 24.04.1 LTS
         0.002010790 "shairport.c:2129" 
         0.000017399 "shairport.c:2129" Shairport Sync Version String:
         0.000026252 "shairport.c:2129"  4.3.4-1-g910264e5-AirPlay2-smi10-OpenSSL-Avahi-ALSA-pa-soxr-sysconfdir:/etc
         0.000017522 "shairport.c:2129" 
         0.000020711 "shairport.c:2129" Command Line:
         0.000014876 "shairport.c:2129"  shairport-sync --displayConfig
         0.000025763 "shairport.c:2129" 
         0.000015590 "shairport.c:2129" Configuration File:
         0.000016316 "shairport.c:2129"  /etc/shairport-sync.conf
         0.000012169 "shairport.c:2129" 
         0.000051831 "shairport.c:2129" Configuration File Settings:
         0.000005733 "shairport.c:2129"  general : 
         0.000004132 "shairport.c:2129"  {
         0.000003812 "shairport.c:2129"    name = "Shairport Sync";
         0.000004169 "shairport.c:2129"    log_verbosity = 3;
         0.000003835 "shairport.c:2129"  };
         0.000003748 "shairport.c:2129"  output_backend = "pa";
         0.000003812 "shairport.c:2129"  pa : 
         0.000003748 "shairport.c:2129"  {
         0.000003729 "shairport.c:2129"    application_name = "Shairport Sync";
         0.000003910 "shairport.c:2129"    service_name = "Shairport Sync on %H";
         0.000003992 "shairport.c:2129"    sink = "bluez_output.50_DC_E7_41_A0_C0.1";
         0.000004794 "shairport.c:2129"  };
         0.000003857 "shairport.c:2129"  alsa : 
         0.000003755 "shairport.c:2129"  {
         0.000003816 "shairport.c:2129"    buffer = 8192;
         0.000003741 "shairport.c:2129"    period = 2048;
         0.000003733 "shairport.c:2129"  };
         0.000003733 "shairport.c:2129"  pulse : 
         0.000003703 "shairport.c:2129"  {
         0.000003718 "shairport.c:2129"    buffer = 8192;
         0.000004380 "shairport.c:2129"    period = 2048;
         0.000003849 "shairport.c:2129"  };
         0.000003756 "shairport.c:2129"  buffering : 
         0.000003741 "shairport.c:2129"  {
         0.000003733 "shairport.c:2129"    buffering_mode = "adaptive";
         0.000003943 "shairport.c:2129"    adaptive_buffer_size = 10000;
         0.000003903 "shairport.c:2129"    fixed_buffer_size = 5000;
         0.000003785 "shairport.c:2129"  };
         0.000004365 "shairport.c:2129" 
         0.000003695 "shairport.c:2129" >> Display Config End.
         0.000004143 "shairport.c:2131" >> Goodbye!
         0.000005215 "shairport.c:1582" exit_function begins
         0.000004105 "shairport.c:1592" exit function called...
         0.000003673 "shairport.c:1602" Stopping the activity monitor.
         0.000007507 "shairport.c:1604" Stopping the activity monitor done.
         0.000011760 "mdns.c:137" Can't stop a DACP monitor -- no mdns_dacp_monitor_stop registered.
         0.000005861 "shairport.c:1729" normal exit
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Apologies for the delay — I’m away from devices in recent days. I’ll respond ASAP. Meantime, let me suggest that you look through older issues, including closed ones — there has been a lot of commentary about Bluetooth and Shairport Sync.

**Comment by mikebrady** [comment]
Apologies again for the delay. It seems possible that this problem is caused by problems with PulseAudio and Bluetooth.

Here are a few points about the configuration. 

1. Don’t use a log verbosity of 3, except for a specific purpose. The reason is that all the outputting of diagnostic information in the log can slow everything down and Shairport Sync can easily lose sync. Normally, a log verbosity of 1 is fine.
2. Shairport Sync does not have a `pulse` or a `buffering` section in the configuration file, so those settings have no effect. You should remove them.
3. You have selected the  PulseAudio backend, so the `alsa` settings are not used. Again, I suggest that you remove them. 

Let me suggest that you run Shairport Sync with a `log_verbosity` of `1` and with `statistics_enabled` set to `”yes”`(both settings are in the diagnostics section of the configuration files.) Then play some music for a minute or so and then post the log here.
