### ISSUE TITLE
AirPlay Video Streaming Status of shairport-sync on Mac OS X

### ISSUE THREAD

**Issue by dwebbuilder** [mikebrady/shairport-sync#191]
I have running shairport-sync on a raspberry pi. I guess since El Capitan is in the menubar the AirPlay video icon with the comment "Off".
![airplay](https://cloud.githubusercontent.com/assets/9950090/12032011/c3aafeb2-ae13-11e5-9562-38bfaa577e90.jpg)
If I turn off the raspberry pi, the icon disappears.
I have an airport express too. When using only the airport express no icon is displayed.

**Comment by mikebrady** [comment]
Thanks. I reliably get the AirPlay icon on my Mac menu bar with just an Apple AirPort Express in the system. When I turn off AirPlay on the device, the icon disappears from my Mac menubar. The AirPort Express is connected over WiFi.

**Comment by dwebbuilder** [comment]
Mike, sorry for the circumstances. I was firmly convinced that the AirPort Express has not the icon. I tried it again - You're right.

Thank you for your employment.

**Comment by mikebrady** [comment]
No problem – thanks for your interest. I'll close the issue now.
