### ISSUE TITLE
[Problem]: Slight crackling during loud parts of songs.  

### ISSUE THREAD

**Issue by tom8347** [mikebrady/shairport-sync#1919]
### What happened?

There's a slight crackling sound during loud parts of some tracks.  Not all tracks, but if I notice it with one track, it will do it consistently with that track.  I notice it the worst when the source is my nixos desktop (pipewire), but I also notice it with my android phone with airmusic to a slightly lesser extent, and I also notice it with my M1 macbook air.  Again it seems to be to different degrees with these three devices.  And again I on't notice it on all tracks, it seems to happen is a track goes suddenly from being quiet to loud, though I'm not quite sure.  It didn't always happen (I don't think... But I'm beginning to doubt myself because it's quite a subtle thing that I might have missed before), and seems to have started in the last month or so.   

The crackling sound is similar to that you sometimes get in VMs when you don't pin cpu cores if that helps at all, though it's much less exaggerated.  

The nature of the crackling changes when I switch between basic interpolation and soxr, but it happens either way.  This makes me think it must be to do with lost packets?

I thought it might be a sign of my pi dying so I switched it out for an identical one but the problem persists.  

The only other thing I can think of is that it is a problem with my network itself, but I'm not aware of any changes to my network in the last months/weeks.  

I'm fairly certain it's not a problem with the dac because the problem goes away when I connect directly to the dac via bluetooth.

### Relevant log output

```shell
output from shairport-sync -v when connecting from my nixos machine:

         0.001293073 "shairport.c:2278" Startup in AirPlay 2 mode, with features 0x405c4a00,0x1c340 on device "b8:27:eb:93:75:07".
         0.000131510 "shairport.c:2317" Version String: "4.3.4-1-g910264e5-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000025729 "shairport.c:2336" Command Line: "shairport-sync -v".
         0.000466302 "shairport.c:2372" Log Verbosity is 1.
         0.000059480 "audio_alsa.c:1082" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000075000 "audio_alsa.c:1371" alsa: disable_standby_mode is "never".
         0.000018229 "audio_alsa.c:1375" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000018594 "audio_alsa.c:1377" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000029479 "audio_alsa.c:1417" alsa: output device name is "hw:Audio".
         0.000236406 "shairport.c:2440" disable_resend_requests is off.
         0.000029010 "shairport.c:2441" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000021250 "shairport.c:2445" statistics_requester status is 0.
         0.000016407 "shairport.c:2450" rtsp listening port is 7000.
         0.000045937 "shairport.c:2451" udp base port is 6001.
         0.000038854 "shairport.c:2452" udp port range is 10.
         0.000036823 "shairport.c:2453" player name is "Living Room".
         0.000036771 "shairport.c:2454" backend is "alsa".
         0.000036510 "shairport.c:2455" run_this_before_play_begins action is "(null)".
         0.000037240 "shairport.c:2456" run_this_after_play_ends action is "(null)".
         0.000036563 "shairport.c:2457" wait-cmd status is 0.
         0.000036250 "shairport.c:2458" run_this_before_play_begins may return output is 0.
         0.000037239 "shairport.c:2459" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000037448 "shairport.c:2461" run_this_before_entering_active_state action is  "(null)".
         0.000037292 "shairport.c:2463" run_this_after_exiting_active_state action is  "(null)".
         0.000037291 "shairport.c:2465" active_state_timeout is  10.000000 seconds.
         0.000041615 "shairport.c:2466" mdns backend "(null)".
         0.000036094 "shairport.c:2468" interpolation setting is "basic".
         0.000036458 "shairport.c:2472" interpolation soxr_delay_threshold is 30000000.
         0.000037188 "shairport.c:2473" resync time is 0.050000 seconds.
         0.000038281 "shairport.c:2474" resync recovery time is 0.100000 seconds.
         0.000037864 "shairport.c:2475" allow a session to be interrupted: 0.
         0.000036302 "shairport.c:2476" busy timeout time is 120.
         0.000036094 "shairport.c:2477" drift tolerance is 0.002000 seconds.
         0.000038125 "shairport.c:2478" password is not set.
         0.000035729 "shairport.c:2479" default airplay volume is: -24.000000.
         0.000040417 "shairport.c:2480" high threshold airplay volume is: -16.000000.
         0.000039167 "shairport.c:2482" check for higher-than-threshold volume for new play session is disabled.
         0.000037239 "shairport.c:2488" ignore_volume_control is 0.
         0.000036563 "shairport.c:2492" volume_max_db is not set
         0.000035364 "shairport.c:2493" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000040000 "shairport.c:2495" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000038386 "shairport.c:2499" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000037656 "shairport.c:2501" disable_synchronization is 0.
         0.000036354 "shairport.c:2502" use_mmap_if_available is 1.
         0.000036250 "shairport.c:2503" output_format automatic selection is enabled.
         0.000036771 "shairport.c:2507" output_rate automatic selection is enabled.
         0.000036510 "shairport.c:2511" audio backend desired buffer length is 0.200000 seconds.
         0.000038386 "shairport.c:2513" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000038854 "shairport.c:2515" audio backend latency offset is 0.000000 seconds.
         0.000053385 "shairport.c:2517" audio backend silence lead-in time is "auto".
         0.000036250 "shairport.c:2521" zeroconf regtype is "_raop._tcp".
         0.000036146 "shairport.c:2522" decoders_supported field is 3.
         0.000036407 "shairport.c:2523" use_apple_decoder is 1.
         0.000036041 "shairport.c:2524" alsa_use_hardware_mute is 0.
         0.000036354 "shairport.c:2528" no special mdns service interface was requested.
         0.000070000 "shairport.c:2531" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000042657 "shairport.c:2561" loudness is 0.
         0.000036823 "shairport.c:2562" loudness reference level is -20.000000
         0.002102812 "shairport.c:2689" NQPTP is online.
        22.561277179 "rtsp.c:4543" Connection 1: Classic AirPlay connection from 192.168.1.13:20003 to self at 192.168.1.23:7000.
         0.136114739 "rtp.c:811" Remote processing time greater than return time -- ignored.




the last line there about the remote processing time didn't used to be there - but then I don't see that line when I connect from my phone (android) or my laptop (macbook) so I'm not sure how relevant it is.
```

### System Information.

I'm running shairport, compiled with Airplay 2 and soxr support, on a raspberry pi 3 model B with an ethernet connection. It's outputting to an SMSL SA300 DAC.

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.3.4-1-g910264e5-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Living Room";
   audio_backend_latency_offset_in_seconds = 0.0;
   interpolation = "basic";
 };
 alsa : 
 {
   output_device = "hw:Audio";
   mixer_control_name = "PCM";
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. If there is a lot of interpolation, then you might hear some crackling if using `basic` interpolation, but it should be almost inaudible if you use `soxr` interpolation. What would be very interesting would be to turn on the gathering of statistics (`statistics` in the `diagnostics` section of the configuration file). This would enable us to see how much interpolation is being done, which might help with troubleshooting.

**Comment by mikebrady** [comment]
Thanks. As I suspected, there is a great deal of interpolation going on — it should be in the 10s of PPM or occasionally up to 150 PPM or so. However, you can see that synchronization error is going positive and negative, indicating that the system is overcompensating. My suggestion would be to make the `drift_tolerance_in_seconds` larger, e.g. 0.020 seconds, (I.e. 20 milliseconds) and see if the amount of interpolation drops. If so, then you can reduce it if you wish.

**Comment by tom8347** [comment]
I've set `drift_tolerance_in_seconds` to 0.020 and it's much better which is great, I hear only very occasional cracks.  Will this affect audio/video synchronisation when watching videos?

This is the output now:

         7.928989893 "player.c:2651" Sync Error ms | Net Sync PPM | All Sync PPM | Missing |   Late | Too Late | Resend Reqs | Min DAC Queue | Min Buffers | Max Buffers | Nominal FPS | Received FPS | Output FPS (r) | Output FPS (c) | Source Drift PPM | Drift Samples
         0.000173229 "player.c:2651"         -3.36            0.0            0.0         0        0          0             0            7851           164           166      44105.49       44082.33              N/A              N/A               0.00               0
         8.006776247 "player.c:2651"         -7.30            0.0            0.0         0        0          0             0            7304           161           166      44091.44       44089.34         44094.46         44094.62               0.00               0
         8.000504945 "player.c:2651"         -7.21            0.0            0.0         0        0          0             0            7788           164           166      44100.54       44104.27         44091.77         44091.93               0.00               0
         8.013773017 "player.c:2651"        -10.44            0.0            0.0         0        0          0             0            7561           164           166      44099.89       44103.13         44094.51         44094.67               0.00               0
         8.000062497 "player.c:2651"        -14.70            0.0            0.0         0        0          0             0            7474           164           166      44099.51       44099.82         44099.98         44100.14               0.00               0
         8.007548279 "player.c:2651"        -15.14            0.0            0.0         0        0          0             0            7455           164           166      44095.67       44098.16         44098.91         44099.07               0.00               0
         8.006932236 "player.c:2651"        -14.90            0.0            0.0         0        0          0             0            7507           164           166      44098.97       44097.52         44098.15         44098.31               0.00               0
         8.014404476 "player.c:2651"        -15.02            2.8            2.8         0        0          0             0            7308           164           166      44101.21       44097.38         44099.22         44099.38               0.00               0
         7.993037393 "player.c:2651"        -15.20            0.0            0.0         0        0          0             0            7535           164           166      44098.81       44100.72         44099.32         44099.48               0.00               0
         8.013876143 "player.c:2651"        -16.10            5.7            5.7         0        0          0             0            7173           164           167      44098.75       44100.60         44099.38         44099.54               0.00               0
         8.000540413 "player.c:2651"        -16.48           11.3           11.3         0        0          0             0            7285           165           167      44098.68       44099.16         44098.35         44098.51               0.00               0
         8.007059060 "player.c:2651"        -16.05            5.7            5.7         0        0          0             0            7344           164           167      44100.26       44098.64         44098.01         44098.16               0.00               0
         8.007253903 "player.c:2651"        -17.28           34.0           34.0         0        0          0             0            7028           164           167      44098.38       44098.11         44099.99         44100.14               0.00               0
         8.010392080 "player.c:2651"        -17.87           34.0           34.0         0        0          0             0            7290           165           166      44099.89       44099.60         44099.15         44099.31               0.00               0
         8.003723070 "player.c:2651"        -17.36           39.7           39.7         0        0          0             0            7142           164           167      44098.47       44100.42         44099.21         44099.36               0.00               0
         7.999963591 "player.c:2651"        -18.30           65.1           65.1         0        0          0             0            7119           164           167      44099.68       44099.64         44100.00         44100.15               0.00               0
         8.007974893 "player.c:2651"        -18.79           48.2           48.2         0        0          0             0            7116           164           167      44099.60       44098.95         44099.99         44100.15               0.00               0
         8.006313174 "player.c:2651"        -17.95           25.5           25.5         0        0          0             0            7052           164           167      44099.50       44098.85         44099.67         44099.82               0.00               0
         8.003817705 "player.c:2651"        -19.69          150.1          150.1         0        0          0             0            7063           164           167      44100.46       44099.51         44099.39         44099.54               0.00               0
         8.003639007 "player.c:2651"        -19.10           87.8           87.8         0        0          0             0            6803           164           167      44099.31       44100.14         44099.71         44099.86               0.00               0
         8.014149633 "player.c:2651"        -19.08           70.8           70.8         0        0          0             0            7182           164           166      44100.19       44100.03         44100.00         44100.15               0.00               0
         8.000061611 "player.c:2651"        -20.37          206.8          206.8         0        0          0             0            6924           164           167      44099.23       44099.44         44099.22         44099.37               0.00               0
         8.000167601 "player.c:2651"        -19.74          116.1          116.1         0        0          0             0            6898           164           167      44100.03       44098.91         44099.75         44099.90               0.00               0
         8.014424164 "player.c:2651"        -19.43           96.3           96.3         0        0          0             0            7160           164           167      44099.95       44098.80         44100.24         44100.39               0.00               0
         8.010638747 "player.c:2651"        -21.42          257.7          257.7         0        0          0             0            6840           164           167      44099.87       44099.53         44099.54         44099.70               0.00               0
         7.996440882 "player.c:2651"        -21.33          192.6          192.6         0        0          0             0            6727           164           168      44099.01       44099.87         44099.34         44099.49               0.00               0
         8.007201456 "player.c:2651"        -19.66           79.3           79.3         0        0          0             0            7145           164           167      44099.68       44099.59         44100.21         44100.36               0.00               0
         8.007396038 "player.c:2651"        -22.23          371.0          371.0         0        0          0             0            6717           164           168      44100.35       44099.26         44100.00         44100.15               0.00               0

Other than that, is there a root cause of the interpolation that I could try to address?

**Comment by mikebrady** [comment]
That’s good news. You will hardly hear a sync mismatch of 20 milliseconds, but you could experiment with reducing the drift tolerance until overcompensation starts — that will be when the All Sync PPM is considerably greater than the Net Sync PPM. 

There seems to be two issues at work here. First, the rate of arrival of audio frames from the player doesn’t quite match the rate at which they are played. Second — and apparently more significant in this case — it looks as if the reference clock on the sending device is wandering, slowly getting faster and slower then faster again, etc. over a period of 10s of seconds.

If your Pi has a good connection to the internet, the Output FPS (c) should be accurate over a long period, as it should be adjusted by the NTP service used by the Pi.

On the face of it, it looks as if your output device is pretty exactly on 44,100. It also looks like the audio is arriving at close to 44,100 fps, but the reference clock seems to be wandering by something in the region of 100 to 150 PPM.

It would be interesting to run it continuously for a few hours if possible, in order to get better readings. Apple sources tend to be stable and accurate, but others maybe not so much.

**Comment by tom8347** [comment]
When I get a chance to do this I will, and then post the output here.  Thank you so much for your help so far!
