### ISSUE TITLE
[Problem]: Apple Music: Airplay device is not compatible with this version of AMPLibraryAgent

### ISSUE THREAD

**Issue by oi-polloio** [mikebrady/shairport-sync#1920]
### What happened?

On attempting to connect to shairport-sync via Apple Music, the error message 'The AirPlay device "[devicename]" is not compatible with this version of AMPLibraryAgent' is displayed.

### Relevant log output

```shell
No log output from shairport-sync, running with the "-v --statistics" options
```

### System Information.

Client is the current version of Windows 10, running Apple Music 1.5.0.155 (1.1280.39681.0)

Server is Raspbian GNU/Linux 11 (bullseye), running the current (as of 2024-10-11) version of shairport-sync

### Configuration Information.

```shell
Only change to /etc/shairport-sync.conf is changing the output_device in the alsa settings to "hw:Headphones".

Audio from shairport-sync is going through alsa as far as I know.
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post.

Unfortunately, Shairport Sync, if built for AirPlay 2 operation, is not compatible with Apple Music or iTunes on Windows. However, it remains compatible if built for classic AirPlay (i.e. "Airplay 1").

**Comment by oi-polloio** [comment]
Thanks, understood. I'm thinking now of trying to get two copies of shairport-sync running, we'll see.

**Comment by mecworks** [comment]
How about a runtime or config switch to enable AirPlay 1 or 2?  I cannot stream to my MoOde Audio instance because of this incompatibility. However, I can stream to other RPis running Kodi,  It would be really nice if it could run either protocol depending on how you configure or start it.

**Comment by mikebrady** [comment]
> How about a runtime or config switch to enable AirPlay 1 or 2? I cannot stream to my MoOde Audio instance because of this incompatibility. However, I can stream to other RPis running Kodi, It would be really nice if it could run either protocol depending on how you configure or start it.

How about having two separate versions of Shairport Sync — one classic and one AirPlay 2 and using a script to start the appropriate one?
