### ISSUE TITLE
Missing Dependency in README

### ISSUE THREAD

**Issue by srwareham** [mikebrady/shairport-sync#193]
The prerequisites listed in the README list autoconf but not automake. Automake appears to be required. Steps to reproduce error (on Linux Mint):
"""

- `apt-get install autoconf libtool libdaemon-dev libasound2-dev libpopt-dev libconfig-dev`
- `apt-get install avahi-daemon libavahi-client-dev` if you want to use Avahi (recommended).
- `apt-get install libssl-dev` if you want to use OpenSSL and libcrypto, or use PolarSSL otherwise.
- `apt-get install libpolarssl-dev` if you want to use PolarSSL, or use OpenSSL/libcrypto otherwise.
- `apt-get install libsoxr-dev` if you want support for libsoxr-based resampling. This library is not yet part of  Raspbian; instructions for how to build it from source are available at [LIBSOXR.md](https://github.com/mikebrady/shairport-sync/blob/development/LIBSOXR.md).

Download Shairport Sync:

`git clone https://github.com/mikebrady/shairport-sync.git`

Next, `cd` into the shairport-sync directory and execute the following command:

```
$ autoreconf -i -f
```
"""
Results in the error:

`Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory`

Installing automake (`apt-get install automake`) fixes this issue.
Tested using Linux Mint
Linux 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May x86_64 x86_64 x86_64 GNU/Linux

**Comment by mikebrady** [comment]
Many thanks for this. As far as I remember, this is fixed in the development branch version of README.md – I can't easily check it right now.

**Comment by mikebrady** [comment]
Closing this, as the update has been made part of stable release 2.8.0.
