### ISSUE TITLE
Once installed, how do you upgrade version to latest?

### ISSUE THREAD

**Issue by ChadTaljaardt** [mikebrady/shairport-sync#194]
Hello, 

I am using shairport on my raspberry pi, i just want to know how to update it once its installed?

Thanks

**Comment by mikebrady** [comment]
Thanks for the post. The easiest thing is to completely redo the installation, including cloning the latest version from Github. It should not disturb any settings.

**Comment by ChadTaljaardt** [comment]
Thanks for the response. 

Would an update like this overwrite the config file?

Might be a good option to include some sort of auto update feature?

Thanks

**Comment by mikebrady** [comment]
Thanks for the suggestion. The update *should* leave the configuration file alone. It would be no harm to make a copy of it beforehand though.

**Comment by mikebrady** [comment]
Could yet us know how it goes pleasE?

**Comment by ChadTaljaardt** [comment]
Yes i will. Ill test an update in the morning tomorrow :+1:

**Comment by roblan** [comment]
I never had a problem with this "setup" (`git pull; make; sudo make install`). Config file should be intact

**Comment by Odal3** [comment]
Mike  - I'm trying to update to the latest dev version. First time I copied the wrong path and got 2.7.4. It installed easily and I didn't realize the mistake until I ran shairport-sync --version, which confirmed it as 2.7.4. But when I tried to redo it with 2.7.6 it doesn't update:  --version still shows 2.7.4 even after reboot.

I'm pulling it by:
wget -O shairport-sync-2.7.6.tar.gz https://github.com/mikebrady/shairport-sync/archive/2.7.6.tar.gz
(and then tar, autoreconf, .configure, make, make install, update-rc.d, reboot)

Do you have any tips how to proceed?

**Comment by mikebrady** [comment]
It's entirely possible that the version doesn't corresponded the release tag. I'll be pushing another development perhaps this evening; I'll try to ensure they match. Thanks for your support.

**Comment by Odal3** [comment]
Got it, and thank YOU for all of your work. 

BTW: Now up and running on 2.7.7 using default config file except alsa out to a USB dac. Only been playing it for 10 min  but so far it works great (and no dropouts with OSMC as the base image)!

**Comment by mikebrady** [comment]
I'm hope it's okay to close this issue. Please feel free to reopen it if there are any developments.
