### ISSUE TITLE
shairport-sync - possible to recast to audio stream to chromecast audio device

### ISSUE THREAD

**Issue by carylewis** [mikebrady/shairport-sync#196]
I was wondering if anyone has thought about using shairport-sync to send output from an ios device to a chromecast or chromecast audio device?

I would think that using the output to a pipe option may facilitate this?

If anyone has any ideas as to how to build that kind of bridge I would appreciate any suggestions as to how to proceed.

**Comment by mikebrady** [comment]
Just FYI, there is a thread about this at #157.

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new one if necessary.
