### ISSUE TITLE
"Could not connect to Shairport Sync"

### ISSUE THREAD

**Issue by elsurudo** [mikebrady/shairport-sync#199]
I've got shairport-sync running on my RasPi, according to the recommended instructions. It even shows up in my Output Devices when I alt-click the volume icon on my Yosemite install. I also can't connect via my iPhone (iOS 7), although it also shows up.

However, when I try to select it, it (after a few seconds) gives me a "Could not connect to Shairport" error. Any ideas on how to troubleshoot this? Nothing in /var/log/syslog, except the following upon shutdown:

`shairport-sync[2866]: avahi client failure`

I don't have a USB sound card yet, so I haven't altered the config at all, hoping I could at least get things working with the onboard sound system first.

Thanks!

**Comment by elsurudo** [comment]
D'oh, this turned out to be a firewall issue. After allowing all required ports, I can connect. I still don't hear any audio, but that is a different issue altogether.

**Comment by mikebrady** [comment]
Thanks for the update. Sorry not to have responded. I'm in a poorly connected area.
