### ISSUE TITLE
Daemon returned 2 as return value.

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#2]
Hi Mike,

thanks for the fantastic rework on shairport. I suscessfully cross-compiled shairport-sync as a package within buildroot. But trying to start shairport as a daemon fails with:

**Daemon returned 2 as return value.**

I previous used shairport from abrasive, which ran fine as a daemon. Any suggestions?

**Comment by Oggymator** [comment]
Hi,
I have the same Issue and try it with "--with-piddir" and I get the following Error, I'm a noob in Linux, so maybe you can help me.
"configure: error: when you use the --with-piddir directive you must specify the pathname of the directory into which the PID file will be written"
thanks!
