### ISSUE TITLE
shairport-sync startup script/service not there after installation

### ISSUE THREAD

**Issue by kyssproject** [mikebrady/shairport-sync#203]
After the installation on a raspberry pi 2 (raspian Jessie), the last step does not seem to work, this is:
pi@raspberrypi:~/shairport-sync $ sudo systemctl enable shairport-sync
Failed to execute operation: No such file or directory

I can see that in the scripts/ folder there are the .service and the init.d files, I assume they have not been copied to the directories.

They are supposed to be copied, aren't they? Or I am missing something here?

**Comment by PeterPablo** [comment]
follow the instructions for systemd

**Comment by kyssproject** [comment]
Yes, now I see it, I missed the group and user part. Thanks!
