### ISSUE TITLE
problem with run_this_before_play_begins on develop

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#204]
I have problem with 'run_this_before_play_begins' (on latest beta, raspbian jessie)
`Error executing on-start command /home/pi/scripts/display_on.sh`
But only when shairport-sync is started as service (when started manually everything works fine).

`run_this_after_play_ends` works fine both as service and manually

**Comment by mikebrady** [comment]
Thanks for this. Just a couple of things:
* Could you make sure to use the full pathname when you're specifying the command to execute. Remember not to use the `~` as a shortcut for the `home` directory.
* Secondly, if the command is a script, make sure it's executable.
* Thirdly, if the script contains commands, they must also be specified using their full pathnames/
* Fourthly, remember that they may run under the username `shairport-sync`. Not sure what privileges it has, but it doesn't have a home directory, for example.

**Comment by roblan** [comment]
Thanks for pointing the obvious :)
It was caused by bad permissions - script was executable, but only for the owner (that's why it worked when it was started manually by script owner).
