### ISSUE TITLE
SPS 2.6 timeout after stream stops

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#206]
Hi Mike,

SPS 2.6 fully integrated into Moode and working beautifully including metadata pipe :-)

I'm working on SPS before/after scripts so users can more easily switch between Moode and SPS. I've noticed that after stopping iTunes playback it takes a few seconds before the "run_this_after_play_ends" script is executed. 

Can this timeout period be adjusted?

Regards,
Tim

**Comment by mikebrady** [comment]
Hi Tim. That's good news, thanks. The delay at the end is caused by iTunes waiting for that period before asking for the play session to end, and it non-adjustable, AFAIK. I don't think there is any particularly reliable or robust way to get around the delay, TBH.

**Comment by moodeaudio** [comment]
Ok, thanks Mike.
