### ISSUE TITLE
Initial hardware volume level

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#207]
Hi Mike,

When SPS is using hardware mixer (ALSA) it appears to use the mixers current volume setting when starting play back, then when the source (iTunes) bumps its volume sliders the hardware volume is adjusted accordingly.

This is a bit of an issue with a typical MPD config where MPD volume control is set to "Software" and the audio device has an on-board hardware volume controller. In this case ALSA volume is configured to 100% (0dB) since MPD will be performing volume using its software algorithm.

Unless the SPS "before" script sets ALSA volume to low value initially, full volume (100%) is output when SPS starts play back, until the source bumps its volume sliders.

Does SPS know the sources volume setting when it initially receives the stream?

Regards,
Tim

**Comment by mikebrady** [comment]
Hi Tim, and thanks for the enquiry. When, say, iTunes is about to start a play session, it sends a set-volume command. SPS sets the hardware mixer according to this and also stores the value so that if SPS is paused (and the ALSA device is used by something else), then when SPS resumes, it will set the hardware mixer to the stored volume. Thus, even if MPD sets the mixer to 100%, SPS should set it correctly before any sound is output.

That's the intention anyhow – I hope I haven't made shome mistake – that is aways possible. If you can describe a scenario where that doesn't seem to happen, I'd be interested.

So, yes, SPS does know the required playback volume when it receives the stream initially. This depends on iTunes etc. actually sending the set-volume command first.

**Comment by moodeaudio** [comment]
Hi Mike,

Here's a repro scenario

(1) boot fresh moode 2.5 image on a Pi-2B
(2) MPD config screen: set MPD volume control to "Hardware"
- defaults to using the on-board audio device which has hardware volume controller
- after applying setting, MPD/ALSA volume levels are reset to 0
(3) System config screen: turn Airplay receiver on
(4) reboot

(5) Launch iTunes and select "Moode Airplay" from the volume control dropdown
(6) Set volume slider to midpoint
(7) Play a track

(8) ssh root@moode (pwd=moode)
(9) amixer

At this point the output from amixer should show ALSA level of ~68% which represents iTunes midpoint slider position. This is the "success" outcome.

(A) Stop iTunes playback

(B) http://moode
(C) bump volume knob to 5
(D) amixer output should show 5%
(E) Start iTunes playback leaving the volume sliders at midpoint
(F) amixer

At this point I see the output from amixer still showing 5% volume level and not ~68% which corresponds to the iTunes slider pos. This is the "failure" outcome.

If iTunes slider is bumped then ALSA level is set correctly.

Regards,
Tim

**Comment by mikebrady** [comment]
Thanks. I'll take a look over the weekend.

**Comment by moodeaudio** [comment]
Thanks Mike,

I’ll make a 2.5 test release 2 (TR2) image for u sometime tomorrow and send u a download link.

Tim

**Comment by mikebrady** [comment]
Thanks. Actually it'll likely be next week before I can test this out – all the machines available over the weekend are headless.

**Comment by moodeaudio** [comment]
Hi Mike,

Moode is headless :-) All thats needed is ssh and web browser.

T

**Comment by mikebrady** [comment]
Excellent – my mhistake.

**Comment by moodeaudio** [comment]
Hi Mike,

Here is download link for Moode 2.5 test release 2 (TR2)
http://moodeaudio.org/downloads/moode-sdimg-r25-tr2-mb.zip
MD5 = 0758649c5f366921c46ef075a1fd2573

Files you might want to examine:
(1) /var/www/inc/playerlib.php, page to bottom, function startSps()
(2) /var/www/spspre.sh
(3) /var/www/spspost.sh

Here is updated repro scenario:

(1) boot fresh moode 2.5 TR2 image on a Pi-2B
(2) Menu, Configure, MPD: set MPD volume control to "Hardware"

- Defaults to using the on-board audio device which has hardware volume controller.
- After applying setting, MPD/ALSA volume levels are reset to 0 

(3) Menu, Configure, System: turn Airplay receiver on then press SET
(4) Menu, Turn off, REBOOT
(5) Launch iTunes and select "Moode Airplay" from the volume control dropdown
(6) Set volume slider to midpoint
(7) Play a track

(8) ssh root@moode (pwd=moode)
(9) amixer

At this point the output from amixer should show ALSA level of ~68% which represents iTunes midpoint slider position. This is the "success" outcome.

(A) Stop iTunes playback, wait 10 secs for sps to drop the Airplay stream

(B) http://moode
(C) bump volume knob to 5
(D) amixer output should show 5%
(E) Start iTunes playback leaving the volume sliders at midpoint
(F) amixer

At this point I see the output from amixer still showing 5% volume level and not ~68% which corresponds to the iTunes midpoint slider pos. This is the "failure" outcome.

If iTunes slider is bumped then ALSA level is set correctly

(G) verify alsa level via amixer

END

**Comment by mikebrady** [comment]
Hi Tim. I can reproduce the fault, and it's still present in 2.7.7. I'll take a look at it over the next while...

**Comment by mikebrady** [comment]
I think I might have found the issue, which is fixable. Whenever SPS pauses or stops, it immediately releases the ALSA device, then reacquires it when needed. However, it was not releasing the mixer, which is responsible for hardware volume control. The mixer state information data structures would stay unaltered during the pause. Thus – I guess – when SPS started to play after a pause, the volume level it sent to the mixer was the same as was stored in the mixer's state information, and therefore ignored. The fix is to drop and reacquire the mixer in the same way as the ALSA device. I'm trying out some code to do that right now, and it looks okay. Thanks for finding this interesting bug!

**Comment by moodeaudio** [comment]
Nice :-) the fix will enable easy switching between Airplay and Moode for users. Any timing yet for SPS 2.7 release?

**Comment by mikebrady** [comment]
I just pushed out 2.7.8 with the fix in it. I'd really like to have people test if for a few weeks before letting it out as a stable release. What's your schedule?

**Comment by moodeaudio** [comment]
I should be able to test today/tonight

**Comment by mikebrady** [comment]
Vey nice work, BTW.

**Comment by moodeaudio** [comment]
how to get 2.7.8 ?

**Comment by mikebrady** [comment]
It's in the development branch. I can mail you a binary for the Pi if you wish.

**Comment by moodeaudio** [comment]
Yes, the binary would be very nice. Mail to tim at moodeaudio dot org

Not much experience with Git but I see in the dev branch readme how to get that code.
- git clone https://github.com/mikebrady/shairport-sync.git
- Next, cd into the shairport-sync directory and execute the following commands:
- git checkout development #select the development branch
- autoreconf -i -f

Tim

**Comment by mikebrady** [comment]
Yep, that's how you'd go about it alright. I've just sent you the binary as an email attachment. Let's hope is isn't stopped by a virus checker...

**Comment by moodeaudio** [comment]
Installed. Will test a bit later

root@rp1:~# shairport-sync -V
2.7.8-openssl-Avahi-ALSA-ao-dummy-stdout-pipe-soxr-metadata

**Comment by moodeaudio** [comment]
Hi Mike - testing confirms issue with hardware mixer is fixed :-) ALSA volume is always set to value corresponding to iTunes slider position at initial iTunes play and thereafter when stop/play or deselect/select Airplay target.

However I'm seeing SPS crash on test system that uses DAC w/o a hardware volume controller. As soon as I press play on iTunes, what was playing on Moode stops as it should but then no sound output from Airplay stream and iTunes Airplay target slider goes gray.

ps -A | grep shairport-sync returns blank indicating crash

Tim

**Comment by mikebrady** [comment]
Thanks Tim. I'll check it later thanks!

**Comment by mikebrady** [comment]
I kind of know what it is – not checking properly for the non-presence of a hardware mixer, but it'll be a few hours before I can get back to it.

**Comment by moodeaudio** [comment]
No prob. Just mail me a new binary when ready and I'll run through the tests.

**Comment by mikebrady** [comment]
Hi Tim. I think I fixed that stupid bug in the latest release, and I've sent you a binary.

**Comment by moodeaudio** [comment]
Hi Mike - works perfectly with both h/w mixer and without. No crash and volume level with h/w mixer always corresponds to slider pos. Much appreciated :-)

**Comment by mikebrady** [comment]
Thanks Tim.

**Comment by mikebrady** [comment]
Closing this, as the bugfix has been made part of stable release 2.8.0.
