### ISSUE TITLE
Detect iphone connection

### ISSUE THREAD

**Issue by DokRaphael** [mikebrady/shairport-sync#208]
Hi, 
I am currently working on my setup : RPI -> DAC -> AMP -> HEADPHONE
I installed some wifi controlled motors (made with arduino-like) on my DAC and AMP in order to switch on when my iphone connects to the RPI (or turn off DAC and AMP when I disconnect the iphone). 
Is there a way to detect that my iphone connects/disconnects (threw airplay) to/from the RPI ?

Thank you

**Comment by mikebrady** [comment]
Shairport Sync can execute a command just before play begins and just after play ends – see the `run_this_before_play_begins` and `run_this_after_play_ends` settings. They should be usable, say, to turn on an amplifier before play begins and to turn it back off again afterwards. Is that the kind of thing you're looking for?

**Comment by DokRaphael** [comment]
This can work, but my amp will toggle after each song. 
Maybe I have to look more on avahi protocol to detect that the iphone is connected/disconnected ?

**Comment by mikebrady** [comment]
If you want to detect the presence of the iPhone on the network, then yes, that's outside the scope of Shairport Sync. You could probably detect when the iPhone checked the availability of Shairport Sync as an AirPlay output, but there's nothing to indicate when it stops looking, I'm afraid.

**Comment by roblan** [comment]
Doesn't 'run_this_before_play_begins' and 'run_this_after_play_ends' run when AirPlay session (no song) starts/ends?
+ I think that only during airplaying source advertise iTunes DACP service ( https://nto.github.io/AirPlay.html#audio-remotecontrol or https://www.sugrsugr.com/index.php/airplay-prev-next/ ) so you can respond when service goes up or down

**Comment by noelhibbard** [comment]
DokRaphael: I do something very similar to you and ran into problems where between tracks it would run the shutdown script and turn off all my hardware and then turn right around and turn it all back on. The work around for me was to write a script with something like Python, PHP or Perl. The shutdown and startup scripts both check a boolean named something like 'airplayshuttingdown'. In my case I just write airplayshuttingdown=true to a text file when the shutdown script is called and airplayshuttingdown=false when the startup script is called. So when the shutdown script is called it first sets airplayshuttingdown=true and then waits 10mins. After 10mins it checks to see if airplayshuttingdown is still equal to true. If so, it precedes with the shutdown of my hardware. If it is no longer set to true then it drops out doing nothing. I hope this makes sense. I can now change tracks and pause without my hardware turning off. The only drawback is when I really am done with playback, everything stays on for 10mins. I can live with this though.

**Comment by noelhibbard** [comment]
roblan: run_this_before_play_begins and run_this_after_play_ends both get called between tracks now. I don't recall it working this way on older versions of iOS. When you pause it also calls run_this_after_play_ends. It's a pain in the butt. But I think it's out of Mike's hands.

**Comment by mikebrady** [comment]
There have been changes in iOS 9.2. If you play a continuous album or playlist, then it's one session, but whenever you skip forward to a new track or back to a previous track, it now tears down the session and starts another. This doesn't happen in iTunes, Not sure if it's a mistake in the Music app. Anyhow, @noelhibbard is right – it's out of my hands, I'm afraid. @noelhibbard's timeout idea looks like a good way to go...

**Comment by DokRaphael** [comment]
Hi 
Thank you for all of your answers. .
@roblan : I think for https://nto.github.io/AirPlay.html#audio-remotecontrol, TEARDOWN can be a good trigger.
@noelhibbard that's a good idea, just have to hope that airplayshuttingdown=true and the checking don't randomely overlap when a song stops

I will try something this weekend and will keep you posted.
Thank you very much for the unofficial documentation

**Comment by DokRaphael** [comment]
Thank you @mikebrady for your feedbacks !

**Comment by chasylexus** [comment]
Here:
http://forums.slimdevices.com/showthread.php?103999-Raspberry-Pi-with-Squeezelite-and-Shairport_Sync
Petar solved the problem of stop Squeezelite before Shairport-sync works and start it after Shairport-sync ends. Does it help?

**Comment by mikebrady** [comment]
Shairport Sync now offers an active mode to address this problem better. Please open a new issue if necessary.
