### ISSUE TITLE
Feature Request: post volume change metadata with disabled volume option

### ISSUE THREAD

**Issue by klaas1979** [mikebrady/shairport-sync#209]
Hi,

I have disabled the volume changes via: ignore_volume_control = "yes"; then the volume metadata is ommitted from the metadata file.

I would like to read the volume metadata from the provided metadata within the pipe. My problem is, when I disable the volume the metadata does not contain volume changes. When I enable the volume_control I get the changes but the software mixer is already doing the volume change.

I would like to use a script to watch for volume changes and then change the volume of an external hardware.

I need to disable the volume mixer and still got the metadata :)

Regards Klaas

**Comment by mikebrady** [comment]
I should be able to do something like this, yeah.

**Comment by mikebrady** [comment]
I just pushed out an update with they feature – see 2.7.10. Let me know if it's working for you.

**Comment by klaas1979** [comment]
Hi Mike,

my server hardware died yesterday. I already ordered the new parts. I will try it as fast as possible and keep you posted about my results.

Thank you very much for your fast help
Klaas

**Comment by mikebrady** [comment]
Closing this, as it has been made part of stable release 2.8.0.

**Comment by klaas1979** [comment]
thank you very much, I am experimenting with your setting right now. It looks great!

**Comment by klaas1979** [comment]
Just if somebody needs an example how to read the metadata with bash, here is part of my volume control script. It contains everything to extract data from the metadadata pipe.

    #!/bin/bash
    item=""
    oldChangeCoeffCli=""
    while read -r line
    do
      item="$item$line"
      # check if item is complete XML snippet
      if [[ $item == *"</item>" ]]
      then
        # type not needed right now so no need to convert it
        # encodedType="${item##*<type>}"
        # encodedType="${encodedType%%</type>*}"
        # decodedType="$(echo "$encodedType" | xxd -r -p)"
     
        # get the code it must be 'pvol' for volume
        encodedCode="${item##*<code>}"
        encodedCode="${encodedCode%%</code>*}"
        # xxd converts hex string to ascii see http://stackoverflow.com/questions/13160309/conversion-hex-string-into-ascii-in-bash-command-line
        decodedCode="$(echo "$encodedCode" | xxd -r -p)"
     
        # is it pvol then change volume
        if [[ $decodedCode == "pvol" ]]
        then
          encodedData="${item##*<data encoding=\"base64\">}"
          encodedData="${encodedData%%</data>*}"
          decodedData="$(echo "$encodedData" | base64 --decode)"
     
          # Only change volume if data could be decoded
          if [[ $? == 0 ]]
          then
            # the volume consists of multiply values separated by a colon, we need only the first
            shairportVolume="${decodedData%%,*}"
            echo "The volume is: $shairportVolume"
          fi
        fi
      fi
    done < /tmp/shairport-sync-metadata

**Comment by mikebrady** [comment]
Many thanks for this.
