### ISSUE TITLE
UFW blocking remote connections

### ISSUE THREAD

**Issue by fcarrega** [mikebrady/shairport-sync#214]
Hello there,

I've been experimenting a firewall issue when trying to connect to a Raspberry Pi (under Wheezy) with a remote device (Spotify on iPhone 5).

This was due to ports blocked by UFW. Adding the following lines allowed me to solve the problem

```
sudo ufw allow from 192.168.1.1/16 to any port 3689 proto tcp
sudo ufw allow from 192.168.1.1/16 to any port 5353
sudo ufw allow from 192.168.1.1/16 to any port 5000:5005 proto tcp
sudo ufw allow from 192.168.1.1/16 to any port 6000:6005 proto udp
sudo ufw allow from 192.168.1.1/16 to any port 35000:65535 proto udp
```

Do you think it would be useful to add a small paragraph on the README for people experiencing the same problem ? If yes, I can write sth and PR it.

Cheers, and thanks for the app !

**Comment by mikebrady** [comment]
Hi Fabrice. Sure thing – I'd be glad of it. I've just added a TROUBLESHOOTING.md document to the development branch, so if you could create a *brief* headed paragraph for it, that would be great.

**Comment by fcarrega** [comment]
PR #216

**Comment by mikebrady** [comment]
Closing this issue. Thanks for the contribution.
