### ISSUE TITLE
lost sync with source on pi + android

### ISSUE THREAD

**Issue by wdehoog** [mikebrady/shairport-sync#217]
I run shairport-sync using the plugin from openmediavault on a banana pi. From windows (TuneBlade) there were no problems. When streaming from my android phone (AllStream) the audio stops every few seconds and I get these errors (see below). Reading through the issues I tried  drift = 350 and resync_threshold = 10000. And now the audio is ok. 

Yes sorry, not exactly an issue but how else should I notify this?

RTSP Flush Requested by handle_record: 3653219918.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2939.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 4861.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -3494.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -3812.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 4787.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2699.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 3461.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2824.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 4647.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -3258.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2755.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 3402.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2993.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 4616.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -3407.

**Comment by mikebrady** [comment]
Thanks for the report. It does look like there is a great deal of variation in the rate that audio packets are arriving at the Pi from Android. Is it possible that the network connection is responsible?

**Comment by wdehoog** [comment]
I doubt it. The windows machine (from which it did work) is on the same wireless network. The banana pi is connected to the router using ethernet. The problem happens when I am close to the wifi router.

As said I am a happy user now so thank you for this magnificent tool.

Side note: most unfortunate is the fact that openmediavault 'owns' the config file so all settings are lost when I enable or disable shairport-sync. And when testing I have to disable it since there is a monitor respawning the shairport daemon whenever it is killed.

**Comment by mikebrady** [comment]
Thanks. We must keep a watching brief.

**Comment by mikebrady** [comment]
Hi there. The latest update on the stable master branch – 2.8.1 – might be relevant to this. It contains a number of fixes, and one of them just might be related...

**Comment by wdehoog** [comment]
Just checked out git. Unfortunately it does not help. But with drift and resync_threshold it still works.

I pasted a log here https://justpaste.it/rza7. The statistics give:

Mar  5 18:17:50 openmediavault shairport-sync[4621]: Sync error: -741.8 (frames); net correction: 67.3 (ppm); corrections: 67.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 2808, min and max buffer occupancy 216 and 280.
Mar  5 18:19:30 openmediavault shairport-sync[4621]: Sync error: -383.6 (frames); net correction: 5.3 (ppm); corrections: 52.2 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 2667, min and max buffer occupancy 244 and 282.

**Comment by mikebrady** [comment]
Thanks for the update. I had a look at the AllStream section of the Google Play Store, and I see that it needs to have a rooted system to operate. So, it's quite a long way outside my comfort zone – I don't own an android device, and I'd be uncomfortable borrowing and rooting someone else's.

One thing that was included in the latest version is an estimation of of the mean, standard deviation and maximum inter-packet times for packets of audio – it's available when you set the log verbosity to 3. The mean should be exactly every 352/44100 of a second, i.e. every 7,891 milliseconds. In my experience, the standard deviation should be between 0.4 (Ethernet direct, without a router) and about 4 milliseconds (WiFi, via a router), and the longest times should not often exceed about 70 milliseconds, and rarely exceed 500 milliseconds. I'd you got a chance, could you see what's coming out of AllStream? TBH, I'm not sure what I'm looking for...

**Comment by wdehoog** [comment]
But the log I pasted in justpaste was with log verbosity set to 3 and the connection was done with Allstream from my rooted Android. It came from syslog. What other information source is there that provides the data you are looking for?

**Comment by mikebrady** [comment]
Hi there. I'm just wondering if there is any news on this, or can I close the issue?

**Comment by wdehoog** [comment]
Sorry. No news. I'll close the issue. Thanks for your work.
