### ISSUE TITLE
Audio Dropouts on ARMv5 Kirkwood Device (GoFlex Home)

### ISSUE THREAD

**Issue by nwcatalyst** [mikebrady/shairport-sync#218]
Howdy,

This might not be an issue, but I'm wondering if anyone else is experiencing frequent dropouts on a low power device like mine? I am running a fresh install of ArchLinux on my GoFlex Home and have a standard USB DAC. I have the config below in hopes to maximize stability. I have no other AirPlay clients so sync is not a concern for me... really just looking for solid playback from sources (AirAudio on Android, sometimes iTunes on a mac). If I ought to change anything let me know. Thanks.

Thanks!

`statistics = "no"; // set to "yes" to print statistics in the log
        drift = 352; // allow this number of frames of drift away from exact synchronisation before attempting to correct it
        resync_threshold = 0; // a synchronisation error greater than this will cause resynchronisation; 0 disables it
metadata =
{
        enabled = "no"; // et to yes to get Shairport Sync to solicit metadata from the source and to pass it on via a pipe
        include_cover_art = "no";`

**Comment by mikebrady** [comment]
By any chance is the network connection via WiFi? And if so, does it have a low-power mode you can disable?

**Comment by nwcatalyst** [comment]
Android is connected via WiFi (it is wireless N) but the GFH is connected via Ethernet. I have dd-wrt running on the router and didn't change any power mode from the default but I will check it now.

Interpolation is set to basic, sorry for not copying the whole config I couldn't grab it all from the chromebook's ssh window.

**Comment by mikebrady** [comment]
That all sounds fine. It might be worth checking to ensure no funny settings on the router alright. Then see if there's much difference between iTunes and AirAudio. If nothing is obvious, you can set the drift to zero to disable resynchronisation. It's worth a try.

**Comment by nwcatalyst** [comment]
Drift is at zero - I just did a reboot after giving the GFH a QoS boost and it seems to be working better now - still occasional skip/drop but much more consistent. 

Do you know of a way in Arch to dedicate more CPU/RAM to the service? I'm sort of new to linux. If not, many thanks for your hard work!

**Comment by mikebrady** [comment]
There's some talk of setting the "niceness" of the process over at #205 – YMMV.

**Comment by mikebrady** [comment]
Hi there. Just FYI, the latest update to the master version is 2.8.1 and contains at least one bug fix which might be related to your report.

**Comment by tsynik** [comment]
**nwcatalyst**, also, did you tried [load snd-usb-audio module with nrpacks = 1](https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture/Troubleshooting#Crackling_sound_with_USB_sound_devices)?

**Comment by nwcatalyst** [comment]
Will do so now - thanks guys.

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new one if necessary.
