### ISSUE TITLE
couldn't create avahi client: Daemon not running!

### ISSUE THREAD

**Issue by tnptek** [mikebrady/shairport-sync#219]
My current setup : PI B+/IQaudio DAC+/Moode OS v.2.5 , everything is working fine except only airplay.
after entering command shirport-sync - V , i got error as below

root@moode:~# shairport-sync - V
startup 
couldn't create avahi client: Daemon not running!

is there anything wrong? Pls advise how to fix it  .Thanks

**Comment by mikebrady** [comment]
Shairport Sync is integrated into the Moode system – it provides the Airplay service – and you are best off enabling it there via the configuration screen. 
![moode](https://cloud.githubusercontent.com/assets/4265913/12828613/cb5a6db4-cb7d-11e5-85e9-29cdbabce10a.png)

**Comment by tnptek** [comment]
I already enabled AirPlay service in the system configuration and reboot it but it's still not working. Something is broken in the Linux?

**Comment by mikebrady** [comment]
Yep, something isn't working right. Might be worth reinstalling it. Avahi provides the Zeroconf service needed to make the AirPlay service visible on the network.

**Comment by mikebrady** [comment]
Hi there. Did you ever sort this one out?

**Comment by amsluis** [comment]
I solved this issue by installing the libnss-mdns package on a C.H.I.P flashed with headless debian.  This SO page was helpful http://askubuntu.com/questions/460371/trouble-using-ssh-and-avahi

You can check if avahi is running with: service avahi-daemon status

Note that you have to be root for service to work on Debian.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
