### ISSUE TITLE
Tuneblade standby mode does not work. => Dropping flushed packet

### ISSUE THREAD

**Issue by gibman** [mikebrady/shairport-sync#220]
Hi all.

**A bit of background first.**
I am using Tuneblade for windows [http://tuneblade.com/](url)
It is capable of transmitting all audio captured on the PC to 'n' number of airplay devices in order to get perfect multi room music in sync.

I have 2 headless rasp pi's running. One with HDMI=>AVR. Another pi running hifiberry digi => toslink => active speaker.

Previously I had the official version of shairport running on the 2 rasperry pi's and this.
This worked ok. No issues with standby mode.
Only problem was that sync would slowly drift.

So i started looking at shairport-sync instead.

**The problem at hand**

Tuneblade supports a really ingenious feature called "standby mode".
After a predefined period of detected silence it will then stop streaming effectively making the airport device available again for other tasks.
Once systemwide audio on the PC is detected tuneblade will re-initiate the stream to the selected airplay devices.

Sadly once standby has been activated and I then after ~1 minute try and resume the stream again from within tuneblade - then this is where the problem occurs.
Nothing but silence is rendered on the pi's. Sometimes music is heard after 30 sec... sometimes it takes 2 minutes. sometimes even longer. Very random.

During these periods of silence the log is filled with:

_Dropping flushed packet in player_put_packet, seqno 16035, timestamp 2485869, flushing to timestamp: 2488464._

Finally audio is heard again. This happens exactly where the log has this:
_syncing to seqno 16043._

I have added comments to the log.
look for "gibman" in the log file attached.

I'd be happy to further explain or even do some testing.
FYI I compiled a version of shairport-sync from the dev branch as of feb. the 4th.

[shairport-sync.log.txt](https://github.com/mikebrady/shairport-sync/files/118763/shairport-sync.log.txt)

**Comment by mikebrady** [comment]
Many thanks for the report. I'll check it out.

**Comment by mikebrady** [comment]
Looking at the log, it seems that an apparently bogus flush command is sent by TuneBlade just before the audio stream starts up. It looks bogus because the timestamp in it is unrelated to the timestamps of the subsequent audio stream. It's the flush command that is muting the output. So I've pushed an update that, rather arbitrarily, ignores flush commands that are received before the first packet of audio. Could you try it out please?

**Comment by gibman** [comment]
hi Mike..

Thanks for looking into this.

ofcourse I will test it. :)

Will let you know the results soon.

regards
gibman

**Comment by gibman** [comment]
I've forwarded this issue to Tuneblade support as well. Just for good measure.

I did try the latest sources and it seems to do ok :)
No more flush entries in the log.
Audio is audible once I resume playback. No delays.

So it seems to be solved.
good work.

I will test it heavily during this weekend.

regards
gibman

**Comment by mikebrady** [comment]
Thanks. I would hesitate to say it's a bug in TuneBlade, but honestly, that's how it looks to me right now. I'd be glad to talk to them, if needed.

**Comment by mikebrady** [comment]
Just checking back with you – is it still okay?

**Comment by gibman** [comment]
hi Mike.

Yeah it most certainly is :)

Everything seems perfect.

Again thanks for fixing it.

regards
gibman

**Comment by mikebrady** [comment]
Cool. It'll be in the next release.

**Comment by mikebrady** [comment]
This has been fixed in 2.8.1.
