### ISSUE TITLE
Restrict shairport-sync to only one network interface?

### ISSUE THREAD

**Issue by lowflyerUK** [mikebrady/shairport-sync#224]
Hi! Thanks for a super project!

Sorry if this should be obvious...

I am running shairport-sync on a Raspberry Pi that has 3 wired ethernet interfaces, providing VPN client access on eth2, normal internet access over adsl on eth0 and fallback internet access on eth1 (if eth0 breaks). I want shairport-sync to be accessible and usable for clients on the same network as eth2, but not visible or usable on eth0 (eth1 doesn't matter as there are no other clients there). I can do this for minidlna using the configuration parameter "network_interface" and/or "listening_ip".  Is there anything similar in shairport-sync? If not, do you have any suggestions as to how I could block access on eth0?

Many thanks.

**Comment by mikebrady** [comment]
Thanks!

Your question is not obvious, nor is the answer, I'm afraid. I think the key to it is to get Avahi to advertise the service only on `eth2` and, TBH, I'm not sure how to do that. Maybe some of the readers have ideas. If it requires programming of Shairport Sync, I'd be interested in it.

**Comment by mikebrady** [comment]
This might be relevant – it refers to `allow-interfaces` and `deny-interfaces` directives...

http://serverfault.com/questions/470773/avahi-daemon-binds-to-eth0-udp-ports-5353-and-53791

**Comment by lowflyerUK** [comment]
Thanks for your quick and helpful replies. I will look at this and report back.

**Comment by lowflyerUK** [comment]
Yes! That seems to work with `deny-interfaces=eth0` in /etc/avahi/avahi-daemon.conf - then restarting both avahi-daemon and shairport-sync. Thanks again!

**Comment by mikebrady** [comment]
Excellent!

**Comment by mikebrady** [comment]
I'll close this – it's done, thanks.
