### ISSUE TITLE
pulseaudio (linux, ver 8.0) -> shairport-sync = no sound (Error in setup request.?)

### ISSUE THREAD

**Issue by mavelli** [mikebrady/shairport-sync#227]
cubieboard a20 with archlinux arm running, installed shairport-sync - with the idea to have it as audio sink for my stereo to stream from different computers/phone music to it - first i decided to make it play music from my workstation (archlinux, pulseaudio 8.0)

cubieboard a20 has a nuforce usb DAC for audio play and works locally (alsa - speaker-test)
```
card 0: Audio [NuForce USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice `#0`
```

linux pulseaudio (airplay discover) -> shairport-sync: no sound

shairport-sync verbose tells this:

```
Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "default".
startup
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "CubieBridge".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "0".
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 1.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
avahi: avahi_register.
avahi: register_service.
Avahi without metadata
culling threads.
new RTSP connection.
    CSeq: 1.
    Content-Type: application/sdp.
    Content-Length: 571.
    User-Agent: iTunes/4.6 (Macintosh; U; PPC Mac OS X 10.3).
    Client-Instance: 291106ac22c25663.
    Apple-Challenge: gNfg37sAAAAAAAAdwQAAAA.
Play connection from user agent "iTunes/4.6 (Macintosh; U; PPC Mac OS X 10.3)".
    Apple-Response: C9oa/TKOuYmfPXkmNDk4/6Xd7H/mvpJ4mxXP3MppNmfh6+QwPIMxtO8Rtj0q8Sqe0otjfaCLi3jevYDGx7lCMIfmEg4sWpBM6l/fcZSQVAzFLmqdM9L9+XFwi3Nx4B11ZbQ7vdP8Q+D4ftzxgCsQ03WoJRX7XysEUUyqRHFULiFTTfFP91aeJvhw+P6WUvnoB51zEaohiPm7Y9IH6ML82z5/Lj3luZ1D68+nvgnSY1glz6OENO6zLujg0517XUHAGfgqeJZ6Qe6GXBRmILfELiuMtFuDhw8bmBM/ZM/J4TfpT2PfeMAKvyzyTHUiB6EqNHOI1/m9QAR/4OTeJQKbkA.
    CSeq: 1.
    Audio-Jack-Status: connected; type=analog.
    CSeq: 2.
    Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=record.
    User-Agent: iTunes/4.6 (Macintosh; U; PPC Mac OS X 10.3).
    Client-Instance: 291106ac22c25663.
Error in setup request.
    CSeq: 2.
    Audio-Jack-Status: connected; type=analog.
```
here, the music on the workstation is playing but i cannot hear it (no output on the cubie to speakers) - i can switch it to another sink on pulseaudio and it will continue and be heard, then switching it to shairport-sync sink it will behave as if it is working but no sound. so i kill the shairport sync:
```
^Cshutdown requested...
avahi: avahi_unregister.
exit...
```

the only thing i see as weird is "Error in setup request." - what is happening?

another detail i realised: while pulseaudio on the workstation is running and in discover airplay devices enabled, i do not see the shairport-sync sink on my osx machine. weird or feature?

**Comment by mikebrady** [comment]
Shairport Sync is not compatible with PulseAudio devices – it needs real hardware. Setting the output to `hw:0` Looks like it might be right. I'm afraid I don't understand your last question. I do not use PulseAudio – are you talking about a PA feature?

**Comment by mavelli** [comment]
last question : yes PA thing

changed to hw:0, still getting the same no sound and same output by shairport-sync

to clarify about pulseaudio. the sink running shairport-sync has no pulseaudio installed. the source linux machine runs pulseaudio and has

via pulseaudio-raop the ability to play to airplay devices (it worked with a apple airport express some time ago) - so i tried to stream to the new setup cubie with shairport-sync installed on it. (this report)

[machine running pulseaudio 8.0] -> shairport-sync : no sound (Error in setup request)

**Comment by mavelli** [comment]
update: just changed from pulseaudio libpulse 8.0 to libpulse-raop2 7.1 (https://hfujita.github.io/pulseaudio-raop2/ https://aur.archlinux.org/packages/pulseaudio-raop2/) and it works fine with shairport-sync

so probably a bug in the pulseaudio 8.0 with the old raop code - hmmm

**Comment by mavelli** [comment]
for documentation: output at shairport-sync when getting stream from libpulse-raop2 7.1:

```
culling threads.
one joined...
new RTSP connection.
    CSeq: 1.
    Content-Type: application/sdp.
    Content-Length: 573.
    User-Agent: iTunes/11.0.4 (Windows; N).
Play connection from user agent "iTunes/11.0.4 (Windows; N)".
    CSeq: 1.
    Audio-Jack-Status: connected; type=analog.
    CSeq: 2.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002.
    User-Agent: iTunes/11.0.4 (Windows; N).
User-Agent is iTunes 10 or better, (actual version is 11); selecting the iTunes latency of -1 frames.
rtp_setup: cport=6001 tport=6002.
Connection from IPv4: 192.168.6.43:44466
listening for audio, control and timing on ports 6001, 6002, 6003.
    CSeq: 2.
    Audio-Jack-Status: connected; type=analog.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6002;timing_port=6003;server_port=6001.
    Session: 1.
    CSeq: 3.
    Session: 1.
    Range: npt=0-.
    RTP-Info: seq=47627;rtptime=1139346551.
    User-Agent: iTunes/11.0.4 (Windows; N).
    CSeq: 3.
    Audio-Jack-Status: connected; type=analog.
    Audio-Latency: 11025.
    CSeq: 4.
    Session: 1.
    Content-Type: text/parameters.
    Content-Length: 18.
    User-Agent: iTunes/11.0.4 (Windows; N).
SET_PARAMETER Content-Type:"text/parameters".
received parameters in SET_PARAMETER request.
    CSeq: 4.
    Audio-Jack-Status: connected; type=analog.
syncing to seqno 47627.
    CSeq: 5.
    Session: 1.
    RTP-Info: seq=48366;rtptime=1139606679.
    User-Agent: iTunes/11.0.4 (Windows; N).
    CSeq: 5.
    Audio-Jack-Status: connected; type=analog.
```

**Comment by mavelli** [comment]
libpulse 7.1 with raop2 works (however, audio lag about 2.2 seconds)
libpulse 8.0 with its own raop does not 
closing - as upstream issue (pulseaudio)
