### ISSUE TITLE
Wrong DACP-ID string for IDs with leading '0' characters

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#229]
shairport-sync forgets the leading `0` characters when handling a DACP-ID string. For example avahi-browse shows:

```
iTunes_Ctrl_0283E4975E57C494
```

but shairport-sync tells:

```
DACP-ID string seen: "283E4975E57C494"
```

For remote control the exact dacp id is necessary, otherwise the iTunes server does not react.

**Comment by mikebrady** [comment]
Is this just a leading zero issue – in other words, does Shairport Sync always from the leading character, or does it only happen when it's a zero? If it's just dropping leading zeroes (of an up-to-16-digit hexadecimal number), then I'd guess it's being dropped by the client... I'll have a look.

**Comment by joerg-krause** [comment]
It only happens with zero characters as leading characters.

**Comment by mikebrady** [comment]
I'm guessing it's a feature rather than a bug, but I'll double-check.

**Comment by joerg-krause** [comment]
I guess the DACP-ID string has always a length of 16 characters. The question is: does the AirPlay server sends all 16 characters, maybe decoded as hex?

**Comment by mikebrady** [comment]
The code is just copying the character string, so it's forwarding what's actually received:
```
  ar = msg_get_header(req, "DACP-ID");
  if (ar) {
    debug(1, "DACP-ID string seen: \"%s\".", ar);
    send_metadata('ssnc', 'daid', ar, strlen(ar), req, 1);
  }
```
If it was always missing the first character, I'd say it was a bug, but since it works for all but leading zeroes, I think it's actually correct. I'd be a bit reluctant to start altering the information that's sent – my thinking is that Shairport Sync should pass the information on as "purely" as possible. What do you think?

**Comment by mikebrady** [comment]
Hi @joerg-krause. I think this will be a "won't-fix", for the reason given above. Is that okay?

**Comment by joerg-krause** [comment]
@mikebrady Yes, it is! I'll fix it in my remote control to fill the string with leading zeros if the DACP-ID string has less than 16 characters.
