### ISSUE TITLE
Possibility to use gstreamer pipeline

### ISSUE THREAD

**Issue by marrem** [mikebrady/shairport-sync#233]
More of a feature request, this...

I have installed some old Wharfedales on top of the kitchen cupboards, which are close to the ceiling. This created an annoying resonance at around 600 Hz. With mopidy I could specify a gstreamer chain including a gstreamer equalizer plugin, which has greatly remedied the bad accoustics of my kitchen speaker arrangement.
I am using the same raspberry pi as an airplay renderer, using shairport-sync. I would like to use this gstreamer equalizer too for shairport. Is this possible?

**Comment by mikebrady** [comment]
I'm afraid I don't think it's possible. Shairport Sync really likes to see a real hardware device as its output to be able to measure the latency for keeping sync.

**Comment by marrem** [comment]
Ok. I understand. Maybe I should look for some none sync fork. But then I loose multiroom sync play. 

Mike Brady <notifications@github.com> schreef op 22 februari 2016 22:54:55 CET:
>I'm afraid I don't think it's possible. Shairport Sync really likes to
>see a real hardware device as its output to be able to measure the
>latency for keeping sync.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mikebrady/shairport-sync/issues/233#issuecomment-187403872

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by mikebrady** [comment]
An equaliser would make a really nice project for someone!

**Comment by marrem** [comment]
could I use the "pipe" backend to stuff audio into a gstreamer pipeline?

**Comment by mikebrady** [comment]
Yes, but you will not have synchronisation.

**Comment by mikebrady** [comment]
I'm closing this issue. Please feel free to reopen it if there are any developments.

**Comment by marrem** [comment]
Hi Mike,

I'm now using the alsa equalizer plugin, which works fine in combination with shairport-sync.
Thanks

Regards,
Marc


-- 
Marc Remijn
Sent with Airmail

Van: Mike Brady <notifications@github.com>
Beantwoord: mikebrady/shairport-sync <reply@reply.github.com>
Datum: 31 mei 2016 at 13:31:45
Aan: mikebrady/shairport-sync <shairport-sync@noreply.github.com>
Cc: marrem <marc@remijn.org>, Author <author@noreply.github.com>
Onderwerp:  Re: [mikebrady/shairport-sync] Possibility to use gstreamer pipeline (#233)  

I'm closing this issue. Please feel free to reopen it if there are any developments.

**Comment by mikebrady** [comment]
Excellent, thanks.

**Comment by LuckyLukeCH** [comment]
Hi Marc,

I'm struggling with the same problem... Could you provide your configuration with shairport-sync and alsaequal?

Thank you and regards
Lukas

**Comment by ni-kan** [comment]
Hey, Lukas, I got alsaequal working with shairport-sync as well. However, I uninstalled it in the end because whenever I don't route sound directly to my hardware dac (HiFiBerry DAC+ Pro) but through the equalizer, it comes out kind of muffled. Your mileage may vary, though. 

After installing alsaequal,  you have to add the following to your /etc/asound.conf configuration file to create a new software equalizer-device (assuming, your dac is hardware card 0, otherwise change it accordingly):
```
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm "plughw:0,0";
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}
```
then comment out the current `output_device` and `mixer_control_name` settings in `/etc/shairport-sync.conf` and add `output_device = "equal"` instead. That's not yet enough, though, because alsa needs to be able to create a `.alsaequal.bin`-config-file in the user's directory or else the equalizer won't work (at least it wouldn't for me). Since shairport-sync is running under the user account `shairport-sync` which does not have a home directory (but is prepared to use on, if you look at `/etc/passwd`), we need to create it with the following command in terminal:

`sudo cp -r /etc/skel /home/shairport-sync && sudo chown shairport-sync:shairport-sync /home/shairport-sync`

Restart your pi afterwards. Then shairport-sync should route the sound to your output device via the equalizer. You can change settings with the following command:

`sudo -H -u shairport-sync alsamixer -D equal`

(use the command w/o the "-D equal" for general changes to alsa sound handling).

Best,

Nick

**Comment by flyingblindonarocketcycle** [comment]
ni-kan, I was very happy to find your instructions on getting eq working with shairport-sync/raspberry/hifiberry as I need the eq functioning with this setup.  Sadly after trying it, I have gone from a functional setup that needed eq to a non-functional setup that produces no audio.  Any idea what I've done wrong?

It might be relevant to add that when typing the home directory command  sudo cp -r /etc/skel /home/shairport-sync && sudo chown shairport-sync:shairport-sync /home/shairport-sync I did not know what prompt I should be at, if that matters.  I think I was at etc when I sent it.

Thanks
Waid

**Comment by flyingblindonarocketcycle** [comment]
Im still trying to recover from the attempt I made at applying this post.  I formatted my raspberry flash and started over completely and I get no audio no matter what I try now.

**Comment by flyingblindonarocketcycle** [comment]
YES! Its working and sounds soooooo good.

Not sure why or if this matters but I installed the EQ before installing shairport-sync.  Made sure the eq was working with a file I put on the raspberry.  Then installed shairport-sync and made sure that was working.
I did NOT so the recursive copy or the change owner command.

I DO access the eq using the sudo -H -u shairport-sync alsamixer -D equal command and notice that the settings are NOT what I had left them at before.  Shairport-sync indeed has its own eq settings and YEAH! it adjust the eq and fixes the audio in the room!

Thank you for the figuring this out guys.
Cheers

**Comment by flyingblindonarocketcycle** [comment]
This is my asound.conf just in case someone finds there way here like I did.

pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw card 1
}
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm "plughw:1,0";
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}

**Comment by boblund** [comment]
I'm using alsaequal with the Justboom amp zero. I can get HW volume control via airplay by setting mixer_control_name='Digital'. I can use alsaequal with output_device=equal, but then I have to comment out mixer_control_name. Is there a way I can get HW volume control and use alsaequal?

Thanks,
Bob

**Comment by mikebrady** [comment]
Hi Bob. Thanks for the post. To be honest, I don’t know whether it is possible or not; maybe some other contributors have ideas.

**Comment by LuckyLukeCH** [comment]
Hello Waid, hello Nick, hello Mike,
Best wishes for the new year!

Thank you for your ideas; now it is working excellent with equalizer. What a difference in sound!
The only thing left is the autostart: It only starts with sound when I enter manually "/usr/local/bin/shairport-sync -d"
Either the init.d nor the rc.local entries seems to work; any idea?

ps aux|grep shairport
root       865  2.8  0.6  70644  5984 ?        Sl   16:44   0:01 /usr/local/bin/shairport-sync -d
-> Autostart; no sound!
kill 865
/usr/local/bin/shairport-sync -d
-> Sound appears
ps aux|grep shairport
root       937 14.2  0.7  71740  7344 ?        Sl   16:45   0:11 /usr/local/bin/shairport-sync -d
-> Both version running under root

Regards
Lukas Gaam

**Comment by flyingblindonarocketcycle** [comment]
Luke

I'm sorry I am no help on this but I can tell you that I don't have that issue and if you think it might benefit you can see all the steps I used for my install on an [instructable ](https://www.instructables.com/id/Raspberry-Pi-Whole-Home-Synchronous-Audio-With-Pho/)I posted.  If I didn't write it down I would never be able to repeat it when adding more Pi/audio zones.

Good luck

**Comment by LuckyLukeCH** [comment]
Hello Waid, hello Mike,
Very nice instructables; especially the hijacking and timeout I was not aware...

The solution for the startup was the user: I couldn't get shairport-sync started as root
And the shairport-sync user didn't work as well

So I decided to start it with the pi user:
nano /lib/systemd/system/shairport-sync.service:
`[Service]
ExecStart=/usr/local/bin/shairport-sync
Restart=always
User=pi
Group=pi`
Afterwards it worked perfect!
The Equalizer must be changed with the pi user logged in, not root...

Regards
Lukas

**Comment by flyingblindonarocketcycle** [comment]
It seems odd that you have to log in as the pi user to make the eq changes.  With the command
```
sudo -u shairport-sync alsamixer -D equal
```
You are forcing the command as if you are logged in as user "shairport_sync".  That is how my install went by the way, installing shairport-sync as if it is its own user but with no password so it doesn't show up as a user in the home directory.  Either that or I'm horribly confused and very lucky.

**Comment by marrem** [comment]
The equalizer settings are stored into the user’s home directory. So if you use a dedicated user for the shairport-sync service, this user has to have it’s own home directory. Also make sure this user is a member of the audio group. 

Marc

Verstuurd vanaf mijn iPhone
