### ISSUE TITLE
Diagnose the quality of the AirPlay stream

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#235]
This is more a question than an issue.

Is it quite normal that I have late and resend packets if both the AirPlay server and the client are connect to the home network via ethernet?

**Comment by mikebrady** [comment]
I have a direct link from a Mac to a Raspberry Pi – no router – and it never registers late or resent packets. Not even out-to-order reports.

**Comment by joerg-krause** [comment]
As far as I understand, audio packet transmission is done via UDP, right? As UDP is unreliable, it is quite normal that some packets or out of order or late - even when transmitting over Ethernet.

It would be great to have an indication of how goozd the link is. I know shairport-sync has statistics and the recently added inter-packet reception, but it would be great to have those values in a parseable format which can be evaluated somehow.

What do you think?

**Comment by mikebrady** [comment]
Hmm, agreed, but I'm not sure what would make sense. Perhaps a range of values for the mean, std-deviation and max values for some representative situations, e.g. direct ethernet; ethernet to router to ethernet; ethernet to router to wifi, wifi to router to wifi, and so on... What would you think yourself?

**Comment by joerg-krause** [comment]
I've thought about having the possibility to pipe some statistics so another process can watch the status of the AirPlay stream and for example visualize the data in a web page or an remote app. This is quite useful for headless system where shairport-sync runs as a daemon.

As the topic has changed in this issue I'll rename the topic.

**Comment by mikebrady** [comment]
Okay – that sounds like something worth thinking through alright. I think there is a fair bit of the infrastructure in place already.

**Comment by joerg-krause** [comment]
Closed, as it's ancient.
