### ISSUE TITLE
Crashing when adjusting volume / skip track

### ISSUE THREAD

**Issue by HiMyNameIsAd** [mikebrady/shairport-sync#238]
Hi,

I am able to successfully connect to shairport sync via iphone and itunes, the music will play but as soon as i begin to adjust volume or try to select a new track, shairport will crash and disconnect the pi from wifi. What could be the issue here?

Many Thanks

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. The development branch has a couple of stability improvements – would you be good enough to to try it and report back? (It seems that recent changes in iOS exposed problems with how Shairport Sync tears and and immediately restarts a play session.)

**Comment by HiMyNameIsAd** [comment]
This worked however when I played the skipped to the next track and tried adjusting the volume, it crashed again, it seems to be related to how quickly you change the volume, if you do it slowly on itunes it seems to keep up but do it quickly and it crashes out. I'm also running smart-mirror and that too crashes with shairport-sync.

**Comment by mikebrady** [comment]
Could you share your /etc/shairport-sync.conf settings please? Also, what sound output device are you using? I don't know smart-mirror, I'm afraid.

**Comment by HiMyNameIsAd** [comment]
`// General Settings
general =
{
        name = "Magic Mirror"; // This is the name the service will advertise to iTunes. The default is "Shairport Sync on <hostname>"
//      password = "secret"; // leave this commented out if you don't want to require a password
        interpolation = "soxr"; // aka "stuffing". Default is "basic", alternative is "soxr". Use "soxr" only if you have a reasonably fast processor.
//      output_backend = "stdout"; // Run "shairport-sync -h" to get a list of all output_backends, e.g. "alsa", "pipe", "stdout". The default is the first one.
//      mdns_backend = "avahi"; // Run "shairport-sync -h" to get a list of all mdns_backends. The default is the first one.
//      port = 5000; // Listen for service requests on this port
//      udp_port_base = 6001; // start allocating UDP ports from this port number when needed
//      udp_port_range = 100; // look for free ports in this number of places, starting at the UDP port base (only three are needed).
//      statistics = "no"; // set to "yes" to print statistics in the log
//      drift = 88; // allow this number of frames of drift away from exact synchronisation before attempting to correct it
//      resync_threshold = 2205; // a synchronisation error greater than this will cause resynchronisation; 0 disables it
//      log_verbosity = 0; // "0" means no debug verbosity, "3" is most verbose.
//  ignore_volume_control = "no"; // set this to "yes" if you want the volume to be at 100% no matter what the source's volume control is set to.
//   volume_range_db = 30 ; // use this to set the range, in dB, you want between the maximum volume and the minimum volume. Range is 30 to 150 dB. Leave it commented out to use mixer's native range.
};

// How to deal with metadata, including artwork
metadata =
{
//      enabled = "no"; // et to yes to get Shairport Sync to solicit metadata from the source and to pass it on via a pipe
//      include_cover_art = "no"; // set to "yes" to get Shairport Sync to solicit cover art from the source and pass it via the pipe. You must also set "enabled" to "yes".
//      pipe_name = "/tmp/shairport-sync-metadata";
};

// Advanced parameters for controlling how a Shairport Sync runs
sessioncontrol =
{
//      run_this_before_play_begins = "/full/path/to/application and args"; // make sure the application has executable permission. It it's a script, include the #!... stuff on the first line
//      run_this_after_play_ends = "/full/path/to/application and args"; // make sure the application has executable permission. It it's a script, include the #!... stuff on the first line
//      wait_for_completion = "no"; // set to "yes" to get Shairport Sync to wait until the "run_this..." applications have terminated before continuing
//      allow_session_interruption = "no"; // set to "yes" to allow another device to interrupt Shairport Sync while it's playing from an existing audio source
//      session_timeout = 120; // wait for this number of seconds after a source disappears before terminating the session and becoming available again.
};

// Back End Settings

// These are parameters for the "alsa" audio back end, the only back end that supports synchronised audio.
alsa =
{
  output_device = "hw:1"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
 mixer_control_name = "Speaker"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
//  mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
//  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
//  audio_backend_buffer_desired_length = 6615; // If set too small, buffer underflow occurs on low-powered machines. Too long and the response times with software mixer become annoying.
};

// These are parameters for the "pipe" audio back end, a back end that directs raw CD-style audio output to a pipe. No interpolation is done.
pipe =
{
//  name = "/path/to/pipe"; // there is no default pipe name for the output
//  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
//  audio_backend_buffer_desired_length = 44100; // Having started to send audio at the right time, send all subsequent audio this many frames ahead of time, creating a buffer this size.
};


// These are parameters for the "stdout" audio back end, a back end that directs raw CD-style audio output to stdout. No interpolation is done.
stdout =
{
  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
  audio_backend_buffer_desired_length = 44100; // Having started to send audio at the right time, send all subsequent audio this many frames ahead of time, creating a buffer this size.
};

// These are parameters for the "ao" audio back end. No interpolation is done.
ao =
{
//  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
//  audio_backend_buffer_desired_length = 44100; // Having started to send audio at the right time, send all subsequent audio this many frames ahead of time, creating a buffer this size.
};

// The following static latency settings are deprecated -- do not use them for new installations. Shairport Sync now sets latencies automatically.
// To compensate for a delay in the output device please use the alsa/stdio/pipe "audio_backend_latency_offset" setting.

// Static latencies for different sources. These have been estimated from listening tests.
latencies =
{
//      default = 88200; // used for unrecognised sources and for iTunes up to and including iTunes 9.X.
//      itunes = 99400; // used for iTunes 10 or later
//      airplay = 88200;
//      forkedDaapd = 99400;
};'

I'm using a USB adaptor with Line in and Headphone out. It works great, the problems begin when either I change the volume too quickly or a song that starts out quiet gets loud and then the whole thing crashes raspbian, knocks any open apps and the wifi off.

**Comment by mikebrady** [comment]
Thanks. The settings are fine, but I notice some of the settings relate to using `stdout`. Is it possible that you could do `shairport-sync -h` and report what the last section reads please? This is what's on mine:
```
Available mDNS backends: 
    avahi
    external-avahi

Available audio outputs:
    alsa (default)
    stdout

Options for output alsa:
    -d output-device    set the output device [default*|...]
    -m mixer-device     set the mixer device ['output-device'*|...]
    -c mixer-control    set the mixer control [Master*|...]
    -i mixer-index      set the mixer index [0*|...]
    *) default option

Options for output stdout:
    stdout takes no arguments
```

If you do `lsusb` it will report the USB devices connected, including the Sound DAC. That would be helpful, thanks.

Finally, by setting the verbosity to 1 or 2 in the configuration file, and by turning on statistics, you'll get some information about what Shairport Sync is doing. That too would be very helpful.

This is a report that I haven't come across before. Does the magic-mirror use audio output?

**Comment by mikebrady** [comment]
Hi there. I've been cleaning up code that I suspect, but can't prove, is possibly causing problems. It's now on the `development` branch. If you got a chance, I'd be obliged if you tried it out, to see it it's any better.

**Comment by mikebrady** [comment]
There have been many updates since this, and I'm pretty sure the problem has been resolved. Please open a new issue if necessary.
