### ISSUE TITLE
corrupted audio every few seconds - running on CHIP

### ISSUE THREAD

**Issue by mrlowalowa** [mikebrady/shairport-sync#240]
Hey,

I got this output and only a fraction of a second sound each 4 seconds:

> Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 2478.

My Wifi is fine. I set this up on a different same hardware and it's working just fine.

Could you give me any hints what I might need to restart or so? I really would like to keep my system running and I'm just wondering what might get me into this.. Internet connection beside this is working absolutely normal on the device.. IRSSI is running also

**Comment by mrlowalowa** [comment]
I installed the developer branch. No sound ticks but instead I got this here:

ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card

**Comment by mikebrady** [comment]
Thanks. Did you specify an output device, or did you use the default, I wonder? If you used the default, it might be worth specifying an actual hardware sound card – use `alsamixer` or similar to explore and then put the setting into `/etc/shairport-sync.conf`. (Maybe you've done this already – apologies if so.)

**Comment by mikebrady** [comment]
Here are the relevant settings I'm using on my CHIP, with commented-out settings removed and comments chopped off:
```
general =
{
	name = "Front Room"; 
};

alsa =
{
  output_device = "hw:0";
  mixer_control_name = "Power Amplifier";
}
```

**Comment by mrlowalowa** [comment]
you do not have to apologies! :D 

but yes I specified the hardware as hw:0. I followed the tutorial here: https://www.hackster.io/11798/c-h-i-p-play-speakers-7cebb9

maybe some configurations are in conflict with the developer build?

I checked alsa and it looks like it is completely crashed.. (That wasn't the case when I installed the normal one..)

**Comment by mikebrady** [comment]
Hmm, there are no changes to the settings between the `master` and the `development` branches, and I go back and forth between them routinely.

Is there some other application using the sound card? (I guess IRSSI doesn't use it...)

**Comment by mrlowalowa** [comment]
nope there is absolutely nothing on it.. But the sound card seems to be broken.

> chip@chip_maze:~/shairport-sync$ alsaloop 
> ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
> playback hw:0,0 open error: No such file or directory
> Loopback initialization failure.

I'm just searching how to restart the sound module..

**Comment by mikebrady** [comment]
Cool. I'm nto sure if you're using `alsaloop`, but if so, I don't how well it would work, TBH. If you just wanted to get Shairport Sync's output into a file, you could try using the `pipe` or `stdout` back ends.

**Comment by mikebrady** [comment]
Thanks. It's really puzzling. And, are you using `alsaloop` on it?

**Comment by mrlowalowa** [comment]
it's installed. I only showed it because it was the onlything that gave me sort of a feedback. alsamixer is also installed and probably used.

**Comment by mikebrady** [comment]
Thanks. I'm a bit baffled, TBH. Mine is running well – I started with the stock software, updated and upgraded it and then followed the installation procedures for Shairport Sync. I'm not using the video and connect via ssh.

**Comment by mrlowalowa** [comment]
maybe it's due to the first debian version flashed on this CHIP? And it's a alpha one.. Maybe I have to check out the other alpha if it is having the same problems..

I'm using no video too. I just want to get this working without messing my 129 days uptime.. :D

**Comment by mikebrady** [comment]
Yes, I completely understand about the uptime! Mine is running 4.3.0 alright.

**Comment by mrlowalowa** [comment]
So you have any clue what Module I could quick Patch to get this working?

Oracle is also offering KSpice that can swap kernels while running..

**Comment by mikebrady** [comment]
I'm afraid not – I'm not a linux guru... When these kinds of things happen, I'm usually quick to go for a restart...

**Comment by mrlowalowa** [comment]
meeeh.... Killed my CHIP at 150 days uptime.. copied zImage, sunix data tree and /lib/modules/4.3.0 to my alpha CHIP and I still get the same error.... :(

(of course I rebooted to apply the new kernel..)

**Comment by mikebrady** [comment]
Agh – sorry for the loss of uptime! Could you / have you updated to the latest Shairport Sync? It contains at least one interesting bug fix, I think.

**Comment by mrlowalowa** [comment]
nope.. did not help too.. :/

what I did:
git pull
(cmd's from the tutorial on hackster.io )
autoreconf xyz..
.configure ...
make
sudo make install

Anything I missed?

**Comment by mrlowalowa** [comment]
So, I refreshed my other alpha CHIP completely and set the whole project up again. And it is working..

I might guess that it have something in common with the groups or other settings concerning the setup process? I can remember that I did it ~3 Times. even once with *yourchipname* included and not replaced... So what I did was removing the 2 other entries in /etc/passwd and checking /etc/group , have I missed something? I even changed the ID of the last entry from 997 to 999 so it might correspond with the group 999

**Comment by mikebrady** [comment]
It's actually quite difficult to work out what's going on here, as you are making so many choices, any one of which could be causing the problem. If I was trying to find out what was happening here, I'd install the  standard Linux from the CHIP crowd, and then I'd install Shairport Sync, following the directions in the README.md document. If I couldn't get it working in those circumstances then it would be pretty simple to work out where the problem might be.

**Comment by mikebrady** [comment]
I'm closing this issue. Please feel free to reopen it if there are any developments.
