### ISSUE TITLE
Beginner issue: Segmentation fault

### ISSUE THREAD

**Issue by ubermacin** [mikebrady/shairport-sync#242]
Hi Mike, I'm trying to get the package running that was added to alpine linux (a really nice diskless linux distro), but I think I might be out of luck.

Here is the package in question:
http://git.alpinelinux.org/cgit/aports/commit/?id=7487bb01e709a1146f65b601201ab03fde4e5f3b

My setup:

Alpine Linux 3.3.1 running on a Raspberry PI B+ with a generic usb sound card.  The package shairport-sync is older, 2.2.2, but it's what I have to work with (and I'm guessing the issue considering other threads).  I tried to go through the manual installation instructions on your readme, but I run out of disk space before I get all the tools and libraries I need to make it :(  This is one down side to running a diskless distro.  

I got all the way to this and EVEN got the first 1 second of audio to play but alas... Segmentation Fault

Is there any work around that doesn't require a new version compiled?
shairport-sync -a "test" -vvv -- -d hw:0 -t hardware -c Speaker

statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
Shairport Sync player name is "test".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
latency is 0.
AirPlayLatency is 88200.
iTunesLatency is 99400.
forkedDaapdLatency is 99400.
stuffing option is "(null)".
resync time is 2205.
busy timeout time is 120.
tolerance is 88 frames.
password is "(null)".
Hardware mixer has dB volume from -28.370000 to -0.060000.
Has mute ability.
startup
avahi: avahi_register.
avahi: register_service.
culling threads.
new RTSP connection.
culling threads.
new RTSP connection.
RTSP connection closed.
closing RTSP connection.
terminating RTSP thread.
    Apple-Challenge: X9m1crIjV3Oz18qrS8MtXA==.
    CSeq: 0.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
    Apple-Response: Q9WRmHJfuv4ZA4Rvx40m0ssZnxrb+rpFjLISE7kIM7mClOH07q7B3AN0qFjKVa57+4i5qby9JKiv3FXQ59g8EaUVaptKt03Fxa4FzjnRCcqbvMLomqf7exCJ1LYsQ0OkZv1KnoPGyz9DNhtTbfg3Wo2HRJ4ICTmaGO2GN7rmmYCsMMYWjqvF/j76tIraRNlg4bVhy6h/FwI87bDLloxA93k51oHDP/Xw7WdUkmqrl52h+C9hPHkK2yLVpw9wNebOnSQlDK5cyxPIsX7g0d0YMyOLrWOEfRQmthZQzlQ5mTEBTdltEz7O5o0f7hp2asqfa5HazHdoHxsQh49WRYgl9g.
    CSeq: 0.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    Content-Length: 662.
    Content-Type: application/sdp.
    CSeq: 1.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
Play connection from "AirPlay/267.3".
    CSeq: 1.
    Audio-Jack-Status: connected; type=analog.
    Transport: RTP/AVP/UDP;unicast;mode=record;timing_port=63764;control_port=56283.
    CSeq: 2.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
User-Agent is AirPlay; selecting the AirPlay latency of 88200 frames.
rtp_setup: cport=56283 tport=63764.
Connection from IPv6: fe80::182e:348d:77a:9b25:50702
listening for audio, control and timing on ports 34722, 49325, 36728.
    CSeq: 2.
    Audio-Jack-Status: connected; type=analog.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=49325;timing_port=36728;server_port=34722.
    Session: 1.
    CSeq: 3.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
    CSeq: 3.
    Audio-Jack-Status: connected; type=analog.
    Audio-Latency: 88200.
    Content-Length: 20.
    Content-Type: text/parameters.
    CSeq: 4.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
    CSeq: 4.
    Audio-Jack-Status: connected; type=analog.
    RTP-Info: seq=38251;rtptime=1677372925.
    CSeq: 5.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
    CSeq: 5.
    Audio-Jack-Status: connected; type=analog.
Dropping flushed packet in player_put_packet, seqno 38251, timestamp 1677368734, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38252, timestamp 1677369086, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38253, timestamp 1677369438, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38254, timestamp 1677369790, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38255, timestamp 1677370142, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38256, timestamp 1677370494, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38257, timestamp 1677370846, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38258, timestamp 1677371198, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38259, timestamp 1677371550, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38260, timestamp 1677371902, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38261, timestamp 1677372254, flushing to timestamp: 1677372925.
Dropping flushed packet in player_put_packet, seqno 38262, timestamp 1677372606, flushing to timestamp: 1677372925.
syncing to seqno 38263.
+++++++++
    CSeq: 6.
    DACP-ID: 1A9B65B4EF1E9A23.
    Active-Remote: 922045449.
    User-Agent: AirPlay/267.3.
    CSeq: 6.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
Segmentation fault

**Comment by joerg-krause** [comment]
As Alpine Linux is musl-based and the shairport-sync version is quite old, I guess this is related to https://github.com/mikebrady/shairport-sync/pull/78.

Please try to update to latest version 2.8.1.

**Comment by mikebrady** [comment]
Hi Jared, and thanks for the post. I agree with Jörg Krause – it would be worth updating the shairport-sync package (or asking for it to be updated). There have been other important improvements since the versioning in the package, so it would be well worth moving up to 2.8.1.

**Comment by ubermacin** [comment]
Okay, thank you to both, I'll see what I can do.  This issue can be closed, thank you for all that you do!

**Comment by ubermacin** [comment]
Update, the seg error vanished because of the update.  Sadly, took a few months for the build tool for armhf alpine linux to get fixed.  Thanks again!
