### ISSUE TITLE
Shairport-Sync doesn't output audio

### ISSUE THREAD

**Issue by sgtjayus** [mikebrady/shairport-sync#243]
I've installed Shairport-Sync, and I can see Shairport-Sync as an Airport option.  However, when I connect to Shairport-Sync, there is no audio output and I get a "Cannot connect to Shairport-Sync" error message shortly afterwards.  I'm on 10.11.3

 pi@raspberrypi:~ $ shairport-sync -V
2.8.1-openssl-Avahi-ALSA-metadata

pi@raspberrypi:~ $ shairport-sync -vv
Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "default".
startup
The processor is running little-endian.
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "Shairport Sync on raspberrypi".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "0".
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
get-coverart is 0.
Failed to bind to address 0.0.0.0.
Failed to bind to address ::.
could not bind any listen sockets!
Request to shut down all rtsp conversation threads
asking playing threads to stop

**Comment by joerg-krause** [comment]
Is your wifi up? Can you post the output of `ifconfig`?

**Comment by mikebrady** [comment]
Another possibility is that another copy of Shairport Sync is already running – use `ps aux | grep shair` or similar to see...

**Comment by sgtjayus** [comment]
Thanks for responding, folks.  This is what I see:

pi@raspberrypi:~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:2f:b3:14  
          inet6 addr: fe80::aa8e:a35f:6af3:2602/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:203 errors:0 dropped:0 overruns:0 frame:0
          TX packets:203 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:17040 (16.6 KiB)  TX bytes:17040 (16.6 KiB)

wlan0     Link encap:Ethernet  HWaddr 74:da:38:6c:e3:79  
          inet addr:192.168.42.75  Bcast:192.168.42.255  Mask:255.255.255.0
          inet6 addr: fe80::aac9:42b0:3c98:2da8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3554 errors:0 dropped:353 overruns:0 frame:0
          TX packets:1011 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:399614 (390.2 KiB)  TX bytes:131489 (128.4 KiB)

pi@raspberrypi:~ $ ps aux | grep shair
shairpo+   457  0.0  0.4  59728  4308 ?        Ssl  06:09   0:00 /usr/local/bin/shairport-sync
pi        1462  0.0  0.2   4280  2004 pts/1    S+   09:12   0:00 grep --color=auto shair

**Comment by mikebrady** [comment]
Thanks. The response to the `ps aux | grep shair` shows `shairport-sync` already running as process 457. I guess it started when you rebooted the Pi? Anyhow, by default the audio output will be going to the "default" device which is probably the headphone jack. Use `alsamixer` to ensure the volume is turned up full. When you get it working, then you can further adjust the settings in the config file.

**Comment by sgtjayus** [comment]
Thanks guys.  I restarted and killed the process and I'm now I'm seeing these in the logs (still no audio output):

Player: packets out of sequence: expected: 12191, got: 11679, sync error: 0 frames.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 178790.
syncing to seqno 12092.
First packet is late! It should have played before now. Flushing 0.1 seconds
Too-short retransmitted audio packet received in control port, ignored.
syncing to seqno 12107.
First packet is late! It should have played before now. Flushing 0.1 seconds
syncing to seqno 12125.
.
.
.
Too-short retransmitted audio packet received in control port, ignored.
.
.
.

**Comment by mikebrady** [comment]
Thanks for the update. It seems like you're making progress alright.

If I had to make a guess, I'd say your network connections was pretty noisy – would that be fair? If so, then try to improve it, at least temporarily, by maybe bringing it closer to the wireless access point. Also, in case you missed it, use `alsamixer` to make sure the output is maxed out.

**Comment by sgtjayus** [comment]
I'm an idiot.  Leaving this as a record for folks with a Raspberry Pi.  The default audio output is HDMI, so remember to change output to audio jack with `amixer cset numid=3 1`

**Comment by wjrochester** [comment]
Hi, similar issue here. The latency is really high between me air-playing and the audio piping through. To remedy I connected my Shairport device (Dell Inspiron Mini running Raspbian) through ethernet to my Mac mini since the Mini has 5g wifi capabilities. Ethernet connection works, successful ping of google.com with 0% packet loss. How do I tell Shairport to operate through ethernet instead of wifi?

**Comment by mikebrady** [comment]
Thanks for the post. AirPlay is designed to have a latency of around two seconds — are you experiencing a longer delay?

There is a setting in the configuration file to specify which interface to advertise Shairport  Sync on. It’s the `interface` setting in the `general` section.
