### ISSUE TITLE
Dynamically change output_device while connected

### ISSUE THREAD

**Issue by cre8dojo** [mikebrady/shairport-sync#244]
Is there a way/command to change the output_device dynamically while playing (without audio interruption)? 

use case: Say I have a working position tracking system that tracks where a source (smartphone) is in a multiple zone house and I want the music to follow that source has it moves around the house from one zone to another. I want that tracking system to issue a command to shairport-sync to change output_devices to match the zone the source is in without having to choose a new Airplay receiver/instance.
 
Alternatively: Can I hand-off a source/connection from one shariport-sync instance to another without interruption of streaming audio?

Thanks,
Rey

BTW Thank you so much for your work and effort on this project. I've really enjoyed working with it on my Raspberry Pi  with Raspbian Jessie Lite over wifi. I have 6 instances of shairport-sync connected to hdmi out, 2 usb 2-channel sound cards and a bluetooth speaker. I have each channel of the usb cards separated, one channel per shairport-sync instance. I've had 2 bluetooth speakers but was limited to only being able to connect to one at a time by bluetooth adapter. I could still add the second and just never connect to both at the same time. I did find the limit of 3 sources/connections at once before the raspberry pi crashes. But that's plenty for one device.

**Comment by mikebrady** [comment]
Hi there. Thanks for your interest in Shairport Sync! You are certainly pushing the envelope of use cases. There is no functionality for either dynamically redirecting the output or to do a hand-off. One thing that comes to mind, though, is to use a script to mute or unsure, or just change the volumes of a number of Shairport Sync instances, one for each zone. So you could use the tracking information to bring up the volume of the output nearest the user and mute or quieter the others... Just a thought.

**Comment by roblan** [comment]
@cre8dojo can You share some info about Your tracking system?

**Comment by cre8dojo** [comment]
@roblan I have no system yet. I was doing some research on use cases in parallel to researching tracking systems. I didn't want to spend a lot of time implementing a system I couldn't use for what I wanted it for.

I did come to the conclusion you would need either an app on the devices you're tracking and/or array of smart access points you have software running on to track and report info about a device.

I couldn't think of a way to just have software on the raspberry pi shairport-sync receiver since it would be stationary. 

One option might be to deploy an array of raspberry pi's as access points or just has tracking array.  However, since I can't use it to the way I wanted with shairport-sync, I put it on the back-burner.

**Comment by mikebrady** [comment]
I'm closing this issue. Please feel free to reopen it if there are any developments.
