### ISSUE TITLE
Different volume from different devices

### ISSUE THREAD

**Issue by wedi** [mikebrady/shairport-sync#245]
Hi.
I’m not sure if this a an issue with my settings, AirPlay in general or shairport-sync but when I connect with iTunes the volume is much louder than it is from my iPhone. Thus, I still have to go to the stereo. I tried it with the same songs on both devices of course. Any advice is much appreciated!
Apart from this everything works just fine and on first try!
Very well done! Thank you so much!

**Comment by mikebrady** [comment]
Thanks – I'm glad you got it working.

The AirPlay device's volume is under the control of the iOS device, but the volume level for the AirPlay device is distinct from that of the iOS device. When you select an AirPlay device as the output device, the volume is set to whatever it was set to last for that device and you can adjust it with the volume control slider (or the buttons on the side) of the iOS device. Then, when you revert to the iOS device's output, the volume setting reverts to whatever is was on the iOS device's speaker before you changed over to AirPlay.

**Comment by wedi** [comment]
Mike, thank you for your prompt response! Luckily I quickly got the hang of controlling the volume via iTunes / iOS Music – although I have to admit – at first I tried it unsuccessfully with the system wide volume control of OS X.

What I am trying to talking about here is the different maximum volume level that my iPhone and iTunes have when playing via ShairPort. When I switch my stereo from FM to AUX and play a song via ShairPort from iTunes with volume control in the middle position the song is played at almost the same volume as the radio was playing before. But when I play the very same song via ShairPort from my iPhone it is playing at a very low level even if I turn up the volume to the maximum. It’s barely recognizable in the mid position of the volume control in Music on iOS. So i need to adjust the volume at my stereo to listen to music from my iPhone and afterwards I shouldn't forget to turn it back down before switching to radio to keep my neighbours friendly.
Is there any way to change the output volume of ShairPlay depending on the connected streaming device? – What might be a use case for stressed parents as well btw. ;)

**Comment by mikebrady** [comment]
Hi Dirk. This is not something I've experienced, TBH. So, If I were you, I'd be checking to see if there are any settings differences between iTunes and the iOS player. For instance, is Sound Check enabled on one but not on the other, or are the equalizers are set differently? Maybe other users have some experience of this?

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
