### ISSUE TITLE
What is the default resampling behavior?

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#246]
Hi Mike,

When SPS analyzes a stream, what criterion is used to determine whether to resample it, and what is the output rate when resampling occurs?

-Tim

**Comment by mikebrady** [comment]
Hi Tim. It's pretty simple minded:

1. Audio data comes from the ALAC decoder in packets of 352 "frames" – each frame consists of one stereo sample, i.e. two sixteen-bit values. Shairport Sync sends these packets to the output device at the appropriate time.
2. When Shairport Sync is sending an audio packet to the output device's hardware buffer, it checks to see how early or late it will be when the first frame in the packet is played.
3. If the timing error it calculates exceed the "drift" value, then it will remove or add one frame to the packet.
4. This adjustment will not fix the timing error for this packet, but it will tend to correct the timing error for subsequent packets.
5. The adjustment is always the addition or removal of one audio frame. If resampling is being done, the 352-frame sample is resampled to either 353 frames or 351 frames.
6. In practice, after the first five or so seconds, not more than approximately one frame in 1,000 will be added or removed – roughly one frame in three packets, maximum.

I hope that helps.

**Comment by moodeaudio** [comment]
Hi Mike,

I may be confused a bit so some context might help.

There are a few Moode users that have asked if its possible to stream > 16/44.1 files over Airplay to Moode/shairport-sync preserving the > 16/44.1 rate at output. My understanding was that rates > 16/44.1 are always resampled to 16/44.1 by ______________? I’m just not sure whether the resampling is done at the source (iTunes, etc.) or whether shairport-sync handles the resampling using SoX for example.

-Tim

**Comment by mikebrady** [comment]
Hi Tim. Everything arrives in Shairport Sync in CD-quality – 44.1kHz 16-bit interleaved stereo – encoded in Apple Lossless (ALAC) format, so iTunes does the transcoding (I don't know the details of the Music app in iOS – I suppose everything in the library is in 44.1/16 format). The protocols seem to allow for the possibility that the source could send audio in other formats, but, in my experience, they are always sent (compressed in ALAC) in CD-quality format. What's more, Shairport Sync would be unable to handle any different formats, and it would be a non-trivial job to make it work at other rates and sizes.

**Comment by moodeaudio** [comment]
Hi Mike, ok so shairport-sync uses resampling to manage timing error and not for up/down sample the entire stream.  Thx :-)

**Comment by mikebrady** [comment]
Exactly!
