### ISSUE TITLE
failed no such file or directory

### ISSUE THREAD

**Issue by wahhaha9394** [mikebrady/shairport-sync#247]
Hi,

I have follow all the steps up to the point enable Shairport Sync
sudo systemctl enable shairport-sync
I get Failed to execute operation: No such file or directory
I'm installing on raspberry pi Jessie
I can see shairport-sync in my home directory

**Comment by mikebrady** [comment]
Thanks for your interest in Shairport Sync!

You need to make sure that you followed all the steps exactly. Once you have compiled Shairport Sync (that's what would have happened when you performed the `make`), you still have to _install_ it using `sudo make install`. Also, you have to ensure that a `shairport-sync` _user_ and _group_ are defined.

Please keep us posted!

**Comment by wahhaha9394** [comment]
Hi,

I have install once again here are the log:

```
pi@Kitchen:~/shairport-sync $ getent group shairport-sync &>/dev/null || sudo groupadd -r shairport-sync >/dev/null
pi@Kitchen:~/shairport-sync $ getent passwd shairport-sync &> /dev/null || sudo useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null
pi@Kitchen:~/shairport-sync $ sudo make install
Making install in man
make[1]: Entering directory '/home/pi/shairport-sync/man'
make[2]: Entering directory '/home/pi/shairport-sync/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/man/man7'
 /usr/bin/install -c -m 644 shairport-sync.7 '/usr/local/share/man/man7'
make[2]: Leaving directory '/home/pi/shairport-sync/man'
make[1]: Leaving directory '/home/pi/shairport-sync/man'
make[1]: Entering directory '/home/pi/shairport-sync'
make[2]: Entering directory '/home/pi/shairport-sync'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c shairport-sync '/usr/local/bin'
make  install-exec-hook
make[3]: Entering directory '/home/pi/shairport-sync'
[ -e /etc ] || mkdir /etc
cp scripts/shairport-sync.conf /etc/shairport-sync.conf.sample
[ -f /etc/shairport-sync.conf ] || cp scripts/shairport-sync.conf /etc/shairport-sync.conf
[ -e /lib/systemd/system ] || mkdir -p /lib/systemd/system
cp scripts/shairport-sync.service /lib/systemd/system
make[3]: Leaving directory '/home/pi/shairport-sync'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/pi/shairport-sync'
make[1]: Leaving directory '/home/pi/shairport-sync'
```
pi@Kitchen:~/shairport-sync $ sudo update-rc.d shairport-sync defaults 90 10
update-rc.d: error: initscript does not exist: /etc/init.d/shairport-sync

**Comment by mikebrady** [comment]
You don't run the `update-rc.d` command with `systemd` systems like Jessie. Just enter the `sudo systemctl enable shairport-sync`, configure the settings in `/etc/shairport-sync.conf` and reboot.

**Comment by wahhaha9394** [comment]
Hi Mike,
Many thanks for your help on the above. it works perfectly now. :)
Have a great day ahead.

**Comment by mikebrady** [comment]
Thanks – it's early spring in this part of the world. Enjoy Shairport Sync!
