### ISSUE TITLE
Shairport bypasses audio loopback

### ISSUE THREAD

**Issue by Resaltare** [mikebrady/shairport-sync#249]
Hello,

First, thank you for this amazing project!
I have successfully set up shairport. The audio is sent to the correct audio device. 
Now I want to create a loopback for music visualization.

I have therefore set my .asoundrc as follows:

```
pcm.!default {
  type asym
  playback.pcm "alsa_sink"
  capture.pcm "alsa_monitor"
}
pcm.alsa_sink {
  type plug
  slave {pcm "multi_dev"}
  route_policy "duplicate"
}

pcm.alsa_monitor {
  type plug
  slave {pcm "hw:Loopback,1,0"}
}

pcm.multi_dev {
  type multi

  slaves.a.pcm "hw:0,0" 
  slaves.a.channels 2
  slaves.b.pcm "hw:Loopback,0,0"
  slaves.b.channels 2

  bindings.0.slave a
  bindings.0.channel 0
  bindings.1.slave a
  bindings.1.channel 1
  bindings.2.slave b
  bindings.2.channel 0
  bindings.3.slave b
  bindings.3.channel 1
}
```

This loopback works well with for instance:
`aplay -D default /usr/share/scratch/Media/Sounds/Vocals/Singer1.wav`

But  with "default" set as output device in shairport conf, only the playback will work, not the loopback.
It looks like shaiport is sending audio directly to "hw0:0" and not to the default asym defined in the .asoundrc.

Is there a way to define it as the output device for shairport?

Thank you and congrats again for this amazing piece of code!

**Comment by mikebrady** [comment]
Thanks for the kind words. Would this: https://github.com/mikebrady/shairport-sync/issues/228#issuecomment-193340653 be relevant?

**Comment by Resaltare** [comment]
That was it! Simple but I was starting to pull out my hair! Thank you!!
