### ISSUE TITLE
Problems with sync

### ISSUE THREAD

**Issue by StreamingMeeMee** [mikebrady/shairport-sync#25]
My setup is a bit of an edge case... I'm using MusicBee (v2.4.5404) with the Remote Speakers plugin (http://emilles.dyndns.org/software/out_apx.html) v.  I'm running Shairport-sync on an Ubuntu machine.  The shairport instance appears fine within the plugin but I'm getting this from the plugin:

Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5311.
syncing to seqno 47739.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5124.
syncing to seqno 47978.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5378.
syncing to seqno 48217.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5192.
syncing to seqno 48456.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5416.
syncing to seqno 48695.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5253.
syncing to seqno 48934.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5125.
syncing to seqno 49173.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5284.
syncing to seqno 49412.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5139.
syncing to seqno 49651.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5249.
syncing to seqno 49890.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5108.
syncing to seqno 50129.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5301.
syncing to seqno 50368.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5170.
syncing to seqno 50607.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5407.
syncing to seqno 50846.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5213.
syncing to seqno 51085.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5090.
syncing to seqno 51324.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5279.
syncing to seqno 51563.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5102.
syncing to seqno 51802.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5346.
syncing to seqno 52041.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5208.
syncing to seqno 52280.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5313.
syncing to seqno 52519.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5151.
syncing to seqno 52758.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5376.
syncing to seqno 52997.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5241.
syncing to seqno 53236.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5445.
syncing to seqno 53475.

And it continues ad nasaum.

Help!

Where to begin?

Thanks.

**Comment by StreamingMeeMee** [comment]
BTW, I'm running v2.1.15-openssl-Avahi-ALSA-soxr of Shairport-sync compiled from source.

**Comment by StreamingMeeMee** [comment]
BTW2 - I also get the same results when running iTunes v11.4.0.18 -> shairport-sync machine.

**Comment by StreamingMeeMee** [comment]
Did I mention that my player device had multiple digital outs?  Yeah, turns out that was rather important as when I specified an available output device the problem went away.  DOH!  Sorry for the noise.

Thanks for a great project!

**Comment by mikebrady** [comment]
Thanks for your reports and your interest! So, to clarify, everything works now, right?

The statistics look pretty normal. The ratio of corrections to net correction is very high, but I think it's a feature of non-Apple players – I guess they can't put out timing signals quite as accurately as, say, iTunes can; that's just s guess though.

**Comment by mikebrady** [comment]
By the way, you can turn off the statistics messages – check the man page...

**Comment by StreamingMeeMee** [comment]
Yes, it is working but it is out of sync when using the 'Remote Speakers' MusicBee plug-in.  The sync is fine when using iTunes.

**Comment by mikebrady** [comment]
Shairport Sync always identifies itself as type=analog – this is behavior inherited from Shairport.

How does the plugin identify itself to Shairport Sync (i.e. what follows the "Play connection from...)?

**Comment by StreamingMeeMee** [comment]
Play connection from "Remote Speakers output/4.9 (Windows; N)".

What, if anything, does the 'type' affect?

**Comment by mikebrady** [comment]
TBH, I don't know what the type affects. 
You can change the latency used for Remiote Speakers using the -L option, independently of the iTunes latency.

**Comment by mikebrady** [comment]
Hi there. Not wishing to reopen this or anything, but two things with version 2.6: first, you can set a larger drift window which will make Shairport Sync do less overcorrecting on MusicBee, and second, the range of corrections Shairport Sync can make is greater than it was.
