### ISSUE TITLE
Invalid audio output specified!

### ISSUE THREAD

**Issue by johnpturner8** [mikebrady/shairport-sync#252]
When I run shairport-sync on my raspberry pi I get the message:
`audio outputs:
Invalid audio output specified!`
In shairport-sync.conf output device is set:
`output_device = "(name of card from alsamixer)";`
Does anyone know how to fix this?

**Comment by mikebrady** [comment]
You need to substitute the actual name of the card into that line. So, for example, if you used `alsamixer` and found that the name of the card you wanted to use was `hw:0` then you should edit that entry to read `output_device = "hw:0"`. Then restart Shairport Sync.

**Comment by johnpturner8** [comment]
The card reported by alsamixer is bcm2835 ALSA
In my config file it reads `output device = "bcm2835 ALSA";`
I still get the same error

**Comment by mikebrady** [comment]
Right, I think I see the problem – you need to specify the *device name* rather than the *card name*. So, with `alsamixer`, if you go to the "Select sound card" item and then select "Enter device name..." you'll see it prompting you with the device name for the currently selected card, in my case `hw:0`.

The confusion is caused, I think, from the use of "card name" when "device name" is appropriate. So the *device name* of your card is what's required, not the *card name*.

Did you find the line `output_device = "(name of card from alsamixer)` in some instructions somewhere?

**Comment by johnpturner8** [comment]
I found the device name like you said (mine was also h=0) but I got the same error.
Maybe the wrong config file is being used by shoot port-sync?
(Btw I just assumed that was what it wanted for the device, I didn't get that from instructions.)

**Comment by mikebrady** [comment]
Thanks for the update. Just checking – it's `hw:0` not "h=0" – was that just autocorrect?

**Comment by johnpturner8** [comment]
Yes, I'm not looking at it right now but it think it was hw:0

**Comment by stek29** [comment]
I have same issue, and I found something interesting: There is no Audio outputs available!
```$ shairport-sync -h
•••
Available audio outputs:
$ ```

**Comment by mikebrady** [comment]
Thanks for the report. If there are no available audio outputs in the list from `shairport-sync -h`, it's a sign that the program has not been configured properly before being compiled. You need to ensure that you include the output backend(s) you want.

This is the standard, recommended in the [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md) guide:

```
./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd
```

Notice the `–with-alsa` – that includes the `alsa` back end. This is what you get in the relevant part of the `shairport-sync -h` output:
```
Available audio outputs:
    alsa (default)
```
I hope this helps.

**Comment by stek29** [comment]
Yeah, it helped.
According to readme:
>`--with-alsa` for the ALSA audio back end. **This is required**.

Idk why, but it confused me and I thought that ALSA is enabled by default

**Comment by johnpturner8** [comment]
I just tried this but it did not fix it. I don't have soxr, but I don't think that should be the problem, and I'm not running systemd and set it up with systemv. I still get no outputs available.

**Comment by mikebrady** [comment]
Hi there. Was there any progress on this? Can I close the issue?

**Comment by johnpturner8** [comment]
No, I never did figure this out. I'm going to try reinstalling next.

On Tuesday, May 31, 2016, Mike Brady <notifications@github.com> wrote:

> Hi there. Was there any progress on this? Can I close the issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mikebrady/shairport-sync/issues/252#issuecomment-222664483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AROZRVYeTaoczfiZbTR6b7IlITBEGot6ks5qHB6XgaJpZM4H4gPF>
> .
>


-- 
- John Turner

**Comment by mikebrady** [comment]
Cool. I'd be glad to hear of any development.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
