### ISSUE TITLE
Shairport + firewall issues

### ISSUE THREAD

**Issue by LaTruelle** [mikebrady/shairport-sync#255]
Hi, I am having a strange issue:
- I compiled and installed the latest stable release on a fedora server (latest, up to date)
- Setup shairport with:
```
general =
{
	output_backend = "alsa";
	port = 5000;
 	udp_port_base = 6001; 
	udp_port_range = 3; 
	statistics = "no"; 
	log_verbosity = 3;
	ignore_volume_control = "yes"; 
};
```
- Setup firewalld to accept incoming connections so that streaming works, i.e. opened 5000/tcp 6002/udp 6003/udp 6001/udp.
- Streaming from iTunes on OS X 10.11.4 works, unless I quit iTunes without first disconnecting the shairport server.
- If I quit iTunes or my laptop brutally shuts down network (for example, no battery left), I cannot reconnect to shairport, unless I restart the service.
- If I do this shutting down iTunes / try to reconnect without the firewall there is no problem, however restarting the firewall stops all streaming.

I saw nothing in the logs that looks like a problem. Let me know if I am missing something somewhere, most likely in my firewall configuration, or if ports are not properly used on the shairport side ?

Thanks!

**Comment by mikebrady** [comment]
Thanks for the report. (First, if I were you, I'd turn the log verbosity down to 1 or 2 – sometimes the volume of messages can be very large.)

I don't have experience of using firewalls, TBH, so I'm not sure if i can offer much help.

For some reason, if UDP ports starting at 6001 are unavailable, Shairport Sync will run up to 6199 looking for free ones. What would happen if you opened up ports, say to 6011 and set the port range to 12? I wonder if it would make a difference?

**Comment by LaTruelle** [comment]
Thanks for the indications, yes the verbosity level was merely for debugging to see if something came up.

I tried with 6 open ports and for some reason it works when I quit iTunes while streaming, I can reconnect to the server. However, if network goes down (for example), I do not see anymore the server in iTunes. Could it actually be avahi related ?

Here is the log I could get:

```
Mar 29 17:29:14 backup-server shairport-sync: New RTSP connection on port 5000
Mar 29 17:29:14 backup-server shairport-sync: Play connection from user agent "iTunes/12.3.3 (Macintosh; OS X 10.11.4)".
Mar 29 17:29:14 backup-server shairport-sync: Active-Remote string seen: "2237594945".
Mar 29 17:29:14 backup-server shairport-sync: User-Agent is iTunes 10 or better, (actual version is 12); selecting the iTunes latency of -1 frames.
Mar 29 17:29:14 backup-server shairport-sync: rtp_setup: cport=6001 tport=6002.
Mar 29 17:29:14 backup-server shairport-sync: Connection from IPv4: 192.168.1.10:59370
Mar 29 17:29:14 backup-server shairport-sync: listening for audio, control and timing on ports 6001, 6002, 6003.
Mar 29 17:29:14 backup-server shairport-sync: Audio receiver -- Server RTP thread starting.
Mar 29 17:29:14 backup-server shairport-sync: Control receiver -- Server RTP thread starting.
Mar 29 17:29:14 backup-server shairport-sync: Timing receiver -- Server RTP thread starting.
Mar 29 17:29:14 backup-server shairport-sync: Timing sender thread starting.
Mar 29 17:29:14 backup-server shairport-sync: SET_PARAMETER Content-Type:"text/parameters".
Mar 29 17:29:14 backup-server shairport-sync: received parameters in SET_PARAMETER request.
Mar 29 17:29:14 backup-server shairport-sync: syncing to seqno 3660.
Mar 29 17:29:14 backup-server shairport-sync: SET_PARAMETER Content-Type:"text/parameters".
Mar 29 17:29:14 backup-server shairport-sync: received parameters in SET_PARAMETER request.
Mar 29 17:29:46 backup-server shairport-sync: Sync error: 108.2 (frames); net correction: -674.9 (ppm); corrections: 674.9 (ppm); missing packets 1847; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4449, min and max buffer occupancy 0 and 270.
Mar 29 17:30:16 backup-server shairport-sync: No frames received in the last sampling interval.
Mar 29 17:30:46 backup-server shairport-sync: No frames received in the last sampling interval.
Mar 29 17:31:16 backup-server shairport-sync: No frames received in the last sampling interval.
Mar 29 17:31:30 backup-server shairport-sync: As Yeats almost said, "Too long a silence / can make a stone of the heart"
Mar 29 17:31:30 backup-server shairport-sync: Request to shut down all rtsp conversation threads
Mar 29 17:31:30 backup-server shairport-sync: asking playing threads to stop
Mar 29 17:31:30 backup-server shairport-sync: RTSP shutdown requested.
Mar 29 17:31:30 backup-server shairport-sync: Closing down RTSP conversation thread...
Mar 29 17:31:30 backup-server shairport-sync: Shut down audio, control and timing threads
Mar 29 17:31:30 backup-server shairport-sync: Control RTP thread interrupted. terminating.
Mar 29 17:31:30 backup-server shairport-sync: Audio receiver -- Server RTP thread interrupted. terminating.
Mar 29 17:31:30 backup-server shairport-sync: Timing thread interrupted. terminating.
Mar 29 17:31:30 backup-server shairport-sync: rtp_timing_sender thread interrupted. terminating.
Mar 29 17:31:30 backup-server shairport-sync: Closed and terminated timer requester thread.
Mar 29 17:31:30 backup-server shairport-sync: Timing RTP thread terminated.
Mar 29 17:31:30 backup-server shairport-sync: timing thread joined
Mar 29 17:31:30 backup-server shairport-sync: audio thread joined
Mar 29 17:31:30 backup-server shairport-sync: control thread joined
Mar 29 17:31:30 backup-server shairport-sync: Player thread exit
Mar 29 17:31:30 backup-server shairport-sync: shutting down RTP thread
Mar 29 17:31:30 backup-server shairport-sync: RTSP conversation thread terminated.
```

At the `sync error` part, that's where the laptop stopped streaming. Then, I do not see anymore the server in iTunes unless I restart the service.

**Comment by mikebrady** [comment]
Well, Avahi implements Zeroconf. See https://help.ubuntu.com/community/HowToZeroconf. Avahi has been around a long time, so it's pretty solid and well understood. There is an app for the Mac called Bonjour Browser that allows you to see what's being advertised; it might be useful. At the server end there's `avahi-browse` and friends, part of the `avahi-utils` package.

**Comment by LaTruelle** [comment]
I solved it, it is due to my not opening the port 5353 for avahi. I do not know why it still worked without opening the port but there you go.

Thanks for the help!

**Comment by mikebrady** [comment]
Great.
