### ISSUE TITLE
OpenMediaVault (2.4.1-openssl-Avahi-ALSA) version doesn't support metadata

### ISSUE THREAD

**Issue by effektsvk** [mikebrady/shairport-sync#256]
Hello, I'd like to know, how can I merge OMV build with the one that supports piping the metadata. The reason for it is that I can easily manage it through OMV web interface. Sorry, I'm newbie :smile:

**Comment by mikebrady** [comment]
Thanks for the question, but I'm afraid I'm not familiar enough with OMV to comment on that. It sounds interesting though!

**Comment by effektsvk** [comment]
Damn, I might just use it as a daemon without the webGUI thingy... I'd rather have metadata than fancy switch on web :smile:

**Comment by mikebrady** [comment]
Well, if you can track down whoever added Shairport Sync to OMV, maybe they could be persuaded to update it and compile in metadata support at the same time...

**Comment by effektsvk** [comment]
Hello, so I managed to put everything together (now I have 2.8.1-openssl-Avahi-ALSA-metadata), I set enabled to yes, include_cover_art to yes but I don't get any metadata, it's just empty 0 byte file and when I run shairport-sync-metadata-reader the only output is only when I change volume. How can I solve it?

**Comment by mikebrady** [comment]
The metadata feed passes on metadata received from the client – Music.app / Deezer / iTunes, etc. Older versions of iOS did not provide much, but recent versions, including those on iOS 9.3, provide a good deal, so it looks like you need to update. Also, iTunes provides metadata.

**Comment by effektsvk** [comment]
Hmm, I'm jailbroken that's why I don't update :/ I guess I'll have to wait for the next jailbreak... Do you think it's possible to create an iOS tweak to fix it?

**Comment by mikebrady** [comment]
I don't think it would be easy – maybe if you could update the Music app without updating the OS. OTOH, it seems that none of the audio apps were forwarding much metadata, so it might be an OS thing.

**Comment by effektsvk** [comment]
Yeah, today, I tried it in school with classmate's iPhone 6 (same as mine but he has iOS 9.3) and it was outputting everything, artist, song name, it even wrote that picture was downloaded (not sure how exactly it said, but it was good - couldn't find it tho...) but I only tried Music.app because he doesn't use anything else

**Comment by mikebrady** [comment]
Good. Just FYI, the shairport-sync-metadata-reader program discards the picture data – it doesn't try to do anything with it.

**Comment by mikebrady** [comment]
Okay to close this issue now?

**Comment by effektsvk** [comment]
yeah yea, sorry forgot about it, the final solution would be updating to newer iOS, didn't try it out with iTunes yet, but I'm sure it will work, if I have any other question, I'll reopen/create new issue, thanks a lot for help! :) keep up the awesome work
