### ISSUE TITLE
Hide Shairport-device

### ISSUE THREAD

**Issue by ashwinvandijk** [mikebrady/shairport-sync#261]
I'm working on a multi-room audio solution, using shairport-sync. I would like to connect to a device which forwards the sound to the other devices. Got this working using node_airtunes. I add these device using the IP address, and I never connect to these devices directly from my phone or laptop. I would like to hide these devices from that list. Would it be possible to hide these? I tried to stop the avahi-daemon service manually, but shairport-sync reports that the service fails, and then stops (I think, since I wasn't able to connect to the device using the IP.)

**Comment by mikebrady** [comment]
Hi there. Nobody Has ever asked for this, but it might be useful not to stop advertising the service but to change the type of the service from `raop` to something else. Thus, it would become invisible to AirPlay clients, but visible to other, as yet undefined, clients. For instance it would be open to your multi-room software to discover them automatically itself. Let me have a look...

**Comment by mikebrady** [comment]
I've put up a development version which allows you to change the `regtype`, so you could change it from the standard `_raop._tcp` to, e.g., `_ramp._tcp` – (the `m` is for "multi"). The Shairport Sync device would then not be visible to AirPlay devices but would still be advertising its presence as before to any devices that knew about the new service.

**Comment by ashwinvandijk** [comment]
Hi Mike, that's great! I will pull it in tomorrow and let you know. Thanks!

**Comment by mikebrady** [comment]
Done!
