### ISSUE TITLE
High CPU utilisation due to spinning condition variable

### ISSUE THREAD

**Issue by Celestrion** [mikebrady/shairport-sync#262]
When configured --with-metadata, the condition variable wait on line 215 of rtsp.c returns immediately (on OS X) because neither the mutex nor condition variable was initialized.  Initializing them in pc_queue_init() solves the problem.

**Comment by mikebrady** [comment]
Fixed [thanks] in the development branch.

**Comment by mikebrady** [comment]
Fixed in 2.8.2.
