### ISSUE TITLE
iOS 9.3.1 not work anymore.

### ISSUE THREAD

**Issue by gameboy709494** [mikebrady/shairport-sync#264]
Hey there,

Does anybody upgrade his iPhone to iOS 9.3.1 and shairport-sync not works anymore?

I tested shairport-sync with my another android phone, and shairport-sync works well.

**Comment by mikebrady** [comment]
Hi there. 9.3.1 works with Shairport Sync for me on an iPhone 6.

**Comment by joerg-krause** [comment]
Works for me with iPhone 4s, too.

**Comment by gameboy709494** [comment]
OH, is it possible that it only happen when you're using iPhone 5S with iOS 9.3.1 :joy:?

**Comment by roblan** [comment]
Doubt it ;) It works with mine 5S.

**Comment by mikebrady** [comment]
Yeah, it seems very unlikely that Shairport Sync itself is the problem.

**Comment by gameboy709494** [comment]
Yeah， My android phone works well.

So It might my phone's problem.
