### ISSUE TITLE
Support for multiple network interfaces?

### ISSUE THREAD

**Issue by patrickgh** [mikebrady/shairport-sync#267]
Hi Mike,

first of all: thanks for the great project!

i have 2 wifi adapters attached to my raspberry pi. Is it possible to bind one shairport-sync instance to both networks? At the moment I only see the Airplay Service when i am connected to the first network. 

Or, if thats not possible, can i specify the interface in the config file, so that i can start another instance for the second network? I want to play music from both networks :)

Thanks in advance!

**Comment by mikebrady** [comment]
Thanks for the interesting question, but I'm afraid i don't know the answers!

- When Shairport Sync is connecting back to the source, it asks for the source IP number to be generated automatically. I *think* that ensures that it will pick an IP number appropriate to the destination, which means that it can work with any network.
- Shairport Sync is made visible to AirPlay clients like iTunes using Zeroconf / Bonjour, usually implemented with Avahi. I know Avahi can be programmed to associate with one interface, so you could ensure that Shairport Sync was visible on just one network. I don't think, however, that you could advertise one instance of Shairport Sync on one network and a separate instance on another. Sorry.

Maybe someone else can provide better answers.

**Comment by patrickgh** [comment]
Hi Mike,

thanks for the background informations. After reading some articles about bonjour and avahi i found out my firewall was blocking the discovery in the second network. My bad... now everything works, even with interruption from the other network 👍 

So you are right, shairport does work with any network (tested with both avahi and tinysvcmdns).

Have a nice day!

**Comment by mikebrady** [comment]
Thanks Patrick. I glad it's working out for you.
