### ISSUE TITLE
How to determine image type in PICT metadata payload?

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#268]
Hi Mike,

I'm testing some code that parses out the metadata feed and the docs mention looking at the first few bytes of the PICT payload to determine whether its jpg or png type. 

Are first 2 bytes some sort of id and if so what are the id's?

-Tim

**Comment by mikebrady** [comment]
Hi Tim. As far as I remember, a JPEG is introduced with the letters JFIF in the first 10 or 12 bytes – https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format, and similarly a PNG pict is introduced by the letter PNG in the first few bytes – https://en.wikipedia.org/wiki/Portable_Network_Graphics. You might have to save a few files to be sure, but that's what I remember...

**Comment by mikebrady** [comment]
One thing is that if Shairport Sync is outputting metadata through the pipe and it blocks, it will wait a maximum of five seconds for it to unblock before giving up. Let me know if that becomes a problem.

**Comment by moodeaudio** [comment]
Checking for JFIF and PNG strings in the raw data is good, thanks.

How to determine when all the pipe data is written for a song start/stop/next/prev? Is there an EOF or something similar to check for?

**Comment by mikebrady** [comment]
There are two sets of payload markers. The tokens `mdst` and `mden` precede and follow a set of metadata, and the tokens `pcst` and `pcen` precede and follow a picture. If available, these four tokens will have an `rtptime` number as their payload. (An `rtptime` is basically a 32-bit unsigned number corresponding to the index number of an audio frame.) A further item of metadata – progress – is sent as a `prgr` token with  the starting, current and expected ending `rtptime` of the current selection. This metadata is sent around the time when a track changes, AFAIK. The current `rtptime` given in the progress metadata should match the rtptime fields of the aforementioned four tokens, thus it should be possible to associate the metadata, picture and track change time together, so one should be able to change a display at approximately the same time as the track changes.

**Comment by mikebrady** [comment]
Okay to close this, Tim?

**Comment by moodeaudio** [comment]
Yes it should be closed.

**Comment by mikebrady** [comment]
Okay, thanks.
