### ISSUE TITLE
avahi_entry_group_add_service_strlst: Assertion `type' failed.

### ISSUE THREAD

**Issue by ralph-irving** [mikebrady/shairport-sync#275]
V2.8.2 exits with the following error from avahi 0.6.32 and avahi 0.6.31 before startup.

./shairport-sync --version
2.8.2-openssl-Avahi-ALSA-soxr

./shairport-sync -a IQaudIODAC -o alsa -S soxr -D -R -- -d hw:CARD=IQaudIODAC
shairport-sync: entrygroup.c:423: avahi_entry_group_add_service_strlst: Assertion `type' failed.
Aborted

The crash with shairport-sync 2.8.2 is 100% repeatable on raspbian 7.8 and wheezy 7.10 i386.

V2.8.1 works fine with both avahi versions on both wheezy platforms.

**Comment by mikebrady** [comment]
Thanks. It'll be a few days before I can check this.

**Comment by mikebrady** [comment]
I can reproduce this fault alright. Let me see what's happening.

**Comment by mikebrady** [comment]
I think I found the bug.

**Comment by mikebrady** [comment]
Hi there. I think I've fixed it and pushed out the fix in Version 2.8.3. Would you be kind enough to try it please? If it's okay, I'll remove the "pre-release" tag.

**Comment by ralph-irving** [comment]
V2.8.3 is working fine on both systems.

Thank you Mike.
