### ISSUE TITLE
Floating Point Optimization

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#278]
Currently, shairport-sync uses double precision floating point for some variables. Depending on the hardware, there is a significant performance penalty when using double precision.

I wonder if double precision is really necessary for these variables or if single precision is sufficient?

**Comment by mikebrady** [comment]
Hi Jörg-Krause. Could you be a bit more specific about where these uses are please?

**Comment by joerg-krause** [comment]
Of course! Sorry if I was not clear enough:

double precision floating point -> `double`
single precision floating point -> `float`

For example in `player_thread_func`: https://github.com/mikebrady/shairport-sync/blob/development/player.c#L1292-L1296 or in `vol2attn`: https://github.com/mikebrady/shairport-sync/blob/development/common.c#L420-L457.

**Comment by mikebrady** [comment]
Yeah, I see that alright, but do you think it'll make much of a difference? Those calculations would be done once every 8 milliseconds or so...

**Comment by joerg-krause** [comment]
At least, for my ARMv5TE soft-float target, binary (statically build) size is reduced by 80 bytes when replacing all doubles by floats:

```
   text	   data	    bss	    dec	    hex	filename
 918104	   9608	  42176	 969888	  ecca0	./shairport-sync_float
 918168	   9608	  42192	 969968	  eccf0	./shairport-sync_double
```

However, I think you're right. The benefit is only marginal and it's not worth it.
