### ISSUE TITLE
Connection time, half a minute

### ISSUE THREAD

**Issue by cgrossde** [mikebrady/shairport-sync#28]
Not sure if this is a bug or by design. After selecting the shairport-server in iTunes(Mac OS X latest) it takes almost half a minute until it starts playing. Is there a way to speed things up?

I'm running shairport on an ubuntu 14.04 box with ALSA.

**Comment by mikebrady** [comment]
Seems to be something to do with recent iTunes. It's the same for me, and happens when the output devices are Airport Expresses and Apple TVs too...
