### ISSUE TITLE
No audio with Omxplayer

### ISSUE THREAD

**Issue by shandoosheri** [mikebrady/shairport-sync#285]
Hi after installing shairport I can connect just fine but there is no audio output. I wanted to use the hdmi on the raspberry pi so I used hw:0,1 as output device. The strange thing is that if I play anything using omxplayer and then start streaming audio wil work for the 2 sources at the same time. But if I start streaming first then there would be no audio and even omxplayer wouldn't work after that and I would have to reboot just to get omxplayer working

Thank you in advance for helping me to tackle this strange problem.

**Comment by mikebrady** [comment]
Thanks for the report. I've never used Omxplayer, but I see that it uses hardware acceleration for video and audio – see http://elinux.org/Omxplayer. Therefore, I can't help thinking that the problem may be caused by some interaction between Omxplayer and the `alsa` subsystem upon which Shairport Sync relies.

So, the first thing I would suggest is to install Shairport Sync on a stock Raspbian image, configure it to use the `cdmi` output and check that everything is working.

**Comment by shandoosheri** [comment]
Hey thanks for the reply. I am in fact using a stock raspbian image just made a fresh install too. Omxplayer is preinstalled. And my problem isn't with omxplayer at all I don't even use it. The problem is with shairport that I can't get it to output audio. Doesn't shairport produce a log somewhere that I can look at

**Comment by mikebrady** [comment]
Omxplayer is not present in the stock Raspbian image, so could you just clarify what you're written?

**Comment by shandoosheri** [comment]
I am running rasbiam jessie the normal version not the lite one. And it comes with omxplayer. The thing is when i use the headphone port on the pu and set shairport to hw:0,0 it works well on the headphone port but not on hdmi

**Comment by mikebrady** [comment]
Many thanks. Let me check this out. It's useful to know that it's working alright on the headphone jack.

**Comment by shandoosheri** [comment]
ok, i really dont know what i did wrong along the way. but, i made a new fresh install. with everything the same except this time i didnt use rpi-update. everything is working perfectly now. thank you for your replies and help. its really appreciated and a million thanks for the awesome software

**Comment by mikebrady** [comment]
Thanks for the update. TBH, I've stopped using rpi-update – see, for example, https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=139932.
