### ISSUE TITLE
Raspberry Pi3: Sound stutters when metadata is enabled

### ISSUE THREAD

**Issue by elParaguayo** [mikebrady/shairport-sync#286]
When I use shairport-sync on my Pi3 it plays really nicely (thank you). However, if I try to enable the metadata option (via the conf file) then the sound is really stuttery and completely unlistenable.

Apologies, I've given you very little to work with there. Is there any way I can provide a more meaningful output to help debug this?

I could well be doing something wrong but I thought I'd report just in case!

**Comment by mikebrady** [comment]
Thanks for the report. Could you tell me if you're using any program to "listen" to the metadata?
Perhaps you could tell me what you've done altogether – it would be very useful.

**Comment by elParaguayo** [comment]
I followed the instructions in the readme (my line was: `./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd`). I then enabled the metadata option via the conf file.
I was just listening with `cat` for the time being but it was stuttering even before I tried reading the pipe.

**Comment by mikebrady** [comment]
Thanks. Let me see if I can replicate this. It seems odd :)

**Comment by elParaguayo** [comment]
It could well be me so don't be afraid to tell me I'm being an idiot!

**Comment by mikebrady** [comment]
Don't worry :) I've just checked this on a Pi3. Shairport Sync is installed and running as a service, and it's running smoothly. Are you running Shairport Sync like that, and have you defined the user and group `shairport-sync`. Also, I'm running it over `ssh` – no GUI, though it shouldn't matter.

**Comment by elParaguayo** [comment]
Running as a service: Yes - via systemd.
User and group: Yes, I ran these commands:
`$getent group shairport-sync &>/dev/null || sudo groupadd -r shairport-sync >/dev/null
$getent passwd shairport-sync &> /dev/null || sudo useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null`
I'm also running via SSH.

I've also got bluetooth and mpd running - let me see if disabling both of those has any impact.

**Comment by elParaguayo** [comment]
Weird. Working now. I disabled bluetooth and mpd. Played music via iPhone and it played with no stutter. Tried restarting mpd and it wouldn't (said it couldn't bind to port "6600"). Changed the port in the mpd config, restarted mpd and everything's good.

Thanks for the quick replies. Good to close this thread I think.

**Comment by mikebrady** [comment]
A mystery, but a least it has a good ending!
