### ISSUE TITLE
ALSA underrun with shairport-sync running in VMWare Workstation

### ISSUE THREAD

**Issue by ejurgensen** [mikebrady/shairport-sync#287]
While testing issue #254 and the current development branch, I got lots of underruns. This was independent on which client I used (tried with forked-daapd, iPad and iPhone). Here is a snippet of the debug output:
```
PCM handle name = 'default'
alsa device parameters:
  access type = RW_INTERLEAVED
  format = 'S16_LE' (Signed 16 bit Little Endian)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 16
  rate = 44100 frames per second (precisely).
  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
  period_time = 23219 us (>).
  period_size = 1024 frames (precisely).
  buffer_time = 23777233 us (>).
  buffer_size = 1048576 frames (>).
  periods_per_buffer = 1024 (precisely).
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -4913.
Flush requested up to 3372260199. It seems as if 0 is special.
syncing to seqno 11510.
    CSeq: 6.
    X-Apple-Device-ID: 0x3010e4a8df60.
    DACP-ID: 6E4A98FC3D76E908.
    Active-Remote: 4225519050.
    User-Agent: AirPlay/200.54.
Error -- ALSA device in incorrect state (4) for play.
Error -- ALSA device in incorrect state (4) for play.
    CSeq: 7.
    X-Apple-Device-ID: 0x3010e4a8df60.
    DACP-ID: 6E4A98FC3D76E908.
    Active-Remote: 4225519050.
    User-Agent: AirPlay/200.54.
Error -- ALSA device in incorrect state (4) for play.
Error -- ALSA device in incorrect state (4) for play.
Error -- ALSA device in incorrect state (4) for play.
(and so on)

```

Working with forked-daapd, I have fought a great deal with ALSA myself. I also saw lots of underruns, and I came to the conclusion that part of the cause is that I do my development in a VM where ALSA seems to have some oddities. However, I didn't feel like I could ignore the problems, since sound otherwise worked fine in the VM, and since I couldn't rule out that the same oddities wouldn't exist in other setups.

So one thing I found out during my work is that if ALSA underruns and you run snd_pcm_prepare (like in your audio_alsa.c) then there is a high risk that it will just underrun again when you feed it a normal AirTunes packet in the next write. Instead, you must make sure to first collect a decent amount of audio, and then restart audio with a large write. That will refill the buffer properly and prevent an immediate underrun.

I haven't looked into how shairport-sync does sync, or how it buffers, so of course I don't know if that is an option for you.

**Comment by mikebrady** [comment]
Thanks for this. I similarly have been developing on VMWare Funion on a Mac, and while there are occasional underruns, particularly when switching VMWare to the foreground, it has not been a big problem. I try to keep the buffer as small as possible too, which leaves less room for compensating for run-time disturbances.
There are definitely issues with the emulation of the audio cards, of the order of tens of milliseconds, so definitely audible, but all in all it's great. For definitive testing, I move to real machines like Raspberry Pis, C.H.I.P.s and so on.

**Comment by ejurgensen** [comment]
Ok, just wanted to let you know about the issue, and also about the possible way of getting out of a repeated underrun scenario.

**Comment by mikebrady** [comment]
Thanks again – I appreciate it.
