### ISSUE TITLE
shairport sync as incognito mode, how?

### ISSUE THREAD

**Issue by JavierJames** [mikebrady/shairport-sync#288]
is there a way to have shairport-sync on a devices like raspberry pi. and have one raspberry pi 1 stream music in sync to the raspberry 2 + raspberry 3 + raspberry 4 ? Without raspberry 2 , raspberry 3, and raspberry 4 being visible to other airplay devices and visible to raspberry 1?   And can this be done having everything still in sync?

**Comment by mikebrady** [comment]
Hi Javier. Nice idea, but I'm afraid the functionality is not there. I think something like it could be done in principle, but Shairport Sync doesn't have the functionality.

**Comment by JavierJames** [comment]
Dear Mike,

Thank you for your quick response and the information.



Have a great day
