### ISSUE TITLE
Skipping the start of songs

### ISSUE THREAD

**Issue by JamieBriers** [mikebrady/shairport-sync#289]
Hi, I finally got this working on an Ubuntu home server after a few hours of tinkering.  I have noticed that the stream appears to cut off between songs, and start back up again, which is causing the start of songs to sometimes get missed, whilst the connection fires up. 

I am currently developing a home network of speakers connected to Pi (running a MusicBox image) and none of them are experiencing this.  Is there anything I can do to debug the issue?

Thanks

**Comment by mikebrady** [comment]
Hi Jamie. Thanks for the post. These gaps you are experiencing are unusual. Where is your music coming from? Is there anything unusual about your network or general setup?

**Comment by JamieBriers** [comment]
Hi

Music is coming from a Mac running iTunes, which is wired to a switch, which is where the Linux server is  attached as well.  I have a Pi with a wireless card running MusicBox, which this doesn't seem to occur on, although I am currently trying to verify this.  It doesn't happen every song, and of course its more noticeable on songs where the music is louder from the first moment.

Hazarding a guess, its almost as if the stream stops, and has to be re connected.  I sometimes get a similar delay in all devices, if I pause and play a song.

**Comment by mikebrady** [comment]
Thanks. From iTunes, there should be no gap at all. My experience on a similar setup is that there aren't gaps, so it might need further investigation. If you could put Shairport Sync on that Pi and see what happens, if might help identify where there might be a problem.

**Comment by JamieBriers** [comment]
Ive spent today trying to pay close attention to it, and its seemed pretty stable. 

Since yesterday I have rebooted the server, Mac and router. 

ill let you know if I experience any more issues and if i can pinpoint how to reproduce. 

Cheers for the nice fork of shairport anyways. Im almost there with my 'sound around the flat' project!

**Comment by mikebrady** [comment]
Cool!

**Comment by mikebrady** [comment]
I'm going to close this, if that's okay. Feel free to reopen it if necessary.
