### ISSUE TITLE
Airplay device discovery wifi vs. wired

### ISSUE THREAD

**Issue by photopsy** [mikebrady/shairport-sync#29]
On a Raspberry Pi running shairport-sync on archlinux arm, I have a this problem: When the raspi is connected via wifi, airplay from a mac computer and from an iphone (both on wifi) works nicely -- but the device is only discovered reliably once, when shairport-sync is started. If the mac or the iphone are then dis- and reconnected from the wifi, they don't always show the airplay device again... only sometimes, it behaves a little strange and I couldn't work out what exactly is needed to reproduce. Doesn't look like a timeout either. Strangely, when the raspi is connected via ethernet, everything works like a charm, the airplay device always getting listed immediately.
I couldn't make out whether the problem is located in my router, in the network configuration, the avahi configuration or shairport, so any pointers would be greatly appreciated ;) 

```bash
# shairport-sync -V
2.1.15-openssl-Avahi-ALSA-soxr
```
startup:
```bash
shairport-sync -a RPI --statistics -v -S soxr -t 20 -- -d hw:1 -t hardware -c PCM
```
```
Jan 04 22:20:48 alarmpi systemd[1]: Starting ShairportSync AirTunes receiver...
Jan 04 22:20:48 alarmpi systemd[1]: Started ShairportSync AirTunes receiver.
Jan 04 22:20:49 alarmpi shairport-sync[131]: Hardware mixer has dB volume from -128.000000 to 0.000000.
Jan 04 22:20:49 alarmpi shairport-sync[131]: Has mute ability.
Jan 04 22:20:49 alarmpi shairport-sync[131]: startup
Jan 04 22:20:49 alarmpi shairport-sync[131]: avahi: avahi_register.
Jan 04 22:20:49 alarmpi shairport-sync[131]: avahi: register_service.
```

In any case, the syncing works absolutely great, thanks for this project!

**Comment by mikebrady** [comment]
Thanks for the report. Some WiFi adapters have a power management / power saving mode that can cause problems.  It would be worth turning it off, to see if it fixes the issues you mention. I'm away from computers now, so can't offer guidance, but standard wifi command line tools like iw etc. allow you to get and set power saving mode.

**Comment by photopsy** [comment]
Thanks! Seems powersave and usb autosuspend was exactly the issue... see https://github.com/xbianonpi/xbian/issues/217 for the fix.

**Comment by mikebrady** [comment]
Good stuff.

**Comment by webattitude** [comment]
Hello.
Weird enough, airplay is working on my macbook on yosemite 10.10.5 with itunes but not with the system sound control...
I've tried to set up my airplay receiver (which is squeezeplug on raspberrypi model b+) with shairtunes2 and shairport.
Maybe I should replace shairport by shairport-sync in squeezeplug, do you know how I should do that ?
