### ISSUE TITLE
Segmentation fault when "ignore_volume_control = "yes";"

### ISSUE THREAD

**Issue by russwyte** [mikebrady/shairport-sync#291]
Happens in current master and development branches.

I also get occasional segfaults when start playing music even when "ignore_volume_control = "no";", but I always get one with "yes".

My setup is pretty basic - I am using a USB DAC (Amanero)
alsa =
{
        output_device = "plughw:Amanero";
};

**Comment by russwyte** [comment]
Sorry I meant to mention I am running on an rpi3.
Linux raspberrypi 4.4.8-v7+ #881 SMP Sat Apr 30 12:16:50 BST 2016 armv7l GNU/Linux

**Comment by mikebrady** [comment]
Thanks for the report. I'll check it out. Can you post the active parts of your config file please?

**Comment by russwyte** [comment]
Glad to do it. Thanks.

general =
{
        name = "Russ Pi"; 
        interpolation = "soxr";
        output_backend = "alsa";
        mdns_backend = "avahi";
        ignore_volume_control = "yes"; 
};
alsa =
{
        output_device = "plughw:Amanero";
};

that's it

and I compiled with these options:

./configure --with-alsa --with-avahi --with-ssl=openssl --with-soxr --with-systemd

**Comment by mikebrady** [comment]
Thanks. I'll have a look.

**Comment by mikebrady** [comment]
As a matter of interest, what happens if you direct the output directly to the hardware device, e.g. something like `hw:1` – `alsamixer` will tell you what the correct device number is...

**Comment by russwyte** [comment]
I have to use plughw because I have to rate convert from 16bit to 32bit words. So if I do as you suggest it always fails because my DAC does not support 16bit words.

**Comment by russwyte** [comment]
On that subject - it would be pretty cool to be able to go out to hw:1 directly - because I want to go direct without any plugins. Why not allow an alsa option to pad to 24, and 32bit samples? It is just a matter of zero stuffing.

**Comment by mikebrady** [comment]
It would be nice alright – it's on the list!

**Comment by mikebrady** [comment]
Just looking at your version of Linux. Where are you getting that from please? 
Mine reads `Linux raspberrypi3 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux`...

**Comment by russwyte** [comment]
uname -a

have you done rpi-update recently?

**Comment by mikebrady** [comment]
Thanks, yeah, I stopped using it when it was no longer bundled into the distribution. I'll give it a try again.

**Comment by mikebrady** [comment]
I wonder if your problem is the same as reported (and possibly fixed) in #282? Would you be kind enough  to try the latest release – 2.8.3.5 – please?

**Comment by russwyte** [comment]
I tried it - and no segfault! 

Nice! You seem to have fixed it. Thank you very much.

**Comment by mikebrady** [comment]
Super, thanks. I'll fix it up nice and make it a full release soon. 

BTW thanks for the reminder about `rpi-update`; I used it and was surprised to find that it didn't wreck anything!

**Comment by mikebrady** [comment]
Fixed in 2.8.4.
