### ISSUE TITLE
Android MIUI OS music player wont start playback

### ISSUE THREAD

**Issue by brbrr** [mikebrady/shairport-sync#297]
MIUI music player (could be found [here](http://en.miui.com/thread-65547-1-1.html)) have functioanlity to cast to external devices such as bluetooth and airplay. So it sees my shairport on rpi.

But once selected - there is no output at all. And song is not played. looks like it stuck in connection phase

with statistics verbosity = 3
```
May 11 22:42:17 raspberrypi shairport-sync[11579]: one thread joined...
May 11 22:42:17 raspberrypi shairport-sync[11579]: New RTSP connection on port 5000
May 11 22:42:22 raspberrypi shairport-sync[11579]: CSeq: 1.
May 11 22:42:22 raspberrypi shairport-sync[11579]: Session: 1.
May 11 22:42:22 raspberrypi shairport-sync[11579]: RTP-Info: seq=4847;rtptime=28300015.
May 11 22:42:22 raspberrypi shairport-sync[11579]: User-Agent: iTunes/9.2.1 (Macintosh; Intel Mac OS X 10.5.8) AppleWebKit/533..
May 11 22:42:22 raspberrypi shairport-sync[11579]: Client-Instance: ABCDEFABCDEF1234.
May 11 22:42:22 raspberrypi shairport-sync[11579]: DACP-ID: ABCDEFABCDEF1234.
May 11 22:42:22 raspberrypi shairport-sync[11579]: Active-Remote: 2706855.
 -> May 11 22:42:22 raspberrypi shairport-sync[11579]: This RTSP conversation thread doesn't think it's playing, but it's sending a response to flush anyway
May 11 22:42:22 raspberrypi shairport-sync[11579]: Flush requested up to 28300015. It seems as if 0 is special.
```

-> happen when pause/play pressed

**Comment by mikebrady** [comment]
Hmm. I don't have an android phone, so it might take a while to check this out. Is what's on the log absolutely everything?

**Comment by mikebrady** [comment]
I don't think I'm going to be able to test this. Shairport Sync does run with other Android players, such as "AllConnect".

**Comment by brbrr** [comment]
sorry for late answer. It's definitely issue with app, or with way it's connects to airplay.

**Comment by mikebrady** [comment]
Thanks for the update. Please let us know if there are any development.
