### ISSUE TITLE
Cannot play sound to Bose Companion 5 (USB port)

### ISSUE THREAD

**Issue by thanhnha0706** [mikebrady/shairport-sync#298]
Hi,
I have installed customized Padavan firmware with this great AirPlay simulator. My purpose is to play sound from my Macbook to my Bose Companion 5 through Airplay. Everything is good, the AirPlay icon does appear on my iPhone. But when i selected it and played music, I hear nothing coming out from my speakers. Please take a look at the system logs.
[syslog.txt](https://github.com/mikebrady/shairport-sync/files/265058/syslog-3.txt)

**Comment by mikebrady** [comment]
Is it okay?

**Comment by thanhnha0706** [comment]
@mikebrady No, it's not! I have opened another thread for this!
