### ISSUE TITLE
Cannot play sound to Bose Companion 5 (USB port)

### ISSUE THREAD

**Issue by thanhnha0706** [mikebrady/shairport-sync#299]
Hi @mikebrady,
I have installed customized Padavan firmware with this great AirPlay simulator. My purpose is to play sound from my Macbook to my Bose Companion 5 through Airplay. Everything is good, the AirPlay icon does appear on my iPhone. But when i selected it and played music, I hear nothing coming out from my speakers. Please take a look at the system logs.
 [syslog.txt](https://github.com/mikebrady/shairport-sync/files/265061/syslog-3.txt)

**Comment by mikebrady** [comment]
Thanks for the report. I notice that at 16:32:37 the log says that an audio device cannot be found for Shairport Sync. That needs to be investigated. If the sound device really appears (use `alsamixer` or similar to check), then Shairport Sync is maybe being started too early in the boot sequence.

**Comment by thanhnha0706** [comment]
But then I unplugged and plugged the speakers again after Shairport had loaded. The result is the same, which I cannot hear any sound even I volume up and down. I notice this error message everytime I play music: "cannot get freq at ep 0x1".

**Comment by alexzautke** [comment]
Hi there, I'm also running shairport-snyc with the Bose Companion 5 speakers. Unfortunately, there is a kernel bug which results in the error message "cannot get freq at ep 0x1". It appears that the problem is, that the Companion 5 speakers only have a USB 1.1 port. In order to get a reliable output USB 2.0 is needed. The trick is connecting the speakers via USB to your device (this disables the automatic power saving mode) AND connect and play the audio via the line-in port. I hope it helps!

**Comment by mikebrady** [comment]
Can you post the configuration file settings that are not commented out, please?

**Comment by thanhnha0706** [comment]
As far as I know Bose USB port is 2.0, not 1.1 like you said.

**Comment by alexzautke** [comment]
You can output the USB version with lsusb -v (look for the bcdUSB field) or cat /sys/kernel/debug/usb/devices. My speakers report a USB 1 connection.

**Comment by mikebrady** [comment]
Thanks for the settings. I notice a couple of things. 

First, you have not set up Shairport Sync to control the volume on the output device. Instead, Shairport Sync will attenuate the volume of the audio as it passes through it in software and then pass it on to the output device. However, the output level of the output device could be anything – it could even be zero! You will have to use some other program to set the output volume on the output device to 100%. I suggest looking at it with `alsamixer` and modifying it with `amixer`.

Second, you are transcoding from 44.1 kHz to 48 kHz using a `plugin`. Two things about that – one is, I don't know if it works properly in terms of synchronisation; I've never actually looked, so let's say it's "unsupported" – other users might have experience. But the other thing is that it takes considerable CPU power. My guess is that your device doesn't have enough horsepower to keep up. You can sort-of check using the `top` utility, or similar, while it's running.

Third, it does indeed look like the output device is being treated as a USB 1 device, but it actually doesn't really matter – it's not uncommon. The real issues are the output level control and, possibly, the CPU horsepower needed to to the transcoding.

**Comment by thanhnha0706** [comment]
Firstly, I noticed that when I played and controlled the volume to max level, I got the logs like this
```
May 16 21:51:05 shairport-sync[494]: New RTSP connection on port 5000
May 16 21:51:05 shairport-sync[494]: Play connection from user agent "AirPlay/250.20".
May 16 21:51:06 shairport-sync[494]: Active-Remote string seen: "1034683066".
May 16 21:51:06 shairport-sync[494]: User-Agent is AirPlay; selecting the AirPlay latency of -1 frames.
May 16 21:51:06 shairport-sync[494]: rtp_setup: cport=51800 tport=56517.
May 16 21:51:06 shairport-sync[494]: Connection from IPv4: 192.168.1.186:53245
May 16 21:51:06 shairport-sync[494]: listening for audio, control and timing on ports 6001, 6002, 6003.
May 16 21:51:06 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:06 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:06 shairport-sync[494]: volume: -18.750000
May 16 21:51:06 shairport-sync[494]: syncing to seqno 22009.
May 16 21:51:06 kernel: 3:1:1: cannot get freq at ep 0x1
May 16 21:51:26 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:26 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:26 shairport-sync[494]: volume: -16.875000
May 16 21:51:26 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:26 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:26 shairport-sync[494]: volume: -15.000000
May 16 21:51:27 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:27 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:27 shairport-sync[494]: volume: -13.125000
May 16 21:51:27 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:27 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:27 shairport-sync[494]: volume: -11.250000
May 16 21:51:27 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:27 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:27 shairport-sync[494]: volume: -9.375000
May 16 21:51:27 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:27 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:27 shairport-sync[494]: volume: -7.500000
May 16 21:51:27 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:27 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:27 shairport-sync[494]: volume: -5.625000
May 16 21:51:31 shairport-sync[494]: SET_PARAMETER Content-Type:"text/parameters".
May 16 21:51:31 shairport-sync[494]: received parameters in SET_PARAMETER request.
May 16 21:51:31 shairport-sync[494]: volume: -3.750000
```
The volume output got the maximum value at 0.0000. I don't know how to control or modify the volume output. Please show me!

Secondly, I think there is no problem about the transcoding because I've commented it out. Thus, it does not transcode anything as you can see from the code that I chose to directly output the sound.

**Comment by mikebrady** [comment]
Yes, the `volume` is actually a parameter send by the client's volume control and it ranges from `0` to `-30` with `-144` meaning "mute". Thus `0` is the highest volume. If the volume is set to `0`, it means that the audio is being sent through Shairport Sync at full volume. The thing is, you have not set up Shairport Sync to control the output device's volume in hardware. To do that – and I recommend that you should – please consult the `README.md` for instructions. 

BTW, I can not see from the log that you are going directly to the output – that information is missing.

Otherwise it's looking good.

**Comment by thanhnha0706** [comment]
Hi all, 

It's been busy for me for a while. I just want to confirm that everything now works perfectly as expected. 

Thank you very much for spending time to support my problem. :))
