### ISSUE TITLE
24/96kHz support

### ISSUE THREAD

**Issue by skuligowski** [mikebrady/shairport-sync#30]
Hi Mike,

I have IQAudio Pi-DAC+ which supports 24/96kHz audio. Is it possible to configure the shaiport-sync that it can use this high quality settings? Now the airplay port is seen by all devices as 16bit/44kHz output device.

Thanks for the response and keep up that great work!

**Comment by mikebrady** [comment]
Hi there. I have a Pi-DAC myself and it is impressive, indeed. I don't have plans for support of different sample rates or depths. The ALAC to PCM decoder in Shairport Sync is set to 44.1/16 though apparently changeable in principle. It's not clear to me what benefits transcoding in software would bring. If Apple moved to different rates, of course, that would be interesting.

**Comment by stigger** [comment]
Apparently, Apple supports 96/24: https://discussions.apple.com/thread/2630381

**Comment by mikebrady** [comment]
Thanks for that. I had a look, and it seems that they only support 44.1/16 over AirPlay at present. Is that a fair reading of it?

**Comment by stigger** [comment]
Sorry, was too excited by one of the first replies and did not read carefully the rest :(. You are right, 44.1/16 it is.

**Comment by bob808** [comment]
Hi Mike,
Any chance on getting shairport-sync to run on more than 16bit/44.1KHz?
Looking for 24/96 tbh. 24 x 96000 x 2channels = 4.6Mbps so a modern N band wifi setup should work.
Is it too hard to do? I presume there are lots of people that would love this feature.

**Comment by mikebrady** [comment]
Hi there. It seems that all sources are converted to 44.1/16 before being sent to an AirPlay device, so there doesn't really seem to be much reason to got to 24 bit or 96k as shairport sync would be doing the conversion. Of course, Apple might introduce a different standard – there doesn't seem to be a technical reason why not. But until they do, there really doesn't seem to be any point.

**Comment by qerub** [comment]
@mikebrady: One reason I can see for going 24 bit is that it would give Shairport's software volume control more headroom allowing users to lower the volume without any significant degradation of the output signal.

**Comment by mikebrady** [comment]
I completely agree, and it's especially true when yo add in dither! I'm trying to figure out how to do a general solution, including 32 bit and proper endianness.

**Comment by qerub** [comment]
@mikebrady: Excellent!

By the way: Please consider accepting donations for shairport-sync (through PayPal or similar); I believe we're many who really appreciate your work.

**Comment by bob808** [comment]
I'd chip in a few beers, yes.
