### ISSUE TITLE
Airplay doesn't work but are shown as a device

### ISSUE THREAD

**Issue by faderullan** [mikebrady/shairport-sync#301]
Hello!

Thanks for a nice product!

I have an annoying problem with my 2 setups with shairport-sync. One rpi2 and one rpi3 is used. The rpi2 is connected via cable and the rpi3 via wifi. Both rpi's have a hifiberry dac+ onboard. The distro i use is raspbian lite from the hifiberry homepage. I used their installer to get the card to work out of the box. This worked just fine.

The rpi2 box works great with airplay but the rpi3 does not. I see it as an audio device (using iPhone and spotify) but when i select the device it takes a few seconds and nothing happens. It goes back to the default output (which in this case is the iPhone speaker).

Using 2.8.3-openssl-Avahi-ALSA-soxr-metadata.

Do you have any idea why this happens? I'm not sure how to debug this problem.

Thanks in advance!

/Mattias

**Comment by mikebrady** [comment]
Hi Mattias. Thanks for the post and the kind words.

On the Raspberry Pi 3 – the problematic one – if you could change the Shairport Sync configuration settings by setting the `log_verbosity` to 1 or 2 (not 3 – it's not very useful for this).

This will cause Shairport Sync to record some information in the system log. You can check the log using `sudo journalctl  -n 1000` or similar. Then post the relevant log here – that would be useful.

**Comment by faderullan** [comment]
Hello again!

As I'm not at home i can't connect with an airplay device. But i changed the log verbosity to 2 and restarted the service. This is the first output i get. When i get home from work i can also try connect to it with my iPhone.

May 18 14:13:28 musicboxk systemd[1]: Starting ShairportSync AirTunes receiver...
May 18 14:13:28 musicboxk systemd[1]: Started ShairportSync AirTunes receiver.
May 18 14:13:28 musicboxk shairport-sync[16630]: Output device name is "hw:0".
May 18 14:13:28 musicboxk shairport-sync[16630]: Open Mixer
May 18 14:13:28 musicboxk shairport-sync[16630]: Lowest dB value is a mute.
May 18 14:13:28 musicboxk shairport-sync[16630]: Can't get dB value corresponding to a "volume" of 1.
May 18 14:13:28 musicboxk shairport-sync[16630]: Hardware mixer has dB volume from -103.000000 to 0.000000.
May 18 14:13:28 musicboxk shairport-sync[16630]: Has mute ability.
May 18 14:13:28 musicboxk shairport-sync[16630]: The processor is running little-endian.
May 18 14:13:28 musicboxk shairport-sync[16630]: Version: "2.8.3-openssl-Avahi-ALSA-soxr-metadata"
May 18 14:13:28 musicboxk shairport-sync[16630]: statistics_requester status is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: daemon status is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: rtsp listening port is 5000.
May 18 14:13:28 musicboxk shairport-sync[16630]: udp base port is 6001.
May 18 14:13:28 musicboxk shairport-sync[16630]: udp port range is 100.
May 18 14:13:28 musicboxk shairport-sync[16630]: Shairport Sync player name is "musicboxk".
May 18 14:13:28 musicboxk shairport-sync[16630]: Audio Output name is "alsa".
May 18 14:13:28 musicboxk shairport-sync[16630]: on-start action is "(null)".
May 18 14:13:28 musicboxk shairport-sync[16630]: on-stop action is "(null)".
May 18 14:13:28 musicboxk shairport-sync[16630]: wait-cmd status is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: mdns backend "avahi".
May 18 14:13:28 musicboxk shairport-sync[16630]: userSuppliedLatency is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: AirPlayLatency is -1.
May 18 14:13:28 musicboxk shairport-sync[16630]: iTunesLatency is -1.
May 18 14:13:28 musicboxk shairport-sync[16630]: forkedDaapdLatency is -1.
May 18 14:13:28 musicboxk shairport-sync[16630]: stuffing option is "0".
May 18 14:13:28 musicboxk shairport-sync[16630]: resync time is 2205.
May 18 14:13:28 musicboxk shairport-sync[16630]: allow a session to be interrupted: 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: busy timeout time is 120.
May 18 14:13:28 musicboxk shairport-sync[16630]: drift tolerance is 88 frames.
May 18 14:13:28 musicboxk shairport-sync[16630]: password is "(null)".
May 18 14:13:28 musicboxk shairport-sync[16630]: ignore_volume_control is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: disable_synchronization is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: audio backend desired buffer length is 6615.
May 18 14:13:28 musicboxk shairport-sync[16630]: audio backend latency offset is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: volume range in dB (zero means use the range specified by the mixer): 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: zeroconf regtype is "_raop._tcp".
May 18 14:13:28 musicboxk shairport-sync[16630]: configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
May 18 14:13:28 musicboxk shairport-sync[16630]: metdata enabled is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: metadata pipename is "/tmp/shairport-sync-metadata".
May 18 14:13:28 musicboxk shairport-sync[16630]: get-coverart is 0.
May 18 14:13:28 musicboxk shairport-sync[16630]: avahi: avahi_register.
May 18 14:13:28 musicboxk shairport-sync[16630]: avahi: register_service.
May 18 14:13:28 musicboxk shairport-sync[16630]: avahi: service 'B177BEB4E80C@musicboxk' group is not yet commited.
May 18 14:13:28 musicboxk shairport-sync[16630]: avahi: request to add "_raop._tcp" service without metadata
May 18 14:13:28 musicboxk shairport-sync[16630]: avahi: service 'B177BEB4E80C@musicboxk' group is registering.
May 18 14:13:29 musicboxk shairport-sync[16630]: avahi: service 'B177BEB4E80C@musicboxk' successfully added.
May 18 14:13:29 musicboxk shairport-sync[16630]: avahi: address advertised is: "192.168.0.85".

**Comment by faderullan** [comment]
Well, I get absolutely nothing in the log when connecting. Any other ideas?

**Comment by mikebrady** [comment]
Okay, if Shairport Sync is running and is visible to your iPhone and absolutely nothing is happening when you try to play to it, maybe there is something odd about your network.

Two things come to mind – first, a firewall and second, some routers to not properly allow information to flow between WiFi and wired ethernet. Sometimes restarting the router helps. Sometimes a router firmware update helps, but that's for later. To investigate if it's a router problem, if you had another wired device like a MacBook or a PC running Windows, it would be interesting to see if it worked. If it's Windows, be careful to set its firewall settings correctly, especially where you tell it what kind of network you're on (Public/Office/Home, etc.). If it's a Mac, it doesn't need a firewall.

**Comment by faderullan** [comment]
Well, somehow the wired device doesn't work either now... No idea why. I can connect to it but nothing is visible in the log. After a while it disconnects automatically. This worked yesterday. Is it possible that some update screwed things up? (like the kernel update or something)

Unless the rpi distro adds a firewall by default there is nothing in my network that would stop the traffic.

Here's an output from avahi-browse on the wired device (musicboxv)

=   eth0 IPv4 B177BEB4E80C@musicboxk                        AirTunes Remote Audio local
   hostname = [musicboxk.local]
   address = [192.168.0.85]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "vn=3" "sr=44100" "ss=16" "ch=2" "cn=0,1" "et=0,1" "ek=1" "sm=false" "tp=UDP"]
=   eth0 IPv4 0AFD9D59AC37@musicboxv                        AirTunes Remote Audio local
   hostname = [musicboxv.local]
   address = [192.168.0.84]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "vn=3" "sr=44100" "ss=16" "ch=2" "cn=0,1" "et=0,1" "ek=1" "sm=false" "tp=UDP"]

**Comment by faderullan** [comment]
If i connect to the wired device it says that its connected (for a while). Nothing found in the log as stated above. But if i reboot the device while the iPhone is connected it goes back to the internal speaker instantly. So some action between them two is obviously happening.

**Comment by joerg-krause** [comment]
A wild guess: https://github.com/raspberrypi/linux/issues/1342.

**Comment by faderullan** [comment]
I'm using an external USB wifi dongle. The internal wifi is disabled. And also, i have the same problem on the wired device now as well. Im reformatting the rpi2 and start all over again. It wouldn't surprise me if i broke it somehow ;)

**Comment by mikebrady** [comment]
Thanks for your updates. I think re-doing it is the right approach. BTW, is there a reason for disabling the internal WiFi? Mine works well.

The `avahi-browse` stuff looks fine.

**Comment by faderullan** [comment]
If i get the wired one to work i will reinstall the wifi rpi3 device as well. And will use the internal wifi. Hopefully it will have the range it needs.

**Comment by faderullan** [comment]
Eureka! The wired one works! Both from my macbook and from the iPhone (had to restart the iPhone though). Now on to the wifi hassle =)

**Comment by faderullan** [comment]
Sorta got the wifi to work for a while but now i see this:

May 19 00:40:25 kitchen shairport-sync[794]: avahi: avahi_register.
May 19 00:40:25 kitchen shairport-sync[794]: avahi: register_service.
May 19 00:40:25 kitchen shairport-sync[794]: avahi: service '09228DAC1556@kitchen' group is not yet commited.
May 19 00:40:25 kitchen shairport-sync[794]: avahi: request to add "_raop._tcp" service without metadata
May 19 00:40:25 kitchen shairport-sync[794]: avahi: service '09228DAC1556@kitchen' group is registering.
May 19 00:40:26 kitchen shairport-sync[794]: avahi: service '09228DAC1556@kitchen' successfully added.
May 19 00:40:26 kitchen shairport-sync[794]: avahi: address advertised is: "fe80::fa93:acdd:16c7:672".
May 19 00:40:26 kitchen shairport-sync[794]: avahi: address advertised is: "192.168.0.23".
May 19 00:40:46 kitchen shairport-sync[794]: New RTSP connection on port 5000
May 19 00:40:47 kitchen shairport-sync[794]: Play connection from user agent "AirPlay/250.20".
May 19 00:40:47 kitchen shairport-sync[794]: Active-Remote string seen: "2219377210".
May 19 00:40:47 kitchen shairport-sync[794]: DACP-ID string seen: "C3CA5C2F39531395".
May 19 00:40:47 kitchen shairport-sync[794]: User-Agent is AirPlay; selecting the AirPlay latency of -1 frames.
May 19 00:40:47 kitchen shairport-sync[794]: rtp_setup: cport=56960 tport=50385.
May 19 00:40:47 kitchen shairport-sync[794]: Connection from IPv6: fe80::a299:9bff:fe15:4b9f:65523
May 19 00:40:47 kitchen shairport-sync[794]: listening for audio, control and timing on ports 6001, 6002, 6003.
May 19 00:40:47 kitchen shairport-sync[794]: Audio receiver -- Server RTP thread starting.
May 19 00:40:47 kitchen shairport-sync[794]: Control receiver -- Server RTP thread starting.
May 19 00:40:47 kitchen shairport-sync[794]: Timing receiver -- Server RTP thread starting.
May 19 00:40:47 kitchen shairport-sync[794]: Timing sender thread starting.
May 19 00:40:47 kitchen shairport-sync[794]: Error sendto-ing to timing socket: Cannot assign requested address
May 19 00:40:47 kitchen shairport-sync[794]: SET_PARAMETER Content-Type:"text/parameters".
May 19 00:40:47 kitchen shairport-sync[794]: received parameters in SET_PARAMETER request.
May 19 00:40:47 kitchen shairport-sync[794]: volume: -20.000000
May 19 00:40:47 kitchen shairport-sync[794]: Setting volume db to -4635.000000.
May 19 00:40:47 kitchen shairport-sync[794]: syncing to seqno 13870.
May 19 00:40:47 kitchen shairport-sync[794]: Sync packet received before we got a timing packet back.
May 19 00:40:47 kitchen shairport-sync[794]: Error sendto-ing to timing socket: Cannot assign requested address
May 19 00:40:48 kitchen shairport-sync[794]: Error sendto-ing to timing socket: Cannot assign requested address
May 19 00:40:48 kitchen shairport-sync[794]: Sync packet received before we got a timing packet back.
May 19 00:40:48 kitchen shairport-sync[794]: Error sendto-ing to timing socket: Cannot assign requested address
May 19 00:40:49 kitchen shairport-sync[794]: Error sendto-ing to timing socket: Cannot assign requested address
May 19 00:40:49 kitchen shairport-sync[794]: Sync packet received before we got a timing packet back.
May 19 00:40:50 kitchen shairport-sync[794]: Sync packet received before we got a timing packet back.
May 19 00:40:51 kitchen shairport-sync[794]: Sync packet received before we got a timing packet back.
May 19 00:40:51 kitchen shairport-sync[794]: Aliasing of buffer index -- reset.
May 19 00:40:52 kitchen shairport-sync[794]: Error sendto-ing to timing socket: Cannot assign requested address

**Comment by faderullan** [comment]
Applied the below from another thread i found here and now it works! Finally! ;)

Thanks for all the help. I will be back when everything crashes again ... ;p

auto lo
iface lo inet loopback

iface eth0 inet manual
    pre-up ifdown wlan0

allow-hotplug wlan0
iface wlan0 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
    pre-up ifdown eth0; echo -n '1-1.1:1.0' > /sys/bus/usb/drivers/smsc95xx/unbind
    post-down echo -n '1-1.1:1.0' > /sys/bus/usb/drivers/smsc95xx/bind

**Comment by joerg-krause** [comment]
Finally, another case for Mr. Troubleshoot :smile:

**Comment by mikebrady** [comment]
That's good news indeed, Mattias, and well done.

If you were willing, you could do something for us. I notice in the last log that the connection being attempted between the source and Shairport Sync is over an IPv6 link-local connection (that IP address that begins with `fexx...`). We have been chasing a bug in Shairport Sync related to this situation and have a proposed fix in the `development` branch. It would be great if you could test it out, if you got the chance. Basically, it would involve going back to the directory in which you compiled Shairport Sync, switching to the `development` branch in git using `git checkout development` and pulling updates using `git pull`, then rebuilding and reinstalling it using the `autoreconf...`, `./configure...`, `make` and `sudo make install` steps. It should be a drop-in replacement – that is, no settings would need to be changed. Assuming it was then working, the experiment would be to remove the changes you made in the `/etc/network/interfaces` file you describe above and restore them to their defaults. If you'd be willing to try this out, let me know. I'd be very grateful.

**Comment by faderullan** [comment]
Hello again!

I'm willing to try this out but i'm not sure when i have the time to do it. I might try this weekend but if i come to a halt for some reason (its linux, not very good at it) i'm gonna need your help. Next week i'll be busy with other stuff so the only thing i want then is the shairport-sync to work so i can listen to music =)

**Comment by mikebrady** [comment]
Thanks Mattias. Don't worry about it – I think we are pretty confident about the fix. Enjoy the music!

**Comment by mikebrady** [comment]
I'm going to close this issue, as I think it's resolved. Feel free to reopen.
