### ISSUE TITLE
Don't override shairport-sync.service file on make install

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#304]
As in title - it would be awesome if make install won't override .service file if it's already present.
Every time I'm upgrading shairport-sync I have to redo all my changes in it (like setting Nice level, etc).

**Comment by mikebrady** [comment]
Ah, I think you mentioned this before; also a good suggestion!

**Comment by roblan** [comment]
In some other issue, but it got lost there :)

**Comment by mikebrady** [comment]
Can you try the latest push in the `development` branch?

**Comment by roblan** [comment]
My .service file was successfully preserved :)
Great! Thanks :)

**Comment by mikebrady** [comment]
Super.
