### ISSUE TITLE
Variables in name setting

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#305]
It would be great if there were some predefined variables, that could been used in name setting, like %H for hostname and %v for shairport-sync version.

**Comment by mikebrady** [comment]
Thanks for the suggestion – it's a good one. I'll try it out!

**Comment by mikebrady** [comment]
Can you try the latest push in the `development` branch?

**Comment by roblan** [comment]
That was fast!
I've tested it a little and it works great :)

Have you ever thought about some kind of donations? I use Your software everyday and I would be happy to give You couple bucks for it :) a good beer at least :)

**Comment by mikebrady** [comment]
Great. Up until now, I've been concentrating more on getting it to work well and reliably' maybe I'll have a look at the donations idea. Thanks.
