### ISSUE TITLE
Raspberry Pi + USB audio: stuttering never recovers

### ISSUE THREAD

**Issue by mrsilver76** [mikebrady/shairport-sync#306]
Hi Mike,

Firstly, thank you very much for all your hard work.

I'm trying to run shairport-sync on a Raspberry Pi 3 running the latest version of Rasbian (Jessie). I'm using a CM108 USB audio adapter which is set up as the default output.

When I run it as a service and play some music then after a random amount of time (could be seconds, could be minutes) it starts stuttering and then fails to recover. When I run it from the command line using `-vv` then I get the following:

	PCM handle name = 'default'
	alsa device parameters:
	  access type = RW_INTERLEAVED
	  format = 'S16_LE' (Signed 16 bit Little Endian)
	  subformat = 'STD' (Standard)
	  number of channels = 2
	  number of significant bits = 16
	  rate = 44100 frames per second (precisely).
	  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
	  period_time = 21333 us (>).
	  period_size = 940 frames (>).
	  buffer_time = 341315 us (>).
	  buffer_size = 15052 frames (>).
	  periods_per_buffer = 341315 (>).
	Buffers exhausted.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 32985.
	syncing to seqno 21546.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 21559.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 21599.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 21612.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	syncing to seqno 21658.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 21672.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 21745.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 21766.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Error -- ALSA device in incorrect state (4) for play.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.

About 50 more of these lines and then...

	Too-short retransmitted audio packet received in control port, ignored.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Aliasing of buffer index -- reset.
	Player: packets out of sequence: expected: 21952, got: 23488, with ab_read: 2348
	9 and ab_write: 23568.
	Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error
	: 34866.
	syncing to seqno 23582.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 23631.
	syncing to seqno 23632.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.

At that point it is pretty much in a constant loop and you're getting very small snippets of music out of the speakers. The music never recovers.

I'm not running any mixers or other programs (it's a basic Raspbian install) and wifi power management is off so I'm at a loss on what to do next.

Any ideas you have gratefully received!

**Comment by mikebrady** [comment]
Thanks for the report. It does sound like a network issue alright and Wifi power management would have been my first thought alright, but it would not normally cut in as quickly as "seconds". I'm guessing your using the built-in WiFi on the Pi3, but what is your music source?

**Comment by mrsilver76** [comment]
Wow, thanks for the speedy response!

Yes, I'm using the built in WiFi and, apologies, should have mentioned it's from an iPhone 6.

Regarding seconds, I've tried a further 5 times and all of those seem to have problems anywhere from 50 seconds to about 2 and a half minutes. Hope that is useful?

**Comment by mikebrady** [comment]
Hmm. It all sounds pretty okay – in fact, it's pretty much what I use. Nothing specific is coming to mind right now, though I wonder what would happen if you restarted your network.  Meantime, I'll be thinking about it.

**Comment by mrsilver76** [comment]
So as you suggested, I rebooted my router (and Pi for good measure), put on "Uptown Funk" and all was looking good:

	PCM handle name = 'default'
	alsa device parameters:
	  access type = RW_INTERLEAVED
	  format = 'S16_LE' (Signed 16 bit Little Endian)
	  subformat = 'STD' (Standard)
	  number of channels = 2
	  number of significant bits = 16
	  rate = 44100 frames per second (precisely).
	  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
	  period_time = 21333 us (>).
	  period_size = 940 frames (>).
	  buffer_time = 341315 us (>).
	  buffer_size = 15052 frames (>).
	  periods_per_buffer = 341315 (>).
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8003.0,    16007.8,   418689.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.7,    13133.7,   115100.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.0,    16125.5,   164213.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.0,    12095.1,    72750.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8004.5,    13061.2,   120617.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8002.5,    12079.4,    99754.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8011.9,    16939.4,   146377.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8241.2,    19210.6,   326822.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     8027.1,    12996.2,   122688.0.
	Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7979.0,    16841.6,   151417.0.

However at the 4 minute mark, this happened:

	Buffers exhausted.
	Buffers exhausted.
	Error -- ALSA device in incorrect state (4) for play.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 7430.
	syncing to seqno 36864.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 36878.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 36892.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 36905.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Buffers exhausted.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Buffers exhausted.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Buffers exhausted.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Buffers exhausted.
	Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 63332.
	syncing to seqno 36961.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 36974.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 36987.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37003.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37019.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37035.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37051.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37090.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37117.
	First packet is late! It should have played before now. Flushing 0.1 seconds
	syncing to seqno 37655.
	Buffers exhausted.
	Error -32 writing 352 samples in play(): "Broken pipe".
	Too-short retransmitted audio packet received in control port, ignored.
	Aliasing of buffer index -- reset.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.
	Too-short retransmitted audio packet received in control port, ignored.

which kept on going until I killed it :(

Hope that helps?

**Comment by mikebrady** [comment]
It's a puzzle, for sure. It so looks like something timing out somewhere. Does your router have WMM settings you could toggle?

**Comment by mrsilver76** [comment]
No settings on the router I'm afraid. 

I did build a Pi 2 with a USB wifi dongle and the original Shairport (sorry!) about 6 months ago and never had any problem with streaming. I'm reluctant to go back to that because the setup was a pain in the backside and I'd really like to use the multi room capabilities!

**Comment by mrsilver76** [comment]
If you're using the same setup, out of interest, what compile/make flags did you use? I noticed someone else used `--with-libsoxr` for their Pi 3 and I didn't.

**Comment by mikebrady** [comment]
I use the exact flags and settings suggested in the README.md guide, so after the `autoreconf -fi` I entered
```
./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd
```

The Raspberry Pi 3 has plenty of horsepower to drive the limited amount of transcoding needed and the program is multithreaded to a limited extent.

I'm still suspicious of a WiFi power management issue, so, as an experiment, just before you're about to run Shairport Sync, how about opening a window on the Pi and starting a `ping` back to some suitable point – maybe just the router itself, maybe somewhere else? It would be interesting to see if the problem occurs under those circumstances and it's a pretty simple thing to try out.

**Comment by mikebrady** [comment]
FWIW, one other thing I noticed just now is that the Power Management on the Pi3 WiFi was enabled when I checked:
```
pi@kitchen:~ $ iwconfig
wlan0     IEEE 802.11bgn  ESSID:"Network Name"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: F4:EC:38:E6:70:82   
          Bit Rate=1 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=27/70  Signal level=-83 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:145  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

eth0      no wireless extensions.
```

AFAIR, it was disabled by default. Anyway, I just turned if off:

```
pi@kitchen:~ $ sudo iwconfig wlan0 power off
pi@kitchen:~ $ iwconfig
wlan0     IEEE 802.11bgn  ESSID:"Network Name"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: F4:EC:38:E6:70:82   
          Bit Rate=2 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=32/70  Signal level=-78 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:302  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

eth0      no wireless extensions.
```

**Comment by mrsilver76** [comment]
Problem solved!

Your hunch was right. I did have power management turned off but running a ping to the router at the same time showed a massive spike in the time reported (from ~250ms to well over 2500m) when the music started to stutter. 

Moving the Pi closer to the router resolved the issue. 

Thanks very much for your help, really appreciate it!

**Comment by mikebrady** [comment]
That's really great. Well done!
