### ISSUE TITLE
Support password option

### ISSUE THREAD

**Issue by tfe** [mikebrady/shairport-sync#31]
It would be nice to be able to set a password to start airplay. The original `shairport` supported this.

```
-k, --password=PW   require password to stream audio
```

**Comment by mikebrady** [comment]
Nice idea alright, I'll look into it.

**Comment by mikebrady** [comment]
I've done that, if you could try it out. Switch to branch 2.2, which is not (yet) the default.

**Comment by tfe** [comment]
Works great, thanks! :+1:
