### ISSUE TITLE
No song metadata on development branch

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#310]
source: iTunes 12.0.4.119 on Mac
lastest development
shairport-sync core metadata are shown, but no song info.
Everything is fine when I revert commit https://github.com/mikebrady/shairport-sync/commit/49d27c35f2d1098f55af50797f2eefd718709444

**Comment by mikebrady** [comment]
Thanks. I believe I see the error.

**Comment by mikebrady** [comment]
Just pushed a brown-bag fix. It seems to work.

**Comment by roblan** [comment]
Everything seems to work just fine now :)
