### ISSUE TITLE
Cannot use usb sound card

### ISSUE THREAD

**Issue by phpfs** [mikebrady/shairport-sync#311]
Hello!

I don't really understand how to use a usb sound card.
Where can i find the hw:?
Do I have to do something else?

Mfg phpfs

**Comment by phpfs** [comment]
Hello again 😀

Worked it out:

In the "aplay -l", you look for the card and the card's device you want to use.
In the shairport-sync config (alsa), you change the following
mixer_device = "hw:x"; //x is your card id
output_device = "hw:x,y"; //and y is your device id, f.ex "hw:1,0" for card 1 and it's 0th device

Hope that will help someone in the future :)

**Comment by mikebrady** [comment]
Thanks for that!
