### ISSUE TITLE
Shairport-sync aborts when accessing Siri on iPhone while streaming

### ISSUE THREAD

**Issue by romanpeters** [mikebrady/shairport-sync#313]
When I'm streaming music from my iPhone 5 with TuneIn Radio over shairport-sync and then hold the home button to summon Siri, the audio not only stops playing, but the shairpot-sync service on my Raspberry Pi Raspbian stops completely. Running shairport-sync in verbose mode gives me this error when it happens:

Player thread exit
**\* Error in `shairport-sync': free(): invalid pointer: 0x756077e0 ***
Aborted

I assume this is not supposed to happen. Is this something that can be fixed? Or is there a way to automatically restart shairport-sync after it aborts?

P.s. thanks for all your hard work. Shairport-sync is great!

**Comment by mikebrady** [comment]
Thanks for the report. Can you make the crash happen reliably?

**Comment by RomanPeters** [comment]
I thought I could, since I tried it a few times in a row, but when I try it now it doesn't happen anymore...

**Comment by mikebrady** [comment]
Thanks for trying. It would be great to catch it!

**Comment by mikebrady** [comment]
Hi Roman. As a matter of interest, had you enabled the metadata features? And if so, were they in use at the times of the crashes? Thanks.

**Comment by RomanPeters** [comment]
No, I didn't use any metadata features. The only things I uncommented in shairport-sync.conf were:

name = 'AirPort';
drift = 352;
volume_range_db = 30;

**Comment by mikebrady** [comment]
Thanks for the clarification.

**Comment by RomanPeters** [comment]
No problem, let me know if there's anything else I can do.

**Comment by mikebrady** [comment]
There have been many updates since this, and I'm pretty sure the problem has been resolved. Please open a new issue if necessary.
