### ISSUE TITLE
No sound IOS 9.2.3 iPhone/iPod, OK iPad Mini, OK iTunes 12.4.0 

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#315]
Hi Mike,

I'm experiencing an issue where IOS 9.2.3 on iPhone or iPod Touch produces no sound output on end point systems even though it successfully connects to shairport-sync (2.8.3) and volume commands are being processed (alsamixer shows volume changing in real time). If I switch to iPad Mini running same ver of IOS, or iTunes 12.4.0 then no issue.

Let me know if u need any diagnostics.

Regards,
Tim

**Comment by mikebrady** [comment]
Hi Tim. Is it reproducible at all? I'm preparing 2.8.4 at the present...

**Comment by moodeaudio** [comment]
Yes, can repro.

**Comment by mikebrady** [comment]
Great! If you could list a sequence of steps, I'll have a look at it, thanks.

**Comment by moodeaudio** [comment]
All iDevices have IOS 9.2.3, Macbook Air has latest ElCap and iTunes 12.4.0

Endpoint systems running shairport-sync 2.8.3 on mix of Pi-1B, 2B and 3B. Pi-1B system has DAC with no hardware volume controller so SPS using software volume. Pi-2B/3B systems have DAC's with hdwr vol controllers so SPS using hardware volume.

TESTS

Sending Airplay stream to each of Pi-1B, 2B and 3B systems individually

1) iPad Mini - OK
2) Mac iTunes - OK
3) iPhone 5C - no sound
4) iPod Touch - no sound

- Tim

**Comment by mikebrady** [comment]
Thanks. I'll give a subset of these a try – I have a Pimoroni DAC without a hardware volume controller too and a few other bits. I might have to come back to you later to get diagnostics, but for now, let me try it out.

**Comment by mikebrady** [comment]
Hi Tim. I've just tried it on stuff I have to hand – a Raspberry Pi B+ with a Pimoroni pHAT DAC, a Mac Pro running OSX10.11.5 / iTunes 12.4.0.119 and an iPhone 6 running iOS 9.3.2 (not 9.2.3 – was that a typo?). The Pi is wired to the Mac which is also acting as a WiFi access point for the iPhone. The connection from iTunes on the Mac comes in over IPv4, and from the iPhone it's over a link-local IPv6 address. Long story short, everything is fine. So, I might need some diagnostics from your devices. If I could see the IP number / style (log verbosity of 2) and maybe if you enabled statistics for a little, it would be very useful.

If you were feeling adventurous, could you put the latest development version on a device and see if it makes a difference?

**Comment by moodeaudio** [comment]
Hi Mike,

Yes typo. I'll try logging and get back to you.

IP addressing for one of the endpoint systems is below.

wlan0     Link encap:Ethernet  HWaddr 74:da:38:09:fd:f6  
          inet addr:192.168.1.149  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::54b7:3958:46ea:6949/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2346728 errors:0 dropped:22241 overruns:0 frame:0
          TX packets:556636 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3278731103 (3.0 GiB)  TX bytes:66623187 (63.5 MiB)

**Comment by moodeaudio** [comment]
Hi Mike,

Where is log file located?

-Tim

**Comment by mikebrady** [comment]
Hi Tim. The log will be placed in the system log, so long as the log verbosity is set to something other than 0.

If you're on Jessie, then something like: `sudo journalctl -n 1000` will work (this will give the last 1000 lines).

Otherwise, on Wheezy, something like `tail -n 1000 /var/log/syslog` will do the same. If you add `-f` to either, it will 'follow' any new log entries, which is handy.

BTW, I'm using Jessie, so please let me know which version of the OS you're using, in case it's important.

**Comment by moodeaudio** [comment]
Hi Mike,

Jessie but I'm not seeing anything from SPS when I tail syslog. SPS is being launched by a PHP script using cmd line options. I enabled logging at 2 in the conf file. Is conf file processed even though cmd line options being used?

-Tim

**Comment by mikebrady** [comment]
If you're on Jessie, what you see in the log depends on your level of privilege. I use `sudo journalctl...` for that reason.

**Comment by mikebrady** [comment]
Yep, the configuration file is looked at. The command line options have priority. If you prefer rouse a command line option, use `-vv` for a log verbosity of 2.

**Comment by moodeaudio** [comment]
Hi Mike,

Was not able to get anything in syslog when launching from PHP script using -vv or with conf setting (I'll investigate later), but when launching from cmd line I have log trace below. Sender is iPhone5C IOS 9.3.2

-Tim

pi@rp4:~ $ sudo /usr/local/bin/shairport-sync -vv -a "RP4 Airplay" -S soxr -w -B /var/www/command/spspre.sh -E /var/www/command/spspost.sh -- -d hw:0 -c Digital
Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "hw:0".
Open Mixer
Lowest dB value is a mute.
Can't get dB value corresponding to a "volume" of 1.
Hardware mixer has dB volume from -103.000000 to 0.000000.
Has mute ability.
The processor is running little-endian.
Version: "2.8.3-openssl-Avahi-ALSA-stdout-soxr-metadata"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "RP4 Airplay".
Audio Output name is "(null)".
on-start action is "/var/www/command/spspre.sh".
on-stop action is "/var/www/command/spspost.sh".
wait-cmd status is 1.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1".
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
disable_synchronization is 0.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
get-coverart is 0.
avahi: avahi_register.
avahi: register_service.
avahi: service 'DA6032FBF3E1@RP4 Airplay' group is not yet commited.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'DA6032FBF3E1@RP4 Airplay' group is registering.
avahi: service 'DA6032FBF3E1@RP4 Airplay' successfully added.
avahi: address advertised is: "fe80::54b7:3958:46ea:6949".
avahi: address advertised is: "192.168.1.149".
New RTSP connection on port 5000
New RTSP connection on port 5000
Play connection from user agent "AirPlay/280.33".
Active-Remote string seen: "1366597472".
DACP-ID string seen: "5952D7E6BEFF91D9".
User-Agent is AirPlay; selecting the AirPlay latency of -1 frames.
rtp_setup: cport=54899 tport=62077.
Connection from IPv6: fe80::47e:5056:b8e1:1795:49862
listening for audio, control and timing on ports 6001, 6002, 6003.
RTSP connection closed.
Closing down RTSP conversation thread...
RTSP conversation thread terminated.
Audio receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.
Timing receiver -- Server RTP thread starting.
Timing sender thread starting.
Error sendto-ing to timing socket: Cannot assign requested address
Error sendto-ing to timing socket: Cannot assign requested address
SET_PARAMETER Content-Type:"text/parameters".
received parameters in SET_PARAMETER request.
volume: -17.250000

Setting volume db to -3785.250000.
syncing to seqno 5080.
Sync packet received before we got a timing packet back.
syncing to seqno 5092.
Error sendto-ing to timing socket: Cannot assign requested address
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Aliasing of buffer index -- reset.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7992.9,    20008.7,   509522.0.
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
syncing to seqno 9113.
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
Aliasing of buffer index -- reset.
Sync packet received before we got a timing packet back.
Error sendto-ing to timing socket: Cannot assign requested address
Sync packet received before we got a timing packet back.
Sync packet received before we got a timing packet back.
RTSP shutdown requested.
Closing down RTSP conversation thread...
Shut down audio, control and timing threads
Control RTP thread interrupted. terminating.
Audio receiver -- Server RTP thread interrupted. terminating.
Timing thread interrupted. terminating.
rtp_timing_sender thread interrupted. terminating.
Closed and terminated timer requester thread.
Timing RTP thread terminated.
timing thread joined
audio thread joined
control thread joined
Player thread exit
shutting down RTP thread
RTSP conversation thread terminated.

**Comment by mikebrady** [comment]
Hi Tim. Thanks for all that. This `Error sendto-ing to timing socket: Cannot assign requested address` is a new thing and it appears to be associated with using an IPv6 local-link address in a situation where the device (the Pi) has more than one network interface. It's a bug in Shairport Sync but it seems to have been dormant until recently, and I don't know what's happened to "awaken" it. However, we believe it's been fixed in the latest development version, so if you'd be kind enough to build it and try it out, I'd be obliged. I'll hold releasing 2.8.4, which would have the fix, until you come back about it.

**Comment by moodeaudio** [comment]
Hi Mike,

I tested on Pi with one iface (eth0) and no issues. The other Pi's that exhibited the failure mode were WiFi and thus had two interfaces (eth0 and wlan0). I'd say u guys nailed the root cause.

I'll test 2.8.4 in a bit and get back to u.

-Tim

**Comment by mikebrady** [comment]
That sounds plausible alright, and thus hopeful. BTW, the latest version on the`development` branch is labelled 2.8.3.12. It's a candidate 2.8.4.

**Comment by moodeaudio** [comment]
Hi Mike,

Tested 2.8.3.12 on Pi-2B and Pi-3B each using WiFi and no issues. It appears that problem is fixed :-)

Do u have timing for 2.8.4 release?

-Tim

**Comment by moodeaudio** [comment]
I should mention that sending clients included iPhone 5C and iPod Touch 5th Gen.
Also Mac iTunes and iPad Mini no issues with 2.8.3.12 and metadata works as well.
 
-Tim

**Comment by mikebrady** [comment]
Great, thanks. Actually, I was hoping to release 2.8.4 this weekend. I'm updating the `man` stuff and things like that...

**Comment by moodeaudio** [comment]
Planned to release Moode 2.6 by end of month so if I see 2.8.4 this weekend, I'll include it :-)

**Comment by mikebrady** [comment]
Thanks.

**Comment by moodeaudio** [comment]
Quick question - whats easiest way for me to check to see if new release has been posted?

**Comment by mikebrady** [comment]
Hi Tim. First, 2.8.4. is out now :). Second, I don't really know the best way to do this. It seems that the frequency of point updates is about monthly, but I do hope that eases off somewhat.

**Comment by mikebrady** [comment]
Fixed in 2.8.4.
