### ISSUE TITLE
Music won't play via shairport-sync when connected to wifi

### ISSUE THREAD

**Issue by rchoucroun** [mikebrady/shairport-sync#322]
I have a raspberry pi 3 running Jessie with shairport-sync installed. I have a CM-108 USB sound card connected. I have spent several days trying to figure out why I couldn't get sound out of the sound card. I made all the suggested changes to all the configuration files, etc to ensure that the sound card is the default. I managed to get sound out of the soundcard at most three times in two days. However, if I paused the music (played from my iphone), I couldn't get it to start again. If I restarted the shairport-sync service, or rebooted the Pi, the music wouldn't start.

After a couple of days of reading things here and elsewhere, I read that the problem may be network-related. So, I connected the Pi to ethernet to my router. I could hear the music playing straight away. I restarted the service and rebooted and I the music would play every time. Repeat, everything works exactly as it should if it is connected to the ethernet cable. If I disconnect the cable, the music will continue to play for a until I restart the Pi.

I disabled the power management on the wifi but it still won't work.

How can I get shairport-sync to play from wifi from boot-up without first connecting to an ethernet cable?

**Comment by mikebrady** [comment]
Thanks for the report. Could you say what version of Shairport Sync you are using? And did you get any logs?

**Comment by rchoucroun** [comment]
Thanks Mike, 

shairport-sync -V returns: **2.8.3-openssl-Avahi-ALSA**

After a reboot of the Pi, I tried playing from my iPhone.  This is the result of tail -50 /var/log/syslog:
```

Jun  7 11:48:51 raspberrypi shairport-sync[475]: listening for audio, control and timing on ports 6001, 6002, 6003.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: Audio receiver -- Server RTP thread starting.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: Control receiver -- Server RTP thread starting.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: Timing receiver -- Server RTP thread starting.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: Timing sender thread starting.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: SET_PARAMETER Content-Type:"text/parameters".
Jun  7 11:48:51 raspberrypi shairport-sync[475]: received parameters in SET_PARAMETER request.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: volume: 0.000000
Jun  7 11:48:51 raspberrypi shairport-sync[475]: syncing to seqno 32407.
Jun  7 11:48:51 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:52 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:53 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:54 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:55 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:55 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
Jun  7 11:48:56 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:57 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:58 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:58 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Tue Jun  7 11:49:28 2016 [try http://www.rsyslog.com/e/2007 ]
Jun  7 11:48:59 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:48:59 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
Jun  7 11:49:00 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:01 raspberrypi CRON[1247]: (root) CMD (/etc/myDevices/crontab.sh)
Jun  7 11:49:01 raspberrypi CRON[1243]: (CRON) info (No MTA installed, discarding output)
Jun  7 11:49:01 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:01 raspberrypi kernel: [  112.846132] w1_master_driver w1_bus_master1: Family 0 for 00.400000000000.46 is not registered.
Jun  7 11:49:02 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:03 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:03 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
Jun  7 11:49:04 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:05 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:06 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:07 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:08 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
Jun  7 11:49:08 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:10 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:11 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:11 raspberrypi shairport-sync[475]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7966.3,    13804.7,   109382.0.
Jun  7 11:49:12 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:12 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
Jun  7 11:49:13 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:14 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:15 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:16 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:16 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
Jun  7 11:49:17 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:18 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:19 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:20 raspberrypi shairport-sync[475]: Sync packet received before we got a timing packet back.
Jun  7 11:49:20 raspberrypi shairport-sync[475]: Aliasing of buffer index -- reset.
```

**Comment by mikebrady** [comment]
Many thanks for this. Could you update to the latest version, which is 2.8.4, please? It has some networking fixes that might relate to this. There is an UPDATING page that might help you.

**Comment by rchoucroun** [comment]
Sorry for my ignorance, but how do I update?  I tried apt-get update.

**Comment by mikebrady** [comment]
I think the fault is mine, for not being explicit enough, so here goes:

If you installed Shairport Sync by using `$ sudo apt-get install shairport-sync` or similar, then you've installed it from a package and it could be quite a long time (months) before it is updated to 2.8.4.

The alternative to waiting is to delete the vision of Shairport Sync that came in the package and to build and install the latest version from sources yourself. There is a bit of work in it, but it's not rocket science and it is well documented on the [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md) page (it even describes how to find and delete existing versions of Shairport Sync). One little piece of advice is to follow the instructions precisely – don't "make it up", as it were.

On the other hand, if you've installed Shairport Sync by following the README instructions, then updating is pretty straightforward – see [UPDATING.md](https://github.com/mikebrady/shairport-sync/blob/master/UPDATING.md).

Good luck!

**Comment by mikebrady** [comment]
Hi there. I wonder if there's been any developments on this?

**Comment by rchoucroun** [comment]
Hi Mike. Apologies for not responding. I've had a few other priorities lately and haven't had a chance to do anything with this. I plan to have a look at it soon but I'm not sure when.

**Comment by mikebrady** [comment]
Thanks. If you don't mind, I'll close the issue and we can reopen it when the time comes.
