### ISSUE TITLE
Problem with Shairport sync in wireless relay mode

### ISSUE THREAD

**Issue by thanhnha0706** [mikebrady/shairport-sync#326]
Hi @mikebrady,

Everything works perfectly until I switch my router to wireless relay mode, which IP is assigned by the other router (the main one). My macbook still sees the airplay icon appearing on the menu but when I select it and play some musics, I cannot hear any sound. After a while, my macbook says that it cannot connect to the chosen airport.

Have anyone faced this problem? Please help me!

**Comment by mikebrady** [comment]
Thanks for the report, but it really sounds like something to do with the change in your network. If you reset everything, then turn on wireless relay mode and then turn on the shairport sync device, what happens?

**Comment by thanhnha0706** [comment]
@mikebrady thank you for your support. I have restarted the Shairport and it just works now. I will continue to check this. Again, thank you very much! :D
