### ISSUE TITLE
Does this work with El Capitan?

### ISSUE THREAD

**Issue by Coaxial** [mikebrady/shairport-sync#327]
I hope this is the right place to ask.

I am currently running El Capitan and can't stream audio via AirPlay to my RPi running OpenELEC. This is a known issue on OpenELEC's side.

Will this project work to stream from El Capitan, either on a RasPi or a C.H.I.P.?

**Comment by mikebrady** [comment]
Hi there. Yep, Shairport Sync will stream to a Raspberry PI using Raspbian and to a C.H.I.P. on its standard Linux from El Capitan.

**Comment by Coaxial** [comment]
Thanks, I ordered a couple C.H.I.P. then!
