### ISSUE TITLE
Is it possible to transfer metadata from MacBook?

### ISSUE THREAD

**Issue by lowercasename** [mikebrady/shairport-sync#328]
Shairport-sync has been working beautifully, I'm very happy with it.

I've been wondering - if I play Spotify on my iPhone through shairport-sync, it transfers metadata information across without a problem. On my MacBook, to connect to shairport-sync I alt-click on the speaker icon and select my Shairport server. With this method, Spotify (or anything else) doesn't transfer metadata, presumably because all shairport is recieving is an audio stream. Is there any way to send metadata along with the audio stream?

**Comment by mikebrady** [comment]
Thanks for your kind words, and I'm glad it's working for you.

But I can't really think of any neat way to capture the metadata – I think that's a question for Apple!

**Comment by mikebrady** [comment]
I'm going to close this issue if that's okay.
