### ISSUE TITLE
Pulseaudio compilation fails

### ISSUE THREAD

**Issue by fiddlerwoaroof** [mikebrady/shairport-sync#33]
On Debian Jessie (8.0), if shairport-sync is configured with the option `--with-pulseaudio`, make fails with the error:

    mv -f .deps/player.Tpo .deps/player.Po
    gcc -g -O2 -o shairport-sync shairport.o rtsp.o mdns.o mdns_external.o common.o rtp.o player.o alac.o audio.o audio_dummy.o audio_pipe.o mdns_avahi.o  audio_alsa.o   audio_pulse.o   -lpulse-simple -lasound  -lavahi-common -lavahi-client -lsoxr -lpolarssl -lpopt  -lm -lpthread -ldaemon -lrt 
    /usr/bin/ld: audio_pulse.o: undefined reference to symbol 'pa_strerror@@PULSE_0'
    //usr/lib/x86_64-linux-gnu/libpulse.so.0: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    Makefile:447: recipe for target 'shairport-sync' failed

If, however, I run the same `gcc` command manually with the option `-lpulse` added, the compilation works, and I can install shairport-sync as normal.

**Comment by mikebrady** [comment]
Thanks for that – I'll check it out. But be aware that while it might compile (with your modification) shairport-sync doesn't work properly – if at all – with pulseaudio. It only works with the ALSA back end.

**Comment by fiddlerwoaroof** [comment]
It seems to work for me.

**Comment by mikebrady** [comment]
Cool – but it won't be synchronising, as I never tried to get DAC buffer information (necessary for accurate timing) back from the pulseaudio back end. I'll try to fix the compiler error anyhow.

**Comment by mikebrady** [comment]
Just checked – the `--with-pulseaudio` option still compiles properly with "Wheezy", and "Jessie" seems to be still beta... So I might just wait until it settles down a bit more...
