### ISSUE TITLE
Can't compile with --with-pipe

### ISSUE THREAD

**Issue by busa-projects** [mikebrady/shairport-sync#331]
The Stable Release allways crashes with the following Error:

make[2]: Entering directory '/root/software/shairport-sync/shairport-sync-2.8.4'
gcc -DHAVE_CONFIG_H -I.    -Wno-multichar  -g -O2 -MT audio_pipe.o -MD -MP -MF .deps/audio_pipe.Tpo -c -o audio_pipe.o audio_pipe.c
mv -f .deps/audio_pipe.Tpo .deps/audio_pipe.Po
gcc -Wno-multichar  -g -O2   -o shairport-sync shairport.o rtsp.o mdns.o mdns_external.o common.o rtp.o player.o alac.o audio.o mdns_avahi.o  audio_alsa.o  audio_stdout.o audio_pipe.o      -lasound   -lavahi-common -lavahi-client -lssl -lcrypto   -lconfig   -lpopt   -lm -lpthread -ldaemon   -lrt 
audio_pipe.o: In function `play':
/root/software/shairport-sync/shairport-sync-2.8.4/audio_pipe.c:58: undefined reference to `non_blocking_write'
collect2: ld returned 1 exit status
Makefile:390: recipe for target 'shairport-sync' failed
make[2]: *** [shairport-sync] Error 1
make[2]: Leaving directory '/root/software/shairport-sync/shairport-sync-2.8.4'
Makefile:441: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/software/shairport-sync/shairport-sync-2.8.4'
Makefile:292: recipe for target 'all' failed
make: *** [all] Error 2

Any Ideas?

Thx! busa

**Comment by mikebrady** [comment]
Thanks for the report. Let me check.

**Comment by mikebrady** [comment]
There is indeed a problem. It's fixed it in the latest development version 2.8.4.2, which you can get if you switch to the `development` branch and do a `$ git pull`. Thanks for reporting the issue, and apologies for the inconvenience.

**Comment by busa-projects** [comment]
Works like a charm! Perfect! 
Thanks a lot for the fast fix! Was the last part for my PiMusicbox Multiroom Setup!
