### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by ABrolund** [mikebrady/shairport-sync#333]
Hi, 
quick question and I do hope it is not a stupid one. I have already looked for it and did not find any information. 

Is the debian package compiled with pipe and metadata pipe support? 
Or do I need to compile it myself?

Thx for help!

**Comment by mikebrady** [comment]
I think that a question best answered by Dan The Person at @dantheperson and Chris Boot at @bootc and also at <bootc@debian.org>.

**Comment by bootc** [comment]
For the Debian package (which is in testing/stretch and unstable/sid), both audio pipe (`--with-pipe`) and metadata support (`--with-metadata`) are enabled. The Ubuntu package is maintained by @dantheperson in his own PPA and may (or may not) have a totally different set of options selected.

Aside: if you'd like to see `shairport-sync` in Debian stable/jessie, just ask and I'll upload a backport.

**Comment by lundzern** [comment]
I'd love to see shairport-sync in Debian jesse! Will it be uploaded soon?

**Comment by bootc** [comment]
I'm working on sorting out the access I need to be able to do this. I'll let you know once it hits backports.

**Comment by lundzern** [comment]
Thanks!

**Comment by bootc** [comment]
@lundzern FYI my backports package has (finally) made it in: https://packages.debian.org/jessie-backports/shairport-sync.

@mikebrady Any reason to keep this ticket open or shall we close it?

**Comment by mikebrady** [comment]
Many thanks Chris – that's good news. I'll close this issue.
