### ISSUE TITLE
2 Shairport-sync installs conflicting

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#335]
I'm having a problem setting up a second Shairport-sync install.

My primary install is running on a Pi 3 (AirPi) and my new secondary install is running off a Pi Zero 1.3 with PHAT DAC (AirZero).

The problem is I can get the AirZero working for a few seconds then it just cuts out. After doing hours of digging, I did a "**shairport-sync -v**" and noticed this error..

_Successful Startup
Unable to listen on IPv4 port 5000. The error is: "Address already in use".
Unable to listen on IPv6 port 5000. The error is: "Address already in use".
Could not establish a service on port 5000 -- program terminating. Is another Shairport Sync running?
Request to shut down all rtsp conversation threads_

So how do I run 2 installs on the same network?

**Comment by PeterPablo** [comment]
Hi, how about changing the port in the config file? This might prevent auto
discovery though.

**Comment by mikebrady** [comment]
Thanks for the post. That error message happens if Shairport Sync is already running *on the same machine*. It sounds like you already started Shairport Sync, maybe through a startup script?

use `$ ps | grep shair` to list any instances of Shairport Sync already running. There is no particular limit to the number of Shairport Syncs that can be running on the network.

**Comment by rockrabbit** [comment]
OK, confused.

I have a Pi 3 running no problems. I've just setup the PiZero.. the PiZero cuts out after a few seconds while the Pi 3 just keeps humming along.

On the PiZero and the Pi 3 I type your command and get nothing in return

The strange thing is I edited the config file port... rebooted... nothing worked... went back in and set it back to default, and now suddenly it appears that the PiZero is working with no drops!

I'm at a loss!

**Comment by mikebrady** [comment]
Hah! It's magic. Seriously though, is everything working now?

**Comment by rockrabbit** [comment]
Yes.. I'm completely stunned!

Been working at this pulling out my hair for the past 24 hours... and I edit something, does not work, set it back.. and now.. I have both systems working!

**Comment by mikebrady** [comment]
It's good that it came right. A small thing, but I've now altered that error message in the `development` branch to be a bit more explicit: "Is another Shairport Sync running on this device?". Hopefully it'll help someone in the future. Is it okay to close this issue?

**Comment by rockrabbit** [comment]
Close it! and thank you!
