### ISSUE TITLE
Continued Issues with multiple Shairport-Sync devices

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#337]
Greetings,

I posted this before and it appears I'm now back to the same issue.

I have a Pi3 (AirPi) and I have a PiZero (AirZero).. both on the latest firmware and both running the latest build of Shairport-Sync. The PiZero was working flawlessly the past few days and then suddenly it begins cutting out. I run **shairport-sync -v** and get the same output:

```
Looking for the configuration file "/etc/shairport-sync.conf".
Output device name is "hw:0".
Version: "2.8.4-OpenSSL-Avahi-ALSA-metadata"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "AirZero".
Audio Output name is "also".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
playback_mode is 0 (0-stereo, 1-mono).
disable_synchronization is 0.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
Successful Startup
Unable to listen on IPv4 port 5000. The error is: "Address already in use".
Unable to listen on IPv6 port 5000. The error is: "Address already in use".
Could not establish a service on port 5000 -- program terminating. Is another Shairport Sync running?
Request to shut down all rtsp conversation threads
```

I'm at a loss!

**Comment by mikebrady** [comment]
Thanks. And what happens if you do `$ ps aux | grep shair`.m? Are you certain no other Shairport Sync is running on the device?

**Comment by rockrabbit** [comment]
If i type and enter `ps aux | grep hair` i get:

> shairpo+   583  0.0  0.6  23624  2936 ?        Ssl  12:08   0:00 /usr/local/bin/shairport-sync
> root       727  0.0  0.6   6172  3016 pts/0    S+   12:12   0:00 sudo nano /etc/shairport-sync.conf
> root       731  0.1  0.6   4788  3080 pts/0    S+   12:12   0:00 nano /etc/shairport-sync.conf
> pi         768  0.0  0.4   4268  2004 pts/1    S+   12:15   0:00 grep --color=auto shair

**Comment by mikebrady** [comment]
Thanks. What that looks like is that Shairport Sync is already running – the first line shows that it's running as user `shairport-synn`. I guess that's because it would have been launched by the startup script.

**Comment by rockrabbit** [comment]
so what does this mean?

**Comment by mikebrady** [comment]
No. This is meant to happen!  When you build and install Shairport Sync, it installs a script that launches it at startup, so you don't have to launch it yourself. When it launches automatically it looks at the configuration file, so just make sure it's got the correct settings. It's a feature, honest :)

**Comment by rockrabbit** [comment]
Ok, but this still does not solve the issue!

I'm having the same issue on both of my Pi's right now!

As far as the config file is setup on the Pi3, the only things uncommented are:

```
name = "AirPi";
output_backend = "alsa";
output_device = "hw:1";
```

The PiZero:

```
name = "AirZero";
output_backend = "alsa";
output_device = "hw:0";

```
The installs are both built with:

```
sudo apt-get -y install build-essential git

sudo apt-get -y install autoconf automake libtool libdaemon-dev libasound2-dev libpopt-dev libconfig-dev

sudo apt-get -y install avahi-daemon libavahi-client-dev

sudo apt-get -y install libssl-dev
```

and both configured with:

`sudo ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemd`

The Pi3 was flawless right up until I added the PiZero setup!

I'm still at a loss!

**Comment by mikebrady** [comment]
I'm afraid I can't really see how the problem is occurring. Is it possible, at all, that there is some confusion about which machine is which? Sorry if it's a silly question.

**Comment by rockrabbit** [comment]
Can't see how?!

They both have unique names! 

I've even renamed the Pi's

The Pi3 is default name of: `raspberrypi `
The PiZero is named: `pizero`

They are both connected to my 2.4Ghz wifi network

This is just bizarre!

**Comment by mikebrady** [comment]
It sure is confusing. I'm afraid I'm out of ideas. Maybe it would be good to get one of them working with the other completely disconnected. Then disconnect it and get the first one going. Then, when both are know to be working separately, switch them off, connect them both up and restart them.

**Comment by mikebrady** [comment]
Right, and presuming you're sending music from iTunes (?), it would begin to sound like some kind of weird network problem.

**Comment by rockrabbit** [comment]
Either from iTunes or from my iPhone!

I have an Apple Airport Extreme Gen 4 g/n/ac model.. up to date... no issues

I do networking for a living so I've debugged that aspect!

**Comment by mikebrady** [comment]
Yep. Another quick thing to check is that WiFi power management is off on both Raspberrys.

**Comment by rockrabbit** [comment]
```
sudo nano /etc/modprobe.d/8192cu.conf  

options 8192cu rtw_power_mgnt=0 rtw_enusbss=0 rtw_ips_mode=1
```

This has been done of both!

I'm beginning to think this might have something to do with IPv6.. a little digging brought this up..

http://goo.gl/mJuaJ0

I tried it and fingers crossed this solves the issue!

**Comment by mikebrady** [comment]
Was that the problem than?

**Comment by rockrabbit** [comment]
I don't know... I turned IPv6 Sharing off and I unhid my network... everything appears to be working...

I have both systems playing right now!

Had a few false starts.. rebooted them both.. right now they seem to be stable!

But they were both stable for the past 48 hours and then this morning the problem kicked!

Going to give it another 72 hours and report back!
