### ISSUE TITLE
Speaker is busy Problem after video stream ends

### ISSUE THREAD

**Issue by mrlowalowa** [mikebrady/shairport-sync#339]
Hey,

specially when I connect my Mac with AirPlay and a video stream ends the audio connection often fails and I can't reconnect to it anymore unless I restart the shairpoint service on my chip.. This is the output shairpoint generates on -v 3 while this is happening:

> Looking for the configuration file "/etc/shairport-sync.conf".
> Output device name is "hw:0".
> startup
> avahi: avahi_register.
> avahi: register_service.
> Avahi without metadata
> New RTSP connection on port 5000
> Play connection from user agent "AirPlay/250.20".
> Active-Remote string seen: "2426532738".
> DACP-ID string seen: "1098E73DA79C5549".
> Connection from IPv6: fe80::baf6:b1ff:fe10:e3a9:52358
> RTSP shutdown requested.
> Now closing RTSP connection.
> Shut down audio, control and timing threads
> Audio receiver -- Server RTP thread interrupted. terminating.
> Control RTP thread interrupted. terminating.
> Timing thread interrupted. terminating.
> rtp_timing_sender thread interrupted. terminating.
> Closed and terminated timer requester thread.
> Timing RTP thread terminated.
> timing thread joined
> audio thread joined
> control thread joined
> Player thread exit

I could write a script that finds the PID and kills the thread each time and restarts it... but that's not a permanent solution of course.. :D 

Hope this error message helps :)

**Comment by mikebrady** [comment]
Hi there, and thanks for the post. The log seems to show that the play session was terminated correctly, as if it was requested. Can you cause the problem reliably? If you can tell me how, I could try to do so here.

**Comment by mrlowalowa** [comment]
It happens with various browsers like google chrome and safari. When I watch a couple of youtube videos or Amazon Prime movies. Just a normal audio transmission. But when these movies/videos ends normally the connection to the AirPlay device get's terminated.

I recognized this because my speaker/CHIP was making a cut of 'noise' when the AirPlay session gets terminated..

But when I want to watch the next video my Mac tries to reestablish a connection to the Airplay Speaker and it says that the AirPlay device is still in use. I also cannot connect with other devices like my iPhone/iPad during this behavior of shairpoint.. It's really an interesting behavior.

**Comment by jamienk** [comment]
I've had a similar issue -- my iTunes reports that the AirPlay device is still in use and won't play. mrlowalowa: did you even write the kill script work-around you were thinking about?

**Comment by mrlowalowa** [comment]
> mrlowalowa: did you even write the kill script work-around you were thinking about?
@jamienk nope.. I didn't. I used another solution. A spotify-connect script.. but this is not autolaunch able...

for this script you would need to safe the PID when starting sharepoint or grep for the PID --> `ps -aux | grep shairpoint` and kill it with it's PID and restart. But the more tricky part is to analyse the output from shairpoint.
You can generate a cron job that greps for certain key words inside it.. But as this behaviour is not indicated as an error you would kill it every time you kill the session..
Maybe a web-triggered action for a remote kill will do.. But all of this is not in proportionality to the effort. Simple logon and generate you the upper part of the script and you are all set.

**Comment by mikebrady** [comment]
There have been many updates since this, and I'm pretty sure the problem has been resolved. Thanks for this contribution. Please open a new issue if necessary.
