### ISSUE TITLE
S32_LE format question (shairport-sync 2.8.4)

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#340]
Hi Mike,

Moode 2.6 user has an Amanero USB-I2S board connected to Soekris DAM1021 DAC via I2S. When an Airplay stream is received, ALSA creates an output stream format of 32 bit 44.1 kHz.

cat /proc/asound/card1/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 5513
buffer_size: 22050

In shairport-sync log, after the connection is negotiated the error below appears and then no audio...

audio_alsa: Sample format not available for device "hw:1": Invalid argument

The error suggests that ALSA determined the Amanero USB device does not support 32/44.1 but then it looks like it was ALSA that generated the 32/44.1 stream to begin with. Very odd. Any thoughts?

Below are links to user posts in diyAudio Moode thread that have details and the complete shairport-sync log.

http://www.diyaudio.com/forums/pc-based/271811-moode-audio-player-raspberry-pi-389.html#post4772488
http://www.diyaudio.com/forums/pc-based/271811-moode-audio-player-raspberry-pi-390.html#post4773106

Regards,
Tim

**Comment by mikebrady** [comment]
Hi Tim. Thanks for the interesting post. Are you sure that the Soekris DAM1021 DAC will provide a 16/44.1 mode? I can't seem to find any specifications online.

**Comment by moodeaudio** [comment]
Hi Mike,

I'm not sure. I believe that both the USB-I2S board (Amanero) and the DAC (Soekris) have to be compatible with one another wrt audio format support.

Most of the DAC issues that come across my desk involve USB interface and the buggy Linux USB audio driver which is in need of a major update from the devs that maintain it.

-Tim

**Comment by mikebrady** [comment]
Thanks. The [web page](http://amanero.com) doesn't appear to state what input formats are supported.

**Comment by moodeaudio** [comment]
Hi Mike,

My interpretation is that the USB receiver accepts PCM input formats with bit depth of 32bit and sample rates of 44.1Khz 48Khz 88.2Khz 96Khz 176.4Khz 192Khz 352.8Khz 384Khz and then outputs an I2S signal to DAC of 32bit plus same PCM rates.

Apparently it can also accept DSD format and then output over I2S.

I'm just guessing but I think when ALSA examines the device descriptor for this device it indicates that it only accepts bit depth of 32, thus 16 or 24 bit files will undergo zero-padding by ALSA to 32 bit.

-Tim

**Comment by mistepien** [comment]
Instead of "hw:" use "plughw:". If you use "hw:" it means that stream is exactly compatible with alsa device. If you use "plughw:" additonal padding can be made by kernel.

**Comment by mikebrady** [comment]
Hi Tim. Can we close this issue, do you think? I'm doing some housekeeping :)

**Comment by moodeaudio** [comment]
Closed.
