### ISSUE TITLE
Shairport-sync on boot problem

### ISSUE THREAD

**Issue by yeralin** [mikebrady/shairport-sync#341]
Running machine: Linux raspberrypi 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux
Connection: Wi-Fi + AUX

After executing: `sudo systemctl enable shairport-sync`

Shairport-sync starts at boot, and is discoverable. But if I try to stream any music from my IPhone or Mac I hear only low-frequency noises. 

When I ssh into my raspberry pi, find the shairport-sync procces, kill it, and start it manually, everything is working fine.

What could be the problem? What type of log messages should I provide?

**Comment by mikebrady** [comment]
Hmm, that's interesting. Did you define the `shairport-sync` user and group?

**Comment by yeralin** [comment]
Output from:
```
daniyar@raspberrypi:~ $ groups shairport-sync
shairport-sync : shairport-sync audio
```
No, I didn't use any of these facilities.

I added `loglevel=2` to my /etc/cmdline.txt file
Now it looks like this:
```dwc_otg.lpm_enable=0 console=ttyAMA0,115200 loglevel=2 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait```

But when I execute: `sudo journalctl -n 1000`
It outputs: `No journal files were found.`
I tried to fix it, no good.

Instead I run: `dmesg`

And I got this output: http://pastebin.com/YPawyM8B

**Comment by mikebrady** [comment]
Hmm, the `group` and `user` stuff looks right. The `journalctl` stuff looks odd.

When I do `hostnamectl` on an Raspberry Pi B running Raspbian, I get:

```
pi@pioneer:~ $ hostnamectl 
   Static hostname: pioneer
         Icon name: computer
           Chassis: n/a
        Machine ID: 3882d14b5e8d408bb132425829ac6413
           Boot ID: 21e3736792f645c4a44580512bedf132
  Operating System: Raspbian GNU/Linux 8 (jessie)
            Kernel: Linux 4.4.14+
      Architecture: arm
pi@pioneer:~ $ 
```
The results from `uname -a` are:
```
Linux pioneer 4.4.14+ #896 Sat Jul 2 14:16:46 BST 2016 armv6l GNU/Linux
```

**Comment by yeralin** [comment]
I couldn't solve the problem. So, I just deleted service, and edited /etc/rc.local

Added:
`screen /usr/local/bin/shaiport-sync`
