### ISSUE TITLE
add max_volume config option to compliment new rpi audio_pwm_mode=2

### ISSUE THREAD

**Issue by rickwookie** [mikebrady/shairport-sync#342]
It would be very useful to add a max_volume (with default 100%) option to go with the volume_range, since as well as limiting the range to something useful on the Raspberry Pi, when using the new audio_pwm_mode=2 RPi /boot/config.txt option (which I would recommend to anyone that wants to get useable audio from the RPi's 3.5 mm socket!), sound is distorted at full volume. I think the recommendation is to not use the top 3 dB.
Ideally this would apply even when ignore_volume_control = "yes", since then the output would simply be fixed at max_volume, rather than 100%.

**Comment by mikebrady** [comment]
Thanks for this suggestion. Can you point us at some information about this new `audio_pwm_mode=2` please?

**Comment by rickwookie** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=136445

**Comment by rickwookie** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=136445

**Comment by mikebrady** [comment]
Thanks – I'll certainly have a look at this, but do you think that when it's finalised, the new Raspberry Pi audio driver will avoid the problem?

**Comment by rickwookie** [comment]
It's hard to tell. There's certainly at least one post there that mentions "squashing the volume table slightly", but it hasn't happened yet.
I do actually think this option would have wider uses. It's not uncommon to have several sources connected to an amp, each with fixed line outputs (e.g. CD player, tuner, etc) but they often have very different levels, so changing source requires a very rapid volume adjustment to avoid uncomfortable levels. Some aps allow gain values to by applied to the inputs to prevent this, but I think it would be very nice to be able to use AirPlay as a fixed input source, but still be able to set that relative level.

**Comment by roblan** [comment]
Shouldn't https://github.com/mikebrady/shairport-sync/pull/293 do the trick?

**Comment by rickwookie** [comment]
So using min_dB and max _dB values in ~/.asoundrc ?
What would be the disadvantage if any of using softvol when the RPi afaik has hardware (firmware) volume control?

**Comment by mikebrady** [comment]
I know it's an old issue, but FWIW, a `volume_max_db` feature was added to Shairport Sync some time back.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
