### ISSUE TITLE
How to configure multiple shairport-sync instances to use diffenet devices

### ISSUE THREAD

**Issue by shairportMulti** [mikebrady/shairport-sync#343]
I have four instances of shairport-sync running (explained in Issue #37) and i want that each of them uses ist own two channel output on a Sweex SC016 USB soundcard. Therefor i configured the .asoundrc as follows:

pcm.snd-card {
         type hw
         card 1
         device 0
}

ctl.snd-card {
         type hw
         card 1
         device 0
}

pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_perm 0666
    slave.pcm "snd-card"
    slave {
        period_time 0
        period_size 1024
        buffer_size 4096
#        rate 48000
        channels 8
    }
    bindings {
        0 0
        1 1
        2 2
        3 3
        4 4
        5 5
        6 6
        7 7
    }
}

pcm.!default {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
    ttable.0.6 1
    ttable.1.7 1
}

pcm.egbad {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.0 1
    ttable.1.1 1
}

pcm.egwohn {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.2 1
    ttable.1.3 1
}

pcm.egkueche {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.4 1
    ttable.1.5 1
}

pcm.ogbad {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.6 1
    ttable.1.7 1
}

pcm.alle {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
    ttable.0.6 1
    ttable.1.7 1
}

With aplay i can reach all devices (egbad, egwohn, egkueche, ogbad, alle) seperatly, e.g:
aplay -D egbad /usr/share/sounds/alsa/Front_Right.wav
aplay -D egwohn /usr/share/sounds/alsa/Front_Right.wav
aplay -D egkueche /usr/share/sounds/alsa/Front_Right.wav
aplay -D ogbad /usr/share/sounds/alsa/Front_Right.wav
aplay -D alle /usr/share/sounds/alsa/Front_Right.wav

But i can't figure out how to configure the shairport-sync.conf (the alsa part) to use egbad, egwohn egkueche, ogbad or alle.

**Comment by shairportMulti** [comment]
now it's working!
had to use the /etc/asound.conf instead of .asoundrc, now i know the answer it is pretty obvious.

**Comment by mikebrady** [comment]
Thanks for the information!
