### ISSUE TITLE
Am able to connect to shariport-sync service, but no sound.

### ISSUE THREAD

**Issue by klokop** [mikebrady/shairport-sync#349]
I'm using a Hifiberry DAC on a Pi B (?). This works fine in combination with spotify-connect, but although I can get an iPad to connect to the service, I can't get shairport-sync to produce any sound.

aplay -l info on the DAC:

```
pi@spotifyhuiskamer ~/git_shairport-sync_mikebrady $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

So far I've tried using these for the value of output_device:

```
output_device = "snd_rpi_hifiberry_dac";
output_device = "hw:0";
output_device = "sndrpihifiberry";
output_device = "default";
```

Yes, I did remember to restart the service after each change :) Also, the spotify-connect service was shut down during testing.

;(

**Comment by mikebrady** [comment]
It looks like `hw:0` should work, but it is a little curious – on my Raspberry Pi devices, `hw:0` is always the built-in DAC, which I do not disable. The last few lines of `/boot/config.txt` read:

```
# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

dtoverlay=hifiberry-dac
```
It might be worth trying. The Hifiberry DAC will then show up as `hw:1`:

```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Note that the Hifiberry DAC doesn't have a hardware volume control. No big deal, of course, and not a problem for Shairport Sync.

**Comment by klokop** [comment]
That seems to've fixed it, thanks! Even volume control works (surprisingly).
Except now spotify-connect won't output sound anymore (but it and shairport-sync won't work simultaneously anyway, so that's okay).

**Comment by mikebrady** [comment]
Great. It may be that spotify-connect is trying to play to `hw:0`, and, maybe (I'm only guessing this) it can be redirected to use `hw:1`...

**Comment by klokop** [comment]
Just in case anyone else has similar issues: using spotify-connect with 

     --device hw:sndrpihifiberry

solved this for me.

**Comment by mikebrady** [comment]
Thanks for that!

**Comment by Phosphor303** [comment]
I have almost exactly the same problem as the OP, but the suggested solution does not work for me. I am using a Hifiberry DAC+ on an RPi 3 with Raspbian Jessie.

**Original configuration:**
Output of `aplay -l`:
<pre><code>pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0</code></pre>

The only uncommented line in `/etc/shairport-sync.conf`:
<pre><code> output_device = "hw:0" </pre></code>

Outcome:
Sound originating from Raspberry Pi works fine. Airplay does not work.

**Configuration according to suggestions of @mikebrady**
Output of `aplay -l`:
<pre><code>pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0</pre></code>

The only uncommented line in `/etc/shairport-sync.conf`:
<pre><code> output_device = "hw:1" </pre></code>

Outcome:
Neither sound originating from Raspberry Pi nor Airplay does work.

Content of `/etc/asound.conf` in both cases:
<pre><code>pcm.!default  {
 type hw card 1
}
ctl.!default {
 type hw card 1
}</pre></code>
plus some configuration for another sound card that was not attached during testing.

**Comment by mikebrady** [comment]
When you specify the output device as a hardware device, as you did with `"hw:1"` above, the contents of `/etc/asound.conf` is irrelevant.

Doe the device have a mixer control? (Use `alsamixer` to find out.) If it does, you should either tell Shairport Sync about it or ensure it's turned up full.

**Comment by Phosphor303** [comment]
Using the configuration I referred to as "Original Configuration" and specifying the mixer as `hw:0` solved the problem. Thank you very much!

**Comment by supagu** [comment]
Hi,

Im trying to get this working on my Manjaro (arch based) machine. But not having much luck. I can connect, but I get no audio through my pc.....

aplay -l output:
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
**card 1: Generic [HD-Audio Generic], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0**
card 1: Generic [HD-Audio Generic], device 1: ALC892 Digital [ALC892 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

alasmixer shows a single device named "PulseAudio"

So I want to specify card 1 i marked in bold... How do I configure this?

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new issue if necessary.
