### ISSUE TITLE
No -M option to know what's playing on ?

### ISSUE THREAD

**Issue by miguelonthenet** [mikebrady/shairport-sync#35]
Hi,

Not sure if it's a regression, but on shairport, there was an option which store the Metadata in a file :
To enable the output of metadata, the -M <directory name> flag must be set to instruct shairport where to save the output. A fifo named now_playing will be created, and records will be written to it when tracks are changed. 

Would you get it work ? It might be usefull :)

Thanks for your work
Regards

Miguelonthenet

**Comment by mikebrady** [comment]
Hi @miguelonthenet. Thanks for your interest in shairport-sync. TBH the metadata is a not a feature I've thought of implementing. I was much more interested in getting synchronous audio to work properly. I can't promise when I'll get around to looking at it, though if it was properly implemented in the original shairport, it shouldn't be too hard to add back in.

**Comment by miguelonthenet** [comment]
Tks for your feedback !
I hope it will be taken into account one day, it will be usefull for my vintage radio to display the song played even on airplay.

Best Regards
Miguel

**Comment by mikebrady** [comment]
BTW, which version of shairport has the metadata option working well? I might take a look at the code...

**Comment by miguelonthenet** [comment]
https://github.com/abrasive/shairport#metadata
I did not check if it is working, I look for that only for 1 week :p

**Comment by mikebrady** [comment]
Thanks. Actually it looks fairly straightforward to re-incorporate the metadata stuff, so I'll give it a try in the next while, when work permits.

**Comment by moritzmhmk** [comment]
I did fork shairport last year just to fix coverart not being synchronous to the other metadata - hope it will help you make shairport-sync even more awesome :)

see: 
https://github.com/moritzmhmk/shairport/commit/c97006b8c4ed58fe8000a3eea0f94a60efe8fdc0
https://github.com/moritzmhmk/shairport/commit/9a2998e316539d7cea7533a6922dc3fddfb14ecb

**Comment by fnordism** [comment]
Maybe adding a function if Airplay doesn't fetch coverart, shairport-sync is executing a command; for example get-cover

https://github.com/DirectorX/get-cover

**Comment by mikebrady** [comment]
I'm trying to incorporate the metadata functionality from https://github.com/abrasive/shairport#metadata, but it is taking a little more time than I thought because I want to make is compatible with PolarSSL as well as OpenSSL...

**Comment by mikebrady** [comment]
I've done some work on this, a lot different from the original. Documentation is in the files rtsp.c and player.c. There is a sample metadata reader available in a new repository.

**Comment by mikebrady** [comment]
I'm going to close this issue, if that's okay. There's a metadata feature in the 2.3 branch now. Feel free to reopen this if necessary.
