### ISSUE TITLE
turn off mmap

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#351]
There is automatically mmap used in 2.8.4.5.
Please make a switch to turn it off.

**Comment by mistepien** [comment]
btw, are you sure that mmap is good?
see this:
http://git.musicpd.org/cgit/master/mpd.git/commit/?id=8ffcdb73e865ee6aff80db7cfcbdb44884b9ba95

**Comment by mikebrady** [comment]
Thanks for the suggestion. Some devices will not work without `mmap`. Is it actually causing problems in your situation?

**Comment by mistepien** [comment]
In fact I tested it in virtualbox and shairport hanged. Maybe that's a matter of bad luck, whatever.
For sake of support of new devices you change support of devices which already worked. MMAP is turn on automatically so now I have no choice. All I suggest is a switch in command line or in conf file to turn it off.

**Comment by mikebrady** [comment]
Thanks. I'll put it "on the list".

**Comment by mikebrady** [comment]
Pretty sure this has been done – see the configuration file. Thanks for this contribution.
