### ISSUE TITLE
No sound from OS X (Spotify Only)

### ISSUE THREAD

**Issue by mredone** [mikebrady/shairport-sync#352]
Hi.
I have problem with my shairport-sync in my omv machine.
Everything works from iOS 9, iTunes, Safari or other sounds from OS X 10.11.6

But Spotify on OS X connect to shairport but no sounds from speaker.

Here is my log from OS X

Thx for help

`05.08.2016 20:40:55,813 AirPlayXPCHelper[106]: 2016-08-05 08:40:55.813132 PM [APEndpointStreamAudio] Using transport compression type: ALAC, audio format: ALAC/44100/16/2
05.08.2016 20:40:55,815 AirPlayXPCHelper[106]: 2016-08-05 08:40:55.814550 PM [APEndpointStreamAudio] [0xD47F] audio endpoint stream resuming...
05.08.2016 20:40:55,815 AirPlayXPCHelper[106]: 2016-08-05 08:40:55.814719 PM [APEndpointStreamAudio] [0xD47F] audio endpoint stream suspending...
05.08.2016 20:40:55,819 AirPlayUIAgent[8118]: 2016-08-05 08:40:55.818685 PM [AirPlayAVSys] AirPlay became the default audio device
05.08.2016 20:40:56,135 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.134624 PM [APEndpointStreamAudio] [0xD47F] audio endpoint stream resuming...
05.08.2016 20:40:56,136 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.135605 PM [APTransportWifiManagerClient] 
Interface en1: Effective Data Transfer Rate = 0 Mi, Interface Open Percent = 0 , Expected Peak Latency = 64 ms, 
05.08.2016 20:40:56,146 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.146222 PM [APTransportConnectionHTTP] [0x3A24] httpconnection_asyncConnectionProgressed: Connecting to address: 192.168.1.7:5000
05.08.2016 20:40:56,146 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.146370 PM [APTransportTrafficRegistrar] APTransportTrafficRegistrar: MAC 00:00:00:00:00:00 has 0 connections, 1 require infrastructure
05.08.2016 20:40:56,147 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.146864 PM [WiFiManagerCore] ### Bind to fallback "awdl0" failed: -3900/0xFFFFF0C4 kA11ParamErr
05.08.2016 20:40:56,147 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.146948 PM [APTransportTrafficRegistrar] APTransportTrafficRegistrar: Register AirPlay traffic for AWDL at MAC 00:00:00:00:00:00 with target infra critical PeerIndication=2 err=-3900
05.08.2016 20:40:56,147 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.147062 PM [APTransportConnectionHTTP] httpconnection_asyncConnectionProgressed: register traffic failed with error kA11ParamErr
05.08.2016 20:40:56,148 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.147823 PM [APTransportConnectionHTTP] [0x3A24] httpconnection_asyncConnectionConnected: HTTPClient connected to 192.168.1.7:5000 (from 192.168.1.3:60497)
05.08.2016 20:40:56,148 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.147939 PM [APSenderSessionSDP] Received unhandled event from 'born' control stream.
05.08.2016 20:40:56,148 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.148317 PM [APEndpoint] Endpoint 0xB368 connected state changed: isConnected = true flags = 1
05.08.2016 20:40:56,176 AirPlayXPCHelper[106]: 2016-08-05 08:40:56.175588 PM [NTPClock] NTP server started on port 51680
05.08.2016 20:40:56,181 AirPlayUIAgent[8118]: 2016-08-05 08:40:56.180657 PM [AirPlayUIAgent] Prompt complete[0x9196] {
    finishedWithPromptInfo : 
    {
        ATVName : "MusicBox"
        savePassword : false
    }
}
05.08.2016 20:40:56,183 AirPlayUIAgent[8118]: 2016-08-05 08:40:56.181107 PM [AirPlayUIAgentUI] Authorization done for MusicBox
`

**Comment by mikebrady** [comment]
Thanks. Do you have any corresponding logs from Shairport Sync?

**Comment by mredone** [comment]
OpenMediaVault don't have logs for Shairport-sync from Gui.
Where shairport-sync save default logs?

**Comment by mikebrady** [comment]
Shairport Sync writes to the standard log, but, by default, it doesn't write much, so you need to change its `log_verbosity`. I've never used OpenMediaVault, so I don't know where the settings file is placed, but by default it is at `/etc/shairport-sync.conf`.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
