### ISSUE TITLE
Request: action on audio-detected 

### ISSUE THREAD

**Issue by jschwalbe** [mikebrady/shairport-sync#353]
I'm working on a project where I'd like to send an IR command when audio is being sent thru the device. Essentially I'd like to turn the speakers off when not in use. 
Is there currently a method to detect this?  Thanks!

**Comment by mikebrady** [comment]
Shairport Sync already has the ability to run scripts before play starts and after it ends – these could be used to turn the speakers on and off before and after a play session.

If your command could remotely control the source, then it could start and stop play, causing the scripts to run.

Some people know more about this, notably @roblan and @joerg-krause.

**Comment by jschwalbe** [comment]
Oh here we go:
```
     -B, --on-start=PROGRAM  run PROGRAM when playback is about to begin.
    -E, --on-stop=PROGRAM   run PROGRAM when playback has ended.
                            For -B and -E options, specify the full path to the program, e.g. /usr/bin/logger.
                            Executable scripts work, but must have #!/bin/sh (or whatever) in the headline.
```
Sorry, just missed that earlier. Thanks!
