### ISSUE TITLE
Run_After_Stop issue

### ISSUE THREAD

**Issue by corrpel** [mikebrady/shairport-sync#354]
Hi,
Can we do something about the IDLE state of the shairport-sync?
Even if you are connected after ~ 15 seconds of no audio the script will run.
It would be good to run after you disconnect from it or include a "shairport-status".
ex: run shairport-sync -stat and will return the following:
1. inuse
2. ready

Then we can create a script to monitor the status of shairport-sync and run it based on status.
Thanks.

**Comment by mikebrady** [comment]
Thanks for the suggestion. However, to do what you ask would be tricky, and in my view, unnecessary.

It would be tricky because it would require a separate instance of Shairport Sync to try to communicate with another one. This will be messy.

You could do something simpler using the facility Shairport Sync already has to run a script before and after it plays to set and clear some kind of a flag – maybe create and delete a file.

**Comment by corrpel** [comment]
Yes you are right! But what can we do to avoid running the process(run_this_after_play_ends) when IDLE. For example, i have mplayer playing an online radio stream when i am not connected to shairport-sync. The issue is that i remain connected with no sound playing, the script will run after ~15 seconds of silence. Maybe include a "silent" signal every 5 seconds when IDLE and activage in config to avoid runing the after play script?! Thank you for your hard work on this awesome software btw :)

**Comment by mikebrady** [comment]
I'm afraid I still don't understand. Am I right in thinking that you want a mechanism to detect if Shairport Sync is playing silence?

**Comment by corrpel** [comment]
Hi @mikebrady.
What i want is run_this_after_disconnect instead of run_this_after_play_ends.
When i am connected to shairport-sync and i don't play anything for about 15 seconds the shairport-sync executes "run_this_after_play_ends" when i am still connected to the received. But what i actually want is shairport-sync execute this when the connection is lost or i manually disconnect from the receiver. Sorry for misunderstanding i was trying also to provide an idea for a solution.
Thank you for your patience :))

**Comment by mikebrady** [comment]
Okay, I understand now, thanks. I'd really prefer to do this using piped metadata messages; let me look into doing that.

**Comment by joerg-krause** [comment]
Yes, you can use the metadata pipe and wait for the `pend` code.

**Comment by mikebrady** [comment]
But see #366. Some work is needed on making the metadata signals more reliable.

**Comment by mikebrady** [comment]
The new `active` mode and associated signals may help here. Please open a new issue if necessary.
