### ISSUE TITLE
Using on systemd OS

### ISSUE THREAD

**Issue by cadavre** [mikebrady/shairport-sync#361]
Commands like `shairport-sync -D` cannot be called because of no `/var/run/shairport-sync.pid` file on `systemd` systems. Any idea how to use such things as `-D`?

**Comment by p3ck** [comment]
I haven't tested this but it might be possible to write out the PID by adding this to the service file.

ExecStartPost=/usr/bin/bash -c "echo $MAINPID > /var/run/shairport-sync.pid"

**Comment by cadavre** [comment]
Thanks for pointing this out!
Finally:
```
ExecStartPost=/bin/bash -c 'pgrep shairport-sync > /var/run/shairport-sync.pid'
PermissionsStartOnly=true
```
