### ISSUE TITLE
30sec silence/delay after pause

### ISSUE THREAD

**Issue by lrbalt** [mikebrady/shairport-sync#362]
Hi

I'm using latest master. I have a player that receives samples from shairport-sync using the `pipe` backend. 
* When I start music on shairport-sync and then attach the player to shairport-sync, music plays
* When I pause the music and quickly start playing again, all goes well
* When I pause the music a bit longer and shairport-sync closes the player thread, after resuming play it takes about 30s for the music to actually start. 
* When I start shairport-sync, attach the player and then start to play music, the 30s delay is there too
* I do not notice this using the alsa backend

So I think it has something to do with starting the play thread on shairport-sync. All music is actually delayed, so skipping to the next song will be heard after 30s from hitting the next button. Same for changing volume, it takes 30s to notice the change.

On the player end, the read on the pipe blocks right after shairport-sync receives the pause. When shairport-sync resumes, the pipe unblocked immediately. During the 30s (i.e. 30*44100 samples) the player receives `0` over the pipe. So currently I ignore all 0 values after the read unblocks so the gap is ignored. 

I think it is about 5MB of zero's (`30*44100*2ch*16bit`), so is this a buffer of Linux or some buffer within shairport-sync?

I've set `audio_backend_buffer_desired_length` to 441

**Comment by mikebrady** [comment]
Thanks for this report. Let me think about it for a while. I'd be surprised to find that Shairport Sync is outputting zeros during a pause. Have you tried a different player, to see if it makes a difference?

**Comment by mikebrady** [comment]
The player that I'd try is `aplay`. Is that what you've been using? I might try to replicate the situation.

**Comment by lrbalt** [comment]
I've been using my own player which does a non-blocking read on the pipe that Shairport Sync is using. I'll try aplay and report back. I did not know aplay can read from a pipe other than stdin/stdout. But a simple `cat /path/to/pipe | aplay` should probably do the trick. Never thought of that :-)

**Comment by mikebrady** [comment]
You'll need to tell `aplay` the format of the feed. I think the command line argument is `-f cd`, but I don't have a computer near me to check.

**Comment by lrbalt** [comment]
I'll figure it out, thanks!

**Comment by mikebrady** [comment]
Just did a quick check on a Raspberry Pi, and I'm not getting that long delay, even after letting the player thread close down. I get some diagnostics from Shairport Sync, but the delay is short – just a few seconds. Here is where I start Shairport Sync:
```
pi@pioneer:~ $ shairport-sync -o pipe -- /tmp/sps
```

Here is where I start `aplay`:

```
pi@pioneer:~ $ cat /tmp/sps | aplay -f cd -d hw:0
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
^CAborted by signal Interrupt...
```

Here is some of the Shairport Sync log:
```
 New RTSP connection from 192.168.2.1:49265 to self at 192.168.2.7:5000.
Play connection from user agent "iTunes/12.4.3 (Macintosh; OS X 10.11.6)".
Active-Remote string seen: "567477703".
DACP-ID string seen: "900B806C3A8FAA81".
Set up play connection from 192.168.2.1 to self at 192.168.2.7.
total packets, missing packets, late packets, too late packets, resend requests, min buffer occupancy, max buffer occupancy
First packet is late! It should have played before now. Flushing 0.1 seconds
First packet is late! It should have played before now. Flushing 0.1 seconds
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
```

**Comment by lrbalt** [comment]
I've just checked with aplay. I get about 3 seconds of delay. So the problem is probably something in my player or the libs I'm using, not Shairport Sync. Thanks for helping me analyse this issue. Closing.
