### ISSUE TITLE
Is there anyway to get rPi 3 with Jessie running shairport over Bluetooth?

### ISSUE THREAD

**Issue by biogerm** [mikebrady/shairport-sync#363]
Hi,

I am trying to setup rPi 3 as a AirPlayer receiver that send music to a bluetooth speaker without success.

I have tried [this method](https://github.com/mikebrady/shairport-sync/issues/200) but it doesn't seem to work. Probably the software on the latest Jessie is too new for shairport? 

Any ideas?

BR
Ryan

**Comment by biogerm** [comment]
btw through 3.5mm it works fine. but my speaker locates at a bad place that wifi is very weak... and i hate long cables hanging..

**Comment by mikebrady** [comment]
I've never really tried to do anything with Bluetooth audio, I'm afraid. Shairport Sync does not support Bluetooth, and never has in the past. Shairport Sync runs very well on the latest Jessie.

**Comment by biogerm** [comment]
I guess since rPi 3 is integrated with bt/wifi, more and more people might start to have this idea to connect to a bt receiver/speaker/headphone.

**Comment by mikebrady** [comment]
Thanks, yeah. If somebody (else!) can properly hook up a Bluetooth speaker through ALSA, then Shairport Sync might be able to use it...
