### ISSUE TITLE
Problem with avahi-deamon?!

### ISSUE THREAD

**Issue by anmue** [mikebrady/shairport-sync#364]
Hi,

i have a problem on startup after i installed a "Timecapsule" with netatalk.

Before i started the pi and shairport worked fine. Now i get an issue.

My Timecapsule isn't in autostart now. I start it with a script 
/home/USER/timecapsule start 

after i started this script shairport stops/freez?

when i get them a service shairport-sync restart. shairport works again. 

So i don't no is it a problem from shairport or my script makes the issue. 

when i manually restart ahavi-deamon that make no issue for shairport. 

[timecapsule.txt](https://github.com/mikebrady/shairport-sync/files/453253/timecapsule.txt)

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. The problem seems to be with your script:

```#!/bin/bash
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi
case "$1" in
    start)
        service avahi-daemon stop
        umount -l /media/TimeCapsule
        mount -t hfsplus -o force /dev/sda1 /media/TimeCapsule/
        service avahi-daemon start
	echo "TimeCapsule hochgefahren"
    ;;
    stop)
        service netatalk stop
        service avahi-daemon stop
        umount -l /media/TimeCapsule
	echo "TimeCasule heruntergefahren"
    ;;
    *)
        echo "Usage: timecapsule {start|stop}"
        exit 1
    ;;
esac
exit 0
```
Your script stops the `avahi-daemon` service, and that's probably what stops Shairport Sync. I say "probably" because it does stop Shairport Sync on Ubuntu 16.04 but you don't say what Linux are you using. BTW, why are you stopping the `avahi-daemon` service anyway?

**Comment by anmue** [comment]
hey mike. thx for your answer.

the script was from an tutorial not from myself. i have modify it and  it works now . 
I delete the start and stop command for the avahi-daemon. 

But when in the old script avahi-deamon start again after mount /sda1. Why that shairsyc not work? when i restart avahi daemon manually with "service avahi-daemon restart" shairport worked again after a short time. 
And it must be successfully started with the old script then de netatalk "time capsule" worked fine. 

So is only a question i ask myself. But now both work fine with the new script. 

I used bananian on my banana-pi is a debian-jessie.

**Comment by mikebrady** [comment]
I'm afraid I don't know why Shairport Sync does not restart after the `avahi-daemon` is restarted. It could be a myriad of things, and I've never really thought about it, because it's a situation that should not normally arise. 

I'm glad it's working properly for you now.
