### ISSUE TITLE
Package.mk for LibreELEC on RPi

### ISSUE THREAD

**Issue by Starbix** [mikebrady/shairport-sync#365]
Hi, would it be possible to write a [package.mk](https://github.com/Starbix/LibreELEC.tv/blob/master/packages/graphics/hyperion/package.mk) for [LibreELEC](https://github.com/plexinc/LibreELEC.tv), especially RPi? 
I think all dependencies are already there except libpopt and OpenSSL (there's LibreSSL instead) and there is a package called soxr, not sure if it's the correct one, but I won't use it anyways.

**Comment by philion** [comment]
Starbix, I might be interested in doing that. I've got shairport-sync on a couple of RPis and now I want it on my OpenPHT RPi.

I'll have to research LibreELEC.

**Comment by PeterPablo** [comment]
@philion, do you have news? I found a report [https://forum.libreelec.tv/thread-1228.html](here), where somebody else wanted the same.

**Comment by Starbix** [comment]
@philion any update on this?
