### ISSUE TITLE
Detecting resume of a stopped playback

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#366]
I have an issue switching playback between shairport-sync and MPD on my audio device.

I am using the onstart script to manage the audio device between both:

```
if shairport then
  stop MPD
  reconnect shairport to audio device (-R)
else if MPD then
  disconnect shairport from the audio device (-D)
  do http request to DACP server (iTunes) issuing a stop command
end
```

This works fine if I wait until iTunes really ends the sessions. Unfortunately, iTunes needs about 10 to 15 seconds before this happens and shairport-sync runs the stop script and emits the `pend` to the metadata pipe. If I press the Play button in iTunes after the session has ended, a new session and therefore playback is started and shairport-sync runs the start script and emits the `pbeg` code.

However, if I restart the playback from iTunes before the session has ended, no start script or `pbeg` is emitted making it impossible to manage the audio device properly and end the MPD stream and reconnect shairport-sync to the audio device.

The only codes I receive when pressing Play after issuing a Stop before are `mdst`, `mden`, `prgr`.

Is it possible to detect that iTunes resumes the playback?

**Comment by joerg-krause** [comment]
I did some investigations and I noticed that shairport-sync does not emit the `prsm` code if it is disconnected from the audio output via `-D`.

Is there any reason for this?

**Comment by mikebrady** [comment]
Hi Jörg-Krause. Thanks for your posts. Two things: first, I'm intending to deprecate the `-D` and the `-R` options. The reason is that the only way to implement them is using Unix signals, and I'd prefer to use the signals for something else.

Second, the generation of the pause and resume metadata signals needs to be overhauled. It's not always reliable. I'll look at trying to rethink it in the next while.

**Comment by joerg-krause** [comment]
> Two things: first, I'm intending to deprecate the -D and the -R options. The reason is that the only way to implement them is using Unix signals, and I'd prefer to use the signals for something else.

I am curious what that might be. Maybe there is another way to implement the behavior of the `-D` and `-R` options.

> Second, the generation of the pause and resume metadata signals needs to be overhauled. It's not always reliable. I'll look at trying to rethink it in the next while.

Many thanks for rethinking! I wonder, why iOS Music and iTunes behaves so different. iOS tears down the  session after issuing a "Stop" command within a four seconds, wheres iTunes waits 10 seconds.

Unfortunately, this is a bad user experience, if I want to switch from AirPlay to MPD via emitting a "Stop" command and have to wait for 10 seconds before MPD can access the audio output device and playback begins.

If there is anything I can do, please tell me!

**Comment by joerg-krause** [comment]
I am using a little helper script now which evaluates the metadata coming from the AirPlay- or iTunes-Server after issuing a "Stop" command. If the server sends certain metadata fields before shairport-sync issues the `pend` code, the script stops MPD and reconnects shairport-sync to the audio output.
