### ISSUE TITLE
soxr quality setting

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#367]
soxr has few settings regarding quality: low, medium, high and very high.
it would be great to have possibility to choose one of them depending available resources.
very handy on small, embedded systems!

**Comment by mikebrady** [comment]
Thanks for the suggestion. Shairport Sync uses the `soxr_oneshot` call which uses `SOXR_LQ` by default, i.e. not quite the lowest quality.... I'll put it on the list on things to add, but it's not very high up, TBH.

**Comment by mikebrady** [comment]
I'm afraid I haven't done this, and TBH am unlikely. I have a better idea...
