### ISSUE TITLE
iOS10 - not compatible anymore?

### ISSUE THREAD

**Issue by zackdvd** [mikebrady/shairport-sync#368]
It seems that shairport-sync does not work with iOS10, can anybody confirm that?
Always showing "Searching for Apple TV"...

**Comment by Yannik25** [comment]
It works, swipe up to the control center, then swipe to the right and down there you can select your speaker.

**Comment by zackdvd** [comment]
Oh sorry, mixed up the new AirPlay option, maybe thats only for mirrowing.
You are right, swipe to right and everything works! Thanks for the quick answer

**Comment by mikebrady** [comment]
Yes indeed, it works with iOS 10 and with the latest iTunes. Let's hope it works with macOS Sierra next week.

**Comment by DannyBoyKN** [comment]
Indeed, just looked at the AirPlay option when swiping up the control center ... shame on me

**Comment by mikebrady** [comment]
Excellent – the right answer arrived at!
