### ISSUE TITLE
Failed to attach mixer

### ISSUE THREAD

**Issue by mazaxaka** [mikebrady/shairport-sync#369]
I have shairport-sync installed on raspberrt pi with arch linux

config file is:
```
general =
{
   name = "Kitchen";
   interpolation = "basic";
   output_backend = "alsa";
   mdns_backend = "avahi";
};

alsa =
{
  output_device = "default";
  mixer_control_name = "PCM";
};
```

when i execute systemctl start shairport-sync 
and check status systemctl status shairport-sync

i get this
```
[root@alarmpi ~]# systemctl status shairport-sync
* shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/usr/lib/systemd/system/shairport-sync.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2016-07-30 23:24:41 MDT; 1 months 18 days ago
 Main PID: 186 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           `-186 /usr/bin/shairport-sync

Jul 30 23:24:41 alarmpi systemd[1]: Started ShairportSync AirTunes receiver.
Jul 30 23:24:42 alarmpi shairport-sync[186]: Failed to attach mixer
```

date on raspberry is incorrect

but when i execute 
`shairport-sync -a kitchen  -d 'default' -c Surround `
evrything is ok

what i'm doing wrong?

**Comment by mikebrady** [comment]
Hi there. thanks for trying Shairport Sync. You have given two different mixer control names – in the config file you've given "PCM" and in the command line, you've given "Surround". It looks like "Surround" is the right one...
