### ISSUE TITLE
multiple instances of shairport-sync on one machine

### ISSUE THREAD

**Issue by tristan-k** [mikebrady/shairport-sync#37]
Is it possible to run more than one shairport-sync instance on one machine? I'm using a raspberry pi with shairport-sync and a bluetooth speaker but I would also like to run another instance on the same machine which makes use of a usb audio device. 

First process:  
``` start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Shairport (bluetooth)" -- -d bluetooth || return 2 ```

Second process: 

``` start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Shairport (USB-Audio)" -- -d hw:1  || return 2 ```

Is this possible?

**Comment by mikebrady** [comment]
I haven't tried this, and I'm not sure about how they would interact with the start-stop stuff.
Two instances of Shairport Sync can run if:
1. Neither one uses the -d (--daemon) option. This is because an instance checks to see if another instance is running by checking for the existence of the PID file.
2. Both listen on different ports – use the -p option to select a port;
3. Both have different service names – use the -a option.

It looks like you're using the -d (daemon) option above and you don't select different ports – both of these would cause problems. I'm afraid you'll have to experiment with the start-stop mechanism to see if you can

**Comment by axel-j** [comment]
It's actually quite easy. Create a symbolic link to shairport-sync name shairport-sync2 or similiary. Then, duplicate the startup file in /etc/init.d and replace all references to shairport-sync by shairport-sync2. Don't forget the Provides: shairport-sync at the beginning.
Finally, run update-rc.d and you're done.

I hope, I haven't forgotton anything, but there was no real problem.

**Comment by mikebrady** [comment]
Thanks! I tried this out and it works perfectly and gets around the `-d` or `--daemon` problem I identified earlier. I think this closes the issue.

**Comment by tristan-k** [comment]
Thanks!

**Comment by rolarga** [comment]
Hello there,

I tried the solution with symbolic link. The different shairport-sync instances start and i can stream to one of them. As soon as i start the second streaming, my rasperry pi crashes and reboots.

What i did:
/usr/local/bin contains shairport-sync, shairport-sync1, shairport-sync2, shairport-sync4
/etc/ contains shairport-sync.conf,  shairport-sync1.conf,  shairport-sync2.conf,  shairport-sync3.conf (each configuration uses its own Port and UPD Port Range as well as output_device)
/etc/init.d/ contains shairport-sync,shairport-sync1, shairport-sync2, shairport-sync3 (i renamed everything to use the corresponding shairport-sync in /usr/local/bin)

As mentioned, it populates the airports and i can see them on my iPad, iPhone and on PC but as soon as i start to stream to the second one. Buuum... 

Can someone help me with this issue?

Thank you very much.

Yves

**Comment by cre8dojo** [comment]
What I did without multiple copies of /usr/local/bin/shairport-sync dir (assuming using systemd)

make one copy of the /lib/systemd/system/shairport-sync.service and name like:

sudo cp /lib/systemd/system/shairport-sync.service /lib/systemd/system/shairport-sync@.service

in side that new .service file:
`
[Unit]
Description=ShairportSync AirTunes receiver %I
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service

[Service]
ExecStart=/usr/local/bin/shairport-sync -c /etc/shairport-sync%I.conf
User=shairport-sync
Group=shairport-sync
SyslogIdentifier=shairport-sync-%I

[Install]
WantedBy=multi-user.target
`

Now make a copy on the /etc/shairport-sync.conf for ever instance/Zone you want:

/etc/shairport-syncZone1.conf
/etc/shairport-syncZone2.conf
/etc/shairport-syncZone3.conf

Modify the zone confs as needs with unique ports, upd port, names, output_device, etc

then start with:

sudo systemctl start shairport-sync@Zone1
sudo systemctl start shairport-sync@Zone2
etc

or enable to auto start with

sudo systemctl enable shairport-sync@Zone1
sudo systemctl enable shairport-sync@Zone2
etc

replace 'Zone1', Zone2' with your Zone names e.g. 
sudo systemctl enable shairport-sync@Patio
sudo systemctl enable shairport-sync@Upstairs

with corresponding confs:
/etc/shairport-syncPatio.conf
/etc/shairport-syncUpstairs.conf

Note @ symbol in systemctl command and .service filename/contents BUT NOT in conf file names.

**Comment by shairportMulti** [comment]
@cre8dojo:
your solution works perfectly!

But i have an other Problem:
I have four instances of shairport-sync running and i want that each of them uses ist own two channel output on a Sweex SC016 USB soundcard. Therefor i configured the .asoundrc as follows:

pcm.snd-card {
         type hw
         card 1
         device 0
}

ctl.snd-card {
         type hw
         card 1
         device 0
}

pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_perm 0666
    slave.pcm "snd-card"
    slave {
        period_time 0
        period_size 1024
        buffer_size 4096
#        rate 48000
        channels 8
    }
    bindings {
        0 0
        1 1
        2 2
        3 3
        4 4
        5 5
        6 6
        7 7
    }
}

pcm.!default {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
    ttable.0.6 1
    ttable.1.7 1
}

pcm.egbad {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.0 1
    ttable.1.1 1
}

pcm.egwohn {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.2 1
    ttable.1.3 1
}

pcm.egkueche {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.4 1
    ttable.1.5 1
}

pcm.ogbad {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.6 1
    ttable.1.7 1
}

pcm.alle {
    type plug
    slave {
        pcm "dmixer"
        channels 8
    }
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
    ttable.0.6 1
    ttable.1.7 1
}

With aplay i can reach all devices (egbad, egwohn, egkueche, ogbad, alle) seperatly, e.g:
aplay -D egbad /usr/share/sounds/alsa/Front_Right.wav
aplay -D egwohn /usr/share/sounds/alsa/Front_Right.wav
aplay -D egkueche /usr/share/sounds/alsa/Front_Right.wav
aplay -D ogbad /usr/share/sounds/alsa/Front_Right.wav
aplay -D alle /usr/share/sounds/alsa/Front_Right.wav

But i can't figure out how to configure the shairport-sync.conf (the alsa part) to use egbad, egwohn egkueche, ogbad or alle.

**Comment by dan-cristian** [comment]
@cre8dojo:
thanks, your solution works well but with one change, port value in conf file must be changed to a unique value for each zone (5000, 5001, etc)

general =
{
port=5000;
}

**Comment by magichew** [comment]
Hi

I think I've followed these steps to the letter but none of the devices show in my AirPlay options on my phone (or laptop).

Do I need to delete or adjust the shairport-sync.conf file to allow the others to be read?

**Comment by samhorne2** [comment]
Hey there!
I followed cre8dojo's instructions perfectly,  but when I initiate each additional instance, they broadcast as a single "raspberrypi" AirPlay receiver instead of the corresponding names.
Here is a rundown of my .conf files and corresponding names:
shairport-sync.conf is named "Kitchen"
shairport-syncZone1.conf is named "Office"
shairport-syncZone2.conf is names "Garage"

When I start all of them, all I see is "Kitchen", and "raspberrypi".
What should I change to get the broadcast to reflect my zone names?
Thanks

**Comment by mdsflyer** [comment]
I've followed the guide above exactly and can see the files in the correct folders. The standard shairport-sync service for raspberrypi is running and works. However when I try the command sudo systemctl start shairport-sync@Zone1 Terminal pauses for a nano second, then goes to a new line. No second zone, I'm relatively new to raspberry pi but have run shairport for windows successfully previously. I'd be grateful if anyone could help me figure out what I am doing wrong.

**Comment by magichew** [comment]
Can someone please tell me how I remove the default "Raspberry Pi" speaker in the AirPlay list as pictured? I'm guessing this is the built in output but I'm using USB sounds cards for my zones as the built in output had a lot of noise on it. 
![img_5bdde602260a-1](https://user-images.githubusercontent.com/5846333/36074401-7226f398-0f37-11e8-9bd8-5865646c6d3b.jpeg)

**Comment by buttercool** [comment]
> What I did without multiple copies of /usr/local/bin/shairport-sync dir (assuming using systemd)
> 
> make one copy of the /lib/systemd/system/shairport-sync.service and name like:
> 
> sudo cp /lib/systemd/system/shairport-sync.service /lib/systemd/system/shairport-sync@.service
> 
> inside that new .service file: ` [Unit] Description=ShairportSync AirTunes receiver %I After=sound.target Requires=avahi-daemon.service After=avahi-daemon.service
> 
> [Service] ExecStart=/usr/local/bin/shairport-sync -c /etc/shairport-sync%I.conf User=shairport-sync Group=shairport-sync SyslogIdentifier=shairport-sync-%I
> 
> [Install] WantedBy=multi-user.target `
> 
> Now make a copy of the /etc/shairport-sync.conf for ever instance/Zone you want:
> 
> /etc/shairport-syncZone1.conf /etc/shairport-syncZone2.conf /etc/shairport-syncZone3.conf
> 
> Modify the zone confs as needs with unique ports, upd port, names, output_device, etc
> 
> then start with:
> 
> sudo systemctl start shairport-sync@Zone1 sudo systemctl start shairport-sync@Zone2 etc
> 
> or enable to auto start with
> 
> sudo systemctl enable shairport-sync@Zone1 sudo systemctl enable shairport-sync@Zone2 etc
> 
> replace 'Zone1', Zone2' with your Zone names e.g. sudo systemctl enable shairport-sync@Patio sudo systemctl enable shairport-sync@Upstairs
> 
> with corresponding confs: /etc/shairport-syncPatio.conf /etc/shairport-syncUpstairs.conf
> 
> Note @ symbol in systemctl command and .service filename/contents BUT NOT in conf file names.

I still go back to this reply years later as it is a great reference for reliably running multiple instances of shairport-sync. Thank you!

Recent updates require some slight changes to the shairport-sync@.service file like seen here: https://github.com/buttercool/barsky_rpi_airplay_server_role/blob/main/files/shairport-sync%40.service
