### ISSUE TITLE
Bind to wi-fi

### ISSUE THREAD

**Issue by mazaxaka** [mikebrady/shairport-sync#370]
i have shairport-sync installded on raspberyy pi with arch linux7 When Raspberry connected wia ethernet evrything is ok, but when it connected only wia wi-fi I can't stream music to it. May be i should add some special setting?

**Comment by mikebrady** [comment]
Shairport Sync works fine over WiFi.

Here are some things to check: 
* If you have had Ethernet connected and disconnected it to try the WiFi without rebooting, then Avahi may not transfer to the WiFi network so that Shairport Sync would be invisible. Try rebooting the Pi with Ethernet completely disconnected.
* Another possibility is that "power management" is enabled on the WiFi chip, causing it to lose connection when the network is idle. You should ensure WiFi power management is off.

**Comment by mazaxaka** [comment]
```
[root@alarmpi ~]# iw dev wlan0 get power_save
Power save: off
[root@alarmpi ~]# systemctl status avahi-daemon
* avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/usr/lib/systemd/system/avahi-daemon.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2016-07-30 23:24:41 MDT; 1min 14s ago
 Main PID: 171 (avahi-daemon)
   Status: "avahi-daemon 0.6.32 starting up."
   CGroup: /system.slice/avahi-daemon.service
           |-171 avahi-daemon: running [alarmpi.local]
           `-174 avahi-daemon: chroot helper

Jul 30 23:24:41 alarmpi avahi-daemon[171]: No service file found in /etc/avahi/services.
Jul 30 23:24:41 alarmpi systemd[1]: Started Avahi mDNS/DNS-SD Stack.
Jul 30 23:24:41 alarmpi avahi-daemon[171]: socket() failed: Address family not supported by protocol
Jul 30 23:24:41 alarmpi avahi-daemon[171]: Failed to create IPv6 socket, proceeding in IPv4 only mode
Jul 30 23:24:41 alarmpi avahi-daemon[171]: socket() failed: Address family not supported by protocol
Jul 30 23:24:41 alarmpi avahi-daemon[171]: Network interface enumeration completed.
Jul 30 23:24:41 alarmpi avahi-daemon[171]: Server startup complete. Host name is alarmpi.local. Local service cookie is 2068057
Jul 30 23:24:58 alarmpi avahi-daemon[171]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.2.244.
Jul 30 23:24:58 alarmpi avahi-daemon[171]: New relevant interface wlan0.IPv4 for mDNS.
Jul 30 23:24:58 alarmpi avahi-daemon[171]: Registering new address record for 192.168.2.244 on wlan0.IPv4.

[root@alarmpi ~]# systemctl status shairport-sync
* shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/usr/lib/systemd/system/shairport-sync.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2016-07-30 23:24:59 MDT; 1min 9s ago
 Main PID: 286 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           `-286 /usr/bin/shairport-sync

Jul 30 23:24:59 alarmpi systemd[1]: Started ShairportSync AirTunes receiver.
Jul 30 23:24:59 alarmpi shairport-sync[286]: Successful Startup
[root@alarmpi ~]# 
```

Ethernet disconnected, power managment disabled, but i still cat see my device on my apple devices, may be something else?

**Comment by mikebrady** [comment]
Good stuff. There is some weirdness with your IPv6 setup, but I don't know if it's relevant.

It looks like Shairport Sync has started up properly – set it's log verbosity to 2 to see information from the avahi subsystem showing the registering of the service, e.g:
```
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service '9837B4D4B99B@Sample' group is not yet commited.
avahi: request to add "_raop._tcp" service without metadata
avahi: service '9837B4D4B99B@ Sample' group is registering.
avahi: service '9837B4D4B99B@ Sample' successfully added.
```
If you are getting something like that, then something else may be wrong with your network. I suggest you check that the Bonjour/Zeroconf services are being propagated around your network properly. Use `avahi-browse` in the `avahi-utitls` package on the Pi, and use an equivalent tool at the other end, e.g. "Bonjour Browser" on a Mac or "Discovery" on an iOS device. A slightly weird thing is that sometimes routers too not allow multicast to propagate properly between wired and wireless connections or are just plain buggy.

**Comment by mazaxaka** [comment]
Thank you! Problem was in router.
