### ISSUE TITLE
Not an issue, but I do not know how to reach you otherwise!

### ISSUE THREAD

**Issue by SirVer** [mikebrady/shairport-sync#371]
Thumps up to this project! I got it up and running on my raspberry pi in < 10 minutes including compilation, configuration, setup of groups and working around the terrible audio jack of the raspberry pi with the `db_range` settings.

Your code works, your documentation is easy to understand, easy to follow and comprehensive. This repo is a prime example of quality engineering!

Thank you. 

(Feel free to close right away)

**Comment by mikebrady** [comment]
Many thanks! I might leave this "issue" open for a little while :)

**Comment by crest42** [comment]
Hi Mike,

i am using shairport-sync over a year now with arch linux running on an odroid u3.

I had exactly the same experience with this project, so also a big "thank you" from my side :+1:

**Comment by attndeficit** [comment]
I'm going to add my gratitude as well... I've been using this for over a year in a warehouse setting.  I have 6 thin clients I saved from the garbage spread about my warehouse with Tiny Core Linux netbooted and speakers attached (no screens, id like to replace these with raspi someday).  Each has shairport-sync.  I use forked-daapd with iTunes Remote to stream to them all in wonderfully perfect sync, then I just control it from my watch/phone.

Outstanding work, sir...

**Thank you!**

**Comment by mikebrady** [comment]
Thanks everyone!
