### ISSUE TITLE
Version 2.8.5

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#374]
Many thanks for the new release!

There are two tag versions out now, [V2.8.5](https://github.com/mikebrady/shairport-sync/releases/tag/V2.8.5) and [2.8.5](https://github.com/mikebrady/shairport-sync/tree/2.8.5). Also, the version is still marked as *Pre-release*.

**Comment by mikebrady** [comment]
Yeah, the one called 2.8.5 is the likely release. I'm deleted V2.8.5.

**Comment by joerg-krause** [comment]
Did you pushed the deletion to github?

**Comment by mikebrady** [comment]
Sure did. I'll check later and make 2.8.5 a full release.

**Comment by mikebrady** [comment]
Hi @joerg-krause. I made 2.8.5 a full release.

**Comment by joerg-krause** [comment]
Thanks! Note, that there is still a V2.8.5 tag...

**Comment by mikebrady** [comment]
Thanks – now I understand. The tag is now gone as well as the release.

**Comment by joerg-krause** [comment]
Great! Closing now.
