### ISSUE TITLE
use_mmap_if_available options does not work

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#376]
I set use_mmap_if_available="no" in 2.8.5
and it changes nothing.
MMAP_INTERLEAVED is used like before.

edit: in 2.8.4 on my usb device there is always MMAP_INTERLEAVED,
meanwhile mpd plays RW_INTERLEAVED.
2.8.4 is not mmap capable per se.
So what is wrong?

mpd uses hw, shairport-sync uses plughw: this is necessary because device is 24_3LE and shairport cannot change by itself bit depth of output.
none of them is playing simultanously.

**Comment by mikebrady** [comment]
Hmm. The setting seems to work for me on a Ubuntu 16.04 in VMWare Fusion. The sound card can do MMAP or RW and the setting. If you set log verbosity to 2 (i.e. use `-vv`), you get the following if mmap is allowed:

```
Output written using MMAP
PCM handle name = 'hw:0'
alsa device parameters:
  access type = MMAP_INTERLEAVED
  format = 'S16_LE' (Signed 16 bit Little Endian)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 16
```
and you get this if it's not allowed:
```
Output written with RW
PCM handle name = 'hw:0'
alsa device parameters:
  access type = RW_INTERLEAVED
  format = 'S16_LE' (Signed 16 bit Little Endian)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 16
```
Can you post the equivalent please?

Also, separately, can your device accept S24_LE or S32_LE?

**Comment by mistepien** [comment]
ok, I got.

syncing to seqno 26522.
Output written with RW
PCM handle name = 'plughw:V102,0'
alsa device parameters:
  access type = RW_INTERLEAVED
  format = 'S16_LE' (Signed 16 bit Little Endian)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 16
  rate = 44100 frames per second (precisely).
  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
  period_time = 5011 us (>).
  period_size = 221 frames (precisely).
  buffer_time = 3962857 us (>).
  buffer_size = 174762 frames (>).

I forced use_mmap_if_available = "no", shairport-sync uses RW but in final in /proc/asound/.../hw_params I have MMAP. This is because plughw is used. As you see shairport uses format S16_LE.
But the device is only S24_3LE capable. Conversion is made by alsa (plughw is responsible for that). This is usb-spdif converter and there is stream0 file (this is unique feature of snd_usb_audio).
In stream0 there sth like that:
Playback:
  Status: Stop
  Interface 1
    Altset 1
    Format: S24_3LE
    Channels: 2
    Endpoint: 1 OUT (ASYNC)
    Rates: 44100, 48000, 88200, 96000

I have also old device which natively supports format S16_LE and turning on-off mmap works great, but in this case there is no alsa conversion from S16_LE to S24_3LE. 

Besides shairport I have also mpd. mpd produces S24_3LE (and all other) by itself according to format supported by device and hw instead of plughw can be used.

**Comment by mikebrady** [comment]
Thanks for this. It looks like the plugin is responsible for selecting MMAP, so it's beyond the reach of Shairport Sync. 

I've just pushed a new development version of Shairport Sync has been uploaded with integer rate and depth conversion, but not, sadly, S24_3. What is the exact difference between S24 and S24_E?

**Comment by mistepien** [comment]
I have not idea, but exactly the same problem was in mpd few years ago, till is was resolved.
Any way, you are right. Everything is ok with use_mmap_if_available.
But you add something about plughw (when it is necessary) and consequences of its usage.

**Comment by mistepien** [comment]
see this:
http://mailman.alsa-project.org/pipermail/alsa-devel/2012-August/054241.html

**Comment by mikebrady** [comment]
Thanks. It's a somewhat confused sequence of comments. I do know that S24 is 24 bits of audio in a 32-bit container with the most significant 8 bits unused and set to zero. It looks like S24_3 is 24 bits of audio in a 24-bit container. I'll put it on the list of things to do...

**Comment by mistepien** [comment]
http://git.musicpd.org/cgit/master/mpd.git/commit/?id=26841b6058a4368821b1ba53cc10757f90ea8a7c

**Comment by mikebrady** [comment]
Thanks – I'll have a look. Problem is that I don't have a S24_3XX device, so i might have to ask you to test. Would that be possible?

**Comment by mistepien** [comment]
Of course, that is not problem. It will be an honor for me to contribute to the development of this project.

**Comment by mikebrady** [comment]
Thanks. I've just pushed a version onto the development branch – 3.0d16 – which has untested support for S24_3LE and S24_3BE. You need to use `shairport-sync.conf` to set the format. Look in the updated `shairport-sync.conf.sample` for more information. Turn your speakers down low while you are doing initial testing, and good luck!

**Comment by mistepien** [comment]
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "batman:V102,0".
Audio Output name is "(null)".
on-start action is "/usr/local/bin/start-shairport.sh".
on-stop action is "/usr/local/bin/stop-shairport.sh".
wait-cmd status is 1.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.002000 seconds.
password is "(null)".
ignore_volume_control is 0.
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 0.
output_rate is 44100.
output_format is 5 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
configuration file name "/tmp/shairport-sync-V102,0.conf" resolves to "/tmp/shairport-sync-V102,0.conf".
metdata enabled is 1.
metadata pipename is "/tmp/shairport_metadata_pipe_V102,0".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service 'DDEA4BFA8365@batman:V102,0' group is not yet commited.
avahi: request to add "_raop._tcp" service with metadata
avahi: service 'DDEA4BFA8365@batman:V102,0' group is registering.
avahi: service 'DDEA4BFA8365@batman:V102,0' successfully added.
New RTSP connection from 192.168.1.182:39190 to self at 192.168.1.5:5000.
rsa_apply encrypt
rsa_apply exit
rsa_apply decrypt
rsa_apply exit
Play connection from user agent "iTunes/4.6 (Macintosh; U; PPC Mac OS X 10.3)".
Error in setup request.
New RTSP connection from 192.168.1.237:51208 to self at 192.168.1.5:5000.
rsa_apply encrypt
rsa_apply exit
rsa_apply decrypt
rsa_apply exit
Play connection from device named "iPhone_Michala".
Play connection from user agent "AirPlay/160.10".
Active-Remote string seen: "3634472402".
DACP-ID string seen: "EB299F157A654F04".
User-Agent is AirPlay; selecting the AirPlay latency of -1 frames.
rtp_setup: cport=61789 tport=57284.
Set up play connection from 192.168.1.237 to self at 192.168.1.5.
listening for audio, control and timing on ports 6001, 6002, 6003.
Output sample ratio is 1.
Output frame bytes is 6.
Output bit depth is 24.
Timing receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.
Audio receiver -- Server RTP thread starting.
Timing sender thread starting.
volume: 0.000000

syncing to seqno 51495.
Hammerton Decoder used on encrypted audio.
Output sample ratio is 1
Output written with RW
PCM handle name = 'hw:V102,0'
alsa device parameters:
  access type = RW_INTERLEAVED
  format = 'S24_3LE' (Signed 24 bit Little Endian in 3bytes)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 24
  rate = 44100 frames per second (precisely).
  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
  period_time = 5011 us (>).
  period_size = 221 frames (precisely).
  buffer_time = 3962857 us (>).
  buffer_size = 174762 frames (>).
  periods_per_buffer = 790 (>).
received metadata tags in SET_PARAMETER request.
empty frame to play -- skipping it (1).
empty frame to play -- skipping it (1).
empty frame to play -- skipping it (1).
empty frame to play -- skipping it (1).
Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7933.4,    20272.8,   613636.0.
Error -- ALSA device in incorrect state (4) for play.
Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7975.2,    14644.7,   162774.0.


and here is hw_params:
access: RW_INTERLEAVED
format: S24_3LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 221
buffer_size: 174762

And I can confirm all is ok, just as it should be. So conversion works, now it would be good to add kind of autodetection of output  format supported by the output device.

**Comment by mistepien** [comment]
Of course music plays good as well, it is not just a matter of logs.

**Comment by mistepien** [comment]
BTW, may I ask sth? In what format stream is sent for instance from iphone to shairport daemon? In pcm or in alac?

**Comment by mikebrady** [comment]
Great, thanks for all that.

The format from the source is always Stereo 16-bit linear PCM at 44,100 samples interleaved, compressed with Apple's Lossless Encoder, i.e. ALAC.

I'm going to wait for a while on the autodection.

**Comment by mistepien** [comment]
here you have example of autodetection code:
https://raw.githubusercontent.com/jmesmon/trifles/master/hw_params.c

**Comment by mikebrady** [comment]
Thanks – that's useful. As I mentioned, I'm going to wait for a little while before I try implementing this.

**Comment by jd20** [comment]
I had a similar issue, I have one particular USB DAC that only supports 24_3LE format, and I can confirm the version on the dev branch works properly (when specifying the right output format, of course). +1 for having auto-detect implemented.

**Comment by mistepien** [comment]
The reference solution is one implemented mpd. Using hw devices since few year is not any problem. I firmly encourage to take a look into mpd code.

**Comment by mikebrady** [comment]
Thanks for the encouragement, everybody. I've a few other things I need to do before this, bit its on the list.

**Comment by mistepien** [comment]
Any way making script with a little help of 
https://raw.githubusercontent.com/jmesmon/trifles/master/hw_params.c
is not rocket science.

hw_params "hw:$NAME4,$NAME2" > "$DUMPFILE"
	ALSAFORMATS=`cat $DUMPFILE  | grep "Formats:" | cut -d: -f2`
	ALSAFORMAT=`echo "$ALSAFORMATS" | rev | cut -d" " -f1 | rev`
	case $ALSAFORMAT in
	    S16_LE)
		    TYPE="hw"
		    FORMAT="S16"
		    ;;
	    S24_LE)
		    TYPE="hw"
		    FORMAT="S24"
		    ;;
	    S24_3LE)
		    TYPE="hw"
		    FORMAT="S24_3LE"
		    ;;
	    S32_LE)
		    TYPE="hw"
		    FORMAT="S32"
		    ;;
	    *)
		    TYPE="plughw"
		    FORMAT=""
		    ;;
values TYPE and FORMAT are ready to use in config file. Use the Force Luke!

**Comment by jd20** [comment]
Is S32 the right output format for S32_LE devices? I tried it with one DAC I have which is S32_LE, and it mostly works, but I'll get glitches and drop-outs every few minutes. On a similar note, any downside to just using plughw in shairport-sync.conf, so that the kernel can just do the conversion automatically? Do I lose any other features when doing this?

**Comment by mistepien** [comment]
Exactly, plughw is failsafe. I didnt't checkout S32_LE, because is have no such device. But what else if not S32 in such cases?

**Comment by mikebrady** [comment]
Pretty sure this has been addressed in more recent versions of Shairport Sync! Closing this inactive issue. Please open a new one if necessary.
