### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by Clamb94** [mikebrady/shairport-sync#377]
Hi,
I've just been able to get shairport-sync running on my raspberry pi 1 for the first time. However, I can't see it in my AirPlay list on my iPhone 7 running iOS 10. 
It is visible on my PC via iTunes however. I guess it's a problem with iOS 10. 
I'm running "AirServer Universal" on my PC, which works fine iOS 10. 

Thanks and best regards

**Comment by joerg-krause** [comment]
Have a look at #368

**Comment by Clamb94** [comment]
Sorry, missed it. Thanks for the fast reply
