### ISSUE TITLE
multiple instances of shairport and pidfile conflict

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#378]
I managed to run two instances of shaiport-sync, each is coupled with different sound card, there can be of course  more than just 2.

The problem is that they cannot be simultanosly run in daemon mode - both instances tries to write the same pidfile. This is why I have to run them in foreground. It would be great to have command line or option in conf file to set name of pidfile.

First instance:
general = {
name = "%h:CODEC,0";
interpolation = "soxr";
port = 5001;
};
metadata = {
enabled = "yes";
pipename = "/tmp/shairport_metadata_pipe_CODEC,0";
};
sessioncontrol = {
run_this_before_play_begins="/usr/local/bin/start-shairport.sh";
run_this_after_play_ends="/usr/local/bin/stop-shairport.sh";
wait_for_completion="yes";
};
alsa = {
output_device = "plughw:CODEC,0";
use_mmap_if_available = "no";
};

Second instance:
general = {
name = "%h:V102,0";
interpolation = "soxr";
port = 5000;
};
metadata = {
enabled = "yes";
pipename = "/tmp/shairport_metadata_pipe_V102,0";
};
sessioncontrol = {
run_this_before_play_begins="/usr/local/bin/start-shairport.sh";
run_this_after_play_ends="/usr/local/bin/stop-shairport.sh";
wait_for_completion="yes";
};
alsa = {
output_device = "plughw:V102,0";
use_mmap_if_available = "no";
};

**Comment by mikebrady** [comment]
I think this is a solved problem – see #37.

**Comment by mistepien** [comment]
ok, trick with symlinks works like a charm. In my case all instances are started by shell script reading list of soundcards, no running symlinks what very easy. Thanks a lot!

**Comment by mikebrady** [comment]
Okay to lose this?

**Comment by mistepien** [comment]
yes

**Comment by hmoffatt** [comment]
How about a pidfile argument/configuration option so that symlink trick is required?

**Comment by mikebrady** [comment]
I’m afraid I don’t understand your question.

**Comment by mikebrady** [comment]
So, I think there's a "not" missing in your original post?

Consider the situation where you are using an option or a config file entry to specify the PID file. Later on, how would you kill that instance of the program? It seems to me that you would have to add the same option or config file to the `$ shairport-sync -k` command. That is, one way or another, you'd have to point shairport-sync explicitly at another program's PID file to halt it. Is that not a bit hackish?. 

Separately, respectfully, I don't agree that symlink solution is any kind of a hack or trick. The symlink defines another name to be associated with the file holding the executable, and is a first-class name for it. If the file is read-only (a reasonable assumption for an executable), each extra link is equivalent to having another logically distinct copy of the executable. Each executable is logically independent, generates its own PID file and looks for its own configuration file by default. Another program or human can readily identify which process the PID file refers to. Definitely not a hack.
