### ISSUE TITLE
unclear about multiroom support

### ISSUE THREAD

**Issue by tcurdt** [mikebrady/shairport-sync#379]
I have two old Raspberry Pi B running an instance of shairport-sync each - working fine individually. Now I am wondering how to play the same source on both at the same time and I don't see how.
What am I missing?

**Comment by mikebrady** [comment]
If you are running iTunes, both should appear in the AirPlay "button" so you simply select both. Unfortunately, iOS devices don't support multi-output operation.

**Comment by tcurdt** [comment]
Aaaah, I am not using iTunes. I was trying from iOS and from OSX (alt-click on the speaker).

Bummer - so there is nothing but iTunes that supports multiroom at this stage?

**Comment by mikebrady** [comment]
Yeah, it is a bummer alright. There are some third party apps, like "Whaale".

**Comment by tcurdt** [comment]
Just found "Whaale" but doesn't look like it would help with Spotify.
Would be great to have those details added to the README.

Anyway - thanks for your awesome work!

**Comment by mikebrady** [comment]
Thanks for the suggestion – I'll do that.

**Comment by tcurdt** [comment]
...and I totally forgot about Airfoil - that helps on OSX at at least.

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new one if necessary.
