### ISSUE TITLE
MusicBee 'Remote Speaker' plug can cause assert crash

### ISSUE THREAD

**Issue by StreamingMeeMee** [mikebrady/shairport-sync#38]
`shairport-sync: player.c:249: alac_decode: Assertion outsize == (4*frame_size)' failed.`

I'm using the latest git shairport code; MusicBee v2.4.5404 and the Remote Speakers Output plugin v5 (http://emilles.dyndns.org/software/out_apx.html).  I'm running Shairport on a Sony Vaio laptop under Ubuntu 14.04.1

it is a sporadic problem for which I haven't quite yet discovered the pattern.  What additional info. can I provide that would be helpful?

**Comment by mikebrady** [comment]
Thanks for the report. Let me have a think about it. Meantime, if you can see any way of provoking it reliably, it would be very useful.

**Comment by StreamingMeeMee** [comment]
Would other AirPlay clients affect an instance of Shairport?  I am running two other clients concurrently; a AirportExpress and a Windows running Shairport4W.

**Comment by mikebrady** [comment]
Just to clarify a couple of questions:

1. You have `Shairport Sync` outputting to `MusicBee/RemoteSpeakersOutput` outputting to `Shairport4W` – is that right, with `MusicBee/RemoteSpeakersOutput` and `Shairport4W` on the same Windows machine?

2. Does the fault always have that same message: `shairport-sync: player.c:249: alac_decode: Assertion outsize == (4*frame_size)' failed.`?

**Comment by StreamingMeeMee** [comment]
Sorry, let me clarify.

The source is a Windows machine running MusicBee w/ RemoteSpeakerOuput.  
It is sending to:
-) Shairport4W running on the same machine
-) ShairportSync running on a Sony Vaio under Ubuntu 14.04
-) Airport Express

I don't have notes on the previous messages but they were very similar 
if not exactly the same as the one quoted below.

It will likely be tomorrow before I can do any significant testing.

T.

**Comment by mikebrady** [comment]
Thanks – That's a lot clearer. I don't think Shairport Sync should not be affected by being one of a number of destinations, as in your scenario. My own scenario is similar: iTunes or iPhone to Airport Express and a variety of Shairport Sync devices.

**Comment by mikebrady** [comment]
Hi Tim. I wonder if you've had any more experiences like you reported above?

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
