### ISSUE TITLE
Curious Update Error

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#381]
Greetings,

pi@raspberrypi:~/shairport-sync $ sudo git pull
remote: Counting objects: 329, done.
remote: Compressing objects: 100% (328/328), done.
remote: Total 329 (delta 214), reused 1 (delta 1), pack-reused 0
Receiving objects: 100% (329/329), 239.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (214/214), completed with 1 local objects.
From https://github.com/mikebrady/shairport-sync
   cbc671a..6c55d89  master     -> origin/master
   a56d103..86a2902  development -> origin/development
 * [new tag]         2.8.5      -> 2.8.5
Updating cbc671a..6c55d89
error: Your local changes to the following files would be overwritten by merge:
	INSTALL
Please, commit your changes or stash them before you can merge.
Aborting

yip.. and thats that! any ideas?

**Comment by mikebrady** [comment]
Thanks for the post. Yeah, the INSTALL thing is harmless: In older versions of the repository, there was an INSTALL file included. In later versions, the file is not included – it is automatically generated by the `autoreconf -fi` step. You should delete the existing INSTALL file.

**Comment by mikebrady** [comment]
Okay to close this?
