### ISSUE TITLE
out of sync with usb sound card

### ISSUE THREAD

**Issue by tcurdt** [mikebrady/shairport-sync#382]
I had it all working fine on the pi with the (horrible) internal soundcard. I could even watch video from the laptop and the sound was still in sync over airplay. Since I upgraded to a usb soundcard that's no longer the case though. I am not wondering how to get this back in sync. How can I adjust the delay? Is this what the `drift` is for?

```
general =
{
  drift = 352;
};
```

**Comment by mikebrady** [comment]
Hi there. There should be no difference between them as far as sync is concerned, so something else has changed.

If you're playing a video in Chrome or Safari or Quicktime or iTunes, and you are directing the System Output to an AirPlay device like Shairport Sync, the application delays the video by two seconds so that it appears in sync with the audio. With VLC you have to manually set a delay.

With a browser, the trick is to select the airplay device as the sound output *before* starting playback; if you change audio output to the AirPlay device without pausing the movie, the browser won't delay the video properly. I'm watching a movie right now on Safari with this setup.

The drift figure is just a tolerance figure – the difference between the actual sync and the calculated sync times has to be greater than this number of frames (44,1000 frames per second) before Shairport Sync will attest to correct it.

See also #380, where the OP seems to be reporting the same problem, which is a bit strange...

**Comment by tcurdt** [comment]
I am still on 10.11.6 and I was redirecting the whole system output (alt-click on the speaker icon). So the client (I think I was using Movist) didn't really know anything about it.

I was actually surprised how well this worked with the build-in card. I could not think of anything but the card that has changed in the setup.

But setting the delay to 2s (as you suggested for VLC) does indeed seem to solve this - I am just a bit curious why I didn't have to do it before ...and where the exact 2s is coming from.

**Comment by mikebrady** [comment]
Thanks for the update. The two seconds delay is negotiated between the audio source and the AirPlay device, and it is actually slightly longer for iTunes. I presume the (rather long) duration was chosen when networks weren't as fast as they are now. 

Haven't tried Movist...

**Comment by tcurdt** [comment]
Unfortunately Movist is no longer developed - so no point in trying.

As for the 2s - IIUC that means the actual delay might change depending on the network conditions?

**Comment by mikebrady** [comment]
Sorry – I'm not really explaining myself well.

In AirPlay, each audio frame has an associated sequence number which is associated with a time on the audio "source" computer. Periodically, the audio "sink" computer – running Shairport Sync in this case – periodically synchronises its clock with the source clock, so it can work out exactly when each audio frame should be played relative to its own, local, clock. The negotiated latency is used as part of that calculation, so the two-second latency that is negotiated between the source and the sink means that each audio frame should be played exactly two seconds after it should have been played at the source, independent of network conditions.

(BTW, with iTunes, if you enable AirPlay and also turn on local playback, the audio going to the local speakers is delayed to match the latency, so all the audio being played locally and on the AirPlay speakers is delayed by exactly the same amount.)

What I was trying to say in the previous post was that two seconds is plenty of time on modern networks to ensure that the packets of frames are reliably received in time (the transport is UDP with separate missing packet recovery).

**Comment by tcurdt** [comment]
> In AirPlay, each audio frame has an associated sequence number which is associated with a time on the audio "source" computer. Periodically, the audio "sink" computer – running Shairport Sync in this case – synchronises its clock with the source clock, so it can work out exactly when each audio frame should be played relative to its own, local, clock.

That's clear.

> The negotiated latency is used as part of that calculation, so the two-second latency that is negotiated between the source and the sink means that each audio frame should be played exactly two seconds after it should have been played at the source, independent of network conditions.

...but whether that's 2s or 4s depends on the network conditions and will be negotiated between the source and the sink?

Which means the delay in e.g. VLC needs to be adjusted to whatever these two did negotiate. Did I understand that correctly?

**Comment by mikebrady** [comment]
Yes, that's correct, except that the latency that is negotiated has always been two seconds, except for iTunes, which negotiates a slightly longer latency. Thus, the adjustment for VLC has always been two seconds. We don't know whether any of this will change in the future, but that's how it has been up until now.

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new one if necessary.
