### ISSUE TITLE
Cannot build on raspberrypi

### ISSUE THREAD

**Issue by jkiddo** [mikebrady/shairport-sync#387]
pi@retropie:~/airplay/shairport-sync $ make
 cd . && /bin/bash /home/pi/airplay/shairport-sync/missing automake-1.14 --gnu
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Makefile.am: error: required file './INSTALL' not found
Makefile.am:   'automake --add-missing' can install 'INSTALL'
Makefile:373: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1

**Comment by mikebrady** [comment]
Hi there. There is something wrong with your locale settings – have you set up the RPi correctly? Then, check that all the build requirements are installed – they are listed in the README.md.

**Comment by jkiddo** [comment]
Running 'automake --add-missing' before calling make solved it

**Comment by mikebrady** [comment]
Great.
