### ISSUE TITLE
compatibility with iOS10 (iTunes 12.5)

### ISSUE THREAD

**Issue by DannyBoyKN** [mikebrady/shairport-sync#390]
I'm using the PiMusicBox (v0.6 on a RaspberryPi 1 with HifiBerry DAC) with the ability to stream music from my iPhone SE over AirPlay (shairport-sync) to the PiMusicBox.
$> shairport-sync -V
2.1.15-openssl-Avahi-ALSA

Airplay streaming is still possible with devices using iOS 9.x.x. Recently, I updated mine with iOS 10 and remarked, that the MusicPi AirPlay device is not visible any longer.

Is this due to iOS 10 (and iTunes 12.5) only ?
Or related to the installed shairport-sync version ?

I did not find any further information concerning this.
Thank you for any feedback

**Comment by mikebrady** [comment]
Thanks for the post. Two things:

1. Yes its still works with iOS 10. Apple have made some changes to the Control Center – see http://www.macrumors.com/how-to/ios-10-control-center/ for example. In sum: swipe up and then swipe left to access the audio airplay stuff.

2. Your version of Shairport Sync is pretty old and some important updates have been included in later versions, currently 2.8.5. After getting (1) sorted out, you should consider updating.

**Comment by DannyBoyKN** [comment]
Thanks Mike, (1) is clear and other AirPlay devices still appear, but not this one on my PiMusicBox served by shairport-sync.
I was already considering (2),  trying to clone and:
`autoreconf -i -f `
`./configure --sysconfdir=/etc --with-alsa --with-avahi --with-metadata --with-systemv
`
but make output gives:
```
...
make[2]: Entering directory '/root/shairport-sync'
gcc -Wno-multichar -DSYSCONFDIR=\"/etc\"  -g -O2   -o shairport-sync shairport.o rtsp.o mdns.o mdns_external.o common.o rtp.o player.o alac.o audio.o mdns_avahi.o  audio_alsa.o         -lasound   -lavahi-common -lavahi-client -lconfig   -lpopt   -lm -lpthread -ldaemon   -lrt 
rtsp.o: In function `handle_announce':
/root/shairport-sync/rtsp.c:1464: undefined reference to `base64_dec'
/root/shairport-sync/rtsp.c:1473: undefined reference to `base64_dec'
/root/shairport-sync/rtsp.c:1474: undefined reference to `rsa_apply'
rtsp.o: In function `apple_challenge':
/root/shairport-sync/rtsp.c:1538: undefined reference to `base64_dec'
/root/shairport-sync/rtsp.c:1573: undefined reference to `rsa_apply'
/root/shairport-sync/rtsp.c:1574: undefined reference to `base64_enc'
rtsp.o: In function `make_nonce':
/root/shairport-sync/rtsp.c:1593: undefined reference to `base64_enc'
collect2: ld returned 1 exit status
Makefile:391: recipe for target 'shairport-sync' failed
...
```

I think the PiMusicBox system is too old to 'harmonize' with a newer shairport-sync

```
$> uname -a
Linux MusicBox 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux
```

**Comment by mikebrady** [comment]
Thanks for the update. You need to include `--with-ssl=openssl`, I think – check the settings in UPDATING.md. 
Let us know how you get on.

**Comment by DannyBoyKN** [comment]
Well, `--with-ssl=openssl` did the trick. It compiled now successfully.

I did not want to overwrite immediately the pre-installed configuration, so I skipped `make install` just did stop the previous service:
`$ sudo service shairport-sync stop`
and started the new manually, just as it was listed in `/etc/init.d/shairport-sync` script, but without the demonizing option and verbose output:
```
$ ./shairport-sync -V
2.8.5-OpenSSL-Avahi-ALSA-sysconfdir:/etc
$ ./shairport-sync -a "MusicBox (MusicBox)" -w -B "/usr/bin/mpc stop" -v
Looking for the configuration file "/etc/shairport-sync.conf".
Output device name is "default".
Version: "2.8.5-OpenSSL-Avahi-ALSA-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "MusicBox (MusicBox)".
Audio Output name is "(null)".
on-start action is "/usr/bin/mpc stop".
on-stop action is "(null)".
wait-cmd status is 1.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
playback_mode is 0 (0-stereo, 1-mono).
disable_synchronization is 0.
use_mmap_if_available is 1.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
configuration file name "/etc/shairport-sync.conf" can not be resolved.
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'AD90B09060A6@MusicBox (MusicBox)' successfully added.

^Cshutdown requested...
avahi: avahi_unregister.
Request to shut down all rtsp conversation threads
```
The AirPlay service 'MusicBox (MusicBox)' still does not appear under iOS 10, but it appears under my tablet running iOS 9 :-(

There's no such "/etc/shairport-sync.conf" anywhere on the system and there was none before neither. Don't know why and how it works. But I think, to make the AirPlay service appear it is not required, right ?

**Comment by mikebrady** [comment]
Good work. Yeah, the `/etc/shairport-sync.conf` is not necessary – it is a recent feature, but the older command-line options which you are using work as well.

I can't imagine what's happening with the iOS 10 device. There's an app called "Discovery" that will enable you to see what Bonjour/Zeroconf information, used by AirPlay devices, is being seen by the device. It should be seeing appropriate "Remote Audio Output Protocol" information.

**Comment by DannyBoyKN** [comment]
The Discovery APP sees 3 devices: our Apple TV3, my sons Pioneer HiFi Station and that shairport-sync device. Unfortunately, my iPhone SE with iOS 10 only see the ATV3.

I attached the Remote Audio Output Protocol (AirTunes) config:
AD90B09060A6@MusicBox (MusicBox)._raop._tcp.local.
Remote Audio Output Protocol (AirTunes)

```
MusicBox.local:5000
<Ipv4-address>:5000
<Ipv6-address>:5000

am = AirPort4,107
ch = 2
cn = 0,1
da = true
ek = 1
et = 0,1
fv = 76400.10
pw = false
sf = 0x4
sr = 44100
ss = 16
sv = false
tp = TCP,UDP
txtvers = 1
vn = 65537
vs = 105.1
```
Do you see any problems in there ?

**Comment by mikebrady** [comment]
Just to clarify, is the Discovery app running on your iPhone SE with iOS 10?

**Comment by DannyBoyKN** [comment]
yes

**Comment by mikebrady** [comment]
So, does this mean that your iPhone cannot see the Shairport Sync device and cannot see the Pioneer HiFi Station?

**Comment by DannyBoyKN** [comment]
Exactly.
But the tablet with iOS 9 does see all

**Comment by mikebrady** [comment]
So, it's not confined to Shairport Sync – rather, it is confined to audio-only AirPlay devices. And, it looks like the appropriate signals both for the Shairport Sync device and the Pioneer are actually reaching the iPhone. Could I ask you again at changes to the Control Center, for example, at #368?

**Comment by DannyBoyKN** [comment]
Indeed, just looked at the AirPlay option when swiping up the control center ... shame on me.
Sorry for bothering you with that :-/

**Comment by mikebrady** [comment]
Not a problem – the right outcome was achieved. Also, this thread may help others...
