### ISSUE TITLE
Events on Connect/Disconnect

### ISSUE THREAD

**Issue by checkerschaf** [mikebrady/shairport-sync#392]
Is there anyway to execute a shell script or anything like that on user connect or disconnect?
I want to adjust some settings if it happens.

PS: I know, strange questions but would be very helpful :)

**Comment by mikebrady** [comment]
Thanks for the post. There isn't anything sensitive to user connect and disconnects. However, there is for just before and just after a play session. Is that any use?

**Comment by checkerschaf** [comment]
Thanks for your answer! I'm not sure, how can I use it or where's a documentation for it?

**Comment by mikebrady** [comment]
It's in the `man` pages. I'm thinking of the `sessioncontrol` settings `run_this_before_play_begins="/path/to/application and args";` and `run_this_after_play_endss="/path/to/application and args";`.

**Comment by mikebrady** [comment]
Pretty sure this has been addressed in more recent versions of Shairport Sync! Also, have a look at the new `active` mode stuff. Please open a new issue if necessary.
