### ISSUE TITLE
Does not appear as an airplay client in MoodeOS.

### ISSUE THREAD

**Issue by bwanaaa** [mikebrady/shairport-sync#393]
I am without airplay even after turning it on in moode.

cleared the syslog, turned on airplay receiver, airplay metadata and rebooted.

ps axg shows two processes running on the pi:

```
2108 ?        S      0:00 sudo /usr/local/bin/shairport-sync -a Moodey Airplay -S soxr -w -B /var/www/command/spspre.sh -E /var/www/command/spspost.sh --metadata-pipename=/tmp/shairport-sync-metadata --get-coverart -- -d hw:1 -c 

 2112 ?        S      0:00 /usr/local/bin/shairport-sync -a Moodey Airplay -S soxr -w -B /var/www/command/spspre.sh -E /var/www/command/spspost.sh --metadata-pipename=/tmp/shairport-sync-metadata --get-coverart -- -d hw:1 -c 
```

Yes , I renamed moode to moodey because it's giving me grief.

I can get moode to show up as an airplay device if I issue this command while ssh'ed into the pi:

`/usr/local/bin/shairport-sync -a Moodey Airplay -S soxr -w -B /var/www/command/spspre.sh -E /var/www/command/spspost.sh --metadata-pipename=/tmp/shairport-sync-metadata --get-coverart -- -d hw:1`

then I get 
`successful startup`

and the process is visible if I open up another terminal to the pi and look at the running processes
I then try to send the opera playing on the iphone to the newly visible moodey on airplay and a little while later get this in the terminal where I started shairport-sync:

`audio_alsa: Sample format not available for device "hw:1": Invalid argument`
I suspect I am missing a few arguments in the command I typed above. But that doesnt change the problem of why i am not seeing the airplay client initially when terminal says it's running.

**Comment by mikebrady** [comment]
Thanks for the post. The message `audio_alsa: Sample format not available for device "hw:1": Invalid argument` means that the output device is not capable of accepting the audio format used by Shairport Sync: 44,100 frames per second / 16 bit signed PCM samples / interleaved stereo – i.e. CD quality output. Is that a likely explanation?

**Comment by bwanaaa** [comment]
The Pi is connected to an iFimicroDSD with a USB cable. That device says it accepts 44khz. And it does play audio from other sources, just not airplay. Do I need to instruct shairport-sync to accept 44khz? I know it's not an apple restriction because a windows pc with airfoil behaves the same way.

Or maybe I should try resampling, huh. When audio from the internet or a hard drive is sent to the iDSD, it plays fine and beautifully. I assume all that stuff is 48khz. (But actually most internet streams are 128 kbps, right? and that's not an even multiple of 48) 

Which raises another interesting question.How do computers play CDs? These things output 44khz audio from the CD player but the pc outputs 48khz. Do ALL 'regular' pcs running windows resample and not tell you? I guess that is WASAPI? Forgive the naïve questions.

And next question, if you resample 44 to 48, what happens to the sound? I mean that is not an integer multiple so some of the original samples coming off a 44khz must get mangled a little(truncated, scaled, convoluted?)

Wow, really went OT. sorry, curiosity got the better of me.

**Comment by mistepien** [comment]
Just use plughw:1 instead hw:1. Shairport-sync 2.X cannot by itself checkout audio card capabilities. Use plughw and your live will be easier.

**Comment by bwanaaa** [comment]
Tres bien monsieur mistepien! Problem solved.  I have let Tim Curtis know (author of Moode audio player). Mike, you can close this issue,
