### ISSUE TITLE
metadata volume events

### ISSUE THREAD

**Issue by noelhibbard** [mikebrady/shairport-sync#394]
I want to enable fixed volume and then use the metadata pipe to capture volume events which I can then forward over to my receiver. I notice that when the volume is maxed out and you hit the vol+ on the phone I don't see an event in the pipe. Is this because the phone itself isn't sending a command because it knows it's already at max volume or is it because shairport-sync isn't forwarding the event because it knows it's already maxed?

I wish I had a receiver with IP control that would let me specify an exact volume level. Then I could just sync the receiver with the volume slider.

**Comment by mikebrady** [comment]
Shairport Sync passes on all volume setting messages it receives (or at least it's intended to) so I think you're out of luck on that one.

**Comment by therealmuffin** [comment]
If you're running shairport-sync on Linux I wrote an application that might do what you want. Basically you instruct shairport-sync to use a dummy soundcard in Alsa for volume control (alsa: mixer_device, mixer_control_name) and synchronize that card with the amplifier. I made it quite configurable so chances are high your amp is supported. For more info you can check https://github.com/therealmuffin/synchronator

**Comment by mikebrady** [comment]
What a great idea – thanks for the post.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue on it if necessary.
