### ISSUE TITLE
Running on Bash on Ubuntu on Windows? 

### ISSUE THREAD

**Issue by Clamb94** [mikebrady/shairport-sync#395]
Hi, 
this is not really an issue with Shairport-sync, but I don't know where to ask it otherwise.

I'm running 2 raspberrys with shairport-sync successfully in two rooms. Audio is nice and sync when streaming from iTunes. However, I'd like to stream the music from I tunes to my main Windows-PC as well (in sync obviously). 
But I can't find a solution for this other than buying an additional raspberry connected to the line-in of my PC. I tried running shairport-sync on the "bash for ubuntu for windows 10" command line, which is available with the anniversary update for windows 10. But that didn't work as planned. I'm not that much into linux as well, so might be my fault. Has anyone done this? Is this even possible?

I've tried other solutions to get the audio to my PC, but none of them were working together with shairport-sync (the PC audio was always way out of sync). 
I tried it with:
- AirServer (with/without "lossless audio receiver)
- Airfoil Satellite
- TuneBlade
- Shairport4w

Any idea how I could solve this?

**Comment by noelhibbard** [comment]
You should be able to compile it under cygwin but if I recall it doesn't support sync. You can find the instructions on building under cygwin here:
https://github.com/mikebrady/shairport-sync/blob/development/CYGWIN.md

**Comment by mikebrady** [comment]
That's correct – no synchronisation on Cygwin.

**Comment by Clamb94** [comment]
For some reason it's now working like a charm when streaming Apple Music from iTunes on my Windows PC. Can't tell why 😄

**Comment by noelhibbard** [comment]
Wait what? You are running it from Bash in Win10 successfully? I haven't read up much on this new Bash shell. Is it actually Ubuntu running under hyperv or something?

**Comment by Clamb94** [comment]
Sorry, I wasn't very clear. I'm running iTunes on my Windows PC streaming to the Shairpot-Sync recievers. The music coming from iTunes on the PC and the shairport-sync recievers are in sync. For some reasons this wasn't the case when I tried in the first time.
