### ISSUE TITLE
Debug output from a Moode user

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#397]
Hi Mike,

Some debug output from a Moode user that is experiencing "dropouts". I'm not sure how to interpret the errors.

-Tim

Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "hw:0".
Open Mixer
Lowest dB value is a mute -- try minimum volume +1
Hardware mixer has dB volume from -103.000000 to 0.000000.
Has mute ability.
The processor is running little-endian.
Version: "2.8.4-OpenSSL-Avahi-ALSA-stdout-soxr-metadata"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "Moode Airplay".
Audio Output name is "(null)".
on-start action is "/var/www/command/spspre.sh".
on-stop action is "/var/www/command/spspost.sh".
wait-cmd status is 1.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
playback_mode is 0 (0-stereo, 1-mono).
disable_synchronization is 0.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 1.
metadata pipename is "/tmp/shairport-sync-metadata".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 1.
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service '4EA8E21A3B78@Moode Airplay' group is not yet commited.
avahi: request to add "_raop._tcp" service with metadata
avahi: service '4EA8E21A3B78@Moode Airplay' group is registering.
avahi: service '4EA8E21A3B78@Moode Airplay' successfully added.
New RTSP connection from 192.168.1.136:53586 to self at 192.168.1.112:5000.
Play connection from user agent "Airfoil/4.9.0 (Macintosh; N; Intel)".
Active-Remote string seen: "2298139828".
DACP-ID string seen: "C1C6747504139237".
Unrecognised User-Agent. Using latency of -1 frames.
rtp_setup: cport=6002 tport=6003.
Set up play connection from 192.168.1.136 to self at 192.168.1.112.
listening for audio, control and timing on ports 6001, 6002, 6003.
Timing receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.
Audio receiver -- Server RTP thread starting.
Timing sender thread starting.
volume: -1.943359

Setting volume db to -333.609965.
syncing to seqno 31966.
received metadata tags in SET_PARAMETER request.
PCM handle name = 'hw:0'
alsa device parameters:
  access type = RW_INTERLEAVED
  format = 'S16_LE' (Signed 16 bit Little Endian)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 16
  rate = 44100 frames per second (precisely).
  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
  period_time = 23219 us (>).
  period_size = 1024 frames (precisely).
  buffer_time = 2972154 us (>).
  buffer_size = 131072 frames (>).
  periods_per_buffer = 128 (precisely).
Open Mixer
Setting volume db to -333.609965.
received metadata tags in SET_PARAMETER request.
received metadata tags in SET_PARAMETER request.
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -- ALSA device in incorrect state (4) for play.
Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7982.9,     1830.3,    26575.0.
Error -- ALSA device in incorrect state (4) for play.
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Error -32 writing 353 samples in play(): "Broken pipe".
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2279.
syncing to seqno 36248.

**Comment by mikebrady** [comment]
Hi Tim, and thanks for the post. I’m guessing this is a Raspberry Pi of some sort — I wonder which, just to get an idea of its power, as there is a big jump from the originals to the Raspberry Pi 2 and 3.

Anyhow, presuming the OS is reasonably up to date, something that comes to mind is that if the user is on WiFi, then s/he should ensure that power save mode is off — see [TROUBLESHOOTING.md](Hi Tim. I’m guessing this is a Raspberry Pi of some sort — I wonder which, just to get an idea of its power, as there is a big jump from the originals to the Raspberry Pi 2 and 3.

Anyhow, presuming the OS is reasonably up to date, something that comes to mind is that if the user is on WiFi, then s/he should ensure that WiFi Power Save mode is off — see [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md#wifi-adapter-running-in-power-saving--low-power-mode).

**Comment by fallenicarus** [comment]
HI Mike,
Tim posted this on my behalf. I have a the pi b+ which is running moode. I am pretty sure I have seen the issue with sending audio over using my iphones airplay setting. The pi is connected via ethernet only so wifi shouldnt be an issue. 

After tim had posted the issue, I tried changing the stuffing back to basic from soxr and that helped in the time I heard it. I will try more after work today. Hope that helps!

**Comment by mikebrady** [comment]
Thanks for the clarifications. If you could turn on statistics during your testing, it would be very helpful.

**Comment by fallenicarus** [comment]
Mike,
Here are the log files with the statistics when soxr and basic are set as the stuffing option. These dropouts all happened within a 3-4 minute song. I was able to play the song again using the basic option without anything. 

Let me know if you need anything else from my end.


`Using SOXR stuffing:`
> Looking for the configuration file "/etc/shairport-sync.conf".
> Looking for configuration file at full path "/etc/shairport-sync.conf"
> Output device name is "hw:0".
> Open Mixer
> Lowest dB value is a mute -- try minimum volume +1
> Hardware mixer has dB volume from -103.000000 to 0.000000.
> Has mute ability.
> The processor is running little-endian.
> Version: "2.8.4-OpenSSL-Avahi-ALSA-stdout-soxr-metadata"
> statistics_requester status is 1.
> daemon status is 0.
> rtsp listening port is 5000.
> udp base port is 6001.
> udp port range is 100.
> Shairport Sync player name is "Moode Airplay".
> Audio Output name is "(null)".
> on-start action is "/var/www/command/spspre.sh".
> on-stop action is "/var/www/command/spspost.sh".
> wait-cmd status is 1.
> mdns backend "(null)".
> userSuppliedLatency is 0.
> AirPlayLatency is -1.
> iTunesLatency is -1.
> forkedDaapdLatency is -1.
> stuffing option is "1" (0-basic, 1-soxr).
> resync time is 2205.
> allow a session to be interrupted: 0.
> busy timeout time is 120.
> drift tolerance is 88 frames.
> password is "(null)".
> ignore_volume_control is 0.
> playback_mode is 0 (0-stereo, 1-mono).
> disable_synchronization is 0.
> audio backend desired buffer length is 6615.
> audio backend latency offset is 0.
> volume range in dB (zero means use the range specified by the mixer): 0.
> zeroconf regtype is "_raop._tcp".
> configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
> metdata enabled is 1.
> metadata pipename is "/tmp/shairport-sync-metadata".
> metadata socket address is "(null)" port 0.
> metadata socket packet size is "500".
> get-coverart is 1.
> Successful Startup
> avahi: avahi_register.
> avahi: register_service.
> avahi: service '4EA8E21A3B78@Moode Airplay' group is not yet commited.
> avahi: request to add "_raop._tcp" service with metadata
> avahi: service '4EA8E21A3B78@Moode Airplay' group is registering.
> avahi: service '4EA8E21A3B78@Moode Airplay' successfully added.
> New RTSP connection from 192.168.1.136:55840 to self at 192.168.1.112:5000.
> Play connection from user agent "Airfoil/4.9.0 (Macintosh; N; Intel)".
> Active-Remote string seen: "1747539330".
> DACP-ID string seen: "5F57F9109C1BCD7A".
> Unrecognised User-Agent. Using latency of -1 frames.
> rtp_setup: cport=6002 tport=6003.
> Set up play connection from 192.168.1.136 to self at 192.168.1.112.
> listening for audio, control and timing on ports 6001, 6002, 6003.
> sync error in frames, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy
> Timing receiver -- Server RTP thread starting.
> Control receiver -- Server RTP thread starting.
> Audio receiver -- Server RTP thread starting.
> Timing sender thread starting.
> volume: -6.267090
> 
> Setting volume db to -1075.850423.
> syncing to seqno 41530.
> received metadata tags in SET_PARAMETER request.
> PCM handle name = 'hw:0'
> alsa device parameters:
>   access type = RW_INTERLEAVED
>   format = 'S16_LE' (Signed 16 bit Little Endian)
>   subformat = 'STD' (Standard)
>   number of channels = 2
>   number of significant bits = 16
>   rate = 44100 frames per second (precisely).
>   precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
>   period_time = 23219 us (>).
>   period_size = 1024 frames (precisely).
>   buffer_time = 2972154 us (>).
>   buffer_size = 131072 frames (>).
>   periods_per_buffer = 128 (precisely).
> Open Mixer
> Setting volume db to -1075.850423.
> Error -- ALSA device in incorrect state (4) for play.
> received metadata tags in SET_PARAMETER request.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7982.7,     1495.3,    21430.0.
> Error -32 writing 353 samples in play(): "Broken pipe".
>       30.8,    -120.2,     558.8,        3758,      0,      0,      0,      0,      0,  228,  250
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2270.
> syncing to seqno 46297.
> Open Mixer
> Setting volume db to -1075.850423.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7982.3,     1918.4,    23470.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.1,     1546.2,    19634.0.
>        2.5,    -172.4,     511.0,        7516,      0,      0,      0,      0,      0,  229,  248
> Error -- ALSA device in incorrect state (4) for play.
> Error -- ALSA device in incorrect state (4) for play.
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2313.
> syncing to seqno 51357.
> Open Mixer
> Setting volume db to -1075.850423.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.2,     1616.8,    21806.0.
>      114.0,    -593.4,     833.8,       11274,      0,      0,      0,      0,      0,  228,  250
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7982.8,     1545.9,    33086.0.
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2309.
> syncing to seqno 55463.
> Open Mixer
> Setting volume db to -1075.850423.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.2,     1395.5,    18006.0.
>      -21.8,      70.3,     353.0,       15032,      0,      0,      0,      0,      0,  228,  248
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.4,     1451.4,    19914.0.
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -- ALSA device in incorrect state (4) for play.
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2289.
> syncing to seqno 59962.
> Open Mixer
> Setting volume db to -1075.850423.
>      -11.4,     -62.0,     390.1,       18790,      0,      0,      0,      0,      0,  229,  248
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.8,     1623.1,    20706.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.4,    20046.1,   181435.0.
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Error -32 writing 353 samples in play(): "Broken pipe".
> Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2304.
> syncing to seqno 64244.
> Open Mixer
> Setting volume db to -1075.850423.
>       17.5,      19.7,     346.2,       22548,      0,      0,      0,      0,      0,  206,  248
> ^Cshutdown requested...
> avahi: avahi_unregister.
> Request to shut down all rtsp conversation threads
> asking playing threads to stop
> RTSP shutdown requested.
> Closing down RTSP conversation thread...



`Using basic stuffing:`

> Looking for the configuration file "/etc/shairport-sync.conf".
> Looking for configuration file at full path "/etc/shairport-sync.conf"
> Output device name is "hw:0".
> Open Mixer
> Lowest dB value is a mute -- try minimum volume +1
> Hardware mixer has dB volume from -103.000000 to 0.000000.
> Has mute ability.
> The processor is running little-endian.
> Version: "2.8.4-OpenSSL-Avahi-ALSA-stdout-soxr-metadata"
> statistics_requester status is 1.
> daemon status is 0.
> rtsp listening port is 5000.
> udp base port is 6001.
> udp port range is 100.
> Shairport Sync player name is "Moode Airplay".
> Audio Output name is "(null)".
> on-start action is "/var/www/command/spspre.sh".
> on-stop action is "/var/www/command/spspost.sh".
> wait-cmd status is 1.
> mdns backend "(null)".
> userSuppliedLatency is 0.
> AirPlayLatency is -1.
> iTunesLatency is -1.
> forkedDaapdLatency is -1.
> stuffing option is "0" (0-basic, 1-soxr).
> resync time is 2205.
> allow a session to be interrupted: 0.
> busy timeout time is 120.
> drift tolerance is 88 frames.
> password is "(null)".
> ignore_volume_control is 0.
> playback_mode is 0 (0-stereo, 1-mono).
> disable_synchronization is 0.
> audio backend desired buffer length is 6615.
> audio backend latency offset is 0.
> volume range in dB (zero means use the range specified by the mixer): 0.
> zeroconf regtype is "_raop._tcp".
> configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
> metdata enabled is 1.
> metadata pipename is "/tmp/shairport-sync-metadata".
> metadata socket address is "(null)" port 0.
> metadata socket packet size is "500".
> get-coverart is 1.
> Successful Startup
> avahi: avahi_register.
> avahi: register_service.
> avahi: service '4EA8E21A3B78@Moode Airplay' group is not yet commited.
> avahi: request to add "_raop._tcp" service with metadata
> avahi: service '4EA8E21A3B78@Moode Airplay' group is registering.
> avahi: service '4EA8E21A3B78@Moode Airplay' successfully added.
> New RTSP connection from 192.168.1.136:55856 to self at 192.168.1.112:5000.
> Play connection from user agent "Airfoil/4.9.0 (Macintosh; N; Intel)".
> Active-Remote string seen: "2304378725".
> DACP-ID string seen: "5F57F9109C1BCD7A".
> Unrecognised User-Agent. Using latency of -1 frames.
> rtp_setup: cport=6002 tport=6003.
> Set up play connection from 192.168.1.136 to self at 192.168.1.112.
> listening for audio, control and timing on ports 6001, 6002, 6003.
> sync error in frames, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy
> Timing receiver -- Server RTP thread starting.
> Control receiver -- Server RTP thread starting.
> volume: -6.267090
> 
> Setting volume db to -1075.850423.
> Audio receiver -- Server RTP thread starting.
> Timing sender thread starting.
> syncing to seqno 978.
> received metadata tags in SET_PARAMETER request.
> PCM handle name = 'hw:0'
> alsa device parameters:
>   access type = RW_INTERLEAVED
>   format = 'S16_LE' (Signed 16 bit Little Endian)
>   subformat = 'STD' (Standard)
>   number of channels = 2
>   number of significant bits = 16
>   rate = 44100 frames per second (precisely).
>   precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
>   period_time = 23219 us (>).
>   period_size = 1024 frames (precisely).
>   buffer_time = 2972154 us (>).
>   buffer_size = 131072 frames (>).
>   periods_per_buffer = 128 (precisely).
> Open Mixer
> Setting volume db to -1075.850423.
> received metadata tags in SET_PARAMETER request.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.1,     1307.9,    19493.0.
>       27.0,      -8.4,     325.0,        3758,      0,      0,      0,      0,   4588,  229,  236
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.0,     1277.3,    17980.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.2,     1317.8,    18219.0.
>       -1.3,      73.3,     679.6,        7516,      0,      0,      0,      0,   6042,  229,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.9,     1312.4,    19096.0.
>       -0.4,      71.8,     690.2,       11274,      0,      0,      0,      0,   5836,  228,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.1,     1266.7,    18855.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.0,     2464.1,   111391.0.
>       -3.7,      74.8,     664.5,       15032,      0,      0,      0,      0,   6045,  217,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7982.8,     1278.3,    19041.0.
>       -1.7,      83.9,     794.5,       18790,      0,      0,      0,      0,   5834,  217,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.1,     2566.9,   114909.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.2,     1211.8,    16467.0.
>       -0.5,      62.7,     706.8,       22548,      0,      0,      0,      0,   6036,  228,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7982.7,     1211.5,    13500.0.
>        1.1,     114.9,     730.3,       26306,      0,      0,      0,      0,   6084,  228,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.1,     1315.9,    24082.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.8,     1288.6,    22912.0.
>       -0.2,      38.6,     676.6,       30064,      0,      0,      0,      0,   5572,  228,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7983.1,     1270.3,    17747.0.
>       -2.2,      61.2,     771.8,       33822,      0,      0,      0,      0,   5860,  229,  231
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.0,     1269.7,    13645.0.
> Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.4,     1312.0,    22718.0.
>       -4.4,      71.1,     687.9,       37580,      0,      0,      0,      0,   5845,  228,  231

PS: Apologies for the long post, I wasnt sure if you preferred the log as a text file or just pasted in here.

**Comment by mikebrady** [comment]
Many thanks for the logs. It looks like a great deal of overcorrection is going on – e.g. on the last line the net correction was 71.1 ppm and the actual corrections is 687.9 ppm. So, I suggest you widen the drift tolerance – set the `drift` to, say, 352. It should reduce the amount of over correction and therefore reduce the computational load when your use`soxr` interpolation.

**Comment by mikebrady** [comment]
Did you ever resolve this issue?

**Comment by moodeaudio** [comment]
Hi Mike,

I was not able to determine root cause.  The issue can be closed.

-Tim

**Comment by fallenicarus** [comment]
Changing the setting helped, Moreover, I moved away from the rpi B that this was happening on to a rpi3. There have been other changes to how I have things setup as well so I cant dig into this anymore. I would assume it was something to do with computational load but not sure. 

The issue can be closed if you want.

**Comment by mikebrady** [comment]
Thanks guys. I'll close the issue. Feel free to reopen it if necessary.
