### ISSUE TITLE
No audio when running as daemon on Raspberry Pi

### ISSUE THREAD

**Issue by Jeroen-R** [mikebrady/shairport-sync#40]
First of all, well done on this awesome project and the level of documentation.

I am experiencing some strange behaviour, but only when running as a Daemon (on a Raspberry Pi B+, Raspbian GNU/Linux 7 (wheezy))

When I run Shairport-Sync directly from the shell (./shairport-sync) all works well. However, when I Daemonize it all appears to work (My ipad sees it and can connect to it), there is just no audio. First I though it was because the daemon runs as root and perhaps the audio settings for root are different (they are not afaik), but after jumping through some hoops to let my 'pi' account write to '/var/run/shairport-sync.pid' I still get no audio.

I have taken the relevant bit out of /etc/init.d/shairport-sync to make testing easier.

    sudo start-stop-daemon --start --pidfile /var/run/shairport-sync.pid --chuid pi --exec /usr/local/bin/shairport-sync -- -d -a "Living Room CLI"

I have tried different audio devices as well and tried separate tests with the audio cable in the RasPi audio out as well as the USB based DAC.

There are no errors in syslog either. I get the same problem on 2 separate RasPis

The original Shairport ran fine as a daemon using the exact same user account.

Any idea what may be wrong?

**Comment by mikebrady** [comment]
Thanks for the kind words. 

A couple of guesses.

* Are you sure it's not working? You're using a software volume control. The device's existing hardware mixer volume won't be under shairport-sync'c control and might be turned right down. Use alsamixer to see it.
* I haven't tried to run it with a different user account, and I wonder if that might be the problem. Other versions of Shairport used a variety of audio back ends, whereas Shairport Sync uses just one – ALSA. It may be that access to the ALSA system requires the user to be in a special group ("audio?") – see https://wiki.debian.org/SoundFAQ. A quick way to check is to see if removing the `--chuid pi' from the command line above makes and difference.

**Comment by Jeroen-R** [comment]
Yes, I am sure. I have checked with alsamixer and also by using shairport-sync from the shell (not as a daemon), which plays audio just fine, I always keep a handy 'test.wav' file handy for checking audio in combination with aplay.

I also get the problem when running it as root (without the --chuid pi). I merely tried using a different account as I thought that might have been the problem.

The original Shairport installation also ran using Alsa.

**Comment by mikebrady** [comment]
Thanks for the clarification. I'll do some experimentation on my (similar) setup and see if I can replicate the fault.

**Comment by mikebrady** [comment]
Hi again. Just tried this on my Raspberry Pi and it worked alright:

`sudo start-stop-daemon --start --pidfile /var/run/shairport-sync.pid --exec /usr/local/bin/shairport-sync -- -d -v -a "Living Room CLI"`

I could see activity in the log: `tail -f -n 1000 /var/log/syslog`

**Comment by Jeroen-R** [comment]
Idontgetit. You can hear audio as well? I have log activity, just can't hear a thing.

**Comment by mikebrady** [comment]
Yes I can – I'm listening to it right now via the Raspberry Pi's headphone jack – that is the default device. It's not too loud, but it's working.

**Comment by mikebrady** [comment]
This is what alsamixer shows on opening...

![alsascreenshot](https://cloud.githubusercontent.com/assets/4265913/6018861/11cae290-ab92-11e4-9657-6ff0601e3c33.png)

**Comment by Jeroen-R** [comment]
I am going to try again tonight,

My alsamixer is set to the top of the white area, perhaps it needs a final boost. However, I don't understand why there is audio output from the shell and not from a daemon. Same alsa, same user.

Are alsa volume settings saved separately for the root user somewhere or is it shared between all users?

**Comment by mikebrady** [comment]
AFAIK, the alsa settings are stored in the device itself, so would be universal. I wonder, though, if it's possible that there are two different default devices, depending on how the user is logged in. It seems very farfetched, TBH. If you added an explicit output device, that might circumvent the issue: `sudo start-stop-daemon --start --pidfile /var/run/shairport-sync.pid --exec /usr/local/bin/shairport-sync -- -d -v -a "Living Room CLI" -- -d hw:0`

**Comment by Jeroen-R** [comment]
I think I got it working in a reliable way now.

I hope this will help someone else (or perhaps I am the only idiot). There are a combination of factors:

1. During system startup it appears to ignore .asoundrc in the /root folder. Manually running 'sudo /etc/init.d/shairport-sync restart' after booting does pick up .asoundrc (which points it to the correct audio card). I have no idea if this is a problem with ALSA or with sharport-sync. To the best of my knowledge the original shairport did not suffer from this problem.

2. During my previous tests, at times it may not have appeared to work because the volume level is so low. The firrst 50% of the volume slider on the ipad generates almost no audio output (when played to shairport-sync). I have to crank it up all the way. I may be wrong, but this appears to be related to how shairport-sync deals with volume levels.

I have now hard coded the audio card in the /etc/init.d/shairport-sync script. I think I I have tested that option before, but never put the double dash in front on the '-d' parameter. 

I haven't (re)tried adding the '--chuid pi' option. One step at a time.

Thanks for all your help. I know you don't have to do this so really appreciate it.

**Comment by mikebrady** [comment]
Thanks for the update. A couple of suggestions for anyone reading this issue later:
* It's probably wise to explicitly set the output device and not rely on the default setting, as it may change depending on which environment Shairport Sync is running in.
* You should always try to use hardware volume control. However, if you do use software volume control, you should set the hardware volume control to 100% using `alsamixer` or whatever. 
* The volume control profile is designed to allow smooth changes at low volumes as well as large changes at high volumes. (This fixes a problem, IMHO, with the original Shairport.)
