### ISSUE TITLE
Works with iOS10 but not OS X Sierra?

### ISSUE THREAD

**Issue by jpete24** [mikebrady/shairport-sync#400]
So i followed this tutorial (http://www.redsilico.com/multiroom-audio-raspberry-pi) to install Shairport-Sync on my custom Debian server running Jessie. Everything works with iOS 10 when I use airplay on my phone, but for some reason it throws an error on OS X Sierra. See the attached image. I have my firewall off on my computer and it still doesn't work. Is there something with Sierra that breaks this or is it something with my installation? I've restarted everything, server, router, computer, still no solution. I'm running a Airport Extreme as my router.

<img width="486" alt="screen shot 2016-10-16 at 11 29 16 pm" src="https://cloud.githubusercontent.com/assets/14237434/19452666/797a0464-9477-11e6-94cc-de138df58164.png">

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. Shairport Sync definitely does work with iTunes on macOS Sierra. There are some old messages about this problem with Airport Expresses – it might be worth having a quick look at them. IPv6 figures prominently, so is it possible you have IPv6 issues?

Also, it might be worth having a quick check of the README.md installation instructions on this site.

Let us know how you do, please.

**Comment by jpete24** [comment]
Why would it work on my iPhone but not my MacBook? I would only assume that its something with OSX?

**Comment by mikebrady** [comment]
Could it be that you've done something to IPv6 settings the Mac?

**Comment by jpete24** [comment]
I use standard settings for my mac. I haven't tinkered with anything on IPv6. Should IPv6 be off or on?

**Comment by jpete24** [comment]
Could it be as simple as this??

Use Finder to open the Applications folder
Select the "Utilities" folder
Select "Terminal"
A screen will open.  At the prompt, enter the following command to determine all of your Mac's network interfaces:  networksetup -listallnetworkservices
To disable IPv6 for wireless, enter the following command: networksetup -setv6off Wi-Fi
To disable IPv6 for Ethernet, enter the following command: networksetup -setv6off Ethernet
To exit the terminal window, open the "Terminal" menu next to the Apple menu at the top left of the screen and select "Quit Terminal"

I'll check when I get home.

**Comment by mikebrady** [comment]
I think it should be on "Automatic", in the "Advanced" tab of the Networks System Preference.

BTW, it might be worth restarting Mac, Shairport Sync device and router first :)

**Comment by jpete24** [comment]
Already did the restart on all devices. Do you have IPv6 on automatic and it still works? Is there a setting on Shairport that would cause this issue?

**Comment by mikebrady** [comment]
Yes, I leave the IPv6 setting at Automatic – I think it's the default.

**Comment by mikebrady** [comment]
It might be helpful to do an `ifconfig` on the Shairport Sync device and also on the Mac and to post the outputs here.

**Comment by jpete24** [comment]
Here is ifconfig from my mac:

`lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether (redact)
	inet 10.0.1.8 netmask 0xffffff00 broadcast 10.0.1.255
	inet6 fe80::(redact)a%en0 prefixlen 64 secured scopeid 0x4 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether (redact)
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether (redact) 
	inet6 fe80::(redact)2%awdl0 prefixlen 64 scopeid 0x6 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::(redact)a%utun0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>`

and from my debian server:

`eth0      Link encap:Ethernet  HWaddr (redact) 
          inet addr:10.0.1.112  Bcast:10.0.1.255  Mask:255.255.255.0
          inet6 addr: (redact)f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2108158 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1780084 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2298584665 (2.1 GiB)  TX bytes:1598705624 (1.4 GiB)
          Interrupt:16 Memory:d0400000-d0420000 
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4139602 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4139602 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:20304651738 (18.9 GiB)  TX bytes:20304651738 (18.9 GiB)`

**Comment by jpete24** [comment]
So AirFoil works on my Mac, but the default OS X system doesn't work. Seems odd.

**Comment by jpete24** [comment]
So I uninstalled Airfoil and its working now....weird without it.

**Comment by mikebrady** [comment]
Interesting. So it might be that AirFoil and the built-in system interfere with one another – I guess it's plausible. I was interested to see if your IPv6 addresses had the same scope...

**Comment by mikebrady** [comment]
Would it be safe to close this?
