### ISSUE TITLE
Support for HTC10

### ISSUE THREAD

**Issue by flyingmichael** [mikebrady/shairport-sync#401]
Hi,

the HTC 10 natively supports AirPlay. If i try to connect my phone via ShairPort to my raspi3 with rasipian jesse i get the following: "WARNING: required params missing from announce"

Its just with the built in AirPlay from HTC Connect.
If i try another Streaming App like  AirAudio its working fine ( just the Microphone sound because device is not rooted).

Ist there any possibility to get the HTC 10 work with Built in AirPlay and Raspi3 with ShairPort?(without root) 

I hope there is a solution.

best wishes

Michael

**Comment by mikebrady** [comment]
Hi there. I thought we had gotten this working, with the help of @joerg-krause. Anyway, could you post some of the log from Shairport Sync?

**Comment by flyingmichael** [comment]
Hi, Thanks for the fast reply!
Im new in this topic and i cant find any Log. Is there a How To or something where i can find it? :D

I also tried it with the included Shairport in OpenElec and OSMC but the whole OS is freezing after connect.

Thank you very much.

**Comment by mikebrady** [comment]
To enable logs, set the `log_verbosity` to 1 or 2. The log entries will appear in the standard log.

I'm not sure whether it is Shairport Sync another, older shairport that's in OpenELec and OSMC.

If it's Shairport Sync, the application is called `shairport-sync`.

**Comment by flyingmichael** [comment]
Hi Mike!

i reinstalled shair point like the installation guide here and it works.... rlly i just dont know where i get my version... 

Thank you very much :D it works perfectly. Just the latency is a bit much but its okay. Maybe i can get it a bit better . 

THANK YOU :)

**Comment by mikebrady** [comment]
I'm glad to hear that it's working for you! The latency is decided by the sender – the HTC in this case – so I guess you're stuck with it...
