### ISSUE TITLE
shairport-sync no pid

### ISSUE THREAD

**Issue by dony71** [mikebrady/shairport-sync#402]
compile with
./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-piddir=/var/run --with-systemv
but no pid in /var/run
how to enable logfile? i don't know how to debug this

**Comment by mikebrady** [comment]
Hi there. Shairport Sync will only put a PID if it's run in the "daemon" mode.
Enable the log file by setting the `log_verbosity` to 1 or 2. Entries will appear in the standard log.

**Comment by dony71** [comment]
thanks
