### ISSUE TITLE
ab_mutex lock

### ISSUE THREAD

**Issue by lujnan** [mikebrady/shairport-sync#405]
I am porting shairport-sync to android system, Now I found the 'ab_mutex' will be locked first in buffer_get_frame() function that called by 'player_thread_func' thread. So when the **rtp_audio_thread** call the 'player_put_packet' function and will be blocked, Because 'player_put_packet' can't lock 'ab_mutex'.
If I commentted the 'pthread_mutex_lock(&ab_mutex);' and 'pthread_mutex_unlock(&ab_mutex)', My device can play sound.

**Comment by lujnan** [comment]
Commentted in 'buffer_get_frame' function

**Comment by mikebrady** [comment]
Thanks for the post. The blocking is intentional – the two threads are accessing a shared resource. Both should release the lock pretty quickly, and that's what happens in my experience. If one thread is holding the lock for a prolonged period, that's a problem worth investigating. But removing the lock on one of the threads will eventually cause a crash.

**Comment by lujnan** [comment]
I understand your mean,  I commented the codes just for test that the 'player_put_packet' was blocked.

**Comment by mikebrady** [comment]
Great, thanks.

**Comment by lujnan** [comment]
This issue has been resolved, The root cause is android 4.4 'pthread_cond_timedwait' only support CLOCK_REALTIME, So I convert the CLOCK_MONOTONIC timespec   to CLOCK_REALTIME to resolve this issue.

**Comment by mikebrady** [comment]
That's good detective work, thanks. Tell me, is there a suitable compilation flag that could be used to conditionally compile for Android?

**Comment by lujnan** [comment]
How to post the patches

**Comment by mikebrady** [comment]
Make a pull request,  I guess. 
Otherwise, if the changes are small, list them here and I'll incorporate them.

**Comment by lujnan** [comment]
Ok,I will post my changes later.

**Comment by lujnan** [comment]
Hi, Mike. Should I fork the project first before making a pull request?

**Comment by mikebrady** [comment]
Yeah. Then, make the changes to your fork and submit a pull request for it.

**Comment by lujnan** [comment]
Mike, I already make a pull request. However, I am confused that why should the "samples" (commented bellow) in the function play(short but[], int samples) of audio_pipe.c multiply by 4? 

static void play(short buf[], int samples) {
  // if the file is not open, try to open it.
  if (fd == -1) {
     fd = open(pipename, O_WRONLY | O_NONBLOCK);
  }
  // if it's got a reader, write to it.
  if (fd != -1) {
    int ignore = non_blocking_write(fd, buf, **samples * 4**); // here: why should samples multiply by 4
  }
}
