### ISSUE TITLE
Two cards with one instance

### ISSUE THREAD

**Issue by phanosp** [mikebrady/shairport-sync#406]
Hi,

I have successfully created two instances of shairport-sync each one with its own usb sound card. The output device of each configuration file is shown below

output_device = "default:CARD=Device";

output_device = "default:CARD=Device_1";

So far this is working just fine. However I have tried to created another third instance of shairport-sync where I try to use both of the above cars using the following directive 

output_device = "default:CARD=Device|default:CARD=Device_1";

but that instance is not working. I tried this because in the help file I notice that 

"Options for output alsa:
    -d output-device    set the output device [default*|...]"

so I assume that the output device can accept multiple audio cards. Is this true or is this a bug on your end???

Regards

**Comment by mikebrady** [comment]
Just one audio device, I'm afraid.

**Comment by mikebrady** [comment]
... the | symbol means "or".

**Comment by phanosp** [comment]
Too bad. I was hoping that the | symbol meant another device. What I was trying to accomplish was to be able to stream audio from my iphone to the entire ground floor (both Living Room and Kitchen). Is there another way to accomplish this with shairport-sync?

**Comment by mikebrady** [comment]
I'm afraid not, as things stand. It's one of those most-requested-features though...

**Comment by phanosp** [comment]
Thanks a lot for the quick response. I hope it is added soon.

**Comment by mistepien** [comment]
Now, very easily you can start more than one instance of shairport, and each of them can play to one device.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
