### ISSUE TITLE
/etc/shairport-sync.conf missing

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#409]
Just did a brand new install of Raspbian Jessie Lite on my Pi3 and a new install of shairport-sync.

After I've done the download and install, I then do:

sudo nano /etc/shairport-sync.conf

and get present with an empty session

I go to shairport-sync/scripts/ and there I see shairport-sync.conf

I then do:

sudo cp shairport-sync.conf /etc/init.d/

But it does not copy!

Any help?

**Comment by mikebrady** [comment]
Hi there. The configuration options have changed – you now specify the system configuration directory – check the README.md. Could that be the problem?

**Comment by rockrabbit** [comment]
I tried adding the --configfile option, but nothing there either!
