### ISSUE TITLE
--on-stop and --on-start options throw error

### ISSUE THREAD

**Issue by howels** [mikebrady/shairport-sync#41]
The on-start and on-stop arguments do not function as expected. This exact setup is working with the original shairport.

rtp_setup: cport=40863 tport=45972.
Connection from IPv4: 192.168.1.127:38936
listening for audio, control and timing on ports 58607, 37928, 47629.
Execution of on-start command failed to start
Error executing on-start command /root/squeezelite-stop
....
RTSP shutdown requested.
closing RTSP connection.
shutting down RTP thread
Audio receiver -- Server RTP thread interrupted. terminating.
Control RTP thread interrupted. terminating.
Timing RTP thread interrupted. terminating.
rtp_timing_sender thread interrupted. terminating.
Closed and terminated timer requester thread.
Timing RTP thread terminated.
Execution of on-stop command failed to start
Error executing on-stop command /root/squeezelite-start
terminating RTSP thread.

**Comment by mikebrady** [comment]
Thanks for the report. The original Shairport arrangements for executing on-start and on-stop commands have been replaced in Shairport Sync. To be capable of being executed in Shairport Sync, the commands must be *executable programs*. If you want to execute a script, if must have execute permission and should have the appropriate `#!/...` header line. See, for example, http://stackoverflow.com/questions/817060/creating-executable-files-in-linux

Doe that fix the issue?

**Comment by howels** [comment]
Thanks, I should have read the man page more closely...

**Comment by Arve** [comment]
I'm having the same issue. The relevant config line reads:

    run_this_before_play_begins = "/usr/local/bin/restart-bf.sh";

The file referenced in run_this_before_plays reads:

    #!/bin/sh
    echo "abort\n" | nc 127.0.0.1 3027 > /dev/null

I'm running shairport-sync as a systemd service (configured as suggested in README.md), and am not getting a whole lot of useful info in /var/log/syslog, only this one-liner:

    Apr 15 17:34:02 soverommet shairport-sync[1894]: Execution of on-start command failed to start

Now, given the limited access of the shairport-sync user/group, is this problem related?

**Comment by mikebrady** [comment]
Thanks for the post. Unless `echo` or `nc` are privileged on your system, then I'd say not. Have you given the full pathnames for the commands? For example, on my Linux box, `echo` is at `/bin/echo`.
