### ISSUE TITLE
Can shairport-sync keep on connecting to iPhone?

### ISSUE THREAD

**Issue by idubnori** [mikebrady/shairport-sync#410]
Can shairport-sync keep on connecting to iPhone?

I'd like to keep connecting shairport-sync to my iPhone after stopping playback or connecting shairport-sync.
I've adjusted a command parameter "-t", but could not it...
Is it an iOS specification? if not, please let me know how to do this.

- My concern steps are followings.
 1. connect to shairport-sync on iPhone.
    (And playback and stop it.)
 2. Push power button and turn off screen.
 3. Wait about 10 to 30 sec.
 4. Observe Airplay connection again. (It disconnected.)

- Environment
    - Volumio on Raspberry pi 2 B+
    - Latest version of shairport-sync via manually build
    - iOS 9 or 10 on iPhone6

Thank you for sharing this great project with us!

**Comment by mikebrady** [comment]
Hi there. I think that this is something that is controlled by iOS. With old versions of iOS, once you made a connection, it persisted. With recent versions (8 or later?), however, it seems as if the connection is dropped almost as soon as you stop using it. With iTunes, the connection still persists.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
