### ISSUE TITLE
Proper way to handle volume for maximum quality?

### ISSUE THREAD

**Issue by zeve-zz** [mikebrady/shairport-sync#412]
Love the project. Struggling a bit with the quality. 

Setup: Standard stock Pi 3 => HDMI => Vizio Sound Bar.

When airplaying, from any device, I'm noticing a bit of degradation in quality. Things just sound too meshy, I would best describe it as if you ripped audio from a youtube video back in the day.

So, one thing I noticed, when I airplayed and kept an eye on the Alsamixer (PCM), it jumped to 100 as soon as the connection was made between my laptop and the airplay/pi. Makes sense since my laptop was at 100%. However, when I dropped the audio in Alsamixerto 65-70, and then upped the volume on the sound bar, it sounds a bit better. I don't know if thats my ears playing tricks on me, or if thats expected.

Just trying to understand the best way I should be handling this. I haven't really messed with the shairport-sync config file, since i'm forcing the pi to output via HDMI (using the raspi-config UI). Should I be?

**Comment by mikebrady** [comment]
Thanks for the interesting post. If you enable `statistics` in the config file, you'll get an idea of the amount of interpolation. With zero interpolation (which you won't get, BTW), the system is bit-perfect. Up to around 250 ppm, with soxr interpolation enabled, I really have a hard time detecting any artefacts. Audio from any Apple source should be lower than that, probably much lower. Audio from a third party source typically requires more interpolation or a wider (e.i. bigger) `drift` range.

**Comment by zeve-zz** [comment]
Thanks for the prompt reply. 

Here is the output when I turned statistics to ON. Something to note: I killed the job manually and then manually restarted it, so it shows up as "Raspberry Pi" instead of the value I have set elsewhere (...although looking at the config now, Im struggling to remember _where_ that was set...)

     -57.4,      99.3,     469.3,        3758,      0,     11,      0,      1,   4297,  213,  233
     -10.3,     157.2,    2036.6,        7516,      0,     25,      0,      2,   5819,  222,  230
       8.4,      70.3,    1426.5,       11274,      0,     54,      0,      6,   5972,  220,  230
      -4.7,      37.8,    1041.7,       15032,      0,     70,      0,      6,   5988,  219,  230
       0.3,     -18.9,     956.3,       18790,      0,    106,      0,      8,   5974,  219,  230
      -3.8,      14.4,    1047.0,       22548,      0,    117,      0,      9,   5824,  220,  230

In terms of the config, I have almost no values enabled. Right now, its just "statistics", run before start, wait for completion. Everything else is commented out.

**Comment by mikebrady** [comment]
The first column is the average deviation from fully synchronised in frames. The second is the net amount of interpolation done, which is respectable enough.

The third column is the total amount of interpolation done, which is the total of insertions and deletions, and it is very high. In other words, there is a great deal of overcorrecting done, and it might account for the slightly weird quality you're detecting. I suggest you set the `drift` value to something greater than 88 – say make it 352 (There's a note about it in the README.md page).

The settings should be in the file `/etc/shairport-sync.conf`.

Once you get that sorted, you can start experimenting for real with the volume level.

**Comment by zeve-zz** [comment]
@mikebrady thanks. That seems to have made a bit of a difference in what I'm hearing. 

    -181.0,      25.0,      25.0,        3758,      0,     27,      0,      1,   4988,  213,  231
    -200.3,      62.0,      63.5,        7516,      0,     40,      0,      4,   5811,  219,  230
    -202.2,      39.3,      39.3,       11274,      0,     56,      0,      4,   5541,  219,  230
    -132.5,      37.0,      37.0,       15032,      0,     72,      0,      8,   5779,  218,  230

I'm now noticing that the volume in Alsamixer is not updating when I change the volume of my Macbook (its at 58, macbook is at 100).

**Comment by mikebrady** [comment]
Good, I think. Does it sound right now? I would think that those are pretty reasonable figures for interpolation.

**Comment by zeve-zz** [comment]
@mikebrady Not sure if its perfect yet, or that it ever can be, but it is definitely significantly better quality. Just not sure how to proceed with volume. What would you recommend as the optimal scenario?

**Comment by mikebrady** [comment]
Not too sure myself, TBH. If, after a lot of listening, you think there is a qualitative difference between the highest level and something less on the mixer, I guess we could add [yet another] setting to be able to specify the maximum level the mixer should be set to. For example, if the maximum level the mixer is capable of is 3.2 dB but the highest acceptable level is -4 dB, then adding the ability to have a setting like `output_level_max = -4` would be worth thinking about.

Actually another user had a similar idea, but his use case was for the regular PWM DAC, I think. (I can't locate the issue right now...)

It might take a little while to get around to it...

**Comment by zeve-zz** [comment]
@mikebrady understood. I don't think its necessary. I'll find a way to make due.

On a maybe related note, I just experienced for the first time a crash with shairport. Suddenly the music stopped and I noticed the airplay receiver was no longer available. I then logged in via ssh to see if it had infact failed.

pi@raspberrypi:~ $ shairport-sync
Process 482 died: No such process; trying to remove PID file. (/var/run/shairport-sync.pid)
Successful Startup

Could this be related to the drift setting being changed? The only other change I made was that I set "allow_interruptions" to yes.

**Comment by mikebrady** [comment]
Thanks. The `allow_interruptions` is problematic, as it's not something that is a standard Apple behaviour. So what happens when another device is allowed to interrupt the current session is that Shairport Sync tries to forcibly stop the session. Unfortunately, the sender to the current session doesn't know this and keeps sending stuff. Occasionally this seems to crash Shairport Sync. I have not been able to replicate the misbehaviour reliably so I haven't been able to nail the problem exactly.

**Comment by mikebrady** [comment]
A lot of changes have been made to Shairport Sync, including a way of handling interruptions that is much more reliable. So, closing the issue. Thanks for your contribution. Please open a new issue if necessary.
