### ISSUE TITLE
Shairport sync suddenly stopped working

### ISSUE THREAD

**Issue by hdsjulian** [mikebrady/shairport-sync#413]
Hi, 
i'd love some hints on how to debug this. I have a raspi, raspbian (latest something), shairport sync (compiled about a month ago). 
Worked like a charm. Perfect. No problems at all. 
Yesterday it started getting hiccups. Suddenly stopped, buffering, etc. Now it stopped alltogether, won't connect anymore. System is up and running, Daemon is up and running. No idea how to approach this. Ideas?

**Comment by mikebrady** [comment]
Hmm. If it's connecting over WiFi, Is WiFi ower save mode off?

**Comment by hdsjulian** [comment]
i changed nothing in the config

**Comment by hdsjulian** [comment]
how would i find that out?

**Comment by PeterPablo** [comment]
Enter `iwconfig` in the console and take a look at the output. The power save mode is deactivated, when you have the following line present: `Power Management:off`

**Comment by mikebrady** [comment]
There's a bit about it in the TROUBLESHOOTING.md page. If that isn't it. I'd be looking for something that's changed.

**Comment by hdsjulian** [comment]
@mikebrady nope, that's not it. unfortunately it broke down in the middle of running so nothing changed before it stopped working (at least i didn't change anything i didn't touch the raspi for weeks). the device is visible in itunes but won't connect.

**Comment by Vince69** [comment]
SD card full ?

**Comment by mikebrady** [comment]
Interesting idea that the SD card might be full. Did you fully expand the file system (with `raspi-config` when building the system in the first place?

**Comment by mikebrady** [comment]
Hi there. Di you ever resolve this issue?

**Comment by mikebrady** [comment]
Closing the issue. Thanks for your contribution. Please open a new issue if necessary.
