### ISSUE TITLE
DBUS MPRIS MediaPlayer2 support - i.e. play/pause and metadata via dbus

### ISSUE THREAD

**Issue by moritzmhmk** [mikebrady/shairport-sync#414]
Hi!

Any plans on implementing [dbus support](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html)?

This would allow GUIs like the Ubuntu audio menu to show Controls and Metadata for shairport sync. ![Ubuntu Audio Menu](http://i.stack.imgur.com/hvh8T.png)

It seems like a clean way of implementing the metadata access and playback control :)

@mikebrady whats your opinion on this?

**Comment by mikebrady** [comment]
Hi there. Thanks for the suggestion. I am indeed struggling to get a very basic `dbus` interface working. However, it will be quite a while before it is useful. I'm hoping to get a very basic one onto it in a month or so, and then it will be a question of adding functionality. It's not an issue with `bus` that has me struggling; it's simply that I don't have a lot of time. But it's definitely on the radar.

**Comment by moritzmhmk** [comment]
any news? Is there an alpha version one can test? ;)

**Comment by mikebrady** [comment]
No new yet, but it's still simmering away. I'm getting the hang of D-Bus. Is there any convenient documentation about what the Ubuntu audio menu expects and does, in terms of D-Bus signals?

**Comment by moritzmhmk** [comment]
there seems to be some progress regarding dbus - anything new on mpris?

**Comment by mikebrady** [comment]
Not so far – trying to get a small Shairport Sync native suite working before looking at mpris.

**Comment by mikebrady** [comment]
A lot of work has been done – quite a functional MPRIS interface and a pretty decent native D-Bus interface. Also an MQTT interface. So, closing the issue. Thanks for your contribution. Please open a new issue if necessary.
