### ISSUE TITLE
Supporting other RPi sound cards?

### ISSUE THREAD

**Issue by shawaj** [mikebrady/shairport-sync#419]
Hi,

In theory, will this work with any RPi soundard - i.e. it uses the standard kernel from Jessie Lite?

You mention IQaudio but not any others.

Thanks

**Comment by mikebrady** [comment]
Shairport Sync will support any card that does "CD" quality output, i.e. 44,100 stereo frames per second, each frame consisting of a signed little-endian 16 bit sample from left and right channels.

The card must have its drivers and stuff installed, and in their Raspberry P i that means it should have the correct "device tree" enabled – it's a setting in there boot configuration file. The image above has the correct settings, I presume, for IQaudIO stuff, but you'll have to ensure you have the correct device tree for whatever card you're using. This is completely separate from Shairport Sync, and you can use standard ALSA tools, e.g. `aplay`, `alsamixer`, `amixer` etc. to check what you've got.

**Comment by shawaj** [comment]
So anything in the standard RasPi kernel that meets those specs will work?

Do you publish a RasPi image yourself?

Thanks

**Comment by mikebrady** [comment]
Yes indeed, and it should work in  pretty much any modern Linux with ALSA support.

I don't publish any standard images, I'm afraid.

**Comment by mcnoche** [comment]
I know this is an older thread but just to add some anecdotal information I have used shairport-sync with the Wolfson WM8731 DAC using the rpi-proto overlay in Raspbian Jessie.

**Comment by shawaj** [comment]
Seems like it should work with any of the JustBoom, HiFiBerry and IQaudIO range then also based on what @mikebrady said above

**Comment by ktb83** [comment]
I'll add that I haven't been able to get it to work properly with the new Audio Injector Octo sound card which has 8 channels.
```
Apr 30 19:41:14 raspberrypi shairport-sync[22297]: audio_alsa: Channels count (2) not available for device "hw:0": Invalid argument
```

Is there any chance of adding an ALSA back end setting option for the number of channels?

**Comment by mikebrady** [comment]
Thanks for the post. That looks like an interesting card! Other multichannel cards seem to expose a two-channel interface that Shairport Sync can use. I guess it's a firmware issue. The problem with the `plughw:0` option is that is may not return the correct synchronisation. Can you post the output of `$ amixer` and/or `$ aplay -L` please?

**Comment by ktb83** [comment]
I'm using Raspbian Stretch with the 4.9.24-v7+ kernel on a Raspberry Pi 3 B. "hw" only works with all 8 channels (which I suppose is expected), while "plughw" supports 1-8 channels.
```
pi@raspberrypi:~$ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right - Rear Left - Rear Right - Front Center - Woofer - Side Left - Side Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 52429 [80%] [on]
  Front Right: Playback 52429 [80%] [on]
  Rear Left: Playback 65536 [100%] [on]
  Rear Right: Playback 65536 [100%] [on]
  Front Center: Playback 65536 [100%] [on]
  Woofer: Playback 65536 [100%] [on]
  Side Left: Playback 65536 [100%] [on]
  Side Right: Playback 65536 [100%] [on]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right - Rear Left - Rear Right - Front Center - Woofer - Side Left - Side Right
  Limits: Capture 0 - 65536
  Front Left: Capture 65536 [100%] [on]
  Front Right: Capture 65536 [100%] [on]
  Rear Left: Capture 65536 [100%] [on]
  Rear Right: Capture 65536 [100%] [on]
  Front Center: Capture 65536 [100%] [on]
  Woofer: Capture 65536 [100%] [on]
  Side Left: Capture 65536 [100%] [on]
  Side Right: Capture 65536 [100%] [on]
```
```
pi@raspberrypi:~$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
anyChannelCount
sysdefault:CARD=audioinjectoroc
    audioinjector-octo-soundcard, 
    Default Audio Device
dmix:CARD=audioinjectoroc,DEV=0
    audioinjector-octo-soundcard, 
    Direct sample mixing device
dsnoop:CARD=audioinjectoroc,DEV=0
    audioinjector-octo-soundcard, 
    Direct sample snooping device
hw:CARD=audioinjectoroc,DEV=0
    audioinjector-octo-soundcard, 
    Direct hardware device without any conversions
plughw:CARD=audioinjectoroc,DEV=0
    audioinjector-octo-soundcard, 
    Hardware device with all software conversions
```

Here's my .asoundrc:
```
pi@raspberrypi:~$ cat ~/.asoundrc
pcm.!default {
#       type hw
#       card 0
        type plug
        slave.pcm "anyChannelCount"
}

ctl.!default {
        type hw
        card 0
}

pcm.anyChannelCount {
    type route
    slave.pcm "hw:0"
    slave.channels 8;
    ttable {
           0.0 1
           1.1 1
           2.2 1
           3.3 1
           4.4 1
           5.5 1
           6.6 1
           7.7 1
    }
}

ctl.anyChannelCount {
    type hw;
    card 0;
}
```

speaker-test:
```
pi@raspberrypi:~$ speaker-test -D plughw:0 -c 2 -t wav -l 1

speaker-test 1.1.3

Playback device is plughw:0
Stream parameters are 48000Hz, S16_LE, 2 channels
WAV file(s)
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 32 to 32768
Period size range from 16 to 16384
Using max buffer size 32768
Periods = 4
was set period_size = 8192
was set buffer_size = 32768
 0 - Front Left
 1 - Front Right
Time per period = 2.402744
pi@raspberrypi:~$ speaker-test -D hw:0 -c 2 -t wav -l 1

speaker-test 1.1.3

Playback device is hw:0
Stream parameters are 48000Hz, S16_LE, 2 channels
WAV file(s)
Channels count (2) not available for playbacks: Invalid argument
Setting of hwparams failed: Invalid argument
pi@raspberrypi:~$ speaker-test -D plughw:0 -c 8 -t wav -l 1

speaker-test 1.1.3

Playback device is plughw:0
Stream parameters are 48000Hz, S16_LE, 8 channels
WAV file(s)
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 32 to 32768
Period size range from 16 to 16384
Using max buffer size 32768
Periods = 4
was set period_size = 8192
was set buffer_size = 32768
 0 - Front Left
 4 - Center
 1 - Front Right
 7 - Side Right
 3 - Rear Right
 2 - Rear Left
 6 - Side Left
 5 - LFE
Time per period = 10.762929
pi@raspberrypi:~$ speaker-test -D hw:0 -c 8 -t wav -l 1

speaker-test 1.1.3

Playback device is hw:0
Stream parameters are 48000Hz, S16_LE, 8 channels
WAV file(s)
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 32 to 32768
Period size range from 16 to 16384
Using max buffer size 32768
Periods = 4
was set period_size = 8192
was set buffer_size = 32768
 0 - Front Left
 4 - Center
 1 - Front Right
 7 - Side Right
 3 - Rear Right
 2 - Rear Left
 6 - Side Left
 5 - LFE
Time per period = 10.762748
```

**Comment by mikebrady** [comment]
Thanks. That confirms that two-channel access to the card hasn't been provided in the firmware. Some users in the closed issues have been able to map Shairport Sync to specific channels in multi channel cards, so it might be worth a look there...

**Comment by mikebrady** [comment]
BTW, it seems as if the Audio Injector Octo cards aren't available to buy. The kickstarter seems closed (?).

**Comment by ktb83** [comment]
Thanks for the tip on looking through the closed issues. I think I went through all the issues which matched searches for "channel" and "channels", but I didn't find anything which seems exactly relevant. I'll keep trying.

Correct. The Kickstarter campaign is closed. I think most backers will receive their Octo sound cards (with RCA breakout boards) soon. Some backers (me included) opted for additional powered balanced breakout boards (with TRS jacks and I think a preamp board has been added with this option) too which will probably be delivered by the end of May. I think they are open to purchases outside of the campaign, but I wouldn't be surprised it they are currently too busy to have set up any sort of formal purchasing process. I believe that will change in the future. If you're interested, I'd recommend you try posting in the forum like someone else did -- http://www.flatmax.org/phpbb/viewtopic.php?f=9&t=403.

**Comment by ktb83** [comment]
I was able to get **output_device = "anyChannelCount";** working for the Audio Injector Octo. It seems I needed to give the shairport-sync user its own .asoundrc config. Also, using **output_device = "default";** works if I modify the shairport-sync systemd service to run as the pi user or if I run pulseaudio in system mode. I'm not sure whether either approach is better than using plughw, but it seems like there is less of a delay.

**Comment by mikebrady** [comment]
Sorry, I forgot about this issue – have you had a look at #343?

**Comment by mikebrady** [comment]
Pulseaudio basically messes synchronisation up – IMHO, it's best to avoid it.

**Comment by mikebrady** [comment]
Closing the issue. Thanks for your contribution. Please open a new issue if necessary.
