### ISSUE TITLE
Static on loading some pages in Chrome

### ISSUE THREAD

**Issue by billtoth** [mikebrady/shairport-sync#42]
Apologies that I'm very new to all of this, so I may be describing a problem on my end, or a feature-not-a-bug, or I may give insufficient information to diagnose it, but I'll do my best. Basically, certain things I do on my laptop (which is providing the audio source) cause the speakers connected to my Pi, which are otherwise silent when no audio is transmitted, to produce static for a few seconds. It seems to occur whenever I load a webpage that might play some form of media, even if it isn't going to play it yet (e.g., facebook, feedly, youtube). 

I assume this is a result of priming for video that might be coming from the browser, but I wanted to see if there's a fix to prevent this static, or if it's a problem on my end that I could solve (or that I can't solve until I get better audio hardware). Thanks!

**Comment by mikebrady** [comment]
Thanks for the report. A few questions:
* What OS is your laptop running?
* What program is it using to send audio to the Pi?

**Comment by billtoth** [comment]
Laptop is running OSX 10.10.1 (about to upgrade to 10.10.2 though). Connecting via AirPlay as a sound output option through settings, and playing things however they come up, in this case Chrome. Generally, it seems like HTML 5 videos sync, though pause/play has a 2 second delay (sounds like that's the norm), but flash videos just play with the 2 second delay in the audio.

**Comment by mikebrady** [comment]
Thanks. I'm running 10.10.2 here. I've tried Chrome on a few pages with what I think are HTML 5 movies, and can't hear the glitches. If you know of any pages that do it reliably, I'd be obliged. My guess is that it's a flaw in Chrome, but then I would say that anyway. In any case, I'd really like to hear the problem for myself.

**Comment by billtoth** [comment]
For one, it occurs nearly every time I load my Facebook newsfeed & even when I scroll on an already loaded page (presumably loading more of the newsfeed). I'll note that I did the recommended configuration but excluded the soxr part.

**Comment by mikebrady** [comment]
Excellent – I'll experiment.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
