### ISSUE TITLE
iOS 10, lost sync issue

### ISSUE THREAD

**Issue by xmflsct** [mikebrady/shairport-sync#422]
I try to airplay music/youtube to shairport-sync installed on a Raspbian on a Raspberry Pi 3, in the output, it says lots of times:
`Lost sync with source for 4 consecutive packets -- flushing and resyncing.`
thus almost I cannot playback a piece nicely. However when I use lower version of iOS device, it is fine. And if I use -r=0, it will stream from iOS 10, but the sound will drop per some seconds.

Anybody has the same issue?

**Comment by mikebrady** [comment]
This shouldn't be happening, so some troubleshooting might be in order. If you're connecting to the Pi over WiFi, then it's worth checking to ensure that WiFi power management is off. If it is, then start checking your network in general – some routers can cause this kind of blocking and its worth checking for firmware updates.

**Comment by xmflsct** [comment]
Thanks @mikebrady for your super fast reply! I have tried to remove and reinstall shairport-sync again, and the issue is gone. Sorry for not trying it hard enough. :)

By the way, after I reinstall the software, I had problem with permission of pulseaudio. Somehow although I have ALSA as the only available audio output, still, the software first use pulseaudio as default. I search further on this issue and found that on issue [#157](https://github.com/mikebrady/shairport-sync/issues/157) you mentioned that pulseaudio is not really supported. So I remove it from my Pi, and everything works now!
