### ISSUE TITLE
shairport-sync and snapcast

### ISSUE THREAD

**Issue by nwolcdas** [mikebrady/shairport-sync#424]
Hello guys,
 i build following Setup. I installed on 3 Raspberry PIs shairport-sync and snapcast. On one PI the snapcast Server is installed. So i would like to pipe the output on the main server to the snapcast output (/tmp/snapfifo). 

For explaining:  IOS Device > shairport-sync > snapcast > broadcast sound to all pi's. 

Follwoing config i used for shairport-sync:

general = {
  name = "Flur";
  output_backend = "pipe";
};

alsa =
{
output_device = "default";
mixer_device = "hw:0";
mixer_control_name = "PCM";
};

sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 20;
}

pipe = {
  name = "/tmp/snapfifo";  
  audio_backend_latency_offset = 0;
  audio_backend_buffer_desired_length = 44100;
}

If I used the option output_backend = "pipe"; shairport told me following:

Nov 15 15:35:05 flur systemd[1]: Starting ShairportSync AirTunes receiver...
Nov 15 15:35:05 flur systemd[1]: Started ShairportSync AirTunes receiver.
Nov 15 15:35:05 flur shairport-sync[3467]: Invalid audio output specified!
Nov 15 15:35:05 flur shairport-sync[3467]: Available audio outputs:
Nov 15 15:35:05 flur shairport-sync[3467]: alsa (default)
Nov 15 15:35:05 flur shairport-sync[3467]: Options for output alsa:
Nov 15 15:35:05 flur shairport-sync[3467]: -d output-device    set the output device [default*|...]
Nov 15 15:35:05 flur shairport-sync[3467]: -m mixer-device     set the mixer device ['output-device'*|...]
Nov 15 15:35:05 flur shairport-sync[3467]: -c mixer-control    set the mixer control [Master*|...]
Nov 15 15:35:05 flur shairport-sync[3467]: -i mixer-index      set the mixer index [0*|...]
Nov 15 15:35:05 flur shairport-sync[3467]: *) default option

If i comment out the option, nothing happend. What is the wrong configuration? Any ideas?

**Comment by mikebrady** [comment]
Thanks for the post. Is it possible that you didn't compile `pipe` support? To find out, could you run the command `$ shairport-sync -V` and post the output string please?

**Comment by nwolcdas** [comment]
Hello Mike, this was the solution! I forgot to compile the pipe support. Now it works! thank you for your expensive time and good luck for all your projects! Best regards Nwolcdas
