### ISSUE TITLE
Volume linearity issue (unsure if related to shairport-sync)

### ISSUE THREAD

**Issue by jsarcand** [mikebrady/shairport-sync#425]
Hi!  I  have an external sound card, a Yamaha uw500.  I don't know if it driver related or shairport-sync, but my sound level is far from linear. 
Adjusting the volume with shairport-sync does adjust the volume in alsamixer. 
However, from 0%, the sound level increases rapidly and reaches an asymptote quite rapidly: from 0 @ -128db to 10% @ -58.32db. 
Setting the sound level with "amixer -R 10%+" will modify it from -128db to -115db. The latter is when it sounds correct. 
Adjusting the sound with "amixer -M 10%+" behaves like the volume control of shairport-sync.  Could you enlighten me? Is it a driver error? Thanks
(Software volume is fine)

**Comment by mikebrady** [comment]
Thanks for the posting.

The transfer function from the volume position to the output in dB is quite non linear and it changes very quickly at the very lowest levels. The idea behind this is that, in a reasonably normal listening environment, the maximum usable range is maybe 60 to 80 dB between almost inaudible and painfully loud. So, assuming that 0 dB is set to maximum tolerable level, the transfer function moves rapidly from a completely inaudible -128 dB to a barely audible -58 dB, leaving the remaining 90% of the volume range in an arguably more useful range.

Somewhat along the same lines, you can set the maximum range in dBs that the volume control can use – normally I set that to around 80 dB which gives a good compromise, I believe.

I hope this helps.

**Comment by jsarcand** [comment]
Thanks Mike, and that really helped !  Good job :+1: 😊

**Comment by mikebrady** [comment]
I'm closing this issue. Feel free to reopen if necessary.
