### ISSUE TITLE
No Config file

### ISSUE THREAD

**Issue by PrudhviBoggavarapu** [mikebrady/shairport-sync#426]
Help I have no config file I used this 

https://www.hackster.io/11798/c-h-i-p-play-speakers-7cebb9

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync has been updated since the Hackster article was written and the instructions for building it have changed slightly.

Specifically, you should add `--sysconfdir=/etc` to the `./configure` arguments. Then you'll find the configuration file in the right place.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new issue if necessary.
