### ISSUE TITLE
Compilation fails with Pulseaudio 5.0

### ISSUE THREAD

**Issue by AlessandroFerri** [mikebrady/shairport-sync#43]
I have previously installed PulseAudio 5.0, as the tutorial on the link:
http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=87138
As you may notice after installing the prerequisites, I have to remove libpulse0.
I state that I have compiled and installed by /abravive/shairport without issue and run regularly with PulseAudio 5.0.
So I installed shairport-sync as your instruction and I find the following errors:

pi@raspberrypi ~/shairport-sync-2.2 $ ./configure --with-alsa --with-avahi --with-pulseaudio --with-ssl=openssl
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for clock_gettime in -lrt... yes
checking for daemon_log in -ldaemon... yes
checking for pthread_create in -lpthread... yes
checking for exp in -lm... yes
checking for POPT... yes
checking encryption libraries chosen... checking for CRYPTO... yes
checking for SSL... yes
>>Including Avahi mDNS support
checking for avahi_client_new in -lavahi-client... yes
checking for avahi_strerror in -lavahi-common... yes
>>Including an ALSA back end
checking for ALSA... yes
>>Including a PulseAudio back end --- N.B. this is probably broken!
checking for pa_simple_new in -lpulse-simple... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking getopt_long.h usability... no
checking getopt_long.h presence... no
checking for getopt_long.h... no
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking mach/mach.h usability... no
checking mach/mach.h presence... no
checking for mach/mach.h... no
checking for memory.h... (cached) yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for error_at_line... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for clock_gettime... yes
checking for gethostname... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for pow... yes
checking for select... yes
checking for socket... yes
checking for stpcpy... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating man/Makefile
config.status: creating config.h
config.status: executing depfiles commands

pi@raspberrypi ~/shairport-sync-2.2 $ make
make  all-recursive
make[1]: Entering directory `/home/pi/shairport-sync-2.2'
Making all in man
make[2]: Entering directory `/home/pi/shairport-sync-2.2/man'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/pi/shairport-sync-2.2/man'
make[2]: Entering directory `/home/pi/shairport-sync-2.2'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT shairport.o -MD -MP -MF .deps/shairport.Tpo -c -o shairport.o shairport.c
mv -f .deps/shairport.Tpo .deps/shairport.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT rtsp.o -MD -MP -MF .deps/rtsp.Tpo -c -o rtsp.o rtsp.c
mv -f .deps/rtsp.Tpo .deps/rtsp.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT mdns.o -MD -MP -MF .deps/mdns.Tpo -c -o mdns.o mdns.c
mv -f .deps/mdns.Tpo .deps/mdns.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT mdns_external.o -MD -MP -MF .deps/mdns_external.Tpo -c -o mdns_external.o mdns_external.c
mv -f .deps/mdns_external.Tpo .deps/mdns_external.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT common.o -MD -MP -MF .deps/common.Tpo -c -o common.o common.c
mv -f .deps/common.Tpo .deps/common.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT rtp.o -MD -MP -MF .deps/rtp.Tpo -c -o rtp.o rtp.c
mv -f .deps/rtp.Tpo .deps/rtp.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT player.o -MD -MP -MF .deps/player.Tpo -c -o player.o player.c
mv -f .deps/player.Tpo .deps/player.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT alac.o -MD -MP -MF .deps/alac.Tpo -c -o alac.o alac.c
mv -f .deps/alac.Tpo .deps/alac.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT audio.o -MD -MP -MF .deps/audio.Tpo -c -o audio.o audio.c
mv -f .deps/audio.Tpo .deps/audio.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT audio_dummy.o -MD -MP -MF .deps/audio_dummy.Tpo -c -o audio_dummy.o audio_dummy.c
mv -f .deps/audio_dummy.Tpo .deps/audio_dummy.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT audio_pipe.o -MD -MP -MF .deps/audio_pipe.Tpo -c -o audio_pipe.o audio_pipe.c
mv -f .deps/audio_pipe.Tpo .deps/audio_pipe.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT mdns_avahi.o -MD -MP -MF .deps/mdns_avahi.Tpo -c -o mdns_avahi.o mdns_avahi.c
mv -f .deps/mdns_avahi.Tpo .deps/mdns_avahi.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT audio_alsa.o -MD -MP -MF .deps/audio_alsa.Tpo -c -o audio_alsa.o audio_alsa.c
mv -f .deps/audio_alsa.Tpo .deps/audio_alsa.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT audio_pulse.o -MD -MP -MF .deps/audio_pulse.Tpo -c -o audio_pulse.o audio_pulse.c
mv -f .deps/audio_pulse.Tpo .deps/audio_pulse.Po
gcc  -g -O2   -o shairport-sync shairport.o rtsp.o mdns.o mdns_external.o common.o rtp.o player.o alac.o audio.o audio_dummy.o audio_pipe.o mdns_avahi.o  audio_alsa.o   audio_pulse.o   -lpulse-simple -lasound   -lavahi-common -lavahi-client -lssl -lcrypto   -lcrypto   -lpopt   -lm -lpthread -ldaemon -lrt 
/usr/bin/ld: audio_pulse.o: undefined reference to symbol 'pa_strerror@@PULSE_0'
/usr/bin/ld: note: 'pa_strerror@@PULSE_0' is defined in DSO /usr/lib/libpulse.so.0 so try adding it to the linker command line
/usr/lib/libpulse.so.0: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [shairport-sync] Error 1
make[2]: Leaving directory `/home/pi/shairport-sync-2.2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/pi/shairport-sync-2.2'
make: *** [all] Error 2

Note in the config: >>Including a PulseAudio back end --- N.B. this is probably broken!

But in the directory / usr / lib I find:

/usr/lib/libpulse.la
/usr/lib/libpulse.so
/usr/lib/libpulse.so.0
/usr/lib/libpulse.so.0.17.3
/usr/lib/libpulsecoer-5.0.la
/usr/lib/libpulsecoer-5.0.so
etc...

If I continue the installation manually with the command

gcc  -g -O2   -o shairport-sync shairport.o rtsp.o mdns.o mdns_external.o common.o rtp.o player.o alac.o audio.o audio_dummy.o audio_pipe.o mdns_avahi.o  audio_alsa.o   audio_pulse.o   -lpulse-simple -lasound   -lavahi-common -lavahi-client -lssl -lcrypto   -lcrypto   -lpopt   -lm -lpthread -ldaemon -lrt -lpulse

and with the addition of -lpulse I can compile shairport-sync and so I can proceeding by installing shairport-sync, I run shairport-sync with the command:

./shairport-sync -a 'Ale' -- -t pulseaudio

it works, but I do not hear anything and mostly do not start with pulseaudio.
Also with
./shairport-sync -a 'Ale' -- -d hw:0
run, but but I do not hear the music

From the pact of pulse audio I see:

pi@raspberrypi ~ $ sudo pactl list clients
Client #0
	Driver: protocol-native.c
	Owner Module: 1
	Properties:
		application.name = "Old Abrasive Shairport"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "29"
		application.process.id = "2302"
		application.process.user = "root"
		application.process.host = "raspberrypi"
		application.process.binary = "shairport"
		application.language = "C"
		application.process.machine_id = "d3670ff77a0bb988a953e7f053a3f4e7"

Client #3
	Driver: protocol-native.c
	Owner Module: 1
	Properties:
		application.name = "pactl"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "29"
		application.process.id = "7764"
		application.process.user = "root"
		application.process.host = "raspberrypi"
		application.process.binary = "pactl"
		application.language = "en_GB.UTF-8"
		window.x11.display = ":0.0"
		application.process.machine_id = "d3670ff77a0bb988a953e7f053a3f4e7"

 with the old shairport, but not with shairport-sync.

If I install libpulse0 again,

sudo apt-get install libpulse0

of course I perform successfully both ./configure that make and make install, but PulseAudio 5.0 does not work. With the command:
./shairport-sync -a 'Ale' -- -d hw:0

I hear the music, but this is not the right way as abrasive/shairport run,  without installing libpulse0 again.
Is there something wrong that I have done or have not done?

**Comment by mikebrady** [comment]
Hi Alessandro, and thanks for your interest in Shairport Sync. When I was initially trying to develop a synchronised version of Shairport, I wasn't able to find the features I needed using PulseAudio as a back end. In particular, I could not find how to measure actual device latencies. Therefore, I concentrated my efforts on ALSA only. Consequently I have done no work on PulseAudio for a long time. I had thought of removing the code for PulseAudio and the other non-functional back ends, but for the moment I've left them in place, in the hope that somebody might develop them. Clearly there is a compile-time error, but when that is fixed, I'd be surprised if the system worked at all, and it certainly won't do synchronised output.

So this is a long way to say that, as far as a PulseAudio back end is concered, "you're on your own", I'm afraid.

Kind regards

**Comment by AlessandroFerri** [comment]
Hi Mike,
I'm not even so much in love with pulseaudio, since it's very complex, but in reality I am bound to pulseaudio because I have the need to calculate the fast furier transform of the audio output signal. I currently use the library impulse.c to connect as a client on pulseaudio and take the incoming audio signal to calculate the fast furier transform.
With shairport-sync, I can take the audio signal from the streaming and in-parallel compute fast furier transform. If you give me a help to get started, the rest I can develop myself.
Please tell me that you can help me.

Best regards.

**Comment by AlessandroFerri** [comment]
Hi Mike,
I'm not even so much in love with pulseaudio, since it's very complex, but in reality I am bound to pulseaudio because I have the need to calculate the fast furier transform of the audio output signal. I currently use the library impulse.c to connect as a client on pulseaudio and take the incoming audio signal to calculate the fast furier transform.
With shairport-sync, I can take the audio signal from the streaming and in-parallel compute fast furier transform. If you give me a help to get started, the rest I can develop myself.
Please tell me that you can help me.

Best regards.

Dott. Ing. Alessandro Ferri
email: alessandroferri_015@fastwebnet.it
cell.: +39 348 5412956

> Il giorno 06/feb/2015, alle ore 14:53, Mike Brady <notifications@github.com> ha scritto:
> 
> Hi Alessandro, and thanks for your interest in Shairport Sync. When I was initially trying to develop a synchronised version of Shairport, I wasn't able to find the features I needed using PulseAudio as a back end. In particular, I could not find how to measure actual device latencies. Therefore, I concentrated my efforts on ALSA only. Consequently I have done no work on PulseAudio for a long time. I had thought of removing the code for PulseAudio and the other non-functional back ends, but for the moment I've left them in place, in the hope that somebody might develop them. Clearly there is a compile-time error, but when that is fixed, I'd be surprised if the system worked at all, and it certainly won't do synchronised output.
> 
> So this is a long way to say that, as far as a PulseAudio back end is concered, "you're on your own", I'm afraid.
> 
> Kind regards
> 
>

**Comment by mikebrady** [comment]
Hi Alessandro. I've fixed the compilation issue in the latest release. When you do `shairport-sync -h` you'll get a little information on options available on the PulseAudio back end, but I have done no work on it, and I would be surprised if it worked. I'm afraid I have no time to devote to it at the present time.

Regards
Mike

**Comment by AlessandroFerri** [comment]
Hi Mike,
I thank you for the suggestions and additions. Now with the command
./shairportsync -a 'name' -o pulse

shairport-sync works fine with pulseaudio 5.0. Indeed it seems that shairport-sync+pulseaudio use less CPU than abrasive / shairport than abrasive/shairport+pulseaudio.
Now I would like to make it run as a daemon. By default, the name that appears on iTunes is:

Shairport Sync on <hostname>

I looked on /etc/init.d/shairport-sync, but I can see where it comes from and how can I change this name. Can you give me help on this?

**Comment by mikebrady** [comment]
Hi Alessandro. From the command line, enter this:
```
./shairport-sync -a "Fourier" -d -o pulse
```
This will give the service the name "Fourier" and will daemonise it.

**Comment by mikebrady** [comment]
I'm closing this as "fixed".
