### ISSUE TITLE
volume_range_db only starting from top?

### ISSUE THREAD

**Issue by ni-kan** [mikebrady/shairport-sync#432]
Hey there! Love the application, wonderful work. However, one issue:

Using HiFiBerry DAC+ Pro and my speakers, the usable volume range is from 0% to around 60%, from 60% onward it gets too loud. Therefore, I'd like to limit AirPlay's access to the volume range from 0% to 60% in order to have more granular control (and not accidentally blow out my ears).

However, the **volume_range_db** setting only allows me limit how far from maximum volume I can go _down_, e.g. only vom 100% to 60%. But I cannot set it the other way round. That would be a nice addition. 

(I tried setting volume in amixer/alsamixer but whatever I do there gets overturned whenever I change volume on my iOS- oder macOS-device airplaying to shairport-sync. I also tried playing with the **mixer_control_name** setting to shift volume control from hardware to software and back but that doesn't seem to do the trick, either.)

Any ideas?

Best,

Nick

**Comment by mikebrady** [comment]
Yikes, that's a problem I wasn't expecting! Anyhow, the solution is to put in a `volume_max_db` setting, or similar. Other users have been looking for something like this for other reasons, so maybe I should just go on ahead and do it. It might take some time, however...

**Comment by ni-kan** [comment]
Wow, thanks for your prompt reply! Yes, a `volume_max_db` sounds like a wonderful solution. Unfortunately, I'm way too unexperienced with code to be of any help with a contribution. However, if I can test something for you, I'd sure love to?

**Comment by mikebrady** [comment]
Thanks. It may be some time before I get around to it. I'll post here when I do...

**Comment by ni-kan** [comment]
Great, I'll follow this thread closely. It's the only thing that's making me miss my old AirPort Express a little (which had different output levels, I presume).

**Comment by ni-kan** [comment]
No need to hurry. In the meantime, I figured out a (very dirty!) way that works for me:

1) In the file _common.h_, I added `int32_t volume_max_db;` to the end of the _typedef struct_ of _shairport_cfg_.

2) In the file _shairport.c_, I made it read the volume_max_db value from the config file by adding 
```
if (config_lookup_int(config.cfg, "general.volume_max_db", &value))
        config.volume_max_db = value;
```
right below the area where it reads volume_range_db from the config file.

3) In the file _player.c_, where the magic happens, I added the following code right above where the hard- or software-attenuation happens (so above the double-typ variable declarations there):
```
  if (config.volume_max_db) {
      debug(1, "Volume_max_db detected, requested lowering by %d.", config.volume_max_db);
      max_db = max_db - config.volume_max_db;
      hw_max_db = hw_max_db - config.volume_max_db;
      sw_max_db = sw_max_db - config.volume_max_db;
  } else {
   debug(1, "No changes to max volume requested.");
  }
```
4) In the file _/etc/shairport-sync.conf_ all I have to do now is enter something like
`volume_max_db = 350;`

Now as I said, I'm no programmer and my quick solution may be breaking a lot of stuff. But for me it works. Interestingly, for me the hardware mixer works with a range of 10300 and lowering maximum volume with a volume_max_db of 350 works fine. I had expected I'd have to go much lower than that but obviously volume doesn't decrease in a linear way so there's some mathematical construct behind it that I don't want to mess with. Working with 350 in the conf-file and testing from there's fine for me.

**Comment by mikebrady** [comment]
Thanks for this. It looks like the number is a delta though – it's not the maximum volume, it's the amount you subtract from the mixer's maximum volume to get the maximum usable volume, I think. Is that the case? If so, I think I'd like to change it to be an absolute value.

Apart from that, the code looks fine – props to you.

**Comment by ni-kan** [comment]
Thanks! (Took me a lot of failed attempts even to just figure out that I have to use `%d.` for the debug values written to syslog to make sense, but all in all it was fun.) 

Yes, exactly, it's just a delta. I specifically implemented it this way because I had no clue what values `max_db`, `hw_max_db` and `sw_max_db` can adopt (possibly even relative to each other?) in different software/hardware-mixer-environments. Figuring that out would have required diving into your code a lot deeper than I can do in a reasonable amount of time. So going with just a delta that reduces all possible maximum volume variables by the same amount seemed like the safe way to go …

**Comment by mikebrady** [comment]
Yeah, these are all valid issues, but I think I'll go with absolute values and do some extra error and sanity checking. I think it's reasonable to expect an interested user to know the `max` and `min` mixer values if s/he is interested enough to want to alter them.

Thanks again.

**Comment by ni-kan** [comment]
Yes, absolutely, since you know how these variables work, you could easily make an absolute value function well. However, it does require the user to know what dB-value the mixer currently maxes out at and if it's a hardware or software solution with all these specifics (something I don't know how to find out apart from tinkering with the code and debug function).

I also considered the idea of a percentage (say `volume_max_db = 80;` as 80 percent of maximum volume, so `volume_max_percent` would probably be a more apt name) but didn't know how to implement that since the range doesn't work in a linear way. So simply going with `max_db = max_db * config.volume_max_db;` doesn't work. But since that would be very self-explanatory and not require previous knowledge of any (possibly hardware-specific) mixer values, I think I'd prefer that option over my delta or an absolute value.

What do you think?

**Comment by mikebrady** [comment]
Some good ideas there alright – let me chew them over.

**Comment by IngoValente** [comment]
Also interest in this! Have the same problem as ni-kan using a PHAT DAC.

**Comment by mikebrady** [comment]
Just put this functionality into the development version, if you'd care to try it out.

**Comment by IngoValente** [comment]
Seems to work like a charm here (running on raspi zero with phat dac)
Thanks for this fantastic project and your work!

**Comment by mikebrady** [comment]
So, closing the issue. Thanks for your contribution. Please open a new issue if necessary.
