### ISSUE TITLE
Send commands to clients

### ISSUE THREAD

**Issue by lordbarba** [mikebrady/shairport-sync#437]
Hi Mike, 
is there a way to send commands to clients? (Skip, Previous,)
How can i retrieve file position and duration of the current playing track?
I've searched in the issues but no result.

Thanks
Leo

**Comment by joerg-krause** [comment]
Please have a look at https://github.com/mikebrady/shairport-sync/issues/86.

**Comment by lordbarba** [comment]
Thanks!
