### ISSUE TITLE
Latency Problem with forked-daapd & Airfoil for Mac

### ISSUE THREAD

**Issue by rollinc** [mikebrady/shairport-sync#44]
Hi, at first let me thank you for your amazing work! I enjoy it every day!

I just found an minor issue. Playing music with forked-daapd and streaming it to shairport-sync and my other airplay devices (airport express, apple TV, Yamaha Receiver) - shairport-sync is out of sync. 

My setup (described above) is totally in sync by setting the latency (via -L) to 99400. But by using this setting with Airfoil for Mac it occurs that shairport-sync is out of sync.

I guess that Airfoil needs 88200 and forked-daapd 99400 as the latency setting. As described in this Issue "https://github.com/mikebrady/shairport-sync/issues/23"

>"(1) making the default latency 88,200 rather than 99,400 frames,
>(2) if a player identifies itself as iTunes, using a latency of 99,400 for iTunes >= 10 and 88,200 >otherwise."

Is it possible to add 99400 frames for forked daapd? I was not able to get the information regarding the identifier send by forked-daapd.

**Comment by mikebrady** [comment]
Thanks for your kind words – it's great to hear that Shairport Sync is enjoyed.
Can you tell me what build of forked-daapd you're using please?

**Comment by rollinc** [comment]
I use this version:
http://www.raspberrypi.org/forums/viewtopic.php?t=49928 
>1a. If you want wheezy-backports (full functionality), then add this line to /etc/apt/sources.list:
>deb http://www.gyfgafguf.dk/raspbian wheezy-backports/armhf/

Currently installed is Version 22.2.39.

**Comment by rollinc** [comment]
If you can recommend a tool, in what I can read the airplay identifier of the forked-daapd version - I´m happy to help.

**Comment by mikebrady** [comment]
Thanks. Actually, there is something you could do to see how the player identifies itself to Shairport Sync. It's doesn't need tools, but it does require a small bit of tinkering. Basically, on the Shairport Sync device, you should stop the Shairport Sync daemon, run it instead from the command line with a verbose setting, note the results and then, when finished, restart the daemon. Here is a walk-through based on one of my systems:

First, note existing setup for the running Shairport Sync service:
```
ps aux | grep shai
```
On my system, I get:
```
1016 root      7776 S    /usr/bin/shairport-sync -a Front Room -d -- -d default -t hardware -c PCM
``` 
Next, stop the service temporarily:
```
sudo /etc/init.d/shairport-sync stop
```
Now, run Shairport Sync from the command line with verbosity enabled and using almost the same arguments -- quotes may be needed -- as the service was using (you don't put it into daemon mode, i.e. you omit the `-d`):

```
shairport-sync -a "Front Room" -v -- -d default -t hardware -c PCM
```
Play something to the service. You'll get a sequence of messages on the command line. This is what I get:

```
Hardware mixer has dB volume from -60.000000 to 0.000000.
Has mute ability.
startup
avahi: avahi_register.
avahi: register_service.
new RTSP connection.
RTSP connection closed.
closing RTSP connection.
new RTSP connection.
Play connection from "iTunes/12.1 (Macintosh; OS X 10.10.2)".
Connection from IPv4: 192.168.2.22:49548
RTSP shutdown requested.
closing RTSP connection.
Audio receiver -- Server RTP thread interrupted. terminating.
Control RTP thread interrupted. terminating.
Timing RTP thread interrupted. terminating.
rtp_timing_sender thread interrupted. terminating.
Closed and terminated timer requester thread.
Timing RTP thread terminated.
```
You can see that the player identifies itself as "iTunes/12.1 (Macintosh; OS X 10.10.2)". If it was an iPhone, you'd get:
```
...
Play connection from "<iPhone's Name>".
...
```
Stop the program and restart the daemon:
```
sudo /etc/init.d/shairport-sync start
```
That's it. Please let me know the contents of the "Play connection..." line.

**Comment by rollinc** [comment]
Thanks for the walk through. This is the line in question:

Play connection from "forked-daapd/22.2".

Could you implement an extra timeframe for forked-daapd? I assume after the slash the version number.

**Comment by mikebrady** [comment]
Thanks. I believe I can do that alright, time permitting.

**Comment by rollinc** [comment]
Sounds great. Thanks!

**Comment by mikebrady** [comment]
I just pushed an update – 2.2.2 – which has an extra setting for forked-daapd of 99,400 frames and a command-line option to change it. Could you try it out?

**Comment by rollinc** [comment]
Thanks. I just tried it and it is totally in sync with my Yamaha Receiver and Airport Express Station.

**Comment by mikebrady** [comment]
Excellent!
