### ISSUE TITLE
Shairport-Sync daemon with "pulse" as the audio backend

### ISSUE THREAD

**Issue by PanDoreS** [mikebrady/shairport-sync#441]
Hi !

I'm trying to use shairport-sync as a daemon with "pulse" as a backend audio.
If I launch shairport-sync with the command line `shairport-sync -a 'Super AirPlay' -o pulse`, everything is working flawlessly like I intend to.
However, if I put in the config file inside /etc/shairport-sync.conf at the line `output_backend = "pulse";` and start the shairport-sync service, nothing is played :(
I could run manually the command said earlier inside a screen, but it's an ugly fix.
Here's the log in /var/log/syslog concerning shairport-sync : 
[log.txt](https://github.com/mikebrady/shairport-sync/files/650310/log.txt)
Configuration file : [shairport-sync.txt](https://github.com/mikebrady/shairport-sync/files/650218/shairport-sync.txt)
Is there any other parameter I should use ?
Thanks in advance

**Comment by mikebrady** [comment]
Hi there. I guess it's not the config file that's the issue, but that when it's running as a service, it is running under a different username and group and will have different permissions and different settings.

**Comment by PanDoreS** [comment]
Ok, I modified the service with my current user (here "htpc") and did a `chmod 777 /run/shairport-sync/`
And the service is launching, but I still have trouble after a reboot because "/run" permissions are reseted.
I guess I call it a night.
Thanks anyway !

**Comment by BaReinhard** [comment]
This is kind of a mickey-mouse type fix, but you could add `chmod 777 /run/shairport-sync` to your `/etc/rc.local` file

**Comment by ehaupt** [comment]
In the FreeBSD port I solved this problem with _start_precmd_ in the init script. Maybe you could adapt this solution.

See:
https://github.com/freebsd/freebsd-ports/blob/master/audio/shairport-sync/files/shairport-sync.in

**Comment by mikebrady** [comment]
So, closing this as an issue. Thanks for your contribution. BTW there is a new PulseAudio backend called `pa` – `pulse` is gone. Please open a new issue if necessary.
