### ISSUE TITLE
Connect Function

### ISSUE THREAD

**Issue by Flacedoo** [mikebrady/shairport-sync#443]
Hi,

First of all, I would like to thank you - your project is really awesome and works perfectly for me.

Could you tell me where in your project connections are handled? I tried to get an overview of your project, but didn't really found anything.

As background information: I wanted to add the functionality to control the power of my speakers via (not quite sure if it's the right term in English?) remote sockets. These little things you plug into wall sockets which are remote controlled - in my case by my raspberry.

So what I wanted to do is whenever a connection from any AirPlay device is established, I want to power them on, and when they disconnect, to shut them down. The control itself works already perfectly, so I just wanted to add this to the shairport.

Would be great if you could help me with this.

Best regards,

Flacedoo

**Comment by mikebrady** [comment]
Hi there. Thanks for the kind words, and I'm glad it's working so well for you.

Shairport Sync can execute a program just before play starts and can execute another one just after play ends. It can also optionally wait until the programs complete. I imagine that you could use the functionality of these to execute scripts in the Pi to control the sockets.

There is some detail in the `man` page and also in the sample configuration file. It can be tricky to set the programs up properly, as the environment they run in is not the same as the environment a logged-in user. You might want to search some of the issues, including closed ones, for some more information. (BTW, your use of 'via' is correct standard English usage.)

**Comment by Flacedoo** [comment]
Ah great, this is exactly what I was searching for - hadn't thought about the possibility that you already included this 👍 

Regarding your last information - I'm not quite sure what you mean. Will these programs specified in the configuration file run before / after every single piece of audio - like a song? Imagine I'm playing a Spotify or iTunes playlist, will these programs run before and after every single song - or before and after the device is connected and started the first song / stops sending audio? Especially the fact that there are small breaks between songs worries me here?

**Comment by mikebrady** [comment]
If you play an album or playlist in iTunes or the Music app on iOS you get a play signal when the first track starts and a stop signal when the last one ends. For other sources I don't know. It might be worth experimenting, but you might end up having to implement some kind of timer to wait for an appreciable time after a stop signal is received before turning the sockets off.

**Comment by mikebrady** [comment]
Okay to close this issue?
