### ISSUE TITLE
Support for specific network interfaces.

### ISSUE THREAD

**Issue by MrCavallo** [mikebrady/shairport-sync#444]
This is similar to the closed issue;

   https://github.com/mikebrady/shairport-sync/issues/267

In my case, I have various machines with both a regular ethernet interface, and a (much slower) VPN interface.  As it stands, shairport-sync appears to advertise itself on AVAHI_IF_UNSPEC (if I'm reading mdns_avahi.c correctly).  As a result, it's a crapshoot whether zeroconf resolves a LAN address, or a VPN one.  Sending audio streams through my VPN is not a great idea.

It would be great to have a way to specify in the conf file that shairport-sync only broadcast its presence on (for example) 'eth0'.  There are already options for name and port.  Having an interface option (that defaults to AVAHI_IF_UNSPEC if not specified) would be utterly swell.

If there already is a way to do this and I've missed it, please, please, please correct me.

**Comment by MrCavallo** [comment]
Addendum: For larks, I modified the AVAHI_IF_UNSPEC variable in mdns_avahi.c to just be 2.  That seems to correspond to eth0 on all the Raspberry Pi's in my life.  I compiled and installed this modified version and it behaves exactly as I want it to, with AirTunes speakers showing up on eth0 only.  However, I'm sure this is very much not the best way to go about this.  It's deeply hacky and likely quite fragile.  Official support via the config file would be far more wholesome.

Not sure if this is something worth your time to include, but it can't hurt to ask.

**Comment by mikebrady** [comment]
This is very interesting, thanks. I'll have a look at it and see if can be incorporated in the development version. Good work!

**Comment by mikebrady** [comment]
Just put this functionality into the development version, if you'd care to try it out.

**Comment by mikebrady** [comment]
Done in version 3, I think.

**Comment by mikebrady** [comment]
Closing the issue – job done. Please open a new issue if necessary.
