### ISSUE TITLE
Missing a donate button

### ISSUE THREAD

**Issue by Bazmundi** [mikebrady/shairport-sync#445]
How can we buy you a beer to say thank you?

**Comment by roblan** [comment]
+1

**Comment by VirtualWolf** [comment]
Still no donate button? :) Honestly, I think a lot of people would be happy to throw a few dollars (or more) your way, especially with your tireless help supporting people with the various issues and questions that pop up!

**Comment by mikebrady** [comment]
Okay, I give in 🙂. I have a PayPal account you can use at https://www.paypal.me/UMBr. Many thanks.

**Comment by bedrin** [comment]
GitHub now allows to add a donate button to your project page

**Comment by mikebrady** [comment]
Done, thanks!
