### ISSUE TITLE
Set audio_pipe output to full volume?

### ISSUE THREAD

**Issue by StevenPloog** [mikebrady/shairport-sync#447]
Is it possible to output PCM samples to the audio pipe at 100% volume all the time while still allowing the device that is playing to control the volume of samples sent to ALSA?

**Comment by mikebrady** [comment]
Hi Steven. I'm afraid not – only one backend can be active at a time. However, you could run two instances of Shairport Sync on the same machine – there is information in some of the issues about doing it. Good luck!

**Comment by StevenPloog** [comment]
Thanks for the suggestion, I'll look into that.
