### ISSUE TITLE
Play to two instances of shairport-sync at once

### ISSUE THREAD

**Issue by StevenPloog** [mikebrady/shairport-sync#448]
I may have closed #447 too early...

Looking through the older issues I found out how to start two instances of shairplay (#37) and have that working just fine.

I would like to play what is being sent from an airplay device over my speakers with volume control from the device, while also capturing a full amplitude PCM stream. With my current setup I can play either to speakers or send PCM data to a pipe. Is there a way to do both at once?

Ex: One iPhone displays one AirTunes receiver, plays audio to that. The receiver plays to both a set of speakers (volume depends on iPhone volume) and sends PCM data to a pipe (volume locked to 100%).

**Comment by mikebrady** [comment]
Sorry, yeah. Having two instances of Shairport Sync to solve your problem presupposes that your source can send to multiple outposts, and while iTunes does have this capability, iOS does not. 

Unfortunately, it would take a fair amount of work to give Shairport Sync the functionality you are looking for.

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
