### ISSUE TITLE
RPi sound output over both hdmi and jack at the same time?

### ISSUE THREAD

**Issue by scrissti** [mikebrady/shairport-sync#449]
Hi,
any idea if this is possible?
My config is currently
alsa =
{
  output_device = "hw:0";
  mixer_control_name = "PCM";
}
and it actually outputs to hdmi only not jack.

**Comment by mikebrady** [comment]
Hi there. Have a look at closed issue #423.

**Comment by scrissti** [comment]
Thanks,
unfortunately the other thread does not solve my problem to output audio both to hdmi and jack at the same time. Just like kodi is doing when selecting sound ouput hdmi+analogue jack.

I need this functionality so that I can send music to my receiver both digital and analogue so that it goes to Zone 2 as well.

**Comment by mikebrady** [comment]
No progress on this issue, I'm afraid. Shairport Sync can output to only one output at a time.
