### ISSUE TITLE
Release tags for branch 2.2

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#45]
Can you provide release tags for the versions of the branch 2.2? Many thanks!

**Comment by mikebrady** [comment]
Hi Jörg. I certainly will, but I'm waiting to accumulate a few issues before I do so. Do you think that this is the right approach, or should I make a new tag for everything as it comes along?

**Comment by joerg-krause** [comment]
I saw that you committed some release notes for a version 2.2 and a version 2.2.1. It would be nice to have a tag and a release tarball for every version as build systems or package managers prefer released versions. This will allow users and maintainers of such systems to test and use new features, enhancements, and bug fixes earlier.

**Comment by mikebrady** [comment]
Thanks for your comment. I have just published a tag for 2.2.1. From now on, I'll publish a tag for every issue; how about that. It means that any problems with changes should be easy to isolate. Does that sound okay?

**Comment by joerg-krause** [comment]
Very okay! I'll update the version in Buildroot in the next days. Many thanks again for this great project!
