### ISSUE TITLE
Mono sound when using shairport-sync

### ISSUE THREAD

**Issue by Umberto73** [mikebrady/shairport-sync#451]
Hi,

I've installed shairport-sync to enable airplay on OSMC (since the build-in Airplay does not work). But when I play audio via Airplay, I hear the left channel on both speakers resulting in mono sound. When I play the audio via OSMC, I hear it perfectly in stereo.

I'm using a DAC (DDDAC 1794) that is connected via I2S to my raspberry pi 2. I have selected the 'hifiberry-dac-overlay' as audio output device using 'My OSMC'.

I've analyzed the problem using 'aplay' and dumping the proc asound status (cat /proc/asound/card0/pcm0p/sub0/status). 
What i've found so far is that when I play audio using 'aplay', I get (=not good):
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 5513
buffer_size: 22052

When I play audio using OSMC, I get (=good):
access: RW_INTERLEAVED
format: S24_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 2400
buffer_size: 9600

Does anyone has some I idea what the solution is? I've been looking at it for days but I'm stuck.

Many thanx in advance,

Umberto

**Comment by mikebrady** [comment]
Thanks for the post. I must say it sounds a bit like a driver issue. Am I correct to assume that when you use `aplay` you get mono (it's not quite clear to me if that is so)?

What reason do you have for using the `hifiberry-dac-overlay`? Have you tried any others?

**Comment by Umberto73** [comment]
Thanks for pointing me in the right direction! I was indeed using the wrong driver! 

My solution was adding the following to /etc/modules :
		snd_soc_bcm2708
		snd_soc_bcm2708_i2s
		bcm2708_dmaengine
		snd-soc-pcm1794a
		snd_soc_rpi_dac

And changing the /boot/config.txt with:
dtoverlay=rpi-dac
