### ISSUE TITLE
Remove EOL PolarSSL and replace with supported mbed TLS

### ISSUE THREAD

**Issue by thess** [mikebrady/shairport-sync#453]
Hi Mike -

The current direction of OpenWrt/LEDE is to remove support for PolarSSL as it is EOL. As part of that process we need to update packages dependent on PolarSSL and adding support for the current mbed TLS libraries instead. I'm about to start on that work for shairport-sync and would like to know if I should submit a PR on the current version here or just supply patches to the OpenWrt package repository. Certainly, going forward it would be best if the upstream version of shairport-sync were to have support for mbed TLS.

Or, this could all be moot if you were to do it :wink:

Regards,
/ted

**Comment by mikebrady** [comment]
Hi Ted. Thanks for the mail. Let me look into it. I might come back to you for hints.

Regards
Mike

**Comment by mikebrady** [comment]
This has been done in the development version, so I'm going to close this as an issue. Please feel free to reopen if necessary.
