### ISSUE TITLE
No metadata output

### ISSUE THREAD

**Issue by zeve-zz** [mikebrady/shairport-sync#455]
```
pi@raspberrypi:/tmp $ sudo nano /usr/local/etc/shairport-sync.conf

metadata =
{
        enabled = "yes"; // et to yes to get Shairport Sync to solicit metadata from the source and to pass it on via a pipe
        include_cover_art = "yes"; // set to "yes" to get Shairport Sync to solicit cover art from the source and pass it via the pipe. You must also set "enabled" to "yes".
        pipe_name = "/tmp/shairport-sync-metadata";
        pipe_timeout = 5000; // wait for this number of milliseconds for a blocked pipe to unblock before giving up
//      socket_address = "226.0.0.1"; // if set to a host name or IP address, UDP packets containing metadata will be sent to this address. May be a multicast address. "socket-$
//      socket_port = 5555; // if socket_address is set, the port to send UDP packets to
//      socket_msglength = 65000; // the maximum packet size for any UDP metadata. This will be clipped to be between 500 or 65000. The default is 500.
};
```
Rest of my values in this file are being respected - including log_verbosity and the "on play" and "on_stop" scripts. Strangely, the name of my speakers are not appearing here, although they appear correctly every time I start the service/the pi reboots. 

Config file just says the following for name
```
//      name = "%H"
```
Assuming that is being set somewhere else on the boot sequence (I set this up a while ago so not sure). But again, everything else in the script seems to be honored.

I checked the logs and nothing is reporting an issue. /tmp/ just doesn't have a new file for shairport.

**Comment by zeve-zz** [comment]
(btw, goal here, is I want to take the song title/artist, and pump them to MagicMirror. If theres a better way for me to be doing that let me know)

**Comment by mikebrady** [comment]
Hi there. Are you sure that Shairport Sync has permission to write into `/tmp`? I guess not, but you should check.

**Comment by zeve-zz** [comment]
@mikebrady not sure how to check.. but i looked up the /tmp permissions with "ls -l" and see this:

drwxrwxrwt  14 root root  4096 Jan  6 18:10 tmp

**Comment by mikebrady** [comment]
Hmm, you'll have to check it out for yourself. But if Shairport Sync can't create the pipe, then something is wrong there. Maybe other commenters can help.

**Comment by zeve-zz** [comment]
@mikebrady would there be some type of error output if it can't write?

**Comment by soulvice** [comment]
I'm having the same issue, but i can create the pipe only if the '--metadata-pipename' argument is provided. But the 'pipe' is empty, no data no nothing

**Comment by zeve-zz** [comment]
im not seeing this post on the issue i opened?

On Friday, January 6, 2017, Soulvice <notifications@github.com> wrote:
> I'm having the same issue, but i can create the pipe only if the
'--metadata-pipename' argument is provided. But the 'pipe' is empty, no
data no nothing
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/ku20xlDjr-JHnORZ8G_VNtMD5OFjoKr_hnUiWLakJoV_A44rz3zu2OiwnE0IF3c_eCezs86EeoHmXwMRgU-9-RVw3ShYjFrVgFfqhSZ35qdeptVfgsiwmry8S2b0iHNBUJCHeuYJgb9srN9guJITB9G0CYKAHw=s0-d-e1-ft#https://github.com/notifications/beacon/AA1s2-DS8IDfc4bnbUH2uCWUbnbpijygks5rPuNggaJpZM4LdC6n.gif>

**Comment by mikebrady** [comment]
Why versions of Shairport Sync are you using please? `$ shairport-sync -V` will give you a string of information.

**Comment by zeve-zz** [comment]
pi@raspberrypi:~ $ shairport-sync -V
2.8.6-OpenSSL-Avahi-ALSA-sysconfdir:/usr/local/etc

**Comment by mikebrady** [comment]
Thanks. I'm traveling at present so responses might be a bit erratic...

**Comment by soulvice** [comment]
I spoke to soon and solved my issue, it appears your version of shairport-sync zeve-zz isn't built with "--with-metadata".

This solved my problem as well as specifying the location of my config file: "sudo shairport-sync -c /file/path/to/config.conf"

**Comment by zeve-zz** [comment]
@soulvice no luck here doing that.

**Comment by mikebrady** [comment]
@zeve-zz, you must compile Shairport Sync with metadata enabled. Otherwise it will not open the pipe or provide metadata. There's more about it in the README document.

**Comment by mikebrady** [comment]
Sorry for the delay. Can you post the string resulting from executing the command `$ shairport-sync-V ` please?

**Comment by mikebrady** [comment]
Hi there. Is it okay to close this issue?

**Comment by rogercorrea** [comment]
I have the same problem. My tmp didn't show nothing in folder of the shairport and I did compile using --with-metadata. I play music normally using my Iphone with Spotify.

**Comment by mikebrady** [comment]
Thanks for the post. The usual problems are that `shairport-sync` has not been compiled properly or that it doesn't have the write-permission necessary.
You can double-check that the version of Shairport Sync you are using is compiled with metadata enabled by entering `$ shairport-sync -V`. The reply should have the word `metadata` in it.
Next, make sure `shairport-sync` has write-permission for the directory into which you want to write the metadata. If `shairport-sync` has been installed in the normal way as a service, make sure the user `shairport-sync` has write-permission.

**Comment by rogercorrea** [comment]
The service run with the shairport-sync user, correct?
I did try config permission to shairport-sync user in the tmp folder but in the boot the config didn't save.
How I configure the tmp folder to shairport-sync?

**Comment by rogercorrea** [comment]
Please,

I reinstalled the Shairport-Sync in other Raspbian Jessie and the metadata output doesn't worked again.
My version is "3.0-OpenSSL-Ahavi-ALSA-soxr-metadata-sysconfdir:/etc".
I followed all the steps written in the README and nothing.

**Comment by rogercorrea** [comment]
The metadata output worked now that I commented the lines of the config file to pipe and art-cover. Now stayed only the "enabled" line config.

metadata =
{
	enabled = "yes"; // set this to yes to get Shairport Sync to solicit metadata from the source and to pass it on via a pipe
//	include_cover_art = "no"; // set to "yes" to get Shairport Sync to solicit cover art from the source and pass it via the pipe. You must also set "enabled" to "yes".
//	pipe_name = "/tmp/shairport-sync-metadata";
//	pipe_timeout = 5000; // wait for this number of milliseconds for a blocked pipe to unblock before giving up
//	socket_address = "226.0.0.1"; // if set to a host name or IP address, UDP packets containing metadata will be sent to this address. May be a multicast address. "socket-port" must be non-zero and "enabled" must be set to yes"
//	socket_port = 5555; // if socket_address is set, the port to send UDP packets to
//	socket_msglength = 65000; // the maximum packet size for any UDP metadata. This will be clipped to be between 500 or 65000. The default is 500.
};

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
