### ISSUE TITLE
High delay issue with TuneBlade and iTunes (JACK Audio)

### ISSUE THREAD

**Issue by Jeroen3007** [mikebrady/shairport-sync#457]
Hi Mike and others,

I've been using Shairport-Sync for quite a while now and I think it's an amazing piece of software.
Lately I have been wanted to use it on an embedded development board (Olimex A20 Micro, running on Armbian) and it installed without problems.
I Have it working without any weird sounds drops so that's great, but the latency is quite high.

I have a **10-15** seconds delay when using iTunes or TuneBlade(in normal mode: supposed to be 2s delay) when streaming to Shairport-Sync to the Olimex board which is connected to an 100Mbit switch.
However when switching TuneBlade to real time streaming mode (expected delay: 5-350 milliseconds delay) the delay is greatly reduced to about **1-3** seconds.

I'm having a hard time finding out why this 2 second increase is an 12 second increase on my system.
Since you and others have tried Shairport-Sync on several devices I was hoping you could provide me with some advice.

**Comment by Jeroen3007** [comment]
Let's see if I can provide more info to diagnose the problem (that occurs with a clean github clone)
I have used very normal compile options
`./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemv`
I've changed a few settings in the config file:
`ignore_volume_control = "yes"
alsa =
{
output_device = "pcm.jack"; // the name of the alsa output device.
disable_synchronization = "yes"; // Set to "yes" to disable synchronization.
};`

To use the JACK audio server I changed the ~/.asoundrc settings to route the alsa sound to JACK (I Believe this is called an ALSA Loopback Device)

**Comment by mikebrady** [comment]
Thanks. When synchronization is disabled, no control is attempted on the delay. What happens if you don't disable it? Also, can you direct the output to the real hardware device?

**Comment by Jeroen3007** [comment]
When writing directly to the hardware device the delay is gone, I noticed this before but couldn't understand why JACK would not throw an error if something was wrong. (i.e. the sample rate or something)
Next step: I'll have to figure out why writing to JACK via ALSA creates such an enourmous delay.

Something I noticed thanks to you: Writing to pcm.jack (the alsa loopback device) with synchronisation enabled throws the following errors
`Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 4394.`
`syncing to seqno 60290.`
`jack_client_new: deprecated`
`Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 3631.`
`syncing to seqno 60571.`
`jack_client_new: deprecated`
`Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 4498.`
`syncing to seqno 60855.`

This doesn't happen when writing to de hardware device directly

**Comment by Jeroen3007** [comment]
Apparently my loopback device is broken. When writing directly to the ALSA device "jack" (instead of my loopback "pcm.jack") these errors don't occur, however the delay isn't reduced with or without synchronisation.

**Comment by mikebrady** [comment]
Hmm, I've never really tried to do much with Jack. The thing is, it may not be reporting latency information back to Shairport Sync, and if that was the case, nothing would work reliably.

**Comment by Jeroen3007** [comment]
Hi Mike, 

I've quite busy with the problems and thought it would be nice to give you an update!
I've tried the following things:
Shairport-Sync > ALSA = No abnormal delay
Shairport-Sync > PulseAudio > ALSA = No abnormal delay
Shairport-Sync > stdout > paplay (PulseAudio) = No abnormal delay

Shairport-Sync > ALSA(JACK ALSA plugin) > JACK = About 7 seconds delay
Shairport-Sync > PulseAudio > JACK = About 7 seconds delay
Shairport-Sync > stdout > paplay (PulseAudio) > JACK = About 7 seconds delay

Finally I got the Loopback Device working! Unfortunately there still is a 4 seconds delay..
According to http://alsa.opensrc.org/Jack_and_Loopback_device_as_Alsa-to-Jack_bridge and the JACK developers this is the way to go...

Almost there!

**Comment by mikebrady** [comment]
Thanks Jeroen!

**Comment by Jeroen3007** [comment]
Alright, apparently SOXR is not the right move for my system, with Basic stuffing, Synchronization enabled and JACK via the ALSA Loopback Device I now get a satisfyingly delay of 2-3 seconds. 
Thank you for making Shairport-Sync, it really is an amazing piece of software.
