### ISSUE TITLE
shairport-sync.conf gets overwritten and cannot autostart

### ISSUE THREAD

**Issue by iimac13** [mikebrady/shairport-sync#460]
Hello Mike!
Your project is great! I've gotten it working on 'manual' mode so far.
I have a little issue where I need your help to get it to run automatically.
I have a CHIP board(the original one, with CHIPos 4.4 GUI(will move to a headless OS after this issue is solved)

To make it autostart I've tried setting it up in the rc.local right before the 'exit 0' line, and also with the systemctl, but it seems that somewhere in the rebooting the '/etc/shairport-sync.conf' file gets overwritten and a last line(line 95) gets added with a bunch of ^@^@^@^@^@^@, so the service never starts properly in automatic.
Can you take a look at this please and point me in the right direction?
Your help is greatly appreciated!

**Comment by mikebrady** [comment]
Thanks for the post. TBH, I am mystified by this phenomenon – it seems that something is writing to the file `/etc/shairport-sync.conf`. I don't know of any mechanism that might account for this. Is it possible that something is altering the file as it is closed after editing – in other words, does the file contain the ^@ characters after it's been edited but before rebooting?

**Comment by mikebrady** [comment]
Hi there. Was there any progress on this?

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
