### ISSUE TITLE
Is there gonna happen Metadata broke, when rapidly altering RTSP connection to ON and OFF several times.(Solved)

### ISSUE THREAD

**Issue by lujnan** [mikebrady/shairport-sync#462]
Hey Mike,
After I have enabled Metadata Function, I tried to rapidly connect and disconnect the RAOP several times, then the date from Metadata would broke. In this condition, is the pthread_kill gonna interrupt the thread when pthread is trying to write datas into pc_queue?
The wired thing is, When I am trying to do that, the entire process will crash.
Looking forward to hear from you. Thanx.

Best,
Lujnan

**Comment by mikebrady** [comment]
Hi Luijan. Thanks for the post, but I'm afraid I don't understand: *"I tried to rapidly connect and disconnect the ROAP several times"*. Could you explain that again please?

**Comment by lujnan** [comment]
I play the musics on my iPhone(source) and output the audio to  the shairport-sync device(target). 
So, There are two devices. One is my iPhone and another is a device that running shairport-sync. 
When I do switching on/off the connection by the iPhone OS's Airplay-Control UI.  
That actions will to cause the shairport-sync program easily crash.  Sometime switch a short times, such as 1 or 2 times,  Also will cause to crash. When I disable the metadata function, every thing is ok. I changed some codes about of metadata process, And not use the pipe or socket mode.  just access memory directly, So i think maybe sometimes the metadata broken.

**Comment by mikebrady** [comment]
Thanks – I'll try that out and see what I can find.

**Comment by mikebrady** [comment]
Hi there. I've been cleaning up code that I suspect, but can't prove, is possibly causing problems. It's now on the `development` branch. I'd be obliged if you tried it out, to see it it's any better.

**Comment by lujnan** [comment]
Okay, Thanks, I will try it.

**Comment by lujnan** [comment]
Hi, Mike. I have been merged the `development` branch,  And testing the new codes.  Up to now the program is very stable, This adjustment is very effective. I will spend more time verifying the stability of the program, So I will close this issue later.

**Comment by mikebrady** [comment]
Thanks for the update.
