### ISSUE TITLE
Shairport-sync not working with Chord MoJo (on Moode 3.1) [Solved]

### ISSUE THREAD

**Issue by franz159** [mikebrady/shairport-sync#463]
**_This is the debug command used to start shairport:_**

`/usr/local/bin/shairport-sync -vvv -a "moode31 Airplay" -S soxr -w -B /var/www/command/spspre.sh -E /var/www/command/spspost.sh --metadata-pipename=/tmp/shairport-sync-metadata --get-coverart -- -d hw:1 -c "PCM"`

**_This is the logged output: returning error on device hw:1"_**

```
Looking for the configuration file "/usr/local/etc/shairport-sync.conf".
Looking for configuration file at full path "/usr/local/etc/shairport-sync.conf"
Output device name is "hw:1".
Open Mixer
Mixer device name is "hw:1".
Mixer Control name is "PCM".
Hardware mixer has dB volume from -127.990000 to 0.000000.
Has mute ability.
The processor is running little-endian.
Version: "2.8.6-OpenSSL-Avahi-ALSA-stdout-soxr-metadata-sysconfdir:/usr/local/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "moode31 Airplay".
Audio Output name is "(null)".
on-start action is "/var/www/command/spspre.sh".
on-stop action is "/var/www/command/spspost.sh".
wait-cmd status is 1.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
playback_mode is 0 (0-stereo, 1-mono).
disable_synchronization is 0.
use_mmap_if_available is 1.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
metdata enabled is 1.
metadata pipename is "/tmp/shairport-sync-metadata".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 1.
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service 'C662EC7487D1@moode31 Airplay' group is not yet commited.
avahi: request to add "_raop._tcp" service with metadata
avahi: service 'C662EC7487D1@moode31 Airplay' group is registering.
avahi: service 'C662EC7487D1@moode31 Airplay' successfully added.
New RTSP connection from [fe80::fe:663c:46c2:8e63]:63607 to self at [fe80::9e63:296f:b8f2:1d08]:5000.
    CSeq: 0.
    X-Apple-Device-ID: 0x1040f3ba4284.
    Apple-Challenge: NobT4YhFrX9c+nZADlrsGA==.
    DACP-ID: 9B854C3CA459EE39.
    Active-Remote: 2380747064.
    User-Agent: AirPlay/211.3.
RTSP Packet received of type "OPTIONS":
  Type: "CSeq", content: "0"
  Type: "X-Apple-Device-ID", content: "0x1040f3ba4284"
  Type: "Apple-Challenge", content: "NobT4YhFrX9c+nZADlrsGA=="
  Type: "DACP-ID", content: "9B854C3CA459EE39"
  Type: "Active-Remote", content: "2380747064"
  Type: "User-Agent", content: "AirPlay/211.3"
RTSP Response:
  Type: "Apple-Response", content: "5LjR6lyc0dAc5XiqmK6MH2IRunhY5bFRiOsYVZkjbVTnuxPYKZsRBYLsmAiBeaKaKnhAdS7G1M+SdX3A4n7oCbmesAlmsDPbO278wUf1LrjDoGbEK2oc6Bpf+ws0CqT9QsZHYqUHOBQsoonz+h3BEQOHYdV+jVS23b7q5CtRnL0E56hSAbJaKuTe+E0qtlt6qxwaJqa7iN2g03tjnyjCynxeRxzyJd6FoBjZAyISfHhgPzyrYD02G6mP/iS6nonT+BQmY/LS+8yHiblxvip5aC1aZRLIgS7fwmN5I5MnGH8Sd22VX4XqjZ24F71NzalnVAAp87ev4UcWdw2qhfYwnw"
  Type: "CSeq", content: "0"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
    X-Apple-Client-Name: iPad di Franz.
    CSeq: 1.
    X-Apple-Device-ID: 0x1040f3ba4284.
    DACP-ID: 9B854C3CA459EE39.
    Active-Remote: 2380747064.
    Content-Type: application/sdp.
    Content-Length: 669.
    User-Agent: AirPlay/211.3.
RTSP Packet received of type "ANNOUNCE":
  Type: "X-Apple-Client-Name", content: "iPad di Franz"
  Type: "CSeq", content: "1"
  Type: "X-Apple-Device-ID", content: "0x1040f3ba4284"
  Type: "DACP-ID", content: "9B854C3CA459EE39"
  Type: "Active-Remote", content: "2380747064"
  Type: "Content-Type", content: "application/sdp"
  Type: "Content-Length", content: "669"
  Type: "User-Agent", content: "AirPlay/211.3"
Play connection from device named "iPad di Franz".
Play connection from user agent "AirPlay/211.3".
RTSP Response:
  Type: "CSeq", content: "1"
  Type: "Server", content: "AirTunes/105.1"
    Transport: RTP/AVP/UDP;unicast;mode=record;timing_port=51316;x-events;control_port=58703.
    CSeq: 2.
    X-Apple-Device-ID: 0x1040f3ba4284.
    DACP-ID: 9B854C3CA459EE39.
    Active-Remote: 2380747064.
    User-Agent: AirPlay/211.3.
RTSP Packet received of type "SETUP":
  Type: "Transport", content: "RTP/AVP/UDP;unicast;mode=record;timing_port=51316;x-events;control_port=58703"
  Type: "CSeq", content: "2"
  Type: "X-Apple-Device-ID", content: "0x1040f3ba4284"
  Type: "DACP-ID", content: "9B854C3CA459EE39"
  Type: "Active-Remote", content: "2380747064"
  Type: "User-Agent", content: "AirPlay/211.3"
Active-Remote string seen: "2380747064".
DACP-ID string seen: "9B854C3CA459EE39".
User-Agent is AirPlay; selecting the AirPlay latency of -1 frames.
rtp_setup: cport=58703 tport=51316.
Set up play connection from fe80::fe:663c:46c2:8e63 to self at fe80::9e63:296f:b8f2:1d08.
listening for audio, control and timing on ports 6001, 6002, 6003.
RTSP Response:
  Type: "CSeq", content: "2"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6002;timing_port=6003;server_port=6001"
  Type: "Session", content: "1"
Audio receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.Timing receiver -- Server RTP thread starting.

Timing sender thread starting.
    Range: npt=0-.
    X-Apple-Durations: b=28; c=25; au=574; an=40; sa=3133.
    CSeq: 3.
    X-Apple-Device-ID: 0x1040f3ba4284.
    DACP-ID: 9B854C3CA459EE39.
    Active-Remote: 2380747064.
    User-Agent: AirPlay/211.3.
RTSP Packet received of type "RECORD":
  Type: "Range", content: "npt=0-"
  Type: "X-Apple-Durations", content: "b=28; c=25; au=574; an=40; sa=3133"
  Type: "CSeq", content: "3"
  Type: "X-Apple-Device-ID", content: "0x1040f3ba4284"
  Type: "DACP-ID", content: "9B854C3CA459EE39"
  Type: "Active-Remote", content: "2380747064"
  Type: "User-Agent", content: "AirPlay/211.3"
RTSP Response:
  Type: "CSeq", content: "3"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Audio-Latency", content: "11025"
    CSeq: 4.
    X-Apple-Device-ID: 0x1040f3ba4284.
    DACP-ID: 9B854C3CA459EE39.
    Active-Remote: 2380747064.
    Content-Type: text/parameters.
    Content-Length: 19.
    User-Agent: AirPlay/211.3.
RTSP Packet received of type "SET_PARAMETER":
  Type: "CSeq", content: "4"
  Type: "X-Apple-Device-ID", content: "0x1040f3ba4284"
  Type: "DACP-ID", content: "9B854C3CA459EE39"
  Type: "Active-Remote", content: "2380747064"
  Type: "Content-Type", content: "text/parameters"
  Type: "Content-Length", content: "19"
  Type: "User-Agent", content: "AirPlay/211.3"
volume: -3.153408

Setting volume db to -672.621937.
RTSP Response:
  Type: "CSeq", content: "4"
  Type: "Server", content: "AirTunes/105.1"
    RTP-Info: seq=2060;rtptime=3839410863.
    CSeq: 5.
    X-Apple-Device-ID: 0x1040f3ba4284.
    DACP-ID: 9B854C3CA459EE39.
    Active-Remote: 2380747064.
    User-Agent: AirPlay/211.3.
RTSP Packet received of type "FLUSH":
  Type: "RTP-Info", content: "seq=2060;rtptime=3839410863"
  Type: "CSeq", content: "5"
  Type: "X-Apple-Device-ID", content: "0x1040f3ba4284"
  Type: "DACP-ID", content: "9B854C3CA459EE39"
  Type: "Active-Remote", content: "2380747064"
  Type: "User-Agent", content: "AirPlay/211.3"
Flush requested up to 3839410863. It seems as if 0 is special.
RTSP Response:
  Type: "CSeq", content: "5"
  Type: "Server", content: "AirTunes/105.1"
syncing to seqno 2060.
Output written using MMAP
audio_alsa: Sample format not available for device "hw:1": Invalid argument
avahi: avahi_unregister.
Request to shut down all rtsp conversation threads
asking playing threads to stop
RTSP shutdown requested.
Closing down RTSP conversation thread...
```

**Device hw:1 is a ChordMojo as shown in aplay -l output**
```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Mojo [Mojo], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

**Comment by franz159** [comment]
Chord MoJo is connected on raspberry USB port

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, it looks like the Chord MoJo does not offer CD format, i.e. 44,100 samples per second, 16 bit signed integer little-endian interleaved  stereo, which Shairport Sync requires. Can you check that? I had a quick look at the website and it doesn't seem to say, one way or the other.

**Comment by franz159** [comment]
It seems rather odd, in Moode I have been personally playing all sort of files, from 44.1KHz to 192KHz PCM plus  DSD64 and DSD128.
In general terms, the Mojo is supposed to play up to 768KHz PCM and DSD256 in DoP format....

**Comment by mikebrady** [comment]
It is odd. The line:
```
audio_alsa: Sample format not available for device "hw:1": Invalid argument
```
is where it states that it can't set the MoJo to receive the required format. Can you be certain that Moode isn't transcoding your files before playing them?

It is frustrating not to be able to see, somewhere, that the MoJo will receive CD-quality material over its USB interface.

**Comment by franz159** [comment]
In terms of sample frequency I'm pretty sure we are good, since I streamed many times 16/44 files, typycally using Moode.

What I'm not sure is the bit number, will MoJo accept a 16 bit input stream?

In fact, examining for example Audio Info in Moode, even when playing a source file decoded to 16 bit, 44.1 kHz Stereo , I see that the output stream format sent to the dac by MDP  is always 32 bit, 44.1 kHz, Stereo.

Similarly, on my Mac Audio Midi Setup, I see the MoJo as 2 channels, 32 bit

Apologies for the maybe stupid question, but could this be the issue? Airplay streaming at 16 bit and MoJo supporting only a 32 bit stream?

**Comment by mikebrady** [comment]
Thanks for this – I think you might have discovered the explanation. The current version of Shairport Sync and all previous versions of Shairport Sync (and other "shairports") have required on 44,100 samples per second, 16-bit, interleaved stereo. The present `development` version of Shairport Sync relaxes this requirement somewhat and can output 24 or 32 bit streams at 44,100, 88,200 or 176,400 samples per second, interleaved stereo, so it should solve your problem. However, it's still in development, and while it is quite robust, the documentation isn't up to date yet. There is some documentation in the configuration file sample, so if you were feeling adventurous, you could try it out... Sorry I can't be more positive about it right now.

**Comment by franz159** [comment]
I would be happy to try.. what should I loose? :)
May I ask you some basic direction to download/compile for raspberry pi3 os should I ask Tim Curtis....

**Comment by mikebrady** [comment]
Well, it is probably worth talking to Tim about it. The instructions for compiling it are in the README, but they presume you are using a standard Raspbian distribution, and I think the Moode image is different. Apart from that, you have nothing to lose, indeed :)

**Comment by franz159** [comment]
I found the readme and I was studying it... :) thanks

**Comment by franz159** [comment]
I recompiled and installed shairport-sync form the development branch.... (I simply followed all instructions on README for Jesse, and it worked, since Moode31 is based on Jessie)

However it still fails with the following error:
`Setting volume db to -672.621937.
RTSP Response:
  Type: "CSeq", content: "4"
  Type: "Server", content: "AirTunes/105.1"
syncing to seqno 24948.
Hammerton Decoder used on encrypted audio.
Output sample ratio is 1
Output written using MMAP
audio_alsa: Sample format 2 not available for device "hw:1": Invalid argument
avahi: avahi_unregister.
Request to shut down all rtsp conversation threads
asking playing threads to stop
RTSP shutdown requested.
Closing down RTSP conversation thread...      `


I'm launching shairport-sync like this
`/usr/local/bin/shairport-sync -vvv -a "moode31 Airplay" -S soxr -w -B /var/www/command/spspre.sh -E /var/www/command/spspost.sh --metadata-pipename=/tmp/shairport-sync-metadata --get-coverart -- -d hw:1 -c "PCM"    `


Should I use some additional parameter when launching the shairport-sync process?

**Comment by mikebrady** [comment]
Good stuff. You will indeed have to put a parameter in the configuration file. When you did the `make install` step, a sample configuration file will have been installed at `/etc/shairport-sync.conf.sample`. Copy it to `/etc/shairport-sync.conf`. (If that file already exists, rename or delete it.)

Open the file and find the line that reads:
```
//  output_format = "S16"; // can be "U8", "S8", "S16", "S24", "S24_3LE", "S24_3BE" or "S32", but the device must have the capability. Except where stated using (*LE or *BE), endianness matches that of the processor.
```
and change it to read as follows:
```
  output_format = "S32"; // can be "U8", "S8", "S16", "S24", "S24_3LE", "S24_3BE" or "S32", but the device must have the capability. Except where stated using (*LE or *BE), endianness matches that of the processor.
```
Notice that (1) the `//` characters are gone from the start of the line so that it's not treated as a comment, and (2) we are specifying S32 (signed 32-bit) output. Endianness will be determined by the endianness of the processor which will be little-endian in Raspian. The format is interleaved stereo always.

**Comment by franz159** [comment]
In the previous conf file there was no output_format entry.
I found the newly created shairport-sync.conf.sample file.
In which "section" of the file should I add the output_format = "S32" entry?

**Comment by mikebrady** [comment]
AFAIK, the configuration file is not used by Tim.

You should not use the previous  configuration file – the configurations are incompatible. Rename it if you want to keep it so that you can revert to it in future.

You'll find the `output_format` entry in the new sample file in the `alsa` section.

**Comment by franz159** [comment]
As I said, In the newwly created conf file, the output_format line is not present.
However, I added it at the begining of the alsa section as follows....

alsa =
{
 **output_format = "S32";** // can be "U8", "S8", "S16", "S24", "S24_3LE", "S24_3BE" or "S32", but the device must have the capability. Except where stated using (*LE or *BE), endianness matches that of the processor.
//  output_device = "default"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
//  mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
//  mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
//  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
//  audio_backend_buffer_desired_length = 6615; // If set too small, buffer underflow occurs on low-powered machines. Too long and the response times with software mixer become annoying.
};


...... and I'm streaming!

Thanks

**Comment by mikebrady** [comment]
Super! Not sure why the updated sample file wasn't installed. Well done!

**Comment by franz159** [comment]
Not sure either...
I launched configure before make as follows

`  ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd`

The "strange" thing I NOTICED is that the .conf file was created in "/usr/local/etc/shairport-sync.conf" and not in "/etc".
I simply moved it to /etc and manually added the missing output_format line in the alsa section, as per your indication.
Of course I also moved the new shairport-sync executable under /usr/local/bin
I tested both launching it manually and then "enabling" it though Moode interface and I'm all set.

Thanks for all your help!

**Comment by moodeaudio** [comment]
Hi Mike,

Cat output format be specified on cmd line or is it only a config file param?

-TIm

**Comment by mikebrady** [comment]
Hi Tim. It's only in the config file, I'm afraid. The command line stuff has gotten out of hand. Is it a problem?

**Comment by moodeaudio** [comment]
Shouldn't be. I can just maintain that param in the config file and leave my cmd line launch string as-is.

**Comment by mikebrady** [comment]
Version 3 is moving along towards release in the next few weeks, so I'm going to close this as solved. Feel free to reopen if necessary.

**Comment by franz159** [comment]
I agree!
And thanks again
Franz

Inviato da iPhone
