### ISSUE TITLE
Metadata mixed up [Solved]

### ISSUE THREAD

**Issue by fosple** [mikebrady/shairport-sync#465]
Hey,

when streaming music from iTunes to shairport-sync the metadata info seems to be scrambled (XML tags are closed before they were opened, etc.). It in fact looks like lines are interchanged or lines are missing. Therefore the shairport-sync-metadata-reader can't parse the resulting XML anymore. This happens when I'm streaming from an iOS device or from iTunes (Mac)

Source:
- iTunes: 12.5.4.24 on Mac OS Sierra
- iOS 10.0.2

Sink:
- Raspberry Pi 3

Command to start shairport-sync & listen to pipe

```
shairport-sync -a "Radio" --metadata-pipename /tmp/shairport-sync-metadata
```

Example:

```
<data encoding="base64">
MjM5OTU1ODMzMA==</data></item>
</data></item>
AIA=</data><item><type>636f7265</type><code>6173636d</code><length>0</length></item>
<item><type>636f7265</type><code>6173666d</code><length>3</length></item>
</item>
</data></item>
<item><type>636f7265</type><code>61654856</code><length>1</length>
<data encoding="base64">
AA==</data></item>
</item>
<item><type>636f7265</type><code>61654744</code><length>4</length>
<data encoding="base64">
AAAGwA==</data></item>
<item><type>636f7265</type><code>61654755</code><length>8</length>
<data encoding="base64">
AAAAAAyIzIA=</data></item>
<item><type>636f7265</type><code>61654752</code><length>8</length>
<data encoding="base64">
AAAAAASMJto=</data><item><type>636f7265</type><code>61654d6b</code><length>4</length>
<data encoding="base64">
<item><type>636f7265</type><code>61736b70</code><length>4</length>
<data encoding="base64">
AAAAAA==</data></item>
<item><type>636f7265</type><code>61736163</code><length>2</length>
<data encoding="base64">
```

**Comment by mikebrady** [comment]
Hi there. Is it possible that you're reading the pipe from two or more places? This is the usual cause of this problem...

**Comment by fosple** [comment]
@mikebrady Thanks! I just checked that and in fact that was the cause of the problem. I did my own implementation of the shairport-sync-metadata-reader and wanted to check it against the original implementation, so I was reading the pipe from two places. Thanks a lot for the super fast reply :)

**Comment by mikebrady** [comment]
Problem solved!
