### ISSUE TITLE
Network Adaptor Binding

### ISSUE THREAD

**Issue by noelhibbard** [mikebrady/shairport-sync#468]
Is there an option to instruct shairport-sync to bind to a specific adapter? If not, that would be a great feature.

**Comment by mikebrady** [comment]
Hi – you mean a specific network interface? There isn't now, but hopefully there will be soon, following a suggestion in #444.

**Comment by noelhibbard** [comment]
Yep, exactly that. Thanks!

**Comment by mikebrady** [comment]
Fixed in version 3, I think.

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
