### ISSUE TITLE
Shairport-Sync won't connect?

### ISSUE THREAD

**Issue by hdsjulian** [mikebrady/shairport-sync#470]
I have no idea whether correlation or causality but since I updated my macbook yesterday (now Mac OS 10.12.3) I can't connect to my raspi with shairport sync anymore. 
I can see the device in iTunes but connection times out. Rebooted raspi and mac several times. 
Now i'm wondering if there is a way to debug this? Or should I just try and reinstall the whole thing? Or do others have the same problem?
Thanks for advice

**Comment by mikebrady** [comment]
That's odd. I'm running 10.12.3 and iTunes 12.5.5.5 and no problems. I'd suspect a firewall setting somewhere – the Mac or you or router. Any possibility there?

**Comment by hdsjulian** [comment]
Nope, no "personal firewall" thing on the mac and the router should be fine, too. Will investigate by reinstalling on second micro-sd and report if problem still persists. 
The actual question here is though: is there a logfile of some sorts?

**Comment by mikebrady** [comment]
Okay. Yes, you can turn on logging by setting log verbosity to 2 in the configuration file at `/etc/shairport-sync.conf`. Also, two apps – `Bonjour Browser` on a Mac and `Discovery` on iOS – will allow you to see some stuff at the Mac/iOS end and `avahi-broswer` on the rPi end might help you somewhat on the service discovery / ZeroConf / Bonjour side of things, though they seem okay.

**Comment by mikebrady** [comment]
Did you have any further luck with this?

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
