### ISSUE TITLE
Add signal to disconnect current RTSP clients, if any

### ISSUE THREAD

**Issue by mcnoche** [mikebrady/shairport-sync#472]
I have a need to be able to disconnect any connected clients via an external mechanism but I don't want to stop/start the shairport-sync process mostly because of the avahi implications but there are others as well.

I would like to use a signal but I see that USR1 and USR2 are already spoken for so I was thinking of using WINCH to effect my desired outcome.  What are your thoughts?  Is there another way that you would suggest?

**Comment by mikebrady** [comment]
Thanks for the post,. I'm not sure what you have in mind. Could you give me an example please?

**Comment by mcnoche** [comment]
Something along this function in shairport.c for dropping all of the RTSP clients (1).

static void sig_shutdown_rtsp_client(int foo, siginfo_t *bar, void *baz) {
    debug(1, "shutting down any RTSP clients");
    rtsp_request_shutdown_stream();
 }
 
My particular use-case is to be able to stop any active streaming from the server side without a restart of the process.

**Comment by mikebrady** [comment]
There is a protocol for sending commands to any AirPlay client, such as iTunes, to ask it to stop sending audio. To use it, you need to know the address of the client and the port number to use. Shairport Sync knows the address of the client and puts it in the metadata stream, but it does not the port number, which is available in a ZeroConf packet. So, you could write an app that takes the metadata to get the address of the client and then use, say, an avahi call to pick up the port number. Then it could send commands to pause or stop the client. Is that the kind of thing you have in mind?

**Comment by mcnoche** [comment]
Yes, I have done something similar with varying success. Sometimes the DACP works and sometimes it doesn't.  Sometimes I don't see the metadata tag as it is not presented or it does not exist from the player (this seems to vary between itunes clients on different OSes).  This is just a more full-proof way of slapping down any connected clients from the shairport side.

**Comment by mikebrady** [comment]
Shairport Sync has a (deprecated) facility to disconnect completely from the output device, leaving it free for other uses, while continuing to accept the audio stream. It really will be going away, hopefully when something better comes along. Sorry to be so vague.

**Comment by mcnoche** [comment]
I am happy to code up the SIGWINCH solution I have and then submit a pull request.  I have had this for a while and I would like to get this into the upstream so I don't have to keep worrying about merge issues.

**Comment by mikebrady** [comment]
It might be best to wait a while – I have a slightly different plan, which is to use a D-bus interface.

**Comment by mcnoche** [comment]
Ah, I like that approach a lot…what is the status on this?  Are you looking for help?

Mike

**Comment by mikebrady** [comment]
Thanks. Yeah, I want to do this is discrete stages. I don't yet have a good understanding of D-Bus, though the ideas are pretty straightforward.

Completely separately from Shairport Sync, IMHO the first thing is to have a good working program acting as a server and another working as a client.

I want to use GDbus, as it seems mainstream and well maintained. The documentation is awful, however. So, I've been trying to follow the really pretty good tutorial here: https://aleksander.es/data/GNOMEASIA2014%20-%20Introduction%20to%20DBus.pdf. I've tried to build an autotools-based project around the server written in C, and have succeeded. (It's on another computer, however, and I need to find it...)

Unfortunately, the client is not given in C and I'm struggling to reconstruct it. I need to find my autotools project with the server in it and put it up on GitHub, and then if you or others could have a look at it, maybe we could build a client in C. (BTW, I'm sure it would be useful to other people trying to use GDbus.)

**Comment by mikebrady** [comment]
[Update] I put up the project so far, at [gdbus-tutorial](https://github.com/mikebrady/gdbus-tutorial).

**Comment by mcnoche** [comment]
Got it...I will be taking a look this weekend at this.

**Comment by ccutrer** [comment]
@mikebrady: are you planning on allowing multiple commands to be piped back to the client (i.e. pause/play, previous/next track, volume change notifications?). That'd be great!

**Comment by mikebrady** [comment]
I am planning to build a D-Bus interface for Shairport Sync. In fact, I have a basic foundation partly built and I think it's reasonably good, based on GDbus.

It would finally allow commands and status information flow to and from Shairport Sync, so hopefully, it would be the basis for some commands and notifications, including what you have done. I hesitate to post it because it is pretty raw, and I'd really like to get a full release of the other stuff out first, (like working PulseAudio and `sndio` backends). 

In the circumstances, I might ask you to defer your most recent pull, pending the arrival of the D-Bus interface, which will be much more general and, all round, much cooler. I'm guessing the first pull gives you sufficient functionality for the present?

**Comment by ccutrer** [comment]
Yup, I'm good for now. And I totally agree that a new release version needs cut. I've been running the same version for several years, and I was impressed with all the progress that has been made in the meantime.

**Comment by mikebrady** [comment]
Okay. I'm just going to drop decline the pull request now, thanks.

**Comment by mikebrady** [comment]
There is a D-Bus interface in place now, and lots of other changes that might resolve these issues. So, closing this issue – please open a new one if necessary.
