### ISSUE TITLE
Setup on Offline Network

### ISSUE THREAD

**Issue by BaReinhard** [mikebrady/shairport-sync#473]
Is it possible to setup shairport-sync with the raspberry pi without having the raspberry pi connected to a network? Would it be possible to setup the raspberry pi as an access point with no internet but have other devices push music over that network to the pi so it may play.

For example, setting up a raspberry pi in the car so that you can connect to the raspberry pi with your iphone and stream music to is which then outputs to your car stereo. 

Would this be possible with how shairport-sync currently works?

**Comment by mikebrady** [comment]
Just for the record, yes, it is possible. But it will only work well for iOS, as it can simultaneously use the AP for accessing Shairport Sync and the cellular network for accessing the Internet.

**Comment by BaReinhard** [comment]
You sir have made me feel like a kid in a candy store, as that is exactly what I wanted. I was under the assumption that I wouldn't be able to receive emails, but given that iOS will allow for cell data to be used , this solves my only issue with that setup. Do you by chance know of s write up or any information as to how I would setup such a network?

**Comment by mikebrady** [comment]
I've done it for two cars, but I haven't written it up properly. Give me a week or so and I'll do it. I remember using hostapd and isc-dhcp-server (not dnsmasq). It works really reliably, and the audio quality is miles better than Bluetooth, IMHO.

**Comment by BaReinhard** [comment]
That would be awesome! I may be able to piece it together if I have enough time, but I've got a ton of web dev stuff I need to catch up on. Who knows if I'll ever get to it. If you do get a chance to do the writeup I would be forever grateful.

**Comment by BaReinhard** [comment]
as of right now I have hostapd setup and setup dhcpd to where I can see the wifi access point on iOS, but I just can't get it to connect.

**Comment by mikebrady** [comment]
Working from memory, the trick is to ensure hostapd comes up and stabilizes before shairport sync starts. To accomplish this, I disabled auto start for both hostapd and shairport sync and put them into  `rc.local` instead. So, in `rc.local`, I started `hostapd, waited for three seconds and then started `shairport-sync`. I'll check when I get a chance.

**Comment by mikebrady** [comment]
Also, make sure power management is disabled on WiFi.

**Comment by othiman** [comment]
And don't forget that the WiFi sign on iPhone is only shown, when this WiFi also has internet connection. So check in setting if the iPhone got an DHCP IP address.

**Comment by BaReinhard** [comment]
I had installed hostapd first, then dhcp server, then shairport-sync. The result was that on boot they both booted in proper order. This could be a fluke so I may choose your route. @othiman thank you for that bit of information I found that out the hard way just by checking after I thought it should be connected by now and it worked! I was unable to test playback just yet as I did it from my phone in bed when I couldn't sleep. That being said I'll check it again later today. I got it working on a pi zero with a forked version of hostapd using a tp link USB dongle. I'll do a brief write up when I have the time later today. When I implement it in my car I'll be using a hifiberry for the pi zero so that will need some testing of its own, but overall it was easier than expected. Only took a few hours of research, but once I understood what hostapds role was and then dhcps role was it was pretty straight forward with a few tweaks from existing tutorials. It also requires the use of the rtl871xdrv driver. Once again I'd like to say thank you for the push in the right direction and the information about it being able to work. Without it I wouldn't be where I am today.

**Comment by BaReinhard** [comment]
Alright here is a brief writeup with what will need to be done: 
First setup your interfaces file:

```
sudo nano /etc/network/interfaces
```
Within the file setup a static ip and comment out the existing iface lines

```
auto lo
iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan0

iface wlan0 inet static
    address 10.0.0.1
    netmask 255.255.255.0
```
```
sudo apt-get update
sudo apt-get autoremove hostapd
sudo wget https://github.com/jenssegers/RTL8188-hostapd/archive/v2.0.tar.gz
sudo tar -zxvf v2.0.tar.gz
cd RTL8188-hostapd-2.0/hostapd
sudo make
sudo make install
sudo nano ~/hostapd-test.conf
```
add the following lines:

```
#change wlan0 to your wireless device
interface=wlan0
driver=rtl871xdrv
ssid=test
channel=1
```

Then test to ensure hostapd works:

```
sudo hostapd ~/hostapd-test.conf
```

Now that everything is working create the actual hostapd conf file:

```
sudo nano /etc/hostapd/hostapd.conf
```

```
interface=wlan0
driver=rtl871xdrv
ssid=BaReinhards_G8_Wifi
hw_mode=g
channel=6
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=3
wpa_passphrase=4doorgto
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
```
Then change default for hostapd and add the daemon config file path after DAEMON_CONF=""

```
sudo nano /etc/default/hostapd
DAEMON_CONF="/etc/hostapd/hostapd.conf"

sudo nano /etc/init.d/hostapd
DAEMON_CONF="/etc/hostapd/hostapd.conf"
```
Now we need to setup the dhcp server

```
sudo apt-get install isc-dhcp-server
sudo nano /etc/dhcp/dhcpd.conf
```
Add the following lines into your file:

```
ddns-update-style none;
ignore client-updates;
authoritative;
option local-wpad code 252 = text;
 
subnet
10.0.0.0 netmask 255.255.255.0 {
# --- default gateway
option routers
10.0.0.1;
# --- Netmask
option subnet-mask
255.255.255.0;
# --- Broadcast Address
option broadcast-address
10.0.0.255;
# --- Domain name servers, tells the clients which DNS servers to use.
option domain-name-servers
10.0.0.1, 8.8.8.8, 8.8.4.4;
option time-offset
0;
range 10.0.0.3 10.0.0.13;
default-lease-time 1209600;
max-lease-time 1814400;
}
```

I believe that is it, I may have missed something, but it's hard to tell without my Pi in front of me.

**Comment by mikebrady** [comment]
So, just for the absence of doubt, can I ask if you definitely got it working?

**Comment by BaReinhard** [comment]
Definitively got it working on both the raspberry pi zero using an external wifi adapter and again using a raspberry pi 3 with its built in wifi.
