### ISSUE TITLE
What player your used to show Shairport metadata?

### ISSUE THREAD

**Issue by rogercorrea** [mikebrady/shairport-sync#475]
Please,

My shairport work fine! Thanks for its fantastic solution!
But I need show the metadata of the musics in execution. What music player I can use?
I'm using in my multimedia car with a display 7" and he work in background only, without nothing indicator.

Thanks for help!

**Comment by roblan** [comment]
None :) I've write my own shairport-sync metadata 'visualizer' using node (to read metadata) + socket.io + chromium.

But (as always) it depends - on what platform?
But you could use eg. http://moodeaudio.org I suppose. It has built-in shairport-sync support as I can remember.

**Comment by rogercorrea** [comment]
Do you can share your code?

**Comment by rogercorrea** [comment]
I'm use in Raspbian Jessie.

**Comment by rogercorrea** [comment]
@roblan I did can read the metadata using Python. Now I go create the web interface using Flask and HTML5 for show the music in my CarPC.

The code:
`#!/usr/bin/python
import subprocess
## command to run - tcp only ##
cmd = "shairport-sync-metadata-reader < /tmp/shairport-sync-metadata"## run it ##
p = subprocess.Popen(cmd, shell=True, stderr=subprocess.PIPE)## But do not wait till netstat finish, start displaying output immediately ##
while True:
    out = p.stderr.read(1)
    if out == '' and p.poll() != None:
        break
    if out != '':
        sys.stdout.write(out)
        sys.stdout.flush()`

**Comment by rogercorrea** [comment]
Please, someone can help me?

**Comment by roblan** [comment]
@rogercorrea You can use node + socket.io + https://github.com/roblan/shairport-sync-reader if you are using HTML5

**Comment by rogercorrea** [comment]
Thanks, @roblan .
I used Python and work but not is always that music is listed in the socket.
Can occur of the I change the music in my phone and the music not show in the sync-reader.

That's correct? Do it occur with you also?

Thanks for help.

**Comment by roblan** [comment]
When album artwork is enabled then metadata stream seems to be unstable sometimes.
But without artwork everything works fine.

**Comment by NickSutton** [comment]
@rogercorrea 

`#!/usr/bin/python3
import os
import time
import subprocess
import sys

cmd = "shairport-sync-metadata-reader < /tmp/shairport-sync-metadata"
proc = subprocess.Popen(cmd,stdout=subprocess.PIPE,shell=True)

while True:
  line = proc.stdout.readline().decode()

  # full debug of pipe output
  # print(line)
  if line != '':
    wordKeys = ["Artist", "Title", "Album", "pbeg", "pend"]
    lineNow = line.rstrip()
    lineNow = lineNow.replace('"', '').strip()
    lineNow = lineNow.replace('.', '').strip()
    head, sep, tail = lineNow.partition(': ')
    for key in wordKeys:
        if key in lineNow:
            if key == "pbeg": print ("Playing music", flush=True)  
            elif key == "pend": print ("Stopping music", flush=True) 
            elif key != ("pbeg", "pend"): print (head + " = " + tail.replace(':', '').strip(), flush=True)
    


`

**Comment by idubnori** [comment]
Hi!

I'm developing a metadata parser which provides track information.
Also, it contains [the web based example app](https://github.com/idubnori/shairport-sync-trackinfo-reader#web-viewer). 
If you use Raspberry Pi 2 / 3,  there are available easy instration steps.
Hope this helps.

https://github.com/idubnori/shairport-sync-trackinfo-reader

Grateful for shairport-sync and Mike!
