### ISSUE TITLE
How I can reinstall Shairport?

### ISSUE THREAD

**Issue by rogercorrea** [mikebrady/shairport-sync#477]
Please,

My Shairport doesn't work fine with the metadata log.
How I can reinstall him?

**Comment by roblan** [comment]
It depends - how did You install it?
But usually - just as You have installed it.

**Comment by rogercorrea** [comment]
@robian
I installed using git clone and sudo make.

**Comment by roblan** [comment]
Quoting newest README:

> The following procedures will install the shairport-sync application into your system. Before continuing, you should check to see if shairport-sync is already installed – you can use the command $ which shairport-sync to find where it is located, if installed. If it is installed you should delete it – you may need superuser privileges. After deleting, check again in case further copies are installed elsewhere. (If the existing installation of shairport-sync is where the new copy will be installed into, it will be overwritten; sometimes, however, the installation is to another location, so it is safer, initially, to delete previous versions manually.)

**Comment by rogercorrea** [comment]
@roblan Thanks for it! My Shairport now work!
But I have a problem for implement a code to use the metadatas. Do you can help me in another issue?
https://github.com/mikebrady/shairport-sync/issues/475

Thanks!
