### ISSUE TITLE
Alsamixer settings reset when starting playing iTunes

### ISSUE THREAD

**Issue by charleypaulus** [mikebrady/shairport-sync#478]
Hi Mike,

I'm facing the following issue.

- I connect to my RPi via ssh.
- I first open Alsamixer with command `alsamixer`. The graphical interface appears (AlsaMixer v1.0.28; card: snd_rpi_hifiberry_dacplus).
- I set "Digital" gain to dB gain: -6.00

- From my Macbook, when I hit play in iTunes, AlsaMixer Digital setting is reset (the graphical interface shows dB gain: 0.00).

The problem also occurs sometimes after playing has started.

_I already tried to store Alsa settings using `sudo alsactl store`, but they are still reset when starting playing with iTunes._

Would you know how to solve this? Thank you.

**Comment by mikebrady** [comment]
Hi Charley. I'm not sure what the problem is, TBH. What are your active (non-default) Shairport Sync settings?

**Comment by charleypaulus** [comment]
Hi Mike,

In the original /etc/shairport-sync.conf, I added the following in alsa group:
`output_device = "hw:0";`
`mixer_control_name = "Digital";`

**Comment by mikebrady** [comment]
Thanks. So, that means that the Digital setting should be under the control of iTunes. If you turn the iTunes volume down, the Digital setting should similarly do down. Does that happen?

**Comment by charleypaulus** [comment]
Hi Mike,

Yes, it happens as you described.
I understand now that this is actually the normal behavior. I should just make sure that iTunes volume is lower than 100%, and shairport-sync will just mimic this.

Thanks!

**Comment by mikebrady** [comment]
Great. BTW, in Shairport Sync 3, coming out soon, you'll be able to limit the highest mixer setting to be used, which might be useful to you.

**Comment by charleypaulus** [comment]
Great! Thanks.
I'll close this issue.
