### ISSUE TITLE
distortion in Audio 

### ISSUE THREAD

**Issue by MP1993** [mikebrady/shairport-sync#479]
I use a LinkIt smart 7688 (OpenWrt) with shairport-sync 2.1.15-1. I connect the modul with my smartphone(app:AllConnect). If i adjust the volume at the smartphone to a higher Volume, the distortion become less, but it is still there.

install:
`opkg install shairport-sync`

**Comment by mikebrady** [comment]
Thanks for the report. Can you describe the distortion? Does it happen with every track?

**Comment by MP1993** [comment]
It is not easy to discripe. I have record the sound [http://vocaroo.com/i/s1IDyBlP5yhu](url). I adjust the volume at the middle of the track.

It happened with every track.

**Comment by mikebrady** [comment]
Hmm – I can't really hear anything, not the music, not the noise, almost nothing at all...

**Comment by MP1993** [comment]
Now i have record this Version with speaker and computer microphone, it should be louder.
http://vocaroo.com/i/s0JasCmzI7dt
I adjust the volume at 0:11.

**Comment by othiman** [comment]
Sounds like a sample rate problem. What sound card are you using? Does it support 44.1 kHz?

**Comment by mikebrady** [comment]
I can hear it now, and it really does sound terrible. Can you try using an Apple device with it, to see where the problem might lie?

**Comment by MP1993** [comment]
I have no apple device, but i tried many differents android apps. It is with every app the same noise. I use the I2S output of the MT7688. The DAC  chip is a WM8960.
Supporting sample rates of the WM8960: 8, 11.025, 12, 16, 22.05, 24, 32, 44.1, 48

**Comment by mikebrady** [comment]
Perhaps you could borrow an Apple device and use it as a reference. My experience of Android implementations of AirPlay is that they are generally pretty poor.
