### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by jonas7654** [mikebrady/shairport-sync#481]
Hello,

I had problems with latency in Volumio2. When i pressed play on my Mac there was a 1-2 sec delay till i could hear the audio trough my Speakers.
I managed to fix that by adding this in the /volumio/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl file:

latencies =
{
itunes=10000;
airplay=10000;
forkedDaapd=10000;
default=10000;
};

After changing this Video playback, e.g. from Youtube, is not in sync with the audio. The Audio source is always 1-2 seconds ahead.

Furthermore when i fast forward a youtube video for instance from 1:00 to 1:15 my computer loses the connection with the shairplay server.

**Comment by mikebrady** [comment]
Hi Jonas. Thanks for the post.

The two-second delay is deliberate, and is set by negotiating between the Mac and the AirPlay device – Shairport Sync in this case. 

When a [recent] YouTube video is played in Safari (and Chrome, AFAIK) and an AirPlay output device is detected, the video is delayed by two seconds to match the audio. Similarly if you play a video through Quicktime or in iTunes. VLC has a setting to allow you to sync video and audio.

The settings you are applying (10,000 frames at 44,100 frames per second) have the effect of reducing the delay to about a quarter of a second, but the Mac doesn't know this and continues to delay the video by two seconds, making it seem that the audio is nearly two seconds ahead.

Another effect of the settings is to almost completely eliminate the buffer that gives Shairport Sync the ability to deal with network problems or load variations, possibly accounting for the connection losses you experienced.

I hope this helps.

**Comment by jonas7654** [comment]
Hi Mike,

Thanks for the quick response.
I totally understand it now. I reseted the config, the 2 second delay is not a big deal for me.

Another issue i have faced is that Soundcloud doesn't work.
When i start a track, the track loops itself at the beginning or my Computer loses the connection to Shairport-Sync. 
Is there anyway to fix that?

Thanks for your help!

**Comment by mikebrady** [comment]
Great – let me check the Soundcloud issue. AFAIR, it was working for me, but I'll check.

**Comment by jonas7654** [comment]
I forgot to mention that the fast forward disconnect happened due to my threshold setting. I set it to high because of dropouts at 10000 frames as you mentioned it before.

Thanks for checking this out.

**Comment by mikebrady** [comment]
Do you mean SoundCloud in a browser like Safari?

**Comment by jonas7654** [comment]
Yes, latest macos sierra with the latest safari browser.

**Comment by mikebrady** [comment]
Just checking this out on the SoundCloud stuff on a newspaper, not having any luck with breaking it. Have you a specific site that could be tried?

**Comment by jonas7654** [comment]
No, Soundcloud is the only Website where i experienced that kind of issue.
I performed a clean install, but it still occurs. Either the audio is looping at the beginning or my connection to Shairplay ends.

**Comment by jonas7654** [comment]
Okay i tried it with Google Chrome and it seems to be working flawless so far.
I will check it out further.

**Comment by mikebrady** [comment]
Thanks for this. I'd be interested in your results.

**Comment by jonas7654** [comment]
So what i discovered is that i can play a Soundcloud track in Chrome without any problems so far.

I wonder why it doesn't work with Safari.

**Comment by mikebrady** [comment]
Can you recommend a web page to try?

**Comment by jonas7654** [comment]
No, i am sorry. This issue only occurs on Soundcloud.

**Comment by nahtnam** [comment]
In response to this: https://github.com/mikebrady/shairport-sync/issues/481#issuecomment-282284639

Quite interesting. Would like to point out that both Spotify and Chrome do not account for this and there is a huge delay. Doesnt really matter for spotify, but youtube on chrome is unusable.

In safari, it shows a black screen for about 2 seconds then plays the video at the same time as the audio. However, if you press pause, the audio keeps going for about two seconds while the video remains still. Then when you press play again, the video fast forwards (no audio) and then when the video is caught up the audio starts playing.

**Comment by drewbitt** [comment]
I have about a two second delay with YouTube Safari through outputting all device audio on the Mac to shairport. Clicking on the YouTube Video and pressing the AirPlay button only comes up with the Apple TV, not shairport, although the Mac sees shairport for all audio. Is this normal? I assume YouTube only auto delays if it's through Airlplay on the YouTube player interface.

**Comment by mikebrady** [comment]
Thanks for the post. I'm pretty sure the AirPlay button only shows AirPlay video devices, so not Shairport Sync. The two second delay is part of the AirPlay standard, and Safari usually delays the video so that is in sync with the delayed audio. I hope this helps.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
