### ISSUE TITLE
Shairport Sync Volumio 2 output to Snapcast Server

### ISSUE THREAD

**Issue by atze09** [mikebrady/shairport-sync#485]
Hello Mike and hello guys,
It's me again with a problem.
My system is a RPi3 with Volumio 2.041 and shairport-sync as default.
I now installed an snapcastclient and snapcast server.
I would like to get the shairport-sync output through the pipe (/tmp/snapfifo)
This is my snapserver Pipe
-s "pipe:///tmp/snapfifo?name=Radio&sampleformat=44100:16:2&codec=flac""

Or is it a better way to get it through the Airplay Pipe, supported by Snapcast.
-s "airplay:///shairport-sync?name=Airplay[&devicename=Snapcast][&port=5000]"
When i tried this solution, snapcast said shairpott sync not found (symbolic link?)
Hope anyone please can help me?

**Comment by joerg-krause** [comment]
Both ways should work. I prefer using snapserver with the pipe stream: `snapserver -c flac --buffer 250 --streamBuffer 260 --stream "pipe:///tmp/snapfifo?name=Multiroom&sampleformat=44100:16:2"`.

What does `which shairport-sync` report on your system?

**Comment by HVPereira** [comment]
Is it possible to provide the shairport-sync.Conf I've been trying to make shairport sync to use snapcast server but I am not being able to figure this out could you help out joerg? Maybe I am missing something here I am currently using volumio which comes with shairport-sync and I just wanted the stream to go to the pipe! Is this possible to be done on volumio? When I do it I am under the impression something is missing on shairport-sync. If you could help me on adding this to volumio I would be very greatful! Thanks

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
