### ISSUE TITLE
Raspberry Pi - USB card noise

### ISSUE THREAD

**Issue by RobertShippey** [mikebrady/shairport-sync#486]
Hi, 

Firstly, great project 👍 

I've purchased a USB sound adapted to plug into the Raspberry Pi in order to get around of the noise that is on the build-in output. I got [this one](https://www.modmypi.com/raspberry-pi/accessories/speakers-and-sound/usb-sound-adapter-for-the-raspberry-pi). However it sounds just as noisy to me, with headphones plugged in. Is there any special settings, beyond setting the correct `output_device` that should go with using the USB?

Is there any USB sound adapter that is 'recommended' for your software?

**Comment by mikebrady** [comment]
Thanks for the kind words!

I've used quite a few USB sound adapters, and the one you gave selected looks fine, as far as I can tell. You can't expect too much of them, but any of them should sound much better than the Pi's own build-in audio.

Just check that you are using the device's hardware mixer. You can use `alsamixer` or similar to find the name to use, then pop it into to the `alsa` group's `mixer_control_name`.

**Comment by RobertShippey** [comment]
Thanks for the tip about `alsamixer` - setting the control to 'Speaker' (rather than leaving it commented out) has given me much better volume control. There's still the noise when the music is quiet though, so I think I've just got a dud device, I'll hunt for a better quality replacement.

Audio stuff is new to me, so all part of the learning curve. Thanks for your swift response!

**Comment by mikebrady** [comment]
The noise might just be caused by the power supply. Can you change it easily and check?

**Comment by RobertShippey** [comment]
I purchased a proper USB DAC adapter and the sound is perfect. Lesson learnt, buy cheap buy twice. 

Thanks for being awesome.

**Comment by mikebrady** [comment]
Excellent.

**Comment by ihardiksharma** [comment]
@RobertShippey  can please let us know which sound card did you purchase ans solve the problem.

**Comment by RobertShippey** [comment]
@ihardiksharma I don't have a link but the title on eBay was `PCM2704 USB MINI Sound Card DAC decoder board for PC` - if you search that, plenty come up. 
![PCM2704 USB MINI Sound Card DAC decoder board for PC](https://user-images.githubusercontent.com/787949/39094623-45f4d388-462a-11e8-83aa-cac5585144e8.jpg)

**Comment by ihardiksharma** [comment]
Re: Ethernet noise interferance with a USB Sound card
EditDelete postReport this postQuote
Tue Apr 24, 2018 10:57 am

I have solved problem. Hope this solution will be helpful. I have open the sound card disconnect its 5v supply coming from usb. and give their a separate 5v supply and noise problem gone. so in conclusion sound card require 5v stable supply from raspberry pi. but it can not give due to interference of Ethernet and others. Give it to separate 5v power supply(of course ground would be common) and problem will be gone.
