### ISSUE TITLE
STDOUT Understanding

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#488]
I've added the --with-stdout (along with --with-apple-alac) flag to my latest install

I'd like to know if this means if I'm sending a 48k 24bit sound file to the Raspberry Pi, that it in turn will natively send that out to my DAC which will automatically recognize and accept anything between 44.1/16 and 192/24?

ALAC will support anything from 44.1/16 to 192/24

I plan to add the HifiBerry Digi + to my Pi3 which will output whatever format it is sent!

https://www.hifiberry.com/shop/boards/hifiberry-digi-pro/

If this is the case, this will make me happy beyond all means and I will be singing the happy happy joy joy song for months, nay years on end!

**Comment by mikebrady** [comment]
Not so fast! ❗️😐  It is true that ALAC will accept anything in that range, but Apple never seems to have used it in AirPlay at other than CD quality. All iTunes material at other rates and depths is translated to CD quality ALAC for AirPlay. Shairport Sync is through-and-through set up to do CD quality only, and at present it can't accept any other format of input. It would be lovely to relax the constraints to allow it to accept other formats (and using the ALAC decoder might be a step on the way), but that's quite a project.

**Comment by rockrabbit** [comment]
*sob* 

So its **Airplay** that is the bottle neck!

*kicking and screaming*

stuck at 44.1/16 no matter what!

Oh well!

Got excited about finally unleashing my 96/24 Nine Inch Nails, but will have to settle for down sampling! :(

**Comment by mikebrady** [comment]
Yeah, I know how you feel. If somebody else could generate AirPlay source at higher rates or depths, it would be an incentive. Maybe @ejurgensen could be persuaded 😊.

**Comment by rockrabbit** [comment]
It is true that most everyone cannot hear the difference between 44.1/16 and 96/24.. I know.. heck its even worse that most people cannot hear the difference between MP3 (yuck) and AAC and CD (44.1/16)

Truth be told its sounds good as it is, and if anything I think using the ALAC CODEC kinda opened up the sound a bit on both my rigs.

Just wanted to see the pretty lights on my Bryston BDA-1 light up like they did when I still had a SACD player!

Thank for for all your hard work making Shairport-Sync into the delightful monster it has become and hopefully continues to grow!

**Comment by mikebrady** [comment]
Thanks. There is more to come alright...
