### ISSUE TITLE
Disable "Busy" Signal?

### ISSUE THREAD

**Issue by graymen2** [mikebrady/shairport-sync#49]
Hello,

I'm wondering if it's possible to disable the "busy" signal? I actually like that the last one playing wins. Maybe add it as an command line option?

Thank you

"Shairport Sync sends back a "busy" signal if it's already playing audio from another source, so other sources can't disrupt an existing Shairport Sync session. (If a source disappears without warning, the session automatically terminates after two minutes and the device becomes available again.)"

**Comment by mikebrady** [comment]
Hi. Thanks for your interest. Yes, you can disable the busy signal by setting the `-t` option to 0 – see the write-up at http://htmlpreview.github.io/?https://github.com/mikebrady/shairport-sync/blob/2.2/man/shairport-sync.html.

**Comment by mikebrady** [comment]
Hi there. Just FYI, I've done some updates to this and replaced the `-t` option with two independent settings, one for disabling the busy signal and one for setting the timeout. They are in the (new) configuration file in the development version.

**Comment by mikebrady** [comment]
These configuration file settings are now in the stable master version.
I'm going to close this – feel free to reopen if there are developments.

**Comment by spinko101** [comment]
hi again, the link above seems to be outdated. Could you please indicate which command has to be passed to Shareport to deactivate the busy signal ? Thank's a ton ;-)

**Comment by spinko101** [comment]
ok, I think I found it here

http://htmlpreview.github.io/?https://github.com/mikebrady/shairport-sync/blob/2.4/man/shairport-sync.html

(2.4)

thank's
