### ISSUE TITLE
Shairport-Sync on Cygwin - unexpected sample rate! (and quits)

### ISSUE THREAD

**Issue by joaodriessen** [mikebrady/shairport-sync#491]
Compiled and installed Shairport-sync following the cygwin guide, with these configure options:

`PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --with-ao --with-ssl=openssl --with-stdout --with-pipe --with-tinysvcmdns --with-ssl=openssl --with-metadata`

then did `make` and `make install`
Shairport-Sync starts up and is visible on my network (iPhone sees it)
When I try to play anything Shairport-Sync gives the following error:

> unexpected sample rate!

output of Shairport-Sync error with -v running:

> Looking for the configuration file "/usr/local/etc/shairport-sync.conf".
Version: "3.0.1-OpenSSL-tinysvcmdns-ao-stdout-pipe-metadata-sysconfdir:/usr/local/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "Sapphire".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 1.000000 seconds.
audio backend latency offset is 0.000000 seconds.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
no special mdns service interface was requested.
configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
Successful Startup
New RTSP connection from [fe80::66:fb65:2bf9:342b]:57361 to self at [fe80::35d1:963c:f871:c57e]:5000.
Play connection from user agent "AirPlay/310.17".
Active-Remote string seen: "855104676".
DACP-ID string seen: "4C6C079DA9299213".
Set up play connection from fe80::66:fb65:2bf9:342b to self at fe80::35d1:963c:f871:c57e.
unexpected sample rate!
Request to shut down all rtsp conversation threads

**Comment by mikebrady** [comment]
Thanks for the report. Can I ask what the player you are using is please? For example, is it iTunes? If you could give details about the version and platform, it would be very helpful.

**Comment by mikebrady** [comment]
Okay, I got the error – let me investigate.

**Comment by mikebrady** [comment]
I hope that's fixed now in 3.0.2.

**Comment by joaodriessen** [comment]
Mike you are wicked awesome, I can't believe you fixed the issue so damn fast!

Do you know whether synchronisation is something that could ever be supported running on Cygwin?
