### ISSUE TITLE
Video synchronization/latency compensation

### ISSUE THREAD

**Issue by Arve** [mikebrady/shairport-sync#494]
I'm trying to use shairport-sync in a setup where I occasionally output the audio from Netflix running on an iPad.

My setup is slightly convoluted, as I'm routing audio into an alsa loopback (using `snd-aloop`), which is then further processed with BruteFIR before BruteFIR routes the convolved audio to a USB DAC.

BruteFIR has a fixed sample delay in my configuration of 16384 samples, plus whatever latency is inherent to the alsa loopback and hardware buffers 

Now, I tried using `audio_backend_latency_offset` to the alsa section of `shairport-sync.conf` as such:

    audio_backend_latency_offset_in_seconds = -0.38;

When adding this option, I'm getting no audio output at all. 

Similarly

    audio_backend_buffer_desired_length_in_seconds = 0.38;

is not fixing the issue for me either - audio and video is still out of sync.

Am I doing something wrong, or is there a bug with the backend latency offset setting?

**Comment by mikebrady** [comment]
Thanks for the report. I'll check it out.

**Comment by mikebrady** [comment]
Hi there. There is definitely a bug here. It's take a little while to work it out and fix it.

**Comment by mikebrady** [comment]
Just pushed an update to the `development` branch that [I think] fixes this problem.

**Comment by Arve** [comment]
Thank you

**Comment by Arve** [comment]
Tested, and audio_backend_latency_offset_in_seconds now does the job I wanted it to do. No more
 offset audio when watching Netflix 🤗

Is there any chance that you'll add (bring back?) sample-accurate latency offset?

**Comment by mikebrady** [comment]
Hi Arve. I'm glad it works. Actually, I'm moving away from sample-rate-based settings deliberately, and while 16384/44100 is 0.371519274376417, the accuracy of synchronisation is no better than 0.002 seconds at present, and unlikely to get better than 0.0002 in the future... You should nevertheless put in something like 0.371519274376417 – the number is treated as an IEEE 754 double before being used to calculate the actual number of samples.
