### ISSUE TITLE
Software Volume boost over 100%

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#496]
Is there any way to boost volume in shairport-sync over 100%?

**Comment by mikebrady** [comment]
No, I'm afraid not. What is implemented is strictly an attenuator.

**Comment by roblan** [comment]
Maybe there is some alsa related magic? :)

**Comment by Arve** [comment]
@roblan Boosting digital volume beyond 100% is one of the things that you strictly speaking should not ever do, because in the case input signal is a full-scale signal, it will clip very badly, sounding distorted in a way that at worst can damage speakers
