### ISSUE TITLE
Change IP caused that Shairport-sync was not showing in iTunes...

### ISSUE THREAD

**Issue by nem0rder** [mikebrady/shairport-sync#497]
Hey

I installed shairport-sync on my Raspberry Pi 3 yesterday and everything was looking nice. Then i connected a Gigabit USB device and USB Sound Device. Everything seem to work on the rpi, but it was not showing in iTunes or on IOS.

I have finally found the solution, when i connected the Gigabit USB i got a new ip (.33) from my router, when i changed it back to the one from the old interface (.228), it popped up in iTunes and IOS. 

I do not known if it is an issue with shairport-sync or my router. But i think it has something to do with multicast or something like that.

**Comment by mikebrady** [comment]
Hmm, that interesting. Sometimes it takes multicast-DNS a while to catch up with IP number changes; I wonder if that's what the issue is...
