### ISSUE TITLE
Flag error if pipe is not writeable

### ISSUE THREAD

**Issue by jbieling** [mikebrady/shairport-sync#498]
While fiddling with forked-daapd and piping audio from shairport-sync, I somehow made the pipe non-writeable for shairport-sync. Since shairport-sync did not flag an error, it was more difficult to spot. The statistics in verbose output did help, but an explicit error when shairport-sync starts would be more convenient.

**Comment by mikebrady** [comment]
Hi there. Thanks for the suggestion.
