### ISSUE TITLE
Sharp static on connect/disconnect

### ISSUE THREAD

**Issue by JarekToro** [mikebrady/shairport-sync#499]
When I connect my iPhone to stream through the hummingboard/pi when I first connect a sharp static plays before music. The music though is clear and Crisp

The same sound happens when I disconnect

**Comment by mikebrady** [comment]
Thanks for the post. What version of Shairport Sync is it please? (`$ shairport-sync -V`)

**Comment by JarekToro** [comment]
Haha well funny thing idk why I decided to submit a bug 1 hr before taking a flight out of town. But I did. I just built it maybe a week ago so it should have all the latest.
It's running on a hummingboard 
I'll be back in 3 days and I can get you the exact version. My bad :)

**Comment by moodeaudio** [comment]
Hi,

I experienced that static noise one time after I stopped playing from iTunes. IIRC I had to reboot Pi to stop the noise.

pi@moode:~ $ shairport-sync -V
3.0-OpenSSL-Avahi-ALSA-stdout-soxr-metadata-sysconfdir:/usr/local/etc

-Tim

**Comment by mikebrady** [comment]
Hi Tim. I fixed a noisy bug in 3.0 and pushed it out in 3.0.1 – it was caused by mishandling the situation missing packets. Just wondering if it might have been the cause.

**Comment by moodeaudio** [comment]
Thx Mike.

**Comment by JarekToro** [comment]
Hello I'm back.
here is my version 3.0-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc
worth noting I have reboot a few times and its not a one time sound every time you connect or disconnect from my iPhone for example a static ring plays.

My hummingbird is connect to network via ethernet just for extra info

**Comment by JarekToro** [comment]
I can try version 3.0.1 if you'd like

**Comment by mikebrady** [comment]
Yes please, or even better, try the `development` branch.

**Comment by JarekToro** [comment]
3.1s3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

**Comment by JarekToro** [comment]
same static

**Comment by JarekToro** [comment]
would you like an audio clip?

**Comment by JarekToro** [comment]
http://vocaroo.com/i/s15dFBQJfiXY

**Comment by mikebrady** [comment]
Thanks. I'm not familiar with the Hummingboard. Does it have the same audio output device as the Pi? (I'm presuming the sound was from the Hummingboard, BTW.)

**Comment by mikebrady** [comment]
It does sound pretty rough alright. Is there a possibility you could play something through it with the `aplay` utility? For preference, a track consisting of total silence, just to see how quiet the system it overall... The test would serve to see if the problem with Shairport Sync or with the system. When Shairport Sun is about to start playing, it will send up to around two seconds of silence beforehand, to sync up the processing chain, and I'm guessing you're hearing what should be silence. Another question would be whether the power supply nice and clean...

**Comment by JarekToro** [comment]
I was just researching the Hummingboard specs but haven't found exacts. I know its not the same but also I know its a better quality DAC and has better silent sounds (less static). I will use aplay and let you know.

**Comment by JarekToro** [comment]
Any options I should include in aplay?

**Comment by mikebrady** [comment]
Well, I guess it would be good if the source was 16-bit little-endian 44,100 samples per second interleaved stereo ("CD quality") as that would be what Shairport Sync puts out by default.

**Comment by JarekToro** [comment]
ok so when playing the actual file with aplay it does the same thing. before it plays it has the sharp static but only for a second. Then it plays the silent audio without any static. Then when I stop the audio it plays the sound again. So this is probably a hardware issue. Do you think it could be a power supply issue?

**Comment by mikebrady** [comment]
It's certainly worth swapping out the existing p/s for another one, see what happens.

**Comment by JarekToro** [comment]
Ok I've tried a few dif power supplies and even swapped out to another hummingboard hardware. I don't have the exact spec power supply. Apparently I have everything but 5v 2a the most common of power supplies. But this for sure seems like a hardware problem and not software. Feel free to close this thread. If anything does come up ill either post it here if its relevant or open a new issue if necessary. Thank you

**Comment by mikebrady** [comment]
Many thanks.

**Comment by bingimar** [comment]
had the same static noise, replaced the power supply, problem solved.
