### ISSUE TITLE
Peaking over 0dbFS

### ISSUE THREAD

**Issue by yetanotherman** [mikebrady/shairport-sync#502]
Hello,

Thanks for great piece of software, first of all!

There may be a bug in audio attenuator in version 3.0.2 and 3.0.1. My setup is:
Raspberry PI 3 running Raspbian 8 -> USB Sound Blaster (SB1095) usbid 041e:30df -> TosLink output -> Motu 828mk3 hybrid

When I run audio from my iPad from iTunes/Apple Music (IOS9) - mainly heavy mastered dance tracks, I clearly hear peaking/see it on meters on TOSLINK interface - that is, before any software processing. Issue goes away after setting maximal volume in config to -2db, note that -1db was not enough - or just lowering volume in IOS.

**Comment by mikebrady** [comment]
Many thanks for the post!

**Comment by mikebrady** [comment]
Quick questions – are you using the equalizer or Sound Check or any of those sound "enhancement" features? If you are, what happens if your turn them off?

**Comment by yetanotherman** [comment]
No, I don't use any kind of enhancement features. Will re-check it now to be sure.

**Comment by yetanotherman** [comment]
Re-checked. The same issue appears when I use software signal generator, so, the problem is not limited to iTunes.

**Comment by mikebrady** [comment]
Thanks. Can you explain how the software signal generator is connected through to Shairport Sync please?

**Comment by yetanotherman** [comment]
Thats an app for iPad. I'm sure that I have no signal processing system-wide in IOS, but I'm not sure about iTunes itself - so, I checked with this app.

**Comment by mikebrady** [comment]
OK, thanks.

**Comment by mikebrady** [comment]
So, I ran a signal (1kHz) through iPad -> Shairport Sync. Can't hear any particular distortion. What are you using to detect peak values?

**Comment by yetanotherman** [comment]
I'm sorry, the issue is not related to shairport-sync. I just re-checked everything using aplay - and the problem is still there - so, thats not related to airplay at all. My bad, I should have checked my own setup before reporting.

**Comment by mikebrady** [comment]
Many thanks for letting me know. I got to know a little bit more about signal generators.
