### ISSUE TITLE
Not an issue but a question on the interface option under shairport-sync.conf

### ISSUE THREAD

**Issue by gilgameshskytrooper** [mikebrady/shairport-sync#505]
Hey Mike. I have been using shairport-sync without a hitch for some time now, and it does everything I need it to do! The only issue is that I can't use my school's WiFi to connect to it. However, I have no issues connecting to it via a the eth0 wired connection.

Now I have been using this as part of a bigger project to be able to run an Alarm Clock on my Raspberry Pi. However, I have started to run into some peculiar issues of not being able to SSH and VNC into my Pi via the school network after keeping my Pi on for more than 24 hours.

I am trying to figure out all possible solutions, and it might be that since shairport-sync opens up to the entire school network, and the school network doesn't allow that connection (Airplay), my school's IT has protocols to cut the inbound connections on the Pi.

Hence, I want to see if limiting shairport-sync's ability to broadcast the airplay server to ONLY wired connection will work.

Now, looking at your documentation at http://htmlpreview.github.io/?https://github.com/mikebrady/shairport-sync/blob/master/man/shairport-sync.html
It still wasn't clear to me what exactly the "interface" is referring to.

I am assuming it means the network interface, but I wasn't sure.

Hence I wanted to confirm, if I uncomment and set interface = "eth0", will this stop shairport-sync from broadcasting to the WiFi network?

Thank you,
Andrew

**Comment by mikebrady** [comment]
Hi Andrew.

Thanks for the interesting post.

Your understanding is correct. The option affects the way Shairport Sync advertises itself using [Bonjour/ZeroConf](http://www.zeroconf.org). When you use the option, the ZeroConf subsystem provided by [Avahi](http://www.avahi.org) or [tinysvcmdns](https://bitbucket.org/geekman/tinysvcmdns) will use the Bonjour/ZeroConf protocol only on the interface you specify.

However, Shairport Sync itself continues to listen for incoming requests on all interfaces. Thus, port 5000 will remain open even on the WiFi interface.

I hope this helps.
Mike

**Comment by gilgameshskytrooper** [comment]
Thanks a bunch!
