### ISSUE TITLE
Potentially shairport-sync somehow blocks standard ssh/http functionality

### ISSUE THREAD

**Issue by gilgameshskytrooper** [mikebrady/shairport-sync#507]
So after specifying the interface to eth0, now I can no longer connect via ssh, or access the website I am serving on it through the wired IP (but using the wireless network, everything else works fine).

It might not be shairport-sync itself, but the fact that the Raspberry Pi has weaker hardware to utilize.

Just thought I should let you know. Other than that, it does everything else marvelously

**Comment by mikebrady** [comment]
Thanks. I can't imagine that Shairport Sync is the cause, to be honest. And the Pi is fast enough to hold its own on a busy university network, so I don't think it's the hardware. I'd be looking somewhere else for the cause.

**Comment by cre8dojo** [comment]
I run run 5 instsnces of shairport-sync, Node Red, and mqtt broker on rpi 2 B+ for over a year with no problems. over eth0
