### ISSUE TITLE
Can't set the D/A converter to 44100 -- set to 48000 instead.

### ISSUE THREAD

**Issue by eripa** [mikebrady/shairport-sync#51]
I've been using shairport-sync on two devices (Pi) with great success. However, only one of them have a proper DAC and then I found an old "3D Sound" USB card laying around, so I figured that I would hook it up to the other Pi to get a bit better sound from it.

However, the USB card only seem to support 48KHz. I found the below thread on volumio.org. Any news on this 'issue'?  Or should I bit the bullet and get another proper DAC? 

https://volumio.org/forum/new-version-shairport-with-audio-synchronisation-t1302.html

**Comment by mikebrady** [comment]
Hi Eric. It's good to hear that you're having success with shairport-sync. TBH, I don't have any near-term plans to support other sample rates, so I think it would be best to bite that bullet. In any case, it's an open question as to whether a first generation Raspberry Pi could support it.

**Comment by eripa** [comment]
Cool, thanks a lot for the explanation. I will look into a real DAC then.

**Comment by Havelock-Vetinari** [comment]
Hi Eric!
For ALSA sound system you can try with rate converter.
Create configuration in **/etc/asound.conf** similiar to one below:

```
pcm_slave.jabra
{
    pcm "hw:2,0"
    rate 48000
}

pcm.jabra_44k1 {
    type rate
    slave jabra
}
```

Now, refer to rate converting device (in example above **jabra_44k1**) in shairport-sync configuration:

```
alsa =
{
  output_device = "jabra_44k1";
};
```

**Comment by patientx** [comment]
> Hi Eric!
> For ALSA sound system you can try with rate converter.
> Create configuration in **/etc/asound.conf** similiar to one below:
> 
> ```
> pcm_slave.jabra
> {
>     pcm "hw:2,0"
>     rate 48000
> }
> 
> pcm.jabra_44k1 {
>     type rate
>     slave jabra
> }
> ```
> Now, refer to rate converting device (in example above **jabra_44k1**) in shairport-sync configuration:
> 
> ```
> alsa =
> {
>   output_device = "jabra_44k1";
> };
> ```

Hi there. I found out about your program today wanted to try it with my pi mopidy setup. It is working with mopidy as the USB AUDIO card as output and everything is fine.

However, when using with shairport-sync I am having the same problem. 

`"fatal error: Can't set the D/A converter to 44100."`

But when I just use :   `shairport -- -d hw:1` the audio works fine there with the usb card.  I mean with tuneblade working on PC the same content -mp3 via winamp- plays on the pi usb speaker just fine.

 I also wanted to try your also converter solution with the asound.conf file but the file is not there on my system and I never needed it at all while setting up mopidy. I can continue to use normal shairport but if possible I want to try the sync version. Thanks for your hardwork.

**Comment by mikebrady** [comment]
Hi there, and thanks for the post. Shairport Sync requires a real sound card with a 44,100 (CD quality) frames per second capability. This is necessary because audio comes in at 44,100 frames per second and Shairport Sync does not transcode.  The rate converter solution proposed above would require a lot of processing power, probably more than a Pi has to offer, and would very likely interfere with synchronisation. Most DACs support 44,100 or a multiple nowadays.

**Comment by VergilGao** [comment]
In my case, I need to use both shairport-sync and gmrender to play music at the same time,I need the dmix plugin to allow multiple programs to share the sound card. but when I use dmix, the device is set to 48k.

this works for me.
```
pcm.analog_44k1 {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:ANALOG"
        rate 44100
    }
}
```
