### ISSUE TITLE
Shairport-sync Name

### ISSUE THREAD

**Issue by envoys** [mikebrady/shairport-sync#510]
Hello,

I have setup shairport-sync and it works great but inside my /etc/shairport-sync.conf I have this:

> general =
{
        name = "Testing 123";
        password = "password";
};

But on any apple device, it is still coming up showing the machine hostname and not asking for the password. Have restarted the service, rebooted etc and it still isn't pick this up.

How can I resolve this?

Thanks for the awesome project!

EDIT:::

Just to update, if I edit the /etc/init.d/shairport-sync file and add "-c /etc/shairport-sync.conf" to the start daemon command, then it loads properly. In debug I get "configuration file name "/usr/local/etc/shairport-sync.conf" can not be resolved." so for now I just created a symlink.

**Comment by mikebrady** [comment]
Hi there. Thanks for the post – I think I can figure out what happened. There is a setting that you might have missed at the `$ ./configure...` stage which tells Shairport Sync where to look for the configuration file `shairport-sync.conf`.

The setting recommended for Linux, is `--sysconfdir=/etc`, and if you include that, Shairport Sync will look in `/etc` for the configuration file. If you omit the setting, then the default location is used, which is the directory `/usr/local/etc`.

Does this sound like the right explanation?

Anyway, it's all mentioned in the guide at [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md). If you are using a guide from another site, it might be worth asking them to update it...

**Comment by envoys** [comment]
@mikebrady sorry for the late reply, that was exactly my issue! Thanks for the awesome software.
