### ISSUE TITLE
Shairport-sync disappears from airplay devices list

### ISSUE THREAD

**Issue by Aldytoff** [mikebrady/shairport-sync#512]
Hello Everyone

A problem that doesn't seem to be a new one, but none of the solutions seem to work for me.

Shairport-sync on a rpi B with wifi dongle, and on a rpi 3 with integrated wifi. Both show the same issue.

Over Ethernet, no problem, over wifi, the connection seems to drop after a couple of minutes.

Wifi Power management as been disabled on both.
And while not showing on AirPlay list, I can still ping the pi from my computer, and ping the computer from the rpi...

Any help would be welcome.

Cheers

**Comment by mikebrady** [comment]
Quick question: is the computer in WiFi or Ethernet? If you can switch, does it make a difference?

**Comment by Aldytoff** [comment]
Hello Mike

For now computer is over ethernet, and same issue if I put it on wifi, or if I use my iPhone to connect over wifi. It appears only for a very brief moment after boot up.

However, when my computer is over wifi, impossible to ping the raspberry pi, or for the rpi to ping my computer. Could that be related ?

Cheers

**Comment by mikebrady** [comment]
Hi there. Yes, I think they could be related. I should have asked if the computer is a Mac or a Windows machine. The problem could be a poor network, a poor router, a firewall somewhere, soon the router, on the computer, on the RPis, though you'd have to do that deliberately. If you install `avahi-utils` on the Shairport Sync devices and Bonjour Browser on the computer, assuming it's a Mac, you can see what Shairport Sync is advertising on the network using ZeroConf/Bonjour and then you can see if that signalling is arriving at your Mac.

If you computer is Windows, check to see if you have a firewall running. It's easy to have one running and not to know it – it seems to be associated with the kind of network you tell Windows you are commented to – Public, Work, Home or whatever.

**Comment by Aldytoff** [comment]
Hi

Thanks for those guide lines, will look into it !

**Comment by metzenseifner** [comment]
I have the same problem on my pi3. It just disappears after awhile. I can still ping and ssh into the pi.

**Comment by mikebrady** [comment]
Thanks for the report. What it disappears next could you check the logs on the Pi3 to see what the status of Shairport Sync is please? You could use `$ sudo systemctl status shairport-sync`.

**Comment by mikebrady** [comment]
Also, when you write “awhile”, how long do you mean?

**Comment by metzenseifner** [comment]
I will check the logs and get back to you. I purposely chose an indeterminant form like “awhile”, because I do not see a pattern to the madness yet. We‘re talking like 5 songs worth give or take 3? Still hard to measure.

**Comment by metzenseifner** [comment]
> Also, when you write “awhile”, how long do you mean?

Ok, I now have some data to provide. It happened just now after about **8 minutes**. I was streaming from Soundcloud. However this time, the menu entry for the shairport server appeared again on my client's list (Macbook Pro).

My raspberry pi 3 is running Arch Linux. 

4.14.86-1-ARCH
3.2.2-OpenSSL-Avahi-ALSA-pa-soxr-sysconfdir:/etc

```
Dec 13 19:53:01 host shairport-sync[887]: RTSP thread 7 received an RTSP Packet of type "TEARDOWN":
Dec 13 19:53:01 host shairport-sync[887]:   Type: "CSeq", content: "251"
Dec 13 19:53:01 host shairport-sync[887]:   Type: "DACP-ID", content: "6B1336985CB57500"
Dec 13 19:53:01 host shairport-sync[887]:   Type: "Active-Remote", content: "1339237558"
Dec 13 19:53:01 host shairport-sync[887]:   Type: "User-Agent", content: "AirPlay/371.6.7"
Dec 13 19:53:01 host shairport-sync[887]: Connection 7: TEARDOWN
Dec 13 19:53:01 host shairport-sync[887]: Cancelling timing, control and audio threads...
Dec 13 19:53:01 host shairport-sync[887]: Cancel timing thread.
Dec 13 19:53:01 host shairport-sync[887]: Join timing thread.
Dec 13 19:53:01 host shairport-sync[887]: shutdown timing socket.
Dec 13 19:53:01 host shairport-sync[887]: close timing socket.
Dec 13 19:53:01 host shairport-sync[887]: Timing thread terminated.
Dec 13 19:53:01 host shairport-sync[887]: Cancel control thread.
Dec 13 19:53:01 host shairport-sync[887]: Join control thread.
Dec 13 19:53:01 host shairport-sync[887]: shutdown control socket.
Dec 13 19:53:01 host shairport-sync[887]: close control socket.
Dec 13 19:53:01 host shairport-sync[887]: Control thread terminated.
Dec 13 19:53:01 host shairport-sync[887]: Cancel audio thread.
Dec 13 19:53:01 host shairport-sync[887]: Join audio thread.
Dec 13 19:53:01 host shairport-sync[887]: shutdown audio socket.
Dec 13 19:53:01 host shairport-sync[887]: close audio socket.
Dec 13 19:53:01 host shairport-sync[887]: Audio thread terminated.
Dec 13 19:53:01 host shairport-sync[887]: Freeing audio buffers and decoders.
Dec 13 19:53:01 host shairport-sync[887]: Connection 7: player thread terminated.
Dec 13 19:53:01 host shairport-sync[887]: RTSP thread 7: RTSP Response:
Dec 13 19:53:01 host shairport-sync[887]:   Type: "CSeq", content: "251"
Dec 13 19:53:01 host shairport-sync[887]:   Type: "Server", content: "AirTunes/105.1"
Dec 13 19:53:01 host shairport-sync[887]:   Type: "Connection", content: "close"
Dec 13 19:53:01 host shairport-sync[887]: Connection 7: RTSP thread terminated.

```

**Comment by mikebrady** [comment]
Thanks. TBH, that looks like the request to terminate the session came from the sound source.

However -- and this is a big however -- a lot of work has been going on to improve the stability of Shairport Sync in general. So, if you were to update to the current `development` branch, you might find it a good bit more resilient.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
