### ISSUE TITLE
Shairport-sync not working with doubleTwist

### ISSUE THREAD

**Issue by HiteshBaadkar** [mikebrady/shairport-sync#515]
I'm using Double Twist and RPI3B along with a USB Sound card as output. (and input for another project).
DoubleTwist can see my Rpi and i connect to cast to the RPI too. But then all i can hear in the output is static noise with pauses in the middle. Don't know what else to do.

PS:-I have also disabled the default 3.5mm audio jack by editing the boot/config.txt and commenting the dtparams line so the default soundcard doesn't load.

**Comment by mikebrady** [comment]
Yeah, there is a problem playing from DoubleTwist – see #492.

**Comment by HiteshBaadkar** [comment]
alright i'll try using allconnect....but check this next one

**Comment by HiteshBaadkar** [comment]
found out something really weird.
if i try
[code] shairport-sync -v[/code]

the output:-

[code]Successful Startup
Unable to listen on IPv4 port 5000. The error is: "Address already in use".
Unable to listen on IPv6 port 5000. The error is: "Address already in use".
Could not establish a service on port 5000 -- program terminating. Is another instance of Shairport Sync running on this device?
Request to shut down all rtsp conversation threads
[/code]

and then check up on shairport-sync -v using the following command, everything looks running:-

[code]sudo systemctl status shairport-sync[/code]

with output:-
[code] shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled)
   Active: active (running) since Fri 2017-04-28 21:44:25 IST; 1min 49s ago
 Main PID: 2131 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─2131 /usr/local/bin/shairport-sync

Apr 28 21:44:25 Cosmic_Hawk systemd[1]: Started ShairportSync AirTunes receiver.
Apr 28 21:44:25 Cosmic_Hawk shairport-sync[2131]: Successful Startup
[/code]


Now the fun part starts here:-
i disable the shairport-sync using:-

[code]sudo systemctl stop shairport-sync[/code]

and then check on it with [code]sudo systemctl status shairport-sync[/code] again and i get

output:-

[code]● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled)
   Active: inactive (dead) since Fri 2017-04-28 21:50:21 IST; 10s ago
  Process: 2131 ExecStart=/usr/local/bin/shairport-sync (code=exited, status=0/SUCCESS)
 Main PID: 2131 (code=exited, status=0/SUCCESS)

Apr 28 21:44:25 Cosmic_Hawk systemd[1]: Started ShairportSync AirTunes receiver.
Apr 28 21:44:25 Cosmic_Hawk shairport-sync[2131]: Successful Startup
Apr 28 21:50:21 Cosmic_Hawk systemd[1]: Stopping ShairportSync AirTunes rece....
Apr 28 21:50:21 Cosmic_Hawk systemd[1]: Stopped ShairportSync AirTunes receiver.
Hint: Some lines were ellipsized, use -l to show in full.
[/code]

but then after this when i use [code]shairport-sync -v[/code] to check it again, just out of the blue

[code]Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'F61B4153B576@Cosmic_Hawk' successfully added.
[/code]

i get the successful output.....can't see what's going on here....

**Comment by mikebrady** [comment]
That's all as expected – no mystery there, I'm afraid. The explanation is that `shairport-sync` is installed and runs as a service after startup and listening on port 5000. When you ran `shairport-sync -v` you were starting a second instance of it, but the port isn't available. When you ran `sudo systemctl stop shairport-sync` you were stopping the service and thus freeing up the port, allowing your new instance to run.

**Comment by HiteshBaadkar** [comment]
Alright, thanks a lot for the project though. Great work! Keep it up :)
Understood the concept now.  Sorry for the inconvenience caused.

**Comment by HiteshBaadkar** [comment]
pi@Cosmic_Hawk:~ $ sudo systemctl status shairport-sync -l
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled)
   Active: active (running) since Sat 2017-04-29 00:34:02 IST; 6min ago
 Main PID: 629 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─629 /usr/local/bin/shairport-sync

Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card
Apr 29 00:40:04 Cosmic_Hawk shairport-sync[629]: ALSA lib pcm_hw.c:1667:(_snd_pc              m_hw_open) Invalid value for card



this is what I get, which file should i edit?

**Comment by mikebrady** [comment]
Can you post details of the sound card please?

**Comment by HiteshBaadkar** [comment]
Here's the link:-
uses CM-108 

[http://www.amazon.in/Enter-External-USB-Sound-card/dp/B00E9R54ZG/ref=cm_cr_arp_d_product_top?ie=UTF8](url)

**Comment by mikebrady** [comment]
Thanks. It looks fine. Could you try to get it to work with the `aplay` program, just to check that it actually works, without using Shairport Sync? It would be perfect if you could play a 44,100 sample per second stereo track through it.

**Comment by HiteshBaadkar** [comment]
yup plays it, I'm currently also using Kodi.

**Comment by mikebrady** [comment]
Thanks. Is it definitely working at 44,100?

**Comment by mikebrady** [comment]
Actually, what would be great is if you could post a complete log from startup to the error messages, with Shairport Sync set to have a verbosity of 1. That would be a big help.

**Comment by HiteshBaadkar** [comment]
yup, I'm using it to work on AlexaPI, works great. Sure, after I get my hands on my RPI? Out right now, will do so by tommorow.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
