### ISSUE TITLE
mDNS Issues

### ISSUE THREAD

**Issue by techwiz001** [mikebrady/shairport-sync#516]
Great work on the program. It installed wonderfully on my Raspberry Pi 2B running Raspbian Jessie. However, whenever I launch the service, it says "Cannot create mDNS advertisement!" and exits. Any advice on resolving this issue?

**Comment by mikebrady** [comment]
Thanks for the post. Can you post the output from
`$ shairport-sync -V`
please?

**Comment by techwiz001** [comment]
`3.0.2-OpenSSL-ALSA-metadata-sysconfdir:/etc`

**Comment by techwiz001** [comment]
After not seeing the Avahi tag, I went back in my command history and ran './configure' again, as I had used the '--with-avahi' flag the first time. It worked, now my Pi sounds wonderful. Thanks again for the fantastic code!

**Comment by mikebrady** [comment]
Yep, that was it. Well spotted.

**Comment by mikebrady** [comment]
Okay to close this now?

**Comment by techwiz001** [comment]
Yes. Thanks for your help, never would have found it without that command.
