### ISSUE TITLE
Apple TV 4 Audio sync

### ISSUE THREAD

**Issue by Peter98** [mikebrady/shairport-sync#520]
Thanks for all the great work done here it's been enlightening reading through the posts.
I have a slightly different use case and I need some inspiration on how to approach/solve the problem.
I basically want to stream my Apple TV audio to 2 independent wireless speakers.
Each speaker has a raspberry pi 3 B, DAC and and amp and running shairport-sync. When connect the Apple TV to each individual speaker i get close to 0 latency between the video and the audio which is what I want but i need to run both at the same time.
Any ideas are appreciate,
Peter

**Comment by mikebrady** [comment]
Thanks for the slightly unusual case. Not sure if Apple TV allows you to connect to two sets of speakers at the same time. If it doesn't, then I'm afraid I don't think Shairport Sync can help.

BTW, the synchronization should be exact. If it isn't, I believe it's because of processing delays in the TV's audio processing after the audio leaves the Apple TV.. You can adjust for it in Shairport Sync's configuration file.

**Comment by Peter98** [comment]
Thanks for getting back to me Mike. I've had pretty good success using the node-airplayhub project which uses and iTunes server to pipe to 2 iTunes streams pointing at two shairport-sync end points, if I cut out all of the buffers and latency in the airtunes stream app (a node app) I'm just a smidge off syncing audio and video, maybe 100ms. Seems piping the stream this way is really fast. An alternative method I tried was: Apple TV -> shairport-sync pipe -> forked-daapd (to split stream into 2)-> 2x shairport-sync end points. The latency ended up being about 4-5 seconds as advertised in the forked-daapd project issues.

In either configuration is there a way to compensate for the lag using shairport-sync? I have tried different options in the config file but nothing has worked yet, what setting were you referring to in your post?

Thanks again for responding!

**Comment by mikebrady** [comment]
Yeah, in the group that corresponds to your back end, there is a setting called `audio_backend_latency_offset_in_seconds`. It should allow you to offset the time by up to about 1 second, so 0.1 seconds should be fine. Let me know if it works or not – I haven't tested it extensively.

**Comment by Peter98** [comment]
Will take a look and get back to you.

**Comment by Peter98** [comment]
Apple were not very vocal about tvOS 11 but they have announced Airplay 2 to be released with iOS 11 in September along with Apple TV 5. I will assume they have to update tvOS 11 to include Airplay 2 to maintain a consistent ecology noting likely supported backward compatibility. So two questions are key.
1) Will streaming to multiple speakers be supported for Airplay/Airplay 2 in tvOS 11 - I think this will be likely
2) How hard is it going to be to build "Shairport 2" - Given backward compatibility this might not be a massive issue but would be a longer term goal.

**Comment by mikebrady** [comment]
See #535.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
