### ISSUE TITLE
Mono Output - Brick wall clipping leads to distortion [FIXED]

### ISSUE THREAD

**Issue by ArrEssJay** [mikebrady/shairport-sync#522]
Mono sum in player.c appears to be a simple summation of L+R, with brick wall clipping of a signed 16-bit signed int. This leads to considerable clipping distortion on loud signals.

Would you be open to pulling a commit that that takes an approach to resolving this such as converting to 24/32-bit ints, and using Mono = L >> 8 + R >> 8, then converting back to 16-bit for output and dithering? I see you've already got some dither code to handle sample rate conversion.

Although I appreciate were dealing with resource-constrained devices, an alternative would be to always (when there's anything in the the signal processing chain) upsample the input/downsample+dither the output so that clipping problems like this are avoided elsewhere.

**Comment by mikebrady** [comment]
Thanks for the post. Let me check it out. What version are you looking at?

**Comment by mikebrady** [comment]
Thanks for sapotting this; I thought I'd changed it, but I'll fix it Real Soon Now.

**Comment by mikebrady** [comment]
Thanks for your offer to do the mod. A simpler approach would, IMHO, simply be to fix what's there. Let me try that first.

**Comment by RobDeBagel** [comment]
Thanks, I was about to take a shot at a quick fix, but if you're already on it.. 👍

**Comment by mikebrady** [comment]
Hi there. I just pushed an update on the `development` branch to 3.1d15 with a fix for this. Could you take a look (and a listen) please?

**Comment by faceless2** [comment]
I was the one that supplied the original mono patch - you may recall this issue has come up before. At the time I pitched in with the observation that you have two options for mixing stereo down to mono.

1. Add the two samples: this will potentially clip, but will result in no loss of volume.

2. Add the two samples and divide by two: this will not clip, but the audio will be up to half as quiet depending on the waveform.

As I recall the last time it came up you were going to put in a patch to allow both options for mixing? I still think this is better than just forcing a divide-by-two, as the loss of volume may be unacceptable for some.

**Comment by RobDeBagel** [comment]
Sorry for the delay in responding.

I've tried the patch applied and the clipping is gone. The math looks good to me at a glance.

I'm still hearing some clipping at high volumes but I suspect this lies within the domain of the raspberry-pi's DAC/amplifier.

I agree with the assessment that the /2 and sum is the only way to avoid clipping when -statically- mixing two signals as is being done here. Stereo content is a mix of correlated and uncorrelated signals. There are many ways to combine them together dynamically that would give a more subjectively pleasant result (e.g. two out of phase signals will cancel here), but this method avoids clipping without the overhead of some intelligence in the mixing process.

I consider this fixed.
