### ISSUE TITLE
TuneBlade Timeout

### ISSUE THREAD

**Issue by ettare** [mikebrady/shairport-sync#524]
Hi,

I'm running shairport-sync 3.0.2 and TuneBlade 1.6.3.0 and am getting the 10 minute timeout problem.

Any suggestions for a fix?

**Comment by Warter21** [comment]
do you use TuneBlade free? There is a limitation on it: "*Limitation: Streaming stops every 10 minutes. "

**Comment by ettare** [comment]
Thanks for the quick reply.  Yes I am using the free version, but it’s supposed to work without limitation with shairport - see attached

**Comment by ettare** [comment]
Ok, I think I can see what happened. It seems that if you let TuneBlade discover the receiver automatically, all is well.  However, if you add the receiver manually (which I must have done), you run into the 10 min limitation problem.

Apologies for any confusion, and thanks for a great piece of software.

Regards... Mike
