### ISSUE TITLE
Sync delay

### ISSUE THREAD

**Issue by SirCameron** [mikebrady/shairport-sync#526]
Hi Mike

Thanks for creating Shairport-sync.

I'm having issues regarding the delay/buffer/latency..
I'm running this on a RPI 3 using a Justboom DAC HAT with a Justboom Amp on top (in case that matters). The original installation of Shairport was from the Volumio image.

The RPI is wired into the router (not via wifi).

I've played with all the config settings I can and still am not able to get immediate playback. 
Always at least 1.5 or so seconds behind.
When I do add the audio_backend_latency_offset_in_seconds, audio_backend_buffer_desired_length_in_seconds config options, all I hear is pops and crackles.

I've tried a range of values for both, trying to get something good... but no luck.

Can you or someone in the community help?

Thanks
C

**Comment by mikebrady** [comment]
Hi there. Thanks for the kind words.

The sync delay is a feature, not a bug, I'm afraid. The length of the delay is negotiated between the client and Shairport Sync. The standard delay is two seconds and is a little more for iTunes. 

You can effectively shorten it by changing the offset, but the shorter you make it, the more likely network problems or processor load fluctuations can cause problems. The offset is really for making small adjustments, e.g. to sync your system with audio coming from a TV speaker bar, which can often be delayed for a few tens of milliseconds for audio processing.

So, I'm afraid it's unavoidable.

**Comment by SirCameron** [comment]
Hi Mike

Thanks for the response. I suppose I don't know enough about the protocol to know how the negotiation works.
So there's no way around it, except to offset it?
I notice the change is immediate when changing volume, but not when starting sound, etc.

Regarding Apple TV, tho, the sound is in sync. Same negotiation?

**Comment by mikebrady** [comment]
Yep, the AppleTV does the same negotiation.

I'm afraid there is no way to zero the delay.

**Comment by spin1974** [comment]
Great info, I was just looking into this.  Thanks guys.
