### ISSUE TITLE
ALAC Compile Support Broken [RESOLVED]

### ISSUE THREAD

**Issue by necouchman** [mikebrady/shairport-sync#527]
When trying to install ALAC libraries into a custom directory, the shairport compile fails because it cannot find the includes.  Here's what I've done:
- Compile alac with prefix=/opt/shairport and make install.  Verify all of the packages and libraries are in the expected locations (/opt/shairport/lib64, /opt/shairport/include, etc.).
- Set PKG_CONFIG_PATH=/opt/shairport/lib64/pkgconfig and run configure.  Configure succeeds.
- Try to compile.  Compile fails with:
```
g++ -DHAVE_CONFIG_H -I.  -Wno-multichar -DSYSCONFDIR=\"/opt/shairport/etc\"   -g -O2 -MT apple_alac.o -MD -MP -MF .deps/apple_alac.Tpo -c -o apple_alac.o apple_alac.cpp
apple_alac.cpp:4:35: fatal error: alac/ALACBitUtilities.h: No such file or directory
 #include <alac/ALACBitUtilities.h>
```
- Set ALAC_CFLAGS="-I/opt/shairport/include" and ALAC_LDFLAGS="-L/opt/shairport/lib64", run configure and compile, again.  Compile fails with the same error.
- Set CFLAGS and LDFLAGS to the above values, and, again, configure and make.  Same error.

Seems like the proper include flags are not being pulled in for at least the apple_alac object.

**Comment by mikebrady** [comment]
Hmm, this works for me. There are two extra steps.

First, if you compile `alac` into a custom directory using the directions given in the ALAC repository, you must tell `ldconfig` about the custom directory by entering (in superuser mode):
```
# ldconfig /opt/shairport/lib
```
(This step is unnecessary if you are using standard directories). Then, when you do `$ ldconfig -p | grep alac` You'll see:
```
	libalac.so.0 (libc6,x86-64) => /opt/shairport/lib/libalac.so.0
	libalac.so (libc6,x86-64) => /opt/shairport/lib/libalac.so
```
...indicating that the library can now be found.

Second, to then compile `shairport-sync`, you have to tell `pkg-config` where to find the `.pc` files describing the `libalac` library and include files, e.g.:

```
PKG_CONFIG_PATH=/opt/shairport/lib/pkgconfig ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-apple-alac
```

Incidentally, there was no `/opt/shairport/lib64/` in my experiment, which was on Ubuntu 16.04 LTS:

```
Linux ubuntu 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
