### ISSUE TITLE
Debian Jessie NO AUDIO 

### ISSUE THREAD

**Issue by robertMadonna** [mikebrady/shairport-sync#528]
I sucessfully installed libconfig9_1.4.9-2_armhf.deb for a Debian Jessie system.

I can see the share in the Air tunes list and connect to it, however I get no audio out.

I have checked that shairport-sync is part of the "audio" group.  

My config looks like this:
```
general = {
  name = "BOBS_PLAY";
  output_backend = "pipe";
};

metadata = {
  enabled = "yes";
  include_cover_art = "yes";
  pipe_name = "/tmp/shairport-sync-metadata";
}

sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 20;
}

pipe = {
  name = "/tmp/snapfifo";
  audio_backend_buffer_desired_length = 48000;
}

alsa =
{
  output_device = "hw:0";
  mixer_device = "hw:0";
  mixer_control_name = "PCM";
  // ... other alsa settings
};
```
Any help would me greatly appreciated.

Bob

**Comment by robertMadonna** [comment]
more info:
sudo systemctl list-units -t service --no-legend
.......
shairport-sync.service             loaded active   running       ShairportSync AirTunes receiver

....

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: imxspdif [imx-spdif], device 0: S/PDIF PCM snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

///

sudo speaker-test -Dplug:sysdefault -c2
passes .....

BUT STILL NO AUDIO FROM shairport-sync

**Comment by mikebrady** [comment]
You seem to be outputting to a pipe rather than to an alsa device. Why is that?

**Comment by robertMadonna** [comment]
Thank you for the quick response.

I resolved my problem by doing a completely fresh Debian install. And then installed shair***.deb packages again. I think another process was holding onto the ALSA port (I had mopidy installed on the same machine and once I removed it the ALSA port started working with the shairport-sync) . I also removed the pipe from the config (I blindly copied the config from tutorial I found on line!).

I'm not sure where I referred to "libconfig". Not sure I did. 

Your package is awesome!
Thank you for creating it!

**Comment by robertMadonna** [comment]
One quick question. I don't have volume control on spdif interface. Is there a way to set the volume through software control?

**Comment by mikebrady** [comment]
Yes. If you don't specify a `mixer_control_name` then Shairport Sync will use an internal software attenuator so that when you change volume on iTunes, it'll use the software attenuator to change the output level to the ALSA device – the SPDIF device in your case.

**Comment by robertMadonna** [comment]
Thanks

**Comment by mikebrady** [comment]
I think it's safe to close this now. Feel free to start another issue if necessary.
