### ISSUE TITLE
FYI on mDNS/tinysvcmdns TTL

### ISSUE THREAD

**Issue by philippe44** [mikebrady/shairport-sync#529]
Hi - I use as well a combination of mDNS and tinysvcmDNS for some AirPlay applications I've developped and I ran recently into a problem with a GGMM E5 speaker that it likley using shairport-sync. It took me a while to understand why the Active-Remote was not working and problem was that the player does not  mDNS multicast response with a TTL lower that 255. My responder was setting a TTL of 1, so that was a simple fix. Just wanted to share that with you if it can help

**Comment by mikebrady** [comment]
Thanks for this. I don't actually know if Shairport Sync is being used, TBH.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
