### ISSUE TITLE
How to debug or increase log-level?

### ISSUE THREAD

**Issue by beligum** [mikebrady/shairport-sync#53]
Hi,

I'm trying to run shairport-sync on the Rasberry Pi model B (version 1) on Raspbian, and everything seems to be working fine while installing. Even the sox resampling code compiles file and links in perfectly. I've adapted the `/etc/init.d/shairport-sync` file to use the command from the Readme: `shairport-sync -d -a "Mike's Boombox" -- -d hw:0 -t hardware -c PCM` and I've also tested it manually without the daemon mode. Everything seems to be running fine.

But when I try to stream to the device, both using an Android app and try to stream from my Linux laptop with pulseaudio (haven't got an Apple device to test with), nothing plays. I can't seem to find anything in /var/log/messages, next to a simple `startup`, so I wondered how I could bump up the log/debug level somewhere to figure out what's up?

Any help?

b.

**Comment by mikebrady** [comment]
Hi there. Thanks for your interest in Shairport Sync. There is a walkthrough of turning on verbosity at https://github.com/mikebrady/shairport-sync/issues/44#issuecomment-73577716 by adding the `-v` option. `-vv` will give you a bit more, and `-vvv` still more – probably too much. I hope it is useful.

**Comment by beligum** [comment]
Thanks, I'll check.

**Comment by cu6apum** [comment]
Hey guys.
Looks dumb, but -d option does TWO things simultaneously!!! If I specify an output device (-d hw1) the program instantly daemonizes (-d)!!!

That's a bug I've never seen anywhere yet. :D

**Comment by mikebrady** [comment]
Well, not exactly :). If you use the `-d` option before the `--` option, it daemonises, but if you use it after the `--` option, it is passed on the the backend and, for example, is used by the `alsa` back end to specify the device name. Would that explain what you see?
