### ISSUE TITLE
Question: Virtual Airplay Zones?

### ISSUE THREAD

**Issue by olsch01** [mikebrady/shairport-sync#530]
Hi all - love shairport-sync and have been using it for a long time!

I recently consolidated a few different RPI's into a single RPI with several USB DACs to drive 5 separate airplay zones and it's working terrific!  Now I want to go one step further if possible.  I have these 5 discrete zones, let's call them the following:
Kitchen
Basement
ScreenPorch
Pool
Garage

Is there a way to create other "virtual" airplay zones that would output to several audio cards at once?  For example, I'd like to set up these zones:
1) "Outdoors" where it would play to both ScreenPorch and Pool.
2) "All Zones" where it would play to everything

Since iOS devices can only output to one airplay target at a time (Unlike AppleTV 1 and iTunes on the PC/MAC) - this would essentially work around that limitation when we want a single audio source to play in multiple spots.

Any thoughts on this?   Thanks!

**Comment by roblan** [comment]
I think that You can achieve something like that using forked-daapd and shairport-sync.
See "pipes" section in https://github.com/ejurgensen/forked-daapd#library

**Comment by roblan** [comment]
https://github.com/mikebrady/shairport-sync/issues/384 - somebody managed to do this using some node packages

**Comment by mikebrady** [comment]
This is a tough one, I'm afraid. It would not be high on the list of priorities right now.

**Comment by noelhibbard** [comment]
@olsch01 Using ALSA you can bust up a single multi channel soundcard into multiple outputs in any way you want. A 7.1 channel card has 8 channels so you could do 4 rooms with stereo in each room. You could also use ALSA to group two rooms into one. Then create an instance of shairport-sync for each output. Each shairport-sync instance needs to run on it's own port and have it's own name. Here is sample asound.conf that should give you some hints:
```
pcm.usbsound_1 {
    type dmix
    ipc_key 673138
    slave {
        pcm "hw:1,0"
        rate 44100
        channels 8
        period_time 0
        period_size 1024
        buffer_size 4096        
    }
    bindings {
        0 0
        1 1
        2 2
        3 3
        4 4
        5 5
        6 6
        7 7
    }
}

pcm.livingroom {
    type route
    slave.pcm usbsound_1
    slave.channels 8
    ttable.0.0 1
    ttable.1.1 1
}

pcm.porch {
    type route
    slave.pcm usbsound_1
    slave.channels 8
    ttable.0.2 1
    ttable.1.3 1
}

pcm.garage {
    type route
    slave.pcm usbsound_1
    slave.channels 8
    ttable.0.4 1
    ttable.1.5 1
}

pcm.bathroom {
    type route
    slave.pcm usbsound_1
    slave.channels 8
    ttable.0.6 1
    ttable.1.7 1
}

pcm.inside {
    type route
    slave.pcm usbsound_1
    slave.channels 8
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.6 1
    ttable.1.7 1
}

pcm.outside {
    type route
    slave.pcm usbsound_1
    slave.channels 8
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
}
```

You can see there are 6 zones here. Garage, Porch, Bathroom, Livingroom, Outside and Inside. Outside includes Garage and Porch and Inside includes Bathroom and Livingroom.

But, I personally wanted something more dynamic where I could select exactly what zones to output to and have the ability to change the volume of each output. So I wrote node-airplayhub which was already pointed out above. You would still need to create an ALSA config to bust up your sound cards into zones and you would still need to have multiple instances of shairport-sync for each zone. But grouping them up would be done via node-airplayhub.

https://github.com/noelhibbard/node-airplayhub

From my experiance node-airplayhub is CPU intensive so I seriously doubt get it to run on the RPi. You could use RPi for all your shairport-sync instances but then run node-airplayhub on another machine somewhere else on your network. but then you may run into bandwidth problems. I have all my shairport-sync instances and node-airplayhub running on a single server so the only network I/O I have is a single stream from my iPhone. I am running it on an Intel i5.

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
