### ISSUE TITLE
No Airplay

### ISSUE THREAD

**Issue by Nijs0478** [mikebrady/shairport-sync#531]
Hello, i tried a lot of things and visited a lot of sites to get het Raspberry Pi 3 to Airplay. Some i got to work, but didnt start on boot and others just wouldnt start.

Started with a new Rasbian Jessie installation
Enabled SSH
Insert the following code in order (got it from https://github.com/mikebrady/shairport-sync):
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential git xmltoman
sudo apt-get install autoconf automake libtool libdaemon-dev libasound2-dev libpopt-dev libconfig-dev
sudo apt-get install avahi-daemon libavahi-client-dev
sudo apt-get install libssl-dev
sudo apt-get install libmbedtls-dev
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync
autoreconf -i -f
ps aux | grep systemd | grep -v grep
./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemd
make
sudo make install
sudo systemctl enable shairport-sync
sudo reboot
```
After reboot, no Airplay. What do i do wrong? Can someone help me with this?

Raspberry Pi is now connected with HDMI to my television and a USB keyboard is connected.

**Comment by mikebrady** [comment]
Thanks for the post, which I edited a little bit for format.

It seems as if you did all the building correctly, but you haven't given any information about how you configured it. If you didn't configure it, then it would have assumed default values.

So, let's see how far along it got. Could you enter the following commands and post the responses please:
```
shairport-sync -V
```
Notice that it's an uppercase "V". You should get a response giving version information that will look something like this:
```
3.0.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc
```
Assuming you get this, enter the following command, noting it's a lowercase "v" this time:
```
shairport-sync -v
```
If you could post the response, that would be great.

**Comment by mikebrady** [comment]
Another quick question: when you use iTunes, can you "see" the AirPlay service on your network?

**Comment by Nijs0478** [comment]
Hi Mike, 

Thanks for your reply.

I didn't configure because i didn't get the Airplay to work yet. As soon as i get the Airplay to work i need to configure the output.

Response after shairport-sync -V:
3.0.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc

Response after shairport-sync -v:
Looking for the configuration file "/etc/shairport-sync.conf".
Output device name is "default".
Version: "3.0.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "RaspberryPi".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'E941AB0A40B3@RaspberryPi' successfully added.

We i'm on my iPhone and swipe-up, i see the Airplay menu, but it can't find any Airplay device. Also in Spotify and YouTube the only device i can play from is the iPhone itself and not the RaspberryPi.

**Comment by mikebrady** [comment]
Thanks – that's encouraging. Your post reveals that Shairport Sync was successfully compiled and installed. Also, it indicates that it starts up cleanly and advertises itself as "RaspberryPi".

It also looks like it is outputting the the default output, which is either the headphone jack or the HDMI audio output. You should use `alsamixer` to set the volume high enough on the default device.

Now, you really need to find the service on the network. You must be on the same network as the Pi. For instance, on my home network, I have a Pi connected to an access point via Ethernet and my phone connected wirelessly to the same access point. You might have to turn off firewalls – see the TROUBLESHOOTING page.

Spotify and YouTube don't always look different when there is an AirPlay device on the network, but Apple's own Music app does, a bit: When you're playing a track, at the bottom centre there is an icon made from an equilateral-ish triangle pointing upwards with three concentric circles centred on its apex. If you touch that, the list of AirPlay speakers will appear. 

So, when Shairport Sync is running from the command line, as you did above with the "-v" option, have a look on your iPhone to see if you can find the "RaspberryPi" AirPlay service.

Another thing is to use the "Discovery" app for you iPhone to see if the mDNS advertising for the AirPlay service is reaching your phone – look for entries for the "Remote Audio Output Protocol".

**Comment by Nijs0478** [comment]
Thanks for the reply. As soon i enter `shairport-sync -v` in PuTTY the Airplay service is visible in Spotify, YouTube and the iOS Music app. Unfortunately i have to enter this code. 

In your tutorial you say enter `sudo systemctl enable shairport-sync` to enable Shairport-Sync on boot, but that doesn't work. So when the Pi needs to reboot, i always have to connect a keyboard and screen or use PuTTY to insert the code.

How can i fix this?

**Comment by Nijs0478** [comment]
Thanks for your reply. I thought i already did this, but i entered the following commands:

`getent group shairport-sync &>/dev/null || sudo groupadd -r shairport-sync >/dev/null`
`getent passwd shairport-sync &> /dev/null || sudo useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null`

It looked like i got it to work. After a reboot (`sudo reboot` or manually restart the pi), the Airplay service started automatically.

I also tried your other comment. I changed the shairport conf with `sudo nano /etc/shairport-sync.conf` and deleted the // and changed the log_verbosity to 1. Saved and Exit.

After this i entered `sudo systemctl start shairport-sync` and `sudo journalctl -n 100`. But now it doesn't work anymore. I tried `sudo reboot`, but no Airplay visible. I dont know it was the change of the log_verbosity or the command `sudo systemctl start shairport-sync` or `sudo journalctl -n 100` why it doesnt work anymore.

Any tips?

**Comment by mikebrady** [comment]
Getting close to working, I think! It seems like you may have made a mistake with the configuration file, but that's a guess.

The `sudo journalctl -n 100` should print the last 100 lines of the log file. Can you see anything related to shairport-sync there? If not, maybe try something like `sudo journalctl | grep -i shairport` to list any relevant lines in the log – you might get a lot; check their dates and times.

**Comment by Nijs0478** [comment]
The line in the conf fil look like this:
`log_verbosity = 1; // "0" means no debug verbosity, "3" is most verbose.` (no // in front of it)

I entered `sudo journalctl | grep -i shairport` and i cant see anything strange (i deleted the router advertisement lines), maybe you cabn see something:
`Jun 01 17:53:28 RaspberryPi sshd[24778]: Accepted password for pi from 192.168.178.166 port 54762 ssh2
Jun 01 17:53:28 RaspberryPi sshd[24778]: pam_unix(sshd:session): session opened for user pi by (uid=0)
Jun 01 17:53:28 RaspberryPi systemd[1]: Starting Session c3 of user pi.
Jun 01 17:53:28 RaspberryPi systemd-logind[443]: New session c3 of user pi.
Jun 01 17:53:28 RaspberryPi systemd[1]: Started Session c3 of user pi.
Jun 01 17:54:09 RaspberryPi sudo[24891]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/nano /etc/shairport-sync.conf
Jun 01 17:54:09 RaspberryPi sudo[24891]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Jun 01 17:56:53 RaspberryPi sudo[24891]: pam_unix(sudo:session): session closed for user root
Jun 01 17:56:56 RaspberryPi sudo[25243]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl -n 100
Jun 01 17:56:56 RaspberryPi sudo[25243]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Jun 01 17:57:49 RaspberryPi sshd[24778]: pam_unix(sshd:session): session closed for user pi
Jun 01 17:57:49 RaspberryPi sudo[25243]: pam_unix(sudo:session): session closed for user root
Jun 01 17:57:49 RaspberryPi systemd-logind[443]: Removed session c3.
Jun 01 17:58:05 RaspberryPi sshd[25432]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.178.166  user=pi
Jun 01 17:58:07 RaspberryPi sshd[25432]: Failed password for pi from 192.168.178.166 port 54788 ssh2
Jun 01 17:58:12 RaspberryPi sshd[25432]: Failed password for pi from 192.168.178.166 port 54788 ssh2
Jun 01 17:58:16 RaspberryPi sshd[25432]: Accepted password for pi from 192.168.178.166 port 54788 ssh2
Jun 01 17:58:16 RaspberryPi sshd[25432]: pam_unix(sshd:session): session opened for user pi by (uid=0)
Jun 01 17:58:16 RaspberryPi systemd[1]: Starting Session c4 of user pi.
Jun 01 17:58:16 RaspberryPi systemd-logind[443]: New session c4 of user pi.
Jun 01 17:58:16 RaspberryPi systemd[1]: Started Session c4 of user pi.
Jun 01 17:58:31 RaspberryPi sudo[25546]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl -n 100
Jun 01 17:58:31 RaspberryPi sudo[25546]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
`

After my last post the Airplay service doesn't show anymore. Maybe i can try to change the conf file back to what it was?Can i enter a command to check what it is doing?

**Comment by Nijs0478** [comment]
After some more reboots, it worked again. I tried changing the conf file, and found out that the Airplay service isn't starting after 1 reboot. After the second reboot the Airplay was visible again.

**Comment by mikebrady** [comment]
Apologies for the silent – it's a busy time at work. When I do the  command, I get:
```
pi@ raspberrypi:~ $ sudo journalctl | grep -i shairport
May 29 12:17:14 raspberrypi systemd[1]: Starting ShairportSync AirTunes receiver...
May 29 12:17:15 raspberrypi systemd[1]: Started ShairportSync AirTunes receiver.
May 29 12:17:15 raspberrypi shairport-sync[772]: Successful Startup
pi@raspberrypi:~ $ sudo journalctl | grep -i shairport
```
(The system was rebooted a few days ago.)

Your earlier idea of using a fresh configuration file is probably a good one – in fact, you could probably just copy the sample configuration:
```
sudo cp /etc/shairport-sync.conf.sample /etc/shairport-sync.conf
```
but just be careful – this will overwrite `/etc/shairport-sync.conf` without further warning.

**Comment by Nijs0478** [comment]
No problem, your helping either way.

I seem to have a love/hate relationship with the shairport-sync. First everything works and i try some things in the conf file, like a password and now it doesnt work anymore. I copied the sample file so all configurations are default again. Also tried to play music from USB, but didnt work.

When i enter `shairport-sync -v` i get the following:

`Looking for the configuration file "/etc/shairport-sync.conf".`
`Output device name is "default".`
`Version: "3.0.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc"`
`statistics_requester status is 0.`
`daemon status is 0.`
`rtsp listening port is 5000.`
`udp base port is 6001.`
`udp port range is 100.`
`Shairport Sync player name is "RaspberryPi".`
`Audio Output name is "(null)".`
`on-start action is "(null)".`
`on-stop action is "(null)".`
`wait-cmd status is 0.`
`mdns backend "(null)".`
`stuffing option is "0" (0-basic, 1-soxr).`
`resync time is 0.050000 seconds.`
`resync time is 0.050000 seconds.`
`allow a session to be interrupted: 0.`
`busy timeout time is 120.`
`drift tolerance is 0.001995 seconds.`
`password is "(null)".`
`ignore_volume_control is 0.`
`volume_max_db is not set`
`playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_righ                                                                                        t).`
`disable_synchronization is 0.`
`use_mmap_if_available is 1.`
`output_rate is 44100.`
`output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7                                                                                        -S32).`
`audio backend desired buffer length is 0.150000 seconds.`
`audio backend latency offset is 0.000000 seconds.`
`volume range in dB (zero means use the range specified by the mixer): 0.`
`zeroconf regtype is "_raop._tcp".`
`decoders_supported field is 1.`
`use_apple_decoder is 0.`
`no special mdns service interface was requested.`
`configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-s                                                                                    ync.conf".`
`metdata enabled is 0.`
`metadata pipename is "(null)".`
`metadata socket address is "(null)" port 0.`
`metadata socket packet size is "500".`
`get-coverart is 0.`
`Successful Startup`
`Unable to listen on IPv4 port 5000. The error is: "Address already in use".`
`Unable to listen on IPv6 port 5000. The error is: "Address already in use".`
`Could not establish a service on port 5000 -- program terminating. Is another in                                                                                        stance of Shairport Sync running on this device?`
`Request to shut down all rtsp conversation threads`


I'm thinking of starting all over and format the SD, but if i know what went wrong, i don't do the same thing again next time.

**Comment by mikebrady** [comment]
The last few lines seem to show that Shairport Sync was already running, presumably from boot-up.

I think the key thing is to try exactly one change at a time, establish it's working and then move on. If you make too many changes, it becomes almost impossible to find out what might be causing problems.

**Comment by Nijs0478** [comment]
I'm testing the changes in the configuration and Airplay service after reboot.

In your manual the commands:
`$ getent group shairport-sync &>/dev/null || sudo groupadd -r shairport-sync >/dev/null`
`$ getent passwd shairport-sync &> /dev/null || sudo useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null`
should be entered between `make` and `sudo make install`

If i enter the commands between `make` and `sudo make install`, it doesn't work. If i enter the commands later on, it works.

Also i found out that sudo reboot doesn't alway do the trick. I changed the hostname in the shairport-sync.conf and after several sudo reboots the Airplay didn't start. After i manually reboot the device by taking out the powercable, the Airplay service did start.

I hope this helps you too.

**Comment by mikebrady** [comment]
Many thanks. You make a fair point regarding the order of things in the text. Actually, in the `development` branch, I've already modified the text and the operation of `sudo make install` so that it will execute those commands automatically if needed.

Regarding your last point, about a hard reset being needed, I have not found that to be the case, so it might need a bit of investigation.

**Comment by johncam11** [comment]
I'm having a similar experience regarding the hard reset with a similar fresh install as described above.  Airplay did not show up on devices until a hard reset was done (after trying several reboots).  I have also noticed that changes to shairport-sync.conf were having some issues.  

For example, I was having a substantial delay when using a USB sound dongle in a RPi3, so I removed it and copied over the shairport-sync.conf.sample to the conf file, switching to the built in 3.5 jack (using the new driver setting in config.txt).  Once I did that, I was able to connect to the default %H name on my devices with no sync issue!

Then, I changed only the "name=" field.  After a hard reboot, both the %H and new name were showing up -- and both were working. (oddly, the new name connection was slightly off sync.)  I went back to the %H name and am going to let things sit for a bit.

**Comment by mikebrady** [comment]
Is it okay to close this issue?

**Comment by Nijs0478** [comment]
Yeah sure!

**Comment by mikebrady** [comment]
Thanks. Feel free to reopen it if necessary.
