### ISSUE TITLE
Visible in iTunes but not iOS

### ISSUE THREAD

**Issue by ghoover** [mikebrady/shairport-sync#532]
I successfully installed Shairport-sync on a Raspberry Pi Zero.  I can see (and stream) to Shairport from iTunes (on Mac) but not from an iPhone on the same network.  

The funny thing is the Bonjour advertisement I see for Shairport has two IP addresses.  The first is the static IP configured for the Raspberry Pi.  The 2nd is a DHCP address that doesn't show up in my router's client list.  Other AirPlay devices (like my Apple-TV) only show a single IP address.  

From iPhone app:

```
CentralAudio.local:5000
10.0.1.40
10.0.1.225
fe80::ba27::ebff::fe99::bc33%en0

TXT RECORD
am = ShairportSync
ch = 2
cn = 0,1
da = true
ek = 1
et = 0,1
fv = 76400.10
pw = false
sf = 0x4
sr = 44100
ss = 16
sv = false
tp = TCP,UDP
txtvers = 1
vn = 65537
vs = 105.1
```

avahi-browse shows the following:

```
+  wlan0 IPv6 D4D4B8E98489@CentralAudio                     AirTunes Remote Audio local
+  wlan0 IPv4 D4D4B8E98489@CentralAudio                     AirTunes Remote Audio local

+  wlan0 IPv6 CentralAudio [b8:27:eb:99:bc:33]              Workstation          local
+  wlan0 IPv4 CentralAudio [b8:27:eb:99:bc:33]              Workstation          local

=  wlan0 IPv6 D4D4B8E98489@CentralAudio                     AirTunes Remote Audio local
   hostname = [CentralAudio.local]
   address = [fe80::ba27:ebff:fe99:bc33]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "ch=2" "cn=0,1" "ek=1" "et=0,1" "sv=false" "da=true" "sr=44100" "ss=16" "vn=65537" "tp=TCP,UDP" "vs=105.1" "am=ShairportSync" "fv=76400.10" "sf=0x4"]

=  wlan0 IPv4 D4D4B8E98489@CentralAudio                     AirTunes Remote Audio local
   hostname = [CentralAudio.local]
   address = [10.0.1.225]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "ch=2" "cn=0,1" "ek=1" "et=0,1" "sv=false" "da=true" "sr=44100" "ss=16" "vn=65537" "tp=TCP,UDP" "vs=105.1" "am=ShairportSync" "fv=76400.10" "sf=0x4"]

=  wlan0 IPv4 CentralAudio [b8:27:eb:99:bc:33]              Workstation          local
   hostname = [CentralAudio.local]
   address = [10.0.1.225]
   port = [9]
   txt = []

=  wlan0 IPv6 CentralAudio [b8:27:eb:99:bc:33]              Workstation          local
   hostname = [CentralAudio.local]
   address = [fe80::ba27:ebff:fe99:bc33]
   port = [9]
   txt = []
```

ifconfig shows:
```
wlan0     Link encap:Ethernet  HWaddr b8:27:eb:99:bc:33  
          inet addr:10.0.1.40  Bcast:10.0.1.255  Mask:255.255.255.0
          inet6 addr: fe80::ba27:ebff:fe99:bc33/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:177835 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4283 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:189916813 (181.1 MiB)  TX bytes:747205 (729.6 KiB)
```

**Comment by ghoover** [comment]
I figured out the 2nd IP address issue but the iPhone still doesn't show the AirPlay device.  Discovery shows the same as above but with only the single IP address now.

**Comment by mikebrady** [comment]
Thanks for the post. Is the Mac connecting over Ethernet? (The phone is over wifi, of course.)

**Comment by ghoover** [comment]
All are wifi – same network.

**Comment by mikebrady** [comment]
Thanks. It looks like the Zeroconf/Bonjour advertisements are/were confused – `avahi-browse` looks like it was advertising 10.0.1.225 whereas the `wlan0` address is 10.0.1.40. These values can be cached in various places on the network and it can take a while for the new values to propagate around. So it would be worth trying again after a awhile.

BTW – and please excuse me for asking the dumb question – but are you certain you can't see the service in iOS (see [here](http://www.imore.com/airplay))?

**Comment by ghoover** [comment]
Certainly not a dumb question.  I'm seeing it in iOS now.  Thanks for your support.

**Comment by mikebrady** [comment]
Great!

**Comment by wjrochester** [comment]
I am having the same issue as OP where my Mac can send audio to shairport but my iPhone can't. My pi is on wifi only (no ethernet). I don't understand the resolution here. What info can I post for a remedy? Here's my ifconfig from my Mac 
`ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en3: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22 
	inet6 fe80::aede:48ff:fe00:1122%en3 prefixlen 64 scopeid 0x4 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
ap1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 3a:f9:d3:70:b1:63 
	media: autoselect
	status: inactive
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 38:f9:d3:70:b1:63 
	inet6 fe80::14c2:f375:4150:b88b%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.1.123 netmask 0xffffff00 broadcast 192.168.1.255
	inet6 2600:8800:7b80:942:a4:228d:19ca:6f6b prefixlen 64 autoconf secured 
	inet6 2600:8800:7b80:942:b8fc:33ab:4b1c:a3ac prefixlen 64 deprecated autoconf temporary 
	inet6 2600:8800:7b80:942:e006:9f85:221f:abbd prefixlen 64 deprecated autoconf temporary 
	inet6 2600:8800:7b80:942:19c9:754f:e21a:fc2e prefixlen 64 deprecated autoconf temporary 
	inet6 2600:8800:7b80:942:f828:f73a:7176:23e9 prefixlen 64 deprecated autoconf temporary 
	inet6 2600:8800:7b80:942:50de:85ab:ff5e:6f56 prefixlen 64 deprecated autoconf temporary 
	inet6 2600:8800:7b80:942:e440:ec6b:651b:67ec prefixlen 64 deprecated autoconf temporary 
	inet6 2600:8800:7b80:942:fc77:9ac0:7f1a:7c56 prefixlen 64 autoconf temporary 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:23:e8:48:58:01 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:23:e8:48:58:00 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:23:e8:48:58:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 8 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 0a:f9:d3:70:b1:63 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 5a:e4:52:75:8e:d7 
	inet6 fe80::58e4:52ff:fe75:8ed7%awdl0 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 5a:e4:52:75:8e:d7 
	inet6 fe80::58e4:52ff:fe75:8ed7%llw0 prefixlen 64 scopeid 0xd 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::eed4:99bb:ac6a:6343%utun0 prefixlen 64 scopeid 0xf 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::eb96:ba5c:fcc3:d76e%utun1 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::c69d:a96a:ff9f:7334%utun2 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::98c4:b8f3:ce10:d213%utun3 prefixlen 64 scopeid 0x12 
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::67d:d34:3eb3:b0c1%utun4 prefixlen 64 scopeid 0x13 
	nd6 options=201<PERFORMNUD,DAD>
utun5: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::dc32:cce5:3518:bade%utun5 prefixlen 64 scopeid 0x14 
	nd6 options=201<PERFORMNUD,DAD>
en6: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=6407<RXCSUM,TXCSUM,VLAN_MTU,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 60:6d:3c:43:29:c0 
	inet6 fe80::1cd3:a863:37b4:b0bb%en6 prefixlen 64 secured scopeid 0x7 
	inet 169.254.214.12 netmask 0xffff0000 broadcast 169.254.255.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
bridge100: flags=8a63<UP,BROADCAST,SMART,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 3a:f9:d3:07:78:64 
	inet 192.168.2.1 netmask 0xffffff00 broadcast 192.168.2.255
	inet6 fe80::14ef:8b07:eb94:e73f%bridge100 prefixlen 64 secured scopeid 0xe 
	inet6 fd5d:d90e:55de:eada:1043:df66:3f20:d088 prefixlen 64 autoconf secured 
	inet6 fd5d:d90e:55de:eada:7123:e5df:a6ac:a4f prefixlen 64 deprecated autoconf temporary 
	inet6 fd5d:d90e:55de:eada:bc43:1701:fe9f:3bd8 prefixlen 64 deprecated autoconf temporary 
	inet6 fd5d:d90e:55de:eada:d412:75a1:fef0:d7a2 prefixlen 64 autoconf temporary 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en6 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 7 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en7: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether be:9f:ef:11:af:8d 
	media: autoselect <full-duplex>
	status: inactive`

**Comment by mikebrady** [comment]
Thanks for the post. (I edited it for format.)

Actually it looks as if your Pi has an active ethernet connection (`eth0`). What I notice about the WiFi connection (`wlan0`) is that it is up but has neither an IPv6 nor an IPv4 connection. Could you clarify the situation please?

**Comment by wjrochester** [comment]
Well that was foolish of me. I had an ethernet connection to my Mac just for file transfers, I didn't realize that the "share internet connection" option was enabled. Disconnected ethernet and the machine connected back up to my wifi. Airplay is now available to the pi on iPhone, issue resolved.
As an aside, I thought Shairport can use any local network connection to advertise. So even though it was connected to ethernet it had network access since my Mac had a wifi connection and the connection was being shared via ethernet.

**Comment by mikebrady** [comment]
It’s good that the issue is resolved. If I understand your networking setup correctly, the Mac would share the WiFi internet connection to its Ethernet port, but it would be acting as a router, so the Pi would be on a different network to the WiFi network. Shairport Sync is always confined to it’s own local network, so that could account for what you experienced.
