### ISSUE TITLE
Interfacing shairport-sync with sound card through USB.

### ISSUE THREAD

**Issue by mohitawasthi9** [mikebrady/shairport-sync#536]
Hi,

I have to use shairport-sync on BeagleBone Black. I'm using TI provided Linux kernel and BSP. I want to use external sound card that will use USB2.0 to get audio output from shairport sync.

**Query** :
Does shairport-sync by default support USB driver to any sound card ? or do I need to write own USB driver for interfacing shairport-sync with sound card ? 

TIA
Mohit

**Comment by mikebrady** [comment]
Thanks for the post. Yes, Shairport Sync should support any sound card, including USB, so long as it's visible in the ALSA subsystem. I don't know about the TI-provided Linux, but most full-sized Linuxes have all the drivers and subsystems installed. If you install the alsa utilities, they include `alsamixer` and `aplay` and you can explore what it there and what is visible. If it's visible, and if it can do 44100/16/stereo, Shairport Sync should be able to use it.
