### ISSUE TITLE
Multidevice Input

### ISSUE THREAD

**Issue by syl666** [mikebrady/shairport-sync#538]
Hi,

I see a lot about multiroom output, but what I'm looking for is the opposite.  Example, if I had 3 devices (A, B and C) and they all sent a song to shairport-sync can they be queued? Similar to a playlist, so that there isn't any interruption to the current song playing from Device A.  Once the song has finished from Device A, the song from Device B can start playing..and so on.  I've looked into MusicBox and Mopidy, but I dont want to use any of these because I feel they aren't simple enough.  I like the idea of just being able to send something to the Pi and it can take care of it from there. 

Is there a way I can get shairport-sync to allow mod like this?  If so, where is the best place to start?

Thanks for your help :)

**Comment by mikebrady** [comment]
Thanks fore the interesting post. What you're looking for sound a bit like an oldstyle juke box. It would take a great deal of work to get Shairport Sync to work like that, I'm afraid. Basically you would have to run a number of instances of it that would receive and store music and then play them sequentially. Of course, it could be done, but it would take a heck of a lot of work.

**Comment by olsch01** [comment]
Interestingly enough I was reading that IOS 11 will introduce a "Shared Up Next" feature that will allow just this.  Haven't seen it in action yet in the beta but looks promising - especially for parties, get togethers, etc and can work with airplay.

**Comment by mikebrady** [comment]
Not quite the same thing, but if you allow session interruption on recent (development) versions of Shairport Sync, it can be a lot of fun with different people playing to the same Shairpor Sync device from their phones, rapidly switching from one device  to another. Later versions are more stable...

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
