### ISSUE TITLE
No shutdown on "failed to attach mixer"

### ISSUE THREAD

**Issue by f3flight** [mikebrady/shairport-sync#539]
I start shairport-sync under systemd, and sometimes I don't have the audio interface attached at that time - what happens is that shairport-sync reports "failed to attach mixer" but it keeps running, and there is no visibility on systemd side that there was an error in the service. I think it makes sense to shutdown the server if it failed to initialize properly. Then systemd may attempt to restart it later.

Example:

```
[root@blackhole ~]# systemctl status shairport-sync
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/usr/lib/systemd/system/shairport-sync.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-06-09 09:19:40 PDT; 5 days ago
 Main PID: 497 (shairport-sync)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/shairport-sync.service
           └─497 /usr/bin/shairport-sync

Jun 09 09:19:40 blackhole systemd[1]: Started ShairportSync AirTunes receiver.
Jun 09 09:19:41 blackhole shairport-sync[497]: Failed to attach mixer
```
Service is still running, but not actually working. I'm puzzled why that would be the case though since in the code I see that "die" function is called, so looks like it's broken somehow?

version I'm using right now is 3.0.2-2, was the same on 2.x

Same (of course) issue when starting directly from shell:
```
[root@blackhole ~]# /usr/bin/shairport-sync
Failed to attach mixer

```
Process does not exit, keeps running.

**Comment by f3flight** [comment]
version I'm using right now is 3.0.2-2

**Comment by mikebrady** [comment]
Thanks. I'll have a look!

**Comment by mikebrady** [comment]
There is an issue there alright – an infinite wait for a mutex to unlock before exiting... Due to work commitments, it'll probably take a few days to fix.

**Comment by mikebrady** [comment]
I've pushed an update just now on the `development` branch. Would you be kind enough to test it please?

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
