### ISSUE TITLE
less timeout when not cleanly disconnecting

### ISSUE THREAD

**Issue by mantheman** [mikebrady/shairport-sync#54]
I once turned off my ipad when it was connected to shairport-sync. Turned out that shairport-sync hogs the audio output for a couple of minutes, before it was possible to reconnect  (even with the -t option set to 0). Maybe it is an idea to have a shorter timeout. Maybe 10-15 seconds for these rare occurances.

I can atleast imagine one scenario with -t 0 (aka party mode): The person playing, is leaving the party, music stops for several minutes, nobody can connect to shairport-sync, causing mucho problemo and panic :D

Edit: come to think of it, with -t 0, one would expect shairport-sync to accept new connections anyways, even if the previous connection wasnt cleanly disconnectes

**Comment by mikebrady** [comment]
It's nice to see Shairport Sync getting out a bit, going to parties and such :) Yes, with `-t 0`, it should accept new connections, so I wonder if there might be some other explanation. I don't know what happened in the situation you describe, to be honest; however, if you had one level of debug verbosity turned on, you could see exactly when Shairport Sync ends a play session. I have noticed that some apps – TuneIn Radio Pro for example – hold on to the session much longer than you might think, sometime long after audio has stopped. Similarly, if you have selected Shairport Sync for audio output and Facebook is active, it may start a silent play session. Weird. AirFoil on Mac and on Windows also holds a play session open all the time too. It could be a bug in Shairport Sync, of course, so if you can get it to happen reliably, I'd love to take a look at it.

**Comment by mantheman** [comment]
I can visually see that shairport hogs the dac, because my usb dac has a display that shows the samplerate whenever its playing, and when its not playing it displays "- - -". It's not because of some random facebook or tunein audio playing, silent audio, or some program hold on to the session. I have zero problems with that, and as such everything works absolutely stellar 100% of the time. 

I've only experienced the hog, when i hardbooted my ipad. (Press and hold menu and power at the same time for several seconds). In other words, i was connected to shairport-sync with my ipad, im playing a song from spotify, i turn off my ipad by holding menu and power, result: my ipad is off, there is obviously no sound, but my usb dac display still says "44" and I can't take control of shairport sync with my iphone until several minutes later. (As expected I also cant use the audio output from MPD or another program while the output is hogged)

I'll try it some more, and be back with more info.

**Comment by mikebrady** [comment]
Thanks. And in this situation, would the -t option be set to 0?

**Comment by mantheman** [comment]
yes of course. everyday is a party.

**Comment by mikebrady** [comment]
Splendid! I'll play around, see if I've missed something.

**Comment by mikebrady** [comment]
Hi there. I've done some updates to this and replaced the `-t` option with two independent settings, one for disabling the busy signal and one for setting the timeout. They are in the (new) configuration file in the development version.

**Comment by mikebrady** [comment]
These configuration file settings are now in the stable master version.
I'm going to close this – feel free to reopen if there are developments.
