### ISSUE TITLE
Shairport-Sync with two USB Soundcards for Multiroom Audio

### ISSUE THREAD

**Issue by shairportMulti** [mikebrady/shairport-sync#540]
Hi,

this is not an issue of shairport-sync, but a wrong configuration an my side. Maybe anybody can help me here.

My setup is:
Raspberry 2 with eight running shairport-sync instances
two USB 7.1 soundcards for 8 stereo channels

With one soundcard with 4 stereo channels my setup is working perfectly with following configuration:
[asound.conf.8Kanal.txt](https://github.com/mikebrady/shairport-sync/files/1085518/asound.conf.8Kanal.txt)

[shairport-syncEGWOHN.conf.txt](https://github.com/mikebrady/shairport-sync/files/1085519/shairport-syncEGWOHN.conf.txt)

But when i try to configure asound.conf for 8 Stereo channels i get errors and 100% load of the shairport process
[asound.conf.16Kanal.txt](https://github.com/mikebrady/shairport-sync/files/1085527/asound.conf.16Kanal.txt)
 
For sure my asound.conf for 8 Stereo channels is wrong, but i'am not familar with alsa and therefor maybe someone can help.
[daemon.log.txt](https://github.com/mikebrady/shairport-sync/files/1085556/daemon.log.txt)

**Comment by mikebrady** [comment]
Wow, that is just fantastic! Can you share the configuration file(s) please?

**Comment by shairportMulti** [comment]
Which configuration file(s) do you mean? All eight shairport-sync*.conf?
but at the moment its not working with two usb soundcards, just for one (with four instances, as i explained in issue #343

**Comment by mikebrady** [comment]
Thanks. I noticed this in the log file: 
```
The alsa buffer is to small (3763 bytes) to accommodate the desired backend buffer length (11025) you have chosen.
```
and I was trying to understand it. Maybe you don't actually alter the backend buffer length anyway?

**Comment by shairportMulti** [comment]
I checked it already and this entry is also in my working configuration, so i don't think that this is the reason (but i will check that again later)

**Comment by mikebrady** [comment]
Overall I'm really impressed that this runs with 4 stereo channels. I would be curious about whether the system is just being overwhelmed by eight stereo channels.

On the face of it, the traffic through the system should be roughly 150 kB/sec to the alsa output for each stereo channel plus about half of that on the network port, so about 225 kB/sec of I/O per stereo channel. Eight channels would make that 1.8 MB/sec, i.e. about 14.5 Mb/sec. Add in some overhead and you might say about 20 Mb/sec.

I wonder if the Pi system can handle this rate of throughput. A possible way to find out would be to set up the 8-channel configuration but to drive initially 4 channels only, then 5, then 6, then 7 and finally 8 channels and see if it breaks down at some intermediate point above 4 but below 8. If it did break down in that way, it might suggest that it's not the configuration that is a problem but instead is a capacity or throughput problem. 

Just a thought.

**Comment by shairportMulti** [comment]
First of all, thx for your input. 
With eight stereo channels i even can't connect one shairport-sync instance because of the errors in daemon.log. With four stereo channels i can connect. So my problem is about the alsa configuration of my two USB cards.

**Comment by mikebrady** [comment]
Thanks for the reply. Okay, so could you set the log verbosity back to 1 and record all the log activity for all the shairport sync instances starting up (verbosity 2 and 3 it too chatty to be able to see much).

**Comment by shairportMulti** [comment]
Here the log entries.

[auth.log.txt](https://github.com/mikebrady/shairport-sync/files/1092178/auth.log.txt)
[syslog.log.txt](https://github.com/mikebrady/shairport-sync/files/1092179/syslog.log.txt)
[daemon.log.txt](https://github.com/mikebrady/shairport-sync/files/1092180/daemon.log.txt)

**Comment by shairportMulti** [comment]
Finally it's done!

I just played around a little with the config and now its working - eight simultaneously running shairport-sync instances all connected and playing music.

my config:
[shairport-syncEGBAD.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092627/shairport-syncEGBAD.conf.txt)
[shairport-syncEGENT.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092629/shairport-syncEGENT.conf.txt)
[shairport-syncEGKUE.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092630/shairport-syncEGKUE.conf.txt)
[shairport-syncEGWOHN.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092631/shairport-syncEGWOHN.conf.txt)
[shairport-syncOGBAD.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092633/shairport-syncOGBAD.conf.txt)
[shairport-syncOGSZ.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092634/shairport-syncOGSZ.conf.txt)
[shairport-syncOGVR.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092635/shairport-syncOGVR.conf.txt)
[shairport-syncOGZOST.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092636/shairport-syncOGZOST.conf.txt)
[shairport-syncOGZWEST.conf.txt](https://github.com/mikebrady/shairport-sync/files/1092637/shairport-syncOGZWEST.conf.txt)
[shairport-sync@.service.txt](https://github.com/mikebrady/shairport-sync/files/1092626/shairport-sync.service.txt)

**Comment by mikebrady** [comment]
Fantastic. Can you say what the issue was?

**Comment by shairportMulti** [comment]
To be honest i don't really know whats the problem was, maybe a wrong character in the old config or that i set the "rate" config in the working configuration.
Here the working and the non working config:

[asound.conf.16Kanal.OK.txt](https://github.com/mikebrady/shairport-sync/files/1095230/asound.conf.16Kanal.OK.txt)
[asound.conf.16Kanal.NOK.txt](https://github.com/mikebrady/shairport-sync/files/1095231/asound.conf.16Kanal.NOK.txt)

**Comment by magichew** [comment]
@shairportMulti This is something very similar to what I would like to achieve. I have Raspberry Pi 3 with 4 USB sounds cards.

I would like 4 instances of Shairport Sync to run to give my 4 Airplay devices or zones for my house.

I've got Shairport Sync working with one USB device but I'm looking for some help to get 4 concurrent Shairport Sync instances running each utilising a different sound card.

Can you please give me some steps (or some links) to explain how I might achieve this? 

Also, just thinking whilst typing, my USB sound cards each have an Audio out and an Audio in. This is then a two channel audio device, am I able to output from the input which would give me 8 stereo channels and so perhaps 8 airport devices (or zones or rooms) to output to?

Thanks in advance.

**Comment by shairportMulti** [comment]
@magichew 
so you have 4 instances of shairport-sync running?
I am no expert for alsa but i think you have to configure it like in the way i did (see asound.conf.16Kanal.OK.txt). For each soundcard there must be a definition of pcm.card (pcm.card1 - pcm.card4), ctl.card (ctl.card1 - ctl.card4), pcm.mixer (pcm.mixer1 - pcm mixer4) with bindings 0 and 1 (two channels). In pcm.out i think you will need 4 slaves (i have two) (0,1 slave a, 2,3 slave b, 4,5 slave c, 6,7 slave d), and then you have to define your 4 zones (pcm.zone1 - pcm.zone4). 
I don't know how to make an input to an output.

**Comment by mikebrady** [comment]
Making an output channel from an input channel doesn't make sense – apart from anything else, output channels will have digital to analog converters whereas input channels will have analog to digital converters.

**Comment by magichew** [comment]
Thank you for your replies. I have been able to achieve what I wanted to achieve by following the steps outlined by @cre8dojo in this article... #37 

The extra output from the mic input would have just been a bonus.

**Comment by cre8dojo** [comment]
if your zones can do with mono sound, you can split the stereo channels into separate zones giving you 8 zones with from 4 usb cards. don't forget the rpi built in output too.

**Comment by noelhibbard** [comment]
I am doing the same at my house but with a single USB soundcard for 4 rooms in stereo. It took me ages to get my alsa config right but once I got it right it works perfect. No sync problems either. To get around the iPhone's inability to stream to multiple AirPlay targets I wrote an AirPlay Proxy/Hub in Node.Js. The AirPlay hub is named [Multiroom] (so it alpha sorts to the top). So if I want to stream to a single room then I AirPlay directly to that room. But if I want to stream from the iPhone to multiple rooms then I stream to [Multiroom] and then fire up the WebUI and then select all the rooms I want to stream to. So the proxy receives the stream from the iPhone and then proxies it back out to the individual AirPlay targets. I have the proxy running on the same machine that has the USB soundcard and Shairport-Sync instances so it doesn't create tons of network I/O.

You can check out my project here:
https://github.com/noelhibbard/node-airplayhub

I originally developed this to run on a weak Intel Atom Nettop but it couldn't handle the CPU load if you ran more than 2 zones at once through the proxy. I moved it to an i5 and now it has no problem running all 4 zones at once.

I know Mike has shot down requests for Multiroom audio but man I would love to see him build some sort of proxy into Shairport-Sync. It will be really interesting when someone cracks the details on AirPlay2. I don't understand why Apple will not open up the protocol a little.

**Comment by noelhibbard** [comment]
BTW, here is my asound.conf. I need to compare it to @shairportMulti to see if I can improve on mine:
[code]
pcm.usbsound1 {
    type dmix
    ipc_key 673138
    slave {
        pcm "hw:1,0"
        rate 44100
        channels 8
        period_time 80000
        buffer_time 320000
        period_size 4096
        buffer_size 16384
    }
    bindings {
        0 0
        1 1
        2 2
        3 3
        4 4
        5 5
        6 6
        7 7
    }
}

pcm.porch {
    type route;
    slave.pcm usbsound1;
    slave.channels 8;
    ttable.0.2 1;
    ttable.1.3 1;
}

pcm.livingroom {
    type route;
    slave.pcm usbsound1;
    slave.channels 8;
    ttable.0.0 1;
    ttable.1.1 1;
}

pcm.garage {
    type route;
    slave.pcm usbsound1;
    slave.channels 8;
    ttable.0.4 1;
    ttable.1.5 1;
}

pcm.bathroom {
    type route;
    slave.pcm usbsound1;
    slave.channels 8;
    ttable.0.6 1;
    ttable.1.7 1;
}
[/code]

**Comment by noelhibbard** [comment]
@shairportMulti just curious what sound cards you are using? Here is the one I am using:
https://www.amazon.com/gp/product/B004HXGJ3S
 Only $26.99 USD

**Comment by shairportMulti** [comment]
@noelhibbard i have similar sound cards, mine are from LogiLink but looking like yours

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
