### ISSUE TITLE
metadata cover picture size over 65k

### ISSUE THREAD

**Issue by lmirel** [mikebrady/shairport-sync#543]
great work on the tool!
any chance the cover metadata can be allowed to go beyond the 65k bytes limit?
I tried changing the size in config but the code doesn't allow it, then even if I patched the code it still wouldn't send a cover picture bigger than 65k.
thanks!

**Comment by mikebrady** [comment]
Hi there. I'm not sure what you are referring to...

**Comment by roblan** [comment]
Shouldn't this https://github.com/mikebrady/shairport-sync/pull/533 fix this issue?
Btw. is there any description to those chunked packages? There is no info about them here https://github.com/mikebrady/shairport-sync-metadata-reader

**Comment by lmirel** [comment]
> Shouldn't this #533 fix this issue?
thanks, it should. waiting for it to be made available into master.
