### ISSUE TITLE
Not reading shairport-sync.conf file

### ISSUE THREAD

**Issue by hui13** [mikebrady/shairport-sync#544]
Hi,

I have run into an unexpected issue and, after a couple of days of searching, reading and reinstalling, I still have not found an explanation nor a solution.

I have been running Shairport-Sync for several years on Raspberry Pis without issue. Most recently I have had version 2.9.5 running on a Pi3 and Raspbian for several months. I decided to update to the latest development version a few days ago. 

pi@raspberrypi:/etc $ shairport-sync -V
3.1d189-OpenSSL-Avahi-ALSA-pipe-soxr-metadata-sysconfdir:/etc

And although the installation functions on a basic level, I have realized that when run as a service/daemon, the shairport-sync.conf file is not read at startup.
If I stop the service and run shairport-sync from the command line with the -c option, it works as desired, having read the conf file.

pi@raspberrypi:/var $ shairport-sync -c /etc/shairport-sync.conf
Successful Startup

I would appreciate any help.

Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. Let me do a check and get back to you – I have been making some changes to the relevant code!

**Comment by mikebrady** [comment]
Well spotted, thanks. I fixed the problem and pushed an update. (The issue was a result of experimenting with a `shairport-sync` subdirectory for holding settings etc. but I forgot to undo the experiment, sorry.)

**Comment by hui13** [comment]
Thank you for the prompt reply and simple solution. I am glad that I was able to help a bit.

**Comment by mikebrady** [comment]
Thanks. Is it okay to close this issue now?

**Comment by hui13** [comment]
Yes. I should have said so. Updated and resolved. Thanks.

**Comment by mikebrady** [comment]
Many thanks,
