### ISSUE TITLE
No sound with HiFiBerry Amp+

### ISSUE THREAD

**Issue by rtmurphy** [mikebrady/shairport-sync#549]
Hello.  I am having problems getting output from Shairport to a HiFiBerry Amp+.   No problems streaming to the on-board audio adapter.  Also, no problem playing a mp3 to the HiFiBerry using mplayer.
Per the instructions from HiFiBerry: (https://www.hifiberry.com/build/documentation/configuring-linux-3-18-x/)
I disabled the on-board adapter by commenting the following:
dtparam=audio=on in the /boot/config.txt

Added the following line to the /boot/config.txt file:
dtoverlay=hifiberry-amp

Created a /etc/asound.conf with the following content:

pcm.!default {
  type hw card 0
}
ctl.!default {
  type hw card 0
}

Checked that the sound card was enabled with “aplay -l”:

**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_amp], device 0: HifiBerry AMP HiFi tas5713-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

In the /etc/shairport-sync.conf, I added:
alsa = {
  output_device = "hw:0";
};

I did not see any mixer associated with the HIFIBerry Amp

Any help getting this configured properly would be appreciated.

**Comment by mikebrady** [comment]
Thanks for the post. Are there any messages in the log file?

**Comment by rtmurphy** [comment]
Mike.  Thank you for the quick response.  The HifiBerry Amp+,  has two outputs that can control volume in the mixer, Master and Channels.  If I set the Master to 100% using amixer, and control the volume using the Channels (which I set in the shairport_sync.conf file, and commented the max volume_range_db setting, it seems to work fine with TuneBlade for Windows.

**Comment by mikebrady** [comment]
That's good. The utility `alsamixer` also helps when looking for device- and mixer names.

**Comment by mikebrady** [comment]
Is it okay to close this issue please?

**Comment by rtmurphy** [comment]
Yes.

**Comment by mikebrady** [comment]
Thanks.
