### ISSUE TITLE
AirPlay Volume

### ISSUE THREAD

**Issue by ghost** [mikebrady/shairport-sync#551]
Hi Mike, 

Not an issue just hoping to find an answer to something. 

Do you know how iOS deals with volume control when streaming to airplay? When you connect to an airplay device the volume changes, I 'think' this is the last used volume when streaming to that airplay device? However I created a new airplay stream and connected and the volume also changed. 

My real aim is, is there a way to influence / control the device volume? 

I want to use the device volume to control the actual sound volume but I don't want the ability to connect at full volume and the sound to be at full. I'd like somehow to set a default volume to the airplay stream.

**Comment by mikebrady** [comment]
Thanks for the question. The short answer to your question is that I don't know. At present, Shairport Sync doesn't send volume control information back to the source, e.g. iTunes. It is possible to send commands to the source, and some have done so with external programs, but it's not part of Shairport Sync. So, I have never tried to send back volume control information before the stream becomes audible.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.

**Comment by WillMo2198** [comment]
@mikebrady Any update on this issue?

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. This issue is close – would you be kind enough to open a new one?
