### ISSUE TITLE
Audio Channel Naming on macOS

### ISSUE THREAD

**Issue by hstriepe** [mikebrady/shairport-sync#554]
It is not clear to me, what the device mapping is on macOS.

I am trying to redirect to USB Audio DAC.

**Comment by mikebrady** [comment]
Thanks for the post. For clarification, are you running Shairport Sync on a Mac? If so, how did you install it? Did you compile it yourself or did you do something else?

**Comment by hstriepe** [comment]
Yes, I am running it on a classic Mac Pro 5,1 with High Sierra beta. It was built using (Home) brew.

Thanks for responding.

**Comment by mikebrady** [comment]
Thanks for that. I'm afraid I don't have any information on that – perhaps another contributor can help?

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
