### ISSUE TITLE
shairport-sync not starting via systemd [SOLVED]

### ISSUE THREAD

**Issue by reefbarman** [mikebrady/shairport-sync#556]
When starting shairport sync via systemd I get this error:

Jul 14 06:04:27 raspberrypi shairport-sync[1468]: shairport-sync: audio_pa.c:126: init: Assertion `pa_context_connect(context, ((void *)0), PA_CONTEXT_NOAUTOSPAWN, ((void *)0)) == 0' failed.

but if I just start it in a terminal with

shairport-sync -v

it works

The above error was the same error I got when trying to start shairport-sync as root user.

Anyone know how to fix it?

**Comment by mikebrady** [comment]
It looks like you are trying to use the pulse audio back end, which needs the PulseAudio system to be running. Unfortunately, PulseAudio normally is not set up to run when the user is root.

Please see the release notes for 3.1d16 in the `development` branch's [RELEASENOTES.md](https://github.com/mikebrady/shairport-sync/blob/development/RELEASENOTES.md).

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
