### ISSUE TITLE
kernel: pcm512x 1-004c: No SCLK, using BCLK: -2

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#557]
Every time when I manually change song in iTunes (12.6.1.25) I find in my journalctl
```
kernel: pcm512x 1-004c: No SCLK, using BCLK: -2
```
shairport-sync 3.1d23-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc
Raspberry Pi 3 with IQaudIO DAC+

Is this normal or suppose to happen?

**Comment by mikebrady** [comment]
Sorry for the long delay, but I get the same message using an IQaudIO Amplifier. I presume it's a benign message from the firmware.

**Comment by roblan** [comment]
Oh, ok then :) I was afraid it's some kind of kernel error :)

**Comment by faxm0dem** [comment]
Same here
