### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by gilgameshskytrooper** [mikebrady/shairport-sync#558]
Recently I have been getting a weird error. If I switch my system sound to output to the shairport-sync server, it plays for the duration of the media. However, if there is a change in media (e.g. the next song starts playing), then my system reverts sound output back to the "system default." However, this usually does not work, and for all intents and purposes, the sound gets outputted to a null device.

I am not really sure what is causing this, and it could potentially be on the client side rather than the shairport-sync server side. But even a clean install did not fix this. Hence, I am just putting this up.

**Comment by gilgameshskytrooper** [comment]
Furthermore, I am using an app called Boom 3D to manage system-wide EQ on my Mac

**Comment by mikebrady** [comment]
Thanks for the interesting post. There are quite a few variables in your situation. Could you say what the source of your audio is – for instance, is it iTunes, Spotify, or something else when these things happen? Also, does the error happen consistently?

**Comment by gilgameshskytrooper** [comment]
I use an app called Swinsian. But it happens no matter what I use (e.g. Youtube on Chrome). However, it seems important to note when I tried to switch to the ShairPlay server on iTunes directly, it would just hang up and never connect. However, it seems however that after reinstalling it from source, I no longer have this issue.

**Comment by mikebrady** [comment]
Fair enough. Feel free to reopen if necessary.
