### ISSUE TITLE
AllConnect problems

### ISSUE THREAD

**Issue by Bazmundi** [mikebrady/shairport-sync#560]
One of those problems.  Could be AllConnect or could be shairport-sync.

My wife ditched her iPhone in favour of a Samsung S8 - she hates it, it isn't an iPhone ... who would have guessed!

So, yes she has an iPad that happily sings to the C.H.I.P. around the house with their speakers attached - it is what I use to buzz out shairport-sync builts on my C.H.I.P.

So does the iTunes running on PC.   I daresay the iPhone she gave to my sister-in-law, instead of giving it to me to be my iPod (grrrrrrrrrr) would talk to them.

But, after downloading dozens of Android apps, the only app that saw the shairport-sync clients out of the box with no fiddly setup was one called [AllConnect](http://www.tuxera.com/products/allconnect/). 

Problem, I can't stream to the devices.  I hit play and the player immediately stops.  I hit stream and it churns then stops.

My problem, not yours of course, wife insists "MUST USE PHONE!".

I am poking around with any config AllConnect may have but this is the 12th app I have tried and am losing interest - I might have to take command of the music and that will only see lawyers involved.

Has anyone successfully driven shairport-sync from an Airplay enabled Android app??

**Comment by mikebrady** [comment]
Hmm, I'm away from my stuff for another two weeks or so, so I can't check stuff, but I think I did get AllConnect to work. I'd suggest turning off soxr interpolation and turning off -- initially at least -- resynchronisation.

**Comment by Bazmundi** [comment]
Mike. I don't have soxr running because of wifi problems ("very choppy"). I
have the same problem whether soxr is enabled or not anyway. The problem
manifests allconnect end where I hit play but it does not run. Its not
shairport sync end per se.

On 30 Jul 2017 10:43 PM, "Mike Brady" <notifications@github.com> wrote:

Hmm, I'm away from my stuff for another two weeks or so, so I can't check
stuff, but I think I did get AllConnect to work. I'd suggest turning off
soxr interpolation and turning off -- initially at least --
resynchronisation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mikebrady/shairport-sync/issues/560#issuecomment-318901183>,
or mute the thread
