### ISSUE TITLE
Syncing video with delayed sound [SOLVED]

### ISSUE THREAD

**Issue by bbbenji** [mikebrady/shairport-sync#561]
I understand the delay between Airplay and Shairplay is unavoidable. However, is it possible to delay video on macOS in order to synchronise it with the delayed audio from the RPi? Specifically, I would like to sync with any video played in Chrome; eg: YouTube, LiveLeak or from Synology Video Station.

**Comment by roblan** [comment]
Just a wild thought - try this in Safari? Maybe it's Chromes fault.

**Comment by mikebrady** [comment]
Thanks for the post. Safari, QuickTime player and iTunes delay the video automatically. YouTube videos played in Safari are mostly delayed as well (I guess that video and audio can't be separated on some old YouTube videos). Chrome used to delay videos as well but stopped doing so recently, for some reason. In VLC you can set a delay too. Don't know about LiveLeak or Synology Video Station, I'm afraid.

**Comment by anandghegde** [comment]
@mikebrady Any solution for plex player?

**Comment by mikebrady** [comment]
Thanms for the post. I don't use Plex Player, I'm afraid. Maybe someone other user has some information to share.

**Comment by anandghegde** [comment]
I had to set the audiodelay parameter to -2000 in `~/Library/Application Support/Plex Media Player/plexmediaplayer.conf`

**Comment by mikebrady** [comment]
That sounds right, thanks!
