### ISSUE TITLE
No 24 bit via Ethernet?

### ISSUE THREAD

**Issue by DomusDigital** [mikebrady/shairport-sync#563]
Hi

I am using moOde on a HiFiBerry DAC Pro+ and my server is a Mac Mini.

Everything is over ethernet, so I should be getting 24 bit to the DAC when playing 24 bit files through wired AirPlay to the Pi, but moOde reports incoming at 16/44.1.  I've written to Tim, but it occurs to me that it might be a shairpoint issue so I thought I would post here as well.

Many thanks for any help in this.

**Comment by roblan** [comment]
As far as I know- AirPlay is always 16 bit. Wireless/cable- doesn't matter. Maybe AirPlay2 will change that as they're saying that HomePod will have amazing music quality.

**Comment by mikebrady** [comment]
Yes, I believe @roblan is correct. In my experience, everything is changed to losslessly-transmitted 44.1kHz 16 bit little-endian interleaved stereo, i.e. "CD quality". The AirPlay protocol is capable of different formats, but AFAIK they have never been used.
