### ISSUE TITLE
ATV Gen 4 + Airplay 

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#566]
Greetings,

Recently my pre-amp died and I pulled it.. Musically I was not concerned as I can control the volume digitally via iTunes. The Apple TV (Gen 4) on the other hand was the reason I still had a pre-amp.

Well imagine my surprise when I discovered I could Airplay from the ATV to my Pi running Shairport.. and the jaw dropping moment I saw that I could control the volume!

No More pre-amp in my rig.. DAC straight out into the Mono Blocks!

Anyway, with all that said, I've noticed a couple of things that I'm not sure if they can be resolved.

1) Press pause and notice the sound still goes on for a few seconds even though the image is paused.

2) The gain seems to be lacking a tad. I have it at lets say 80% according to the bar and thats about where my pre-amp at 50% gain would give equal gain output.

Not sure if either of these "issues" can be solved or if this is just the nature of the beast!

Either way, thought I'd get some input!

**Comment by mikebrady** [comment]
Hmm – I don't have an ATV 4G, so I can't check this out...

**Comment by rockrabbit** [comment]
Mike,

Start checking craigslist and your local pawn shops... get one and see what I'm talking about... think it will put a smile on your face!

**Comment by mikebrady** [comment]
Haha, thanks :). I do have a second-generation ATV which I'll try first -- a week or so.

**Comment by mikebrady** [comment]
Hi there. Shairport Sync players well with audio from a Second Generation Apple TV. Thanks for the heads-up.

**Comment by mikebrady** [comment]
Hi there. Is it okay to close this? I’ve put a mention of the Apple TV in the README.
