### ISSUE TITLE
sndio backend stopping after ~1 second: xrun, pause cycle [FIXED]

### ISSUE THREAD

**Issue by tsia** [mikebrady/shairport-sync#567]
hi, i am trying to use shairport-sync with the sndio backend on Linux (Debian 8.9).
shairport-sync is configured to use the device `snd/0`.
i start `sndiod -f snd@something.local/0 -ddd` to see the debug output.

when streaming from iOS to shairport sync, it works for ~1 second and then `sndiod` outputs `shairpo0 vol=127,pst=run,mmc=off: xrun, pause cycle` forever and the audio stops playing.

i also tried `aucat` to play via the local `sndiod` and it works fine so it seems to be an issue with the way, shairport-sync streams to sndio.

i am sending it via network to another `sndiod` but i have the same issue when outputting locally.

i tried to set `snd@something.local/0` as device in shairport-sync and not use the local sndio. it has the same problem.

i removed the `xrun` checks from `sndio` to see what happens and it just says the buffer is empty `(0bytes)` and stops.

i tried `master` and `development` branch as well.

debug logs:
[sndio.txt](https://github.com/mikebrady/shairport-sync/files/1205789/sndio.txt)
[shairport-sync.txt](https://github.com/mikebrady/shairport-sync/files/1205805/shairport-sync.txt)

**Comment by tsia** [comment]
running shairport-sync with `pipe` output and pipe it into `aucat -i -` sutters a bit but works.

**Comment by mikebrady** [comment]
Many thanks for the report. I'll check it out, though it may take a little time.

**Comment by mikebrady** [comment]
Quick question: is there anything special about your hardware? By any chance, is it a virtual machine?

**Comment by tsia** [comment]
It’s just a generic Intel Atom Board. No virtualization or anything special.

**Comment by mikebrady** [comment]
Thanks for the information.

**Comment by mikebrady** [comment]
Hi there. I just started looking at this, though on the current Debian (V9) in a VMWare Virtual Machine.

Firstly, PulseAudio is installed -- is it installed on your system?

Secondly, I could not get `aucat` to play a wav file unless `sndiod` was disabled (!). In other words, if `sndiod` was running, `aucat` stuttered badly. When `sndiod` was not running, `aucat` played perfectly, presumably through PulseAudio.

Maybe I'm doing something really stupid -- any comments or clarifications would be welcome.

**Comment by tsia** [comment]
we could fix the stuttering by calling `aucat` with the parameter `-r 44100` to match the sample rate

**Comment by mikebrady** [comment]
Thanks. And is PulseAudio installed on your system?

**Comment by tsia** [comment]
no pulseaudio installed.

**Comment by mikebrady** [comment]
Thanks for that. I finally managed to get `aucat` playing a file smoothly by setting `sndiod` running as follows: `$ sndiod -ddd -r 44100 -m play`. The rate setting could be done on `aucat`, but the mode setting was vital. Anyhow, now I get the problem you reported above with Shairport Sync, but without the resampling message `resamp: 882/960`. I'll dig in some more over the next few days.

**Comment by mikebrady** [comment]
Could you try this quick hack please? In the file `audio_alsa.c`, look for the function called `onmove_cb`, possibly on line 240. It contains a `pthread` lock call and a corresponding unlock call. If you comment both of them out, `make` and test, could you let us know how it goes? (I don't have access to my normal testing systems right now.)

**Comment by mikebrady** [comment]
Sorry – not `audio_alsa.c`, duh, I meant `audio_sndio.c`. Apologies!

**Comment by tsia** [comment]
Nice! It works with those lines commented out.

**Comment by mikebrady** [comment]
Great. I need to check it a bit more – I was being ultra-careful (apparently too careful) controlling possible multiple access.

**Comment by mikebrady** [comment]
Hi there. Just FYI, I've rolled those changes into 3.1.1, which is at the RC0 stage now.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
