### ISSUE TITLE
Trouble with update and daemon

### ISSUE THREAD

**Issue by MCUdude** [mikebrady/shairport-sync#570]
Hi!
First, thank you for the great project! I use Shairport-sync every day for listening to music, and it's simply awesome 🥇 

I've been running an older version of Shairport-sync for a while now (compiled it a year ago I think), and the last few weeks shairport-sync have stopped working a few times, so I thought it might be smart to update to the latest version. I'm running Ubuntu 14.04.5 LTS.

After running $sudo make install, I get this error:
```
chromebox@chromebox:~/shairport-sync$ sudo make install
Making install in man
make[1]: Entering directory `/home/chromebox/shairport-sync/man'
make[2]: Entering directory `/home/chromebox/shairport-sync/man'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/share/man/man7'
 /usr/bin/install -c -m 644 shairport-sync.7 '/usr/local/share/man/man7'
make[2]: Leaving directory `/home/chromebox/shairport-sync/man'
make[1]: Leaving directory `/home/chromebox/shairport-sync/man'
make[1]: Entering directory `/home/chromebox/shairport-sync'
make[2]: Entering directory `/home/chromebox/shairport-sync'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c shairport-sync '/usr/local/bin'
make  install-exec-hook
make[3]: Entering directory `/home/chromebox/shairport-sync'
[ -e /etc ] || mkdir /etc
cp scripts/shairport-sync.conf /etc/shairport-sync.conf.sample
[ -f /etc/shairport-sync.conf ] || cp scripts/shairport-sync.conf /etc/shairport-sync.conf
getent group shairport-sync &>/dev/null || groupadd -r shairport-sync >/dev/null
getent passwd shairport-sync &> /dev/null || useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null
[ -e  ] || mkdir -p 
[ -f /shairport-sync.service ] || cp scripts/shairport-sync.service 
cp: missing destination file operand after ‘scripts/shairport-sync.service’
Try 'cp --help' for more information.
make[3]: *** [install-exec-hook] Error 1
make[3]: Leaving directory `/home/chromebox/shairport-sync'
make[2]: *** [install-exec-am] Error 2
make[2]: Leaving directory `/home/chromebox/shairport-sync'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/chromebox/shairport-sync'
make: *** [install-recursive] Error 1
```

The latest version of shairport-sync is installed (checked by running `shairport-sync --version`), but I'm unable to start the daemon:

```
chromebox@chromebox:~/shairport-sync$ sudo service shairport-sync start
Daemon returned 2 as return value.
```

Any idea how this can be solved? Shairport-sync works; I'm able to listen to my music, but I'm not able to demonize it. Thanks 🙂

**Comment by mikebrady** [comment]
Thanks for the kind words. I'll check this out – might take a few days!

**Comment by mikebrady** [comment]
Hi there. I ran up a new instance of Ubuntu 14.04.5, updated it and installed Shairport Sync and got it working fully without any difficulty.

One thing of note is that 14.04 does not use the `systemd` init system – it uses `upstart`, so you should install for a System V system, not a `systemd` system, as I think you did above.

I think the suggestion in the README for figuring out whether a system is running `systemd` or not is a bit confusing – when you look at Ubuntu 14.04, it's a kind of hybrid, as it's got some `systemd` stuff in it, but it's not using `systemd` for the init system – instead it's using `upstart`.

**Comment by MCUdude** [comment]
You're right, I'm not running a `systemd` installation.

I entered the downloaded shairport-sync folder, and ran the following command:
``` bash
$ ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemv
```

.. and then `make` and `sudo make install`. The output from the latter was a bit cryptic; I didn't realize the installation succeeded before trying to start the daemon. Now the shairport daemon works perfectly!

Again, thank you so much for this project and the great support! You should definitely add a *Donate* button on the front page 😉

**Comment by mikebrady** [comment]
Thanks!

**Comment by MCUdude** [comment]
Hi there again!

Recently I've had some trouble with my media box (which is running Shairport-sync), so I decided to run the usual `apt-get update` and `apt-get upgrade`. After the update Shairport-sync wouldn't autostart anymore. I ran the "service command", and the daemon returned the number **2** again..

```
$ sudo service shairport-sync start
Daemon returned 2 as return value.
```

I tried to update to the latest version of Shairport-sync again, this time with `--with-systemv`. After the update I was able to manually start the daemon (`sudo service shairport-sync start`), the same error occurs again after a reboot. Any idea how to solve this? 🙂 

``` bash
# Update procedure
$ cd shairport-sync
$ git pull
$ autoreconf -fi
$ ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemv
$ sudo make
$ sudo make install

**Comment by mikebrady** [comment]
Thanks for the post. Can you say what version of Linux you are running please?

**Comment by MCUdude** [comment]
Here's the current version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by mikebrady** [comment]
Thanks. I'll check it in the next few days.

**Comment by mikebrady** [comment]
I had a look at this, and there is a bug in it alright – I'll fix it in the next couple of days. Apologies!

**Comment by mikebrady** [comment]
Hi there. I've pushed an update in a new [temporary] branch called `piddircreate`. Would you be kind enough to try it please?

**Comment by MCUdude** [comment]
Fantastic! It works perfectly, no error anymore when starting the daemon!
Again, thank you so much for your support!

PS: I'd like to make a donation to you and this project. Would you like to share your PayPal username? 🙂

**Comment by mikebrady** [comment]
I'm glad it's working, and I'll merge the fix into the main branch in the next few days. It's really not necessary to make a donation, but if you really insist, please go to https://paypal.me/UMBr.

**Comment by MCUdude** [comment]
Thanks Mike! I'd like to make a donation because we use Shairport for hours every day in my house.
It's also incredible that I can report a bug where you're able to track it doen an fix it in a couple of days. One cannot expect that from anyone, but you're doing this for me, and so many other users; for free! 🥇 

I have a few repos myself that have gotten quite popular (Arduino related), and I know how much time support can take, ecpecially when they expect everything to work 100% on terrible, home made hardware.

It feels great to support a project that I use more than my car! That's why I'd like to make a donation 🙂 
Thank you!
