### ISSUE TITLE
Can I use shairport for syncing without apple sound source?

### ISSUE THREAD

**Issue by a-x-** [mikebrady/shairport-sync#571]
I like to use shairport installed on my tho raspberries with my iPhone as sound source. But sometimes I want to sync sound from one raspberry with second without iPhone. 

Can I achieve it with shairport-sync?
Are you know how to implement it?

Thank you!

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, Shairport Sync does not offer this capability, but you should look at  [SnapCast](https://github.com/badaix/snapcast), which might have something for you.

**Comment by a-x-** [comment]
Thank you!
