### ISSUE TITLE
redirect output to tcp [SOLVED]

### ISSUE THREAD

**Issue by wysiecki** [mikebrady/shairport-sync#573]
Hi, i'm a newbe with shairport, need a bit of help.

What i like to accomplish is to redirect the stdout or the raw pcm data to an IP.
This is working for example:
shairport-sync -o stdout | avconv -f s16le -i pipe:0 -f s16le -acodec pcm_u8 -ac 1 -ar 33000 tcp://192.168.0.180:5522

however, i do not need to convert the data, so avconv is not needed, and giving me only errors when stream stops.

How could i configure this with only shairport-sync ?

Many Thanks

Best
Martin

**Comment by mikebrady** [comment]
Thanks for the interesting post. I'm afraid I do not know the answer to this. Maybe some other members of the community could help?

**Comment by tsia** [comment]
did you try netcat for example?
so something like this: `shairport-sync -o stdout | nc 192.168.0.180 5522`

**Comment by gretel** [comment]
> so something like this: `shairport-sync -o stdout | nc 192.168.0.180 5522`
this actually works

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
