### ISSUE TITLE
No sound with USB-soundcard AudioBox 22 VSL [SOLVED]

### ISSUE THREAD

**Issue by Skinboy1999** [mikebrady/shairport-sync#576]
Hello 
First of all, thank you for this awesome piece of software!

I'm running af RPI 3 model B with Jessie and a USB soundcard called "AudioBox 22 VSL".
I got the soundcard to work with the RPI by following the answer from David McCann in this forum thread:
http://www.linuxquestions.org/questions/linux-software-2/alsa-configuration-on-raspberry-pi-usb-soundcard-can%27t-play-sound-4175601546/

In short, I made a file called .asoundrc in the folder /home/pi/.asoundrc 
```
pi@raspberrypi:~ $ cat /home/pi/.asoundrc

defaults.pcm.card 1
defaults.pcm.device 0
defaults.ctl.card 1
```
And that worked perfectly, meaning that the sound from the RPI came through the soundcard 

When I installed Shairport-sync, following the steps in the README file and it all worked fine. Until I tried to play a song from my macbook through shairport-sync, and discovered that there was no sound. 
I tried changing the also output settings to 
`alsa = {
  output_device = "hw:1";`
That just resulted in the RPI disappeared from the list of airplay devices....
So my question is, how do I get shairport-Sync to send audio to my USB-soundcard?

Here is the aplay -l 
```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: VSL [AudioBox 22 VSL], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

All the best and thank you

**Comment by mikebrady** [comment]
Thanks for the post. On the face of it, it looks like `hw:1` should work.

To move forward, I suggest you start looking at the system log file, using, for example:
```
$ sudo journalctl -n 100
```
...to look at the last 100 lines of log. When you chose `hw:1` and Shairport Sync disappeared, it probably stopped deliberately because it could not set the designated output device properly – the log should tell you more. Feel free to post the log information here.

(Just looking at the spec at https://www.presonus.com/products/AudioBox-22VSL/tech-specs it seems to specify 24-bit working but not 16-bit. Let us know that the log says...)

**Comment by Skinboy1999** [comment]
I found a solution to the problem. Following these steps from this [website](http://www.chickensinenvelopes.net/2016/02/airplay-receiver-with-raspbian-jessie/), I changed the default audio options in the also.conf file. And it worked :-D

**Comment by humve** [comment]
Hello,
thank you for this wonderful sw. 
I just installed it on a pi following the [Simple install instructions](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) and all went smooth. 
I can see the pi available but no sound will play from the USB speakers.

The USB speakers are listed as card 1:

<pre>aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Audio [Bose USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
</pre>
  
But when I select hw:1 on /etc/shairport-sync.conf and try to play something I get an error, here below the config:
 <pre>// These are parameters for the "alsa" audio back end.
alsa =
{
  output_device = "hw:1";
  mixer_control_name = "PCM";
//	output_device = "default"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
//	mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
//	mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
//	output_rate = 44100; // can be 44100, 88200, 176400 or 352800, but the device must have the capability.
//	output_format = "S16"; // can be "U8", "S8", "S16", "S24", "S24_3LE", "S24_3BE" or "S32", but the device must have the capability. Except where stated using (*LE or *BE), endianness matches that of the processor.
//	disable_synchronization = "no"; // Set to "yes" to disable synchronization. Default is "no".
//	period_size = <number>; // Use this optional advanced setting to set the alsa period size near to this value
//	buffer_size = <number>; // Use this optional advanced setting to set the alsa buffer size near to this value
//	use_mmap_if_available = "yes"; // Use this optional advanced setting to control whether MMAP-based output is used to communicate  with the DAC. Default is "yes"
//	use_hardware_mute_if_available = "no"; // Use this optional advanced setting to control whether the hardware in the DAC is used for muting. Default is "no", for compatibility with other audio players.
};
</pre>

On the logs I get the following:

<pre>fatal error: audio_alsa: Channels count (2) not available for device "hw:1": Invalid argument
avahi: avahi_unregister.
Request to shut down all rtsp conversation threads
asking playing threads to stop
Error -5 ("Input/output error") dropping output device.
RTSP Channel unexpectedly closed or a serious error occured -- closing the player thread.
</pre>

have you guys seen this error before?
Thank you 
Cheers

**Comment by mikebrady** [comment]
Thanks for the post. My guess is that the Bose USB card is not capable of 44,100 frames per second stereo. Just to be sure the installation is generally working, you could temporarily change the output to `hw:0` / and check that audio can be heard through the built in audio jack.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
