### ISSUE TITLE
shairport-sync available in Fedora

### ISSUE THREAD

**Issue by p3ck** [mikebrady/shairport-sync#578]
Hello Mike,

I've been working to get shairport-sync in Fedora properly.  I will create a PR to update the README.md on how to install when it's finally out of testing.  Currently it's available in the updates-testing repo for f25.  It will eventually be available for f26, and the development branches too.

To install from updates-testing:
`dnf --enablerepo=updates-testing install shairport-sync`

To give karma and get this moved to production quicker see here:
https://src.fedoraproject.org/rpms/shairport-sync
https://bodhi.fedoraproject.org/updates/FEDORA-2017-ec32afadcc
https://bodhi.fedoraproject.org/updates/FEDORA-2017-07de239c9a

and finally all the builds:
https://koji.fedoraproject.org/koji/packageinfo?packageID=24568

Thanks for all your hard work!

**Comment by mikebrady** [comment]
Thanks for this!
