### ISSUE TITLE
How to completely remove shairport-sync?

### ISSUE THREAD

**Issue by billcui57** [mikebrady/shairport-sync#580]
I installed shairport-sync by
cd ~
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync
autoreconf -i -f
./configure --with-alsa --with-avahi --with-ssl=openssl
make
sudo make install

How would I completely remove shairport-sync off my raspberry pi? Including the conf and other changes done to my system
Thanks!

**Comment by mikebrady** [comment]
Thanks for the post. Looking at the `./configure` arguments above, you didn't install any configuration files. So, you just need to remove the executable and the `man` file.

To find the executable, use the `$ which shairport-sync` command. On my Pi I get the following:

```
$ which shairport-sync
/usr/local/bin/shairport-sync
$ 
```
So I would execute `$ sudo rm /usr/local/bin/shairport-sync`.

The `man` file is installed at `/usr/local/share/man/man7/shairport-sync.7`, so use the command:
`$ sudo rm /usr/local/share/man/man7/shairport-sync.7` to delete it.

**Comment by kilvn** [comment]
**### Can you write the uninstall method to the document?**
