### ISSUE TITLE
No airplay after reboot

### ISSUE THREAD

**Issue by wedgetail84** [mikebrady/shairport-sync#581]
Hi Mike,
I'm hoping you could help me with an issue I've encountered while trying to get shairport-sync up and running. I've just installed shairport-sync on my Raspberrypi Zero W running raspbian stretchw/desktop following this guide https://discourse.osmc.tv/t/airplay-audio-server/20294

Initially it showed up on my iphone, but then I moved the pi to another room to plug into the amp and I couldn't find it again. In case it helps, entering shairport-sync -V gives:
"2.8.6-OpenSSL-Avahi-ASLA-pulse-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc

Then shairport-sync -v gives:
"Daemon already running on PID file 284"

If you could advise me where to go next I would be very grateful!

**Comment by roblan** [comment]
Something in `sudo systemctl status shairport-sync`?

**Comment by wedgetail84** [comment]
Sure - I'm pretty green at this... What would I be looking for?

**Comment by wedgetail84** [comment]
here's what I get when I run the above line:
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor p
   Active: active (running) since Sun 2017-08-27 21:21:55 AEST; 19h ago
     Docs: man:shairport-sync(7)
           file:///usr/share/doc/shairport-sync/README.md.gz
           https://github.com/mikebrady/shairport-sync
  Process: 302 ExecStart=/usr/bin/shairport-sync --daemon $DAEMON_ARGS (code=exi
 Main PID: 326 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─326 /usr/bin/shairport-sync --daemon

Aug 27 21:21:54 raspberrypi systemd[1]: Starting ShairportSync AirTunes receiver
Aug 27 21:21:55 raspberrypi shairport-sync[326]: Failed to attach mixer
Aug 27 21:21:55 raspberrypi systemd[1]: Started ShairportSync AirTunes receiver.

**Comment by mikebrady** [comment]
Thanks for the posts and for the status report.

The message:
```
Aug 27 21:21:55 raspberrypi shairport-sync[326]: Failed to attach mixer
```
indicates that the mixer name you are using is wrong – can you check that please?

**Comment by mikebrady** [comment]
Separately, the installation guide you followed is now somewhat out of date. When you get this sorted out, I suggest you follow the guide on the README.md page.

**Comment by rockrabbit** [comment]
`sudo systemctl status shairport-sync`

This command is a god send!

After updating my PiZero with a PhatDAC, I wasn't getting Shairport to launch!

After beating my head a few times, came here.. say the command... ran it..

Doh!

I had mistyped my `output_rate` as 17600... left out the 4

Its 176400 and ta da... All is well!

**Comment by mikebrady** [comment]
Great. Did you get a sensible diagnostic message?

**Comment by rockrabbit** [comment]
Very sensible.. so sensible that it made me feel like the idiot I am!

Good job!

**Comment by mikebrady** [comment]
Haha great – my work here is done 😊.

**Comment by a-x-** [comment]
I have the same issue,
but I have no errors in the logs.

```
sudo systemctl status -n50 shairport-sync
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled)
   Active: active (running) since Thu 2017-09-21 19:51:07 MSK; 19min ago
 Main PID: 11192 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─11192 /usr/local/bin/shairport-sync

Sep 21 19:51:07 rpi3 systemd[1]: Started ShairportSync AirTunes receiver.
Sep 21 19:51:07 rpi3 shairport-sync[11192]: Successful Startup
```

Also, I see no full log:
```
journalctl -u shairport-sync
No journal files were found.
```

**Comment by a-x-** [comment]
Raspberry PI 3
Raspbian
Kodi also installed (I tried to switch on/off its out-of-the-box AirPlay option)

**Comment by mikebrady** [comment]
Hi there. The log seems to indicate that the service is running, so it's a different issue. What version of Raspbian and what version of Shairport Sync are you running? What output device? What settings in the configuration file?

**Comment by a-x-** [comment]
I have no airplay after reboot too.
Sometimes after next reboot airplay starting work, but next reboot makes airplay broken again.

linux 4.9.41
Raspbian GNU/Linux 8 (jessie)
shairport-sync 3.1
rpi3 with default audio output hardware, jack, an experimental driver (is the problem here, maybe?)

clients: iOS10, iOS11, macOS Sierra

**Comment by mikebrady** [comment]
Thanks. I do not know how well Shairport Sync plays with Kodi. Other users who have some experience with it might be able to comment – I don't use it.

To troubleshoot this, can I suggest a few things.

1. Update to the latest version – 3.1.2 (or it might be called 3.1.2rc0). Then, turn on some debugging information by setting the `log_verbosity` in the configuration file to `1` or maybe `2`. That will cause entries to be placed in the log file that might help.
2. Check is if the output device is muted – use `alsamixer`, for example, to see if an the output device is in a mute state. Recent versions of Shairport Sync will not unmute a muted output device.
3. If you have not specified a hardware volume control / mixer, `alsamixer` can be used to check that you have set the overall output high enough to hear.
4. When you say "experimental driver" can you say any more about it? The "new" driver referred to in the README should not cause any problems.
5. Are you sure that output is being routed to the headphone jack? (You can use `aplay` to play a file to the output and then ensure you can hear it.

**Comment by mikebrady** [comment]
A follow on – are you using the sound manager called "jack"? If so, I really don't know what effect it will have.

**Comment by a-x-** [comment]
oh, no, jack stands just for sound output connector

**Comment by a-x-** [comment]
<img align="right" width="320" alt="image" src="https://user-images.githubusercontent.com/6201068/30796584-61105c8a-a1db-11e7-94fb-42c50fa899d6.png">


I'll try update and log_verbosity

Now I just want to add some information:
Sound works at all. Another sound sources are ok.
Shairport does not show in AirPlay selector on iPhone/macbook.

**Picture**: AirPlay selector with another shairport on raspberry2, but rpi3

**Comment by a-x-** [comment]
log_verbosity=3 looks well:
```
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metadata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
loudness is 0.
loudness reference level is -20.000000
Successful Startup
avahi: avahi_register.
```

**Comment by a-x-** [comment]
<details><summary>jfyi: my installation script</summary>

```sh
cd ~/services
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync
sudo apt-get install -y build-essential git xmltoman \
autoconf automake libtool libdaemon-dev libpopt-dev libconfig-dev \
libasound2-dev \
avahi-daemon libavahi-client-dev \
libssl-dev \
libsoxr-dev
autoreconf -i -f
./configure --with-alsa  --sysconfdir=/etc --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd
make
sudo make install
sudo systemctl enable shairport-sync
```

</details>

**Comment by mikebrady** [comment]
Thanks. As a matter of interest, did the log give you something like this:
```
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'DF814135652A@Office' successfully added.
```
Specifically, did you get those extra avahi lines after the `avahi_register` line?

Anyway, the AirPlay service is advertised on the network using Bonjour/ZeroConf. Two more tools you could use – `avahi-browse` on the Pi end (it's part of the `avahi-utils` package) to see how/whether the AirPlay service is being advertised using Bonjour/ZeroConf on the Pi's end of the network and an iOS app called "Discovery" that shows what Bonjour/ZeroConf stuff is being seen at the iPhone's end of the network. They may help to see if there is some kind of network problem.

Is the Raspberry Pi 2 running Shairport Sync or some other variant of shairport?

Finally, is it possible that your RPi 3 has two active network interfaces – WiFi and Ethernet? If so, it may be that case the avahi is advertising AirPlay on the "wrong" network...

**Comment by mikebrady** [comment]
Hi there. Can I ask if you ever resolved this issue?

**Comment by a-x-** [comment]
saying about me,

Issue disappeared for me one day.

But it can come back 
When it'll happens I'll try debug it with your recommendation. 
Thank you.

**Comment by mikebrady** [comment]
Okay thanks.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
