### ISSUE TITLE
Raspbian Stretch + Shairport-sync

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#583]
Happy to report that a Fresh install of Raspian Stretch Lite on my Pi 3 plus a Fresh install of Shairport-Sync are working wonderfully!

Would suggest a clean install as my upgrade attempt was less than successful!

Enjoy!

**Comment by mikebrady** [comment]
Thanks for the news. Agreed about the advisability of a clean install. From [RaspberryPi.org](https://www.raspberrypi.org/blog/raspbian-stretch/):

> Upgrading an existing Jessie image is possible, but is not guaranteed to work in every circumstance. If you wish to try upgrading a Jessie image to Stretch, we strongly recommend taking a backup first – we can accept no responsibility for loss of data from a failed update.
