### ISSUE TITLE
Can't Autoreconf -i -f on RPi Zero W

### ISSUE THREAD

**Issue by brad5ross** [mikebrady/shairport-sync#586]
Hi,

I am running the latest version of Raspian Jessie on a Raspberry Pi Zero W and I am trying to build and install shairport-sync onto the device. 

I am up to the step of running "cd shairport-sync" and then running "autoreconf -i -f"

I am getting the error message of: 
"autom4te: cannot create autom4te.cache: No Such file or directory
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1"

I have looked everywhere to try and solve this problem and cannot find a solution. Thank you for your help!

**Comment by brad5ross** [comment]
Also, I am running the Pimoroni pHat DAC through my RPi, if that makes a difference.

**Comment by faxm0dem** [comment]
This looks like an issue unrelated to shairport-sync. I guess you're missing the proper permissions.
Maybe you cloned the repository as one user, then tried to compile using another?

**Comment by mikebrady** [comment]
Thanks for your post. There are lots of good guides to Linux or Unix — here is just one: http://www.ee.surrey.ac.uk/Teaching/Unix/. Good luck, we have all been noobs at some stage.

**Comment by mikebrady** [comment]
I’m going to close this issue, if that’s okay. I’ve actually built a system just like the one you’re working on — a Pimoroni PHAT DAC on a Pi Zero W in the last few days, so it should work out for you.

**Comment by brad5ross** [comment]
Hey Mike!

That is totally fine! 

I am actually still working on building out the system with a Raspberry Pi Zero W with a Pimoroni pHat DAC and I am still having significant trouble. I think I was finally able to build and install the shairport-sync software onto the RPi but it is not showing up as an airplay device on my phone. I have looked literally EVERYWHERE on the internet to try to figure out how to solve my problem and nothing has sufficed. I know you are probably super busy, but I would love some help on how to get my RPi up and running using your software. 

I have an awesome idea that I would love to pursue with your software but I need to figure out how to get it on my RPi first haha. 

You, and your software, is famous all over the internet! Really impressed with it. 

Let me know if you are willing to help me out! If not, I totally understand!

Best,

Brad

**Comment by mikebrady** [comment]
Thanks. You’re right, I’m afraid — I am really busy right now. I’m glad you’ve made progress on compiling Shairport Sync. Sometimes, when you have figured out how to do something, it pays to completely redo it — get a fresh copy of Raspbian, go through the full sequence described in the README and then see what’s happening.

You can turn on some diagnostic output from Shairport Sync to give some indication of what’s happening in the logs.

You can use tools like `avahi-browse` (from the `avahi-utils` package) and the iOS app called “Discovery” to see whether Shairport Sync is being advertised properly and seen on the network — it may be that a network router firewall is blocking the information, or it may be poor multicast handling by your router.

**Comment by brad5ross** [comment]
Ah, that’s okay! 

Maybe I can ask a question or two while I have you. 

1) I am trying to run my RPi on my school’s “guest” wi-fi because I can’t setup the wi-fi on the Pi with my school’s username and password. Do you think that might be one of the reasons it isn’t running correctly?

2) When I go to setup the pHat DAC for the RPi, should I do that before or after I build and install shairport-sync on my RPi? 

3) Once I have my RPi and shairport-sync up and running, is connecting multiple together as easy as just running music out of my phone? I noticed on one of your issue threads the “nodetunes” and “node airplay hub”, does that need to be used to connect multiple speakers together? Or does shairport-sync automatically sync multiple RPi’s together?

Thanks for your time and I can’t wait to get your software up and running on my RPi. 

All the best,

Brad

**Comment by mikebrady** [comment]
OKay:
1. Almost certainly the “guest” WiFi is blocking at least some access between devices connected to it. In some places, multicast is disabled, so that Bonjour/Zeroconf is disabled. This would prevent AirPlay services being seen.

2. It doesn’t matter which way around you do this.

3. It depends on the player. iTunes can send an audio stream to multiple AirPlay devices simultaneously. An iOS device, however, can only send audio to one AirPlay device at a time. The forthcoming “AirPlay 2” seems to be a completely different protocol and will allow iOS devices to output to multiple devices. Unfortunately, it doesn’t seem to be available yet, and there is no certainty that the AirPlay 1 protocols used by Shairport Sync will be supported. See #592 for more on this.

**Comment by brad5ross** [comment]
Mike,

I can’t tell you how grateful I am for all your help! Thank you so much for answering my questions and helping me out! 

I’ll stop annoying you now so you can get back to work! 

Thanks again,

Brad

**Comment by mikebrady** [comment]
Hi Brad. You're quite welcome. All the best.
