### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#59]
I'd like to suggest a different version scheme.

The problem with the current versioning is that bug fixes, e.g. a8796c407a7258cd80fa6c541aa1582064758022,  are not available for the users relying on a stable version.

How about using a stable and a development branch? For instance use the current branch `2.2` as stable branch and introduce a new branch, e.g. `next` or sth. else, for new feature development.

So, if for instance within one or two weeks some bugs are fixed you can publish a new patched version, e.g `2.2.3`: 
* Fix memory leak
* Fix another memory leak
* Fix another bug

If a new feature is introduced, e.g. metadata support added, a version bump can be released, e.g. version `2.3.0` and becomes the new stable branch `2.3`:
* Add metadata support

What do you think?

**Comment by mikebrady** [comment]
Thanks for this suggestion! To be honest, I am inexperienced and undisciplined in the use of branches. I will try to move towards that scheme.

**Comment by joerg-krause** [comment]
Branching with git is very straightforward and I think you will like it.

The most basic approach would be to have a stable `master` branch where you use tags to define a release and an unstable `next` branch for new feature development (or even a branch for each new feature). So you can add fixes to the master branch, do a new patch release, eg from 2.2.2 to 2.2.3, and merge the fixes into the development branch. 

Then, if you think the new feature from the development branch is ready to be published you can merge the branch into the `master` branch and do a minor version bump, eg from 2.2.x to 2.3.

But this is only a suggestion of course.
