### ISSUE TITLE
No audio after played a while on raspberry pi zero w with justboom zero amp

### ISSUE THREAD

**Issue by guanaco** [mikebrady/shairport-sync#590]
Hi,

I'm using latest release code with tag 3.1.2. It played alright for a while and then randomly stopped outputting audio, while from the phone it seems to show that it's still playing.

Repeating errors from the log:
```
Sep 19 15:17:36 rpi0w-speaker shairport-sync[436]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 15:49:29 rpi0w-speaker shairport-sync[436]: Error -5 writing 351 samples in play(): "Input/output error".
```
I captured the log with `use_mmap_if_available = "no"; `, but I could reproduce it with default value `use_mmap_if_available = "yes"; ` as well.

Detailed log see attached:
[log3.txt](https://github.com/mikebrady/shairport-sync/files/1315614/log3.txt)

Any more information needed, please let me know.
Thanks!

**Comment by mikebrady** [comment]
Thanks for the log. It actually looks like a different problem now. At 15:47:44/45 it shows that packets of data were being lost and requests were made for resends. Then it runs out of audio to output – that's the "Buffers exhausted" messages. In this context, occasional Error -32 messages would not be significant.

All these messages point to a problematic network connection. Also, if you look at the mean standard deviation and max messages, it seems that, on occasion, almost half a second elapses between successive packets of audio, which should be around 7.9 milliseconds apart. Again, this indicates a faulty network. You should check that power management of the WiFi is off on the Pi, and maybe look at some of the suggestions in the TROUBLESHOOTING.md page.

Also, can you move the Pi (or the phone) around and see if that influences things? It would help twith troubleshooting.

**Comment by guanaco** [comment]
Thanks Mike for your help!
I've now turned the power management for Pi's WIFI and will report back if the problem persist.
Just curious (and having NOT reading your code), when the problem happened (assuming underflow?), why it could not recover when the network is back to normal but kept on silent, and on the Phone end it seems to be happy of the receiver and kept playing and updating its status?
Thanks!

**Comment by mikebrady** [comment]
It should indeed recover and continue – so, I'm guessing that the stream did not come back properly. Of course, there could be problems with recovering properly in Shairport Sync, but my experience with it is that it does recover even from pretty bad situations.

**Comment by mikebrady** [comment]
So, just to check, I've put together a Raspberry Pi Zero W with a Pimoroni PHAP DAC and it's working for me without any issues – in fact it's a rather nice compact package.

**Comment by guanaco** [comment]
Thanks Mike for checking. A lot of the time it does work flawlessly, however as I mentioned earlier it stopped working randomly. Can you check with wavemon what signal level are you getting? I’m normally getting around 50% link quality.
Also for the instance that shairport-sync can not recover, after turning of power control on PI I still managed to reproduce, though it seems to be less frequent. What do you need to keep on digging?

Thanks!
________________________________

**Comment by mikebrady** [comment]
Thanks for suggesting `wavemon` — somehow I hadn’t seen it before.

On the Pi Zero, it reports link quality of 75% to 80% — never less than 73%. Signal level of -57 dBm.
On a Pi 3, it reports link quality of 55% to about 68% with a signal level of -70 dBm. It is extremely reliable — playing continuously for days.

There isn’t much more digging I can do, TBH, but you should find out why there are those long gaps between packets — half a second is crazy long. One possible cause is strong interference. Another is a poor quality router — sometimes its possible to update the router’s firmware, sometimes not. If there is some way to get rid of the router, even temporarily, for testing purposes, it often helps. I have spent a lot of time trying to get a decent networking setup.

**Comment by mikebrady** [comment]
Hi there. We’re there any further developments on this?

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
