### ISSUE TITLE
Long Shot - Support Sabrent Wifi Audio Receiver (WF-RADU)

### ISSUE THREAD

**Issue by cdlenfert** [mikebrady/shairport-sync#591]
The WF-RADU https://www.sabrent.com/product/WF-RADU/wi-fi-audio-receiver/ is the cheapest smallest dedicated Airplay receiver I've found available. I've used one for years and it's very reliable as an AirPlay audio receiver. The only grip I have is the lack of syncing capability with other Airplay receivers. Thanks to this article (https://sweethack.wordpress.com/2015/01/01/hacking-the-sabrent-low-cost-airplayairtunes-dongle-for-speakers/#more-63) I've seen it's possible to access the system via Telnet, but the firmware would have to be modified and repacked to make any permanent changes. It's beyond my ability, but it sure would be an awesome update to swap in shairport-sync.

Firmware is available here: https://www.sabrent.com/download/wf-radu-firmware-update/

**Comment by mikebrady** [comment]
Hmm, it really is a long shot – also the product is out of stock, so I wonder if it's made any more.
If it could take [OpenWrt](https://openwrt.org) or similar, then there's a chance you could get Shairport Sync into it.
