### ISSUE TITLE
macOS highsierra and airplay 2

### ISSUE THREAD

**Issue by jonas18z** [mikebrady/shairport-sync#592]
Anyone know how the shairport-sync will work with macOS High Sierra thats using AirPlay 2? Will the macOS support old AirPlay 1 if the device only supports that?

**Comment by mikebrady** [comment]
Thanks for the post. So far, Shairport Sync works with High Sierra beta. I'm not sure anyone has seen AirPlay 2 yet. See #535.

**Comment by rockrabbit** [comment]
> Anyone know how the shairport-sync will work with macOS High Sierra thats using AirPlay 2? Will the macOS support old AirPlay 1 if the device only supports that?

Pretty sure you are talking about iTunes and the build in High Sierra.

I can tell you the new version of iTunes in HS is a tad different, but the function of being able to send the same music to multiple Pi's running Shairport at different volumes is still present and works like a charm.


![screen shot 2017-09-25 at 10 32 20 pm](https://user-images.githubusercontent.com/2807420/30839682-75dc0a90-a241-11e7-8df4-1e3b8cd4e90c.png)

Airplay 2 has nothing to do with High Sierra or iTunes, rather everything to do with iOS 11 and more than likely will only be seen in 11.1!

**Comment by 1liminal1** [comment]
Anyone have any news about Airplay 2 being enabled? It seems to have disappeared off the face of the earth lol

**Comment by 1liminal1** [comment]
So am I understanding this, shairport will need an update to be compatible?

**Comment by mikebrady** [comment]
Shairport Sync is compatible with AirPlay 1 only. The newly available mac OS High Sierra and iOS 11 are still compatible with AirPlay 1 devices, so nothing appears to have changed.

As far as I know, nobody has any worthwhile information about AirPlay 2, and it doesn't seem to be is use yet. It may well be that it's already built into iOS/macOS now but doesn't become active until AirPlay 2 devices are available.

As far as "updating" Shairport Sync is concerned, nothing is know about the AirPlay 2 system, so it's impossible to tell. My guess is that it is very unlikely to be possible.

**Comment by echamberlain** [comment]
AirPlay 2 is enabled in iOS 11 by going to Settings->Developer.  There is a switch labeled AirPlay 2 under the AirPlay Testing section.

**Comment by mikebrady** [comment]
Thanks. Do you have to do something to your iOS device to enable developer settings? Perhaps it only available if you are a certified Developer ?

**Comment by echamberlain** [comment]
You need to enable the device for development in Xcode.

**Comment by 1liminal1** [comment]
Thanks for that info :)

**Comment by alecs2287** [comment]
Is there any way of enabling AirPlay 2 in mac OS High Sierra? Something similar to IOS device?

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
