### ISSUE TITLE
forcing pulse via .config stops deamon starting.

### ISSUE THREAD

**Issue by jer1956** [mikebrady/shairport-sync#602]
I have installed shairport-sync via zesty "as is". If i mod the config to set output_backend="pulse", or "pa", the deamon never starts on boot. I have to use the default config, kill the autoload deamon, and restart using shairport-sync output_backend="pulse" -d
Is that option only via command line input?

**Comment by mikebrady** [comment]
Thanks for the post. You can not start Shairport Sync as a daemon if you are outputting to PulseAudio, as mentioned in the “Starting and Stopping” part of the “Configuring Shairport Sync” section of the README. It’s a limitation of the way PulseAudio is normally configured.
