### ISSUE TITLE
Distorted Audio from MacBook, iPad and iPhone (Raspberry Pi 3)

### ISSUE THREAD

**Issue by lyndwyrm666** [mikebrady/shairport-sync#603]
I installed shairport-sync by building it from source on my Raspberry Pi 3 (Raspbian). I can connect either of my Apple Devices (MacBook Air, iPad Pro, iPhone 5S, all running the most recent OS (Sierra, iOS 11)) to it and play sound. But the sound comes out distorted.

I am using a USB Sound Card, (Sound Blaster), which works fine without distortion if I playback Youtube videos or the build-in soundtest on my Raspberry Pi.

I have read through most of the forum posts concerning this topic, but couldn't find any solution or get them to work.

I got it to work 2 years ago, but my SD Card somehow got corrupted and I had to reflash it. Sadly I don't remember how exactly I set it up.

**Comment by mikebrady** [comment]
Thanks for the post. If you direct the output to the built-in audio jack, does it sound okay?

**Comment by lyndwyrm666** [comment]
It works like a charm through the audio jack.
Now I'm at a loss as to why it sounds distorted when I use my USB-Card with shairport and no distortion if I play music directly on my pi.

**Comment by mikebrady** [comment]
Thanks. When you are outputting to the USB Card, can you post the output configuration options you are choosing please? (I'm guessing, recklessly, that the USB card does not natively do 44,100, and that you are sending the output to an `alsa` pseudo-device that is attempting to do rate translation from 44,100 sample per second to, say, 48,000 samples per second.)

**Comment by lyndwyrm666** [comment]
That is correct, I tried changing the sampling settings in the shairport-sync.conf with no success.

```
alsa =
{
    output_device = "hw:1,1"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the$
//  mixer_control_name = "Speaker"; // the name of the mixer to use to adjust output volume. If not specified, $
//  mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn$
//  output_rate = 44100; // can be 44100, 88200, 176400 or 352800, but the device must have the capability.
//  output_format = "S16"; // can be "U8", "S8", "S16", "S24", "S24_3LE", "S24_3BE" or "S32", but the device mu$
//  disable_synchronization = "no"; // Set to "yes" to disable synchronization. Default is "no".
    period_size = 21845; // Use this optional advanced setting to set the alsa period size near to this value
    buffer_size = 87380; // Use this optional advanced setting to set the alsa buffer size near to this value
//  use_mmap_if_available = "yes"; // Use this optional advanced setting to control whether MMAP-based output i$
//  mute_using_playback_switch = "no"; // Use this optional advanced setting to control whether the snd_mixer_s$
};
```

**Comment by mikebrady** [comment]
Thanks for the update.

What should happen is that Shairport Sync should complain in the log that it can't set the output device to the correct sampling rate and it should then exit. Did you find that setting the period size and buffer size was beneficial?

What is the make and model of the USB card?

**Comment by lyndwyrm666** [comment]
I used the journalctl command to check the log, but shairport didn't complain, at least not in that log.

I changed the buffer and period sizes as I had Issues with the playback being interrupted by buffer brakes. So I set them to the highest values I could without crashing shairport on pressing play.

I use a Sound Blaster X-Fi Surround 5.1 Pro, which does not support 44.1kHz or any other rate of the options as far as I know. I used this card when I got it to work successfully though.

Thanks for your help so far, I know this stuff is frustrating....

**Comment by mikebrady** [comment]
Thanks; it’s odd that Shairport Sync didn’t complain, but it may be that the Sound Blaster driver isn’t responding properly. Anyway, have you looked at issue #167?’

**Comment by lyndwyrm666** [comment]
Just now did, I tried the given configuration file but to no success.

**Comment by mikebrady** [comment]
Hmm, I’m kind of out of ideas, I’m afraid. I wonder if anyone else has any ideas.

**Comment by lyndwyrm666** [comment]
I'll dig deeper into the sampling issue, the problem has to be there :D 
Thanks for the kind help, I'll close this for now and if I find a solution I will post it.

**Comment by mikebrady** [comment]
Thanks.
