### ISSUE TITLE
Crash after about 3 hours of continuous streaming

### ISSUE THREAD

**Issue by davglass** [mikebrady/shairport-sync#604]
First off, love the project, nice work!

I'm using `shairport-sync` in my `lightshowpi` setup to power my Christmas lights, I also use it to power a few speakers in my house too.

Last year I was having an issue where the lightshow would freeze after 2.5-3.5 hours of continuous playing. I've started prepping for this year and decided to debug it.

I've debugged it down to just running `shairport-sync` and streaming to it for a few hours. It will eventually just stop and crash the process.

Here is a log from tonight with `-v` added to the command: https://gist.github.com/davglass/c8868abb920cd61a55c9ffee389547df

If you want, I can also run it with `-vv` or `-vvv`. It just takes a few hours to get it to break :)

**Comment by mikebrady** [comment]
Thanks for the post. Just looking at the log, I can’t see any sign of a fault occurring. What I see is a playing sequence starting at 18:18. Then at 21:37 I see an attempt to play from another device but Shairport Sync refuses and the request goes away. I can’t see any message relating to the play session — thread 0. 

More generally, is there anything else happening on your network that might cause the problem. For example, some networks periodically drop out for a few seconds from time to time. Are there any interesting messages in the log?

**Comment by davglass** [comment]
Right, I can't see anything else in the log either. The playing started at 18:18 and was a steady stream from my iPad. The Pi is hooked to the network via ethernet, wifi isn't even turned on.

The process just exits at the moment that this line is written:

```
Oct 20 21:37:26 lightshowpi shairport-sync[9805]: RTSP conversation thread 1 terminated.
```

I have replicated this several times and the outcome is always that it just dies after 2.5-3.5 hours os solid streaming. I can attempt it again with `-vv` or `-vvv` if you want that output too.

**Comment by mikebrady** [comment]
Okay, so it would be good to get some more information on this. The problem is that, in the master version, verbosity level 3 is way too chatty and level 2 doesn't give enough information. So, I've made a few changes in the development version.

Could you change over to the latest development version and set the debug verbosity level to 2 (i.e. use `-vv`) and turn on statistics ( `--statistics`) please? If you post the results, we should get an idea of the quality of the network connection and stuff like that.

**Comment by davglass** [comment]
Apologies, I was traveling for a few days. I just pulled the `development` branch, compiled it and started the tests again. I'll post the results in a few hours.. Thanks for all the help so far..

**Comment by davglass** [comment]
Ok, here's the output:
https://gist.github.com/davglass/c960eb3959142a7746aabedca5e17914

It ran for right at 3 hours and crashed. The logs don't show what happened, it just writes the last log line at `Oct 26 11:37:13` and dies. Doesn't seem to have too much in there but stats.

**Comment by mikebrady** [comment]
Very interesting indeed. A few observations:
1. The network looks fine – good maximum intervals, and consistent.
2. The Raspberry Pi is doing a huge amount of overcorrecting for synchronisation – are you using the Pi's bid-in audio? I suggest you set the drift to 0.010 seconds, i.e. 10 milliseconds. That will cut down on the amount of overcorrection going on.
3. I am speculating that the Pi gets overloaded with some other work at intervals. Look at 08:24:15 where the sync goes off by around a quarter of a second. I guess this is because the Pi has suddenly been called on to do something else. Could that be so? Look at 09:01:28 – almost half a second off sync!

These are huge and apparently sudden deviations. What kind of a PI is it, and what else is it doing?

**Comment by davglass** [comment]
It's doing nothing else. I'm using a Pi 3b that I just installed stretch on to test this outside of my lightshow, just to be sure nothing else is interfering.

**Comment by mikebrady** [comment]
That’s really interesting. Could you post the output of the two commands: `$ aplay -l` and `$ aplay -L` please? And if you ran it again until it crashed, could you post the outcome of `$ ps aux | grep shair` as well?

**Comment by davglass** [comment]
```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

```
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
```

After it stops there is nothing in `ps ax` as the process completely crashes. I have `12GB` free on the sdcard. Let me run it with `-vvv` and see what it looks like.

**Comment by mikebrady** [comment]
Thanks. On my Pi, `$ aplay -l` gives the same output, but `$ aplay -L` is slightly different:

```
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
```
I can't see how it would make any difference, TBH, but might be worth setting the output_device in the configuration file to `hw:0`. I'll be having a look here to see if I can cause any similar mayhem.

**Comment by mikebrady** [comment]
One quick question: have you added the `audio_pwm_mode=2` setting to the Pi's config file? I'm just trying to get as close to your configuration as possible here.

**Comment by davglass** [comment]
Here is my `/boot/config.txt`: https://gist.github.com/davglass/daaa173afe771a62b8aa179466cb9ce5

**Comment by davglass** [comment]
I've set the verbosity to `-vvv`, set the drift to `0.010` and set the default device to `hw:0` and have started the test. I'll grab the logs after and post them.. Thanks for all the help!

**Comment by mikebrady** [comment]
Thanks. I've set a Pi up here with your original config, and we'll see how it goes too.

**Comment by davglass** [comment]
Awesome, thanks again..

**Comment by mikebrady** [comment]
Also, when you said "Stretch" above, did you mean Raspbian Stretch or straight Debian Stretch?

**Comment by davglass** [comment]
Raspbian Stretch

**Comment by davglass** [comment]
Well crap, right at the 3 hour mark I accidentally stopped the stream. Then I restarted it and started another and accidentally killed that one too. I've started another stream with the above settings so no I wait and this time I won't touch my ipad for any reason :)

**Comment by davglass** [comment]
Interesting after changing the drift to `0.010` it's been streaming just fine for the last 5 hours. I'll let it keep going this evening to see if it keeps running. Then I'll remove that setting and try again tomorrow to see if the process crashes.

**Comment by mikebrady** [comment]
Yeah, my test setup is still going after 16 hours. It’s got the original setting (0.002 seconds drift tolerance) but the source is a Mac Pro.

It looks like I need to think of a better way to stress test it...

**Comment by davglass** [comment]
After removing the settings it ran for about 3.5 hours then died.. The logs show nothing of interest, I'll attach them in a bit. I've now started a test with just the `drift` setting to see if that crashes or not. If it doesn't then I'll test with the hardware set to `hw:0` instead of `default`.

**Comment by mikebrady** [comment]
Thanks. My setup is still running after 24 or 25 hours. Intriguing.

**Comment by davglass** [comment]
I added the drift back in and it died after 3.5 hours. I have changed it to use `hw:0` as the default and it's running now.

**Comment by mikebrady** [comment]
Hmm. My experimental setup terminated yesterday after about 55 hours because the source — an internet radio station playing through iTunes — went offline. Do you have any news yourself? BTW, is it full-fat Stretch or Stretch Lite you are using?

**Comment by davglass** [comment]
I haven't had any luck on my side. I've tried different settings and it still crashes for me. I'm using Stretch Lite as I don't need a gui.

**Comment by mikebrady** [comment]
Thanks again. BTW, can you say something about the source? It’s an iPad right? What application are you using?

**Comment by davglass** [comment]
Yes, it's an iPad Pro streaming from Apple Music downloaded files. I didn't want the network to be an issue for the lightshow so all songs are downloaded locally.

**Comment by mikebrady** [comment]
Okay thanks. Ill try to replicate that exact situation in the next few days.

**Comment by mikebrady** [comment]
So, I ran the Music app on an iPad Pro overnight, playing a downloaded album repeatedly, to a Raspberry Pi 3 running the latest Shairport Sync. If worked fine, even though a few disconnects caused by a nearby microwave oven. Here are the last few entries:
```
Nov 01 09:29:08 raspberrypi shairport-sync[1046]:        0.1,     -22.7,    1410.5,     4965853,    267,   4971,     11,   2153,   5858,  218,  233
Nov 01 09:29:09 raspberrypi shairport-sync[1046]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.2,    19503.5,   109216.0.
Nov 01 09:29:16 raspberrypi shairport-sync[1046]:       -0.0,      22.7,    1314.2,     4966856,    267,   4971,     11,   2153,   5879,  219,  233
Nov 01 09:29:24 raspberrypi shairport-sync[1046]:        0.0,      17.0,    1382.2,     4967859,    267,   4972,     11,   2153,   5856,  218,  233
Nov 01 09:29:29 raspberrypi shairport-sync[1046]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7989.5,    19439.4,   101749.0.
Nov 01 09:29:32 raspberrypi shairport-sync[1046]:       -0.0,      34.0,    1393.5,     4968862,    267,   4972,     11,   2153,   5852,  219,  233
Nov 01 09:29:40 raspberrypi shairport-sync[1046]:       -0.1,      65.1,    1373.7,     4969865,    267,   4972,     11,   2153,   5865,  219,  233
Nov 01 09:29:48 raspberrypi shairport-sync[1046]:       -0.9,     286.1,    1792.9,     4970868,    267,   4975,     11,   2153,   5652,  219,  233
Nov 01 09:29:49 raspberrypi shairport-sync[1046]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7979.3,    19425.2,   101600.0.
Nov 01 09:29:56 raspberrypi shairport-sync[1046]:        1.3,    -662.8,    1654.1,     4971871,    267,   4975,     11,   2153,   5811,  219,  234
Nov 01 09:30:04 raspberrypi shairport-sync[1046]:       -1.0,     572.1,    1835.4,     4972874,    267,   4975,     11,   2153,   5797,  219,  233
Nov 01 09:30:09 raspberrypi shairport-sync[1046]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7989.7,    19449.9,   102237.0.
Nov 01 09:30:12 raspberrypi shairport-sync[1046]:       -0.6,     359.7,    1526.7,     4973877,    267,   4975,     11,   2153,   5841,  219,  233
Nov 01 09:30:20 raspberrypi shairport-sync[1046]:        0.8,    -458.9,    1812.7,     4974880,    267,   4975,     11,   2153,   5800,  219,  233
Nov 01 09:30:28 raspberrypi shairport-sync[1046]:        0.2,     -73.6,    1376.6,     4975883,    267,   4975,     11,   2153,   5833,  219,  233
Nov 01 09:30:29 raspberrypi shairport-sync[1046]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7979.4,    19461.7,   104694.0.
Nov 01 09:30:36 raspberrypi shairport-sync[1046]:        0.5,    -249.3,    1421.9,     4976886,    267,   4975,     11,   2153,   5924,  218,  233
Nov 01 09:30:44 raspberrypi shairport-sync[1046]:       -0.4,     303.1,    1430.4,     4977889,    267,   4975,     11,   2153,   5873,  218,  233
Nov 01 09:30:49 raspberrypi shairport-sync[1046]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.5,    19491.1,   105199.0.
Nov 01 09:30:52 raspberrypi shairport-sync[1046]:        0.1,       5.7,    1353.9,     4978892,    267,   4975,     11,   2153,   5871,  219,  233
```
So, very high level of overcorrection, a lot of packet loss due to the microwave incident, but still working okay.

So, I have a few more troubleshooting ideas, all revolving around the idea of switching something to see if the problem follows the switched-out component. For example, if you had a spare Pi and put the same SD card into it, does it exhibit the same behaviour. Or, if you use a different SD card on the same P{i, does the problem remain. (Ideally, a second PI and a second SD Card, switch them around and see where the problem goes.) Or, if you use a cheapo USB sound card, does the problem continue?

**Comment by mikebrady** [comment]
Thanks. It's a real mystery.

**Comment by davglass** [comment]
Sorry for the delay, it's been a long month..

I've rebuilt the image on 3 different pis and the issue went away. There must have been some really weird config that I had on that older pi image that caused it to break.

Closing this, thanks for helping me debug it..

**Comment by mikebrady** [comment]
Many thanks for the update, and glad it was resolved.
