### ISSUE TITLE
Control playback with Python

### ISSUE THREAD

**Issue by dennisjanssen** [mikebrady/shairport-sync#606]
Hi guys,

I'm using Shairport Sync to build an airplay speaker with an RPi3, but combined with the Google Assistant SDK. But there's one issue, the music keeps playing when I say the 'Okay Google' hotword. That makes sense of course, but makes it a lot less useful.

I can run Python code when certain events are thrown (like hotword detection). But now I can't seem to find information on certain commands to run to temporarily mute or lower volume when talking to the Assistant. Does anybody have a clue if this is even an option? Would be really useful help!

**Comment by mikebrady** [comment]
Hi Dennis. Shairport Sync is a daemon and does not receive any commands whatever from the local computer. However, there may be a way around it: assuming you're using the `alsa` back end, you could mute or lower the volume by controlling the `alsa` output device directly using `alsa` command line tools from `alas-utils`. I'm thinking of `amixer` for example – I'm not an expert.

(There is work going on to give Shairport Sync a D-Bus interface, but it's early days yet. I suggest the above idea is most likely to be fruitful.)

**Comment by mikebrady** [comment]
This has been addressed in more recent versions of Shairport Sync! Closing this inactive issue. Please open a new one if necessary.
