### ISSUE TITLE
Able to find shairpoint device as sound output but not airplay device

### ISSUE THREAD

**Issue by AndrewKwok** [mikebrady/shairport-sync#609]
Hi, I'm having problem with airplay to my Pi3. The Pi3 connect to a monitor via HDMI. I am able to play sound to the Pi3 no problem, but unable to airplay the screen over.

<img width="189" alt="screen shot 2017-10-25 at 1 55 55 pm" src="https://user-images.githubusercontent.com/18108912/31982660-6af4dbfe-b98c-11e7-9a66-f11b92e61214.png">
Able to find Pi3 as an sound output

<img width="230" alt="screen shot 2017-10-25 at 1 56 07 pm" src="https://user-images.githubusercontent.com/18108912/31982705-94a6beae-b98c-11e7-97f1-c8d47f6ac5ce.png">
Unable to find it as a display option

This also happens on my iPhone.

MacOS High Sierra 
iOS 11.0.3

Thanks for the help.

**Comment by mikebrady** [comment]
Hi Andrew. Thanks for the post. Shairport Sync doesn’t do video, I’m afraid. It’s audio only.

**Comment by AndrewKwok** [comment]
Oh right didn't read the instructions correctly. Thanks for the reply
