### ISSUE TITLE
ios airplay to multiple devices

### ISSUE THREAD

**Issue by jimmyfiris** [mikebrady/shairport-sync#61]
I was wondering if it's possible to airplay to multiple shairport-sync devices from iOS? From my understanding it's a limitations of iOS. Since I don't think it's possible to go directly from iOS to multiple shairport-sync, do you know of a good server software that would allow for rebroadcasting to multiple shairport-sync/airplay devices? Sorry this isn't an actual issue, big thanks for your efforts on the software.

Jim

**Comment by mikebrady** [comment]
Hi Jim. Thanks for your interest in Shairport Sync. Unfortunately, I'm afraid I don't know the answer to your question – maybe some more knowledgable reader might be able to help.

**Comment by senthor** [comment]
I have also been looking for a solution for this, and did not find anything.
However, it should be possible, although I'm not capable of writing this sort of stuff.
The idea is some kind of re-broadcasting-server-software, which acts as follows:
1. Act as if single AirPlay receiver
2. Receive audio from iOS device
3. Re-broadcast audio as AirPlay sender to multiple AirPlay receivers which were preconfigured

**Comment by jimmyfiris** [comment]
Yes I see that airfoil would be a nice solution for PC as well if you want to pay for the full version. After searching a little more I found that TuneBlade + Shairport4w is a good/free choice for PC that works as a server/repeater of your music, especially when you can also use the remote for tuneblade iOS app to choose your airplay audio receivers to turn on/off zones from the phone. Haven't gotten to really test it out for long periods of time to ensure that the audio is in sync and that it works consistently.

**Comment by nguyer** [comment]
@senthor  I have been working on a project that does exactly this: https://github.com/nguyer/shaircast.

I have it playing to two Raspberry Pis in my house, but I have had some problems with audio cutting out pretty consistently. I haven't figured out where the problem in the stream is yet.

**Comment by noelhibbard** [comment]
@nguyer took a look at your project and it looks cool. The only problem is nodetunes doesn't do ALAC. But maybe nodetunes could be replaced with shairport-sync to solve that problem.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
