### ISSUE TITLE
Disabling PulseAudio autospawn? [Fixed]

### ISSUE THREAD

**Issue by mhitchens** [mikebrady/shairport-sync#610]
I noticed that the "pa" backend is telling libpulse to connect with auto-spawning disabled.

https://github.com/mikebrady/shairport-sync/blob/91c6587d78475e643686016510fed2170ab0a41e/audio_pa.c#L91

Any particular reason? My setup is headless and it'd be much more convenient to ensure that libpulse takes care of spawning the daemon process for me. I'm also pretty new to PulseAudio, so I may be missing something obvious about the choice here.

Love the product. Been using it for years. Thanks for your efforts.

**Comment by mikebrady** [comment]
Thanks for the interesting post. To be honest, there was no particular reason other than trying to make the minimum change to the environment – I'm not too familiar with PulseAudio myself. I've just pushed a `development` update with `PA_CONTEXT_NOAUTOSPAWN` removed. If you'd be good enough to check it out, I'd be obliged. If it doesn't cause any other problems, then it can be left as the default. It works alright in a standard desktop Linux environment.

**Comment by mhitchens** [comment]
Built and tested on a Raspberry Pi 3 running stretch, works like a charm. I'm working on our home's multi-room audio setup and this will help simplify host setup. Thanks for the quick turnaround!

**Comment by mikebrady** [comment]
Thanks. I’m sure we’d all be interested in a method for doing headless autostart into a PulseAudio backend if it doesn’t involve too much hacking. So, if you had a chance, could you share your experiences?

**Comment by mhitchens** [comment]
Happily. My method right now (with these changes) is really very succinct. Your "make install" creates the user and group, and installs the systemd unit. Since PulseAudio wants to read/write files to the user's home directory under .config/pulse, I ask root to mkdir /home/shairport-sync and chown accordingly. After activating the systemd unit, I can restart and see that shairport-sync is running with its PulseAudio daemon automatically launched.

This is part of an experiment for using shairport-sync as a way to conveniently create PulseAudio sinks that correlate to physical locations in my house, then send that audio to a PulseAudio sink that ultimately applies some rules and ducking (e.g. someone rang the doorbell, play the chime over the temporarily quieted music channel). My use case right now just uses the alsa backend and keeps things relatively local, so naturally I expect some roadblocks and surprises as I move these services into the network into a bit. I'm also trying to keep my head above the appropriate concerns of synchronization at different layers.

Anyway, getting ahead of myself a bit. My primary concern is whether it's appropriate for me to give shairport-sync a home directory in /home, or if possibly the more appropriate location is /var/lib/shairport-sync. I'm even less sure of what the appropriate location might be for BSD, so let's call that a hack for now. Is there a need or desire for shairport-sync to have a place to write files outside of the PulseAudio use case? If so, it might be worth getting a proper home directory concept hammered out for the user.

**Comment by p3ck** [comment]
Just for reference the Fedora rpm/spec file has the following in it to
create the group/user for shairport-sync:

getent group shairport-sync &>/dev/null || groupadd --system shairport-sync
>/dev/null
getent passwd shairport-sync &> /dev/null || useradd --system -c
"shairport-sync User" \
        -d /var/shairport-sync -m -g shairport-sync -s /sbin/nologin \
        -G audio shairport-sync >/dev/null

Hope that helps.

Bill

On Mon, Oct 30, 2017 at 11:19 AM, Matthew Hitchens <notifications@github.com

**Comment by mhitchens** [comment]
That's useful perspective @p3ck, and it would appear Debian's package management makes similar decisions

https://anonscm.debian.org/cgit/collab-maint/shairport-sync.git/tree/debian/shairport-sync.postinst

```
	# create shairport-sync group if there isn't one already
	if ! getent group shairport-sync >/dev/null; then
		addgroup --system shairport-sync >/dev/null
	fi

	# create shairport-sync user if there isn't one already
	if ! getent passwd shairport-sync >/dev/null; then
		adduser --system --ingroup shairport-sync --shell /usr/sbin/nologin \
			--home /run/shairport-sync shairport-sync >/dev/null
		# Add shairport-sync to the audio group
		adduser shairport-sync audio
	elif [ "$(getent passwd shairport-sync | awk -F: '{ print $6 }')" = "/var/lib/shairport-sync" ]; then
		# If the home directory is the old location, try to update it
		# This will fail if any processes are running under the user.
		# This isn't normally the case here in the postinst but it's
		# not worth aborting the whole install if we can't fix that up.
		if usermod -d /run/shairport-sync shairport-sync; then
			# Try to remove the unused and obsolete directory.
			# Ignore the failure if it's non-empty.
			rmdir /var/lib/shairport-sync || true
		fi
	fi
	;;
```

So that makes me feel better about taking bespoke action for my installation (and apparently I have some reading to do about why daemon homes are now in /run instead of /var/lib).

@mikebrady, from a turnkey perspective, do you think it wise to create a shairport-sync homedir in the install target? It could be configurable with a reasonable default of some kind. Otherwise there may be some confusion about why the "pa" backend doesn't work out of the box. Thoughts?

**Comment by mikebrady** [comment]
Thanks for all that. It would certainly be easy to create a `shairport-sync` home directory at installation time, similar to Debian or Fedora.

 Just trying to clarify the situation, is the homedir at `/run/shairport-sync` going to be persistent across reboots? How about the homedir at `/run/shairport-sync` – will that be persistent?

**Comment by mhitchens** [comment]
Per the Filesystem Hierarchy Standard, /run is not preserved across reboots and /var is.

https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by mikebrady** [comment]
Thanks – that's what I was thinking about. So, if it's not persistent across reboots, it is any use to create shairport-sync homedir at `/run/shairport-sync` in the install target. I must admit I'm a bit puzzled.

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new one if necessary.
