### ISSUE TITLE
How can I further attenuate the low-end audio? [Solved]

### ISSUE THREAD

**Issue by echamberlain** [mikebrady/shairport-sync#616]
Hello,

I have some USB SoundSticks connected to an Raspberry Pi Model B.  On the lowest iPhone volume setting (before mute), the sound coming from the speakers is too loud.  When I use alsamixer and reduce the volume to 1.  The volume is still to loud.

Is there some way I can further attenuate the audio, without a big impact on the processor?

<img width="822" alt="screen shot 2017-11-17 at 7 54 51 am" src="https://user-images.githubusercontent.com/117235/32957426-821a55fc-cb70-11e7-9962-c16ffbfb4e93.png">

```
/etc/shareport-sync.conf
// General Settings
general =
{
	name = "Bedroom";
	interpolation = "soxr";
	output_backend = "alsa";
};

// Back End Settings

// These are parameters for the "alsa" audio back end, the only back end that supports synchronised audio.
alsa =
{
  output_device = "hw:1"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
  mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
};
```

**Comment by mikebrady** [comment]
Thanks for the interesting post. Can you post the minimum and maximum dB gain values please? It would be nice to see the range of attenuation the PCM mixer is capable of.

**Comment by mikebrady** [comment]
BTW, are they Harmon Kardon USB SoundSticks you are using? (Not jealous, or anything, no.)

**Comment by echamberlain** [comment]
Yeah, they are version 1 of the SoundSticks.  They sound nice, but are a pain to clean the dust out of.

Here are the min and max dB:

<img width="822" alt="screen shot 2017-11-18 at 9 27 20 am" src=https://user-images.githubusercontent.com/117235/32983016-0149d776-cc43-11e7-96a2-9e7bc335876e.png">

<img width="822" alt="screen shot 2017-11-18 at 9 26 05 am" src="https://user-images.githubusercontent.com/117235/32983018-0919c600-cc43-11e7-9131-45133124effc.png">

**Comment by mikebrady** [comment]
So the overall range is 41 dB, which – as you've discovered – isn't really enough.

Anyhow, yes, Shairport Sync can give you an increased attenuation range by combining any hardware attenuation available with software attenuation.

In the configuration file, look for the `volume_range_db` setting in the `general` stanza, uncomment it and set the value to something sensible, e.g. 70 db. This would be asking Shairport Sync to combine software and hardware attenuation (if available) to give you a range of 70dB. So it will do a maximum of 29 dB attenuation in software and 51 dB in hardware.

Save the file and restart Shairport Sync.

Let us know if it works. Most domestic HiFi systems have a range of about 60 to 80 dB, AFAIK.

**Comment by echamberlain** [comment]
The changes work perfectly.  Thank you.

**Comment by mikebrady** [comment]
Great.
