### ISSUE TITLE
Lost sync with source for 4 consecutive packets -- flushing and resyncing

### ISSUE THREAD

**Issue by tsynik** [mikebrady/shairport-sync#62]
Hi, Mike! Thanks for a brilliant software! I like it a lot.
I have mixed results on my config. Sometimes it works fine, but sometimes it gives me the error, and service restart doesn't help. I can't yet understand what's going on. Tried -r 0 option without success.

My setup: # shairport-sync --version
2.1.12-openssl-Avahi-ALSA-soxr.
Command line: shairport-sync -d --verbose -vv --statistics -- -d hw:0,0
ARM Wi-Fi router with connected PCM2704 DAC. MacBook Pro OS X 10.9.5. Software mixer control. System output (all sounds), iTunes 12 output, ot VOX Player output (it have AirPlay switch too). All fail. Or all worked.

Here is full log when error occur (System Output):
http://pastebin.com/iZMJTdmJ
and this from iTunes 12:
http://pastebin.com/b1KTvb1f

What can cause that issues?

**Comment by tsynik** [comment]
Oh, It was driver fault. Fore some strange reason modules wasn't loaded on startup, so sound device didn't exist. But there was no message from shairport itself about it.

**Comment by mikebrady** [comment]
Glad it worked out! When debug verbosity is turned on, Shairport Sync does log an error. Maybe I will change it so that it logs the error even without any verbosity...
