### ISSUE TITLE
Shairport not visible across 2.4Ghz/5GHz router 

### ISSUE THREAD

**Issue by George-ou812** [mikebrady/shairport-sync#622]
Hi,
This may not be a shairport issue but any information on how iPads etc see shairport advertising would help greatly. Problem is shairport is never seen when devices like iPads are on the 5GHz side of my router. If the 5GHz side of my router is disabled and everything defaults to 2.4GHz then shairport can be seen every time. As I walk away from my router with an iPad ( initially 5GHz ) and it changes over to 2.4GHz then shairport pops up. Shairport runs on a 2.4GHz board. My hub BT (British Telecom ) branded. 

Other music apps like DLNA need CONFIG_IP_MULTICAST to join igmp groups, could I be missing a kernel config somewhere?

Regards.

**Comment by echamberlain** [comment]
Is the Bonjour AirPlay advertisement traffic making it to 5GHz?

You can use an app, like Discovery, to compare the Bonjour traffic on the 2.4GHz and 5GHz networks.

I suspect the router is blocking the traffic.

**Comment by mikebrady** [comment]
I suspect you are right about the possibility of router issue. If there is a "WMM" setting, it is probably worth fiddling with it. Also, it's worth checking for router firmware updates.

**Comment by mikebrady** [comment]
To answer your question about kernel configuration, if Shairport Sync is visible on the 2.4 GHz network, it’s an indication that Bonjour/Zeroconf — which relies on multicast and which is used to advertise the player’s presence — Is working properly. So, I wouldn’t think any further configuration is necessary of Shairport Sync or of the machine its running on.

**Comment by mikebrady** [comment]
Okay to close this?

**Comment by George-ou812** [comment]
Yes.

**Comment by mikebrady** [comment]
Thanks.
