### ISSUE TITLE
Metadata ssncdapo never available.

### ISSUE THREAD

**Issue by Swancoat** [mikebrady/shairport-sync#623]
Pretty straightforward issue for me here. Everything works great on this, and I have a process set up that reads the metadata stream over UDP from another machine, but the source remote port data (ssncdapo) is never available. I'd like to be able to control the source and it works great if the source is just a computer playing iTunes (as the port defaults to 3689), but for iOS devices it varies.

Given that all of the other metadata shows up just fine, I can't imagine I have a setting wrong. Is this just a small bug?

**Comment by mikebrady** [comment]
Thanks for the post. I’ve been messing around with this, and might have broken it. I’ll check.

**Comment by mikebrady** [comment]
I did a quick check just now, from iTunes on a Mac and then from the Music App on an iPad into the sample metadata reader:
```
$ ./shairport-sync-metadata-reader < /tmp/shairport-sync-metadata 
Client's IP: "192.168.50.62".
"ssnc" "svip": "192.168.50.90".
Client's IP: "192.168.50.62".
"ssnc" "svip": "192.168.50.90".
"ssnc" "snua": "iTunes/12.7.1 (Macintosh; OS X 10.13.1)".
"ssnc" "acre": "3128682323".
"ssnc" "daid": "F18FE780B35CFD8D".
"ssnc" "pbeg": "".
"ssnc" "pfls": "".
"ssnc" "dapo": "3689".
"ssnc" "pvol": "-12.59,-21.92,-96.30,0.00".
"ssnc" "pvol": "-12.59,-21.92,-96.30,0.00".
"ssnc" "mdst": "3138783670".
Album Name: "Rachmaninoff - Complete Works for Piano and Orchestra".
Artist: "Zoltan Kocsis; San Francisco Symphony Orchestra; Edo de Waart".
Comment: "".
Composer: "Sergei Rachmaninov".
Genre: "Classical".
File kind: "Apple Lossless audio file".
Title: "Piano Concerto No. 2 in C minor, Op. 18 - Moderato".
Sort as: "".
"ssnc" "mden": "3138783670".
"ssnc" "pcst": "3138783670".
Picture received, length 0 bytes.
"ssnc" "pcen": "3138783670".
"ssnc" "prgr": "3131575734/3138783670/3157065534".
"ssnc" "prsm": "".
Client's IP: "192.168.50.19".
"ssnc" "svip": "192.168.50.90".
"ssnc" "snua": "AirPlay/354.54.6".
"ssnc" "acre": "785308044".
"ssnc" "daid": "D1BCC26DDD63F800".
"ssnc" "pbeg": "".
"ssnc" "dapo": "53965".
"ssnc" "flsr": "530013794".
"ssnc" "pfls": "".
"ssnc" "pcst": "530008282".
Picture received, length 97532 bytes.
"ssnc" "pcen": "530008282".
"ssnc" "flsr": "530016427".
"ssnc" "pfls": "".
"ssnc" "mdst": "530010918".
Album Name: "Alison Krauss & Union Station: Live".
Artist: "Alison Krauss & Union Station".
Composer: "Allyson Taylor & Larry Brown".
Genre: "Country".
Title: "Stay".
"ssnc" "mden": "530010918".
"ssnc" "pcst": "530011622".
Picture received, length 97532 bytes.
"ssnc" "pcen": "530011622".
"ssnc" "mdst": "530023942".
Album Name: "Alison Krauss & Union Station: Live".
Artist: "Alison Krauss & Union Station".
Composer: "Allyson Taylor & Larry Brown".
Genre: "Country".
Title: "Stay".
"ssnc" "mden": "530023942".
"ssnc" "prgr": "530014715/530023942/538682875".
"ssnc" "prsm": "".
```
BTW, that `"ssnc" "dapo"` message is new, and it currently only available in the `development` branch.

**Comment by Swancoat** [comment]
Wow - First if all, thank you so much not only for addressing this, but addressing it so quickly. I’m extremely grateful.

Secondly, if you wouldn’t mind a quick bit of advice (I’m a hobbyist and pretty inexperienced with Unix/Linux/etc...).

I’ve managed to update versions of Shairport-sync in the past with success. But to install the development branch: Do I just add the ‘git checkout development’ line prior to autoreconf? (If so, does that preserve my config file, etc?). Sorry for such a beginner question (I’m punching above my weight with this whole process!)

Thanks again!!!

Jeremy

**Comment by mikebrady** [comment]
Hi Jeremy, and thanks for the kind words. Your idea is correct. Add `$ git checkout development` just prior to the `$autoreconf -fi`. You'll than have to run the `./configure...` stuff the same as before. (The README.md note is slightly different in the `development` branch, and I hope it would resolve most of your questions.)

**Comment by mikebrady** [comment]
Okay to closed this?

**Comment by Swancoat** [comment]
YES! working great - thank you!

JS

**Comment by mikebrady** [comment]
Cool thanks.
