### ISSUE TITLE
Assertion error with pulseaudio back-end

### ISSUE THREAD

**Issue by hdante** [mikebrady/shairport-sync#624]
Hello, I'm forwarding this issue:

https://bugs.archlinux.org/task/56439

Description is replicated here:
Description:
nov 24 20:51:09 baerlon shairport-sync[337]: shairport-sync: audio_pa.c:91: init: Assertion `pa_context_connect(context, NULL, PA_CONTEXT_NOAUTOSPAWN,

Additional info:
* package version(s)
shairport-sync 3.1.4-1
* config and/or log files etc.
nov 24 20:51:10 baerlon systemd-coredump[356]: Process 337 (shairport-sync) of user 994 dumped core.

<pre>
Stack trace of thread 337:
#0 0x00007f315b63f8a0 raise (libc.so.6)
#1 0x00007f315b640f09 abort (libc.so.6)
#2 0x00007f315b6380dc __assert_fail_base (libc.so.6)
#3 0x00007f315b638153 __assert_fail (libc.so.6)
#4 0x000055955fe1e2b3 n/a (shairport-sync)
#5 0x000055955fe0ba76 main (shairport-sync)
#6 0x00007f315b62bf6a __libc_start_main (libc.so.6)
#7 0x000055955fe0c66a n/a (shairport-sync)

Stack trace of thread 351:
#0 0x00007f315b701471 __clone (libc.so.6)
#1 0x0000000000000000 n/a (n/a)
</pre>

Steps to reproduce:
- Install shairport-sync
- Uncomment output back-end line: output_backend = "pa";
- systemctl start shairport-sync
- assertion failed

**Comment by mikebrady** [comment]
Thanks for the report. I’ll have a look at this in the next week or so. Can you say anything about the exact environment this happens in please?

**Comment by hdante** [comment]
Hello, it's Arch Linux amd64 running systemd, gdm, gnome shell and pulse audio.

**Comment by mikebrady** [comment]
Great, thanks.

**Comment by anatol** [comment]
@hdante you will get more information about `#4 0x000055955fe1e2b3 n/a (shairport-sync)` frame if you recompile the Arch package with `debug !strip` options.

**Comment by hdante** [comment]
That address is audio_pa.c line 91, where the assertion error happens.

**Comment by mikebrady** [comment]
Very useful, thanks.

**Comment by mikebrady** [comment]
Okay, so I haven't got an Arch Linux running yet, but I have pushed an update to `audio_pa.c` with (I hope) a diagnostic message logging what has happened. I'd be grateful if you could try it out please. 

It seems this might indicate a more general issue with pulseaudio configuration, e.g. see [here](https://www.reddit.com/r/linux_gaming/comments/5tidzc/a_solution_for_pulseaudio_pa_context_connect/). If so, while I could make Shairport Sync handle the problem more gracefully, I would not actually be able to fix the problem, as it would be beyond the scope of Shairport Sync. What do you think?

**Comment by hdante** [comment]
Hello, ok, I'll try the patched version and I'll give you an update, but if the problem is the "hand-over" that happens with pulseaudio when the user logs in and acquires the seat, I think it would make sense that shairport did something similar. I don't know how the hand-over procedure works to give more details.

**Comment by anatol** [comment]
Could it be related to this bug https://github.com/mikebrady/shairport-sync/issues/556

**Comment by mikebrady** [comment]
@anato, thanks for the post. I think there’s a good chance it is the same alright.

**Comment by muesli4** [comment]
I temporarily fixed this by running **shairport-sync** as a user service. For that I slightly modified the service file:

```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
#Requires=avahi-daemon.service
#After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/bin/shairport-sync

[Install]
WantedBy=multi-user.target
```
Unfortunately, then you don't get the dependency to **libavahi-daemon**. (I also don't know whether this works on boot then.) What I usually do instead is just pass in the user it should run as as parameter (with filename `shairport-sync-user@.service`, the `@` is important):
```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/bin/shairport-sync
User=%i

[Install]
WantedBy=multi-user.target
```
Then you can start it with `systemctl start shairport-sync-user@user`. However, this time it didn't work (same error) and I don't know why. Maybe something from the environment is missing.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
