### ISSUE TITLE
Having trouble running cvlc from golang program after killing shairport-sync

### ISSUE THREAD

**Issue by gilgameshskytrooper** [mikebrady/shairport-sync#625]
I have written the following program in golang as part of my alarm clock program, which plays a song via a shell command to `cvlc` when a user supplied alarm time matches the current time.

```
var playsound = exec.Command("cvlc", "/home/pi/go/src/github.com/gilgameshskytrooper/prometheus/public/assets/Break The Bans-I'm In Love With U Tonight.mp3")
errrrror := playsound.Start()
if errrrror != nil {
    fmt.Println("ERRRRRROR")
}
```

The above execution is stopped via this command:

```
errrrrorkill := playsound.Process.Kill()
if errrrrorkill != nil {
    fmt.Println("ERRRRRROR")
}
```

Up until today when I installed shairport-sync, I was able play songs without any trouble (albeit, I had to modify the settings of VLC through the VLC gui application which is a peculiar way to do things). However, according to [this](https://github.com/mikebrady/shairport-sync/issues/519), "requires exclusive access to a hardware sound card."

Hence, I modified my code to kill the shairport-sync daemon before attempting to start the cvlc shell command:

```
shairportkill := exec.Command("shairport-sync", "-k")
shairportkillerror := shairportkill.Run()
if shairportkillerror != nil {
    fmt.Println("Could not kill shairport-sync daemon")
}
//Sleep so that there is enough time to kill the running shairport-sync daemon
time.Sleep(time.Second * 15)

var playsound = exec.Command("cvlc", utils.Pwd()+"/public/assets/"+Soundname)
errrrror := playsound.Start()
if errrrror != nil {
    fmt.Println("ERRRRRROR")
}
var playsound = exec.Command("cvlc", "/home/pi/go/src/github.com/gilgameshskytrooper/prometheus/public/assets/Break The Bans-I'm In Love With U Tonight.mp3")
errrrror := playsound.Start()
if errrrror != nil {
    fmt.Println("ERRRRRROR")
}
```

However, running this code still does not work.

The weird thing is that doing what my code is supposed to do manually in bash will do what I want:

```
$shairport-sync -v
Daemon already running on PID [PID NUMBER]
$sudo shairport-sync -k
$cvlc /home/pi/go/src/github.com/gilgameshskytrooper/prometheus/public/assets/Break The Bans-I'm In Love With U Tonight.mp3
```

I guess there is a lot of moving parts, but I have no idea why this wouldn't be working. Any help in this area would be much appreciated.

If you are interested in seeing my main project, check out [this link](https://github.com/gilgameshskytrooper/prometheus)

**Comment by mikebrady** [comment]
Could it be a permissions issue? I see you use `sudo ...` from the command line, but not in there script.

**Comment by gilgameshskytrooper** [comment]
im launching the program from rc.local so this should not be the issue. furthermore, I am putting some extensive logging, and if it was a permissions issue, it would let me know.

**Comment by mikebrady** [comment]
Thanks for the update. Have you enabled login in Shairport Sync?

**Comment by mikebrady** [comment]
Another possibility is that the script can’t find the executable. Try putting in the full path to it — for example, if it’s at `/use/local/bin/shairport-sync` then put that into the script. (The PATH settings in the environment `rc.local` runs in will be different to a login shell.)

**Comment by gilgameshskytrooper** [comment]
Hey mike, thanks for your help. The problem was trying to start `cvlc` from root (since my program gets run by `rc.local`). VLC bans root from opening the program. So once I fixed this, I am good to go.

Although now I'm hitting a different issue: will open a new issue

Thanks a bunch
