### ISSUE TITLE
iOS 11.2 - iPhone X

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#627]
Greetings,

Interesting issue this one. I begin play music from the iPhone via Airplay to my Pi.

Have the volume at 50%-ish... hit pause... wait for the iPhone Screen to go black (30 secs), tap the screen to wake.. now tap the pause button to being play..

While the the volume slider is still at 50-ish the volume of the Pi is now at full blast!

slide the volume down to 40%-ish and then the volume matches again.

This an iOS issue or a Shairport Issue?

Version: "3.1.4-OpenSSL-Avahi-ALSA-stdout-sysconfdir:/etc"

**Comment by mikebrady** [comment]
Thanks for the post. Can you post the settiings you are using please? I’d like to try to reproduce it.

**Comment by mikebrady** [comment]
Just a quick clarification. After you tap the screen to wake, the button you press is the “play” button in the Music App, correct? (In other words, it’s not in that system-wide play controls screen you sometimes get on a locked screen, is it?)

**Comment by mikebrady** [comment]
A quick check with an iPhone 6 and iOS 11.2 reveals normal behaviour. It could be an iPhone X specific bug, or it could be a legitimate use of AirPlay that’s never been seen before — Remember, we don’t actually have a specification :)

**Comment by thejacko12354** [comment]
@mikebrady @rockrabbit  I'll test it as soon as I'm home ;)

**Comment by rockrabbit** [comment]
Thinking this is iOS 11.2 specific. I have the newest iPad where the exact same issue is present.

So now I'm thinking that this either Jesse + Shairport specific.

`sudo ./configure --with-alsa --with-avahi --with-systemd --with-apple-alac --with-stdout --sysconfdir=/etc --with-ssl=openssl`

@mikebrady just tell me what else you need or need me to do to help debug this?

**Comment by mikebrady** [comment]
Great – it means it should be possible to reproduce and investigate the issue. It could be a bug or a missing feature in Shairport Sync.

**Comment by mikebrady** [comment]
Could you list the exact sequence you followed on the iPad please?

**Comment by rockrabbit** [comment]
1. Open Music App on iPad

2. Press Shuffle

3. Press AirPlay Icon

4. Select : PiZero

Observe : Music is now playing on PiZero at volume set on iPad

5. Press the Lock Button

6. Press the Lock Button again

7. On the Lock Screen note music playing, now press Pause

8. Press the Lock Button

9. Wait a few seconds

10. Press the Lock Button

11. Press Play

Observe : Music in now playing a full blast, even though the volume has not been touched

12. Drag music slider down

Observe : Music now playing at correct relative volume

**Comment by mikebrady** [comment]
Cool, thanks. I'll try it out when I Can.

**Comment by rockrabbit** [comment]
Last login: Fri Dec  8 07:19:50 on console
Manic-Mini:~ andrew$ ssh pi@10.0.1.10
Linux PiZero 4.9.67+ #1061 Tue Dec 5 16:53:41 GMT 2017 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Dec  7 18:38:52 2017 from 10.0.1.225

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@PiZero:~ $ sudo nano /etc/shairport-sync.conf





























  GNU nano 2.7.4                                               File: /etc/shairport-sync.conf                                                         

// Sample Configuration File for Shairport Sync
// Commented out settings are generally the defaults, except where noted.

// General Settings
general =
{
        name = "PiZero"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
//              The default is "Hostname" -- i.e. the machine's hostname with the first letter capitalised (ASCII only.)
//              You can use the following substitutions:
//                              %h for the hostname,
//                              %H for the Hostname (i.e. with first letter capitalised (ASCII only)),
//                              %v for the version number, e.g. 3.0 and
//                              %V for the full version string, e.g. 3.0-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc
//              Overall length can not exceed 50 characters. Example: "Shairport Sync %v on %H".
//      password = "secret"; // leave this commented out if you don't want to require a password
//      interpolation = "basic"; // aka "stuffing". Default is "basic", alternative is "soxr". Use "soxr" only if you have a reasonably fast processo$
        output_backend = "alsa"; // Run "shairport-sync -h" to get a list of all output_backends, e.g. "alsa", "pipe", "stdout". The default is the f$
//      mdns_backend = "avahi"; // Run "shairport-sync -h" to get a list of all mdns_backends. The default is the first one.
//      port = 5000; // Listen for service requests on this port
//      udp_port_base = 6001; // start allocating UDP ports from this port number when needed
//      udp_port_range = 100; // look for free ports in this number of places, starting at the UDP port base. Allow at least 10, though only three ar$
//      statistics = "no"; // set to "yes" to print statistics in the log
//      drift_tolerance_in_seconds = 0.002; // allow a timing error of this number of seconds of drift away from exact synchronisation before attempt$
//      resync_threshold_in_seconds = 0.050; // a synchronisation error greater than this number of seconds will cause resynchronisation; 0 disables $
//      log_verbosity = 2; // "0" means no debug verbosity, "3" is most verbose.

//      ignore_volume_control = "no"; // set this to "yes" if you want the volume to be at 100% no matter what the source's volume control is set to.
//      volume_range_db = 60 ; // use this advanced setting to set the range, in dB, you want between the maximum volume and the minimum volume. Rang$
//      volume_max_db = 0.0 ; // use this advanced setting, which must have a decimal point in it, to set the maximum volume, in dB, you wish to use.
//              The setting is for the hardware mixer, if chosen, or the software mixer otherwise. The value must be in the mixer's range (0.0 to -96$
//              Leave it commented out to use mixer's maximum volume.
//  run_this_when_volume_is_set = "/full/path/to/application/and/args"; //  Run the specified application whenever the volume control is set or chang$
//    The desired AirPlay volume is appended to the end of the command line – leave a space if you want it treated as an extra argument.
//    AirPlay volume goes from 0 to -30 and -144 means "mute".

//      regtype = "_raop._tcp"; // Use this advanced setting to set the service type and transport to be advertised by Zeroconf/Bonjour. Default is "$
//      playback_mode = "stereo"; // This can be "stereo", "mono", "reverse stereo", "both left" or "both right". Default is "stereo".
        alac_decoder = "apple"; // This can be "hammerton" or "apple". This advanced setting allows you to choose
//              the original Shairport decoder by David Hammerton or the Apple Lossless Audio Codec (ALAC) decoder written by Apple.
//      interface = "name"; // Use this advanced setting to specify the interface on which Shairport Sync should provide its service. Leave it commen$
                                                                  [ Read 143 lines ]
^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page    M-\ First Line  M-W WhereIs Next
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page    M-/ Last Line   M-] To Bracket

**Comment by rockrabbit** [comment]
These are my config settings.. no issue when playing through iTunes on the Mac.. this is just iOS where this issue is present.

Using a Pi Zero with a Pimoroni PHAT DAC


```
        name = "PiZero"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
        output_backend = "alsa"; // Run "shairport-sync -h" to get a list of all output_backends, e.g. "alsa", "pipe", "stdout". The default is the f$
        alac_decoder = "apple"; // This can be "hammerton" or "apple". This advanced setting allows you to choose

// These are parameters for the "alsa" audio back end.
alsa =
    output_device = "hw:0"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
    output_rate = 176400; // can be 44100, 88200, 176400 or 352800, but the device must have the capability.
    output_format = "S32"; // can be "U8", "S8", "S16", "S24", "S24_3LE", "S24_3BE" or "S32", but the device must have the capability. Except where s$
```

**Comment by mikebrady** [comment]
Thanks again. I'll get a good look at this over the weekend.

**Comment by Debilski** [comment]
Similar problem here on newest macOS (10.13.2) as well. Playing directly from iTunes to my Raspberry (and all other sound going through the MacBook speakers), everything is as it should be. But when I change the output device in the menu bar for the whole system, it will default to 100% loudness whenever a song is stopped and started again. Pressing F11 or F12 will automatically reduce it to the value it should have been.

**Comment by thejacko12354** [comment]
@rockrabbit @mikebrady I just tested it a few times with my iPhone X on iOS 11.2 and it just played it absolutely normal.

'''--version''' gives me this:

'''3.0.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc'''

**Comment by mikebrady** [comment]
Thanks @rockrabbit – I can reproduce the problem! Now, let me see about finding out out what's going on and fixing it.

**Comment by mikebrady** [comment]
When AirPlay pauses for more than a few seconds, the play session is terminated, i.e. torn down completely. When AirPlay starts *playing* again, it will start a new session and send a volume level. There is a change with the latest software, however: up until now, when AirPlay *resumes*, it would start a new session and send a volume level with it. But now, when it starts the new session it doesn't always send a volume level, and so Shairport Sync starts at the default 100%. So, the solution is to get Shairport Sync to remember the last volume level and use it by default, so that if no volume is set, it will use the last one. There might be more implications, so it might take a few days...

(My guess, FWIW, is that there is a lot of work going on at Apple re-engineering the AirPlay infrastructure to make is work in conjunction with AirPlay 2, and that this is an oversight.)

**Comment by rockrabbit** [comment]
@mikebrady While I'm thrilled to hear that this is not just me or an isolated incident, I'm yet again left shaking my head at Apple!

With a bit of hope the genius that is you, will have a solution and update to my beloved Shairport sooner than later to "fix" this!

**Comment by echamberlain** [comment]
@mikebrady I noticed a similar behavior prior to 11.2 while playing a song and then using Siri.  The volume would go to 100% for Siri’s tone and voice.  Then jump back to the prior volume level when the song resumed.

@rockrabbit this is why Apple has the MFi program for vendors using AirPlay.  AirPlay isn’t an open spec.

**Comment by mikebrady** [comment]
Thanks for that, Eric. Yeah, we can't really complain about Apple – after all, the spec has never been revealed, and this might be legitimate behaviour. Anyway, let's try to get a workaround.

**Comment by mikebrady** [comment]
Interestingly enough, this bug doesn't manifest itself if you're using a hardware mixer, as the mixer itself remembers the last setting automagically.

**Comment by mikebrady** [comment]
I just pushed out a release on the `development` branch which has a tentative fix for this problem. Would you be kind enough to try it out, please, and let me know if it's working?

**Comment by rockrabbit** [comment]
@mikebrady what do I need to do on my PI to pull the developer release?

**Comment by mikebrady** [comment]
I'm guessing you already built the regular `master` version. If so, look at the UPDATING page, and just after you have done the `$ cd shairport-sync`, do `$ git checkout development`. Then follow the rest of the procedure – everything else is the same. is that okay?

**Comment by rockrabbit** [comment]
updated to development. tested

problem solved!

**Comment by mikebrady** [comment]
Great. I might tidy the thing up before I put it the master branch. I’m glad it worked.

**Comment by mikebrady** [comment]
@echamberlain, I'm not sure whether the behaviour with Siri is related to this. Am I right in thinking that the scenario is where you are playing some musing via Shairport Sync, you call up Siri and then let the music resume?

**Comment by echamberlain** [comment]
@mikebrady yes.  The volume would go loud with Siri.

I’ll give the new update a try and see if the issue is still reproducible.

**Comment by echamberlain** [comment]
@mikebrady I'm unable to reproduce the Siri issue with the latest release.  Great work.

**Comment by mikebrady** [comment]
Thanks for that. I'll push the fix to the `master` branch in the next few days.

**Comment by mikebrady** [comment]
I’ve just pushed an update to the `master` branch as a pre-release.

**Comment by charlesvestal** [comment]
Confirming I had this issue and the update has resolved it!

**Comment by Debilski** [comment]
Seems also to solve the problems on High Sierra. Thanks!
