### ISSUE TITLE
Failed to attach mixer

### ISSUE THREAD

**Issue by tobx** [mikebrady/shairport-sync#628]
Hi,

I build shairport-sync as described here on Debian. Now, when the system reboots, I get the following error message and cannot find shairport-sync as AirPlay device:

```
$ service shairport-sync status
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-12-08 12:07:50 CET; 11min ago
 Main PID: 424 (shairport-sync)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/shairport-sync.service
           └─424 /usr/local/bin/shairport-sync

Dec 08 12:07:50 <hostname> systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Dec 08 12:07:50 <hostname> shairport-sync[424]: fatal error: Failed to attach mixer
root@obelix:~$ nano /lib/systemd/system/shairport-sync.service 
```

Relevant part: `fatal error: Failed to attach mixer`

After `service shairport-sync restart` everything works as expected.

`/lib/systemd/system/shairport-sync.service` should be fine:

```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/local/bin/shairport-sync
User=shairport-sync
Group=shairport-sync

[Install]
WantedBy=multi-user.target
```

Any ideas?

**Comment by mikebrady** [comment]
Thanks for the post. Can you say what kind of a system it's running on please? 

Off hand, I'd guess that Shairport Sync is being started up before the output device has become ready. If you could add a delay to the launch of the service of maybe ten seconds, you might find that everything is okay.

**Comment by tobx** [comment]
I am running Debian Stretch on a Desktop machine, but your tip was very helpful. I was thinking how to start the service after the mixers get loaded, but a delay did not come to mind :). So I googled for it and found [systemd timers](https://www.freedesktop.org/software/systemd/man/systemd.timer.html). 

Here is my solution in case someone has the same problem:

Create a `shairport-sync.timer` file in the same folder as the `shairport-sync.service` file (`/lib/systemd/system/shairport-sync.timer`) with the following content:

```
[Unit]
Description=Delay Shairport Sync start
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Timer]
OnActiveSec=5

[Install]
WantedBy=multi-user.target
```

Disable `shairport-sync.service` and enable `shairport-sync.timer`:

```bash
systemctl disable shairport-sync.service
systemctl enable shairport-sync.timer
```

**Comment by mikebrady** [comment]
Great work, thanks. I might put this in the troubleshooting page.

**Comment by jkiddo** [comment]
@tobx that fix worked like a charm on my ol' raspberry 1 b+ where it was an issue. It didn't occur on the model 3's
