### ISSUE TITLE
Shairport sync on new Synology 64Bit Nas

### ISSUE THREAD

**Issue by Pommmmes** [mikebrady/shairport-sync#629]
Hi,
First of all thanks for Shairport sync!
I used to run Shairport Sync on my Synology Ds216j and it worked flawlessly. 
Now I migrated to a new 64Bit Ds418j
and the Shairport package doesn’t show anymore. Is this because of the new 64Bit architecture of the nas?
I am completely new to Linux , wonder that I was even able to find this place here and get Shairport to work on the old nas:-)

**Comment by mikebrady** [comment]
Thanks for the post. I am not familiar with the new Ds418j, I'm afraid.

The availability of Shairport Sync for Synology depends on an enthusiast building it and making it available. I suggest checking on the [Synology Community Forum](https://forum.synology.com/enu/viewforum.php?f=190).

**Comment by mikebrady** [comment]
Is it okay to close this?

**Comment by Pommmmes** [comment]
Yes sure, thank you

Best Regards
Thomas Sawera

**Comment by mikebrady** [comment]
Thanks.
