### ISSUE TITLE
pops pressing pause or changing track from iTunes on Windows

### ISSUE THREAD

**Issue by Hamster128** [mikebrady/shairport-sync#63]
the function buffer_get_frame() in player.c has a bug.
curframe is not initialized which leads to this problem, because if flush_requested==1 the loop is left without setting curframe. Also some checks of curframe after the main loop should be fixed.

the second problem is the atoi() funcition in rtsp.c handle_flush(), which returns 0x7fffffff if a value >0x7fffffff is received. This value is interpreted as don`t flush anything and leads to "pop" noise.
I have changed the function ot atoll() (atol() ether not working), and changed the special value from 0x7fffffff to 0x0 = flush off, and had no longer any "pop" noise

**Comment by mikebrady** [comment]
Thanks for looking at this. I'll check over your points over the next few days and report back. Can you tell me what output device (DAC) you are using please?

**Comment by Hamster128** [comment]
I have a "Wadia 151 PowerDAC mini“ connected.
http://www.digitalaudioreview.net/2013/03/wadia-151powerdac-mini-amplifier-review/ <http://www.digitalaudioreview.net/2013/03/wadia-151powerdac-mini-amplifier-review/>


Greetings
Henry

**Comment by mikebrady** [comment]
Thanks – that's interesting; I hadn't come across that unit. Looking at the popping issue now.

**Comment by mikebrady** [comment]
I just pushed a fix for the second of the two issues you mentioned, and I'd be glad if you'd try it out. Still looking at the first issue.

**Comment by mikebrady** [comment]
Hi there. Thanks for looking at these issues. I'm just looking as the first of the two issues, trying to understand your comment.

My reasoning is as follows: If `ab_synced` is true (line 445 of player.c in the development branch, 2.3), then `curframe` is initialised alright (line 447). `buffer_get_frame()` cannot exit until `ab_synced` becomes `true` (line 578), which, when detected, will cause `curframe` to be initialised (line 447). `ab_synced` is made `true` by `ab_resync()`, which is called, (among other times), when `flush_requested` is `true`.

Or am I missing something?

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
