### ISSUE TITLE
Add and install sysusers.d systemd file

### ISSUE THREAD

**Issue by anatol** [mikebrady/shairport-sync#630]
systemd has a nice declarative way to describe users/groups that need to be created by the installer. See https://www.freedesktop.org/software/systemd/man/sysusers.d.html

Please add sysusers file and install it if `systemd` is enabled.

**Comment by mikebrady** [comment]
Thanks for this. Could you tell me what benefit it might bring?

**Comment by anatol** [comment]
Main advantage for me as a package manager is unification. Instead of having imperative way of user checking/creation that varies from project-to-project and distro-to-distro, we will have one simple and clean way to manage it.

A bit more information can be found in this blogpost http://0pointer.net/blog/projects/stateless.html

**Comment by anatol** [comment]
I created a sysusers file that I think should work

```
u shairport-sync - "ShairportSync AirPort receiver" /var/lib/shairport-sync
g shairport-sync
m shairport-sync audio
```

The file should be installed as `/var/lib/shairport-sync`

**Comment by mikebrady** [comment]
Thanks for this -- I've been having a look at this. Do you happen to know if support for it is widespread? I'm concerned perhaps that older systemd systems might not have the support. What do you think?

BTW, if I read the spec correctly, the second line of the sysusers file is not needed.

**Comment by anatol** [comment]
`sysusers` is a standard systemd tool that aims to replace manual users/groups management. The tool has been added to systemd codebase around 2014. Arch/Debian and probably other systemd-based Linux distros already have support for `sysusers`.

**Comment by mikebrady** [comment]
Thanks. I'm just looking at trying this out, and I have another quick question, if you don't mind. (Excuse my ignorance on this -- the online discussions on this are confusing and rather doctrinaire in tone...)

Your example has `/var/lib/shairport-sync` as a home directory  for Shairport Sync. For the moment, Shairport Sync doesn't have home directory, but if it did, why would `/var/lib/shairport-sync` be the right one? 

Then there's the `/run` directory. It seems `/var` is guaranteed to be writable and *may* be preserved across power cycles (not in an embedded Linux though), whereas `/run` will always be erased by a power cycle -- did I get that right?

**Comment by anatol** [comment]
> why would /var/lib/shairport-sync be the right one?

I see that many Arch system users use `/var/lib` for their HOME dirs. I am following common practice here but I am not 100% confident that is the standard solution. You might want to consult "Filesystem Hierarchy Standard", it might answer your question.

**Comment by mikebrady** [comment]
Thanks.

**Comment by mikebrady** [comment]
Hello again. I just did a bit of investigation. There is no `sysusers.d` directory on Ubuntu 17.10 (or 16.04). If I manually create one and put the suggested `shairport-sync.conf` file into it and then reboot, it doesn't appear to have any effect. So, unless there is something wrong with my method, I'm thinking that support for `sysusers.d` might not be sufficiently widespread yet. To support it would require a installation-time check for the existence of the `sysusers.d` directory, and, apart from the added complexity, it seems to defeat the purpose of a declarative approach to system user and group definition. What do you think?

**Comment by mikebrady** [comment]
Might come back to this in the future when suppport is more widespread...

**Comment by SchoolGuy** [comment]
Stumbled across this via Google. openSUSE has Support for this and deprecated the "old way" as of a few weeks/months now.

Help can be found in the wiki article for it: https://en.opensuse.org/openSUSE:Packaging_guidelines#Users_and_Groups
