### ISSUE TITLE
xcb_connection_has_error() returned true

### ISSUE THREAD

**Issue by chapter09** [mikebrady/shairport-sync#632]
I get this `xcb_connection_has_error() returned true` error when my device was connecting to the Raspberry Pi 3. 

For most time, there's still clear sound streaming to the speaker, but sometimes there's no sound at all.

I guess it's the error from `pulseaudio` but I don't know how to fix it.

**Comment by mikebrady** [comment]
Thanks for the post. If, by observation, you could figure out the circumstances that cause it to occur, so that it could be replicated, that would be great. BTW, is that the exact text of the error message?

**Comment by mikebrady** [comment]
Also, could you say what version of what OS you are using, please?

**Comment by mikebrady** [comment]
I’ll close this for the moment. Please feel free to reopen if there are further developments.

**Comment by superkoira** [comment]
fyi, I got this same error message after installing pulseaudio for my Raspi 3B+
(Need pulseaudio for Handsfree usage)

**Comment by fedon** [comment]
I can see this message only if I play sound (mpv, etc.) via ssh with X forward. PMOS (Alpine on arm64). No pulse ;) So, it definitely has nothing with Shairport :)
