### ISSUE TITLE
Error when install in DietPi

### ISSUE THREAD

**Issue by Renlong-Yin** [mikebrady/shairport-sync#633]
And shows the error message like below:

> Error 
> Unable to Install Shairport Sync: airplay audio player with    │ multiroom sync                                                     
> 
> http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1..0.1t-1+deb8u6_armhf.deb is offline and/or unreachable.   

    

I confirm that this verison is been removed in http://ftp.us.debian.org/debian/pool/main/o/openssl/, would you please fix it?

Best

**Comment by mikebrady** [comment]
Thanks for the post, but somebody else wold have built the DietPi packages. So, I think it would be better to ask the guys at DietPi to update the package. Maybe put a request in at http://dietpi.com/phpbb/viewforum.php?f=12.
