### ISSUE TITLE
The confuse with process principle of AirPlay in macOS

### ISSUE THREAD

**Issue by Renlong-Yin** [mikebrady/shairport-sync#634]
Hi, I would like to ask the different of AIrplay process in macOS and DietPi (Rasp. Pi). When install with`apt-get`, there would be two separate processes work concurrently in OS, which means that may enable Airplay in iTunes and, in the same time, be able to use internal speak also; 

Issues have been found since I have tried the installation from source today: there shows only one process when start up in macOS: only to choose DietPi (the AirPlay device) as primary audio output that could be able to use AirPlay in iTunes. That’s mean all the audio output would pass through AirPlay, instead of music from iTunes solely.

Would you please let me know how the issue occures?

The information attatched as following: 

`Linux DietPi 4.9.62-v7+`
`3.1.7-mbedTLS-Avahi-ALSA-stdout-pipe-soxr-convolution-sysconfdir:/etc`

Compiling parameter:
`--with-alsa --with-stdout --with-pipe --with-avahi --with-ssl=openssl --with-ssl=mbedtls --with-soxr --with-piddir=/run/shairport-sync --with-pkg-config --with-apple-alac --with-convolution --with-systemd --with-systemv`

Thank you in advance and best wishes!

**Comment by mikebrady** [comment]
Hi there. Thanks for the post, but I'm afraid I just don't understand it. A could of general things I can say are:

Looking at your compilation parameters, you should choose `--with-systemd` or `--with-systemv` but not both.

Shairport Sync works as an AirPlay device – it can be chosen as one of a number of simultaneous output devices by iTunes or as the only output device by macOS. This is a feature or limitation of AirPlay, not of Shairport Sync itself.

**Comment by Renlong-Yin** [comment]
Hi, thank you for your reply. I would liket to let you know that AirPlay can able to playback simultaneously just by _one_ device, but in reality, it may able to choose _two_ output voice in the same time: one is the AirPlay device, another one is internal speaker of MacBook. Just a minor matter to be clear.

Best

**Comment by mikebrady** [comment]
Many thanks.
