### ISSUE TITLE
Is it possible to force Shairport Sync to output 32 bit in Volumio? (solved)

### ISSUE THREAD

**Issue by mc002b** [mikebrady/shairport-sync#637]
I‘ve the following problem:

I use Raspberry Pi 3, Soekris dam1021 DAC connected via I2S and actual Volumio. The Soekris DAC needs 32 bit at the I2S-Input. At Volumio I can force mpd to play with 32 bit with the classical Volumio  Music DB. When I use airplay, the Dac does not synchronize. This normally the case, when there is no 32 bit input. So I think, that the problem is solved, when I force shairport to 32 bit output. 

At this point I need a little bit help. Thanks....

Christian

**Comment by mikebrady** [comment]
Thanks for the post. It is indeed possible to set the output to 32 bit. In the configuration file `/etc/shairport-sync.conf`, set the `output_format` in the `alsa` group to `S32` to get signed 32-bit output. Remember to uncomment the line by removing the `//` at the start of the line. You’’ll need to restart Shairport Sync — it might be just as easy to reboot the machine. (You can look in the sample configuration file at `/etc/shairport-sync.conf.sample` for reference.)

**Comment by mc002b** [comment]
Hi Mike,

I‘ve seen this and I‘ve changed this parameter, but after the reboot Volumio seems to copy the old configuration file back, so the change is gone.

I havn‘t found the pisitiin where this can be changed.

Christian

Von meinem iPhone gesendet

**Comment by mc002b** [comment]
Hi Mike,

the problem is at Volumio. When I stop the Volumio service, change the shairport-sync.conf, start shairport-sync alone. All functions fine! So I have to ask Michelangelo from Volumio.org, where the output parameter could be inserted.

Christian

**Comment by mc002b** [comment]
Here is the place to change shairport-sync:

/volumio/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl

**Comment by mikebrady** [comment]
Very useful, thanks.

**Comment by mikebrady** [comment]
I just changed the title a little, to make it more explicit. I hope that’s okay.

**Comment by mc002b** [comment]
perfect 🤓
