### ISSUE TITLE
raspberry / one device at a time

### ISSUE THREAD

**Issue by gal1564** [mikebrady/shairport-sync#638]
hi,
I set up my raspberry pi 3  as an audio receiver and it works fine
But I have a problem when a device is connected to the raspberry other device can connect and disconnect the device that is already connected.
Is there an option to lock other devices from connecting while another device is connected?

**Comment by mikebrady** [comment]
Thanks for the post. I'm not sure what you mean, so let me say that what *should* happen is that, while a device is playing music to a Shairport Sync player, no other device can interrupt it and disconnect it. When the device has finished playing, then, after a few seconds, any other device can take over the Shairport Sync player.

There is a setting in the `sessioncontrol` section of the configuration file called `allow_session_interruption`. By default, this is set to `"no"`. If you change it to `"yes"`, then a play session can be interrupted by another device.

Does this explain the problem you are experiencing?

**Comment by mikebrady** [comment]
Closing this inactive issue. Please open a new one if necessary.
