### ISSUE TITLE
Unsure if shairport's fault: Popping noise when starting / stopping playback

### ISSUE THREAD

**Issue by senthor** [mikebrady/shairport-sync#64]
Hi,
everything's working super for me — thank you for your continued work and support.
I have one small issue, tho, and am not sure if it's shairport-sync's fault:
Whenever I start or stop playback (iTunes 12.1, OS X 10.10.2) I get a popping noise from my server (Ubuntu 14.0.4, shairport-sync 2.2.3-openssl-Avahi-ALSA-soxr, Realtek ALC892 on ASRock Q1900 DC-ITX), as if a headphone jack was plugged / unplugged. Once playing sound quality is great.
init-script:
```start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Zephyr HiFi" -S soxr --password=password -- -d hw:0 -t hardware -c "Front" || return 2```

Thank's a lot!

**Comment by senthor** [comment]
Not shaiport-sync's fault. Power management of sound card became somehow activated. For Intel HDA cards, disable with the following line added to ```/etc/rc.local``` before ``èxit```:
```echo 0 > /sys/module/snd_hda_intel/parameters/power_save```

**Comment by mikebrady** [comment]
Very useful, thanks.

**Comment by asakaev** [comment]
Same problem, but there is no power_save module parameter on USB audio interface.

**Comment by mikebrady** [comment]
Hi there -- I know it's an old issue, but [this](
https://github.com/mikebrady/shairport-sync/blob/development/RELEASENOTES.md#version-33d39-to-version-33d38) might be of interest — it certainly helps on I2S DACs.
