### ISSUE TITLE
Metadata not working

### ISSUE THREAD

**Issue by allstrike** [mikebrady/shairport-sync#641]
Hi everybody,

I read a few posts about the same problem but i didn't figured out how to resolve this.

here my version i installed "shairport-sync -V" : 

```3.1.7-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/usr/local/etc```

I configured my config file in "/usr/local/etc/shairport-sync.conf " : 
```
metadata =
{
        enabled = "yes"; // set this to yes to get Shairport Sync to solicit metadata from the sour$
        include_cover_art = "yes"; // set to "yes" to get Shairport Sync to solicit cover art from $
        pipe_name = "/tmp/shairport-sync-metadata";
        pipe_timeout = 5000; // wait for this number of milliseconds for a blocked pipe to unblock $
//      socket_address = "226.0.0.1"; // if set to a host name or IP address, UDP packets containin$
//      socket_port = 5555; // if socket_address is set, the port to send UDP packets to
//      socket_msglength = 65000; // the maximum packet size for any UDP metadata. This will be cli$
};
```

I looked at my permissions "ls -l  /tmp" :

```
total 16
drwx------ 2 pi             pi             4096 Jan  8 06:03 dhcpcd-(null)
prw-r--r-- 1 shairport-sync shairport-sync    0 Jan  8 06:03 shairport-sync-metadata
drwx------ 2 pi             pi             4096 Jan  8 06:03 ssh-lKoH7N2BFmkq
drwx------ 2 pi             pi             4096 Jan  8 06:03 ssh-sDzToy9g1TsU
drwx------ 3 root           root           4096 Jan  8 06:02 systemd-private-
```

so i tried to add write to shairport : 

```total 16
drwx------ 2 pi             pi             4096 Jan  8 06:03 dhcpcd-(null)
prw-rw-rw- 1 shairport-sync shairport-sync    0 Jan  8 06:03 shairport-sync-metadata
drwx------ 2 pi             pi             4096 Jan  8 06:03 ssh-lKoH7N2BFmkq
drwx------ 2 pi             pi             4096 Jan  8 06:03 ssh-sDzToy9g1TsU
drwx------ 3 root           root           4096 Jan  8 06:02 systemd-```


But i still have nothing in my folder, can you help me ?

**Comment by mikebrady** [comment]
Hi there. The metadata should be written into the pipe you have specified. But it's not a file -- it doesn't store anything -- you must take the metadata out of the other end of the pipe. A trivial example would be `$ cat /tmp/shairport-sync-metadata` which would send anything that comes into the pipe out to the standard output. For more, look at the sample code in [shairport-sync-metadata-reader](https://github.com/mikebrady/shairport-sync-metadata-reader). In that example, the output of the pipe is directed to the input of the metadata reader program.

**Comment by allstrike** [comment]
I installed this and effectively i receive the metadata. 

I have then a problem with [MMM-ShairportMetadata](https://github.com/surekap/MMM-ShairportMetadata) because i have nothing on my Screen.

Thanks for your help, i suppose you can't give me a hand for this.

**Comment by mikebrady** [comment]
Sorry — it’s beyond my expertise. It looks promising though.

**Comment by roblan** [comment]
@allstrike if you know js/node a little you could use https://www.npmjs.com/package/shairport-sync-reader there
