### ISSUE TITLE
I'm back at it again this time using wlan0

### ISSUE THREAD

**Issue by gilgameshskytrooper** [mikebrady/shairport-sync#642]
Hey Mike, thanks for all your help last time.

This time around, I am using a different set up (using the same Raspberry Pi). This time, I am using my own router connecting to my school's enterprise network. In theory (TC/IP protocol), since the connection should go directly from my Mac to the router, directly to the Pi, the enterprise network limitation for AirPlay shouldn't apply.

However, I am not able to see the shairport-sync server anywhere on my network. I can confirm that I can ssh from my computer to the Pi through the router.

I have tried `sudo ufw disable`, but it seems Pi does not come pre-installed with it. Any idea what might be the issue? The configuration of shairplay-sync remains exactly the same from last time when I was trying to connect via `eth0` (and getting initial success, but inevitably getting network connection lost).

Please let me know what other steps I should try before giving up completely.

Thanks

**Comment by min-xu-ai** [comment]
Dumb question: is your Pi and the airplay client (an iPhone) on the same subnet? I think airplay only works on the same subnet if I remember correctly.

What's output of `avahi-browse -a`? Maybe this page can help you debug it a bit:

https://raspberrypi.stackexchange.com/questions/22485/how-to-debug-avahi-daemon-hostname-not-coming-through

**Comment by mikebrady** [comment]
Hello again Andrew, and hi to Min. Min's suggestion to use `avahi-browse -a` on the Pi is a good one, and at the Mac end you can use the application [Bonjour Browser](http://www.tildesoft.com) on your Mac and its equivalent [Discovery - DNS-SD Browser](https://itunes.apple.com/ie/app/discovery-dns-sd-browser/id305441017?mt=8) for you iOS devices. You should be able to see what's being advertised and how far the Bonjour signals are propagating.

**Comment by mikebrady** [comment]
BTW, I've never had any problem with a firewall on *standard* Raspian installations. It's only been on Windows PCs and some routers that there have been occasional problems.

**Comment by gilgameshskytrooper** [comment]
@min-xu-ai I believe I am on the same subnet because of the following: 

As I said, the router I am using connects via ethernet connection to my school's enterprise network at large. The IP's assigned by the devices that are attached to the router are in the subnet range 192.168.11.0-192.168.11.255 (my Pi specifically is on 192.168.11.4, my computer is on 192.168.11.3 (while the IP's assigned to my school's enterprise network start with 130...

Furthermore, to test, I tried to ssh to the Pi (192 IP range) from the enterprise network (130... IP range), and got `no route to host`.

Hence, I think I am on my own subnet.

Doing `avahi-browse -a` shows nothing at all while using Discovery - DNS-SD Browser (on my Phone running the same network from my router) shows many services being advertised on my Macbook, but not the shairport-sync server on the Pi.

**Comment by min-xu-ai** [comment]
maybe avahi daemon is not running or is having problems? My pi shows a lot of output from avahi-browse even when shairport is not running.

**Comment by gilgameshskytrooper** [comment]
```
pi@raspberrypi:~ $ ps ax | grep avahi
  489 ?        Ss     0:00 avahi-daemon: running [raspberrypi.local]
  499 ?        S      0:00 avahi-daemon: chroot helper
18197 pts/0    S+     0:00 grep --color=auto avahi
```

**Comment by min-xu-ai** [comment]
How is shairport-sync compiled and started? `ps -ef|grep shairport`?

I would focus on the Pi box since avahi-browse -a shouldn't return nothing. If shairport is registered correctly, it should at least show that.

**Comment by gilgameshskytrooper** [comment]
```
pi@raspberrypi:~ $ ps -ef | grep shairport
root      6585     1  0 Jan09 ?        00:00:00 shairport-sync -d
pi       18984 17179  0 00:05 pts/0    00:00:00 grep --color=auto shairport
```

I never set up a `systemd` service for shairport-sync because I start shairport-sync via a program that I am starting in `rc.local`.

The program (which is called by root), calls `shairport-sync -d`

Although I highly doubt it (as the same boot sequence with the same configurations (*[at least temporarily](https://github.com/mikebrady/shairport-sync/issues/626)*) when I am using the `eth0` interface), it is possible that it is starting shairport-sync (and by extension, the `avahi-daemon`) is starting too early in the initialization sequence.

**Comment by min-xu-ai** [comment]
why not try restart it by hand and dump avahi browse -a again?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikebrady** [comment]
Thanks for this. I agree with Min's line of approach.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue due to inactivity. Please open a new one if necessary.

**Comment by gilgameshskytrooper** [comment]
Sorry for the delay in closing. For anyone interested, this had everything to do with the horrible router I was using. The moment I bought a fast mesh router (in my case Orbi), Shairport-Sync worked like a charm.

Thanks again.

**Comment by mikebrady** [comment]
Excellent, thanks.
