### ISSUE TITLE
[3.1.7] Synchronisation seems to be broken

### ISSUE THREAD

**Issue by Mmoi-Fr** [mikebrady/shairport-sync#647]
HI,

I updated to 3.1.7 sable version and it sems that I lost the synchronisation.
I played some youtube videos and the audio wasn't synced with the video (can't tell if it's too late or too soon).

3.1.4 is OK.
IOS 11.1.2, Raspbian (Debian 8 - kernel 4.14.12-v7+), compiled version with "--sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata".

Just wanted to warn.

**Comment by mikebrady** [comment]
Thanks for the post. Could you say what browser you’re using and what version of the Mac (?) OS you are on please?

**Comment by Mmoi-Fr** [comment]
I use an iPhone (6s) on IOS 11.1.2 with the official youtube app.

**Comment by mikebrady** [comment]
Many thanks. Some changes have been made to the latency calculations recently because I think something changed in AirPlay. So I have experimented further in the `development` branch. Would you be kind enough to try it? On 11.2.1 on an iPhone 6, it sounds right to me, but I’m going to check again once I’ve updated to 11.2.2.

**Comment by mikebrady** [comment]
By the way, is it possible that you are using anything that might introduce an extra delay, such as Bluetooth output devices or [some] entertainment systems or sound Bars?

**Comment by Mmoi-Fr** [comment]
I gonna test the development branch tonigth. The iPhone is over WiFi (5GHz), then the router sends the straffic to the raspberry via ethernet and that one outputs the sound directly via mini jack.

**Comment by Mmoi-Fr** [comment]
Version: "3.2d23-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc"
The development branch is working fine!

**Comment by mikebrady** [comment]
Thanks for the update.

**Comment by mikebrady** [comment]
It may be a little while before this `development` version becomes part of the `master` branch, as there are other things in the `development` branch that need to be baked some more beforehand...

**Comment by Mmoi-Fr** [comment]
So,

Here is a video of the problem (200ms delay, if I my measures are good): http://uptobox.com/rop2xfqaudaq . The first pass is via the 3.2RC5 version and the second with the 3.2d28 version).
The audio jack is directly connected to a jack stereo (https://soysuper.com/p/altavoces-auchan-sp2-1-10-auc-black#product-gallery-modal). I don’t think it’s hardware related as the other version works. Adding that, when the computer use those speakers, I do not have any delay.

Thanks for the reply support

**Comment by mikebrady** [comment]
Thanks for the information. My guess is that the stereo amplifier is introducing the delay — it Would explain everything. It’s easy to check — just try using normal headphones instead of the stereo to check the synchronisation. (Do not use Bluetooth or echo-cancelling headphones, because the also have their own processing delays. Best of all are plain ordinary wired headphones.) If the audio is in sync using headphones and out of sync using the stereo, then the stereo is introducing the delay and you can compensate for the delay using the `audio_backend_latency_offset_in_seconds` setting.

**Comment by Mmoi-Fr** [comment]
I just tested with the iphone's basic jack headphones. Still same results.

**Comment by Mmoi-Fr** [comment]
When I use the -v option to check the parameters, apart of the version number, only the following line is added: "diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately."

**Comment by mikebrady** [comment]
Thanks. I hope you won’t mind me checking that you were using the headphones in the Pi’s jack, not the jack on the stereo. Sorry for the somewhat insulting question — it’s not intended.

**Comment by Mmoi-Fr** [comment]
I did some tech support, I totally understand the question :)
Yes, plugged directly in the RPI jack

**Comment by mikebrady** [comment]
Thanks. What are you using to play that video on the iPhone? It's not YouTube, by the look of it...

**Comment by Mmoi-Fr** [comment]
It was Safari. But I have the same delay via the youtube app itself.

**Comment by mikebrady** [comment]
Most peculiar. Whats really odd is that the audio in your case is *ahead* of the video.
I tried, without success, to replicate your problem. [Here](http://uptobox.com/ixhbi3ty7giw) is the setup using the iPhone 6's built-in speaker and [here](http://uptobox.com/4a1e0ivznved) is the setup with Shairport Sync powered room speakers.

Could you turn on Shairport Sync with a log verbosity of 1 in the configuration file, restart Shairport Sync and post the startup messages please? The will log something like this:
```
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: alsa output device name is "hw:1".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: Hardware mixer has dB volume from -45.000000 to 0.000000.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: Version: "3.2RC5-mbedTLS-Avahi-ALSA-metadata-dbus-mpris-sysconfdir:/etc"
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: statistics_requester status is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: daemon status is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: deamon pid file is "/var/run/shairport-sync/shairport-sync.pid".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: rtsp listening port is 5000.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: udp base port is 6001.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: udp port range is 100.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: player name is "Raspberrypi3w".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: backend is "(null)".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: on-start action is "(null)".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: on-stop action is "(null)".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: wait-cmd status is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: on-start returns output is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: mdns backend "(null)".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: stuffing option is "0" (0-basic, 1-soxr).
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: resync time is 0.050000 seconds.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: allow a session to be interrupted: 1.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: busy timeout time is 120.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: drift tolerance is 0.001995 seconds.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: password is "(null)".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: ignore_volume_control is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: volume_max_db is not set
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: disable_synchronization is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: use_mmap_if_available is 1.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: output_rate is 44100.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: audio backend desired buffer length is 0.150000 seconds.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: audio backend latency offset is 0.000000 seconds.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: volume range in dB (zero means use the range specified by the mixer): 50.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: zeroconf regtype is "_raop._tcp".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: decoders_supported field is 1.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: use_apple_decoder is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: alsa_use_playback_switch_for_mute is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: no special mdns service interface was requested.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: metadata enabled is 1.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: metadata pipename is "/tmp/shairport-sync-metadata".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: metadata socket address is "(null)" port 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: metadata socket packet size is "500".
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: get-coverart is 1.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: loudness is 0.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: loudness reference level is -20.000000
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: disable resend requests is off.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: Setting loudness threshhold to -20.000000.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: "notify_loudness_filter_active_callback" called.
May 04 08:38:08 raspberrypi3w shairport-sync[7095]: deactivating loudness filter
May 04 08:38:09 raspberrypi3w shairport-sync[7095]: avahi: service '605B2B5EEB50@Raspberrypi3w' successfully added.
```

**Comment by mikebrady** [comment]
Oops -- didn't mean to close the issue!

**Comment by mikebrady** [comment]
This is a real conundrum! Is your iOS still iOS 11.1.2? Maybe it's as simple as that -- if the version of AirPlay is 363 or less, keep the old scheme of adding 11,025 (i.e. 0.25 seconds) to the nominal latency requested.

**Comment by Mmoi-Fr** [comment]
I'm still on IOS 11.1.2. I gonna test with an IOS 11.3.1 monday and tell you if it's the version that changes the latency.

**Comment by mikebrady** [comment]
That's okay -- I think it does! I've pushed a `development` update that checks the User Agent's AirPlay version number. If it corresponds to 11.1.2 or earlier, it adds 11,025, which I believe makes it exactly right. Just checking it on an iOS 9 iPhone and it looks right. I don't know what user agent version number of AirPlay that the change in operation happened...

**Comment by mikebrady** [comment]
Thanks for the warning. It should still work for you, but I might change if from 363 to 353 over the weekend.

**Comment by mikebrady** [comment]
Great.
