### ISSUE TITLE
Make metadata an option at build time

### ISSUE THREAD

**Issue by mantheman** [mikebrady/shairport-sync#65]
Many of us are using shairport-sync in a headless server. The recent metadata additions are super cool but imho should not be a permanent feature, but an option at build time. The commits right before the initial metadata commits are super stable, and ideally I'd just like the "bug fixes" from upstream. If I ever need metadata support, it's easy to rebuild.

**Comment by mikebrady** [comment]
Thanks for your comment. Actually @joerg-krause makes a similar point at https://github.com/mikebrady/shairport-sync/issues/59. I'll try in the next few weeks to move to  `stable` and `development` branches, move the metadata stuff to the development branch and make it an option at build time. It might take a little work...

**Comment by mikebrady** [comment]
Hi @mantheman and @joerg-krause. How about this for a plan:

1 Make a new branch called 2.3 now and consider it the `development` branch
2 Make the current branch (2.2) the `stable` branch
3 Remove the metadata stuff from the `stable` branch.
4 Make the metadata stuff in the `development` branch compile-time conditional.

Crucially, this would leave the bug fixes in place, but it would also leave a small amount of new memory management stuff, necessary for metadata handling, in place too. It would, I think, be much easier to organise from the git point of view.

Going forward, only fixes would be added to the `stable` branch and development would only be done on the `development` branch.

**Comment by mantheman** [comment]
I have nothig to add. That sounds just about perfect:)

**Comment by joerg-krause** [comment]
1 to 3 looks good to me! 

For me it is not necessary to have the metadata compile-time conditional. The development branch is considered to be unstable and a place for testing new features. It's up to you.

**Comment by mikebrady** [comment]
I've made the changes I suggested above, although, for convenience, I left a small amount of memory management code in 2.2 that is only really useful in 2.3. So, I'll close this issue. Feel free to reopen if necessary.
