### ISSUE TITLE
shairport-sync nodes on showing up on iPad

### ISSUE THREAD

**Issue by Bazmundi** [mikebrady/shairport-sync#652]
Alas, I suspect my wife upgraded here iPad and for some reason the shairport-sync nodes are no longer visible.  Has Apple moved away from the protocol on iOS devices?  

I am running iTunes 12.2.7.60 on my pc under windoze 10 but that still sees the nodes.  Do I need fear upgrading when prompted?

Cheers,
B

**Comment by mikebrady** [comment]
Well, here we have all iOS and macOS devices up to date and Shairport Sync devices are working fine.

**Comment by Bazmundi** [comment]
Hmmm.  Madam has iOS 10.3.3 and is running iTunes something or other (where does one find the version for iTunes on a iPad.  Only searches for AppleTV under Airplay???  Sorry, not much help as I am not Apple savvi per se.  Madam claims to have updated at least once since I had it running.  I notice the panel at the bottom has changed format since I played with it a while back.
