### ISSUE TITLE
Static in playback over AirPlay from various devices

### ISSUE THREAD

**Issue by stulevine** [mikebrady/shairport-sync#659]
Up until just recently, I was using shairport on the raspberry pi along with a USB 24bit/96kHz DAC for over a year now without any issues.  Sound was clear over AirPlay from both the Mac running the most up to date version High Sierra and any of my iOS devices running iOS 11.2.5.  However, after updating to the latest version of shairport (I've tried both master and develop) I started hearing lots of static/hissing sounds under the music.  Something I've never heard before.  I configured shairport running on the raspberry pi according to the README by setting the following general parameters:

drift_tolerance_in_seconds = 0.010
volume_range_db = 30

And, these are the same settings I've been using since first installing shairport on this raspberry pi. Any ideas on how to fix?

**Comment by mikebrady** [comment]
Thanks for the post. Can you clarify which output device you are using, please? The drift tolerance and volume range are really only appropriate for the built-in DAC.

**Comment by stulevine** [comment]
@mikebrady,

Sorry for the delay in response. Your reply ended up in my spam bucket and I just noticed you had replied.  

As I mentioned, I'd been using a version of Shairport that was about 6+ months old and that seemed to work fine for quite some time. The RPi3 is hooked up to Ethernet for the least amount of latency over AirPlay.  And, the DAC I'm using has not changed since then either.  It's a HiFimeDIY Sabre U2 Asynchronous USB DAC plugged into one of the Rpi3's USB ports and connected to a pair of B&W MM-1s via the analog port.

I've also play with the drift tolerance and volume range, but like I mentioned it did nothing to solve the issue.

Thanks,

Stuart

**Comment by mikebrady** [comment]
Thanks Stuart. It would be great if you would update to the `development` branch and turn on some logging. It has some changes and some extra diagnostics. The instructions for updating are on the  UPDATING.md page.

When you install Shairport Sync with `$ sudo make install`, a sample configuration file is installed at `/etc/shairport.sync.sample`. If you look at the new diagnostic section at the end of that file, you'll see how to enable relative and absolute time messaging in the log. I'd also suggest log verbosity level of 2 and statistics enabled. It's a bit noisy, but it might help to see what's happening.

**Comment by kwasmich** [comment]
I am experiencing the same issue. I was using a version from 2016 for a very long time without updating shairport-sync. But I did update iTunes/macOS/iOS and also Raspbian. I am not using it on a regular basis, so I cannot nail down when the issue started. I am still investigating the cause.

A promintent example is the first 30 seconds of Echoes from Pink Floyd. The ping sound is heavily distorted. For now I tried:
* using the build-in analog audio jack
* using a USB sound card
* adjusting the volume in ALSA
* adjusting the volume in iTunes on my Mac and on my iPhone

There is no problem when playing the song locally using `omxplayer` and `mplayer`.

**Comment by kwasmich** [comment]
I tried it on a Dell Latitude laptop running Pixel Desktop in addition to different iterations of the Raspberry Pi. So this is not a platform issue on ARM as the issue also appears on i386.

**Comment by mikebrady** [comment]
Thanks for the posts, Michael. It's really hard to nail these things down without the actual track. Is it an iTunes track you are using, or from somewhere else? (I'd like to try it on my own equipment.)

**Comment by mikebrady** [comment]
A quick question -- what happens (say, on the Dell Latitude) when you select `soxr` interpolation?

**Comment by kwasmich** [comment]
I'll try it right away. In the mean time I've compared the waveforms more throughly. I've packed 3 [screenshots](https://shared.kwasi-ich.de/distorted2.zip). There you can see that the statics are very subtle in the wave form but pretty prominent when hearing.
If I wouldn't know it better I'd say that's an off-by-one error. There is definitively a sample missing.

**Comment by mikebrady** [comment]
Interesting. The basic interpolation method will remove or add samples to keep time — that could be what you’re seeing ands hearing. If so, using `soxr` interpolation should help.

**Comment by kwasmich** [comment]
Using SoXR the static is almost not noticeable. You have to pump up the volume, use headphones and know what you are listening for to notice it.
On the Raspberry Pi (first generation) the song plays well until shortly after the first ping. Then the CPU usage goes through the roof and the sound is even more distorted. As expected by your description.

But I still don't quite understand why it has to compensate such frequently. In my case it seems to drop a sample every 20ms. That is almost every 1000th sample or 9000 samples in a 3 minute song. The clocks can't be that far off, can they? during the playback of such a song the clock of the Dell would be 0.2 seconds ahead and accumulated over the day that's 1.5 minutes. That doesn't seem right.

**Comment by mikebrady** [comment]
I'd glad the mystery is resolved, at least for the most part. Yeah, it's a bit of a mystery to me too -- I routinely see divergences of around 100 ppm between Macs/iOS devices and the Pis. Much more with PCs. (Turn on `statistics` to get an idea.) More recently, I am seeing very low rates of divergences from an internet radio source such as Radio Svizzera Classica. But to be honest, it's a surprise.

**Comment by kwasmich** [comment]
Perhaps the default value for `drift_tolerance_in_seconds` is a bit too aggressive?
I've tried the statistics but don't know how to read them. Perhaps you can enlighten me?

On my Raspberry Pi wired over Ethernet I get:
```
sync error in milliseconds, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy
       2.5,    -263.2,     623.7,        1003,      1,      1,      0,      1,   6258,  262,  264
       0.2,      62.3,    1750.4,        2006,      1,      1,      0,      1,   6169,  263,  264
       0.0,     107.6,    1756.1,        3009,      1,      1,      0,      1,   6197,  262,  264
       0.1,      62.3,    1756.1,        4012,      1,      1,      0,      1,   6194,  263,  264
      -0.1,     104.8,    1792.9,        5015,      1,      1,      0,      1,   6199,  263,  264
      -0.1,      56.6,    1778.8,        6018,      1,      1,      0,      1,   6091,  263,  264
      -0.1,      76.5,    1758.9,        7021,      1,      1,      0,      1,   6188,  263,  264
      -0.0,      76.5,    1809.9,        8024,      1,      1,      0,      1,   6108,  263,  264
      -0.0,     127.5,    1843.9,        9027,      1,      1,      0,      1,   6044,  263,  264
      -0.1,     110.5,    1787.3,       10030,      1,      1,      0,      1,   5918,  262,  264
       0.0,     119.0,    1761.8,       11033,      1,      1,      0,      1,   6129,  263,  264
       0.1,      87.8,    1758.9,       12036,      1,      2,      0,      2,   6009,  262,  264
       0.3,     -17.0,    1778.8,       13039,      1,     13,      0,     13,   5699,  257,  264
       0.1,     104.8,    1753.3,       14042,      1,     13,      0,     13,   6163,  262,  264
      -0.1,     119.0,    1739.1,       15045,      1,     13,      0,     13,   6120,  262,  264
       0.0,      31.2,    1753.3,       16048,      1,     13,      0,     13,   6087,  262,  264
      -0.1,     133.1,    1764.6,       17051,      1,     13,      0,     13,   6184,  262,  264
       0.0,      73.6,    1773.1,       18054,      1,     13,      0,     13,   6084,  262,  264
       0.1,      93.5,    1798.6,       19057,      1,     13,      0,     13,   6176,  263,  264
       0.1,     110.5,    1787.3,       20060,      1,     13,      0,     13,   6148,  263,  264
      -0.1,     138.8,    1775.9,       21063,      1,     13,      0,     13,   6100,  263,  264
       0.0,      59.5,    1736.3,       22066,      1,     13,      0,     13,   6193,  262,  264
       0.0,      82.1,    1775.9,       23069,      1,     16,      0,     16,   5921,  260,  264
```

On my Dell Laptop (Core 2 Duo) using 5GHz WiFi with the access point in sight I have:
```
sync error in milliseconds, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy
       2.1,    -548.7,     548.7,        1003,      0,      0,      0,      0,   6355,  263,  265
       2.0,    -793.1,     793.1,        2006,      0,      0,      0,      0,   6225,  260,  265
       2.0,    -841.2,     841.2,        3009,      0,      0,      0,      0,   6228,  263,  265
       2.0,    -798.7,     798.7,        4012,      0,      0,      0,      0,   6265,  260,  265
       2.0,    -914.9,     914.9,        5015,      0,      0,      0,      0,   6179,  253,  265
       2.0,    -781.7,     781.7,        6018,      0,      0,      0,      0,   6218,  251,  264
       2.0,    -784.6,     784.6,        7021,      0,      0,      0,      0,   6422,  263,  264
       2.0,    -832.7,     832.7,        8024,      0,      0,      0,      0,   6410,  263,  264
       2.0,    -784.6,     784.6,        9027,      0,      0,      0,      0,   6258,  263,  265
       2.0,    -815.7,     815.7,       10030,      0,      0,      0,      0,   6248,  263,  265
       2.0,    -926.2,     926.2,       11033,      0,      0,      0,      0,   6297,  261,  264
       2.0,    -736.4,     736.4,       12036,      0,      0,      0,      0,   6254,  261,  265
       2.0,    -778.9,     778.9,       13039,      0,      0,      0,      0,   6219,  251,  265
       2.0,    -855.4,     855.4,       14042,      0,      0,      0,      0,   6223,  253,  265
```

**Comment by mikebrady** [comment]
Yes indeed, there is far too much over-correction going on the Pi, and the Dell looks like its clock is off by nearly 1 part in 1,000, which is pretty remarkable, but not (in my experience) madly unusual. 

Regarding the Pi, the `drift_tolerance_in_seconds` needs to be widened if you're using the built-in DAC, but should be okay for a decent I2S or USB DAC.

**Comment by mikebrady** [comment]
Just for reference, this is what I'm getting right now playing a YouTube video of Diana Krall - Walk On By (Live) from an iMac running 10.13.3 and the latest Safari to a Raspberry Pi 3 over WiFi with an IQaudIO I2S amplifier. The output rate is  176,400 samples per second at 32 bits. WiFi is via an [excellent] Ubiquiti AP AC Pro base station.
```
Mar 26 21:18:20 kitchen shairport-sync[16038]: sync error in milliseconds, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy
Mar 26 21:18:20 kitchen kernel: pcm512x 1-004c: No SCLK, using BCLK: -2
Mar 26 21:18:30 kitchen shairport-sync[16038]: 0.0,       0.0,       0.0,        1003,      0,      0,      0,      0,  24551,  226,  231
Mar 26 21:18:38 kitchen shairport-sync[16038]: -0.1,       0.0,       0.0,        2006,      0,      0,      0,      0,  24532,  227,  231
Mar 26 21:18:46 kitchen shairport-sync[16038]: -0.2,       0.0,       0.0,        3009,      0,      0,      0,      0,  24515,  227,  231
Mar 26 21:18:54 kitchen shairport-sync[16038]: -0.3,       0.0,       0.0,        4012,      0,      0,      0,      0,  24503,  226,  231
Mar 26 21:19:02 kitchen shairport-sync[16038]: -0.5,       0.0,       0.0,        5015,      0,      0,      0,      0,  24479,  226,  230
Mar 26 21:19:10 kitchen shairport-sync[16038]: -0.6,       0.0,       0.0,        6018,      0,      0,      0,      0,  24387,  226,  230
Mar 26 21:19:18 kitchen shairport-sync[16038]: -0.7,       0.0,       0.0,        7021,      0,      0,      0,      0,  24439,  226,  230
Mar 26 21:19:26 kitchen shairport-sync[16038]: -0.8,       0.0,       0.0,        8024,      0,      0,      0,      0,  24423,  226,  230
Mar 26 21:19:34 kitchen shairport-sync[16038]: -0.9,       0.0,       0.0,        9027,      0,      0,      0,      0,  24395,  225,  231
Mar 26 21:19:42 kitchen shairport-sync[16038]: -0.9,       0.0,       0.0,       10030,      0,      0,      0,      0,  24375,  225,  231
Mar 26 21:19:50 kitchen shairport-sync[16038]: -0.9,       0.0,       0.0,       11033,      0,      0,      0,      0,  24367,  227,  230
Mar 26 21:19:58 kitchen shairport-sync[16038]: -1.2,       0.0,       0.0,       12036,      0,      0,      0,      0,  24323,  226,  230
Mar 26 21:20:06 kitchen shairport-sync[16038]: -1.4,       0.0,       0.0,       13039,      0,      0,      0,      0,  24315,  227,  230
Mar 26 21:20:14 kitchen shairport-sync[16038]: -1.5,       0.0,       0.0,       14042,      0,      0,      0,      0,  24303,  226,  230
Mar 26 21:20:22 kitchen shairport-sync[16038]: -1.6,       0.0,       0.0,       15045,      0,      0,      0,      0,  24255,  226,  230
Mar 26 21:20:30 kitchen shairport-sync[16038]: -1.6,       0.0,       0.0,       16048,      0,      0,      0,      0,  24251,  226,  230
Mar 26 21:20:38 kitchen shairport-sync[16038]: -1.8,       0.0,       0.0,       17051,      0,      0,      0,      0,  24235,  226,  230
Mar 26 21:20:46 kitchen shairport-sync[16038]: -1.9,       5.7,       5.7,       18054,      0,      0,      0,      0,  24219,  227,  230
Mar 26 21:20:54 kitchen shairport-sync[16038]: -2.0,       8.5,       8.5,       19057,      0,      0,      0,      0,  24212,  227,  230
Mar 26 21:21:02 kitchen shairport-sync[16038]: -2.0,       9.9,       9.9,       20060,      0,      0,      0,      0,  24211,  227,  230
Mar 26 21:21:10 kitchen shairport-sync[16038]: -2.0,      21.2,      21.2,       21063,      0,      0,      0,      0,  24213,  227,  231
Mar 26 21:21:18 kitchen shairport-sync[16038]: -2.0,      17.7,      17.7,       22066,      0,      0,      0,      0,  24204,  223,  230
Mar 26 21:21:26 kitchen shairport-sync[16038]: -2.0,       9.9,       9.9,       23069,      0,      0,      0,      0,  24201,  227,  230
Mar 26 21:21:34 kitchen shairport-sync[16038]: -2.0,       5.0,       5.0,       24072,      0,      0,      0,      0,  24213,  211,  230
Mar 26 21:21:42 kitchen shairport-sync[16038]: -2.0,      31.2,      31.2,       25075,      0,      0,      0,      0,  24215,  209,  230
Mar 26 21:21:50 kitchen shairport-sync[16038]: -2.0,       6.4,       6.4,       26078,      0,      0,      0,      0,  24212,  225,  230
Mar 26 21:21:58 kitchen shairport-sync[16038]: -2.0,      25.5,      25.5,       27081,      0,      0,      0,      0,  24218,  226,  230
Mar 26 21:22:06 kitchen shairport-sync[16038]: -2.0,       0.7,       0.7,       28084,      0,      0,      0,      0,  24214,  227,  230
Mar 26 21:22:14 kitchen shairport-sync[16038]: -2.0,      48.2,      48.2,       29087,      0,      0,      0,      0,  24209,  226,  230
Mar 26 21:22:22 kitchen shairport-sync[16038]: -1.8,      16.3,      16.3,       30090,      0,      0,      0,      0,  24218,  226,  230
Mar 26 21:22:30 kitchen shairport-sync[16038]: -1.7,       0.0,       0.0,       31093,      0,      0,      0,      0,  24266,  224,  230
Mar 26 21:22:38 kitchen shairport-sync[16038]: -1.9,       0.0,       0.0,       32096,      0,      0,      0,      0,  24222,  226,  230
Mar 26 21:22:46 kitchen shairport-sync[16038]: -2.0,       8.5,       8.5,       33099,      0,      0,      0,      0,  24210,  225,  230
Mar 26 21:22:54 kitchen shairport-sync[16038]: -1.9,      13.5,      13.5,       34102,      0,      0,      0,      0,  24215,  225,  230
Mar 26 21:23:02 kitchen shairport-sync[16038]: -1.9,       4.2,       4.2,       35105,      0,      0,      0,      0,  24211,  224,  230
Mar 26 21:23:10 kitchen shairport-sync[16038]: -1.9,      26.9,      26.9,       36108,      0,      0,      0,      0,  24235,  209,  230
Mar 26 21:23:18 kitchen shairport-sync[16038]: -2.0,      12.7,      12.7,       37111,      0,      0,      0,      0,  24219,  212,  230
Mar 26 21:23:26 kitchen shairport-sync[16038]: -1.9,       0.0,       0.0,       38114,      0,      0,      0,      0,  24223,  227,  230
```

**Comment by kwasmich** [comment]
Funny the Dell Laptop never goes down from 2ms sync error. Also setting the `drift_tolerance_in_seconds` to `0.02` only leads to smooth playback until it reaches 20ms sync error and then the crackling starts and never stops again.

```
sync error in milliseconds, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy
       3.3,       0.0,       0.0,        1003,      0,      0,      0,      0,   6419,  263,  264
       9.7,       0.0,       0.0,        2006,      0,      0,      0,      0,   6736,  264,  264
      16.5,       0.0,       0.0,        3009,      0,      0,      0,      0,   6978,  263,  264
      20.0,    -844.1,     844.1,        4012,      0,      0,      0,      0,   7039,  260,  265
      20.0,    -787.4,     787.4,        5015,      0,      0,      0,      0,   7067,  263,  265
      20.0,    -778.9,     778.9,        6018,      0,      0,      0,      0,   7217,  263,  264
```

There is definitively something wrong with the Dell's clock. Perhaps the algorithm cannot handle it well when the client is ahead of the synchronization all the time.

But I also see on the Pi that I am overcompensating all the time as long as I am too close to 0ms. The used algorithm seems to settle at roughly `x - 4.6ms` where x is the drift tolerance. Your proposed 10ms works well for the Pi.

**Comment by mikebrady** [comment]
Fair enough. I wish i could explain the Dell situation some other way than an inaccurate clock, but it's all that's left at this stage...

**Comment by kwasmich** [comment]
I've come up with a solution that does a great job for my Raspberry Pi.
1. I average the `sync_error` over the last 16 frames
2. In `stuff_buffer_basic_32` instead of picking a random position, I scan the entire frame and pick the center element where three elements in a row either are very close together much apart. So in sections where the waveform is almost horizontal or very steep. In either case an added or missing sample is very unnoticeable.

**Comment by mikebrady** [comment]
That sounds interesting — no pun intended! Could you let us see the code?

**Comment by kwasmich** [comment]
Its at the end of [this commit](https://github.com/kwasmich/shairport-sync/commit/32c7386b526ef7aff018aab9e3bd9aabcf7a278f). It is not the most elegant solution for sure.

**Comment by mikebrady** [comment]
I’ll have a look, thanks.
