### ISSUE TITLE
[package feature request] rpm spec could include pipe, stdout, dummy backends by default

### ISSUE THREAD

**Issue by sshambar** [mikebrady/shairport-sync#661]
The shairport-sync.spec currently only includes avahi and alsa backends by default, but pipe, stdout and dummy could be included easily on any platform that support rpm.

Currently, I have to download and rebuild on Fedora to add pipe each time there's a new release.  It'd be nice to be able to use the binary releases :)

I'm not sure if these backends are available on all supported platforms, but perhaps it might be nice for the configure.ac to include them by default (and then the spec file wouldn't need changing), especially since at lease pipe and stdout are mentioned as options in the default config file.  There could always be a --without-xxx configure option if they really aren't wanted...

**Comment by p3ck** [comment]
Since I build the Fedora package I can look into this.

**Comment by p3ck** [comment]
I've built new packages for f27 and f26.  Testing would be appreciated.

https://bodhi.fedoraproject.org/updates/FEDORA-2018-e869255345
https://bodhi.fedoraproject.org/updates/FEDORA-2018-67de08067c

**Comment by sshambar** [comment]
Installed on my system, and brings up the pipe just like my custom builds... looks good!

**Comment by p3ck** [comment]
This has been pushed to batch updates.  Next batch update should include the new version.
@mikebrady you can close this now.

**Comment by mikebrady** [comment]
Many thanks for this!
