### ISSUE TITLE
Send to HomePod?

### ISSUE THREAD

**Issue by pmengaziol** [mikebrady/shairport-sync#662]
Just saw a HomePod at Apple Store. There's no way to send "real" audio to it without converting to iTunes format. Is there any chance that shairport-sync will work as an Airplay transmitter? I image a RaspberryPi with an analog audio (stereo) in sending directly to HP. Is this a planned effort?

**Comment by roblan** [comment]
shairport-sync is a receiver, so it won’t send audio anywhere. Try forked-daapd maybe?

Btw. what you mean by "real audio"? If something can be send to shairport-sync then it could be send to HomePod as well.

**Comment by pmengaziol** [comment]
Thanks for the response! What doesn't seem to exist is a simple way to 
hook up an audio output (like a "tape" out) and send this audio via 
Airplay to any Airplay destination. Is that what forked-daapd does?

On Sat, Feb 10, 2018 at 05:18 AM, roblan wrote:

shairport-sync is a receiver, so it won’t send audio anywhere. Try 
forked-daapd maybe?

Btw. what you mean by "real audio"? If something can be send to 
shairport-sync then it could be send to HomePod as well.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/mikebrady/shairport-sync/issues/662#issuecomment-364641224> 
, or mute the thread

**Comment by roblan** [comment]
AFAIR forked-daapd can forward audio from pipe to AirPlay receiver
