### ISSUE TITLE
[feature request] realtime scheduler

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#663]
In MPD there is something like that:
https://www.musicpd.org/doc/user/realtime.html

In MPD's code that is:
https://github.com/MusicPlayerDaemon/MPD/blob/817656504dea224dbf849e5e988e277d798ae08e/src/thread/Util.cxx

It could be utilised in shairport-sync in relation to thread which holds output device.

**Comment by mikebrady** [comment]
Hmm, thanks for the suggestion. To be honest, I've always tried to steer clear of "tuning" the operating system like this. The thing about Shairport Sync is it only has a limited set of things to do basically listening to the network, feeding the DAC, doing some calculations. So, for example, it doesn't have to do file handling or disk I/O etc., so any potential gains seem to be small. (?)
