### ISSUE TITLE
Can't play from iTunes running on Windows [solved]

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#664]
3.1.7-OpenSSL-Avahi-ALSA-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc

pulseaudio 11.1, debian sid

in server logs I have this:

> Feb 13 22:14:34 shadow daemon.debug shairport-sync.5000[2267]: New RTSP connection from 192.168.1.230:54198 to self at 192.168.1.5:5000 on conversation thread 1.
Feb 13 22:14:34 shadow user.notice shairport-sync:5000: "ssnc" "clip": "192.168.1.230".
Feb 13 22:14:34 shadow user.notice shairport-sync:5000: "ssnc" "svip": "192.168.1.5".
Feb 13 22:14:34 shadow daemon.debug shairport-sync.5000[2267]: RTSP conversation thread 1 terminated.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: New RTSP connection from 192.168.1.230:54214 to self at 192.168.1.5:5000 on conversation thread 2.
Feb 13 22:15:05 shadow user.notice shairport-sync:5000: "ssnc" "clip": "192.168.1.230".
Feb 13 22:15:05 shadow user.notice shairport-sync:5000: "ssnc" "svip": "192.168.1.5".
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Play connection from user agent "iTunes/11.0.4 (Windows; N)" on RTSP conversation thread 2.
Feb 13 22:15:05 shadow user.notice shairport-sync:5000: "ssnc" "snua": "iTunes/11.0.4 (Windows; N)".
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: User-Agent is iTunes 10 or better, (actual version is 11); selecting the iTunes latency of -1 frames.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: rtp_setup: cport=6001 tport=6002.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Set up play connection from 192.168.1.230 to self at 192.168.1.5 on RTSP conversation thread 2.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: listening for audio, control and timing on ports 6001, 6002, 6003.
Feb 13 22:15:05 shadow user.notice root: shairport-sync play
Feb 13 22:15:05 shadow user.notice shairport-sync:5000: "ssnc" "pbeg": "".
Feb 13 22:15:05 shadow user.notice shairport-sync:5000: "ssnc" "pfls": "".
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Output frame bytes is 6.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Audio receiver -- Server RTP thread starting.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Output bit depth is 24.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Dithering will be enabled because the output volume is being altered in software
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Timing receiver -- Server RTP thread starting.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Timing sender thread starting.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Control receiver -- Server RTP thread starting.
Feb 13 22:15:05 shadow daemon.debug shairport-sync.5000[2267]: Set initial volume to -5.909090.
Feb 13 22:15:05 shadow user.notice shairport-sync:5000: "ssnc" "pvol": "-5.91,-9.48,-96.30,0.00".
Feb 13 22:15:06 shadow user.notice shairport-sync:5000: "ssnc" "pvol": "0.00,0.00,-96.30,0.00".
Feb 13 22:15:06 shadow daemon.debug shairport-sync.5000[2267]: syncing to seqno 20779.
Feb 13 22:15:06 shadow daemon.debug shairport-sync.5000[2267]: Hammerton Decoder used on encrypted audio.
Feb 13 22:15:06 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:07 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:08 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:09 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:10 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:10 shadow daemon.debug shairport-sync.5000[2267]: Aliasing of buffer index -- reset.
Feb 13 22:15:11 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:12 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:13 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:14 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:14 shadow daemon.debug shairport-sync.5000[2267]: Aliasing of buffer index -- reset.
Feb 13 22:15:15 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:16 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:17 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:18 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:18 shadow daemon.debug shairport-sync.5000[2267]: Aliasing of buffer index -- reset.
Feb 13 22:15:19 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:20 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:21 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:22 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:22 shadow daemon.debug shairport-sync.5000[2267]: Aliasing of buffer index -- reset.
Feb 13 22:15:23 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:24 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:25 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:26 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.
Feb 13 22:15:26 shadow daemon.debug shairport-sync.5000[2267]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7976.7,      156.9,     834
3.0.
Feb 13 22:15:26 shadow daemon.debug shairport-sync.5000[2267]: Aliasing of buffer index -- reset.
Feb 13 22:15:27 shadow daemon.debug shairport-sync.5000[2267]: Sync packet received before we got a timing packet back.

iTunes and my ios7 works just fine.
All is in wired LAN with wifi AP (eg. for iphone),
but the above quoted transmission is in wired LAN with working (NFS!) mtu 9000.

**Comment by mikebrady** [comment]
Hi there. That’s for the post and the log. You’re connecting from iTunes on Windows and it looks like a firewall is blocking some ports. This is common if the wrong type of network security is chosen on Windows — public / office / home and so on. Please check in the TROUBLESHOOTING page for some information and suggestions.

**Comment by mistepien** [comment]
yes, you are right, thanks!
