### ISSUE TITLE
 Synology  （群晖） docker install  ubuntu  run this ... fail..

### ISSUE THREAD

**Issue by jiangxutao** [mikebrady/shairport-sync#665]
I have a Synology   dsm 6.1  
i can not find this on softshop . 
i  read same issues .  to find the way .
i  use docker .  run a ubuntu . 
maybe the port or same other  part  is wrong .
 shairport-sync didnot run.

"http://www.tony.wiki/development/2016/06/07/airplay-on-ubuntu.html"
 
i follow the wiki , and fail,

plz .  make a Synology   dsm 6.1  copy .  
so sameone like me can download  shairport-sync in softshop , 
use airplay easy ! 
thank you .

I am Chinese, English is not very good.
Please upload your work in Synology's software store.
Let us can use airplay function simply.
thanks.

我是中国人，英语不太好。
请在Synology   的软件商店里面上传你的作品。
让我们可以简单的使用到airplay功能。
多谢啦。

**Comment by mikebrady** [comment]
The availability of Shairport Sync for Synology depends on enthusiasts building it and making it available for that platform. I suggest checking on the [Synology Community Forum](https://forum.synology.com/enu/viewforum.php?f=190).

**Comment by jiangxutao** [comment]
thank you 。
