### ISSUE TITLE
Integer output rates ex 192K

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#666]
Hi Mike,

I've had couple requests over the years for 192K, 384k rate output from shairport-sync and just got another one the other day. The scenario is that user proposes that audio device performs or sounds best at these rates. I don't really know but maybe it does.

In any case, whats your thought on implementing integer rate output?

-Tim

**Comment by moodeaudio** [comment]
I was thinking more along the lines of extending the existing capability of doing multiples of 44.1 to also include the integer rates and then outputting directly to hw:0. Something like below.

output_device = "hw:0"
mixer_control_name = "Digital"
output_rate = 192000
output_format = "S24"

But if there is already a way to do 192K to an ALSA device then I'll give it try. Whats the config for setting this up?

-Tim

**Comment by mikebrady** [comment]
Yes indeed, there is a way, but for integer multiples of 44,100 only (192,000 is a multiple of 48,000). Your example would work as follows:
```
alsa = {
  output_device = "hw:0";
  mixer_control_name = "Digital";
  output_rate = 176400;
  output_format = "S24";
  // other alsa settings
}
```
Shairport Sync doesn't support the resampling necessary to cross over from, say, 44,100 to 48,000 samples per second.

**Comment by moodeaudio** [comment]
Yes of course. Maybe a typo in your earlier post :-0
"You can already output at 88.2, 192 and 384k to alsa devices.)"

One config I tried was to set output_device = "alsa_dmix" where alsa_dmix is a hand created alsa pcm plugin that does the resampling. The file would be /usr/share/alsa/alsa.conf.d/alsa-dmix.conf. MPD for example can use these named alsa plugins as audio outputs.

```
pcm.alsa_dmix {
    type plug
    slave.pcm "plug_alsa_dmix"
}

pcm.plug_alsa_dmix {
    type dmix
    ipc_key 321456
    slave {
        pcm {
            type hw
            card 0
            device 0
        }
        format "S24_LE"
        rate 192000
    }
}

```
Running this config generates error below.

```
Looking for configuration file at full path "/usr/local/etc/shairport-sync.conf"
Value read for output rate is 44100.
alsa output device name is "alsa_dmix".
Open Mixer
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL alsa_dmix
fatal error: Failed to attach mixer
Request to shut down all rtsp conversation threads
asking playing threads to stop

```
Another config I have not tried yet is shairport-sync stdout --> sox stdin

-Tim

**Comment by mikebrady** [comment]
Yes, sorry about the typo. I’m on a very poor internet connection.

**Comment by moodeaudio** [comment]
Thats no fun unless the bad Internet is cuz you are chillin' on a nice beach somewhere :-)

Maybe when u get a moment you could have a look at what might be involved in enabling output_device to accept eitther "hw:0" or something like "alsa_dmix". It could just be a matter of using a different alsa api, but of course it could end up being much more complicated... I'm not really too familiar with alsa coding.

-Tim

**Comment by mikebrady** [comment]
Haha, I wish :) I'll certainly have a look when I get the time.

Just noticing, I miswrote my earlier response by including 192 and 384k. The correct numbers are: 44100, 88200, 176400 or 352800 (all multiples of 44,100 only). Apologies for the error -- I've edited it in the response. (Maybe we were at cross purposes because I didn't understand your question, sorry.)

**Comment by moodeaudio** [comment]
This can be closed.
