### ISSUE TITLE
homebrew start services

### ISSUE THREAD

**Issue by drsassafras** [mikebrady/shairport-sync#669]
Could you enable this server to start with homebrew?

It looks like a relatively easy thing to do. Here is an example of a commit that was made to enable brew to manage to start another service at startup:

https://github.com/Homebrew/homebrew-core/commit/5faab57f3f61d4fc51e128db801195a437ccdcf2

This way mac users could type:

```
brew install shairport-sync
brew services start shairport-sync
```

And that would be all that is needed to install and keep the server running.

If you like I could try making the changes myself, but don't know how to test such a change, so am afraid I know just enough to be dangerous. :)

**Comment by mikebrady** [comment]
Thanks for the mail. Might this be one for @shtirlic?

**Comment by shtirlic** [comment]
Yes, it's possible, but what defaults options should be?
