### ISSUE TITLE
Mac doesn't see Raspberry (airplay icon doesn't show up)

### ISSUE THREAD

**Issue by matt12f** [mikebrady/shairport-sync#670]
Hi, 
I've done a clean install of shairport-sync on my Raspberry Pi3b but the device doesn't show up on my mac. 
I'm connected via wifi to the same router and if I type in the command `shairport-sync -v` I get the following: 

`..`
`Unable to listen on IPv4 port 5000. The error is: "Address already in use".`
`Unable to listen on IPv6 port 5000. The error is: "Address already in use".`
`Could not establish a service on port 5000 -- program terminating. Is another Shairport Sync running?`
`Request to shut down all rtsp conversation threads`

So I've done a little searching and I found other people encountering the same error and I've tried the following: 
I tried `ps aux | grep shair` and I get:

`shairpo+ 430 0.0 0.2 28212 2560 ?  Ssl 10:16 0:00 /usr/local/bin/shairport-sync`
`pi 19135 0.0 0.0 4372 556 pts/0         S+ 11:01 0:00 grep --color=auto shair`

I also tried `avari-browse -a` getting:
`+ wlan0 IPv4 AF31192A3A11@Raspberrypi     AirTunes Remote Audio local`

I have no idea of what the problem might be. Also I'm not an expert with these things so my digging stops here... 

Additional note: I've downloaded on my android phone an app called "AllConnect" that streams to airplay devices and it detects the Raspberry but it can't stream anything to it.

Any idea of what might have gone wrong?

**Comment by mikebrady** [comment]
Thanks for the post. The diagnostic messages indicate that Shairport Sync is already running. The `avahi-browse` diagnostic indicates that's it's broadcasting on you network.

You can use a program like Bonjour Browser on the Mac to see if it can see the AirPlay service. If not, I suggest you check your network. Is there a firewall somewhere disabling mDNS? Have a look at the TROUBLESHOOTING page for some ideas on that...

Don't really know anything about AllConnect except that it seems to work. Best get it all working on the Mac first, I'd suggest.

**Comment by matt12f** [comment]
I've disabled my VPN and now it works fine (Is there any chance I could get it to work without having to disable my VPN?) even though it plays music through HDMI instead of my DAC, do I have to make changes to shairport-sync or to the raspberry itself?

**Comment by mikebrady** [comment]
Good stuff. You can configure Shairport Sync to play though the DAC -- there are some hints in the README document. TBH, I don't know of a way around the VPN issue -- that's a Mac thing.

**Comment by matt12f** [comment]
I'll try to see what I can do for the VPN, maybe if I connect the wifi router directly to the VPN it's going to work. 
Thanks for the support!

**Comment by mikebrady** [comment]
I'm glad it's working out for you, and good luck with the VPN stuff.
