### ISSUE TITLE
systemd pulseaudio volume control not show?

### ISSUE THREAD

**Issue by sonvirgo** [mikebrady/shairport-sync#671]
I compile with --with-systemd option, then configure to use pulse and enable service. And it works fine. 
`$sudo systemctl enable shairport-sync`
But show no volume control in pavucontrol. If I stop the service and run in temninal 
`$shairport-sync`
Then I can see and change the volume in pavucontrol
The service run in the context of shairport-sync account, while terminal run under my user account.
So it their a way to make the service volume shows up in pavucontrol?
Thanks!

**Comment by mikebrady** [comment]
Thanks for the post. I'm afraid I don't know a way to fix this. It seems to be a limitation of the way pulseaudio is normally configured.

**Comment by sonvirgo** [comment]
Thanks. I have tried to start service under user account, change groups, etc but to no effect. The same issue to CoreAudio, osx, no way to control volumes when Shairport-sync is installed on os x.

**Comment by sonvirgo** [comment]
So just accept as it
Thanks
