### ISSUE TITLE
equal loudness contour according to ISO226

### ISSUE THREAD

**Issue by shokoladas** [mikebrady/shairport-sync#673]
Hi,
I very like equal loudness contour feature in shairport. The second one i can find is in Jriver. It is uncommon feature,but from my point of view it is a must feature. From what i see in shairport code and if i am not wrong , loudness is boosted only at low frequencies. My point of view that if making feature, it should be as good as possible:) Why not to make a closer approximation to loudness curve ISO226 https://se.mathworks.com/matlabcentral/fileexchange/7028-iso-226-equal-loudness-level-contour-signal?focused=5059341&tab=function&requestedDomain=true
It will influence not only low frequencies.   The function for calculating the curve itself is there,so the filter is needed according to that. 
What do you think?  It would be closer to Jriver's filter which boost's high frequencies as well. Sorry i am quality addict:)

**Comment by mikebrady** [comment]
Thanks. I wonder if @yannpom would have a view on this...

**Comment by shokoladas** [comment]
No interest in this issue?...  Can it be done like payed project?
