### ISSUE TITLE
Stuttering since Pi system update

### ISSUE THREAD

**Issue by vasilisvg** [mikebrady/shairport-sync#674]
Yesterday evening I updated these packages on my Raspberry Pi

````
libraspberrypi0 1.20180328-1
libraspberrypi-bin 1.20180328-1
libraspberrypi-dev 1.20180328-1
libraspberrypi-doc 1.20180328-1
raspberrypi-bootloader 1.20180328-1
raspberrypi-kernel 1.20180328-1
raspberrypi-sys-mods 20180328+1
````
And ever since Shairport-Sync stutters at regular intervals. Mostly package loss, but sometimes even an `Error -32 writing 352 samples in play(): "Broken pipe".` 
Before the update everything had been running smoothly without any problems for months. Does anybody have any idea what may cause this and how I can fix it?

**Comment by mikebrady** [comment]
Thanks for the post. What kind of a Pi? Are you connecting over WiFi?

**Comment by vasilisvg** [comment]
It’s a Pi 3. I connect via Wifi to my router, and the Pi is connected with an ethernet cable to the router. Until this last update this setup ran super smooth, without any hickups.

**Comment by mikebrady** [comment]
Thanks. I just did a fresh install of Raspbian Stretch Lite onto a Pi 3 with WiFi, connected over WiFi and did the usual updates:
```
# apt-get update
# apt-get upgrade
# rpi-update
```
followed by a standard installation of Shairport Sync, using the special setting mentioned in the [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md) for the Raspberry Pi. Everything is running well.

Here is the package list corresponding to what you list above:
```
pi@raspberrypi3w:~ $ dpkg -l | grep raspberrypi
ii  libraspberrypi-bin              1.20180328-1                 armhf        Miscellaneous Raspberry Pi utilities
ii  libraspberrypi-dev              1.20180328-1                 armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
ii  libraspberrypi-doc              1.20180328-1                 armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
ii  libraspberrypi0                 1.20180328-1                 armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV
ii  raspberrypi-bootloader          1.20180328-1                 armhf        Raspberry Pi bootloader
ii  raspberrypi-kernel              1.20180328-1                 armhf        Raspberry Pi bootloader
ii  raspberrypi-net-mods            1.2.7                        all          Network configuration for the Raspberry Pi UI
ii  raspberrypi-sys-mods            20180328+1                   armhf        System tweaks for the Raspberry Pi
pi@raspberrypi3w:~ $ 
```

Make sure you have turned off `soxr` interpolation, as it may be overloading the Pi.

**Comment by vasilisvg** [comment]
I’m starting to think it may be a network/router issue. I ran a backup of the system I called *super stable* before and it had the same hickups. It looks like the system update is a coincidence. I’m sorry for the unnecessary issue!
