### ISSUE TITLE
Airport expresses appearing in Home.app in 11.4 beta 1

### ISSUE THREAD

**Issue by Cloudore** [mikebrady/shairport-sync#678]
Might this mean airplay 2 compatibility for old hardware?

Though you guys would be interested in knowing

https://www.reddit.com/r/HomeKit/comments/89p2zk/airport_express_showing_up_in_home_app_airplay_2/?st=JFL8KB46&sh=d0128d29

I don't run the beta myself, anyone have their shairport pi's appear as well?

**Comment by mikebrady** [comment]
Yikes, that *is* interesting!
