### ISSUE TITLE
2s delay from pressing pause to audio pausing in YouTube app

### ISSUE THREAD

**Issue by runeksvendsen** [mikebrady/shairport-sync#68]
Using the YouTube app on my iPhone 6, with the sound output set to the shairport-sync AirPlay server, I see a ~2 second delay between pressing pause and the sound stopping. When I press pause, the video stops playing immediately, and 2 seconds later, the audio stops playing. Then when I press play, the video starts playing immediately, and after 2 seconds, the audio appears.

Everything is always in sync, but the delay is there.

I understand why a delay after pressing play can be necessary: if there were no delay, and the relevant audio data hasn't been received yet, the audio wouldn't be in sync with the video. But when pressing pause, the audio should stop immediately, the remaining audio samples in the buffer shouldn't be played. No loss of synchronization happens by reacting immediately to a pause command, as far as I can see.

I run shairport-sync like this:

    shairport-sync -d -a Stereo -- -d hw:1,0

**Comment by mikebrady** [comment]
Unfortunately, you've actually run across a feature of AirPlay – a delay of two seconds is built in. When you play a movie from FaceBook or the Video app on the iPhone, the video is delayed for two seconds too, so it stays in sync with the audio, but YouTube doesn't do that, I'm afraid.

**Comment by runeksvendsen** [comment]
Thanks for the quick response.

Doing a packet capture on the system running shairport-sync, I can see that no HTTP request is sent by the iPhone when pausing video playback in the YouTube app. So it appears that pausing the video on the iPhone simply pauses the video immediately, and sends the remaining ~2s buffer of audio to the AirPlay device, which can do nothing but play what it receives. It really seems like an odd way to implement it, but it certainly seems this is how it works.

I'd love to do a test with an Apple TV, to see if the same behavior is present here.

**Comment by mikebrady** [comment]
Yeah, it's not very Apple-like, and the whole thing has a "legacy" feel to it, from when networks were slower and less reliable. I can't help feeling that Apple will let it go soon, and come in with something new in the area.
