### ISSUE TITLE
3.2RC1 - Unable To Connect to <Name> after pausing audio for a few minutes

### ISSUE THREAD

**Issue by obsidianspider** [mikebrady/shairport-sync#680]
I have successfully been running shairport-sync on a Raspberry Pi Zero W running Raspbian Jessie with the latest updates (Stretch won't mute my soundcard when the volume is turned down, seems to be related to issue #643 ).

3.1.7 was very stable and worked great. I updated to 3.2RC1 and noticed that if I paused the audio on my iPad, after a few minutes my iPad would show an error stating "unable to connect to `name of my shairport-sync device`". If I restarted shairport-sync by SSHing into the Raspberry Pi, then I could use it again.

I regressed back to 3.1.7 by using a backup of the `shairport-sync` folder from another Pi and rebuilding, and now things are stable again. I realize a lot of changes were made in 3.2, but I wanted to bring this to your attention. If there's something specific you'd like me to try to help you debug this, please let me know. I'm not sure if/what logs may be helpful.

**Comment by mikebrady** [comment]
Many thanks for the report. Indeed, if you could enable logs by setting the log_verbosity to 1 in the configuration file, and/or if you can get this problem to happen at will and let us see the log if available, I'd be really grateful.

**Comment by obsidianspider** [comment]
Of course now that I'm trying to recreate the issue which was happening all morning for me, I can't. I've re-updated to 3.2RC1 and will post log info as soon as it crashes again.

**Comment by mikebrady** [comment]
Thanks for your efforts. It sounds like an intermittent bug, always hard to get. I'll keep trying here too.

**Comment by mikebrady** [comment]
Can you recall whether you had to restart or simply start Shairport Sync during those outages? (Also, I’ve added some more diagnostics in the `development` branch if you’re feeling a bit adventurous...)

**Comment by obsidianspider** [comment]
In two instances the whole Pi froze so I had to unplug it and hard reboot. (Note: during none of the crashes were any other processes running. I wasn't trying to "do anything" else with the Pi).

One other time I was able to ssh in and restart shairport-sync

Since yesterday I've been actively trying to break it, and now I can't. It's quite frustrating not being able to recreate it.

**Comment by mikebrady** [comment]
Thanks. That freezing is something that's never happened with me. Hmm. Do you have `soxr` interpolation enabled, by any chance? (The Pi Zero probably doesn't have the horsepower to run it well.)

**Comment by obsidianspider** [comment]
I readily admit I don't know much about what I'm doing, but I installed with the default configuration by copy-pasting. Here's the version info for the one that froze on me a few times the other day.

```
$ shairport-sync -V
3.2RC1-OpenSSL-Avahi-ALSA-pa-soxr-metadata-sysconfdir:/etc
```

Here's the version info from one of the other Pi Zero Ws on my network that is still running 3.1.7 and was set up initially around six months ago

```
shairport-sync -V
3.1.7-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc
```

**Comment by mikebrady** [comment]
Sorry to drop the ball on this. As you might have seen, a number of pretty big bugs have been identified and fixed. When you got a chance, would you be kind enough to update to the latest, either the Release Candidates or the `development` branch. If the bugs persist or return, we’ll have another look at them. There’s an updating guide on the UPDATING.md page.

**Comment by obsidianspider** [comment]
I've updated and so far things are stable.

```
$ shairport-sync -V
3.2RC4-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc
```

**Comment by obsidianspider** [comment]
Since updating to 3.2RC4 I haven't experienced any instability problems. Closing the issue.

**Comment by mikebrady** [comment]
Thanks.
