### ISSUE TITLE
Query for connected clients

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#682]
Hi,

Is there a way to query shairport-sync for the host name of the connected client?

-Tim

**Comment by mikebrady** [comment]
Hi Tim. The IP number of the connected client is provided as a piece of metadata. Getting the hostname is tricky, though, and I haven't found a good way to do this.

**Comment by mikebrady** [comment]
One possible thing you could try is using `avahi-browse` with the IP number. For example, if you do:

```
pi@raspberrypi:~ $ avahi-browse -apr
```
you'll get something like this -- you can see the IP number and the device's "local" name.


```
...
=;wlan0;IPv6;Mac\032Pro;Apple File Sharing;local;Mac-Pro.local;169.254.167.254;548;
=;wlan0;IPv4;Mac\032Pro;Apple File Sharing;local;Mac-Pro.local;169.254.167.254;548;
...
```

**Comment by Hello71** [comment]
logically I think it should be `avahi-resolve -a ip`
