### ISSUE TITLE
Report: Output to pipe and speakers via ALSA tee

### ISSUE THREAD

**Issue by alexjago** [mikebrady/shairport-sync#685]
Hi all - 

It's frequently asked around here whether it's possible to get multiple outputs, i.e. some sort of pipe as well as to the system audio output. The answer so far has been 'no' as far as Shairport's built-in capabilities are concerned. 

However, I'm pleased to report what looks like success in this regard: ALSA has the built-in capability to copy its input to a file while continuing to play said input to the usual output. ("A file" includes "a fifo", although that has problems if there's a writer but not a reader on the fifo...)

Edit `/etc/asound.conf` to include something like 

```
pcm.teeraw {
	type copy
	slave.pcm "tee:default,'/path/to/fifo',raw"
}
```

I haven't yet managed to do anything useful with it, but launching `xxd /path/to/fifo | tail` while playing music via shairport demonstrates that there is stuff going through there. 

Meanwhile in the shairport config, it's necessary to specify that the output device is `teeraw` but the *mixer* remains `default`. 

I hope this is useful to someone!

**Comment by mikebrady** [comment]
Thanks -- it's amazing what people are doing with Shairport Sync!
