### ISSUE TITLE
Question about frame timing for mdst, mden, prgr metadata

### ISSUE THREAD

**Issue by brookstalley** [mikebrady/shairport-sync#687]
Shairport sync is working great, and I'm pretty far along on a project to pull live data from Musicbrainz + Acousticbrainz for live lighting control (e.g. from beat timing).

To do that, I need to sync my app's internal clock to the current RTP frame Shairport Sync is playing. I'm currently doing that by looking at the "current" frame from the prgr metadata, but I'm wondering if I should use the frame on the mdst message instead.

Any insight on whether mdst or prgr will be a better mapping of frame to real-world time? Or, since the RTP frame is supplied by the client and has some latency, is there a better way to determine the local clock time when a particular frame ID will be sent to output?

**Comment by mikebrady** [comment]
Thanks for the interesting question, which I’d like to think about. One possible route is to add a D-Bus command to retrieve the local time and associated frame number. Would that suit? It might take a week or so...
