### ISSUE TITLE
Latest Version on the Debian Archive

### ISSUE THREAD

**Issue by biocross** [mikebrady/shairport-sync#688]
Hey @mikebrady,

First of all, thank you so much for this great piece of software! I have got it up an running on my C.H.I.P with my Bose Companion 5 Speakers.

It sounds awesome, except that it stops playing for a few seconds every 10-15 seconds or so. 

Before troubleshooting the issue further, I checked the version I had installed using the `-V` flag, and it printed out the following: 

`2.8.6-OpenSSL-Avahi-ALSA-pulse-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc`

I'm pretty sure, the latest stable version is `3.1.7`, so I ran `apt-get update` and `upgrade` for `shairport-sync`, but it says it's already at the latest version.

I don't know how the debian archives work (linux n00b here), but any chance you might have missed publishing the latest releases to the archives?

**Comment by mikebrady** [comment]
Thanks for the post. Updating on Debian can take some time, I’m afraid, so it could easily be that 2.8.6 is the latest one there. There have been many important bug fixes since 2.8.6, and indeed there have been more important bug fixes since 3.1.7 — 3.2 is nearly ready to release. Would you consider building the application yourself?

**Comment by biocross** [comment]
Hey! So yeah, I ended up building it myself, and upgraded all the way to `3.2RC4`.

Just that, now, the audio is worse. Now when I Airplay, I get about 20 seconds of crystal clear audio, and post that it just completely breaks down, with either no sound, or little bits of audio intermittently every few seconds.

I checked the CPU usage using `top`, and it's a little under 15%. 

Any steps I can take to improve this? Maybe things that can increase the CPU load, but make it work better?

**Comment by biocross** [comment]
Great, so looks like my wifi power_save was getting turn on every boot, so I disabled it permanently, and the performance has considerably improved!

Now I can listen to almost 1 min of audio before it breaks down. Also, it seems to recovering at times from the breakdown.

Here's the log you requested:
[verbose2_logs.txt](https://github.com/mikebrady/shairport-sync/files/1935923/verbose2_logs.txt)

**Comment by mikebrady** [comment]
That's progress, certainly. I see that your output device is "plughw:1". That means it's not a real hardware sound card, but rather a software-mediated device of some kind. Shairport Sync really relies on good timing information coming directly from a real output device, and I simply do not know (and don't really trust) these virtual devices. Using `alsamixer` on my C.H.I.P., I can see that there is indeed a real hardware device at `hw:0` and it has a mixer called `Power Amplifier`, so my `alsa` settings are:
```
alsa = {
  output_device = "hw:0"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
  mixer_control_name = "Power Amplifier"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
// all the other settings are commented out
};
```
Could you try it and see what happens please?

**Comment by biocross** [comment]
Sure thing. So, I'm using my CHIP to output to my Bose Companion 5 Speakers using USB.

Due to my lack of knowledge in setting up audio interfaces in linux, I did quite a bit of trial and error before I could finally get sound out of these via USB.

The output of `aplay` and `amixer` doesn't make much sense to me, so I'm attaching the output of 
`amixer`, `aplay -l` & `aplay -L` for you here:

[outputs.txt](https://github.com/mikebrady/shairport-sync/files/1938496/outputs.txt)

Maybe it makes way more sense to you as to which device I should be using in the Shairport Configuration?

**Comment by biocross** [comment]
Also, when I do select `hw:1` in Shairport config and play music to it, I get the following error: 

![screen shot 2018-04-23 at 7 41 26 pm](https://user-images.githubusercontent.com/840512/39132031-81ba000a-472e-11e8-888d-15b5cf54fa88.png)

**Comment by mikebrady** [comment]
Thanks for this. You should try `hw:0` rather than `hw:1`.

**Comment by biocross** [comment]
Setting it to `hw:0` outputs to the 3.5mm jack on the CHIP, instead of my speakers. The speakers are connected to the CHIP via USB, and I want to output to them :)

**Comment by mikebrady** [comment]
I had a quick look on the internet and there has been some discussion about getting the Bose Companion 5 USB recognised and used.

[This page](http://www.volkerschatz.com/noise/alsa.html) might help if you want to do a bit of detective work on the card. It looks like it could help you figure out the capabilities of the USB interface.

**Comment by biocross** [comment]
Thanks for the pointers! Will get back to you when I have something. Closing this issue for now :)

**Comment by mikebrady** [comment]
Great, thanks.
