### ISSUE TITLE
configure: WARNING: unrecognized options: --with-dbus-interface

### ISSUE THREAD

**Issue by thk4711** [mikebrady/shairport-sync#691]
I cannot build it with dbus interface. configure --help does indicate the option --with-dbus-interface but when I run configure with that option it tells me : configure: WARNING: unrecognized options: --with-dbus-interface. When I build shairport and start it the dbus interface is also not active.
The same thing is also happening with the --with-mpris-interface option.

**Comment by mikebrady** [comment]
Thanks -- this isn't documented yet, but the options are `--with-dbus` and `--with-mpris` respectively. You should also include `--with-metadata`. 

(If you enter `$ ./configure --help` you'll get the options available.)

**Comment by mikebrady** [comment]
The fixes are up, so `--with-dbus-interface` and `--with-mpris-interface` work now.

One other thing to look out for is the, by default, these interfaces are opened on the dbus system bus. If you want them on the bus session bus, set an option in the configuration file -- see `/etc/shairport-sync.conf.sample` for examples.

**Comment by thk4711** [comment]
Thank You for fixing this !
