### ISSUE TITLE
Troubleshooting Correction

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/shairport-sync#692]
Hello Mike,

As I have no other way to get hold of you, I created this ticket to point out on the troubleshooting page you have stated that the issue was a failing router.

After much debugging, the Apple Airport Extreme is just fine. The issue was a failing 802.11n nub on the Pi Zero. Once this was replaced with an Edimax EW-7811 AC600, not only did this resolve the Shairport Issue, but various other slow updates.

Please correct the Troubleshooting Page to state that one should use the following speed test guide to observe if the Wi-Fi nub being used by someone is in fact the real problem.

https://thepi.io/how-to-use-your-raspberry-pi-to-monitor-broadband-speed/

Please close this ticket once the update has been made.

Your loyal fan!

**Comment by mikebrady** [comment]
Will do, thanks.
