### ISSUE TITLE
Stream video and photos

### ISSUE THREAD

**Issue by marcofranssen** [mikebrady/shairport-sync#693]
Are there any plans to support streaming video and pictures?

It would be great if I could play youtube video's from my phone via raspberry on my TV.

Or to watch my holiday pictures from my phone via raspberry on my TV.

**Comment by mikebrady** [comment]
Thanks for the post. The short answer, I'm afraid, is "no".

Some projects in the past have implemented video and picture streaming, but it seems that changes made by Apple a few years back have made these stop working. In any case, they were never a focus in the shairport world.
