### ISSUE TITLE
Plays too fast / higher pitch

### ISSUE THREAD

**Issue by clintinthecode** [mikebrady/shairport-sync#695]
Hi,

Ive set up using a raspberry pi with a Soundblaster audigy 2 nx usb sound card.

it plays too fast and has a higher pitch.

I was using `./shairport.pl -a Sundancer-Pi` to launch.

ve been googling for hours now and havent found anything helpful.

I am now using `./shairport.pl -a Sundancer-Pi --ao_devicename=default` to launch, shas same issue, but it works for all my speakers. I have a 8 channel sound card and currently have 6 channels configured together in alsa going to different zones on my boat. I have cabin speakers, rear deck speakers and cabin sub woofer, soon ill be adding rear deck sub woofers too as a 4th zone. Its all the same audio going to every zone, but i have individual volume controls to get the right levels depending on where you are on the boat.

Any ideas on why it plays too fast and has a higher pitch?

on the terminal window it keeps saying missing frame when first playing, then repeatedly says requesting resend on 1 packets (port 53187), and every so often the audio stops for a second or two before playing again.

**Comment by mikebrady** [comment]
Thanks for the post. It's not clear whether you are using Shairport Sync or an old version of shairport. Certainly, `./shairport.pl` is not part of Shairport Sync.

My guess is that the sound card you are using does not do 44,100 frames per second and that the `alsa` subsystem is trying to transcode from 44,100 (from shairport) to 48,000 for your card. Unfortunatelythe PI isn't powerful enough so it can't keep up.

There have been some other users of different version of Soundblaster Audigy, but with similar problems.

**Comment by clintinthecode** [comment]
Ahhh id say im using a different version! I just looked at the website i used to install it, i followed these instructions and see its a different git repo!

git clone https://github.com/hendrikw82/shairport.git
cd shairport
make

last commit 2012.... ill delete that now and download your version! haha..

**Comment by clintinthecode** [comment]
Ok, ive installed your version, now im at the issue of my sound card seeming to support 48000khz when this is using 44100.

I get this error fatal error: Can't set the D/A converter to 44100.

Is there any way to get it working as is using config? can the software resample from 44100 to 48000?

I guess if not i have to buy a new sound card?

**Comment by mikebrady** [comment]
Shairport Sync requires 44,100 samples per second or multiples of it -- it doesn't do conversion from other rates. The `alsa` subsystem does have rate converters, but they introduce all kinds of other problems and don't really work, AFAIK. So, yeah, you might have to look for another card. I think some users have configured 7.1 cards -- have a look in some of the closed issues -- but I don't have any direct experience of it, I'm afraid.
