### ISSUE TITLE
HiFiBerry AMP+ Support?

### ISSUE THREAD

**Issue by VeniceNerd** [mikebrady/shairport-sync#696]
Hi,

I’m wondering if Shairport sync supports the [HiFiBerry AMP+ ](https://www.hifiberry.com/products/ampplus/)?

I’d love to get a couple of Raspberry Pi’s with the AMP+ and connect them to my on house speaker for multi-room airplay support.

Thanks!

Philipp

**Comment by mikebrady** [comment]
Maybe others have direct experience of this amplifier. I don't see what not.

**Comment by orbsmiv** [comment]
I'm using Shairport Sync on a HifiBerry DAC+ Pro without issue.

**Comment by uMotif-john** [comment]
Yes, it does. I've got two hifiberry AMP+ and two IQaudio digiamp+ running shairport sync. Both types work well.

**Comment by nettings** [comment]
Same here, with the current AMP2.

**Comment by gmkey** [comment]
if your question is answered, please close the issue.
