### ISSUE TITLE
Playback won't resume after pausing (cygwin)

### ISSUE THREAD

**Issue by priitohlo** [mikebrady/shairport-sync#699]
Cannot resume playback after pausing on a device (an iPad in this case).

Version 3.1.7
Environment: cygwin64, Win10

Log attached.
[shairport.log](https://github.com/mikebrady/shairport-sync/files/2007023/shairport.log)

**Comment by mikebrady** [comment]
Thanks. I’ll have a look.

**Comment by mikebrady** [comment]
I can replicate the problem alright...

**Comment by mikebrady** [comment]
I have pushed out an update which I think addresses the issue. It you got an opportunity to check it out, I'd be obliged. It's in the `development` branch, 3.2d53.

**Comment by priitohlo** [comment]
Looks much better.

My eternal gratitude for the quick turnaround on this and for the rest of your work on this project.

**Comment by mikebrady** [comment]
I pushed another version, 3.2d54, with a bug fix for another possible cause of lock-up.
Many thanks for your bug report -- it provoked a good deal of (useful!) head-scratching.
