### ISSUE TITLE
Shairport-sync crashes on Rasperry Pi 3B when SoXr is running

### ISSUE THREAD

**Issue by janui** [mikebrady/shairport-sync#702]
I am using shairport-sync on a Raspberry Pi Zero and 3B as part of a RuneAudio configuration. Linux version 4.14.24-1-ARCH. Using the latest version of shairport-sync with build options: './configure --prefix="$pkgdir/usr" --with-alsa --with-avahi --with-ssl=openssl --with-soxr --with-dns_sd --with-metadata --with-stdout --with-pipe --with-convolution --with-apple-alac'
All is working well, including metadata. But when SoXr is switched on it becomes unstable. It will work for a while with reasonable CPU usage, then, for no apparent reason, it grabs all available cpu power which causes the Pi's to crash. These same symptoms are seen on both the Pi Zero and 3B models. On the 3B model it has been tested with a dedicated CPU, which can be seen maxing out.
My questions is: Is this to be expected when SoXr is used?
If you need more information, please specify how it needs to be produced and delivered.
janui

**Comment by mikebrady** [comment]
Hi Janui. Thanks for the post. Yes indeed, it is to be expected with soxr on a not-very-powerful machine like a Pi. Unfortunately, a lot of CPU power is needed for libsoxr-based interpolation. In addition, the interpolation code runs on a single thread, so multicore doesn’t help.

**Comment by janui** [comment]
Thanks Mike,
Shame that is won't work.
janui
