### ISSUE TITLE
Stuttering audio using codec on fixed sample rate

### ISSUE THREAD

**Issue by MKSounds** [mikebrady/shairport-sync#703]
Hello,

I'm using the newest version of Volumio (2.389 2018-03-26) in combination with an overlay to directly send the audio data to a dsp via I2S. The overlay is tested and is working without problems.
Thus the dsp has to run as a clock master, the codec is configured to be the clock slave (receiving the bclk and lrclk from the dsp). The problem is, that the dsp doesn't have an ASRC, so it has to run at a fixed sample rate (which is 48 kHz/24 bit because of the assembled oscillator).
Therefore I use the in-build resampling of Volumio which is absolutely fine when playing local files from USB.

Now I'm testing with AirPlay as source and the sound is badly stuttering. It's like 2 seconds break, then 1 second of audio playing as it should, then again 2 s pause and so on.
I suspect the problem is caused by the sample rate and bit depth of the airplay output.
Is shairport-sync directly sending the audio to the hardware ? 
I already checked the possibility to change sample rate and bitdepth in shairport-sync.conf (in the alsa block), but there are just multiples of 44,1 kHz possible selections. 
What would be the easiest way to do the resampling from 44,1 kHz to 48 kHz in the context of volumio ? 

Best regards.

**Comment by mikebrady** [comment]
Thanks for the post. You are correct that Shairport Sync does expect to be outputting to a hardware device at 44.1 kHz or an exact multiples thereof. It monitors the device for delay — the number of frames in the output queue at any time. I’m afraid I do not know exactly why the transcoding isn’t working. It could be that the delay information isn’t being fed back, or it could be that the CPU is overloaded, though that seems unlikely if it is working for local files. The Volumio guys would be best placed to answer the transcoding question — it’s not something I use.

**Comment by MKSounds** [comment]
Thanks for your reply.
I already checked the cpu load, which is always <10%.
Could you give me a short explanation on how the audio routing, starting at the shairport output, is done?
I considered, if it's possible to do the resampling for the whole system in the ~/.asoundrc file.

**Comment by mikebrady** [comment]
The audio is sent, usually in packets of 352 "frames", where there are 44,100 frames to the second, to a specialised "backend" which is adapted to the system it's connecting to. For instance, there is a `pipe` backend which output the audio to a unix pipe.

The `alsa` backend takes the audio packets, with their associated timing data, and sends the audio to the `alsa subsystem at just the right time to appear on the output of the DAC at exactly the correct instant. To do this, it monitors the length of the queue of audio frames waiting to be processed in the `alsa` subsystem. Knowing the exact time, the exact length of the queue and the exact time an audio frame must be played, it can ensure that the audio reaches the DAC at exactly the right instant.

To make these calculations, the `alsa` backend must have access to this queue size information, and the queue size information must be a faithful reals-time representation of the queue size. My guess is that this type of information is not provided by the transcoder, thus throwing the backend off its correct operation.
