### ISSUE TITLE
Mixer mutes on disconnect (3.2RC9)

### ISSUE THREAD

**Issue by orbsmiv** [mikebrady/shairport-sync#704]
I've finally gotten around to testing 3.2 (currently using 3.2RC9) and have noticed that the hardware mixer now mutes on disconnect, which is different behaviour from 3.1.7. Is this expected and is there an option to enable/disable it? (I've tried `mute_using_playback_switch` to no avail.)

As an aside I've finally put something together with Jenkins so that each of your tags _should_ build a new Docker image for the Raspberry Pi - it's available at https://hub.docker.com/r/orbsmiv/shairport-sync-rpi and I've found it pretty useful for comparison purposes. Fantastic project btw!

**Comment by mikebrady** [comment]
Thanks. What hardware are you checking the mute behavior on, please?

**Comment by mikebrady** [comment]
Thanks for the Jenkins stuff — I’ll take a look at it in the next little while.

**Comment by orbsmiv** [comment]
Both the Raspberry Pi 3's internal sound and on a HifiBerry DAC+ Pro.

**Comment by mikebrady** [comment]
Thanks. With the internal sound card, there are two ways to get a mute. The first is to use the playback switch. The problem with this is that you have to explicitly undo the mute to get anything out of it subsequently, so using the playback switch is disabled by default. The second way is to set the volume to a magic number — this mutes the output but can be unmuted simply by setting a different volume. That’s facility is used automagically if it exists. (At least, that’s how I understand it.) Is it causing problems?

**Comment by orbsmiv** [comment]
I'm running a few different sound-related services on the device (none of which have direct control over the ALSA mixer) so when I then connect to Shairport from e.g. my iPhone, the subsequent termination of the connection mutes the output in ALSA and I have to manually reset it to use any of the other services. In 3.1.7, disconnecting from Shairport doesn't affect the mixer level.

**Comment by mikebrady** [comment]
Okay thanks -- let me check my logic again; it might take a while, as it has become quite complex. (I feel that some simplification should be attempted -- always a hazardous undertaking.)

**Comment by mikebrady** [comment]
I've pushed an update in the `development` branch. The `mute_using_playback_switch` is gone, replaced by a `use_hardware_mute_if_available` which defaults to no. This controls both the playback switch method and the magic volume level method. Would you be kind enough to try it out, and let me know if it works please?

**Comment by orbsmiv** [comment]
I've tested using 3.2d56 and this works well: with `use_hardware_mute_if_available` set to `"no"` the behaviour is the same as with 3.1.7; when set to `"yes"` the mute is enabled/disabled on disconnect/connect in the alsa mixer whereas previously the mixer control value was set to 0.
Thanks!

**Comment by mikebrady** [comment]
Thanks for the reply. I've moved the fix into RC10.
