### ISSUE TITLE
Corrupted Size when adding IR file to Convolution Filter

### ISSUE THREAD

**Issue by jmellars** [mikebrady/shairport-sync#707]
Whenever I add a .wav file to the convolution filter, shairport-sync fails to launch on reboot. 

I uncommented and added the following to /etc/shairport-sync.conf
```
convolution = "yes";
convolution_ir_file = "/home/pi/Shower_v1.wav";
```
After rebooting, Pulling `journalctl -xe` gives me the following
```
May 27 01:46:39 ShowerPi shairport-sync[772]: *** Error in '/usr/local/bin/shairport-sync': corrupted size vs. prev_size: 0x00cf4198 ***
May 27 01:46:39 ShowerPi systemd[1]: shairport-sync.service: Control process exited, code=killed status=6
May 27 01:46:39 ShowerPi systemd[1]: Failed to start ShairportSync AirTunes receiver.
```

Recommenting the two above lines in the .conf file instantly fixes the issue and shairport-sync will launch.

**Comment by mikebrady** [comment]
Thanks. That message is a memory allocation error. Are there any hints in [this pull request](https://github.com/mikebrady/shairport-sync/pull/484) regarding the form and format of IR filter files?

**Comment by jmellars** [comment]
No, unfortunately. I read through that while fighting with this last night. I tried using the test .wav file that was linked there, and had the same results.

**Comment by mikebrady** [comment]
Hmm, I'll have to take a look at this...

**Comment by mikebrady** [comment]
I have had success with the filter at  https://b.ouisnap.com/upload/lyd3_000_ortf_44100.wav, referenced [here](https://github.com/mikebrady/shairport-sync/pull/484#issuecomment-283022871). (I set gain to -12dB, BTW.)

**Comment by jmellars** [comment]
Strange. That is the one I was testing with. I get the same result with it as I did with my own file.

**Comment by mikebrady** [comment]
I'm just listening to it now on an original Raspberry Pi B using its built-in audio. Setting the gain to -9 dB seems to be okay too. The source is iTunes and it's in sync with other speakers. Could I suggest you maybe run Shairport Sync from the command line [make sure it's not running as a service -- maybe disable that] with log verbosity set to 2 (or use the `-vv` command line option). Maybe it can't find the convolution file.

**Comment by jmellars** [comment]
Following the above steps does allow it to launch properly and implement the filter, both with the test wav file and my own file. As expected, it does still fail to launch on reboot.

Pi in question is a ZeroW, so I’ve only been running from command line, though it was being launched at boot as a service. I have now disabled it as a service, so I guess I will need to change that process now.

**Comment by mikebrady** [comment]
Sorry to neglect this, but have you actually enabled it to start upon boot up, using:
```
$ sudo systemctl stop shairport-sync
```
as mentioned in the README? If so, what does the log say?

**Comment by jmellars** [comment]
Apologies for the delayed response. I have been out of country and will be until mid-July. I'll get back to you as soon as I get my hands on the Pi again.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
