### ISSUE TITLE
Support AirPlay 2 with multiroom

### ISSUE THREAD

**Issue by verseeq** [mikebrady/shairport-sync#709]

**Comment by joerg-krause** [comment]
Duplicate of #535

**Comment by Technodad** [comment]
+1 on AirPlay 2, particularly with [AirPlay 2 embedding in TVs being one of the sleeper announcement at CES 2019](https://www.engadget.com/2019/01/11/apple-airplay-2-ces-2019/).

**Comment by seniorgod** [comment]
+1

**Comment by Midifreakz** [comment]
+1

**Comment by Episcop** [comment]
+1

**Comment by ssbarnea** [comment]
@github-action bot shut up, you are drunk.

**Comment by charlesomer** [comment]
Since this is a duplicate of #535 as mentioned earlier, I think this issue can be closed?
