### ISSUE TITLE
Stream airport via http

### ISSUE THREAD

**Issue by theo-69** [mikebrady/shairport-sync#711]
Hi I am trying to stream the music coming in via http like http://192.0.0.0:8080/sound.mp3

Any Ideas?

**Comment by myxxmikeyxx** [comment]
I believe https://www.mopidy.com/ would be a better option for what you want, you can stream from more locations and addresses.

**Comment by theo-69** [comment]
Thanks for the info, however I would like to play music via iTunes to http

**Comment by myxxmikeyxx** [comment]
sorry i miss understood and im not sure on that bit but i know kodi has a stream in and you can set it up as a server to host music so maybe look into that route if you don't get any other help, but you could also look at using the audio out and pipline it into another application that can make the pi (or what ever system you use) into a streaming service and see if that application has a pipline in feature.

**Comment by mikebrady** [comment]
Shairport Sync can output to `stdout` or to a Unix pipe; I believe you can use that to stream out on a http stream; in fact, I'm pretty sure someone has already reported this -- if so, it'll be in the issues, maybe in closed issues. I'm afraid I don't have time right now to search for it, sorry.

**Comment by theo-69** [comment]
thanks again, searching everywhere can not find the right tool or script
