### ISSUE TITLE
Speakers shutdown if there's no connected devices (Raspberry Pi)

### ISSUE THREAD

**Issue by pavelbelousov** [mikebrady/shairport-sync#712]
Is it possible to use one of the GPIO of the Raspberry Pi to control speakers power line?
My speakers generate some low-frequency noise when there is no audio input.
It would be great if Shairport could set some GPIO pin of the Raspberry Pi to, for example, LOW level when there is no active audio streaming, to switch high-voltage relay off (which delivers power to speakers), and set the GPIO pin HIGH when there is some audio to output, to switch speakers on.
Thank you!

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync can run programs just before it starts to play an audio stream and just after it finishes. Have a look in `man` entry or the [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md#configuring-shairport-sync) for details.

**Comment by pavelbelousov** [comment]
Thank you!
