### ISSUE TITLE
"prgr" data via dbus/mpris

### ISSUE THREAD

**Issue by exoqrtx** [mikebrady/shairport-sync#717]
I'm currently using a combination of methods to access metadata from what's playing via Shairport-Sync.  The first is a solution I've cobbled together from various examples I've found that use the metadata pipe output and the second is dbus/mpris metadata.  In general dbus/mpris has been a lot cleaner and requires drastically less code than my old solution.  

The only metadata I'm currently using but can't get from dbus is what is coming under the "prgr" tag in the metadata.  I'm basically only using this to get the current frame location and the total frame length of the track, converting them to seconds and then manually incrementing them so I can have an elapsed time/total time counter and progress bar in my app.  It's not always exact, but ballpark accuracy is more than good enough for my purposes.

I see in the dbus/mpris there is DeltaTime and ElapsedTime, but they're just coming through as boolean.  How difficult would it be to add something like current position and total track time?  It doesn't need to be updated in realtime with the song, maybe just updated when a song starts/stops or is moved manually ahead/back on the source.  Or is this already working on the more recent versions?  (I'm currently running a development version that I compiled sometime between RC's 9 and 10.)

**Comment by mikebrady** [comment]
Thanks for the post. The progress information could certainly be made visible as a string property in the regular `dbus` interface -- you'd have to parse it yourself. Would that be sufficient?

The DeltaTime and ElapsedTime stuff is only for diagnostic messages, so that's not relevant to this.

**Comment by exoqrtx** [comment]
That'd be perfect.

**Comment by mikebrady** [comment]
Just pushed out a quick-and-dirty update in the `development` branch -- a `ProgressString` property in the `RemoteControl` interface. It will change whenever the `'prgr'` token would be emitted.

**Comment by exoqrtx** [comment]
Awesome, I'll take a look later today and let you know how it goes!

**Comment by mikebrady** [comment]
Okay. It might be a bit messy.

**Comment by exoqrtx** [comment]
Seems to be working pretty good.  At first I was getting some weird data coming through for the end frame, but it seems to be working ok now.  Thanks!

**Comment by mikebrady** [comment]
Good stuff. Please keep us posted if there are any issues.
