### ISSUE TITLE
macOS Configuration

### ISSUE THREAD

**Issue by hstriepe** [mikebrady/shairport-sync#718]
I am trying to set up sh airport-sync installed via HomeBrew and am having trouble.
- Running it with just -s to show the version, it shows up in the AirPlay popup
- I am trying to redirect to an audio DAC that works with AirPlay and SwitchAudio with the command line:
shairport-sync   -- -n “USB Audio DAC   "
The extra spaces are in the advertised name.
This was reported by SwitchAudioSource and also works with SwitchAudioSource -s.
Shairport-sync starts up without error but there is showing up in the AirPlay lists. I have tried other output devices as reported by SwitchAudioSource -a

What am I doing wrong?

If I want to set up a config list, where would it be placed. No samples in /etc...

Thanks,
-- Harald

**Comment by hstriepe** [comment]
Ah, "/usr/local/etc/shairport-sync/shairport-sync.conf"

It works using the system default.

$ shairport-sync -v
Version: "3.1.7-OpenSSL-ao-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc/shairport-sync"
statistics_requester status is 0.
daemon status is 0.
deamon pid file is "/usr/local/var/run/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Neptune".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 1.000000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_playback_switch_for_mute is 0.
no special mdns service interface was requested.
configuration file name "/usr/local/etc/shairport-sync/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync/shairport-sync.conf".
metadata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
loudness is 0.
loudness reference level is -20.000000
Successful Startup

**Comment by hstriepe** [comment]
SwitchAudioSource works with the macOS CoreAudio framework. It clearly maps displayed devices to internal.
What I have not figured out is what the device options are for ao.

**Comment by whizkid79** [comment]
Having the same issues here. I'm looking for a way to tell shairport-sync on macOS which audio device and which channels to use.

**Comment by luckman212** [comment]
@whizkid79 @hstriepe did you guys ever figure this out? Today I installed `shairport-sync` on 11.2 using Homebrew 3.0 and got it to play (no `pulseaudio` required) with this command:

    shairport-sync --name=mac-mini --output=ao --statistics

But not sure if there's a better invocation, or any way to use a different backend, since according to the readme:

> _Note that the installation uses the libao library and so synchronisation is not available — **playback glitches will occur** occasionally, when the ao system's buffers overflow or underflow._

**Comment by Badsheep** [comment]
Hi there,

In case someone is interested, I use this command tine to start shairport on my Mac OS, and I can choose the device I need (in my case it's called : "'MIO Airplay") : 

`do shell script "/usr/local/opt/shairport-sync/bin/shairport-sync -d -o ao -- -n 'MIO Airplay'"`

I run this command in a script at the start of the computer.
