### ISSUE TITLE
Two way volume synchronization, is it possible?

### ISSUE THREAD

**Issue by timaydin** [mikebrady/shairport-sync#719]
I'm using shairport-sync in an embedded device. I know that when I change the volume in iTunes, that information is received by shairport-sync and is applied to the hardware. But my embedded device has volume up/down buttons that allows changing the volume locally. So I was wondering if it's possible to "notify" iTunes about this volume change?

In other words, I want to be able to change the volume with the local up/down keys and want the iTunes volume slider to be updated with the change. Does the AirPlay protocol have a provision for receiving actual volume information back?

**Comment by mikebrady** [comment]
The short answer is "yes". The slightly longer answer is that you'll have to write some code -- a script or two will suffice.

Starting with the version 3.2, Shairport Sync has a D-Bus based interface that allows other programs to communicate with it -- get properties, send commands etc. Among the commands and properties are ones for getting, raising and lowering the volume. The commands are in fact relayed to the source, which could be iTunes running on a Mac or PC, or it could be an iOS device, for example.

So you could imagine using something like `triggerhappy` to respond to button presses by executing scripts to use a D-Bus CLI tool such as `dbus-send` to send a D-Bus command to Shairport Sync,  which would in turn send a command to the source. Right now, I'm afraid I can't offer direct assistance, but have a look at the D-Bus interface commands and properties to get an idea what Shairport Sync can offer. Please let us know how you do!
