### ISSUE TITLE
mute on crackling due to bad wifi signal

### ISSUE THREAD

**Issue by shokoladas** [mikebrady/shairport-sync#720]
The very ugly crackling sound starts when my iphone gets out of good wifi signal zone. Normal that it can't play, but it is not normal that it tries to play with such bad crackling sound continuously. I wonder why not to mute sound if the buffer is low enough to cause the  crackling. And then unmute on good signal or pause/play pressing? It would be wise if walk out the house with my phone in the pocket and music stops.

**Comment by mikebrady** [comment]
Thanks for the post. To be honest, this has not been a focus of activity. When the signal gets poor, the output become intermittent for a while, but the output will always be a function of the signal, and never exceeds it in volume. I'll keep it in mind.
