### ISSUE TITLE
Question: Long delay after "play" until sound from speakers

### ISSUE THREAD

**Issue by IvarZarans** [mikebrady/shairport-sync#721]
I'm using shairport-sync on linux with Pulseaudio backend.
After pressing "play" on tablet, there is about 4-5 second delay before sound from speakers.
Is there any way to make it shorter?

**Comment by mikebrady** [comment]
Thanks for the post. The delay should be two seconds. Could tell us what version of Shairport Sync you are using please? (Use `$ shairport-sync -V`— that’s an uppercase V.) And also, are you using the `pa` backend or the older `pulseaudio` backend?

**Comment by IvarZarans** [comment]
I'm using Shairport Sync 3.2RC11, built according to installation instructions. OS is Ubuntu 16.04 LTS
Backend is "pa".
I tried also alsa backend (with alsa loopback), but this had similar delay.
Any suggestions, how to debug this situation, are very welcome :)

**Comment by mikebrady** [comment]
So I just checked this with the latest Release Candidate on Ubuntu 16.04:

```
mike@ubuntu:~/sps$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
mike@ubuntu:~/sps$ ./shairport-sync -V
3.2RC13-OpenSSL-Avahi-ALSA-pa-soxr-sysconfdir:/etc
mike@ubuntu:~/sps$ 
```
Calling Shairport Sync from the console like this:
```
$ shairport-sync -o pa
```
activated the player. It was giving the standard delay and was in sync with other speakers being played from the same iTunes source. The standard delay with iTunes seems to be 2.25 seconds, with two seconds for other stuff.

Anyway, it seems as if Shairport Sync is not introducing an untoward delay into playback. So, what is PulseAudio doing with the audio delivered to it by Shairport Sync? Is it forwarding the audio to another device over the network, or (possibly) over BlueTooth? If so, these transports might be introducing extra delays.

**Comment by mikebrady** [comment]
Thanks for the post, @Gaming271, but your situation is different to the OP’s, who is using the PulseAudio system on a reasonably recent standard Linux using a very recent build of Shairport Sync. In your case, what output device are you using, and what delay are you experiencing?

**Comment by Gaming271** [comment]
I expierience a 1-2 s delay everytime i start/stop the playback. 
shirport delivers the sound to a alsa which gives the sound to the headphone jack
`DietPi-JustBoom > ALSA Output Info
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 256
buffer_size: 32768
closed
`

**Comment by Gaming271** [comment]
when i play sound from the pi itself with moc (music on console) the delay is not there.
moc also uses alsa as the output device.

**Comment by Gaming271** [comment]
Version: `3.2.1-OpenSSL-Avahi-ALSA-pa-metadata-sysconfdir:/etc`
configured with `./configure --sysconfdir=/etc --with-alsa --with-pa --with-avahi --with-ssl=openssl --with-metadata --with-systemd`
delay didn't change

**Comment by mikebrady** [comment]
Thanks for your responses. There is a delay, which is normally 2.0 or 2.25 seconds, built in to the AirPlay 1 protocol -- it's part of the standard. In more detail, the audio sender and receiver negotiate a delay or "latency" at the start of a session. Most sources choose a two-second delay but some, like iTunes, pick a longer delay, close to 2.25 seconds.

**Comment by Gaming271** [comment]
is there any (resonabale) way to set it manually

**Comment by mikebrady** [comment]
There is a setting in the configuration file -- the `general` setting `audio_backend_latency_offset_in_seconds`. For example, if you set this to -1.2, it will make the audio come out 1.2 seconds before it it is supposed to. So, if the latency has been set to 2.0 seconds, it would come out at 2.0 - 1.2 = 0.8 seconds after it was sent. Don't make the resulting delay too short, anything less than about 0.5 seconds might cause network problems...
