### ISSUE TITLE
Car Installation [Discussion Thread]

### ISSUE THREAD

**Issue by mikebrady** [mikebrady/shairport-sync#724]
This issue is about car installations of Shairport Sync. The suggested method for a car installation is described in [CAR INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/CAR%20INSTALL.md). See the next comment for an alternative approach.

**Comment by mikebrady** [comment]
# From [FnasBas](https://github.com/FnasBas)
This contribution, from [FnasBas](https://github.com/FnasBas), is based on [this comment](https://github.com/mikebrady/shairport-sync/issues/482#issuecomment-402543454).

Here's a starting point. I hope it is useful to someone :)

# Alternative car setup approach
This is offered in the hopes it will be useful to someone. The background is that, besides all the advantages of WiFi/AirPlay over Bluetooth,
when travelling my phone is my only internet connection, and I want to be able to share it with other devices.
Like an iPad or laptop. I may also want to be able to send audio to the car Shairport Sync service from my other devices while
simultaneously having internet access on them, via the phone.

So the basic idea is just to turn the table on which device acts as the Access Point for the WiFi. Which works perfectly well.
The prerequisite is that your carrier/contract allows tethering, as otherwise you won't be able to have your phone act as a WiFi Access Point.
I also think this is a bit simpler to set up as you don't need to set up `hostapd` and a DHCP server on the Pi.
The drawback is that you need to do a gesture and tap a button on the phone to make its network discoverable when entering your car.

## Phone configuration
Enable tethering on your iPhone with a secure passphrase. 

## Raspberry Pi configuration
Set up Shairport Sync according to your needs and instructions found elsewhere.

### Network
Configure your Raspberry Pi with only one WiFi network. Through experimentation I found that if I was in the vicinity of my home network,
the Pi would not reliably choose the iPhone's WiFi network even though it was prioritized over the home network.
And it seems `wpa-supplicant` in general is a bit difficult to get to roam between different WiFi networks once it's decided on one.

Example of `/etc/wpa_supplicant/wpa_supplicant.conf`

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1  
country=SE  
network={  
	priority=3  
	ssid="My unique clever wifi network name"  
	psk="My very secure wifi key"  
}  
```

### Read only root filesystem
By configuring your Pi to have a read only root filesystem, you need not ever worry about an improper shutdown of the OS
causing the Pi to fail to boot. You will also be sure that the Pi always boots to a predetermined state.
And you will eleminate wear on the SD card completely except for when modifying the system.
This will result in a very reliable AirPlay service. 

These instructions are a bit old but a good starting point: (https://openenergymonitor.org/forum-archive/node/5331.html) 

In addition to what's laid out there I've also:

* Added the `/boot` fs to be mounted read-only and modified the rpi-rw/ro scripts and `/etc/fstab` accordingly
* in `/etc/systemd/journald.conf`, set `storage=volatile`
* As the `systemd` `ntp` client is hard-coded to use a specific path for its book keeping, I've disabled that and installed `ntpd`
and set the drift file to `/tmp/drift`
* Your DHCP client will complain that it can't write its lease to a file. You can work around this by setting it to write its lease
to a file in `/tmp` or disregard it as it will work fine in any case.

In my case I do not use a car stereo but go straight Pi>Dac>Power amplifier. So I've also set up EQ with `alsa`, and a relay module to a
GPIO pin and some scripts that run on session start/stop that turns the power amplifier on and off accordingly.
But this could turn in to "How I set up my car audio" rather than offering an alternative to [what's currently suggested
for a car installation](https://github.com/mikebrady/shairport-sync/blob/master/CAR%20INSTALL.md).
So I stop. ;)

## Using it
Make your phone's network discoverable. In iOS 11 there's a shortcut for this – swipe up and hold down on the connectivity section.
There's a button to turn on Internet Sharing.
In my experiments the Pi connects almost instantaneously to this network and a few moments later the AirPlay service offered by Shairport Sync
will become visible.

## Changing and Maintaining it
Make your phone network discoverable. The Pi connects. Connect your laptop to the same network.
The iPhone does not appear to resolve host names from one tethered device to another so you need to `ssh` to the Pi's IP-address.
There's a number of ways to find the Pi's IP-address:

* You can check your laptop's IP and try subtracting or adding from the last octet
* Use a `zeroconf/avahi` browser tool and locate the AirPlay service and find the IP address that way
* Use `nmap` or other similar utility to scan for the Pi

`ssh` to the Pi
```
rpi-rw
change stuff
rpi-ro 
```

### Further thinking
Other Apple devices can wake the WiFi Access Point on the iPhone. My conclusion is that this must be accomplished via Bluetooth,
but Apple doesn't seem to be open spec on this subject as all I've been able to find is that certain devices, when paired with Bluetooth,
connected to iCloud etc. etc. will offer this functionality.
Being able to reverse-engineer what Bluetooth communication is actually done in order to turn on the WiFi Access Point on the phone
would mitigate the drawback of this method, as the Paspberry Pi could be constantly looking for the phone via Bluetooth and
enabling Internet Sharing that way.

**Comment by mikebrady** [comment]
# From [FnasBas](https://github.com/FnasBas)
This contribution, from [FnasBas](https://github.com/FnasBas), is based on [this comment](https://github.com/mikebrady/shairport-sync/issues/482#issuecomment-404470479):

I found a huge disadvantage btw with my car setup approach. Something that never occurred to me. That is that if you're without cell phone coverage, the phone wont properly act as a WiFi access point.

But I still need that Internet sharing when I have it. So maybe some hybrid set up would be ideal. Need to figure out if and how one would do e.g. provide both a network from the Pi and have it probe for the phones network and whenever found, jump to that rather than being an AP.

**Comment by mikebrady** [comment]
# From [FnasBas](https://github.com/FnasBas)
This contribution, from [FnasBas](https://github.com/FnasBas), is based on [this comment](https://github.com/mikebrady/shairport-sync/issues/482#issuecomment-405082892):

[...] My problem with no cell reception became a real problem. It's nice to be forcibly disconnected from everything, but not without my music! I'm in a part of the country where basically only one carrier has coverage. So I had to fix it. And the only way of working on the pi was removing the sd-card, editing config files on my lap-top, re-inserting it and hoping for the best. So not the best of circumstances. Either a local console or an ethernet connection would have helped greatly. (thanks Apple for removing ethernet from the macbook pro..)

Anyways, the way it's set up now is:
At boot, look for the iphones network
If not available, start up hostapd and dnsmasq as dhcp-server.
ta-da.
It boots so quick and I have the power switch very handy so it's completely acceptable for the moment.

The limitation is obviously that it only happens at boot, and that it's a hack. But I needed to have music on my trip :) I'll probably work on getting it more stable when I get home.

The point of my alternate car approach was of course to have booth teathering and airplay available. And only audio when there's no coverage. Which never happens at home.. So the setup I'm going to gp for is to primarily use the Phone as an AP whenever possible and then with some degree of automation falling back to the pi providing it's own network.

It's getting complex, but fun as well :)

By the way. My phone (6S iOS 11.4) doesn't behave as you claim in the CAR SETUP.md file. Maybe I've missed something, but my dhcp server is not pushing any gateways or routes. Just assigns an IP on a /24 network. When the phone is connected to this wifi and has cell coverage, I can't get internet access. I've probably missed something. Don't care for the moment. Have music, Happy traveling. :)

**Comment by mikebrady** [comment]
Hmm. I have been using the setup described in [CAR INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/CAR%20INSTALL.md) all over Europe for well over a year now without problems -- yay for EU Roaming! The phone I use -- an iPhone 6, fully updated -- works normally, with full internet access.

**Comment by FnasBas** [comment]
Back home, and have been thinking a bit about this along the way.

The holy grail for me would be:

* A network provided by the pi as described in CAR SETUP.md (and getting the phone to continue to have internet access even when connected to this dead end network)
* The pi looking for the phones network and whenever available connecting to it.
* preferentially the Pi continuing to provide it's own network whilst connected as a client to the phones network.

All this without any extra hardware over the Pi and the audio interface.

This would be simple with an extra USB wifi dongle dedicated to either being a client or base station, but I would prefer it if it could be accomplished with only the raspberry pi 3 model b+ hardware. 

Experimentation to follow.

One thing I considered for a while was if one could find a very small wifi access point which would be happy running directly on car power (i.e. something in between 11.5-ish to 14.1-ish volts), and connect that to the ethernet port on the pi. This would probably be the most reliable solution, but also a bit messy and possibly difficult to find the space to install it in the car.

I should add that the car I'm working with here is my camper car (no not camper van, camper Car). So it gets a bit more complicated. It's also the reason the tethering functionality of the phone is so important to retain. If it was my regular get from point a to b car, the problem with losing coverage and such would be so small I could disregard this whole thing.

The use case is e.g. when having found a spot for the night, being able to play/stream some media on e.g. my laptop, have internet access via the phone, and have the audio playing on the car sound system thanks to shairport-sync. And in the case of no cell service, at least be able to play local media on the laptop or whatever and have the sound play through shairport-sync. I may be over reaching.. ;)

**Comment by FnasBas** [comment]
Found this thing that will solve all my issues quite affordably:
https://www.tp-link.com/au/products/details/cat-9_TL-WR802N.html
Connecting that to the Ethernet port of the Pi would most likely be quite solid.

But I'm going to give the stuff laid out above a try. If I can't figure it out, or it turns out not to be possible to get reliable enough, I'll go with the mini-ap. I guess that solution is a bit out of scope of the shairport-sync project, so if it turns out that way, my suggestion is to keep the two separate car install docs, and put a big Caveat at the top of mine saying this only works when you have a functioning internet connection on your phone.

**Comment by FnasBas** [comment]
Done some work, had some success!

First try and undo all the dirty hacks from the road..

Then followed:
https://github.com/peebles/rpi3-wifi-station-ap-stretch

And, at least on the bench, it actually works quite well.

I've tried:

## Booting up the pi without internet sharing enabled on phone. 
Results in the pi's network becoming visible and connectable. Shairtport-sync service is visible and usable. The issue I had with the phone not having internet access while connected to the pi's dead end network was my fault. dnsmasq pushes a default gateway by default, disabling that leads to the behaviour described in CAR INSTALL.md.

### From the state above, 
enabling internet sharing on the phone. The pi connects to the phones network. shairport-sync service visible and working, now over the phones network. 

### From this state, 
connecting my laptop to the Pi's network. shairport-sync service visible and usable from the laptop.

### Connecting the laptop to the phones network. 
shairport-sync works fine and internet access from the laptop and pi is as good as your cell signal.

I also tried leaving out the option in dnsmasq not to send a gateway, and set up masquerading and ip forwarding on the pi. With the pi connected to the phones network, I can get internet access on the laptop via the pi's network. However there seems to be some serious performance degradation when using it like this. So for my ultimate raspberry pi car audio system and more, I'd probably still go for the mini-ap connected to the ethernet port. Then the car would have it's own wifi network provided by a "proper" hw access point. And if the pi has internet access via the phone's network, any client connected to the car wifi would also have internet access.

But as long as we're keeping this in the scope of shairport-sync, I think it looks quite promising. You can have your cake and eat it too. What do you think? It obviously needs some proper field testing. But at least on the bench it works pretty much exactly how I wanted it to. 

This raspbian installation has been through so many changes by now that I ought to wipe it and start over and document the whole thing from beginning to end.

**Comment by FnasBas** [comment]
Field report.

It sort of works. But not good enough. There's something going on when using the the built in WiFi as both an AP and client simultaneously (even when the client is not actively connected to a network) and the performance for clients connected to the Pi's network will not perform good enough for totally smooth airplay playback. It's just barely noticable when listening to e.g. an audio book or podcast, but for music it's unacceptable in my humble opinion.

I will proceed like this:

* Get the mini ap, and connect it to the ethernet port of the Pi (I'm calling this the car network)
* Dedicate the built in WiFi of the Pi as a client for the Phones network
* Do an exemption for the Phones MAC address so not to send a gateway when it connects as a client on the car network (thereby retaining internet connectivity on the phone, while it's using the car network for airplay)
* Push regular full DHCP responses to all other clients on the car network
* Set up a VPN on the Pi so if I'm using the car network, I will effectively be on my home network
* The Pi will also run a mpd server for pure music enjoyment

This will also give some advantages for other devices, as at least iOS and OSX devices will not automatically connect to an iPhones shared network, when turned on/woken up. While they will instantly connect to the car network if they see it, be it a dead end or not.

When enabling internet sharing on the phone, the car network will be connected to the internet with the Pi acting as a NAT router via WiFi over the phones network.

It could be the case that performance with my current set up will improve with future driver or firmware updates, but it might just as well not.

So @mikebrady I leave it to you as this is your baby. In the process of doing the above I will start over from scratch with this installation. And as a part of that I could document the process of getting from a clean raspbian installation to a shairport-sync ready service, using the Phone as an AP as my original proposal. It will work perfectly fine as long as you have cell service.. ;) It would also include steps for running it in read only mode as I feel that is important for both the longevity of the sd card, and the reliability of the service. I think I could keep it in scope of shairport-sync.

So, if you'd like, I'd be happy to contribute that documentation. If you feel it doesn't add something useful enough, I'll be on my way and continue to use your fantastic project in all sorts of applications.

**Comment by FnasBas** [comment]
As I didn't get a response (not blaming, simply accepting the fact), I went ahead and did it my way. This is way beyond the scope of shairport-sync. But in case someone finds it useful, I'm leaving a link here. At the time of writing this it's still a work on progress.

https://hedenberg.org/carsetup/

**Comment by mikebrady** [comment]
@FnasBas, thanks for this interesting write-up. I've put a link to it at the top of this thread.

**Comment by FnasBas** [comment]
Thanks :)

tis 7 aug. 2018 kl. 12:41 skrev Mike Brady <notifications@github.com>:
