### ISSUE TITLE
shairport-sync device disappears from Airplay device list [Resolved]

### ISSUE THREAD

**Issue by oscar-c** [mikebrady/shairport-sync#725]
I ran 2 shairport-sync instances on my host. After I streamed music from my iPhone to one of the instances for some time (couple hours), both instances will stop showing up on the Airplay device list.

- My host has wired connection;
- After shairport-sync devices disappeared, other Airplay-compatible devices on the local network would can still be discovered by the iPhone;
- While the iPhone can not discover shairport-sync devices, my second iPhone can still discover and stream to them;
- Both iPhones are running iOS 11.4.1;
- A quick fix is to turn Wi-Fi off and on;
- I've tried turning the iPhone off and on, and reseting network setting, but this problem comes back;
- If I wait for a while (~10 min), the shairport-sync devices will reappear in the airplay device list, but when try to connect to them, I'm asked for the password again.

[The startup log is here.](https://gist.github.com/oscar-c/abbd8a6b8dc79a5d42949e5328cf2dbd)

**Comment by mikebrady** [comment]
Thanks for the post. This is indeed a mystery, and it looks awfully like some obscure kind of network problem. It your router up to date and configured properly? Routers can sometimes do weird things with multicast going between wired and wireless. Does it have any firewalls running?

Separately, I guess one thing I would do straight away is remove the non-ASCII characters from the service names, though I have no idea if it makes any difference. The fact that you can connect and stream from the second iPhone (point 3 above) is very curious. Is it always the same iPhone that is the second one? (I'm wondering does one iPhone use a 2.4 GHz WiFi and the other a 5 GHz connection, which again would point to a router issue.)

There are a few apps -- "Discovery" from TildeSoft on iOS / "Bonjour Browser" on the Mac -- can let you see what Zeroconf/Bonjour messages can be seen on the iPhone/Mac, so you could see if the Shairport Sync service really has disappeared or not (AirPlay uses Bonjour to advertise its services.) Similarly, if you install `avahi-utils` on the Pi, it can show you what Bonjour services are being advertised.

I guess one of your speakers is a Bluetooth speaker? So, I guess the next thing is to see if the problem arises when you only run one Shairport Sync instance (and I'd select the wired one...). A think to keep an eye on might be the processor load, e.g. use `htop` or similar to view it when the service disappears.

**Comment by oscar-c** [comment]
Thanks for the reply. I did few things:

- I installed Bonjour Browser on macOS and Discovery on iOS;
- I used Wireshark to tap into the network interfaces on iOS and my host.

I discovered following when the iPhone cannot discover shariport-sync devices:

- The iPhone cannot discover other services advertised by the host.
- When trying to resolve the host's MDNS name from iPhone (using `ping [hostname].local`), on Wireshark running on the **iPhone's** interface, I can see only MDNS query packet being broadcased asking for the host name;
- Also during the ping, on Wireshark running on the **host's** interface, I see both iPhone's query and host's response being broadcasted.
- On the iPhone's interface, I can still see other hosts' MDNS responses.

I gess now this is more of a MDNS/avahi problem than a shariport-sync problem.

**Comment by mikebrady** [comment]
That's good detective work -- I didn't think of suggesting Wireshark. I wonder if the router is somehow suppressing returns from the host (maybe it is deliberate -- some setting or other). It would be interesting to see if the returns were visible from another wired device while they are invisible to the iPhone.

**Comment by oscar-c** [comment]
When iPhone cannot discover shariport-sync devices:

- "The returns" are visible from another host (wired), but are not sent to the iPhone;
- `ping 224.0.0.251` (the multicast address for mDNS) on the host that runs shairport-sync should reveal all hosts that registered for receving the multicast. But the ICMP packets were not sent to the iPhone, however "another host" can receive and reply the ICMP packets.

Below is a diagram for the topology of my network.
```
                                        +---------------------+
                                        |                     |
                                        |  commercial router  |
                                        |                     |
                                        +-----+---------------+
                                              |
                                              |
                                              |
                                              |
                                        +-----+----+
                                        |          |
                          +-------------+  switch  +--------------------+
                          |             |          |                    |
                          |             +----------+                    |
                          |                                             |
                          |                                             |
                          |                                             |
              +-----------+----------+                      +-----------+-----------+
              |                      |                      |                       |
          +---+  switch/wireless AP  |                      |  shairport-sync host  |
          |   |                      |                      |                       |
          |   +------------------+---+                      +-----------------------+
          |                      /
          |                      /  (wireless)
+---------+--------+     +-------+------+
|                  |     |              |
|  "another host"  |     |  the iPhone  |
|                  |     |              |
+------------------+     +--------------+

```

I begin to doubt it's the `switch/wireless AP`'s fault.

**Comment by noelhibbard** [comment]
I have this problem but only in my bathroom. I have one AP the covers my whole house and backyard well and another one outside in a bush which covers the front yard. My bathroom is very close to the outdoor AP so I think my phone tends to randomly roam between the indoor AP and outdoor AP when ever I am in my bathroom. I have a shairport-sync instance for the bathroom, back porch, garage and livingroom. I always see my shairport-sync instances when I am in the livingroom (connected to the indoor AP 100% of the time) and I always see my shairport-sync instances when I am standing outside right next to my outdoor AP. The only place it is a problem is when I am sort of randomly jumpping between the indoor and outdoor AP.

I have OpenWRT running on both of my APs.

@oscar-c, do you happen to have multiple APs in your home?

On another note, I also have Shairport4w running on a hardwired computer and an Apple TV4 (also hardwired) which both show up on my list even at times where my shairport-sync instances (also hardwired) are missing.

**Comment by mikebrady** [comment]
Thanks @noelhibbard. @oscar-c, I'd really be looking at the switch or switch/wireless AP. If one of them was blocking some packets going between the wired shairport sync host and the WiFi network, would that not account for what you're experiencing?

**Comment by oscar-c** [comment]
Today I did another test, turned my host that runs shairport-sync into a wireless AP in bridge mode. Then I connect my iPhone to it.
Still, the shairport-sync instance will disappear from the device list.

**Comment by oscar-c** [comment]
I managed to find a workaround for this problem. The cause for this problem is the multicast package will not reach my iPhone ( I remember reading it somewhere that the way multicast works on wireless net work is different that on ethernet). So I just sent large amount of multicast packages to force this channel open again.

I wrote [this script](https://gist.github.com/oscar-c/178ac28495d8f2319323bedf8ccf5e8a) and have `corn` run it every minute on the host that runs shairport-sync. Now I don't have this problem anymore.

**Comment by mikebrady** [comment]
Yikes, that is a bizarre workaround, but if it works, 😎. Good work!

**Comment by oscar-c** [comment]
I should've posted the following earlier:
This problem was now completely gone after updating to iOS 12, and now my iPhone is running iOS 13, there is no such problem either.

**Comment by mikebrady** [comment]
That’s good news indeed, thanks.
