### ISSUE TITLE
NTC chip and microwave oven [Solved]

### ISSUE THREAD

**Issue by pieman68** [mikebrady/shairport-sync#726]
Firstly Mike thanks for the fab shairport-sync. I have been using this for a couple of weeks with the NTC chip someone gave me. it has been working great and the quality of audio is good. I had occasional breakups of audio in the past and resyncing.. droput and then speeding up which i couldn't understand. I have discovered that my Logic microwave oven when cooking  screws up something and I get drop out as described above continually. So either the the NTC chip is not very well screened (bare) or the microwave oven is producing excessive microwave/EMF energy?? It is repeatable. Could be a reason other users are having issues. The microwave oven is approx 8 feet from the chip and the iphone that feeds it over wifi. Just thought this might help as maybe other users issues are not with your software or inherent wifi connection but something else in their wifi/home environment?

Thanks Again

Simon

**Comment by mikebrady** [comment]
Thanks for the post, Simon.  The problem you have observed is almost certainly the microwave — see [here](http://sciabc.us/F6Gaa) for example. I’ll add it to the troubleshooting pages.

**Comment by pieman68** [comment]
Now I have reheated my dinner in the microwave my NTC. iphone and shair-pont are working beautifully!
