### ISSUE TITLE
Logs?

### ISSUE THREAD

**Issue by tswaddell** [mikebrady/shairport-sync#727]
I've installed shairport-sync on a Rasberry Pi 3 running Rasbian 9.  I believe I have it installed correctly on the pi, but I don't see it as an airport option on my 2 ios devices running 11.4.1.

I've worked through the installation instructions a few times and tried installing it from the repositories.  But no luck.

Are there program logs I can review to troubleshoot this?

Thanks!

**Comment by tswaddell** [comment]
Thanks for your fast reply, Mike.

Here's the output:

Version:
`3.2.1-OpenSSL-Avahi-ALSA-sysconfdir:/etc`

Status:
```
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-08-06 08:02:38 PDT; 4min 10s ago
 Main PID: 529 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─529 /usr/local/bin/shairport-sync

Aug 06 08:02:38 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

Journal:
```
...
Aug 06 08:02:38 raspberrypi systemd[1]: Starting LSB: powerful, efficient, and scalable Mail Transport Agent...
Aug 06 08:02:38 raspberrypi systemd[1]: Starting Samba NMB Daemon...
Aug 06 08:02:38 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Aug 06 08:02:38 raspberrypi systemd[1]: Starting OpenBSD Secure Shell server...
Aug 06 08:02:38 raspberrypi systemd[1]: Starting /etc/rc.local Compatibility...
Aug 06 08:02:38 raspberrypi systemd[1]: Starting Permit User Sessions...
Aug 06 08:02:38 raspberrypi systemd[1]: Started /etc/rc.local Compatibility.
Aug 06 08:02:38 raspberrypi systemd[1]: Started Permit User Sessions.
Aug 06 08:02:38 raspberrypi systemd[1]: Starting Hold until boot process finishes up...
...
```

Needless to say, still no joy.

**Comment by mikebrady** [comment]
Okay, so it looks like Shairport Sync is actually running.

A couple of questions: 
* Are you running a firewall somewhere?
* Do you have two active network ports on your Pi?

There is an iOS app called "Discovery" from TildeSoft (they also do "Bonjour Browser" for a Mac) and `avahi-browse` in the `avahiutils` package to allow you to see what is being advertised at the Shairport Sync end and what is being seen as the iOS device end.

If something isn't getting through, the usual culprit is a firewall somewhere or a bad-quality router.

Alternatively it might also be that Shairport Sync is advertising its services on another [i.e. the wrong] network port.

There's a bit more detail on the [TROUBLESHOOTING.md](
https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page.

**Comment by tswaddell** [comment]
Thanks for the tip about the iOS discovery app.  With the app, I can see the airplay stream coming off of my Apple TV, but can't find anything coming out of the pi.

I'm running a very good Netgear R7000 router. Just to be sure, I moved the pi into the same room, a few feet from the router.  No go.

I'm not currently running a firewall on the PI and have disabled ufw.

I am running the stock shairport-sync config file.

I have turned off power saving/low power modes.

Only one network connection wlan0 and I turned off eth0.

**Comment by mikebrady** [comment]
Thanks for the update. In the configuration file, at `/etc/shairport-sync.conf`, there is a setting in the `general` section called `interface`. If you uncomment this and give it the name of the interface you want to advertise on (e.g. `wlan0`) and reboot, then you should be safe using both network ports.

Using `avahi-browse` on the Pi, you should be able to see that it’s advertising the Shairport Sync AirPlay service, and indeed you should be able to see the AppleTV service as well. If not, then something — maybe some setting — is up with your network. Bonjour relies on multicast — is it possible that the Netgear router is suppressing multicast or something like that?

**Comment by tswaddell** [comment]
I reimaged the pi and got it working.

Thanks for your time and help with this--not to mention the great software.

**Comment by mikebrady** [comment]
I’m glad it worked out for you.
