### ISSUE TITLE
Is there DACP support in shairport-sync?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [mikebrady/shairport-sync#729]
Hi,

There is a homebridge plugin for DACP control of a music player, and it seems that shairport has some DACP support. Can it paired with the homebridge platform somehow? What capabilities does the implementation expose?

**Comment by FredrikKarlssonSpeech** [comment]
Ah, I see. So shairport does not receive DACP commands, but may send them then. So basically it may have a similar role as the homebridge plugin would have (I guess - I am not sure I understand this yet).

The repo for the plugin is here https://github.com/grover/homebridge-dacp

**Comment by mikebrady** [comment]
Thanks for the information. You’re right about Shairport Sync’s role — it essentially sends requests as DACP messages to the audio source, which could be iTunes, etc.

**Comment by toby** [comment]
Hi, if it's helpful I just released a project that uses shairport-sync to get the DACP info for the playback source, then issues commands directly to the DACP HTTP server.

https://github.com/toby/onair

It only supports three commands right now (`nextitem`, `previtem`, `playpause`).

**Comment by toby** [comment]
Thanks @mikebrady! If you're curious, I wrote up some of the reasoning for making this project here:

https://reddit.com/r/linux/comments/9icnfw/onair_shairportsync_metadata_display_and_control/

Also, it will be very easy for me to add the rest of the DACP commands so I should probably do that.

**Comment by toby** [comment]
I've implemented the rest of the DACP commands for `onair`. You can use the same command name as in the protocol as well as some friendlier aliases:

https://github.com/toby/onair#usage
