### ISSUE TITLE
Disable volume control

### ISSUE THREAD

**Issue by silverwind** [mikebrady/shairport-sync#73]
Very minor issue, but I run with
```
shairport-sync -d -a Name -- -d hw:0 -t hardware -c PCM
```
Now, I'd like to just disable the volume control (always have it at 100%), while retaining the other benefits from the hardware options. If I just remove `-c PCM`, I get this error:

````
shairport-sync[973]: Failed to find mixer element
````

Maybe an option to disable volume control would help?

**Comment by mikebrady** [comment]
I'm not sure I understand – why would you want to disable the volume control?

**Comment by silverwind** [comment]
Because I usually run my Macbook at around 20% volume, and for some reason the audio is almist inaudible at that volume on my HiFi. Now I could crank it up every time on the Macbook, but it's a bit inconvenient, and I'd prefer to use the HiFi remote for that :)

**Comment by mikebrady** [comment]
Fair enough. I'll put it on the list. The number of command-line options is getting a bit crazy, so I'm beginning to work on an /etc/shairport-sync.conf settings file, and when that's working, I'll add a setting, if that's okay.

**Comment by silverwind** [comment]
Sure. It's just a minor inconvenience, no hurry :+1:

**Comment by mikebrady** [comment]
Hi there. This is a new setting in the (new) configuration file in the development version.

**Comment by silverwind** [comment]
Thanks! I've been having some trouble getting the development branch to compile:

```
gcc -DHAVE_CONFIG_H -I.    -Wno-multichar  -g -O2 -MT shairport.o -MD -MP -MF .deps/shairport.Tpo -c -o shairport.o shairport.c
shairport.c: In function 'parse_options':
shairport.c:414:17: error: 'shairport_cfg' has no member named 'metadata_enabled'
           config.metadata_enabled=0;
                 ^
shairport.c:416:17: error: 'shairport_cfg' has no member named 'metadata_enabled'
           config.metadata_enabled=1;
                 ^
shairport.c:423:17: error: 'shairport_cfg' has no member named 'get_coverart'
           config.get_coverart=0;
                 ^
shairport.c:425:17: error: 'shairport_cfg' has no member named 'get_coverart'
           config.get_coverart=1;
                 ^
shairport.c:431:15: error: 'shairport_cfg' has no member named 'metadata_pipename'
         config.metadata_pipename=(char *)str;
               ^
Makefile:487: recipe for target 'shairport.o' failed
```

Is it stable enough yet?

**Comment by mikebrady** [comment]
Yikes – it's working for me. Could you try a `make clean` first?

**Comment by mikebrady** [comment]
Wait – you might be right. I'm just checking something w.r.t. conditional compilation.

**Comment by silverwind** [comment]
Yeah, no difference on `make clean`. It errors pretty fast. I'm on Archlinux ARM, using the build steps in https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/shairport-sync

**Comment by mikebrady** [comment]
Yeah, sorry, I know what's wrong: I've been compiling it with the `--with-metadata` configuration option, and when I turn that off, some metadata-specific code is inadvertently left behind, causing the problem. Give me a few minutes to upload a fixed version.

**Comment by mikebrady** [comment]
Could you do a `git pull` to get an update to `shairport.c`.

**Comment by silverwind** [comment]
That did it, thanks. Will try to test this volume thing now.

**Comment by silverwind** [comment]
Looks to be working great, thanks again!

**Comment by mikebrady** [comment]
Cool.
