### ISSUE TITLE
Audio channel discovery on macOS

### ISSUE THREAD

**Issue by hstriepe** [mikebrady/shairport-sync#731]
Currently I resorted to enabling shairport-sync with the active default device and then changing it. I have not found a device list that I could use with shairport-sync recognizing it.

Is there a way to get a listing of the valid devices in a configuration that would be recognized by shairport-sync on the command line?

Would love to set up a startup daemon that holds a particular device (USB AUDIO DAC.)

**Comment by whizkid79** [comment]
same issue here

**Comment by Rastafabisch** [comment]
I don't think this is possible, as the OS handles the audio routing and not certain applications. [Though there is (paid) software out there which does provide individual sound routing.](https://rogueamoeba.com).

**Comment by whizkid79** [comment]
Actually thats not true. There are different types of application. Some just play audio and let the system decide what to do with it. For those you need extra software to route the audio. But on the other hand there are loads of other software that is more aware of the audio capabilities of the system like any normal DAW or even "simple" recording software like audacity lets you chose recording and playbay channels/devices.
Not sure how flexible libao is on the mac, but it has a dev flag you can pass onto it, so it should be possible to chose a audio device at least.

**Comment by dge8** [comment]
Sorry to comment on a closed issue, noting for posterity that AFAICT the dev flag for the macosx driver in libao has _never actually worked_. There is a fix [here](https://gitlab.xiph.org/xiph/libao/-/merge_requests/7) that I've bumped - if you manually compile libao using this patch it works. If patch ever gets merged (last release 1.2.2 was in 2016, although there was merge activity up to 2021) then that will solve this issue when using the libao backend.
