### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by arjunmenon** [mikebrady/shairport-sync#732]
Hey
I had installed this and it was running for a moment, even after a reboot. But after few days, it stopped working. It doesn't show up in my Ipad.

I tried re-installing everything, restarted multiple times and even then nothing appears.

I followed your trouble shooting guidelines, still didn't work.

How to debug this?

Running in RPI3 jessie.

```
pi@raspberrypi:~ $ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled)
   Active: active (running) since Sun 2018-08-19 20:57:48 UTC; 7min ago
  Process: 1135 ExecStartPre=/bin/sleep 5 (code=exited, status=0/SUCCESS)
 Main PID: 1178 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─1178 /usr/local/bin/shairport-sync

Aug 19 20:57:48 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

**Comment by mikebrady** [comment]
Thanks for the post. Have a look in some of the closed issues, especially #727, for information about logs and some other tools for discovering what's what.
