### ISSUE TITLE
Crackling noise when reducing volume to 0

### ISSUE THREAD

**Issue by Ewald342** [mikebrady/shairport-sync#736]
Plattform: Pi Zero with Adafruit Speaker Bonnet
Raspbian: 9.4, Linux 4.14.62+ armv6l GNU/Linux
Package: shairport-sync
Version: 2.8.6-1
Architecture: armhf

While streaming from iTunes/iPhone to shairport-sync and reducing volume to 0 **via alsamixer** i get a constant crackling noise until i raise the volume.
This does not occure when lowering volume in iTunes, although the volumecontrol is linked to the same device in shairport-sync.conf:
`mixer_control_name = "PCM";`

While playing audio i.e. with mpd lowering volume to 0 with alsamixer works just fine.

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest that you update Shairport Sync to the latest version (currently 3.2.1). There have been many important bug fixes since 2.8.6, and maybe the issue you have has already been dealt with.

**Comment by Ewald342** [comment]
Thanks for your fast answer.
I used the official repository raspbian.raspberrypi.org

Is there a precompiled 3.2.1 somewhere?

**Comment by mikebrady** [comment]
I’m afraid I don’t know. The official repository can lag behind quite a bit, as they have a long qualification process to go through.

**Comment by Ewald342** [comment]
OK, i will try to compile it...

**Comment by mikebrady** [comment]
Okay. Just FYI, the [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) page has a quick guide for an up-to-date Raspberry Pi.

**Comment by joerg-krause** [comment]
Same here on an embedded Linux (i.MX6UL) board.

```
# shairport-sync --version
3.2.1-OpenSSL-Avahi-ALSA-stdout-pipe-metadata-sysconfdir:/etc
```

Crackling noise occurs when setting volume to 0.

**Comment by joerg-krause** [comment]
With version 2.8.6 the crackling noise only occurs when setting the volume to 0 via amixer/alsamixer, but not when using the AirPlay slider.

With version 3.2.1 the crackling noise occurs using both methods.

**Comment by joerg-krause** [comment]
So I went back in time until version 2.8.3.6. This is the version shortly after the ALSA softvol plugin was introduced. The crackling noise only occurs for 1 or 2 seconds when setting the volume to 0 using amixer.

**Comment by joerg-krause** [comment]
It turns out this isn't related to the program, but to my complex ALSA plugin configuration.

For reference, the crackling noise occurs when using the following PCM plugin path:
```
softvol ➜ plug ➜ multi ➜ hooks ➜ hw
```

.. but does **not** occur when using the following path:
```
plug ➜ multi ➜ softvol ➜ hooks ➜ hw
```

**Comment by mikebrady** [comment]
Thanks for the update. So, does it mean that Shairport Sync is "off the hook", so to speak?

**Comment by joerg-krause** [comment]
The issue does not occur with other audio players, like MPD. So, it is specific to Shairport Sync, I would say.

**Comment by mikebrady** [comment]
Hi there. I  have been busy trying to improve the general reliability of Shairport Sync, and one of the things I've done is to rebuild the volume control and muting software. Volume control has its own mutex and the calculations are simplified quite a bit. I have certainly noticed an improvement in the (for want of a better word) "smoothness" of the response when using the built-in software attenuation, an external mixer or -- especially -- a combination of both.

If you got a chance to test it and see if your crackling problem remains, I'd be obliged. At present, it's in the `unstable` branch, but it's actually probably reasonably stable.
