### ISSUE TITLE
command line tool to mux in a wave file?

### ISSUE THREAD

**Issue by hplato** [mikebrady/shairport-sync#737]
This might be a very niche and specialized use case, but could there be any method to multiplex in a wave file into a playing stream. Think the mail sound from an iphone when streaming audio.

Right now I 'aplay' the wave file to the same alsa device that shairport uses and the audio gets mixed. I use a Delta 410 so that I can run 4 rooms off one server.

However being able to do this through shairport would allow for distributed audio and I wouldn't need multi-out audio. 

Best case there would be a command like shairplay "Name of Published Airplay Source" /tmp/sound.wav.

**Comment by mikebrady** [comment]
Thanks for the interesting post. To be honest, it would be down the list of priorities. In principle, it could be done via the D-Bus interface, but would take a fair bit of work...

**Comment by hplato** [comment]
Thanks Mike, appreciate the response. Never hurts to ask!
