### ISSUE TITLE
Change Port from 5000?

### ISSUE THREAD

**Issue by xXRoboBoyXx** [mikebrady/shairport-sync#738]
I have Octoprint, which uses port 5000 for it's web interface. Can i change the configuration of shareport-sync so it doesn't use port 5000? and so i can start Octoprint with no issues?

**Comment by mikebrady** [comment]
Yep -- it's a setting in the configuration file.

**Comment by xXRoboBoyXx** [comment]
This may be a stupid question- Where's the configuration file?
