### ISSUE TITLE
HDMI audio lead in silence

### ISSUE THREAD

**Issue by dbugg** [mikebrady/shairport-sync#739]
Hi Mike, thanks for your brilliant work. I am using s-s via HDMI and I also use HDMI CEC to start stop the amp. Is there a way to **delay the start of audio** (fill silence) so I won't miss the first 5 seconds of the song? Thank you.

PS: I've tried _audio_backend_silent_lead_in_time_ to no avail as it seems it has different purpose (audio sync).

**Comment by mikebrady** [comment]
Thanks for the kind words. You could try the `audio_backend_latency_offset_in_seconds` setting -- that's added to the latency. The maximum amount is 1.5 seconds though. Does it help?

**Comment by dbugg** [comment]
Thanks for the prompt reply. However, after fiddling with `audio_backend_latency_offset_in_seconds` s-s.conf I don't hear any difference. Then I found this:

> This usage is discouraged -- the `audio_backend_latency_offset` in the appropriate backend stanza (e.g. in the "alsa" stanza) should be used for this. Static latency settings are now deprecated, and will be removed in a future version of Shairport Sync.

Does this mean I have to fiddle with the **alsa** driver? Thank you.

**Comment by mikebrady** [comment]
I may have forgotten to update the documentation. Let me check and get back to you.

**Comment by mikebrady** [comment]
Hello again. What you found was in the release notes to a rather ancient version of Shairport Sync -- 2.4.2. The latest is 3.2.1 -- which I encourage you to update to -- has somewhat different settings and, if you look in the sample `/etc/shairport-sync.conf`, you'll can see that you can set the `audio_backend_latency_offset_in_seconds`, now in the `general` section, to up to 1.5 seconds. This will add 1.5 seconds to the dynamic latency -- usually 2 or 2.25 seconds --  that is negotiated between the player and Shairport Sync. Thus the delay will be 3.5 to 3.75 seconds. It's some ways short of five seconds, but I guess the first thing to check is whether you can experience it. If so, then maybe I can extend the range.

**Comment by dbugg** [comment]
Thank you for your time. I have the latest version. 

Also I found the culprit. 

It’s the handshake between the the Pi and the receiver. Every time the PCM stream is sent there’s a negotiation, which cuts the song. I have a separate SD image with OSMC and there’s a setting HDMI Keep Alive, which fixes the issue. I’ll keep you posted if I find a solution for shairport. Thanks again and keep the good job.

**Comment by dbugg** [comment]
Hello Mike, I have a simple fix. I've just made `aplay /dev/zero` to start as a service, which acts as a HDMI keep alive link. Works like a charm. Anytime I change a song it starts with no handshake/delay.

Do you think it's a good idea to add HDMI link/CEC control integration README.md? I often forget that the core feature of your shairport is multiple devices but still. 

The readme will include: solving problems executing cec commands via .conf sh scripts (/dev/vchiq fixing permission), the keep alive hack and common cec instructions.

**Comment by mikebrady** [comment]
Thanks. It's a good idea, but I think it belongs in a Hints and Tips page. How about HINTSANDTIPS.md, with different sections for different topics, so a section for HDMI/CEC Topics? Whaddyathink?

**Comment by dbugg** [comment]
It's up to you. I think HDMI-CEC-SETUP.md would be better as I have to include intro to CEC protocol. I saw you have BLUETOOTH or CAR SETUP. Your call.

**Comment by mikebrady** [comment]
Okay — let’s go ahead with your idea, thanks.

**Comment by mikebrady** [comment]
Did you just make a pull request to a different (i.e. the wrong) repository?

**Comment by dbugg** [comment]
Sorry, I went to hospital right after this question. I am fine now. 

Quick update: there's built in way to keep the HDMI connection alive. You need to add the following line in `/boot/config.txt`:

`force_hdmi_open=1`

Will add it to the readme.

**Comment by mikebrady** [comment]
Yikes, glad to hear you’re okay.
