### ISSUE TITLE
Output to jack audio

### ISSUE THREAD

**Issue by corentoulf** [mikebrady/shairport-sync#74]
I wondered if it was possible to route the signal to a jack audio server, to do signal processing before it goes out of the raspberry ? I tried different thing with alsa but I can't figure out how to do...
Thanks

**Comment by mikebrady** [comment]
Haven't tried it, but there is some information about going from an alsa output "device" to a jack inputer at http://jackaudio.org/faq/routing_alsa.html.

I imagine that these techniques will introduce a layer of latency, which would affect synchronisation.

**Comment by corentoulf** [comment]
Thanks for the fast feedback. I'll try it and tell you how fine that works.

**Comment by Candid-Code** [comment]
Have you tried to force audio thru the 3.5mm jack via "sudo raspi-config" ?

**Comment by mikebrady** [comment]
Hi there. The "jack" in question is not the headphone jack – it's the sound server software called "jack".

**Comment by mikebrady** [comment]
You can get the raw PCM out of a pipe with the latest version. No synchronisation though...

**Comment by corentoulf** [comment]
Okay, thanks for the information !

**Comment by shtirlic** [comment]
Would it be nice to add jack output natively in shairport-sync, so even on mac osx we can use jack( via coreadio) without buggy libao? What you think @mikebrady?
