### ISSUE TITLE
soxr not enabled even with --with-soxr

### ISSUE THREAD

**Issue by moonwatcher** [mikebrady/shairport-sync#740]
Building the latest development branch on a raspberry pi, specifying `--with-soxr` does everything correctly and builds `shairport-sync` with soxr but the `#define` in `config.h` is not enabled correctly so the resulting binary bails if I try to enable soxr.

if I manually edit `config.h` and correct the `#define` statement after `./configure` and before`make` all is well and working. 

I assume it's a typo somewhere.

**Comment by mikebrady** [comment]
Thanks — let me check.

**Comment by mikebrady** [comment]
[Fixed](
https://github.com/mikebrady/shairport-sync/blob/development/RELEASENOTES.md#version-33d7), I believe. Thanks for your help.

**Comment by joerg-krause** [comment]
I can confirm that this issue is fixed by commit cd6a99a7cfde1c5e1c1cc74ee6a77041bb4012d9.
