### ISSUE TITLE
on start command won't run

### ISSUE THREAD

**Issue by JackDarnell** [mikebrady/shairport-sync#744]
I am trying to get a Pimoroni blinkt to run rainbow.py when a song plays but I always get this error:
"shairport-sync[545]: Execution of on-start command failed to start"
the line in the config file looks like this:
"run_this_before_play_begins = "#!/home/pi/Pimoroni/blinkt/examples/graph.py";"
I have no clue why it's failing, I tried excluding the #! at the beginning of it and I originally didn't use the full pathname but I fixed that. If anyone knows how to get the python script to run it would be super helpful.

**Comment by mikebrady** [comment]
Thanks for the post. Have a look at [this](https://stackoverflow.com/questions/304883/what-do-i-use-on-linux-to-make-a-python-program-executable), and make sure you give the full path to your python script in the Shairport Sync configuration file.

**Comment by mikebrady** [comment]
Okay to close this?

**Comment by JackDarnell** [comment]
Yup, I just put a clean install of raspian on it and it worked fine.

Thanks

**Comment by mikebrady** [comment]
Thanks, Jack.
