### ISSUE TITLE
Error when run_this_when_volume_is_set is set [Fixed in development branch]

### ISSUE THREAD

**Issue by shaven** [mikebrady/shairport-sync#749]
This app is amazing. I was able to setup an Airplay device in a matter of minutes and get it to turn on the amp and set the input with great ease. Thank you for building this. I am having one issue when I try to use the command that runs when the volume is changed.

When I set the parameter:

run_this_when_volume_is_set

To run a command, I get an error. At first I was thinking it was the shell script that was turned executable that was the issue, but then I set it to '/bin/bash' and I get the same error. I am running it command line with verbose and adding the begin command and end command to turn on and off the amp via hdmi.

**Comment by mikebrady** [comment]
Thanks for the post. Please give me a little time to check it.

**Comment by mikebrady** [comment]
Actually, I believe I found the bug and fixed it. I pushed the update to the `development` branch. Would you be kind enough to try it please, and let us know if it's working for you?

**Comment by shaven** [comment]
Wow.. that was fast. I will give it a try in the morning and report back. Thank you.

**Comment by shaven** [comment]
That fix works correctly now for running it on volume change. I even went so far as to update it in my local master branch and it worked there as well. Thank you so much for the fix.
