### ISSUE TITLE
Delay of several seconds when interacting with shairport-sync [Answered]

### ISSUE THREAD

**Issue by ByteFight** [mikebrady/shairport-sync#752]
Hey,

whenever i use the shairport-sync i have a delay of up to three seconds after interacting. Interaction means play, pause, skip, ... I have this problem with both of my devices:

MacBook Pro (Retina, 15', Mid 2014)
MacOS 10.13.6 (17G65)

iPhone 6
iOS 12.0 (16A366)

**Comment by mikebrady** [comment]
Hi there. Shairport Sync uses AirPlay. There is a delay inherent in AirPlay, and its normally around 2 or 2.25 seconds. The video part off a movie is usually delayed by the right amount to match the delay in AirPlay. Could this be what you're experiencing?

Apparently AirPlay 2 mostly eliminates the delay, but Shairport Sync uses the original AirPlay as the details of AirPlay 2 have not been published.

**Comment by leisgee** [comment]
Ok, that could be the problem, thank you! Are you going to implement AirPlay 2 when its "released"?

**Comment by mikebrady** [comment]
If it is ever "released", I'd be really interested in trying to, yeah, but Apple doesn't tend to be very forthcoming on these things...

**Comment by BrainStone** [comment]
Out of interest, is there any update on that?

**Comment by mikebrady** [comment]
Not much to report, TBH. People are working on it, but progress is slow and rather uncertain.
