### ISSUE TITLE
AirPlay Speaker Not Available Error

### ISSUE THREAD

**Issue by SalmonSurprise** [mikebrady/shairport-sync#753]
Hi Mike,

Thanks for helping me with my previous thread:
https://github.com/mikebrady/shairport-sync/issues/741#issuecomment-420038620

I am having a new issue. Everything works fine other than this error. Only solution seems to be rebooting, but it happens every 2-3 days.

![error](https://user-images.githubusercontent.com/43150879/46683597-39dbe980-cbb6-11e8-9aee-86000463170e.jpg)

Any ideas on how to stop this from happening?

**Comment by SalmonSurprise** [comment]
How do I access the logs? Here is the output of the command you g
![systemctl](https://user-images.githubusercontent.com/43150879/46700249-e67f9080-cbe1-11e8-8838-1bb0061b541e.PNG)
ave.

**Comment by mikebrady** [comment]
That look interesting -- Shairport Sync seems to have been running for over a week... Anyway, please have a look at #727 for some information about logging.

**Comment by SalmonSurprise** [comment]
There doesn't appear to be any useful info there. Below is the output. I tried to connect via AirPlay in between those timestamps. I changed the verbosity to 3. I'm not sure if I did that right. Pic of that is below as well.
![verbosity](https://user-images.githubusercontent.com/43150879/46756237-96a9d380-cc8c-11e8-8f7a-3c295720ef2d.PNG)
![journal](https://user-images.githubusercontent.com/43150879/46756239-96a9d380-cc8c-11e8-827f-b006b7a9eb88.PNG)

**Comment by mikebrady** [comment]
A verbosity of 3 is probably too high; try 2 and let’s see the log after a while.

**Comment by SalmonSurprise** [comment]
So I changed it to 2. I haven't rebooted the Pi in a week, and therefore Shairport-Sync has not worked in days. It just gives that error. Do you want me to do anything to cause activity in the log before sending back? It doesn't seem to be logging much.

**Comment by SalmonSurprise** [comment]
![restart](https://user-images.githubusercontent.com/43150879/46815628-e2b65000-cd40-11e8-9f5f-4f9c36cbda0e.PNG)
Seems to have successfully restarted. I will post back with the log when the problem recurs.

**Comment by SalmonSurprise** [comment]
Okay, it restarted successfully. Sorry for the deleted comment, I realized why I got the strange feedback, it was because I was typing a command intended for another machine in the wrong SSH window.

I will post back when the problem recurs.

**Comment by SalmonSurprise** [comment]
So this wasn't the problem I was contacting you about, but the Pi stopped showing up in the AirPlay list on the iOS devices. So I am following the same instructions to try to figure out why. See below.

![1](https://user-images.githubusercontent.com/43150879/46910283-48eccf80-cf07-11e8-9949-e98722d1d2b1.PNG)

**Comment by mikebrady** [comment]
They are interesting screenshots, thanks. They seem to indicate two things.

The first is some kind of an intermittent problem with the network -- see the `Time ping turnaround time:…` (Could there be a source of interference, e.g. a microwave?)

The second thing is shairport-sync getting confused and deliberately shutting down -- see the `fatal error: Failed to…` Of course, it's a fault in shairport-sync that it gives up at that point. I'll try to figure out what's happening and post an update. It might take a few days.

**Comment by mikebrady** [comment]
I'm still looking at this…

**Comment by mikebrady** [comment]
Hi there. I've just made a number of significant changes to Shairport Sync as a result of some of your diagnostic messages. The changes won't magically fix your problem, but I believe they will make Shairport Sync more robust in dealing with them, and I'd be really interested in your experience with the updates.

The updates have been applied to the `development` branch. If you could, at your leisure, update to it – please see [UPDATING.md](https://github.com/mikebrady/shairport-sync/blob/master/UPDATING.md) for an updating guide, and remember to `git checkout development` where indicated – that would be great.

**Comment by SalmonSurprise** [comment]
Hi Mike,

Good to hear from you again. I have updated as per your instructions. Seems to be working. I will report back with any problems in this thread. Also when following the instructions it appears I don't have "soxr" is that a problem?

**Comment by mikebrady** [comment]
Thanks for your quick response. The "soxr" thing shouldn't be a problem, at least for me (!). The purpose of soxr here is to reduce the audibility of synchronisation activity. If there is a great deal of synchronisation activity occurring, then, without soxr it can get faintly audible. The downside of soxr is that it uses lots of computer power. In these present circumstances, for testing, it's probably best to leave soxr out until we can establish what the underlying problem. Then we can reintroduce it.

**Comment by SalmonSurprise** [comment]
Ok. Sounds good.

**Comment by mikebrady** [comment]
A lot of troubleshooting and debugging has gone in to the latest release – 3.3.1 – and it would be cool to get your evaluation of it, whenever is convenient.
