### ISSUE TITLE
Do not terminate connection on idle

### ISSUE THREAD

**Issue by benjamindaines** [mikebrady/shairport-sync#754]
I cannot currently find a way to keep shairplay from automatically disconnecting after a period of inactivity.  Setting session_timeout to 0 does not have the desired results.  

If there isn't currently a way to do this, could it be added?  The only thing I use this iPad for is streaming Tidal, so it would be nice to just have it connected to shairport all the time.

**Comment by mikebrady** [comment]
Thanks for the post. Actually, it is the client (e.g. your iPad) that controls disconnection. Unfortunately, Shairport Sync (not "shairplay" BTW) has no control over it.

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
