### ISSUE TITLE
volume_range_db via command line

### ISSUE THREAD

**Issue by senthor** [mikebrady/shairport-sync#757]
Hi!
Having a bit of a weird request here. I'm using shairport-sync as part of PiCorePlayer, which mostly works fine. However, for some reason, my volume_range is wildly out of hand – range is just 36dB, and alsamixer just mutes when going under 25% volume. As a result, shairport-sync only sets volume in the alsa-range from 25 to 100%, so -36 to 0dB, which is way too loud even at the low end.

All this could probably easily be fixed with the volume_range_db setting, however, for unknown reasons, this distro decided not to use any configuration file and solely relies on command line arguments. Thus, long story short, I have more of a question than an issue: 

**Is it possible to configure _volume_range_db_ via command line arguments?**

Thanks!

**Comment by mikebrady** [comment]
Thanks for the mail. I'm afraid there isn't a command-line setting for the `volume_range_db`. What output device are you using?

**Comment by senthor** [comment]
I'm using a USB sound card, a Speedlink Vigo Supreme, SL-800100-SR (C-Media Electronics Inc. USB Audio Device) via usb-1.1.3, full speed. Thanks!

**Comment by mikebrady** [comment]
Well, one thing you could do with the command line is to specify your own settings file -- the `-c` option allows you to specify the location of your own settings file. Would that be of use?

**Comment by senthor** [comment]
Yes and no. PiCorePlayer is based on TinyCore Linux, which is a RAM-only system (perfect for volatile power deliveries, I hooked my RPi directly up to the integrated power sockets of my HiFi receiver). So no easy file editing – and especially no easy file preservation during upgrades.

I have however found a solution: PiCorePlayer allows for custom commands to be run at boot, I created one to write a simple configuration file via echo to the /tmp directory:
`echo 'general={name = "name"; interpolation = "soxr"; volume_range_db = 60.0;} alsa={output_device = "hw:0";mixer_control_name = "Speaker";}' >> /tmp/shairport-sync.conf`

Now comes the very weird part: The volume range seems to be adjusted on the top. Minimum is still -36dB, maximum is a theoretical +24dB; however, volume is cut off at +0dB, so I now have maximum loudness starting from 60% volume on the client devices. That's even worse :/

Seems to be an issue in alsa with too high lowest volume. Any ideas?

Thanks a lot!

**Comment by mikebrady** [comment]
Thanks for this. I will check the code in Shairport Sync. The Raspberry Pi's own built-in DAC has a range up to some small positive number of dBs and Shairport Sync deals with it correctly, but I'll have to check it with a higher value...

**Comment by mikebrady** [comment]
I've had a quick look at this by hacking what the Pi reports about the range of the built-in DAC, and it looks like it is working :(.

Here is a selection of volume settings to `alsa`:
```
Set alsa volume to -1678.377650
Set alsa volume to -730.872803
Set alsa volume to -105.241928
Set alsa volume to 364.263954
Set alsa volume to 959.820786
Set alsa volume to 1410.485458
Set alsa volume to 1708.448982
Set alsa volume to 1908.732891
Set alsa volume to 2167.183590
Set alsa volume to 2400.000000
Set alsa volume to -10238.000000
Set alsa volume to -3591.170443
Set alsa volume to -3550.841464
Set alsa volume to -3501.465489
Set alsa volume to -3460.154959
Set alsa volume to -3439.659471
Set alsa volume to -3421.116521
Set alsa volume to -3380.623803
```
You'll see from +24 to -36 db, down to -102.38 for mute.
A quick question -- what version of Shairport Sync are you running? Current is 3.2.1/2...

**Comment by senthor** [comment]
This should answer all questions:
`Lowest dB value is a mute -- try minimum volume +1
Hardware mixer has dB volume from -36.000000 to 0.000000.
Version: "3.1.7-OpenSSL-tinysvcmdns-ALSA-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc"`

This is with the following settings:
`general={
   name = "name"; 
   interpolation = "soxr"; 
   volume_range_db = 60.0; 
   volume_max_db = -10.0;
} 
alsa={
   output_device = "hw:0";
   mixer_control_name = "Speaker";
}`

amixer reports:
`Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 37`

**Comment by mikebrady** [comment]
Thanks. A couple of things.
1. Doesn't it looks like `amixer` is reporting a range of 0 dB to -37 dB? It seems more or less consistent with the 0 to -36 dB reported by Shairport Sync? If that is indeed the case (sorry if I'm being a bit dense here, but if this is true, then point 3 below applies).

2. Shairport Sync seems to have deduced that the lowest setting number, -37, is in fact a mute.

3. If you don't use the `volume_range_db` setting, what happens? If the built-in hardware range of your DAC is really from 0 dB down to -36 dB, then my test on the Raspberry Pi's but;t-in DAC was not quite faithful to your situation, as I was using the `volume_range_db` to restrict the range available, whereas you would have been extending it... In that case, I'll have to do a little more testing. I have used a cheap USB DAC in the recent past with a mere 30 dB range and recall having extended it with the `volume_range_db` setting, but I'd need to check again.

**Comment by mikebrady** [comment]
Just following up on this, I tried Shairport Sync with a cheap USB DAC having a hardware mixer with a 0 to -45 dB attenuation range. I set the `volume_range_db` range to 60. If you visualise the 60 dB range now, the hardware mixer's 45 dB range is at the bottom and Shairport Sync's own software attenuation (up to 15dB here) at the top.

Thus, for example, to set the output at its lowest level, Shairport Sync will set the hardware mixer to -45 dB and will additionally attenuate (in software) the output going to the DAC by 15 dB, giving 60 dB of attenuation in total. As another example, to get 15 dB of attenuation, Shairport Sync will set the hardware mixer to 0 dB and will attenuate (in software) the output going to the DAC by 15 dB.

When no attenuation is required -- i.e. the top of the volume, the hardware mixer will be set to 0 dB and no software attenuation will occur. 

This is working properly on the latest release, 3.2.2. I hope this helps.

**Comment by senthor** [comment]
Thanks for following up. This seems to fit my situation quite perfectly. Points 1 and 2 do apply, and removing `volume _range_db` does change the attentuation. I'm having difficulties explaining this, sorry. Let's try this:

```
Without volume_range_db
Shairport (Client, %):   0 …  25 …  50 …  75 … 100
alsamixer (Server, %):  25 …  46 …  66 …  83 … 100
            (db gain): -36 … -20 … -11 …  -5 …   0

With volume_range_db=60
Shairport (Client, %):   0 …  25 …  50 …  75 … 100
alsamixer (Server, %):  25 …  74 … 100 … 100 … 100
            (db gain): -36 …  -8 …   0 …   0 …   0
```

I'm pretty sure this is a driver issue of my cheap USB sound card; especially the skip from 25% to 0% in alsamixer seems very odd. I have, however, not found a solution to fix this within alsa or the driver.
What I would like Shairport Sync to do is the opposite of what it seems to be doing now: Lowering the volume in software for all volumes between 0 and 25%, i.e. subtracting another 24dB between 25% to 1% and software-muting at 0%. But this is probably a very sole issue of mine…

**Comment by mikebrady** [comment]
Let me think about this for a while...

**Comment by senthor** [comment]
Hi Mike. I'm very sorry for the long delay. I don't have the skills to build packages for TinyCore Linux myself, and thus had to rely on the developers of PiCorePlayer to update shairport-sync. Luckily, they finally did, and I'm now running 3.3.6.
I'm not very sure if I quite got your solution, this is what I tried: 
```
general =
{
   name = "name";
   interpolation = "soxr";
   volume_range_db = 60;
   volume_range_combined_hardware_priority = "yes";
}
alsa =
{
        output_device = "hw:0";
        mixer_control_name = "Speaker";
}
```
However, this does not produce the wanted result. In fact, changing the `volume_range_combined_hardware_priority` setting does not change anything for me: Volume is still abruptly muted, i.e. having the slider at the lowest non-muted position in iTunes is not quiet enough. `alsamixer` jumps from 25% (-36dB) to muted; Instead, it get's even louder than the hardware mixer allows.
Having a look at the verbose output, I noted that changing this setting seems not to have been picked up by shairport-sync:
```
0.000024479 "shairport.c:1756" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
```
Any other changes to the configuration are being picked up. I tried `yes`, `no`, `0` and `1`, all produced the same result. What am I missing here?
Here's a full startup log:
```
0.001332396 "shairport.c:1636" Started!
0.000360572 "shairport.c:1660" software version: "3.3.6-libdaemon-OpenSSL-tinysvcmdns-ALSA-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc"
0.000110782 "shairport.c:1666" log verbosity is 1.
0.000407552 "audio_alsa.c:1018" alsa: alsa_maximum_stall_time of 0.200000 sec.
0.000163489 "audio_alsa.c:1303" alsa: disable_standby_mode is "never".
0.000186146 "audio_alsa.c:1305" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
0.000167813 "audio_alsa.c:1307" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
0.000196198 "audio_alsa.c:1346" alsa: output device name is "hw:0".
0.000330156 "shairport.c:1714" disable resend requests is off.
0.000073281 "shairport.c:1717" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
0.000058073 "shairport.c:1718" statistics_requester status is 0.
0.000114479 "shairport.c:1720" daemon status is 0.
0.000057188 "shairport.c:1721" daemon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
0.000038333 "shairport.c:1723" rtsp listening port is 5000.
0.000039844 "shairport.c:1724" udp base port is 6001.
0.000047344 "shairport.c:1725" udp port range is 10.
0.000034322 "shairport.c:1726" player name is "Arbeitszimmer".
0.000035573 "shairport.c:1727" backend is "alsa".
0.000035157 "shairport.c:1728" run_this_before_play_begins action is "(null)".
0.000034583 "shairport.c:1729" run_this_after_play_ends action is "(null)".
0.000036406 "shairport.c:1730" wait-cmd status is 0.
0.000034115 "shairport.c:1731" run_this_before_play_begins may return output is 0.
0.000034583 "shairport.c:1732" run_this_if_an_unfixable_error_is_detected action is "(null)".
0.000037761 "shairport.c:1733" run_this_before_entering_active_state action is  "(null)".
0.000035104 "shairport.c:1734" run_this_after_exiting_active_state action is  "(null)".
0.000035677 "shairport.c:1735" active_state_timeout is  10.000000 seconds.
0.000040156 "shairport.c:1736" mdns backend "(null)".
0.000039375 "shairport.c:1740" interpolation setting is "soxr".
0.000034427 "shairport.c:1741" interpolation soxr_delay_threshold is 30.
0.000034583 "shairport.c:1742" resync time is 0.050000 seconds.
0.000037292 "shairport.c:1743" allow a session to be interrupted: 0.
0.000034427 "shairport.c:1744" busy timeout time is 120.
0.000035156 "shairport.c:1745" drift tolerance is 0.001995 seconds.
0.000037188 "shairport.c:1746" password is "(null)".
0.000033958 "shairport.c:1747" ignore_volume_control is 0.
0.000034532 "shairport.c:1751" volume_max_db is not set
0.000035468 "shairport.c:1753" volume range in dB (zero means use the range specified by the mixer): 59.
0.000040990 "shairport.c:1756" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
0.000035833 "shairport.c:1758" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
0.000036719 "shairport.c:1759" disable_synchronization is 0.
0.000039479 "shairport.c:1760" use_mmap_if_available is 1.
0.000035000 "shairport.c:1762" output_format automatic selection is enabled.
0.000035000 "shairport.c:1766" output_rate automatic selection is enabled.
0.000036563 "shairport.c:1770" audio backend desired buffer length is 0.200000 seconds.
0.000041302 "shairport.c:1772" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
0.000041614 "shairport.c:1773" audio backend latency offset is 0.000000 seconds.
0.000035677 "shairport.c:1775" audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
0.000036407 "shairport.c:1776" zeroconf regtype is "_raop._tcp".
0.000037187 "shairport.c:1777" decoders_supported field is 1.
0.000035261 "shairport.c:1778" use_apple_decoder is 0.
0.000033906 "shairport.c:1779" alsa_use_hardware_mute is 0.
0.000036250 "shairport.c:1783" no special mdns service interface was requested.
0.000075677 "shairport.c:1787" configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
0.000041250 "shairport.c:1793" metadata enabled is 1.
0.000036406 "shairport.c:1794" metadata pipename is "/tmp/shairport-sync-metadata".
0.000037969 "shairport.c:1796" metadata socket address is "(null)" port 0.
0.000035000 "shairport.c:1797" metadata socket packet size is "500".
0.000034375 "shairport.c:1798" get-coverart is 1.
0.000038229 "shairport.c:1816" loudness is 0.
0.000033854 "shairport.c:1817" loudness reference level is -20.000000
```
