### ISSUE TITLE
Q: Is Audio playing? [Resolved]

### ISSUE THREAD

**Issue by fundix** [mikebrady/shairport-sync#759]
Hi, it's possible find, if now some music playing? If is shairport-sync started as deamon?

**Comment by mikebrady** [comment]
Thanks for the post. Please have a look at #727 for some information about using logs. Also, enabling `statistics` may also help you to find out what’s happening.

**Comment by fundix** [comment]
Hi, I solved this problem with cat /proc/asound/ALSA/pcm0p/sub0/status -- if something plays - file contains some stats, but if nothing plays file contain 'closed'
// I was looking for automatic amplifier swithing on and off (I have openhab2 and smart power plugs)

**Comment by mikebrady** [comment]
Thanks -- now I understand :) By the way, there are two program / script hooks for this in the configuration file for attaching programs just before play starts and just after play ends -- look for `run_this_before_play_begins` and `run_this_after_play_ends` in the `sessioncontrol` section.
