### ISSUE TITLE
problem executing autoreconf -fi  libtoolize: AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AMFLAGS=-I ./m4. 

### ISSUE THREAD

**Issue by titusfx** [mikebrady/shairport-sync#763]
When I execute `autoreconf -fi` in windows with Cygwin64x I get the following error:

`libtoolize: AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4. `

**Comment by titusfx** [comment]
To fix it I did the following:

When you try for the first time execute autoreconf -fi the problem appears but some files are generated, so if you delete those new file with help of Git and you add the .gitattributes files with the content of:

*.sh -crlf
*.ac -crlf
*.am -crlf

as http://pete.akeo.ie/2010/12/that-darn-libtoolize-acconfigmacrodirm4.html explain, you will get it work

*A WAY TO AVOID THIS PROBLEM IS TO SET IN THE GUIDE TO ADD THIS .gitattributes file with this content*

**Comment by mikebrady** [comment]
Thanks. I haven't had this problem. Could you tell me more about your Linux environment please?

**Comment by titusfx** [comment]
It was on windows with Cygwin

**Comment by mikebrady** [comment]
Thanks. I'll have a play around.
