### ISSUE TITLE
crash on wrong mqtt remote comand

### ISSUE THREAD

**Issue by roblan** [mikebrady/shairport-sync#767]
Shairport Sync seems to crash when mqtt payload is empty

Logs
```
shairport-sync[8549]: Client Kuchnia received PUBLISH (d0, q0, r0, m0, 'shairport/remote', ... (0 bytes))
shairport-sync[8549]: [MQTT]: received Message on topic shairport/remote:
systemd[1]: shairport-sync.service: main process exited, code=killed, status=11/SEGV
systemd[1]: Unit shairport-sync.service entered failed state.
```

**Comment by mikebrady** [comment]
Thanks for the report. I wonder if @tillz has a view. Till?

**Comment by mikebrady** [comment]
Let us wait a little while to see if Till responds; if not, we'll have to dive in...

**Comment by tillz** [comment]
Sorry, obviously the case of an invalid command being sent to shairplay wasn't tested. The PR above fixes this.

**Comment by mikebrady** [comment]
Many thanks, @tillz. The pull request is merged.

**Comment by mikebrady** [comment]
Okay to close this?
