### ISSUE TITLE
Help with read-only Raspian Lite

### ISSUE THREAD

**Issue by giggywithit** [mikebrady/shairport-sync#769]
Hello

I am attempting to get shairport-sync up and running using the raspberry pi in read only mode.

Using the script and method on the [Adafruit](https://learn.adafruit.com/read-only-raspberry-pi/overview) website to set a working image to read only, I have successfully set up a raspian lite into read only mode. Before this conversion, shairport-sync worked as expected. After, the read only shairport-sync does connect and is shown as an output device, however there is no audio being played back.

I would really like to get this going read only, so any help is appreciated.
ps. I am using an IQaudio DAC+ type of hat, which shouldn't matter and works fine before

Here's my

```
sudo shairport-sync -vvv
Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "default".
The processor is running little-endian.
Version: "2.8.6-OpenSSL-Avahi-ALSA-pulse-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "Raspberrypi".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "0" (0-basic, 1-soxr).
resync time is 2205.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 88 frames.
password is "(null)".
ignore_volume_control is 0.
playback_mode is 0 (0-stereo, 1-mono).
disable_synchronization is 0.
use_mmap_if_available is 1.
audio backend desired buffer length is 6615.
audio backend latency offset is 0.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service 'AF31192A3A11@Raspberrypi' group is not yet committed.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'AF31192A3A11@Raspberrypi' group is registering.
avahi: service 'AF31192A3A11@Raspberrypi' successfully added.
New RTSP connection from 10.42.0.1:37884 to self at 10.42.0.45:5000.
    CSeq: 1.
    User-Agent: iTunes/11.0.4 (Windows; N).
    Client-Instance: 47cdd8c7e14da7a3.
    Apple-Challenge: PkIq4+fn+offkfnopEP2ww.
RTSP Packet received of type "OPTIONS":
  Type: "CSeq", content: "1"
  Type: "User-Agent", content: "iTunes/11.0.4 (Windows; N)"
  Type: "Client-Instance", content: "47cdd8c7e14da7a3"
  Type: "Apple-Challenge", content: "PkIq4+fn+offkfnopEP2ww"
RTSP Response:
  Type: "Apple-Response", content: "RMA8FZRM83TkrMQH12wrja3g9JPiJhBIXMafKqDv6Fls+BDVTyfyQy46p6VIMpASnADpaHOf7hVsWolLWWmpdfACxVywkcKRxecjMLV3TvYtxHF7nouqP4BZ/6uL67NcitLTqcMPJFpkngx93kbd+0CHODSRygebkeRfzRFwCmLvdMMY0cUcsGdpYUdWmeQvWjVNKghOLqxdwwV5tT1AnHFnEXSuXGcDXmPTYOJsxSZeEB5EhmA3TQiMkRrF6AzF8I8FnKb9VUi1OVyR8wumyD5SfeliOgzkwDat9jXwX44h58EpfbQzHN03rq2oPCENNdHbRfYRFKUaYW042lGKUg"
  Type: "CSeq", content: "1"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
RTSP connection closed.
Closing down RTSP conversation thread...
RTSP conversation thread terminated.
```

**Comment by mikebrady** [comment]
Thanks for the post. I have not looked at the read-only idea before, so I can't get too involved, but I notice that the version of Shairport Sync is rather old, and there have been many fixes since then. Would it be possible to update to the latest version?

I'll have a look at the problem in general in the next few days.

**Comment by mikebrady** [comment]
Another thing is that you've set the output to "default". Does that refer to the IQaudio DAC+ or to the built-in DAC?

**Comment by giggywithit** [comment]
OK

Did a full re-install of the whole system and it's working ATM
I'll keep you posted. Let me know if there is anything you'd like me to to help you in this regard.

Thanks Mike

**Comment by mikebrady** [comment]
Good work. Just FYI, I was going to write that the previous message indicated that Shairport Sync had actually launched and was already running in the background. It didn’t show up on the service list because it used the more recent `systemd` launch system. You can use the `systemctl` command to find out what `systemd` services are running. With `systemd` a background program doesn’t have to daemonise itself — that’s why the kill command didn’t find anything.

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
