### ISSUE TITLE
Wrap metadata into one XML object

### ISSUE THREAD

**Issue by geolessel** [mikebrady/shairport-sync#77]
When sending/writing the metadata, can you wrap all the associated data into one level? For example:

```xml
<metadata>
  <type>...</type>
  <code>...</code>
  <data encoding="base64">...</data>
</metadata>
```

I think it would make it a lot easier to parse if it were grouped like that. Thoughts?

**Comment by mikebrady** [comment]
Hi, and thanks for your interest. It would be really easy to do this, yeah. Please bear in mind that I'm not an XML expert, but my question is, would it make such a big difference?

**Comment by geolessel** [comment]
Thanks for the response! As it stands now, yes I believe it would make a big difference. As a specification, XML should be ["well formed"](http://en.wikipedia.org/wiki/XML#Well-formedness_and_error-handling) which means that there is a root elements. Element nesting is a big part of ensuring that pieces of data that are meant to go together with each other are kept together.

My background is web development and I don't have hardly any experience with C so I'm not sure how easy/trivial this is to implement. But I do know that XML parsers (specifically in Ruby for me) will have some issues with this without them properly grouped.

As an aside, I'm not sure `metadata` is the best name for the group. Thinking through it more, something a little less generic and top-level would make more sense. Perhaps

```xml
<metadata-group>
  <type>...</type>
  <code>...</code>
  <data encoding="base64">...</data>
</metadata-group>
<metadata-group>
  <type>....</type>
<!-- etc. -->
```

Thanks for the consideration! I'm excited to get this working.

**Comment by mikebrady** [comment]
Thanks for the reply. I'll set about doing it. Instead of `<metadata-group>` how about something like `<item>...</item>`. Would that work?

**Comment by geolessel** [comment]
Sounds good enough to me! I had forked your repo and added the code myself. So far it works fine. I unfortunately did not upload my branch and the code is on my Raspberry Pi at home (I'm out of town this week). Otherwise I'd just point you to my code which was working fine for me.

As I'm not real familiar with C, I'm sure your implementation will outdo mine! =)

**Comment by mikebrady** [comment]
I think I've just done that on the latest development release.

**Comment by mikebrady** [comment]
Your faith I'm my coding ability was misplaced – I managed to do it wrong. I hope to push a fixed version tomorrow. Apologies.

**Comment by mikebrady** [comment]
I think this is really fixed now. Feel free to reopen if necessary.
