### ISSUE TITLE
windows and ios devices see it, android devices dont?

### ISSUE THREAD

**Issue by daxtrajero** [mikebrady/shairport-sync#771]
Hi, my windows pc sees shareport-sync, my ios devices see it, but my android devices dont? ie. on android spotify, shareport-sync isn't shown in the list of available devices

Tested both wired and wireless LAN, same results

Shairport-sync is running on raspberry pi, latest model

Is this a known issue?

**Comment by gibman** [comment]
android devices do not natively support airplay devices such as shairport-sync.
spotify connects to "spotify connect" devices. eg. the windows version of spotify, or some other device running spotify (android).

if you want to run spotify on the pi, try and look into moode audio project:
http://moodeaudio.org

it has the librespot project installed, which enables this feature.

**Comment by daxtrajero** [comment]
thanks for the info

so to recap, spotify connects to "spotify connect" devices
so, does spotify iOS, see other airplay devices as "spotify connect" devices?

I only use the PI to receive spotify music and output it to my speakers, via my Hifiberry

I'll give Moode a go, thanks

PS: When installing Raspian on the PI, I chose the full install option. Can I get away with a more basic streamlined version?

**Comment by gibman** [comment]
hi..

The easiest thing you can do is to grab the moode image and write to a SD card (4-8 gb) on a windows PC using win32diskimager
https://sourceforge.net/projects/win32diskimager/

you will need a USB cardreader/writer.

once done, just insert the card into the PI and let it boot.

airplay on an IOS device acts the same way as bluetooth does. It relays all local audio on the ISO device to the airplay device.

google has the chrome audio, which is similar.

**Comment by mikebrady** [comment]
Okay to close this issue?

**Comment by daxtrajero** [comment]
Yes, took your advice tried Moode and it solved the issue for me - many thanks
