### ISSUE TITLE
MQTT control volume with absolute value

### ISSUE THREAD

**Issue by ophilips** [mikebrady/shairport-sync#773]
Is it possible to set volume to an absolute value? I only found "volumeup" and "volumedown" in the configuration file. As an enhancement there should be **"volumeset"** to control shairport-sync from other platforms like Home Assistant: 
https://www.home-assistant.io/components/media_player/#media-control-services

**Comment by mikebrady** [comment]
I might pass that over to Till Zimmerman -- @tillz?

I know that absolute volume is tricky on AirPlay because there is the issue of whether it's for the device itself or for the entire ensemble of devices that may be playing in sync.

**Comment by ophilips** [comment]
I think every device should be individually controllable. Otherwise there would be too many volume control options in your network if you had more than one instance of shairport-sync running. Grouping them should be quite easy in every home automation system.

**Comment by mikebrady** [comment]
One rather obvious thing I forgot to mention is that absolute volume is not exposed by iOS players. iTunes does give you absolute volumes, albeit in a convoluted way, but iOS devices do not provide absolute volume level nor do they allow you to set absolute values. So, there might be a solution for iTunes sources, but not for iOS sources, I'm afraid.

**Comment by ophilips** [comment]
Shouldn't it be enough to control just the local "alsa/pulse" volume of the device shairport-sync is running on? Do you know if that state is reported back when changed manually?

**Comment by ophilips** [comment]
Ok. I thought that both settings were somehow connected. If the state is not reported back you should just leave it as it is for now and close the issue.

**Comment by mikebrady** [comment]
Thanks. Yeah, the central issue is that one can't set the volume on a iOS-type player, only on an iTunes-type player. Incidentally, both (i.e. iOS and iTunes) suites of commands and statuses are exposed on the D-Bus interface.
