### ISSUE TITLE
Shairport-Sync with audio sync running as a service on macOS [Solved!]

### ISSUE THREAD

**Issue by Rastafabisch** [mikebrady/shairport-sync#774]
**I ended up installing it natively on Mac using pulseaudio. [Scroll down.](https://github.com/mikebrady/shairport-sync/issues/774#issuecomment-441401337)**

–––––––––––––––––––––––––––––––––––––––––––

As it appears the macOS (home-brew) build does not contain audio synchronisation.
However I would like to use this feature, so I got 3 (well 2 and a half) scenarios imagined to get this to work, and I would like to know, which would be the "most recommended" way of doing this, as macOS is taken for granted. 

The first would involve virtualisation using virtual box (headless, x86), with audio passthrough enabled. This would be the easiest way, as I could just drop a small debian image and install Shairport-sync using the defaults.

The second way would be running a docker container (which on Mac requires virtualisation, too, but would be far more low-level). However as there's no alsa audio (interface) on macOS the pulse audio backend would be utilised, as this one does have a macOS port, which can be set up as a client. 

The third way would be a native install on macOS (like the home-brew one), which would also be linked to pulseaudio.

I would like to refrain from using the virtualbox implementation as I've got serious doubts about the additional latency involved. So how about the pulse audio route? Would this include audio-synchronisation, and if yes, what might be the better was of installing it.

**Comment by mikebrady** [comment]
Hmm, I'm afraid I don't have much guidance. PulseAudio always seems such a huge piece of software to me, I try to avoid it. How about [sndio](http://www.sndio.org), which runs natively on FreeBSD. I wonder if there's a Mac port?

**Comment by Rastafabisch** [comment]
Although FreeBSD compatibility would not be enough to my knowledge (macOS proprietary CoreAudio audio stack - the reason DJs and audio engineers prefer macOS), sndio still compiles on my daily driver Macbook. However I do not want to install it, as I don't want to modify my main system to much, and will wait for my Mac mini server to arrive to do some further testing. 

How would I configure Shairport-sync with sndio to do my testing?

**Comment by mikebrady** [comment]
I’m not sure how to set it up for the Mac; I haven’t looked at it. The `sndio` guys will know how / whether `sndio` actually works with the Mac.

**Comment by Rastafabisch** [comment]
It appears that sndio does not really work on Mac - well, [have a year ago it didn't](http://www.sndio.org/arch/0035.html). I might experiment with pulse though I think at least for now I'll go with the headless virtualbox approach, though a headless Debian does not appear to include audio drivers and even with `apt install alsautils` I did not get it to work. I think for facilitating I'll use an Xubuntu/lubuntu "full featured" install and disable the desktop environment later to save resources. I'll report back in the coming days, though if anyone has another idea or something to say about pulseaudio+shairport-sync+mac I'd be happy to get some further input.

**Comment by Rastafabisch** [comment]
Well it was actually very easy due to the work that has already been done: 

I installed brew on my Mac mini server and than ran `brew edit shairport-sync` rather than `brew install shairport-sync` to open the brew formula (=docker like install instructions). Then I just replaced `depends_on "libao"` with `depends_on "pulseaudio"` and  `--with-ao` with  `--with-pa`. Afterwards it was as easy as `brew services start pulseaudio` and `shairport-sync -d`.

So far first test ran great with Youtube audio keeping in sync whatsoever. 

I will look into building a legit macOS launch service for Shairport, that I would share.

**Comment by mikebrady** [comment]
Very useful, thanks!

**Comment by Rastafabisch** [comment]
I've updated the home-brew formula and included code to start it as a service using brew `services start shairport-sync`. Here it is:

```
class ShairportSync < Formula
  desc "AirTunes emulator that adds multi-room capability"
  homepage "https://github.com/mikebrady/shairport-sync"
  url "https://github.com/mikebrady/shairport-sync/archive/3.2.2.tar.gz"
  sha256 "4f1ee142b887842727ae0c310e21c83ea2386518e841a25c7ddb015d08b54eba"
  head "https://github.com/mikebrady/shairport-sync.git", :branch => "development"

  bottle do
    sha256 "7dc8276b51f1ef0ef4cf38c27228d46e80678425626783efc0e71646b8a6c60f" => :mojave
    sha256 "8ed5e98d394f2dc6136abbbc15ecdc27a471244ef2c67c69558fbf9c3fae77ed" => :high_sierra
    sha256 "72a828bd11b9c6a28d0c4b3c90e92ded0c4ee4ba5aa095f06a22362e5c78212d" => :sierra
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "pkg-config" => :build
  depends_on "pulseaudio"
  depends_on "libconfig"
  depends_on "libdaemon"
  depends_on "libsoxr"
  depends_on "openssl"
  depends_on "popt"

  def install
    system "autoreconf", "-fvi"
    args = %W[
      --with-os=darwin
      --with-ssl=openssl
      --with-dns_sd
      --with-pa
      --with-stdout
      --with-pipe
      --with-soxr
      --with-metadata
      --with-piddir=#{var}/run
      --sysconfdir=#{etc}/shairport-sync
      --prefix=#{prefix}
    ]
    system "./configure", *args
    system "make", "install"
  end

  def post_install
    (var/"run").mkpath
  end

  test do
    output = shell_output("#{bin}/shairport-sync -V", 1)
    assert_match "OpenSSL-ao-stdout-pipe-soxr-metadata", output
  end

  plist_options :manual => "shairport-sync"

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>Label</key>
      <string>#{plist_name}</string>
      <key>ProgramArguments</key>
      <array>
        <string>#{opt_bin}/shairport-sync</string>
        <string>-d</string>
      </array>
      <key>RunAtLoad</key>
      <true/>
    </dict>
    </plist>
  EOS
  end

end
```

**Comment by Rastafabisch** [comment]
What's missing is the ability to skip and pause using the AppleRemote/MediaKeys (appear the same to the System) - However this is above my abilities… but if anyone is triggered by this, this would be welcome.
