### ISSUE TITLE
Audio Plays for a Few Seconds & Then Cuts Off Completely

### ISSUE THREAD

**Issue by cansurmeli** [mikebrady/shairport-sync#778]
Hello.

I've successfully installed Shairport on my rPi Zero.

Since I don't have a rPi Zero W, I had to plug some more stuff to be able to wirelessly send my audio stream. Hence, currently my rPi is connected as below:
- dedicated USB power source,
- data port of my rPi is connected to [this USB hub](https://www.amazon.de/gp/product/B075ZKJ76L/ref=oh_aui_detailpage_o06_s00?ie=UTF8&psc=1),
- and the hub connects:
    - [Wi-Fi adapter](https://www.tp-link.com/us/download/TL-WN725N_V1.html),
    - [sound adapter](https://www.sabrent.com/product/AU-MMSA/usb-external-stereo-3d-sound-adapter-black/#description).

Currently, I've a stable Wi-Fi connection. Here is the result of `speedtest`:

```
Retrieving speedtest.net configuration...
Testing from Telepark Passau GmbH (185.39.64.46)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by DegNet GmbH (Deggendorf) [41.93 km]: 35.566 ms
Testing download speed................................................................................
Download: 38.74 Mbit/s
Testing upload speed....................................................................................................
Upload: 10.37 Mbit/s
```

`ping -c 10 1.1.1.1`:

```
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=56 time=33.3 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=56 time=13.4 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=56 time=13.3 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=56 time=14.2 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=56 time=25.4 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=56 time=23.5 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=56 time=70.9 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=56 time=13.4 ms
64 bytes from 1.1.1.1: icmp_seq=9 ttl=56 time=29.9 ms
64 bytes from 1.1.1.1: icmp_seq=10 ttl=56 time=15.5 ms

--- 1.1.1.1 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9010ms
rtt min/avg/max/mdev = 13.325/25.305/70.916/16.768 ms
```

`ping -c 10 192.168.1.1`:

```
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=63 time=22.6 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=63 time=26.9 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=63 time=23.9 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=63 time=15.3 ms
64 bytes from 192.168.1.1: icmp_seq=5 ttl=63 time=15.9 ms
64 bytes from 192.168.1.1: icmp_seq=6 ttl=63 time=13.8 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=63 time=12.4 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=63 time=10.9 ms
64 bytes from 192.168.1.1: icmp_seq=9 ttl=63 time=19.9 ms
64 bytes from 192.168.1.1: icmp_seq=10 ttl=63 time=14.6 ms

--- 192.168.1.1 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9013ms
rtt min/avg/max/mdev = 10.930/17.666/26.934/5.106 ms
```

`Shairport-sync -vvv`:

```
Looking for configuration file at full path "/usr/local/etc/shairport-sync.conf"
debug_mutex_lock at "audio_alsa.c:169".
alsa output device name is "default".
debug_mutex_unlock at "audio_alsa.c:465".
The processor is running little-endian.
Version: "3.2.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/usr/local/etc"
statistics_requester status is 1.
daemon status is 0.
deamon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "CAN's Stereo".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "coleus-landing-horse".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 60.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_hardware_mute is 0.
no special mdns service interface was requested.
configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
metadata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
loudness is 0.
loudness reference level is -20.000000
disable resend requests is off.
diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
Unable to listen on IPv4 port 5000. The error is: "Address already in use".
Unable to listen on IPv6 port 5000. The error is: "Address already in use".
fatal error: Could not establish a service on port 5000 -- program terminating. Is another instance of Shairport Sync running on this device?
Request to shut down all rtsp conversation threads
asking playing threads to stop
debug_mutex_lock at "audio_alsa.c:906".
debug_mutex_unlock at "audio_alsa.c:923".
*** Error in `shairport-sync': corrupted double-linked list: 0x0176c318 ***
[1]    1704 abort      shairport-sync -vvv
```

Moreover, I've tested my audio output with `speaker-test`. Everything sounds fine. And Wi-Fi power saving is disabled.

At the moment, the situation is that my devices(iTunes on MBP(macOS 10.14.2) & iPhone SE( iOS 12.1.1)) see Shairport and can send the audio to my stereo. The audio starts playing for a few seconds(i.e. =~ 7 seconds) which the quality is good at this interval but afterwards it cuts off with a slight buzzing sound even though it keeps playing on the device. And it stays cut off with occasional slight buzzing sounds during the rest of the playback.

I've read a lot about possible issues and how to troubleshoot them. However, I don't want to make major changes since Shairport is a highly configurable system that I could end up breaking something before knowing the exact cause of the issue.

Could you please direct me in the right direction. Appreciate it.

p.s. 
- even though I've concluded in the beginning that certain settings are already in place, if you've concerns about them, I'll be happy to test them out again,
- I've another rPi(Model 3B v1.2) on my network connected via ethernet, also has Shairport installed and connected to another stereo which works flawlessly,
- **finally, Mike, thanks a lot for your hard work. It's an amazing project.**

**Comment by cansurmeli** [comment]
Even though the instructions on the page you've provided(which I've also previously followed through) does not work for me since I've a Zero but not a Zero W, that was the right way to go for me first since it turns out my Wi-Fi power management wasn't disabled after all.

The Wi-Fi adapter that I've(`TL-WN725N`) makes use of the chip `Realtek RTL8188CUS`(pretty common among many Wi-Fi adapters) which uses the kernel module `8192cu`. Therefore I'd to:
- `sudo vim /etc/modprobe.d/r8188eu.conf`,
- paste `options r8188eu rtw_power_mgnt=0 rtw_enusbss=0` into it,
- reboot,
- control the status by `cat /sys/module/r8188eu/parameters/rtw_power_mgnt`.

The last command above now returns `0` so according to the instructions on the internet, my power management for my Wi-Fi adapter seems to be disabled. However, the issue is ongoing.

It's a bit weird because I've read that the Wi-Fi power management kicks in after a minute or so whereas my music get cut off at the 7th second every time. And as a workaround on the internet, if one cannot disable his/her Wi-Fi adapter's power management, it's suggested to a run a ping command as a cron job to keep the adapter busy at all times.

BTW, I've tried to use Shairport with a ping command going on which the results were the same; no audio after the 7th second.

Anyways, now that the power management seems to be disabled, the buzzes after the 7th second output a bit of the music for a second or less. So I guess something has changed with my Wi-Fi adapter.

The thing is, for the first 7 seconds, the audio is pretty good and the fact that it goes silent after that seems more like a software issue to me. Therefore I'd like to do some more debugging on my current setup. If I'm not mistaken, I've seen some more debugging commands related to pinging and specific to Shairport on other issues. Could share or any other related commands please.

**Comment by mikebrady** [comment]
Sure. First thing, IMHO, would be to switch to the `development` branch, where changes can be made quickly, if necessary. There are details on the UPDATE.md page.

Next, set log verbosity to 1 or 2 (not 3 -- it's too noisy) and see if anything significant is logged. It's too short a time to produce statistics, so they are not much use right now.

Also, I'd suggest setting the `log_show_time_since_last_message` to `"yes"` (remember to uncomment these entries!).

To see if the Bonjour / Zeroconf stuff is working (I think it is working, BTW), you can use `avahi-utils` at the Pi end, "Bonjour Browser" at the Mac end and the "Discovery" app on iOS (made by Tilde Software, IIRC).

**Comment by cansurmeli** [comment]
Alright, good news! I've handled it and it was my mistake. Sorry for taking your time Mike.

The issue was occupying my mind from the beginning because if hardware were faulty than it shouldn't work from the start. Upon your latest comment, somehow it struck me to reinstall the dependencies to see if one of them were missing and aha, one of them was missing indeed.

After installing the missing dependency and reinstalling Shairport, everything started to work flawlessly.

Again, thanks a lot for your time and highly responsive replies!

**Comment by mikebrady** [comment]
Thanks. I'm glad it worked out for you.
