### ISSUE TITLE
audio|acacia

### ISSUE THREAD

**Issue by noelhibbard** [mikebrady/shairport-sync#782]
There is another multi room audio project that seems to be completely unknown. It's very impressive but seems to be completely dead development wise. I haven't tried it in several years so I can't remember what it was that kept me from going that route at my house. It is called [audio|acacia](http://www.plethra.com/software). It is seriously worth doing a trial and get some ideas. It handles AirPlay in a very unique way. It has a single AirPlay instance which accepts multiple streams from any number of iDevices. When you first start your stream there will be no output (basically null-out). You then go to the controller and find your device on the list (because more than one device can stream to it at the same time) and then direct your device to whatever output(s) you want.

At my house I used a 7.1 channel sound card and using ALSA I busted it up into 4 stereo outputs and then I have 4 instances of shairport-sync tied to each output. I could also bust it up into 8 mono outputs and handle 8 rooms if I wanted. I wish Windows had the same flexibility as ALSA. Anyways, what I would love to see is single instance of shairport-sync which accepts multiple streams and by default any new stream just directs to sort of a null-out. Then using some sort of API (dbus?) you could get a list of connected devices and then send a command back telling shairport-sync which output you want to tie the stream to. I know this is asking for some significant changes but if this could be done it would be the ultimate multiroom framework. I know everyone is beating you up for AirPlay 2 but this would give people a lot of what they want in AP2 but with AP1.

I know we can use forked-daapd but that adds a lot of overhead and lag. I would rather see all the streaming happen in shairport-sync and just dynamically redirect the output.

**Comment by mikebrady** [comment]
Thanks for the post. It's an intriguing idea alright, and I have thought about it. Now that Shairport Sync is a bit more stable I'll have another look.
