### ISSUE TITLE
error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by a-x-** [mikebrady/shairport-sync#786]
Shairport-sync in systemd cannot find libssl.so.1.0.0
But I have libssl1.0.2

Linux 4.14.79+ Raspbian based on Debian 9 (stretch)

**Comment by a-x-** [comment]
error: Illegal instruction

**Comment by a-x-** [comment]
of course, that libssl is for debian 8 jessie, debian 9 has no libssl1.0.0 library package...

**Comment by a-x-** [comment]
I builded those shairport on the other machine.
Problem gone after rebuild on the current rpi.
Thanks

**Comment by mikebrady** [comment]
Good to know, thanks.
