### ISSUE TITLE
Do multiple shairport-syncs play in sync?

### ISSUE THREAD

**Issue by vasilisvg** [mikebrady/shairport-sync#787]
I run a raspberry pi with a [Dion Audio Loco DAC AMP](http://dionaudio.nl/wp-content/uploads/LOCO-manual.pdf). I have two regular stereo speakers connected to it, and a rather simple, non-powered dipole sub-woofer. I can not control the volume of the sub independently, but I would like to. So I was thinking:

What if I gave the sub its own shairport sync amp? I assume I could connect to both the one for the speakers and the one for the sub simultaneously, right? And in this case I could control the volume independently, I assume. Now the thing I worry about, of course, is if the two instances will be perfectly in sync, or if there may be noticable delays?

**Comment by mikebrady** [comment]
Thanks for the post. It’s a plausible idea. I know that if you have multiple Shairport Sync outputs in the same listening area, they sound pretty tightly in sync. The audio should be presented to the amplifiers in sync within a few milliseconds. So worth trying, certainly, and you could set the Shairport Sync driving the subwoofer to mono. 
But remember, you’d have to be using a source like iTunes, TuneBlade, AirFoil etc. capable of driving multiple outputs. So, not iOS, unfortunately.

**Comment by vasilisvg** [comment]
Thank you for the answer. I'll give it a try. It even seems to be possible to work around the iOS issue with Airfoil.

**Comment by vasilisvg** [comment]
Just to let you know, it works! Now I need to listen for a while to see if I notice sync issues. And I should try and find out how _convolution filters_ work to see if I can filter out some mid tones from the sub. 
Did I ever thank you for your incredible work? If not, thank you so much!

**Comment by mikebrady** [comment]
Very good!

**Comment by giggywithit** [comment]
Hello

I am looking into trying out the same thing, using a subwoofer, and would like to know how you went about filtering.. were you able to filter in software?

Thanks for sharing your results with us
S

**Comment by vasilisvg** [comment]
I just reversed back to powering both the speakers and the sub with one amp. Mostly because I had to use Airfoil, and this turned out to be buggy.
And now to answer your question: no, I never got filtering working. I was too busy trying to get the overcomplicated setup to run smoothly (-:

**Comment by mikebrady** [comment]
Thanks, duly noted 😕.

**Comment by mikebrady** [comment]
Closing this interesting issue as resolved. Please feel free to open another one if necessary.
