### ISSUE TITLE
Support for libressl

### ISSUE THREAD

**Issue by Necktwi** [mikebrady/shairport-sync#788]
Request to support libressl. I believe no major changes are required.

**Comment by mikebrady** [comment]
Thanks for the suggestion. Is it a drop-in replacement for OpenSSL?

**Comment by necktwi** [comment]
LibreSSL dev has not put any note on API differences though I've come across few with very old OpenSSL API. I use LibreSSL in place of OpenSSL on RPi1B(arm, Gentoo). However in past, on RPi3B(arm64), Gentoo didn't allow `curl` to be built with `libressl`, instead, I used `gnutls` for `curl` there.

**Comment by nettings** [comment]
I just built it with libreSSL on openSUSE tumbleweed without any issues. That was on the road though, and only for trying a totally unrelated thing, so I didn't really test whether it works. Looked good, though.
