### ISSUE TITLE
Metadata is written to pipe before cmd_start_returns_output

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [mikebrady/shairport-sync#791]
I want shairport-sync to launch a metadata reader when it starts playing.
My metadata reader is working fine, but it needs a second to launch and read from the pipe.

The metadata is written to the pipe as soon as I click play on my device and not until my reader returns any output, so it cannot read the very first metadata.

**Comment by mikebrady** [comment]
Thanks for the post. 

The command that is launched just before play begins can be set to wait for completion, but that probably still would not be enough to ensure that the metadata reader was ready to accept metadata by the time the first item is sent?

Is there a reason why the metadata reader can not be launched long before Shairport Sync?

**Comment by Unkn0wn-MDCLXIV** [comment]
Well, nvm.

It was actually a full featured metadata reader which publishes the metadata via mqtt.
But I just noticed that this feature is included in your development version :disappointed:

**Comment by mikebrady** [comment]
Ouch! My commiserations. 😟

**Comment by mikebrady** [comment]
Would it be okay to close this please?
