### ISSUE TITLE
MQTT Remote control fails

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [mikebrady/shairport-sync#795]
I get the following debug output when I try to control my shairport-sync instance via mqtt:

```
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: Client <shairport> received PUBLISH (d0, q1, r0, m3, '<topic>', ... (8 bytes))
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: Client <shairport> sending PUBACK (Mid: 3)
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: [MQTT]: received Message on topic <topic>: nextitem
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: [MQTT]: DACP Command: nextitem
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: Sending command "nextitem".
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: dacp_send_command: connect failed with errno 115.
Jan 24 20:27:34 raspberrypi shairport-sync[10737]: dacp_send_command: 0.086179 seconds, response code 496, command "nextitem".
```

**Comment by mikebrady** [comment]
Also, what version of Shairport Sync is this happening with please? You can use:
```
$ shairport-sync -V
```
to find out...

**Comment by Unkn0wn-MDCLXIV** [comment]
`~# shairport-sync -V`
`3.3d48-OpenSSL-tinysvcmdns-ALSA-soxr-metadata-mqtt-sysconfdir:/etc`

I tried it with iTunes on windows and with the native music app on my iPhone.

**Comment by mikebrady** [comment]
Great, thanks. I have been experimenting with that `dacp_send_command` stuff recently -- maybe I broke it.

**Comment by mikebrady** [comment]
Aha, I see something. The remote control depends on using `Avahi`, and not `tinysvcmdns`. The reason is, Avahi allows one to search for Zeroconf packets, but unfortunately, `tinysvcmdns` does not. So, that's at least part of the issue.

**Comment by mikebrady** [comment]
(Hmm, I really must document this stuff.)

**Comment by Unkn0wn-MDCLXIV** [comment]
So do I have to switch to avahi in order to make it work?

**Comment by mikebrady** [comment]
Yes indeed, you do have to switch over to Avahi.

**Comment by Unkn0wn-MDCLXIV** [comment]
Using avahi it's working flawless.
