### ISSUE TITLE
Orange pi GPIO

### ISSUE THREAD

**Issue by lisergio** [mikebrady/shairport-sync#796]
Hi!
I'm trying to control the GPIO of an orange PI ZERO, but it does not work.
I have created two python scripts to activate and deactivate the GPIO making them executable.
if I write in the console the path of the file and the name of the file works ( /python/on.py or /python/off.py ), the GPIO is activated or deactivated correctly.

but if I edit the file "shairport-sync.conf" it does not work ... :-(

         run_this_before_play_begins = "/python/on.py";
         run_this_after_play_ends = "/python/off.py";

I've read all the issues, and I've tried the options but none of them work

> sudo usermod -aG gpio shairport-sync

not work for me, 

> usermod: group 'gpio' does not exist

Is it possible to see a log to find the problem?

thanks for help...

**Comment by mikebrady** [comment]
Thanks for the post. You can view the logs in the normal way. For example, on Raspbian:
```
sudo journalctl -n 100
```
To see the last 100 lines.

**Comment by lisergio** [comment]
I have tried to install everything in a raspberry pi 3 model b, and it works correctly, the gpio is activated when starting the playback and it turns off when disconnecting, so the failure of the operations in the orange pi zero, is by the permissions, but I can not get it to work.
I have created the group "gpio" and I have given execution permissions to shairport-sync, but it does not work ...
I created the user "pi" to do the installation from that user but it does not work either.
Any idea to try?
Thanks

the log works ok...

**Comment by nettings** [comment]
@lisergio, the OS running on the Orange might not have that group. On Raspbian, it works because /dev/gpiomem is readable and writable by group "gpio". which allows you access without root privileges.
First of all, check if you have that device, and what group it is owned by, and what rights that group has. Then, join that group. Note that you have to log out and back in for group membership changes to take effect.

**Comment by lisergio** [comment]
Thanks! I try it and comment...
