### ISSUE TITLE
Playing multiroom from iTunes broken recently

### ISSUE THREAD

**Issue by a-x-** [mikebrady/shairport-sync#798]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/6201068/51971703-da6a5800-248a-11e9-8c95-8d0bb9e9d3b1.png">

Playing single room from iPhone or via macOS audio redirect works
<img width="340" alt="image" src="https://user-images.githubusercontent.com/6201068/51971748-f2da7280-248a-11e9-8b4c-36561e652d58.png">

iTunes: Version 12.9.2.5
macOS:  10.14.3
shairport-sync: 3.2.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc

related to https://github.com/mikebrady/shairport-sync/issues/656, but I don't  have an error. Just nothing happens when I select multiple devices.

I writed to Apple too

**Comment by a-x-** [comment]
### Logs
<summary><details>when I add second device, sound comes back to mac only and:</details>

```
Jan 30 12:38:35 rpi2main shairport-sync[23370]: New RTSP connection from 192.168.0.136:54069 to self at 192.168.0.133:5000 on conversation thread 25.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Connection 25: RTSP thread terminated.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: RTSP thread 24 received an RTSP Packet of type "TEARDOWN":
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "CSeq", content: "277"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "DACP-ID", content: "F63305EBCCC54BDC"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "Active-Remote", content: "1294268056"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "User-Agent", content: "AirPlay/373.8"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Connection 24: TEARDOWN
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Cancelling timing, control and audio threads...
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Cancel timing thread.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Join timing thread.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: shutdown timing socket.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: close timing socket.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Timing thread terminated.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Cancel control thread.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Join control thread.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: shutdown control socket.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: close control socket.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Control thread terminated.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Cancel audio thread.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Join audio thread.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: shutdown audio socket.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: close audio socket.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Audio thread terminated.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Freeing audio buffers and decoders.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Connection 24: player thread terminated.
Jan 30 12:38:35 rpi2main shairport-sync[23370]: pend
Jan 30 12:38:35 rpi2main shairport-sync[23370]: RTSP thread 24: RTSP Response:
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "CSeq", content: "277"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "Server", content: "AirTunes/105.1"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Type: "Connection", content: "close"
Jan 30 12:38:35 rpi2main shairport-sync[23370]: Connection 24: RTSP thread terminated.
Jan 30 12:38:48 rpi2main shairport-sync[23370]: New RTSP connection from 192.168.0.136:54123 to self at 192.168.0.133:5000 on conversation thread 26.
Jan 30 12:38:48 rpi2main shairport-sync[23370]: Connection 26: RTSP thread terminated.
```

</summary>

**Comment by a-x-** [comment]
Seems like Apple getting started break api... :-(

**Comment by mikebrady** [comment]
Multi room is still working fine for me with iTunes. The user interface has changed a little though. To add a speaker, click inside the checkbox. If you click anywhere else, any previous choice is removed.

**Comment by a-x-** [comment]
I understand how to use iTunes airplay selector. I used it for a 2+ years.
It has broken for me this month suddenly... :(

**Comment by a-x-** [comment]
I use beta vesrion of macOS

can you say your macOS and iTunes versions?

**Comment by a-x-** [comment]
You can look at logs for 1-room and trying to add second room cases above👆

**Comment by mikebrady** [comment]
So, I've has another look at this.

I'm running the most up-to-date Mac Software
```
macOS 10.4.3
iTunes 12.9.2.5
```
On the Shairport Sync side, I'm running an unstable recent version:
```
3.3d49-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc
```
Everything is fine. Multiroom is available.

![image](https://user-images.githubusercontent.com/4265913/52137119-bef57d80-2641-11e9-9bcc-6dfd1342841a.png)

**Comment by mikebrady** [comment]
Is is possible you are playing protected music or media? IIRC Apple Music restricts you to one set of AirPLay speakers. Can't remember -- I don't use it.

**Comment by a-x-** [comment]
unlikely, I listened the same music.

BUT

Something interesting happened today.
My display has broken suddenly just after back up had completed. 
Next, I changed laptop to the equivalent one and restored with back up.

a-a-a-and.
All is working now...
I don't know what it was.

**Comment by a-x-** [comment]
Thank you and sorry for strange things here

**Comment by mikebrady** [comment]
Glad it worked out, and commiserations on the laptop...
