### ISSUE TITLE
build without libdaemon

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#799]
It would be great to have ability to build shairport-sync without libdaemon. Eg. in buildroot shairport-sync is started via start-stop-daemon thus option "-d" is not used, but libdaemon have to be build because shairport-sync depends upon libdaemon.

**Comment by mikebrady** [comment]
I'll put it on the list. It was quite an advance to use it in place of the code that was there, but I see your point. It'll take quite a bit of care to remove it.

**Comment by mistepien** [comment]
I didn't mean "removing" but rather adding a switch to build with or without libdaemon.

**Comment by mikebrady** [comment]
Of course.

**Comment by mikebrady** [comment]
This has been attempted in the latest `development` version. Would you be kind enough to try it out please?

**Comment by nettings** [comment]
I've been building it without libdaemon installed and using the explicit ./configure --with-libdaemon=no option on five or six machines now, without ill effects. Only thing I think I'm seeing is that now less messages make it to stdout when I start it from the command line with ./shairport-sync -vvv - or am I getting confused with my debug options?

**Comment by mikebrady** [comment]
Thanks for the comment. You are completely correct about the disappearing log messages from the command line. To get around it, there is a new menu entry `-u` to direct the messages to STDERR, i.e. the command line.

**Comment by nettings** [comment]
Yeah thanks, just found it an hour ago. The quiet came as a bit of a surprise given the amount of debug statements I sprinkled all over the JACK backend. But this is a very nice solution for testing from the command line, without the full systemd scaffold.

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
