### ISSUE TITLE
build only with mdns_backend=external-avahi 

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#800]
It would be great possibility to have only externa-avahi support what is very unix-way and may be usefull in case of embedded systems.

**Comment by mikebrady** [comment]
Sure thing. It's actually already there but is [incorrectly] only available if you include direct Avahi support. I'll fix it.

One thing to note, though, is that the D-Bus and MQTT remote control facilities rely on direct Avahi support, as some extra Avahi features are used to get some of the remote control parameters.

**Comment by mikebrady** [comment]
This has been attempted in the latest `development` version. Would you be kind enough to try it out please?

**Comment by mistepien** [comment]
It works fine. BUT
This avahi discovery view from outside on shairport-sync:

> Service Type: _raop._tcp
Service Name: DDEA4BFA8365@shadow:V102,0
Domain Name: local
Interface: enp8s0 IPv4
Address: shadow.local/192.168.1.5:5000
TXT md = 0,2
TXT ch = 2
TXT pw = false
TXT ek = 1
TXT ss = 16
TXT sr = 44100
TXT fv = 76400.10
TXT am = ShairportSync
TXT sv = false
TXT vn = 65537
TXT da = true
TXT vs = 105.1
TXT tp = TCP,UDP
TXT txtvers = 1
TXT et = 0,1
TXT sf = 0x4
TXT cn = 0,1

As you see there is "TXT tp = TCP,UDP", but shairport-sync does not listen on any udp socket.

**Comment by griff** [comment]
@mikebrady it breaks the build on macOS

**Comment by mikebrady** [comment]
Thanks for the post. Can you say what sequence of instructions you're following to build it on the Mac please?

**Comment by mikebrady** [comment]
Okay — I see the pull request now.

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
