### ISSUE TITLE
Name of devices in Windows

### ISSUE THREAD

**Issue by OneBobone** [mikebrady/shairport-sync#801]
Hello,

Just started using Shairport-Sync on Win7 with Cygwin. Works fine!
Have a 7.1 configuration with Attero Tech MatchBox USB that I must stick to.
Can only get sound out of the default pair, but need to address the others.

How can I find this out? 
Can’t seem to fin anything in the log file either that could give me a hint.

"alsamixer" or "aplay" are not windows alternatives afaik. (From the config file: "output_device = "default"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.")

Many thanks for a very promissing solution!

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, `alsa` is not supported on Cygwin. If you followed the [CYGWIN Guide](https://github.com/mikebrady/shairport-sync/blob/master/CYGWIN.md), then Shairport Sync is installed with a backend for the [`libao`](https://www.xiph.org/ao/) audio library. On my installation of Cygwin, `libao` in turn hands off to [OSS](https://en.wikipedia.org/wiki/Open_Sound_System). 

OSS does not appear to be widely used any more, and does not permit synchronisation, so interest is limited. You might find information about settings on the [OSS support pages](http://www.opensound.com).

**Comment by OneBobone** [comment]
Thx. I'll have a look and report back.

**Comment by mikebrady** [comment]
Oops. Finger trouble, sorry!

**Comment by OneBobone** [comment]
Did you actually solve this with the new install?
I will give it a try and report back.

**Comment by mikebrady** [comment]
Haven't looked at the speaker selection issue, no.

**Comment by OneBobone** [comment]
Oh, I got the impression when I read you write-up. 
Sorry for the confusion.

**Comment by OneBobone** [comment]
I am way out of my league, but do you think that this would be the right path to follow:
http://ossnext.trueinstruments.com/wiki/index.php/Tips_And_Tricks#Changing_the_default_sound_output

**Comment by mikebrady** [comment]
On my installation of Cygwin, `libao` hands off to OSS. Beyond that, I’m afraid I have no knowledge of the situation.

**Comment by OneBobone** [comment]
How could I tell if it hands off to OSS on my installation?

**Comment by mikebrady** [comment]
Add `debug` to the configuration file as detailed [here](https://www.xiph.org/ao/doc/drivers.html) and then run Shairport Sync from the command line with verbosity of 1 (this is an older Shairport Sync, BTW):
```
$ ./shairport-sync.exe -v
debug: Loaded driver null (built-in)
debug: Loaded driver wav (built-in)
debug: Loaded driver raw (built-in)
debug: Loaded driver au (built-in)
debug: Loaded driver wmm (built-in)
debug: Loading driver plugins from /usr/lib/ao/plugins-4...
debug: Loaded driver esd
debug: Loaded driver nas
debug: Loaded driver oss
debug: Testing drivers to find playback default...
debug: ...testing esd
debug: ...testing oss
debug: OK, using driver oss
Version: "3.2RC10-OpenSSL-tinysvcmdns-ao-sysconfdir:/usr/local/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "DESKTOP-NIKAKL3".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 1.000000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_hardware_mute is 0.
no special mdns service interface was requested.
configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
loudness is 0.
loudness reference level is -20.000000
disable resend requests is off.
diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
```

**Comment by OneBobone** [comment]
OK. So since I don't have a "/etc/libao.conf" (can't find it), I need to create one and then insert the debug option?

**Comment by OneBobone** [comment]
Unfortunate answer from the guys at Cygwin:

> Cygwin only has one audio device, namely /dev/dsp -- and that device is 
> the current default device in Windows.  So no, it doesn#t matter which 
> library you are using, they will all have to use the same single device. 
> Corinna was asking for someone to provide code so that any other sound 
> devices Windows knows about show up under /dev as well.  Only then would 
> it become possible for libraries to address "other devices".

**Comment by mikebrady** [comment]
Fair enough -- that's interesting.

**Comment by mikebrady** [comment]
Closing this issue – the problem lies elsewhere, it seems.
