### ISSUE TITLE
Metadata encoding -- Cover art

### ISSUE THREAD

**Issue by OneBobone** [mikebrady/shairport-sync#806]
Fantastic SW, thank you so much!
Am having some issues encoding the data sent over UDP.
Metadata text works fine when I encode using UTF8 (ASCII is not international enough), but I am having some problems with the cover art. It "looks" similar to other cover art jpegs that I have, but there are some slight differences. 
UTF7 looks slightly better for a jpeg but destroys int'l letters.
What is the right way to encode/decode the UDP stream?
Also, I get some short data in coreastm ("song time" = duration?), but cannot decipher it.

**Comment by mikebrady** [comment]
Yep, it's probably UTF-8. It comes from the audio source directly, as does the "astm" data. I don't know what it means -- song time in milliseconds?

Cover art can be any picture format; again it comes straight from the audio source and is encoded in BASE64 form. I have observed JPEGs and PNGs.

**Comment by OneBobone** [comment]
Sorry for being dense:
- Shareport-sync creates metadata starting with “ssnd” that is originally in UTF8? 
- Then encodes it to base64.
- What format is the incoming data in? Is everything in base64?
- do you concatenate the Base64 bytes (after the encoding) for each metadata? E.g. “~ssndpict” + ~image? How do you identify the right source metadata? As base64 strings or bytes?
- then everything is shipped out over udp in base64?
-  picture can be both png and jpg... so there is some metadata in the source data for that? I have just been saving all data after sssndpict as *.jpg...

Hmm, I maybe don’t need to know all the background, but my problem remains.  
The data encoded in utf-8 from the udp stream minus the header “ssndpict” looks very similar, but still different than other jpgs. The characters/bytes have the same position but are sometimes slightly different. The file will not be accepted as pictures in viewers (chunked or not) or online picture repair sites. It makes me think that the utf8 bytes are encoded correctly,  but the more advanced bytes are not.

**Comment by mikebrady** [comment]
The metadata was originally intended for output over a unix pipe. Later work by another contributor put it out on UDP. Have a look in the sample metadata reader for hints, and also have a look in RTSP.c for some information.

There doesn't seem to be any metadata indicating the format of the picture -- you have to look at the raw data.

I imagine the artwork is copyright, BTW, so sharing it with other sites is really a questionable practice.

**Comment by OneBobone** [comment]
Thx for the tip. WIll have a look.
To other public sites, definitely questionable, for private use between devices, I think less.
:-)

**Comment by OneBobone** [comment]
UTF7 gives the closest results, but not good enough.
Think I have to give up for now... I am puzzled.

**Comment by OneBobone** [comment]
I finally solved this mor more less well.
There where two problems:
- coding/decoding
- chunking

Best is to try to save the UDP stream directly to a file. 
I searched for "PICT" in a UTF8 encoded string that I need anyway, and then used that position directly to cut out the right array from the UDP stream.

Chunking does not seem to work perfectly and caused some headache.
The final "ssncpcen" after the last chunk is not present (maybe it is in the last chunk...)

`    hs.Writelog(LogLabel, "Opened Shairport UDP Server")
    Try
        While hs.GetVar("ApReceive") = True
            Dim bitarna As Byte() = listener.Receive(groupEP)
            Metadata = Encoding.UTF8.GetString(bitarna, 0, bitarna.Length)
            Hs.RunScriptFunc("Airplay.vb", "Main", Metadata, True, False)

            PICTpos = instr(1, Metadata, "PICT")
            If PICTpos > 0 Then
                'hs.Writelog("PICTpos", PICTpos & " " & bitarna.Length & " " & left(Metadata, 25))
                If bitarna.Length > 10000 Then
                    Dim filePath As String = "C:\Program Files\HomeSeer HS3\html\images\Shairport\Thumbnails\"
                    PICTpos = PICTpos + 3
                    Dim mySubArray(Ubound(bitarna) - PICTpos) As Byte
                    System.Array.Copy(bitarna, PICTpos, mySubArray, 0, mySubArray.Length - 1)
                    My.Computer.FileSystem.WriteAllBytes(filePath & hs.GetVar("ApArtist") & ".jpg", mySubArray, True)
                    File.Copy(filePath & hs.GetVar("ApArtist") & ".jpg", filePath & "CurrentThumbnail.jpg", True)
                    Hs.waitsecs(0.2)
                End If
            End If
        End While
    Catch e As SocketException
        hs.Writelog(LogLabel, e)
    Finally
        listener.Close()
        hs.Writelog(LogLabel, "Closed Shairport UDP Server")
    End Try`
