### ISSUE TITLE
JACK backend discussion

### ISSUE THREAD

**Issue by nettings** [mikebrady/shairport-sync#808]
Hi @mikebrady,

just started using shairpoint-sync a day ago. Worked out-of-the-box with ALSA backend, my Macbook running Mojave could stream its output with one click, wonderful! Thanks for your amazing work!
Now my next step was to try and add jack support, but after checking out the dev branch, I see you're already working on one. Would you like to pool resources?

After a quick first read, I see a few issues with the current code:

1. it still kinda pretends it's a blocking output device, which it isn't
1. it uses a mutex in the process callback, which is a no-no
1. it seems to try to connect to the jack server only if there is audio to be played.
1. it seems to assume jack is running at 44k1

Problems 1 and 2 might be easily fixable with a lock-free ringbuffer, which, if full, simulates a block for the writer, so that the push model of shairport-sync can continue to be used. The jack API provides a nice implementation of one.
Problem 3 is just a misunderstanding of how JACK works, I guess. When shairport-sync is started, it should create its jack ports and maintain them until the process ends. Anything else is just broken, because it effectively prevents you from doing anything intelligent with the audio down the line. Mplayer has the same misfeature, as have many others (portaudio pretty much forces you to get it wrong)...
Problem 4 is best solved by forcing the user to run jackd at 44k1 for now. But since the standard clock for the larger project I'm working on is 48k, I will want to look at your libsoxr code eventually - the same resampling that fixes minute timing deviations could probably also provide the upsampling at no extra cost, if done in the same step.

All in all, my gut feeling is that audio_jack.c should ultimately be the shortest of all audio backends in terms of lines of code, if the jack API is used in a more idiomatic way. (Famous last words :)

I'm by no means an expert C programmer, just an audio engineer scratching an itch. But I'm looking forward to hearing from you, and to trying to contribute code to the best of my abilties.

Best, Jörn

**Comment by nettings** [comment]
Just discovered -vvv, and I see that my assumption no. 3 is wrong. The port is there as soon as shairport-sync starts, good. So I guess the reconnection behaviour is for the case where no JACK server can be found initially. 
Now for some digging around, all while listening to an Airplay stream going through my JACK signal graph. A great motivator :-D

**Comment by mikebrady** [comment]
Thanks for you interest, and it’s great that you’re enjoying it. Let me take a little time to respond fully.

**Comment by nettings** [comment]
No rush. I'm reading through the code, and as a first exercise on the shallow end, I'm trying to replace your mutexed buffer with the lock-free ringbuffer from the jack library. That won't require me to understand all the strange timing tricks just yet :-D

**Comment by mikebrady** [comment]
That sounds cool!

**Comment by nettings** [comment]
I'm getting the hang of it. As in, it compiles, it connects, but then massive underruns and I completely broke everything :-D Guess I'm taking  a little food break now. If you want to know what I've been up to: https://github.com/nettings/shairport-sync/commits/development

**Comment by nettings** [comment]
Yay! Found a couple of stupid bugs and omissions in my code, and now it works. I have another couple clean-ups pending where I think the JACK API is not used to best effect. Should I keep adding those and send one big pull request for you to review, or would you rather I whip it into shape as it is now and send it over, before I tackle the next item?

**Comment by mikebrady** [comment]
Many thanks for this. TBH, I'm a bit stretched at the present, with a few separate work projects, so perhaps best for you to plough on. Would that be okay?

**Comment by nettings** [comment]
Sure! Will send you a pull request by Sunday, I hope. After that, no hurry - I found a treasure trove for free, I'm not going to stress its main developer :-D
BTW, while we're talking: is all of shairport-sync BSD-licensed, or are there some parts with more restrictive licences that I have overlooked?

**Comment by nettings** [comment]
Progress. audio_jack.c lost 150 lines, should be realtime-safe now, and got a lot more efficient in the bottlenecks. I'm no expert on the JACK API, but I'd say it's going well. Been listening to the code at work for hours, and I believe I fixed all regressions I introduced on the way.
Ruthlessly removed all jack options that didn't make sense to me. Tomorrow I'll add one, though: a set of ports to optionally auto-connect to, so you don't need an external script to make connections when shairport-sync starts up. Then help and command line parsing.
Also considering to add an option to use the ALSA mixer handler for volume changes and mutes. That might mean some refactoring of audio_alsa.c to avoid code duplication, though. Don't know how intrusive it's going to be, wouldn't try it if it was...

**Comment by nettings** [comment]
Still playing in the morning. Not that that's the most dangerous corner case to test, but it's a good sign.

**Comment by mikebrady** [comment]
It sounds like you've made impressive progress. BTW, much of the time since the last master release has been spent improving Shairport Sync's reliability. Many bugs have been fixed and it seems considerable progress has been made, so it's good to see that it's bearing up in your experiments. It'll soon be time for a new master release!

**Comment by mikebrady** [comment]
To answer some of your questions:
1. Worth checking the individual components for licenses. I looks a few years ago and was not particularly disturbed.
2. If you're refactoring, consider putting stuff that would be common to all the backends into `audio.c`. The mixer handler / volume control and mute stuff in `audio_alsa.c` is really new, so may not be fully baked.
3. Command line arguments are deprecated, so it's not actually necessary to add them for `jack`, unless you want to, of course.

**Comment by nettings** [comment]
Re master release: that would be awesome!
Re licenses: good to hear... with this kind of semi-proprietary tech, I'm always a bit nervous about booby traps...
Re refactoring: ok, thanks, will do that if I get to it.
Re cmdline, that's good, I was dreading this. Just wrote a getopt parser for another, much simpler project of mine (https://github.com/nettings/gpioctl), and I'm not keen to repeat the experience :) The config file is so much cleaner. Does that mean that &help is also on the way out? Or will it be re-used to document the config structure, so that eventually script/shairplay-sync.conf can be auto-generated from code so it's always up to date?

**Comment by nettings** [comment]
#809
