### ISSUE TITLE
Metadata: What is "corecaps" ? How to identify playing application?

### ISSUE THREAD

**Issue by OneBobone** [mikebrady/shairport-sync#810]
What is "corecaps"? It is not documented afaik.

Is there some way to figure out the playing application? 
The metadata pattern changes depending on application and it is quite difficult to establish a robust scheme to model the status for all apps...

**Comment by mikebrady** [comment]
'caps' seems to be the sender's play status. "2" means stopped; "3" means paused; "3" means playing.
There is quite a bit of information out there, e.g. [here](https://github.com/mattstevens/dmap-parser/blob/master/dmap_parser.c).

**Comment by mikebrady** [comment]
Regarding identification of the type of audio source -- 'snam' and 'snua' give you Device Name and User Agent information, if available.

**Comment by OneBobone** [comment]
Great! I was googling for "corecaps". Silly of me....

Well, 'snam' and 'snua' give you Device Name and User Agent information woul dbe nice, but I mostly get the same e.g. "AirPlay/375.3" independently of app.
