### ISSUE TITLE
Shairport always tries to get PulseAudio and DBus before ALSA

### ISSUE THREAD

**Issue by kbumsik** [mikebrady/shairport-sync#812]
Hi,
thanks for this amazing project.
I'm using [Nvidia Tegra Jetson TX2 board](https://elinux.org/Jetson_TX2) with a USB DAC (Sound Blaster E3) connected. I'm reporting a problem while using Shairport-sync.

My current problem is that it seems to grab PulseAudio/DBus interface first at the beginning but it works fine after it fails, then shairport-sync stops working after an hour (but still running). I wonder this is expected behavior. The environment is a fresh ARM64 Ubuntu 16.04 LTS with GUI (Jetpack 3.3).

My installation is the following:
> ./configure --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-metadata

My configuration is the following, I think this should be correct:
```
general = {
    interface = "eth1";  // My ethernet connection
};
alsa = {
    output_device = "hw:2,0";    // My USB DAC. I checked it using aplay -l
};
sndio = {};
pa = {};
pipe = {};
dsp = {};
metadata = {};
diagnostics = {};
```

The very error I got is it complains there is no home directory for `shairport-sync` user: `/home/shairport-sync`. (btw, the `shairport-sync` user's home directory is set as `/usr/bin/nologin` in `/etc/passwd`):
```
Feb 19 15:27:21 tegra-ubuntu systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Feb 19 15:28:29 tegra-ubuntu shairport-sync[6488]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
Feb 19 15:28:29 tegra-ubuntu pulseaudio[6528]: [autospawn] core-util.c: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
```
I resolved this problem by creating directories for the user:
```
sudo mkdir -p /home/shairport-sync/.config/pulse
sudo chown -R shairport-sync:shairport-sync /home/shairport-sync
```

After restarting the systemd service, I got the following error:
```
Feb 19 15:41:02 tegra-ubuntu systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Feb 19 15:41:27 tegra-ubuntu pulseaudio[6723]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Feb 19 15:41:27 tegra-ubuntu pulseaudio[6723]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```
Though shairport-sync works fine for like an hour, the problems are it has a long delay of 7 seconds at the first music play (I suspect it is because of the error above), and it stops serving AirPlay correctly.

**Comment by mikebrady** [comment]
Thanks for the post. The PulseAudio and D-Bus messages seem to happen if PulseAudio is active, but AFAIK they don't seem to represent any particular problem. However, it would be important to ensure that (a) `hw:2.0` is not being used by PulseAudio and (b) that `hw:2.0` is not, in fact, a fake hardware device to allow ALSA outputs to be routed into PulseAudio.

Regarding the drop-off after an hour, or so, there could be many reasons. The upcoming version of Shairport Sync, available now in the `development` branch, is a good deal more reliable in the face of network problems, so perhaps you'd like to try it and let us know how it works out.

**Comment by nettings** [comment]
Just a shot in the dark, but since you're using a distribution that mikebrady likely hasn't had the chance to test, you may be having systemd-related issues. First of all, the right to open a sound device is often tied to the user's login session. If you want to run a permanent service, you may have to create some policies and also set a DBUS environment variable. I guess this is covered by shairport-sync, but it might fail in subtle ways. If stuff stops working after a while, could it be that you logged into the machine as the shairport-sync user, maybe for debugging reasons? Because systemd has a routine to clean up a user's temporary files after they close the last login session, unfortunately any that may have been created by a system service that was never tied to a login session in the first place.

**Comment by mikebrady** [comment]
Hmm. Not sure that works. This line:
```
Feb 19 15:28:29 tegra-ubuntu shairport-sync[6488]: Failed to create secure directory (/home/shairport-sync/.config/pulse): No such file or directory
```
looks like a message from Shairport Sync, but it's not -- Shairport Sync doesn't have anything to do with PulseAudio when using the ALSA back end. Therefore, this message must indicate that PulseAudio has some kind on connection into the ALSA system. Maybe it's simply monitoring ALSA devices, or maybe it has some kind of hooks ("tentacles?") in the ALSA system itself.

**Comment by mikebrady** [comment]
Hi there. Did you ever get any further with this issue?

**Comment by Neustradamus** [comment]
@nettings: Any news?
