### ISSUE TITLE
Potential segfault with JACK backend when using incorrect regex

### ISSUE THREAD

**Issue by nettings** [mikebrady/shairport-sync#813]
The rewritten JACK backend (currently in the development branch) allows the user to specify a pattern of JACK ports that shairport-sync should try to autoconnect to when it starts, via the option jack.autoconnect_pattern. This can be set to a POSIX extended regular expression, for example, "system:playback_[78]", which will cause shairport-sync to look for matching ports (in this case, those would be "system:playback_7" and "system:playback_8".
These regular expressions are handled in libjack. Since it hasn't included proper error checking until yesterday, the user can crash libjack (and with it shairport-sync) by providing a syntactically incorrect regular expression in the shairport-sync config file.
A warning has been added to our documentation.
This problem has been fixed upstream in jack2 by Thomas Brand with https://github.com/jackaudio/jack2/commit/d4ef6800b4fe9ee61d0b9a1b76af1292023a40e7 and https://github.com/jackaudio/jack2/commit/d63193b6ebb84b9b2a104517cb6ab1b087ca3a54. jack1 is probably still affected

**Comment by microfx** [comment]
are you proceeding with the development? Any idea when this could be included in the main branche?

**Comment by nettings** [comment]
Since this is an upstream bug, there is nothing that we can meaningfully do about it, other than add documentation. It's an important bug because users shouldn't be able to segfault a jack server, but in this case "user" means the admin of shairport-sync, not random end-users connecting their devices. So I think we can live with it for now.
As to the basic JACK functionality, it's there and works reliably for me.
For now, there is the limitation that the JACK server will have to run at 44k1, and while I hope to find time to understand the already-existing adaptive soxr resamplling well enough to be able to cater to arbitrary JACK backend sample rates at minimal or no additional CPU cost, I don't think it should be a blocking issue.

**Comment by microfx** [comment]
Good to hear! And yeah, my jack/DAC runs at 48 kHz .. so I guess I have to hope you find time as well. Thanks a lot for the update!

**Comment by nettings** [comment]
Yeah, same here, I run all my studio gear at 48k, too. If you don't mind a little project, here's a workaround: install shairport-sync on a small computer such as a RPi3B+, and use zita-j2n to bridge this JACK (running at 44k1) to the network. Then, on the main machine, zita-n2j will receive the stream and feed it into your JACK graph. Since it has to do adaptive resampling anyways because the two JACK clocks are unsynchronized, it will gladly convert between 44k1 and 48 at no extra computational cost.
