### ISSUE TITLE
Is it possible to see whether the current song is playing from the metadata?

### ISSUE THREAD

**Issue by MCJack123** [mikebrady/shairport-sync#814]
I would like to display some song information on a display only if a song is currently playing; otherwise it shows a clock. Is it possible to see if a song is playing? If so, which metadata code do I check?

**Comment by mikebrady** [comment]
You might find some information in the [README.md](
https://github.com/mikebrady/shairport-sync-metadata-reader/blob/master/README.md) file for the sample metadata reader.

I'd suggest:
 * `pbeg` -- play stream begin. No arguments
 * `pend` -- play stream end. No arguments
 * `pfls` -- play stream flush. No arguments
 * `prsm` -- play stream resume. No arguments

... you might have to experiment.

**Comment by MCJack123** [comment]
I ended up using the `prsm` code to detect paused/playing state, but it seems like sometimes shairport-sync sends `prsm` even if the song is being paused. Another thing is that `prsm` is send after `mden`, which required me to change the script to return on `prsm` instead of `mden`. My script sometimes sends out the metadata even though I paused the song because of this. It's not too big of a deal as it only appears for a split second, but this may need to be investigated.

**Comment by mikebrady** [comment]
That's interesting. Shairport Sync is somewhat at the mercy of whatever comes from the audio source. In the upcoming update (see the `development` branch), Shairport Sync introduces an "active mode" which smooths out the transitions a bit. It has two new metadata codes -- `abeg' and `aend`. Not sure it's what you want, but maybe worth a look.

**Comment by OneBobone** [comment]
I spent a lot of time on this recently and tested with many sources.
My recommendation is to trigger on the status code `corecaps` complemented with `abeg` and `aend`. 
Also to avoid unnecessary pause/play when songs change, I make sure to only execute when Duration>0, but to use the duration = 0 to latch play on `coreastm` 

Hmm, not a very good explanation...
I could append some code?
