### ISSUE TITLE
Settings for Allo DigiOne transport

### ISSUE THREAD

**Issue by nicolabotta** [mikebrady/shairport-sync#815]
I am running shairport-sync (2.8.6-OpenSSL-Avahi-ALSA-pulse-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc) on a Raspberry Pi 3B+ running a minimal Raspbian Lite distribution (Linux rpi6 4.14.74-rt44-v7+ #1 SMP PREEMPT RT Thu Nov 8 12:16:44 CET 2018 armv7l GNU/Linux).

The sound card is an Allo DigiOne Signature transport. Everything works fine but from time to time I get massive dropouts while streaming Idagio contents from an iPad under iOS 12.1.4.

I suspect problems upstream shairport-sync because the dropouts also affect local replay on the iPad. However the shairport-sync logs seem to suggest synchronization problems, please see below. I have two specific questions:

1) Where can I find the shairport-sync log file? I can only see shairport-sync log messages in /var/log/syslog.

2) Is there a recommended setting for using shairport-sync in conjunction with the Allo DigiOne (Signature) transport?

I understand that I am running an old version of shairport-sync but I thought I would ask before I try to build shairport-sync from the sources. Thanks for your support and, of course, for providing shairport-sync!

```
Feb 24 14:57:24 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7966.5,    18716.0,    93169.0.
Feb 24 14:57:37 rpi6 shairport-sync[1241]:       85.6,     -24.9,      24.9,       93950,      0,      4,      0,      4,   6225,  232,  245
Feb 24 14:57:44 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7954.8,    18692.3,    93568.0.
Feb 24 14:58:04 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7956.3,    18716.6,    93336.0.
Feb 24 14:58:07 rpi6 shairport-sync[1241]:       83.0,     -33.3,      33.3,       97708,      0,      4,      0,      4,   6220,  232,  245
Feb 24 14:58:24 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7969.1,    18721.5,    93816.0.
Feb 24 14:58:37 rpi6 shairport-sync[1241]:       79.5,     -15.9,      15.9,      101466,      0,      4,      0,      4,   6210,  232,  245
Feb 24 14:58:44 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.9,    18752.8,    93434.0.
Feb 24 14:59:04 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7989.8,    18760.6,    93260.0.
Feb 24 14:59:07 rpi6 shairport-sync[1241]:       84.3,     -23.4,      23.4,      105224,      0,      4,      0,      4,   6224,  232,  245
Feb 24 14:59:24 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.4,    18723.3,    93468.0.
Feb 24 14:59:37 rpi6 shairport-sync[1241]:       85.4,     -21.9,      21.9,      108982,      0,      4,      0,      4,   6225,  232,  245
Feb 24 14:59:43 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.3,    18729.6,    92871.0.
Feb 24 15:00:03 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7991.8,    18758.1,    93240.0.
Feb 24 15:00:07 rpi6 shairport-sync[1241]:       85.4,     -21.9,      21.9,      112740,      0,      4,      0,      4,   6218,  232,  245
Feb 24 15:00:23 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7978.5,    18730.4,    93398.0.
Feb 24 15:00:37 rpi6 shairport-sync[1241]:       83.2,     -24.2,      24.2,      116498,      0,      4,      0,      4,   6221,  232,  245
Feb 24 15:00:43 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7992.1,    18725.7,    93346.0.
Feb 24 15:01:03 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.8,    18756.7,    93542.0.
Feb 24 15:01:07 rpi6 shairport-sync[1241]:       79.6,     -36.3,      36.3,      120256,      0,      4,      0,      4,   6193,  232,  245
Feb 24 15:01:23 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7978.1,    18689.8,    93179.0.
Feb 24 15:01:37 rpi6 shairport-sync[1241]:       79.6,     -10.6,      10.6,      124014,      0,      4,      0,      4,   6213,  232,  245
Feb 24 15:01:43 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7991.4,    18746.0,    93492.0.
Feb 24 15:02:03 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7979.2,    18733.7,    93145.0.
Feb 24 15:02:07 rpi6 shairport-sync[1241]:       78.0,     -32.5,      32.5,      127772,      0,      4,      0,      4,   6204,  232,  245
Feb 24 15:02:23 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7965.8,    18710.5,    93652.0.
Feb 24 15:02:37 rpi6 shairport-sync[1241]:       78.2,     -20.4,      20.4,      131530,      0,      4,      0,      4,   6212,  232,  245
Feb 24 15:02:43 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7966.0,    18649.6,    93139.0.
Feb 24 15:03:03 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7968.7,    18686.8,    93220.0.
Feb 24 15:03:07 rpi6 shairport-sync[1241]:       83.7,     -16.6,      16.6,      135288,      0,      4,      0,      4,   6222,  232,  245
Feb 24 15:03:23 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7981.9,    18739.5,    93030.0.
Feb 24 15:03:37 rpi6 shairport-sync[1241]:       85.0,     -26.5,      26.5,      139046,      0,      4,      0,      4,   6223,  232,  245
Feb 24 15:03:43 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.6,    18695.2,    93027.0.
Feb 24 15:04:03 rpi6 shairport-sync[1241]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7980.1,    18640.2,    92966.0.
Feb 24 15:04:07 rpi6 shairport-sync[1241]:       83.7,     -22.7,      22.7,      142804,      0,      4,      0,      4,   6222,  232,  245
```

**Comment by mikebrady** [comment]
Thanks for the post and for the kind words. TBH, the log doesn't really reveal much of a synchronisation problem. It looks like there is a divergence between the source and your player of about 20 or 25 ppm, which is not bad at all, in my experience.

Similarly, the maximum packet reception intervals at something less than 100 ms is okay, in my experience.

The number of missing packets is also very low -- effectively zero.

To answer your specific questions:
1. There is no shairport-sync.log -- it's all routed to the syslog. 
2. Looking at the [rather skimpy] manual, it's an I2S device. You should look at it with something like `alsamixer` to see if it has an attenuator / mixer and what name to use to control it. Also, you should really consider updating to the latest version of Shairport Sync. Apart from fixing quite a few bugs, you can set the output to 24 or 32 bits, which would certainly be useful if the device has no mixer / attenuator.

**Comment by nicolabotta** [comment]
Thanks, I have now installed 3.2.2 and the issues are still there. I very much suspect the problems to be due to the Idagio app or to the iPad/network.

On the settings side: my MPD setting for the DigiOne Signature are as follows:

```
  type                "alsa"
  name                "Allo DigiOne"
  # device             "hw:0,0"                                                                                           
  device              "hw:sndallodigione"
  # mixer_type         "hardware"                                                                                         
  mixer_type          "none"
  replay_gain_handler "none"
  auto_resample       "no"
  auto_channels       "no"
  auto_format         "no"
  use_mmap            "yes"
  dop                 "yes"
```
Can you suggest suitable settings for shairport-sync? I am particularly interested in suitable values for `mixer_control_name`, `mixer_device`, `output_rate` and `output_format`. My only deviations from the default settings at this point are

```
  ignore_volume_control = "yes";
  output_device = "hw:0,0";
  statistics = "yes";
  log_verbosity = 2;
```
The DigiOne I2S to S/PDIF interface is connected to a Naim DAC via electrical S/PDIF, thus everything up to 24bits / 192kHz should be fine. On the other hand, Idagio streams are 16bits/ / 44.1kHz and I would prefer not to do any upsampling. 

Thanks,
Nicola

**Comment by mikebrady** [comment]
Thanks for the information.

Perhaps a little experimentation is in order. Maybe you've done this before, so please forgive me if you have.

First, for Shairport Sync, if you change the output device to, simply, `"hw:0"`, does it continue to work?

Secondly, if you run up `alsamixer` and select this device, do you get something like this (this picture is from the default Raspberry Pi output device, and show that the output device's mixer name is `"PCM"`)?

<img width="976" alt="image" src="https://user-images.githubusercontent.com/4265913/53304494-e40a9400-386d-11e9-8ede-51e7bdea0039.png">

Regarding sampling rates, I share your reluctance to do any kind of resampling. If the DAC has a hardware mixer, I would make no changes so as to route audio through Shairport Sync with as little interference as possible. However, if it has no mixer, they you will be relying on the build-in software attenuator. Switching to 24- or 32-bit output is advantageous, as the dither will be at bottom of the expanded dynamic range. Switching samples from 16- to 24- or 32-bit is a completely straightforward multiplication by 256 or 65536, so it is effectively not changing the samples at all.

**Comment by nicolabotta** [comment]
Changing the output device to `hw:0` has no effect, it works as before. Here is my alsamixer screenshot

![screenshot_2019-02-24_21-36-52](https://user-images.githubusercontent.com/2726946/53305105-9564f600-387d-11e9-8948-6705efcf3e27.png)

I have no clear notion of what an hardware mixer is but I very much doubt that the DigiOne Signature or the Naim DAC attached to it have such a functionality. All the devices that go into the Naim DAC (TV, Oppo 203 and DigiOne Signature) have no volume control or are set to fixed max. volume. The volume level is consistent through devices. The DigiOne Signature specs. mention that 

_Output is coaxial/BNC and rise/fall time is 1ns and voltage level is exactly as per guidelines (550mV on coaxial) measured at end of transmitting cables_

if this can be of any help. I have used the above MPD settings since ever but I will check them again on the Allo DigiOne Signature support forum on CA and report back.Thanks again for your assistance!

**Comment by nicolabotta** [comment]
Cross checking the MPD settings:  https://audiophilestyle.com/forums/topic/49667-allo-digione-signature/?do=findComment&comment=932046

**Comment by mikebrady** [comment]
Looking at the screenshot and the MPD stuff, it does indeed look like there is no hardware mixer, and in any case, you want everything to go through at full volume. It seem to me therefore that the settings you have are the best ones — audio data gets through Shairport Sync without modification apart from occasional interpolation. I haven’t tried Idagio for a while, so can’t really comment on the problems you’re having upstream.

**Comment by nicolabotta** [comment]
I have now been streaming Idagio contents for a couple of hours without any glitches by letting the iPad resting on my table:
```
Feb 25 17:29:32 rpi6 shairport-sync[414]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7979.9,    18738.4,    93270.0.
Feb 25 17:29:33 rpi6 shairport-sync[414]:        1.9,      -2.8,       2.8,     1510518,      0,      3,      0,      3,   6227,  233,  245
Feb 25 17:29:41 rpi6 shairport-sync[414]:        1.9,     -59.5,      59.5,     1511521,      0,      3,      0,      3,   6226,  232,  245
Feb 25 17:29:49 rpi6 shairport-sync[414]:        1.9,     -17.0,      17.0,     1512524,      0,      3,      0,      3,   6228,  233,  246
Feb 25 17:29:52 rpi6 shairport-sync[414]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7990.5,    18804.8,    93849.0.
Feb 25 17:29:57 rpi6 shairport-sync[414]:        1.9,     -36.8,      36.8,     1513527,      0,      3,      0,      3,   6227,  232,  245
Feb 25 17:30:05 rpi6 shairport-sync[414]:        1.9,     -51.0,      51.0,     1514530,      0,      3,      0,      3,   6225,  233,  245
Feb 25 17:30:12 rpi6 shairport-sync[414]: Packet reception interval stats: mean, standard deviation and max for the last 2,500 packets in microseconds:     7978.7,    18703.5,    92901.0.
Feb 25 17:30:13 rpi6 shairport-sync[414]:        1.8,       0.0,       0.0,     1515533,      0,      3,      0,      3,   6221,  233,  245
Feb 25 17:30:21 rpi6 shairport-sync[414]:        1.9,     -25.5,      25.5,     1516536,      0,      3,      0,      3,   6225,  233,  245
```
As long as I do not touch the iPad, everything works fine. Dropouts immediately start as soon as I play around with the iPad.  

Thus, this seems to be a problem with iOS and I think that you can close the issue. It's a pity because the sound quality is fine and the connection is very reliable as long as ... the the iPad is idling! Thanks again for your assistance!

**Comment by mikebrady** [comment]
Many thanks.

**Comment by voideater** [comment]
@nicolabotta what kind of settings for shairport-sync did you end up using to get audio out from the Allo DigiOne?

**Comment by apski** [comment]
@nicolabotta @voideater did you get this working? I'm also struggling to get shairport-sync working with Allo DigiOne.

**Comment by mikebrady** [comment]
It might be worth running [sps-alsa-explore](https://github.com/mikebrady/sps-alsa-explore)to see if it can guide you as to what hardware devices are available for Shairport Sync.
