### ISSUE TITLE
interpolation default to soxr if built with libsoxr support

### ISSUE THREAD

**Issue by swills** [mikebrady/shairport-sync#817]
I was having bad distortion using shairport-sync, but discovered that changing interpoltion to soxr fixed it. It seems to me that it would be nice if it were setup so that if shairport-sync is built with soxr support, then that would be the default. I can work on a patch for this, but thought I'd see what you think of the idea first.

**Comment by mikebrady** [comment]
Thanks for the post, and I'm glad that you got the distortion fixed. In my experience, the distortion from the "basic" interpolation is almost inaudible when you are playing normal audio material. There is no doubt that "soxr" interpolation is less intrusive, but, using the analogy of the canary in the coalmine, is it possible that there are problems elsewhere with the setup (e.g. if there is lots of interpolation going on, then many the clock sources are suspect)?

To turn to your suggestion, I guess my working idea was that one would (a) include support for something extra and then (b) explicitly enable it. Your suggestion turns that convention around. It seems to me that the logic of it should apply to any extra feature for which support is included, e.g. the Apple ALAC decoder and metadata.  Let's have a think about it first.

**Comment by swills** [comment]
Thanks for the quick response. I'm pretty sure the interpolation is the source of the issue, as I notice it pretty prominently and it goes away immediately without making any change other than the interpolation.

You're correct about changing the convention. The idea is, if the user enabled soxr, they clearly want to use it, so make it default instead of requiring an extra step. It simply makes things easier and nicer for the user.

You make a good point about applying the logic uniformly across all extra features. The soxr and ALAC support seem like the only places where this change needs to be made. The default audio back-end already changes if you only enable one. And the description for the soxr option even seems to imply it will be used if you enable it, while the ALAC option suggests only that it is available:

```
  --with-soxr = choose libsoxr for high-quality interpolation
  --with-apple-alac = include support for the Apple ALAC decoder
```

**Comment by mikebrady** [comment]
Fair points indeed.

Going back to your initial issue, if you enable statistics, you’ll get an idea of how much interpolation is going on. If it’s more than about 120 ppm, it deserves investigation.

**Comment by mikebrady** [comment]
I've actually made the change you suggested, along with the same for the Apple ALAC decoder and for anything to do with metadata. Let's see what happens....

Thanks for the idea, I think :)

**Comment by swills** [comment]
Looks great, thanks!
