### ISSUE TITLE
3.3rc0 mqtt missing ?

### ISSUE THREAD

**Issue by gibman** [mikebrady/shairport-sync#818]
Hi Mike.

I just updated to vers : 3.3rc0-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/usr/local/etc

As I found the MQTT addition very interesting.

Although it seems like it's not included into the binary.
Just did some raw searching in the compiled binary for mqtt. no trace of any of the mqtt keys.

do I have to do something special in order to get MQTT working ?

here's an small excerpt from the config:
```
// How to enable the MQTT-metadata/remote-service
mqtt = 
{
    enabled = "yes"; // set this to yes to enable the mqtt-metadata-service
    hostname = "192.168.1.123"; // Hostname of the MQTT Broker
    port = "1883";
    username = "***"; //set this to a string with your username, to enable username authentication
    password = "***"; //set this to a string with your password, to enable username & password authentication
//	capath = NULL; //set this to the folder with the CA-Certificates to be accepted for the server certificate. If not set, TLS is not used
//	cafile = NULL; //this may be used as an (exclusive) alternative to capath with a single file for all ca-certificates
//	certfile = NULL; //set this to a string to a user certificate to enable MQTT Client certificates. keyfile must also be set!
//	keyfile = NULL; //private key for MQTT Client authentication
	topic = "house/firstfloor/kitchen/airplay"; //MQTT topic where this instance of shairport-sync should publish. If not set, the general.name value is used.
//	publish_raw = "no"; //whether to publish all available metadata under the codes given in the 'metadata' docs.
	publish_parsed = "yes"; //whether to publish a small (but useful) subset of metadata under human-understandable topics
//	Currently published topics:artist,album,title,genre,format,songalbum,volume,client_ip,
//	Additionally, empty messages at the topics play_start,play_end,play_flush,play_resume are published
//	publish_cover = "no"; //whether to publish the cover over mqtt in binary form. This may lead to a bit of load on the broker
    enable_remote = "yes"; //whether to remote control via MQTT. RC is available under `topic`/remote.
//	Available commands are "command", "beginff", "beginrew", "mutetoggle", "nextitem", "previtem", "pause", "playpause", "play", "stop", "playresume", "shuffle_songs", "volumedown", "volumeup"
};
```

**Comment by mikebrady** [comment]
Thanks for the post. You need to include `--with-mqtt-client` At the `./configure...` stage. (Documentation need an update...)

**Comment by gibman** [comment]
ahh.. thank you :)

I did suspect the configure part as being the culprit.

**Comment by gibman** [comment]
btw. I had to install this in order to be able to run configure
sudo apt-get install libmosquitto-dev

**Comment by mikebrady** [comment]
Yep, the ultra-smart configure script told you, right? 😉

**Comment by gibman** [comment]
hehe.. yeah :)

Very cool btw. now I have my rpi3 running an instance of the hass.io (home assistant software) that listens to "play_end" / "play_start" topics.

It makes me able to automatically turn on the associated AVR automatically once I start stream to shairport-sync. It will also automatically turn off the AVR once done streaming.
logitech's harmony hub + a IR wireless repeater make it all happen.

I'm a bit confused about the MQTT commands.
Play/ pause etc.
what does it do for an airplay endpoint like SPS ?

Although I can see the good use for "volumedown", "volumeup"

**Comment by mikebrady** [comment]
What should happen to those commands is that they are relayed to the AirPlay source. Some sources will obey them (e.g. iOS and iTunes). Not sure about TuneBlade. So, you should be able to control the AirPlay source: MQTT → Shairport Sync → AirPlay Source.

**Comment by gibman** [comment]
Ahh makes sense now.

regarding payload topic for 'volume'
i get stuff like this back: '-0.00,-0.00,-96.30,0.00'
How should this be interpreted ?

**Comment by mikebrady** [comment]
BTW, I just pushed an update in `development` which adds "active_start" and "active_end", I think.

**Comment by mikebrady** [comment]
It's always worth checking the comments in `rtsp.c`:

```
//    'pvol' -- play volume. The volume is sent as a string --
//    "airplay_volume,volume,lowest_volume,highest_volume"
//              volume, lowest_volume and highest_volume are given in dB.
//              The "airplay_volume" is what's sent to the player, and is from
//              0.00 down to -30.00,
//              with -144.00 meaning mute.
//              This is linear on the volume control slider of iTunes or iOS
//              AirPlay.
```

**Comment by mikebrady** [comment]
(I really do need to update the documentation, sigh...)

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
