### ISSUE TITLE
Discovery like AppleTV

### ISSUE THREAD

**Issue by Candid-Code** [mikebrady/shairport-sync#82]
I would really like if shairport would be discoverable without being connected to an wifi access point. The Apple TV has this ability via wifi.

**Comment by mikebrady** [comment]
Hi there. Thanks for your interest in Shairport Sync. I'm pretty sure that the technology Apple uses to achieve this is based on a combination of an advanced feature of some WiFi transceivers and Bluetooth LE – the same technologies they use to implement "AirDrop" and "Handoff". It's well beyond the scope of Shairport Sync, I'm afraid, which uses Zeroconf.

**Comment by mikebrady** [comment]
I'm going to close this as being out of scope – it's got nothing really to do with Shairport Sync. Feel free to reopen if you wish.
