### ISSUE TITLE
macOS 

### ISSUE THREAD

**Issue by signalsout** [mikebrady/shairport-sync#821]
Hello, Running shairport-sync on Mac OS. Have two Mac related questions. 

While running as regular user it will play through my line out fine until I play audio from another source such as a system sound then it crashes. I imagine it’s holding the device to itself and then panics when something else takes control. How do I resolve this issue. 

Also when running as -d as root it plays audio through my internal speaker. I’m assuming it’s because the default interface for root is internal speaker. Any assistance would be greatly appreciated. 

Mac OS X 10.7.5.

**Comment by mikebrady** [comment]
I wonder if any of the homebrew guys have any suggestions.

**Comment by Clovel** [comment]
I don't quite get you scenario for your first issue. Can you be a little more explicit ? 

Default interface for the the `root` user is the internal speakers. When you change the output device, I think it changes it for the current user. (Someone should check this). You would need to change the interface used by `root`, maybe with the command line. Maybe test changing the output for "Sound effects" in `System Preferences.app`
