### ISSUE TITLE
Ubuntu 19.04

### ISSUE THREAD

**Issue by kentherzz** [mikebrady/shairport-sync#823]
I just installed Shairport Sync on Ubuntu 19.04 and I cannot seem to get audio when streaming from my iPhone with the same config I was using for 18.10. However the version of shairport-sync changed from 3.1.7 to 3.2.2 as it got upgraded. What could be the issue? 
Regards

**Comment by mikebrady** [comment]
Hmm. Just (March 24) ran up the latest daily of Ubuntu 19.04 on VMWare Fusion and installed Shairport Sync 3.2.2, which worked without issue on default settings.

Ubuntu 19.04 is not finalised yet, and it was a little bit tricky to get it to install in VMWare in the first place. Maybe the drivers for your audio device (?) haven't been included yet, or something. It's [due on April 18](https://thishosting.rocks/ubuntu-19-04/).

**Comment by mikebrady** [comment]
One thing worth noting is that the Ubuntu 19.04 (like all recent versions) uses PulseAudio, and maybe the default ALSA output device is really a virtual device that feeds into the PulseAudio system. Shairport Sync really works best with a real hardware device, which will have a name beginning with `hw:`, like `hw:0`.

**Comment by kentherzz** [comment]
Thanks for the answer! Following up on this.
- Shairport doesn't appear under Applications in sound menu on 19.04, it did in 18.10.
- Default settings doesn't work for me. I use following:

These are my settings:
name = “HTPC";
drift = 352; 
volume_range_db = 30;
output_device = “hw:0”;
mixer_control_name = “PCM”

This is a Intel NUC and it is connected to HDMI 24/7, the audio works fine. The only thing I changed in Pulseaudio deamon was the sample rate. I changed it to 48000, as the standard 44100 caused the sound to not play from TV speakers. I guess there are no sample rate related settings in Shairport sync is there?

Btw: not sure if "drift" is deprecated now, I stumbled upon these settings here https://discourse.osmc.tv/t/airplay-audio-server/20294 and have sticked with them since.
After using these settings things worked in Ubuntu 18.10. Default didnt work there either.

Any more hints or suggestions? :) Thanks a lot!

**Comment by kentherzz** [comment]
I'm so sorry, things didn't work in 18.10 either for me. I meant version 18.04! The LTS, it was all working fine there. So the question is, what has changed?

**Comment by kentherzz** [comment]
Update: I get following error message when trying to play sound:
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave

**Comment by kentherzz** [comment]
Another update with some verbose debugging.

I managed to get it working now by running Shairport Sync with my normal users, default settings in Shairport are indeed fine.

With command "shairport-sync -v" sound from speakers work.

However if i do "sudo systemctl enable shairport-sync" and then "sudo systemctl start shairport-sync".  it doesn't work. I verified this by running "sudo shairport-sync -v" and program was running but no sound from speakers. I get this message when I run as system/admin: 

No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Whats the reason for that?

**Comment by mikebrady** [comment]
To be honest, I'm getting a bit confused here. It looks like Shairport Sync is outputting to PulseAudio, but that seems to conflict with the earlier report.

So, would you be kind enough to post the result of executing `$ shairport-sync -V` please? (Note, it's a capital V.) Also, are there any more settings other than those you quote above?

**Comment by kentherzz** [comment]
htpc@HTPC:~$  shairport-sync -V
3.2.2-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc

**Comment by kentherzz** [comment]
It is outputting to ALSA, no? Is there a way at all to output to Pulseaudio directly? This Linux is confusing when it comes to ALSA/Pulseaudio. Haven't figured out properly this yet.

Anyways, some more system settings:
### ALSA SETTINGS ###
etc/asound.conf
**I added these:**
pcm.default pulse
ctl.default pulse

### PULSEAUDIO SETTINGS ###
/etc/pulse/default.pa
**I added these:**
load-module module-alsa-sink device=hw:0
load-module module-alsa-source device=hw:0

**Comment by mikebrady** [comment]
Thanks. You have indeed built Shairport Sync for using the ALSA sound system. Unfortunately, your setup is such that the default ALSA device is actually not a real output device – it's a conduit into the PulseAudio system. So, audio routed from Shairport Sync into the default ALSA device is then sent into the PulseAudio system.

This causes problems because PulseAudio is not set up to be a system-wide facility, so it can't provide an audio service that runs as a daemon service like Shairport Sync does when it is fully installed. It works from the command line because it's running under your account name, and because you are logged in, PulseAudio has been set up for your account.

If you can direct Shairport Sync's output to a real hardware ALSA device, then that should work.

**Comment by mikebrady** [comment]
BTW, if it's set up for ALSA, it won't appear in the Sound Applications – you need to compile it for PulseAudio and use the PulseAudio backend for that to happen. Futehrmsre,  it only works when you are logged in – it can't be set up to run as a daemon due to the restrictions imposed by the PulseAudio setup.

**Comment by kentherzz** [comment]
Thanks for your time and help Mike, I really appreciate it! I am pretty new to Ubuntu and just starting to figure things out. I didn't build Shairport Sync, I just got it from the Ubuntu repository with apt install.

Why doesn't the package on Ubuntu servers contain pa backend? Is it possible to add this? Who decides that? It would be much more convenient for me to update Shairport Sync though a system update without having to build every time.

Some other quick questions:
- Apple codec: Is this better than the default one? Why would someone need that?
- Latency: Is it possible to reduce the 2-3 second latency at all?
- SOXR: what is it? Does it give me better sound quality? Is it enabled by default in config?

Thanks a lot!

**Comment by mikebrady** [comment]
Thanks. Some answers, though most of them are answered in the README.
* I haven't seen much difference between the Apple ALAC and the Hammerton.
* Soxr allows Shairport Sync to use the SoX library to give smoother interpolation.
* If the system has PulseAudio, then it's best not to uninstall it and to use the `pa` backend for Shairport Sync.
* Convolution and loudness should be off by default and are not included in the build. You should consider both of them to be experimental.
* Sync works on `alsa`, `pulseaudio` and `sndio` backends. Playing e.g. a video in Facebook on YouTube either the app or in Safari on an iOS device should be synced.

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
