### ISSUE TITLE
How to read metadata with dbus?

### ISSUE THREAD

**Issue by vasilisvg** [mikebrady/shairport-sync#824]
By following [the steps I found in this comment](https://github.com/mikebrady/shairport-sync/issues/223#issuecomment-441758016) I was able to create a very simple remote control app which issues simple commands like `airplay-remote VolumeUp`. This works really well. 

The thing that’s missing from this remote is some metadata: I would like to see what song is playing. And I can’t figure out how to get this metadata from dbus. It doesn't seem to be as simple as using something like `airplay-remote Artist`. Does anybody know how to get this done?

**Comment by OneBobone** [comment]
I would suggest to use the metadata that is available by setting the flag --with-metadata when compiling to add support for Shairport Sync to pipe metadata to a compatible application of your choice or UDP. 
Enable the settings in the config file.
See https://github.com/mikebrady/shairport-sync-metadata-reader for a sample metadata reader.

**Comment by mikebrady** [comment]
Thanks for your interest in this. Shairport Sync actually offers two D-Bus interfaces. One is a pretty decent subset of the [MPRIS](https://specifications.freedesktop.org/mpris-spec/2.2/) interface standard and the other is a Shairport-Sync-specific interface, modelled on MPRIS. Both provide quite a lot of metadata, including artwork, title, artist and so on. However, D-Bus interface programming is a bit tricky.

If you build Shairport Sync with an extra configuration flag: `--with-dbus-test-client`, you'll get a very simple application program, written in C, that listens to notifications coming from a fully-installed Shairport Sync. It might give you some hints.

**Comment by mikebrady** [comment]
Closing this. Please feel free to open another issue if necessary.
