### ISSUE TITLE
Meta Data Isn't working for me.

### ISSUE THREAD

**Issue by dxfan227** [mikebrady/shairport-sync#826]
Very new at all of this so I appreciate your patience. I am trying to set up a magic mirror and airplay speaker with my Raspberry Pi B+. I installed shairport via the "simple" installation procedure listed in the read me file. I then tried to use a module for magic mirror that reads the meta data from /tmp/ folder. It doent work.

I scoured for a long time and I think my issues was during the build and compile and install procedure I didnt do --with-meta-data   so I started over, rm'ed the folder listed in the instructions...and added with-meta-data to the string......It still doest display my meta data and their doesnt seem to be a folder in my tmp directory with meta data socket.

I really don't know how to troubleshoot further on my own so I am looking for guidance here. 

One thing I did think was interesting was even after doing the rm command listed in the instructions I was still left with a Shairpoint-server folder and after "re-installing" my config file was still the same( with the proper meta data fields enabled"

**Comment by mikebrady** [comment]
Thanks for the post. Have you followed the README instructions at [MMM-ShairportMetadata](https://github.com/surekap/MMM-ShairportMetadata)? n important thing to note is that everything must be done _exactly_ as described -- Linux is case-sensitive and even a stray space or tab can cause a program or a script not to work.

**Comment by dxfan227** [comment]
Hi ! Thank you for the response!

Yes I read everything , I get an error when running the module saying that the directory /temp/stair port-meta data/ ( working off memory but it’s the folder specified in the module and the shairport confid file) does not exist.

I have been doing more reading and I think the first step it to ensure that my /tmp/ folder has the right permissions. How would I check this?

**Comment by dxfan227** [comment]
Please close this issue. It was resolved by locating the correct config file for share-port

**Comment by mikebrady** [comment]
Great, thanks.
