### ISSUE TITLE
Displaying Apple Music "Now Playing" Cover Art on Another Screen?

### ISSUE THREAD

**Issue by DomusDigital** [mikebrady/shairport-sync#827]
Hi

Our scenario is in a home with networked music utilising AirPlay to a Pi running moode with ShairPoint on a home network.

User plays music on AppleMusic via their iPhone, and AirPlays to the network. 

There will also be a small screen on the wall, either running Android or, in the case of an Intel-driven display, running either Windows 10 or Linux. I expect the AirPlay receiver(s) on the network will be a couple of Pi's running Shairpoint (probably with moode) but there will be an AppleTv and even could be a Mini if that would help us to achieve our goal.

We'd like that panel to pick up from AirPlay the information regarding what is playing and display the cover art, and if possible even have access to the strings that share the ability to Stop, Play, Pause, etc. 

When using the Moode player, it broadcasts this information (art URL and control strings) and any browser can connect and get access to this information (what's playing, where it is in the track, the ability to pause play stop etc).

Can we achieve the above bolded goals, particularly the album art display.

**Comment by dxfan227** [comment]
Hello. I am very new but thought I could try and help.

Look into the magic mirror project specifically the module shaker port meta data. It pulls the meta data from shairport to the module ( album art and track name) and displays it.

**Comment by DomusDigital** [comment]
Will do. Thank you.

**Comment by dxfan227** [comment]
Sorry I was a bit rushed on my last message. Here's a link to MagicMirror

https://magicmirror.builders/ -It's very simple to get up and running I have literally zero linux experience and was able to use their guide to get it up and running within 15 min. They have options to start on boot as well.

Here is a link to the shairport-sync widget:

https://github.com/surekap/MMM-ShairportMetadata

basically you just clone that repo to your newly created /MagicMirror/modules folder, then edit your magic mirror config.js file to include the module code. 

Don't forget to edit the configuration file for shairport-sync aswell and UNCOMMENT out the areas specificed in the modules gitwiki to enable meta data.

Last tip, when installing/compiling etc the shairport-sync program itsellf make sure you use --with-metadata.

hope this helps

**Comment by xuepgao** [comment]
@mikebrady 

Thank you for give us this AirPlay modules. It's so faddish!
Except for the album art and track name, can it display song lyrics?
