### ISSUE TITLE
No Audio Through Bluetooth Speaker

### ISSUE THREAD

**Issue by dxfan227** [mikebrady/shairport-sync#828]
I have shairport up and running (sporadically but that’s another issue to be dealt with later)

I have a blue tooth speaker hooked up to the pie and it plays system sounds/YouTube no problem. But when I play anything on my phone via airplay it’s dead silence.

**Comment by mikebrady** [comment]
There is quite a bit about this on the internet and indeed on these pages. I haven’t tried it out but it does not look straightforward.

**Comment by dxfan227** [comment]
I agree, I looked through some of the posts here late last night. Seems very difficult to get it working with Shaireport for some reason.

That being said I am now looking at wired options and I'm a little stuck so maybe you have some Ideas? Do I need a DAC or and AMP? Do you have any reccomendations on what type of speakers are easiest to get up and running on the PI/Shairport compatible?

**Comment by mikebrady** [comment]
Any decent DAC, I2S or USB will work. I’ve had success with the IQAudIO DACs and amplifiers and with the lowest-cost Pimoroni PHAT DAC.

**Comment by dxfan227** [comment]
I guesse I need to understand what each one does a bit more... with just a DAC I would still need and amp correct?

**Comment by mikebrady** [comment]
Yep. Digital Audio → DAC → Amplfier → Speakers

**Comment by dxfan227** [comment]
Alright, and are most speakers ( like say pc speakers) require an amp...or do they have them onboard? How do I tell the difference...would it just be speakers that have power cordes vs those that dont?

in the cases of speakers with internal amps.....the kind of connecting do you use for DAC----> speakers

**Comment by mikebrady** [comment]
Yep, speakers with built-in amps (sometimes called “active speakers”) will have a power supply — either via a power cord or built-in batteries.

**Comment by dxfan227** [comment]
Alright thanks, real quick how does an amplifier like this 

https://www.adafruit.com/product/987. Power the speakers? I don’t see a traditional power input... so is it powered by the pi itself?

Also is an analog signal a requirement for the speakers? Or for shairport?

**Comment by mikebrady** [comment]
Shairport Sync gets the digital data to an output, usually a DAC which produces an analog signal, sometimes to a jack and sometimes directly into an integrated amplifier. What happens there is really someone else's expert area.
