### ISSUE TITLE
No audio played - iPod with iOS 4.2.1

### ISSUE THREAD

**Issue by flxkrmr** [mikebrady/shairport-sync#83]
Hey,
I'm currently trying to debug this. Do you have any suggestion what might go wrong?

Shairport-sync is running on a Carambola 2 Board in AP mode. Audio streaming works with my Android phone and the AirAudio app. With the iPod a connection is set up, but it seems that the iPod isn't sending the RECORD message. Here is the output of -vv (I have also enabled the message dump prints):

```
root@carambola2:/# shairport-sync -vv -a WARP
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
Shairport Sync player name is "WARP".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
latency is 0.
AirPlayLatency is 88200.
iTunesLatency is 99400.
stuffing option is "(null)".
resync time is 2205.
busy timeout time is 120.
startup
avahi: avahi_register.
avahi: register_service.
culling threads.
new RTSP connection.
    CSeq: 0.
    Apple-Challenge: 3nCmb0RWt1+XLrlSNjcByQ==.
RTSP Packet received of type "OPTIONS":
  Type: "CSeq", content: "0"
  Type: "Apple-Challenge", content: "3nCmb0RWt1+XLrlSNjcByQ=="
RTSP Response:
  Type: "Apple-Response", content: "K3KV/lrq8MzR65qogDpNSIT5T/pB4VtJ1CZ82yRJ+GBIfhpiTy3iyJjDyaGreUxhLOnyXthnAL4/xd4WCSelT9vHyysCyOaqVdlzdy5haRGiC9A3O6P9PD4oyG7Bsx5IEybbpXJ3E4YOAf3WZARjxFcSCmTuKzt5gJurRivsGfl5vIgb05qJRBAUA9wBcoVqZYwtbfz3QC99DHEEHGliZddI61X5gQBtBg+1WJQn0l9i5Qgak2qEXuQQtjZtiw0foyluvKVAPq1Kkan2pX8nz3qJfb8Z7pvidGRv2WCrvPQuDtTDH6XaMw28MhqBHboq/gKVABoXyn/tkFxoDoEpMA"
  Type: "CSeq", content: "0"
  Type: "Audio-Jack-Status", content: "connected; type=analog"
  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
    Apple-Response: K3KV/lrq8MzR65qogDpNSIT5T/pB4VtJ1CZ82yRJ+GBIfhpiTy3iyJjDyaGreUxhLOnyXthnAL4/xd4WCSelT9vHyysCyOaqVdlzdy5haRGiC9A3O6P9PD4oyG7Bsx5IEybbpXJ3E4YOAf3WZARjxFcSCmTuKzt5gJurRivsGfl5vIgb05qJRBAUA9wBcoVqZYwtbfz3QC99DHEEHGliZddI61X5gQBtBg+1WJQn0l9i5Qgak2qEXuQQtjZtiw0foyluvKVAPq1Kkan2pX8nz3qJfb8Z7pvidGRv2WCrvPQuDtTDH6XaMw28MhqBHboq/gKVABoXyn/tkFxoDoEpMA.
    CSeq: 0.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 1.
    Content-Type: application/sdp.
    Content-Length: 589.
RTSP Packet received of type "ANNOUNCE":
  Type: "CSeq", content: "1"
  Type: "Content-Type", content: "application/sdp"
  Type: "Content-Length", content: "589"
RTSP Response:
  Type: "CSeq", content: "1"
  Type: "Audio-Jack-Status", content: "connected; type=analog"
    CSeq: 1.
    Audio-Jack-Status: connected; type=analog.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=55382;timing_port=56323.
    CSeq: 2.
RTSP Packet received of type "SETUP":
  Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=55382;timing_port=56323"
  Type: "CSeq", content: "2"
No User-Agent string found in the SETUP message and no user-supplied latency. Using AirPlay latency of 88200 frames.
RTSP Response:
  Type: "CSeq", content: "2"
  Type: "Audio-Jack-Status", content: "connected; type=analog"
    CSeq: 2.
    Audio-Jack-Status: connected; type=analog.
```
I know the iOS is very old :sweat_smile: but maybe it's an easy fix.

**Comment by flxkrmr** [comment]
Ok, I think I know where the problem is:
The handle_setup() function returns when there is no User-Agent field in the SETUP message by the iPod. Because of this rtsp_take_player(), rtp_setup() and player_play() are not called.
```
      char * ua = msg_get_header(req,"User-Agent");
      if (!ua) {
        debug(1,"No User-Agent string found in the SETUP message and no user-supplied latency. Using AirPlay latency of %d frames.",config.AirPlayLatency);
        return;
      }
```
This return is not present in the current version of shairport-sync, but in version 2.1.12. This is the version, the OpenWrt makefile points to. 
I've deleted the return, but this produced a segmentation fault. Then I tried to change the shairport version to 2.2.1 in the OpenWrt makfile, but now it does not compile anymore. It fails on configuration:
```
checking for POPT... no
configure: error: Package requirements (popt) were not met:

No package 'popt' found
```
This really confuses me as I have the libpopt package enabled and it is also in the makefile dependencies.

Is there a reason why shairport-sync-for-openwrt is still on version 2.1.12?

This issue belongs to the shairport-sync-for-openwrt repository, sorry about that.

**Comment by mikebrady** [comment]
Hi there. Thanks for your interest in Shairport Sync! I think the problem runs deeper – see  https://github.com/lperrin/node_airtunes#airtunes-airplay-raop- . There are basically two versions of the AirTunes protocol, and I'm guessing the old iPod uses the older one, which is incompatible with Shairport Sync.

The `popt` problem is because the version of `libpopt` in the current release of OpenWrt does not include the files needed for `ldconfig` to find it. This has been fixed in `trunk`.

If you go to the development branch of `shairport-sync-for-openwrt`, you'll find a package for the absolutely latest development release of Shairport Sync, which has a number of improvements and which supports a configuration file at `/etc/shairport-sync`. It compiles (and runs!) with OpenWrt `trunk`.

**Comment by flxkrmr** [comment]
Thanks for the quick answer! I read about the AirTunes protocol changes and thought this could be a problem. 
Unfortunately I cannot update to the latest OpenWrt easily, as I added quiet a few changes to my current OpenWrt version and I think these changes cannot be easily merged to the trunk. But I'll have to do that at some point.

**Comment by mikebrady** [comment]
Thanks – that's an interesting-looking device, the Carambola 2.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
