### ISSUE TITLE
Long Titles Shift The Modules position

### ISSUE THREAD

**Issue by dxfan227** [mikebrady/shairport-sync#830]
Hi Mike;

Thanks for all your hard work with this module. I have it all set up and working well. But do have one issue, whenever I choose a song with a longer title.....the entire module shifts to the left. I tried turning off the marquee in the js file but that didnt help the matter. Do you have any ideas?

**Comment by dxfan227** [comment]
sorry i just realized you have nothing to do with the magic mirror module. :(

**Comment by mikebrady** [comment]
No problem. It's nice to see that it's working!

**Comment by mikebrady** [comment]
Closing this, as it's not a Shairport Sync issue.
