### ISSUE TITLE
Crash on start-up (can be fixed by removing Type=forking from systemd unit)

### ISSUE THREAD

**Issue by aaronk6** [mikebrady/shairport-sync#831]
Hi,

shairport-sync 3.2.2 is crashing for me right after start-up.

**Version details:**

```
$ shairport-sync -V
3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc
```

(OS is Raspbian Stretch, shairport-sync installed from **stretch-backports**)

**Syslog:**

```
Apr  5 15:16:36 info-pi systemd[1]: Starting ShairportSync AirTunes receiver...
Apr  5 15:16:36 info-pi shairport-sync[3908]: *** Error in `/usr/bin/shairport-sync': double free or corruption (fasttop): 0x02090380 ***
Apr  5 15:16:36 info-pi systemd[1]: shairport-sync.service: Control process exited, code=killed status=6
```

I’m using the unmodified systemd unit that comes with the Debian package—`/lib/systemd/system/shairport-sync.service`:

```
[Unit]
Description=ShairportSync AirTunes receiver
Documentation=man:shairport-sync(7)
Documentation=file:///usr/share/doc/shairport-sync/README.md.gz
Documentation=https://github.com/mikebrady/shairport-sync
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service

[Service]
Type=forking
Restart=on-failure
EnvironmentFile=-/etc/default/shairport-sync
ExecStart=/usr/bin/shairport-sync --daemon $DAEMON_ARGS
User=shairport-sync
Group=shairport-sync
PIDFile=/run/shairport-sync/shairport-sync.pid

[Install]
WantedBy=multi-user.target
```

**Interestingly, when I remove the line `Type=forking`, it won’t crash.**

With version 2.8.6 (the one [that’s in the stable stretch repository](https://packages.debian.org/stretch/shairport-sync)), it won’t crash, even though `Type=forking` is set.

**Comment by mikebrady** [comment]
Thanks for the report. A new version of Shairport Sync is nearly ready, and is in the `development` branch. It has squashed many bugs. Would you be kind enough to try it out?

**Comment by aaronk6** [comment]
Okay, I think I’ve figured out what’s going on.

The [systemd service file that is used for the Debian package](https://salsa.debian.org/debian/shairport-sync/blob/stretch-backports/debian/shairport-sync.service) starts shairport-sync with the `--daemon` options and sets `Type=forking` which causes the crash for me with version 3.2.2.

Your [systemd service file in this repository](https://github.com/mikebrady/shairport-sync/blob/development/scripts/shairport-sync.service.in) however doesn’t do this, so it won’t crash when using a systemd unit without forking.

Luckily, in version 3.3rc3 (from development branch at bdc9846), the crash seems to be fixed and both options will work fine:

**Forking (Debian install):**

```
Type=forking
ExecStart=/usr/local/bin/shairport-sync --daemon $DAEMON_ARGS
```

**Normal (your method):**

```
ExecStart=/usr/local/bin/shairport-sync
```

**Comment by mikebrady** [comment]
Super, thanks.
