### ISSUE TITLE
Audio drifts after a few seconds - 44,1 kHz with 48 kHz DAC

### ISSUE THREAD

**Issue by microfx** [mikebrady/shairport-sync#833]
Hey!

I am using a 48 kHz DAC with my Raspberry Pi 3b+ to stream audio from my Apple TV 4k or Macbook and at first it looks fine but after a short time I notice that the audio drifts away. So this seems to be a problem with the sample rate conversion. Tried so many .asoundrc configs and nothing seems to fix that. My current .asoundrc looks like this (copied from your "FAQ"): 

```
pcm.!default {
    type plug
    slave.pcm {
        type dmix
        ipc_key 1024
        slave {
            pcm "hw:0"
            rate 48000        # this line is only needed for USB DACs which only su$
            period_time 0
            period_size 1920
            buffer_size 19200
        }
    }
}
```

This was all working fine when I was using volumio - so they know how to do it. Any idea what I could try to solve this?

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync is really designed to drive the output device directly, and can only do accurate synchronisation if it is getting reliable timing information from the device. The sample rate conversion is interposed between Shairport Sync and the output device, so I guess that's where the inaccuracy and drift is coming from.

If you can at all, you should allow Shairport Sync to connected directly with the output device, which needs to be capable of working at 44,100 frames per second.

AFAIK, Volumio actually uses Shairport Sync as its AirPlay device, so why it should work okay in Volumio but not on its own is a mystery to me.

Maybe some other users have more experience in this area?

**Comment by microfx** [comment]
Hey mikebrady, thanks for the quick answer. 

The DAC (a pisound from https://blokas.io/pisound) is only capable to run at sampling rates 48 kHz (and its multiples) unfortunately. 

I forgot to mention that it is a drift between audio / video - if that is unclear to anyone reading this. Tried many .asoundrc configs but the problem is persistent.

**Comment by mikebrady** [comment]
I think it might be best to ask the Volume guys about PulseAudio – I really don't know too much about how they manage it.

That DAC certainly looks nice, and it's a shame it doesn't do 44.1k. I'd be very surprised if the chips they are using would not allow it.

**Comment by microfx** [comment]
Fixed this indeed by using your pulseaudio backend 

I installed all this: 

```
sudo apt-get install -y xmltoman autoconf automake libtool libdaemon-dev libasound2-dev libpopt-dev libconfig-dev avahi-daemon libavahi-client-dev libssl-dev libsoxr-dev libpulse-dev
```

then rebuilt shairport-sync with this command:

```
autoreconf -i -f
./configure --sysconfdir=/etc --with-alsa --with-pa --with-avahi --with-ssl=openssl --with-metadata --with-soxr #--with-systemd 
make
sudo make install
```

**Comment by mikebrady** [comment]
Closing this, as the issue seems to be resolved.
