### ISSUE TITLE
Using Shairport to mimic microphone on raspberry pi 

### ISSUE THREAD

**Issue by hankp46** [mikebrady/shairport-sync#835]
I'm working on a project to issue voice commands to a robot. I can't use a USB mic since car makes too much noise. Attempting to use my IPhone as a mic. Have gotten Shairport working and playing my commands. 
Is there a way to have Shairport mimic microphone  input?
If not, is there a way to save output to a.wav file?
Thanks!

**Comment by mikebrady** [comment]
Thanks for the post. I'm afraid I don't quite understand what your question is. Could you tell us some more please?

**Comment by hankp46** [comment]
Thank you for your reply. First I'm pretty new at this and "learn by example". 
Rather than send audio output to the speaker I want to save it to file.
I think I need to use the "pipe" argument in the config file.
Now need to learn more about pipes and the correct syntax for the pipe argument.

Hope this makes sense.

Thanks again 

Hank Poletto
hpoletto@cfl.rr.com

**Comment by mikebrady** [comment]
Well, you can certainly save audio that comes through Shairport Sync into a file via the usual unix `pipe` or `stdout` methods. Getting audio into Shairport Sync would require an app at the iPhone end. Maybe there is an app that takes the microphone input and send it straight to audio, in which case you might be able to send it to AirPlay and thus to Shairport Sync. However, remember that there is a latency or around two seconds in AirPlay. You can reduce it, but it will be unstable below about 0.25 seconds, I'd guess.

**Comment by hankp46** [comment]
I know you are not suppose to be a tutor but...
I can send  the mic input to Shairpoint and get it to play thru the speaker.

I then added this to the conf file to try to save to a file
stdout =
{
//      name = "/home/pi/testout.raw"; // there is no default name for the
output
};
Rebooted. Once again mic output went to the speakers but not to the file.
I assume my syntax is wrong. Any help would be greatly appreciated it.

**Comment by mikebrady** [comment]
Cool. You need to uncomment the setting — Remove the two `//` symbols. If the program is running automatically from startup, it may have permission problems. Maybe try the `/tmp` directory instead if necessary.

**Comment by hankp46** [comment]
Sorry to bother you again.
This is what i edited:
*sudo nano /usr/local/etc/shairport-sync.conf*
this is what I added:



*stdout ={      name = "/tmp/testout.raw"; // there is no default name for
the output};*
stop shairport
*pi@raspberrypi:~ $ bash
/home/pi/mike/super-simple-raspberry-pi-audio-receiver-install/shScripts/shairportend.sh*
[NEW] Controller B8:27:EB:A3:ED:67 hankphone [default]
[NEW] Device 18:F6:43:C2:5B:64 iPhone
[bluetooth]# discoverable on
[bluetooth]# quit
[DEL] Controller B8:27:EB:A3:ED:67 hankphone [default]
numid=3,iface=MIXER,name='Master Playback Volume'
  ; type=INTEGER,access=rw------,values=2,min=0,max=65536,step=1
  : values=58983,58983
start shairport
 *bash
/home/pi/mike/super-simple-raspberry-pi-audio-receiver-install/shScripts/shairportstart.sh
*
[NEW] Controller B8:27:EB:A3:ED:67 hankphone [default]
[NEW] Device 18:F6:43:C2:5B:64 iPhone
[bluetooth]# discoverable off
[bluetooth]# quit
[DEL] Controller B8:27:EB:A3:ED:67 hankphone [default]
numid=3,iface=MIXER,name='Master Playback Volume'
  ; type=INTEGER,access=rw------,values=2,min=0,max=65536,step=1
  : values=58983,58983
*speak into my Iphone mic.*
*Output comes out of raspberry speaker*
*no /tmp/testout.raw file.*
Thought maybe file needed to exist so created it.
Repeat sequence
Nothing in file.

At a loss on what to do next.

**Comment by mikebrady** [comment]
I’m afraid I can’t make any sense of that at all.  It looks like gobbledegook — perhaps you could try formatting it with [GitHub Markdown](https://guides.github.com/features/mastering-markdown/). 

Anyway, did you set the `output_backend` to `pipe` in the Shairport Sync configuration file?

**Comment by hankp46** [comment]
Hope this is clearer

If I set my config file to 
general =
{
	name = "hankphone"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
    interpolation = "soxr";
        output_backend = "pipe"
}
and
pipe =
{
     name = "/tmp/testout"; // there is no default pipe name for the output
};
The file /tmp/testout gets created but after using the microphone nothing is in the file.

If I set config file to
general =
{
	name = "hankphone"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
    interpolation = "soxr";
        output_backend = "stdout"
}
and
stdout =
{
    name = "/tmp/testout.raw"

};
The file is not created

**Comment by mikebrady** [comment]
Thanks. That's a good bit clearer (and I added a few formatting edits for clarity).

Le me try to clarify what happens:
1. If the pipe you specify (`/tmp/testout` in your example) does not exist, Shairport Sync will create it as a pipe.
2. However, if a file already exists by that name, Shairport Sync will will use the file.

So, depending on whether or note a file already existed with the name you specify, when Shairport Sync is outputting, it will either be outputting to a *pipe* or to a *file*.

If Shairport Sync is outputting to a *file*, it will behave as I think you expect – the file will accumulate the data that is written to it.

However, if Shairport Sync is outputting to a *pipe*, then the pipe will not store data – instead it will accept data only if there is another program reading from it. (And Shairport Sync won't put any data into the pipe unless a reader is taking the data out at the other end.)

So, if you want "file" behaviour, create an empty file before starting Shairport Sync. But if you want "pipe" behaviour, don't create the empty file – instead, allow Shairport Sync to create the pipe and, in another window or program, take output from the other end of the pipe, e.g. in another command line window: `$ cat /tmp/testout > samples.raw`.

If you use `stdout` then output is directed to the standard output, usually the console. You can redirect it in the standard way. For example:
```
$ shairport-sync -o stdout | cat > samples.raw
```

**Comment by hankp46** [comment]
Good news!  Got the output into the file and converted it to a .wav file by
running:
sox -t raw -r 44100 -b 16 -c 1 -L -e signed-integer /tmp/testout.raw
/home/pi/testout.wav

Bad news... very distorted. Sounds like its in slow motion.
Any ideas on how to improve it?

**Comment by mikebrady** [comment]
Shairport Sync outputs interleaved stereo – two channels. You've specified one; that would do it.

**Comment by hankp46** [comment]
That did it. Everything is now working perfectly. Thank you for all your help. Closing
