### ISSUE TITLE
Album Art in AirPlay to ShairPort Stream - How To Access

### ISSUE THREAD

**Issue by DomusDigital** [mikebrady/shairport-sync#836]
We are setting up a system using iPhones running Apple Music AirPlaying to a Raspberry Pi running ShairPoint (via moode, I think) to speakers in the kitchen, and want to direct the album art to an Android panel in the kitchen wall.

Looking at a photo of a Bose AirPlay speaker today, I noticed that it does display album art, so that image must be embedded in the AirPlay/ShairPort stream.

Does anybody know how I might isolate the graphic file in order to send it to the panel?

**Comment by mikebrady** [comment]
Thanks for the post. Is this not the same as #827?

**Comment by idcrook** [comment]
with the great MQTT feature in newly released Version 3.3 of shairport-sync, the PICT metadata can be published to MQTT broker. Once it is available in MQTT, along with other metadata if desired, it is simple to get at the image data.

For it to work, It requires setting up access to an MQTT broker (server) such as `mosquitto` and configuring `shairport-sync` to enable its mqtt metadata support and connect to broker.

I was able to quickly create a simple app that serves webpage with cover art and track info and shared on github, if you'd like to take a look at code examples
  - https://github.com/idcrook/shairport-sync-mqtt-display

Thanks for the MQTT metadata support @mikebrady @tillz !

**Comment by mikebrady** [comment]
@idcrook, that looks intriguing, thanks. I’ll give it a try.

**Comment by idcrook** [comment]
👍 @mikebrady I am by no means an expert in webdev. The CSS styling could be improved with someone that knows what they're doing. The MQTT and socket.io parts in the Flask app are basically from going through their library documentation intro examples. open source FTW!

**Comment by idcrook** [comment]
it's come a long way in a couple days.  the playback buttons now work on the configurable webui.
the client is working well as a webapp launched from iPhone or iPad home screen...
