### ISSUE TITLE
Can I add ALAC support post install?

### ISSUE THREAD

**Issue by superkoira** [mikebrady/shairport-sync#837]
Can I include ALAC support after installing Shairport?

If not, how do I properly uninstall shairport? It is running on RPi 3 B+ with ALSA support.

Another question: Can I delete ~/shairport-sync directory after installing Shairport?

thanks!

**Comment by mikebrady** [comment]
Thanks for the mail. 

If you have built Shairport Sync in the `~/shairport-sync` directory, then`cd` back into it and run the `./configure...` step again, this time including `--with-apple-alac`. You may have to install the ALAC library, but there are [instructions for that too](https://github.com/mikebrady/alac).

Build and install as before – it will overwrite the previous version of Shairport Sync. 

You can delete the `~/shairport-sync` when you're done.

If you want to be really sure you've removed the old `shairport-sync` then use:
```
$ which shairport-sync
``` 
to locate any copies of the application and delete them. You might need superuser privileges to do so.

**Comment by mikebrady** [comment]
Closing this, as the issue has been resolved.
