### ISSUE TITLE
Mono Output Distorted

### ISSUE THREAD

**Issue by hankp46** [mikebrady/shairport-sync#838]
Piping to a file. 
If I set my config to

name = "hankphone"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
interpolation = "soxr";
output_backend = "pipe"
playback_mode = "stereo"
}
and
pipe =
{
name = "/tmp/testout.raw"; // there is no default pipe name for the output
};
File is created
When I convert to a wav file
sox -t raw -r 44100 -b 16 -c 2 -L -e signed-integer /tmp/testout.raw /home/pi/testout.wav
and then play the wav file it comes out perfect.

I then attempted to output a mono file with this config:
name = "hankphone"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
interpolation = "soxr";
output_backend = "pipe"
playback_mode = "mono"
}
Deleted old raw file and created a new one
Run shairport-sync
File is created
Converted to wav file using
sox -t raw -r 44100 -b 16 -c 1 -L -e signed-integer /tmp/testout.raw /home/pi/testout.wav
Playing the wav file outputs very distorted sound.

In my previous post you said
Shairport Sync outputs interleaved stereo – two channels
I thought by changing playback_mode = 'mono" would create 1 channel
Is this a wrong assumption?
Is there any way to create 1 channel (mono)?

**Comment by mikebrady** [comment]
The “mono” output is two-channel mono, so it makes little difference. There is no facilitya in Shairport Sync to get single channel mono. But maybe some programs can convert for you if you pipe the output into them?
