### ISSUE TITLE
Autmatic Switch to HDMI Output

### ISSUE THREAD

**Issue by hankp46** [mikebrady/shairport-sync#839]
Shairport Constantly shifts to HDMI output. If i start a song on my IPhone my Speaker Output goes to HDMI. If i manually change i while the song is running  it starts to play through the 3.5 output. If I exit IPhone and repeat the sequence it once again shifts to HDMI.
Here's the output from Aplay:
 aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

Here's the config file:
};//	output_backend = "alsa"; // Run "shairport-sync -h" to get a list of all output_backends,
alsa =
{
output_device = "hw:0,0"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
//  mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
//  mixer_device = "default"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
//  audio_backend_latency_offset = 0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -4410.
//  audio_backend_buffer_desired_length = 6615; // If set too small, buffer underflow occurs on low-powered machines. Too long and the response times with software mixer become annoying.
//  disable_synchronization = "no"; // Set to "yes" to disable synchronization. Default is "no".
//  period_size = <number>; // Use this optional advanced setting to set the alsa period size near to this value
//  use_mmap_if_available = "yes"; // Use this optional advanced setting to control whether MMAP-based output is used to communicate  with the DAC. Default is "yes"

**Here's part of the log file:
Apr 26 16:45:52 raspberrypi shairport-sync[11791]: PCM handle name = 'hw:0,0'
Apr 26 16:45:52 raspberrypi shairport-sync[11791]: alsa device parameters:
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   access type = MMAP_INTERLEAVED
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   format = 'S16_LE' (Signed 16 bit Little Endian)
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   subformat = 'STD' (Standard)
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   number of channels = 2
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   number of significant bits = 16
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   rate = 44100 frames per second (precisely).
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   period_time = 5804 us (>).
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   period_size = 256 frames (precisely).
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   buffer_time = 743038 us (>).
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   buffer_size = 32768 frames (>).
Apr 26 16:45:52 raspberrypi shairport-sync[11791]:   periods_per_buffer = 128 (precisely).

**Comment by hankp46** [comment]
While working on another project (AlexaPi) I requested Airplay support. It created a shairport-sync config file in another location. When I rebooted shairport-sync was using the new config file and the problem disappeared.  I haven't compared the 2 files yet but thought you would like to know. You can close this issue.

**Comment by mikebrady** [comment]
Sorry to have missed this issue, but glad to see that you've resolved it.
