### ISSUE TITLE
3.3 RC4 crash when I turn off USB DAC

### ISSUE THREAD

**Issue by chuhuanping** [mikebrady/shairport-sync#840]
I turn off USB DAC, connect to shairport-sync in iphone, then click play button. Shairport-sync crashed.

I made a little change in service file, it may restart shairport-sync. I hope that may help.

Restart=always

[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
**Restart=always**
ExecStart=@prefix@/bin/shairport-sync
User=shairport-sync
Group=shairport-sync

[Install]
WantedBy=multi-user.target

**Comment by mikebrady** [comment]
Thanks for the report. Actually this is deliberate – when you try to play to a device that can not be reached, Shairport Sync logs a fatal error message and aborts. I will revise that and maybe get Shairport Sync to abandon the play session instead.
