### ISSUE TITLE
PulseAudio doesn't work in daemon mode

### ISSUE THREAD

**Issue by shawnc722** [mikebrady/shairport-sync#843]
Hi Mike,
First of all, thanks for making this program. I've had it running for a while now and really loved it. Recently I tried to reinstall it with dbus support, which required running in daemon mode, and I've been having no luck. The service starts on boot, as it should, but can't seem to use pa:
```
$ systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-02 14:52:07 EDT; 1min 14s ago
 Main PID: 1033 (shairport-sync)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/shairport-sync.service
           └─1033 /usr/local/bin/shairport-sync

May 02 14:52:07 shawn-eOS systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
May 02 14:52:07 shawn-eOS shairport-sync[1033]: Failed to create secure directory (/run/shairport-sync/.config/pulse): No such file or directory
May 02 14:52:07 shawn-eOS pulseaudio[1039]: [autospawn] core-util.c: Failed to create secure directory (/run/shairport-sync/.config/pulse): No such file or directory
May 02 14:52:07 shawn-eOS pulseaudio[1039]: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
May 02 14:52:07 shawn-eOS pulseaudio[1039]: [pulseaudio] main.c: Failed to acquire autospawn lock
May 02 14:52:07 shawn-eOS shairport-sync[1033]: fatal error: failed to connect to the pulseaudio context -- the error message is "Connection refused".
```
If I run `shairport-sync` manually, everything (except the dbus, obviously) works. I've tried restarting the service through systemctl, which doesn't change anything. Do you have any suggestions?
Thanks

**Comment by mikebrady** [comment]
Thanks for the post. The reason is that, for security reasons, PulseAudio is normally configured as a user service, and not as a system-wide service.

Apparently [you can set it up as a system service](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/), though it is not recommended. I haven’t tried it.

**Comment by shawnc722** [comment]
Okay, I've got it running with alsa now instead. Thanks for the info!

**Comment by mikebrady** [comment]
Closing this, as the issue has been resolved.
