### ISSUE TITLE
Arch Linux/RPi: shairport-sync.conf not being found error

### ISSUE THREAD

**Issue by misterwiggles** [mikebrady/shairport-sync#847]
@mikebrady So I followed you install instructions from way back in 2015 to get an Arch Linux on Raspberry Pi 3B+ install of Shairport-Sync working. The install went fine but the audio never worked. Hours later I think I've determined that the shairport-sync can't find the .conf file. Getting a configuration file cannot be resolved error using the shairport-sync -v command. I'm not a linux guru and most of the help I find doesn't work in Arch. Can you help here by updating your build/install instructions to get this working? Or is there an easy way to update shairport with the correct path to the .conf file after an install? BTW: I am logging into my RPi using the 'alarm' user as referenced in your instructions. And I can see the .conf file in the /etc directory. Your original instructions are here: https://github.com/mikebrady/shairport-sync/issues/168#issuecomment-162313076

It also seems that two instances of SPS are running; one as root and another as the 'alarm' user as referenced in your instructions. This caused me a lot of confusion as it seemed unclear as to which shairport-sync.conf file I should be editing since there are two of them in different directories.

Why Arch? Because I have a Ropieee install for Roon purposes but want Airplay on this RPi. So pretty sure I can make this work if I just get updated install instructions. Thanks!

**Comment by misterwiggles** [comment]
So I looked into your PKGBUILD file that was downloaded as part of the 2015 install commands. The part that seems relevant is:

build() {
  cd shairport-sync
#  git checkout development > /dev/null 2>&1
  autoreconf -i -f
  ./configure --with-alsa --with-avahi --with-ssl=openssl --with-soxr --without-configfiles --prefix="$pkgdir/usr"
  make
}

package() {
  install -D -m644 shairport-sync.service "$pkgdir/usr/lib/systemd/system/shairport-sync.service"
  install -D -m644 shairport-sync.conf "$pkgdir/etc/conf.d/shairport-sync"

For the life of my I can't reconcile how to fix the configuration file can't be resolved error I am getting with the build script variables for config file locations. It's not even clear how I fix this without completely uninstalling SPS and trying again.

**Comment by misterwiggles** [comment]
Update: So I tried uninstalling shairport-sync and rebuilding just to be sure I didn't create any errors. Getting same result. Using the Arch Linux/Rpi install instructions provide by @mikebrady it gives me the following shairport-sync -v output. Note the configuration file can't be found based on whatever Mike's PKGBUILD script is creating:

shairport-sync -v
alsa output device name is "default".
Version: "3.2.2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/home/alarm/shairport-sync-PKGBUILD/pkg/shairport-sync-git/usr/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "MGOfficePiRME".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_hardware_mute is 0.
no special mdns service interface was requested.
configuration file name "/home/alarm/shairport-sync-PKGBUILD/pkg/shairport-sync-git/usr/etc/shairport-sync.conf" can not be resolved.
loudness is 0.
loudness reference level is 0.000000
disable resend requests is off.
diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
Unable to listen on IPv4 port 5000. The error is: "Address already in use".
Unable to listen on IPv6 port 5000. The error is: "Address already in use".
fatal error: Could not establish a service on port 5000 -- program terminating. Is another instance of Shairport Sync running on this device?
Request to shut down all rtsp conversation threads
asking playing threads to stop
[alarm@MGOfficePiRME ~]$ cd /home/alarm/shairport-sync-PKGBUILD/pkg/shairport-sync-git/usr/etc
-bash: cd: /home/alarm/shairport-sync-PKGBUILD/pkg/shairport-sync-git/usr/etc: No such file or directory
[alarm@MGOfficePiRME ~]$

**Comment by misterwiggles** [comment]
Which also explains why the changes I made to the shairport-sync.conf file are being ignored in this output. The .conf file is not being seen by shairport-sync.

**Comment by mikebrady** [comment]
Thanks for the report. I’ll take a look, but it will be a few days...

**Comment by mikebrady** [comment]
Yeah, Shairport Sync will be going to 3.3 soon – it's at Release Candidate stage. As soon as it's ready, I'll update the script.

BTW, I added a little to [this](https://github.com/mikebrady/shairport-sync-PKGBUILD/blob/master/README.md).

**Comment by mikebrady** [comment]
Update – the script has been renamed to [shairport-sync-for-arch-linux](https://github.com/mikebrady/shairport-sync-for-arch-linux).

**Comment by mikebrady** [comment]
Closing this, as the issue has been resolved.
