### ISSUE TITLE
Setting mqtt.port as in config file example does not work

### ISSUE THREAD

**Issue by idcrook** [mikebrady/shairport-sync#854]
Using MQTT with TLS wanted to specify a different mqtt server port, in my case `8883`.
Setting in config file has no effect.
```
mqtt =
{
...
	port = "8883";
...
```

other settings are used, for example (from output with debug level set to 3)

```
mqtt hostname is rpih1, port is 1883.
```

As I was browsing the source code and debugging this, I figured out why. the number in the config file example shouldn't be enclosed in double quotes. I was using the example file `//	port = "1883";`

So I dropped the quotes
```
	port = 8883;
```

and now the MQTT TLS connection works.

```
mqtt hostname is rpih1, port is 8883.
...
[MQTT]: connected
```

I am going to submit a PR that
 1. updates the example file 
 2. updates the source code to be consistent with rest of config file value handling and setting a default value.

```
~/projects/shairport-sync $ echo $(git describe --tags --dirty)
3.3
```

**Comment by mikebrady** [comment]
Many thanks, David. The fixes will be in the next release.
