### ISSUE TITLE
Avahi advertisement no longer works with 3.3 in RoPieee

### ISSUE THREAD

**Issue by spockfish** [mikebrady/shairport-sync#863]
Hi Mike,

Awesome job!

I'm experimenting with including shairport-sync into RoPieee (www.ropieee.org). I've switched from 3.2 to 3.3 and for some reason the advertizement on Avahi stopped working.

What I normally see in the log from avahi is something like this:

```
avahi: service '5136A04150AB@RoPieeeXL [ropieeetouch]' group is registering.
avahi: service '5136A04150AB@RoPieeeXL [ropieeetouch]' successfully added.
```

However, with this new build that's no longer happening. I tried everything, switching between 'avahi' and 'avahi-external' for the mdns_backend parameter, but no luck. 

Any clues?

**Comment by mikebrady** [comment]
Thanks for the kind words. 
On 3.3.1 for me on Raspbian Lite, at verbosity level 1, I get:
```
         0.768125654|avahi: service '2D11D6B582C4@RaspberryPi3BP' successfully added.
```
and at verbosity level 2 I get:
```
         0.002580868|avahi: service '2D11D6B582C4@RaspberryPi3BP' group is registering.
         0.001914623|alsa: delay_and_status using snd_pcm_status_get_delay() to calculate delay
         0.778107113|avahi: service '2D11D6B582C4@RaspberryPi3BP' successfully added.
```
Are you certain Avahi itself is running? Anyway, if you use `avahi-browse` –  part of `avahi-utils`, I think – then you can see what's visible, including what is being advertised, on the device.

**Comment by spockfish** [comment]
That's weird that it works for you. I don't see the messages, and I also don't see anything with avahi-browse. This are my configure settings:

```
--sysconfdir=/etc --with-alsa --with-avahi --with-external-mdns --with-stdout --with-pipe --with-ssl=open
ssl --with-soxr --with-dns_sd --with-pkg-config --with-systemd --with-configfiles --without-libdaemon
```

**Comment by mikebrady** [comment]
Thanks. I have just run up the latest version of Ropieee, and you're right – the messages do not appear. I'm going to see if I can isolate the problem. I did a fair amount of work with Arch Linux recently and it worked well. I'll check that first, and then come back to Ropieee.

**Comment by mikebrady** [comment]
The plot thickens. Before leaving Ropieee, I tried using the "external" method of registering, in which Shairport Sync uses an external command – in this case `avahi-publish-service` – to register the service, and it's not working either. Leaving Shairport Sync behind, the following sample command works properly on Rapsbian, with the response as indicated:
```
$ avahi-publish-service light _coap._udp 5683
Established under name 'light'
```
whereas nothing happens on Ropieee:
```
$ avahi-publish-service light _coap._udp 5683
```
Thus, whatever the problem is, Shairport Sync doesn't seem to be part of it. I suggest you bring the issue to the attention of the Ropieee guys...

**Comment by mikebrady** [comment]
Just installed the Arch Linux on a Raspberry Pi 3B+. Installed Shairport Sync as described [here](https://github.com/mikebrady/shairport-sync-for-arch-linux). Enabled the `avahi-deamon` as a service and started Shairport Sync Everything is peachy.

**Comment by spockfish** [comment]
hehe. ok fine. As I *am* 'the RoPieee guy', its's up to me to figure out what's going on. Still weird that this behavoiur changes when I go back to an older version of Shairport Sync. Anyways, thanks for looking into this!

**Comment by spockfish** [comment]
hmmm... seems something wrong with avahi-daemon for some reason :-(

**Comment by mikebrady** [comment]
Delighted to make your acquaintance! Let me know if I can help, please.

**Comment by spockfish** [comment]
HI Mike,

I think I've located the issue. It seems related to the startup of the Avahi-daemon and bringing up Shairport-Sync. In other words: a timing issue. 

So I'm continuing the search, but for now many thanks for your help and your awesome project. I'm gonna close the issue as this seems to be not an issue with Shairport-Sync itself.

Thanks!

**Comment by mikebrady** [comment]
Thanks Harry. All the best in your endeavours.
