### ISSUE TITLE
Cannot play music from multiple senders

### ISSUE THREAD

**Issue by bedrin** [mikebrady/shairport-sync#866]
Original project allowed me to connect two devices (say iPhone and iPad) and stream music from them simultaneously. It was mixed together.

However with shairport-sync I'm getting "NAME is beling used by someone else." error.

Is it a bug or is it done deliberately ?

**Comment by mikebrady** [comment]
Thanks for the mail. There must be some confusion here – Shairport Sync always allowed just one source at a time, and never allowed mixing. You can set it so that when a new source begins to play, the previous source is dropped, but no mixing, I'm afraid.

**Comment by bedrin** [comment]
Okay, found it - "allow_session_interruption". Thanks a lot!
