### ISSUE TITLE
System crash or something like this with latest version on orange pi

### ISSUE THREAD

**Issue by a-x-** [mikebrady/shairport-sync#871]
after another update since some playing time after another stop-play shairport got weird:
1. a few seconds had not started playing
2. next system crash caused as I can understand ... with my whole stupid-smart-home :-( :-/ :'-) 
3. next I logged into system and find out gpio is broken
4. I restarted a system and everything gonna ok

### versions
- **orange pi**: 4.19.20-sunxi / armbian 5.75 / armv7l
- **shairport-sync**: 3.3.1-OpenSSL-Avahi-ALSA-metadata-sysconfdir:/etc (d91e41d9 Add missing support for S32_LE,,,)

### timing
between: 
18:19:45: stuttering
--:--: stop, resume, touch volume some times
--:--: crash?
18:37:30: stuttering

### log

journalctl (shairport verbosity 3, statistics: true): https://gist.github.com/a-x-/0cc882f6457e8c6d67086db9445a2b19

**Comment by a-x-** [comment]
Part of log (many a "underrun" and "incorrect packets order" reports) 
<img width="1426" alt="Screenshot 2019-06-23 at 21 43 03" src="https://user-images.githubusercontent.com/6201068/59980693-151f8900-9602-11e9-93f5-b717b860e4fe.png">

When I logged it, what I see:
<img width="1426" alt="Screenshot 2019-06-23 at 21 42 04" src="https://user-images.githubusercontent.com/6201068/59980694-16e94c80-9602-11e9-951f-b280d3a2023c.png">

**Comment by a-x-** [comment]
related: #851

**Comment by mikebrady** [comment]
Let's follow this on #851.
