### ISSUE TITLE
Unable to connect using iphone

### ISSUE THREAD

**Issue by qqpp4130** [mikebrady/shairport-sync#876]
setting up the shairport-sync use pulseaudio and avira as back end. Everything runs smoothly but now I cannot connect to the server using iphone. Any ideas? Please request any log, screenshot or material needed. Thanks for all!

**Comment by mikebrady** [comment]
Thanks for the post. I suggest you have a look at #849 for some ideas about troubleshooting the issue.

**Comment by mikebrady** [comment]
Its probably worth remembering that pulseaudio is normally installed as a user-mode daemon and so can not be used without modification as the back end of a system that starts automatically after powering in the machine.
