### ISSUE TITLE
good evening, is it possible to add shairport to homebridge

### ISSUE THREAD

**Issue by belous0ff** [mikebrady/shairport-sync#877]

**Comment by mikebrady** [comment]
Thanks for the question. I am afraid that I have never used homebridge, so I can’t answer the question. Perhaps some other users may be able to help.

**Comment by ruudvdb** [comment]
Homekit and homebridge are for Airplay 2 only, so as long as shairport doesn't support airplay 2 it won't be possible I guess...

**Comment by aleksandryants** [comment]
I have the same question

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, nothing has changed. Shairport Sync supports AirPlay 1 only, so doesn't support HomeKit/Homebridge.

**Comment by iRayanKhan** [comment]
So some new characteristic states were added to HomeKit and now home bridge regarding speakers. While yes you do need to have it use AirPlay 2, there may be a workaround ish.

Is there a way to control shairport using commands like shairport -pause or whatever?
If so I could try to hook up a fake TV or use homebridge-command switches to run commands when the accessory is controlled and pause shairport.

**Comment by ahmadnazirafiq** [comment]
Is it possible to run Shairport server alongside Homebridge instance? Tried to install via Terminal but I keep getting this error:

`E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?`

**Comment by mxkyb** [comment]
It is possible and I have it up and running without a problem. Maybe you forgot to run your apt install as sudo?
