### ISSUE TITLE
Issues with Amazon music app - "silent" playback of every second song

### ISSUE THREAD

**Issue by KlaMa** [mikebrady/shairport-sync#88]
Hello Mike Brady. 
I really love shairport port. Today installed version shairport-sync 2.2.4. Before I used shairport version 1.0. I love the fact that shairport-sync appears to be running more stably, easily allows to change the volume using the hardware mixer, and that now a message is displayed if a second device tries to connect to the same speaker.  I am running Shairport-sync on a Raspberry pi running Raspbian, which is based on Debian Wheeze. 

By upgrading to your fork I was hoping to resolve an issue with the Amazon music app that I use for playing music on my iphone: 
1. While the first song plays correctly to the shairport connected speakers, the next song plays silently, no music can be heard. The next song (song 3) then plays normally with audible music, while the next song (song 4) plays but again, no music can be heard. "Silent" songs can be made audible if the progress slider is moved, but this workaround is to cumbersome to really be of value. I am not sure what could be the problem here. Maybe the next song's sound data arrives to fast for shairport and a brief playback pause could resolve the problem.
2. What is quite striking is that from the perspective of the user interface everything appears to be normal even for those silent songs mentioned before: the song appears to be playing, the progress bar is moving and after the song is finished the next song plays and is audible.Of course I also tried changing the volume when a "silent" song is playing, but that was not the issue. By running also mixer in a window I could see that the loudness was indeed in the mid-range and not 0.
3. It is also noteworthy that similar errors do not occur if using the apple music app, youtube playlists, etc. It therefore appears to be an issue specific to amazon music app. Unfortunately I do not own a genuine airport device so I cannot test that it is an issue that occurs with amazon music in general. Using google, however, I did not find any problem related to silent playing of songs with the genuine apple device and amazon music, though, that's why I would kindly ask you to look into this issue of shairport. 
Best regards,
Klaas

**Comment by mikebrady** [comment]
I'll have a look, sure.

**Comment by mikebrady** [comment]
Still haven't gotten a way to test this, I'm afraid.

**Comment by mikebrady** [comment]
Hi. I still have no way to test this. Is it still happening?

**Comment by mikebrady** [comment]
Gonna close this. Please reopen if there are any developments...

**Comment by mikebrady** [comment]
Hi there. This actually might have been fixed on the latest version -- a long-standing bug that just might have caused this behaviour was fixed. Worth a try, I'd say...
