### ISSUE TITLE
Multi room playback / Airplay 2 

### ISSUE THREAD

**Issue by carlderdritte** [mikebrady/shairport-sync#881]
Hi,
Is their any chance to get it to a stage where I can play music from my iOS device to the Shairport and home pods at the same time? without setting it up on iTunes?

thx a lot

**Comment by mikebrady** [comment]
Thanks for the post. This really depends on iOS. Shairport Sync implements AirPlay 1 and AFAIK iOS will not allow Airplay 1 devices to play in sync with each other or with AirPlay 2 devices.

**Comment by maru3l** [comment]
@carlderdritte There's already an issue about it #535
