### ISSUE TITLE
It takes a long time for my iPhone to discover the AirPlay service

### ISSUE THREAD

**Issue by lihk11** [mikebrady/shairport-sync#884]
It takes quite a long time for my iPhone to discover the AirPlay service, but my mac does not have this problem.

**Comment by mikebrady** [comment]
Thanks for the post. This may be caused by issues with the network, including old router firmware or inappropriate settings. The mechanism for detecting the AirPlay service is the same for all devices.

Can you say what kind of setup you have – you give no details?

**Comment by lihk11** [comment]
@mikebrady  Thanks for your rely and the tool you maintaining, its really useful! 
Is it possible that too many(about 50) devices under the same router may slow down the detecting process?

**Comment by mikebrady** [comment]
To be honest, I don't know for sure, but I doubt it. I do know that implementing something like multicast, which Bonjour/ZeroConf relies on, can be complex on WiFi networks, but I haven't really tracked the issue.
