### ISSUE TITLE
start/Stop service from python script ?

### ISSUE THREAD

**Issue by TGWC** [mikebrady/shairport-sync#886]
Hi,

I need to start/stop the service via a python script. How to do it?

**Comment by krazbali** [comment]
Hi,

you can  run the start/stop commands from python with `os.system()`

`import os

#to start service:
os.system('sudo service shairport-sync start')

#to stop service:
os.system('sudo service shairport-sync stop')`

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
