### ISSUE TITLE
Shairport-Sync with LED Visualisations

### ISSUE THREAD

**Issue by NickSutton** [mikebrady/shairport-sync#889]
Hi Mike,
Long time user of Shairport-sync and very much following the discussion over Airplay2. In the meantime I’m looking to add some bells and whistles to an older project that uses Shairport-sync. I’d like to add sound reactive LEDs to my speaker set up.

Here’s the Git: https://github.com/scottlawsonbc/audio-reactive-led-strip
With a RPi, i’m looking to (physically) pipe the audio output to my speakers using Shairport (working great currently) then, using a splitter, send audio back to the mic input of a USB sound card. My current speaker setup is via an IQaudio HAT as the default output device.

The USB sound card working as an input device is required for the visualisation code. However, when I run the visualisation software Shairport craps out and becomes unresponsive.

Is there a way I can find out what’s upsetting Shairport-sync?

Thanks

**Comment by mikebrady** [comment]
Thanks for the post, Nick. I'd say the first thing to do would be to raise the log verbosity and see if there are any clues there. I suggest setting it the `log_verbosiry` in the `diagnostics` section of the configuration file to `2` initially – that is chatty but not excessive. Then restart Shairport Sync and see if anything interesting is logged.

**Comment by NickSutton** [comment]
Hi Mike,
I alerted the `log_verbosity` As recommended then tried to run the script for the audio visualisation. Shairport stopped playing and dropped this into `journalctl`:


`Aug 10 16:24:54 piRadio shairport-sync[1091]:          5.213165204|alsa: underrun while writing 352 samples to alsa device.
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.034763563|Large negative sync error: -8606 with should_be_frame_32 of 3661016918, nt of 366093
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.000817651|Play a silence of 8606 frames.
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.000213436|alsa: device status returns fault status -32 and SND_PCM_STATE_* 3  for play.
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.005616316|alsa: underrun while writing 352 samples to alsa device.
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.070971960|Player: packets out of sequence: expected: 7183, got: 7192, with ab_read: 7193 and a
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.024885246|Large negative sync error: -8534 with should_be_frame_32 of 3661021438, nt of 366094
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.001645874|Play a silence of 8534 frames.
Aug 10 16:24:54 piRadio shairport-sync[1091]:          0.075885156|Player: packets out of sequence: expected: 7196, got: 7205, with ab_read: 7206 and a
Aug 10 16:25:09 piRadio shairport-sync[1091]:         14.569730960|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:25:29 piRadio shairport-sync[1091]:         19.930946941|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:25:49 piRadio shairport-sync[1091]:         19.979518380|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:26:09 piRadio shairport-sync[1091]:         19.979709816|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:26:28 piRadio shairport-sync[1091]:         19.949558524|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:26:48 piRadio shairport-sync[1091]:         19.913941037|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:27:08 piRadio shairport-sync[1091]:         19.979239947|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:27:28 piRadio shairport-sync[1091]:         19.990468615|Packet reception interval stats: mean, standard deviation and max for the last 2,500
Aug 10 16:27:48 piRadio shairport-sync[1091]:         19.920450847|Packet reception interval stats: mean, standard deviation and max for the last 2,500
`

Does that mean much to you? I’ve also logged my issue on the visualisation git here, if that’s any help: [https://github.com/scottlawsonbc/audio-reactive-led-strip/issues/226](url)

**Comment by mikebrady** [comment]
Hi Nick. The log looks pretty normal to me, apart from a few glitches at the start. It doesn’t look as if Shairport Sync is misbehaving.

Notice that I edited the message for clarity. I suggest you do the same editing on your other message as it’s difficult to read the diagnostics as it stands.

One other little thing is that the log has been truncated — the right-hand end of each line of the reception interval stats is missing.

**Comment by NickSutton** [comment]
Hi Mike, thanks for looking, that’s reassuring at least!

I wonder then if the visualisation software is acquiring the audio out or something similar. If shairport is staying up, it’s not playing any audio.

Did you just manually edit the doc? I posted from iPad so thought it just looked crappy to me. Sorry about that.

Cheers,
Nick

On 11 Aug 2019, at 07:15, Mike Brady <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Nick. The log looks pretty normal to me, apart from a few glitches at the start. It doesn’t look as if Shairport Sync is misbehaving.

Notice that I edited the message for clarity. I suggest you do the same editing on your other message as it’s difficult to read the diagnostics as it stands.

One other little thing is that the log has been truncated — the right-hand end of each line of the reception interval stats is missing.

**Comment by mikebrady** [comment]
> I wonder then if the visualisation software is acquiring the audio out or something similar. If shairport is staying up, it’s not playing any audio.

Hmm, I'm afraid I can't really tell, Nick.

> Did you just manually edit the doc? I posted from iPad so thought it just looked crappy to me.

Yeah, I just changed how the log was quoted – there are guides to using markdown for formatting, e.g. https://guides.github.com/features/mastering-markdown.

**Comment by NickSutton** [comment]
Ok, so re-tested and shairport is working fine! But I do have a follow up question... Is there a parameter to send the audio to a non-default sound card?

For the visualisation software to work, the default sound card apparently must be a USB device.. The USB device i have is a simple mic & speaker USB card, but obviously this requires the audio to come from the USB sound card which is crappy and I’d need it to go via the IQAudio HAT I’ve got! 

I’ve checked various forums and I’ve not found a way to specify a default mic and default audio out, so hoping the flexible configuration of Shairport can help me out!?

**Comment by mikebrady** [comment]
Hi Nick. If I understand your query correctly, then yes, you can easily get Shairport Sync to direct the audio to a non-default output. If you enter:
```
$ shairport-sync -h
```
then somewhere near the end of the help text there is a list of the available output devices, all beginning with `hw:...`. Just use the appropriate one of those as the output device in the settings file.

**Comment by NickSutton** [comment]
Got that sorted, shairport-sync is so flexible!

However, the visualization software is still pinching the audio for some reason, even though it’s only got a USB mic now. I’ve opened a stack exchange post so will try over there.

Thanks for your help!

On 14 Aug 2019, at 22:13, Mike Brady <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Nick. If I understand your query correctly, then yes, you can easily get Shairport Sync to direct the audio to a non-default output. If you enter:

$ shairport-sync -h


then somewhere near the end of the help text there is a list of the available output devices, all beginning with hw:.... Just use the appropriate one of those as the output device in the settings file.

**Comment by ruudvdb** [comment]
> With a RPi, i’m looking to (physically) pipe the audio output to my speakers using Shairport (working great currently) then, using a splitter, send audio back to the mic input of a USB sound card. 

So you transfer music from your phone (airplay) to shairport sync and then you split the output from shairport sync to 1) a rPi hat and 2) a virtual input (mic)?

How did you do that?

**Comment by NickSutton** [comment]
> > With a RPi, i’m looking to (physically) pipe the audio output to my speakers using Shairport (working great currently) then, using a splitter, send audio back to the mic input of a USB sound card.
> 
> So you transfer music from your phone (airplay) to shairport sync and then you split the output from shairport sync to 1) a rPi hat and 2) a virtual input (mic)?
> 
> How did you do that?

That’s the bit I’m struggling with. I’m hoping I can use the shairport-sync configuration file to force the audio to the HAT and set the OS default sound card to a virtual input.
