### ISSUE TITLE
Possibility to reduce to zero the volume

### ISSUE THREAD

**Issue by sasagr** [mikebrady/shairport-sync#892]
Hi. I have setup a raspberry pi 3 and it connected to my old Bose Soundock II. I used the suggested settings for the raspberry but I noticed a low noise when I m not air playing. This is due to the normal level of the PCM volume that I set to around 68. I would prefer not to go below this volume, in order to cancel the noise, so I have enough room to increase it with my iPhone. Maybe there is some setting I m missing that switch or reduce the volume when I m not playing and restore it when I start playing?

Pls let me know
Thanks

**Comment by sasagr** [comment]
I have discovered that the Bose SDII when connected to AUX, it goes to sleep after 20min of inactivity so eventually the noise disappers on its own. The only inconvenience it is that when I start to airplay again I need to manually bring up the volume in the bose again

**Comment by bedrin** [comment]
I guess that is because of shitty default audio output on Raspberry

**Comment by mikebrady** [comment]
Yes, it would be interesting to know how you are connecting the Raspberry Pi to the Bose – are you taking output from the Pi's built-in audio output jack and sending it in to the Bose? If so, then @bedrin's observation holds – the quality of the Pi's built-in audio output is poor.

The solution would be to buy an alternative audio output device. An inexpensive Linux-compatible USB sound card would be a big improvement. A slightly more expensive purpose-built DAC – from IQaudIO or Pimoroni among others – would be much better.

**Comment by sasagr** [comment]
Yes, the connection is from the 3.5mm jack. I was thinking eventually to an Airport Express 2. Not sure if this would be relatively the best

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
