### ISSUE TITLE
PCM mixer with disconnected DAC

### ISSUE THREAD

**Issue by Aridor2006** [mikebrady/shairport-sync#896]
Hi,
Is there a way to use the PCM mixer with a USB DAC that is sometimes turned off?
I have the following setting in the config file:
mixer_control_name = "PCM";
This works as long as the DAC is turned on. Once it is turned off though, I get the error: "fatal error: Failed to attach mixer", which it never recovers from.

Version: 3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc

Thanks!

**Comment by Aridor2006** [comment]
I made some progress on this. After upgrading to current master, the issue seems mostly gone.
It doesn't fatal anymore and recovers fine when the audio device is disconnected. 

The only issue left is when the audio device is not present during the first time streaming after startup. This causes the volume to be really low until restarting the application.
```
         0.000133749|loudness is 0.
         0.000350571|loudness reference level is -20.000000
         0.976434972|avahi: service 'AF31192A3A11@Raspberrypi' successfully added.
         0.527603791|"soxr" interpolation has been chosen.
         6.364890953|Connection 1: SETUP DACP-ID "1181ACD6D3601957" from fe80::1c5d:91c:52b9:e66f to fe80::ac59:647:d321:9d22 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
ALSA lib confmisc.c:767:(parse_card) cannot find card '1'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
         0.019915713|*warning: the alsa output_device "default" can not be found.
         0.006646939|Failed to attach mixer
```

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync wasn’t really designed for a dynamic environment. At present, it checks the status of the mixer at startup. If it isn’t there, it issues a warning and never tries to access the mixer again. One could imagine a situation where it would do a full check every time it set or changed the volume level, but it might take some time to do that. Meantime, maybe you could use the `amixer` or the `alsamixer` commands to set the mixer’s level directly.
