### ISSUE TITLE
Ignoring volume up/down and instead forwarding the data

### ISSUE THREAD

**Issue by jespernasman** [mikebrady/shairport-sync#900]
My amplifier has a serial port with which I can control the volume and some other things from a raspberry pi that I've connected to it. 
I'd like to set the volume to a constant on the raspberry pi (`ignore_volume_control`?) and instead pass the volume up/down to the serial port, sort of like `run_this_when_volume_is_set ` but passing "up"/"down" instead of the volume itself. 
I'm not very familiar with C, I've been digging around in the code but can't seem to find where it actually parses the input from the client, would it be feasible to just send the up/down commands to the serial port from there? 
Thanks

**Comment by mikebrady** [comment]
Thanks for the interesting post. It would be quite a piece of work to add that up/down stuff to Shairport Sync itself – I really wouldn't advise it.

An alternative would be to write a `run_this_when_volume_is_set` script that recorded the previous volume, (if any), say, in a file in the `/tmp` directory and then use it to decide whether the new volume was up or down...

**Comment by jespernasman** [comment]
I thought I had it working by making shairport-sync call a python script which stores the previous volume in a text file and then compares it to the argument provided, so that I would know whether to increase or decrease the volume. 
But I then realied that the client doesn't send anything if you increase the volume while it's at max, or decrease the volume while it's at min, which kind of defeats the porpose since I would anyway be limited by the number of volume steps on the client (10 or something on iOS), and then I might as well just control the volume from shairport. I wanted to be able to utilize the entire volume range on the amplifier, with steps of 0.5dB. I guess there's not much to do about that since there's no way I can change how iTunes behaves.

I appreciate the input though!

**Comment by mikebrady** [comment]
That's exactly the problem, I'm afraid, so I agree – there isn't much that can be done about it.

**Comment by noelhibbard** [comment]
I have a receiver that only has IR input so I can't command it to be at a specific volume. I can only send Vol+/-. I ran into the same problem you have where the iOS client doesn't send the commands once it's reached max or min. Such a bummer but out of Mike's control.

**Comment by mikeszila** [comment]
> That's exactly the problem, I'm afraid, so I agree – there isn't much that can be done about it.

I've been searching around trying to find a way to get more then 16 steps of volume control.  Is there any way possible?  Some event buried deep in the code?

**Comment by noelhibbard** [comment]
> 
> I've been searching around trying to find a way to get more then 16 steps of volume control. Is there any way possible? Some event buried deep in the code?

It's only limited so 16 steps if using the hardware vol buttons on the phone and there is no way around that. If you use a vol slider with your finger you get much more resolution. Some apps have their own vol sliders which span the whole screen which give good resolution but the best global vol slider I've found is by long pressing the volume in the control center.

**Comment by mikebrady** [comment]
@noelhibbard @mikeszila, some good news: it turns out that there is indeed a command that allows the control of volume directly – I came across it last week. See [here](https://github.com/ejurgensen/forked-daapd/issues/202). It is incorporated in the latest update on the `development` branch.

**Comment by jespernasman** [comment]
So I finally had time to look at the possibility of controlling the AirPlay volume, and this now actually works the way I wanted it to!

`if python -c "exit(0 if $1 == -5.0 else 1)"`
`then`
`    exit 1`
`fi`

`if python -c "exit(0 if $1 < -5.0 else 1)"`
`then`
`    /bin/bash /home/pi/scripts/voldown.sh`
`else`
`    /bin/bash /home/pi/scripts/volup.sh`
`fi`

/bin/bash /home/pi/scripts/set_airplay_volume.sh -5.0`

Whenever the volume changes, I check if it's more or less than -5.0, which is the "locked" AirPlay volume, and then set the volume on my amplifier accordingly, and set the AirPlay volume to -5.0 again. I also set the AirPlay volume to -5.0 on `run_this_before_entering_active_state` to make sure it works from the start. 

There's one small problem though - `run_this_when_volume_is_set` is always run twice when I change the volume on my phone (using the physical buttons), and the second time the volume received by the script is -5.0 and that's why I'm running the first if statement, and this makes changing the volume a big sluggish. @mikebrady is this intentional, and is there any way to prevent it?

Another small issue is that AirPlay volume very briefly increases or decreases when I change it on my phone, since it doesn't reset to -5.0 instantly, which makes the volume "wobbly". But I doubt there's anything to do about that. I considered `ignore_volume_control`, but locking it at 100% volume will make it impossible to increase the volume.
