### ISSUE TITLE
Regression in providing volume metadata with ignore_volume_control

### ISSUE THREAD

**Issue by jorbas** [mikebrady/shairport-sync#903]
Previously, volume metadata would still be sent even if configured to ignore volume control. 

Now, no volume metadata is sent if configured to ignore volume control.

I believe [this](https://github.com/mikebrady/shairport-sync/commit/c5ff0dfed0d11605d75c4795ab059e903fa42c02) commit broke it by adding a check that `config.ignore_volume_control == 0` _around_ the code which outputs volume metadata. You can see that inside this conditional block, there is a check that `config.ignore_volume_control == 1`, which _cannot_ be true as it is in a block which asserted it was `0`!

**Comment by mikebrady** [comment]
Thanks for the post — let me check.

**Comment by mikebrady** [comment]
Yes, you are right, and your diagnosis was correct too, thanks. I've fixed the problem and pushed an update into the `development` branch. Many thanks.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
