### ISSUE TITLE
shairport-sync fails to run with system.d, runs perfectly as deamon

### ISSUE THREAD

**Issue by kspeeckaert** [mikebrady/shairport-sync#905]
I've installed Shairport-sync on my Raspberryi PI 3 (runnin Raspbian Buster) using the apt package (`sudo apt install shairport-sync`), following the instructions in [this guide](https://gist.github.com/bmweiner/f80e7aaeca5bcee1db46e56914b415fa).

Everything works when I run start the deamon from the commandline:

```
pi@raspberrypi:~ $ sudo shairport-sync -d 
free(): double free detected in tcache 2
Aborted
```

However, when I try to use `sudo systemctl start shairport-sync.service` (or when it starts at bootup), it always fails with the following output:

```
Job for shairport-sync.service failed because a fatal signal was delivered to the control process.
See "systemctl status shairport-sync.service" and "journalctl -xe" for details.
```

Running the `status` command, returns:

```
systemctl status shairport-sync.service
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sun 2019-09-15 14:05:06 CEST; 34s ago
     Docs: man:shairport-sync(7)
           file:///usr/share/doc/shairport-sync/README.md.gz
           https://github.com/mikebrady/shairport-sync
  Process: 1564 ExecStart=/usr/bin/shairport-sync --daemon $DAEMON_ARGS (code=killed, signal=ABRT)

Sep 15 14:05:06 raspberrypi systemd[1]: shairport-sync.service: Unit entered failed state.
Sep 15 14:05:06 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'signal'.
Sep 15 14:05:06 raspberrypi systemd[1]: shairport-sync.service: Service hold-off time over, scheduling restart.
Sep 15 14:05:06 raspberrypi systemd[1]: Stopped ShairportSync AirTunes receiver.
Sep 15 14:05:06 raspberrypi systemd[1]: shairport-sync.service: Start request repeated too quickly.
Sep 15 14:05:06 raspberrypi systemd[1]: Failed to start ShairportSync AirTunes receiver.
Sep 15 14:05:06 raspberrypi systemd[1]: shairport-sync.service: Unit entered failed state.
Sep 15 14:05:06 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'signal'.
```

This is my `/lib/systemd/system/shairport-sync.service` file:

```
[Unit]
Description=ShairportSync AirTunes receiver
Documentation=man:shairport-sync(7)
Documentation=file:///usr/share/doc/shairport-sync/README.md.gz
Documentation=https://github.com/mikebrady/shairport-sync
After=sound.target
#Requires=avahi-daemon.service
#After=avahi-daemon.service

[Service]
Type=forking
Restart=on-failure
EnvironmentFile=-/etc/default/shairport-sync
ExecStart=/usr/bin/shairport-sync --daemon $DAEMON_ARGS
User=pi
Group=nogroup
PIDFile=/var/run/shairport-sync/shairport-sync.pid

[Install]
WantedBy=multi-user.target
```

I'm currently running ShairportSync by starting it once, manually, as a deamon process. The RaspberryPi isn't restarted unless absolutely necessary, so it's an acceptable workaround. But if anyone could point me in the right direction, I'd be very grateful. Thank you!

**Comment by mikebrady** [comment]
Thanks for the post. The crash in Shairport Sync _may_ have been fixed in the last few updates, so if you would pull the latest version and switch to the `development` branch, recompile and reinstall it, you should get further. To do this, just before the `$ autoreconf -fi` step, execute the command:

```
$ git checkout development
```
Please let us know how you do.

**Comment by kspeeckaert** [comment]
Hi Mike,

Thanks very much for the feedback. Alas, due to an issue at my end (completely unrelated to ShaireportSync), I'm getting error messages when I try to run `autoreconf -fi`. I got the same thing when I tried to install the package from source earlier (on the `master` branch), so it's definitely to do with me.

Just FYI, this is the error:

```
$ autoreconf -fi
Can't locate File/stat.pm in @INC (you may need to install the File::stat module) (@INC contains: /usr/share/autoconf /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
Compilation failed in require at /usr/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /usr/bin/autoreconf line 42.
```

**Comment by mikebrady** [comment]
Thanks for the update. It seems as if some of the build tools are not installed or not installed properly. The instructions you refer to do not make it clear that the installation of the tools should be while in the super user (“root”) mode. If you check the tools installation on the [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) and take note of what must be done in the super user mode, perhaps it might help.

**Comment by mikebrady** [comment]
Update – looking at this again, there are a number of issues:
1. By using `$sudo apt install shairport-sync` you are installing Shairport Sync. That's fine as far as it goes, but the version is truly ancient – 2.8.6. For reference, the current version is 3.3.2. Many serious bugs have been removed since 2.8.6.
2. By following [that guide](https://gist.github.com/bmweiner/f80e7aaeca5bcee1db46e56914b415fa), you would be installing another version of Shairport Sync. The guide make this far more complicated than it needs to be and if successful, you would then end up with two copies of Shairport Sync in your system. Given that the `$ autoreconf -fi` step didn't work, I guess that you did not complete the installation according to the guide.

My suggestion would be to start over and follow [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) to install Shairport Sync, except use the following as the contents of the configuration file `/etc/shairport-sync.conf`:
```
general = {
  name = "Sonos";
  interpolation = "basic";
};
```
Then follow that guide, skipping over the Shairport Sync section.

**Comment by kspeeckaert** [comment]
Thanks for taking the time to look into this again. Using the (very clear) instructions in [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md), everything worked like a charm.

The only issue I ran into, was when running `systemctl enable shairport-sync`. I got the error:

```
sudo systemctl enable shairport-sync
Synchronizing state of shairport-sync.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable shairport-sync
Failed to enable unit: Unit file /etc/systemd/system/shairport-sync.service is masked.
Failed to enable unit: Unit file /etc/systemd/system/shairport-sync.service is masked.
```

I followed [these instructions](https://blog.ruanbekker.com/blog/2017/12/09/unmask-a-masked-service-in-systemd/) (basically running `sudo rm /etc/systemd/system/shairport-sync.service`) and then tried again.

The version that I had installed through apt was 3.2.2-1, by the way.

Thanks again!

**Comment by mikebrady** [comment]
Thanks for the update. Just to be clear, am I right to assume that Shairport Sync is working properly now?

**Comment by kspeeckaert** [comment]
Yes, everything is working perfectly now. No issues anymore. 😊

**Comment by mikebrady** [comment]
I'll close this issues now, as it seems to be finished.
