### ISSUE TITLE
mqtt client disconnects and metadata stops working with mosquitto release 1.6.6

### ISSUE THREAD

**Issue by idcrook** [mikebrady/shairport-sync#906]
`mosquitto` 1.6.6 was just released.

after upgrading mosquitto MQTT packages (raspbian stretch, packages from repo.mosquitto.org), noticed shairport-sync MQTT stopped working. 

After various lines of troubleshooting (checking client configs, broker config, rebuilding shairport-sync (on `master` branch BTW)), determined that could only get it working again by downgrading `libmosquitto1`. Downgrading the broker itself was insufficient `sudo apt-get install mosquitto=1.6.4-0mosquitto1~stretch1`

So I was able to use the following "workaround":

```
sudo apt-get install libmosquitto1=1.6.4-0mosquitto1~stretch1
```

Since `shairport-sync` relies on `libmosquitto` for its MQTT client functionality, the latest client libs would appear to be suspect.

#### repo.mosquitto.org info
```
cat /etc/apt/sources.list.d/mosquitto-stretch.list
deb https://repo.mosquitto.org/debian stretch main
```

#### what working log level 3 pattern looks like

**libmosquitto 1.6.4**
```
Sep 18 19:57:39 rpih1 shairport-sync[6287]:          0.000372656|Initialising MQTT
Sep 18 19:57:39 rpih1 shairport-sync[6287]:          0.008958367|Client Basement Speakers rpih1 sending CONNECT
Sep 18 19:57:39 rpih1 shairport-sync[6287]:          0.000476041|Client Basement Speakers rpih1 received CONNACK (0)
Sep 18 19:57:39 rpih1 shairport-sync[6287]:          0.000081458|[MQTT]: connected
```

with **libmosquitto 1.6.6**, a CONNACK never shows up in the log, and eventually the broker reports client timeout/disconnect, with shairport-sync reporting the following around metadata updates:

```
[MQTT]: Client not connected, skipping metadata handling
```

**Comment by mikebrady** [comment]
Thanks for the report. I wonder if @tillz might have a view on it. Meantime, there have been some bug fixes on the `development` branch, and, although none seem relevant, it might be worth updating to it anyway. If any fixes are needed, they will appear first on the `development` branch.

**Comment by tillz** [comment]
I had a look at this and found out that either there's an issue with libmosquitto 1.6.6, or I've missed a fundamental part of mosquittos documentation. As I've double checked the code and tried again with both versions with a minimal example without success, I've opened an [issue](https://github.com/eclipse/mosquitto/issues/1415).

**Comment by mikebrady** [comment]
Many thanks, Till.

**Comment by idcrook** [comment]
Verified that MQTT support is now working again with libmosquitto1 `1.6.7` just released.

On my raspbian stretch:
Version: `1.6.7-0mosquitto1~stretch1`

Closing.
