### ISSUE TITLE
shairplay-sync in raspberry question

### ISSUE THREAD

**Issue by yort16** [mikebrady/shairport-sync#91]
more or less i am a newbie to linux programming.  my curiosity may get me into trouble but im learning as i go.  i am interested in the shairport functionality and i have followed the instructions to the best of my abilities on the github site.  i tried osmc but i can't vnc serve or remote desktop with this os installed and moreover id like more control of the finer points.  that being said, if i wanted airplay id buy airplay.  i currently have a raspberry pi 2 with wheezy debian installed and updated.  with osmc installed i did see my iphone 5 (v 8.3) and ipad 3 (v 8.2) viewable in the interface and it was functional.  below are the errors given when "sudo make install" was initiated.
________________________________________________
Makefile:369: recipe for target 'shairport-sync' failed

make[2]: *** [shairport-sync] Error 1

make[2]: Leaving directory '/home/pi/shairport-sync'

Makefile:419: recipe for target 'all-recursive' failed

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory '/home/pi/shairport-sync'

Makefile:275: recipe for target 'all' failed

make: *** [all] Error 2

pi@raspberrypi ~/shairport-sync$
_____________________________________
as a side note i opted out of "apt-get install libsoxr-dev"
any help is greatly appreciated.  i know im in over my head but im trying to learn.  
thank you for your time.

**Comment by mikebrady** [comment]
Hi there, and thanks for your interest in Shairport Sync. I guess you should got ahead and do the `apt-get install libsoxr-dev` and try the build again. Even if you build in the libsoxr support, you are not forced to use it.

**Comment by jonasschnelli** [comment]
It's `sudo apt-get install libsox-dev`

**Comment by jonasschnelli** [comment]
Sorry. This was wrong.

**Comment by yort16** [comment]
1.  im a bonehead.  id didn't even notice that you (Mike Brady) state that libsoxr is not available for rasbian, which i am currently running.  i did start from scratch, left out libsoxr and managed to not receive any errors during the install process.
2. because im a bonehead im not sure if shairport-sync is running or not.  its not appearing on any of my devices.  when i attempt to execute the following command:
pi@raspberrypi ~/shairport-sync $ shairport-sync -d -a "test" -- -d hw:0 -t hardware -c PCM

i get the following error:
Process 2739 died: No such process; trying to remove PID file. (/var/run/shairport-sync.pid)
Daemon returned 2 as return value.

as always your help is greatly appreciated.

cheers,

**Comment by mikebrady** [comment]
You're nearly there. Try:
```
sudo shairport-sync -d -a "test" -- -d hw:0 -t hardware -c PCM
```
The thing is, for Shairport Sync to run as a deamon (`-d`) in the background, it has to have root permission – that's probably what's causing the (rather cryptic!) error message.

I say "nearly there" because, while this should work, giving you sound through the Raspberry Pi's headphone jack, the sound quality will be poor. If you want decent sound quality, you'll need to use a better output device – even a cheap $5 USB DAC: see https://github.com/mikebrady/shairport-sync/issues/92 for a thread about that.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
