### ISSUE TITLE
Volume not resumed after phone call

### ISSUE THREAD

**Issue by hunhejj** [mikebrady/shairport-sync#910]
I am running shairport-sync on a Raspberry Pi 4 and streaming music over AirPlay from an iPhone. Whenever I receive a call, the music is muted as expected, however after I finish the call, the volume does not resume to the same state before the call. Rather it stays at a low level (maybe resets to a constant predefined volume?).

Not sure if this is a bug on shairport-sync's side but it is quite annoying to reset the volume every time. Am I missing something?

**Comment by mikebrady** [comment]
Hmm, haven't noticed this – let me try to reproduce it. Could you post your `alsa` group settings please?

**Comment by mikebrady** [comment]
Also, it would be useful if you could post the version of Shairport Sync. Enter:
```
$ shairport-sync -V
```
to get a response  which might look something like this:
```
3.3.2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

```

**Comment by mikebrady** [comment]
I just tried this out, and it looks like an iOS bug, because after the call ends and the music continues, the volume setting on the phone has been reduced. I'll need to check with other devices, but it looks like an iOS bug so far...

**Comment by mikebrady** [comment]
Update – it also happens with genuine Apple equipment, so it really looks like an iOS bug...

**Comment by hunhejj** [comment]
By genuine Apple equipment you mean an AppleTV / any other officially supported AirPlay device? Great that you have one in stock so you could test it! Too bad that it is an iOS bug though...

**Comment by mikebrady** [comment]
It was tested on a second-generation Airport Express, the device it's meant to be emulating. A check will be made on a second-generation Apple TV later today. If the bug is indeed an iOS bug, I'd be fairly confident it will be fixed by Apple – they are usually pretty good about attention to detail.

**Comment by mikebrady** [comment]
[Update] The same behaviour is apparent when outputting to a second generation Apple TV, so it looks almost definitely to be an iOS bug.

**Comment by hunhejj** [comment]
Thanks again for investigating as I don't have access to an Apple TV. As it seems to be an iOS bug, I will close this issue.

**Comment by hunhejj** [comment]
@mikebrady I reported the bug to Apple, but they asked me to provide a syslog from both the iOS device AND the AirPlay device. As I have no genuine Apple AirPlay equipment, can you maybe report the bug to Apple (or alternatively send me some syslog files that I can upload to the Feedback Assistant)?
