### ISSUE TITLE
Separate volume controls 

### ISSUE THREAD

**Issue by agneevX** [mikebrady/shairport-sync#911]
Hi,

I was wondering if it's possible to isolate the iOS volume control from `alsamixer`.
What I'm hoping for is max volume in `alsamixer` and then adjust volume on the phone.

Thanks. 

```
alsa =
{
        output_device = "hw:0"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
        mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
```

**Comment by mikebrady** [comment]
Thanks for the post. Yes, if I understand your question properly, it is possible to prevent iOS from altering the volume set by `alsamixer`. All you have to do is omit the mixer control name.

**Comment by agneevX** [comment]
I've commented that out. That won't affect the functionality or the quality of the output, right?

**Comment by mikebrady** [comment]
What happens is that, since Shairport Sync will not now be using a hardware mixer to set the volume, it uses software instead. It sounds fine – it has a 96 dB range and uses dithering.

**Comment by agneevX** [comment]
Hmm ok. Is it just my speaker or does the changing the volume when it's below, say 60% is almost unnoticeable?

**Comment by mikebrady** [comment]
Are you on a Raspberry Pi, using the built-in DAC? If so, only the top 50 or 60 dB of the hardware mixer range are usable – see [here](https://github.com/mikebrady/shairport-sync/blob/master/README.md#configuring-shairport-sync).

**Comment by agneevX** [comment]
Uhhh I'm not sure.

Part of the config:
```
alsa =
{
        output_device = "hw:0"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
        mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
```

**Comment by mikebrady** [comment]
It's really pretty simple:
1. Are you using a Raspberry Pi?
2. Are you listing to the output of the built-in audio jack?
If the answer to both is yes, then you are using the built-in DAC.
