### ISSUE TITLE
Alternative Sample Rate Support for Jack Audio

### ISSUE THREAD

**Issue by jmichaelbarker** [mikebrady/shairport-sync#912]
I'm running into an issue using shairport-sync with a jack audio server backend; specifically, I would like to use a higher sampling rate (192KHz) than is currently support by shairport-sync (44.1KHz). I'm attempting to wrap my head around some of the work that has been done on the jack backend previously but I'm not particularly familiar with this sort of development so I'm not really sure where to begin.

I specifically require this higher sampling rate to attempt to decrease latency in my setup. I run a multimedia server inside a libvirt VM that includes routing to 3 other VMs for music production as well as playback, in addition to video playback. The only way I can keep both latency and xruns down is by increasing the sampling rate as much as possible (while passing through a PCIe sound card that supports this sampling rate to the VM and locking CPUs and memory on the same NUMA node as the card to it, giving it realtime priority in the host kernel, etc.) I know this is a very abnormal situation and a bit of an oddball request but if you're able to look into supporting higher sampling rates with the Jack backend I would be forever grateful. If not, I'll continue looking at the project and eventually submit a pull request.

**Comment by mikebrady** [comment]
Thanks for the post. Jörn Nettingsmeier @nettings did a lot of work on the Jack Audio backend, so I'd be interested in his views.

**Comment by nettings** [comment]
Hi @jmichaelbarker, your requirements are indeed very particular. While I agree that it would be great to support arbitrary sample rates in the shairport-sync Jack backend, the things you are trying to accomplish seem to be a bit contradictory:
* you want very low latency for reasons you don't specify
* you want to do realtime music production
* you are using shairport-sync, which is a high-latency, high convenience, low reliability (in this context) protocol
* you are using VMs, which is again just the opposite of reliable low latency scheduling, adding a layer of scheduling complication that is pretty much impossible to get to run reliably
VMs are great for render farms where latency is not an issue. For low latency operation, you 
*really* want to run directly on the iron.

To reduce latency, you reduce the buffer size. While it's true that doubling the sampling rate will halve the buffer delay, the same could be accomplished by using half the buffer size, at a lot less bandwidth and CPU usage. The only time where higher sampling rates actually make sense to further reduce latency is when you have arrived at the minimum buffer size that your hardware supports, or when you want to reduce the impact of hardware delays in the converters, which are always N samples regardless of sampling rate. But there, N is usually in the low single digits and doesn't really factor in the grand scheme of things.
You also claim that increasing the sampling rate reduces xruns, which is frankly not a logical hypothesis. If you really observe this, it sounds like a bug in the hardware or driver.

In any case, if you do decide to work on it, I will gladly test your code and try to contribute.
I think the resampling step should happen in the soxr DLL, where it won't incur extra costs.

**Comment by pdgendt** [comment]
Resampling has been added in pull request #939 for the jack audio backend, you can try to use that to up-sample to 192kHz.
