### ISSUE TITLE
Is it possible to get the current playlist?

### ISSUE THREAD

**Issue by project-owner** [mikebrady/shairport-sync#916]
Just wondering if it's possible to get from player the current playlist?
Thanks!

**Comment by mikebrady** [comment]
Well, I don’t know, TBH. From iTunes it might be possible, but from the regular remote service such as iOS provides, I don’t think so. It would require a great deal of detective work on protocols and I haven’t followed up in it.

**Comment by project-owner** [comment]
I'm trying to add shairport-sync to the Peppy player. In that player when you click on the album art you get the playlist. So now I need to disable that functionality when shairport-sync is in use.
Thank you!

**Comment by project-owner** [comment]
Also player can play audio files from the file system. There is no playlist in this case.
