### ISSUE TITLE
Some questions regarding dbus interfaces

### ISSUE THREAD

**Issue by project-owner** [mikebrady/shairport-sync#917]
I was able to control player (Spotify running on iPhone) - Pause/Play/Next/VolumeUp/VolumeDown through dbus using Python. Some commands don't work (PlayPause, Previous doesn't work for free Spotify account) and that's OK.

I need info about track time and elapsed time. I cannot get ElapsedTime from the org.gnome.ShairportSync.Diagnostics interface. Does it depend on player (Spotify in my case)? Also I couldn't find track time in interface/properties including Metadata.

What is "ProgressString" in the interface org.gnome.ShairportSync.RemoteControl? Here is the example of that string:
3904418928/3904521244/3912489228

It looks like you save album art in file system and provide the path in the Metadata:
/tmp/shairport-sync/.cache/coverart/cover-f90a624ed2f804a3174e8875bee2cacc.jpg
Is it possible to switch this feature off? I could get album art without temporary files using named pipe. It's better to avoid writing to the file system based on the flash memory (e.g. Raspberry Pi). I hope that in case of a named pipe you don't write temporary files to the file system (?)

Is it possible to change volume scale from logarithmic (-28 -> 0) to the linear?

Thank you!

**Comment by mikebrady** [comment]
> I was able to control player (Spotify running on iPhone) - Pause/Play/Next/VolumeUp/VolumeDown through dbus using Python. Some commands don't work (PlayPause, Previous doesn't work for free Spotify account) and that's OK.

> I need info about track time and elapsed time. I cannot get ElapsedTime from the org.gnome.ShairportSync.Diagnostics interface. Does it depend on player (Spotify in my case)? Also I couldn't find track time in interface/properties including Metadata.

I guess it does depend ultimately on the player. Is is provided by, e.g. the Music app?

> What is "ProgressString" in the interface org.gnome.ShairportSync.RemoteControl? Here is the example of that string:
3904418928/3904521244/3912489228

This seems to be three figures – the start of the current play sequence, the present position and the ending position of the current play sequence. It is denominated in frames, with 44,100 per second.

> It looks like you save album art in file system and provide the path in the Metadata:
`/tmp/shairport-sync/.cache/coverart/cover-f90a624ed2f804a3174e8875bee2cacc.jpg`
Is it possible to switch this feature off? I could get album art without temporary files using named pipe. It's better to avoid writing to the file system based on the flash memory (e.g. Raspberry Pi).

There is no switch in place at present, but I'll have a look. Meantime, consider using `ramfs` or `tmpfs` for the temporary writable files. This is common in real embedded systems. 

> I hope that in case of a named pipe you don't write temporary files to the file system (?)

Writing it to the named pipe only.

> Is it possible to change volume scale from logarithmic (-28 -> 0) to the linear?

The scale -30 to 0, with -144 being "mute", is supplied by Apple.

**Comment by project-owner** [comment]
I'm testing with Spotify app/player running on iPhone. I'm currently using free Spotify account.

Is it possible to derive track time and elapsed time from the ProgressString by applying some math on it? Is it always 44K sample rate and it's independent from the source rate? Just wondering why start play sequence is not 0.

Thank you for the tmpfs hint. I'll try to use it. Hopefully 10MBytes is enough for /tmp/shairport-sync/.cache. Do you cache anything else besides cover art?

Is it possible to get information about player and platform on which it's running. For example - Spotify player running on iPhone. I see there is Server property but I'm not sure what that is. It looks like a MAC address.

**Comment by project-owner** [comment]
I'm trying to get dbus signal names which I could use for callbacks from this file:
https://github.com/mikebrady/shairport-sync/blob/master/dbus-service.c
As far as I understand the signal names are handle-volume-up, handle-volume-down etc.
But when I try to use those names in Python:
proxy.connect_to_signal(handler_function=handler, signal_name="handle-volume-down")
I got exception:
ValueError: Invalid member name 'handle-volume-down': contains invalid character '-'
Should I use some other names?
Thank you!

**Comment by mikebrady** [comment]
> Is it possible to derive track time and elapsed time from the ProgressString by applying some math on it? Is it always 44K sample rate and it's independent from the source rate?

Yes, and the rate on all existing AirPlay implementations is 44,100 fps.
> Just wondering why start play sequence is not 0.

No idea.

> Thank you for the tmpfs hint. I'll try to use it. Hopefully 10MBytes is enough for /tmp/shairport-sync/.cache. Do you cache anything else besides cover art?

Nothing else is cached on a file system. In my experience, there will be the occasional artwork of over 10 MB.

> Is it possible to get information about player and platform on which it's running. For example - Spotify player running on iPhone. I see there is Server property but I'm not sure what that is. It looks like a MAC address.

Unfortunately, we are at the mercy of what the application or audio subsystem reveals. AFAIK, there is no information coming from iOS about the client. Nor is there any information about the name of the device. The IP number (which could be an IPv4 or IPv6 number) of the audio device is available, which you could try to use to get, e.g., its hostname.

> I'm trying to get dbus signal names which I could use for callbacks from this file:
https://github.com/mikebrady/shairport-sync/blob/master/dbus-service.c
As far as I understand the signal names are handle-volume-up, handle-volume-down etc.
But when I try to use those names in Python:
proxy.connect_to_signal(handler_function=handler, signal_name="handle-volume-down")
I got exception:
ValueError: Invalid member name 'handle-volume-down': contains invalid character '-'
Should I use some other names?

If you look at the [xml](https://github.com/mikebrady/shairport-sync/blob/master/org.gnome.ShairportSync.xml) file defining the D-Bus service, the names are define there – "VolumeUp", "VolumeDown", etc.

**Comment by project-owner** [comment]
Thank you for the answers! Do you delete the old image from the file cache when the new one arrives? If not, I should probably do that myself to avoid out of disk space on tmpfs.

**Comment by project-owner** [comment]
Great! And probably the last questions - how often do you update ProgressString?

**Comment by mikebrady** [comment]
> Great! And probably the last questions - how often do you update ProgressString?

ProgressString is updated whenever it arrives from the client, so it's under the client's control.

> BTW, VolumeUp is the method name. Is the signal name the same?

There is no Volume signal in the RemoteContol interface because it is not provided by regular iOS "AirPlay" remote control. There is one in the AdvanceRemoteControl, but that only seems to be implemented by iTunes.

> Also, I cannot find method to set current playback position in the track which is usually called 'seek' in other players. Does it exist in the shairport-sync?

No, it's not implemented in the `RemoteControl` interface because it's not supported, AFAIK, in the regular iOS "AirPlay" remote control, and I have not tried to implement it for the AdvancedRemoteControl interface.

**Comment by project-owner** [comment]
Thank you!

**Comment by mikebrady** [comment]
Good luck with your work!

**Comment by mikebrady** [comment]
@project-owner, I just added the ability to disable cover art file caching to the `development` branch – please see [here](https://github.com/mikebrady/shairport-sync/blob/development/RELEASENOTES-DEVELOPMENT.md).

**Comment by project-owner** [comment]
Thanks a lot! That eliminates the need in tmpfs for embedded systems. The images can be taken from a named pipe. Whenever I'm done with implementation I'll post the links to the source files and screenshots. Thanks again for the great project!

**Comment by mikebrady** [comment]
That would be great, thanks. BTW, just fixed a tiny conditional flag compilation problem.
