### ISSUE TITLE
iOS 13.1.3 could not connect

### ISSUE THREAD

**Issue by NewFolk** [mikebrady/shairport-sync#918]
Hello,

I have iPhone with 13.1.3 iOS. And 3 raspberry with Shairport-sync.
All devices has **3.3.2 version**. 
Everything was ok before iPhone update.
All other devices(iOS and OS X) at home are ok. But there is no other devices with 13.1.3 to check.
I could not find the same Issue is it known problem? or my local issue?

**Comment by mikebrady** [comment]
Haven't come across this as a problem, and running iOS 13.1.3 on all devices...

**Comment by NewFolk** [comment]
oh, could not connect to Apple TV, too.
Looks like some Apple bug, or my router(why all the other device work then...)

**Comment by toschill** [comment]
Same issue here. Unable to connect since iOS update to 13.1.3. Mac is working fine.

**Comment by mikebrady** [comment]
Hmm, this sounds like a network connectivity issue. On the Shairport Sync device, if you run:
```
$ avahi-browse _raop._tcp
```
on the Shairport Sync device, it should show all RAOP (AirPlay) services, including the service provided by the device itself. For example:
```
pi@raspberryPi4B:~ $ avahi-browse _raop._tcp
+  wlan0 IPv6 A119362D4672@RaspberryPi4B                    AirTunes Remote Audio local
+  wlan0 IPv6 CFAD0A7419F4@Blink                            AirTunes Remote Audio local
+  wlan0 IPv6 329F7E1A955F@Front Room                       AirTunes Remote Audio local
+  wlan0 IPv6 33FA00A66F2E@Kitchen                          AirTunes Remote Audio local
+  wlan0 IPv4 A119362D4672@RaspberryPi4B                    AirTunes Remote Audio local
+  wlan0 IPv4 329F7E1A955F@Front Room                       AirTunes Remote Audio local
+  wlan0 IPv4 33FA00A66F2E@Kitchen                          AirTunes Remote Audio local
+  wlan0 IPv4 CFAD0A7419F4@Blink                            AirTunes Remote Audio local
+  wlan0 IPv4 001FF3F66F5E@Main Bedroom                     AirTunes Remote Audio local
+  wlan0 IPv6 001FF3F66F5E@Main Bedroom                     AirTunes Remote Audio local
+  wlan0 IPv6 5855CA032BB2@Apple TV                         AirTunes Remote Audio local
+  wlan0 IPv4 5855CA032BB2@Apple TV                         AirTunes Remote Audio local
```
 The device's own Shairport Sync service is showing up as `A119362D4672@RaspberryPi4B`. (`avahi-browse` is part of the `avahi-utils` package in Debian.)

Then, if you run `Discovery` from TildeSoft on your iOS devices, it should include `_raop._tcp` information from the AirPlay devices. They should be the same.

![pic](https://user-images.githubusercontent.com/4265913/67474221-04346200-f64c-11e9-93ed-d77339bbee0a.jpg)

**Comment by NewFolk** [comment]
It very floating bug and i think it is network issue too. I have a lot if wifi point nearby.
