### ISSUE TITLE
Is the metadata available from the named pipe on Windows?

### ISSUE THREAD

**Issue by project-owner** [mikebrady/shairport-sync#919]
I've read this page:
https://github.com/mikebrady/shairport-sync/blob/master/CYGWIN.md
and wondering if metadata is available in the named pipe in the Cygwin?
Also I've read a long discussion about difficulties of using dbus on Windows installation. Are there any news about that?
Thank you!

**Comment by mikebrady** [comment]
No news on the D-Bus front, but I believe the metadata is available via the named pipe alright. I haven't checked recently; maybe over the next week or so.

**Comment by project-owner** [comment]
Thank you!
