### ISSUE TITLE
Constant hiss when streaming to Raspberry Pi

### ISSUE THREAD

**Issue by jarrah31** [mikebrady/shairport-sync#92]
Hello,

I followed the excellent instructions found here for shairport-sync: http://www.redsilico.com/multiroom-audio-raspberry-pi#comment-157, but unfortunately all the sound from my Raspberry Pi is accompanied by a constant background hiss.

My init.d startup command is as follows:

    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "StudyAirPlay" --statistics -- -d hw:0 -t hardware -c "PCM" || return 2

I'm using a Raspberry Pi B+ on a wired network. I'm streaming from my MacBook (10.10.4 - wired) and iPhone 5S (iOS 8.4 - wifi) and both suffer from hiss. 

I can hear the hiss when connected to the stereo via the Pi's 3.5mm jack, and more so via headphones (which I used for testing).

Enabling statistics shows the following:

    Jul  2 10:51:56 raspberrypi shairport-sync[2338]: Sync error: -18.2 (frames); net correction: 135.3 (ppm); corrections: 605.5 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6030, min and max buffer occupancy 263 and 265.
    Jul  2 10:52:31 raspberrypi shairport-sync[2338]: Sync error: 3.6 (frames); net correction: 17.4 (ppm); corrections: 585.9 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6083, min and max buffer occupancy 263 and 265.
    Jul  2 10:53:01 raspberrypi shairport-sync[2338]: Sync error: -0.4 (frames); net correction: 28.7 (ppm); corrections: 606.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5882, min and max buffer occupancy 262 and 265.
    Jul  2 10:53:31 raspberrypi shairport-sync[2338]: Sync error: -9.2 (frames); net correction: 67.3 (ppm); corrections: 631.2 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6170, min and max buffer occupancy 263 and 265.
    Jul  2 10:54:01 raspberrypi shairport-sync[2338]: Sync error: -2.2 (frames); net correction: 50.6 (ppm); corrections: 605.5 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6164, min and max buffer occupancy 263 and 265.
    Jul  2 10:54:31 raspberrypi shairport-sync[2338]: Sync error: -4.7 (frames); net correction: 45.4 (ppm); corrections: 615.4 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6104, min and max buffer occupancy 263 and 265.

I should add that I'm using a fresh Raspbian 2015-05-05 image which was then fully updated and upgraded before compiling shairport-sync.

Thanks in advance!

**Comment by mikebrady** [comment]
Hi there. Well done on getting Shairport Sync installed an running. The hiss problem is caused by the poor quality of the built-in audio output device on the Raspberry PI. If you use a USB sound card instead, even a cheap $5 one, the sound will be immeasurably better.

**Comment by jarrah31** [comment]
Ah fair enough. :( 

I know that the original Pi had poor audio out but I thought they improved it with the B+? Is a Pi2 any better?

If I were to buy a cheap $5 usb sound card, are there certain features I should ensure it has? Any recommendations? 

Thanks.

**Comment by mikebrady** [comment]
The sound quality has improved a little – fewer loud pops, but it's not really noticeably better on the B+ or the 2, both of which I have tried.

You can get those little sound cards on EBay, Amazon and suchlike. I just went to the nearest PC accessories store and paid a little more for immediacy. Many of them seem to have a "3D Sound" type of branding, and have a microphone jack and a headphone jack. They are usually advertised as Windows/Linux/Mac compatible.

Here's a picture of one:

![cheapo](https://cloud.githubusercontent.com/assets/4265913/8477937/e1ffe458-20c5-11e5-95e6-d46363ffdfd1.jpg)

A minor thing about these sound cards is that the range of volume adjustments is quite limited – around 30 dB as against 60 dB for a reasonable HiFi setup. Otherwise, they're fine for normal listening and for $5, who'd complain!

**Comment by jarrah31** [comment]
Thanks, I'll give that a go!

**Comment by jarrah31** [comment]
I can confirm that audio is much improved with an external USB sound card! I used this one in the end: http://www.amazon.co.uk/gp/product/B00IRVQ0F8 

Thanks for your help!

**Comment by mikebrady** [comment]
Glad to hear it, thanks.
