### ISSUE TITLE
active_state_timeout = x  - any value makes no difference

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#920]
Hi,

I'd like to use the active_state_timeout set to about 1 second after the end play audio. I'm using run_this_after_exiting_active_state to launch another program which works well, but the delay is always 8-10 seconds regardless of what active_state_timeout is set too.

[EDIT]
Interestingly doing a word search throughout the entire project returns nothing for "active_state_timeout". Has this been made redundant? 

Thanks.

**Comment by mikebrady** [comment]
Hi. Active state timeout is [should be!] alive and well. It is in the `sessioncontrol` part of the [configuration file](https://github.com/mikebrady/shairport-sync/blob/master/scripts/shairport-sync.conf). When I get a chance, I'll double-check it's still working...

**Comment by mikebrady** [comment]
[Update] I  just checked it again there, and it is responding to changes in the `active_state_timeout` setting alright.

**Comment by juliandc1969** [comment]
Hi Mike,

Think the issue is my version. Just read the readme in the latest release 3.3+  
A new `active` state. New hooks are provided to execute programs before entering and after leaving the `active` state which covers sequences of play sessions separated by short intervals. This simplifies amplifier switch-on and switch-off, for example.

I'm running 3.2.2. I'll rebuild and retry today.

Thanks!

**Comment by mikebrady** [comment]
Thanks for the update – yes, that's exactly why it was added.

**Comment by juliandc1969** [comment]
Hi Mike,

Shairport-sync 3.2.2 built.
./configure --with-alsa --with-avahi --with-dbus-interface --with-ssl=openssl cross_compiling=yes

Still the same for me, no change regarding the duration of active_state_timeout. I am expecting the hook run_this_after_exiting_active_state to be "padded" by the amount of time specified in active_state_timeout. Always ~10 seconds regardless of setting. 

I've also lost my debug!!

Ran as:
/usr/bin/shairport-sync -vv -c /usr/local/disign/shairport-sync.conf


My config:
general =
{
	name = "imx";
	output_backend = "alsa";
};

alsa =
{
	output_device = "shairportsyncloopback";
};

sessioncontrol =
{
	dbus_service_bus = "system";
	active_state_timeout = 1.0;
	run_this_after_exiting_active_state = "/usr/bin/test2.sh";
};

Cheers.

**Comment by juliandc1969** [comment]
--use-stderr  debugs back, different, but back...

**Comment by mikebrady** [comment]
Also `-u` brings them back.

**Comment by juliandc1969** [comment]
So it's just this timing weirdism. Could it be ARM x-compilation related? Don't think it's config related as I hard-coded the default value in shairport.c to 1.0 ( config.active_state_timeout = 1.0 ). No difference..

**Comment by mikebrady** [comment]
I just did some testing. I added a script to the `run_this_after_play_ends` hook:
```
#!/bin/sh

/usr/bin/logger "Play end"
```
and another script to the `run_this_after_exiting_active_state` hook. (This is the interval set by `active_state_timeout`.)
```
#!/bin/sh

/usr/bin/logger "Active state exit"
```
The script files were placed in the `/etc/ directory and given permissions `755`. They leave messages in the log, which are timed. This is the default situation:
```
Oct 25 17:36:41 raspberryPi4B shairport-sync[4132]: Play end
Oct 25 17:36:51 raspberryPi4B shairport-sync[4135]: Active state exit
```
and this is when you set the timeout to 30 seconds:
```
Oct 25 17:43:02 raspberryPi4B shairport-sync[4193]: Play end
Oct 25 17:43:32 raspberryPi4B shairport-sync[4195]: Active state exit
```
Then, this is when the active timeout is set to 1 second:
```
Oct 25 17:45:48 raspberryPi4B shairport-sync[4244]: Play end
Oct 25 17:45:49 raspberryPi4B shairport-sync[4246]: Active state exit
```
The timing of `Play end` is effectively controlled by the client – iOS/iTunes, etc. It can take quite a while from when play seems to stop for us humans and when it is determined to stop the client. I wonder is that what might be causing your issue?

**Comment by juliandc1969** [comment]
A couple of things, first need more sleep!! I left my 3.2.2 terminal window open, changing 3.3.2, then compiling 3.2.2 and SCPing to my board, no wonder why hard-coded things refused to work!!
So the timer does work but now but the minimum time is ~9 seconds ( with a timeout of 1 ). So all times are ~9+time_out. The music stops around at 1-2  seconds rest must be iOS? 

Thanks.

**Comment by mikebrady** [comment]
Yes indeed, I believe it is due to iOS. It's a bit different with iTunes – IIRC it's a bit shorter.

**Comment by juliandc1969** [comment]
Cool, thanks. Case closed!
