### ISSUE TITLE
Issue controlling via MQTT

### ISSUE THREAD

**Issue by marleyjaffe** [mikebrady/shairport-sync#924]
I am having issues controlling Shairpoint through MQTT commands. I've tried
```
$ mosquitto_pub -t '/shairport/remote' -m 'nextitem'
```
 and
```
$ mosquitto_pub -t '/shairport/remote' -m 'playpause'
```
 I've tried having my source as both iTunes on a mac as well as an iPhone. I do see the proper output when running
```
$ mosquitto_sub -t 'shairport/#'
```
_Originally posted by @tillz in https://github.com/mikebrady/shairport-sync/pull/716#issuecomment-398705299_

**Comment by mikebrady** [comment]
Looking at this, and assuming that the `mosquitto_sub -t 'shairport/#'` command works as shown, there is an error in your `mosquitto_pub` commands. Instead of:
```
$ mosquitto_pub -t '/shairport/remote' -m 'playpause'
```
use:
```
$ mosquitto_pub -t 'shairport/remote' -m 'playpause'
```
Separately, please note that the new macOS "Music" app (the replacement for iTunes) does respond to remote control commands.

**Comment by roblan** [comment]
> Separately, please note that the new macOS "Music" app (the replacement for iTunes) does respond to remote control commands.
does or does not?

**Comment by mikebrady** [comment]
Aargh. Is should be “does not”! Thanks.

**Comment by marleyjaffe** [comment]
> use:
> 
> ```
> $ mosquitto_pub -t 'shairport/remote' -m 'playpause'
> ```

I’ll try this today.

> Separately, please note that the new macOS "Music" app (the replacement for iTunes) does not respond to remote control commands.

Should controlling an iPhone source (Spotify app or otherwise) work?

**Comment by mikebrady** [comment]
Yes, an iOS source should work. The iOS music app and TuneIn Radio Pro work. Not sure about Spotify.

**Comment by marleyjaffe** [comment]
That fixed the issue. MQTT is able to control the spotify app on my iPhone too! Thanks for the assistance.
