### ISSUE TITLE
Debian Repo Update

### ISSUE THREAD

**Issue by mynameisdaniel32** [mikebrady/shairport-sync#926]
More of a question than an issue - how long does it take for the latest release to make its way onto the debian repo? Even under sid.

Just trying to work out if I should be patient, or try going down the road of uninstalling everything and building myself to get the latest version.

**Comment by mikebrady** [comment]
Maybe @bootc might have an expert’s opinion...

**Comment by bootc** [comment]
I maintain the Debian packages of shairport-sync in Debian. Debian Stable (currently Buster) will not be updated to a new release. Important bug fixes may trickle through, however, if I get bug reports and they can be reasonably isolated.

However, new releases may appear via backports. For that to happen I need to upload to Unstable first, then after a few days they migrate to testing (all being well) and from there I can upload to backports.

With that said I haven't had a lot of time to keep up lately (I have a young daughter now...), and nobody has prompted me to upload newer versions until now, so I haven't.

Would you rather see 3.3.2 that's currently in testing go into stable-backports, or for me to prepare 3.3.4 for upload to unstable so it can make its way into testing in a few days? Note that I *cannot* upload something to backports that's not in testing, so I can't push 3.3.4 into backports without it going though unstable and testing first.

**Comment by mikebrady** [comment]
Hi Chris. Better, I think, to wait for 3.3.5, as there appears to be an issue in 3.3.4. Congratulations on the daughter,  BTW!

**Comment by mynameisdaniel32** [comment]
Thanks Chris - whenever you get a chance to update to the latest version I'd be very happy to test :)

**Comment by mikebrady** [comment]
Hello again Chris. Well, 3.3.5 is out for a short while now, and I think it would be worth updating to it alright — It was worth waiting to get that little bug out.

All the best.

**Comment by bootc** [comment]
Good stuff, I'll try to find some time to get that packaged up soon. Probably at the weekend.

**Comment by mikebrady** [comment]
Chris, can I suggest that it is probably a good idea to include the `--with-libdaemon` configuration flag in the build, as it is needed now for Shairport Sync to support the daemon mode `-d` option. Even though it's no longer necessary to do that on `systemd` systems, some scripts still include it...

**Comment by bootc** [comment]
I've uploaded 3.3.5-1 to Debian unstable/sid yesterday: https://tracker.debian.org/news/1083878/accepted-shairport-sync-335-1-source-into-unstable/

It should hopefully land in testing/bullseye in 5 days' time, after which I can backport it to buster.

**Comment by mikebrady** [comment]
Many thanks, Chris.

**Comment by bootc** [comment]
3.3.5-1~bpo10+1 went into buster-backports yesterday:
https://tracker.debian.org/news/1086431/accepted-shairport-sync-335-1bpo101-source-amd64-into-buster-backports-buster-backports/
