### ISSUE TITLE
Could 96000 be a valid value for alsa output_rate?

### ISSUE THREAD

**Issue by vasilisvg** [mikebrady/shairport-sync#928]
Right now I have this setup: I pipe music with 32bits 96 kHz from a record player via forked-daapd to another Raspberry Pi that runs Shairport Sync. 

Shairport Sync seems to use different values for its `output_rate`. I can use a pipe_sample_rate of 96000, but when I tried using a 32/88200 pipe with forked-daapd I get this message:

```
forked-daapd[929]: [FATAL]   player: The configuration of pipe_sample_rate is invalid: 88200
```

Would it be possible to make 96000 (and other numbers based on 48000) a valid value for alsa `output_rate` as well, for better compatibility with forked-daapd? 

*[(I asked a similar question over at forked-daapd)](https://github.com/ejurgensen/forked-daapd/issues/838)*

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, it would require major work to make Shairport Sync work at an input rate other than 44,100. All the timing and syncing is based on that rate. While it would be possible to make it work, there are essentially zero sources working at other rates.
