### ISSUE TITLE
 [Feature] FFT convolver load during session

### ISSUE THREAD

**Issue by corrpel** [mikebrady/shairport-sync#929]
Hello,
It would be awesome to be able to load different impulse response file while audio is playing.
How i use FFT:
I add some reverb and modify the low frequency values to my likes.
But sometimes, let's say at 10 PM, i want to apply a different sound signature to reduce disconfort for my neighbords, so it would be nice to load a new sample via dbus for example, without needing to modify the config file and restart the application.

**Comment by mikebrady** [comment]
Thanks for the suggestion. I’ll have a look at it.

**Comment by mikebrady** [comment]
@corrpel , would you have any impulse response files you could share for experimentation, or could you point to any that are already available, please?

**Comment by corrpel** [comment]
Hi Mike,
I will get back to you with two files.
I am currently at work.
Thanks.

Cornel

**Comment by mikebrady** [comment]
Thanks. I’ve made some headway on it and I’d like to test it out a bit.

**Comment by corrpel** [comment]
[dirac_boom.zip](https://github.com/mikebrady/shairport-sync/files/3832524/dirac_boom.zip)
dirac is a linear impulse response
boom is a bit modified

**Comment by mikebrady** [comment]
I've just pushed 3.3.5d1 into the `development` branch with some new properties in the native D-Bus interface to enable you to control convolution. If you got a chance to try it out, I'd be interested to hear of your experiences.

**Comment by mikebrady** [comment]
Actually, wait, there's a compilation bug....

**Comment by mikebrady** [comment]
Compilation bugs fixed!

**Comment by corrpel** [comment]
Nice!
Is working very well.
I've tested disable, enable, and load new file.
All working good!
Thank you!

**Comment by mikebrady** [comment]
Thanks. I’ll close this issue when the update is pushed to the `master` branch.

**Comment by PaulWieland** [comment]
Can either of you elaborate on how to use this feature?

I believe that I have the dsp/convolution_ir_file generated correctly but I would like to be able to toggle it on/off or between different filter files to hear the effect.

FYI - I'm using the docker image if that matters...
