### ISSUE TITLE
"Ask" Shairport-sync if there are any audio output

### ISSUE THREAD

**Issue by hansibull** [mikebrady/shairport-sync#93]
Hi!
I'm trying to automatically tun on my AV receiver with telnet, based on Shairport. If Shairport receives audio from a device, and the AV Receiver is in standby mode, the computer that runs Shairport-sync is going to send a telnet command that tells the AV receiver to turn on.
Is there any statement that return either false or true, depending on Shairport are receiving audio or not?
(take a look at the pseudo-code below)

if(shairport-sync.audio == true)
{
 //telnet command -  turn on AV receiver
 //telnet command -  change source
}

**Comment by joerg-krause** [comment]
You can use the `-B` and `-E` command line options:

```sh
    -B, --on-start=PROGRAM  run PROGRAM when playback is about to begin
    -E, --on-stop=PROGRAM   run PROGRAM when playback has ended
```

For example: `-B "telnet <command>"`

**Comment by mikebrady** [comment]
Hi there. Thanks for your interest in Shairport Sync. The suggestion made by @joerg-krause is the best one. You could also add the `-w` option to make Shairport Sync wait for the completion of each command. Try `man shairport-sync` for more information.

**Comment by hansibull** [comment]
Thanks! I created a simple Bash script (and made it executable) that that check the power status and changes the sudio source on request. The script works fine itself, but I can't get it working with shairport. I've been modified the /etc/init.d/shairport-sync file to suit my needs (external DAC etc). When I try to use the -B parameter, i get this error:
Process 2767 died: No such process; trying to remove PID file. (/var/run/shairport-sync.pid)

how can I edit this line to run my script on playback start?
start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Shairport" -- -d plughw:CARD=DAC  -B "./marantz-SR5008.sh" || return 2

**Comment by mikebrady** [comment]
I'm glad you got it working. The thing to remember is that you must give the full path to the command you're using in the `-B` or `-E` option. BTW, I'm not sure `/etc/init.d/` is a good choice of a place to store your script (also I don't think the `./` is necessary. Putting the script in a new folder in `/etc`, e.g. `/etc/shairport-sync-scripts` might be safer.
