### ISSUE TITLE
Run script when music plays

### ISSUE THREAD

**Issue by NickSutton** [mikebrady/shairport-sync#931]
Hi Mike,

I’m trying to get Shairport to run a script when starting to play music.
The script is executable, and the command at the prompt would be `bash runLED.sh`

I have `bash /home/pi/Desktop/runLED.sh` in the Conf file, but get a ‘failed to start’ message.

Any pointers? Cheers, Nick

**Comment by mikebrady** [comment]
Yeah. The key thing is that you must give the full path for everything, including the `bash` command in your example, but also in your script itself.

**Comment by NickSutton** [comment]
Full paths everywhere, except the initial bash command... I’ll try and find that out and give it a go!

On 13 Nov 2019, at 17:45, Mike Brady <notifications@github.com> wrote:

﻿

Yeah. The key thing is that you must give the full path for everything, including the bash command in your example, but also in your script itself.

**Comment by kdubious** [comment]
@NickSutton I have this working by just setting the value to “/opt/my-script”
That file is marked as executable by all users.
That file starts with:
`#!/bin/sh`
(I use busybox with the sh shell)

**Comment by NickSutton** [comment]
Thanks, I tried as CHOWNing the script from ‘pi’ to ‘root’ but that didn’t help either. What user does Shairport run as?

The command is to actually SSH onto another api (that controls sound reactive LEDs) but the script runs from the prompt without issue, so not sure why shairport is being grumpy?

On 14 Nov 2019, at 04:53, Kevin Welsh <notifications@github.com> wrote:

﻿

@NickSutton<https://github.com/NickSutton> I have this working by just setting the value to “/opt/my-script”
That file is marked as executable by all users.
That file starts with:
#!/bin/sh
(I use busybox with the sh shell)

**Comment by mikebrady** [comment]
Nick, I suggest you take it step by step. The `chown` thing is irrelevant if you are calling `bash` explicitly: `bash /home/pi/Desktop/runLED.sh` as you are in the OP – it's only an issue if you try to call the script directly as an executable: `/home/pi/Desktop/runLED.sh`.

I suggest you put some diagnostic commands in the script itself. For example, the first line in the script could be to print a message to the log, e.g:
```
/usr/bin/logger "Started the script..."
```
and so on. That way, you could review progress in the log. (The full path for `logger` above is correct on a Raspberry Pi.)

**Comment by NickSutton** [comment]
Hi, 

Added the `/usr/bin/logger` line and can see that in `journalctl` so it opens the script ok at least.

The script simply contains the line : `sshpass -p "**MyPassword**" ssh **myUser**@**myHostname** "sudo python /home/pi/AR-LED/dancyPi-audio-reactive-led/python/visualization.py spectrum"` and I also tried with just that command in the Shairport Conf file, but no luck.

As always, both the script and the command above execute perfectly well at the terminal prompt.

**Comment by NickSutton** [comment]
My file starts with `#!/bin/bash` too

**Comment by mikebrady** [comment]
Nick, did you give the full pathname to `sshpass` and to `ssh`?

**Comment by NickSutton** [comment]
> Nick, did you give the full pathname to `sshpass` and to `ssh`?

I didn’t... How do I find those?

**Comment by mikebrady** [comment]
To find out where an executable is (i.e. to get its full pathname), use the `which` command.
E.g. on a Pi:
```
$which shairport-sync`
```
will (usually) return:
```
/usr/local/bin/shairport-sync
```

**Comment by NickSutton** [comment]
Got the same with `type` thanks. Will update the script and try again

**Comment by NickSutton** [comment]
Still: `Nov 14 17:15:06 PiRadio-Audio shairport-sync[6841]: Execution of command "bash /home/pi/Desktop/runLED.sh " failed to start`

**Comment by mikebrady** [comment]
Hmm, I think I'll have to leave it to you, as it seem that Shairport Sync is calling the script alright. But perhaps you can use a few more of those `logger` messages and maybe turn on any diagnostics that may be in the `sshpass` and `ssh` utilities to see if they are being called and to see what's happening with them.

**Comment by NickSutton** [comment]
No worries, thanks for the help. But in theory, no problem with this sort of approach?

On 14 Nov 2019, at 17:19, Mike Brady <notifications@github.com> wrote:

﻿

Hmm, I think I'll have to leave it to you, as it seem that Shairport Sync is calling the script alright. But perhaps you can use a few more of those logger messages and maybe turn on any diagnostics that may be in the sshpass and ssh utilities to see if they are being called and to see what's happening with them.

**Comment by mikebrady** [comment]
Generally, using a script should be fine, but — as you are discovering — the environment the script runs in is much different to when it is called from a command line. I do worry about using `ssh` though. My guess is that that's where the problem might lie, but I really don't know.

**Comment by NickSutton** [comment]
Must have been the sshpass or ssh it didn’t like. I built a web server on the client computer with a .PHP control and now execute curl commands from Shairport-sync to correctly start and stop the audio reactive LEDS! Cheers.

**Comment by mikebrady** [comment]
Fantastic – good work.
