### ISSUE TITLE
Peer to peer airplay?

### ISSUE THREAD

**Issue by chetanpm** [mikebrady/shairport-sync#933]
Apple's own hardware like their TV, homepod does wireless streaming without the need for all the devices be on same wifi network. Infact, no wifi router required to stream directly to the speaker from iphone. I was wondering if that is something possible for a raspberry pi or similar wifi devices?

https://www.youtube.com/watch?v=kN76FyITNMw

**Comment by mikebrady** [comment]
Thanks for the interesting question. This would require some work on Apple's peer-to-peer discovery stuff, so it is well out of the current scope of this project. There appears to be [some work on AirDrop](https://github.com/seemoo-lab/opendrop) which might be relevant, but I guess it would require a fair bit of investigation...

**Comment by chetanpm** [comment]
Discovering the audio device through bluetooth trigger and then handing out the connection to wifi direct. It looks like they don't have special hardware but everything is implemented in the software. Apple kind of lock features with security certificates. I don't know if anyone can do it at all but it just feels good to when devices communicate peer to peer instead of always needing a router in between.

**Comment by mikebrady** [comment]
I had a quick look at this and it’s a morass at the moment — it is very far from being a routine matter to add the networking infrastructure needed. Even then we don’t know what protocols are in play. For the present, therefore, I’d say it is far out of reach.

**Comment by chetanpm** [comment]
Well, It was worth a try :)
It is probably for a reason that no one has tried doing it so far, knowing that apple released p2p airplay functionality in ios 8. If someone could think about a way to do it in the future, it would be interesting thats all.

**Comment by mikebrady** [comment]
Yeah, it's a nice idea alright. Let's keep an eye on developments... For the present, though, I'll close the issue.

**Comment by chetanpm** [comment]
I realized we can connect the pi to the iphone hotspot and in turn use the same iphone to stream the music back. There could be a little scope to streamline if someone decides to look into it.

**Comment by mikebrady** [comment]
Another modality is to make the Pi itself a WiFi access point that is not connected to the internet. The iPhone can then use its cellular connection to connect, as normal, to the Internet and can use the Pi's WiFi network to connect to the Shairport Sync player. That approach is documented in the [CAR INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/CAR%20INSTALL.md) document.

**Comment by Raynoxis** [comment]
Hello , do you have some News ? Thank you

**Comment by teelekkung** [comment]
any update?

**Comment by dddanielliu** [comment]
I’ve recently found out that Belkin SOUNDFORM CONNECT can do it, but how?

**Comment by docterling** [comment]
any update?
