### ISSUE TITLE
reconnect/disconnectFromOutput

### ISSUE THREAD

**Issue by Rekss13** [mikebrady/shairport-sync#934]
Good night, I am developing a stereo receiver and using shairport-sync in my project. Only the old version can be found in the ubuntu repository, and I need at least version 3.3 to use run_this_before_entering_active_state and run_this_after_exiting_active_state. But when building the version from git under Ubuntu, I lose the opportunity to disconnect and reconnect shairport-sync using the keys R and D, to switch to mpd. What to use now?

**Comment by mikebrady** [comment]
Thanks for the post. Can you be more specific about "using the keys R and D" please? Perhaps if you could give an example?

**Comment by Rekss13** [comment]
I compiled shairport from git according to the instructions https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md and this
https://github.com/mikebrady/shairport-sync for custom armbian build based on ubuntu 18.04.3 kernel 5.3.9 for Orange pi zero 1.4. As a result, I got 3.3.5-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc, which does not have the ability to reconnect to alsa with the commands "shairport-sync -R" and "shairport-sync -D". Earlier, I used them in server code on nodejs to control mpd. But now they are not there because I can only collect as --with-systemd otherwise I get a bug error.

During the tests, I switched to a similar system on Debian due to sysv support and the assembly with --with-libdaemon --with-systemv went without errors, but it works as if I were assembling it with the argument --with-systemd. As a result, I returned to Ubuntu, and I need to make changes to the project so that it works stably on Debian, especially since the desired result was not achieved.

As a temporary solution, before sending the mpd play command, I execute systemctl stop shairport-sync, and after the mpd starts playing, I execute systemctl start shairport-sync.
To play shairport using the run_this_before_play_begins hook, I stop playing in mpd and everything works. I already came up with this today.

Sorry for my bad english.

**Comment by mikebrady** [comment]
Thanks. Your English is very good.

The `-R` and `-D` commands have been deprecated for some time, and finally were removed. The reason was that a very ugly signalling system was being used. The functionality could perhaps be restored through the D-Bus interface. It might take a little time...

**Comment by Rekss13** [comment]
I get it. Thanks. Then I will use what I already thought up. This is not my English - this is Google Translate))))

**Comment by mikebrady** [comment]
Thank you for your response. If you use what you have already designed and it works alright, then I will not start adding the D-Bus commands. If it does not work out, please let us know.

**Comment by Rekss13** [comment]
OK

**Comment by Rekss13** [comment]
Good day.
I have this picture when playing iphone 6 and from a PC to Win10 (Version 10.0.14393). On PC, I use iTunes 12.10.2.3.

`Nov 29 06:17:50 URRI shairport-sync[1382]:      -0.15,       0.0,       0.0,        1003,      0,      0,      0,      0,   8556,  404,  412,   44100.05,   44160.17,   44100.95,      0.00,     0,     20.45
Nov 29 06:17:58 URRI shairport-sync[1382]:       0.12,       0.0,       0.0,        2006,      0,      0,      0,      0,   8540,  404,  412,   44100.01,   44141.32,   44099.49,      0.00,     0,    -11.82
Nov 29 06:18:06 URRI shairport-sync[1382]:      -0.24,       0.0,       0.0,        3009,      0,      0,      0,      0,   8540,  405,  412,   44100.03,   44043.40,   44101.02,      0.00,     0,     22.49
Nov 29 06:18:14 URRI shairport-sync[1382]:      -0.35,       0.0,       0.0,        4012,      0,      0,      0,      0,   8540,  404,  412,   44100.03,   44117.05,   44100.75,      0.00,     0,     16.32
Nov 29 06:18:22 URRI shairport-sync[1382]:      -0.44,       0.0,       0.0,        5015,      0,      0,      0,      0,   8540,  404,  412,   44100.02,   44109.85,   44101.13,      0.00,     0,     25.36
Nov 29 06:18:30 URRI shairport-sync[1382]:      -0.54,       0.0,       0.0,        6018,      0,      0,      0,      0,   8540,  405,  412,   44100.01,   44090.62,   44100.64,      0.00,     0,     14.19
Nov 29 06:18:38 URRI shairport-sync[1382]:      -0.58,       0.0,       0.0,        7021,      0,      0,      0,      0,   8524,  404,  412,   44100.01,   44095.47,   44101.17,      0.00,     0,     26.14
Nov 29 06:18:46 URRI shairport-sync[1382]:      -0.50,       0.0,       0.0,        8024,      0,      0,      0,      0,   8540,  406,  412,   44100.01,   44102.84,   44101.06,      0.00,     0,     23.78
Nov 29 06:18:54 URRI shairport-sync[1382]:      -0.68,       0.0,       0.0,        9027,      0,      0,      0,      0,   8524,  404,  412,   44100.01,   44100.09,   44101.05,      0.00,     0,     23.68
Nov 29 06:19:02 URRI shairport-sync[1382]:      -0.70,       0.0,       0.0,       10030,      0,      0,      0,      0,   8524,  405,  412,   44100.01,   44102.10,   44100.90,      0.00,     0,     20.22
Nov 29 06:19:10 URRI shairport-sync[1382]:      -0.58,       0.0,       0.0,       11033,      0,      0,      0,      0,   8524,  405,  412,   44100.01,   44100.06,   44101.05,     18.27,     9,      5.50
Nov 29 06:19:18 URRI shairport-sync[1382]:      -4.66,      82.1,      82.1,       12036,      0,      0,      0,      0,   1729,  406,  412,   44100.00,   44101.55,       0.00,     14.27,    12,      0.00
Nov 29 06:19:26 URRI shairport-sync[1382]:    -121.63,    2840.9,    2840.9,       13039,      0,      0,      0,      0,   2733,  403,  412,   44100.00,   44103.19,   44101.63,     12.93,    15,     23.93
Nov 29 06:19:34 URRI shairport-sync[1382]:     -98.99,    2840.9,    2840.9,       14042,      0,      0,      0,      0,   3744,  405,  412,   44100.00,   44101.38,   44102.07,     11.78,    17,     35.05
Nov 29 06:19:42 URRI shairport-sync[1382]:     -76.29,    2840.9,    2840.9,       15045,      0,      0,      0,      0,   4725,  404,  412,   44100.00,   44102.48,   44100.62,     11.95,    19,      2.02
Nov 29 06:19:50 URRI shairport-sync[1382]:     -53.55,    2840.9,    2840.9,       16048,      0,      0,      0,      0,   5725,  403,  412,   44100.00,   44105.26,   44101.76,     12.36,    21,     27.56
Nov 29 06:19:58 URRI shairport-sync[1382]:     -30.81,    2838.1,    2838.1,       17051,      0,      0,      0,      0,   6726,  404,  412,   44100.01,   44096.29,   44101.82,     12.22,    23,     28.96
Nov 29 06:20:06 URRI shairport-sync[1382]:     -13.56,    1076.3,    1076.3,       18054,      0,      0,      0,      0,   7726,  406,  412,   44100.00,   44097.82,   44101.08,     13.06,    25,     11.38
Nov 29 06:20:14 URRI shairport-sync[1382]:     -10.21,      87.8,      87.8,       19057,      0,      0,      0,      0,   7996,  404,  412,   44100.00,   44099.02,   44100.86,     14.37,    27,      5.03
Nov 29 06:20:22 URRI shairport-sync[1382]:     -10.03,      45.3,      45.3,       20060,      0,      0,      0,      0,   8112,  403,  412,   44100.01,   44097.94,   44100.93,     13.88,    29,      7.13
Nov 29 06:20:30 URRI shairport-sync[1382]:      -9.89,      31.2,      31.2,       21063,      0,      0,      0,      0,   8113,  405,  412,   44100.00,   44100.66,   44100.99,     13.57,    31,      8.86
`
The PC is wired to the Mikrotik RB951G-2HnD router, orange pi zero is wired and via Wi-Fi. Moreover, the picture is approximately the same. When playing Internet radio via mpd, everything is fine, but when playing on Airplay, I observe small gaps in playback. However, they can be seen from the statistics. Advise edits of a config to improve a situation. Here is my config:

`general =
{
      name = "URRI Receiver";
      volume_range_db = 66;
      output_backend = "alsa";
      drift_tolerance_in_seconds = 0.010;
      resync_threshold_in_seconds = 0.0;
      audio_backend_latency_offset_in_seconds = 1.5;
};

metadata =
{
      enabled = "yes";
      include_cover_art = "yes";
};

sessioncontrol =
{
      run_this_before_play_begins = "/usr/local/bin/stop-radio.sh";
      run_this_before_entering_active_state = "/usr/local/bin/unmute.sh";
      run_this_after_exiting_active_state = "/usr/local/bin/mute.sh";
      active_state_timeout = 0.1;
      wait_for_completion = "yes";
      allow_session_interruption = "yes";
      session_timeout = 60;
};

alsa =
{
      output_device = "hw:0";
      disable_standby_mode = "yes";
};

diagnostics =
{
      statistics = "yes";
     // log_verbosity = 3;
     // log_show_file_and_line = "yes";
};
`

**Comment by mikebrady** [comment]
Thanks. (I edited some of the formatting of your post.)

It is very difficult to diagnose this issue. It looks as if everything is fine – no pack losses whatever – until there is a sudden event of some kind, knocking synchronisation off by 121 milliseconds. Then you can see Shairport Sync resynchronising over a long period afterwards. I must say that I have had a poor experience with an Orange PI Zero; in fact, I have stopped using it completely..

**Comment by Rekss13** [comment]
I can’t already choose another board for which an expansion board was developed and produced with power and sound filtering and a built-in amplifier. Maybe there are some recommendations?

**Comment by mikebrady** [comment]
I'm not quite sure I understand what you mean, but if you are looking for a recommendation for something with a built-in amplifier, maybe some other contributors would have suggestions. Personally, I have found the combination of a Raspberry Pi 3B or better and the IQaudIO Pi-DigiAMP+ to be very good and trouble-free.
