### ISSUE TITLE
how to start shairport-sync from rc.local?

### ISSUE THREAD

**Issue by steeley** [mikebrady/shairport-sync#935]
Having a nightmare with systemctl starting shairport. it ran once after I installed on RPI(latest distro, apt-get install shairport-sync) and played sound etc.  but now I just rebooted and it won't start at all.

what is the correct way to manually start it, and can this be run from rc.local?

thanks.

**Comment by mikebrady** [comment]
Thanks for the post. It is easy to start Shairport Sync from `rc.local` of course, but it should start upon boot-up, and it would be important to figure out why it was not done so, in case it is a sign that something else is wrong.

Please have a look [here](https://github.com/mikebrady/shairport-sync/blob/master/CONTRIBUTING.md#issue-reports) for suggestions about what to look for and what include in the issue report.

**Comment by steeley** [comment]
thanks -  here is the info as requested:

3.2.2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-sysconfdir:/etc

● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-11-28 22:43:05 GMT; 11h ago
     Docs: man:shairport-sync(7)
           file:///usr/share/doc/shairport-sync/README.md.gz
           https://github.com/mikebrady/shairport-sync
  Process: 412 ExecStart=/usr/bin/shairport-sync --daemon $DAEMON_ARGS (code=exited, status=1/FAILURE)

Nov 28 22:43:05 piaplus systemd[1]: shairport-sync.service: Service RestartSec=100ms expired, scheduling restart.
Nov 28 22:43:05 piaplus systemd[1]: shairport-sync.service: Scheduled restart job, restart counter is at 5.
Nov 28 22:43:05 piaplus systemd[1]: Stopped ShairportSync AirTunes receiver.
Nov 28 22:43:05 piaplus systemd[1]: shairport-sync.service: Start request repeated too quickly.
Nov 28 22:43:05 piaplus systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
Nov 28 22:43:05 piaplus systemd[1]: Failed to start ShairportSync AirTunes receiver.

**Comment by mikebrady** [comment]
Thanks. There is an incompatibility in the startup script which is attempting to put Shairport Sync into the old-fashioned daemon mode. This is not necessary on a `systemd` system and Shairport Sync was built without support for it. So, you could try the following.

You should disable automatic booting of Shairport Sync:
```
$ sudo systemctl disable shairport-sync
```
and then add the following line into `rc.local`:
```
shairport-sync&
```
so that it looks a bit like this, with the command before the `exit 0` line:
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

shairport-sync&

exit 0
```
Let us know if that works?
