### ISSUE TITLE
Named pipe size

### ISSUE THREAD

**Issue by project-owner** [mikebrady/shairport-sync#936]
The default pipe buffer size in most Linux systems is 64K. The album art images often exceed this size. How will it work in shairport-sync in this case? Thank you!

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync will time out after trying to write the image through the pipe for five seconds. Also, AFAIR, if nothing is connected to the read end of the pipe, a write isn't attempted at all.

**Comment by project-owner** [comment]
OK, good to know. That means that if I'm not fast enough reading from the pipe I can face this timeout. I believe there is a setting in the config file which can be used to adjust that 5 seconds interval. Thank you!
