### ISSUE TITLE
shairport-sync segfaults when playback should start

### ISSUE THREAD

**Issue by berlinexilant** [mikebrady/shairport-sync#94]
As soon as shairport-sync should playback my music it segfaults.

Tried as daemon via systemd and as my own user as seen below. No difference.

As far as I get this it has something do to with glibc. Any ideas what to do? I'd love to use this old Macbook as an airplay receiver.

If you need more log or you can tell me where to find the core dump I will provide it.

I am running Arch on a Macbook 3,1 and the latest stable shairport-sync.

[oliver@ArchMB bin]$ ./shairport-sync -v
startup
avahi: avahi_register.
avahi: register_service.
Avahi without metadata
new RTSP connection.
Play connection from "AirPlay/241.5".
Connection from IPv6: fe80::18c7:a2f4:3344:e743:62910
Segmentation fault (core dumped)

Jul 14 12:49:40 ArchMB kernel: shairport-sync[3683]: segfault at 7f48acc78ff8 ip 00007f48aabd6e92 sp 00007f48acc79000 error 6 in libc-2.21.s

**Comment by joerg-krause** [comment]
Please try the following: Have a look at this line in player.c: https://github.com/mikebrady/shairport-sync/blob/e12d7ad23ee3c40b61c31543737dd1b929e08a53/player.c#L1109.

Replace 128 with 256, eg:
```
size_t size = (PTHREAD_STACK_MIN + 256 * 1024);
```

Recompile and test again.

**Comment by berlinexilant** [comment]
That solved it! Thank you very much!

**Comment by joerg-krause** [comment]
For some reason, a stack size of 128K + PTHREAD_STACK_MIN is not enough for glibc + gcc 5.1. I'll prepare a patch for this soon.

**Comment by joerg-krause** [comment]
@mikebrady We have two possibilities here: Increase the stack size or decrease stack usage by moving the statistics array to the heap.

Note that glibc's default stack size (several MBs, depending on the platform) is quite large compared to the default stack size defined by musl (80K). So increasing the stack size to, let's say 256KB, is not to much burden.

What do you think?

**Comment by mikebrady** [comment]
The quickest and easiest thing would be simply to increase the stack size – you have added the code for this already, right? I am away from my machines right now, so recording the array is a bit awkward at present. Would you be able to add the patch?

**Comment by joerg-krause** [comment]
Yey, I can do this.
