### ISSUE TITLE
No makefile found 

### ISSUE THREAD

**Issue by ItsFieryGaming** [mikebrady/shairport-sync#944]
Hi I’m new to the RaspberryPi and I wanted to try this out to make my speakers work with my iPhone. 

Upon running the command “make” this error comes up `make: *** No targets specified and no makefile found. Stop.` How do I fix this?

**Comment by mikebrady** [comment]
Thanks for the post. This is a build error – maybe you are not in the correct directory, maybe you haven't run `autoreconf` or the `./configure...` steps.

It's a good idea to follow the instructions in [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md) or [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md) very closely, as it will save a good deal of trouble.
