### ISSUE TITLE
Sync iPhone volume with external amplifier

### ISSUE THREAD

**Issue by MunchHansen** [mikebrady/shairport-sync#946]
Hi there,

So I have a Raspberry Pi running Shairport Sync. I would like to be able to run a IR-command every time it is recognise that the volume is being turned either up or down on the iPhone.

I have the IR command working and ready - but I have no clue - if it would be possible for the Raspberry to recognise when the volume is being changed on the device connected through Shairport Sync?

Any suggestions? Thanks in advance.

**Comment by mikebrady** [comment]
Thanks for the post.

The short answer is "yes" – Shairport Sync recognises when the volume is adjusted on the iPhone and it can execute a program or send a signal in response. 

From Shairport Sync, you can run a command whenever the volume is changed – look at the `run_this_when_the_volume_is_set` hook in the configuration file, normally installed at `/etc/shairport-sync.conf`.

Alternatively, if you build Shairport Sync with D-Bus, MPRIS or MQTT support, you can get notice of a volume change.`

Normally, Shairport Sync also adjusts the output volume, but you can also set it to leave the actual output level unchanged – see the `ignore_volume_control` setting in the configuration file.

**Comment by MunchHansen** [comment]
Hi Mikebrady.

Thanks for the quick reply. I will try this! Btw. thanks for supporting this awesome program!

**Comment by mikebrady** [comment]
The new volume is appended to the string you provide as the `run_this_when_the_volume_is_set` argument. For example, if you provided the string `/usr/bin/vc ` (note the space at the end) and the volume changed to `-20.600` then the full command that would be executed would be `/usr/bin/vc -20.600`

**Comment by MunchHansen** [comment]
Mhm, so you would suggest something pseudo like this:

run_this_when_the_volume_is_set="/home/pi/testscript.sh"

testscript.sh:
```
if 'cat /usr/bin/vc > 0; then
   irsend command_turn_volume_up
else
   irsend command turn_volume_down
fi
```

Kinda? Or what would you suggest? :-)

**Comment by mikebrady** [comment]
This idea has been discussed over on Issue #900, so it's probably a good idea to have a look there. As discussed there, it looks like there is a logical problem trying to control an external device with up/down commands derived from the volume information coming the iPhone.

**Comment by MunchHansen** [comment]
@mikebrady I am not sure - I understand how to use the "run_this_when_the_volume_is_set" setting.

Would I be able to pipe the current volume into a file? Or could you maybe give me an example of how to use this?
