### ISSUE TITLE
Playback Interrupted on Raspbian Buster

### ISSUE THREAD

**Issue by techwiz001** [mikebrady/shairport-sync#947]
Hello, 
I have thoroughly enjoyed using your software on my Raspberry Pi 3 running Raspbian Jessie. 
I recently acquired a Raspberry Pi 4, which runs Raspbian Buster. I did not have issues installing or running the code, everything worked as it was supposed to. However, when listening to music, the playback is interrupted after 1-2 minutes. If I re-select the Pi on my source device, playback is resumed but again cuts off after about 1-2 minutes. Have you ever encountered something like this?

Thanks for your help.

```
:~ $ systemctl status shairport-sync
● shairport-sync.service - ShairportSync AirTunes receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: activating (start) since Sun 2019-12-29 14:20:00 EST; 59s ago
     Docs: man:shairport-sync(7)
           file:///usr/share/doc/shairport-sync/README.md.gz
           https://github.com/mikebrady/shairport-sync
Cntrl PID: 7844 (shairport-sync)
    Tasks: 4 (limit: 4915)
   Memory: 644.0K
   CGroup: /system.slice/shairport-sync.service
           └─7844 /usr/local/bin/shairport-sync

Dec 29 14:20:00 matthews-pi-4 systemd[1]: Starting ShairportSync AirTunes receiver...
```

Update:
The problem is averted by removing the "forking" and relaunch on failure lines from the generated systemd file, but I am not sure if this will have averse effects elsewhere.

**Comment by mikebrady** [comment]
Thanks for the post. There are a number of things you could check.
1. First, presuming that the Pi is connected over WiFi, it’s important to ensure that WiFi power management is off. Have a look [here](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md#wifi-adapter-running-in-power-saving--low-power-mode) for more information.
2. If you have installed Shairport Sync as a package — using `apt install...` etc., then the version installed is a bit old and missing some bug fixes. You can check the version by entering:
```
$ shairport-sync -V
```
The current version is 3.3.5 and is now in Debian backports, so it'll be a matter of time before it becomes available in the Raspbian package system. Alternatively, you could build the latest version from here. Instructions are at [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md). If you do so, be sure to pay close attention to cleaning up before building and installing, as detailed on the page.

**Comment by techwiz001** [comment]
Mike, 
Thanks for your quick and detailed reply. 
Wi-Fi power management was already disabled, and the software was installed using the directions in README.md. I was sure to remove the old copies and systemd files before beginning the installation process. 
The version command yields:
'''
3.3.5-OpenSSL-Avahi-ALSA-stdout-pipe-sysconfdir:/etc
'''

Not sure what is causing the issue, but modifying the systemd file resolved it. So far, I have not noticed any negative consequences...

**Comment by mikebrady** [comment]
Thanks for the update, and I'm glad you got it working properly. Out of interest, can you say what you did to the `systemd` file, please?

**Comment by techwiz001** [comment]
I should have saved a backup copy of the file before I modified it! I deleted the first two lines under the '[Service' heading, which appeared to be making the service re-launch itself every minute or two since `/usr/local/bin/shairport-sync` may not have explicitly returned a successful value. I'm not sure if that is exactly what was going on, but it is my best guess.


My modified `systemd` file:
```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/local/bin/shairport-sync
User=shairport-sync
Group=shairport-sync

[Install]
WantedBy=multi-user.target
```

**Comment by mikebrady** [comment]
Super, thanks.
