### ISSUE TITLE
Troubleshooting on Raspberry Pi

### ISSUE THREAD

**Issue by jarrah31** [mikebrady/shairport-sync#95]
Hi Mike,

I have two Raspberry Pi's configured with Shairport-sync, one on a wired network and the other on wifi. The wired Pi always shows up in the AirPlay play on my iDevices without fail, but the one on wifi most of then than not doesn't.

For example, I can always still connect to the Pi via SSH and ping without any packet loss and a decent response rate, yet the AirPlay server won't appear on my iPhone/iPad/iMac to stream to. Other times it's visible on my iMac, but not on iPhone/iPad, and when this happens, sending a stream from the Mac then causes it to be visible on the iPhone/iPad. Rebooting the Pi fixes things and it becomes visible to stream to again on all devices.

As I'm running the program as a service, what do you recommend I should do to troubleshoot the AirPlay server? Can I somehow query the port that AirPlay advertises itself on? Should I enable any logging? Can I trace AirPlay requests somehow to see if the Pi is receiving the message that a device is looking for AirPlay servers? How can I check if the service is still up and running and hasn't failed?

Many thanks in advance for your help.

P.S. I just want to add that when both are working, it's a joy to be had when I can play fully synchronised music all around my house in conjunction with two Apple TVs that I have. Your program is just fantastic so I'm really hoping we can find a solution to this.

**Comment by joerg-krause** [comment]
There were a lot of network discovery troubles with the `discoveryd` in 8.0 < iOS < 8.4 and 10.10.0 < OS X < 10.10.4. With iOS 8.4 and OS X 10.10.4 Apple replaced `discoveryd` with the old `mDNSResponder` which shall resolve this network issues.

Which versions your iDevices are running?

**Comment by mikebrady** [comment]
Thanks for the kind words. The problem you report seems to be widespread, and not confined to shairport sync. See https://github.com/mikebrady/shairport-sync/issues/15 for example. @joerg-krause is right that recent versions of OS X and possibly iOS have fixed most of the problem.

**Comment by jarrah31** [comment]
Hi - I'm on iOS 8.4 and OS X 10.10.4, so at least I'm on a good footing to start with.

**Comment by jarrah31** [comment]
Just to clarify, my Apple TV and wired shairport-sync on a Pi always show up in the AirPlay list, it's just my wifi connected Pi that seems to struggle, with the weak wifi probably partly to blame. 

When an iPhone probes the network for AirPlay servers, does it 'ping' out on a certain port to receive a response from those that are active? Can I emulate this from another unix machine to check it's working ok? Can Shairport-sync be affected by a weak network signal even though ssh connects ok? 

Thanks.

**Comment by mikebrady** [comment]
Another possibility worth checking is whether the WiFi device is going into a low power mode when it determines that it is idle. See https://github.com/mikebrady/shairport-sync/issues/29.

**Comment by mikebrady** [comment]
It uses Bonjour to advertise itself. You could try Bonjour Browser to see what's out there. Check it he power thing first though IMHO.

**Comment by jarrah31** [comment]
Very good point about the power saving - I'll add "wireless-power off" to my /etc/network/interfaces and see what happens. Thanks!!

**Comment by mikebrady** [comment]
Hmm. `discovered` is still used in iOS 8.4.

**Comment by jarrah31** [comment]
I think adding wireless-power off seems to have worked for me as no more dropouts so far - I'll keep an eye on it over the next week though.

**Comment by mikebrady** [comment]
That's good news, thanks.

**Comment by mikebrady** [comment]
BTW, as a matter of interest, what WiFi adapter are you using?

**Comment by jarrah31** [comment]
Hi Mike, it's the official Raspberry Pi one.

**Comment by mikebrady** [comment]
Thanks.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
