### ISSUE TITLE
Detection of play starting again after pausing user device via DBus remotecontrol

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#954]
Hi,

A question regarding detecting a restarting of "play" during a pause. Monitoring shairport-sync's debug after pausing my iPad via DBus remotecontrol I notice that there's approximately 8 seconds before player.c tears down the ALSA sink. Past discussions with Mike suggested this ~8 second period was more iOS behaviour not releasing the transport than shairport-sync's doing - which I totally understand. 

I have a few music services that share the ALSA sink some of which are DSD and due to a number of good reasons I cannot use pulse or jack so I physically swap the ALSA sink when each music service needs it. For example if music service A wants to play I pause music service B and pinch B's ALSA sink. All is fine except with this 8 second pause period in shairport-sync as during this pause period it assumes it still owns the ALSA sink ( which I've just stolen ) and if the user quickly presses play on their Airplay device then I have no way of detecting music has resumed so the result is video without audio ( BTW the sink back-end is based on a modified alsa loopback so in shairport-sync's case it's more a connection/disconnection with alsaloop ) . 

So due to state changes within player.c being dictated by iOS ( creating this delay before pulling down the sink ), is there another way to detect the music stream has resumed? When the stream stops and starts due to an immediate pause/play can I monitor anything like an empty buffer state, ceasing of frames or something that fills or drains?

In normal use the user won't be switching music services back and forth ( within 8 seconds ) so shairport-sync will setup and tear-down ALSA naturally, they might spend a few hours on Airplay, then a while on Bluetooth then leave it running on MPD as background music for example ( each time the sink's swapped ). I just need to cover the use case that if a user changes their mind very quickly or someone else snipers Airplay after the main user has chosen to change the music service. All music service are on the one platform and share the same ALSA sink. 

UPDATE: during this pause period ( no music playing ) RTP audio packets ( in rtp.c ) are still flooding through up to the point shairport-sync pulls down its sink. So can't use those. 

UPDATE: Reasonable results via detecting the silence period within a pause state, this gets things down to 2 seconds probably being shairport-sync's 2 second buffering. If the music is restarted then silence disappears and based on that I can grab the sink back.. Still open for ideas.. 

Hope this all makes sense..
Cheers.

**Comment by mikebrady** [comment]
Thanks for the post. It does make sense alright, and it's a frustrating aspect of the AirPlay protocol. BTW, if memory serves, the behaviour of iOS and iTunes is different here. 

Detecting complete silence is pretty easy and not particularly costly, so it's not a bad approach, IMHO.

**Comment by juliandc1969** [comment]
Thanks, it seem to behave alright and it's only for the one use case otherwise in normal running the silent code not ran. I'll run with it for now.  

Cheers.
