### ISSUE TITLE
Documentation for dbus ProgressString property

### ISSUE THREAD

**Issue by lrusak** [mikebrady/shairport-sync#956]
Hello!

I'm looking for some documentation about how the `ProgressString` dbus property.
```
.ProgressString                               property  s         "2488012892/2488016721/2500493192"       emits-change
```

I wrote a simple app that uses the shairport-sync dbus api and am trying to understand how the ProgressString dbus property works. I have a added a signal reciever for `PropertiesChanged` via `org.freedesktop.DBus.Properties` on `org.gnome.ShairportSync` but it doesn't seem to emit the `ProgressString` like I thought it would. I thought it would tick as the track played but this doesn't seem to be the case. It seems to emit at the start of the playback and then randomly until the track ends.

My sample app is here: https://github.com/lrusak/shairport-display

I'm not even sure what the values mean. Can you help me out?

**Comment by mikebrady** [comment]
Thanks for the post. These come straight from the player, and I believe they mean the starting time, the current time and the ending time of the current selection. They are denominated in frames, at 44,100 frames per second. The origin (i.e. the zero point) is unknown. 

So, the numbers above state that the selection is 2500493192 - 2488012892 frames long, i.e. 283 seconds or 4:43. It looks like, 2488016721 - 2488012892 frames, i.e. 0.087 seconds or material, have been played.

**Comment by lrusak** [comment]
Thanks for the info, I was able to implement the `ProgressString` into my project. It only emits every once and a while so I have to use a timer and keep track of the player state in order to properly update the progress bar. My code is here for anyone interested.

https://github.com/lrusak/shairport-display/blob/master/shairport-display.py#L247-L262
