### ISSUE TITLE
Metadata via MQTT is awesome!

### ISSUE THREAD

**Issue by tanuva** [mikebrady/shairport-sync#959]
Hello,

I just wanted to give you a 👍 for making the AirPlay-ed metadata accessible to the outside world!

There's a tiny 128x64 display sitting on top of my stereo that used to display info for the media playing in XBMC/Kodi back in the days. Then I switched to Plex and adapted the program but it wasn't the same. (For reasons.) Besides, I play stuff from more sources than just Plex. Then I accidentally discovered that shairport-sync can pour metadata into an MQTT broker. Yay!

After one or two evenings of hacking the [tiny cinema](https://github.com/tanuva/mediadisp) shows not only what is playing via Plex but *everything* coming in via AirPlay. 🤘

**Comment by mikebrady** [comment]
Thanks for the post! Good work!
