### ISSUE TITLE
Can't run shairport-sync in background

### ISSUE THREAD

**Issue by SamusAranX** [mikebrady/shairport-sync#96]
I'm trying to run shairport-sync on a Raspberry Pi 2 Model B with an IQaudIO Pi-DAC+, but it constantly fails to put itself into the background.
This is the command I'm using:
`shairport-sync -a "Test" -- -d hw:0 -t hardware -c "Digital"`
which runs in the foreground. Using
`shairport-sync -d -a "Test" -- -d hw:0 -t hardware -c "Digital"` (note the extra `-d`)
fails with code 2. What's the problem here?

Also, I'm not sure whether this is related or not, but I'm experiencing frequent underruns that coincide with audio cut outs. Before the Pi-DAC+, I was using a cheap USB sound card, and underruns never happened with that. I got the Pi-DAC today, and this is the first time I've had real audio problems.

Edit: I'm using an iPhone 5 on iOS 8.4 and an iMac on OS X 10.10.4 to transmit music to the Raspberry Pi. Not sure if this makes a difference.

**Comment by mikebrady** [comment]
Hi Peter. You need to be in supervisor mode – try putting `sudo` in front of that command. Not sure about the underruns – I have a Pi with a Pi-DAC and it is very solid.

**Comment by SamusAranX** [comment]
Hi! Sorry for the late reply, I just got around to actually booting up the Pi again.
Using `sudo` solved one of my problems, thanks. I feel kinda stupid for not trying that first. :smile:
The other problem I had with buffer underruns seems to have disappeared as well, so that's great.

There's only one little thing left: I always get a bit of crackle or noise between tracks. Is this something I can get rid of with shairport-sync?

**Comment by mikebrady** [comment]
Hi there. It's good to hear that it's mostly working. That tiny crackle is something I get on my Pi-DAC when I change track – if I'm just going from one to the next, there's no crackle. To the best of my knowledge it's a property of the Pi-DAC or the driver. I've tried a few things to remove it but nothing seems to work except keeping it continually busy by sending it silent frames all the time. This is impractical, unfortunately. It might be worth asking the manufacturers about it – they are usually very responsive.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
