### ISSUE TITLE
Build shairport-sync for Android

### ISSUE THREAD

**Issue by heinrichrebehn** [mikebrady/shairport-sync#961]
Hello,
I have been unsuccessfully looking for build instructions for Android.
I want to run it on a Ugoos X2Pro TV Box under Android 9.0.
Does the device have to be rooted?
Can I create an apk for normal install?

Thanks for any help,
Heinrich

**Comment by mikebrady** [comment]
Yikes, I don’t know anything about this, I’m afraid.

**Comment by heinrichrebehn** [comment]
Sorry, my bad. I misinterpreted some occurrences of the string “android” in the release notes as Android support, although it was about Android *clients*.

Anyway, thanks for quick reply :-)

-Heinrich
