### ISSUE TITLE
Allow volume control to change alsa audio level

### ISSUE THREAD

**Issue by BrainStone** [mikebrady/shairport-sync#966]
The alsa audio driver has its own audio level. When I connect to shairport the volume that was set before is used. And the audio slider just varies it between that level.

It would be nice if the volume control would control the alsa volume. And even better if it worked in reverse too. So that if the volume is changed externally that on my AirPlay device the audio slider changes too.

Reading other issues this seems to be possible. But I can figure out how.

**Comment by mikebrady** [comment]
Thanks for the post.

You just need to give the name of the ALSA volume control to Shairport Sync in the setting file to get Shairport Sync to control it — have a look at the README.

There isn’t a facility to go in the other direction, I’m afraid.

**Comment by BrainStone** [comment]
Thank you. It works now.

Regarding the other direction: Does the AirPlay protocol support controling the device volume at all? Because if so that would make for a good feature request I think.

**Comment by mikebrady** [comment]
Good stuff. Until a few weeks ago, I would have said it was generally impossible, but it turns out that there is a remote command for setting the device volume.Even so, it would be exceedingly tricky to do it properly.

**Comment by BrainStone** [comment]
Thank you for letting me know. While I don't think this feature will be happening any time soon I still would apprechiate if you'd change this to a feature request and leave it open.

Additionally it might be beneficial to link resources to that command, so in the future someone might be able to implement it.

**Comment by BrainStone** [comment]
Still would love to have this

**Comment by BrainStone** [comment]
That's fine. I'd still be happy to keep this open.
