### ISSUE TITLE
Change "device/model" in raop

### ISSUE THREAD

**Issue by juliandc1969** [mikebrady/shairport-sync#967]
Hi,

I would like to be able to change the device/model name within the raop information. Most of the time my apps use the name in the conf under "general". I have one app that displays this name but also "ShairportSync" being the device/model. I'd like to change that to suit the actual device/model if possible.
I've traced the possible source of this string using Linux's Avahi-discovery utility to the TXT "am" tag. Using this utility and referencing this document https://nto.github.io/AirPlay.html is appears the "am" device/model tag is the culprit.  Can this be changed?

Thanks.

**Comment by mikebrady** [comment]
Thanks for the post. You would have to recompile Shairport Sync to do this.

It’s rather odd for an app to use this tag as a displayable name — AFAIK it’s really meant to be read by software only.

**Comment by juliandc1969** [comment]
Thanks, agreed it is odd and a pain. Could you point me to what to I need change?

**Comment by mikebrady** [comment]
Sure, look in the file `mdns.h`. It's in two places.

**Comment by juliandc1969** [comment]
Worked! Thank you.
