### ISSUE TITLE
pkg-build / libconfig issue on CentOS (ClearOS) 6

### ISSUE THREAD

**Issue by newtonjd1** [mikebrady/shairport-sync#97]
I've been trying to install shairport-sync on a clearos vm.  I've been able to install all of the necessary dependencies without any issues but when I get to the configure stage of installation it can't find popt.  This seems to be the same issue that people are having on OpenWrt.  I tried using the development branch with the -without-pack-build command line argument which allowed configure to finish properly but I get errors from libconfig when trying to run make install.

**Comment by mikebrady** [comment]
I haven't tried CentOS/clearos. Could you post the output from trying to do the make install please?

**Comment by mikebrady** [comment]
Just trying to find my way to replicating your setup. I installed a ClearOS Server on a VMWare VM. Did you then install a CentOS virtual machine into the server (if so, which one?), or were you working directly on the server itself?

**Comment by newtonjd1** [comment]
Here are the details on the setup:  The server is an old Mac Mini running OS X 10.6.8.  The VM is Clear OS Community 6 (CentOS 6) running in VIrtualbox.  I am doing all of my work via ssh on the ClearOS/CentOS VM. So in your setup, on the server.  If it matters, I am running the i686 version of ClearOS because of the hardware that the VM used to run on.  

Originally my issue was identical to what others were getting in OpenWrt.  After enabling the extra repositories in ClearOS, I got the needed packages installed but when I run ./configure --with-alsa --with-avahi --with-ssl=openssl it wasn't finding libpopt.  I don't have that issue with configure when I use the previously mentioned flag.  

I'm getting the following output/errors when running make install

[root@clearos shairport-sync]# make install
Making install in man
make[1]: Entering directory `/root/shairport-sync/man'
make[2]: Entering directory `/root/shairport-sync/man'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/man/man7" || /bin/mkdir -p "/usr/local/share/man/man7"
 /usr/bin/install -c -m 644 shairport-sync.7 '/usr/local/share/man/man7'
make[2]: Leaving directory `/root/shairport-sync/man'
make[1]: Leaving directory `/root/shairport-sync/man'
make[1]: Entering directory `/root/shairport-sync'
gcc -DHAVE_CONFIG_H -I.    -Wno-multichar  -g -O2 -MT shairport.o -MD -MP -MF .deps/shairport.Tpo -c -o shairport.o shairport.c
shairport.c: In function ‘parse_options’:
shairport.c:318: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:327: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:336: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:368: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:372: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:376: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:395: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:399: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:403: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:407: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:465: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type
/usr/include/libconfig.h:235: note: expected ‘long int *’ but argument is of type ‘int *’
shairport.c:471: error: ‘CONFIG_ERR_FILE_IO’ undeclared (first use in this function)
shairport.c:471: error: (Each undeclared identifier is reported only once
shairport.c:471: error: for each function it appears in.)
make[1]: *** [shairport.o] Error 1
make[1]: Leaving directory `/root/shairport-sync'
make: *** [install-recursive] Error 1

My libconfig info: libconfig-devel-1.3.2-1.1.el6.i686

**Comment by mikebrady** [comment]
Thanks for that.

Okay, I'm guessing that you are on the `development` branch of Shairport Sync (?), and if so there is something missing from your configuration – `libconfig`. This is a new dependency for Shairport Sync 2.3 and greater. You need to install `libconfig-dev`, I think – it's mentioned in the README from the `development` branch. You should continue to use the `--without-pkg-config` flag too.

Let me know if this works; if not I'll start replicating your setup – I think I installed the 64-bit version of the server, but I would go back and try the 32-bit version.

**Comment by newtonjd1** [comment]
Sorry. I listed it after the make install output by I do have libconfig and libconfig-Dev installed based on the read me. 

My libconfig info: libconfig-devel-1.3.2-1.1.el6.i686

P.S.  My apologies if I opened this issue in the wrong place. I am using the development branch.

**Comment by newtonjd1** [comment]
Version of libconfig-dev: libconfig-devel-1.3.2-1.1.el6.i686

**Comment by mikebrady** [comment]
Yikes – sorry, I missed that. The version I am using right now is 1.4.9. I wonder if that's the problem...

**Comment by mikebrady** [comment]
Yep – it looks like the constant CONFIG_ERR_FILE_IO is defined in 1.4.9 but not in 1.3.2.

**Comment by newtonjd1** [comment]
I'm going to see if I can get 1.4.9+ from a CentOS repository to upgrade the one I have from the ClearOS repositories.

**Comment by mikebrady** [comment]
Okay. Another _very_ hacky thing to try is to delete lines 470 – 477, inclusive, of shairport.c. It will get past that problem at least...

**Comment by newtonjd1** [comment]
I tried the very hacky version and got this:


Making install in man
make[1]: Entering directory `/root/shairport-sync/man'
make[2]: Entering directory `/root/shairport-sync/man'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/man/man7" || /bin/mkdir -p "/usr/local/share/man/man7"
 /usr/bin/install -c -m 644 shairport-sync.7 '/usr/local/share/man/man7'
make[2]: Leaving directory `/root/shairport-sync/man'
make[1]: Leaving directory `/root/shairport-sync/man'
make[1]: Entering directory `/root/shairport-sync'
gcc -Wno-multichar  -g -O2   -o shairport-sync shairport.o rtsp.o mdns.o mdns_external.o common.o rtp.o player.o alac.o audio.o audio_dummy.o audio_pipe.o audio_stdout.o mdns_avahi.o  audio_alsa.o         -lasound -lavahi-common -lavahi-client -lconfig -lpopt -lm -lpthread -ldaemon -lrt 
rtsp.o: In function `handle_announce':
/root/shairport-sync/rtsp.c:1180: undefined reference to `base64_dec'
/root/shairport-sync/rtsp.c:1189: undefined reference to `base64_dec'
/root/shairport-sync/rtsp.c:1190: undefined reference to `rsa_apply'
rtsp.o: In function `apple_challenge':
/root/shairport-sync/rtsp.c:1253: undefined reference to `base64_dec'
/root/shairport-sync/rtsp.c:1288: undefined reference to `rsa_apply'
/root/shairport-sync/rtsp.c:1289: undefined reference to `base64_enc'
rtsp.o: In function `make_nonce':
/root/shairport-sync/rtsp.c:1308: undefined reference to `base64_enc'
collect2: ld returned 1 exit status
make[1]: *** [shairport-sync] Error 1
make[1]: Leaving directory `/root/shairport-sync'
make: *** [install-recursive] Error 1

**Comment by mikebrady** [comment]
That's pretty good. Is it possible that you might have left out the `configure` option to select either `openssl` or `polarssl`? So maybe you should have something list:
```
$ ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr
```
Might that be a possibility?

**Comment by mikebrady** [comment]
Meh, I see you included OpenSSL in your earlier post...

**Comment by newtonjd1** [comment]
I did some experimenting and the beta of ClearOS 7, which has an updated CentOS underneath, has libconfig-devel-1.4.9. Still using the -without-pkg-config, everything goes good until it tries to install the init script to run on startup. Since this server is always on functioning as my DHCP server and DNS it's not a big deal. I run it once and it's up until the server will need to go down. (Not sure when that will ever be) This seems to confirm that the original issue is the libconfig version for sure. 

Here is the new make install error:

update-rc.d shairport-sync defaults 90 10
make[3]: update-rc.d: Command not found
make[3]: *** [install-exec-hook] Error 127
make[3]: Leaving directory `/root/shairport-sync'
make[2]: *** [install-exec-am] Error 2
make[2]: Leaving directory `/root/shairport-sync'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/root/shairport-sync'
make: *** [install-recursive] Error 1

**Comment by newtonjd1** [comment]
Looks like CentOS doesn't have an update-rc command. I see the script in /etc/init.d/ but it's not set to run.

**Comment by mikebrady** [comment]
That's good. Does it have `chkconfig` which I think might be similar?

**Comment by newtonjd1** [comment]
It does have chkconfig. I used it to enable avahi and didn't even think to try that to enable shairport-sync.  I'll give that a go.

**Comment by newtonjd1** [comment]
All looks good at this point.  I haven't cycled the server yet to test whether it comes up properly or not because I'm 90% sure my kids are watching netflix and I don't want to spoil their fun.

chkconfig output:
[root@clearos7b init.d]# chkconfig --add shairport-sync
[root@clearos7b init.d]# chkconfig --list

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

firewall       	0:off	1:off	2:on	3:on	4:on	5:on	6:off
firewall6      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
netconsole     	0:off	1:off	2:off	3:off	4:off	5:off	6:off
network        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
shairport-sync 	0:off	1:off	2:on	3:on	4:on	5:on	6:off
storage        	0:off	1:on	2:on	3:on	4:on	5:on	6:off
syswatch       	0:off	1:off	2:on	3:on	4:on	5:on	6:off

**Comment by newtonjd1** [comment]
Not sure if this is the best place to put this so if you think it should be somewhere else feel free to copy it and use it however you want.  Thank you for all of your help!

Here is a step-by-step guide to get Shairport Sync running in Clear OS.  These are the steps I followed (twice) to get Shairport Sync up and running on a Clear OS VM running in Virtual Box.  I believe this will apply to users of Cent OS as well but I don’t know that for sure.  (I will try Cent OS as soon as I can.)

A few caveats to running in ClearOS: you will have the same issues that some users of OpenWRT have encountered with popt. This requires that you install the development branch of Shairport Sync in order to use the -without-pkg-config option for configure, I had to update my server to ClearOS 7.1 Beta 2 to get the version of libconfig (1.4.9) that was required by the development branch of Shairport Sync. 

Note: In ClearOS 7.1 Beta 2, all repositories are enabled by default and no Marketplace App or yum commands are required to  enable extra repositories.

Install required packages:

    yum -y install autoconf libtool-ltdl libdaemon-devel popt-devel
    yum -y install alsa-lib-devel libconfig-devel avahi-devel
    yum -y install openssl-devel - if you want to use OpenSSL (I haven’t tried PolarSSL)
    yum -y install git - if you haven’t installed it for any other reason.  I hadn’t.

Download Shairport Sync:

    git clone -b development https://github.com/mikebrady/shairport-sync.git - development is required at the time of writing this to allow the -without-pkg-config flag during configuration.

cd to the shairport-sync directory that was created:

    cd ./shairport-sync

Run autoreconf:

    autoreconf -i -f

See shairport-sync README.md for `—with` options.  

For basic install with avahi, openssl, and also (These options are working perfectly on ClearOS 7.1 beta 2):

    ./configure -without-pkg-config --with-alsa --with-avahi --with-ssl=openssl

Run make install to install Shairport Sync and install the init script:

    make install

If you have installed all required packages and haven’t skipped any steps, make install should finish with one error:

    update-rc.d shairport-sync defaults 90 10
    make[3]: update-rc.d: Command not found
    make[3]: *** [install-exec-hook] Error 127
    make[3]: Leaving directory /root/shairport-sync' make[2]: *** [install-exec-am] Error 2 make[2]: Leaving directory/root/shairport-sync'
    make[1]: *** [install-am] Error 2
    make[1]: Leaving directory `/root/shairport-sync'
    make: *** [install-recursive] Error 1

CentOS / ClearOS doesn’t use the update-rc command to install startup scripts / services.  To enable Shairport Sync at startup run:

    chkconfig —add shairport-sync

My ClearOS machine didn’t have Avahi enabled by default so I did the following to start and enable avahi-daemon:

    chkconfig avahi-daemon on
    or
    systemctl enable avahi-daemon.service

Before you start the service and are concerned that you hear no audio run alsamixer to unmute and raise the volume of the ‘Master’ and ‘PCM’ channels.

You can now run:

    shairport-sync -d -a “ClearAir” -c PCM - I wasn’t able to control the volume in alsamixer properly until I included the “-c PCM” option.

**Comment by mikebrady** [comment]
Many thanks for this. I think this is as goods place as any to put the guide, for the present. Thanks again.

Are you sure the last command line is complete? It's just got a `-c` option in the backend part. Does it not need a `-t` as well?

**Comment by newtonjd1** [comment]
I haven't been using `-t` as I thought software was the default and I'm just using alsamixer for volume control.  I think using `-t software -c PCM` would be more explicit.  Am I missing or mixing up the usage here?

**Comment by newtonjd1** [comment]
So I tried to follow these exact steps in a new basic install of CentOS and while I didn't experience anything different when it came to the configure, make install, chkconfig steps, I am now getting the issue when trying to run with -d flag.  I tried running it with sudo which doesn't throw an error but I don't see the device on the network.  Still messing around with this.

**Comment by newtonjd1** [comment]
There is something odd going on in CentOS.  The daemon always fails to load on startup.  If I run `shairport-sync -d` as a user I get return 2 which I assuming has to do with needing root access for the daemon mode.  Running with sudo gives me a command not found error.  If I run it as root, I don't get any errors and I can see the device on my iPhone and in iTunes on my Macs but if I select it and play a song, no audio is produced after 6 seconds of silence, exactly, it pauses, disconnects from the device, and no longer shows up as an option under AirPlay.

When I got back to the machine, I don't see any issues and `ps -fe | grep -i shair` shows that process is still running.  I have replicated this about 12 times.

I also tried running `shairport-sync -a CentOS -t 0 -c PCM &` to just through the process in the background like I used to do with shairport but that results in no device showing up the AirPlay menu.

I tried to view the log but apparently the default log location listed in the README.md file doesn't exist on CentOS.

**Comment by mikebrady** [comment]
Hmmm. Maybe it uses `journalctl` like Arch Linux. I'm afraid I'm constrained from experimenting much, as I'm away from my machines until about the middle of August.

**Comment by mikebrady** [comment]
Regarding the use of the `-c` option, yes indeed, you must use the `-t` option for it to have effect. It's as if you are saying: I want to use a hardware mixer for volume control (`-t hardware`) and the name of the mixer on the output device to use for volume control is PCM (`-c PCM`). If you omit the `-t` option, then the `-c` option is ignored.

**Comment by newtonjd1** [comment]
I have been running it with -t and -c. I don't think that's absolutely necessary on my setup but it's consistent. Without those options sometimes it wasn't starting up right.

**Comment by newtonjd1** [comment]
No problem.  I have Shairport Sync running great on all of the machines I actually use at this point.  I wanted to experiment with CentOS to see if the steps I laid out work for that distribution as well.  Here is the error I receive from the startup script: `line 37: /lib/init/vars.sh: No such file or directory`

**Comment by mikebrady** [comment]
That's an odd one – it'll have to wait until the middle of August before I can run it down... Sounds like something is missing from the environment.

**Comment by mikebrady** [comment]
I'm closing this issue. Feel free to reopen.

**Comment by dantheperson** [comment]
Just for the record, deleting that else block was that's required to make trunk compile on ubuntu 12.04 LTS
