### ISSUE TITLE
On Linux Firewalld doesn't allow local UDP ports which leads non-working sound

### ISSUE THREAD

**Issue by illuusio** [mikebrady/shairport-sync#974]
Firewalld doesn't allow Timing UDP port to be opened automatically locally and that causes Shairplay to print:
`rtp.c:449" Sync packet received before we got a timing packet back.`

**Comment by mikebrady** [comment]
Thanks for the post. It’ll take a couple of days to check back.

**Comment by illuusio** [comment]
It seems it's not magic bullet as I rebooted today and now it's not working again. I'll debug more.

**Comment by illuusio** [comment]
I also tested with https://github.com/philippe44/RAOP-Player and the it behaves the same.

**Comment by mikebrady** [comment]
It's probably worth looking at the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page – you may have some firewall issues.

Just FYI, I have successfully used a version of Phillippe44's player.

The PulseAudio AirPlay player may be very old – obsolete in fact, working on the pre-2011 protocol. I suggest you get Shaorport Sync going on a known-good player and then see what's happening.

**Comment by illuusio** [comment]
Thank you for strict and fast answers! I investigated and read TROUBLESHOOTING.md. Main problem is actually my side firewall is too strict to allow UDP Multicasting. Should I change topic and post firewalld rules after I get this working

**Comment by illuusio** [comment]
Ok it took some time to invest and this is not best way to deal with it. Main (as you probably know) is  that Timing port tries to connect local port which is not allowed normally with UDP on local machine. FirewallD rule that makes everything work (8888 is just as number which I took as it seemed that ports locally are selected mostly above that) :
`firewall-cmd --permanent --zone=home --add-rich-rule 'rule family="ipv4" source address="10.0.0.50" port port="8888-65535" protocol="udp" accept'`
but with this makes your security lower (I assume you are in your home WLAN don't do this on nets that you don't trust!!) and you can have only one IP (which Airplay or Shairplay normally haves even with DHCP) and if you use something like '10.0.0.0/24' you can have every machine from 10.0.0.* network allowed  to work your ports. So this more practical than secure solution. More troubleshooting ahead..

**Comment by Ircama** [comment]
Even if *shairport-sync* correctly performs synching, there are special cases where the transmitter (e.g., an Android app) cannot disable the firewall restrictions of its subsystem (e.g., a custom Android emulator) and we get the following:

```
         0.889953362 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.284077668 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.200850390 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.275403515 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.201151570 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.281582590 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.282208086 "rtp.c:419" Sync packet received before we got a timing packet back.
         1.275689933 "rtp.c:419" Sync packet received before we got a timing packet back.
         0.238328402 "player.c:1033" Aliasing of buffer index -- reset.
```

Indeed in such cases old AirPlay audio players like https://github.com/abrasive/shairport and https://github.com/juhovh/shairplay still perfectly work.

I would possibly suggest a future option to overcome the current checks and allow unsynched playout.

I tried to roughly modify the code myself without success.

Notice that at the moment [TROUBLESHOOTING](https://github.com/mikebrady/shairport-sync/blob/153c88a357cb9f7c84cc21c03b84fdae0e436fb9/TROUBLESHOOTING.md) is not really reporting this exact case, but the one where it is the receiver (running shairport-sync) that has firewall restrictions (not the transmitter).

**Comment by Ircama** [comment]
@mikebrady, as a possible future enhancement and if not too complex, I'd recommend adding an option to allow unsynched playout, thanks.

**Comment by mikebrady** [comment]
> @mikebrady, as a possible future enhancement and if not too complex, I'd recommend adding an option to allow unsynched playout, thanks.

@Ircama, thanks for the suggestion, but I'm afraid unsynced playback, in the sense you mean, would be very problematic, so we won't pursue it.

**Comment by illuusio** [comment]
Only solution that is reliable for this with Linux that I have found is to trust UDP packages from Shairport source. So I think this should be closed.

**Comment by illuusio** [comment]
This one is fixed on newer Firewalld NFTables system! Nice to have this working as expected on Linux.
