### ISSUE TITLE
loss audio - Buildroot  - ARMv7l - linux 3.19.0

### ISSUE THREAD

**Issue by giuseppeRoar** [mikebrady/shairport-sync#98]
Hello,

i'm just working on Buildroot - SAMA 5d3ek - ARMv7 with buildroot  system and linux 3.19.0 as kernel.
i'm using shairport 2.2.4 from github.
2.2.4-openssl-tinysvcmdns-ALSA-soxrù

startup command:
nice -n -20  /usr/bin/shairport-sync  -S soxr  -p  20000  -vvvv -a  "giuseppe 5"   -m tinysvcmdns -k  -r0 --statistics

problem tested on mac: 1.9.3 and iphone iOs 8.4, device are connected without problem but,  in a time from 100 to 120 seconds we hear a  fastidious "click" from speaker and next audio will disappear. 
in the console command i've some error like:

Sync error: -21904.2 (frames); net correction: 516.3 (ppm); corrections: 930.6 (ppm); missing packets 2048; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4148, min and max buffer occupancy 512 and 4294965540.

with aplay or mplayer i've not problem or click with audio out.

Thanks for your work, if you need i will provide more details or tests

this is a part log track:
CSeq: 129.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 130.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 130.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 131.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 131.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 132.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 132.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 133.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 133.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 134.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 134.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 135.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 135.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 136.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 136.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 137.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 137.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 138.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 138.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
Sync error: 32146.3 (frames); net correction: -707.6 (ppm); corrections: 975.2 (ppm); missing packets 2048; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5083, min and max buffer occupancy 512 and 4294965764.
    CSeq: 139.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 139.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 140.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 140.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 141.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 141.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 142.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 142.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 143.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 143.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 144.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 144.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 145.
    X-Apple-Device-ID: 0x10ddb19e0ef9.
    DACP-ID: F849ABEDF0A03C45.
    Active-Remote: 2333971193.
    User-Agent: AirPlay/200.34.4.
    CSeq: 145.
    Audio-Jack-Status: connected; type=analog.
    Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
    CSeq: 146.

**Comment by giuseppeRoar** [comment]
Hi, 

 .) -k is really there, one instances of shairport-sync are running
 .) i've added nice for increase the priority of process (same audio result with or without )
 .) mac os 10.9.3 are fine, works fine with Old Shairport ( 0.8  )

i've see the #89  post, i will check the right timing on i2s bus. thanks for your reply.

GM

**Comment by mikebrady** [comment]
Thanks.

**Comment by mikebrady** [comment]
I'm going to close this – feel free to reopen if there are developments.
