### ISSUE TITLE
[Alsa output] How to select a different USB device 

### ISSUE THREAD

**Issue by sedlacekdavid** [mikebrady/shairport-sync#985]
Hi Guys, for you it would be probably a simple question. I'm using an external USB sound card (soundblaster x-fi) and I'm able to 
`aplay -Dsurround51:Pro xxxx -c 6` any file.

But I'm just not able to use such output with shairport. Can someone please help me?

I've tried many combinations but none of them have worked.

shairport -a 'Test' -o alsa -d "surround51:Pro" etc etc

Keep up excellent work, thank you, David

> pi@raspberrypi:/tmp/shairport $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dmix:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Hardware device with all software conversions
default:CARD=Pro
    SB X-Fi Surround 5.1 Pro, USB Audio
    Default Audio Device
sysdefault:CARD=Pro
    SB X-Fi Surround 5.1 Pro, USB Audio
    Default Audio Device
front:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    Front speakers
surround21:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    Direct sample mixing device
dmix:CARD=Pro,DEV=1
    SB X-Fi Surround 5.1 Pro, USB Audio #1
    Direct sample mixing device
dsnoop:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    Direct sample snooping device
dsnoop:CARD=Pro,DEV=1
    SB X-Fi Surround 5.1 Pro, USB Audio #1
    Direct sample snooping device
hw:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    Direct hardware device without any conversions
hw:CARD=Pro,DEV=1
    SB X-Fi Surround 5.1 Pro, USB Audio #1
    Direct hardware device without any conversions
plughw:CARD=Pro,DEV=0
    SB X-Fi Surround 5.1 Pro, USB Audio
    Hardware device with all software conversions
plughw:CARD=Pro,DEV=1
    SB X-Fi Surround 5.1 Pro, USB Audio #1
    Hardware device with all software conversions

**Comment by mikebrady** [comment]
Thanks for the post – I just edited it for layout.

Assuming you're using the latest version of Shairport Sync, you can get a list of the hardware devices it can see at the end of the `help` summary:
```
$ shairport-sync -h
```
You'll see something list this:
```
Usage: ./shairport-sync [options...]
  or:  ./shairport-sync [options...] -- [audio output-specific options]

Options:
    -h, --help              show this help.
    -V, --version           show version information.

[...]

Available mDNS backends: 
    avahi

Available audio backends:
    alsa (default)

Settings and options for the audio backend "alsa":
    -d output-device    set the output device, default is "default".
    -c mixer-control    set the mixer control name, default is to use no mixer.
    -m mixer-device     set the mixer device, default is the output device.
    -i mixer-index      set the mixer index, default is 0.
    hardware output devices:
      "hw:ALSA"
      "hw:sndrpihifiberry"
```
You can see that there are two output devices, `hw:ALSA` and  `hw:sndrpihifiberry`.

The sample command you gave has a couple of issues:
```
shairport -a 'Test' -o alsa -d "surround51:Pro" etc etc
```
There should be a double hyphen, a `--`,  to separate the program's options from the backend's options (and it's `shairport-sync` rather than `shairport`):
```
shairport-sync -a 'Test' -o alsa -- -d "surround51:Pro"
```
Here, the `-d "surround51:Pro"` is an option to the `also` backend, so it comes after the `--` separator.

**Comment by sedlacekdavid** [comment]
Hi @mikebrady ! Thank you very much, it's worked. 

The goal is to "control" 6 different rooms separately. My current setup is one USB soundblaster and 6 amplifiers (3 stereo amps). It works, I can play sounds on 6 different channels.

But I'm affraid that it won't be possible with shairport, since:
```
shairport-sync -a 'Test' -o alsa -- -d "surround51:Pro"
fatal error: Can't set the D/A converter to 44100
```

So did a 10 second searching and found out that it **works** with:
```
shairport-sync -a 'Test' -o alsa -- -d "hw:1,0"
```
And that thread here I found indicated that some audio processing would be neccessary and Pi doesn't have such power. And in my case we are talking about 6 different channels.


But that's something I need to investigate.

**Comment by mikebrady** [comment]
BTW, some people have done stuff like this before — you might find something in the open and closed issues here.
