### ISSUE TITLE
output to alsa plugin crashing

### ISSUE THREAD

**Issue by DeLub** [mikebrady/shairport-sync#990]
Hi,

Thanks for your work on shairport-sync!

When I start shairport-sync with `shairport-sync -- -d hw:CARD=ODACrevB,DEV=0` everything seems to be working fine. However, I want to have sox do some processing, so I have created the following alsa device:
```
pcm.raw {
  type file
  slave {
    pcm null
  }
  format "raw"
  file "| sox -b 16 -c 2 -e signed-integer -r 44100 -t raw -L - \
              -b 24 -c 2 -e signed-integer -t raw -L - \
              gain -4.9 \
              rate -v -p 45 -b 95 88.2k \
              bass 5.0 105 0.71q \
              equalizer 125 0.45q -3.6 \
              equalizer 1310 1.7q -2.1 \
              equalizer 3100 2.2q -3.9 \
              equalizer 3500 4.0q -1.0 \
              equalizer 5000 6.0q -1.8 \
              equalizer 5900 5.0q -5.7 \
              equalizer 6000 0.71q 3.0 \
              equalizer 8100 5.0q -3.2 \
              treble -5.0 13000 0.71q \
        | aplay -D hw:CARD=ODACrevB,DEV=0 -t raw -c 2 -f S24_3LE -r 88200"
}
```

And this works fine with aplay:
```
pi@raspberrypi:~ $ aplay -D raw monty.wav 
Playing WAVE 'monty.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Playing raw data 'stdin' : Signed 24 bit Little Endian in 3bytes, Rate 88200 Hz, Stereo
```

But `shairport-sync -- -d raw` crashes with `fatal error: audio_alsa: Unable to set hw parameters for device "raw": Invalid argument.`

Could you please give a pointer how to solve this?

Regards,
Alex

**Comment by mikebrady** [comment]
Thanks for the interesting post. Could you say what version of Shairport Sync you are using please? And, have you made any settings in the `alsa` section of the configuration file?

**Comment by DeLub** [comment]
I’m on Raspbian, version 3.2.2. I did not make any changes to alsa section in the config file.

I’ll try installing the version from testing/unstable branch.

**Comment by DeLub** [comment]
So... I've updated my pi to the testing version of Raspbian (shairport-syc 3.3.5). Looking at the config file, there are quite a lot of changes: there are a number of parameters (sample rate, format) which now have an "auto" default. Since my pipe expects a certain rate, I chose those in the config file.

This time shairport-sync does not crash. But I get 2 times the same output line:
```
Playing raw data 'stdin' : Signed 24 bit Little Endian in 3bytes, Rate 88200 Hz, Stereo
Playing raw data 'stdin' : Signed 24 bit Little Endian in 3bytes, Rate 88200 Hz, Stereo
```

So somehow my pipe command is executed twice. Playing seems to continue but there is no sound. (And to double check: aplay still works correctly as before.)

**Comment by mikebrady** [comment]
Thanks. I was just about to reply about the changes in the latest version 3.3.6, which has minor changes from 3.3.5, what you have.

It's good to see that Shairport Sync is able to set the hardware parameters successfully.

It might be worth checking that you're now overtaxing the Pi – use `top` or `htop` to see how busy the Pi is getting. Shairport Sync is probably automatically using `soxr` interpolation, so it's probably a good idea to set it to `basic` in the configuration file.

**Comment by DeLub** [comment]
The Pi isn't really very busy. And if I replace the pipe in my alsa device with:
```
file "| aplay -D hw:CARD=ODACrevB,DEV=0 -t raw -c 2 -f S16_LE -r 44100"
```
I also get the same line repeated twice, without sound.

I did found a work around. I set the backend to 'pipe', and have created a script that actually does the same as my alsa device, reading the sound from the pipe configured in the shairport-sync config file:
```
#!/bin/sh

sox -b 16 -c 2 -e signed-integer -r 44100 -t raw -L /dev/shm/shairport-raw \
    -b 24 -c 2 -e signed-integer -t raw -L - \
    gain -4.9 \
    rate -v -p 45 -b 95 88200 \
    bass 5.0 105 0.71q \
    equalizer 125 0.45q -3.6 \
    equalizer 1310 1.7q -2.1 \
    equalizer 3100 2.2q -3.9 \
    equalizer 3500 4.0q -1.0 \
    equalizer 5000 6.0q -1.8 \
    equalizer 5900 5.0q -5.7 \
    equalizer 6000 0.71q 3.0 \
    equalizer 8100 5.0q -3.2 \
    treble -5.0 13000 0.71q \
| aplay -D hw:CARD=ODACrevB,DEV=0 -t raw -c 2 -f S24_3LE -r 88200
```
I have set `run_this_before_play_begins` to point to my script (or should I use `run_this_before_entering_active_state`?). This actually works. Without putting too much load on the Pi.

I'd still prefer alsa, though, as I think this provides better control over timing. Or am I mistaken?

**Comment by mikebrady** [comment]
Yeah, `alsa` should provide better timing control. Can you vary (i.e. lengthen) the length of the input buffer that `aplay` uses?

**Comment by DeLub** [comment]
Tried that. Unfortunately didn't work. But why do I need aplay anyway, I should just let sox output to alsa... 

I changed my pipe in `asound.conf` to:
```
  file "| sox -b 16 -c 2 -e signed-integer -r 44100 -t raw -L - \
              -b 24 -c 2 -e signed-integer -t alsa -L hw:CARD=ODACrevB,DEV=0 \
  ...
```

Playing from the command line (using aplay to feed my alsa device):
```
pi@raspberrypi:~ $ aplay -D raw monty.wav 
Playing WAVE 'monty.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

-: (raw)

 File Size: 0         
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: unknown      

In:0.00% 00:02:03.53 [00:00:00.00] Out:5.45M [   -==|===-  ] Hd:5.1 Clip:0 
```
It works.

With shairplay-sync something similar happened as before. I started shairplay-sync with `shairplay-sync -v` (not as a daemon). Output looks like:
```
 from 192.168.1.2 to 192.168.1.37 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.

-: (raw)

 File Size: 0         
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: unknown      

In:0.00% 00:00:00.10 [00:00:00.00] Out:4.41k [      |      ]        Clip:0    
Done.

-: (raw)

 File Size: 0         
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: unknown      

In:0.00% 00:00:09.10 [00:00:00.00] Out:401k  [      |      ]        Clip:0      
```
So again two invocations?? And no sound unfortunately.

I also tried quadrupling the buffer size for sox with --buffer 32768. Didn't have any effect unfortunately.

**Comment by mikebrady** [comment]
You should include a `u` with that `v` to get messages from Shairport Sync onto the console. Also, it might be worth turning on `--statistics` to see how or whether audio is passing through Shairport Sync.

**Comment by DeLub** [comment]
```
         4.027727433 "rtsp.c:996" Connection 2: SETUP DACP-ID "B45F76C01885C5D4" from 192.168.1.2 to 192.168.1.37 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
         0.023686996 "player.c:1883" sync error in milliseconds, net correction in ppm, corrections in ppm, total packets, missing packets, late packets, too late packets, resend requests, min DAC queue size, min buffer occupancy, max buffer occupancy, source nominal frames per second, source actual frames per second, output frames per second, source clock drift in ppm, source clock drift sample count, rough calculated correction in ppm

-: (raw)

 File Size: 0         
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: unknown      

In:0.00% 00:00:00.10 [00:00:00.00] Out:8.82k [      |      ]        Clip:0    
Done.

-: (raw)

 File Size: 0         
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: unknown      

In:0.00% 00:00:10.03 [00:00:00.00] Out:874k  [      |      ]        Clip:0    ^C
Aborted.
```

I see the header of the statistics, but no rows. Does this mean nothing passes trough shairport-sync?
If so, any clues?

**Comment by mikebrady** [comment]
Thanks for the information. Yes, that would be my conclusion.

The `alsa` plugin is providing no feedback to Shairport Sync. In particular, the minimum DAC queue size – which Shairport Sync uses to monitor the state of synchronisation – can go down to zero. Shairport Sync expects to be outputting to a real hardware device with a queue of frames to be played. It monitors that. The plugin doesn't seem to provide one.

You could try turning synchronisation off in the configuration file. Unfortunately, even if that helps, it means that sooner or later you'll get overrun or underrun.

**Comment by DeLub** [comment]
Too bad, doesn’t work either.

So, I should put in a feature request :)

Could you please allow a sort of hook in which users can perform custom (sox) transformations on sound flowing through shairport-sync?

**Comment by mikebrady** [comment]
Thanks for the suggestion. I know it would be a major piece of work, so it won't be a high priority thing. But I'll have a look.

**Comment by DeLub** [comment]
Thanks. And thanks for you help and work on shairport-sync!

**Comment by DeLub** [comment]
Sorry for coming back on this topic again. I had a brain wave...

I solved this using an alsa loopback device. I made sure that at boot the kernel module `snd-aloop` is loaded. Then I created a script to run at boot:
```
#!/bin/sh

sox \
    -b 16 -c 2 -e signed-integer -r 44100 -t alsa -L hw:CARD=Loopback,DEV=1 \
    -b 24 -c 2 -e signed-integer -t alsa -L hw:CARD=ODACrevB,DEV=0 \

...
```
and I set the output device for shairport-sync to `hw:CARD=Loopback,DEV=0`.

So: shairport-sync is playing to the loopback device, sox is reading from the loopback device, doing it's thing, and outputing to the USB DAC.

Seems to work like a charm!

**Comment by DeLub** [comment]
Thanks again for shairport-sync!

**Comment by mikebrady** [comment]
Thank you for you interest in Shairport Sync!
