### ISSUE TITLE
how do I set pipe output parameter

### ISSUE THREAD

**Issue by powerpun** [mikebrady/shairport-sync#993]
like what alsa did using soxr ?

```
pipe =
{
    name = "/path/to/pipe";
    rate=48000;
    format="s24";
};
```

**Comment by mikebrady** [comment]
Thanks for the post. I’m not quite sure what you’re asking, but looking at the settings you have given, let me say that the pipe doesn’t take `rate` or `format` parameters — it delivers exactly what comes in, which is always 44,100 frames per second 16-bit little-endian interleaved stereo (i.e. CD format audio).

**Comment by powerpun** [comment]
> Thanks for the post. I’m not quite sure what you’re asking, but looking at the settings you have given, let me say that the pipe doesn’t take `rate` or `format` parameters — it delivers exactly what comes in, which is always 44,100 frames per second 16-bit little-endian interleaved stereo (i.e. CD format audio).

what't I am asking is does airplay support multi sample rates or only supports 16bit/44.1kHz ?

**Comment by mikebrady** [comment]
Thanks. (I edited your response for clarity.)

Yes, even though it could in theory use different rates, Airplay always uses 16 bit / 44.1 stereo, so the output from the pipe is always that.
