### ISSUE TITLE
Remembering last volume or choosing a default volume different than 33%

### ISSUE THREAD

**Issue by janek** [mikebrady/shairport-sync#996]
Thanks so much for the awesome work and for your time!

One problem that I have is that the volume is always set at 33% when I connect. I would love to ideally have the device "remember" the last volume that I set it at or let me choose a different (higher) default volume. 

I read an [article](https://www.howtogeek.com/217007/how-to-adjust-volume-settings-for-individual-audio-devices-and-sound-effects-in-os-x/) suggesting the general AirPlay behaviour should be to remember the volume. I also saw a comment in #245 suggesting that should also be the behaviour in shairport. But I already set it up more than once and every time I have had my volume set itself at 33% when I connect to the device. I was using new versions of Raspbian every time.

**Comment by mikebrady** [comment]
Thanks for the post and for the kind words.

My experience is that the device I'm playing from – iPhone, iPad, Mac – remembers the setting it used last and then applies it to the next play. Could you say what apps or players you are using please? Also, if you could let us know the version of Shairport Sync you are using, that would be helpful.

**Comment by janek** [comment]
Thank you! Sure!

my iPhone is broken, so I can't check that now, but will update later if still relevant

On macOS, I'm using on `10.15.3` (Catalina). I tested Spotify, Safari and Chrome. You gave me the idea to check an app that handles AirPlay in it's own way, and that worked - I used Vox and shairport-sync remembered my volume when the output Airplay device was set from Vox. When I set Vox to use the "system output", it was the same as other apps.

Catalina is well known for having introduced some breaking changes, in particular related to making the system more secure (e.g. some new security prompts), but I guess some bugs, too. Could it be that this is the root of the issue?

my `shairport-sync` is `3.3.5`

**Comment by janek** [comment]
It works with an iPhone on iOS `13.3.1`

**Comment by mikebrady** [comment]
Thanks. I’ll check with the latest Catalina and report back.

**Comment by janek** [comment]
Were you able to take a look?
There is no rush at all, just wanted to ping in case this got lost.

**Comment by mikebrady** [comment]
Thanks for the reminder. What I notice is that, if you look in the Output part of the Sound panel in System Preferences, you will observe that the Mac seems to reset the output volume to some standard value when you switch from the AirPlay device to  the Internal Speakers and back.

So, in summary, from iOS, it looks as if when the iOS device reconnects to an AirPlay device, it restores the last volume level it used. Similarly with iTunes and the macOS Music app. However, the macOS System Sound output system does not restore the last volume level used on that output device. It looks like a bug in macOS.

**Comment by janek** [comment]
Yes, that's what my experience was, too. I'm not sure if it can be considered a bug in macOS - as far as I know, commercial speakers that support AirPlay don't exhibit this behavior. 

I can use a program called AirFoil to go around it if I need to. Feel free to close the issue if you want! Thank you for taking the time!

**Comment by mikebrady** [comment]
Thanks. That’s interesting about commercial speakers. If you come across an example, I’d be glad to hear of it.

**Comment by janek** [comment]
I asked my friend about the model and he checked again more thoroughly. The "remembering volume" behaviour is actually not different for commercial speakers (or at least not the one he tested). He's used to managing sound from Music.app, so that's what he initially checked. I think that's it for this issue then, thanks very much for your time!
